### PR TITLE
Added example about dropping columns on which views are not dependent

### LINKED ISSUE #7849: sql: track fine-grained view dependencies
PR: https://github.com/cockroachdb/cockroach/pull/49872

From release notes:
> Views now only create a dependency on a table's column if the column is referenced in the view definition. Previously, all columns in a table referenced in a view were added to the view's dependencies. [#49872][#49872] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7849.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8608#-:-MJSsww9ClaZzOLH4kYD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ericharmeling** [comment]
TFTR @rytaft !

**Review by lnhsingh — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8608#-:-MJTnNrDBTtitwAzCcRW:b-85i648)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by ericharmeling** [comment]
TFTR @lnhsingh !

**Pull request merged**
