### PR TITLE
add v21.2.0-alpha.1 release notes

### PR DESCRIPTION
**Pull request by taroface**

### CODE REVIEW

**Review by jseldess — APPROVED** [review]
This :lgtm: but I didn't closely proofread all lines, and the preview is no longer available. @taroface, can you get another test build and let me know.

Also, @mikecrl, how does this first alpha intersect with the automated creation of docs issues? This is a massive release, and I assume we need to use our old script to generate docs issues for many of the changes in here, but I'm not sure.

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11220#-:-Miy45Rm9TQ1f2YVpAoV:b-ymskf9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[releases/v21.2.0-alpha.1.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/11220#-Miy3PeD82JTooAdlTVm:-Miy3PeD82JTooAdlTVn:b-a3d8b7) ([raw file](https://github.com/cockroachdb/docs/blob/2979c8a68ed61f83d79aa50be71a8f6c8d25824f/releases/v21.2.0-alpha.1.md#L7)):*
> ```Markdown
> ---
> 
> ## September 01, 2021
> ```

We need to update this date.

**Comment by taroface** [comment]
TFTR @jseldess! Here is the preview: https://deploy-preview-11220--cockroachdb-docs.netlify.app/docs/releases/v21.2.0-alpha.1

**Comment by jseldess** [comment]
LGTM

**Comment by taroface** [comment]
Closing as the release was cancelled.

**Pull request closed without merging**
