### PR TITLE
CC Release Notes December

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/DOC-2043

### CODE REVIEW

**Review by jramos-crl — APPROVED** [review]
Looks good to me!

**Review by kannanlakshmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @kevin-v-ngo, and @thtruo)

**Review by emily-horing — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @kevin-v-ngo, and @thtruo)

___
*[releases/cockroachcloud-12062021.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/12467#-MpqbtQv4pu9F7XxAad4:-MpqbtQv4pu9F7XxAad5:b-paltdn) ([raw file](https://github.com/cockroachdb/docs/blob/b80620e111f5565b1c1af61d72ba69a97860171b/releases/cockroachcloud-12062021.md#L17)):*
> ```Markdown
> - New {{ site.data.products.db }} clusters will now run [v21.2.1](v21.2.1.html).
> - New {{ site.data.products.db }} clusters will now have [Admission Control](../{{site.versions["stable"]}}/architecture/admission-control.html) enabled by default.
> - {{ site.data.products.dedicated }} clusters will now run on new [machine types and disks](../cockroachcloud/create-your-cluster.html#step-2-select-the-cloud-provider). Clusters created before December 1, 2021 will be transitioned to the new hardware configurations by the end of the month, and pricing may change slightly.
> ```

Not blocking but if we are sure about how the pricing will change (I believe it was lower pricing) it would be nice to state it here so existing customers don't get concerned.

**Review by thtruo — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @kevin-v-ngo)

**Comment by gemma-shay** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12467)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @kevin-v-ngo, and @thtruo)
> 
> _[releases/cockroachcloud-12062021.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/12467#-MpqbtQv4pu9F7XxAad4:-MpqbtQv4pu9F7XxAad5:b-paltdn) ([raw file](https://github.com/cockroachdb/docs/blob/b80620e111f5565b1c1af61d72ba69a97860171b/releases/cockroachcloud-12062021.md#L17)):_
> 
> > ```gfm
> > - New {{ site.data.products.db }} clusters will now run [v21.2.1](v21.2.1.html).
> > - New {{ site.data.products.db }} clusters will now have [Admission Control](../{{site.versions["stable"]}}/architecture/admission-control.html) enabled by default.
> > - {{ site.data.products.dedicated }} clusters will now run on new [machine types and disks](../cockroachcloud/create-your-cluster.html#step-2-select-the-cloud-provider). Clusters created before December 1, 2021 will be transitioned to the new hardware configurations by the end of the month, and pricing may change slightly.
> > ```
> 
> Not blocking but if we are sure about how the pricing will change (I believe it was lower pricing) it would be nice to state it here so existing customers don't get concerned.

It was originally going to be a lot lower, but it ended up being almost exactly the same.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
