### PR TITLE
Add upstream tracking info to Contributing doc

### PR DESCRIPTION
**Pull request by sploiselle**
Recommendation is to add upstream tracking commands to CONTRIBUTING.md. Which specifies name of master branch, how to add upstream tracking (my macro didn't work because it relies on the name being `master`), as well as fetch/merge because I was already there.

(Sorry for the extra commits from the closed fork yesterday. Tried squashing them but to no avail.)

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/339)

### CODE REVIEW

**Comment by jseldess** [comment]
This is a great addition, Sean. Thanks! I have a few minor suggestions (see below). And I'd like you to try squashing the unrelated commits as follows:

1. Get on your local branch.
2. Run `git rebase -i gh-pages`. This will open the commit list in VIM. 
3. Press `i` to enter edit mode.
4. At the top, delete all "pick" lines EXCEPT the one for `adding Keep Contributing section`. 
5. Press `esc`, then `:`, then `wq`, then `enter`. At this point, you will have squashed the commits down to only the one relevant.
6. Run `git push --force origin <you branch name>`. This should force your local branch to overwrite the remote branch. 

If that doesn't work, I'll create another branch and learn how to cherry pick the right commit from your branch.

<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary>
> #### Add upstream tracking info to Contributing doc
> 
> Recommendation is to add upstream tracking commands to CONTRIBUTING.md. Which specifies name of master branch, how to add upstream tracking (my macro didn't work because it relies on the name being `master`), as well as fetch/merge because I was already there.
> 
> 
> 
> (Sorry for the extra commits from the closed fork yesterday. Tried squashing them but to no avail.)
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/339#-KJBPzrOgiig7hJEQcoN:-KJBPzrOgiig7hJEQcoO:1245801226) ([raw file](https://github.com/cockroachdb/docs/blob/a0ee6567031ee1837009b07c1d871d21cf1de869/CONTRIBUTING.md#L47)):*
> ```Markdown
>     ```
> 
>     ``` shell
> ```

This an arbitrary style thing, but let's keep `git fetch upstream` and `git merge upstream/gh-pages` in the same code block.

---

*[CONTRIBUTING.md, line 51 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/339#-KJBQ93txO_VkBfuNVba:-KJBQ93usB1_TmUTGIa9:-1060182601) ([raw file](https://github.com/cockroachdb/docs/blob/a0ee6567031ee1837009b07c1d871d21cf1de869/CONTRIBUTING.md#L51)):*
> ```Markdown
>     ```
> 
> 4. Repeat the write, build, push, pull flow from the __Get Started__ section above.
> ```

Let's make Get Started a link. All headers are link anchors by default, so you can use this syntax: 

[Get Started](#get-started)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/339#-:-KJBQPrgJRA5DZHst_SI:815140380)*

**Comment by jseldess** [comment]
*[CONTRIBUTING.md, line 51 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/339#-KJBQ93txO_VkBfuNVba:-KJBS-KBTFEdKf0zLSwi:1158878953) ([raw file](https://github.com/cockroachdb/docs/blob/a0ee6567031ee1837009b07c1d871d21cf1de869/CONTRIBUTING.md#L51)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Let's make Get Started a link. All headers are link anchors by default, so you can use this syntax: 
> 
> [Get Started](#get-started)
</details>
Formatting for that link is `[Get Started](#get-started)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/339)*

**Comment by jseldess** [comment]
Hey @sploiselle, I see that you've made the adjustments to `CONTRIBUTING.md`, but it looks like there are still some unrelated commits in here. Is it ok for me to open a new PR with your `CONTRIBUTING.md` changes, close this one, and then have you review to validate that I caught everything you wanted?

**Comment by sploiselle** [comment]
@jseldess That would be great. I've caught myself in a rat's nest of commits which I've been trying to untangle all morning.

**Pull request closed without merging**
