### PR TITLE
Updates to GORM hello world sample and tutorial

### LINKED ISSUE #7184: Use our GORM library for transaction retries
Re: [Build a Go App with CockroachDB and GORM](https://cockroachlabs.com/docs//v19.2/build-a-go-app-with-cockroachdb-gorm.html)

I've added native support for GORM to the cockroach-go/crdb/gorm library. We should use it in these samples for handling transaction retries.

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7184.
Related to #8227. 

- Organized the GORM samples a bit (added folder `gorm-sample` and changed file name to `main.go`).
- Updated the sample code to use the `crdbgorm.ExecuteTx()` helper function instead of custom retry logic.
- Simplified steps by using `go mod init` for dependencies.

See https://github.com/cockroachlabs/hello-world-go-gorm/pull/1.

Note that this first commit only affects v20.2 docs. I'll propagate changes to v20.1 and v19.2 and squash when everything is approved.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@andreimatei Friendly review reminder :)

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8261#-:-MHMOn0BCYVF3u16XX7e:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by ericharmeling** [comment]
@andreimatei TFTR!

**Review by lnhsingh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8261#-:-MHMkEqZBTf3Z2odF-3V:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh)

**Pull request merged**
