### PR TITLE
Managed CockroachDB Docs

### LINKED ISSUE #3979: Creating and Viewing Clusters [Managed Console]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/rec27ToEi06PVi6aL
PM: @kannanlakshmi 
Eng partner: @vilterp

### PR DESCRIPTION
**Pull request by lhirata**
Docs for 3/18 - Console in limited availability.

Changes / additions include:

- How to sign up
- How to connect to your cluster
- How to use the Console
- Some FAQs
- SQL user management
- Cluster management

Still need to do:

- [ ] Add screenshots

Closes #3979, #4200.

### CODE REVIEW

**Comment by lhirata** [comment]
@jseldess @kannanlakshmi @Amruta-Ranade - Apologies for the last minute reviews, but if you can review by EOD tomorrow, that would be great. I'm trying to get this reviewed and merged by Monday.

**Comment by lhirata** [comment]
@kannanlakshmi @vilterp - updated docs based on the UI changes + added screenshots. Still waiting to take screenshots of the Clusters page (all clusters) and Cluster Overview page. These screenshots are non-blocking, so this PR could be merged and those screenshots can be added once the screens are updated.

You can view the most up to date changes here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9933efd98f9014ad4796b3cc5a310f1eaa790931/managed/dev/managed-sign-up-for-a-cluster.html

**Comment by kannanlakshmi** [comment]
Hey @lhirata 
Apologies for missing this on Friday. 

In the `Sign up for managed cluster` page, can you remove the first sentence "The Managed CockroachDB offering is currently in Limited Availability and accepting customers on a qualified basis." 
Let's also remove "To be considered for participation:" since there is no waitlist of any sort now. 
Cockroach Labs will consider your use case and follow up with you within 1 business day --> to just "Cockroach Labs will follow up with you within 1 business day" 

Since this page didn't change, I missed it earlier. 

The rest of it all looks great, thanks again for getting all of this done before 3/18!

**Comment by lhirata** [comment]
@jseldess can I get a LGTM from you, if it looks good? Two more screenshots can be added after this PR is merged. I don't want them to hold up the other content

**Comment by lhirata** [comment]
Thanks @jseldess. I only see one v2.1 managed-sign-up-for-a-cluster. Was there something else you wanted to point out? Your comment wasn't complete

**Comment by lhirata** [comment]
Merging now, will open a new PR for screenshots and any other fine-tuning

**Pull request merged**
