### PR TITLE
Add docs for auto-rehoming of RBR tables

### LINKED ISSUE #11212: sql: add docs for auto re-homing on update
Add docs for auto re-homing on update. Note, some specifics and concerns are raised in this [thread](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1629996186001400).

### LINKED ISSUE #11214: sql: introduce variable to disable auto-rehoming
https://github.com/cockroachdb/cockroach/pull/69626 --- See release note. Unfortunately due to the ON UPDATE clause not being able to take the same column as input, we have to rely on checking this condition at the optimizer layer.  Release justification: gating new functionality  Release note (sql change): Users can now opt to disable auto-rehoming for a session by setting `on_update_rehome_row_enabled = false`. This can be permanently unset by default using the cluster setting `sql.defaults.on_update_rehome_row.enabled`.

### LINKED ISSUE #11454: sql: enable auto-rehoming of REGIONAL BY ROW tables
PR: https://github.com/cockroachdb/cockroach/pull/69381

From release notes:
> The [cluster setting](../v21.2/cluster-settings.html) `sql.defaults.experimental_auto_rehoming.enabled` and session setting `experimental_enable_auto_rehoming` were added to enable auto-rehoming on [`UPDATE`](../v21.2/update.html) for `REGIONAL BY ROW` tables. [#69381][#69381]

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #11214
Fixes #11454
Fixes #11212

Depends on a link that will exist once we merge #12035

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rmloveland)

___
*[v21.2/set-locality.md, line 165 at r1](https://reviewable.io/reviews/cockroachdb/docs/12081#-MmzCNY-2B4qSs4yL8za:-MnCd8qi1bI-HeLwTT_q:bp9r6jr) ([raw file](https://github.com/cockroachdb/docs/blob/89c924ffa82a7b6c68d492b0ebad1201a886e447/v21.2/set-locality.md#L165)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

AHA - ok, I have revised this section to take that into account.  Hopefully it makes it clear enough what is going on -  PTAL!
</blockquote></details>

Let's capture this in prose as well. Left a suggestion above. The demo looks good! 
___
*[v21.2/set-locality.md, line 143 at r3](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnCcjJC1LcPp2JGqwr6:-MnCcjJC1LcPp2JGqwr7:bb5la7b) ([raw file](https://github.com/cockroachdb/docs/blob/09808d0dc3c5ff5de297795ef1c38b0b5b3f3ec2/v21.2/set-locality.md#L143)):*
> ```Markdown
> When auto-rehoming is enabled, the [home region](#crdb_region) of rows in [`REGIONAL BY ROW`](#set-the-table-locality-to-regional-by-row) tables are automatically set to the region of the [gateway node](ui-sessions-page.html#session-details-gateway-node) from which any [`UPDATE`](update.html) or [`UPSERT`](upsert.html) statements that operate on those rows originate. This functionality is provided by adding [an `ON UPDATE` expression](add-column.html#on-update-expressions) to the [home region column](#crdb_region).
> 
> This feature is off by default.
> ```

Let's add some words here which call out that this setting only applies to newly created (or altered to) RBR tables. It has no effect on existing tables.

**Review by rmloveland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[v21.2/set-locality.md, line 165 at r1](https://reviewable.io/reviews/cockroachdb/docs/12081#-MmzCNY-2B4qSs4yL8za:-MnR7vdO57TReQLSJ9Lj:b-ucfknh) ([raw file](https://github.com/cockroachdb/docs/blob/89c924ffa82a7b6c68d492b0ebad1201a886e447/v21.2/set-locality.md#L165)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's capture this in prose as well. Left a suggestion above. The demo looks good! 
</blockquote></details>

Thanks!
___
*[v21.2/set-locality.md, line 143 at r3](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnCcjJC1LcPp2JGqwr6:-MnRBSvVAx-afzGKXxEq:b-u8d33g) ([raw file](https://github.com/cockroachdb/docs/blob/09808d0dc3c5ff5de297795ef1c38b0b5b3f3ec2/v21.2/set-locality.md#L143)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add some words here which call out that this setting only applies to newly created (or altered to) RBR tables. It has no effect on existing tables. 
</blockquote></details>

Good call, added some more stuff here.  Ended up reorganizing the section to make the flow something like:

1. it's off by default
2. when enabled, it does x
3. note this is only for new RBR, not existing

PTAL!

**Comment by rmloveland** [comment]
Hey Arul are you OK with this after the latest changes?  Sorry to ping, trying to wrap this and a couple other things up by the v21.2 official release date

**Review by arulajmani — APPROVED** [review]
Yup, this looks good! Sorry for the delay, I missed the previous notification. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12081#-:-MncEhA_AjNIJTT9yT4V:bqrabu8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rmloveland)

___
*[v21.2/set-locality.md, line 143 at r3](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnCcjJC1LcPp2JGqwr6:-MncEpNd2xKpL7CiT8Mg:bmi8ppe) ([raw file](https://github.com/cockroachdb/docs/blob/09808d0dc3c5ff5de297795ef1c38b0b5b3f3ec2/v21.2/set-locality.md#L143)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Good call, added some more stuff here.  Ended up reorganizing the section to make the flow something like:

1. it's off by default
2. when enabled, it does x
3. note this is only for new RBR, not existing

PTAL!
</blockquote></details>

:100:

**Comment by rmloveland** [comment]
Thanks Arul!

**Review by taroface — CHANGES_REQUESTED** [review]
A few nits and IMO a minor blocker/question about the numbering of the terminal windows in the example!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12081#-:-MnfkYCY7Xh4kDfHBas0:b-42jntg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rmloveland, and @taroface)

___
*[v21.2/set-locality.md, line 141 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfgrg8-exvnvEeNi3V:-Mnfgrg8-exvnvEeNi3W:bqfuwh) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L141)):*
> ```Markdown
> {% include {{ page.version.version }}/misc/experimental-warning.md %}
> 
> This feature is off by default.
> ```

Maybe "disabled by default"? Looks like we use that phrase more.
___
*[v21.2/set-locality.md, line 143 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfh3ex1V7r2fT9Fmi-:-Mnfh3ey3TphM7hk3Ryk:b-b9ba5k) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L143)):*
> ```
> the [home region](#crdb_region) of rows in [`REGIONAL BY ROW`](#set-the-table-locality-to-regional-by-row) tables are automatically set
> ```

Should this be "the home region of rows [...] is automatically set"?
___
*[v21.2/set-locality.md, line 171 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnfhwuL76aR02qA0y5f:-MnfhwuL76aR02qA0y5g:bqs84x0) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L171)):*
> ```
> Terminal window
> ```

I think this one should be lowercase, unless you are referring to the macOS application name
___
*[v21.2/set-locality.md, line 180 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfi9bt0l8558t8ciKp:-Mnfi9bt0l8558t8ciKq:b-29id4c) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L180)):*
> ```
> In different Terminal window
> ```

"In a different terminal window"

Also, this seems to be the second terminal window opened in these steps, but it isn't numbered (Terminal 2 below is a third window). Maybe renumber the terminal window names, or reuse this one as Terminal 2 below?
___
*[v21.2/set-locality.md, line 180 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnfiSiJBPFNbNUSwLWS:-MnfiSiKB7NPL0DVrhVn:bgrmneh) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L180)):*
> ```
> Step 3
> ```

Nit: lowercase for consistency
___
*[v21.2/set-locality.md, line 196 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfizz7AkZ7wEqLFGRK:-Mnfizz7AkZ7wEqLFGRL:b-q2uyja) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L196)):*
> ```
> call it Terminal 2
> ```

See above comment about the window numbering.
___
*[v21.2/set-locality.md, line 204 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfj3HjEDHPCdLr5swj:-Mnfj3HjEDHPCdLr5swk:b40u7y2) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L204)):*
> ```Markdown
> 
>     ~~~
>     #
> ```

Nit: Maybe ok to cut this line?
___
*[v21.2/set-locality.md, line 265 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnfkRA43_7d5fT5yn4F:-MnfkRA43_7d5fT5yn4G:b-51h77j) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L265)):*
> ```
> automatically rehomed
> ```

Worth reiterating the "auto-rehomed" terminology here?

**Review by rmloveland — COMMENTED** [review]
Thanks Ryan!  Updated and hopefully addressed all your feedback

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12081#-:-MnRCHiF9XhGWQlc5xvB:b-cjiok5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @taroface)

___
*[v21.2/set-locality.md, line 143 at r3](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnCcjJC1LcPp2JGqwr6:-Mo0D3FA1o2wA015lFge:bb6muj3) ([raw file](https://github.com/cockroachdb/docs/blob/09808d0dc3c5ff5de297795ef1c38b0b5b3f3ec2/v21.2/set-locality.md#L143)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

:100: 
</blockquote></details>

:-) 
___
*[v21.2/set-locality.md, line 141 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfgrg8-exvnvEeNi3V:-Mo0CeUTBzqt9DlvAtgg:b-bw8e1h) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L141)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Maybe "disabled by default"? Looks like we use that phrase more.
</blockquote></details>

Updated!
___
*[v21.2/set-locality.md, line 143 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfh3ex1V7r2fT9Fmi-:-Mo0CllH2Sm5xv1X0kWB:bi3dovi) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L143)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> the [home region](#crdb_region) of rows in [`REGIONAL BY ROW`](#set-the-table-locality-to-regional-by-row) tables are automatically set
> ```

Should this be "the home region of rows [...] is automatically set"?
</blockquote></details>

I think this can also be fixed by making "home regions" plural as in "the home regions ... are automatically set" so I went with that.  Do you think that also could work?
___
*[v21.2/set-locality.md, line 171 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnfhwuL76aR02qA0y5f:-Mo0DGwh3CblFuCfFop5:blouyh) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L171)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Terminal window
> ```

I think this one should be lowercase, unless you are referring to the macOS application name
</blockquote></details>

Agreed!  Changed everything in this section to lowercase "terminal"
___
*[v21.2/set-locality.md, line 180 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfi9bt0l8558t8ciKp:-Mo0Dgdi5wR4vOIp_lev:bkazt0x) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L180)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> In different Terminal window
> ```

"In a different terminal window"

Also, this seems to be the second terminal window opened in these steps, but it isn't numbered (Terminal 2 below is a third window). Maybe renumber the terminal window names, or reuse this one as Terminal 2 below?
</blockquote></details>

Good point.  I have renumbered this one as terminal 2, and the one that follows where we do other things is now terminal 3
___
*[v21.2/set-locality.md, line 180 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnfiSiJBPFNbNUSwLWS:-Mo0DnOw5snuOrrDw4e_:b-qsseby) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L180)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Step 3
> ```

Nit: lowercase for consistency
</blockquote></details>

fixed!
___
*[v21.2/set-locality.md, line 196 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfizz7AkZ7wEqLFGRK:-Mo0Dp6o2aradMYxgFsV:bv2yis7) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L196)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> call it Terminal 2
> ```

See above comment about the window numbering.
</blockquote></details>

updated to terminal 3!
___
*[v21.2/set-locality.md, line 204 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfj3HjEDHPCdLr5swj:-Mo0Dryd2IGGuy18D2fn:b-gv659p) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L204)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: Maybe ok to cut this line?
</blockquote></details>

cut it!
___
*[v21.2/set-locality.md, line 265 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-MnfkRA43_7d5fT5yn4F:-Mo0Dz8xE3XJphSB_Sg7:b-whnb92) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L265)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> automatically rehomed
> ```

Worth reiterating the "auto-rehomed" terminology here?
</blockquote></details>

oh yeah good point - changed to "auto-rehomed"

**Review by taroface — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12081#-:-Mo0HjjL6tFaXxxoa7Pu:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rmloveland, and @taroface)

___
*[v21.2/set-locality.md, line 143 at r4](https://reviewable.io/reviews/cockroachdb/docs/12081#-Mnfh3ex1V7r2fT9Fmi-:-Mo0HYlC4qasjJzd1XaB:b-80tlqx) ([raw file](https://github.com/cockroachdb/docs/blob/e895aa8988460b8419f931f9723e387bd3a49826/v21.2/set-locality.md#L143)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I think this can also be fixed by making "home regions" plural as in "the home regions ... are automatically set" so I went with that.  Do you think that also could work?
</blockquote></details>

Sure!

**Pull request merged**
