### PR TITLE
Update kv.snapshot_recovery.max_rate removal note

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-10070

### CODE REVIEW

**Comment by rmloveland** [comment]
@andrewbaptist any objection to the release note changes in this PR re: `kv.snapshot_recovery.max_rate` ?  (DOC-10070 has a link to the Slack convo for add'l context)

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Thanks for getting this changed!

**Comment by rmloveland** [comment]
> Thanks for getting this changed!

np - thank YOU for pinging me about it!

**Comment by rmloveland** [comment]
@florence-crl summary is we're revising a previous release note for a cluster setting removal that was really a "disable, then remove later" that was causing some confusion - more context in the issue

**Review by florence-crl — APPROVED** [review]
LGTM with 1 link suggestion

**Pull request merged**
