### PR TITLE
Add scheduled backups metrics

### LINKED ISSUE #8420: schedules: prometheus metrics and alerting rules
Placeholder for now and I'll add metrics here

cc @miretskiy

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8420

### CODE REVIEW

**Review by mwang1026 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @miretskiy, and @mwang1026)

___
*[v20.2/manage-a-backup-schedule.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAHKVX9-kUdy8mjOE7:-MLAHKVX9-kUdy8mjOE8:bh07xb7) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L34)):*
> ```
>  and alert on metrics that will confirm that your backups are completing
> ```

This phrase seems weird to me. I guess, I feel like what'd be helpful is "what to do if I see X happen". So maybe instead it's `alert when there are anomalies such as backups that have failed or no backups succeeding over X amount of time, at which point you can inspect scheduled by running SHOW SCHEDULES`
___
*[v20.2/manage-a-backup-schedule.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAGmFv2YyLY8iKtZsh:-MLAGmFv2YyLY8iKtZsi:b58ufl0) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L41)):*
> ```Markdown
> 
>     - `schedules_BACKUP_started` - The total number of backups started by a schedule
>     - `schedules_BACKUP_failed` - The number of backups started by a schedule that failed
> ```

What's the right way to point people that they can inspect the latest error in 'SHOW SCHEDULES'? That way they can (1) see which one failed and (2) what the error was
___
*[v20.2/manage-a-backup-schedule.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAH0cT1TjCeeRFVuAE:-MLAH0cT1TjCeeRFVuAF:bwnaq6i) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L46)):*
> ```Markdown
> - Scheduler-specific metrics:
> 
>     - `schedules.round.reschedule-wait` - The number of schedules that were rescheduled due to a currently running backup job. A value > 0 indicates that a previous backup was still running when a new scheduled backup was supposed to start. This corresponds to the [`on_previous_running=wait`](create-schedule-for-backup.html#on-previous-running-option) schedule option.
> ```

How much should we be giving advice -- such as "if you see a lot of this it means your backups are being taken more frequently than can be successfully completed" and for users to consider adjusting the backup cadence to avoid wait or skip if they don't want to have these happen?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @miretskiy, and @mwang1026)

___
*[v20.2/manage-a-backup-schedule.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAGmFv2YyLY8iKtZsh:-MLAb5jU26ZbkdkiqAiy:buevcsl) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L41)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

What's the right way to point people that they can inspect the latest error in 'SHOW SCHEDULES'? That way they can (1) see which one failed and (2) what the error was
</blockquote></details>

I think we should indicate that these are counters.  Any increase in the failed counter should be acted upon, including alerting, and/or examine the reason for the failure via `show schedule(s)`
___
*[v20.2/manage-a-backup-schedule.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAH0cT1TjCeeRFVuAE:-MLAapWi35P3pT1mqSBy:b-hubvul) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L46)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

How much should we be giving advice -- such as "if you see a lot of this it means your backups are being taken more frequently than can be successfully completed" and for users to consider adjusting the backup cadence to avoid wait or skip if they don't want to have these happen?
</blockquote></details>

I think we should indicate that those are gauge metrics.  It's useful to perhaps graph those; it's less useful to alert on these, IMO.  I think we can add a general comment that persistent positive values in those 2 metrics might indicate misconfigured backup cadence.
___
*[v20.2/manage-a-backup-schedule.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAaFvLDxMW6kaqopS5:-MLAaFvLDxMW6kaqopS6:b-70dhg7) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L48)):*
> ```Markdown
>     - `schedules.round.reschedule-wait` - The number of schedules that were rescheduled due to a currently running backup job. A value > 0 indicates that a previous backup was still running when a new scheduled backup was supposed to start. This corresponds to the [`on_previous_running=wait`](create-schedule-for-backup.html#on-previous-running-option) schedule option.
> 
>     - `schedules.roach.reschedule-skip` - The number of schedules that were skipped due to a currently running backup job. A value > 0 indicates that a previous backup was still running when a new scheduled backup was supposed to start. This corresponds to the [`on_previous_running=skip`](create-schedule-for-backup.html#on-previous-running-option) schedule option.
> ```

typo? `schedules.round.reschedule-skip`

Technically, these metrics are not backup specific.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @mwang1026)

___
*[v20.2/manage-a-backup-schedule.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAHKVX9-kUdy8mjOE7:-MLDU56i2s9bCmpQp7nm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L34)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
>  and alert on metrics that will confirm that your backups are completing
> ```

This phrase seems weird to me. I guess, I feel like what'd be helpful is "what to do if I see X happen". So maybe instead it's `alert when there are anomalies such as backups that have failed or no backups succeeding over X amount of time, at which point you can inspect scheduled by running SHOW SCHEDULES`
</blockquote></details>

Done.
___
*[v20.2/manage-a-backup-schedule.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAGmFv2YyLY8iKtZsh:-MLDUfRD8MCQzyw4CqdI:b-je6zpm) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L41)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we should indicate that these are counters.  Any increase in the failed counter should be acted upon, including alerting, and/or examine the reason for the failure via `show schedule(s)`
</blockquote></details>

Edited - missed the note that you included in the issue.
___
*[v20.2/manage-a-backup-schedule.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAH0cT1TjCeeRFVuAE:-MLDadL8EilDLZPtRa84:bvudy74) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L46)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we should indicate that those are gauge metrics.  It's useful to perhaps graph those; it's less useful to alert on these, IMO.  I think we can add a general comment that persistent positive values in those 2 metrics might indicate misconfigured backup cadence.
</blockquote></details>

Edited.
___
*[v20.2/manage-a-backup-schedule.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLAaFvLDxMW6kaqopS5:-MLDUnyb7oF-3yHtPFv9:b-4vsbjf) ([raw file](https://github.com/cockroachdb/docs/blob/c84e3442c017d2d8b59bc20b68f849b58d793421/v20.2/manage-a-backup-schedule.md#L48)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

typo? `schedules.round.reschedule-skip`

Technically, these metrics are not backup specific.
</blockquote></details>

Whoops, a freudian slip :) 

Removed "backup"

**Review by miretskiy — APPROVED** [review]
:lgtm: 
I'll let @mwang1026  chime in as well. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813#-:-MLDklES6LFC_8gVeC_f:b5tjl5i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @mwang1026)

**Review by mwang1026 — APPROVED** [review]
LGTM as well! Noted one minor typo.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813#-:-MLIk0iE02hKko6lKwNY:bza6fwj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh, @miretskiy, @mwang1026, and @taroface)

___
*[v20.2/manage-a-backup-schedule.md, line 34 at r2](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLIjmWx4kdB6XzTGmrR:-MLIjmWx4kdB6XzTGmrS:b-gopnl9) ([raw file](https://github.com/cockroachdb/docs/blob/c0506f456237f82274f738e174cea90a388fc17f/v20.2/manage-a-backup-schedule.md#L34)):*
> ```
> scheduled
> ```
typo? should be `schedules`

**Review by lnhsingh — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813#-:-MLIoe1N82pZ2bnZNLST:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy, @mwang1026, and @taroface)

___
*[v20.2/manage-a-backup-schedule.md, line 34 at r2](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLIjmWx4kdB6XzTGmrR:-MLIocyTDyJ8lyBPDMQX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c0506f456237f82274f738e174cea90a388fc17f/v20.2/manage-a-backup-schedule.md#L34)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> scheduled
> ```
typo? should be `schedules`
</blockquote></details>

Done.

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh, @miretskiy, @mwang1026, and @taroface)

___
*[v20.2/manage-a-backup-schedule.md, line 40 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJAkB52rcqnBqY6NQc:-MLJAkB52rcqnBqY6NQd:b-k0nbh7) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L40)):*
> ```Markdown
> - Backup schedule-specific metrics, aggregated across all schedules:
> 
>     - `schedules_BACKUP_started` - A counter for the total number of backups started by a schedule
> ```

Extremely small nit (applied throughout this doc), but I feel like a colon is usually used for docs elements like this (or at least, I'm using a colon), rather than a hyphen. But please ignore/correct me if this is in line with existing usage
___
*[v20.2/manage-a-backup-schedule.md, line 48 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJBE79E5-cPn6qePVH:-MLJBE79E5-cPn6qePVI:bd9jprh) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L48)):*
> ```
> value > 0
> ```

Maybe `0` with code ticks, if that matches the format?
___
*[v20.2/manage-a-backup-schedule.md, line 50 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJBRyg8FKB3QJG9aw8:-MLJBRyg8FKB3QJG9aw9:b2nreh6) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L50)):*
> ```Markdown
>     - `schedules.round.reschedule-wait` - The number of schedules that were rescheduled due to a currently running job. A value > 0 indicates that a previous backup was still running when a new scheduled backup was supposed to start. This corresponds to the [`on_previous_running=wait`](create-schedule-for-backup.html#on-previous-running-option) schedule option.
> 
>     - `schedules.round.reschedule-skip` - The number of schedules that were skipped due to a currently running job. A value > 0 indicates that a previous backup was still running when a new scheduled backup was supposed to start. This corresponds to the [`on_previous_running=skip`](create-schedule-for-backup.html#on-previous-running-option) schedule option.
> ```

Same as above.
___
*[v20.2/manage-a-backup-schedule.md, line 53 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJCGQq2LvdeleVlVL8:-MLJCGQq2LvdeleVlVL9:b-hvyktv) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L53)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> `schedules.round.reschedule-wait` and `schedules.round.reschedule-skip` are gauge metrics and can be graphed. A persistent positive value for either of these metrics may indicate a misconfigured backup cadence, and you should consider adjusting the cadence to avoid waiting for or skipping the next backup.
> ```

It's not clear to me what "persistent" means in this context, but perhaps it will be to others?
___
*[v20.2/manage-a-backup-schedule.md, line 56 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJCbZ-Awfb7Ynx1KI8:-MLJCbZ-Awfb7Ynx1KI9:bs9obp) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L56)):*
> ```
> Prometheus
> ```

I'd add "to set up monitoring and alerting" after "Prometheus"

**Review by lnhsingh — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8813#-:-MLJE_ZE5RdeS2lD2UzH:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy, @mwang1026, and @taroface)

___
*[v20.2/manage-a-backup-schedule.md, line 40 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJAkB52rcqnBqY6NQc:-MLJD4iuDJFBqVS-_vyo:b78xwgi) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L40)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extremely small nit (applied throughout this doc), but I feel like a colon is usually used for docs elements like this (or at least, I'm using a colon), rather than a hyphen. But please ignore/correct me if this is in line with existing usage
</blockquote></details>

I'm not sure if we have a standard and I never know what to use. Colon works!
___
*[v20.2/manage-a-backup-schedule.md, line 48 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJBE79E5-cPn6qePVH:-MLJDPJr0cmn2nI4OaE4:bl8hjxb) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L48)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> value > 0
> ```

Maybe `0` with code ticks, if that matches the format?
</blockquote></details>

I think I'll leave as is, since it could be referring to a value shown on a graph, not necessarily a counter. But I switched to spelling out "greater than".
___
*[v20.2/manage-a-backup-schedule.md, line 50 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJBRyg8FKB3QJG9aw8:-MLJDfy8-X0W3IXXQfQw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L50)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[v20.2/manage-a-backup-schedule.md, line 53 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJCGQq2LvdeleVlVL8:-MLJDju16HX1mL9TWWsQ:biv5ybu) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L53)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

It's not clear to me what "persistent" means in this context, but perhaps it will be to others?
</blockquote></details>

A positive value that "hangs around for awhile" - revised with the synonym "continual", which I hope clarifies a bit
___
*[v20.2/manage-a-backup-schedule.md, line 56 at r3](https://reviewable.io/reviews/cockroachdb/docs/8813#-MLJCbZ-Awfb7Ynx1KI8:-MLJESUU90KYSfKdAtt5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f97ee5456399e0503a9927030c3efb8b8db004d5/v20.2/manage-a-backup-schedule.md#L56)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Prometheus
> ```

I'd add "to set up monitoring and alerting" after "Prometheus"
</blockquote></details>

Done.

**Pull request merged**
