### PR TITLE
Document the fallout from crdb PR #42563

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by knz** [comment]
Updated as requested by @mattcrdb to mention the privileged UI screens.

**Comment by knz** [comment]
Do you mind taking this PR over and polish it as you see fit?

**Comment by knz** [comment]
cc @aaron-crl  for your information

**Comment by knz** [comment]
Please also include a link to https://github.com/cockroachdb/cockroach/issues/44033 for the blank pages in the UI.

**Comment by knz** [comment]
I have propagated the new understanding to the text. PTAL

**Comment by knz** [comment]
@tim-o requests:

> Generally I think Monday for both would be better - we want to be coordinated and also avoid looking like we’re sneaking something in before the weekend. I don’t want anyone to start an upgrade now. It’s also 4pm in London and after business hours in the rest of the world.

**Comment by tim-o** [comment]
Merging. Thanks @dbist, @jseldess , and @knz !

**Pull request merged**
