### PR TITLE
Diagnostics reporting and global settings

### PR DESCRIPTION
**Pull request by jseldess**
- Add page on diagnostic metrics sent to Cockroach Labs and how to opt out.
- Add page on how to view and change cluster-wide settings.
- Add note about cluster-wide settings to `cockroach start` docs.
- Update SQL reference docs concerning cluster-wide settings.
- Add new pages to the sidenav.

Partly address #1277.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1336)

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @dt. I removed explanations of current global settings, and I added some callouts before you change a global setting. PTAL.

Will move on to the `SHOW` and `SET` reference docs now.

**Comment by dianasaur323** [comment]
I'm on the side that we might be overcompensating in terms of the detail of information we are sharing. I'm trying to find some other examples of how people do it, but I can't seem to find a good example. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-:-KikUBvncg73TCnf5zR0:b7ueqte)*

**Comment by jseldess** [comment]
Thanks, @dianasaur323. I personally feel that we're not sharing anything alarming; rather, the details try to clarify that there's no need for alarm at all. But let's get @bdarnell's opinion here.

**Comment by sploiselle** [comment]
For being a transparent, open-source project, I think this approach aligns with our ethics and does so really tastefully. Really great work on this, @jseldress. 

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[global-configurations.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikUEMgIH1bIZev545P:-KikUEMgIH1bIZev545Q:b-v2fnyt) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/global-configurations.md#L9)):*
> ```Markdown
> In CockroachDB, there are two levels of configuration:
> 
> - 	**Node-level configurations** apply to a single node of a CockroachDB cluster and define, for example, the interfaces for communicating with other nodes and the percent of system memory allocated to key-value operations performed by the node. These settings are defined when a node is started with `cockroach start` and cannot be changed without stopping and restarting the node.
> ```

Because node-level configurations do not apply globally, I would change the architecture of this a little bit to align the content to the title. Instead of talking about the two levels of configuration, I would address cluster-wide configurations primarily and only make a note of the node-level configurations.

Alternatively, you could change the title of the page to something like "Node- and Cluster-Level Configurations."

Also, re: whatever we end up doing to discuss node-level configs, I would also clarify that the settings are defined by the flags passed to the node through `cockroach start`, but that is maybe too pedantic.

---

*[global-configurations.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikUjg0O2CHioUXbPnX:-KikUjg0O2CHioUXbPnY:bfqvzfi) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/global-configurations.md#L11)):*
> ```Markdown
> - 	**Node-level configurations** apply to a single node of a CockroachDB cluster and define, for example, the interfaces for communicating with other nodes and the percent of system memory allocated to key-value operations performed by the node. These settings are defined when a node is started with `cockroach start` and cannot be changed without stopping and restarting the node.
> 
> - 	**Cluster-wide configurations** apply to all nodes of CockroachDB cluster and define, for example, whether or not to share diagnostic details with Cockroach Labs and advanced options for debugging and cluster tuning. These settings are defined via SQL `SET` statements and therefore can be updated anytime after a cluster has been started.
> ```

"via SQL `SET CLUSTER` statements"?

---

*[diagnostic-reporting.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikRnwIPJuxiO01mo_6:-KikRnwIPJuxiO01mo_7:blkwlmk) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostic-reporting.md#L9)):*
> ```Markdown
> By default, each node of a CockroachDB cluster shares diagnostic details with Cockroach Labs on a daily basis. These details greatly help us understand and improve how the system behaves in real-world scenarios, and they are completely scrubbed of identifiable information.
> 
> This page explains the details that get shared and how to opt out of sharing.
> ```

Maybe add a link to the Admin UI doc pages here inline or in a note that says something to the effect of, "For information about your cluster's diagnostics, use our Admin UI." Think it would be easy to mistake this page's title for Admin UI-type info.

---

*[diagnostic-reporting.md, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikSMpVS_LoI1oXpV75:-KikSMpVS_LoI1oXpV76:b-ismw2q) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostic-reporting.md#L15)):*
> ```Markdown
> ## What Gets Shared
> 
> When diagnostic reporting is on, each node of a CockroachDB cluster shares storage and table schema details with Cockroach Labs on a daily basis.
> ```

"shares _anonymized_ storage and table schema details"

---

*[diagnostic-reporting.md, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikSYmoo5VCmnJrWdXj:-KikSYmoo5VCmnJrWdXk:b13770i) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostic-reporting.md#L24)):*
> ```Markdown
> -------|------------
> Node ID | The ID of the node.
> Store ID | The ID of each store on the node.
> ```

My slight confusion/apprehension here is if these values uniquely identify my cluster. The `Table` description below expresses that the ID is just an internal ID; is this ID the same kind of thing?

---

*[diagnostic-reporting.md, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikTo2O-6VoKHkGuacK:-KikTo2O-6VoKHkGuacL:b-4meo7t) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostic-reporting.md#L189)):*
> ```Markdown
> ~~~
> 
> ## How to Opt Out
> ```

nit: Would prefer a title like "Opt Out of Diagnostics Reporting"

---

*[diagnostic-reporting.md, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikS73NKXmBibgG37M0:-KikS73NKXmBibgG37M1:bobt26u) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostic-reporting.md#L197)):*
> ```Markdown
> ~~~
> 
> Note that this change will not be instantaneous, as it must be propigated to other nodes in the cluster. If you want to make sure that no diagnostic details are shared, you can set the environment variable `COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true` before starting the first node of the cluster. Note that this works only when set before starting the first node of the cluster. Once the cluster is running, you need to use the `SET` method described above.
> ```

s/propigated/propagated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-:-KikZ3ejtNdBGm8ekrnt:b-4xcy3r)*

**Comment by jseldess** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[diagnostics-reporting.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikRnwIPJuxiO01mo_6:-KiknzZJ_3yVPNdYjkKP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostics-reporting.md#L9)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Maybe add a link to the Admin UI doc pages here inline or in a note that says something to the effect of, "For information about your cluster's diagnostics, use our Admin UI." Think it would be easy to mistake this page's title for Admin UI-type info.
</blockquote></details>

Done.

---

*[diagnostics-reporting.md, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikSMpVS_LoI1oXpV75:-KikhM-wvcGffRdHIckU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostics-reporting.md#L15)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

"shares _anonymized_ storage and table schema details"
</blockquote></details>

Done.

---

*[diagnostics-reporting.md, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikSYmoo5VCmnJrWdXj:-KikhXT79jrJCipY_Usa:bj48mfl) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostics-reporting.md#L24)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

My slight confusion/apprehension here is if these values uniquely identify my cluster. The `Table` description below expresses that the ID is just an internal ID; is this ID the same kind of thing?
</blockquote></details>

Yeah, by `internal`, I just mean that CockroachDB assigns the value rather than a user/client. I've added that, but let me know if you think I should add another sentence.

---

*[diagnostics-reporting.md, line 189 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikTo2O-6VoKHkGuacK:-Kiki0933CnE9jX5PHi1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostics-reporting.md#L189)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

nit: Would prefer a title like "Opt Out of Diagnostics Reporting"
</blockquote></details>

Done.

---

*[diagnostics-reporting.md, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikS73NKXmBibgG37M0:-KikiNZxyw26s320quAV:b-tb6ely) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/diagnostics-reporting.md#L197)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

s/propigated/propagated
</blockquote></details>

Done. I really need to use an automated spellchecker!

---

*[global-configurations.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikUEMgIH1bIZev545P:-KikmLE3_x5Mwbxw4mOq:b6vfxr7) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/global-configurations.md#L9)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Because node-level configurations do not apply globally, I would change the architecture of this a little bit to align the content to the title. Instead of talking about the two levels of configuration, I would address cluster-wide configurations primarily and only make a note of the node-level configurations.

Alternatively, you could change the title of the page to something like "Node- and Cluster-Level Configurations."

Also, re: whatever we end up doing to discuss node-level configs, I would also clarify that the settings are defined by the flags passed to the node through `cockroach start`, but that is maybe too pedantic.
</blockquote></details>

Done. Great feedback. 

---

*[global-configurations.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikUjg0O2CHioUXbPnX:-KikiaGQLx3ub08g6fOz:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/global-configurations.md#L11)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

"via SQL `SET CLUSTER` statements"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336)*

**Comment by sploiselle** [comment]
really great work :lgtm:

---

Reviewed 4 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-:-KikqWFf2x16Bvqkc5Zw:bs9ly60)*

**Comment by knz** [comment]
Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[diagnostics-reporting.md, line 66 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil4nyr9ni5BE66c79P:-Kil4nyr9ni5BE66c79Q:bjxr5ro) ([raw file](https://github.com/cockroachdb/docs/blob/d976595f1d0f1be01b3841bda6c17627ec03134f/diagnostics-reporting.md#L66)):*
> ```Markdown
> Each node of a CockroachDB cluster shares the following schema details for each table stored on the node:
> 
> {{site.data.alerts.callout_info}}No actual table data is shared, just metadata about the schema of tables, and all name and other string values are scrubbed and replaced with underscores.{{site.data.alerts.end}}
> ```

I would place a period between "about the schema of tables" and "All names and ..."

---

*[global-configurations.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikUjg0O2CHioUXbPnX:-Kil5sAawXRpOMQeCW0J:b6ya27z) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/global-configurations.md#L11)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Mention also that only the root user can modify settings.
(And perhaps highlight that's one more reason to create users for client apps in a production environment, because client apps logged as root could change these and that would be unsafe.)

---

*[global-configurations.md, line 69 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil6FAXw10L-zNuUnqU:-Kil6FAXw10L-zNuUnqV:ba4783s) ([raw file](https://github.com/cockroachdb/docs/blob/d976595f1d0f1be01b3841bda6c17627ec03134f/global-configurations.md#L69)):*
> ```Markdown
> Before changing a global configuration, please note the following:
> 
> - 	Many global configurations are intended for tuning CockroachDB internals. Before changing these settings, it's best to [discuss your goals with CockroachDB](https://gitter.im/cockroachdb/cockroach); otherwise, you use them at your own risk.
> ```

I think the responsibility disclaimer is too weak with this phrasing.
Right now I could read that "As long as I mentioned it on gitter, even though it was on sunday at night and nobody noticed, I did my share of telling and thus CRL is responsible for the consequences." 

Perhaps invert the sentence: "Use this configuration mechanism at your own risk. If you think you need to tune these knobs, we encourage you to first [discuss your goals ...]. "

---

*[_data/sidebar_doc.yml, line 205 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil6v-kJcpo0IvD6Gx_:-Kil6v-kJcpo0IvD6Gxa:b-dbc7z0) ([raw file](https://github.com/cockroachdb/docs/blob/d976595f1d0f1be01b3841bda6c17627ec03134f/_data/sidebar_doc.yml#L205)):*
> ```YAML
>                   url: /select.html
> 
>                 - title: <code>SET DATABASE</code>
> ```

SET CLUSTER SETTING is missing here (and SHOW [ALL] CLUSTER SETTING) below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[diagnostics-reporting.md, line 66 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil4nyr9ni5BE66c79P:-Kil8u3aob831Mlfe05q:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d976595f1d0f1be01b3841bda6c17627ec03134f/diagnostics-reporting.md#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would place a period between "about the schema of tables" and "All names and ..."
</blockquote></details>

Done.

---

*[global-configurations.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KikUjg0O2CHioUXbPnX:-Kil9qw-15Nz5MStTrgX:b5espj9) ([raw file](https://github.com/cockroachdb/docs/blob/2314c7af3913041025869d8a825b2835de90f090/global-configurations.md#L11)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Mention also that only the root user can modify settings.
(And perhaps highlight that's one more reason to create users for client apps in a production environment, because client apps logged as root could change these and that would be unsafe.)
</blockquote></details>

I added the detail about `SET CLUSTER SETTING` being limited to the `root` user. Thanks for pointing that out! I didn't add the detail about non-root users for client apps. It's a very good point, but the guidance is broader than this feature, so I want to find the right place for it. Opened this issue: https://github.com/cockroachdb/docs/issues/1342

---

*[global-configurations.md, line 69 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil6FAXw10L-zNuUnqU:-KilDLVgk0gWk-LHJOsZ:b-12z4dr) ([raw file](https://github.com/cockroachdb/docs/blob/d976595f1d0f1be01b3841bda6c17627ec03134f/global-configurations.md#L69)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the responsibility disclaimer is too weak with this phrasing.
Right now I could read that "As long as I mentioned it on gitter, even though it was on sunday at night and nobody noticed, I did my share of telling and thus CRL is responsible for the consequences." 

Perhaps invert the sentence: "Use this configuration mechanism at your own risk. If you think you need to tune these knobs, we encourage you to first [discuss your goals ...]. "
</blockquote></details>

Strengthened the language, styled it as a warning, and listed it first.

---

*[_data/sidebar_doc.yml, line 205 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil6v-kJcpo0IvD6Gx_:-KilDTjT0BcttkEyvxUB:b-ihe065) ([raw file](https://github.com/cockroachdb/docs/blob/d976595f1d0f1be01b3841bda6c17627ec03134f/_data/sidebar_doc.yml#L205)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

SET CLUSTER SETTING is missing here (and SHOW [ALL] CLUSTER SETTING) below
</blockquote></details>

I didn't create stand-alone pages for these statements but rather covered them in the `global-configurations.md` page. Though I did list them on `sql-statements.md`, I can't add them to the sidenav as you ask due to a quirk in the way the sidenav behaves: If multiple items in the sidenav match the current url, all sections containing those items are expanded, which is just bad user experience. This is definitely something we should fix at some point, since it's natural to want to link to the same page from multiple parts of a navigation sometimes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336)*

**Comment by bdarnell** [comment]
LGTM. I agree with being detailed about what's being collected, and especially with being explicit about the scrubbing being done. 

---

Reviewed 1 of 4 files at r2, 1 of 2 files at r5.
Review status: 4 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[diagnostics-reporting.md, line 17 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilZBQGcqiz3qIngmCi:-KilZBQGcqiz3qIngmCj:b-gode6w) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L17)):*
> ```Markdown
> ## What Gets Shared
> 
> When diagnostics reporting is on, each node of a CockroachDB cluster shares anonymized storage and table schema details with Cockroach Labs on a daily basis.
> ```

How do we want to handle the fact that this set will change over time? In particular we're close to adding details about query skeletons (I think this will be going in for 1.0).  It's great that we're specific about what gets shared, but we want to be clear that we may change this in future releases. 

---

*[diagnostics-reporting.md, line 33 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilYAIMhsckQaJUGQ_P:-KilYAIMhsckQaJUGQ_Q:brlk9pb) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L33)):*
> ```Markdown
> #### Example
> 
> This JSON example shows what storage details look like when sent to Cockroach Labs, in this case for a node with two stores:
> ```

I think I'd drop all the json examples; they're fairly redundant and make the page much more verbose. Or we could collapse them somehow so you can still get to them if you want, but I don't know if it's worth keeping them around (and up to date) if they won't be shown by default (or maybe it is, since it would be nice to show the effects of the scrubbing, especially for the query stats)

On the other hand, it would be nice if we had a link in the admin UI to show a copy of all the uploaded information for *your* cluster.

---

*[diagnostics-reporting.md, line 64 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilYfMckxRED3xkO7lI:-KilYfMckxRED3xkO7lJ:boz0r3h) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L64)):*
> ```Markdown
> ### SQL Schemas
> 
> Each node of a CockroachDB cluster shares the following schema details for each table stored on the node:
> ```

We may want to use the word "structure" here instead of "schema", to emphasize that we're only sending the tables in a skeletal form. 

---

*[diagnostics-reporting.md, line 66 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilYq2BMceLKpVa1WsM:-KilYq2BMceLKpVa1WsN:bfesntp) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L66)):*
> ```Markdown
> Each node of a CockroachDB cluster shares the following schema details for each table stored on the node:
> 
> {{site.data.alerts.callout_info}}No actual table data is shared, just metadata about the schema of tables. All name and other string values are scrubbed and replaced with underscores.{{site.data.alerts.end}}
> ```

"No actual table data or table/column names are shared..."

---

*[global-configurations.md, line 2 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil_TW__OUnC-cki579:-Kil_TW__OUnC-cki57A:b34q1b0) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/global-configurations.md#L2)):*
> ```Markdown
> ---
> title: Global Configurations
> ```

Maybe call this "cluster settings" since that's what the commands say?

---

*[global-configurations.md, line 28 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil_NGWk9VXhxMx1wq7:-Kil_NGWk9VXhxMx1wq8:baiypy1) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/global-configurations.md#L28)):*
> ```Markdown
> -------|------| -----------
> `diagnostics.reporting.enabled` | Boolean | Whether or not nodes sends diagnostic details to CockroachDB. For more details, see [Diagnostics Reporting](diagnostics-reporting.html).<br><br>**Possible values:** `true` or `false`<br>**Default:** `true`
> `enterprise.enabled` | Boolean | Whether or not Enterprise-grade features covered under the CockroachDB Community License (CCL) are enabled. For pricing and other details, please contact [CockroachDB Sales](https://www.cockroachlabs.com/pricing/sales/).
> ```

Remove this. We're hiding the enterprise.enabled setting for 1.0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-:-Kil_y9Qmj9DDFlLcs4M:b-19g8r)*

**Comment by jseldess** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[diagnostics-reporting.md, line 17 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilZBQGcqiz3qIngmCi:-KimSxdVB3bJvL92ccrV:b-ytlfcn) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L17)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How do we want to handle the fact that this set will change over time? In particular we're close to adding details about query skeletons (I think this will be going in for 1.0).  It's great that we're specific about what gets shared, but we want to be clear that we may change this in future releases. 
</blockquote></details>

I've added a note that these details may change in the future. I think we should just strive to update this page when we do change or add things. 

---

*[diagnostics-reporting.md, line 33 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilYAIMhsckQaJUGQ_P:-KimXsvx8sz_Gc6DX54o:b-7k5uge) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L33)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think I'd drop all the json examples; they're fairly redundant and make the page much more verbose. Or we could collapse them somehow so you can still get to them if you want, but I don't know if it's worth keeping them around (and up to date) if they won't be shown by default (or maybe it is, since it would be nice to show the effects of the scrubbing, especially for the query stats)

On the other hand, it would be nice if we had a link in the admin UI to show a copy of all the uploaded information for *your* cluster.
</blockquote></details>

Yeah, I like providing the JSON as proof that we're scrubbing strings. I agree that they make the page more verbose, though, especially the schema example, so I've truncated most of the it away and called out that it's just an excerpt of what table structure data looks like when it gets sent.

---

*[diagnostics-reporting.md, line 64 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilYfMckxRED3xkO7lI:-KimXrk7f2ufp3N-e0BC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L64)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We may want to use the word "structure" here instead of "schema", to emphasize that we're only sending the tables in a skeletal form. 
</blockquote></details>

Done.

---

*[diagnostics-reporting.md, line 66 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-KilYq2BMceLKpVa1WsM:-KimXqa762jMncydvWx0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/diagnostics-reporting.md#L66)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"No actual table data or table/column names are shared..."
</blockquote></details>

Done.

---

*[global-configurations.md, line 2 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil_TW__OUnC-cki579:-KimaltYeEGKAQQ7U9ng:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/global-configurations.md#L2)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe call this "cluster settings" since that's what the commands say?
</blockquote></details>

Done.

---

*[global-configurations.md, line 28 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1336#-Kil_NGWk9VXhxMx1wq7:-KimYZBGFS5lIHjmwu_a:b-hacujd) ([raw file](https://github.com/cockroachdb/docs/blob/c713a64e04597c9f54187c38a73b444e5b5c9af5/global-configurations.md#L28)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this. We're hiding the enterprise.enabled setting for 1.0.
</blockquote></details>

Done. This section is commented out for now, but might as well remove this setting now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1336)*

**Pull request merged**
