### PR TITLE
advisories: add advisory 68005

### PR DESCRIPTION
**Pull request by jordanlewis**

### CODE REVIEW

**Comment by nickelnickel** [comment]
Can we make the links go to the PR directly? Right now it's showing as [#68002] and not a link to github. Otherwise this .LGTM

**Review by nickelnickel — CHANGES_REQUESTED** [review]
Make the links go to the PR directly? Right now it's showing as [#68002] and not a link to github. Otherwise this .LGTM

**Comment by jordanlewis** [comment]
Done

**Comment by nickelnickel** [comment]
LGTM. Ship it!

**Review by shermanCRL — APPROVED** [review]
LGTM. Thanks!

**Review by lnhsingh — COMMENTED** [review]
Some style and formatting nits. Once fixed, LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11091#-:-MhodsLbAuW_vvWyHPss:b-rut0t7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[advisories/a68005.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-Mhob_jV9YUBQh_bQdsK:-Mhob_jW8agihGIXmsj3:b-tm5ub1) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L11)):*
> ```
> sql.trace.txn.enable_threshold cluster setting
> ```

"sql.trace.txn.enable_threshold" should have backticks around it and "cluster setting" should link to `../v21.1/cluster-settings.html`
___
*[advisories/a68005.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhocFiVCAJSCmlkZZtL:-MhocFiVCAJSCmlkZZtM:bw9ypbi) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L13)):*
> ```Markdown
> Cockroach Labs has discovered a bug in which setting the sql.trace.txn.enable_threshold cluster setting to a non-0 value causes nodes to crash loop in versions 21.1.0 to 21.1.6. The cause of this bug was a misuse of an internal tracing API.
> 
> ## Statement
> ```

Add an empty line after this heading
___
*[advisories/a68005.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhocNRx9LQ-tCb-5t1q:-MhocNRx9LQ-tCb-5t1r:b-fg52dd) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L16)):*
> ```
> 21.1.7+
> ```
This should be "v21.1.7+"
___
*[advisories/a68005.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhocW5V2p0u-sZ2n53Q:-MhocW5V2p0u-sZ2n53R:banrz1x) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L22)):*
> ```Markdown
> ## Mitigation
> 
> The mitigation is to upgrade to CockroachDB version 21.1.7+ or to restore from a backup that did not have the cluster setting set to a non-0 value.
> ```

"restore" should link to `/v21.1/restore`
___
*[advisories/a68005.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-Mhod-63BYMG-n8Vi1Ns:-Mhod-6472Q47Kw5nM4T:b56168p) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L26)):*
> ```Markdown
> ## Impact
> 
> Setting the sql.trace.txn.enable_threshold cluster setting to a non-0 value causes all nodes in the cluster to permanently crash loop. There is no mitigation possible besides upgrading to CockroachDB 21.1.7+, restoring a backup into a 20.2 cluster, or restoring a backup without the cluster setting set into 21.1.
> ```

- sql.trace.txn.enable_threshold needs backticks around it
- "CockroachDB 21.1.7+" should be "CockroachDB 21.1.7+", same with "20.2" should be "v20.2" and "21.1" should be "v21.1"

Style nit: "There is no mitigation possible" makes it seem like there's no mitigation, so I'd recommend rewording to be something like "To mitigate, upgrade to CockroachDB.., restore a backup ... , or restore a backup without the cluster setting ..."
___
*[advisories/a68005.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhodmMVEHadbpOrlZ7r:-MhodmMVEHadbpOrlZ7s:bb3lol8) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L28)):*
> ```Markdown
> Setting the sql.trace.txn.enable_threshold cluster setting to a non-0 value causes all nodes in the cluster to permanently crash loop. There is no mitigation possible besides upgrading to CockroachDB 21.1.7+, restoring a backup into a 20.2 cluster, or restoring a backup without the cluster setting set into 21.1.
> 
> All deployments running CockroachDB 21.1.0 to 21.1.6 are affected. Upgrading a 20.2 cluster to an affected version of 21.1 that has the cluster already set will also be affected by the bug. Such an upgrade can be mitigated by rolling back to 20.2 unless the version upgrade was finalized. Cockroach Labs acknowledges the issue and has issued a fix that is available in 21.1.7.
> ```

version numbers in this paragraph need a "v" in front of them.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11091)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[advisories/a68005.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-Mhob_jV9YUBQh_bQdsK:-Mhp4RhnEDIM9_wXDBEN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L11)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

> ```
> sql.trace.txn.enable_threshold cluster setting
> ```

"sql.trace.txn.enable_threshold" should have backticks around it and "cluster setting" should link to `../v21.1/cluster-settings.html`
</blockquote></details>

Done.
___
*[advisories/a68005.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhocFiVCAJSCmlkZZtL:-Mhp4RsHANgyeyOHDDwC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L13)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Add an empty line after this heading
</blockquote></details>

Done.
___
*[advisories/a68005.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhocNRx9LQ-tCb-5t1q:-Mhp4SAuD2lIGNAS4Cox:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L16)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

> ```
> 21.1.7+
> ```
This should be "v21.1.7+"
</blockquote></details>

Done.
___
*[advisories/a68005.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhocW5V2p0u-sZ2n53Q:-Mhp4SVHBgkGNyQx36hi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L22)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

"restore" should link to `/v21.1/restore`
</blockquote></details>

Done.
___
*[advisories/a68005.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-Mhod-63BYMG-n8Vi1Ns:-Mhp4Sm916mzquxToPR7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L26)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

- sql.trace.txn.enable_threshold needs backticks around it
- "CockroachDB 21.1.7+" should be "CockroachDB 21.1.7+", same with "20.2" should be "v20.2" and "21.1" should be "v21.1"

Style nit: "There is no mitigation possible" makes it seem like there's no mitigation, so I'd recommend rewording to be something like "To mitigate, upgrade to CockroachDB.., restore a backup ... , or restore a backup without the cluster setting ..."

</blockquote></details>

Done.
___
*[advisories/a68005.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/11091#-MhodmMVEHadbpOrlZ7r:-Mhp4TLXEEY2kkmCvXtc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c805c7c165766ec57e57ae68fd4b0c2662fd3fc6/advisories/a68005.md#L28)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

version numbers in this paragraph need a "v" in front of them.
</blockquote></details>

Done.

**Pull request merged**
