### PR TITLE
Add known limitation around dropping interleaved indexes

### LINKED ISSUE #1589: Known limitation: Dropping an interleave index causes backreference preventing DDL activities
Add to 1.0 known limitations: https://github.com/cockroachdb/cockroach/issues/16471#issuecomment-308132198

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1589

### CODE REVIEW

**Comment by jseldess** [comment]
@m-schneider, finally adding this as a known limitation for 1.0. Also adding it as a limitation ion 1.1, but once https://github.com/cockroachdb/cockroach/pull/17860 lands, I can remove that.

**Comment by m-schneider** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.0/known-limitations.md, line 286 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1859#-KsJdmJFDjS3UyZbMakL:-KsJdmJFDjS3UyZbMakM:bgkncgg) ([raw file](https://github.com/cockroachdb/docs/blob/6e955243c61de21627325dd4e951301daead2d49/v1.0/known-limitations.md#L286)):*
> ```Markdown
> ## Dropping an interleaved index prevents DDL operations
> 
> When you [drop an interleaved index](drop-index.html) on a table, future DDL operations on the table will fail, for example:
> ```

The limitation is only when you drop an interleaved index on the same table. In your example: INTERLEAVE IN PARENT t1 (id2); would fail, but if the parent was t2 or any other table we wouldn't have the problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1859)*

**Comment by jseldess** [comment]
*[v1.0/known-limitations.md, line 286 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1859#-KsJdmJFDjS3UyZbMakL:-KsJnR_iVMEuAzGJVEsJ:bwoewwx) ([raw file](https://github.com/cockroachdb/docs/blob/6e955243c61de21627325dd4e951301daead2d49/v1.0/known-limitations.md#L286)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

The limitation is only when you drop an interleaved index on the same table. In your example: INTERLEAVE IN PARENT t1 (id2); would fail, but if the parent was t2 or any other table we wouldn't have the problem.
</blockquote></details>

Thanks, Masha. Take another look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1859)*

**Comment by m-schneider** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[v1.0/known-limitations.md, line 286 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1859#-KsJdmJFDjS3UyZbMakL:-KsJns8zDL6C34j7SL6I:b-vs1prh) ([raw file](https://github.com/cockroachdb/docs/blob/6e955243c61de21627325dd4e951301daead2d49/v1.0/known-limitations.md#L286)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Thanks, Masha. Take another look.
</blockquote></details>

Looks good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1859#-:-KsJnvIg-5lWkM5gZiw6:bnfp4nl)*

**Pull request merged**
