### PR TITLE
DOC-8247: Add content for Dedicated advanced

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Addresses [DOC-8247](https://cockroachlabs.atlassian.net/browse/DOC-8247)

### CODE REVIEW

**Comment by theodore-hyman** [comment]
@Amruta-Ranade can you tell me what I'm doing wrong here? The below URL doesn't show anything for me

https://deploy-preview-17593--cockroachdb-docs.netlify.app/v23.1/choose-a-deployment-option.md

Thank you

**Comment by Amruta-Ranade** [comment]
> @Amruta-Ranade can you tell me what I'm doing wrong here? The below URL doesn't show anything for me
> 
> https://deploy-preview-17593--cockroachdb-docs.netlify.app/v23.1/choose-a-deployment-option.md
> 
> Thank you

Hi! Can you try this link: https://deploy-preview-17593--cockroachdb-docs.netlify.app/docs/stable/choose-a-deployment-option

**Comment by theodore-hyman** [comment]
Thank you @Amruta-Ranade appreciate the assistance there. Taking a review of the page, it looks good. Appreciate the fast turnaround on getting this docs page created. The way you split out Advanced Dedicated and put "All CockroachDB Dedicated features." and then listed only the relevant additional features - it looks really clean nicely done.

**Comment by kannanlakshmi** [comment]
LGTM - thanks @Amruta-Ranade 
Also tagging @jramos-crl quickly to check on the advanced tier docs.

**Comment by jramos-crl** [comment]
@Amruta-Ranade one clarification - Audit Logs are for both cluster and org logs, in case we want to be clear there. Similarly for SSO, it is cluster and org SSO. Otherwise, it looks good!

**Comment by Amruta-Ranade** [comment]
> @Amruta-Ranade one clarification - Audit Logs are for both cluster and org logs, in case we want to be clear there. Similarly for SSO, it is cluster and org SSO. Otherwise, it looks good!

Done.

**Review by florence-crl — APPROVED** [review]
LGTM!

**Pull request merged**
