### PR TITLE
Uplevel Driver/ORM support in Developer Guide

### PR DESCRIPTION
**Pull request by ericharmeling**
Upleveled Driver/ORM support overview in "Develop" section.

I also removed this from the SQL Reference section, as this isn't reference material.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@awoods187 FYI

**Comment by awoods187** [comment]
I love pulling this up--this is great. I like Jesse's idea but I think I'd need to see it in practice.

**Comment by ericharmeling** [comment]
> Should we consider making this action-oriented, like the rest of the topics in this guide: `Install a Postgres Client`? 

This is a great idea. We currently have no instructions for specific drivers/ORMs outside of their Hello World tutorials. It might be best to decouple that from this PR though, as I'll probably do that for all of them and then make those instructions into includes that we add to the Hello World examples. Thoughts @jseldess ?

**Comment by jseldess** [comment]
SGTM!

**Pull request merged**
