### PR TITLE
Add a c# tutorial for an insecure cluster

### LINKED ISSUE #1679: Test C# driver with CockroachDB
Re: [Install Client Drivers](https://cockroachlabs.com/docs//v1.0/install-client-drivers.html)

## Issue Description
Where is C# driver?

### LINKED ISSUE #1888: New Doc Proposal: Build a .NET Core App with CockroachDB
I'm happy to contribute this documentation when I have time.

## Title
Build a .NET Core App with CockroachDB

## Description
This tutorial shows you how build a simple .NET Core application with CockroachDB using a PostgreSQL-compatible driver or ORM.

## Outline
1. Install/set up .NET Core app
2. Install/set up Cockroach
3. Connect app to db with Npgsql and one of two ORMs:
    - Entity Framework Core
    - Dapper
4. Basic CRUD operations
5. Transactions

## Expected Audience
Web app developers

### LINKED ISSUE #2020: Support C#
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recbx4TkrFl7nc84m

PRs:
- https://github.com/cockroachdb/docs/pull/1991

### LINKED ISSUE #2108: no c# Client Driver?
no c# Client Driver?

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #2020 

Also:
Fixes #2108 
Fixes #1888 
Fixes #1679

### CODE REVIEW

**Comment by BramGruneir** [comment]
There is no link the pulldown menu to the page.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[v1.1/build-a-csharp-app-with-cockroachdb.md, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-L-IM5QBjksKZ2fNCFlp:-L-IM5QBjksKZ2fNCFlq:bpgy2f0) ([raw file](https://github.com/cockroachdb/docs/blob/378bfcb7240dc685c7409b9c3b61d4ba3291edd8/v1.1/build-a-csharp-app-with-cockroachdb.md#L19)):*
> ```Markdown
> 
> {% include copy-clipboard.html %}
> ~~~ shell
> ```

So all of this is very linux/mac os centric.  Perhaps we should add instructions for windows as well.  (In a follow up PR perhaps.)  Most c# users will be windows users.

---

*[v1.1/build-a-csharp-app-with-cockroachdb.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-L-IMQQp_GKyI7kkA6yQ:-L-IMQQp_GKyI7kkA6yR:b80z38d) ([raw file](https://github.com/cockroachdb/docs/blob/378bfcb7240dc685c7409b9c3b61d4ba3291edd8/v1.1/build-a-csharp-app-with-cockroachdb.md#L36)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ shell
> $ dotnet add package Npgsql --version 3.2.5
> ```

This version number will change.  Perhaps mention to use the latest stable.  I wonder if it will work without the version number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-:-L-ILkuerR1coBceG5Jk:bzai9b2)*

**Comment by jseldess** [comment]
Added it to the sidenav. Thanks for catching that, Bram.

---

Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[v1.1/build-a-csharp-app-with-cockroachdb.md, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-L-IM5QBjksKZ2fNCFlp:-L-ITFxCrw8RPJLXTzJO:b-fg83z1) ([raw file](https://github.com/cockroachdb/docs/blob/378bfcb7240dc685c7409b9c3b61d4ba3291edd8/v1.1/build-a-csharp-app-with-cockroachdb.md#L19)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So all of this is very linux/mac os centric.  Perhaps we should add instructions for windows as well.  (In a follow up PR perhaps.)  Most c# users will be windows users.
</blockquote></details>

If you find that some commands differ on Windows, I can definitely add an OS toggle. Let me know.

---

*[v1.1/build-a-csharp-app-with-cockroachdb.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-L-IMQQp_GKyI7kkA6yQ:-L-IU_ybJAh1VM4C2QZq:b-rsildt) ([raw file](https://github.com/cockroachdb/docs/blob/378bfcb7240dc685c7409b9c3b61d4ba3291edd8/v1.1/build-a-csharp-app-with-cockroachdb.md#L36)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This version number will change.  Perhaps mention to use the latest stable.  I wonder if it will work without the version number.
</blockquote></details>

Good point. It does work without the version number, for me at least, so I've removed the `--version` flag:

```
~/cockroachdb-test-app2$ dotnet add package Npgsql
  Writing /var/folders/5t/1rt6nzr17sjg87mz5n0fw15c0000gn/T/tmp60g0LB.tmp
info : Adding PackageReference for package 'Npgsql' into project '/Users/jesseseldess/cockroachdb-test-app2/cockroachdb-test-app2.csproj'.
log  : Restoring packages for /Users/jesseseldess/cockroachdb-test-app2/cockroachdb-test-app2.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/npgsql/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/npgsql/index.json 128ms
info : Package 'Npgsql' is compatible with all the specified frameworks in project '/Users/jesseseldess/cockroachdb-test-app2/cockroachdb-test-app2.csproj'.
info : PackageReference for package 'Npgsql' version '3.2.5' added to file '/Users/jesseseldess/cockroachdb-test-app2/cockroachdb-test-app2.csproj'.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-:-L-ITAKb55mRaTmI0l9I:b-7e9mzy)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2236#-:-L-XWIFWuPUOxYcWLtbd:bnfp4nl)*

**Comment by BramGruneir** [comment]
Reviewed 34 of 38 files at r3.
Review status: 36 of 40 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2236)*

**Pull request merged**
