### PR TITLE
CC Release Notes - March 2021

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes [CC-3654](https://cockroachlabs.atlassian.net/browse/CC-3654)

### CODE REVIEW

**Review by kannanlakshmi — APPROVED** [review]
LGTM. I didn't raise this in Slack but raising it here because I don't know if we ever covered this but do we want to say that AWS PrivateLink is now GA and available to all organizations? We dont see to have covered it in Feb release notes. cc @thtruo 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9937#-:-MVCFIIz-4TeGgezQADO:b-mukcsp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by lnhsingh — COMMENTED** [review]
Yeah, good point - this is the first time that PrivateLink is coming up in release notes since it missed February's release notes. In that case, i can elevate it to be the first bullet point. @thtruo do you have any thoughts on what it should say? Or just something like:

```
AWS PrivateLink is now generally available to any CockroachCloud clusters running on AWS.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9937#-:-MVHDXI8CEmjTbIQOKev:bjrq9za)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by thtruo** [comment]
@lnhsingh that plan sounds good 👍 Minor suggestion/amendment to what the snippet could say (feel free to keep what you want and toss what you don't like)

```
Self-service AWS PrivateLink is now generally available for CockroachCloud clusters running on AWS.
```

**Review by lnhsingh — COMMENTED** [review]
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9937#-:-MVHkzqVACLRBS4iXwwp:b-u8hs9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by gemma-shay — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[releases/cockroachcloud-03082021.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/9937#-MVHzUOj2-_UiszTHtVP:-MVHzUOj2-_UiszTHtVQ:b312uv8) ([raw file](https://github.com/cockroachdb/docs/blob/4553f196a61eb825503ca1a1bb5d391a50e501aa/releases/cockroachcloud-03082021.md#L19)):*
> ```Markdown
> ### Console changes
> 
> - Self-service [AWS PrivateLink](../cockroachcloud/connect-to-your-cluster.html#establish-vpc-peering-or-aws-privatelink) is now generally available for CockroachCloud clusters running on AWS.
> ```

Nit: Might be better to link to /network-authorization.html#aws-privatelink for more info about PL. I see this page as the main source of PL information and the Connect steps as quick & simplified.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9937)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/cockroachcloud-03082021.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/9937#-MVHzUOj2-_UiszTHtVP:-MVI0sal3GIzPFv0bC_-:b-ie0w2r) ([raw file](https://github.com/cockroachdb/docs/blob/4553f196a61eb825503ca1a1bb5d391a50e501aa/releases/cockroachcloud-03082021.md#L19)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Nit: Might be better to link to /network-authorization.html#aws-privatelink for more info about PL. I see this page as the main source of PL information and the Connect steps as quick & simplified.
</blockquote></details>

Good call - updated!

**Pull request merged**
