### PR TITLE
Update admin-ui-overview.md

### PR DESCRIPTION
**Pull request by dbist**

### CODE REVIEW

**Comment by dbist** [comment]
@jseldess according to this [thread](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1581935937148700?thread_ts=1581577209.135700&cid=CP4D9LD5F), the admin UI mitigation for non-admin users requires server restart. I did not see the same set of instructions on v20.1

**Comment by jseldess** [comment]
@Amruta-Ranade, @taroface, whoever takes https://github.com/cockroachdb/docs/pull/6858 should take this as well.

**Comment by taroface** [comment]
@jseldess @Amruta-Ranade 

Amruta has taken #6858, but I might be better positioned to address this update, since I did the Admin UI security updates and this step needs to be added to a number of different docs (see: #6640). If you both don't mind, I can self-assign this.

**Comment by Amruta-Ranade** [comment]
Oh..hmm..Then do you mind taking both issues? I think dividing them up might cause something to slip through the cracks.

**Comment by taroface** [comment]
@Amruta-Ranade Sure! I will take both. Sorry for any confusion.

**Comment by taroface** [comment]
I opened #6958 based on this change. Closing this one!

**Pull request closed without merging**
