### PR TITLE
20.1 known limitations

### PR DESCRIPTION
**Pull request by jseldess**
Add new limitations and remove resolved limitations.

### CODE REVIEW

**Comment by awoods187** [comment]
@lucy-zhang @jordanlewis and @RaduBerinde are there any other known limitations that can be lifted for 20.1?

**Comment by jseldess** [comment]
___
*[v20.1/known-limitations.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/7118#-M537eZR2gqWQ5_o56an:-M537eZR2gqWQ5_o56ao:b-tb9c9d) ([raw file](https://github.com/cockroachdb/docs/blob/ce25c3ff0e96458157560fa5c0c484fa97ae63c6/v20.1/known-limitations.md#L60)):*
> ```Markdown
> [Tracking Github Issue](https://github.com/cockroachdb/cockroach/issues/43177)
> 
> ### Concurrent SQL shells overwrite each other's history
> ```

@knz, PTAL.

**Comment by jseldess** [comment]
___
*[v20.1/known-limitations.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/docs/7118#-M537i_SAN7D8GRIUZ2F:-M537i_SAN7D8GRIUZ2G:b-tb9c9d) ([raw file](https://github.com/cockroachdb/docs/blob/ce25c3ff0e96458157560fa5c0c484fa97ae63c6/v20.1/known-limitations.md#L78)):*
> ```Markdown
> ## Unresolved limitations
> 
> ### Enterprise `BACKUP` does not capture database/table/column comments
> ```

@knz, PTAL.

**Comment by jseldess** [comment]
___
*[v20.1/known-limitations.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/7118#-M5384f_2YfN1SMa4A0z:-M5384f_2YfN1SMa4A1-:b-tb9c9d) ([raw file](https://github.com/cockroachdb/docs/blob/ce25c3ff0e96458157560fa5c0c484fa97ae63c6/v20.1/known-limitations.md#L11)):*
> ```Markdown
> ## New limitations
> 
> ### `ROLLBACK TO SAVEPOINT` in high-priority transactions containing DDL
> ```

@knz, PTAL.

**Comment by jseldess** [comment]
___
*[v20.1/known-limitations.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/7118#-M53896G2GZ3Snuxg10n:-M53896G2GZ3Snuxg10o:b-hybdvz) ([raw file](https://github.com/cockroachdb/docs/blob/ce25c3ff0e96458157560fa5c0c484fa97ae63c6/v20.1/known-limitations.md#L28)):*
> ```Markdown
> [Tracking Github Issue](https://github.com/cockroachdb/cockroach/issues/46414)
> 
> ### Column name from an outer column inside a subquery differs from PostgreSQL
> ```

@raduberinde, PTAL.

**Comment by jseldess** [comment]
___
*[v20.1/known-limitations.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/7118#-M538I-y74kRozcKZYJL:-M538I-y74kRozcKZYJM:b-tb9c9d) ([raw file](https://github.com/cockroachdb/docs/blob/ce25c3ff0e96458157560fa5c0c484fa97ae63c6/v20.1/known-limitations.md#L54)):*
> ```Markdown
> [Tracking Github Issue](https://github.com/cockroachdb/cockroach/issues/46563)
> 
> ### Privileges required to access to certain virtual tables differs from PostgreSQL
> ```

@knz, PTAL.

**Comment by RaduBerinde** [comment]
___
*[v20.1/known-limitations.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/7118#-M53896G2GZ3Snuxg10n:-M58DV3eA-QwiJyzd-Pd:b-qbxl94) ([raw file](https://github.com/cockroachdb/docs/blob/ce25c3ff0e96458157560fa5c0c484fa97ae63c6/v20.1/known-limitations.md#L28)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

@raduberinde, PTAL.
</blockquote></details>

Looks great, thanks!

**Pull request merged**
