### PR TITLE
add v22.1.1 release notes

### PR DESCRIPTION
**Pull request by taroface**
Fixes DOC-2248.

### CODE REVIEW

**Review by MichaelTrestman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @MichaelTrestman and @taroface)

___
*[`_includes/releases/v22.1/v22.1.1.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3amB5t-RJe6fuHvEVg:-N3amB5t-RJe6fuHvEVh:byqhp2y) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L13)):*
> ```Markdown
> <h3 id="v22-1-1-general-changes">General changes</h3>
> 
> - When using Azure Storage for data operations, CockroachDB now calculates the storage account URL from the provided `AZURE_ENVIRONMENT` query parameter. If not specified, this defaults to `AzurePublicCloud` to maintain backward compatibility. This parameter should **not** be used when the cluster is in a mixed-version or upgrading state, as nodes that have not been upgraded will continue to send requests to `AzurePublicCloud` even in the presence of this parameter. [#80801][#80801]
> ```

A link or something for context would be helpful for those who, like me, have no idea what this is or what kind of CLI command or whatever this would be for. Query parameter on what?
___
*[`_includes/releases/v22.1/v22.1.1.md` line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3amq_N5QJkPG8vLbm-:-N3amq_N5QJkPG8vLbm0:b-qfft3k) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L22)):*
> ```Markdown
> <h3 id="v22-1-1-sql-language-changes">SQL language changes</h3>
> 
> - `ttl_job_cron` is now displayed on [`SHOW CREATE TABLE`](../v22.1/show-create.html) and `reloptions` by default. [#80292][#80292]
> ```

what's a reloption? Searching our docs for `reloptions` doesn't return anything. I guess it's a PostgreSQL thing? Maybe we don't need to clarify then, but this sentence sure is baffling to me.
___
*[`_includes/releases/v22.1/v22.1.1.md` line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3angQJ1_oib4s2ppWq:-N3angQJ1_oib4s2ppWr:b-6958st) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L24)):*
> ```Markdown
> - `ttl_job_cron` is now displayed on [`SHOW CREATE TABLE`](../v22.1/show-create.html) and `reloptions` by default. [#80292][#80292]
> - Added the `crdb_internal.cluster_locks` virtual table, which exposes the current state of locks on keys tracked by concurrency control. The virtual table displays metadata on locks currently held by transactions, as well as operations waiting to obtain the locks, and as such can be used to visualize active contention. The `VIEWACTIVITY` or `VIEWACTIVITYREDACTED` [role option](../v22.1/security-reference/authorization.html#role-options), or the [`admin` role](../v22.1/security-reference/authorization.html#admin-role), is required to access the virtual table; however, if the user only has the `VIEWACTIVITYREDACTED` role option, the key on which a lock is held will be redacted. [#80517][#80517]
> - [`BACKUP`](../v22.1/backup.html), [`IMPORT`](../v22.1/import.html), and [`RESTORE`](../v22.1/restore.html) jobs will be paused instead of entering a failed state if they continue to encounter transient errors once they have retried a maximum number of times. The user is responsible for cancelling or resuming the job from this state. [#80434][#80434]
> ```

Wow, this 'pause instead of fail' sounds to me like a pretty major behavior change that should be flagged elsewhere in the docs. That seems like it could easily become catastrophic if it caught you unaware.
Are there tickets to put warn callouts in the right place? @mikecrl     thoughts?

**Comment by MichaelTrestman** [comment]
*[`_includes/releases/v22.1/v22.1.1.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3aqKLO071wilftjXGq:-N3aqKLO071wilftjXGr:b-i9vkmf) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L42)):*
> ```Markdown
> 
> - The standalone SQL shell executable `cockroach-sql` can now be installed (renamed/symlinked) as `cockroach`, and invoked via `cockroach sql`. For example, the following commands are all equivalent: `cockroach-sql -f foo.sql`, `cockroach-sql sql -f foo.sql`; and after running `ln -s cockroach-sql cockroach`, `cockroach sql -f foo.sql`. [#80930][#80930]
> - Added a new flag `--advertise-http-addr` for setting the HTTP advertise address explicitly. Previously, this address was derived from the OS hostname, the `--advertise-addr`, and the `--http-addr` flags, in that order. The new logic will override the HTTP advertise host with the host from `--advertise-addr` first if set, and then the host from `--http-addr`. The port will **never** be inherited from `--advertise-host` and will only be inherited from `--http-addr`, which is `8080` by default. The HTTP advertise address is used to report the DB Console address to access on a cluster and by nodes to proxy HTTP connections as described in #73285. It may be necessary to set this flag in order for that feature to work correctly in some deployments. [#81316][#81316]
> ```

This sentence is pretty confusing. I'm not 100% sure how to even parse it. I think like this:
"The HTTP advertise address is used both a) to report the DB Console address to access on a cluster, and b) by nodes to proxy HTTP connections as described in #7328"
But that's still pretty garbled.
Not really sure what this even is trying to say so I'd be kind of guessing to try to clarify. Maybe ask the author for clarification, if you think it's worth it?



_Code quote:_
```Markdown
The HTTP advertise address is used to report the DB Console address to access on a cluster and by nodes to proxy HTTP connections as described in #7328
```

**Review by MichaelTrestman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @MichaelTrestman and @taroface)

___
*[`_includes/releases/v22.1/v22.1.1.md` line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3arU1e3hFUl6-_iX2X:-N3arU1e3hFUl6-_iX2Y:b9kz9ot) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L43)):*
> ```Markdown
> - The standalone SQL shell executable `cockroach-sql` can now be installed (renamed/symlinked) as `cockroach`, and invoked via `cockroach sql`. For example, the following commands are all equivalent: `cockroach-sql -f foo.sql`, `cockroach-sql sql -f foo.sql`; and after running `ln -s cockroach-sql cockroach`, `cockroach sql -f foo.sql`. [#80930][#80930]
> - Added a new flag `--advertise-http-addr` for setting the HTTP advertise address explicitly. Previously, this address was derived from the OS hostname, the `--advertise-addr`, and the `--http-addr` flags, in that order. The new logic will override the HTTP advertise host with the host from `--advertise-addr` first if set, and then the host from `--http-addr`. The port will **never** be inherited from `--advertise-host` and will only be inherited from `--http-addr`, which is `8080` by default. The HTTP advertise address is used to report the DB Console address to access on a cluster and by nodes to proxy HTTP connections as described in #73285. It may be necessary to set this flag in order for that feature to work correctly in some deployments. [#81316][#81316]
> - If [node decommissioning](../v22.1/node-shutdown.html?filters=decommission) is slow or stalls, the descriptions of some "stuck" replicas are now printed to the operator. [#79516][#79516]
> ```

Some "stuck" replicas? Which ones, just a random selection? Not sure if this is just a strange wording or if there's some logic here that would be worth explicating.
___
*[`_includes/releases/v22.1/v22.1.1.md` line 44 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3arnf9EyY79KGEW1qg:-N3arnf9EyY79KGEW1qh:b-he3bfq) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L44)):*
> ```Markdown
> - Added a new flag `--advertise-http-addr` for setting the HTTP advertise address explicitly. Previously, this address was derived from the OS hostname, the `--advertise-addr`, and the `--http-addr` flags, in that order. The new logic will override the HTTP advertise host with the host from `--advertise-addr` first if set, and then the host from `--http-addr`. The port will **never** be inherited from `--advertise-host` and will only be inherited from `--http-addr`, which is `8080` by default. The HTTP advertise address is used to report the DB Console address to access on a cluster and by nodes to proxy HTTP connections as described in #73285. It may be necessary to set this flag in order for that feature to work correctly in some deployments. [#81316][#81316]
> - If [node decommissioning](../v22.1/node-shutdown.html?filters=decommission) is slow or stalls, the descriptions of some "stuck" replicas are now printed to the operator. [#79516][#79516]
> - [`cockroach debug zip`](../v22.1/cockroach-debug-zip.html) now includes all system tables by default, except for a few, using a denylist instead of an allowlist. [#81383][#81383]
> ```

Just a few random ones.... Maybe worth saying which? Or does this mean only expliticly denylisted ones or are there some excluded by default. This is ambiguous.

**Comment by MichaelTrestman** [comment]
Just a few minor suggestions, otherwise LGTM!

**Comment by taroface** [comment]
TFTR!

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kathancox, @MichaelTrestman, @mikeCRL, and @taroface)

___
*[`_includes/releases/v22.1/v22.1.1.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3amB5t-RJe6fuHvEVg:-N3tX6dA4tAiwPUdrijO:b2v2d3k) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L13)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

A link or something for context would be helpful for those who, like me, have no idea what this is or what kind of CLI command or whatever this would be for. Query parameter on what?
</blockquote></details>

I'm hesitant to link to external docs as they become stale. I think the link to the PR here can suffice - there are full usage details there. A "query parameter" is usually passed in an HTTP request and I think this will be apparent to people who are using Azure Storage.
___
*[`_includes/releases/v22.1/v22.1.1.md` line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3amq_N5QJkPG8vLbm-:-N3tffY-B7awvq-MReFs:b4oockn) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L22)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

what's a reloption? Searching our docs for `reloptions` doesn't return anything. I guess it's a PostgreSQL thing? Maybe we don't need to clarify then, but this sentence sure is baffling to me.
</blockquote></details>

Agree; I tweaked a bit to clarify.
___
*[`_includes/releases/v22.1/v22.1.1.md` line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3angQJ1_oib4s2ppWq:-N3tfq5u3Hvz2H8ykc-q:by98xyz) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L24)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Wow, this 'pause instead of fail' sounds to me like a pretty major behavior change that should be flagged elsewhere in the docs. That seems like it could easily become catastrophic if it caught you unaware.
Are there tickets to put warn callouts in the right place? @mikecrl     thoughts?
</blockquote></details>

Also cc @kathancox on this question!
___
*[`_includes/releases/v22.1/v22.1.1.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3aqKLO071wilftjXGq:-N3tinON2KJnvbthuIIZ:b305ki9) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L42)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

This sentence is pretty confusing. I'm not 100% sure how to even parse it. I think like this:
"The HTTP advertise address is used both a) to report the DB Console address to access on a cluster, and b) by nodes to proxy HTTP connections as described in #7328"
But that's still pretty garbled.
Not really sure what this even is trying to say so I'd be kind of guessing to try to clarify. Maybe ask the author for clarification, if you think it's worth it?
</blockquote></details>

I agree. @dhartunian can you help out on the sentence quoted above?
___
*[`_includes/releases/v22.1/v22.1.1.md` line 44 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3arnf9EyY79KGEW1qg:-N3tjsBW0tQJP5T5yrPN:b4ebw98) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L44)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Just a few random ones.... Maybe worth saying which? Or does this mean only expliticly denylisted ones or are there some excluded by default. This is ambiguous.
</blockquote></details>

Clarified the wording!

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kathancox, @MichaelTrestman, @mikeCRL, and @taroface)

___
*[`_includes/releases/v22.1/v22.1.1.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3aqKLO071wilftjXGq:-N3tlrhm5QqSzcUSzt_F:bcpcdtv) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L42)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I agree. @dhartunian can you help out on the sentence quoted above?
</blockquote></details>

Sorry for the confusion, hopefully this can clarify the problematic sentence quoted above:

a) This HTTP advertise addr is output when starting a new cluster. we give feedback to the user on what URL to use for DB Console (the `webui` row below):
```
CockroachDB node starting at 2022-06-06 16:10:36.327494 +0000 UTC (took 2.1s)
build:               CCL v21.2.6 @ 2022/02/22 18:33:27 (go1.16.6)
webui:               http://crlMBP.local:8080
sql:                 postgresql://root@crlMBP.local:26257/defaultdb?sslmode=disable
sql (JDBC):          jdbc:postgresql://crlMBP.local:26257/defaultdb?sslmode=disable&user=root
RPC client flags:    cockroach <client cmd> --host=crlMBP.local:26257 --insecure
logs:                /Users/david/go/src/github.com/cockroachlabs/managed-service/cockroach-data/logs
temp dir:            /Users/david/go/src/github.com/cockroachlabs/managed-service/cockroach-data/cockroach-temp703529071
external I/O path:   /Users/david/go/src/github.com/cockroachlabs/managed-service/cockroach-data/extern
store[0]:            path=/Users/david/go/src/github.com/cockroachlabs/managed-service/cockroach-data
storage engine:      pebble
status:              restarted pre-existing node
clusterID:           a5029b3f-7480-4fcd-bbb4-2e0cf8d90a84
nodeID:              1
```

b) The proxy feature allows nodes to route HTTP connections to each other and enables users to access "node M's" DB console from "node N". Sometimes, setting the advertise addr is necessary for nodes to be able to reach each other over HTTP. Previously, customers had no direct control over this address. 

Let me know if this helps, I can also clarify further.

**Comment by mikeCRL** [comment]
*[`_includes/releases/v22.1/v22.1.1.md` line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/14015#-N3angQJ1_oib4s2ppWq:-N40MH8q9NfyFRLsEYEV:btp66au) ([raw file](https://github.com/cockroachdb/docs/blob/3e2ee081887306710653b7e53e7b35e9845a735e/_includes/releases/v22.1/v22.1.1.md#L24)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Also cc @kathancox on this question!
</blockquote></details>

Thanks for flagging, @michaeltrestman. From the description here https://github.com/cockroachdb/cockroach/pull/80434 it looks like a sheer improvement to cases of backups that would have previously failed outright, but I think it's safe to assume that we'll need doc coverage. @kathancox has an issue for this in the July sprint: https://cockroachlabs.atlassian.net/browse/DOC-3506. I defer to her and PM for prioritization.

**Pull request merged**
