### PR TITLE
Update leaseholder information in Dist Layer docs

### LINKED ISSUE #10576: Distribution Layer in Architecture makes incorrect claims about leaseholder info in range descriptors
Throughout https://www.cockroachlabs.com/docs/v20.2/architecture/distribution-layer.html, we make reference to information about a range's leaseholder being stored in meta ranges. For instance, we say that the meta range KV structure includes leaseholder information and that leaseholder changes require an update to a range's descriptor.

This is inaccurate. Leaseholder state is local to a range and is not stored outside of the range or in the range's descriptor. As a result, changes to a range's leaseholder do not result in updates to its range descriptor.

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #10576.

Summary of changes (all to the 'Distribution Layer' page):

- Update descriptions of the meta range lookup process in "Using the
  monolithic sorted map"

- Revise description of `DistSender` operation to punt out the meta key
  lookup description to the section mentioned above, and remove mentions
  of the leaseholder being in the cache, etc.

- Various small edits to remove mention of how the range descriptor was
  updated when the range's leaseholder changed (which it doesn't anymore
  apparently)

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey Nathan,

I took a shot at some edits based on reading around in 

- `dist_sender.go`
- `range_cache.go`
- `range_lookup.go`

etc.  However it's likely I was not able to put everything together based on just reading the code, so I would appreciate any feedback/corrections you may offer.  Thanks!

**Review by nvanbenschoten — COMMENTED** [review]
This looks great! I just have one minor comment.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802#-:-MdZEKSP4b1qfxX01FNn:b-6xthv2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/architecture/distribution-layer.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10802#-MdZD-iX0-dsIoFElIYw:-MdZD-iX0-dsIoFElIYx:b-c1utt8) ([raw file](https://github.com/cockroachdb/docs/blob/7681366a1760932ecc725e12f58edeb61ef9a17d/v21.1/architecture/distribution-layer.md#L51)):*
> ```Markdown
> ### Using the monolithic sorted map
> 
> When a node receives a request, it looks up the location of the range(s) that include the keys in the request.  For each key, it looks up the specified key in the first level of range metadata (`meta1`), which returns the location of the key within the second level of range metadata (`meta2`).  The second level of metadata is then queried to retrieve the location of the range where the key's value resides.
> ```

This is close, but the order of operations is actually inverted. The request looks up the location of the range where the key's value resides in meta2 first. If this hits the cache, all good. If not, it looks up the location of the range where meta2's value (the key's descriptor) resides. If this hits the cache, we retrieve the descriptor from meta using an RPC. If this misses, we look up the location of the range where meta1's value (meta2's descriptor) resides. This always hits because this location is gossiped, and so in this case we retrieve the meta2 descriptor from meta1 using an RPC.

It's a bit mind-bending because this is all recursive.
___
*[v21.1/architecture/distribution-layer.md, line 93 at r1](https://reviewable.io/reviews/cockroachdb/docs/10802#-MdZE4stCph5NLy4xt1H:-MdZE4su9Gol6BfmjZ47:blgzemf) ([raw file](https://github.com/cockroachdb/docs/blob/7681366a1760932ecc725e12f58edeb61ef9a17d/v21.1/architecture/distribution-layer.md#L93)):*
> ```Markdown
> 
> ~~~
> metaX/successorKey -> [list of other nodes containing data]
> ```

~other~

**Review by rmloveland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rmloveland)

___
*[v21.1/architecture/distribution-layer.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10802#-MdZD-iX0-dsIoFElIYw:-Me1pqNu4AJsCmeuDWsd:b48o0me) ([raw file](https://github.com/cockroachdb/docs/blob/7681366a1760932ecc725e12f58edeb61ef9a17d/v21.1/architecture/distribution-layer.md#L51)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is close, but the order of operations is actually inverted. The request looks up the location of the range where the key's value resides in meta2 first. If this hits the cache, all good. If not, it looks up the location of the range where meta2's value (the key's descriptor) resides. If this hits the cache, we retrieve the descriptor from meta using an RPC. If this misses, we look up the location of the range where meta1's value (meta2's descriptor) resides. This always hits because this location is gossiped, and so in this case we retrieve the meta2 descriptor from meta1 using an RPC.

It's a bit mind-bending because this is all recursive.
</blockquote></details>

Thanks for explaining this.  I used a combination of your note here and some of the comments in `range_lookup.go` to hopefully get this text closer to reality.  I also added a little ASCII tree diagram to the *Meta ranges* section similar to the one in the comments of `range_lookup.go` file to make the tree structure easier to visualize.

Please let me know what you think!  Happy to make further changes.

(Also- once this is in shape, would all of this info apply to v20.2 also?  if so I will port it over there as well once this is OK)

**Review by rmloveland — COMMENTED** [review]
thanks for the review Nathan!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802#-:-MeQNa5466YQGiRL31DD:bdeq98k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[v21.1/architecture/distribution-layer.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10802#-MdZD-iX0-dsIoFElIYw:-MeQNHzn2UggsYVriY_I:bcagkqc) ([raw file](https://github.com/cockroachdb/docs/blob/7681366a1760932ecc725e12f58edeb61ef9a17d/v21.1/architecture/distribution-layer.md#L51)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks great!

> once this is in shape, would all of this info apply to v20.2 also? if so I will port it over there as well once this is OK

:thumbsup: this has been the same for years. You could backport as far as you like.
</blockquote></details>

yay thanks!

OK, once this is reviewed by a docs person I will add it to the older docs as well

**Review by taroface — CHANGES_REQUESTED** [review]
One blocking request (the diagram looks broken in the preview link), and some suggestions for adding some conceptual clarity (hopefully not just for me)!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802#-:-MeRVqNq6CIi_srLuszR:b-efi79z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rmloveland)

___
*[v21.1/architecture/distribution-layer.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRRqO367UaM-wmBv_y:-MeRRqO367UaM-wmBv_z:b-1barhm) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L51)):*
> ```
> ▲                                       │
> ```

Just checking. Should the up arrow be there on the left?
___
*[v21.1/architecture/distribution-layer.md, line 57 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRRlR7Ephm3jTw7RZB:-MeRRlR7Ephm3jTw7RZC:bwegdxq) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L57)):*
> ```
> ▼             │
> ```

Should that character on the right be a downward arrow?
___
*[v21.1/architecture/distribution-layer.md, line 62 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRA4nU0Kq019N1szvx:-MeRA4nU0Kq019N1szvy:bskxz2t) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L62)):*
> ```Markdown
> └──────┘      └──────┘                 └──────┘        └────────┘
> ~~~
> ```

This is awesome! But the code block isn't rendering correctly for me (Firefox):



Along with our docs discussion today, I'm inclined to prefer a PNG with alt-text here. What do you think?
___
*[v21.1/architecture/distribution-layer.md, line 85 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRANTU3y5ax6py3PNx:-MeRANTU3y5ax6py3PNy:b-g1h7x9) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L85)):*
> ```Markdown
> As described in the [meta ranges section](#meta-ranges), the locations of all the ranges in a cluster are stored in a two-level index:
> 
> - The first level (`meta1`) addresses the second level, and
> ```

Suggest striking `, and` and ending this as a sentence.
___
*[v21.1/architecture/distribution-layer.md, line 90 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRAgQ1CUg_XdMQ-sgl:-MeRAgQ1CUg_XdMQ-sgm:b-gak45k) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L90)):*
> ```Markdown
> This can also be visualized as a tree, with the root at `meta1`, the second level at `meta2`, and the leaves of the tree made up of the ranges that hold user data.
> 
> When a node receives a request, it looks up the location of the range(s) that include the keys in the request in a "bottom up" fashion, starting at the leaves of this tree.  This process works as follows:
> ```

`"bottom up"` -> `bottom-up` (without quotes) imo. However, this feels like a mixed metaphor here - I'd expect the "bottom" of the tree to be the root and not the leaves.

Separately, I'm confused how the process starts at the leaves, if the first step below states that the node starts looking at `meta2`. Maybe there's a small conceptual jump I missed?

Also, extra space between the last 2 sentences!
___
*[v21.1/architecture/distribution-layer.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRJqeR0KPesC7yrE4T:-MeRJqeS9jN1otHPHsLZ:bxi0kde) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L92)):*
> ```Markdown
> When a node receives a request, it looks up the location of the range(s) that include the keys in the request in a "bottom up" fashion, starting at the leaves of this tree.  This process works as follows:
> 
> 1. For each key, the node looks up the specified key in the second level of range metadata (`meta2`).  That information is cached for performance; if the range's location is found in the cache, it is returned immediately.
> ```

Extra space between these sentences.
___
*[v21.1/architecture/distribution-layer.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRUIcnBMwfUD0DhLVJ:-MeRUIcnBMwfUD0DhLVK:bwij1om) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L92)):*
> ```
> the node looks up the specified key
> ```

Judging from Nathan's comment above, should this be something like 

`the node looks up the location of the range containing the specified key` ?
___
*[v21.1/architecture/distribution-layer.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRJuGQArdGj8Z7IVgm:-MeRJuGQArdGj8Z7IVgn:bk0i24t) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L94)):*
> ```Markdown
> 1. For each key, the node looks up the specified key in the second level of range metadata (`meta2`).  That information is cached for performance; if the range's location is found in the cache, it is returned immediately.
> 
> 2. If the location is not found in the cache, the node looks up the location of the range where the actual value of `meta2` resides.  This information is also cached; if the location of the `meta2` range is found in the cache, the node sends an RPC to the `meta2` range to get the location of the keys the request wants to operate on, and returns that information.
> ```

Suggest: If the location -> If the range's location
___
*[v21.1/architecture/distribution-layer.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeROXxP64nfq9sjkU1i:-MeROXxP64nfq9sjkU1j:b-bfyemn) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L94)):*
> ```
> the location of the range where the actual value of `meta2` resides.
> ```

Having trouble parsing this, maybe due to the phrase "actual value of `meta2`". Is it worth reiterating that this value is the key's descriptor?
___
*[v21.1/architecture/distribution-layer.md, line 96 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRLrZCD3mvKhpm5Jtj:-MeRLrZCD3mvKhpm5Jtk:b-nwf8wq) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L96)):*
> ```Markdown
> 2. If the location is not found in the cache, the node looks up the location of the range where the actual value of `meta2` resides.  This information is also cached; if the location of the `meta2` range is found in the cache, the node sends an RPC to the `meta2` range to get the location of the keys the request wants to operate on, and returns that information.
> 
> 3. Finally, if the location of the `meta2` range is not found in the cache, the node looks up the location of the range where the actual value of the first level of range metadata (`meta1`) resides.  This lookup always succeeds because the location of `meta1` is distributed among all the nodes in the cluster using a gossip protocol.  The node then uses the information from `meta1` to look up the location of `meta2`, and from `meta2` it looks up the locations of the ranges that include the keys in the request.
> ```

Extra space between the last two sentences.

**Review by rmloveland — COMMENTED** [review]
Fixed the blocking thing (and hopefully addressed most of the others!)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802#-:-MeWN2aH1epZKpDPCRcw:b-a1xuo7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @taroface)

___
*[v21.1/architecture/distribution-layer.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRRqO367UaM-wmBv_y:-MeW22wK3rMia1WWFtdh:b-gh1uuy) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L51)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> ▲                                       │
> ```

Just checking. Should the up arrow be there on the left?
</blockquote></details>

Aha!  You are right, this one arrow is reversed.  In some sense, it doesn't matter if they are pointing up or down, but down is a little more comprehensible and in either case they should *definitely* all be pointing the same way.

Fixed, thanks!
___
*[v21.1/architecture/distribution-layer.md, line 57 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRRlR7Ephm3jTw7RZB:-MeW2HdD7ouzixEcSpwf:b-31oyc1) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L57)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> ▼             │
> ```

Should that character on the right be a downward arrow?
</blockquote></details>

I think this is fixed by the above
___
*[v21.1/architecture/distribution-layer.md, line 62 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRA4nU0Kq019N1szvx:-MeW2JyUBPGGBI2YEUea:b7lk10v) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L62)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This is awesome! But the code block isn't rendering correctly for me (Firefox):



Along with our docs discussion today, I'm inclined to prefer a PNG with alt-text here. What do you think?
</blockquote></details>

Went with a PNG with alt text!

(PS as the other remaining FF user (when not at work) I apologize! Guessing Monodraw developer does not use FF)
___
*[v21.1/architecture/distribution-layer.md, line 85 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRANTU3y5ax6py3PNx:-MeW2xdiD6GWr81zg8yd:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L85)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest striking `, and` and ending this as a sentence.
</blockquote></details>

Done!
___
*[v21.1/architecture/distribution-layer.md, line 90 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRAgQ1CUg_XdMQ-sgl:-MeW38GB1Y_aG53n7Ali:bp2pwcq) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L90)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

`"bottom up"` -> `bottom-up` (without quotes) imo. However, this feels like a mixed metaphor here - I'd expect the "bottom" of the tree to be the root and not the leaves.

Separately, I'm confused how the process starts at the leaves, if the first step below states that the node starts looking at `meta2`. Maybe there's a small conceptual jump I missed?

Also, extra space between the last 2 sentences!
</blockquote></details>

Fixed to say bottom-up

Re: how it starts at the leaves, that is a good question.  I'm not sure the phrase "starting at the leaves" is necessary, since "bottom-up" is already doing some work here.  But I do think it's useful for getting a general picture in one's head. I guess my answer would be that given a set of keys, we need to look "up" the tree at what's in meta2, so in some sense we are at the leaves.  Although I guess in some other sense we are really saying "hey meta2, where are the leaves located?"  which implies we are not actually starting at the leaves.  A case for leaving it in despite its fuzziness (haha see what I did there) is I think it helps to emphasize the bottom-up nature of the process in practice, even though it may be slightly "off" from a strict "the hip bone's connected to the thigh bone" POV.

Re: spacing, all fixed (here and elsewhere in this doc).

(Although I still stand by the two space rule in my private life, I accept that a random MS Word PM in the 1980s was able to change public opinion on this.)
___
*[v21.1/architecture/distribution-layer.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRJqeR0KPesC7yrE4T:-MeW3fpL6g7TYWJWFBTs:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L92)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra space between these sentences.
</blockquote></details>

Fixed!
___
*[v21.1/architecture/distribution-layer.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRUIcnBMwfUD0DhLVJ:-MeW9mfO90uC_m6TVUba:bavytpj) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L92)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> the node looks up the specified key
> ```

Judging from Nathan's comment above, should this be something like 

`the node looks up the location of the range containing the specified key` ?
</blockquote></details>

Works for me - updated!
___
*[v21.1/architecture/distribution-layer.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRJuGQArdGj8Z7IVgm:-MeW9q_v5kVbJaxrekZ5:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L94)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest: If the location -> If the range's location
</blockquote></details>

Done!
___
*[v21.1/architecture/distribution-layer.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeROXxP64nfq9sjkU1i:-MeW9ruIEX8oCf2Nrp1K:b-krun90) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L94)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> the location of the range where the actual value of `meta2` resides.
> ```

Having trouble parsing this, maybe due to the phrase "actual value of `meta2`". Is it worth reiterating that this value is the key's descriptor?
</blockquote></details>

I guess I meant it in the sense of "the value is cached, but if the cache is out of date, we have to compute/lookup the actual value".  I'm sort of torn about saying "descriptor" because while technically correct it is also kind of an interruption/dictionary term that one has to go look up and learn and internalize
___
*[v21.1/architecture/distribution-layer.md, line 96 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRLrZCD3mvKhpm5Jtj:-MeWAqab-Z3O1qmqCGG1:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L96)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Extra space between the last two sentences.
</blockquote></details>

Fixed!

**Review by taroface — APPROVED** [review]
LGTM, just a suggestion on the leaves thing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802#-:-MeacgTU23SYLO9wLdDt:b-7qo5nn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @rmloveland, and @taroface)

___
*[v21.1/architecture/distribution-layer.md, line 90 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRAgQ1CUg_XdMQ-sgl:-Meabiy-0XUhT2I7kfcD:bdiv4wv) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L90)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Fixed to say bottom-up

Re: how it starts at the leaves, that is a good question.  I'm not sure the phrase "starting at the leaves" is necessary, since "bottom-up" is already doing some work here.  But I do think it's useful for getting a general picture in one's head. I guess my answer would be that given a set of keys, we need to look "up" the tree at what's in meta2, so in some sense we are at the leaves.  Although I guess in some other sense we are really saying "hey meta2, where are the leaves located?"  which implies we are not actually starting at the leaves.  A case for leaving it in despite its fuzziness (haha see what I did there) is I think it helps to emphasize the bottom-up nature of the process in practice, even though it may be slightly "off" from a strict "the hip bone's connected to the thigh bone" POV.

Re: spacing, all fixed (here and elsewhere in this doc).

(Although I still stand by the two space rule in my private life, I accept that a random MS Word PM in the 1980s was able to change public opinion on this.)
</blockquote></details>

Yep, I see your point about emphasizing the bottom-up direction with the leaves. I wonder if "starting with the leaves" would convey this better, since "at" places weight on the location of the process, whereas "with" is more about the subject (keys).
___
*[v21.1/architecture/distribution-layer.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeROXxP64nfq9sjkU1i:-Meacdto-A1r2un045oZ:b-4hvi0z) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L94)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I guess I meant it in the sense of "the value is cached, but if the cache is out of date, we have to compute/lookup the actual value".  I'm sort of torn about saying "descriptor" because while technically correct it is also kind of an interruption/dictionary term that one has to go look up and learn and internalize
</blockquote></details>

Got it!

**Review by rmloveland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10802)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @rmloveland, and @taroface)

___
*[v21.1/architecture/distribution-layer.md, line 90 at r2](https://reviewable.io/reviews/cockroachdb/docs/10802#-MeRAgQ1CUg_XdMQ-sgl:-MefrjCh9BLFUHrvSEaR:b-ykonb3) ([raw file](https://github.com/cockroachdb/docs/blob/da6784a1454b4c45236b6fdb02b8f95232232582/v21.1/architecture/distribution-layer.md#L90)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Yep, I see your point about emphasizing the bottom-up direction with the leaves. I wonder if "starting with the leaves" would convey this better, since "at" places weight on the location of the process, whereas "with" is more about the subject (keys).
</blockquote></details>

Went "with" that (hehe)

**Pull request merged**
