### PR TITLE
SCRAM doesn't work with Looker/Google Data Studio

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-6660

### CODE REVIEW

**Comment by rmloveland** [comment]
@dikshant pls let me know if there is some more context to add here, like ISTR you had mentioned a forum link or something?

**Comment by dikshant** [comment]
@rmloveland This is the issue on Google's side:
https://issuetracker.google.com/issues/203573707
We could link to it I suppose.

**Review by dikshant — APPROVED** [review]
LGTM, we can add the link to the issue on Google's side as well.

**Comment by rmloveland** [comment]
> LGTM, we can add the link to the issue on Google's side as well.

Thanks Dikshant!  Added link in latest push.  Now sending on for Docs team review

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
