### PR TITLE
ARM on Linux and Docker is GA for 23.1.16

### PR DESCRIPTION
**Pull request by mdlinville**
ARM on Linux and Docker is GA for 23.1.16

Relates to https://github.com/cockroachdb/ed-tools/pull/54 which updates the release-note script defaults
Ref: [DOC-8595] 

### Previews
https://deploy-preview-18330--cockroachdb-docs.netlify.app/docs/releases/#v23-1
https://deploy-preview-18330--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-16

### CODE REVIEW

**Comment by rmloveland** [comment]
@mdlinville is there a Jira we can point to as proof that these are GA for v23.1.16?  for future reference?

**Review by rmloveland — APPROVED** [review]
I'd really like to have a link to a Jira or something that can be the reference for "ARM is GA for version XX.YY"

otherwise LGTM

**Comment by mdlinville** [comment]
> I'd really like to have a link to a Jira or something that can be the reference for "ARM is GA for version XX.YY"
> 
> otherwise LGTM

We discussed offline, but ARM was GA in 23.1.14: https://github.com/cockroachdb/docs/pull/18196 This is just a papercut due to a tooling miss on my part.

**Comment by rmloveland** [comment]
@mdlinville followed up with me via another channel and we have this info in Jira, this PR is fixing a paper cut in our infra - thanks Matt!

**Pull request merged**
