### PR TITLE
Fix commands overview title in nav bar and page.

### PR DESCRIPTION
**Pull request by stbof**

### CODE REVIEW

**Comment by MichaelTrestman** [comment]
___
*[v22.1/cockroach-commands.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13281#-MyP1ruG55DZ6mDRjFL5:-MyP1ruG55DZ6mDRjFL6:b-dsq0fg) ([raw file](https://github.com/cockroachdb/docs/blob/a2211172d5e4ef95261572c8e6ea5b366b4390fe/v22.1/cockroach-commands.md#L2)):*
> ```Markdown
> ---
> title: cockroach Commands Overview
> ```

So... I get that this is lowercase because it's supposed to be code-formatted, but it can't be formatted because it's in a title.
But... it's lowercaseness here, I'm not sure the authorial intent for it be a doomed homage to code-format really lands, and it kind of just looks like a typo? So it might be better to just leave it capitalized. I could see doing that and still even leaving the side-bar handle as is, with the code format.
The page title could also be "CockroachDB CLI commands". 'cockroach', as in `cockroach sql...` is the file-handle of the executable that *is* the CockroachDB CLI, right?  So `cockroach` commands are CockroachDB CLI commands, nah?

By the same token, I rather dislike "This page introduces the `cockroach` commands for configuring, starting, and managing a CockroachDB cluster, as well as environment variables that can be used in place of certain flags."

It seems ungrammatical; I don't think English supports code interpolation that way. Code blocks make sense when we say "run `code`", or refer to like the `param` parameter, but in that sentence, seems to me it should say "...introduces the CockroachDB CLI commands..."

Just being real nit-picky here.

**Review by MichaelTrestman — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @MichaelTrestman and @stbof)

**Comment by stbof** [comment]
> _[v22.1/cockroach-commands.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13281#-MyP1ruG55DZ6mDRjFL5:-MyP1ruG55DZ6mDRjFL6:b-dsq0fg) ([raw file](https://github.com/cockroachdb/docs/blob/a2211172d5e4ef95261572c8e6ea5b366b4390fe/v22.1/cockroach-commands.md#L2)):_
> 
> > ```gfm
> > ---
> > title: cockroach Commands Overview
> > ```
> 
> So... I get that this is lowercase because it's supposed to be code-formatted, but it can't be formatted because it's in a title. But... it's lowercaseness here, I'm not sure the authorial intent for it be a doomed homage to code-format really lands, and it kind of just looks like a typo? So it might be better to just leave it capitalized. I could see doing that and still even leaving the side-bar handle as is, with the code format. The page title could also be "CockroachDB CLI commands". 'cockroach', as in `cockroach sql...` is the file-handle of the executable that _is_ the CockroachDB CLI, right? So `cockroach` commands are CockroachDB CLI commands, nah?

We need an Overview page to distinguish it from the folder `cockroach` Commands containing the individual pages and Overview is pretty much our convention for these types of pages. 

I think we have to live with the fact that we can't put code-format `cockroach` in the title.

The page title should match the nav bar title.  

> 
> By the same token, I rather dislike "This page introduces the `cockroach` commands for configuring, starting, and managing a CockroachDB cluster, as well as environment variables that can be used in place of certain flags."
> 
> It seems ungrammatical; I don't think English supports code interpolation that way. Code blocks make sense when we say "run `code`", or refer to like the `param` parameter, but in that sentence, seems to me it should say "...introduces the CockroachDB CLI commands..."
> 
> Just being real nit-picky here.

This PR isn't about the page contents, it's  only about the titles in the nav bar and page.

**Review by MichaelTrestman — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stbof)

___
*[v22.1/cockroach-commands.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13281#-MyP1ruG55DZ6mDRjFL5:-MyQnHVSEnVgPk4jH0rg:b-a1h38m) ([raw file](https://github.com/cockroachdb/docs/blob/a2211172d5e4ef95261572c8e6ea5b366b4390fe/v22.1/cockroach-commands.md#L2)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

> > ```gfm
> > ---
> > title: cockroach Commands Overview
> > ```
> > 

> 
> So... I get that this is lowercase because it's supposed to be code-formatted, but it can't be formatted because it's in a title. But... it's lowercaseness here, I'm not sure the authorial intent for it be a doomed homage to code-format really lands, and it kind of just looks like a typo? So it might be better to just leave it capitalized. I could see doing that and still even leaving the side-bar handle as is, with the code format. The page title could also be "CockroachDB CLI commands". 'cockroach', as in `cockroach sql...` is the file-handle of the executable that _is_ the CockroachDB CLI, right? So `cockroach` commands are CockroachDB CLI commands, nah?
> 

We need an Overview page to distinguish it from the folder `cockroach` Commands containing the individual pages and Overview is pretty much our convention for these types of pages. 

I think we have to live with the fact that we can't code-format `cockroach` in the title.

The page title should match the nav bar title.  


> 
> By the same token, I rather dislike "This page introduces the `cockroach` commands for configuring, starting, and managing a CockroachDB cluster, as well as environment variables that can be used in place of certain flags."
> 
> It seems ungrammatical; I don't think English supports code interpolation that way. Code blocks make sense when we say "run `code`", or refer to like the `param` parameter, but in that sentence, seems to me it should say "...introduces the CockroachDB CLI commands..."
> 
> Just being real nit-picky here.
> 

This PR isn't about the page contents, it's  only about the titles in the nav bar and page. 

I'm also not attempting to do a wholesale renaming a la CockroachDB CLI. Could we leave that to another Jira/PR?

</blockquote></details>

ok, lgtm then.

**Review by MichaelTrestman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13281#-:-MyQnWCgEBQQJzgI9R-X:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stbof)

**Pull request merged**
