### PR TITLE
inject_retry_errors_enabled session variable

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1212.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice example!

**Comment by ericharmeling** [comment]
@rafiss TFTR!

**Review by nickvigilante — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13397#-:-MzMIT-WCRXsj3mlmIE5:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Comment by ericharmeling** [comment]
TFTR @nickvigilante !

**Pull request merged**
