### PR TITLE
re-styling search form

### PR DESCRIPTION
**Pull request by jseldess**
Styled the search form to more closely resemble search on blog, and removed unused css.

@mjibson, @jess-edwards: Thoughts?

screen shot 2016-02-26 at 11 28 22 am

### CODE REVIEW

**Comment by mjibson** [comment]
LGTM

**Comment by jess-edwards** [comment]
Can you get a rounded box on the search bar? 

screen shot 2016-02-26 at 1 11 58 pm

**Comment by jseldess** [comment]
Rounded the corners, @jess-edwards. Look better?

screen shot 2016-02-26 at 1 17 40 pm

**Comment by jess-edwards** [comment]
LG*TM

*great!

**Pull request merged**
