### PR TITLE
Minimum Windows version for Windows binary

### LINKED ISSUE #1377: Windows binary requires Windows 8+
I believe (still waiting on confirmation) that the Windows binaries to fail for this user on the forum because they're running a version of Windows pre-8: https://forum.cockroachlabs.com/t/where-are-the-windows-binaries/602/4

We should document the minimum required Windows version wherever we link to the binaries.

@tamird, can you confirm? Seems to be a RocksDB issue? https://github.com/facebook/rocksdb/issues/726.

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1377

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1379)

### CODE REVIEW

**Comment by tamird** [comment]
Sorry for not seeing it before merging. I think this text is misleading in that it conflates "the Windows binary" with the source code which is what actually requires Windows 8+.

In other words, the current wording suggests that building from source might remove this requirement, but it would not.

**Comment by jseldess** [comment]
@tamird, "build from source" isn't even presented as an option on Windows, as it is on Mac and Linux. We only present either "download the binary" or "use docker". 

If we want to provide instructions for building from source on Windows, I'll need help understanding how the process differs. Feels unnecessary, though, given that Windows support is only experimental...

**Comment by benesch** [comment]
I suppose it could say "CockroachDB requires Windows 8 or later. Windows
support is experimental and has not been extensively tested by Cockroach
Labs. The binary is provided..."

The current wording doesn't bother me, though.

**Comment by tamird** [comment]
@jseldess I think it is naive to assume that users won't try something just because it isn't presented in the docs (we have seen a variety of platforms and even had folks try ARMv8, after all).

I also appreciate that we don't necessarily want to consider those users when writing our docs, since they're off in uncharted territory, yet I find that the language here is imprecise and that making  it precise could be achieved without making it more pedantic or convoluted.

Would you accept a PR with such rewording? I'd be happy to take the task.

**Comment by jseldess** [comment]
Of course, @tamird. Thanks for offering.

**Pull request merged**
