### PR TITLE
Fix change "datacenter" to "availability zone" #5686

### LINKED ISSUE #5686: Change "datacenter" to "availability zone"
When talking about cloud topologies, we should say "availability zone" instead of "datacenter".

Docs that need to be changed:
- https://www.cockroachlabs.com/docs/dev/configure-replication-zones.html
- https://www.cockroachlabs.com/docs/dev/partitioning
- https://www.cockroachlabs.com/docs/v19.2/training/geo-partitioning.html
- etc.

### PR DESCRIPTION
**Pull request by Shiwanee**
Fixes #5686

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
Hi @shiwanee, thanks for working on this! I left a few comments for you to address. There are also some broken links now, can you fix those?

Here are the pages that the broken links are on, and the link that needs to be fixed:

```
/v20.2/configure-replication-zones.html --> #per-replica-constraints-to-specific-availability%20zones
/v20.2/demo-automatic-cloud-migration.html --> configure-replication-zones.html#even-replication-across-datacenters
/v20.1/configure-replication-zones.html --> #per-replica-constraints-to-specific-availability%20zones
/v20.1/demo-automatic-cloud-migration.html --> configure-replication-zones.html#even-replication-across-datacenters
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8765#-:-MKkM9x49M47qXI70MPq:bqfyi6o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Shiwanee)

___
*[v20.1/cockroach-start.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/8765#-MKkJyiw7P0TusxtrMk7:-MKkJyiw7P0TusxtrMk8:bncbn2t) ([raw file](https://github.com/cockroachdb/docs/blob/ebfedd8222d028c4fba40b85720b1b1d0cb9f96e/v20.1/cockroach-start.md#L60)):*
> ```Markdown
> `--external-io-dir` | The path of the external IO directory with which the local file access paths are prefixed while performing backup and restore operations using local node directories or NFS drives. If set to `disabled`, backups and restores using local node directories and NFS drives, as well as [`cockroach nodelocal upload`](cockroach-nodelocal-upload.html), are disabled.<br><br>**Default:** `extern` subdirectory of the first configured [`store`](#store).<br><br>To set the `--external-io-dir` flag to the locations you want to use without needing to restart nodes, create symlinks to the desired locations from within the `extern` directory.
> `--listening-url-file` | The file to which the node's SQL connection URL will be written as soon as the node is ready to accept connections, in addition to being printed to the [standard output](#standard-output). When `--background` is used, this happens before the process detaches from the terminal.<br><br>This is particularly helpful in identifying the node's port when an unused port is assigned automatically (`--port=0`).
> `--locality` | Arbitrary key-value pairs that describe the location of the node. Locality might include country, region, availability zone, rack, etc. For more details, see [Locality](#locality) below.
> ```

Can you remove `rack,` here? It doesn't make sense now.
___
*[v20.1/cockroach-start.md, line 99 at r1](https://reviewable.io/reviews/cockroachdb/docs/8765#-MKkK38V34MdZgvq00nG:-MKkK38V34MdZgvq00nH:bncbn2t) ([raw file](https://github.com/cockroachdb/docs/blob/ebfedd8222d028c4fba40b85720b1b1d0cb9f96e/v20.1/cockroach-start.md#L99)):*
> ```Markdown
> ### Locality
> 
> The `--locality` flag accepts arbitrary key-value pairs that describe the location of the node. Locality might include region, country, availability zone, rack, etc. The key-value pairs should be ordered into _locality tiers_ from most inclusive to least inclusive (e.g., region before availability zone as in `region=eu,zone=paris`), and the keys and order of key-value pairs must be the same on all nodes. It's typically better to include more pairs than fewer.
> ```

Can you remove `rack,` here? It doesn't make sense now.
___
*[v20.1/configure-replication-zones.md, line 101 at r1](https://reviewable.io/reviews/cockroachdb/docs/8765#-MKkK6ONDsqmcJMMfyrZ:-MKkK6ONDsqmcJMMfyr_:bncbn2t) ([raw file](https://github.com/cockroachdb/docs/blob/ebfedd8222d028c4fba40b85720b1b1d0cb9f96e/v20.1/configure-replication-zones.md#L101)):*
> ```Markdown
> Attribute Type | Description
> ---------------|------------
> **Node Locality** | <a name="zone-config-node-locality"></a> Using the [`--locality`](cockroach-start.html#locality) flag, you can assign arbitrary key-value pairs that describe the location of the node. Locality might include region, country, availability zone, rack, etc. The key-value pairs should be ordered into _locality tiers_ that range from most inclusive to least inclusive (e.g., region before availability zone as in `region=eu,az=paris`), and the keys and the order of key-value pairs must be the same on all nodes. It's typically better to include more pairs than fewer. For example:<br><br>`--locality=region=east,az=us-east-1`<br>`--locality=region=east,az=us-east-2`<br>`--locality=region=west,az=us-west-1`<br><br>CockroachDB attempts to spread replicas evenly across the cluster based on locality, with the order of locality tiers determining the priority. Locality can also be used to influence the location of data replicas in various ways using replication zones.<br><br>When there is high latency between nodes, CockroachDB uses locality to move range leases closer to the current workload, reducing network round trips and improving read performance. See [Follow-the-workload](topology-follow-the-workload.html) for more details.
> ```

Can you remove `rack,` here? It doesn't make sense now.
___
*[v20.2/cockroach-start.md, line 62 at r1](https://reviewable.io/reviews/cockroachdb/docs/8765#-MKkKIGD-z0c0br6VhtB:-MKkKIGD-z0c0br6VhtC:bncbn2t) ([raw file](https://github.com/cockroachdb/docs/blob/ebfedd8222d028c4fba40b85720b1b1d0cb9f96e/v20.2/cockroach-start.md#L62)):*
> ```Markdown
> `--external-io-dir` | The path of the external IO directory with which the local file access paths are prefixed while performing backup and restore operations using local node directories or NFS drives. If set to `disabled`, backups and restores using local node directories and NFS drives, as well as [`cockroach nodelocal upload`](cockroach-nodelocal-upload.html), are disabled.<br><br>**Default:** `extern` subdirectory of the first configured [`store`](#store).<br><br>To set the `--external-io-dir` flag to the locations you want to use without needing to restart nodes, create symlinks to the desired locations from within the `extern` directory.
> `--listening-url-file` | The file to which the node's SQL connection URL will be written as soon as the node is ready to accept connections, in addition to being printed to the [standard output](#standard-output). When `--background` is used, this happens before the process detaches from the terminal.<br><br>This is particularly helpful in identifying the node's port when an unused port is assigned automatically (`--port=0`).
> `--locality` | Arbitrary key-value pairs that describe the location of the node. Locality might include country, region, availability zone, rack, etc. For more details, see [Locality](#locality) below.
> ```

Can you remove `rack,` here? It doesn't make sense now.
___
*[v20.2/cockroach-start.md, line 101 at r1](https://reviewable.io/reviews/cockroachdb/docs/8765#-MKkKLcl0S2dLBsQHD1i:-MKkKLcl0S2dLBsQHD1j:b-lp0ou2) ([raw file](https://github.com/cockroachdb/docs/blob/ebfedd8222d028c4fba40b85720b1b1d0cb9f96e/v20.2/cockroach-start.md#L101)):*
> ```Markdown
> ### Locality
> 
> The `--locality` flag accepts arbitrary key-value pairs that describe the location of the node. Locality might include region, country, availability zone, rack, etc. The key-value pairs should be ordered into _locality tiers_ from most inclusive to least inclusive (e.g., region before availability zone as in `region=eu,dc=paris`), and the keys and order of key-value pairs must be the same on all nodes. It's typically better to include more pairs than fewer.
> ```

Can you remove `rack,` here? It doesn't make sense now.

Also, in the parenthetical, can you change `dc` to `zone` to match the updated language?
___
*[v20.2/configure-replication-zones.md, line 101 at r1](https://reviewable.io/reviews/cockroachdb/docs/8765#-MKkKlSZBXBxN5fk7P8u:-MKkKlS_6HNMDyXJ3FPu:bncbn2t) ([raw file](https://github.com/cockroachdb/docs/blob/ebfedd8222d028c4fba40b85720b1b1d0cb9f96e/v20.2/configure-replication-zones.md#L101)):*
> ```Markdown
> Attribute Type | Description
> ---------------|------------
> **Node Locality** | <a name="zone-config-node-locality"></a> Using the [`--locality`](cockroach-start.html#locality) flag, you can assign arbitrary key-value pairs that describe the location of the node. Locality might include region, country, availability zone, rack, etc. The key-value pairs should be ordered into _locality tiers_ that range from most inclusive to least inclusive (e.g., region before availability zone as in `region=eu,az=paris`), and the keys and the order of key-value pairs must be the same on all nodes. It's typically better to include more pairs than fewer. For example:<br><br>`--locality=region=east,az=us-east-1`<br>`--locality=region=east,az=us-east-2`<br>`--locality=region=west,az=us-west-1`<br><br>CockroachDB attempts to spread replicas evenly across the cluster based on locality, with the order of locality tiers determining the priority. Locality can also be used to influence the location of data replicas in various ways using replication zones.<br><br>When there is high latency between nodes, CockroachDB uses locality to move range leases closer to the current workload, reducing network round trips and improving read performance. See [Follow-the-workload](topology-follow-the-workload.html) for more details.
> ```

Can you remove `rack,` here? It doesn't make sense now.

**Comment by Shiwanee** [comment]
@lnhsingh  Thank you so much for your time and review comments for this issue!

I have implemented your comments. Please let me know what you think.

About broken links, I did not get any error message when I executed the "make cockroachdb" command. Is there any way I can check the links at my end? 

Thanks once again,
Shiwanee

**Comment by lnhsingh** [comment]
@Shiwanee thank you! This looks great - I will merge this for you :) 

For the broken links, I just check the build log on the PR once a commit is pushed. If you take a look at the box at the bottom of this PR, it currently says "All checks have passed", but if there are broken links (or other errors), GitHub CI will post "Some checks were unsuccessful" and you can then look at the details of the error / the build log to see what went wrong. The build log lists what pages / links are broken.

**Comment by Shiwanee** [comment]
Thanks so much @lnhsingh !
Looking forward to work with you on more issues :-)

Shiwanee

**Comment by Amruta-Ranade** [comment]
Hey, @Shiwanee ! Can you let me know the best way to contact you (twitter or other social media platform)? We'd like to send you some swag for being a top contributor :) You can also [join our Slack](https://cockroa.ch/slack) and message me there if you'd prefer!

**Comment by Shiwanee** [comment]
Yay! Nice to know that and thanks for the swag :-)
I am on CockroachDB Slack; just message you there @Amruta-Ranade 

Btw, currently I have bandwidth for more projects; feel free to assign some more issues :-) 

Shiwanee

**Pull request merged**
