### PR TITLE
Update links to Cockroach U courses

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-2292

### CODE REVIEW

**Comment by rmloveland** [comment]
Hi @alexyarosh 

Thanks for pointing out the TOC links.  Sorry for missing that

FWIW I also searched in the v20.2 and v21.1 docs for any of the old links, and did not find anything.  I think this is everything, but please let me know if I missed something.

**Comment by rmloveland** [comment]
you're welcome @alexyarosh !

@ericharmeling this one is pretty simple but I'd appreciate a look from you to avoid triggering Murphy's Law :-)

**Review by ericharmeling — APPROVED** [review]
LGTM!

**Comment by rmloveland** [comment]
@alexyarosh FYI the links should be updated in the next few (say <30) minutes once this builds and deploys

**Pull request merged**
