### PR TITLE
update minikube start defaults

### PR DESCRIPTION
**Pull request by taroface**
Adjusted the minikube CPU and memory defaults (7 CPU and 26 GB) to work with the resource requests (2 CPU and 8 GB) we prepopulate in the [example.yaml](https://github.com/cockroachdb/cockroach-operator/blob/master/examples/example.yaml) for the Operator. This updates the [local Kubernetes deployment guide](https://www.cockroachlabs.com/docs/v20.2/orchestrate-a-local-cluster-with-kubernetes.html) for 20.2 and 21.1.

(Also removed the restart count for a cockroach pod in the example deploy output)

### CODE REVIEW

**Comment by taroface** [comment]
@keith-mcclellan Would you mind weighing in on these values? I do not know if they make any sense at all. However, they were roughly the minimums that worked for me as I inched up from 3 CPUs and 15 GB for minikube.

**Comment by keith-mcclellan** [comment]
This still seems really heavy - we may need a minikube specific example.yaml for local deployments if this is something we want to support. our kind deployments don't require nearly this much memory fwiw so this is probably a config issue.  @taroface is this something we need to focus on?  I haven't used minikube in a while but I could set it back up.

**Comment by taroface** [comment]
@keith-mcclellan Per our convo I'll see if there's a memory issue on my end first.

**Comment by taroface** [comment]
I need to do some retesting on this, so will reopen when that's done.

**Pull request closed without merging**
