### PR TITLE
Added note about histograms on ARRAY-typed columns

### LINKED ISSUE #7608: sql: do not try to create histograms on array columns
PR: https://github.com/cockroachdb/cockroach/pull/47281

From release notes:
> Histogram collection with `CREATE STATISTICS` is no longer supported on columns with type [`ARRAY`](../v20.2/array.html). Only row count, distinct count, and _NULL_ count are collected for array-type columns. [#47281][#47281] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7608.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8609#-:-MJStbBmDoLQVmOEc62B:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ericharmeling** [comment]
TFTR @rytaft !

**Review by lnhsingh — COMMENTED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8609#-:-MJTlq34-jvF-AVotuvZ:b-85i648)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by ericharmeling** [comment]
@lnhsingh TFTR!

**Pull request merged**
