### PR TITLE
doc updates for table-based show statements

### LINKED ISSUE #504: SHOW CREATE TABLE statement
Need `.md` file and grammar diagrams.

### LINKED ISSUE #556: SHOW COLUMNS statement
Finish docs.

### LINKED ISSUE #557: Update privileges for table-based show statements
See PR https://github.com/cockroachdb/cockroach/pull/8070

### PR DESCRIPTION
**Pull request by jseldess**
This PR updates docs for table-based show statements as follows:
- Adds docs for `SHOW CREATE TABLE`, including adding statement to sql overview and sidebar, and adding various links to the page.
- Completes docs for `SHOW COLUMNS`.
- Updates required privileges for table-based show statements.

I've also made a few tweaks to related grammar diagrams. 

Fixes #557
Fixes #556 
Fixes #504

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/558)

### CODE REVIEW

**Comment by jseldess** [comment]
HTML version here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2a4553e34d47a470020a702fedf75a11d8dabbcb/

**Comment by mjibson** [comment]
:lgtm: after that one comment

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[show-constraints.md, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/558#-KPTyNvZIENgzSSomwxH:-KPTyNvZIENgzSSomwxI:brc794p) ([raw file](https://github.com/cockroachdb/docs/blob/2a4553e34d47a470020a702fedf75a11d8dabbcb/show-constraints.md#L29)):*
> ```Markdown
> Parameter | Description
> ----------|------------
> `table_name` | The name of the table for which to column constraints.
> ```

Grammar error here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/558#-:-KPTyjcaEgsMM2UxvABV:b-355ra9)*

**Comment by jseldess** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[show-constraints.md, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/558#-KPTyNvZIENgzSSomwxH:-KPU1lt6ZcnnbDmUEs-P:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2a4553e34d47a470020a702fedf75a11d8dabbcb/show-constraints.md#L29)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Grammar error here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/558)*

**Comment by sploiselle** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[show-create-table.md, line 3 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/558#-KPU7zy3MXFwPn5ohnNF:-KPU7zy3MXFwPn5ohnNG:btro7yb) ([raw file](https://github.com/cockroachdb/docs/blob/2a4553e34d47a470020a702fedf75a11d8dabbcb/show-create-table.md#L3)):*
> ```Markdown
> ---
> title: SHOW CREATE TABLE
> summary: The SHOW CREATE TABLE statement shows the CREATE TABLE statement for an existing table. 
> ```

_...shows the `CREATE TABLE` statement that would create a carbon copy of the specified table..._ or something to that effect? My thought here is to specify whether it shows the `CREATE TABLE` statement used to create the table, vs. showing the statement that would reproduce the table including any `ALTER TABLE` statements used on it after it was created.

---

*[show-create-table.md, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/558#-KPU8hUiQE4OlhK9ImHh:-KPU8hUjtuvd0ycqQ_kL:b-nfs5z8) ([raw file](https://github.com/cockroachdb/docs/blob/2a4553e34d47a470020a702fedf75a11d8dabbcb/show-create-table.md#L27)):*
> ```Markdown
> ## Response
> 
> The following fields are returned for each column. 
> ```

s/column/table

Also don't think it's each because the statement only accepts a single table. Maybe something like "A table with the following fields is returned."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/558)*

**Comment by jseldess** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[show-create-table.md, line 3 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/558#-KPU7zy3MXFwPn5ohnNF:-KPUDeWZ1L7jhTJw6n4t:b-vslonv) ([raw file](https://github.com/cockroachdb/docs/blob/2a4553e34d47a470020a702fedf75a11d8dabbcb/show-create-table.md#L3)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary>
> _...shows the `CREATE TABLE` statement that would create a carbon copy of the specified table..._ or something to that effect? My thought here is to specify whether it shows the `CREATE TABLE` statement used to create the table, vs. showing the statement that would reproduce the table including any `ALTER TABLE` statements used on it after it was created.
</details>
Thanks, Sean. Good points. 

---

*[show-create-table.md, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/558#-KPU8hUiQE4OlhK9ImHh:-KPUDQdXbVjOjONb0g_4:bztvs1) ([raw file](https://github.com/cockroachdb/docs/blob/2a4553e34d47a470020a702fedf75a11d8dabbcb/show-create-table.md#L27)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary>
> s/column/table
> 
> Also don't think it's each because the statement only accepts a single table. Maybe something like "A table with the following fields is returned."?
</details>
Included that intro sentence accidentally. Don't think it's needed in this case, so I've removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/558)*

**Comment by sploiselle** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/558#-:-KPUGOXjz2Mr97rm0xFW:bnfp4nl)*

**Pull request merged**
