### PR TITLE
Update secure-a-cluster.md

### PR DESCRIPTION
**Pull request by dbist**

### CODE REVIEW

**Comment by dbist** [comment]
no equivalent 20.1 entry.

**Comment by Amruta-Ranade** [comment]
> no equivalent 20.1 entry.

Thanks for fixing the error! There's a 20.1 doc that also needs to be updated. LMK if you'd prefer me to do it!

**Comment by dbist** [comment]
go right ahead @Amruta-Ranade

**Comment by jseldess** [comment]
@Amruta-Ranade, I'm actually just opening a PR to fix this page for a different reason, so I'll make this change as part of that PR. Sorry for the churn here.

**Pull request closed without merging**
