### PR TITLE
[WIP] Add 'Migration Guide' to 2.1 docs

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes:

- #3140 (general migration issue)
- #2936 (MySQL)
- #3273 (Postgres)

Summary of changes:

- New pages: 'Migrate from {CSV,MySQL,Postgres}' with instructions for
  each database / format.  Examples pull real SQL/CSV data from S3
  buckets.

- New page: 'Migration Overview' with orientation and links to all of
  the above.

- Update `IMPORT` reference page: Mention new databases / formats, as
  well as general edits/improvements, and links to new migration how-to
  pages.

- Update 'Create a file server' page: Add local server examples that are
  one-liners, and thus easier to use with `IMPORT` (in PHP, Python,
  Ruby).

- Administrivia: Update link on release notes page; Add new pages to
  v2.1 sidebar; turn "Import Data" page into a redirect to the Migration
  Guide's overview page.

- TODO items: Update `IMPORT` page railroad diagram and associated
  grammar keyword descriptions.  Introduce some include usage to reduce
  duplication.

### CODE REVIEW

**Comment by rmloveland** [comment]
@dt @mjibson @rolandcrosby asking for the gang review but let me know if any of y'all would like to drop off.

Direct links for easier review:

- [`IMPORT` page](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/216350d714edcb40bcdd2eff7d94d1b031ac4bef/dev/import.html) (updated)

**Comment by rolandcrosby** [comment]
You might want to consider compressing the example dump files on S3 -- the MySQL employees dataset (employees-full.sql) is 161 MB, but only 35 MB when gzipped. This would also give us a nice opportunity to demonstrate CockroachDB's native support for importing compressed data.

**Comment by rmloveland** [comment]
> You might want to consider compressing the example dump files on S3 -- the MySQL employees dataset (employees-full.sql) is 161 MB, but only 35 MB when gzipped.

Thanks @rolandcrosby - just did this for the various MySQL, Postgres, and CSV examples that point to S3.

**Comment by jseldess** [comment]
@rmloveland, are you ready for me to take a look at this?

**Comment by rmloveland** [comment]
Hey @mjibson do the changes I made address your comments?  Are there any additional changes you would like to see before this goes through the docs team's review?

**Pull request merged**
