### PR TITLE
Clarify user vs. role on Authorization page

### PR DESCRIPTION
**Pull request by mikeCRL**
Addresses part of https://github.com/cockroachdb/docs/issues/7968 by adding clarifications on role vs. user on authorization.md.

### CODE REVIEW

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9802)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

**Comment by mikeCRL** [comment]
Thanks, knz.

Holding off on merging in order to add this to 20.2, as well. It may be best to retain a note in that versions page, reflecting what's changed in 20.x—so it's more than a copy/paste. Will get to it when back 'in the office' this week.

**Review by taroface — CHANGES_REQUESTED** [review]
A few suggestions. I left the comments on v20.1, but they apply to v20.2 and v21.1 as well. (One comment is on v20.2 because I thought of it after Reviewable had moved on...)

> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9802#-:-MTh9zxRALmNcFwJ3KBi:b-bk9fjn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @mikeCRL)

___
*[v20.1/authorization.md, line 18 at r4](https://reviewable.io/reviews/cockroachdb/docs/9802#-MTh84XP4e9ZcvKGXv_4:-MTh84XP4e9ZcvKGXv_5:b8yuasv) ([raw file](https://github.com/cockroachdb/docs/blob/1294b2d95d494b23c8fc4ebb0265fd44c7975889/v20.1/authorization.md#L18)):*
> ```Markdown
> There is no technical distinction between a role or user in CockroachDB. A role/user can:
> 
> - be permitted to log in to the SQL shell.
> ```

Suggest linking `cockroach-sql` here.
___
*[v20.1/authorization.md, line 19 at r4](https://reviewable.io/reviews/cockroachdb/docs/9802#-MTh88cE1zfalVOR4zzN:-MTh88cE1zfalVOR4zzO:b-mjio19) ([raw file](https://github.com/cockroachdb/docs/blob/1294b2d95d494b23c8fc4ebb0265fd44c7975889/v20.1/authorization.md#L19)):*
> ```Markdown
> 
> - be permitted to log in to the SQL shell.
> - be granted privileges to specific actions and database objects.
> ```

Ditto for `#assign-privileges` on this page.
___
*[v20.1/authorization.md, line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/9802#-MTh8lNO-sfocgpti_1d:-MTh8lNO-sfocgpti_1e:bmzocvy) ([raw file](https://github.com/cockroachdb/docs/blob/1294b2d95d494b23c8fc4ebb0265fd44c7975889/v20.1/authorization.md#L21)):*
> ```Markdown
> - be granted privileges to specific actions and database objects.
> - be a member of other users/roles, inheriting their privileges.
> - have other users/roles as members.
> ```

Worth adding "that inherit its privileges" for clarity?
___
*[v20.1/authorization.md, line 25 at r4](https://reviewable.io/reviews/cockroachdb/docs/9802#-MTh9-_X0QvJlz8R6Ol7:-MTh9-_X0QvJlz8R6Ol8:b-weyk0d) ([raw file](https://github.com/cockroachdb/docs/blob/1294b2d95d494b23c8fc4ebb0265fd44c7975889/v20.1/authorization.md#L25)):*
> ```Markdown
> We refer to these as "roles" when they are created for managing the privileges of their member "users" and not for logging in directly, which is typically reserved for "users".
> 
> The SQL statements `CREATE USER` and `CREATE ROLE` will create the same entity with one exception: `CREATE ROLE` will add the `NOLOGIN` option by default, preventing the user/role from being used to log in. Othwerise, for enhanced PostgreSQL compatibility, the keywords `ROLE` and `USER` can be used interchangeably in SQL statements.
> ```

Probably best to link `CREATE USER` and `CREATE ROLE` docs here.

Typo on "Otherwise".
___
*[v20.2/authorization.md, line 14 at r4](https://reviewable.io/reviews/cockroachdb/docs/9802#-MTh9hKW2u31_9fpQS9o:-MTh9hKW2u31_9fpQS9p:b-etvdrw) ([raw file](https://github.com/cockroachdb/docs/blob/1294b2d95d494b23c8fc4ebb0265fd44c7975889/v20.2/authorization.md#L14)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> ## Users and Roles
> ```

Since we use sentence case for headers, I think "Roles" should be lowercase here (unless there's a style convention I'm not aware of).

**Review by taroface — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9802#-:-MTlvrIb7ejAJGUoW8Cn:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @mikeCRL, and @taroface)

**Comment by mikeCRL** [comment]
@taroface Implemented all your edits. TFTR!

**Pull request merged**
