### PR TITLE
Basic hardware recs

### PR DESCRIPTION
**Pull request by jseldess**
Starts to address #1132, though not yet per-cloud.

### CODE REVIEW

**Comment by jseldess** [comment]
@bdarnell, @mberhault, is it worth publishing these basic hardware recommendations in advance of having cloud-specific guidance? If so, anything need to be tweaked or added? 

Question: What exactly should I say about disk space? Cassandra has some nice **[docs](https://docs.datastax.com/en/landing_page/doc/landing_page/planning/planningHardware.html#planningHardware__disk) as well as a procedure for [estimating usable disk space](https://docs.datastax.com/en/landing_page/doc/landing_page/planning/planPlanningDiskCapacity.html).

**Comment by sploiselle** [comment]
@jseldess Don't know if it's worth trying to fix, but the failing Azure page on TC loads much more quickly with a trailing slash (i.e., `https://azure.microsoft.com/en-us/updates/create-empty-resource-groups/`)

**Comment by jseldess** [comment]
@sploiselle, hmm, we're already using a trailing slash...

**Comment by sploiselle** [comment]
@jseldess Ah. The TC error was showing a URL without the slash; I didn't check the source. My mistake!

**Comment by bdarnell** [comment]
Yes, we should go ahead and publish this information even though we don't yet have it translated into the cloud provider's machine classes. 

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[recommended-production-settings.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CVK6EDI8R9lYMsCm:-Km2CVK6EDI8R9lYMsCn:b32pfvi) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L14)):*
> ```Markdown
> ## Hardware
> 
> Each node of a CockroachDB cluster requires at a mimimum:
> ```

This would be a good place to repeat the requirement that you need a minimum of three nodes for a replicated cluster.

---

*[recommended-production-settings.md, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2BgfZvCZmC-sX5k4G:-Km2Bgf_lOI8VszPI6oQ:b-pjkpgo) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L16)):*
> ```Markdown
> Each node of a CockroachDB cluster requires at a mimimum:
> 
> - 2 CPU cores
> ```

@mberhault Why make this a hard requirement? More is better, of course, but everything should work with a single core.  (i'd rather run with one core on an SSD than two cores on HDD, for example)

---

*[recommended-production-settings.md, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2DReKvRiAwgnFU1R9:-Km2DReKvRiAwgnFU1RA:bd6pq9f) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L21)):*
> ```Markdown
> If performance is a priority, also consider the following:
> 
> - Use SSDs over HHDs.
> ```

s/HHD/HDD/

---

*[recommended-production-settings.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CLqdYQaGHNWFMlPK:-Km2CLqdYQaGHNWFMlPL:b-tgd8dq) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L22)):*
> ```Markdown
> 
> - Use SSDs over HHDs.
> - Since CockroachDB balances data approximately evenly across nodes, use more nodes to increase the work that can be handled in parallel and to reduce the amount of data to recover in case of node failure.
> ```

It's not very clear to me what this line is trying to say. 

---

*[recommended-production-settings.md, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2D5SQIzIQtAzaOp--:-Km2D5SQIzIQtAzaOp-0:b-xox1s6) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L23)):*
> ```Markdown
> - Use SSDs over HHDs.
> - Since CockroachDB balances data approximately evenly across nodes, use more nodes to increase the work that can be handled in parallel and to reduce the amount of data to recover in case of node failure.
> - Use larger nodes to increase processing power and, on cloud platforms, to increase the chance of getting a dedicated machine.
> ```

We should also say that in most cases, adding more CPUs will be more beneficial than adding more RAM. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-:-Km2Dck6WVNdJalCnUAf:biys6jy)*

**Comment by jseldess** [comment]
*[recommended-production-settings.md, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2BgfZvCZmC-sX5k4G:-Km2EuEBjYMVlR4k2CUH:b-dvpori) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L16)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

@mberhault Why make this a hard requirement? More is better, of course, but everything should work with a single core.  (i'd rather run with one core on an SSD than two cores on HDD, for example)
</blockquote></details>

Oh, @mberhault's rec was 1 core. I saw a later comment from you in the issue and thought you were suggesting that 2 should be our minimum. I must've misunderstood.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527)*

**Comment by jseldess** [comment]
*[recommended-production-settings.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CLqdYQaGHNWFMlPK:-Km2F6DydngcSiuVJh78:bwcaqv1) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L22)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's not very clear to me what this line is trying to say. 
</blockquote></details>

Hmm, the main point not being made clearly is that recovery from node failure will be quicker with more nodes? How would you explain that? 

I guess the other point I was trying to make - the the processing of queries is distributed just as the data is - isn't really relevant here...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[recommended-production-settings.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CLqdYQaGHNWFMlPK:-Km2fSIsGhByLSNGTVun:b-gxfwts) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L22)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Hmm, the main point not being made clearly is that recovery from node failure will be quicker with more nodes? How would you explain that? 

I guess the other point I was trying to make - the the processing of queries is distributed just as the data is - isn't really relevant here...
</blockquote></details>

More nodes will improve recovery speed, but will generally reduce performance (it's true that some queries will be able to take advantage of more nodes, but *all* queries will be able to take advantage of faster nodes). This is why I was confused to see this in the "performance" section. 

How about making that tradeoff explicit with something like this:

For best performance:
- Use SSDs over HDDs
- Use larger/more powerful nodes. Adding more CPU is usually more beneficial than adding more RAM

For best resiliency:
- Use many smaller nodes instead of fewer larger ones. Recovery from a failed node is faster when data is spread across more nodes.
- Use zone configs to set a replication factor of 5 (instead of the default 3)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[recommended-production-settings.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CVK6EDI8R9lYMsCm:-Km2lq8sidHMZJdC7Ea8:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L14)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This would be a good place to repeat the requirement that you need a minimum of three nodes for a replicated cluster.
</blockquote></details>

Done.

---

*[recommended-production-settings.md, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2DReKvRiAwgnFU1R9:-Km2eePrt-8HKlh-mkgf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L21)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/HHD/HDD/
</blockquote></details>

Done.

---

*[recommended-production-settings.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CLqdYQaGHNWFMlPK:-Km2lroQkonjyt7whEV0:b-fld0l8) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L22)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

More nodes will improve recovery speed, but will generally reduce performance (it's true that some queries will be able to take advantage of more nodes, but *all* queries will be able to take advantage of faster nodes). This is why I was confused to see this in the "performance" section. 

How about making that tradeoff explicit with something like this:

For best performance:
- Use SSDs over HDDs
- Use larger/more powerful nodes. Adding more CPU is usually more beneficial than adding more RAM

For best resiliency:
- Use many smaller nodes instead of fewer larger ones. Recovery from a failed node is faster when data is spread across more nodes.
- Use zone configs to set a replication factor of 5 (instead of the default 3)
</blockquote></details>

Done. 

For the zone config bullet, I've just linked to the start of the zone config page. Is the more specific recommendation here to change the default zone config to replicate 5 ways? If so, I could link directly to this example instead: https://www.cockroachlabs.com/docs/configure-replication-zones.html#edit-the-default-replication-zone

---

*[recommended-production-settings.md, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2D5SQIzIQtAzaOp--:-Km2lsXCfAFQRAbd3_Ni:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L23)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should also say that in most cases, adding more CPUs will be more beneficial than adding more RAM. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[recommended-production-settings.md, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2BgfZvCZmC-sX5k4G:-Km2yI4Xy7uO3TZZhAq9:b-mmpxd9) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L16)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Oh, @mberhault's rec was 1 core. I saw a later comment from you in the issue and thought you were suggesting that 2 should be our minimum. I must've misunderstood.
</blockquote></details>

I'm not sure if we need to list this if it's just 1 (unless it's to distinguish VMs that could otherwise get a fractional CPU)

---

*[recommended-production-settings.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CLqdYQaGHNWFMlPK:-Km2yG2jPp3oaFyvTOXA:b-mjh13h) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L22)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Done. 

For the zone config bullet, I've just linked to the start of the zone config page. Is the more specific recommendation here to change the default zone config to replicate 5 ways? If so, I could link directly to this example instead: https://www.cockroachlabs.com/docs/configure-replication-zones.html#edit-the-default-replication-zone
</blockquote></details>

Yeah, linking to that example would be good. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-:-Km2ykjbhLk9_DW5T3sC:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[recommended-production-settings.md, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2BgfZvCZmC-sX5k4G:-Km3G588rI4yrI64lCsh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L16)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not sure if we need to list this if it's just 1 (unless it's to distinguish VMs that could otherwise get a fractional CPU)
</blockquote></details>

Done.

---

*[recommended-production-settings.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1527#-Km2CLqdYQaGHNWFMlPK:-Km3D6eNRG1q420H7fY-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ad4eea541c719ba78bfe3fdf818ecb9284f03850/recommended-production-settings.md#L22)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, linking to that example would be good. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1527)*

**Comment by jseldess** [comment]
@mberhault, any feedback before I merge these initial hardware recommendations?

**Comment by mberhault** [comment]
LGTM, sorry about the delay.

**Pull request merged**
