### PR TITLE
v20.2.0-rc.1 Release Notes

### LINKED ISSUE #7982: v20.2.0-rc.1 Release Notes
Prep date: 10/8/20
Release date: 10/15/20
SHA: `4e07f485cb01c7eb40935a841d8367db6d02ca38 `
Release Manager: Lucy
Issue: https://github.com/cockroachdb/cockroach/issues/55335

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [x] Run script to generate release notes
- [x] Update docs site
- [x] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #7982

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8639)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[releases/v20.2.0-rc.1.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTKYjE3Skt_ajI-OOy:-MJTKYjE3Skt_ajI-OOz:b-3eknvn) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L42)):*
> ```Markdown
> ## Known limitations
> 
> - The new Docker image (see [release note below](#new-docker-image)) does not work with the CockroachDB Kubernetes manifest, so customers using Kubernetes cannot upgrade to this testing release. This will be fixed in the next testing release (see [tracking issue][#55390]).
> ```

@jlinder can you review this note? It's similar to what I slacked you.

**Review by jlinder — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @taroface)

___
*[releases/v20.2.0-rc.1.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTKYjE3Skt_ajI-OOy:-MJTLFS77TLlDruUDooz:b-supao7) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L42)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@jlinder can you review this note? It's similar to what I slacked you.
</blockquote></details>

That looks great. Thanks!
___
*[releases/v20.2.0-rc.1.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTLd3X69n0rH7GZDAD:-MJTLd3X69n0rH7GZDAE:b-6xen4y) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L46)):*
> ```Markdown
> ## Backward-incompatible changes
> 
> - <a name="new-docker-image"></a>CockroachDB Docker images are now based on the RedHat UBI8/UBI base image instead of Debian 9.12 slim. This will help on-premise customers from a security and compliance perspective. [#55130][#55130]
> ```

I noticed the caps on `UBI8/UBI`. Following what I see on the RedHat website, it should be either "RedHat UBI 8" or "RedHat ubi8/ubi" (the `ubi8/ubi` format references the specific image used and should be lower-cased).

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @taroface)

___
*[releases/v20.2.0-rc.1.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTNq6y8VfCPvYT4zLu:-MJTNq6y8VfCPvYT4zLv:b3sjer) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L2)):*
> ```Markdown
> ---
> title: What&#39;s New in v20.2.0-beta.4
> ```

Should this be `v20.2.0-rc.1`?
___
*[releases/v20.2.0-rc.1.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTOnMp4l-AGbUK7Im8:-MJTOnMp4l-AGbUK7Im9:bv1fc9s) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L60)):*
> ```Markdown
> 
> - Implemented the geometry-based [builtin](../v20.2/functions-and-operators.html#built-in-functions) `ST_SwapOrdinates`. [#54564][#54564]
> - Implemented the geometry [builtin](../v20.2/functions-and-operators.html#built-in-functions) `ST_OrderingEquals`. [#54564][#54564]
> ```

Nit: make the language around "geometry" in the above 2 lines consistent (not sure which is better).
___
*[releases/v20.2.0-rc.1.md, line 79 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTP6cS2rSwkSHaWlPi:-MJTP6cS2rSwkSHaWlPj:b-al9dmr) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L79)):*
> ```Markdown
> ### Bug fixes
> 
> - Fixed a bug where previous versions of v20.2 would not properly clear grants and owners on non-cluster restores. [#54854][#54854]
> ```

For clarity, maybe change "previous versions of v20.2" to "previous v20.2 testing releases" or similar
___
*[releases/v20.2.0-rc.1.md, line 82 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPEom1YLXYhyB6cmc:-MJTPEom1YLXYhyB6cmd:b-1qemfe) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L82)):*
> ```Markdown
> - Fixed a bug in v20.2 testing releases that under-accounted for scan memory. Note that the bug wasn't a regression from v20.1, which never had any scan memory accounting at all. [#54894][#54894]
> - Fixed issue when jobs duration could be negative value or increased periodically for finished jobs. [#54872][#54872]
> - Fixed a rare bug which can lead to index backfills failing in the face of transaction restarts. [#54858][#54858]
> ```

Nit: which can lead -> which could lead
___
*[releases/v20.2.0-rc.1.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPHPJ9Lkj5slcBbz8:-MJTPHPJ9Lkj5slcBbz9:b-sgl22t) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L83)):*
> ```Markdown
> - Fixed issue when jobs duration could be negative value or increased periodically for finished jobs. [#54872][#54872]
> - Fixed a rare bug which can lead to index backfills failing in the face of transaction restarts. [#54858][#54858]
> - Fixed a bug which lead to inscrutable errors being returned when creating a backup failed; for example, due to protected timestamp limits. [#54967][#54967]
> ```

lead -> led
___
*[releases/v20.2.0-rc.1.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPP0I8SUDiZ_ucfxs:-MJTPP0I8SUDiZ_ucfxt:bnyak77) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L86)):*
This sentence wording is a bit confusing, maybe just:

> Previously, canceling schema changes when there were multiple queued schema changes could result in future schema changes being stuck. This has been fixed.
___
*[releases/v20.2.0-rc.1.md, line 89 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPjJ397hCIfU4fn1c:-MJTPjJ397hCIfU4fn1d:b-bwdobq) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L89)):*
> ```Markdown
> - Fixed an error that could occur during planning when attempting to create or use a partial index. The error implied that the partial index could not be used (e.g., "my_index is a partial index that does not contain all the rows needed to execute this query") when in fact the partial index could be used correctly. [#55080][#55080]
> - Cross-database temporary schemas are now properly resolved. [#55198][#55198]
> - Previously, restoring a cluster backup that contained user-defined schemas or user-defined type in `defaultdb` would fail. [#55249][#55249]
> ```

Nit: user-defined types
___
*[releases/v20.2.0-rc.1.md, line 90 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPnL72ziDFBhBktq-:-MJTPnL84ex_rAWW-pCc:b6f13eh) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L90)):*
> ```Markdown
> - Cross-database temporary schemas are now properly resolved. [#55198][#55198]
> - Previously, restoring a cluster backup that contained user-defined schemas or user-defined type in `defaultdb` would fail. [#55249][#55249]
> - Options set on users (e.g., `ALTER USER u CREATEDB`) were not included in cluster backups and thus not restored. Role options have been introduced in v20.2. [#55250][#55250]
> ```

Is there a link to include for "Role options"?

**Review by jlinder — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[releases/v20.2.0-rc.1.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTLd3X69n0rH7GZDAD:-MJTliKW-ZUXT5L7XnKm:b-le9bjq) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L46)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

I noticed the caps on `UBI8/UBI`. Following what I see on the RedHat website, it should be either "RedHat UBI 8" or "RedHat ubi8/ubi" (the `ubi8/ubi` format references the specific image used and should be lower-cased). 
</blockquote></details>

Actually, could you use "RedHat UBI 8" here? There is a possibility we will switch to using the `ubi8/ubi-minimal` image instead of `ubi8/ubi`.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @lnhsingh, and @taroface)

___
*[releases/v20.2.0-rc.1.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTNq6y8VfCPvYT4zLu:-MJTqcYiDiE42HIHqBGI:bt2vr1b) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L2)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Should this be `v20.2.0-rc.1`?
</blockquote></details>

Fixed.
___
*[releases/v20.2.0-rc.1.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTLd3X69n0rH7GZDAD:-MJTqlnQ0m_myvplE70e:bvrgoba) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L46)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Actually, could you use "RedHat UBI 8" here? There is a possibility we will switch to using the `ubi8/ubi-minimal` image instead of `ubi8/ubi`.
</blockquote></details>

Changed to "RedHat UBI 8"
___
*[releases/v20.2.0-rc.1.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTOnMp4l-AGbUK7Im8:-MJTqt426D7diALkQrLu:bwigkyz) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L60)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: make the language around "geometry" in the above 2 lines consistent (not sure which is better).
</blockquote></details>

I think it's been just "geometry builtin" in past release notes so I'll keep that.
___
*[releases/v20.2.0-rc.1.md, line 79 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTP6cS2rSwkSHaWlPi:-MJTr1cl8rv9cXDbKeas:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L79)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

For clarity, maybe change "previous versions of v20.2" to "previous v20.2 testing releases" or similar
</blockquote></details>

Done.
___
*[releases/v20.2.0-rc.1.md, line 82 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPEom1YLXYhyB6cmc:-MJTr6nV2p3LfMX7Eche:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L82)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: which can lead -> which could lead
</blockquote></details>

Done.
___
*[releases/v20.2.0-rc.1.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPHPJ9Lkj5slcBbz8:-MJTrA1L6p2rQwK3Phtw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L83)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

lead -> led
</blockquote></details>

Done.
___
*[releases/v20.2.0-rc.1.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPP0I8SUDiZ_ucfxs:-MJTrFNr7KN6YVKR1fZr:b-9mv7ul) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L86)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This sentence wording is a bit confusing, maybe just:

> Previously, canceling schema changes when there were multiple queued schema changes could result in future schema changes being stuck. This has been fixed.
</blockquote></details>

TY! Fixed.
___
*[releases/v20.2.0-rc.1.md, line 89 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPjJ397hCIfU4fn1c:-MJTrPh82PumSc4ySkPK:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L89)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: user-defined types
</blockquote></details>

Done
___
*[releases/v20.2.0-rc.1.md, line 90 at r1](https://reviewable.io/reviews/cockroachdb/docs/8639#-MJTPnL72ziDFBhBktq-:-MJTryY9EG-lDyQOS1-t:bqmjwcz) ([raw file](https://github.com/cockroachdb/docs/blob/9362941ad9caa36c44c20d188edbfa4275633f8d/releases/v20.2.0-rc.1.md#L90)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Is there a link to include for "Role options"?
</blockquote></details>

Added.

**Pull request merged**
