### PR TITLE
Update domiciling docs with moar super region info

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-3680

Summary of changes:

- Update 'Data Domiciling' and 'Multiregion Overview > Super Regions'
  pages to state that super regions are the only way using the new
  high-level multiregion syntax to do domiciling and have region
  survivability.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: 

Just one nit.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14025#-:-N5BlnnD6e9NvYNKNRik:bfvysac)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187 and @rmloveland)

___
*[`_includes/v22.1/sql/super-regions-for-domiciling-with-region-survivability.md` line 1 at r1](https://reviewable.io/reviews/cockroachdb/docs/14025#-N5Blj5SE3iY7eOr4gbS:-N5Blj5SE3iY7eOr4gbT:b-btux10) ([raw file](https://github.com/cockroachdb/docs/blob/f4cc14a2013bdd8baf3a08feed883fe516a7f7c7/_includes/v22.1/sql/super-regions-for-domiciling-with-region-survivability.md#L1)):*
> ```Markdown
> If you want to do data domiciling for databases with [region survival goals](multiregion-overview.html#survive-region-failures) {% if page.name == "multiregion-overview.md" %} using the higher-level multiregion abstractions, you must use Super Regions {% else %} using the higher-level [multiregion abstractions](multiregion-overview.html), you must use [Super Regions](multiregion-overview.html#super-regions) {% endif %}. Using [`ALTER DATABASE ... PLACEMENT RESTRICTED`](placement-restricted.html) will not work for databases that are set up with region survival goals.
> ```

Nit: Extra space after "Super Regions".

**Comment by rmloveland** [comment]
Thanks Adam.  Fixed now.  Passing along for docs review

**Review by ianjevans — APPROVED** [review]
Just need to fix the Vale warnings about multi-region/multiregion in the include.

**Comment by rmloveland** [comment]
> Just need to fix the Vale warnings about multi-region/multiregion in the include.

Fixed!  

PS I'm trying to make "multiregion" happen, similar to how folks wrote "e-mail" at one time, but we have "email" now.  One day the world will agree with meeeeee!!!!!1!  (until then I updated the PR lol)

**Pull request merged**
