### PR TITLE
Advertise a PostGIS version compatibility

### PR DESCRIPTION
**Pull request by stbof**
https://cockroachlabs.atlassian.net/browse/DOC-830

### CODE REVIEW

**Review by awoods187 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stbof)

**Review by vy-ton — APPROVED** [review]

**Comment by vy-ton** [comment]
@otan For my knowledge, do we have testing that confirms compatibility with a specific PostGIS version?

**Comment by otan** [comment]
not testing per say, but our aim (atm) is 3.0

**Review by rmloveland — APPROVED** [review]
LGTM!

**Pull request merged**
