### PR TITLE
Add link to Cockroach University

### PR DESCRIPTION
**Pull request by gliptak**
Fixes https://github.com/cockroachdb/docs/issues/8793.

### CODE REVIEW

**Comment by gliptak** [comment]
@taroface @lnhsingh please review

**Review by lnhsingh — CHANGES_REQUESTED** [review]
Hi @gliptak, thank you for opening this PR! I added @ericharmeling as a reviewer since he is the owner of this product area. The original issue says we might want to add this callout to the SQLAlchemy tutorial and perhaps others -- Eric, are there specific docs that you'd want to advertise the CockroachU course on (can you list them here)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8846#-:-MLjDtPb6lZXwdGTiAM1:b51iq91)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @gliptak, and @lnhsingh)

___
*[v20.1/build-a-python-app-with-cockroachdb.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/8846#-MLjDwdJ7K23KzzomksP:-MLjDwdK-bZnfshyOt7M:bcyzto8) ([raw file](https://github.com/cockroachdb/docs/blob/7860229bad7ada27efe4e4a212794539a2fb9a34/v20.1/build-a-python-app-with-cockroachdb.md#L17)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> [Take the free online course at Cockroach University](https://university.cockroachlabs.com/)
> ```

@ericharmeling - need your help on wording here. I think it should be something like `Take our newest Cockroach University course, [CockroachDB for Python Developers](https://university.cockroachlabs.com/).` but not sure.

**Review by ericharmeling — COMMENTED** [review]
Thanks for your contribution, @gliptak !

Please see my inline comment.

After you've followed up on that, can you add your changes to the following files as well:

- v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v20.2/build-a-python-app-with-cockroachdb.md
- v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v20.1/developer-guide-overview.md (at the end of the section entitled `## Sample Apps and Tutorials`)
- v20.2/developer-guide-overview.md (at the end of the section entitled `## Sample Apps and Tutorials`)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8846#-:-MLru6fi-7bwrwrGrnai:bng7wnh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @gliptak)

___
*[v20.1/build-a-python-app-with-cockroachdb.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/8846#-MLjDwdJ7K23KzzomksP:-MLruFlq21-5nrsdcFY_:bze4xm6) ([raw file](https://github.com/cockroachdb/docs/blob/7860229bad7ada27efe4e4a212794539a2fb9a34/v20.1/build-a-python-app-with-cockroachdb.md#L17)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@ericharmeling - need your help on wording here. I think it should be something like `Take our newest Cockroach University course, [CockroachDB for Python Developers](https://university.cockroachlabs.com/).` but not sure.
</blockquote></details>

I agree.

@gliptak Please update this text to `Take our newest Cockroach University course, [CockroachDB for Python Developers](https://university.cockroachlabs.com/).`

**Review by ericharmeling — APPROVED** [review]
@gliptak Apologies for the super late review! LGTM!

**Comment by gliptak** [comment]
@lnhsingh please review

**Comment by ericharmeling** [comment]
@gliptak I'm going to go ahead and merge for you.

**Review by ericharmeling — CHANGES_REQUESTED** [review]
@gliptak 

Apologies. On second review, I noticed that there is an open bracket ("`[`") that needs to be removed from each of the callouts in this commit.

**Comment by gliptak** [comment]
@ericharmeling updated

**Comment by ericharmeling** [comment]
@gliptak LGTM. Thanks for your contribution here! Will merge later this week.

**Review by ericharmeling — APPROVED** [review]

**Pull request merged**
