### PR TITLE
adding sql server to comparison chart

### PR DESCRIPTION
**Pull request by jseldess**
Adding SQL Server in response to issue #143.

@BramGruneir, please double-check the answers for me. Here's what it'll look like. The table's getting too wide, so I'll open a separate issue to find better ways to style it.

screen shot 2016-03-24 at 12 19 10 pm

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/145)

### CODE REVIEW

**Comment by spencerkimball** [comment]
Still looks ok width-wise to me. I wouldn't add to your plate to restyle just yet.

LGTM

**Comment by BramGruneir** [comment]
@mrtracy can you help confirm the values for SqlServer please?

**Comment by RaduBerinde** [comment]
LGTM. An easy way to reduce the width a bit is to make the fonts for Yes/No/Optional/Full smaller.

Unrelated to this PR, but I don't understand the difference between `Optional` and `Yes` for `Eventually Consistent Reads` (defined as "Ability to read from replicas that do not have the most recently written data" which sounds like a feature). Does `Yes` mean that those systems *always* read from potentially outdated replicas? Because that's worse than the other systems. If so, I propose changing the definition to "Optionally allows reading from replicas that do not have the most recently written data", replacing the `Yes`s with `N/A` (maybe with a footnote), and replacing the `Optionals` to `Yes`.

**Comment by jseldess** [comment]
@RaduBerinde, I agree that "Optional" is confusing for "Eventually Consistent Reads". Since the definition is about the "ability" to do inconsistent reads, a "Yes" doesn't imply "always". So maybe we could just change all instances of "Optional" to "Yes"? @spencerkimball, would that be ok? I don't remember why we went with optional in the first place.

**Comment by spencerkimball** [comment]
Fine by me.

**Comment by jseldess** [comment]
OK, updated eventually consistent reads. Will handle styling/restructuring in a later PR. Starting to wonder whether it might be good to have two tables one comparing CockroachDB to other relational dbs and the other comparing to NoSQL dbs.

**Pull request merged**
