### PR TITLE
August release notes for CC

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/CC-3668

### CODE REVIEW

**Review by thtruo — APPROVED** [review]
Thanks for adding me as a reviewer - there aren't missing Observability specific callouts from my read - this LGTM!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11004#-:-MgI78as6W5ag_aBcyRR:bo9zcjc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

**Review by kannanlakshmi — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

**Comment by kannanlakshmi** [comment]
Actually I just thought of something. @jramos-crl do you want to call out that we now bill once a month rather than twice a month in the Aug release notes? 
Also @gemma-shay let's add @emily-horing and @jramos-crl in addition to me going forward, thanks!

**Comment by gemma-shay** [comment]
@kannanlakshmi Sounds good! And I believe we called out the billing change in July’s release notes.

**Review by jramos-crl — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @ianjevans)

**Review by ianjevans — APPROVED** [review]

**Review by emily-horing — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11004#-:-Mgfsp522eqPLzawiUs2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/cockroachcloud-08092021.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/11004#-MgfsgSqD0Qv-Olbr4FX:-MgfsgSqD0Qv-Olbr4FY:bi0rqkv) ([raw file](https://github.com/cockroachdb/docs/blob/04699a84ddf385099fbedf38226ecce71cb39a83/releases/cockroachcloud-08092021.md#L20)):*
> ```Markdown
> ### Console changes
> 
> - Improved user experience on the Cluster Overview page for a deleted cluster.
> ```

What change is this referring to?

**Comment by gemma-shay** [comment]
@emily-horing

> Previously, Overview/Plan details were being displayed for clusters,
> even if they were deleted.
> 
> To improve the user-experience for deleted clusters, this PR:
> - short-circuits the Overview/Plan display logic, showing a
>   "cluster has been deleted" note if cluster has been deleted
> - modifies logic to show "[Deleted]" next to the cluster
>   name (to account for local clusters created using the
>   fake intrusion)
> - redirects users from other side nav pages to the overview
>   page

**Pull request merged**
