### PR TITLE
DOC-2462 debug zip incl repl reports

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-2462
CRDB: [#75239](https://github.com/cockroachdb/cockroach/pull/75239)

- Added entry to `cockroach debug zip` reference page under `Files` to indicate that Replication Reports are now also included in the resulting zip file.
- EDIT: Just noticed [#75794](https://github.com/cockroachdb/cockroach/pull/75794), so performed this also for `v21.2`

[cockroach-debug-zip.html](https://deploy-preview-13827--cockroachdb-docs.netlify.app/docs/v22.1/cockroach-debug-zip#files)

### CODE REVIEW

**Review by andf-crl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13827)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`v22.1/cockroach-debug-zip.md` line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/13827#-N1PrUT89-KMrNo3jc4F:-N1PrUT89-KMrNo3jc4G:bozl125) ([raw file](https://github.com/cockroachdb/docs/blob/1ab5b17073dc33b27c8e1614fa4bd6d05fa3b6a8/v22.1/cockroach-debug-zip.md#L64)):*
> ```Markdown
> - [Cluster Settings](cluster-settings.html)
> - [Metrics](ui-custom-chart-debug-page.html#available-metrics)
> - [Replication Reports](query-replication-reports.html)
> ```

Opting to include just overarching category: "Replication Reports" w/ link.

Let me know if you'd prefer for three discrete entries in this table for the actual tables included:

- `system.replication_stats`
- `system.replication_critical_localities`
- `system.replication_constraint_stats`

with direct links to their individual entries on repl reports page (like: `query-replication-reports.html#system-replication_stats`)

As these are cluster-wide, and not subject to `--exclude-files`, `--include-files`, etc, we must include this entry in this "cannot be filtered" listing.

**Review by andf-crl — COMMENTED** [review]
Hi -- straightforward docs review for you! Question inline if you'd like a slightly different approach. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13827#-:-N1PsXWWC3tMskOkHXJn:b-n1efhq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl)

___
*[`v22.1/cockroach-debug-zip.md` line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/13827#-N1PrUT89-KMrNo3jc4F:-N1tPcaF8Kvr_CewWuJ-:bsdt1sg) ([raw file](https://github.com/cockroachdb/docs/blob/1ab5b17073dc33b27c8e1614fa4bd6d05fa3b6a8/v22.1/cockroach-debug-zip.md#L64)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Opting to include just overarching category: "Replication Reports" w/ link.

Let me know if you'd prefer for three discrete entries in this table for the actual tables included:

- `system.replication_stats`
- `system.replication_critical_localities`
- `system.replication_constraint_stats`

with direct links to their individual entries on repl reports page (like: `query-replication-reports.html#system-replication_stats`)

As these are cluster-wide, and not subject to `--exclude-files`, `--include-files`, etc, we must include this entry in this "cannot be filtered" listing.
</blockquote></details>

This is fine, thanks

**Review by taroface — APPROVED** [review]
LGTM!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13827#-:-N2DE2TY1ntXWRvOlsip:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl)

**Review by andf-crl — COMMENTED** [review]
TYFRs both!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13827#-:-N2DHcw8Comg0OsWNDUM:bmrua2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl)

**Pull request merged**
