### PR TITLE
Removed include_cached new-in.html from MD tables

### PR DESCRIPTION
**Pull request by nickvigilante**

### CODE REVIEW

**Comment by stbof** [comment]
In `v21.2/create-changefeed.md` there are a lot of instances of `<span class="version-tag">New in v21.2:</span>`. I thought we wanted to use only `**New in v21.2:**.

**Comment by nickvigilante** [comment]
@stbof Check now. There were several `<span>` tags that either I missed the first time or others added after I did my initial pass.

**Review by stbof — APPROVED** [review]
I didn't check every single replacement, but a scan (no pun intended) says this is good.

**Comment by nickvigilante** [comment]
@stbof Nothing funky is happening with the version switcher, so I'm merging.

**Pull request merged**
