### PR TITLE
CC Release Notes May 2021

### PR DESCRIPTION
**Pull request by gemma-shay**
Release notes for May 3, 2021

Closes: https://cockroachlabs.atlassian.net/browse/CC-3656?atlOrigin=eyJpIjoiZGRmZjUwZTFlNDM5NDYzYmEzNTEwYjY4ODJiZjBlNmYiLCJwIjoiaiJ9

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/cockroachcloud-05032021.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTJJV4AqI2dSGrXOED:-MZTJJV4AqI2dSGrXOEE:b-ri8s1z) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L13)):*
> ```Markdown
> {% include marketo.html %}
> 
> ### General changes
> ```

I checked for feature flags that were enabled since the last release notes (https://cockroachlabs.atlassian.net/issues/?filter=10275&jql=project%20in%20(SREOPS)%20AND%20issuetype%20%3D%20%22Feature%20Flag%22%20AND%20statusCategory%20%3D%20Done%20AND%20statusCategoryChangedDate%20%3E%3D%202021-04-05) and it looks like GitHub auth was enabled in the past month. This should be added to the release notes.
___
*[releases/cockroachcloud-05032021.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTHmye5ckg5D_tlHM0:-MZTHmye5ckg5D_tlHM1:b-pfc0ju) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L16)):*
> ```
> Free clusters
> ```

nit: change to `CockroachCloud Free` and maybe link to the Quickstart
___
*[releases/cockroachcloud-05032021.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTI04A0KvgDYSwXD5N:-MZTI04A0KvgDYSwXD5O:b-ytoddz) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L16)):*
> ```Markdown
> 
> - New CockroachCloud clusters will now run CockroachDB [v20.2.8](v20.2.8.html).
> - Free clusters are now available in four new regions: GCP `europe-west1`, GCP `asia-southeast1`, AWS `eu-west-1`, and AWS `ap-southeast-1`.
> ```

Let's make this a list, like:

- GCP: `europe-west1', `asia-southeast1`
- AWS: ...
___
*[releases/cockroachcloud-05032021.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTHw6J2_LABuE0VWm2:-MZTHw6J2_LABuE0VWm3:b-uuk490) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L20)):*
> ```Markdown
> ### Console changes
> 
> - Emails sent from CockroachCloud to users now have updated style and copy.
> ```

We can delete this one
___
*[releases/cockroachcloud-05032021.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTIMyo9HKEXfMt2Vg-:-MZTIMyo9HKEXfMt2Vg0:b-e401y9) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L21)):*
> ```Markdown
> 
> - Emails sent from CockroachCloud to users now have updated style and copy.
> - When login fails due to user input, the error message now includes [login method](../cockroachcloud/create-an-account.html#change-your-login-method) as a potential reason for failure.
> ```

nit: `When login fails` > `When logging in fails`
___
*[releases/cockroachcloud-05032021.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTIdIrEeV5TT3NX9O9:-MZTIdIrEeV5TT3NX9OA:b-esu6ww) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L27)):*
> ```Markdown
> ### Bug fixes
> 
> - Previously, the **Name** field in the **Reset Password** form didn't align with the **Password** field. Now they are the same width.
> ```

We can delete this one too - I don't think users will care :)
___
*[releases/cockroachcloud-05032021.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTIjgf5K-OzrtzA4yc:-MZTIjgf5K-OzrtzA4yd:brg6vav) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L28)):*
> ```Markdown
> 
> - Previously, the **Name** field in the **Reset Password** form didn't align with the **Password** field. Now they are the same width.
> - **Contact Us** links now direct users to [customer support portal](https://support.cockroachlabs.com/) instead of the user's mail app.
> ```

nit: `to customer support portal` > `to the customer support portal`

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[releases/cockroachcloud-05032021.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTJJV4AqI2dSGrXOED:-MZTa82-DoaxPIrUI-eb:b-yxhqn8) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L13)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I checked for feature flags that were enabled since the last release notes (https://cockroachlabs.atlassian.net/issues/?filter=10275&jql=project%20in%20(SREOPS)%20AND%20issuetype%20%3D%20%22Feature%20Flag%22%20AND%20statusCategory%20%3D%20Done%20AND%20statusCategoryChangedDate%20%3E%3D%202021-04-05) and it looks like GitHub auth was enabled in the past month. This should be added to the release notes.
</blockquote></details>

Done. Not sure why it didn't show up in generated notes..?
___
*[releases/cockroachcloud-05032021.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTI04A0KvgDYSwXD5N:-MZTSzH4C-QYXHf7mCHD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L16)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Let's make this a list, like:

- GCP: `europe-west1', `asia-southeast1`
- AWS: ...
</blockquote></details>

Done.
___
*[releases/cockroachcloud-05032021.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTHw6J2_LABuE0VWm2:-MZTTE324fKNZmr3pFhE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L20)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

We can delete this one
</blockquote></details>

Done.
___
*[releases/cockroachcloud-05032021.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZTIdIrEeV5TT3NX9O9:-MZTTKAU6ZRuFkXLTCjP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6c2f586e97a8fd7bcd9709a8b2bcab0e6a7b4ef0/releases/cockroachcloud-05032021.md#L27)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

We can delete this one too - I don't think users will care :)
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448#-:-MZTffw29kvHhuC570xv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by lnhsingh — COMMENTED** [review]
Whoops, preemptively added that! Still need to add a note for the GitHub Auth. Once that's added, please send to the PM(s) to review (probably just Lakshmi and maybe Emily for GH auth)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448#-:-MZTfiH17KR_cX-PclNd:b-qwc281)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by gemma-shay** [comment]
@lnhsingh I put GitHub Auth in Console changes, should it be General?

**Review by lnhsingh — COMMENTED** [review]
Ah, good point. I think it could be kept there, though now that I think about it... is there a difference between General vs Console really? Maybe we should combine the two sections into General. I'm not sure if it's worth delineating between the two right now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448#-:-MZToXHW5Dq0ucQI1Uqb:b-yvxxwz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by emily-horing — APPROVED** [review]
Added 2 nits but lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448#-:-MZUALbxACBzLyW0gZAQ:b-gy4vne)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gemma-shay, @kannanlakshmi, and @lnhsingh)

___
*[releases/cockroachcloud-05032021.md, line 16 at r2](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZU9BJ_D-i4Bfj8GOLk:-MZU9BJ_D-i4Bfj8GOLl:b-2e8dkz) ([raw file](https://github.com/cockroachdb/docs/blob/7cb807eae4c7c11e8c7c3aef4871cb850c23c616/releases/cockroachcloud-05032021.md#L16)):*
> ```Markdown
> 
> - New CockroachCloud clusters will now run CockroachDB [v20.2.8](v20.2.8.html).
> - [CockroachCloud Free](../cockroachcloud/quickstart.html) clusters are now available in four new regions:
> ```

nit: I would add "additional" regions, so it's clear that we did not remove the previous ones.
___
*[releases/cockroachcloud-05032021.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZUAw9Q91N-vAoay1yf:-MZUAw9Q91N-vAoay1yg:bjsicv8) ([raw file](https://github.com/cockroachdb/docs/blob/7cb807eae4c7c11e8c7c3aef4871cb850c23c616/releases/cockroachcloud-05032021.md#L22)):*
> ```Markdown
> ### Console changes
> 
> - New users can now [sign up](../cockroachcloud/create-an-account.html) for CockroachCloud with Github Authorization. Current users can [switch their login method](../cockroachcloud/create-an-account.html#change-your-login-method) between email and GitHub.
> ```

It would be nice to add that users can then use Github's 2FA to enforce 2FA on their CC account

**Review by kannanlakshmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gemma-shay and @lnhsingh)

___
*[releases/cockroachcloud-05032021.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZUC_YkEvwxfR2MO5Xo:-MZUC_YkEvwxfR2MO5Xp:b-lj82p9) ([raw file](https://github.com/cockroachdb/docs/blob/7cb807eae4c7c11e8c7c3aef4871cb850c23c616/releases/cockroachcloud-05032021.md#L24)):*
> ```Markdown
> - New users can now [sign up](../cockroachcloud/create-an-account.html) for CockroachCloud with Github Authorization. Current users can [switch their login method](../cockroachcloud/create-an-account.html#change-your-login-method) between email and GitHub.
> - When logging in fails due to user input, the error message now includes [login method](../cockroachcloud/create-an-account.html#change-your-login-method) as a potential reason for failure.
> - In the **Send test email** form on the [**Alerts** page](../cockroachcloud/alerts-page.html), three new node-level options have been added to the **Alert type** dropdown menu, a success message is now shown when a test email is sent, and the recipient list is now reset after a successful send.
> ```

Did we ever add that "Alerts" are released as a feature? I didn't see that in the April release notes. cc @thtruo 
Also, are the statements, transactions and sessions pages still behind feature flags @thtruo

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gemma-shay, @lnhsingh, and @thtruo)

___
*[releases/cockroachcloud-05032021.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZUC_YkEvwxfR2MO5Xo:-MZUEg0oDfQSdpRrfbDa:b-m501hb) ([raw file](https://github.com/cockroachdb/docs/blob/7cb807eae4c7c11e8c7c3aef4871cb850c23c616/releases/cockroachcloud-05032021.md#L24)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

Did we ever add that "Alerts" are released as a feature? I didn't see that in the April release notes. cc @thtruo 
Also, are the statements, transactions and sessions pages still behind feature flags @thtruo 
</blockquote></details>

There were only 2 Jira issues related to feature flags closed since the last release notes were published: https://cockroachlabs.atlassian.net/issues/?filter=10275&jql=project%20in%20(SREOPS)%20AND%20issuetype%20%3D%20%22Feature%20Flag%22%20AND%20statusCategory%20%3D%20Done%20AND%20statusCategoryChangedDate%20%3E%3D%202021-04-05 and it looks like the feature flag for Alerts was only enabled for our internal org - is this correct?

I guess to clarify:  if the Alerts page is still behind a feature flag, that means this release note should be removed from this month's release notes since it's not available to end-users yet-- right?

**Comment by thtruo** [comment]
Correct, Alerts has only been enabled on our internal prod org and is not yet available to all end users yet. We're in the process of working with SREs to get this out to all users which may roll past the weekend.  

> I guess to clarify: if the Alerts page is still behind a feature flag, that means this release note should be removed from this month's release notes since it's not available to end-users yet-- right?

Yep that's correct

> Also, are the statements, transactions and sessions pages still behind feature flags

Statements and Sessions are still behind a feature flag and not yet available to all users (note: the Transactions page was not an active feature so that won't be included).  It is in the same boat as Alerts regarding progress of rolling it out to all users in prod.

cc @kannanlakshmi  @lnhsingh

**Review by lnhsingh — COMMENTED** [review]
A couple small nits, but LGTM otherwise - feel free to merge once edited!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448#-:-MZmhpyb0oB5DJzk8ye9:b-dxy3h9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @emily-horing, @gemma-shay, @lnhsingh, and @thtruo)

___
*[releases/cockroachcloud-05032021.md, line 22 at r3](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZmhC_W24N0Or5Dzx_b:-MZmhC_X07q285OMWIMA:b-hq9841) ([raw file](https://github.com/cockroachdb/docs/blob/579d1a12ba0decff57c62276df5747efe80b1706/releases/cockroachcloud-05032021.md#L22)):*
> ```Markdown
> ### Console changes
> 
> - New users can now [sign up](../cockroachcloud/create-an-account.html) for CockroachCloud with Github Authorization. Current users can [switch their login method](../cockroachcloud/create-an-account.html#change-your-login-method) between email and GitHub. Logging in with GitHub allows users to enforce [GitHub's two-factor authentication (2FA)](https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa) on their CockroachCloud account.
> ```

Style suggestion: Swap the order of the second and third sentences here to make it flow better (since the first and third sentences talk about signing in with GH and the second sentence is about switching login methods)
___
*[releases/cockroachcloud-05032021.md, line 24 at r3](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZmhijl2GNHEPLI2HCU:-MZmhijl2GNHEPLI2HCV:b5d4799) ([raw file](https://github.com/cockroachdb/docs/blob/579d1a12ba0decff57c62276df5747efe80b1706/releases/cockroachcloud-05032021.md#L24)):*
> ```
> while [creating a cluster](../cockroachcloud/create-a-free-cluster.html) reset
> ```

nit: should this be `would reset`?

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10448)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @emily-horing, @lnhsingh, and @thtruo)

___
*[releases/cockroachcloud-05032021.md, line 22 at r3](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZmhC_W24N0Or5Dzx_b:-MZmotQ29oxw28dN6Xua:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/579d1a12ba0decff57c62276df5747efe80b1706/releases/cockroachcloud-05032021.md#L22)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Style suggestion: Swap the order of the second and third sentences here to make it flow better (since the first and third sentences talk about signing in with GH and the second sentence is about switching login methods)
</blockquote></details>

Done.
___
*[releases/cockroachcloud-05032021.md, line 24 at r3](https://reviewable.io/reviews/cockroachdb/docs/10448#-MZmhijl2GNHEPLI2HCU:-MZmod-zB6BKi5H-En_x:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/579d1a12ba0decff57c62276df5747efe80b1706/releases/cockroachcloud-05032021.md#L24)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

> ```
> while [creating a cluster](../cockroachcloud/create-a-free-cluster.html) reset
> ```

nit: should this be `would reset`?
</blockquote></details>

Done.

**Pull request merged**
