### PR TITLE
Update default range size from 64 to 512 MiB

### LINKED ISSUE #5971: Increase maximum storage per node
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recO3yD744y8oNI3Y

Description: In 19.2, CockroachDB default range size is 64MiB and falls over at roughly 1TB per node. With this change, CockroachDB has a default range size that's higher than 64MiB and stores up to 10TB per node.

--

Customer Problem: Cost

The problem that his feature addresses is cost for customers with on-prem hosts that can store significantly more than 1TB. When running CRDB, they are forced to add more nodes to their deployments than necessary if Cockroach could support more data per node. Ultimately, customers have to pay more than necessary because they have to pay for more nodes.

Team: John Kendall, Andrew Werner, Andrew Kryczka

Github Tracking Issue: https://github.com/cockroachdb/cockroach/pull/31663 https://github.com/cockroachdb/docs/issues/5971

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #5971.

Summary of changes:

- Update all mentions of the default range size to the new value in
  CockroachDB v20.1: 512 MiB.

- Update 'Known Limitations' to mention that a single SQL statement can
  perform at most $new_range_size worth of updates.

### CODE REVIEW

**Comment by rmloveland** [comment]
@ajwerner beyond the other mechanical changes here that are basically `s/64 MiB/512 MiB/g`, I had one more question since this stood out as the same "magic number" as the (previous) range size:

- We currently have a known limitation that ["A single statement can perform at most 64MiB of combined updates"](https://www.cockroachlabs.com/docs/dev/known-limitations.html#write-and-update-limits-for-a-single-statement). That seems like a magic number based on the previous range size. Will this limit on a single SQL statement now rise to 512 MiB?

**Comment by rmloveland** [comment]
Update: the known limitation referenced in my previous comment has been removed.

I'll rebase this PR on master and update.

**Comment by rmloveland** [comment]
Andrew, the only semi-nuanced part of this PR is the part that removes mention of "increase the default range size to 128 MiB" from the 'cold start of large clusters' known limitation (mentioned in #7188).  Since that action is obviously meaningless in 20.1-world.

My assessment of the known limitation is that it has not actually been addressed (based on what is in evidence in GH at least), since the related issues are still open.  Therefore I have only deleted the paragraph re: upping the range size, for now, as part of the minimal change that will address this issue (64 -> 512).

Anyway this is RFAL. Thanks!

**Comment by rmloveland** [comment]
Hey @ajwerner I'd love to pass this along for docs team review unless you think there are any errors here.  Mostly a mechanical change (and thus tedious to review, I know - sorry!).

Sorry to ping again, just trying to get things merged by Monday for the 20.1 release.

**Comment by ajwerner** [comment]
:lgtm: - sorry for the delay

**Pull request merged**
