### PR TITLE
Expanding docs CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jseldess**
Adding @sploiselle's new **Keep Contributing** section, which helps contributors stay in sync with updates to `cockroachdb/docs`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/344)

### CODE REVIEW

**Comment by jseldess** [comment]
@sploiselle, let me know if I missed anything.

**Comment by sploiselle** [comment]
@jseldess LGTM! 

I dug up why this went so far south for me and figured it out (it all starts out with the fact that I didn't create a branch for the changes to --http-port in my local fork). I'm going to get something for that drafted tonight because I cannot find anyone who's documented it front-to-back from an actual user's perspective. I'll throw it in a Gist and you can see if it's something that you think linking to would be useful.

**Comment by jseldess** [comment]
Sounds good. Look forward to reading that. 

For me, I've prevent this from happening by having multiple branches in my fork, one per PR I intend to open. I don't commit to my gh-pages branch, so before creating a new branch, I always switch back to gh-pages so as to not carry unwanted commits to the new branch.

**Comment by uptimeDBA** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/344#-KJD0PblWuXUg2u2KSDG:-KJD0PblWuXUg2u2KSDH:-176750677) ([raw file](https://github.com/cockroachdb/docs/blob/283d8c6f3e96bd4351ec63a46494997a444b0ef4/CONTRIBUTING.md#L38)):*
> ```Markdown
> 
>     ``` shell
>     $ git remote add --track gh-pages upstream https://github.com/cockroachdb/docs.git
> ```

FYI As a git newbie, the `--track gh-pages` was something I missed when adding the upstream repo. I was getting everything when I `fetch`ed. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/344)*

**Pull request merged**
