### PR TITLE
Add database object sizing considerations and limits info

### PR DESCRIPTION
**Pull request by mikeCRL**
Initial PR to publish this information per https://github.com/cockroachdb/docs/issues/1830, https://github.com/cockroachdb/docs/issues/10031, and the internal SSOT sheet https://docs.google.com/spreadsheets/d/1JWqggZ1tZ_wDI_lrvWdEBtge4hQFvXEZYczQtMhkRjI/.

Going forward, efforts to gather further information for discovering limits or sizing best practices can be addressed separately in the respective issues (or otherwise as separate topics).

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[v20.2/schema-design-overview.md, line 113 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZnZzY826zCmEZ8yDw:-MWZnZzY826zCmEZ8yDx:b-b2wxft) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L113)):*
> ```Markdown
> 
> - The number of databases or schemas has minimal impact as compared to the total number of tables and their complexity.
> - Increasing RAM may have the greatest impact on performance. Increasing the number of nodes will not have a substantial effect.
> ```

Instead of "performance", I'd say "greatest impact on the number of tables that can be supported". 
___
*[v20.2/schema-design-overview.md, line 123 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZoTeEDm--Dxr8VJzE:-MWZoTeEDm--Dxr8VJzF:bnxe70n) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L123)):*
> ```Markdown
> - the number of tables in a database or cluster.
> - the number of the following objects per table, database, or cluster:
>   - rows
> ```

The number of rows is in a separate category than the rest of these. For everything else on this list, the limiting factor is the total size of all the schema objects (and the limit is based on the amount of RAM per node, so adding more nodes doesn't help). But you can have as many rows as you want by adding more nodes and storage. 
___
*[v20.2/schema-design-overview.md, line 131 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZpX8QE1KoAFn6G7GJ:-MWZpX8QE1KoAFn6G7GK:b2vih3g) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L131)):*
> ```Markdown
> - the length of identifiers. Note:
>   - a maximum of 128 bytes is recommended for identifiers and may be enforced in future versions of CockroachDB. For compatibility with other databases, CockroachDB has a `max_identifier_length` variable set to 128. This is a reported value that is not currently enforced.
>   - this does not apply to role or user names, which have a limit of 63 bytes, among other [restrictions](create-role.html#role-name-limitations).
> ```

There are several levels of negation here (the top level "no hard limits", then "this does not apply to role or user names"). I'd add a table/list above the "while practical limitations exist" paragraph to list the cases where there are actually hard limits (and go ahead and say there is a 128 byte limit for identifiers, with the fact that it's not currently enforced as a footnote). 
___
*[v20.2/schema-design-overview.md, line 133 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZq5DD1WfmVDcr-3v7:-MWZq5DD1WfmVDcr-3v8:b-clqwm8) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L133)):*
> ```Markdown
>   - this does not apply to role or user names, which have a limit of 63 bytes, among other [restrictions](create-role.html#role-name-limitations).
> 
> By default, a [range](architecture/overview.html#terms) automatically [splits](architecture/distribution-layer.html#range-splits) into two ranges when it reaches 512MiB in size. You can also choose to [manually split ranges](https://www.cockroachlabs.com/docs/stable/split-at.html) at a specified row in a table or index. The size of each range will continue to be within the 512MiB limit, in this case.
> ```

This paragraph feels out of place here - what is a user supposed to take away from it in this context?

**Review by mikeCRL — COMMENTED** [review]
@bdarnell Thanks for the review. Please see my replies and review the updated draft.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MW_uyYoCGC19mMbtCXR:br0nijv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[v20.2/schema-design-overview.md, line 113 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZnZzY826zCmEZ8yDw:-MW_r2TFCdOOwxgN3mBI:b-mr073q) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L113)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Instead of "performance", I'd say "greatest impact on the number of tables that can be supported". 
</blockquote></details>

Done. Additionally I updated the first sentence of the section to mention "support" instead of performance. Please let me know if you want to bring it back.
___
*[v20.2/schema-design-overview.md, line 123 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZoTeEDm--Dxr8VJzE:-MW_kHggCqL-4TWAO7QR:b-nms5wl) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L123)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The number of rows is in a separate category than the rest of these. For everything else on this list, the limiting factor is the total size of all the schema objects (and the limit is based on the amount of RAM per node, so adding more nodes doesn't help). But you can have as many rows as you want by adding more nodes and storage. 
</blockquote></details>

Rewrote to reflect the above.

- I included tables among the schema objects that are RAM-limited.
- I now mention that "CockroachDB can support any number of rows by adding additional nodes and storage." Does this need a caveat (e.g. if there's a theoretical limitation of nodes per cluster)?
___
*[v20.2/schema-design-overview.md, line 131 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZpX8QE1KoAFn6G7GJ:-MW_sFJV1lykPzajdbO9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L131)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There are several levels of negation here (the top level "no hard limits", then "this does not apply to role or user names"). I'd add a table/list above the "while practical limitations exist" paragraph to list the cases where there are actually hard limits (and go ahead and say there is a 128 byte limit for identifiers, with the fact that it's not currently enforced as a footnote). 
</blockquote></details>

Done.
___
*[v20.2/schema-design-overview.md, line 133 at r3](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWZq5DD1WfmVDcr-3v7:-MW_sLcTC39Y2ba8y5iB:b-6f32yh) ([raw file](https://github.com/cockroachdb/docs/blob/88a36fc2a3858d3381703f4fc143450fb247a06b/v20.2/schema-design-overview.md#L133)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This paragraph feels out of place here - what is a user supposed to take away from it in this context?
</blockquote></details>

Removed. There is content to be found if one performs a search; I don't want to cause confusion by mixing topics here.

**Comment by mikeCRL** [comment]
@bdarnell The focus is now heavily on the "quantity" of schema objects but I'm wondering if there's a way we can/should clarify the impact of the size of the data itself within these objects.

**Review by bdarnell — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MWdzOWw6k9-AaGm4sNa:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell)

**Comment by mikeCRL** [comment]
TFTR, @bdarnell. Assigning to @taroface for docs writer review before merging.

**Review by taroface — CHANGES_REQUESTED** [review]
A couple suggestions and questions!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MWePfhJ0WL_PcZgnruh:bdjojpm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @mikeCRL)

___
*[v20.2/schema-design-overview.md, line 106 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe1BCJ1ldJtJErCiYJ:-MWe1BCJ1ldJtJErCiYK:b7wzleq) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L106)):*
> ```Markdown
> ## Object size and scaling considerations
> 
> CockroachDB does not place hard limits on most database objects, however, there are scenarios where extremely large attributes may not be supported.
> ```

Suggest splitting into 2 sentences:

`...on most database objects. However, ...`

Also, I think the statement "does not place hard limits" followed by the "Hard limits" heading is somewhat counterintuitive. What do you think about rephrasing the sentence to something like:

`...extremely large attributes are not supported in certain scenarios, described below.`
___
*[v20.2/schema-design-overview.md, line 120 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5F1561khGvvU2D1h:-MWe5F1561khGvvU2D1i:b-22v19h) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L120)):*
> ```Markdown
> ### Quantity of tables and other schema objects
> 
> CockroachDB has been shown to perform well with clusters containing 2,500 tables. Greater numbers are possible, depending on the complexity of the tables (number of columns and indexes) and system specifications.
> ```

Wondering if it can be clearer what "system specifications" refers to, e.g., machine size?
___
*[v20.2/schema-design-overview.md, line 124 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5TIC8ep23MYCzWMY:-MWe5TIC8ep23MYCzWMZ:bylcd87) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L124)):*
> ```Markdown
> As you scale to a large number of tables, note that:
> 
> - The amount of RAM per node is the limiting factor for the number of tables and other schema objects the cluster can support. This includes columns, indexes, inverted indexes, constraints, and partitions. Increasing RAM is likely to have the greatest impact, while increasing the number of nodes will not have a substantial effect.
> ```

In the last sentence, suggest reiterating for clarity, e.g., "greatest impact on limits"

Actually just saw Ben's comment below, and wonder if it is meant to apply here? 
___
*[v20.2/schema-design-overview.md, line 125 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWeOsKu50hq61poRyBB:-MWeOsKu50hq61poRyBC:b-3slmkq) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L125)):*
> ```Markdown
> 
> - The amount of RAM per node is the limiting factor for the number of tables and other schema objects the cluster can support. This includes columns, indexes, inverted indexes, constraints, and partitions. Increasing RAM is likely to have the greatest impact, while increasing the number of nodes will not have a substantial effect.
> - The number of databases or schemas has minimal impact as compared to the total number of tables and their complexity.
> ```

I find the second bullet hard to understand right now. The first bullet describes the impact of RAM on table limits, but this one refers to the impact of databases/schemas on - is it also the table limits? If so, maybe replace "as compared to" with "on"?

I might be completely off here!

**Review by mikeCRL — COMMENTED** [review]
TFTR @taroface! Please see my edits and one follow-up question.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MWe_ueXDlC8t4R_NWZI:b6ii1g9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @taroface)

___
*[v20.2/schema-design-overview.md, line 106 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe1BCJ1ldJtJErCiYJ:-MWeYMhWCYz-d4kIjhoz:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L106)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest splitting into 2 sentences:

`...on most database objects. However, ...`

Also, I think the statement "does not place hard limits" followed by the "Hard limits" heading is somewhat counterintuitive. What do you think about rephrasing the sentence to something like:

`...extremely large attributes are not supported in certain scenarios, described below.`
</blockquote></details>

Done.
___
*[v20.2/schema-design-overview.md, line 120 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5F1561khGvvU2D1h:-MWeXdKt1VJGUYQRGFl8:b-a5cjyg) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L120)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Wondering if it can be clearer what "system specifications" refers to, e.g., machine size?
</blockquote></details>

First, I've replaced this term with "hardware specifications" for better clarity.

I also added a link out to the hardware recommendations (Production Checklists) near the end of the section to help complete the picture. So the intro sentence remains open-ended, then we cover some detail about the key factor here (RAM), and now there's a path to learn about other ways to ensure performance depending on the expected type of workloads.

I then added a reference back from the Production Checklist (CPU and memory section).
___
*[v20.2/schema-design-overview.md, line 124 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5TIC8ep23MYCzWMY:-MWe__0kE-klk6fSYnNy:b-xw5wuy) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L124)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

In the last sentence, suggest reiterating for clarity, e.g., "greatest impact on limits"

Actually just saw Ben's comment below, and wonder if it is meant to apply here? 
</blockquote></details>

@taroface I'm not totally sure which sentence and which of Ben's comments you are referring to. Could you please clarify, but maybe take a look at my latest edits first to see if this still applies? Happy to take another look after that.
___
*[v20.2/schema-design-overview.md, line 125 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWeOsKu50hq61poRyBB:-MWeZCgy4okCyU8N-w4w:b9dfuu3) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L125)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I find the second bullet hard to understand right now. The first bullet describes the impact of RAM on table limits, but this one refers to the impact of databases/schemas on - is it also the table limits? If so, maybe replace "as compared to" with "on"?

I might be completely off here!
</blockquote></details>

Rephrased.

**Review by taroface — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @mikeCRL, and @taroface)

___
*[v20.2/recommended-production-settings.md, line 57 at r8](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWf2ezB49E8Aco4KHRc:-MWf2ezB49E8Aco4KHRd:b-glzdop) ([raw file](https://github.com/cockroachdb/docs/blob/b8e3684c90a40de7d1fd2e2dc85bc7ac717d0e8d/v20.2/recommended-production-settings.md#L57)):*
> ```Markdown
> - To optimize for resiliency, use many smaller nodes instead of fewer larger nodes. Recovery from a failed node is faster when data is spread across more nodes.
> 
> - To optimize for the support of large numbers of tables, increase the amount of RAM. For more information, see [Quantity of tables and other schema objects](schema-design-overview.html#quantity-of-tables-and-other-schema-objects). Supporting a large number of rows is a matter of [Storage](#storage).
> ```

This is awesome!
___
*[v20.2/schema-design-overview.md, line 106 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe1BCJ1ldJtJErCiYJ:-MWf3E9b0v9XG-lIvYDT:b-iwzxkp) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L106)):*
> ```
> CockroachDB does not place hard limits on most database objects, however, extremely large attributes are not supported in certain scenarios.
> ```

This part still looks the same as before to me. Maybe Reviewable is borked?
___
*[v20.2/schema-design-overview.md, line 124 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5TIC8ep23MYCzWMY:-MWf2vle-dDRoplHeXvz:b1a2inx) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L124)):*
> ```
> Increasing RAM is likely to have the greatest impact
> ```

Sorry, I'm referring to this sentence. It was just a suggestion to reiterate/clarify what exactly is being impacted by increasing RAM.

Ben's comment was: 

> Instead of "performance", I'd say "greatest impact on the number of tables that can be supported".

I thought it might also be referring to the above snippet, but perhaps you addressed that elsewhere and I just didn't see it.

**Review by mikeCRL — COMMENTED** [review]
@taroface Thanks again. Made a minor edit to catch this up with your suggestions in full. No need to re-review, I think - just let me know if you disagree with any of my replies.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MWismvHB6vDpTbgpE2H:bwg85xg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @taroface)

___
*[v20.2/recommended-production-settings.md, line 57 at r8](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWf2ezB49E8Aco4KHRc:-MWio0MFBCF7nf3RtORg:b44tpx) ([raw file](https://github.com/cockroachdb/docs/blob/b8e3684c90a40de7d1fd2e2dc85bc7ac717d0e8d/v20.2/recommended-production-settings.md#L57)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This is awesome!
</blockquote></details>

👍
___
*[v20.2/schema-design-overview.md, line 106 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe1BCJ1ldJtJErCiYJ:-MWinMly9P4E68HsaYcT:b8w6hfv) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L106)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> CockroachDB does not place hard limits on most database objects, however, extremely large attributes are not supported in certain scenarios.
> ```

This part still looks the same as before to me. Maybe Reviewable is borked?
</blockquote></details>

Sorry, the borking was all on my end. Really fixed this time. I wrote "...as described in this section" as opposed to "below" because I didn't want to imply I was referring to the immediate/first subsection (on Hard Limits) but rather the ones after that.
___
*[v20.2/schema-design-overview.md, line 124 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5TIC8ep23MYCzWMY:-MWipD9ICqwLkVxGRB2z:becfteq) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L124)):*
Ah yes, thanks to your comments I'd ensured this was clearer in my previous edit.

Here, it's clear from the context of the first sentence.

> - The amount of RAM per node is the limiting factor for the number of tables and other schema objects the cluster can support. [...] Increasing RAM is likely to have the greatest impact, while [...]

Here, it's been added explicitly.

> - The number of databases or schemas on the cluster has minimal impact on the total number of tables that it can support. (here it's been added explicitly)

**Review by mikeCRL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @taroface)

___
*[v20.2/schema-design-overview.md, line 124 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5TIC8ep23MYCzWMY:-MXIu60f8VcAt8xV3QQd:b8y0geo) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L124)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Ah yes, thanks to your comments I'd ensured this was clearer in my previous edit.

Here, it's clear from the context of the first sentence.

> - The amount of RAM per node is the limiting factor for the number of tables and other schema objects the cluster can support. [...] Increasing RAM is likely to have the greatest impact, while [...]

Here, it's been added explicitly.

> - The number of databases or schemas on the cluster has minimal impact on the total number of tables that it can support. (here it's been added explicitly)
</blockquote></details>

Actually, this could still be clearer. I pushed another commit to clarify it.

**Comment by mikeCRL** [comment]
Awaiting sign-off on the latest edits from @bdarnell and @taroface. I'd like to confirm that this has remained technically accurate before publishing this and communicating it internally. Thank you.

**Review by taroface — APPROVED** [review]
:lgtm_strong: Looks great.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MXJB_671pKGqglmTmvM:bx0ho00)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @mikeCRL, and @taroface)

___
*[v20.2/schema-design-overview.md, line 124 at r6](https://reviewable.io/reviews/cockroachdb/docs/10035#-MWe5TIC8ep23MYCzWMY:-MXJBTI-CILMTm8kmhlO:bhuxl2z) ([raw file](https://github.com/cockroachdb/docs/blob/adbd54c3b4b11caf7af3a4ca12884b4e40308498/v20.2/schema-design-overview.md#L124)):*
<details><summary><i>Previously, mikeCRL (Mike Lewis) wrote…</i></summary><blockquote>

Actually, this could still be clearer. I pushed another commit to clarify it.
</blockquote></details>

This is crystal clear (to me) now :)

**Review by bdarnell — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r8, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10035#-:-MXXzq8W4e6stwRahoRI:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mikeCRL and @taroface)

**Comment by mikeCRL** [comment]
Ported to 21.1. Merging. Thanks, all.

**Pull request merged**
