### PR TITLE
Restyle TOC

### LINKED ISSUE #8065: Style ‘On this page’ (TOC)

### PR DESCRIPTION
**Pull request by yingzhuchin**
Fixes #8065.

Will merge into `docs-redesign` instead of `master` once reviewed.

### CODE REVIEW

**Comment by lnhsingh** [comment]
It's supposed to look like [this](https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2087%3A12650) right? I'm seeing this in the preview:

image

Also, when I hover I see the link icon:

image

Should that be there? If so, I think it should display at the end of the line, instead of underneath it.

**Comment by yingzhuchin** [comment]
Hi @lnhsingh, the link icon is from current production. I didn't see any reference to it in Figma, so I didn't modify it, but I've removed it now with the latest push. Is that better?

**Comment by lnhsingh** [comment]
Yes, looks better! Removing the icon helps with the line spacing between the headings too. Should there be a persistent grey line that the blue bar slides down?

**Comment by yingzhuchin** [comment]
> Yes, looks better! Removing the icon helps with the line spacing between the headings too. Should there be a persistent grey line that the blue bar slides down?

I don't think a grey line will work, since we have nested TOC headings. I discussed with Lucia here: https://cockroachlabs.slack.com/archives/C019NHZ819S/p1600271082017600?thread_ts=1600188259.004700&cid=C019NHZ819S

**Comment by lnhsingh** [comment]
Oh, got it! Sorry, I glanced at that thread and didn't realize it was discussing the grey line. Currently, when you navigate to a new page, the blue line doesn't appear until you start scrolling past the first section. Would it make sense for the blue line to display in the first heading whenever the page is loaded? The TOC looks kind of bare without it at the beginning-- thoughts @luciaaaaaaa ?

**Comment by jseldess** [comment]
@yingzhuchin, now when you hover over a heading, you no longer see an anchor link icon. I like that we've removed that icon from the TOC, but I think it's helpful to have them when hovering over a heading. Can we somehow achieve that?

**Comment by yingzhuchin** [comment]
> @yingzhuchin, now when you hover over a heading, you no longer see an anchor link icon. I like that we've removed that icon from the TOC, but I think it's helpful to have them when hovering over a heading. Can we somehow achieve that?

Done.

**Comment by yingzhuchin** [comment]
> Would it make sense for the blue line to display in the first heading whenever the page is loaded? The TOC looks kind of bare without it at the beginning-- thoughts @luciaaaaaaa ?

I worry this might be confusing because some pages can have lengthy intros before the first heading is introduced, in which case it doesn't make sense to highlight the heading until the user has reached that section?

**Comment by luciaaaaaaa** [comment]
Notes from our weekly catch up:

When we review final details in QA, @anagio will look at it to see if we can show the grey line and the blue line without nesting with a 'child' is selected.

**Review by jseldess — APPROVED** [review]
:lgtm: now. Thanks, @yingzhuchin!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8411#-:-MHvmyjF4-RgNVuGpxnj:blca6n7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @anagio, @jseldess, @lnhsingh, and @luciaaaaaaa)

**Comment by yingzhuchin** [comment]
Closing this PR and leaving the linked issue open so Peter can take a another look. I have merged the changes in this PR into `docs-redesign`.

**Pull request closed without merging**
