### PR TITLE
Migrate from Avro

### LINKED ISSUE #5961: Import from Avro format
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recoR5m8evEz6tMhG

Description: Enable Spanner users to migrate to CockroachDB by providing a facility to import the Avro + JSON format that Spanner uses for exports.

Team: 

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5961

### PR DESCRIPTION
**Pull request by lnhsingh**
- Added new page `migrate-from-avro.md`
- Added avro options and examples to `import.md`
- Added avro to `import-into.md`

TO DO:
- [x] Update SQL diagram - need to add `AVRO DATA` to the `IMPORT .. CSV` diagram
- [x] Update SQL diagram - need to add `AVRO DATA` to `IMPORT INTO` diagram

Closes #5961.

### CODE REVIEW

**Comment by lnhsingh** [comment]
@mwang1026 @miretskiy - can you review for technical correctness / completeness please?

**Comment by jseldess** [comment]
___
*[v20.1/import-into.md, line 66 at r3](https://reviewable.io/reviews/cockroachdb/docs/6768#-M1zwxN81HoSeR-tTErQ:-M1zwxN81HoSeR-tTErR:bp36ey9) ([raw file](https://github.com/cockroachdb/docs/blob/b8484b610834383a15600966550c8dd2e3785706/v20.1/import-into.md#L66)):*
> ```Markdown
>  Option  | Description   | Example
>  --------+---------------+----------
> `strict_validation`      | Rejects Avro records that do not have a one-to-one mapping between Avro fields to the target CockroachDB schema. By default, CockroachDB ignores unknown Avro fields and sets missing SQL fields to `NULL`. CockroachDB will also attempt to convert the Avro field to the CockroachDB [data type](migrate-from-avro#data-type-mapping); otherwise, it will report an error. | `IMPORT INTO foo (..) AVRO DATA ('file.avro') WITH strict_validation;`
> ```

This link is missing the `.html`

**Comment by jseldess** [comment]
___
*[v20.1/import-into.md, line 236 at r3](https://reviewable.io/reviews/cockroachdb/docs/6768#-M1zxBbf2qKtTUlfVUBb:-M1zxBbg5RUJhFaP-7kX:bn0qd3b) ([raw file](https://github.com/cockroachdb/docs/blob/b8484b610834383a15600966550c8dd2e3785706/v20.1/import-into.md#L236)):*
> ```Markdown
> ~~~
> 
> For more detailed information about importing data from Avro and examples, see [Migrate from Avro][avro].
> ```

I think this link will work like this?

**Comment by jseldess** [comment]
___
*[_includes/sidebar-data-v20.1.cockroachcloud.json, line 103 at r3](https://reviewable.io/reviews/cockroachdb/docs/6768#-M1zzczM1-iZ6IcJ2rdB:-M1zzczM1-iZ6IcJ2rdC:b-icqvoj) ([raw file](https://github.com/cockroachdb/docs/blob/b8484b610834383a15600966550c8dd2e3785706/_includes/sidebar-data-v20.1.cockroachcloud.json#L103)):*
> ```JSON
>               "/${VERSION}/migrate-from-avro.html"
>             ]
>           },
> ```

Need to remove this comma. That's the problem!

**Pull request merged**
