### PR TITLE
CBO supports COLLATE expressions

### LINKED ISSUE #4178: opt: support COLLATE expressions
PR: https://github.com/cockroachdb/cockroach/pull/32500

From release notes:
> Queries involving `COLLATE` expressions are now supported by the cost-based optimizer. [#32500][#32500] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #4178.

### CODE REVIEW

**Comment by jseldess** [comment]
@justinj, ping.

**Comment by justinj** [comment]
I don't think `COLLATE` belongs in this list, `COLLATE` is a scalar expression more akin to things like `1 + 2`, the rest of these are statements.

**Comment by justinj** [comment]
I don't think there should be any docs changes required for `COLLATE`.

**Comment by jseldess** [comment]
@justinj, I was responding to this release note:

> Queries involving COLLATE expressions are now supported by the cost-based optimizer. [#32500][#32500] {% comment %}doc{% endcomment %}

Did I misunderstand?

**Comment by justinj** [comment]
The release note is accurate, but the other things listed here aren't expressions, they're statements.

**Comment by jseldess** [comment]
Well, there's also mention of `FILTER` clauses and Sequences, so it's not all statements. But if you don't think any updates are needed, I'll just close this.

**Comment by justinj** [comment]
Ah, I didn't notice those, well the text above the list describes them as statements, so I would say those probably don't belong there either. Otherwise there is a very long list of features (basically all of SQL) that would need to be listed.

**Comment by jseldess** [comment]
@rmloveland, I'll leave it to you to decide what to list here and what not. Perhaps it's only important to list what's NOT covered by CBO at this point?

**Comment by rmloveland** [comment]
> @rmloveland, I'll leave it to you to decide what to list here and what not. Perhaps it's only important to list what's NOT covered by CBO at this point?

Good question, filed #4626 to address that (though probably after the 19.1 release).

**Pull request closed without merging**
