### PR TITLE
move footer email pop up

### PR DESCRIPTION
**Pull request by sploiselle**
Moved email sign up form to pop up at 75% of page height instead of at very bottom

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1024)

### CODE REVIEW

**Comment by jseldess** [comment]
@sploiselle, I can't get the pop up to show at all. Can you?

**Comment by jseldess** [comment]
@sploiselle, is this working for you? I still can't git it to pop up.

**Comment by sploiselle** [comment]
@jseldess It's working locally but not on the preview site.

**Comment by jseldess** [comment]
OK, I'll clone it and test locally, too.

**Comment by sploiselle** [comment]
@jseldess Fixed and ready for review!

**Comment by jseldess** [comment]
Fixes #983

**Pull request merged**
