### PR TITLE
CC October release notes

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/CC-3670

### CODE REVIEW

**Comment by jramos-crl** [comment]
@gemma-shay when are these supposed to go out? Specifically asking because of Serverless - is that expected to be part of a separate release note?

**Comment by gemma-shay** [comment]
They're going out Oct 4 for everything that changed over the past month, so Serverless will be the Nov notes.

**Comment by jramos-crl** [comment]
Sounds good 👍  looks good to me then. Thank you!

**Review by jramos-crl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11798#-:-Mkcd9qs81TLugpHHpVv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emily-horing, @kannanlakshmi, and @thtruo)

**Review by kannanlakshmi — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11798)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emily-horing, @jramos-crl, and @thtruo)

**Comment by emily-horing** [comment]
I think we could include these updates as well: https://cockroachlabs.atlassian.net/browse/CC-4743 + https://cockroachlabs.atlassian.net/browse/CC-4875

**Comment by gemma-shay** [comment]
thanks for catching those, Emily! added both but I'm kind of on the fence about including the accordion expansion.

**Comment by emily-horing** [comment]
Yeah I was thinking the same thing :) Up to you if you want to include it. I would maybe just say "CockroachCloud clusters now default to 3 regions for new users" or something if you do.

**Review by emily-horing — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11798#-:-MkcuKEG3TId-oAnmUMI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @kannanlakshmi and @thtruo)

**Review by thtruo — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11798)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @gemma-shay)

**Review by lnhsingh — APPROVED** [review]
:lgtm:

IMO, we just include the Serverless launch in the Nov notes and not do standalone notes for it (since Marketing will already be promoting it with a blog post, site changes, etc.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11798#-:-Mkmkpht-nNiZb2oxkfK:b-pfrqvu)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @gemma-shay and @thtruo)

___
*[releases/cockroachcloud-10042021.md, line 2 at r3](https://reviewable.io/reviews/cockroachdb/docs/11798#-Mkmk6Vo2fwIs6aB58yl:-Mkmk6Vo2fwIs6aB58ym:b5s1w40) ([raw file](https://github.com/cockroachdb/docs/blob/71895bd4dae7421a274feeca3c4daef4c4912eae/releases/cockroachcloud-10042021.md#L2)):*
> ```Markdown
> ---
> title: What's New in CockroachCloud
> ```

Just a comment to think about for later: We currently name our CC release note files `cockroachcloud-MMDDYYYY`. Once we change the product names, we should also think about possibly changing the structure of the release notes directory (maybe creating a `/cloud/` subdir?) or if we just want to keep it flat and prepend `cloud` instead of `cockroachcloud`

**Pull request merged**
