### PR TITLE
Admission control in v21.2

### LINKED ISSUE #11474: sql,server: add admission control for DistSQL responses
PR: https://github.com/cockroachdb/cockroach/pull/67531

From release notes:
> DistSQL response admission control can now be enabled using the [cluster setting](../v21.2/cluster-settings.html) `admission.sql_sql_response.enabled`. [#67531][#67531]

### PR DESCRIPTION
**Pull request by ianjevans**
This PR documents the new admission control system introduced in v21.2. The new Overload dashboard is documented as part of this PR.

Documents CRDB-2581.
Fixes #11474.

### CODE REVIEW

**Comment by ianjevans** [comment]
@sumeerbhola pinging to review your change requests.

**Review by vy-ton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12023)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ianjevans, @RaduBerinde, and @sumeerbhola)

___
*[v21.2/architecture/admission-control.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnaKoxXD5gMbXZ4V6ps:-MnaKoxY4YyLy-AAk9Hx:b-w00sql) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/architecture/admission-control.md#L7)):*
> ```Markdown
> ---
> 
> <span class="version-tag">New in v21.2:</span> CockroachDB implements an optional admission control system to maintain cluster performance and availability when some nodes experience high load. When admission control is enabled, CockroachDB sorts request and response operations into work queues by priority, giving preference to higher priority operations. Internal operations critical to node health, like node liveness heartbeats are high priority. The admission control system also prioritizes transactions that hold locks, to reduce contention by releasing locks in a timely manner.
> ```

We should indicate that "admission control is opt-in in 21.2, which could change in future releases"

**Comment by sumeerbhola** [comment]
> @sumeerbhola pinging to review your change requests.

Thanks, I'll look this afternoon. I wasn't aware that my comments had been addressed.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12023)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ianjevans, @RaduBerinde, and @sumeerbhola)

___
*[v21.2/transactions.md, line 192 at r3](https://reviewable.io/reviews/cockroachdb/docs/12023#-MmuD7sZ7VYg1oeM0fcJ:-Mnawzjz18KLVkZoMuT2:b-ns13y6) ([raw file](https://github.com/cockroachdb/docs/blob/e577b38383d32f7ccdd7a61a4446340ca88f9289/v21.2/transactions.md#L192)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we haven't plumbed transaction priority into the admission control system in this release, so we shouldn't be mentioning admission control here.
</blockquote></details>

This file shouldn't be changed in this PR -- I see a comma has been deleted.
___
*[v21.2/ui-overload-dashboard.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/12023#-MmuE7V4AkelRbg48KWI:-MnaxMx99HUXfRG36QIb:bysm5dp) ([raw file](https://github.com/cockroachdb/docs/blob/e577b38383d32f7ccdd7a61a4446340ca88f9289/v21.2/ui-overload-dashboard.md#L7)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> the files and subfiles in memory
> ```

There are no such things as subfiles and these are not in-memory.

this should say, "the health of the persistent store(s), which are implemented as log-structured merge trees" and refer to https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html


</blockquote></details>

Comment doesn't seem addressed.
___
*[v21.2/ui-overload-dashboard.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnaxskD7q6zWxHPS-sV:-MnaxskE687ovv0t-W-X:b2j19hr) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L29)):*
> ```Markdown
> Level 0 is the highest level of the LSM tree and consists of files containing the latest data written to the [Pebble storage engine](cockroach-start.html#storage-engine). High values indicate heavy write load that is causing accumulation of files in level 0. These files are not being compacted fast enough to lower levels.
> 
> - In the node view, the graph shows the health of the persitent store on the selected node.
> ```

persistent

same below

Should run spellcheck -- I didn't pay careful attention to spelling.
___
*[v21.2/ui-overload-dashboard.md, line 43 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-Mnayaj84w53lUh2QXYu:-Mnayaj84w53lUh2QXYv:b-qybch2) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L43)):*
> ```Markdown
> ## KV Admission IO Tokens Exhausted Duration Per Second
> 
> This graph indicates write I/O overload, which affects KV write operations to storage. This happens during transactions that have writes mutations. The admission control system dynamically calculates write tokens (similar to a [token bucket](https://en.wikipedia.org/wiki/Token_bucket)) to allow for high write throughput without severely overloading each store. This graph displays the microseconds that there were no write tokens left for arriving write requests. When there are no write tokens, these write requests are queued.
> ```

"writes mutations" is duplication. Let's just drop that sentence -- the reader who knows anything about what the KV layer is, will know that transactions that do writes cause KV writes.
___
*[v21.2/ui-overload-dashboard.md, line 43 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnaytxE75EqDZfdAPBs:-MnaytxE75EqDZfdAPBt:b-zhxaug) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L43)):*
> ```Markdown
> ## KV Admission IO Tokens Exhausted Duration Per Second
> 
> This graph indicates write I/O overload, which affects KV write operations to storage. This happens during transactions that have writes mutations. The admission control system dynamically calculates write tokens (similar to a [token bucket](https://en.wikipedia.org/wiki/Token_bucket)) to allow for high write throughput without severely overloading each store. This graph displays the microseconds that there were no write tokens left for arriving write requests. When there are no write tokens, these write requests are queued.
> ```

displays the microseconds per second ...

- not saying the per second part would indicate that this is showing the cumulative metric, which this is not -- it is showing the per-second rate
- the 2 bullets below also need fixing.
___
*[v21.2/ui-overload-dashboard.md, line 52 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnazSaV8pGp_gKNppUw:-MnazSaV8pGp_gKNppUx:bod7a1c) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L52)):*
> ```Markdown
> This graph shows the rate that operations within the admission control system are processed. There are lines for requests within the KV layer, write requests within the KV layer, responses between the KV and SQL layer, and responses within the SQL layer when receiving DistSQL responses.
> 
> This sums up the delay experienced by operations of each kind, and takes the rate per second. Dividing this rate by the rate observed in the admission work rate graph gives the mean delay experienced per operation.
> ```

this has been added to the wrong section. My comment was about the "Admission Delay Rate" section.

**Comment by ianjevans** [comment]
> > Reviewed 1 of 6 files at r1, 5 of 5 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12023)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ianjevans, @RaduBerinde, and @sumeerbhola)
> 
> _[v21.2/transactions.md, line 192 at r3](https://reviewable.io/reviews/cockroachdb/docs/12023#-MmuD7sZ7VYg1oeM0fcJ:-Mnawzjz18KLVkZoMuT2:b-ns13y6) ([raw file](https://github.com/cockroachdb/docs/blob/e577b38383d32f7ccdd7a61a4446340ca88f9289/v21.2/transactions.md#L192)):_
> 
> Previously, sumeerbhola wrote…
> This file shouldn't be changed in this PR -- I see a comma has been deleted.

The comma was not needed, so I removed it.

> _[v21.2/ui-overload-dashboard.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/12023#-MmuE7V4AkelRbg48KWI:-MnaxMx99HUXfRG36QIb:bysm5dp) ([raw file](https://github.com/cockroachdb/docs/blob/e577b38383d32f7ccdd7a61a4446340ca88f9289/v21.2/ui-overload-dashboard.md#L7)):_
> 
> Previously, sumeerbhola wrote…
> > > ```
> > > the files and subfiles in memory
> > > ```
> > 
> > 
> > There are no such things as subfiles and these are not in-memory.
> > this should say, "the health of the persistent store(s), which are implemented as log-structured merge trees" and refer to https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html
> 
> Comment doesn't seem addressed.

Missed that update in the overview paragraph, now fixed. The link to the storage layer doc is in the description of the graph below. The overview paragraph, IMO, shouldn't link off to different docs, as it is orienting the user to what graphs are on the dashboard.

> 
> _[v21.2/ui-overload-dashboard.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnaxskD7q6zWxHPS-sV:-MnaxskE687ovv0t-W-X:b2j19hr) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L29)):_
> 
> > ```gfm
> > Level 0 is the highest level of the LSM tree and consists of files containing the latest data written to the [Pebble storage engine](cockroach-start.html#storage-engine). High values indicate heavy write load that is causing accumulation of files in level 0. These files are not being compacted fast enough to lower levels.
> > 
> > - In the node view, the graph shows the health of the persitent store on the selected node.
> > ```
> 
> persistent
> 
> same below
> 
> Should run spellcheck -- I didn't pay careful attention to spelling.

Fixed.

> 
> _[v21.2/ui-overload-dashboard.md, line 43 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-Mnayaj84w53lUh2QXYu:-Mnayaj84w53lUh2QXYv:b-qybch2) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L43)):_
> 
> > ```gfm
> > ## KV Admission IO Tokens Exhausted Duration Per Second
> > 
> > This graph indicates write I/O overload, which affects KV write operations to storage. This happens during transactions that have writes mutations. The admission control system dynamically calculates write tokens (similar to a [token bucket](https://en.wikipedia.org/wiki/Token_bucket)) to allow for high write throughput without severely overloading each store. This graph displays the microseconds that there were no write tokens left for arriving write requests. When there are no write tokens, these write requests are queued.
> > ```
> 
> "writes mutations" is duplication. Let's just drop that sentence -- the reader who knows anything about what the KV layer is, will know that transactions that do writes cause KV writes.

Done.

> 
> _[v21.2/ui-overload-dashboard.md, line 43 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnaytxE75EqDZfdAPBs:-MnaytxE75EqDZfdAPBt:b-zhxaug) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L43)):_
> 
> > ```gfm
> > ## KV Admission IO Tokens Exhausted Duration Per Second
> > 
> > This graph indicates write I/O overload, which affects KV write operations to storage. This happens during transactions that have writes mutations. The admission control system dynamically calculates write tokens (similar to a [token bucket](https://en.wikipedia.org/wiki/Token_bucket)) to allow for high write throughput without severely overloading each store. This graph displays the microseconds that there were no write tokens left for arriving write requests. When there are no write tokens, these write requests are queued.
> > ```
> 
> displays the microseconds per second ...
> 
> * not saying the per second part would indicate that this is showing the cumulative metric, which this is not -- it is showing the per-second rate
> * the 2 bullets below also need fixing.

The phrase "microseconds per second" is a little confusing. Leaving it for now, but I'll think about a better way phrasing this.

> _[v21.2/ui-overload-dashboard.md, line 52 at r4](https://reviewable.io/reviews/cockroachdb/docs/12023#-MnazSaV8pGp_gKNppUw:-MnazSaV8pGp_gKNppUx:bod7a1c) ([raw file](https://github.com/cockroachdb/docs/blob/146565cfb122b72eccca1665f4cf38d1bb7df5cf/v21.2/ui-overload-dashboard.md#L52)):_
> 
> > ```gfm
> > This graph shows the rate that operations within the admission control system are processed. There are lines for requests within the KV layer, write requests within the KV layer, responses between the KV and SQL layer, and responses within the SQL layer when receiving DistSQL responses.
> > 
> > This sums up the delay experienced by operations of each kind, and takes the rate per second. Dividing this rate by the rate observed in the admission work rate graph gives the mean delay experienced per operation.
> > ```
> 
> this has been added to the wrong section. My comment was about the "Admission Delay Rate" section.

Fixed.

**Comment by ianjevans** [comment]
I'm going to merge this. If there's further edits, I'll create a follow-up PR.

**Pull request merged**
