### PR TITLE
Document how to truncate timeseries data sooner

### LINKED ISSUE #2180: ts: Make timeseries truncation threshold configurable
PR: https://github.com/cockroachdb/cockroach/pull/18632

From release notes:
> New cluster setting `timeseries.resolution_10s.storage_duration` can be used to reduce the storage used by built-in monitoring.

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #2180

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm: but I'd wait for @mrtracy to chime in as well. In particular, I think we'll want to explain how the two different controls (sampling frequency and storage duration) interact with each other, and I'm guessing it's not obvious judging by the name of the storage duration cluster setting.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2210#-:-Kzy8D39r35EoAejR0S9:b26qqgv)*

**Comment by mrtracy** [comment]
I would *not* document the second method at all; changing that setting is not tested, and I personally do not think it is plumbed through the system correctly.

**Comment by mrtracy** [comment]
Opened cockroachdb/cockroach/issues/20310 to follow up on my concerns with this setting.

**Comment by jseldess** [comment]
@mrtracy, I removed mention of that second method from the 1.2 docs. Should we also remove from the 1.1 and 1.0 docs? The cluster setting doesn't exist in those versions, so the env variable is the only way to affect timeseries data storage.

**Comment by mrtracy** [comment]
:lgtm:, thanks Jesse

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2210#-:-L-4K2pPoM5QwGNrQGjJ:bq9wyew)*

**Comment by jseldess** [comment]
Merging despite the still broken libpqxx c++ driver site.

**Pull request merged**
