### PR TITLE
Fix serverless content on use managed backups page

### PR DESCRIPTION
**Pull request by ashleykwtam**
- Fixed Serverless section due to missing content

Preview:
[Use Managed Service Backups](https://deploy-preview-16711--cockroachdb-docs.netlify.app/docs/cockroachcloud/use-managed-service-backups.html?filters=dedicated)

### CODE REVIEW

**Comment by ashleykwtam** [comment]
@kathancox when I worked on the epic [DOC-6759](https://github.com/cockroachdb/docs/pull/16528) it already addressed removing the 'Status' field. I noticed that the Serverless section was displaying incorrectly so this PR just updates that error.

**Comment by kathancox** [comment]
This LGTM to @ashleykwtam, but can you update the PR description and title of the PR as it doesn't reflect the error you're correcting here. It might be better to mark the JIRA in a way that we know that the status field was removed with the prior PR and that it doesn't need work.

**Review by kathancox — APPROVED** [review]
LGTM, let's merge this ASAP since content is missing from the page.

**Comment by ashleykwtam** [comment]
Done. Will update the JIRA accordingly, thanks Kathryn!

**Pull request merged**
