### PR TITLE
Add basic docs on multi-region zone configs

### LINKED ISSUE #9741: config/sql: add global_reads field to ZoneConfig, use for GLOBAL tables
PR: https://github.com/cockroachdb/cockroach/pull/59304

From release notes:
> A new, unused field called `global_reads` was added to [zone configurations](../v21.1/configure-replication-zones.html). The field does not yet have any effect. [#59304][#59304] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #9741, #9746.

Addresses #9287.

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey Aayush, this is basically your commit message from https://github.com/cockroachdb/cockroach/pull/57184 along with a mention of `global_reads` (FYI @nvanbenschoten)

I expect to update this again later in the release cycle to be more comprehensive; right now I'm just trying to get a first-pass "skeleton" for multi-region things built out in the docs.

**Comment by rmloveland** [comment]
Hey Aayush, any comments on these docs?  If not I'll plan to merge them this week.

**Comment by aayushshah15** [comment]
sorry for missing this earlier. It LGTM.

**Comment by rmloveland** [comment]
No problem Aayush!  Thanks for taking a look.

**Review by lnhsingh — COMMENTED** [review]
LGTM with a very small and annoying nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9897#-:-MVJ8iik2GDV58PsHO68:b-jha4ye)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @rmloveland)

___
*[_includes/v21.1/zone-configs/variables.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/9897#-MVJ8VU260IWBYcm2GvR:-MVJ8VU3EFVt-cDqttmj:b-n4o6o7) ([raw file](https://github.com/cockroachdb/docs/blob/c0a799c5d889034d0a26895db92b8fa93c928361/_includes/v21.1/zone-configs/variables.md#L9)):*
> ```Markdown
> `constraints` | An array of required (`+`) and/or prohibited (`-`) constraints influencing the location of replicas. See [Types of Constraints](configure-replication-zones.html#types-of-constraints) and [Scope of Constraints](configure-replication-zones.html#scope-of-constraints) for more details.<br/><br/>To prevent hard-to-detect typos, constraints placed on [store attributes and node localities](configure-replication-zones.html#descriptive-attributes-assigned-to-nodes) must match the values passed to at least one node in the cluster. If not, an error is signalled. To prevent this error, make sure at least one active node is configured to match the constraint. For example, apply `constraints = '[+region=west]'` only if you had set `--locality=region=west` for at least one node while starting the cluster.<br/><br/>**Default:** No constraints, with CockroachDB locating each replica on a unique node and attempting to spread replicas evenly across localities.
> `lease_preferences` <a name="lease_preferences"></a> | An ordered list of required and/or prohibited constraints influencing the location of [leaseholders](architecture/overview.html#glossary).  Whether each constraint is required or prohibited is expressed with a leading `+` or `-`, respectively.  Note that lease preference constraints do not have to be shared with the `constraints` field.  For example, it's valid for your configuration to define a `lease_preferences` field that does not reference any values from the `constraints` field.  It's also valid to define a `lease_preferences` field with no `constraints` field at all. <br /><br />  If the first preference cannot be satisfied, CockroachDB will attempt to satisfy the second preference, and so on.  If none of the preferences can be met, the lease will be placed using the default lease placement algorithm, which is to base lease placement decisions on how many leases each node already has, trying to make all the nodes have around the same amount.<br /><br />Each value in the list can include multiple constraints.  For example, the list `[[+zone=us-east-1b, +ssd], [+zone=us-east-1a], [+zone=us-east-1c, +ssd]]` means "prefer nodes with an SSD in `us-east-1b`, then any nodes in `us-east-1a`, then nodes in `us-east-1c` with an SSD."<br /><br /> For a usage example, see [Constrain leaseholders to specific availability zones](configure-replication-zones.html#constrain-leaseholders-to-specific-availability-zones).<br /><br />**Default**: No lease location preferences are applied if this field is not specified.
> `global_reads` | If `true`, transactions operating on the range(s) affected by this zone config should be non-blocking.  Most users will not need to modify this setting; it is applied automatically when you [use the `GLOBAL` table locality in a multi-region cluster](multiregion-overview.html#table-locality).
> ```

nit: there's an extra space after the first sentence

**Review by rmloveland — COMMENTED** [review]
Thanks Lauren!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9897#-:-MVMbl8l-hmK4KbnvR9o:b-jia9os)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @lnhsingh)

___
*[_includes/v21.1/zone-configs/variables.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/9897#-MVJ8VU260IWBYcm2GvR:-MVMaj7S7vd1w5yqbiVm:bp6v0sr) ([raw file](https://github.com/cockroachdb/docs/blob/c0a799c5d889034d0a26895db92b8fa93c928361/_includes/v21.1/zone-configs/variables.md#L9)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: there's an extra space after the first sentence
</blockquote></details>

Fixed!

(Although I must state for the record that two spaces after a period is fundamentally correct and one space after a period is incorrect, a shared hallucination caused by something some PM on the Word team decided in 1989 without consulting the proper historical context. But here we are.)

**Pull request merged**
