### PR TITLE
add pl/pgsql to enterprise feature and license pages

### PR DESCRIPTION
**Pull request by taroface**
DOC-9620

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
@taroface we'll also need to explicitly update the release notes for 23.2.0 to mention that PL/pgSQL requires an Enterprise license. See the release note for Column-Level Encryption for an example.

**Comment by taroface** [comment]
> @taroface we'll also need to explicitly update the release notes for 23.2.0 to mention that PL/pgSQL requires an Enterprise license. See the release note for Column-Level Encryption for an example. Can you add a commit for that to this PR?

Updated.

**Review by DingDLu — APPROVED** [review]
LGTM

**Review by shannonbradshaw — APPROVED** [review]
LGTM. Rendered changes look good.

**Pull request merged**
