### PR TITLE
Clarify sslmode=require warning

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-4378

### CODE REVIEW

**Review by DuskEagle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10772)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @mikeCRL)

___
*[cockroachcloud/connect-to-a-free-cluster.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/docs/10772#-McAb8zV9TQDWBmcusOq:-McAb8zV9TQDWBmcusOr:b-26cwrj) ([raw file](https://github.com/cockroachdb/docs/blob/27d2b19ac5f010567f35bf6b38a80caa30d09384/cockroachcloud/connect-to-a-free-cluster.md#L49)):*
> ```Markdown
> 1. Click the name of the `cc-ca.crt` to download the CA certificate to your local machine.
> 
>     Alternatively, you can set [`sslmode=require`](authentication.html#ssl-mode-settings). This is less secure than using a CA certificate and can make the cluster susceptible to MITM and impersonation attacks, so you should not use this setting with sensitive data.
> ```

Small nit: Maybe instead of "make the cluster susceptible", we could say "make your connection susceptible"?

**Review by DuskEagle — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10772#-:-McArRBY8XoHNbgebWQH:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @mikeCRL)

**Comment by gemma-shay** [comment]
@mikeCRL friendly reminder to review when you get a chance!

**Review by mikeCRL — APPROVED** [review]
LGTM. Sorry for the delay.

**Pull request merged**
