### PR TITLE
Update to cockroach quit and cockroach node docs

### LINKED ISSUE #334: Change --http-port to --port in client command docs
Secure a Cluster already updated with PR #332. Need to update `quit` and check all other client command docs, as well as Manual Deployment doc.

### PR DESCRIPTION
**Pull request by jseldess**
Updated docs to reflect that `quit` and `node` use `--port` instead of `--http-port`. And made a few small improvements to `--host` and `--port` definitions on client command docs.

Fixes #334.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/337)

### CODE REVIEW

**Comment by jseldess** [comment]
@bdarnell, updated the `--host` definition for `cockroach start` based on your answer to a question on Gitter. PTAL at change to `start-a-node.md`.

**Comment by sploiselle** [comment]
@jseldess You got everything I had put in #335 – sorry/no sweat on the duplication. Didn't figure you'd be back at it until the morning.

**Comment by tschottdorf** [comment]
LGTM

**Comment by jseldess** [comment]
Thanks, @sploiselle, @tschottdorf.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
