### PR TITLE
Add CREATE SEQUENCE to declarative schema changer

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-10536, DOC-9611

### CODE REVIEW

**Review by fqazi — APPROVED** [review]

**Comment by rmloveland** [comment]
@fqazi although the epic https://cockroachlabs.atlassian.net/browse/CRDB-31332 is marked for v24.2 I notice that your PR https://github.com/cockroachdb/cockroach/pull/104350 is from 2023. 

Should the doc change also be ported to older versions?  If so which ones? Thanks!

**Comment by fqazi** [comment]
> @fqazi although the epic https://cockroachlabs.atlassian.net/browse/CRDB-31332 is marked for v24.2 I notice that your PR [cockroachdb/cockroach#104350](https://github.com/cockroachdb/cockroach/pull/104350) is from 2023.
> 
> Should the doc change also be ported to older versions? If so which ones? Thanks!

Its been there since 24.1, so we should backport it there too.

**Comment by rmloveland** [comment]
> Its been there since 24.1, so we should backport it there too.

Thanks @fqazi added the changes to v24.1 docs as well

**Review by fqazi — APPROVED** [review]

**Comment by rmloveland** [comment]
@taroface mind taking a look? very small change, should hopefully be quick

**Review by taroface — APPROVED** [review]

**Pull request merged**
