### PR TITLE
Performance Benchmarking TPC-C 10K

### LINKED ISSUE #3355: Follow up: Performance Benchmarking TPC-C 10K
Add benchmarking for TPC-C 10K closer to 2.1 - will be able to run 10K without partitioning

Related: #3281 #2920

### PR DESCRIPTION
**Pull request by lhirata**
Closes #3355.

### CODE REVIEW

**Comment by lhirata** [comment]
@nvanbenschoten ready for another review!

**Comment by jseldess** [comment]
___
*[v2.1/performance-benchmarking-with-tpc-c.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/3410#-LHo55Vg8tOc2Ugerf_c:-LIgk6jC5BEuki8Eg1ws:b-ddlkty) ([raw file](https://github.com/cockroachdb/docs/blob/b54ca7b4178938ad320738ee28ed9897c454cdbe/v2.1/performance-benchmarking-with-tpc-c.md#L40)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

How does this make the SSD more performant? What do the different settings mean?
</blockquote></details>

@lhirata, here's how I'm documenting this in my performance tuning tutorial, in case it helps:

```
1. [Create 3 instances](https://cloud.google.com/compute/docs/instances/create-start-instance) for your CockroachDB nodes. While creating each instance:  
    - Select the **us-east1-b** [zone](https://cloud.google.com/compute/docs/regions-zones/).
    - Use the `n1-standard-4` machine type (4 vCPUs, 15 GB memory).
    - [Create and mount a local SSD](https://cloud.google.com/compute/docs/disks/local-ssd#create_local_ssd).
    - To apply the Admin UI firewall rule you created earlier, click **Management, disk, networking, SSH keys**, select the **Networking** tab, and then enter `cockroachdb` in the **Network tags** field.

2. Note the internal IP address of each `n1-standard-4` instance. You'll need these addresses when starting the CockroachDB nodes.

3. SSH to each instance and [optimize the local SSD for write performance](https://cloud.google.com/compute/docs/disks/performance#optimize_local_ssd) (see the **Disable write cache flushing** section).

4. Create a separate instance for read/write testing, also in the **us-east1-b** zone. This instance can be smaller, such as `n1-standard-1`.
```

I'm not including the exact command from the whitepaper because I'm not sure it'll work with non-roachprod-created instances. I'll look into this more.

**Comment by jseldess** [comment]
___
*[v2.1/performance-benchmarking-with-tpc-c.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/3410#-LHo55Vg8tOc2Ugerf_c:-LIgmPCD9MKaQmiAqGAp:b-3j4n55) ([raw file](https://github.com/cockroachdb/docs/blob/b54ca7b4178938ad320738ee28ed9897c454cdbe/v2.1/performance-benchmarking-with-tpc-c.md#L40)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

@lhirata, here's how I'm documenting this in my performance tuning tutorial, in case it helps:

```
1. [Create 3 instances](https://cloud.google.com/compute/docs/instances/create-start-instance) for your CockroachDB nodes. While creating each instance:  
    - Select the **us-east1-b** [zone](https://cloud.google.com/compute/docs/regions-zones/).
    - Use the `n1-standard-4` machine type (4 vCPUs, 15 GB memory).
    - [Create and mount a local SSD](https://cloud.google.com/compute/docs/disks/local-ssd#create_local_ssd).
    - To apply the Admin UI firewall rule you created earlier, click **Management, disk, networking, SSH keys**, select the **Networking** tab, and then enter `cockroachdb` in the **Network tags** field.

2. Note the internal IP address of each `n1-standard-4` instance. You'll need these addresses when starting the CockroachDB nodes.

3. SSH to each instance and [optimize the local SSD for write performance](https://cloud.google.com/compute/docs/disks/performance#optimize_local_ssd) (see the **Disable write cache flushing** section).

4. Create a separate instance for read/write testing, also in the **us-east1-b** zone. This instance can be smaller, such as `n1-standard-1`.
```

I'm not including the exact command from the whitepaper because I'm not sure it'll work with non-roachprod-created instances. I'll look into this more.
</blockquote></details>

Yeah, let's use the formulation above instead of the explicit command. The link to the google doc in step 3 should be sufficient. Part of the `sudo umount` command depends on how their ssd is named, which we can't really know.

**Comment by lhirata** [comment]
Hey @jseldess and @nvanbenschoten, can you take one last pass on this? Thanks!

**Comment by lhirata** [comment]
@nvanbenschoten / @jseldess - Can I get a final review/LGTM from you?

**Comment by lhirata** [comment]
TFTRs @nvanbenschoten and @jseldess. Finally merging!

**Pull request merged**
