### PR TITLE
Foreign Key docs

### PR DESCRIPTION
**Pull request by sploiselle**
Adding foreign key constraint info to relevant docs. Will follow up with additional documentation on removing foreign keys using `DROP INDEX`.

@dt – Could I get you to check this out for me?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/528)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[constraints.md, line 217 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH--GTcPMa5HyRO_Eq:-KOH--GTcPMa5HyRO_Er:973193847) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L217)):*
> ```Markdown
> #### Rules for Creating Foreign Keys
> 
> __Constrained Columns__
> ```

Maybe overly pedantic, but the referenced columns are also constrained by the constraint in the other table, since they can't be deleted if referenced.

---

*[constraints.md, line 220 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOGyfS2meWpE2LaSMFb:-KOGyfS2meWpE2LaSMFc:1278855322) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L220)):*
> oreign
s/ oreign/ Foreign/

I'd probably also emphasize `INDEX` more than the others, e.g. "using `INDEX` (or one of UNIQUE or PRIMARY KEY, which imply the creation of an index)", and also not that it is only required that the columns constrained appear _as the prefix_ of an index.

---

*[constraints.md, line 222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOGzKv_SgeXFltG7dZJ:-KOGzKv_SgeXFltG7dZK:-871549294) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L222)):*
> ```Markdown
> - oreign key columns must be [indexed](indexes.html) in the [`CREATE TABLE`](create-table.html) statement using [`PRIMARY KEY`](#primary-key), [`UNIQUE`](#unique), or [`INDEX`](create-table.html#create-a-table-with-secondary-indexes).
> - The constrained column must be of the same [type](data-types.html) as the column it references.
> - Each column can have no more than 1 Foreign Key constraint.
> ```

specifically, can appear in no more than one... e.g. `FOREIGN KEY (a, b) REFERENCES foo (a,b)` means no other fk constraint can include `a` or `b` (though note this is only for constrained cols -- a col can be *referenced* by any number of FKs).

---

*[constraints.md, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH-UZC8fgrCWOTrjoo:-KOH-UZC8fgrCWOTrjop:1190754783) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L227)):*
> ```Markdown
> __Referenced Columns__
> 
> - Referenced columns must contain only unique values. This means the `REFERENCES` clause must use exactly the same columns as a [`PRIMARY KEY`](#primary-key) or [`UNIQUE`](#unique) constraint.
> ```

I think this could use a little clarification, as well as an example saying that ` REFERENCES foo (a, b)` requires `(a,b)` be `UNIQUE` (or PRIMARY KEY, since that also implies UNIQUE).

---

*[constraints.md, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH0NGccCu3kBH6x4X7:-KOH0NGccCu3kBH6x4X8:777586262) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L228)):*
> ```Markdown
> 
> - Referenced columns must contain only unique values. This means the `REFERENCES` clause must use exactly the same columns as a [`PRIMARY KEY`](#primary-key) or [`UNIQUE`](#unique) constraint.
> - In the `REFERENCES` clause, if you specify the table but no columns, CockroachDB references the table's primary key. In these cases, you can only create single-column foreign keys.
> ```

it should work fine if the primary key is compound.
note that `REFERENCES` at the column level can only reference a single col, named or implicit, while at the table level it's just that the they have to be the same number.

---

*[constraints.md, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH0qf4sFMFGrU4PGA8:-KOH0qf4sFMFGrU4PGA9:891019765) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L232)):*
> ```Markdown
> __Using Null Values__
> 
> You can write _NULL_ values to columns with the Foreign Key constraint if and only if the write contains _NULL_ values for each constrained column. (This is similar to the `MATCH FULL` behavior in Postgres.) For example, if you have a Foreign Key constraint column on two columns and try to write an `INT` into one and a _NULL_ into the other, it will fail. However, writing _NULL_ values into both columns would succeed.
> ```

not exactly: if all the cols involved in the FK are null, then it isn't checked -- I think you can still write if some but not are null if that same combination exists in the referenced table?

---

*[constraints.md, line 234 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH16LQ8to6NP4S5H2Y:-KOH16LQ8to6NP4S5H2Z:1156506897) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L234)):*
> ```Markdown
> You can write _NULL_ values to columns with the Foreign Key constraint if and only if the write contains _NULL_ values for each constrained column. (This is similar to the `MATCH FULL` behavior in Postgres.) For example, if you have a Foreign Key constraint column on two columns and try to write an `INT` into one and a _NULL_ into the other, it will fail. However, writing _NULL_ values into both columns would succeed.
> 
> Because using _NULL_ values can conceptually break referential integrity, we recommend using [`NOT NULL`](#not-null) in conjunction with your Foreign Key constraint.
> ```

I'm not sure I'd say they "break" it but rather flip it around with a more positive approach, specifically pointing out that since FKs ensure every *value* in a table appears in the referenced table while not-null ensures every row has a value, used together they ensure every row corresponds to a row in the referenced table.

---

*[constraints.md, line 238 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH26jtjCR5OZIspcaj:-KOH26jtjCR5OZIspcak:-1140157213) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L238)):*
> ```Markdown
> __Bulk Inserts__
> 
> Though not a rule, we do not currently recommend bulk inserting rows into tables with foreign keys due to potential performance issues.
> ```

I don't know that we recommend against it, just that it might be slow and we don't have a workaround yet (like disabling the check until after the insert then running a one-shot validation or something).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/528)*

**Comment by sploiselle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[constraints.md, line 217 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH--GTcPMa5HyRO_Eq:-KOfECG8VOv50LKwg30j:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L217)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Maybe overly pedantic, but the referenced columns are also constrained by the constraint in the other table, since they can't be deleted if referenced.
</details>
Done.

---

*[constraints.md, line 220 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOGyfS2meWpE2LaSMFb:-KOgQYwZjIwdGIjUNqG_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L220)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> > oreign
> s/ oreign/ Foreign/
> 
> I'd probably also emphasize `INDEX` more than the others, e.g. "using `INDEX` (or one of UNIQUE or PRIMARY KEY, which imply the creation of an index)", and also not that it is only required that the columns constrained appear _as the prefix_ of an index.
</details>
Done.

---

*[constraints.md, line 222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOGzKv_SgeXFltG7dZJ:-KOfFqdgDASyggbyWqsC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L222)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> specifically, can appear in no more than one... e.g. `FOREIGN KEY (a, b) REFERENCES foo (a,b)` means no other fk constraint can include `a` or `b` (though note this is only for constrained cols -- a col can be *referenced* by any number of FKs).
</details>
Done.

---

*[constraints.md, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH-UZC8fgrCWOTrjoo:-KOgRfsG3BgrhKIa0FZp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L227)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I think this could use a little clarification, as well as an example saying that ` REFERENCES foo (a, b)` requires `(a,b)` be `UNIQUE` (or PRIMARY KEY, since that also implies UNIQUE).
</details>
Done.

---

*[constraints.md, line 228 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH0NGccCu3kBH6x4X7:-KOjpNeE1KDUNgu0d60s:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L228)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> it should work fine if the primary key is compound.
> note that `REFERENCES` at the column level can only reference a single col, named or implicit, while at the table level it's just that the they have to be the same number.
</details>
Done.

---

*[constraints.md, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH0qf4sFMFGrU4PGA8:-KOgRs8HpX_RhYFG--Bl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L232)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> not exactly: if all the cols involved in the FK are null, then it isn't checked -- I think you can still write if some but not are null if that same combination exists in the referenced table?
</details>
Done.

---

*[constraints.md, line 234 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH16LQ8to6NP4S5H2Y:-KOgRsuarut73apqBH-8:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L234)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I'm not sure I'd say they "break" it but rather flip it around with a more positive approach, specifically pointing out that since FKs ensure every *value* in a table appears in the referenced table while not-null ensures every row has a value, used together they ensure every row corresponds to a row in the referenced table.
</details>
Done.

---

*[constraints.md, line 238 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOH26jtjCR5OZIspcaj:-KOgRtUVMuiC8VbFlssH:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5c7494480dfde26b372039f04a6b6e764347a164/constraints.md#L238)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I don't know that we recommend against it, just that it might be slow and we don't have a workaround yet (like disabling the check until after the insert then running a one-shot validation or something).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/528)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[constraints.md, line 208 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOl9SbzN6nzjWe_0Zg_:-KOl9SbzN6nzjWe_0Zga:b-76yr75) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L208)):*
> ```Markdown
> ### Foreign Keys
> 
> The Foreign Key constraint is specified using `REFERENCES` at the column level or `FOREIGN KEY` and `REFERENCES` at the table level. It helps enforce referential integrity between two tables by guaranteeing that all values in a table's foreign key columns already exist in the referenced columns of another table.
> ```

it isn't always "already" -- it also prevents deletion/updates of those values in the referenced table.

---

*[constraints.md, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlA-p2X_UKBQwPAzXF:-KOlA-p2X_UKBQwPAzXG:b-q0jc0m) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L231)):*
> ```Markdown
> #### _NULL_ Values
> 
> By default, foreign keys will accept _NULL values in some scenarios. However, because [_NULL_](null-handling.html) values can introduce ambiguous references in data, we recommend strictly enforcing referential integrity by using [`NOT NULL`](#not-null) on both the foreign key and referenced columns when [creating your tables](create-table.html). (`NOT NULL` cannot be added to existing tables.)
> ```

`_NULL`?

---

*[constraints.md, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlA4uV_bra7aiOMQVO:-KOlA4uV_bra7aiOMQVP:b-iv9t4v) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L231)):*
> ```Markdown
> #### _NULL_ Values
> 
> By default, foreign keys will accept _NULL values in some scenarios. However, because [_NULL_](null-handling.html) values can introduce ambiguous references in data, we recommend strictly enforcing referential integrity by using [`NOT NULL`](#not-null) on both the foreign key and referenced columns when [creating your tables](create-table.html). (`NOT NULL` cannot be added to existing tables.)
> ```

ditto comment below on "ambiguous" being unclear.

I think we could say explicitly:
- NOT NULL  makes you provide a value.
- FK makes sure the value you provided actually exists in the other table.
Each is fulfilling a distinct purpose, but used in conjunction, they give you the property that you can always join and not be missing things. I don't think it is so much that we recommend doing so as much as that's just how they add up.

there's a parallel to CHECK constraints here too, where NOT-NULL makes you provide a value, and CHECK makes sure any provided values are valid.

---

*[constraints.md, line 244 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlAZRz1h9CvTrQ3kmA:-KOlAZRz1h9CvTrQ3kmB:b-ctbxhg) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L244)):*
> ```Markdown
> For example, if you have a Foreign Key constraint on columns `(A, B)` and try to insert `(1, NULL)`, the write would fail unless the row with the value `1` for `(A)` contained a _NULL_ value for `(B)`. However, inserting `(NULL, NULL)` would succeed, albeit with the side effect of degrading your tables' referential integrity.
> 
> Similarly, if your foreign keys' referenced columns allow for _NULL_ values, those reference can become ambiguous and result in similar degradation of the tables' referential integrity.
> ```

They're not really `ambiguous` -- it's not unclear what they point to, so much as they just don't point to anything. 

---

*[constraints.md, line 248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlC9Y_RluNgZKd9bzQ:-KOlC9Y_RluNgZKd9bzR:bezwkl4) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L248)):*
> ```Markdown
> #### Bulk Inserts
> 
> Bulk inserts into tables with foreign keys might be slow, but we're working to improve their performance.
> ```

I don't know if we even need to call out just bulk inserts, so much as added cost, in general, to operations on the tables involved: each row written to or updated in the referencing table has to also look up rows in the referenced table, and every row deleted and updated on the referenced table need to check for rows in the referencing table... currently all these checks are done per-row, but we're working to reduce that cost in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/528)*

**Comment by dt** [comment]
just as an fyi, you can just `git commit --amend -a` and then force-push to update the PR.

**Comment by sploiselle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[constraints.md, line 208 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOl9SbzN6nzjWe_0Zg_:-KOorEVXpgZwSHwT6hgy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L208)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> it isn't always "already" -- it also prevents deletion/updates of those values in the referenced table.
</details>
Done.

---

*[constraints.md, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlA-p2X_UKBQwPAzXF:-KOorErMkhlfGHnTw9Xp:b-kgi6m4) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L231)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> `_NULL`?
</details>
Typo. I need a Markdown linter.

---

*[constraints.md, line 231 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlA4uV_bra7aiOMQVO:-KOoxk5urcf4X7rmkh8G:b-gf1p04) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L231)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> ditto comment below on "ambiguous" being unclear.
> 
> I think we could say explicitly:
> - NOT NULL  makes you provide a value.
> - FK makes sure the value you provided actually exists in the other table.
> Each is fulfilling a distinct purpose, but used in conjunction, they give you the property that you can always join and not be missing things. I don't think it is so much that we recommend doing so as much as that's just how they add up.
> 
> there's a parallel to CHECK constraints here too, where NOT-NULL makes you provide a value, and CHECK makes sure any provided values are valid.
> 
</details>
The problem is just that they _can_ be ambiguous, which is antithetical to referential integrity. For example:

`CREATE TABLE tbl1 (a INT, b INT, c INT, UNIQUE(a, b));
INSERT INTO tbl1 VALUES (1, NULL, 1);
INSERT INTO tbl1 VALUES (1, NULL, 2);
INSERT INTO tbl1 VALUES (1, NULL, 3);
CREATE TABLE tbl2 (d INT, e INT, INDEX (d, e), FOREIGN KEY (d, e) REFERENCES tbl1 (a, b));
INSERT INTO tbl2 VALUES (1, NULL);`

Which set of `(a, b, c)` values that the one row of `(d, e)` references is ambiguous specifically because of _NULL_.

That being said, I:
1. Reorganized to focus on the explanation of the behavior
2. Removed the phrase "recommended"
3. Removed the term ambiguous in favor of "degraded referential integrity."

If we see users tripped up on this, we can:
- Include greater detail about foreign keys and `JOIN` –– I held off on that for the time being because we don't have the `JOIN` docs ready yet
- Expand the section later to include greater detail about the interaction of `NOT NULL` and foreign keys

---

*[constraints.md, line 244 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlAZRz1h9CvTrQ3kmA:-KOorNNmGh_BlgQhLfRM:bp4n4gh) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L244)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> They're not really `ambiguous` -- it's not unclear what they point to, so much as they just don't point to anything. 
</details>
Fix detailed above.

---

*[constraints.md, line 248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/528#-KOlC9Y_RluNgZKd9bzQ:-KOpV4ZjcwVtCvz8AwmT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6cccf76fe1f27b8158e31f92d7bba093eff7daad/constraints.md#L248)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I don't know if we even need to call out just bulk inserts, so much as added cost, in general, to operations on the tables involved: each row written to or updated in the referencing table has to also look up rows in the referenced table, and every row deleted and updated on the referenced table need to check for rows in the referencing table... currently all these checks are done per-row, but we're working to reduce that cost in the future.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/528)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/528#-:-KOpyb3-T7Nhvvtf5S6_:bnfp4nl)*

**Pull request merged**
