### PR TITLE
remove warning about renaming cols in CHECK

### PR DESCRIPTION
**Pull request by dt**
cockroachdb/cockroach#7311 fixed the issue with renames

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/402)

### CODE REVIEW

**Comment by jseldess** [comment]
:lgtm:, with a few minor suggestions

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[null-handling.md, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/402#-KKjXg88ndh2BTot10J4:-KKjXg88ndh2BTot10J5:-374681373) ([raw file](https://github.com/cockroachdb/docs/blob/5fcd76245330e9d56be655426a874e76937f96c0/null-handling.md#L284)):*
> ```Markdown
> 
> A `CHECK` constraint expression that evaluates to `NULL` is considered to pass, allowing for concise expressions like `discount < price` without worrying about adding `OR discount IS NULL` clauses. When non-null validation is desired, the usual `NOT NULL` constraint can be
> used along side a CHECK expression.
> ```

Looks good, David. Just a few suggestions:

1. Add an example. 
2. Make the first `CHECK` a link:

   ```
   [`CHECK`](constraints.html#check)
   ```
3. Can you code-format the final `CHECK`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/402#-:-KKjYt-RCmLiqXf01cs_:-1198565592)*

**Comment by dt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[null-handling.md, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/402#-KKjXg88ndh2BTot10J4:-KKjfBIxu62bxzwWBJba:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/5fcd76245330e9d56be655426a874e76937f96c0/null-handling.md#L284)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Looks good, David. Just a few suggestions:
> 
> 1. Add an example. 
> 2. Make the first `CHECK` a link:
> 
>    ```
>    [`CHECK`](constraints.html#check)
>    ```
> 3. Can you code-format the final `CHECK`?
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/402)*

**Comment by jseldess** [comment]
Thanks, @dt. Looks good. @uptimeDBA, any feedback before we merge?

**Comment by uptimeDBA** [comment]
:lgtm:  (like the Star Trek reference)

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/402#-:-KKlMRc4E191fk3ml0An:-1736641843)*

**Pull request merged**
