### PR TITLE
document active query dumps

### LINKED ISSUE #11216: heapprofiler: add periodic query dump mechanism
Exalate commented:

https://github.com/cockroachdb/cockroach/pull/66901 --- Release note (ops change): operators will potentially have access to a CSV file containing active queries from the last run of the queryprofile upon OOM. This feature is toggled on/off by a new cluster setting, "diagnostics.active_query_dumps.enabled"  Release justification: Low-risk addition of a new observability feature providing insight into active queries when memory pressure is detected.

### PR DESCRIPTION
**Pull request by taroface**
Fixes #11216.

@abarganier, let me know if I shouldn't have this on the debug zip page yet. I can save that for a separate PR if that part is further out.

### CODE REVIEW

**Comment by abarganier** [comment]
@taroface thanks for the updates - I've not yet completed the work to pull these files into debug.zip but I hope to next week. I will keep you posted 👍

**Comment by taroface** [comment]
@abarganier This should be ready for your review!

**Review by abarganier — APPROVED** [review]
:lgtm:, thanks @taroface!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12261#-:-Mpm1JsE6cRYlbYNB6gK:b-mtdfp0)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by kathancox — APPROVED** [review]
LGTM!

**Pull request merged**
