### PR TITLE
asciinema for start local cluster

### PR DESCRIPTION
**Pull request by jseldess**
Made an asciinema recording of the `start-a-local-cluster.md` process, and added it to a new "Watch a Demo" section. Also removed the "Before You Begin" section, since the overall intro to the page clearly indicates that installation is a prerequisite.

@sploiselle, @jess-edwards, @kuanluo: I was considering expand/collapse or using jquery to open the video in a popup, but then I settled on this simpler solution. Thoughts? Happy to do this differently.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/861)

### CODE REVIEW

**Comment by kuanluo** [comment]
LGTM, @jseldess. The simpler solution is more elegant - I like it. Also, you can copy commands from the video? That's SO rad.

**Comment by sploiselle** [comment]
This is phenomenal, @jseldess! A few thoughts:

- Can we get the files to host this ourselves without relying on the asciinema site?
- Can we add even tracking through Google Tag Manager for clicks on the video?
- The video takes up a lot of horizontal room. Part of me prefers to have its footprint start smaller and expand only if it's engaged: maybe that's a compelling A/B test once we have that set up. For the time being, though, I think the inline solution you've come up with works exceptionally well.

**Comment by jess-edwards** [comment]
@jseldess +1 this is excellent! The simple solution is quite nice.

**Comment by dianasaur323** [comment]
This is great! is there a way to speed it up a little so that there is less waiting between "Steps" and when you actually type in commands?

**Comment by jseldess** [comment]
Thanks, @kuanluo and @sploiselle. 

Sean, it seems that we can host ourselves, yes. Just found [this](https://github.com/asciinema/asciinema-player#self-hosting-quick-start). I'll read through.

And yes, we can and should add event tracking. I'll do that soon as well.

**Comment by jseldess** [comment]
@dianasaur323, I sped it up. Better, or should I speed it up even more? See the link above.

**Comment by jess-edwards** [comment]
@jseldess @dianasaur323 

We may not need to dictate a faster a video speed. It's possible for the user to control the speed if you include an instruction on how to do so. Just using the --> arrow key advances each command for users who want to speed up or go back. I've tested it, and it works: 

According to [this thread](https://github.com/asciinema/asciinema.org/issues/128), 
```you can now now use < and > keys to change playback speed. There's no visual feedback when changing this yet but I'll be adding some indicator to the player's UI.```

**Comment by jseldess** [comment]
@jess-edwards, good find! I'll add instructions.

**Comment by dianasaur323** [comment]
@jseldess Yeah, that's better! Adding in instructions also sounds like a good idea. @jess-edwards

**Comment by jseldess** [comment]
So < and > actually goes back and forward, which is also pretty awesome.

**Comment by jseldess** [comment]
@sploiselle, we're now hosting everything ourselves. PTAL.

**Comment by jseldess** [comment]
@sploiselle, just added a class for google event tracking, and published a new tag/trigger in google tag manager.

**Comment by jseldess** [comment]
@sploiselle, I think I fixed the play button problem. PTAL.

**Comment by mjibson** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/head.html, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/861#-KWfvBT1rJ2IcFy_wY2S:-KWfvBT1rJ2IcFy_wY2T:b-ukfdv3) ([raw file](https://github.com/cockroachdb/docs/blob/fb8905c5f9038ace7420b0ddb62c5db08dc5f7fb/_includes/head.html#L23)):*
> ```HTML
> <script src="js/anchor.js"></script>
> <script src="js/feedback-widget.js"></script>
> <script src="js/asciinema-player.js"></script>
> ```

Remove this: already in _layouts/page.html.

---

*[css/customstyles.scss, line 625 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/861#-KWfvNEO9AqCZdrtPSFJ:-KWfvNEPjLA3ZgbZEcJU:b97a1he) ([raw file](https://github.com/cockroachdb/docs/blob/fb8905c5f9038ace7420b0ddb62c5db08dc5f7fb/css/customstyles.scss#L625)):*
> ```SCSS
> @import "components/back-to-top";
> @import "components/buttons";
> @import "components/asciinema-player";
> ```

There's no need to include this css in every page load. I would move this include to a similar conditional thing as in _layouts/page.html, but in the css section of the header. There's no need to convert it to a scss file: we can just leave it as the same asset downloaded from the asciinema player release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/861)*

**Comment by jseldess** [comment]
Thanks for the tips, @mjibson!

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/head.html, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/861#-KWfvBT1rJ2IcFy_wY2S:-KWgtO0fuiq8vrbUcm_3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fb8905c5f9038ace7420b0ddb62c5db08dc5f7fb/_includes/head.html#L23)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Remove this: already in _layouts/page.html.
</details>
Done.

---

*[css/customstyles.scss, line 625 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/861#-KWfvNEO9AqCZdrtPSFJ:-KWgvKFWxxcjqP4VFfj9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fb8905c5f9038ace7420b0ddb62c5db08dc5f7fb/css/customstyles.scss#L625)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> There's no need to include this css in every page load. I would move this include to a similar conditional thing as in _layouts/page.html, but in the css section of the header. There's no need to convert it to a scss file: we can just leave it as the same asset downloaded from the asciinema player release.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/861#-:-KWgvLMLDmY3TMfbYETf:b-g5ra5b)*

**Comment by sploiselle** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/861#-:-KWhp8bPzoE6JVa6WQBN:bnfp4nl)*

**Comment by jseldess** [comment]
Fixes #861

**Pull request merged**
