### PR TITLE
beta-20161027 release note updates

### PR DESCRIPTION
**Pull request by jseldess**
This PR updates the release notes and adds some supporting docs.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/796)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[beta-20161027.md, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/796#-KV6D2rWJVFPL1h6J7eB:-KV6D2rWJVFPL1h6J7eC:b-5uuhtf) ([raw file](https://github.com/cockroachdb/docs/blob/ecf3b98aff12ab4e30947b148651a988cd877b11/beta-20161027.md#L45)):*
> ```Markdown
> - Reduced overhead of the internal time-series metric system. [#9889](https://github.com/cockroachdb/cockroach/pull/9889)
> - Reduced impact of schema changes on regular queries. [#9798](https://github.com/cockroachdb/cockroach/pull/9798)
> - In the event of a node failure, schema changes now save their progress and can resume from their last checkpoint instead of from the beginning. [#10036](https://github.com/cockroachdb/cockroach/pull/10036)
> ```

[nit, feel free to ignore] "instead of from the beginning" sounds off, maybe "instead of restarting from the beginning"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/796#-:-KV6DJPyVBMDy0WG4a2W:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[show-all.md, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/796#-KV6D-t3klJwtgNDZaPS:-KV6D-t4n4tB4LQRuwjw:bxpglab) ([raw file](https://github.com/cockroachdb/docs/blob/ecf3b98aff12ab4e30947b148651a988cd877b11/show-all.md#L33)):*
> ```Markdown
> | TIME ZONE                     | UTC          |
> | TRANSACTION ISOLATION LEVEL   | SERIALIZABLE |
> | TRANSACTION PRIORITY          | NORMAL       |
> ```

I realize it may be out of scope for this PR, but it seems as though it'd be really nice for user experience if there were explanations or links to explanations of what the variables do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/796#-:-KV6DQQQ_vlf3crvBCTh:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[show-all.md, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/796#-KV6D-t3klJwtgNDZaPS:-KV6KMxBD7uTJhu79IJS:b-vdvhjl) ([raw file](https://github.com/cockroachdb/docs/blob/ecf3b98aff12ab4e30947b148651a988cd877b11/show-all.md#L33)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> I realize it may be out of scope for this PR, but it seems as though it'd be really nice for user experience if there were explanations or links to explanations of what the variables do
</details>
Yeah, I was a bit lazy here. I've added a section describing the response. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/796)*

**Comment by jseldess** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[beta-20161027.md, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/796#-KV6D2rWJVFPL1h6J7eB:-KV6KYJX_-1Dyvrvv08_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ecf3b98aff12ab4e30947b148651a988cd877b11/beta-20161027.md#L45)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit, feel free to ignore] "instead of from the beginning" sounds off, maybe "instead of restarting from the beginning"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/796)*

**Pull request merged**
