### PR TITLE
21.1 benchmarking updates

### LINKED ISSUE #10350: Update our performance benchmarking docs for 21.1
@awoods187, @mwang1026, do we have new tpcc benchmarking results for 21.1 that should be reflected in the docs? And should we update the tutorials in any way? 

https://www.cockroachlabs.com/docs/v21.1/performance.html

### PR DESCRIPTION
**Pull request by jseldess**
As there were no noteworthy performance benchmarking changes from 20.2 to 21.1, this PR makes a few cosmetic updates to the 21.1 performance overview page:
- Change 20.2 to 21.1 in performance graph 
- Change 20.2 to 21.1 in performance metrics table

The benchmarking instructions don't require any updates, as the version references are auto-generated correctly based on the docs version. 

This PR also updates the `See also` link for performance tuning to point to the new multi-region overview page and fixes a minor Liquid syntax error in an unrelated page. 

Fixes #10350

### CODE REVIEW

**Comment by jseldess** [comment]
___
*[v21.1/performance.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/10363#-MYjSb-bCKnn9qV9LRsq:-MYjSb-bCKnn9qV9LRsr:b7xhui) ([raw file](https://github.com/cockroachdb/docs/blob/89232d16b1592e43ebee15a5af086a99dc4c84f2/v21.1/performance.md#L26)):*
> ```Markdown
> TPC-C 140,000
> 
> | Metric                                          | CockroachDB 19.2 | CockroachDB 20.2 |
> ```

@nvanbenschoten, @awoods187, this is the only explicit reference to 20.2. How should we handle this? Should we include a note about how we expect 21.1 performance to resemble 20.2?

**Review by nvanbenschoten — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10363)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187)

___
*[v21.1/performance.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/10363#-MYjSb-bCKnn9qV9LRsq:-MYkTFqC4jLWLRp3nYuI:bwi5bfk) ([raw file](https://github.com/cockroachdb/docs/blob/89232d16b1592e43ebee15a5af086a99dc4c84f2/v21.1/performance.md#L26)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

@nvanbenschoten, @awoods187, this is the only explicit reference to 20.2. How should we handle this? Should we include a note about how we expect 21.1 performance to resemble 20.2?
</blockquote></details>

My thinking was that we would just change this to mention 21.1 because we do not believe the performance has changed between the two versions. 

Also, the other reference to 20.2 is in the image directly above this.

**Review by jseldess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10363)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @nvanbenschoten)

___
*[v21.1/performance.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/10363#-MYjSb-bCKnn9qV9LRsq:-MZYXq7L5EvrJKozf0k6:b4b9f89) ([raw file](https://github.com/cockroachdb/docs/blob/89232d16b1592e43ebee15a5af086a99dc4c84f2/v21.1/performance.md#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

My thinking was that we would just change this to mention 21.1 because we do not believe the performance has changed between the two versions. 

Also, the other reference to 20.2 is in the image directly above this.
</blockquote></details>

Makes sense. I've changed the text. Asking Design to help update the image.

**Comment by jseldess** [comment]
___
*[v21.1/performance.md, line 26 at r2](https://reviewable.io/reviews/cockroachdb/docs/10363#-MYjSb-bCKnn9qV9LRsq:-MZYb6bC1TaA1QDw4YNe:by6rn0f) ([raw file](https://github.com/cockroachdb/docs/blob/89232d16b1592e43ebee15a5af086a99dc4c84f2/v21.1/performance.md#L26)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Makes sense. I've changed the text. Asking Design to help update the image. 
</blockquote></details>

Image updated as well.

**Comment by jseldess** [comment]
@nvanbenschoten, since these changes are so trivial, I'll just merge. If you have additional feedback, I can open a follow-up PR.

**Review by nvanbenschoten — COMMENTED** [review]
:lgtm: thanks Jesse!

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10363#-:-MZwupP-C5nqbZcfq8uj:b-o2vnlt)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
