### PR TITLE
--join troubleshooting for existing data directory

### PR DESCRIPTION
**Pull request by sploiselle**
Troubleshooting steps to solve issue for starting a node, stopping it, and then trying to get the same machine to start a new node joining a different cluster.

Also a few misc. improvements to the troubleshooting doc.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/610)

### CODE REVIEW

**Comment by sploiselle** [comment]
added commit for:
fixes #611

Can I get you to take a look @knz?

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[troubleshoot.md, line 14 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQfRnipOYnAStQFSYPV:-KQfRniqzMA38A0aFPBf:bum62j0) ([raw file](https://github.com/cockroachdb/docs/blob/de650bcddf38358f031279ea400d306d0edb705c/troubleshoot.md#L14)):*
> ```Markdown
> $ cockroach start <flags> --logtostderr`
> ```
> ```

Add an explanatory sentence: "This tells CockroachDB to redirect its logging output to the standard error instead of log files in the data directory."

Then:
"If you want to both watch what is going on and capture the logging to a file so you can send this file to us later, you can also use:

```
$ cockroach start <flags> --logtostderr 2>&1 | tee error.log 
```
"

(I know we also have a flag `--alsologtostderr` but this does something different and slightly less useful, so I'd suggest not mentioning it here.)

---

*[troubleshoot.md, line 71 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQfSoBjSWqrpJz7vwZL:-KQfSoBjSWqrpJz7vwZM:b2eqar7) ([raw file](https://github.com/cockroachdb/docs/blob/de650bcddf38358f031279ea400d306d0edb705c/troubleshoot.md#L71)):*
> ```Markdown
> When running a multi-node CockroachDB cluster, if you see an error like the one above about replicas failing, some nodes might not be able to talk to each other. Here are some recommended actions:
> 
> 1. Check to make sure that every node but the first was started with the `--join` flag set to the hostname and port of the first node. If the flag was not set correctly for a node, shut down the node and restart it with the `--join` flag set correctly. See [Stop a Node](stop-a-node.html) and [Start a Node](start-a-node.html) for more details. 
> ```

A mention here that "If you already have started a node without --join and now you want to join another cluster, be sure to first remove your data directory first. this is because when you started your node without --join, it created its own small cluster at that point and you first need to get rid of that."

---

*[troubleshoot.md, line 81 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQfT9t9rzwp13OLLk99:-KQfT9t9rzwp13OLLk9A:b-ydrgfi) ([raw file](https://github.com/cockroachdb/docs/blob/de650bcddf38358f031279ea400d306d0edb705c/troubleshoot.md#L81)):*
> ```Markdown
> - [CockroachDB Community Forum](https://forum.cockroachlabs.com): Ask questions, find answers, and help other users.
> - [Join us on Gitter](https://gitter.im/cockroachdb/cockroach): This is the most immediate way to connect with CockroachDB engineers. To open Gitter without leaving these docs, click **Chat with Developers** in the lower-right corner of any page.
> - **Send Us Feedback**: In the **Was this page helpful?** section below, click **No**, and then send us details about your issue.
> ```

I would separate this last point from the other two. 

The first two points are about when a problem does not have a solution.

The last point is when the doc is clearly wrong or incomplete. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/610)*

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[troubleshoot.md, line 14 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQfRnipOYnAStQFSYPV:-KR-BDco7GPJ9ZtWDDNa:boyexb3) ([raw file](https://github.com/cockroachdb/docs/blob/de650bcddf38358f031279ea400d306d0edb705c/troubleshoot.md#L14)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Add an explanatory sentence: "This tells CockroachDB to redirect its logging output to the standard error instead of log files in the data directory."
> 
> Then:
> "If you want to both watch what is going on and capture the logging to a file so you can send this file to us later, you can also use:
> 
> ```
> $ cockroach start <flags> --logtostderr 2>&1 | tee error.log 
> ```
> "
> 
> (I know we also have a flag `--alsologtostderr` but this does something different and slightly less useful, so I'd suggest not mentioning it here.)
> 
</details>
Done. Thanks!

---

*[troubleshoot.md, line 71 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQfSoBjSWqrpJz7vwZL:-KR-BECjurTpBdNJZf_0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/de650bcddf38358f031279ea400d306d0edb705c/troubleshoot.md#L71)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> A mention here that "If you already have started a node without --join and now you want to join another cluster, be sure to first remove your data directory first. this is because when you started your node without --join, it created its own small cluster at that point and you first need to get rid of that."
</details>
Done.

---

*[troubleshoot.md, line 81 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQfT9t9rzwp13OLLk99:-KR-BIH0LFZ97Vya9M7P:b-r4wjba) ([raw file](https://github.com/cockroachdb/docs/blob/de650bcddf38358f031279ea400d306d0edb705c/troubleshoot.md#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I would separate this last point from the other two. 
> 
> The first two points are about when a problem does not have a solution.
> 
> The last point is when the doc is clearly wrong or incomplete. 
</details>
I think we can also use the last bullet to handle capturing feedback when the problem is both not in the document, as well as when it doesn't have a solution.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/610)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/610#-:-KR-DsxFfssdR1VR4P61:bnfp4nl)*

**Comment by jseldess** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[troubleshoot.md, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/610#-KQcUZ0cSvhH-4KPM7mi:-KQcUZ0dY6Yg8t61xEGQ:bv91vym) ([raw file](https://github.com/cockroachdb/docs/blob/b8316d647d1a57b72bd652c2fac604ae4cef813e/troubleshoot.md#L12)):*
> ```Markdown
> 
> ```shell
> $ cockroach start <flags> --logtostderr`
> ```

Extra ` at end of line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/610#-:-KR495hRMywNPIFUoSNk:bnfp4nl)*

**Pull request merged**
