### PR TITLE
Add page listing third-party tools

### LINKED ISSUE #2979: Support open source database tools
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recQn4SSaisYmtf7e
PM: @awoods187 
Eng Partner:

### PR DESCRIPTION
**Pull request by rmloveland**
... including DBeaver.

Fixes #2979.

Summary of changes:

- Add a page 'Reference > Third-Party Tools' that lists schema migration
  tools, GUIs, ORMs, and driver libraries.

- Add a page 'Get Started > Connect DBeaver to a Secure Cluster' that
  shows (using screenshots) how to enter the required certificates
  during DBeaver setup, including how to do the Java openssl pk8 dance.

### CODE REVIEW

**Comment by rmloveland** [comment]
Direct links for easier reference:

- [Third-Party Tools](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e097bc91a1197089085bcc319811effad0b59bfb/dev/third-party-tools.html)
- [Connect DBeaver to a secure cluster](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e097bc91a1197089085bcc319811effad0b59bfb/dev/dbeaver.html)

@awoods187 and @knz :  This draft probably needs plenty of input.  In particular I think more precise guidance / language around how well we support these various tools will be good to have, in addition to any other feedback you think is warranted.  But at least it's a start! :-)

**Comment by jseldess** [comment]
@rmloveland, this is a bit of a drive-by review before I've been invited, but I have a structural suggestion that I don't want to wait too long to give: Instead of listing this under "Get Started", I'd suggest we:
1. Add it under `Explore Features` and rename it something like `Third-Party GUI Support` or `Third-Party Database Tools`.
2. Beef up the intro with language expressing the Cockroach supports third-party tools (with link to full reference page) and language specifically about DBeaver and why to use it.

Thoughts?

**Comment by rmloveland** [comment]
> I'd suggest we:
> - Add it under Explore Features and rename it something like Third-Party GUI Support or Third-Party Database Tools.
> - Beef up the intro with language expressing the Cockroach supports third-party tools (with link to full reference page) and language specifically about DBeaver and why to use it.
> Thoughts?

SGTM @jseldess !  Will update to take this into account as part of the ongoing work.

**Comment by rmloveland** [comment]
@awoods187 and @knz I have a question:

Since the DBeaver-specific bits for the 2.1 release are happening via #3915 I propose doing the following.

1. Close this PR.
2. Draft some docs to accomplish the goals of this PR, but according to the plan proposed by Raphael in the comments above.
3. When ready, open a new PR with the results of that work.

I think that will be better than trying to trim down/redirect this PR.  It would also avoid having a "hanging PR" that is open for too long and distracting you (and me).

What do you think?

**Comment by knz** [comment]
No comment from me. I'm happy either way.

**Comment by awoods187** [comment]
Sounds good to me @rmloveland

**Pull request closed without merging**
