### PR TITLE
Add closed timestamps to architecture docs

### LINKED ISSUE #6793: Add closed timestamps to the architecture docs
Currently, the only place where we mention closed timestamps is on the [Follower Reads](https://www.cockroachlabs.com/docs/stable/follower-reads.html) page (AFAICT).

We should find out where they live in the architecture and document them there as well.

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #6793

Addresses #9040

Also a prerequisite for #11016 (we can't really get into the details of
bounded staleness without more of this background info)

Summary of changes:

- Update the 'Reading' section of the Transaction Layer page to list
  consistent vs. stale reads

- Add a new 'Closed timestamp' section to the Transaction Layer page

- Link to the above from the Follower Reads page

- Update the transaction retry errors page to link to the new closed
  timestamp section of the Transaction Layer page

- Opportunistic update to the 'Timestamp Cache' section of the
  Transaction Layer page based on the contents of the blog post 'An Epic
  Read on Follower Reads'[1] (on which this PR is based)

- Update the 'Read refreshing' section of the Transaction Layer page to
  add links to closed timestamps and to link to more docs on the
  transaction retry error type mentioned there.

[1]: https://www.cockroachlabs.com/blog/follower-reads-stale-data/

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey Andrei and Nathan,

Added you both to review as you are the authors of the epic blog post from which much of this info was taken.  Feel free to unassign or punt me to other reviewers if needed !

**Review by andreimatei — APPROVED** [review]
:LGTM: thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11762#-:-MkdDKMN0vYzc5AOPSiQ:bww03zd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rmloveland)

___
*[v21.2/architecture/transaction-layer.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdDWkp6eyM2v_77NDd:-MkdDWkp6eyM2v_77NDe:b-ro9ict) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L47)):*
> ```Markdown
> CockroachDB provides the following types of reads:
> 
> - Strongly-consistent (a.k.a. "non-stale") reads: These are the default and most common type of read. For example, read-write transactions will always perform strongly-consistent reads. These reads go through the [leaseholder](replication-layer.html#leases) and always return data that is correct and up to date.
> ```

If you're not gonna go into it more, I would strike the part about "read-write" transactions, because you cast doubt about what other transactions do. The thing I'd say in this paragraph is that these reads see all writes performed by writers that committed before the reading transaction started.
___
*[v21.2/architecture/transaction-layer.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdDusS6bcqY2Xv4Xk9:-MkdDusS6bcqY2Xv4XkA:b2m6kjk) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L48)):*
> ```
> They can only be used in read-only transactions.
> ```

I'd make it concrete and say something about `as of system time` here.
___
*[v21.2/architecture/transaction-layer.md, line 101 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCD96AwQ2o5vGK152:-MkdCD96AwQ2o5vGK153:bgu6rfi) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L101)):*
> ```Markdown
> As part of providing serializability, whenever an operation reads a value, we store the operation's timestamp in a timestamp cache, which shows the high-water mark for values being read.
> 
> The timestamp cache is a data structure used to store information about the reads performed by [leaseholders](replication-layer.html#leases). This is used to ensure that once some transaction *t1* reads a row, another transaction *t2* that comes along and tries to write to that row will be ordered after *t1*, thus ensuring a serial order of transactions, a.k.a. serializability.
> ```

nicely put
___
*[v21.2/architecture/transaction-layer.md, line 105 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdE-Wz1ZIK1pZJC6cf:-MkdE-Wz1ZIK1pZJC6cg:bw0ii1h) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L105)):*
> ```Markdown
> Whenever a write occurs, its timestamp is checked against the timestamp cache. If the timestamp is less than the timestamp cache's latest value, we attempt to push the timestamp for its transaction forward to a later time. Pushing the timestamp might cause the transaction to restart in the second phase of the transaction (see [read refreshing](#read-refreshing)).
> 
> ### Closed timestamps
> ```

consider linking to the blog post somewhere in this section
___
*[v21.2/architecture/transaction-layer.md, line 107 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCNt0BSkqXKZ0SpR7:-MkdCNt0BSkqXKZ0SpR8:b-4nqjgd) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L107)):*
> ```
> advances forward by some target interval behind the current time
> ```

perhaps "advances continuously, and lag the current time by a target interval".
___
*[v21.2/architecture/transaction-layer.md, line 107 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCYy9Ax0O46R-MABf:-MkdCYy9Ax0O46R-MABg:btis5eh) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L107)):*
> ```
> it rejects the write
> ```

"rejects" sounds harsh if you don't qualify it. Consider saying that a transaction trying to write below the closed ts is forced to change its timestamp (which might result in a retry error), and link to "refreshing" if we talk about that anywhere.
___
*[v21.2/architecture/transaction-layer.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCu4V07CIIMRy_ua4:-MkdCu4V07CIIMRy_ua5:b-kdjk2x) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L115)):*
> ```Markdown
> Once the follower replica has applied the abovementioned Raft commands, it has all the data necessary to serve reads with timestamps less than or equal to the closed timestamp.
> 
> Note that closed timestamps are durable even if the leaseholder changes; in other words, they are preserved across [lease transfers](replication-layer.html#epoch-based-leases-table-data).
> ```

Unfortunately, they currently are not "durable" in the usual meaning of the word, which is "persisted to disk; recoverable after node restart". Hopefully they will be, one day.
I'd say that closed timestamps are valid even as leaseholders change; a new leaseholder will not break a promise made by an old leaseholder.

**Review by rmloveland — COMMENTED** [review]
Thanks for the review Andrei!  Updated based on your comments, thanks for the good clarifications & suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11762#-:-MkmMau_2niZ_N9g8WMV:b7955z6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[v21.2/architecture/transaction-layer.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdDWkp6eyM2v_77NDd:-MkmIxSoAQ7jH6BIZDPw:bwdra9i) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L47)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If you're not gonna go into it more, I would strike the part about "read-write" transactions, because you cast doubt about what other transactions do. The thing I'd say in this paragraph is that these reads see all writes performed by writers that committed before the reading transaction started.
</blockquote></details>

Updated to remove the "read-write" comment and use that language
___
*[v21.2/architecture/transaction-layer.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdDusS6bcqY2Xv4Xk9:-MkmJGLtBx4wtmcRgpVD:bv7fw0b) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L48)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> They can only be used in read-only transactions.
> ```

I'd make it concrete and say something about `as of system time` here.
</blockquote></details>

Updated to  "read-only transactions that use AOST (link)"
___
*[v21.2/architecture/transaction-layer.md, line 101 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCD96AwQ2o5vGK152:-MkmK0fN9jJYwGzjpdPM:b-nlsh8t) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L101)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nicely put
</blockquote></details>

Thanks!  Though I think it's mostly adapted from your epic blog post :-) 
___
*[v21.2/architecture/transaction-layer.md, line 105 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdE-Wz1ZIK1pZJC6cf:-MkmKb2i2ud0aRhbouYR:b-zdghvb) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L105)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider linking to the blog post somewhere in this section
</blockquote></details>

Added "For more information about the implementation of closed timestamps and Follower Reads, see our blog post [An Epic Read on Follower Reads](https://www.cockroachlabs.com/blog/follower-reads-stale-data/)" to the end of the section
___
*[v21.2/architecture/transaction-layer.md, line 107 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCNt0BSkqXKZ0SpR7:-MkmKlhi48_nyxWIxcbm:bxa3wyf) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L107)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> advances forward by some target interval behind the current time
> ```

perhaps "advances continuously, and lag the current time by a target interval".
</blockquote></details>

Updated to say that
___
*[v21.2/architecture/transaction-layer.md, line 107 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCYy9Ax0O46R-MABf:-MkmLWDiCQTR99UHyYv0:baq6mau) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L107)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> it rejects the write
> ```

"rejects" sounds harsh if you don't qualify it. Consider saying that a transaction trying to write below the closed ts is forced to change its timestamp (which might result in a retry error), and link to "refreshing" if we talk about that anywhere.
</blockquote></details>

Updated to "If the range receives a write at a timestamp less than its closed timestamp, the write is forced to change its timestamp, which might result in a retry error (see [read refreshing](#read-refreshing))."
___
*[v21.2/architecture/transaction-layer.md, line 115 at r1](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkdCu4V07CIIMRy_ua4:-MkmMTrc5_yKvGm5M8Lm:bf9umgh) ([raw file](https://github.com/cockroachdb/docs/blob/f523c3fc55ed154c7f4845083893241664ab5548/v21.2/architecture/transaction-layer.md#L115)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Unfortunately, they currently are not "durable" in the usual meaning of the word, which is "persisted to disk; recoverable after node restart". Hopefully they will be, one day.
I'd say that closed timestamps are valid even as leaseholders change; a new leaseholder will not break a promise made by an old leaseholder.
</blockquote></details>

Revised based on this comment to say 

"Note that closed timestamps are valid even if the leaseholder changes, since they are preserved across [lease transfers](replication-layer.html#epoch-based-leases-table-data).  Once a lease transfer occurs, the new leaseholder will not break the closed timestamp promise made by the old leaseholder."

**Review by taroface — APPROVED** [review]
Mostly had minor terminology/clarification questions around "timestamp", but otherwise lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11762#-:-Mkmrlvt99p6k7BFy6A8:b-hqxvib)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @rmloveland)

___
*[v21.2/follower-reads.md, line 25 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmorQT9sDKdMtiGajn:-MkmorQT9sDKdMtiGajo:bq5lyp5) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/follower-reads.md#L25)):*
> ```
> "closed timestamp"
> ```

Should this be quotes or italics? You use the latter below
___
*[v21.2/architecture/replication-layer.md, line 76 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoHIH6Ya2Wm1togFo:-MkmoHIH6Ya2Wm1togFp:bf5bwyk) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/replication-layer.md#L76)):*
> ```
> a.k.a.
> ```

Nit: aka
___
*[v21.2/architecture/replication-layer.md, line 76 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoNsF9eYbTy27GEZ2:-MkmoNsF9eYbTy27GEZ3:b-w81pin) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/replication-layer.md#L76)):*
> ```
> incurring networking round trips
> ```

Should this be something like "incurring latency from networking round trips"?
___
*[v21.2/architecture/transaction-layer.md, line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoTwP80S6pOGPJD6p:-MkmoTwP80S6pOGPJD6q:bf5bwyk) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L47)):*
> ```
> a.k.a.
> ```

Nit: aka
___
*[v21.2/architecture/transaction-layer.md, line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoXGZ5yV04XlGXiXP:-MkmoXGZ5yV04XlGXiXQ:b-c7nxs8) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L47)):*
> ```
> up to date
> ```

Nit: up-to-date
___
*[v21.2/architecture/transaction-layer.md, line 101 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoePq-v3eA0i6B8Ou:-MkmoePq-v3eA0i6B8Ov:bf5bwyk) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L101)):*
> ```
> a.k.a.
> ```

Nit: aka
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmonzUDgIU5MNhpJfo:-MkmonzUDgIU5MNhpJfp:b-g2hwcl) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
> ```
> "closed timestamp"
> ```

Ditto: quotes or italics?
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmp2EI4W3z2N01ZmD5:-Mkmp2EI4W3z2N01ZmD6:be9hco2) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
> ```
> retry error
> ```

transaction retry error?
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmp9zD46UT5ex6B0D3:-Mkmp9zD46UT5ex6B0D4:b-r9fwnb) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
> ```
> below that timestamp
> ```

Is "below" a common timestamp term? (Disregard if so.) 

If not, would "before" (or "earlier than", "prior to") that timestamp be clearer?
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmpRIe-el-tKNUrZ7G:-MkmpRIe-el-tKNUrZ7H:b-s7w5fu) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
> ```
> a timestamp less than its closed timestamp
> ```

Ditto - "less" also seems to have a different meaning than "below"; would "a timestamp with a lower value than" be too much?
___
*[v21.2/architecture/transaction-layer.md, line 109 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmq4Xs6LRyxzVhHI1U:-Mkmq4Xs6LRyxzVhHI1V:b-md9cn0) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L109)):*
> ```
> t will not accept writes below that timestamp.
> ```

Ditto
___
*[v21.2/architecture/transaction-layer.md, line 111 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmqw8T3hcLNrhFL-9l:-Mkmqw8T3hcLNrhFL-9m:b-evszz3) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L111)):*
> ```
> closed timestamps
> ```

Necessary to hyphenate? Not sure
___
*[v21.2/architecture/transaction-layer.md, line 111 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmrIDw5L-n3VfQ8V5D:-MkmrIDw5L-n3VfQ8V5E:b-5zua01) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L111)):*
> ```
> piggy-backing
> ```

Happy to report that "piggybacking" is one (1) word!
___
*[v21.2/architecture/transaction-layer.md, line 113 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmr5GHCY3KKL2t_1m4:-Mkmr5GIANLTNFG5XuNf:b-p4us8s) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L113)):*
> ```
> timestamps less than or equal to
> ```

Same general terminology question as above, although the meaning here is very clear to me
___
*[v21.2/architecture/transaction-layer.md, line 115 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmrbYN6rJydvo6lLNU:-MkmrbYN6rJydvo6lLNV:b-a8br2t) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L115)):*
> ```
> closed timestamp
> ```

Ditto re: hyphenation
___
*[v21.2/architecture/transaction-layer.md, line 412 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmrikF4sU7YUMesvit:-MkmrikF4sU7YUMesviu:bhd0d4o) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L412)):*
> ```
> closed timestamp
> ```

Maybe ital this?

**Review by rmloveland — COMMENTED** [review]
Thanks Ryan!!!

PS "Piggybacking" finally made it in! Yay!!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11762#-:-MkrUQym35KKXhZnsDkT:by506qc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @nvanbenschoten, and @taroface)

___
*[v21.2/follower-reads.md, line 25 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmorQT9sDKdMtiGajn:-MkrSBAU2NtB-VJCljke:b-8cm98y) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/follower-reads.md#L25)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> "closed timestamp"
> ```

Should this be quotes or italics? You use the latter below
</blockquote></details>

Changed to use italics for first use on the Follower Reads page
___
*[v21.2/architecture/replication-layer.md, line 76 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoHIH6Ya2Wm1togFo:-MkrSOGg5ENLaJqD9RQe:b-bu91xm) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/replication-layer.md#L76)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> a.k.a.
> ```

Nit: aka
</blockquote></details>

Updated
___
*[v21.2/architecture/replication-layer.md, line 76 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoNsF9eYbTy27GEZ2:-MkrSRbgEvKJh_i1K2E6:b-xrbfyu) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/replication-layer.md#L76)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> incurring networking round trips
> ```

Should this be something like "incurring latency from networking round trips"?
</blockquote></details>

Updated to say that!
___
*[v21.2/architecture/transaction-layer.md, line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoTwP80S6pOGPJD6p:-MkrSYkl9oSBWhHmV1t9:b-bw8e1h) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L47)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> a.k.a.
> ```

Nit: aka
</blockquote></details>

Updated!
___
*[v21.2/architecture/transaction-layer.md, line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoXGZ5yV04XlGXiXP:-MkrSbMO2r76s7JJYCrE:b-bu91xm) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L47)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> up to date
> ```

Nit: up-to-date
</blockquote></details>

Updated
___
*[v21.2/architecture/transaction-layer.md, line 101 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmoePq-v3eA0i6B8Ou:-MkrSjnHCRDcXSQvVLnz:b-bu91xm) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L101)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> a.k.a.
> ```

Nit: aka
</blockquote></details>

Updated
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmonzUDgIU5MNhpJfo:-MkrSqX2C03Ra8uoGxT2:b-w5b0bp) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> "closed timestamp"
> ```

Ditto: quotes or italics?
</blockquote></details>

Updated to use italics upon first use - matches FR page now
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmp2EI4W3z2N01ZmD5:-MkrSvtN1WlkIpgzpSp5:b-qzycc6) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> retry error
> ```

transaction retry error?
</blockquote></details>

yes, added
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmp9zD46UT5ex6B0D3:-MkrT-pG-5w1Bwo7pDqU:b-qi58iw) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> below that timestamp
> ```

Is "below" a common timestamp term? (Disregard if so.) 

If not, would "before" (or "earlier than", "prior to") that timestamp be clearer?
</blockquote></details>

Yeah it's in common usage - elsewhere we also talk about a "high water mark" or similar that is always rising
___
*[v21.2/architecture/transaction-layer.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmpRIe-el-tKNUrZ7G:-MkrTDpF07EXsTAG_xec:b-i1aupv) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L107)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> a timestamp less than its closed timestamp
> ```

Ditto - "less" also seems to have a different meaning than "below"; would "a timestamp with a lower value than" be too much?
</blockquote></details>

I think "less than" and "below" are meant to be synonyms, but just using different words to avoid overusing "below"
___
*[v21.2/architecture/transaction-layer.md, line 109 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmq4Xs6LRyxzVhHI1U:-MkrTdFx6-LCHDl249Iq:b-ya81ng) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L109)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> t will not accept writes below that timestamp.
> ```

Ditto
</blockquote></details>

Same as above
___
*[v21.2/architecture/transaction-layer.md, line 111 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmqw8T3hcLNrhFL-9l:-MkrTo0kBFdLuAVuu3E8:b-xkrr2a) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L111)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> closed timestamps
> ```

Necessary to hyphenate? Not sure
</blockquote></details>

I don't think so (but of course I wouldn't! :-} )
___
*[v21.2/architecture/transaction-layer.md, line 111 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmrIDw5L-n3VfQ8V5D:-MkrTs2YDoC6vKoceX4H:b-n9gchx) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L111)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> piggy-backing
> ```

Happy to report that "piggybacking" is one (1) word!
</blockquote></details>

WHAT

ok updated

it has finally evolved into normal usage!@!!!!!1!
___
*[v21.2/architecture/transaction-layer.md, line 113 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-Mkmr5GHCY3KKL2t_1m4:-MkrTzHx3cW5I00YJ_Vm:b-5evtag) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L113)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> timestamps less than or equal to
> ```

Same general terminology question as above, although the meaning here is very clear to me
</blockquote></details>

I think same as above this is just to provide another way of thinking about it, but essentially a synonym for "below" 
___
*[v21.2/architecture/transaction-layer.md, line 115 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmrbYN6rJydvo6lLNU:-MkrU8800lY5kgMhxoM0:b-wtpjsn) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L115)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> closed timestamp
> ```

Ditto re: hyphenation
</blockquote></details>

I don't think so?
___
*[v21.2/architecture/transaction-layer.md, line 412 at r2](https://reviewable.io/reviews/cockroachdb/docs/11762#-MkmrikF4sU7YUMesvit:-MkrUJ-oA0C9A_oL4yiZ:b-dzxer1) ([raw file](https://github.com/cockroachdb/docs/blob/9795596c58251eb49bf40b1475f369308b49141d/v21.2/architecture/transaction-layer.md#L412)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> closed timestamp
> ```

Maybe ital this?
</blockquote></details>

I think I'll leave the italics for the first usage in the 'Closed Timestamps' section. Tbh I don't really know which is right, but that feels ok

**Pull request merged**
