### PR TITLE
DOC-6023: First round of external link fixes

### PR DESCRIPTION
**Pull request by nickvigilante**
- Fix link in Kubernetes Operator docs
- Add has_sha256sum to `releases.csv` to properly render what links are available
- Exclude local-only URLs from htmltest

Fixes DOC-6023

Relates to DOC-6024

### CODE REVIEW

**Review by andf-crl — APPROVED** [review]
LGTM, as long as seemingly unrelated `no_source` column update from `true` to `false` was intended.

I spot checked a few dozen `SHA256` download links, and all work as expected now. Nice one!

**Comment by nickvigilante** [comment]
@andf-crl My RegEx failed me! Aaaah. One sec

**Review by rmloveland — APPROVED** [review]
LGTM modulo that I don't understand the SHA256 thing very well

It would be good if what that means were written in the description of linked issue, even just a few words for future CRDB archaeologists

**Comment by nickvigilante** [comment]
@rmloveland Thanks for the feedback! I forgot to add descriptions in those tickets since I created it from the subtask view. Anyway, those are added, and this should be ready to go. I'll be around tomorrow in case you wanna regenerate the new release note using the latest script and repo.

**Comment by rmloveland** [comment]
Nick Vigilante ***@***.***> writes:

> @rmloveland Thanks for the feedback! I forgot to add descriptions in
> those tickets since I created it from the subtask view. Anyway, those
> are added, and this should be ready to go.

Awesome thank you!!!!!

> I'll be around tomorrow in
> case you wanna regenerate the new release note using the latest script
> and repo.

OK will def be doing that tomorrow (er, today) :-}

**Pull request merged**
