### PR TITLE
DOC-1449 new custom drag time selection

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-1449 

- Added mention of new feature: drag within a Custom Chart to set a custom time range.
	- Feautre backported through to v21.2, so including this text backwards likewise.

Staging:

- [ui-custom-chart-debug-page.md](https://deploy-preview-15461--cockroachdb-docs.netlify.app/docs/stable/ui-custom-chart-debug-page.html#use-the-custom-chart-page)

### CODE REVIEW

**Review by thtruo — APPROVED** [review]
Short and sweet, LGTM!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15461#-:-NFk1ZW42mxEazKyHkpb:byaitvf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl)

**Comment by andf-crl** [comment]
@thtruo Thanks for the review!

**Review by MichaelTrestman — APPROVED** [review]
LGTM

**Comment by andf-crl** [comment]
@MichaelTrestman TYFR!

**Pull request merged**
