### PR TITLE
Node cache recommendations

### PR DESCRIPTION
**Pull request by sploiselle**
- Recommendations for setting cache manually for machines running something in addition to CockroachDB
- Mention of cache flag's default in `start-a-node.md`

@bdarnell – Could I get you to take a quick look? Forgot whose issue this was originally but glad to get them to look at it, as well. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/532)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[recommended-production-settings.md, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/532#-KOGNQ-J06TjbyCOJFA-:-KOGNQ-J06TjbyCOJFA0:370505889) ([raw file](https://github.com/cockroachdb/docs/blob/ad9caf6967e727b02d8a552f8d9e0103db3bcd2e/recommended-production-settings.md#L24)):*
> ```Markdown
> ## Cache Size
> 
> If you run multiple applications on the same machine as a CockroachDB node, you might consider manually setting the cache size instead of using the default 25% of the available disk space.
> ```

`s/the available disk space/available memory/g`

---

*[start-a-node.md, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/532#-KOGNeifil7KoZKJmA0H:-KOGNeifil7KoZKJmA0I:1700997001) ([raw file](https://github.com/cockroachdb/docs/blob/ad9caf6967e727b02d8a552f8d9e0103db3bcd2e/start-a-node.md#L32)):*
> ```Markdown
> `--attrs` | Arbitrary strings, separated by colons, relating to node-level attributes such as topography or machine capability. These can be used to influence the location of data replicas. See [Configure Replication Zones](configure-replication-zones.html) for full details.<br><br>Topography might include datacenter designation (e.g., `us-west-1a`, `us-west-1b`, `us-east-1c`). Machine capabilities might include specialized hardware or number of cores (e.g., `gpu`, `x16c`). The relative geographic proximity of two nodes is inferred from the common prefix of the attributes list, so topographic attributes should be specified first and in the same order for all nodes, for example: <br><br> `--attrs=us-west-1b:gpu`
> `--background` | Set this to start the node in the background. This is better than appending `&` to the command because control is returned to the shell only once the node is ready to accept requests.
> `--cache` | The total size for caches, shared evenly if there are multiple storage devices. This can be in any bytes-based unit, for example: <br><br>`--cache=1000000000  -> 1000000000 bytes`<br>`--cache=1GB         -> 1000000000 bytes`<br>`--cache=1GiB        -> 1073741824 bytes` <br><br>**Default:** Cache size is limited to to 25% of the available disk space calculated when the node starts.
> ```

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/532)*

**Comment by sploiselle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[recommended-production-settings.md, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/532#-KOGNQ-J06TjbyCOJFA-:-KOGXkIdKnzBS5t0mMBO:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/ad9caf6967e727b02d8a552f8d9e0103db3bcd2e/recommended-production-settings.md#L24)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/the available disk space/available memory/g`
</details>
Done.

---

*[start-a-node.md, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/532#-KOGNeifil7KoZKJmA0H:-KOGXkwb_0ebZmeZWvkH:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/ad9caf6967e727b02d8a552f8d9e0103db3bcd2e/start-a-node.md#L32)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ditto.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/532)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/532#-:-KOGowjSTZF6yRmrW-p2:1417088721)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/532#-:-KOGzLCDIf7Bmd9EBjrZ:1417088721)*

**Comment by sploiselle** [comment]
Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/532#-:-KOHc0bPUeYxU9uQo4yR:-1834867277)*

**Pull request merged**
