### PR TITLE
Added content for Logical plans

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Addresses #2044

### CODE REVIEW

**Comment by couchand** [comment]
Looks good.  One thing I think we should mention is the fact that the plan is randomly sampled, so it may or may not be representative of any particular execution of the statement.  Not sure the best way to say that.

**Comment by Amruta-Ranade** [comment]
___
*[v2.2/admin-ui-statements-page.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/4227#-LVsAzXR8vQvx2O92tmd:-LVx8B-2Cbjqe_piT_wp:b1yzey7) ([raw file](https://github.com/cockroachdb/docs/blob/18606f5e4bd6ad63f8ef4a8fbad81f0379c9062e/v2.2/admin-ui-statements-page.md#L65)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

Noting this so we don't forget to do this later:

Once we've implemented the final design for the Logical Plan, we'll want to replace this image with a new snapshot of the statements page (that shows a logical plan).

</blockquote></details>

Yup..made a note of it in my to-check list for the final release doc.

**Comment by Amruta-Ranade** [comment]
Oh! I thought the statements having the same fingerprint would also have the same logical plan. Am I mistaken?

**Comment by Amruta-Ranade** [comment]
Is it okay if I merge this PR for now, and we can rework the section once I get back from vacation? Or is this caveat a blocker?

**Comment by piyush-singh** [comment]
For an Alpha, I think this is okay. There are some nuances - sampling plans for example like Andrew mentioned, and indeed, statements having the same fingerprint can have different logical plans (i.e. you can cause a join to use different join mechanisms based on cardinality of inputs, or you can just add an index to a table and the same exact query will now be planned differently). We can worry about those more subtly nuances for the full release docs.

**Pull request merged**
