### PR TITLE
v2.0 alpha.20180122 release notes

### PR DESCRIPTION
**Pull request by jseldess**

### CODE REVIEW

**Comment by jseldess** [comment]
@dt, this PR didn't have a release note text. Does it need to be mentioned? https://github.com/cockroachdb/cockroach/pull/20449

**Comment by dt** [comment]
@jseldess Whoops, sorry, yes:

Release note (enterprise): sync bulk writes to disk periodically to more predictable performance.

**Comment by lhirata** [comment]
LGTM with a minor nit:

In Bug Fixes > "Fixed tuple equality to evaluate correctly in the presence of NULL elements. #21230", should NULL be `NULL`?

**Comment by jseldess** [comment]
Thanks, @lhirata.

**Pull request merged**
