### PR TITLE
20.2 EXPLAIN updates

### LINKED ISSUE #5987: Unify Explain User Experience
Background: https://cockroachlabs.atlassian.net/browse/CRDB-302

Description: CockroachDB now supports a robust EXPLAIN. EXPLAIN contains all of the relevant information needed to understand query planning and execution for the majority of use cases. 

Currently, CockroachDB has multiple permutations for EXPLAIN including Verbose, Opt, Types, DistSQL as well as the intersections of these permutations (e.g., Opt ENV). This can be confusing to customers and can make it difficult to drive customers to consistently use EXPLAIN--a primary introspection tool for use understanding query planning and execution. 

Developers can be unsure which EXPLAIN variation should be used as their primary troubleshooting tool.

Team: Andrew Woods, Jordan Lewis, Radu Berinde

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/41039 https://github.com/cockroachdb/cockroach/issues/41201

### LINKED ISSUE #6376: sql: improve explain documentation by highlighting all=full table scan
In the [explain documentation](https://www.cockroachlabs.com/docs/v19.2/explain.html#main-content), we don't show that all is equal to a full table scan.

However, in the [explain guide](https://www.cockroachlabs.com/docs/v19.2/sql-tuning-with-explain.html), we do:

```
The row with spans | ALL shows you that, without a secondary index on the name column, CockroachDB scans every row of the users table, ordered by the primary key (city/id), until it finds the row with the correct name value.
```

We should highlight this in the documentation so that people can better understand the value of explain.

### LINKED ISSUE #7521: SQL Tuning page: Plan shows hash-join instead of lookup-join
I believe the plan example in this spot in the docs shows the wrong plan. It shows a hash-join, but the description suggests an lookup-join

https://www.cockroachlabs.com/docs/stable/sql-tuning-with-explain.html#solution-provide-primary-key-to-allow-lookup-join

image

Also, when I run the explain on the movr database, it shows a lookup-join.

```
root@:26257/movr> EXPLAIN SELECT * FROM vehicles JOIN rides ON rides.vehicle_id = vehicles.id and rides.city = vehicles.city limit 1;
          tree          |         field         |           description
------------------------+-----------------------+----------------------------------
                        | distributed           | true
                        | vectorized            | false
  render                |                       |
   └── limit            |                       |
        │               | count                 | 1
        └── lookup-join |                       |
             │          | table                 | vehicles@primary
             │          | type                  | inner
             │          | equality              | (city, vehicle_id) = (city, id)
             │          | equality cols are key |
             │          | parallel              |
             └── scan   |                       |
                        | table                 | rides@primary
                        | spans                 | FULL SCAN
(14 rows)

Time: 1.471ms
```

### LINKED ISSUE #7599: sql: clarify 'SPANS ALL' is EXPLAIN output
PR: https://github.com/cockroachdb/cockroach/pull/46708

From release notes:
> CockroachDB will now be more verbose about full scans when executing [`EXPLAIN`](../v20.2/explain.html). Previously, we would output `SPANS | ALL`, now it will be `SPANS | FULL SCAN` or (if there is a limit) `SPANS | LIMITED SCAN`. [#46708][#46708] {% comment %}doc{% endcomment %}

### LINKED ISSUE #7851: sql: implement ConstructFilter and ConstructExplain in the new factory
PR: https://github.com/cockroachdb/cockroach/pull/49857

From release notes:
> For some [`EXPLAIN`](../v20.2/explain.html) variants, the property `distributed` for the output variable `Field` has been renamed as `distribution` and can have `local`, `partial`, or `full` values. The `partial` state is currently only possible with the experimental setting. [#49857][#49857] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8140: sql: don't show the "hidden" column flag in EXPLAIN
PR: https://github.com/cockroachdb/cockroach/pull/51837

From release notes:
> [`EXPLAIN`](../v20.2/explain.html) no longer shows the "hidden" annotation for columns. [#51837][#51837] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8146: sql: clean up EXPLAIN node names
PR: https://github.com/cockroachdb/cockroach/pull/52195

From release notes:
> Added cosmetic improvements to [`EXPLAIN`](../v20.2/explain.html) node naming. [#52195][#52195] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8149: sql: don't show grouping columns as aggregations in EXPLAIN
PR: https://github.com/cockroachdb/cockroach/pull/52232

From release notes:
> [`EXPLAIN`](../v20.2/explain.html) no longer shows grouping columns as "aggregations" for the group operator. [#52232][#52232] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8163: sql: new EXPLAIN infrastructure
PR: https://github.com/cockroachdb/cockroach/pull/52730

From release notes:
> Added various improvements to [`EXPLAIN`](../v20.2/explain.html). [#52730][#52730] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8299: sql: add estimated row count and cost in EXPLAIN
PR: https://github.com/cockroachdb/cockroach/pull/52798

From release notes:
> [`EXPLAIN`](../v20.2/explain.html) now shows estimated row count for scans (when statistics are available). [`EXPLAIN (VERBOSE)`](../v20.2/explain.html) now shows the estimated row count for all operators. [#52798][#52798] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8304: sql: reduce projects, improve span display in EXPLAIN
PR: https://github.com/cockroachdb/cockroach/pull/52865

From release notes:
> Improved display of spans in [`EXPLAIN`](../v20.2/explain.html). [#52865][#52865] {% comment %}doc{% endcomment %}
>
> [`EXPLAIN`](../v20.2/explain.html) now shows fewer "project" nodes. [#52865][#52865] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8310: sql: more EXPLAIN improvements
PR: https://github.com/cockroachdb/cockroach/pull/53003

From release notes:
> Improved [`EXPLAIN`](../v20.2/explain.html) output for set operations. [#53003][#53003] {% comment %}doc{% endcomment %}
>
> Improved [`EXPLAIN`](../v20.2/explain.html) output for scalar groups. [#53003][#53003] {% comment %}doc{% endcomment %}
>
> Improved [`EXPLAIN`](../v20.2/explain.html) output for join nodes. [#53003][#53003] {% comment %}doc{% endcomment %}
>
> Removed some unnecessary [`EXPLAIN`](../v20.2/explain.html) fields, and relegated others to the `VERBOSE` variant. [#53003][#53003] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8331: colexec: clean up vectorized stats
PR: https://github.com/cockroachdb/cockroach/pull/53153

From release notes:
> Previously, `selectivity` information would be included in [`EXPLAIN ANALYZE`](../v20.2/explain-analyze.html) diagrams if a query was executed via the [vectorized execution engine](../v20.2/vectorized-execution.html). This has been removed due to being confusing and probably unhelpful. [#53153][#53153] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8332: colexec: clean up vectorized stats
PR: https://github.com/cockroachdb/cockroach/pull/53153

From release notes:
> `stall time` has been renamed to `IO time` in [`EXPLAIN ANALYZE`](../v20.2/explain-analyze.html) diagrams for queries executed via the [vectorized execution engine](../v20.2/vectorized-execution.html). [#53153][#53153] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8347: colexec: add bytes read information to the vectorized stats
PR: https://github.com/cockroachdb/cockroach/pull/53371

From release notes:
> [`EXPLAIN ANALYZE`](../v20.2/explain-analyze.html) diagrams now contain "bytes read" information for table readers and lookup joins when the queries are executed via the [vectorized execution engine](../v20.2/vectorized-execution.html). [#53371][#53371] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8350: colexec: add number of rows read by ColBatchScan
PR: https://github.com/cockroachdb/cockroach/pull/53775

From release notes:
> [`EXPLAIN ANALYZE`](../v20.2/explain-analyze.html) diagrams now contain the information about the number of rows read by the vectorized table reader. [#53775][#53775] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7521.
Fixes #8149. 
Fixes #8140. 
Fixes #8146.
Fixes #7599. 
Fixes #7851. 
Fixes #8347.
Fixes #6376. 
Fixes #8350. 
Fixes #8331.
Fixes #8299. 
Fixes #8163. 
Fixes #8304. 
Fixes #8310.
Fixes #8332.
Fixes #5987.

This PR includes:
* Updates to example output (including DistSQL diagrams) on `EXPLAIN` pages and other pages with examples that use `EXPLAIN`.
* Updates to parameter and output field descriptions listed in `EXPLAIN` docs.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@RaduBerinde Adding you as primary engineer to review updates. Please let me know if I've missed anything important.

@yuzefovich Adding you to review vectorized output updates, especially on the `EXPLAIN ANALYZE` page.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @RaduBerinde, and @yuzefovich)

___
*[v20.2/explain-analyze.md, line 56 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSOptVCYiGLWKaqctr:-MHSOptVCYiGLWKaqcts:bn86vi9) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L56)):*
> ```Markdown
> Field | Description | Execution engine
> ------+-------------+----------------
> &lt;ProcessorName&gt;/&lt;n&gt; | The processor and processor ID used to read data into the SQL execution engine.<br><br>A processor is a component that takes streams of input rows, processes them according to a specification, and outputs one stream of rows. For example, a "TableReader" processor reads in data, and an "Aggregator" aggregates input rows. | Both
> ```

`<ProcessorName>/<n>` - this looks unusual.
___
*[v20.2/explain-analyze.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSP-JM3_zHYAeDXZN1:-MHSP-JM3_zHYAeDXZN2:bvm01fj) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L58)):*
> ```Markdown
> &lt;ProcessorName&gt;/&lt;n&gt; | The processor and processor ID used to read data into the SQL execution engine.<br><br>A processor is a component that takes streams of input rows, processes them according to a specification, and outputs one stream of rows. For example, a "TableReader" processor reads in data, and an "Aggregator" aggregates input rows. | Both
> &lt;index&gt;@&lt;table&gt; | The index used by the processor. | Both
> Spans | The columns used by the processor. | Both
> ```

`Spans` is a different thing - it is an interval of the key space that will be read by the processor (for example, `[/1 - /1]` indicates that only the key with value `1` will be read by the processor). I'm not sure how to describe it in comprehensible terms though. Maybe Radu will have some thoughts.
___
*[v20.2/explain-analyze.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSPkme07MTG2TpFnFw:-MHSPkme07MTG2TpFnFx:bgsrq7b) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L70)):*
> ```Markdown
> execution time | How long the engine spent executing the processor. | Vectorized engine only
> max vectorized memory allocated | How much memory is allocated to the processor to buffer batches of columnar data. | Vectorized engine only
> max disk used | How much disk (if any) is used to buffer data. Routers and processors will spill to disk buffering if there is not enough memory to buffer the data. | Both
> ```

`max disk used` is displayed by row-by-row processors and `max vectorized disk used` is displayed by vectorized processors.
___
*[v20.2/explain-analyze.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQ0vl2CDrPJTNzYr6:-MHSQ0vl2CDrPJTNzYr7:bdghznd) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L73)):*
> ```Markdown
> left(@&lt;n&gt;)=right(@&lt;n&gt;) | The equality columns used in the join. | Both
> stored side | The smaller table that was stored as an in-memory hash table. | Both
> rows routed | How many rows were sent by routers, which can be used to understand network usage. | Both
> ```

`rows routed` is only displayed with row-by-row engine.
___
*[v20.2/known-limitations.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQNBEBpI_m63Ir4u4:-MHSQNBEBpI_m63Ir4u5:bp9026h) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/known-limitations.md#L103)):*
> ```Markdown
> [Tracking Github Issue](https://github.com/cockroachdb/cockroach/issues/42896)
> 
> ### Filtering by `now()` results in a full table scan
> ```

This is no longer true, but there might be a separate docs issue opened for it.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421#-:-MHXHulk9KpRycCGBnkP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @RaduBerinde)

___
*[v20.1/sql-tuning-with-explain.md, line 296 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHXHR7f9gLhGKqIv65i:-MHXHR7f9gLhGKqIv65j:brez1at) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.1/sql-tuning-with-explain.md#L296)):*
> ```
> users_name_idx
> ```

This index shouldn't exist here, should it?

**Review by ericharmeling — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421#-:-MHlm98D0mdQqTNzs2zZ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[v20.1/sql-tuning-with-explain.md, line 296 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHXHR7f9gLhGKqIv65i:-MHljCsE8uH7ZUHT9i_8:b-x9rimf) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.1/sql-tuning-with-explain.md#L296)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

> ```
> users_name_idx
> ```

This index shouldn't exist here, should it?
</blockquote></details>

It should not. Good catch! fixed.
___
*[v20.2/explain-analyze.md, line 56 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSOptVCYiGLWKaqctr:-MHlkRns0cG6TNao1p3F:b-uvb3rf) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L56)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`<ProcessorName>/<n>` - this looks unusual.
</blockquote></details>

It does. I changed it to `&lt;Processor&gt;/&lt;id&gt;`. Is that a little better?
___
*[v20.2/explain-analyze.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSP-JM3_zHYAeDXZN1:-MHlkvdt0GD7GOd106FV:b-bw8e14) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L58)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`Spans` is a different thing - it is an interval of the key space that will be read by the processor (for example, `[/1 - /1]` indicates that only the key with value `1` will be read by the processor). I'm not sure how to describe it in comprehensible terms though. Maybe Radu will have some thoughts.
</blockquote></details>

Updated.
___
*[v20.2/explain-analyze.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSPkme07MTG2TpFnFw:-MHllR_oDwoL3qyEpNPa:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L70)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`max disk used` is displayed by row-by-row processors and `max vectorized disk used` is displayed by vectorized processors.
</blockquote></details>

Done.
___
*[v20.2/explain-analyze.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQ0vl2CDrPJTNzYr6:-MHllSAf-1aQRFhqXHSx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L73)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`rows routed` is only displayed with row-by-row engine.
</blockquote></details>

Done.
___
*[v20.2/known-limitations.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQNBEBpI_m63Ir4u4:-MHlm3Pm31p76PpWtCBl:b2z38vu) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/known-limitations.md#L103)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This is no longer true, but there might be a separate docs issue opened for it.
</blockquote></details>

I think we should address that in a separate docs PR, but I don't see a separate docs issue... do you have a link to the `cockroachdb` PR?

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @RaduBerinde)

___
*[v20.2/explain-analyze.md, line 56 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSOptVCYiGLWKaqctr:-MHmE1fZErodsZhVD2pE:b-5a6q3r) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L56)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

It does. I changed it to `&lt;Processor&gt;/&lt;id&gt;`. Is that a little better?
</blockquote></details>

Yeah, I think it's cleaner this way - (when I saw it initially, I thought it was like HTML gone wrong - `/<n>` is similar to a newline character).
___
*[v20.2/known-limitations.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQNBEBpI_m63Ir4u4:-MHmEWaVANReCl3T37E_:bj2b60q) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/known-limitations.md#L103)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I think we should address that in a separate docs PR, but I don't see a separate docs issue... do you have a link to the `cockroachdb` PR?
</blockquote></details>

@raduberinde I think we have addressed this limitation in 20.2, right? I couldn't find a PR though.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @yuzefovich)

___
*[v20.2/known-limitations.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQNBEBpI_m63Ir4u4:-MHmGn7g2jGSizXnEz7x:bn5d6c8) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/known-limitations.md#L103)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@raduberinde I think we have addressed this limitation in 20.2, right? I couldn't find a PR though.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/50320  Added the docs-todo label.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @yuzefovich)

___
*[v20.2/known-limitations.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQNBEBpI_m63Ir4u4:-MHmGwe49S9KSuvH8M1R:b-cqeegt) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/known-limitations.md#L103)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/pull/50320  Added the docs-todo label.
</blockquote></details>

This was the issue: https://github.com/cockroachdb/cockroach/issues/18836

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[v20.2/explain-analyze.md, line 56 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSOptVCYiGLWKaqctr:-MHqGwuLEakaQI2u8OJd:b-7ofvx8) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/explain-analyze.md#L56)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, I think it's cleaner this way - (when I saw it initially, I thought it was like HTML gone wrong - `/<n>` is similar to a newline character).
</blockquote></details>

That makes a lot of sense. Thanks!
___
*[v20.2/known-limitations.md, line 103 at r1](https://reviewable.io/reviews/cockroachdb/docs/8421#-MHSQNBEBpI_m63Ir4u4:-MHqHSXmBbvei6bLXh_1:bob02c4) ([raw file](https://github.com/cockroachdb/docs/blob/7a95d0681df0ee1a95c0eabb792e17327838c6c2/v20.2/known-limitations.md#L103)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This was the issue: https://github.com/cockroachdb/cockroach/issues/18836
</blockquote></details>

Got it. Opened a new docs issue for this: https://github.com/cockroachdb/docs/issues/8442.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8421#-:-MHrHEsYEoBeSgHRIDd0:by6fmpn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh and @yuzefovich)

**Pull request merged**
