### PR TITLE
251 constraints

### PR DESCRIPTION
**Pull request by uptimeDBA**
Ok, be gentle. My first ever PR.
It would be nice to be able to include the grammar diagrams for the constraints.
Not sure if the {{site.data.alerts.warning}} markdown works.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/280)

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @uptimeDBA! And congrats on your first PR! It's also our first substantial docs PR from an external contributor!

I think it's best to focus on correctness rather than style (copyediting, formatting). Once we get sign-off from a few devs, I'll merge and then open a separate PR for copyediting.

@dt, @mjibson, can you please review for correctness?

**Comment by dt** [comment]
Might see several changes if/when cockroachdb/cockroach/pull/6625 lands.

<details><summary><i>Previously, jseldess wrote…</i></summary>
> Thanks, @uptimeDBA! And congrats on your first PR! It's also our first substantial docs PR from an external contributor!
> 
> 
> 
> I think it's best to focus on correctness rather than style (copyediting, formatting). Once we get sign-off from a few devs, I'll merge and then open a separate PR for copyediting.
> 
> 
> 
> @dt, @mjibson, can you please review for correctness?</details>


---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[data-definition.md, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVE-apYtypBCY0Am8p:-KHVE-apYtypBCY0Am8q:1483984805) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L51)):*
> ```Markdown
> ### Primary Key Constraint
> 
> Specifies the column values are unique and that the column may **not** contain *NULL* values. A `UNIQUE` index called **primary** is created on the column.
> ```

Not sure if I'd assert `A `UNIQUE` index called **primary** is created on the column.` -- we don't create an additional index really, rather the keys under which rows are stored are derived from the primary key, meaning they can be used like an index.

Also might be worth noting something to the effect that specifying a primary key does't add any storage/index cost the way specifying a secondary index does, since if a primary key is *not* specified, a special, hidden column is added internally and made the primary key anyway. Thus, with rare exceptions, it is almost always preferable to specify an explicit primary key.

---

*[data-definition.md, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVDHTzP3Ys8v1vte7g:-KHVDHTzP3Ys8v1vte7h:-448635421) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L111)):*
> ```Markdown
> 
> A Check constraint allows you to specify a boolean expression that must evaluate to true for every row affected by an INSERT or UPDATE statement. The DML statement will fail if the condition evaluates to false or unknown for any row.
> ```

Should probably drop a big warning here that CHECKs are still a work in progress and are not ready for production use (not checked during UPDATE, not maintained in renames, etc).

---

*[data-definition.md, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVBxTbsOIcgiqRTZo4:-KHVBxTbsOIcgiqRTZo5:-1467210074) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L112)):*
> ```Markdown
> A Check constraint allows you to specify a boolean expression that must evaluate to true for every row affected by an INSERT or UPDATE statement. The DML statement will fail if the condition evaluates to false or unknown for any row.
> 
> You can only have one Check constraint on a single column but you can combine multiple conditions with the AND operator and you can have Check constraints on multiple columns but an argument of a Check constraint cannot refer to other columns.
> ```

I just sent a out cockroachdb/cockroach#6625 which will add table-level, and move all constraints up to the table-level.

---

*[data-definition.md, line 132 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVB_kf9kwYz8T2UzpR:-KHVB_kf9kwYz8T2UzpS:-1225217816) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L132)):*
> ```Markdown
> ~~~
> 
> Check constraints can only be specified at the column level, not at the table level.
> ```

Ditto cockroachdb/cockroach#6625: column-level are just shorthand and get moved during CREATE).

---

*[data-definition.md, line 136 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVBMjDqloI3VzbZwnq:-KHVBMjDqloI3VzbZwnr:1134262623) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L136)):*
> ```Markdown
> 
> {{site.data.alerts.warning}}
> If a Check constraint is defined on an optional column (one where a NULL value is allowed), then all INSERT or UPDATE statements containing rows with NULL values in that column will fail because the condition will not evaluate to true when a NULL is used in the expression. To work around this, include the condition "OR column IS NULL" in the Check constraint.
> ```

cockroachdb/cockroach#6625 also includes allowing NULLs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280#-:-KHVCyxc0shcfGVUa8KC:1598710975)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVE-apYtypBCY0Am8p:-KHVSsnoLyG7YE_nC8VR:-1417766601) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L51)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Not sure if I'd assert `A `UNIQUE` index called **primary** is created on the column.` -- we don't create an additional index really, rather the keys under which rows are stored are derived from the primary key, meaning they can be used like an index.
> 
> Also might be worth noting something to the effect that specifying a primary key does't add any storage/index cost the way specifying a secondary index does, since if a primary key is *not* specified, a special, hidden column is added internally and made the primary key anyway. Thus, with rare exceptions, it is almost always preferable to specify an explicit primary key.</details>
It's also possible to give the primary index a name other than "primary" (with `CREATE TABLE (... CONSTRAINT index_name PRIMARY KEY (col))` 

The primary key is special in other ways as well: it can only be set in CREATE TABLE; it can't be changed later with ALTER TABLE or DROP INDEX. 

---

*[data-definition.md, line 31 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVVSdZIfkoIyCF7BiB:-KHVVSdZIfkoIyCF7BiC:-965144930) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L31)):*
> ```Markdown
> | NOT NULL | Specifies the column **may not** contain *NULL* values. See [NOT NULL](data-definition.html#not-null) Constraint.  |
> | Primary Key | Specifies that the column(s) values are unique and that the column(s) **may not** contain *NULL* values. See [Primary Key](data-definition.html#primary-key) Constraint. |
> | Unique | Specifies that the column(s) values are unique and that the column(s) **may** contain *NULL* values. See [Unique](data-definition.html#unique) Constraint. |
> ```

We also have non-unique indexes (which can only be specified at the table level). They're not technically constraints, although they're close enough to unique indexes that they should probably be discussed here.

---

*[data-definition.md, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVRrWcVbEBhVdSOqXq:-KHVRrWcVbEBhVdSOqXr:-838259974) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L33)):*
> ```Markdown
> | Unique | Specifies that the column(s) values are unique and that the column(s) **may** contain *NULL* values. See [Unique](data-definition.html#unique) Constraint. |
> | Check |  Specifies that the column value must satisfy a Boolean expression. See [Check](data-definition.html#check) Constraint. |
> | Default Value | Specifies a value to populate a column with if none is provided. See [Default Value](data-definition.html#default-value) Constraint. |
> ```

Defaults aren't technically a constraint, so I'd probably keep them in a separate section (although if we're including non-unique indexes then maybe this doesn't need to be strictly limited to constraints)

---

*[data-definition.md, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVW7a_nFVTDI52haK4:-KHVW7a_nFVTDI52haK5:497281833) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L36)):*
> ```Markdown
> 
> 
> ### NOT NULL
> ```

It's also possible to indicate the absence of a NOT NULL constraint by explicitly declaring a column as NULL: `cust_name STRING(30) NULL`. (It's redundant so I'm not sure if it's ever useful to do this, but it's there)

---

*[data-definition.md, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVTP2P0rfKFCtci9ZO:-KHVTP2QqJbjL8VF4HFA:1013447871) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L85)):*
> ```Markdown
> ### Unique
> 
> A Unique constraint is specified using `UNIQUE` at either the column or table level. It requires that the column(s) values are unique and that the column(s) **may** contain *NULL* values. A unique index called ***\<tablename\>*_*\<columnname(s)\>*_key** is created on the column(s).
> ```

Again, the index can be given a name other than the default with the `CONSTRAINT name` syntax.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVRrWcVbEBhVdSOqXq:-KHVX22GCmdYtQZkNX3c:-697953167) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L33)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Defaults aren't technically a constraint, so I'd probably keep them in a separate section (although if we're including non-unique indexes then maybe this doesn't need to be strictly limited to constraints)</details>
fwiw, http://www.postgresql.org/docs/current/static/sql-createtable.html includes `DEFAULT` as a "constraint" too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVRrWcVbEBhVdSOqXq:-KHVXgG5EjUB0E0Xd8Z4:-856264722) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L33)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> fwiw, http://www.postgresql.org/docs/current/static/sql-createtable.html includes `DEFAULT` as a "constraint" too.</details>
Though in the more detailed docs they split it out: http://www.postgresql.org/docs/9.5/static/ddl.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVDHTzP3Ys8v1vte7g:-KHWP0RpLm4lLE_WHv6S:-1956583398) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L111)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Should probably drop a big warning here that CHECKs are still a work in progress and are not ready for production use (not checked during UPDATE, not maintained in renames, etc).</details>
Let's definitely call this out, Paul. We can open another PR once CHECKs are fully implemented.

---

*[data-definition.md, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVBxTbsOIcgiqRTZo4:-KHWPGZpyMs_Gn0K8x3k:-1418415078) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L112)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I just sent a out cockroachdb/cockroach#6625 which will add table-level, and move all constraints up to the table-level.</details>
I apologize for not calling out that this change is imminent, Paul. Feel free to hold off on revisions until David's PR has been merged. 

---

*[data-definition.md, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVRrWcVbEBhVdSOqXq:-KHWOYAv8O2_Ld-DuDjb:-564411831) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L33)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Though in the more detailed docs they split it out: http://www.postgresql.org/docs/9.5/static/ddl.html</details>
I actually intended to have a separate section on "Default Values", so I like the idea of creating a separate section on this page for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by uptimeDBA** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVBxTbsOIcgiqRTZo4:-KHWWjpcfRFU1Sn6ByzF:132819761) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L112)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> I apologize for not calling out that this change is imminent, Paul. Feel free to hold off on revisions until David's PR has been merged. </details>
All good, I'll wait for [#6625](https://github.com/cockroachdb/cockroach/pull/6625)

---

*[data-definition.md, line 132 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVB_kf9kwYz8T2UzpR:-KHWXfvViczT8tUhJ8q7:-124011965) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L132)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Ditto cockroachdb/cockroach#6625: column-level are just shorthand and get moved during CREATE).</details>
Is the column level CHECK constraint syntax disappearing or just being added to the table level? I understand all constraints will be internally represented at the table level but is this a distinction to be made in the documentation? (other than any reflection will show them at table level.) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by uptimeDBA** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 31 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVVSdZIfkoIyCF7BiB:-KHWdqopzW2TOx0UydD3:909280285) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> We also have non-unique indexes (which can only be specified at the table level). They're not technically constraints, although they're close enough to unique indexes that they should probably be discussed here.</details>
The discussion around non-unique indexes, and the unique indexes associated with the `PRIMARY KEY` and `UNIQUE` constraints will be included in the Indexes section.

---

*[data-definition.md, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVW7a_nFVTDI52haK4:-KHWeoAOOBAhxvW0dsAj:180708186) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L36)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It's also possible to indicate the absence of a NOT NULL constraint by explicitly declaring a column as NULL: `cust_name STRING(30) NULL`. (It's redundant so I'm not sure if it's ever useful to do this, but it's there)</details>
In other works I've referred to this constraint as an Optionality  constraint with values `NULL` and `NOT NULL`. I'll mention the ability to specify `NULL`  and change the example to `cust_name STRING(30) NULL`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 132 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVB_kf9kwYz8T2UzpR:-KHWdIjRN5Ro6DOUNWMb:2119951320) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L132)):*
<details><summary><i>Previously, uptimeDBA (Paul Steffensen) wrote…</i></summary>
> Is the column level CHECK constraint syntax disappearing or just being added to the table level? I understand all constraints will be internally represented at the table level but is this a distinction to be made in the documentation? (other than any reflection will show them at table level.) </details>
Yep, specifying on the column will still work -- it will be rewritten to be table level before the CREATE is executed, so they are effectively just short-hand for the general case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by jseldess** [comment]
@uptimeDBA, just FYI, that PR on moving constraints up to the table level has been merged: https://github.com/cockroachdb/cockroach/pull/6625

**Comment by uptimeDBA** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[data-definition.md, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVRrWcVbEBhVdSOqXq:-KHq1Vtkke1Fh5wHuIKi:-1451534605) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L33)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> I actually intended to have a separate section on "Default Values", so I like the idea of creating a separate section on this page for that.</details>
Yep, semantically speaking, defaults aren't constraints but they are lumped in with them. Our sql grammar makes them look like a constraint.



The syntax supports statements like `CREATE TABLE t (c1 INT CONSTRAINT c1_default DEFAULT 100)`. 

I think we should keep the Default Values documentation together with constraints or change the syntax to something like:



 I have no idea how hard/easy changing the grammar would be so my preference is to keep it as is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by uptimeDBA** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[data-definition.md, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVE-apYtypBCY0Am8p:-KHqJ5mHY6XsQZKoBqxb:2097200941) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L51)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It's also possible to give the primary index a name other than "primary" (with `CREATE TABLE (... CONSTRAINT index_name PRIMARY KEY (col))` 
> 
> The primary key is special in other ways as well: it can only be set in CREATE TABLE; it can't be changed later with ALTER TABLE or DROP INDEX. </details>
@dt On the surface (in the SQL layer), it *looks* like we create an unique index called primary.
~~~sql
CREATE TABLE t (c1 INT PRIMARY KEY)
SHOW INDEXES FROM t
+-------+---------+--------+-----+--------+-----------+---------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing |
+-------+---------+--------+-----+--------+-----------+---------+
| t     | primary | true   |   1 | c1     | ASC       | false   |
+-------+---------+--------+-----+--------+-----------+---------+
~~~
I'll include comments that this is really a pseudo index that is derived from the keys  under which rows are stored. 

@bdarnell  From my tests, you can optionally name a Primary Key constraint  but the name is not given to the index or  referenced in error messages.

~~~sql
root@localhost:26257> create table t (c1 int constraint t_pk primary key not null);
CREATE TABLE
root@localhost:26257> show indexes from t;
+-------+---------+--------+-----+--------+-----------+---------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing |
+-------+---------+--------+-----+--------+-----------+---------+
| t     | primary | true   |   1 | c1     | ASC       | false   |
+-------+---------+--------+-----+--------+-----------+---------+
root@localhost:26257> insert into t values (100);
INSERT 1
root@localhost:26257> insert into t values (100);
pq: duplicate key value (c1)=(100) violates unique constraint "primary"
root@localhost:26257>  
~~~

I will include the special restrictions around modifying the primary key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[data-definition.md, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVE-apYtypBCY0Am8p:-KHrQXCso0nIcT1ue5JG:-333320498) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L51)):*
<details><summary><i>Previously, uptimeDBA (Paul Steffensen) wrote…</i></summary>
> @dt On the surface (in the SQL layer), it *looks* like we create an unique index called primary.
> ~~~sql
> CREATE TABLE t (c1 INT PRIMARY KEY)
> SHOW INDEXES FROM t
> +-------+---------+--------+-----+--------+-----------+---------+
> | Table |  Name   | Unique | Seq | Column | Direction | Storing |
> +-------+---------+--------+-----+--------+-----------+---------+
> | t     | primary | true   |   1 | c1     | ASC       | false   |
> +-------+---------+--------+-----+--------+-----------+---------+
> ~~~
> I'll include comments that this is really a pseudo index that is derived from the keys  under which rows are stored. 
> 
> @bdarnell  From my tests, you can optionally name a Primary Key constraint  but the name is not given to the index or  referenced in error messages.
> 
> ~~~sql
> root@localhost:26257> create table t (c1 int constraint t_pk primary key not null);
> CREATE TABLE
> root@localhost:26257> show indexes from t;
> +-------+---------+--------+-----+--------+-----------+---------+
> | Table |  Name   | Unique | Seq | Column | Direction | Storing |
> +-------+---------+--------+-----+--------+-----------+---------+
> | t     | primary | true   |   1 | c1     | ASC       | false   |
> +-------+---------+--------+-----+--------+-----------+---------+
> root@localhost:26257> insert into t values (100);
> INSERT 1
> root@localhost:26257> insert into t values (100);
> pq: duplicate key value (c1)=(100) violates unique constraint "primary"
> root@localhost:26257>  
> ~~~
> 
> I will include the special restrictions around modifying the primary key.</details>
Ah, looks like that's a bug. We use the name if the CONSTRAINT clause is on its own, but not if it's used as a modifier to the column:

```
root@:26257> create table t (c1 int constraint t_pk primary key not null);
CREATE TABLE
root@:26257> show indexes from t;
+-------+---------+--------+-----+--------+-----------+---------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing |
+-------+---------+--------+-----+--------+-----------+---------+
| t     | primary | true   |   1 | c1     | ASC       | false   |
+-------+---------+--------+-----+--------+-----------+---------+
root@:26257> drop table t;
^[[ADROP TABLE
root@:26257> create table t (c1 int not null, constraint t_pk primary key (c1));
CREATE TABLE
root@:26257> show indexes from t;
+-------+------+--------+-----+--------+-----------+---------+
| Table | Name | Unique | Seq | Column | Direction | Storing |
+-------+------+--------+-----+--------+-----------+---------+
| t     | t_pk | true   |   1 | c1     | ASC       | false   |
+-------+------+--------+-----+--------+-----------+---------+
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by uptimeDBA** [comment]
Review status: 0 of 35 files reviewed at latest revision, 8 unresolved discussions.

---

*[data-definition.md, line 136 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVBMjDqloI3VzbZwnq:-KHwmOjEWS28E2dYWRdg:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/3ae234cd22e507ec97db5dfb1790f26ef06347cb/data-definition.md#L136)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> cockroachdb/cockroach#6625 also includes allowing NULLs.</details>
Done.

---

*[data-definition.md, line 85 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/280#-KHVTP2P0rfKFCtci9ZO:-KHwmVHyU3OXo_whYELy:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/84f05d1c8b97928a9849b117b8fde86490fcbcdb/data-definition.md#L85)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Again, the index can be given a name other than the default with the `CONSTRAINT name` syntax.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280)*

**Comment by dt** [comment]
BTW, this (and #296) want to be squashed before they're ready to merge. Interactive rebase is the most general way to do that, but in this case you might want the simpler `git reset --soft origin/gh-pages && git commit` (the first part moves the index back to master but leaves your changes staged to commit, the second lets you write a single commit message that describes the whole change).

**Comment by dt** [comment]
And if you want to get really fancy, if you include a line `Fixes #251` in the commit message (has to be on its own line), then it will automatically update the issue and, when the commit merges, close that issue with a link to the commit.

**Comment by bdarnell** [comment]
I wouldn't worry too much about squashing doc commits - we're much less likely to be poring through the logs like we do in the code repos.

**Comment by jseldess** [comment]
LGTM, Paul. Thanks for working this out. I'll merge this PR and then open another to take care of formatting and copyedits. 

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I wouldn't worry too much about squashing doc commits - we're much less likely to be poring through the logs like we do in the code repos. 
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 35 of 35 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/280#-:-KI4q3NASc-Y9aDhsK_t:-260625765)*

**Pull request merged**
