### PR TITLE
mark external links with arrow symbol

### PR DESCRIPTION
**Pull request by elkmaster**
mark all links with different hostname
Screenshot 2020-11-04 at 15 25 06

Resolves: #2607

### CODE REVIEW

**Review by jseldess — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8823#-:-MLhYcFqBjFyzobLdqYR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yingzhuchin** [comment]
I think this is ready to merge. @luciaaaaaaa and @lnhsingh, do you want to sign off?

**Comment by lnhsingh** [comment]
Can we exclude the links in the footer and the top left logo from having the arrow icon?

**Comment by elkmaster** [comment]
@lnhsingh We can, but in prod all `cochoachlabs.com` links will be internal and will not have this symbol. Only couple in footer that are really external will be marked. So I would leave it as is, what do you think?

**Comment by lnhsingh** [comment]
@elkmaster Oh, ok! That makes sense. It seems fine to leave as is then - thank you! LGTM

**Review by lnhsingh — APPROVED** [review]

**Comment by lnhsingh** [comment]
@luciaaaaaaa I think this is ready to merge - where you able to take a look at this?

**Pull request merged**
