### PR TITLE
Remove a known limitation.

### PR DESCRIPTION
**Pull request by knz**
Requested by @andreimatei in https://github.com/cockroachdb/cockroach/pull/23373#issuecomment-383617998.

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @knz, but it's misleading to remove the limitation before the fix has made it into an official release, don't you think? Instead of deleting the limitation from the page, we tend to add a note that it's been "resolved as of xxx release", for example, https://www.cockroachlabs.com/docs/v1.1/known-limitations.html#maximum-cluster-size. Should we just open a docs issue to do this work in conjunction with the next 2.1 alpha release?

**Comment by knz** [comment]
We could leave this PR open until the relevant 2.1 alpha is released. I'm happy if you take this over. I created this docs PR just because @andreimatei didn't want me (us) to forget about documenting that this limitation is being lifted.

**Comment by andreimatei** [comment]
I thought there was a place where we list the "resolved limitations" since the previous major release, but I can't find it now... @jseldess is there / should there be?

My opinion is that this PR can be merged. I feel that it's not worth being strict about when documentation for unreleased versions is updated.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/3013#-:-LAnef50722plF9HR-kg:bn7u48d)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/3013#-:-LAnf1KI-n_I_JyXAeWi:bnfp4nl)*

**Comment by jseldess** [comment]
@andreimatei, the way we've done it up till now is we've added a "Resolved in xxx release" and then, in the known limitations for the following major release, we've remove the limitations entirely. 

I agree that we shouldn't be strict about merging changes for dev releases. It's a discussion topic in tomorrow's docs meeting, actually, so I'll return to this once the team is on the same page here.

**Comment by jseldess** [comment]
The docs team now has a more formalized approach to [documenting across versions](https://github.com/cockroachdb/docs/wiki/Updating-Docs-Across-Versions), which includes updating dev (2.1) docs before releases, if need be. So merging this. Thanks, @knz and @andreimatei.

**Pull request merged**
