### PR TITLE
Update orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

### PR DESCRIPTION
**Pull request by Geet-writes**
Typo fixed for the issue - "typo on K8s multi-cluster setup page #7967"
Changed 'Context' to 'Contexts' on line 482.

### CODE REVIEW

**Review by taroface — APPROVED** [review]
LGTM 👍

**Comment by taroface** [comment]
@Geet-writes Thank you for your help on this! I approved, but just realized that v20.2 docs should also have this correction. Would you be able to update that version of the doc as well?

**Comment by Geet-writes** [comment]
Hi,
Thanks.
Yes sure I will do that as well.

**Comment by jseldess** [comment]
Thanks for your help, @Geet-writes. We took care of the full update in https://github.com/cockroachdb/docs/issues/7967.

**Comment by Geet-writes** [comment]
Thank you.
Apologies for not being able to finish it. Family medical problems!

Regards,
Geetanjali

**Pull request closed without merging**
