### PR TITLE
Added cloud toggle examples to BACKUP & RESTORE pages v21.1

### LINKED ISSUE #10285: Documentation for backups does not show examples of uploading to AWS, S3 etc.
https://www.cockroachlabs.com/docs/stable/backup.html

This file only shows examples of backing up to Google storage.  There are no examples for AWS, S3.  In addition, all the upload types are not even mentioned, so there's no way for a customer to know uploading to AWS, S3 etc is even possible.

Also, there needs to be examples of using userfile and nodelocal.

### PR DESCRIPTION
**Pull request by kathancox**
Closes #10285 

Relates to #10544

Added a toggle to the example sections of `BACKUP` and `RESTORE` (v21.1) for s3, gcs, and azure. This covers some issues and questions around specific URLs for the cloud options. 

Possibility to add further storage options to toggle in future. And gives the opportunity to provide more detail on some of the examples when cloud specific.

This toggle setup will be replicated across all the bulk operations, `IMPORT`, `EXPORT` etc.

### CODE REVIEW

**Review by mwang1026 — CHANGES_REQUESTED** [review]
The toggles look great! The changes below look good to me. I don't know if you wanted a separate PR / issue to track those same changes / how you want to approach changes on the "subpages" such as `take-full-and-incremental-backups#incremental-backups-with-explicitly-specified-destinations`. For now requesting changes assuming it'll be same PR but if you want to track separately go ahead!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10770#-:-McL2vwg9Jjc6tsH17vf:b-uostdf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

**Comment by kathancox** [comment]
I've included updates to further backup/restore related pages here. Couple notes:

* Kept toggling only to **Examples** sections.
* On the incremental backups page I've followed the PITR page and used a generic `{destination}` where it made sense.
* On the Encryption page, from what I gather AWS KMS encryption is available beyond AWS services, but you would need a further API... so I kept the connection path in that section to `s3` for now.
* Haven't worked on Locality-aware yet, will bundle this into the next PR after I've done some testing!

**Review by mwang1026 — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

**Comment by kathancox** [comment]
cc @mikeCRL

**Review by rmloveland — APPROVED** [review]
LGTM, wrote a few things but nothing non-blocking!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10770#-:-Mcyt7zZ3126lel8wVY2:b-7lhw2a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

___
*[v21.1/backup.md, line 262 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcyt_MI6dHUwaiZHHQl:-Mcyt_MI6dHUwaiZHHQm:b-qxb5al) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/backup.md#L262)):*
> ```Markdown
> 
> <section class="filter-content" markdown="1" data-scope="azure">
> ```

meta comment: the complexity tax would probably be terrible, but with these filter buttons I have wondered if there's a way to add conditional logic using the Liquid templating language in Jekyll so we can avoid some of the costly repetition in the filter subsections.  Then again we would have the costly complexity of checking the conditional logic, so :shrug: 

nothing to do just thinking out loud, sorry!
___
*[v21.1/backup.md, line 265 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McyjAw09zOcSAnE3jEt:-McyjAw09zOcSAnE3jEu:bujgb7w) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/backup.md#L265)):*
> ```Markdown
> ### Backup a cluster
> 
> To take a [full backup](take-full-and-incremental-backups.html#full-backups) a cluster:
> ```

"of a cluster"  ?
___
*[v21.1/backup.md, line 276 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McyjL1zETMc3uxb7sR5:-McyjL1zETMc3uxb7sR6:b-bko1s7) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/backup.md#L276)):*
> ```Markdown
> ### Backup a database
> 
> To take a [full backup](take-full-and-incremental-backups.html#full-backups) a single database:
> ```

"of a single database" ?
___
*[v21.1/backup.md, line 346 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcyk4aa8bOKwa9GikPh:-Mcyk4aa8bOKwa9GikPi:bj4t1l2) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/backup.md#L346)):*
> ```Markdown
> ~~~
> 
> **Without** the `DETACHED` option, `BACKUP` will block the SQL connection until the job completes. Once finished, the job status and more detailed job data is returned:
> ```

Noice add'l detail
___
*[v21.1/backup.md, line 365 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McykEdyCIzvJTuOeWbN:-McykEdyCIzvJTuOeWbO:b-crgiku) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/backup.md#L365)):*
> ```Markdown
> ### Backup a cluster
> 
> To take a [full backup](take-full-and-incremental-backups.html#full-backups) a cluster:
> ```

"of a cluster" ?
___
*[v21.1/backup.md, line 376 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McykHQD-hyEFKGXzivJ:-McykHQD-hyEFKGXzivK:b-bko1s7) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/backup.md#L376)):*
> ```Markdown
> ### Backup a database
> 
> To take a [full backup](take-full-and-incremental-backups.html#full-backups) a single database:
> ```

"of a single database" ?
___
*[v21.1/restore.md, line 203 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McykqaqAjTOH27dcOfV:-McykqaqAjTOH27dcOfW:buniwn7) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L203)):*
> ```Markdown
> ### View the backup subdirectories
> 
> <span class="version-tag">New in v21.1:</span> `BACKUP ... INTO` adds a backup to a collection within the backup destination. The path to the backup is created using a date-based naming scheme. To view the backup paths in a given destination, use [`SHOW BACKUPS`]:
> ```

Not part of this PR, but this `SHOW BACKUPS` reference here is busted
___
*[v21.1/restore.md, line 371 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McylRYIDDNvwF4MqpS9:-McylRYIDDNvwF4MqpSA:b-2stlqt) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L371)):*
> ```Markdown
> </section>
> 
> <section class="filter-content" markdown="1" data-scope="gcs">
> ```

Very nit: It doesn't matter at all technically, but it might be slightly nicer for folks working on this page if the ordering of the `<section>`s were the same as the ordering in the filter buttons above

however since for the foreseeable future "folks working on this page" is probably "you" feel free to ignore this! :-) 
___
*[v21.1/restore.md, line 379 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcylsfc-2knRU6Kom-S:-Mcylsfc-2knRU6Kom-T:b-orgc99) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L379)):*
> ```Markdown
> ### View the backup subdirectories
> 
> <span class="version-tag">New in v21.1:</span> `BACKUP ... INTO` adds a backup to a collection within the backup destination. The path to the backup is created using a date-based naming scheme. To view the backup paths in a given destination, use [`SHOW BACKUPS`]:
> ```

`SHOW BACKUPS` ref is busted
___
*[v21.1/restore.md, line 408 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcym8Z11VFk_ZtK9MRB:-Mcym8Z11VFk_ZtK9MRC:b-mfjyhh) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L408)):*
> ```Markdown
> To view the available subdirectories, use [`SHOW BACKUPS`](#view-the-backup-subdirectories).
> 
> ### Restore a database
> ```

nit: For ultimate consistency, it would be nice if this section had "To restore a database: ..." like the others
___
*[v21.1/restore.md, line 508 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McymofXA74RlPEgdi5B:-McymofXA74RlPEgdi5C:bc1gtnf) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L508)):*
> ```Markdown
> #### Remove the foreign key before restore
> 
> By default, tables with [Foreign Key](foreign-key.html) constraints must be restored at the same time as the tables they reference. However, using the [`skip_missing_foreign_keys`](restore.html#skip_missing_foreign_keys) option you can remove the Foreign Key constraint from the table and then restore it.
> ```

Foreign Key does not need to be capitalized/titlecased in this context
___
*[v21.1/restore.md, line 523 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcynlb2AFgRXhhaT8LL:-McynYbZEeyOyhuc7F_M:b-b7k8dz) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L523)):*
> ```Markdown
> After it's restored into a new database, you can write the restored `users` table data to the cluster's existing `system.users` table.
> 
> {% include copy-clipboard.html %}
> ```

In addition to the explanation above, it might be good to explicitly walk the user through each of these steps and what they mean to ensure they know exactly which part of this they are doing at each step, since this seems like a sensitive operation on the `system` table.

E.g., 

"first create the new DB you'll restore the system.users table into

after the restore completes, add the users to the existing system.users table"

etc.

however that may be too hand-holdy and not necessary, leave it to you, I don't really know this area well etc.
___
*[v21.1/restore.md, line 551 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McynN2pC4V1UCxQ0GIC:-McynN2q3mQc73GYv5jM:bbp0p1e) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L551)):*
> ```Markdown
> ### View the backup subdirectories
> 
> <span class="version-tag">New in v21.1:</span> `BACKUP ... INTO` adds a backup to a collection within the backup destination. The path to the backup is created using a date-based naming scheme. To view the backup paths in a given destination, use [`SHOW BACKUPS`]:
> ```

busted ref to `SHOW BACKUPS`
___
*[v21.1/restore.md, line 580 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McyocJyD7X-6jflEf88:-McyocJyD7X-6jflEf89:b-vowy0x) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L580)):*
> ```Markdown
> To view the available subdirectories, use [`SHOW BACKUPS`](#view-the-backup-subdirectories).
> 
> ### Restore a database
> ```

same as above re: mumbling something here before the SQL statement
___
*[v21.1/restore.md, line 633 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcyolqh87eTYt5f6Vnm:-Mcyolqh87eTYt5f6Vnn:bq8t7vv) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L633)):*
> ```Markdown
> <span class="version-tag">New in v21.1:</span> `RESTORE` will re-validate [indexes](indexes.html) when [incremental backups](take-full-and-incremental-backups.html) are created from an older version, but restored from a newer version.
> 
> Incremental backups created by v20.2.2 and prior v20.2.x releases or v20.1.4 and prior v20.1.x releases may include incomplete data for indexes that were in the process of being created. Therefore, when incremental backups taken by these versions are restored by v21.1.0+, any indexes created during those incremental backups will be re-validated by `RESTORE`.
> ```

The first part makes me think CRDB always re-validates indexes

the second makes me think it only happens for the specified versions

which is it?  or are both things true?

FWIW I think the first part is less specific but much easier to understand, but can understand if the info in the 2nd part is necessary because we are talking about backups here and folks could get concerned about specifics

but IMO if the second paragraph is obsoleted by what's in the first then the second is not necessary (again, just IMO, I don't have context). the specificity in the 2nd feels like a "confusion tax" on all users so we can say something specific to 20.1 and 20.2 users, so it depends on whether that is needed / worth it

(Guess this question also applies to the other "copies" of this too)
___
*[v21.1/restore.md, line 680 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McypHa01424Gb0dbFHP:-McypHa01424Gb0dbFHQ:b-bprfjt) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L680)):*
> ```Markdown
> #### Remove the foreign key before restore
> 
> By default, tables with [Foreign Key](foreign-key.html) constraints must be restored at the same time as the tables they reference. However, using the [`skip_missing_foreign_keys`](restore.html#skip_missing_foreign_keys) option you can remove the Foreign Key constraint from the table and then restore it.
> ```

same re: not needing caps on foreign key mentions
___
*[v21.1/restore.md, line 695 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McypMhm4b7-urrI9EFs:-McypMhm4b7-urrI9EFt:boktixd) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/restore.md#L695)):*
> ```Markdown
> After it's restored into a new database, you can write the restored `users` table data to the cluster's existing `system.users` table.
> 
> {% include copy-clipboard.html %}
> ```

same as above re: whether to be more hand-holdy 
___
*[v21.1/take-and-restore-encrypted-backups.md, line 124 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McypgItAq6cZow53xTf:-McypgItAq6cZow53xTg:by0t43t) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/take-and-restore-encrypted-backups.md#L124)):*
> ```Markdown
> - [Restore from an encrypted backup using a passphrase](#restore-from-an-encrypted-backup-using-a-passphrase)
> 
> <div class="filters clearfix">
> ```

not strictly in this PR, but this page has multiple "Examples" anchors in the TOC but b/c they are not unique, when I click the one that's supposed to point to here, it takes me to the other one

apologies since you are probably very familiar with this but I think this could be solved with custom anchors or just renaming the subsections

... or not worrying about it in this PR, if that is your preference :-) 
___
*[v21.1/take-and-restore-encrypted-backups.md, line 140 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McyqE1P5AuCLcvGgj46:-McyqE1Q2a6SRL95VLWj:bjvc5jm) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/take-and-restore-encrypted-backups.md#L140)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> > BACKUP TO 's3://{BUCKET NAME}/{PATH}?AWS_ACCESS_KEY_ID={KEY ID}&AWS_SECRET_ACCESS_KEY={SECRET ACCESS KEY}' WITH encryption_passphrase = 'password123';
> ```

random thought: this could be 'hunter2' for moar internet points but maybe this is better in a professional setting

no need to respond, sorry sorry
___
*[v21.1/take-and-restore-encrypted-backups.md, line 149 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McyqxK0AZKTQ45ZPweY:-McyqxK0AZKTQ45ZPweZ:b-yx8g4a) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/take-and-restore-encrypted-backups.md#L149)):*
> ```Markdown
> ~~~
> 
> To [restore](restore.html), use the same `encryption_passphrase`. See the [example](#restore-from-an-encrypted-backup-using-a-passphrase) below for more details.
> ```

I like the anchor to the next/prev examples as future-proofing!
___
*[v21.1/take-and-restore-locality-aware-backups.md, line 50 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-McyraHA2z4YxpLcXhax:-McyraHA2z4YxpLcXhay:bk7xrqy) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/take-and-restore-locality-aware-backups.md#L50)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> For guidance on connecting to other storage options or using other authentication parameters, read [Use Cloud Storage for Bulk Operations](use-cloud-storage-for-bulk-operations.html).
> ```

This and the other 4-6 variations of this phrase in this PR could be made into 1 "include" that says the same thing everywhere.  That said, I'm kinda ambivalent about them because they are a different kind of pain.  In this case because there are so many almost-repetitions of this phrase in various places it might be worth doing an include, since the variations may make it hard to search/update in the future
___
*[v21.1/take-full-and-incremental-backups.md, line 186 at r2](https://reviewable.io/reviews/cockroachdb/docs/10770#-Mcysc_54hFJTcpsLjsf:-Mcysc_54hFJTcpsLjsg:b-42q7h1) ([raw file](https://github.com/cockroachdb/docs/blob/b635fbf2faa62f462b2d2df70b029a9eb6a3acfc/v21.1/take-full-and-incremental-backups.md#L186)):*
> ```Markdown
> </section>
> 
> <section class="filter-content" markdown="1" data-scope="azure">
> ```

same as above re: matching ordering of filter buttons and sections, if it matters to you (and ok if it doesn't)

**Pull request merged**
