### PR TITLE
v2.1.9 release notes

### LINKED ISSUE #5369: v2.1.9 Release Notes
https://github.com/cockroachdb/cockroach/issues/40491

Tentative release: 9/23

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #5369.

### CODE REVIEW

**Comment by bdarnell** [comment]
We should add a note for cockroachdb/cockroach#40353, which went in without one because we didn't grasp its significance when it was originally written. This is the biggest bug fix and the whole reason we're pushing this build now. 

"Fixed a bug that could lead to data inconsistencies and crashes with the message `consistency check failed with N inconsistent replicas`."

**Comment by ericharmeling** [comment]
> We should add a note for [cockroachdb/cockroach#40353](https://github.com/cockroachdb/cockroach/pull/40353), which went in without one because we didn't grasp its significance when it was originally written. This is the biggest bug fix and the whole reason we're pushing this build now.
> 
> "Fixed a bug that could lead to data inconsistencies and crashes with the message `consistency check failed with N inconsistent replicas`."

Done! Thanks @bdarnell.

**Comment by ericharmeling** [comment]
Handing this off to you, @rmloveland

**Comment by rmloveland** [comment]
@bdarnell  and @jseldess , mind taking one more pass over these?  

Updated with a few new commits and updated the date to 9/23, everything else should be the same, hopefully.

**Comment by rmloveland** [comment]
Thanks Ben.  Removed dupes, publishing now.

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUCYZFCDXEPyJoDtcw:-LpUCYZFCDXEPyJoDtcx:b-drtqx3) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L51)):*
> ```Markdown
> - Fix bug where MVCC value at future timestamp is returned after a transaction restart. [#40632][#40632] [9dbb670a8][9dbb670a8]
> - Consider intents in a read's uncertainty interval to be uncertain just as if they were committed values. This removes the potential for stale reads when a causally dependent transaction runs into the not-yet resolved intents from a causal ancestor. [#40632][#40632] [d6b00e37e][d6b00e37e]
> - Fix wrong comparator used in RocksDB compaction picker, which can lead to infinite compaction loop. [#40752][#40752] [23459d2c4][23459d2c4]
> ```

Duplicate?

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 50 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUCP5k0gdzQlPxvgDS:-LpUCP5lACwB7PsItlhD:b-o9b0sw) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L50)):*
> ```Markdown
> - Unary negatives in constant arithmetic expressions are no longer ignored. [#39368][#39368] [75a8d2468][75a8d2468]
> - Fix bug where MVCC value at future timestamp is returned after a transaction restart. [#40632][#40632] [9dbb670a8][9dbb670a8]
> - Consider intents in a read's uncertainty interval to be uncertain just as if they were committed values. This removes the potential for stale reads when a causally dependent transaction runs into the not-yet resolved intents from a causal ancestor. [#40632][#40632] [d6b00e37e][d6b00e37e]
> ```

Rephrase: Intents in a read's uncertainty interval are now considered uncertain just ....

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 49 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUBGcC2TDPwNuvViAW:-LpUBGcD5p29RfUkvxOU:bb6u7xe) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L49)):*
> ```Markdown
> - Fixed a potential infinite loop in queries involving reverse scans. [#39105][#39105] [6f537772c][6f537772c]
> - Unary negatives in constant arithmetic expressions are no longer ignored. [#39368][#39368] [75a8d2468][75a8d2468]
> - Fix bug where MVCC value at future timestamp is returned after a transaction restart. [#40632][#40632] [9dbb670a8][9dbb670a8]
> ```

Fix > Fixed

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 48 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUCKmp2OSzCxM0hWKW:-LpUCKmp2OSzCxM0hWKX:b-drtqxk) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L48)):*
> ```Markdown
> - Fixed incorrect results, or "unordered span" errors in some cases involving exclusive inequalities with non-numeric types. [#38897][#38897] [c2919b478][c2919b478]
> - Fixed a potential infinite loop in queries involving reverse scans. [#39105][#39105] [6f537772c][6f537772c]
> - Unary negatives in constant arithmetic expressions are no longer ignored. [#39368][#39368] [75a8d2468][75a8d2468]
> ```

Duplicate.

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 47 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUCIKGDOjpWshYRQvD:-LpUCIKGDOjpWshYRQvE:b-ijvpxh) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L47)):*
> ```Markdown
> - Fix wrong comparator used in RocksDB compaction picker, which can lead to infinite compaction loop. [#40752][#40752] [23459d2c4][23459d2c4]
> - Fixed incorrect results, or "unordered span" errors in some cases involving exclusive inequalities with non-numeric types. [#38897][#38897] [c2919b478][c2919b478]
> - Fixed a potential infinite loop in queries involving reverse scans. [#39105][#39105] [6f537772c][6f537772c]
> ```

This is a duplicate.

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUCA4WB3xYChUfkwoa:-LpUCA4WB3xYChUfkwob:b-ijvpxh) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L46)):*
> ```Markdown
> - Unary negatives in constant arithmetic expressions are no longer ignored. [#39368][#39368]
> - Fix wrong comparator used in RocksDB compaction picker, which can lead to infinite compaction loop. [#40752][#40752] [23459d2c4][23459d2c4]
> - Fixed incorrect results, or "unordered span" errors in some cases involving exclusive inequalities with non-numeric types. [#38897][#38897] [c2919b478][c2919b478]
> ```

This is a duplicate.

**Comment by jseldess** [comment]
___
*[releases/v2.1.9.md, line 45 at r2](https://reviewable.io/reviews/cockroachdb/docs/5370#-LpUBEzM2nnWAQnoKk52:-LpUBEzM2nnWAQnoKk53:bb6u7xe) ([raw file](https://github.com/cockroachdb/docs/blob/9febf82b73f0a0ef7379fa407abcf17ddee9bdf4/releases/v2.1.9.md#L45)):*
> ```Markdown
> - Fixed a potential infinite loop in queries involving reverse scans. [#39105][#39105]
> - Unary negatives in constant arithmetic expressions are no longer ignored. [#39368][#39368]
> - Fix wrong comparator used in RocksDB compaction picker, which can lead to infinite compaction loop. [#40752][#40752] [23459d2c4][23459d2c4]
> ```

Fix > Fixed

**Pull request merged**
