### PR TITLE
Add a temp unlinked doc for the CC Free closed beta

### LINKED ISSUE #9169: Add a temporary unlinked docs page on free tier
We want to enable free tier beta for a subset of new organizations before we release it broadly in our marketing launch in January. To support users who get this early access, we want to have a docs page that covers the key points of information but we don't want this page to be broadly accessible to the public. Instead, it should be hidden in the docs nav, and we will simply link to this page from the Console.

The content should basically just cover what we've been emailing customers about, including tenant architecture basics, known limitations, and a request for feedback. This does not need to be as polished as our January docs will be!

Feel free to reach out to Emily with questions.

### PR DESCRIPTION
**Pull request by lnhsingh**
Using the [copy from the email](https://docs.google.com/document/d/1OHRaKknfBifj1bMOzlyg7reUZ4rtkwK4iUUZ7UZdhUk/edit#) that goes out to closed beta users, create a temporary, unlinked doc that explains what CC Free (closed beta) is.

This page will be removed once Free (beta) is released at the end of the month.

Closes #9169.

### CODE REVIEW

**Review by jramos-crl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9272)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jramos-crl and @lnhsingh)

___
*[cockroachcloud/free-closed-beta.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIHsUe4QFifjmIwLzP:-MQIHsUe4QFifjmIwLzQ:bavf636) ([raw file](https://github.com/cockroachdb/docs/blob/c6155eeadf6e770b615f806e68297d0f87b64840/cockroachcloud/free-closed-beta.md#L9)):*
> ```Markdown
> We have been busy building out and improving the CockroachCloud experience and are excited to invite you to a **closed beta** of a new version that will be permanently free to consume!
> 
> We have turned on the ability to create a CockroachCloud Free cluster in your account. Your existing clusters will be unaffected by this additional capability. You will now be able to create up to five free clusters in your organization.
> ```

I would remove the first sentence, "We have turned on the ability to create a CockroachCloud Free cluster in your account." That sentence is meant for users that we reach out to directly. The following sentences there is still important, though it might need some rewording. Perhaps something like "You are now able to create up to five free clusters in your organization. Creating a CockroachCloud Free cluster will not affect your existing clusters in any way."
___
*[cockroachcloud/free-closed-beta.md, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIIaJq9eFNR_1h5SA6:-MQIIaJq9eFNR_1h5SA7:bs1dr94) ([raw file](https://github.com/cockroachdb/docs/blob/c6155eeadf6e770b615f806e68297d0f87b64840/cockroachcloud/free-closed-beta.md#L13)):*
> ```Markdown
> ## What is CockroachCloud Free?
> 
> CockroachCloud Free delivers free CockroachDB clusters for you and your organization. It is a managed instance of CockroachDB that also removes the friction of initial cluster sizing and auto-scales based on your application traffic. While we have eliminated the concept of nodes for you, there will be an upper limit of usage of up to 1 vCPU and 5GB storage per free cluster. More information to follow.
> ```

I would remove the last sentence, "More information to follow".

**Review by jramos-crl — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9272)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9272)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jramos-crl)

___
*[cockroachcloud/free-closed-beta.md, line 9 at r2](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIHsUe4QFifjmIwLzP:-MQIM3Wp19frCioj9PEi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c6155eeadf6e770b615f806e68297d0f87b64840/cockroachcloud/free-closed-beta.md#L9)):*
<details><summary><i>Previously, jramos-crl wrote…</i></summary><blockquote>

I would remove the first sentence, "We have turned on the ability to create a CockroachCloud Free cluster in your account." That sentence is meant for users that we reach out to directly. The following sentences there is still important, though it might need some rewording. Perhaps something like "You are now able to create up to five free clusters in your organization. Creating a CockroachCloud Free cluster will not affect your existing clusters in any way."
</blockquote></details>

Done.
___
*[cockroachcloud/free-closed-beta.md, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIIaJq9eFNR_1h5SA6:-MQIM7nA2IhL_QSmbWbq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c6155eeadf6e770b615f806e68297d0f87b64840/cockroachcloud/free-closed-beta.md#L13)):*
<details><summary><i>Previously, jramos-crl wrote…</i></summary><blockquote>

I would remove the last sentence, "More information to follow". 
</blockquote></details>

Done.

**Comment by jramos-crl** [comment]
Looks good to me! (The emoji wouldn't come up for me...#newb).

**Review by emily-horing — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9272)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jramos-crl, @lnhsingh, and @rmloveland)

___
*[cockroachcloud/free-closed-beta.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIi-_HDrnnkc7jhEI9:-MQIi-_IBMnIDP2kbA_n:b-j6pon6) ([raw file](https://github.com/cockroachdb/docs/blob/d17db5aec2a6b60acca2d3397e2c0cf81c10a736/cockroachcloud/free-closed-beta.md#L7)):*
> ```Markdown
> ---
> 
> We have been busy building out and improving the CockroachCloud experience and are excited to invite you to a **closed beta** of a new version that will be permanently free to consume!
> ```

Would use "offering" instead of "version"
___
*[cockroachcloud/free-closed-beta.md, line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIhNOc1vwdtPFQsOBe:-MQIhNOc1vwdtPFQsOBf:bfsvnv1) ([raw file](https://github.com/cockroachdb/docs/blob/d17db5aec2a6b60acca2d3397e2c0cf81c10a736/cockroachcloud/free-closed-beta.md#L17)):*
> ```Markdown
> ## Can CockroachCloud Free be used for production apps?
> 
> CockroachCloud Free is currently in beta and as such, it is not suitable for production use. Specifically, there are capabilities we are still working on enabling such as the ability to enable backups, and no-downtime upgrades to a paid tier. These capabilities and more are coming soon!
> ```

Would change to "...still working on enabling such as backups and no-downtime upgrades..."
Maybe also worth noting the lack of IMPORT here?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9272)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @jramos-crl, and @rmloveland)

___
*[cockroachcloud/free-closed-beta.md, line 7 at r4](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIi-_HDrnnkc7jhEI9:-MQIrcjJ59k-kbz-8Y0n:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d17db5aec2a6b60acca2d3397e2c0cf81c10a736/cockroachcloud/free-closed-beta.md#L7)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Would use "offering" instead of "version"
</blockquote></details>

Done.
___
*[cockroachcloud/free-closed-beta.md, line 17 at r4](https://reviewable.io/reviews/cockroachdb/docs/9272#-MQIhNOc1vwdtPFQsOBe:-MQIuVsb1RXNYYF1OKa0:b-hdk8iw) ([raw file](https://github.com/cockroachdb/docs/blob/d17db5aec2a6b60acca2d3397e2c0cf81c10a736/cockroachcloud/free-closed-beta.md#L17)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Would change to "...still working on enabling such as backups and no-downtime upgrades..."
Maybe also worth noting the lack of IMPORT here?

</blockquote></details>

Changed to `Specifically, there are capabilities we are still working on enabling, such as the ability to enable backups, to import data, and no-downtime upgrades to a paid tier. These capabilities and more are coming soon!`

**Review by rmloveland — APPROVED** [review]
LGTM but I'm a little bummed we did not go with "Free Forever (tm) (*)" although I know that language is kinda fraught :-) 

(*) as long as this business exists, or until we change our minds, etc.

**Review by lnhsingh — COMMENTED** [review]
Or, "Free 4Eva"

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9272#-:-MQJ3iakC4ujWCRsgktI:bmblaew)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @jramos-crl, and @rmloveland)

**Pull request merged**
