### PR TITLE
Update 20.2 sidebar

### PR DESCRIPTION
**Pull request by lnhsingh**
Update sidebar to match 20.1 sections and add back links that were dropped

cc @yingzhuchin

### CODE REVIEW

**Comment by lnhsingh** [comment]
For reference, the links were dropped from #7964 and #8039. I think those are the only merge conflicts that occurred

**Comment by yingzhuchin** [comment]
Sorry @lnhsingh, just went back and saw a couple links were missed when porting over your CC merge that happened while my PR was open. Restoring with a commit in your branch here -- hope that's okay.

**Comment by lnhsingh** [comment]
Thanks YZ!

**Review by jseldess — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8233#-:-MGIj7g41F-nsFsJvBGd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jseldess)

**Pull request merged**
