### PR TITLE
Propagate lack of stored proc support to 21.2.

### PR DESCRIPTION
**Pull request by stbof**
Fixes https://github.com/cockroachdb/docs/issues/10689 in 21.2.

### CODE REVIEW

**Comment by stbof** [comment]
The last (Misc) table on the web site is broken. 
Screen Shot 2021-09-24 at 1 40 58 PM

I played around with the included warning, but the only way to fix the table was to explictly specify the warning instead of including it. Not sure why.

**Review by ianjevans — APPROVED** [review]
Approved. But I think the reason the include didn't work is because there's a trailing line break in `interleave-deprecation-notice.md`. Can you try removing the line break and see if the table still breaks?

**Comment by stbof** [comment]
> Approved. But I think the reason the include didn't work is because there's a trailing line break in `interleave-deprecation-notice.md`. Can you try removing the line break and see if the table still breaks?

There is no trailing line break that I can see either in Atom, vi, or GH.

**Comment by stbof** [comment]
@ianjevans I could not get the include file to work with the latest version of the referring file. I realized that the include exists because multiple files were including it. I'm worried that the include file still referenced in alter-primary-key and the explicit warning in sql-feature-support will get out of sync. Should I still merge this?

**Comment by ianjevans** [comment]
> @ianjevans I could not get the include file to work with the latest version of the referring file. I realized that the include exists because multiple files were including it. I'm worried that the include file still referenced in alter-primary-key and the explicit warning in sql-feature-support will get out of sync. Should I still merge this?

I tried this locally, and it worked.

```
Interleaved tables | ✓ | CockroachDB Extension | [Interleaved Tables documentation](interleave-in-parent.html)<br>{% include {{ page.version.version }}/misc/interleave-deprecation-note.md -%}
```

See the [Liquid docs on whitespace control](https://shopify.github.io/liquid/basics/whitespace/).

But I also see that my local build doesn't break the table even without the `-%}`. So there's a discrepancy between local Jekyll builds and the Netlify builds, perhaps. Regardless, try pushing a commit with the `-%}` at the end of the include and see if it breaks the table.

**Pull request merged**
