### PR TITLE
beta-20160929 release note updates

### PR DESCRIPTION
**Pull request by jseldess**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/701)

### CODE REVIEW

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/pull/9503: Add the --advertise-host to override the external listening address a node advertises.
https://github.com/cockroachdb/cockroach/pull/9571: Export more metrics about the internal garbage collection of deleted values.
https://github.com/cockroachdb/cockroach/pull/9550: Avoid a potential brief service interruption after a shard splits.
https://github.com/cockroachdb/cockroach/pull/9582: Export metrics about file descriptor usage.
https://github.com/cockroachdb/cockroach/pull/9573: Add the --http-host flag (which together with --http-port will replace --http-addr in a future release).
https://github.com/cockroachdb/cockroach/pull/9578: Updated the system to use OpenTracing's new key-value style logging APIs.
https://github.com/cockroachdb/cockroach/pull/9606: Reenabled consensus-level optimizations for network i/o.

**Comment by jseldess** [comment]
Thanks, @tschottdorf . Are these the right buckets?

**New Features:**
https://github.com/cockroachdb/cockroach/pull/9503: Add the --advertise-host flag to override the external listening address a node advertises.
https://github.com/cockroachdb/cockroach/pull/9571: Export more metrics about the internal garbage collection of deleted values.
https://github.com/cockroachdb/cockroach/pull/9582: Export metrics about file descriptor usage.
https://github.com/cockroachdb/cockroach/pull/9573: Add the --http-host flag (which together with --http-port will replace --http-addr in a future release).
https://github.com/cockroachdb/cockroach/pull/9578: Updated the system to use OpenTracing's new key-value style logging APIs.

**Performance Improvements:**
https://github.com/cockroachdb/cockroach/pull/9550: Avoid a potential brief service interruption after a shard splits.
https://github.com/cockroachdb/cockroach/pull/9606: Re-enabled consensus-level optimizations for network i/o.

Or are some of these considered bug fixes?

**Comment by tschottdorf** [comment]
I would say #9550 is a bug fix. Agreed about the rest and probably you want to group the two flag changes next  to each other.

**Comment by jseldess** [comment]
@tschottdorf, I think we're ready now. PTAL.

**Comment by tschottdorf** [comment]
:lgtm:. I assume you're intentionally not linking to the beta page yet.

---

Reviewed 1 of 2 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[start-a-node.md, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/701#-KSrTW0y2zxDQptQd3TU:-KSrTW0y2zxDQptQd3TV:bjyrvtu) ([raw file](https://github.com/cockroachdb/docs/blob/7ff48c105b5a0895b378d924065d3741665bc26c/start-a-node.md#L30)):*
> ```Markdown
> Flag | Description
> -----|-----------
> `--advertise-host` | The hostname or IP address to advertise to other CockroachDB nodes. If it is a hostname, it must be resolvable from all nodes; if it is an IP address, it must be routable from all nodes.<br><br>When this flag is not set, the node advertises the address in the `--host` flag.
> ```

Shouldn't those be self-closing tags (`<br />`) throughout?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/701#-:-KSrU4yyPV5FaViuR9SD:buh1a6n)*

**Comment by jseldess** [comment]
@tschottdorf, linking to the beta page where?

And `<br>` is actually fine: http://www.w3schools.com/tags/tag_br.asp

**Comment by tschottdorf** [comment]
I thought there was a page that linked to all our beta releases.

**Comment by jseldess** [comment]
Nope, the four most recent releases are show in the sidenav: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4f94c031e906fe8624de56b5eb4dbee337a337a8/beta-20160929.html

Older releases are listed on a specific page: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4f94c031e906fe8624de56b5eb4dbee337a337a8/older-versions.html

**Pull request merged**
