### PR TITLE
Update DATABASE_URLs to specify DB in conn string

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-9413

Summary of changes:

- Update all uses by app example code to include a database name in the connection string.

### CODE REVIEW

**Comment by rmloveland** [comment]
interesting trivia:

- Prisma doesn't seem to need the DB specified, but breaks when running the `prisma migrate` command in the docs didn't work (separate issue, filed DOC-9470)
- Rust example doesn't care about DB being specified in the conn string
- Go examples don't care
- All other example apps break if DB is not specified in conn string

**Review by Xiang-Gu — APPROVED** [review]
LGTM!

**Review by taroface — COMMENTED** [review]
Should this specify the `bank` database according to the examples? Just checking.

**Comment by rmloveland** [comment]
> Should this specify the `bank` database according to the examples? Just checking.

I don't think so. As part of this I manually checked every example app to use this conn string (via the env var) and they all worked fine with this change. 

(I found some other issues with the example apps like out of date libraries n stuff, but that is another matter)

**Comment by taroface** [comment]
> Given that a lot of the apps aren't working at all right now with the existing conn string, I think this is still an improvement!

No, I agree! Chalk it up to my still-fuzzy understanding of how the conn strings work. 

LGTM

**Review by taroface — APPROVED** [review]

**Pull request merged**
