### PR TITLE
adding FAQ

### PR DESCRIPTION
**Pull request by sploiselle**
added JSON, JOIN, and bulk insert FAQ

@knz – Could I get you to take a quick look at the mentions I made of `JOIN` here? I wasn't sure if we could remove it as a limitation or not.

@paperstreet – Could I get you to review the JSON/bulk insert mentions? Feel free to loop in anyone else who ought to review.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/533)

### CODE REVIEW

**Comment by knz** [comment]
A few minor comments. LGTM otherwise.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[frequently-asked-questions.md, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/533#-KOGKNIfLbuzh3hMRhiz:-KOGKNIfLbuzh3hMRhj-:-2036793517) ([raw file](https://github.com/cockroachdb/docs/blob/f65739f2cd0277f8e582ef846dfc0c5d579a9119/frequently-asked-questions.md#L149)):*
> ```Markdown
> ## How do I bulk insert data into CockroachDB?
> 
> Right now, the best way to bulk insert data is to run [`INSERT`](insert.html) statements in batches of 1,000.
> ```

... of hundreds of rows at a time, so that the total payload per INSERT becomes larger than a few kilobytes. However you should still avoid INSERTS of more than a couple megabytes a time.

---

*[frequently-asked-questions.md, line 155 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/533#-KOGKk-t4YxLP0_VuLzT:-KOGKk-t4YxLP0_VuLzU:1088346468) ([raw file](https://github.com/cockroachdb/docs/blob/f65739f2cd0277f8e582ef846dfc0c5d579a9119/frequently-asked-questions.md#L155)):*
> ```Markdown
> CockroachDB has basic, non-optimized support for SQL `JOIN`, whose performance we're working to improve.
> 
> To learn more, see our blog post [CockroachDB's JOIN](https://www.cockroachlabs.com/blog/cockroachdbs-first-join/).
> ```

perhaps "our blog post *on* CockroachDB's JOIN"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/533#-:-KOGKq8eFW3oi1o5HUTS:1396591241)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/533#-:-KOGv59_3oHP3pRdn4O2:1417088721)*

**Comment by paperstreet** [comment]
Thanks! Sorry for randomizing you with this

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[frequently-asked-questions.md, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/533#-KOGKNIfLbuzh3hMRhiz:-KOH0tG9Y9IBumjxtTbP:979068729) ([raw file](https://github.com/cockroachdb/docs/blob/f65739f2cd0277f8e582ef846dfc0c5d579a9119/frequently-asked-questions.md#L149)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> ... of hundreds of rows at a time, so that the total payload per INSERT becomes larger than a few kilobytes. However you should still avoid INSERTS of more than a couple megabytes a time.
</details>
Hard to calculate the size of the rows; did a quick back-of-the-envelope calculation with @paperstreet and figured that 1,000 - 10,000 rows covers most people with a caveat that it depends on the size of the rows. Think that makes a simple recommendation will still making sure we're addressing the concern about size.

---

*[frequently-asked-questions.md, line 155 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/533#-KOGKk-t4YxLP0_VuLzT:-KOH1IrHWjYUxD0udmtD:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/f65739f2cd0277f8e582ef846dfc0c5d579a9119/frequently-asked-questions.md#L155)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> perhaps "our blog post *on* CockroachDB's JOIN"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/533)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[frequently-asked-questions.md, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/533#-KOGKNIfLbuzh3hMRhiz:-KOH46doa96JDqYZzSxQ:945185076) ([raw file](https://github.com/cockroachdb/docs/blob/f65739f2cd0277f8e582ef846dfc0c5d579a9119/frequently-asked-questions.md#L149)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary>
> Hard to calculate the size of the rows; did a quick back-of-the-envelope calculation with @paperstreet and figured that 1,000 - 10,000 rows covers most people with a caveat that it depends on the size of the rows. Think that makes a simple recommendation will still making sure we're addressing the concern about size.
</details>
Then add a footnote / remark saying exactly that! "1,000 - 10,000 rows covers most people with a caveat that it depends on the size of the rows."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/533)*

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[frequently-asked-questions.md, line 149 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/533#-KOGKNIfLbuzh3hMRhiz:-KOHbljyTpc6eQWIxuUG:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/f65739f2cd0277f8e582ef846dfc0c5d579a9119/frequently-asked-questions.md#L149)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Then add a footnote / remark saying exactly that! "1,000 - 10,000 rows covers most people with a caveat that it depends on the size of the rows."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/533)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/533#-:-KOHfcCjQR9S1XKzyw-a:1417088721)*

**Pull request merged**
