### PR TITLE
Add basic PHP sample

### PR DESCRIPTION
**Pull request by tschottdorf**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/154)

### CODE REVIEW

**Comment by jseldess** [comment]
*[_includes/app/basic-sample.php, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/154#-KDtOdFczrVUPevbtkpZ:-KDtOdFczrVUPevbtkp_:572675508) ([raw file](https://github.com/cockroachdb/docs/blob/881b7548bca14bf59790a90014ff963752b3c0e7/_includes/app/basic-sample.php#L9)):*
Toby, we decided to show database creation and table creation using the sql client before these samples, so you can take this bit out. Also, we'll show the `maxroach` user connecting rather than `root`.  

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/154)*

**Comment by jseldess** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/154#-:-KDtQPAOGbKQ4kERfHYu:1417088721)*

**Comment by andreimatei** [comment]
:LGTM: after addressing Jesse's thing.
Are you gonna do the transactional one too, you unsung hero you? :)

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/app/basic-sample.php, line 3 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/154#-KDyjObFH3kZ3BjzXlKa:-KDyjObFH3kZ3BjzXlKb:-1618206422) ([raw file](https://github.com/cockroachdb/docs/blob/881b7548bca14bf59790a90014ff963752b3c0e7/_includes/app/basic-sample.php#L3)):*
nit tabs

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/154#-:-KDyjd8N31uBNoEa4YFy:-143603156)*

**Comment by tschottdorf** [comment]
I'm half-way through a system update just to get php with postgresql
running locally, so I guess I should.

**Pull request merged**
