### PR TITLE
Add link to scheduled backup on Take Full and Incremental Backups

### LINKED ISSUE #8872: backup: Update docs to mention Schedules more prolifically
https://www.cockroachlabs.com/docs/v20.2/take-full-and-incremental-backups.html

Should mention schedules in the section around `Perform backup and restore` as the way to automate your backups.

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8872.

### CODE REVIEW

**Review by mwang1026 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxRvZM9nNaMZDcujQA:-MLxRvZNB6-9DqKxj-wY:b-dcp8on) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L122)):*
> ```Markdown
> ### Examples
> 
> #### Automated full and incremental backups
> ```

Do you see a strong reason for having this vs. just pushing people towards schedules?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxRvZM9nNaMZDcujQA:-MLxUMMB0hwSWZmfYL-t:b9inja7) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Do you see a strong reason for having this vs. just pushing people towards schedules?
</blockquote></details>

Not really, if we prefer people to use schedules

**Review by taroface — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxTY79E68QYOAl3_Im:-MLxTY79E68QYOAl3_In:bigotfw) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L24)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> <span class="version-tag">New in v20.2:</span> You can create [schedules for periodic backups](manage-a-backup-schedule.html) in CockroachDB. We recommend using scheduled backups to automate daily backups of your cluster.
> ```

It was hard for me to parse the difference between the two options here. It might be simpler to say e.g.

"You can create a backup schedule in CockroachDB. We recommend scheduling daily backups of your cluster.

You can also automate daily backups of your cluster using scripts."
___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxRvZM9nNaMZDcujQA:-MLxU6hMB0sfX6jXFG7E:b-8mb739) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Not really, if we prefer people to use schedules
</blockquote></details>

I have the same question. In the callout above, it sounds like scheduled backups are being recommended over scripts.

However, is it more of a general recommendation for daily backups, whether via schedule or automation?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxTY79E68QYOAl3_Im:-MLxV7MS4yqUZBEkpos9:b-8s11ja) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L24)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

It was hard for me to parse the difference between the two options here. It might be simpler to say e.g.

"You can create a backup schedule in CockroachDB. We recommend scheduling daily backups of your cluster.

You can also automate daily backups of your cluster using scripts."
</blockquote></details>

Yeah, given your and Michael's comments, I think it makes sense to get rid of the automating with scripts part now that we have schedules

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r3](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLyIw4kAfL8h_b0JaLg:-MLyIw4kAfL8h_b0JaLh:b-mkw803) ([raw file](https://github.com/cockroachdb/docs/blob/8db0ba0d7c872573c7a4c24eff7109427e438e80/v20.2/take-full-and-incremental-backups.md#L122)):*
> ```
> All users (both core and enterprise) 
> ```

I might suggest "Both core and enterprise users" because "all users" makes me think of authorization (e.g. admin) roles. But maybe this is another common usage that I haven't seen until now.

> ```
> clause, for example to take
> ```

Nit: `clause. For example, to take`

**Review by lnhsingh — COMMENTED** [review]
TFTRs! Can you take a look at the CREATE SCHEDULE FOR BACKUP doc? I added another small edit about temporary credentials and schedules.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905#-:-MLyL97lA5BziQ7pHgjv:bhp7pim)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r3](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLyIw4kAfL8h_b0JaLg:-MLyL0P6-QEElXPhiTbg:b-e8ex3m) ([raw file](https://github.com/cockroachdb/docs/blob/8db0ba0d7c872573c7a4c24eff7109427e438e80/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> All users (both core and enterprise) 
> ```

I might suggest "Both core and enterprise users" because "all users" makes me think of authorization (e.g. admin) roles. But maybe this is another common usage that I haven't seen until now.

> ```
> clause, for example to take
> ```

Nit: `clause. For example, to take`
</blockquote></details>

No, your call out re: auth makes is a good point. Updated.

**Comment by lnhsingh** [comment]
@mwang1026 / @taroface friendly ping to PTAL. thanks!

**Review by taroface — APPROVED** [review]
Just one nit!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905#-:-MMNEwC8Adc4k2z1d2a5:b-q95gvj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r3](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLyIw4kAfL8h_b0JaLg:-MMNEnRvEGXF9kKWOTHg:b-pbrosa) ([raw file](https://github.com/cockroachdb/docs/blob/8db0ba0d7c872573c7a4c24eff7109427e438e80/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

No, your call out re: auth makes is a good point. Updated.
</blockquote></details>

Nit: Add a comma after `For example`

**Review by mwang1026 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r5](https://reviewable.io/reviews/cockroachdb/docs/8905#-MMNT6T0DVxXc-52FsJe:-MMNT6T0DVxXc-52FsJf:bh0vx2n) ([raw file](https://github.com/cockroachdb/docs/blob/62128616a72075c8336962b83a1f0925279a5cda/v20.2/take-full-and-incremental-backups.md#L122)):*
> ```
> Full backups are taken with the `FULL BACKUP ALWAYS` clause.
> ```

I think this is more "to create schedules that only take full backups, include the `FULL BACKUP ALWAYS` clause"
___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r5](https://reviewable.io/reviews/cockroachdb/docs/8905#-MMNTKdVBn17TeJt8OPa:-MMNTKdVBn17TeJt8OPb:b-6dkwyv) ([raw file](https://github.com/cockroachdb/docs/blob/62128616a72075c8336962b83a1f0925279a5cda/v20.2/take-full-and-incremental-backups.md#L122)):*
> ```
> take a full cluster backup
> ```

nit: This is to create a schedule that schedules full backups, rather than taking backups.
___
*[v20.2/take-full-and-incremental-backups.md, line 139 at r5](https://reviewable.io/reviews/cockroachdb/docs/8905#-MMNTPhlBJ_pAOt1_xn_:-MMNTPhlBJ_pAOt1_xna:b-9cgn3o) ([raw file](https://github.com/cockroachdb/docs/blob/62128616a72075c8336962b83a1f0925279a5cda/v20.2/take-full-and-incremental-backups.md#L139)):*
> ```
> schedule backups,
> ```

Maybe add `including schedules that take full and incremental backups`

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @taroface)

___
*[v20.2/take-full-and-incremental-backups.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxTY79E68QYOAl3_Im:-MLyLvwxEfaSRuo6QYSA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L24)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Yeah, given your and Michael's comments, I think it makes sense to get rid of the automating with scripts part now that we have schedules
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLxRvZM9nNaMZDcujQA:-MMS042A-UK7KhJzVj3f:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/671b5fd00ef828014b9d0f29cc48bfa3390912dd/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I have the same question. In the callout above, it sounds like scheduled backups are being recommended over scripts.

However, is it more of a general recommendation for daily backups, whether via schedule or automation?
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r3](https://reviewable.io/reviews/cockroachdb/docs/8905#-MLyIw4kAfL8h_b0JaLg:-MMS03ASB_0mTbj7RRZG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8db0ba0d7c872573c7a4c24eff7109427e438e80/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: Add a comma after `For example`
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r5](https://reviewable.io/reviews/cockroachdb/docs/8905#-MMNTKdVBn17TeJt8OPa:-MMS0UMH-Vlp5Vy4_D8B:bt2vr1b) ([raw file](https://github.com/cockroachdb/docs/blob/62128616a72075c8336962b83a1f0925279a5cda/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> take a full cluster backup
> ```

nit: This is to create a schedule that schedules full backups, rather than taking backups.
</blockquote></details>

Fixed.
___
*[v20.2/take-full-and-incremental-backups.md, line 122 at r5](https://reviewable.io/reviews/cockroachdb/docs/8905#-MMNT6T0DVxXc-52FsJe:-MMS0aX8AwN2dqUJz87b:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/62128616a72075c8336962b83a1f0925279a5cda/v20.2/take-full-and-incremental-backups.md#L122)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> Full backups are taken with the `FULL BACKUP ALWAYS` clause.
> ```

I think this is more "to create schedules that only take full backups, include the `FULL BACKUP ALWAYS` clause"
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 139 at r5](https://reviewable.io/reviews/cockroachdb/docs/8905#-MMNTPhlBJ_pAOt1_xn_:-MMS0fY-AD2her8TlUZa:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/62128616a72075c8336962b83a1f0925279a5cda/v20.2/take-full-and-incremental-backups.md#L139)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> schedule backups,
> ```

Maybe add `including schedules that take full and incremental backups`
</blockquote></details>

Done.

**Comment by lnhsingh** [comment]
Going to merge - @mwang1026 if you have additional edits later, lmk. TFTRs!

**Pull request merged**
