### PR TITLE
add missing copy option to doc

### LINKED ISSUE #8533: Orchestrate CockroachDB Across Multiple Kubernetes Clusters Doc Update
Re: [Orchestrate CockroachDB Across Multiple Kubernetes Clusters](https://cockroachlabs.com/docs//v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html)

## Issue Description
`python teardown.py`
step is missing copy option

### PR DESCRIPTION
**Pull request by dufcrule**
Added missing code copy option for step `python teardown.py`.

Closes #8533

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
LGTM! Can you update the 20.2 doc too?

**Comment by dufcrule** [comment]
Sure!

**Comment by dufcrule** [comment]
20.2 doc also updated in this PR.

**Comment by Amruta-Ranade** [comment]
LGTM! Thank you!!

**Pull request merged**
