### PR TITLE
Removed `sasl_mechanism` from 20.2 CREATE CHANGEFEED docs

### LINKED ISSUE #10497: sasl_mechanism included in changefeed docs before it is available
The CREATE CHANGEFEED documentation [1] references the query parameter "sasl_mechanism" but the feature enabling that has not yet been released (as of 20.2.8).  This should be removed until which time a user can implement it to avoid confusion.

[1] https://www.cockroachlabs.com/docs/v20.2/create-changefeed.html

gz#8218

### PR DESCRIPTION
**Pull request by kathancox**
Removed `sasl_mechanism` from 20.2 CREATE CHANGEFEED docs.

Closes #10497

### CODE REVIEW

**Comment by kathancox** [comment]
Just pinging on this one @amruss - lmk if anything needs to change here. Thanks!

**Review by amruss — APPROVED** [review]
LGTM

**Comment by jseldess** [comment]
___
*[v20.2/create-changefeed.md, line 88 at r1](https://reviewable.io/reviews/cockroachdb/docs/10526#-MbC4fPl3TyqkfLKK561:-MbC4fPl3TyqkfLKK562:btjqdu2) ([raw file](https://github.com/cockroachdb/docs/blob/d10c984be0bd4eeae2bf497e4b13176edc6a2671/v20.2/create-changefeed.md#L88)):*
> ```Markdown
> `client_cert`      | [Kafka](#kafka)                               | [`STRING`](string.html)             | The base64-encoded Privacy Enhanced Mail (PEM) certificate. This is used with `client_key`.
> `client_key`       | [Kafka](#kafka)                               | [`STRING`](string.html)             | The base64-encoded private key for the PEM certificate. This is used with `client_cert`.
> `sasl_enabled`     | [Kafka](#kafka)                               | [`BOOL`](bool.html)                 | If `true`, [use SASL/PLAIN to authenticate](https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_plain.html). This requires a `sasl_user` and `sasl_password` (see below). <br><br>**Default:** `false`
> ```

@kathancox, what is "see below" in referencing?

**Comment by kathancox** [comment]
@jseldess So the "see below" was referring to the next row in that table. I don't feel it is needed, now that you've pointed it out. I've removed it, and I have removed another "see below" from the table, which was also referring to the row following it.

**Review by jseldess — APPROVED** [review]
Thanks, @kathancox. LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10526#-:-MbCfKZ47aAoFNEL3Urs:b-thchv3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

**Pull request merged**
