### PR TITLE
CC FAQ Expansion & Updates

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-3703
Closes https://cockroachlabs.atlassian.net/browse/CC-3684
Closes https://cockroachlabs.atlassian.net/browse/CC-3681
Closes https://cockroachlabs.atlassian.net/browse/CC-3686

Additional questions pulled from [internal FAQ](https://docs.google.com/document/d/1foKgViAVMbXF15SROF3JFKEeWFvX3f4cyCL6dUPgFlo/edit)

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/frequently-asked-questions.md, line 90 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWjznqV7bT2ddzGJ1j1:-MWjznqV7bT2ddzGJ1j2:b-qdluyr) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L90)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> You can also [backup and restore](../stable/backup-and-restore.html) data on your own.
> ```

I think this link should point to the relevant CC docs: `backups-page.html#back-up-and-restore-data-manually`
___
*[cockroachcloud/frequently-asked-questions.md, line 92 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWjzVNVD8NV4n2JZpAQ:-MWjzVNVD8NV4n2JZpAR:b-fbz3ib) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L92)):*
> ```Markdown
> You can also [backup and restore](../stable/backup-and-restore.html) data on your own.
> 
> If you need additional help, [contact us](https://support.cockroachlabs.com).
> ```

nit: this doesn't need to be on its own line. 
___
*[cockroachcloud/frequently-asked-questions.md, line 96 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk-6XW0dLzcXarR1mE:-MWk-6XW0dLzcXarR1mF:bye78zk) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L96)):*
> ```Markdown
> ### Can I download the backups that CockroachCloud takes for me?
> 
> CockroachCloud automated backups cannot be downloaded, but you can manually [run a backup](../stable/take-full-and-incremental-backups.html) to your own [storage location](../v20.2/backup.html#backup-file-urls) at any time. To do this, you will need either `admin` or `SELECT` privileges on the data you are backing up.
> ```

Same as above - I think this link should point to `backups-page.html#back-up-and-restore-data-manually`
___
*[cockroachcloud/frequently-asked-questions.md, line 114 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk-TaSBqmDJn6FlAzd:-MWk-TaSBqmDJn6FlAze:b-soahld) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L114)):*
> ```Markdown
> ### Is there a public API for CockroachCloud?
> 
> Our team is currently working on creating a public API for CockroachCloud, and our goal is to have foundational API cabilities available in 2021. The initial work is focused on core automation requirements, such as creation, modification, and deletion of clusters. We’re always looking for design partners and customer input for our features, so please [contact us](https://support.cockroachlabs.com/hc/en-us) if you have specific API requirements.
> ```

Not sure if we want to include "available in 2021" here, since we usually don't add expected release dates to our docs so there is still some flexibility if things change. I think you can just remove `, and our goal is to have foundational API capabilities available in 2021.`
___
*[cockroachcloud/frequently-asked-questions.md, line 122 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk0AJd801VZjFWKlwn:-MWk0AJd801VZjFWKlwo:bxamuyf) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L122)):*
> ```
> Response times are under 10ms for public access and typically much lower.
> ```

Grammatically, should this be ", but typically much lower."? 
___
*[cockroachcloud/frequently-asked-questions.md, line 124 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk0RP-ApFCLl4h0rJC:-MWk0RP-ApFCLl4h0rJD:bq830yd) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L124)):*
> ```Markdown
> Response times are under 10ms for public access and typically much lower. Additionally, using [VPC peering](network-authorization.html#vpc-peering) or [AWS PrivateLink](network-authorization.html#aws-privatelink) will reduce latency.
> 
> ### How can I manage resources such as CPU, memory, and IOPS?
> ```

I'm not sure if this question is worded correctly for the given answer. Maybe something like "How do I monitor resource usage such as CPU, memory, and IOPS?"
___
*[cockroachcloud/frequently-asked-questions.md, line 130 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk1A38508LgSoAJNaG:-MWk1A38508LgSoAJNaH:b-979yx6) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L130)):*
> ```Markdown
> ### How does CockroachCloud support replication between regions?
> 
> Cockroach enables locality flags with the [`cockroach start`](../stable/cockroach-start.html) command, which enforces placement of replicas across regions for optimal resiliency. Additionally, the [`configure zone`](../stable/configure-zone.html) command can be used to customize replication settings.
> ```

The first sentence is a little convoluted. Should it say something like `CockroachDB can be [started](cockroach-start.html) with locality flags, which enforce the placement of replicas...`?

But also, is this FAQ relevant yet? Since we don't currently support multi-region clusters, do we need to talk about replication between regions? Should this instead be "replication between availability zones"?

cc @kannanlakshmi 
___
*[cockroachcloud/frequently-asked-questions.md, line 136 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk2f4v0Yv-mB1HXvdD:-MWk2f4v0Yv-mB1HXvdE:b-3ehr1z) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L136)):*
> ```Markdown
> ### Am I in control of upgrades for all environments that use CockroachCloud?
> 
> Yes. The Cockroach Labs Customer Success team will work with you to control when upgrades are applied to each of your environments. Major release upgrades can be applied directly [through the CockroachCloud Console](upgrade-to-v20.2.html). Minor release upgrades are automatically applied to all clusters. For more information, see the [Upgrade Policy](upgrade-policy.html).
> ```

Should this first sentence say "...will work with you to control when major upgrades are applied..."? Since the sentence about minor release upgrades says they are automatically applied to all clusters, which seems contradictory to saying "you can work with the CS team to control when upgrades are applied."

Lakshmi might be able to help clarify here too, if needed.
___
*[cockroachcloud/frequently-asked-questions.md, line 144 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk3qqp8ScV3S94KVdB:-MWk3qqp8ScV3S94KVdC:b97vodv) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L144)):*
> ```Markdown
> ### What is the outage history in production?
> 
> We support 99.95% uptime for CockroachCloud clusters. To date, we have not had any full scale or major outages affecting all customers. CockroachDB's distributed architecture is designed to be more resilient than traditional databases, and most of our customers achieve higher resilience by deploying more than 3 nodes. We can help size the right cluster for you based on your specific resilience or downtime needs.
> ```

nit: `3` > `three` since you write out numbers under 10 usually

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kannanlakshmi and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 96 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk-6XW0dLzcXarR1mE:-MWyfiGD1vAnSxzh1qpc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L96)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Same as above - I think this link should point to `backups-page.html#back-up-and-restore-data-manually`
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
One additional comment on EAR and need clarification from Lakshmi, but otherwise LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156#-:-MWypWIE6VvKEVGDa9W1:be2swj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @kannanlakshmi)

___
*[cockroachcloud/frequently-asked-questions.md, line 136 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk2f4v0Yv-mB1HXvdD:-MWypTfY-Su8dfMWW55w:bsrfkwe) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L136)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

re-worded, let me know what you think
</blockquote></details>

Looks good
___
*[cockroachcloud/frequently-asked-questions.md, line 49 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWyoz314ogTecAop3Dx:-MWyoz314ogTecAop3Dy:bk3pyws) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L49)):*
> ```Markdown
> We use separate certificate authorities for each cluster, and all connections to the cluster over the internet use TLS 1.2.
> 
> ### Is encryption-at-rest enabled on CockroachCloud?
> ```

Lakshmi had commented on your planning docs about possibly linking to https://www.cockroachlabs.com/docs/cockroachcloud/security-overview.html. Do you think we need to add that link as maybe a "See the Security Overview for more info"? Or do you think this answer covers it?

**Review by kannanlakshmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 130 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk1A38508LgSoAJNaG:-MX-ojE0451nUajAVsYC:bgvsbzs) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L130)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Not sure, the internal FAQ used "between regions" but I'll change it to "availability zones" unless @kannanlakshmi  disagrees.
</blockquote></details>

I am not sure we need this question yet, at some point when we have multi-region, I can see the need for it but its probably at least 3 months away. 
___
*[cockroachcloud/frequently-asked-questions.md, line 136 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk2f4v0Yv-mB1HXvdD:-MX-ot7XDlU8x_aj5jpk:binqazt) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L136)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Looks good
</blockquote></details>

We should add some more detail on the minor upgrades (unless its part of the upgrade policy already). Specifically the part about  ensuring apps have retry logic. 
___
*[cockroachcloud/frequently-asked-questions.md, line 49 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWyoz314ogTecAop3Dx:-MX-nrv69G3aaQEjicg1:becenbk) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L49)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Lakshmi had commented on your planning docs about possibly linking to https://www.cockroachlabs.com/docs/cockroachcloud/security-overview.html. Do you think we need to add that link as maybe a "See the Security Overview for more info"? Or do you think this answer covers it?
</blockquote></details>

It would be great to link to the security overview as the frequently asked question is about the nature of EAR we use. If we do that, we can actually remove the next two sentences (if you want to keep this ever growing FAQ at a reasonable length). 
___
*[cockroachcloud/frequently-asked-questions.md, line 124 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-oNSc4UJfwsjNj3Cr:-MX-oNSc4UJfwsjNj3Cs:b-54u9rw) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L124)):*
> ```Markdown
> ### How can I monitor resource usage such as CPU, memory, and IOPS?
> 
> The Cockroach Labs SRE team monitors cluster resources and is alerted in the event of storage and compute threshold issues and node downtime. The team also monitors performance and will work with you to add nodes as necessary to remediate any issues. Additional capabilities for direct customer alerts are being developed to notify you of any anomalies in real time.
> ```

I wouldn't say that we monitor "compute threshold" I actually wouldn't say "we will work with you to add nodes" either bc that's a self-service action and we're trying to move to a world where we aren't responsible for any of these actions ever. Curious where this question from, do we need it at all? It raises more questions than answers. 
___
*[cockroachcloud/frequently-asked-questions.md, line 142 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pblT0XtcGciqnyT3:-MX-pblU5misTo6m1fds:b-zfzbho) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L142)):*
> ```Markdown
> ### What is the outage history in production?
> 
> We support 99.95% uptime for CockroachCloud clusters. To date, we have not had any full scale or major outages affecting all customers. CockroachDB's distributed architecture is designed to be more resilient than traditional databases, and most of our customers achieve higher resilience by deploying more than three nodes. We can help size the right cluster for you based on your specific resilience or downtime needs.
> ```

"more than three nodes" should be "three or more nodes" 
Also not sure where this question came from. Do we need it? Seems to unecessarily draw attention? That said, this would be a good place to add that we have a status page that's releasing this week! cc @iibuaka 
___
*[cockroachcloud/frequently-asked-questions.md, line 144 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pobYEHy6BLGmMWl3:-MX-pobYEHy6BLGmMWl4:b-opnqdf) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L144)):*
> ```Markdown
> We support 99.95% uptime for CockroachCloud clusters. To date, we have not had any full scale or major outages affecting all customers. CockroachDB's distributed architecture is designed to be more resilient than traditional databases, and most of our customers achieve higher resilience by deploying more than three nodes. We can help size the right cluster for you based on your specific resilience or downtime needs.
> 
> ### What is the process and SLA for disaster recovery?
> ```

Not sure what this question means. We just talked about self-service backup?restore above. We dont have an SLA for disaster recovery if the customer wants to restore - its self-service.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @iibuaka, and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 142 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pblT0XtcGciqnyT3:-MX3bAJE01mLNj-t_z2m:bt801nr) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L142)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

"more than three nodes" should be "three or more nodes" 
Also not sure where this question came from. Do we need it? Seems to unecessarily draw attention? That said, this would be a good place to add that we have a status page that's releasing this week! cc @iibuaka 
</blockquote></details>

@gemma-shay - Let's repurpose this question for linking to the CC Status Page (like Lakshmi mentioned). Here's my suggested update:

```
### How do I check to see if CockroachCloud is down?

The [**CockroachCloud Status** page](https://status.cockroachlabs.cloud) is a publicly available page that displays the current uptime status of the following services:

- [**CockroachCloud Console**](https://cockroachlabs.cloud/clusters): The UI used for signing up for CockroachCloud, cluster creation and management, and user management.
- [**CockroachDB Support Portal**](https://support.cockroachlabs.com/hc/en-us): Where registered CockroachCloud customers can report, track, and resolve issues.
- **AWS**: The status reported here reflects the health of existing AWS CockroachCloud clusters and the ability to provision new clusters in AWS.
- **GCP**: The status reported here reflects the health of existing GCP CockroachCloud clusters and the ability to provision new clusters in GCP.
```

@iibuaka- let us know if this wording works for you. If so, we'll wait to publish the FAQs until the Status page is live (ETA: sometime this week)

**Comment by gemma-shay** [comment]
___
*[cockroachcloud/frequently-asked-questions.md, line 136 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk2f4v0Yv-mB1HXvdD:-MX3IiGL42gE9QyzrkIE:brwowfc) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L136)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

We should add some more detail on the minor upgrades (unless its part of the upgrade policy already). Specifically the part about  ensuring apps have retry logic. 
</blockquote></details>

Could you expand on this? I'm not familiar with these details and couldn't find any info on the upgrade policy page.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @iibuaka, @kannanlakshmi, and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 130 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk1A38508LgSoAJNaG:-MX2bHDG4CbNYZEGhFNr:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L130)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

I am not sure we need this question yet, at some point when we have multi-region, I can see the need for it but its probably at least 3 months away. 
</blockquote></details>

Removed.
___
*[cockroachcloud/frequently-asked-questions.md, line 49 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWyoz314ogTecAop3Dx:-MX3cxHFCmcjxuFzytAs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L49)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

It would be great to link to the security overview as the frequently asked question is about the nature of EAR we use. If we do that, we can actually remove the next two sentences (if you want to keep this ever growing FAQ at a reasonable length). 
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 124 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-oNSc4UJfwsjNj3Cr:-MX2bIHc3jB1gv1KqQzJ:b-asbv77) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L124)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

I wouldn't say that we monitor "compute threshold" I actually wouldn't say "we will work with you to add nodes" either bc that's a self-service action and we're trying to move to a world where we aren't responsible for any of these actions ever. Curious where this question from, do we need it at all? It raises more questions than answers. 
</blockquote></details>

All of the additional Q&As came from the internal FAQ. Will remove this as it sounds like it's better to keep it internal.
___
*[cockroachcloud/frequently-asked-questions.md, line 142 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pblT0XtcGciqnyT3:-MX2dUGQ5vHYr5HGW3m_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L142)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@gemma-shay - Let's repurpose this question for linking to the CC Status Page (like Lakshmi mentioned). Here's my suggested update:

```
### How do I check to see if CockroachCloud is down?

The [**CockroachCloud Status** page](https://status.cockroachlabs.cloud) is a publicly available page that displays the current uptime status of the following services:

- [**CockroachCloud Console**](https://cockroachlabs.cloud/clusters): The UI used for signing up for CockroachCloud, cluster creation and management, and user management.
- [**CockroachDB Support Portal**](https://support.cockroachlabs.com/hc/en-us): Where registered CockroachCloud customers can report, track, and resolve issues.
- **AWS**: The status reported here reflects the health of existing AWS CockroachCloud clusters and the ability to provision new clusters in AWS.
- **GCP**: The status reported here reflects the health of existing GCP CockroachCloud clusters and the ability to provision new clusters in GCP.
```

@iibuaka- let us know if this wording works for you. If so, we'll wait to publish the FAQs until the Status page is live (ETA: sometime this week)
</blockquote></details>

Done.
___
*[cockroachcloud/frequently-asked-questions.md, line 144 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pobYEHy6BLGmMWl3:-MX2c5F17Y8-YByceK03:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L144)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

Not sure what this question means. We just talked about self-service backup?restore above. We dont have an SLA for disaster recovery if the customer wants to restore - its self-service. 
</blockquote></details>

Removed.

**Review by kannanlakshmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @iibuaka, @kannanlakshmi, and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 136 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk2f4v0Yv-mB1HXvdD:-MX4v_iF3d_SGyj1-B6i:bkxgeoa) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L136)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Could you expand on this? I'm not familiar with these details and couldn't find any info on the upgrade policy page.
</blockquote></details>

More info here https://cockroachlabs.atlassian.net/browse/CC-3838

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @iibuaka, @kannanlakshmi, and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 136 at r3](https://reviewable.io/reviews/cockroachdb/docs/10156#-MWk2f4v0Yv-mB1HXvdD:-MX8Z6PICD4kJ9GmTyED:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4a14792f32e34dd39a02058674a5cf228971338c/cockroachcloud/frequently-asked-questions.md#L136)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

More info here https://cockroachlabs.atlassian.net/browse/CC-3838
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
One more update - then I think it LGTM. We'll want to wait until the Status page goes live to publish this PR though (tomorrow)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156#-:-MX94uv47vLLYP_Kidqo:b3a3w0b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @iibuaka, @kannanlakshmi, and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 142 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pblT0XtcGciqnyT3:-MX94psF7BmVCrwwBmc6:b-hd71z2) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L142)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Chatted with Ivory - can you remove the bullet about the Support Portal?

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10156)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @iibuaka, @kannanlakshmi, and @lnhsingh)

___
*[cockroachcloud/frequently-asked-questions.md, line 142 at r4](https://reviewable.io/reviews/cockroachdb/docs/10156#-MX-pblT0XtcGciqnyT3:-MX9DkxG0qLf0GQC33qV:b-qwut9w) ([raw file](https://github.com/cockroachdb/docs/blob/98b711a89bce2ba184f25d11be8f14901ab922d0/cockroachcloud/frequently-asked-questions.md#L142)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Chatted with Ivory - can you remove the bullet about the Support Portal?
</blockquote></details>

Sorry missed this in the SLA/Support policy push. Done now!

**Pull request merged**
