### PR TITLE
Add release notes for v20.2.0-beta.3

### LINKED ISSUE #7981: v20.2.0-beta.3 Release Notes
Prep date: ~9/7/20~
Release date: ~9/14/20~ 9/28/2020
SHA: `<add>`
Release Manager: Lucy

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [ ] Run script to generate release notes
- [ ] Update docs site
- [ ] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #7981.

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey Eric! if you could review in the next 24 hours that would be great!  but if you can’t let me know, not a problem - i will ask someone else

**Review by ericharmeling — COMMENTED** [review]
A few nits and links missing. Otherwise, lgtm!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8490#-:-MIQaQKYDqiEXDj4tmbh:bk8dnsj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[releases/v20.2.0-beta.3.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQX2FC70tQVyBDdR--:-MIQX2FC70tQVyBDdR-0:ba98mmd) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L7)):*
> ```
> September 25, 2020
> ```

September 30, 2020
___
*[releases/v20.2.0-beta.3.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXHqP7cEYxfB9xwFH:-MIQXHqP7cEYxfB9xwFI:b-wo6cps) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L42)):*
> ```
> DB
> ```

database
___
*[releases/v20.2.0-beta.3.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXKfJ7X1WLGZCK2EW:-MIQXKfJ7X1WLGZCK2EX:bnqq4gk) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L42)):*
> ```
> cluster settings
> ```

link to cluster-settings.html
___
*[releases/v20.2.0-beta.3.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXU6m424LjoYiulxm:-MIQXU6m424LjoYiulxn:bzfyy2p) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L46)):*
> ```
> (long-lived requests)
> ```

(i.e., long-lived requests)
___
*[releases/v20.2.0-beta.3.md, line 52 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXbea2v0FSGg0yB5L:-MIQXbea2v0FSGg0yB5M:b-kjmf2j) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L52)):*
> ```
> are immediately
> ```

are now immediately
___
*[releases/v20.2.0-beta.3.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXwUV5ApHL6XVNcrz:-MIQXwUV5ApHL6XVNcs-:b-d2c3xq) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L54)):*
> ```
> This is currently a no-op for -1 (default, unlimited connections), and errors for any other value.
> ```

This is currently a no-op for -1, and errors for any other value. By default, the number of connections are unlimited. 
___
*[releases/v20.2.0-beta.3.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQYSRt6nCWku-5Gh6R:-MIQYSRt6nCWku-5Gh6S:b-a2s820) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L57)):*
> ```
> Partial index
> ```

link to partial-indexes.html
___
*[releases/v20.2.0-beta.3.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQYnVp5M4azEnlL7Wj:-MIQYnVq6zAPw0Vepk2Q:b-gjbndv) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L66)):*
> ```
> we do not yet support but may plan to.
> ```

we do not yet support.
___
*[releases/v20.2.0-beta.3.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQYx8nBETxakvB8vzF:-MIQYx8nBETxakvB8vzG:b-uv97qw) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L72)):*
> ```
> builtins
> ```

link to functions-and-operators.html
___
*[releases/v20.2.0-beta.3.md, line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQZ0uD4R4JTXI_SP6g:-MIQZ0uD4R4JTXI_SP6h:b72bwem) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L77)):*
> ```
> geometry and geography types
> ```

link to the type pages?
___
*[releases/v20.2.0-beta.3.md, line 82 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQZ5ohEhq6aThXhNpd:-MIQZ5ohEhq6aThXhNpe:b-p62xz1) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L82)):*
> ```
> ([`cockroach sql`](../v20.2/cockroach-sql.html), [`cockroach demo`](../v20.2/cockroach-sql.html))
> ```

(e.g., [`cockroach sql`](../v20.2/cockroach-sql.html), [`cockroach demo`](../v20.2/cockroach-sql.html))
___
*[releases/v20.2.0-beta.3.md, line 92 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQZmgTDsZWrFAN1MVG:-MIQZmgUDWGK_GSFTyIz:b258ug2) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L92)):*
> ```
> Versions below 20.1.4 were susceptible to this bug; versions 20.1.4+ were no longer crashing, just printing scary messages in the log files.
> ```

Versions below 20.1.4 are susceptible to this bug. Versions 20.1.4+ will not crash, but instead print messages to the log files.
___
*[releases/v20.2.0-beta.3.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQ_VmV-__M6Al-FPKr:-MIQ_VmW9CWCBDOGfXwf:b-pff88q) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L100)):*
> ```
> Starting with v20.2.0-alpha.3, CockroachDB would crash when performing an `UPSERT` with a `RETURNING` clause of more than 10k rows. This is now fixed. 
> ```

link to upsert.html

Also, is this related to https://www.cockroachlabs.com/docs/advisories/a54418 ?
___
*[releases/v20.2.0-beta.3.md, line 106 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQaDWbDVX777bJgcEe:-MIQaDWbDVX777bJgcEf:b-lvqva5) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L106)):*
> ```
> is no longer bogus.
> ```

has been fixed.

**Review by rmloveland — COMMENTED** [review]
Thanks Eric!  I have fixed everything you mentioned (I think!) and reached out to Yahor for confirmation re: the advisory.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8490#-:-MIUPjg5Eg3J-MppJOTq:b5rukel)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @yuzefovich)

___
*[releases/v20.2.0-beta.3.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQX2FC70tQVyBDdR--:-MIUMLtw8ksb4MHXKc3Z:b4vxok8) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L7)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> September 25, 2020
> ```

September 30, 2020
</blockquote></details>

WHOA - thanks.  Dang.  Fixed.
___
*[releases/v20.2.0-beta.3.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXHqP7cEYxfB9xwFH:-MIUMUctAAlWwZtw6FDS:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L42)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> DB
> ```

database
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXKfJ7X1WLGZCK2EW:-MIUMZtZBuxIs9OlaCV1:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L42)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> cluster settings
> ```

link to cluster-settings.html
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXU6m424LjoYiulxm:-MIUMac8EA5_B1edrt1Q:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L46)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> (long-lived requests)
> ```

(i.e., long-lived requests)
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 52 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXbea2v0FSGg0yB5L:-MIUMf-q2lyT80ZuE75W:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L52)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> are immediately
> ```

are now immediately
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 54 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQXwUV5ApHL6XVNcrz:-MIUMvsA4EiUNO5F_x2-:b-fnpdcz) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L54)):*
Tweaked slightly to include that the default is -1 = unlimited

> By default, the value is -1 (unlimited connections).
___
*[releases/v20.2.0-beta.3.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQYSRt6nCWku-5Gh6R:-MIUN4Fh9F8ETCF07NxV:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L57)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> Partial index
> ```

link to partial-indexes.html
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQYnVp5M4azEnlL7Wj:-MIUN7lUDNmpCuowF3Yz:b-9hfig0) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L66)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> we do not yet support but may plan to.
> ```

we do not yet support.
</blockquote></details>

Fixed - yeah docs should never ever say "but oh we will soon, I think" :-) 
___
*[releases/v20.2.0-beta.3.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQYx8nBETxakvB8vzF:-MIUNIPUAGd7Ys09P3h9:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L72)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> builtins
> ```

link to functions-and-operators.html
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQZ0uD4R4JTXI_SP6g:-MIUNJcq9YqDVR6G82uo:bf28ccb) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L77)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> geometry and geography types
> ```

link to the type pages?
</blockquote></details>

I haven't written them yet! :-) / :-( 
___
*[releases/v20.2.0-beta.3.md, line 82 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQZ5ohEhq6aThXhNpd:-MIUNUMz2irUfq7pfNqo:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L82)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> ([`cockroach sql`](../v20.2/cockroach-sql.html), [`cockroach demo`](../v20.2/cockroach-sql.html))
> ```

(e.g., [`cockroach sql`](../v20.2/cockroach-sql.html), [`cockroach demo`](../v20.2/cockroach-sql.html))
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 92 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQZmgTDsZWrFAN1MVG:-MIUNgAE0sjU9Zn8SkLP:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L92)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> Versions below 20.1.4 were susceptible to this bug; versions 20.1.4+ were no longer crashing, just printing scary messages in the log files.
> ```

Versions below 20.1.4 are susceptible to this bug. Versions 20.1.4+ will not crash, but instead print messages to the log files.
</blockquote></details>

Fixed
___
*[releases/v20.2.0-beta.3.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQ_VmV-__M6Al-FPKr:-MIUOIL_0YlLU6f8pFG8:b-rzi3h9) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L100)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> Starting with v20.2.0-alpha.3, CockroachDB would crash when performing an `UPSERT` with a `RETURNING` clause of more than 10k rows. This is now fixed. 
> ```

link to upsert.html

Also, is this related to https://www.cockroachlabs.com/docs/advisories/a54418 ?
</blockquote></details>

Added the link.

Re: the advisory, it sure looks like it!  But let's confirm.

@yuzefovich can you confirm whether this line of the 20.2 beta.3 release notes is related to  https://www.cockroachlabs.com/docs/advisories/a54418 ?  The text descriptions of the bug appear to be the same in various PRs but the PR links are to different issues, I think due to backporting.
___
*[releases/v20.2.0-beta.3.md, line 106 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQaDWbDVX777bJgcEe:-MIUP46o9897p_OUB0V2:b-s7ypfa) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L106)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> is no longer bogus.
> ```

has been fixed.
</blockquote></details>

Fixed.  PS I wish we could say "bogus"

**Review by ericharmeling — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[releases/v20.2.0-beta.3.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQ_VmV-__M6Al-FPKr:-MIUTtvn3Oei73_Dkw3f:brhcxul) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L100)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Added the link.

Re: the advisory, it sure looks like it!  But let's confirm.

@yuzefovich can you confirm whether this line of the 20.2 beta.3 release notes is related to  https://www.cockroachlabs.com/docs/advisories/a54418 ?  The text descriptions of the bug appear to be the same in various PRs but the PR links are to different issues, I think due to backporting.
</blockquote></details>

No, the tech advisory is *only* applicable to 20.1.4 and 20.1.5, and the bug present on 20.2.0 testing versions is a lot less severe - as the release note says, we would crash in a certain scenario (and not silently fail to execute correctly). The link to the applicable issue is https://github.com/cockroachdb/cockroach/issues/54465.

**Review by rmloveland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[releases/v20.2.0-beta.3.md, line 100 at r1](https://reviewable.io/reviews/cockroachdb/docs/8490#-MIQ_VmV-__M6Al-FPKr:-MIVEZD46VlpgG0S4Dgt:bjvhyck) ([raw file](https://github.com/cockroachdb/docs/blob/f1bcf4bb7f41292e10f822d75f427667661920f0/releases/v20.2.0-beta.3.md#L100)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

No, the tech advisory is *only* applicable to 20.1.4 and 20.1.5, and the bug present on 20.2.0 testing versions is a lot less severe - as the release note says, we would crash in a certain scenario (and not silently fail to execute correctly). The link to the applicable issue is https://github.com/cockroachdb/cockroach/issues/54465.
</blockquote></details>

Thanks for confirming, Yahor! 

I have left this line as is then, since the issue link you provided is mentioned in https://github.com/cockroachdb/cockroach/pull/54490

(as I'm sure you know since you wrote it :-} )

**Pull request merged**
