### PR TITLE
JSONB data type

### LINKED ISSUE #2011: JSON support
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recDY0WRtP15DyeSp
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170925_jsonb_scope.md

PRs:
- [sql: add json operators to parser](https://github.com/cockroachdb/cockroach/pull/19109)
- [sql: add JSONB datum](https://github.com/cockroachdb/cockroach/pull/19163)
- [inverted indexes for JSONB](https://github.com/cockroachdb/cockroach/pull/20941)
- [JSON inverted indexes in CREATE TABLE](https://github.com/cockroachdb/cockroach/pull/22217)

### PR DESCRIPTION
**Pull request by lhirata**
Closes #2011.

This PR only covers the JSONB data type. A separate PR will be opened for inverted indexes.

### CODE REVIEW

**Comment by justinj** [comment]
We might want to outline some useful functions and operators here at some point too, doesn't have to be part of this PR, but for example, it would be useful for people to know how to use `->` and `->>` in particular, and there's a couple other helpful ones, like `jsonb_pretty(...)` that people should probably know about.

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[v2.0/jsonb.md, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J199QBdMknJXQOINS:-L6J199QBdMknJXQOINT:bezdwn) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L17)):*
> ```Markdown
> ## Alias
> 
> In CockroachDB, the `JSON` is an alias for `JSONB`.
> ```

Maybe worth calling out that this is different from Postgres?

---

*[v2.0/jsonb.md, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1NWa4QyFfEEpUtrw:-L6J1NWbW-VS5oSdAove:bnr2489) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L32)):*
> ```Markdown
> type `JSONB`.
> 
> There are seven types of `JSONB` values:
> ```

This is true on an implementation level, but I think most users would probably rather think of `true` and `false` as the two members of the "boolean" type, rather than as their own types.

---

*[v2.0/jsonb.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1J913LSSZNIUWV9O:-L6J1J913LSSZNIUWV9P:b982dpw) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L36)):*
> ```Markdown
> - `true`
> - `false`
> -  `null`
> ```

nit: extra space here

---

*[v2.0/jsonb.md, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1XY4e5By_qOn0otk:-L6J1XY4e5By_qOn0otl:bhhqhbb) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L38)):*
> ```Markdown
> -  `null`
> - Strings
> - Numbers (i.e., [`decimal`](decimal))
> ```

One gotcha people should be aware of here is that our (and Postgres') JSONB numbers are *not* float64s, as many would probably expect (and is standard).

---

*[v2.0/jsonb.md, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1pF7Qa2q9-vJkICa:-L6J1pF7Qa2q9-vJkICb:b2ni78k) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L44)):*
> ```Markdown
> Examples:
> 
> - `'{"type": "account creation", "username": "harvestboy93"}'`
> ```

lol

---

*[v2.0/jsonb.md, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J2fPhUNH5_uZKPYhP:-L6J2fPijAfmgX_bTZfg:b53yw02) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L57)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> > CREATE TABLE users (
> ```

I'm glad we're doing this kind of example :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-:-L6J23lt1UnM0ydvC9kC:b-ka70qt)*

**Comment by lhirata** [comment]
I added a link at the bottom to the Functions and Operators doc. Do you think adding example(s) using the above function/operators would also be useful? 

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[v2.0/jsonb.md, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J199QBdMknJXQOINS:-L6JFFH7FBD2yUp4LPxP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L17)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Maybe worth calling out that this is different from Postgres?
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1NWa4QyFfEEpUtrw:-L6JFG8GIL96BvcI_NVO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L32)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This is true on an implementation level, but I think most users would probably rather think of `true` and `false` as the two members of the "boolean" type, rather than as their own types.
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1J913LSSZNIUWV9O:-L6JFH-GGEnSUAIAep1f:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L36)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: extra space here
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6J1XY4e5By_qOn0otk:-L6JFISzQkUsLKquMhLX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e040a06ee3b7db1ff98368a7abf61e73a65a9f5/v2.0/jsonb.md#L38)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

One gotcha people should be aware of here is that our (and Postgres') JSONB numbers are *not* float64s, as many would probably expect (and is standard).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-:-L6JETjSMYdhj-hhObbd:b2fo3t6)*

**Comment by justinj** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-:-L6JITTnTI2FUvqcTKK2:bnfp4nl)*

**Comment by justinj** [comment]
I think adding examples of using the operators would be useful, yeah.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-:-L6JIWCjka0hBTrtZSFf:bmq4682)*

**Comment by lhirata** [comment]
Thanks for the review / help @justinj!  Can you take a quick look at the new examples?

@jseldess - ready for your review.

**Comment by justinj** [comment]
Examples LGTM

**Comment by jseldess** [comment]
Nice work! :lgtm:, with a few minor questions and comments.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[v2.0/data-types.md, line 23 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6TMSKvjFG8kbOZYSgo:-L6TMSKvjFG8kbOZYSgp:b-44sfag) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/data-types.md#L23)):*
> ```Markdown
> [`INT`](int.html) | A signed integer, up to 64 bits. | `12345`
> [`INTERVAL`](interval.html) | A span of time. | `INTERVAL '2h30m30s'`
> [`JSONB`](jsonb.html) | <span class="version-tag">New in v2.0:</span> JSON (JavaScript Object Notation) data. | `('{"first_name": "Lola", "last_name": "Dog", "location": "NYC", "online" : true, "friends" : 547}')`
> ```

Do we need the opening and closing parentheses?

---

*[v2.0/jsonb.md, line 7 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6SydcQmsIRoT10il2m:-L6SydcQmsIRoT10il2n:bdalmvj) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L7)):*
> ```Markdown
> ---
> 
> <span class="version-tag">New in v2.0:</span> The `JSONB` [data type](data-types.html) stores JSON (JavaScript Object Notation) data as a binary representation of the `JSONB` value, which eliminates whitespace, duplicate keys, and key ordering. JSONB supports inverted indexing.
> ```

nit: Put back-ticks around the final `JSONB`.

---

*[v2.0/jsonb.md, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6Syu4Z3DUufs00Kt3r:-L6Syu4Z3DUufs00Kt3s:b18ojqe) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L19)):*
> ```Markdown
> In CockroachDB, `JSON` is an alias for `JSONB`.
> 
> {{site.data.alerts.callout_info}}The <code>JSONB</code> / <code>JSON</code> data type in CockroachDB is similar in behavior to the <a href="https://www.postgresql.org/docs/current/static/datatype-json.html"><code>JSONB</code> data type in PostgreSQL</a>.
> ```

I'm conflicted about saying `similar in behavior`. It feels vague. Post-2.0, we're going to do more work to more explicitly identify how we differ with postgres. Should we wait? @justinj, what are you thoughts?

---

*[v2.0/jsonb.md, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6SzMwL9u2wsJskyEWs:-L6SzMwL9u2wsJskyEWt:b-w9alqd) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L24)):*
> ```Markdown
> ## Considerations
> 
> - The [primary key](primary-key.html) and [unique](unique.html) [constraints](constraints.html) cannot be used on `JSONB` values.
> ```

I don't think the foreign key constraint be used on `JSONB` values...?

---

*[v2.0/jsonb.md, line 55 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T-4hli4MmIpzqRLgz:-L6T-4hli4MmIpzqRLh-:bzfscrh) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L55)):*
> ```Markdown
> The size of a `JSONB` value is variable, but it's recommended to keep values under 1 MB to ensure performance. Above that threshold, [write amplification](https://en.wikipedia.org/wiki/Write_amplification) and other considerations may cause significant performance degradation.
> 
> ## Example
> ```

nit: `Example` > `Examples`

---

*[v2.0/jsonb.md, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T4D8fT44WU81kSljw:-L6T4D8fT44WU81kSljx:bzas93s) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L132)):*
I think the distinction between this and the next example is a bit too subtle. After chatting with Justin, I'd suggest just having one example called **Retrieve specific fields from a `JSONB` value**, show retrieval of a few fields of a JSON value, and then follow it with a note and example about returning fields as strings, for example:

```
> SELECT user_profile->'first_name',user_profile->'location' FROM users;
```

```
+----------------------------+--------------------------+
| user_profile->'first_name' | user_profile->'location' |
+----------------------------+--------------------------+
| "Lola"                     | "NYC"                    |
| "Ernie"                    | "Brooklyn"               |
+----------------------------+--------------------------+
(2 rows)
```  

You can also use the `->>` operator to return JSON field values as `STRING` values:

```
> SELECT user_profile->>'first_name',user_profile->>'location' FROM users;
```

```
+-----------------------------+---------------------------+
| user_profile->>'first_name' | user_profile->>'location' |
+-----------------------------+---------------------------+
| Lola                        | NYC                       |
| Ernie                       | Brooklyn                  |
+-----------------------------+---------------------------+
(2 rows)
```  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-:-L6TMYzM6cL6JCtiSF3e:bnmdt40)*

**Comment by lhirata** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[v2.0/data-types.md, line 23 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6TMSKvjFG8kbOZYSgo:-L6TRBXWaLTrt2EjiMjY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/data-types.md#L23)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Do we need the opening and closing parentheses?
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6SzMwL9u2wsJskyEWs:-L6TS2ZgHS_5o7Rmlqlh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L24)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I don't think the foreign key constraint be used on `JSONB` values...?
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T4D8fT44WU81kSljw:-L6TSezc6tcIZ6uGeSjw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L132)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I think the distinction between this and the next example is a bit too subtle. After chatting with Justin, I'd suggest just having one example called **Retrieve specific fields from a `JSONB` value**, show retrieval of a few fields of a JSON value, and then follow it with a note and example about returning fields as strings, for example:

```
> SELECT user_profile->'first_name',user_profile->'location' FROM users;
```

```
+----------------------------+--------------------------+
| user_profile->'first_name' | user_profile->'location' |
+----------------------------+--------------------------+
| "Lola"                     | "NYC"                    |
| "Ernie"                    | "Brooklyn"               |
+----------------------------+--------------------------+
(2 rows)
```  

You can also use the `->>` operator to return JSON field values as `STRING` values:

```
> SELECT user_profile->>'first_name',user_profile->>'location' FROM users;
```

```
+-----------------------------+---------------------------+
| user_profile->>'first_name' | user_profile->>'location' |
+-----------------------------+---------------------------+
| Lola                        | NYC                       |
| Ernie                       | Brooklyn                  |
+-----------------------------+---------------------------+
(2 rows)
```  

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by lhirata** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[v2.0/jsonb.md, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6Syu4Z3DUufs00Kt3r:-L6TYFUj8eRL-RYoDeeN:b-kshakc) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L19)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I'm conflicted about saying `similar in behavior`. It feels vague. Post-2.0, we're going to do more work to more explicitly identify how we differ with postgres. Should we wait? @justinj, what are you thoughts?
</blockquote></details>

I included this note because Postgres JSON and JSONB are two different data types, whereas JSON is an alias for JSONB in CRDB. Should I clarify this better? Or is this note maybe not needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by jseldess** [comment]
*[v2.0/jsonb.md, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6Syu4Z3DUufs00Kt3r:-L6WCHnvILKziWP41J2e:b6jyejh) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L19)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

I included this note because Postgres JSON and JSONB are two different data types, whereas JSON is an alias for JSONB in CRDB. Should I clarify this better? Or is this note maybe not needed?
</blockquote></details>

OH, I see. I didn't understand that based on the text. Can you make it more explicit that our `JSONB` is similar to posgres' `JSONB` but not their `JSON` type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by jseldess** [comment]
*[v2.0/jsonb.md, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T4D8fT44WU81kSljw:-L6WD2fvwXPqLFO35wDR:b3ju8ho) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L132)):*
I shouldn't mentioned before, but it'd be nice to start this example with a sentence like:

> To retrieve a specific field from a JSON value, use the `->` operator: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by jseldess** [comment]
*[v2.0/jsonb.md, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T4D8fT44WU81kSljw:-L6WDLQW338mjtVvFpRK:bfy0he3) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L132)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I shouldn't mentioned before, but it'd be nice to start this example with a sentence like:

> To retrieve a specific field from a JSON value, use the `->` operator: 
</blockquote></details>

I meant "I should've mentioned before".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by jseldess** [comment]
*[v2.0/jsonb.md, line 147 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6WCrvGHw-HuLFEUWvQ:-L6WCrvGHw-HuLFEUWvR:b-1z2985) ([raw file](https://github.com/cockroachdb/docs/blob/299da2212c32e086ad7aa333a7d7a97396818861/v2.0/jsonb.md#L147)):*
> ```Markdown
> ~~~
> 
> You can also use the ->> operator to return `JSONB` field values as `STRING` values:
> ```

nit: backticks around `->>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by lhirata** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[v2.0/jsonb.md, line 7 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6SydcQmsIRoT10il2m:-L6WplOt_fqhXz3UM-Z7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L7)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

nit: Put back-ticks around the final `JSONB`.
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6Syu4Z3DUufs00Kt3r:-L6WpvorMZZ0yRVYl0-O:b-dwzas2) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L19)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

OH, I see. I didn't understand that based on the text. Can you make it more explicit that our `JSONB` is similar to posgres' `JSONB` but not their `JSON` type?
</blockquote></details>

Updated. Can you take a quick look?

---

*[v2.0/jsonb.md, line 55 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T-4hli4MmIpzqRLgz:-L6Wpr7k8E2Egzri0J3F:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L55)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

nit: `Example` > `Examples`
</blockquote></details>

Done.

---

*[v2.0/jsonb.md, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6T4D8fT44WU81kSljw:-L6Wpsg7m5VMt65e7ttJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L132)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I meant "I should've mentioned before".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Comment by jseldess** [comment]
*[v2.0/jsonb.md, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2561#-L6Syu4Z3DUufs00Kt3r:-L6X3JD6yuC6Z4ykgFiK:b-85i648) ([raw file](https://github.com/cockroachdb/docs/blob/c91aa3cc350876493996810292ffe477102bf42e/v2.0/jsonb.md#L19)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Updated. Can you take a quick look?
</blockquote></details>

LGTM!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2561)*

**Pull request merged**
