### PR TITLE
CC GitHub Auth

### PR DESCRIPTION
**Pull request by gemma-shay**
Hold until Console changes are live.

Add instructions to switch between GitHub and email login methods.
Closes https://cockroachlabs.atlassian.net/browse/CC-3651

### CODE REVIEW

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9964)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/create-an-account.md, line 158 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVRp5Xo53Dv6RRcInY-:-MVRp1W77j4Q_j2hN5na:b-jyqfqb) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L158)):*
> ```
> m
> ```
Wasn't sure if this should be a step or just text.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9964)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/create-an-account.md, line 158 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVRp5Xo53Dv6RRcInY-:-MVRpYVr1laSXzD1jlL0:bxi6m1m) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L158)):*
> ```
> 1. You will be prompted to log in to GitHub if you haven't already.
> ```
Meant to refer to this line. Not sure why it says "m" above.

**Review by emily-horing — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9964)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/create-an-account.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwbyd65aA8vBsKGKSs:-MVwbyd65aA8vBsKGKSt:bkujblz) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L21)):*
> ```Markdown
> <section class="filter-content" markdown="1" data-scope="github">
> 
> 1. Click **Sign up with GitHub**.
> ```

you'll be prompted after you click sign up with gh to agree to our T&cs. might want to add this as a new step or just add it to this step
___
*[cockroachcloud/create-an-account.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwcHR5-jTrRXTk-izz:-MVwcHR5-jTrRXTk-j--:b-aacm5q) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L22)):*
> ```Markdown
> 
> 1. Click **Sign up with GitHub**.
> 1. Enter your GitHub **Username or email address** associated with your account.
> ```

note: if you are already logged into a github session in the same browser you won't see login steps
___
*[cockroachcloud/create-an-account.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwca1d0QnUucExVtyk:-MVwca1d0QnUucExVtyl:b-asoegq) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L28)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> GitHub will verify your identity using [GitHub 2FA](https://docs.github.com/en/github/authenticating-to-github/about-two-factor-authentication), if you have it enabled.
> {{site.data.alerts.end}}
> ```

after you sign in i think there is still one more step to accept the connection to CC and authorize us to access your email address from gh
___
*[cockroachcloud/create-an-account.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwdKX_7y7MNIzCWZyL:-MVwdKX_7y7MNIzCWZyM:b1wf70l) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L145)):*
> ```Markdown
> 1. Click **Save**.
> 
>     A confirmation email will be sent to your email address.
> ```

one other thing maybe worth noting -- you can/maybe should follow up in your GH account and remove CC's access to your details as a best security practice. we won't use that information anymore (might even delete it from our db? @laurenbarker you can correct me here) but it's just a good practice I think to do both

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9964)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @laurenbarker, and @lnhsingh)

___
*[cockroachcloud/create-an-account.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwbyd65aA8vBsKGKSs:-MW0c4icEWjfGllLZTBO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L21)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

you'll be prompted after you click sign up with gh to agree to our T&cs. might want to add this as a new step or just add it to this step
</blockquote></details>

Done.
___
*[cockroachcloud/create-an-account.md, line 22 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwcHR5-jTrRXTk-izz:-MW0cP9L-URcKFCA3P52:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L22)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

note: if you are already logged into a github session in the same browser you won't see login steps
</blockquote></details>

Done.
___
*[cockroachcloud/create-an-account.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwca1d0QnUucExVtyk:-MW0cSjZEcnA0eSt6GVK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L28)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

after you sign in i think there is still one more step to accept the connection to CC and authorize us to access your email address from gh
</blockquote></details>

Done.
___
*[cockroachcloud/create-an-account.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/docs/9964#-MVwdKX_7y7MNIzCWZyL:-MW0cUHA94lw-0xD4G4f:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/73a0a333b785f7424299b8fb3baadd1ff29bb677/cockroachcloud/create-an-account.md#L145)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

one other thing maybe worth noting -- you can/maybe should follow up in your GH account and remove CC's access to your details as a best security practice. we won't use that information anymore (might even delete it from our db? @laurenbarker you can correct me here) but it's just a good practice I think to do both
</blockquote></details>

Done.

**Comment by emily-horing** [comment]
@gemma-shay I noticed a few things were off styling-wise in the preview. Not sure if there is much you can do about all of them (might be our defaults?) but thought I'd call them out:
Screen Shot 2021-03-17 at 2 51 19 PM

**Review by lnhsingh — APPROVED** [review]
One nit, but otherwise :lgtm: 

@emily-horing - we can't do much about the styling in this PR since it's a sitewide issue, but it might be ok on the live site once Gemma publishes (i.e., the preview site might not have the current style)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9964#-:-MW4bc4g1IZPzSovDK5z:b-x8md8n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, and @laurenbarker)

___
*[cockroachcloud/create-an-account.md, line 154 at r2](https://reviewable.io/reviews/cockroachdb/docs/9964#-MW4bZek-EfAQ23ukRF4:-MW4bZek-EfAQ23ukRF5:bmqiij) ([raw file](https://github.com/cockroachdb/docs/blob/514303bc8d1a662c94091a5e8593f027094316f8/cockroachcloud/create-an-account.md#L154)):*
> ```Markdown
>         
> {{site.data.alerts.callout_info}}
> Creating an account password will _not_ change your [SQL user](user-authorization.html#create-a-sql-user) password.
> ```

I don't think you need this callout here.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9964)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @emily-horing, @laurenbarker, and @lnhsingh)

___
*[cockroachcloud/create-an-account.md, line 154 at r2](https://reviewable.io/reviews/cockroachdb/docs/9964#-MW4bZek-EfAQ23ukRF4:-MW4wOEw0d8_1YJi0Pgq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/514303bc8d1a662c94091a5e8593f027094316f8/cockroachcloud/create-an-account.md#L154)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I don't think you need this callout here.
</blockquote></details>

Done.

**Pull request merged**
