### PR TITLE
SHOW TYPES: remove incorrect note, fix examples

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-10601

Follows up on something that was missed from DOC-6739

Tested and ported back to all doc sets v23.1+

### CODE REVIEW

**Comment by rmloveland** [comment]
Hi @rafiss I missed this update to `SHOW TYPES` back when creating user-defined composite types happened in v23.1 (the original docs PR was https://github.com/cockroachdb/docs/pull/16767)

Found this when getting ready to add `COMMENT ON TYPE` docs for the v24.2 release this summer 

Tested `SHOW TYPES` for composite types in v23.1 and it works (see PR description)

Please let me know if I should find another reviewer - thanks!

**Review by rafiss — CHANGES_REQUESTED** [review]
this lgtm!

btw, DOC-10601 is another ticket that tracks this outdated info. i believe that issue also mentions that the `Examples` are not up to date, so i think we should address that here too.

**Comment by rmloveland** [comment]
> this lgtm!

Sweet!

> btw, [DOC-10601](https://cockroachlabs.atlassian.net/browse/DOC-10601) is another ticket that tracks this outdated info. i believe that issue also mentions that the `Examples` are not up to date, so i think we should address that here too.

Should be fixed in the latest changes.  Tested and updated on everything v23.1+ 

PTAL!

**Review by rafiss — APPROVED** [review]
lgtm, thank you!

**Review by taroface — APPROVED** [review]

**Pull request merged**
