### PR TITLE
Views

### LINKED ISSUE #660: sql: Non-materialized Views Overview
Reference:
- Dev: @a-robinson 
- RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/views.md
- Issue: https://github.com/cockroachdb/cockroach/issues/2971
- PRs:
  - https://github.com/cockroachdb/cockroach/pull/9212
  - https://github.com/cockroachdb/cockroach/pull/9355
  - https://github.com/cockroachdb/cockroach/pull/9724
  - https://github.com/cockroachdb/cockroach/pull/10009
  - https://github.com/cockroachdb/cockroach/pull/9988

### LINKED ISSUE #769: sql: CREATE VIEW statement

### LINKED ISSUE #770: sql: DROP VIEW statement

### LINKED ISSUE #771: sql: ALTER VIEW statement

### PR DESCRIPTION
**Pull request by jseldess**
This PR provides an overview of views and reference docs for each view-related sql statement. 

Fixes #771 
Fixes #770 
Fixes #769 
Fixes #660 

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/774)

### CODE REVIEW

**Comment by a-robinson** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[show-create-view.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXgu492hme-18sjoYF:-KUXgu4Ap3hLhkRZzD7N:b-bhtf6h) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/show-create-view.md#L3)):*
> ```Markdown
> ---
> title: SHOW CREATE VIEW
> summary: The SHOW CREATE TABLE statement shows the CREATE TABLE statement that would create a carbon copy of the specified table. 
> ```

s/table/view

---

*[views.md, line 118 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXej7UWev-Legs4dkt:-KUXej7UWev-Legs4dku:b-v19tw2) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L118)):*
> ```Markdown
> 
> ~~~ sql
> > SHOW GRANTS on bank.accounts;
> ```

nit, but capitalize "on"

---

*[views.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXemesX4fUPY6sAPnN:-KUXemesX4fUPY6sAPnO:b-v19tw2) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L134)):*
> ```Markdown
> 
> ~~~ sql
> > GRANT SELECT on bank.user_accounts TO bob;
> ```

nit, but capitalize "on"

---

*[views.md, line 263 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXfux-5eldIkAAMPbU:-KUXfux-5eldIkAAMPbV:bt763la) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L263)):*
> ```Markdown
> ~~~
> 
> However, it is possible to drop columns that a view depends on and to rename tables, views, or columns that a view depends on, but doing so will cause the view to stop working. 
> ```

This statement is not (or should not) be true. It should not be possible to drop columns that a view depends on (as of https://github.com/cockroachdb/cockroach/pull/10089) or to rename objects that a view depends on (as of https://github.com/cockroachdb/cockroach/pull/9988).

It may be worth mentioning that it is possible to drop columns/tables/views etc. that a view depends on if you specify CASCADE. For example, this should fail:

DROP TABLE bank.accounts;

But this should succeed and drop the dependent user_accounts view in the process:

DROP TABLE bank.accounts CASCADE;

---

*[views.md, line 287 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXgcUuRX98PnY6RLgK:-KUXgcUuRX98PnY6RLgL:b5dmaze) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L287)):*
> ```Markdown
> ~~~
> 
> It is not possible to change the `SELECT` statement executed by the view. Therefore, when underlying tables are renamed or columns in underlying tables are dropped or renamed, it's necessary to drop the existing view and create a new view with the correctly named targets.
> ```

As mentioned above, the second part of this statement should not apply because it shouldn't be possible to rename/drop things a view depends on

---

*[views.md, line 301 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXgl8D1qZz4ofzUTCi:-KUXgl8D1qZz4ofzUTCj:bwi6f43) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L301)):*
> ```Markdown
> ~~~
> 
> However, note that a view targeted by another view cannot be dropped. For example, if you have a `bank.num_of_accounts` view that counts the rows resulting from a `bank.user_accounts view`, attempting to `DROP` `bank.user_accounts` will result in an error:
> ```

Again, might be worth mentioning CASCADE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774)*

**Comment by jseldess** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[show-create-view.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXgu492hme-18sjoYF:-KUXhfabNfavSaIB7-kn:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/show-create-view.md#L3)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> s/table/view
</details>
Done.

---

*[views.md, line 118 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXej7UWev-Legs4dkt:-KUXhldVJ4bi5PNM-HdU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L118)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> nit, but capitalize "on"
</details>
Done.

---

*[views.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXemesX4fUPY6sAPnN:-KUXhmGSq0CMDid47M33:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L134)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> nit, but capitalize "on"
</details>
Done.

---

*[views.md, line 263 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXfux-5eldIkAAMPbU:-KUYNMK8H1XF8MAxu0qC:byew5fk) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L263)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> This statement is not (or should not) be true. It should not be possible to drop columns that a view depends on (as of https://github.com/cockroachdb/cockroach/pull/10089) or to rename objects that a view depends on (as of https://github.com/cockroachdb/cockroach/pull/9988).
> 
> It may be worth mentioning that it is possible to drop columns/tables/views etc. that a view depends on if you specify CASCADE. For example, this should fail:
> 
> DROP TABLE bank.accounts;
> 
> But this should succeed and drop the dependent user_accounts view in the process:
> 
> DROP TABLE bank.accounts CASCADE;
</details>
Thanks for catching this. I've updated my version and am now seeing that you can't drop/rename a dependent table, view, or column without `CASCADE`. I've updated this section accordingly. PTAL.

I'm seeing only one potential problem: I'm not able to drop a dependent **column** even with `CASCADE`. Is that expected or something that needs to be addressed?

```
root@:26257> ALTER TABLE accounts DROP COLUMN email cascade;
pq: cannot drop column email because view "bank.user_accounts" depends on it
```

---

*[views.md, line 287 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXgcUuRX98PnY6RLgK:-KUZLuRQM3LGVtr-a4IR:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L287)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> As mentioned above, the second part of this statement should not apply because it shouldn't be possible to rename/drop things a view depends on
</details>
Done.

---

*[views.md, line 301 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXgl8D1qZz4ofzUTCi:-KUYOalsoQn_JdhVNTWS:bdv17vg) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L301)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Again, might be worth mentioning CASCADE
</details>
Think I'll remove in favor of covering this in the dependencies section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774)*

**Comment by a-robinson** [comment]
The overview looks good to me!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[views.md, line 263 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KUXfux-5eldIkAAMPbU:-KU_9J9WHllndL8VeJA8:b-eja9y1) ([raw file](https://github.com/cockroachdb/docs/blob/194d9b2fbb5ae9cc95a232c2f66058f8d256b4e6/views.md#L263)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Thanks for catching this. I've updated my version and am now seeing that you can't drop/rename a dependent table, view, or column without `CASCADE`. I've updated this section accordingly. PTAL.
> 
> I'm seeing only one potential problem: I'm not able to drop a dependent **column** even with `CASCADE`. Is that expected or something that needs to be addressed?
> 
> ```
> root@:26257> ALTER TABLE accounts DROP COLUMN email cascade;
> pq: cannot drop column email because view "bank.user_accounts" depends on it
> ```
</details>
You're a fantastic tester :) I sent out a PR to fix that this afternoon:
https://github.com/cockroachdb/cockroach/pull/10124

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774#-:-KU_AxgtBWR5CfPdH_HS:b1lfj2g)*

**Comment by jseldess** [comment]
@a-robinson, the view statement pages and related updates are now ready for your review. 

We still need to add detailed docs on `ALTER TABLE ... DROP COLUMN`. I'll do that separately, and when I do, I'll be sure to include details about `CASCADE`. If I've missed anything else, though, please let me know.

**Comment by a-robinson** [comment]
Reviewed 19 of 19 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[alter-view.md, line 7 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5L0moSxicncoDlvqD:-KV5L0moSxicncoDlvqE:b-vynw23) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/alter-view.md#L7)):*
> ```Markdown
> ---
> 
> The `ALTER VIEW` [statement](sql-statements.html) changes the name of a [view](views.html). 
> ```

Speaking of the sql-statements.html page, shouldn't the new statements be included on it?

---

*[alter-view.md, line 9 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5QNWCjp32ChiUAw8i:-KV5QNWDxtiqyLmeLdls:b-bkybu9) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/alter-view.md#L9)):*
> ```Markdown
> The `ALTER VIEW` [statement](sql-statements.html) changes the name of a [view](views.html). 
> 
> {{site.data.alerts.callout_info}}It is not possible to change the <code>SELECT</code> statement executed by a view. Instead, you must drop the existing view and create a new view. Also, it is not possible to rename a view that other views depend on, but this ability may be added in the future (see <a href="https://github.com/cockroachdb/cockroach/issues/10083">this issue</a>).{{site.data.alerts.end}}
> ```

Your call, but I might instead say "it is not currently possible to change the [...]" since supporting that behavior hasn't been ruled out, we just haven't bothered with it yet.

---

*[alter-view.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5Qxn-fD1SA5g6iA9E:-KV5Qxn-fD1SA5g6iA9F:b-v5ptaq) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/alter-view.md#L13)):*
> ```Markdown
> <div id="toc"></div>
> 
> ## Required Privileges
> ```

This requires DROP on the view and CREATE on the target database

---

*[alter-view.md, line 25 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5Qn1kFvy_1oc0OCc5:-KV5Qn1kFvy_1oc0OCc6:b-iudmxp) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/alter-view.md#L25)):*
> ```Markdown
> `IF EXISTS` | Rename the view only if a view of `view_name` exists; if one does not exist, do not return an error. 
> `view_name` | The name of the view to rename. To find view names, use:<br><br>`SELECT * FROM information_schema.tables WHERE table_type = 'VIEW';` 
> `name` | The new [`name`](sql-grammar.html#name) for the view, which must be unique to its datbase and follow these [identifier rules](keywords-and-identifiers.html#identifiers). 
> ```

s/datbase/database

---

*[create-view.md, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5S95dcudhaVsqIKo0:-KV5S95dcudhaVsqIKo1:b-miaxp) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/create-view.md#L24)):*
> ```Markdown
> ----------|------------
> `view_name` | The name of the view to create, which must be unique within its database and follow these [identifier rules](keywords-and-identifiers.html#identifiers). When the parent database is not set as the default, the name must be formatted as `database.name`.
> `opt_column_list` | An optional, comma-separated list of column names for the view. If specified, these names will be used in the response instead of the columns specified in `AS select_stmt`.
> ```

We don't make it super clear what the format of opt_column_list is -- maybe it should be part of an example? If I had never done it before and only read this doc, I'm not sure I'd be able to put together a CREATE VIEW statement that included one

---

*[create-view.md, line 52 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5Ryu239DCAmIdJJca:-KV5Ryu3EjJQSDHvT9yr:bkmzt9f) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/create-view.md#L52)):*
> ```Markdown
> ~~~
> 
> Alternately, to make it much easier to run this complex query, you could create a view:
> ```

Insignificant nit, but I believe that both here and in views.md this should be "Alternatively" instead

---

*[drop-table.md, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5SawWyQo0NiYWJJp3:-KV5SawXr-jNnb85NsDX:brt6klf) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-table.md#L24)):*
> ```Markdown
> ----------|------------
> `IF EXISTS`   | Drop the table if it exists; if it does not exist, do not return an error.
> `table_name`  | A comma-separated list of table names. To find table names, use [`SHOW TABLES`](show-tables.html.
> ```

Need to fix this broken link (missing parenthesis)

---

*[drop-table.md, line 96 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5StHLFhcJuyD5j2Rm:-KV5StHLFhcJuyD5j2Rn:byscqyz) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-table.md#L96)):*
> ```Markdown
> 
> ~~~
> pq: cannot drop table "accounts" because it is depended on by view "bank.user_accounts_view"
> ```

This is my fault for changing the error so late, but I got some feedback that it was better phrased as an active sentence. It should be:

pq: cannot drop table "accounts" because view "user_accounts_view" depends on it

---

*[drop-view.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5T7EslqvFY8ra1xDF:-KV5T7EslqvFY8ra1xDG:bcbuvjz) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-view.md#L13)):*
> ```Markdown
> ## Required Privileges
> 
> The user must have the `DROP` [privilege](privileges.html) on the specified view(s). If `CASCADE` is used to drop dependent views, the user must have the `DROP` privilege on each dependent view as well.
> ```

Just pointing out that you mention the need for additional privilege when using CASCADE here but not in DROP TABLE's privilege documentation, even though they behave the same way as each other

---

*[drop-view.md, line 94 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5TVgH3eSKfQVrExxM:-KV5TVgH3eSKfQVrExxN:b-do238a) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-view.md#L94)):*
> ```Markdown
> 
> ~~~ 
> pq: cannot drop view "user_accounts" because it is depended on by view "bank.user_emails"
> ```

Again, sorry for the change, but this would now be:

pq: cannot drop view "user_accounts" because view "user_emails" depends on it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[alter-view.md, line 7 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5L0moSxicncoDlvqD:-KV5ZQMcxVZTl3NyM4LT:bulzyxe) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/alter-view.md#L7)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Speaking of the sql-statements.html page, shouldn't the new statements be included on it?
</details>
Yes, thanks for catching that. Done.

---

*[drop-view.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5T7EslqvFY8ra1xDF:-KV5a9fzBRg4jL_VDGIk:br836l8) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-view.md#L13)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Just pointing out that you mention the need for additional privilege when using CASCADE here but not in DROP TABLE's privilege documentation, even though they behave the same way as each other
</details>
Thanks for the catch! I updated that privilege section to account for dropping dependent views. What about dropping dependent constraints? What type of privilege do you need on those affected tables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774)*

**Comment by a-robinson** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[drop-view.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5T7EslqvFY8ra1xDF:-KV5cFNwL2AjYeO_PHZM:bgyxfah) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-view.md#L13)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Thanks for the catch! I updated that privilege section to account for dropping dependent views. What about dropping dependent constraints? What type of privilege do you need on those affected tables?
</details>
To remove a foreign key constraint as part of a cascade, you need the CREATE privilege on the table containing the constraint. You could alternatively just say that you need to have the appropriate privileges to drop each dependent constraint, which would hopefully guide people to the docs for dropping constraints if there are any.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[create-view.md, line 24 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5S95dcudhaVsqIKo0:-KV5sgPJuIU8tkOGREAF:b-mx6wce) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/create-view.md#L24)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> We don't make it super clear what the format of opt_column_list is -- maybe it should be part of an example? If I had never done it before and only read this doc, I'm not sure I'd be able to put together a CREATE VIEW statement that included one
</details>
I've adjusted the diagram to better reflect the parenthetical format, and I've uses this parameter in the example here and on `views.md`. Thanks for the careful review!

---

*[drop-view.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/774#-KV5T7EslqvFY8ra1xDF:-KV5lzOlaKgVx9twdrOB:bza8t3r) ([raw file](https://github.com/cockroachdb/docs/blob/5119057ec9fcef7d750b95c989368be4a956c519/drop-view.md#L13)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> To remove a foreign key constraint as part of a cascade, you need the CREATE privilege on the table containing the constraint. You could alternatively just say that you need to have the appropriate privileges to drop each dependent constraint, which would hopefully guide people to the docs for dropping constraints if there are any.
</details>
I like that approach better. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/774#-:-KV5uQGc3BJIgZ7om1Hc:bnfp4nl)*

**Pull request merged**
