### PR TITLE
August release notes CC

### PR DESCRIPTION
**Pull request by gemma-shay**
Cloud release notes https://cockroachlabs.atlassian.net/browse/DOC-5214

### CODE REVIEW

**Review by emily-horing — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14584#-:-N8QWzGX8QA8VQeWQNDx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jramos-crl, @kevin-v-ngo, and @thtruo)

**Comment by gemma-shay** [comment]
@kevin-v-ngo @jramos-crl @thtruo @rmloveland hi everyone! these notes are already a little late so hoping to get them out by the end of the day

**Review by thtruo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14584#-:-N8yBX8fC12c8nMH_F4t:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @kevin-v-ngo and @rmloveland)

**Review by rmloveland — APPROVED** [review]
LGTM!

**Pull request merged**
