### PR TITLE
Add warning to release pages affected by A-58932

### PR DESCRIPTION
**Pull request by mikeCRL**
I gave the Technical Advisory wiki page a full read and noticed a step I'd missed in the prior PR https://github.com/cockroachdb/docs/pull/9687: adding an alert to each affected release page. I've done that here, modeled after the existing instances of `{{site.data.alerts.callout_danger}}` on the v20.1.4 and v20.1.5 release pages.

@taroface Could you please review this and let me know if you think it requires review from anyone else? Thank you.

### CODE REVIEW

**Review by taroface — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[_includes/v19.2/alerts/warning-a58932.md, line 1 at r2](https://reviewable.io/reviews/cockroachdb/docs/9728#-MT1Wfez81qWb_t836T_:-MT1Wfez81qWb_t836Ta:bbcegnz) ([raw file](https://github.com/cockroachdb/docs/blob/2e6d2c9972605c40834991987ea3eef44afdfd5b/_includes/v19.2/alerts/warning-a58932.md#L1)):*
> ```Markdown
> A denial-of-service (DoS) vulnerability is present in CockroachDB v19.2.0 - v19.2.11 due to a bug in [protobuf](https://github.com/gogo/protobuf). This is resolved in CockroachDB [v19.2.12](../releases/v19.2.12.html) and [later releases](/docs/releases/#production-releases). When upgrading is not an option, users should audit their network configuration to verify that the CockroachDB HTTP port is not available to untrusted clients. We recommend blocking the HTTP port behind a firewall.
> ```

My understanding based on the TA is that this bug is also present in v20.1 and v21.1, and that the earliest respective bug-free versions are v19.2.12, v20.1.11, v20.2.4. If that's the case, I'd recommend cutting `v19.2.0 - v19.2.11` and adding `, v20.1.11, v20.2.4` (with links) to the second sentence.

Also, the "later releases" link isn't working for me on preview. Possibly because of `/docs` in the URL?

**Comment by taroface** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)
> 
> _[_includes/v19.2/alerts/warning-a58932.md, line 1 at r2](https://reviewable.io/reviews/cockroachdb/docs/9728#-MT1Wfez81qWb_t836T_:-MT1Wfez81qWb_t836Ta:bbcegnz) ([raw file](https://github.com/cockroachdb/docs/blob/2e6d2c9972605c40834991987ea3eef44afdfd5b/_includes/v19.2/alerts/warning-a58932.md#L1)):_
> 
> > ```gfm
> > A denial-of-service (DoS) vulnerability is present in CockroachDB v19.2.0 - v19.2.11 due to a bug in [protobuf](https://github.com/gogo/protobuf). This is resolved in CockroachDB [v19.2.12](../releases/v19.2.12.html) and [later releases](/docs/releases/#production-releases). When upgrading is not an option, users should audit their network configuration to verify that the CockroachDB HTTP port is not available to untrusted clients. We recommend blocking the HTTP port behind a firewall.
> > ```
> 
> My understanding based on the TA is that this bug is also present in v20.1 and v21.1, and that the earliest respective bug-free versions are v19.2.12, v20.1.11, v20.2.4. If that's the case, I'd recommend cutting `v19.2.0 - v19.2.11` and adding `, v20.1.11, v20.2.4` (with links) to the second sentence.

Oh sorry, Reviewable tricked me into thinking the v19.2 snippet was the only update! Please disregard this part of the comment. I'll look through the rest now.

**Review by taroface — CHANGES_REQUESTED** [review]
> Reviewed 56 of 59 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[releases/v19.2.1.md, line 15 at r2](https://reviewable.io/reviews/cockroachdb/docs/9728#-MT1bENC79FjesPyCVrw:-MT1bENC79FjesPyCVrx:bvj9315) ([raw file](https://github.com/cockroachdb/docs/blob/2e6d2c9972605c40834991987ea3eef44afdfd5b/releases/v19.2.1.md#L15)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> {% include /v20.2/alerts/warning-a58932.md %}
> ```

This should be v19.2.

**Review by mikeCRL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL and @taroface)

___
*[releases/v19.2.1.md, line 15 at r2](https://reviewable.io/reviews/cockroachdb/docs/9728#-MT1bENC79FjesPyCVrw:-MT1d1V53_IcrxTuFHAe:bves986) ([raw file](https://github.com/cockroachdb/docs/blob/2e6d2c9972605c40834991987ea3eef44afdfd5b/releases/v19.2.1.md#L15)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This should be v19.2.
</blockquote></details>

Good catch! Fixed.

**Comment by taroface** [comment]
Maybe @bobvawter can have a look and confirm that the snippet is accurate.

**Review by mikeCRL — COMMENTED** [review]
> Dismissed @taroface from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Comment by mikeCRL** [comment]
@taroface Thanks for the quick review. I think I've acknowledged everything properly in Reviewable (please let me know if not; still figuring out how to use it) and pushed that one fix. I see a TC build error. Doesn't look like it's my fault. But I'm not sure how to re-run the build. Can you please advise?

**Comment by taroface** [comment]
> @taroface Thanks for the quick review. I think I've acknowledged everything properly in Reviewable (please let me know if not; still figuring out how to use it) and pushed that one fix. I see a TC build error. Doesn't look like it's my fault. But I'm not sure how to re-run the build. Can you please advise?

Yes, that is related to this other comment I had (it was a little buried):

> Also, the "later releases" link isn't working for me on preview. Possibly because of /docs in the URL?

**Review by taroface — APPROVED** [review]
LGTM after the docs link is fixed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728#-:-MT1kY9q2QerZUM3QWtZ:b4wosvc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Comment by mikeCRL** [comment]
> > @taroface Thanks for the quick review. I think I've acknowledged everything properly in Reviewable (please let me know if not; still figuring out how to use it) and pushed that one fix. I see a TC build error. Doesn't look like it's my fault. But I'm not sure how to re-run the build. Can you please advise?
> 
> Yes, that is related to this other comment I had (it was a little buried):
> 
> > Also, the "later releases" link isn't working for me on preview. Possibly because of /docs in the URL?

Thanks. Missed that. Pushed a fix and will confirm it works.

**Comment by mikeCRL** [comment]
@knz Would you mind reviewing? It's a brief summary of the last technical advisory, in the form of a warning on each affected release page. (After publishing the advisory, I found this listed as a requirement on the [Technical Advisory wiki page](https://cockroachlabs.atlassian.net/wiki/spaces/TS/pages/271155269/Technical+Alerts+Proposal) in Process Flow > Alert Types.)

I produced 3 variants of the message, one for each major version affected, to not overload the note with many unrelated version numbers. They're exemplified on these three pages though they're included on all preceding release pages of the respective major release.

- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0c14bcb52e821f224f401d3fd598ac376c4facf7/releases/v20.2.3.html
- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0c14bcb52e821f224f401d3fd598ac376c4facf7/releases/v20.1.10.html
- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/0c14bcb52e821f224f401d3fd598ac376c4facf7/releases/v19.2.9.html

Thank you.

**Review by knz — COMMENTED** [review]
The text of the callout is fine,
however I am a bit surprised / saddened by how much work you had to do to add the callout everywhere.

Also I am surprised we did not add callouts for previous TAs which also had serious shortcomings.

Here's an idea:

- keep the include but without the alert box in every release page, i.e. replace

  `{{site.data.alerts.callout_danger}}{% include ... %}{{site.data.alerts.end}}`

   with

  `{% include ... %}`

- make the include reference a *generic* TA-related include page, e.g. replace

  `{% include /v19.2/alerts/warning-a58932.md %}`

   with

  `{% include /v19.2/alerts/ta-callouts.md %}`

- change the release note generation script to add this include in every new and future release note page, so that it gets linked automatically.

- make the page `ta-callouts.md` use the `{{site.data.alerts...}}` enclosure, one per relevant TA

> Reviewed 1 of 59 files at r1, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9728#-:-MTAMbT_0E0JSLT7Qnum:bjv568z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Comment by mikeCRL** [comment]
@knz Great ideas. Thank you. I am merging this as-is so we get the notice up without further delay, but will:
1. Create an issue for the Docs Team to consider these solutions (with a reminder to consider updating my A-58932 markup, if we do set a new standard). https://github.com/cockroachdb/docs/issues/9789 (Includes a note on why I had considered and chose not to do your 'suggestion `1`' when I was originally authoring.)
2. Add info about Technical Advisories in the Docs Team wiki section, and potentially refine the existing instructions within [Technical Advisory wiki page](https://cockroachlabs.atlassian.net/wiki/spaces/TS/pages/271155269/Technical+Alerts+Proposal) - ensuring not to duplicate, but cross-link as appropriate.

**Pull request merged**
