### PR TITLE
Cross-database foreign key and view references disallowed by default.

### LINKED ISSUE #8503: release-20.2: sql: disallow cross-database foreign keys and views
PR: https://github.com/cockroachdb/cockroach/pull/54520

From release notes:
> Creating [views](../v20.2/views.html) that refer to tables in other databases is now disallowed (and can be re-enabled via the `sql.cross_db_views.enabled` cluster setting). [#54520][#54520] {% comment %}doc{% endcomment %}
>
> Creating cross-database [foreign key references](../v20.2/foreign-key.html) is now disallowed (and can be re-enabled via the `sql.cross_db_fks.enabled` cluster setting). [#54520][#54520] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #8503. 

Added notes to Views, `CREATE VIEW`, Foreign Keys, `ADD CONSTRAINT` docs.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Looks great. There is one more thing - in 20.2 the `OWNED BY` option of [CREATE SEQUENCE](https://www.cockroachlabs.com/docs/stable/create-sequence.html#parameters) cannot refer to a column in another database (and can be enabled using the cluster setting `sql.cross_db_sequence_owners.enabled`). This was done in https://github.com/cockroachdb/cockroach/pull/54585

**Comment by ericharmeling** [comment]
> Looks great. There is one more thing - in 20.2 the `OWNED BY` option of [CREATE SEQUENCE](https://www.cockroachlabs.com/docs/stable/create-sequence.html#parameters) cannot refer to a column in another database (and can be enabled using the cluster setting `sql.cross_db_sequence_owners.enabled`). This was done in [cockroachdb/cockroach#54585](https://github.com/cockroachdb/cockroach/pull/54585)

@RaduBerinde TFTR and thanks for the heads-up. We're tracking that separating here: https://github.com/cockroachdb/docs/issues/8511.

**Review by RaduBerinde — APPROVED** [review]

**Review by lnhsingh — COMMENTED** [review]
A question about how we use `foreign-key` vs `foreign key` but the updates in general LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8551#-:-MJ3cBmI5nYSyKwa6Plo:b-ilyxxz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @lnhsingh)

___
*[v20.2/add-constraint.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/docs/8551#-MJ3begqBMhk86F_Veki:-MJ3begqBMhk86F_Vekj:b-z7r3o9) ([raw file](https://github.com/cockroachdb/docs/blob/d7982415ef4131c8a03811aedfef50a35a837432/v20.2/add-constraint.md#L163)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> <span class="version-tag">New in v20.2:</span> By default, referenced columns must be in the same database as the referencing foreign-key column. To enable cross-database foreign-key references, set the `sql.cross_db_fks.enabled` [cluster setting](cluster-settings.html) to `true`.
> ```

From a quick search of our docs, it seems like `foreign-key` shouldn't be hyphenated-- was this intentional? I'll leave it up to you but my recommendation is to change all the mentions of `foreign-key` > `foreign key` in your updates.

**Review by ericharmeling — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8551#-:-MJ3gC_V7vETyHSenYV7:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[v20.2/add-constraint.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/docs/8551#-MJ3begqBMhk86F_Veki:-MJ3eMie8HQiw836aynU:b-7v501d) ([raw file](https://github.com/cockroachdb/docs/blob/d7982415ef4131c8a03811aedfef50a35a837432/v20.2/add-constraint.md#L163)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

From a quick search of our docs, it seems like `foreign-key` shouldn't be hyphenated-- was this intentional? I'll leave it up to you but my recommendation is to change all the mentions of `foreign-key` > `foreign key` in your updates.
</blockquote></details>

Changed all `foreign-key` to `foreign key`.

It was intentional lol. For some reason, I thought that you hyphenate compound words when they are used as an adjective (e.g., foreign-key column) [1]? But we *definitely* don't follow this as a rule in our docs (or even throughout this page).

[1] For reference: https://apastyle.apa.org/learn/faqs/when-use-hyphen

**Pull request merged**
