### PR TITLE
Add docs on how slow user/pass auth can happen

### LINKED ISSUE #10921: Document why a dead/disconnected node means you can not create new connections on other nodes for a while
As explained by @rafiss in #10913:

> A major motivation for this docs request was a report from a customer who observed a long period of inability to create any new connections to any node in the cluster when one other node was forcefully terminated and black-holed. It was actually easy to reproduce reliably. Note that the system ranges are also very early in the keyspace. During authentication user/password information needs to be looked from a system range. So if that system range is colocated with the liveness range, it made the period of inability-to-connect last longer.

So there are at least the following pieces of work:

1. We need docs (probably in [Troubleshoot Cluster > Authentication issues](https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#cockroachdb-authentication-issues)) about what it means when this happens, with a link to ...

2. An update to the [Replication Layer docs]() that at least mentions this behavior and how it is linked to the fact that liveness range and the range holding user/pass auth info are nearby - with links back over to the troubleshooting docs for findability

Did not want to do this directly in #10917 since it's a slightly different ask than "describe how leases are transferred when a node dies" and as such would make writing a coherent PR harder if it was smushed in that one.

See also:

- #5470
- #10913

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #10921

Related:

- #10917

### CODE REVIEW

**Comment by rmloveland** [comment]
@rafiss I tried to capture some info from the support ticket and other things you linked in your comment on #10921 but please let me know if I missed anything or got something wrong

Specific questions:

- Does this apply to basically every version prior to (the eventual) v21.2 ?
  - if so, I will add this section to the last 3 versions of the docs (v20.1, v20.2, v21.1)
- Are we planning to back port a fix to e.g. v20.2 or v21.1?  it looks like that hasn't happened yet, so I did not mention in this draft

**Review by rafiss — APPROVED** [review]
this looks good! can the same docs go into 20.2 and earlier versions? (we shouldn't need this in 21.2 since i added a cache to fix this problem in the vast majority of cases)

**Comment by rafiss** [comment]
oh oops, missed your comment. correct: currently no plans to backport this since it's a bit of a large change

**Comment by rmloveland** [comment]
> this looks good! can the same docs go into 20.2 and earlier versions? (we shouldn't need this in 21.2 since i added a cache to fix this problem in the vast majority of cases)

great!  yes I will definitely add this info to the docs for v20.2 and earlier once this gets through Docs Team review

> currently no plans to backport the cache since it's a bit of a large change

duly noted!  thanks for the review Rafi!

**Review by taroface — APPROVED** [review]
LGTM. 1 typo and 2 light suggestions!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10964#-:-Mg7kp1IES1gZWAwpcdu:btdact1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/cluster-setup-troubleshooting.md, line 261 at r1](https://reviewable.io/reviews/cockroachdb/docs/10964#-Mg7jEJqD4zC_ZLwj355:-Mg7jEJqD4zC_ZLwj356:bqhrh0a) ([raw file](https://github.com/cockroachdb/docs/blob/4918ed73e761416f17f901c0b2f0d79318c08d0c/v21.1/cluster-setup-troubleshooting.md#L261)):*
> ```Markdown
> ### Cannot create new connections to cluster for up to 40 seconds after a node dies
> 
> When a node dies abruptly and/or loses its network connection to the cluster, the following behavior can occur:
> ```

Suggest linking this statement to `#node-liveness-issues` (I know it's also linked below, but extra context should be helpful here)
___
*[v21.1/cluster-setup-troubleshooting.md, line 269 at r1](https://reviewable.io/reviews/cockroachdb/docs/10964#-Mg7j8C9Aq8HfrLn8rLq:-Mg7j8CA4hBPDR1PBH_B:b-nlgyng) ([raw file](https://github.com/cockroachdb/docs/blob/4918ed73e761416f17f901c0b2f0d79318c08d0c/v21.1/cluster-setup-troubleshooting.md#L269)):*
> ```Markdown
> 
> - Username and password information is stored in a system range.
> - Since all system ranges are located [near the begging of the keyspace](architecture/distribution-layer.html#monolithic-sorted-map-structure), this system range can sometimes be colocated with another system range that is used to determine [node liveness](#node-liveness-issues).
> ```

begging -> beginning
___
*[v21.1/cluster-setup-troubleshooting.md, line 269 at r1](https://reviewable.io/reviews/cockroachdb/docs/10964#-Mg7jcH9461M0uNK9rdj:-Mg7jcH9461M0uNK9rdk:bwfnbev) ([raw file](https://github.com/cockroachdb/docs/blob/4918ed73e761416f17f901c0b2f0d79318c08d0c/v21.1/cluster-setup-troubleshooting.md#L269)):*
> ```
> this system range
> ```

Maybe "the system range containing the username/password", to be extra-hyper-clear, but your call!

**Review by rmloveland — COMMENTED** [review]
Thanks Ryan!  Excellent review suggestions as always!  Did all the things.

(Also porting these changes to v20.1 and v20.2)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10964#-:-MgCDUKg-Dkuu84IzUeF:b-2kea6c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[v21.1/cluster-setup-troubleshooting.md, line 261 at r1](https://reviewable.io/reviews/cockroachdb/docs/10964#-Mg7jEJqD4zC_ZLwj355:-MgCDGRu1FfczeHiMnbd:bjez9f4) ([raw file](https://github.com/cockroachdb/docs/blob/4918ed73e761416f17f901c0b2f0d79318c08d0c/v21.1/cluster-setup-troubleshooting.md#L261)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest linking this statement to `#node-liveness-issues` (I know it's also linked below, but extra context should be helpful here)
</blockquote></details>

Did it!
___
*[v21.1/cluster-setup-troubleshooting.md, line 269 at r1](https://reviewable.io/reviews/cockroachdb/docs/10964#-Mg7j8C9Aq8HfrLn8rLq:-MgCDK15BKJOOO8m2xHq:b1gbt06) ([raw file](https://github.com/cockroachdb/docs/blob/4918ed73e761416f17f901c0b2f0d79318c08d0c/v21.1/cluster-setup-troubleshooting.md#L269)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

begging -> beginning
</blockquote></details>

HA

Fixed
___
*[v21.1/cluster-setup-troubleshooting.md, line 269 at r1](https://reviewable.io/reviews/cockroachdb/docs/10964#-Mg7jcH9461M0uNK9rdj:-MgCDQxa6PSdDSRDoCos:b-n8xte2) ([raw file](https://github.com/cockroachdb/docs/blob/4918ed73e761416f17f901c0b2f0d79318c08d0c/v21.1/cluster-setup-troubleshooting.md#L269)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> this system range
> ```

Maybe "the system range containing the username/password", to be extra-hyper-clear, but your call!
</blockquote></details>

I like it!  Clarity is good. Updated!

**Pull request merged**
