### PR TITLE
column family updates

### LINKED ISSUE #426: Column family defaults
Update docs to cover column family defaults: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_column_families.md

Related to https://github.com/cockroachdb/cockroach/pull/7491

### PR DESCRIPTION
**Pull request by jseldess**
This PR updates our column family and create table docs to account for recently released column family heuristics. 

Fixes #426

HTML version  here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6aed09d6fbe537be2134279e5f1cba28a91776e1/

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/450)

### CODE REVIEW

**Comment by paperstreet** [comment]
Apologies if I missed it, but we should cover the family support in ALTER TABLE ADD column (https://github.com/cockroachdb/cockroach/pull/7711 and https://github.com/cockroachdb/cockroach/pull/7466)

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[column-families.md, line 17 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KM_xF-cLmwlEOxEIINa:-KM_xF-cLmwlEOxEIINb:1332548913) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/column-families.md#L17)):*
> ```Markdown
> When a table is created, CockroachDB automatically groups columns into families as follows:
> 
> - Fixed-size columns are stored as a single column family: `INT`, `DECIMAL` with precision, `FLOAT`, `BOOL`, `DATE`, `TIMESTAMP`, `INTERVAL`, `STRING` with length limit, and `BYTES`. 
> ```

no BYTES

---

*[column-families.md, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KM_xeYAUju7nrpmFzh1:-KM_xeYAUju7nrpmFzh2:1440534848) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/column-families.md#L35)):*
> ```Markdown
> To manually create a column family, you use the `FAMILY` keyword on table creation. 
> 
> For example, let's say we want to create a `users` table containing `id` and `last_login` columns. Since both of these columns are of a fixed size, CockroachDB would assign them to a single column family by default. However, since it's very likely that the `last_login` column will be updated more often than the `id` column, we can use the `FAMILY` keyword to make sure the columns are assigned to separate families:
> ```

Since the first case is much more important, I'd much rather we use the user name

```
CREATE TABLE users (
  id INT PRIMARY KEY,
  joined TIMESTAMP,
  name STRING,
  FAMILY (id, joined, name)
)
```

The name is unbounded because that's best practice for dealing with human names (who knows how long the longest name is), but names are generally short, so they should be put in the same family
  

---

*[column-families.md, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KM_z7jFFJZiH6MjhfSR:-KM_z7jFFJZiH6MjhfSS:-494198571) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/column-families.md#L64)):*
> ```Markdown
> ## Compatibility with Past Releases
> 
> As of the [`beta-20160714`](beta-20160714.html) release, creating a new table makes your data incompatible with earlier versions. 
> ```

Using the beta-20160714 release makes your data incompatible with versions earlier than the beta-20160629 release

---

*[create-table.md, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KMa-XUBPgZ1Na4jOMIg:-KMa-XUCfr0mVLZ8O0K3:903151148) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/create-table.md#L125)):*
> ```Markdown
> CREATE TABLE logoff (
>     user_id INT PRIMARY KEY, 
>     user_email STRING(50) UNIQUE, 
> ```

We should avoid limiting the size of fields if we can. I feel like it isn't best practice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/450#-:-KMa-jurwEOI_Ia6_tJD:1254835512)*

**Comment by jseldess** [comment]
@paperstreet, addressed everything but `alter table add`, which I'll do next. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[column-families.md, line 17 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KM_xF-cLmwlEOxEIINa:-KMdlfbgZ5HJKGq3CXzo:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/column-families.md#L17)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> no BYTES
</details>
Done.

---

*[column-families.md, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KM_xeYAUju7nrpmFzh1:-KMdpY5Fbck6V__50DRK:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/column-families.md#L35)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Since the first case is much more important, I'd much rather we use the user name
> 
> ```
> CREATE TABLE users (
>   id INT PRIMARY KEY,
>   joined TIMESTAMP,
>   name STRING,
>   FAMILY (id, joined, name)
> )
> ```
> 
> The name is unbounded because that's best practice for dealing with human names (who knows how long the longest name is), but names are generally short, so they should be put in the same family
>   
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/450#-:-KMdv4y7BadH5EEJHwg7:-1402556372)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[column-families.md, line 63 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KMdyS3LnSfXfS94xio9:-KMdyS3LnSfXfS94xioA:-1292932306) ([raw file](https://github.com/cockroachdb/docs/blob/58238aba37e2b20be221395d6b4f579a958a3703/column-families.md#L63)):*
> ```Markdown
> {{site.data.alerts.callout_info}}Columns that are part of the primary index are always assigned to the first column family. If you manually assign primary index columns to a family, it must therefore be the first family listed in the <code>CREATE TABLE</code> statement.{{site.data.alerts.end}} 
> 
> ## Compatibility with Past Releases
> ```

This seems fine for now, but it really belongs on that page we discussed about compatibility between versions. Consider prioritizing that page soon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/450#-:-KMdyudChRbP32LDxJhW:1417088721)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[column-families.md, line 67 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KMeABZDaqSnFEB6k3HB:-KMeABZE_lxaIOmOblov:-1744145593) ([raw file](https://github.com/cockroachdb/docs/blob/f4652361bc9d87b7d293b9f4e8f5c8d240af9c1f/column-families.md#L67)):*
> ```Markdown
> When using the `ALTER TABLE` statement to add a column to a table, you can assign the column to a new or existing column family. 
> 
> - To add a column and assign it to a new family, use the `CREATE FAMILY` keyword. For example, if we wanted to add an `email` column to the `users` table above and assign it to a new column family, we would run the following: 
> ```

how about `data BYTES` for this one example since we're saying elsewhere that `email` should be grouped with other columns

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/450#-:-KMeAXX1DJ15yR0TLs6X:1417088721)*

**Comment by jseldess** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[column-families.md, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KM_z7jFFJZiH6MjhfSR:-KMeGJ6Wi-wD3D3dxe8R:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/5cfebbbf20b5b9df46bc44f398aa0733f976275e/column-families.md#L64)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Using the beta-20160714 release makes your data incompatible with versions earlier than the beta-20160629 release
</details>
Done.

---

*[column-families.md, line 63 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KMdyS3LnSfXfS94xio9:-KMeG94It0d0p0vwP4ib:655561296) ([raw file](https://github.com/cockroachdb/docs/blob/58238aba37e2b20be221395d6b4f579a958a3703/column-families.md#L63)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> This seems fine for now, but it really belongs on that page we discussed about compatibility between versions. Consider prioritizing that page soon
</details>
OK, I'll work on this soon.

---

*[column-families.md, line 67 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/450#-KMeABZDaqSnFEB6k3HB:-KMeG8YWc_j14MovzbYH:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/f4652361bc9d87b7d293b9f4e8f5c8d240af9c1f/column-families.md#L67)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> how about `data BYTES` for this one example since we're saying elsewhere that `email` should be grouped with other columns
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/450)*

**Pull request merged**
