### PR TITLE
Embedded some new videos

### LINKED ISSUE #7804: Embedding tutorial videos in appropriate docs pages
Hey @ericharmeling,

Recently we made some tutorial videos that would fit nicely in the corresponding docs pages. Jesse mentioned that there is not an existing convention for how to make this happen. But maybe we can invent one!?

Anyways, here is what I'm thinking:

Embed this Schema Migration demo ( https://youtu.be/xz4j5tU0ZRU) into this docs page: https://www.cockroachlabs.com/docs/stable/flyway.html

Here are a couple existing examples of how that should look:

• https://www.cockroachlabs.com/docs/v20.1/topology-duplicate-indexes.html
• https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-upgrade-to-v20.1.html 
• https://www.cockroachlabs.com/docs/stable/demo-automatic-cloud-migration.html

If this goes well, I have a list of other videos to embed (https://docs.google.com/spreadsheets/d/1hdXbwPtVrcUHr6HMsQ6WUSkxBBdpdbK4vck6uSCgO1w/edit?usp=sharing). And there will be more on the way. But I don't want to get too far ahead of myself....

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7804. 

FYI @dankellycockroach @jseldess

### CODE REVIEW

**Comment by ericharmeling** [comment]
These aren't loading in the preview.
@jseldess Have you encountered this in previous video-embedding PRs?

**Comment by lnhsingh** [comment]
Is there a way to load videos in the preview @jseldess? If not, Eric might just need to merge the PR and revert the changes if need be.

**Comment by jseldess** [comment]
Sorry for the delay! I can't remember seeing this issue before. We might have some youtube rules in place to allow embedding only in certain domains. That would be my guess. @dankellycockroach, do you know if such rules exist.

If Dan doesn't know what's up here, I'm fine merging and then, if necessary, reverting.

**Comment by ericharmeling** [comment]
> Sorry for the delay! I can't remember seeing this issue before. We might have some youtube rules in place to allow embedding only in certain domains. That would be my guess. @dankellycockroach, do you know if such rules exist.
> 
> If Dan doesn't know what's up here, I'm fine merging and then, if necessary, reverting.

If you don't have any problems with the video placement @lnhsingh, I'm going to go ahead and merge this, and, if the videos don't show up, revert.

**Pull request merged**
