### PR TITLE
CC July Release Notes

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/CC-3667

### CODE REVIEW

**Review by kannanlakshmi — COMMENTED** [review]
Adding @thtruo @emily-horing @jramos-crl for review as well. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855#-:-MdSuanx4W-bLkCk6Eg1:b-hk83oz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing)

**Review by kannanlakshmi — APPROVED** [review]
LGTM tho I know Tommy has some updates around statements page in the CC UI. Let's always add Tommy as a reviewer. 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855#-:-MdSz__y5q_slRfCRg_b:b-t8s3tl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing)

**Review by kannanlakshmi — CHANGES_REQUESTED** [review]
One more question for @jramos-crl do we want to say that starting next month, you'll only receive 1 bill per month ie we're changing our billing period? Users might expect a bill on July 15th. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855#-:-MdSziB34-CxRaQVHHe3:bz6cw1p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing)

**Comment by kannanlakshmi** [comment]
ah sorry for the many disparate comments Gemma but note that the [feature flag](https://cockroachlabs.atlassian.net/browse/SREOPS-2358) for multiregion hasnt been turned on yet, so lets not publish the release notes till that says "Done"

**Comment by gemma-shay** [comment]
- Oh I thought multiregion was live now, whoops. It will be turned on by July 6, right? 
- Added billing change.
- If there are statements changes other than the Reset Sql Stats feature, where could I find those for release notes generator script purposes?

**Comment by kannanlakshmi** [comment]
> * Oh I thought multiregion was live now, whoops. It will be turned on by July 6, right?
Yes it should be, I am keeping a close eye on that ticket. 
> * Added billing change.
Thanks! 
> * If there are statements changes other than the Reset Sql Stats feature, where could I find those for release notes generator script purposes?
@thtruo, do you know what the observability team uses?

**Review by thtruo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @gemma-shay)

___
*[releases/cockroachcloud-07062021.md, line 16 at r2](https://reviewable.io/reviews/cockroachdb/docs/10855#-MdT5SlM1jJSlkKRm293:-MdT5SlM1jJSlkKRm294:b-bg4cq0) ([raw file](https://github.com/cockroachdb/docs/blob/4ff0d35f2faf39c9b1658c07dc796ad4cf90fefd/releases/cockroachcloud-07062021.md#L16)):*
> ```Markdown
> 
> - New CockroachCloud clusters will now run CockroachDB [v21.1.3](v21.1.3.html).
> - Starting this month, paid CockroachCloud clusters will be billed monthly instead of every two weeks.
> ```

@gemma-shay We recently added the Transactions page to CockroachCloud. Could we add a statement similar to what we had in June's release note, e.g.:

"All CockroachCloud Dedicated users now have access to the Transactions page in the Console."

**Comment by thtruo** [comment]
Hey @kannanlakshmi, 

> If there are statements changes other than the Reset Sql Stats feature, where could I find those for release notes generator script purposes?
@thtruo, do you know what the observability team uses?

^ We've handed off the Statements/Sessions/Txns pages to the SQL Observability team, so looping in @kevin-v-ngo re "Reset Sql Stats" feature

**Review by jramos-crl — COMMENTED** [review]
Thanks for adding the billing change, looks good to me :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855#-:-MdTEOLa7o3Z891g8ipp:b-9km9ec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @gemma-shay)

**Review by thtruo — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @gemma-shay)

___
*[releases/cockroachcloud-07062021.md, line 22 at r3](https://reviewable.io/reviews/cockroachdb/docs/10855#-MdTp1fj21EpDdCtS9uv:-MdTp1fj21EpDdCtS9uw:b3b84h) ([raw file](https://github.com/cockroachdb/docs/blob/c2a842bcd7b1d781c65af36ed32dae3f4f5c4869/releases/cockroachcloud-07062021.md#L22)):*
> ```Markdown
> - [Multi-region](../cockroachcloud/create-your-cluster.html#step-3-select-the-region-s) clusters can now be created through the Console. To learn more about creating a multi-region cluster, see [Planning your cluster](../cockroachcloud/cluster-management.html?filters=dedicated#planning-your-cluster).
> - The **Connect** modal now has updated commands to make [connecting to your cluster](../cockroachcloud/connect-to-a-free-cluster.html) a smoother experience on Mac, Linux, and Windows.
> - All CockroachCloud users now have access to the [**Transactions** page](../cockroachcloud/transactions-page.html) in the Console.
> ```

Nice, this LGTM!

**Review by emily-horing — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10855)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

**Comment by kevin-v-ngo** [comment]
Thanks Tommy. I wasn't aware that we ported reset SQL stats (or 21.1 changes) to CC. We had an epic tracking this work: https://cockroachlabs.atlassian.net/browse/CRDB-6920?filter=10362. 

Adding @maryliag and @Azhng to confirm. Are changes made to cluster-ui in cockroach repo automatically pulled into CC Console now?

If so, as for DB console udpates made in self-hosted in 21.1.3, here's the list: https://www.cockroachlabs.com/docs/releases/v21.1.3#db-console-changes

**Comment by Azhng** [comment]
I double checked the [cluster-ui doc](https://github.com/cockroachdb/cockroach/tree/master/pkg/ui/cluster-ui#4-publish), it seems like it's a manual process and someone needs to manually pull the changes from DB Console into CC Console. @maryliag  can you confirm?

**Comment by maryliag** [comment]
Changes made to cluster-ui in cockroach repo are NOT automatically pulled into CC Console, but @Azhng requested that this feature be backported, so the changes were in fact backported, but it's under a flag, you can see the backport PR here: https://github.com/cockroachdb/cockroach/pull/66198

**Comment by gemma-shay** [comment]
New clusters are now running 21.1.5 after a serious bug in 21.1.4 (https://cockroachlabs.atlassian.net/browse/SREOPS-2371). Postponing these notes briefly until there are CRDB docs for the two extraordinary releases.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
