### PR TITLE
DOC-9773 Update Observability docs for Cloud 2.0 - Third-Party

### PR DESCRIPTION
**Pull request by florence-crl**
Fixes DOC-9773

(1) In monitor-cockroachdb-with-prometheus.md, (a) added/modified tip for CockroachDB Cloud integration with Prometheus with links to Export Metrics Standard and Advanced.
(2) In export-metrics.md, (a) replaced standard with cloud in Datadog link.
(3) In export-metrics-advanced.md, (a) replaced advanced with cloud in Datadog link, (b) simplified Datadog intro sentences to remove redundancy.
(4) In datadog.md, replaced dedicated with cloud and fixed link format.
(5) In kibana.md, replaced dedicated with standard/advanced and fixed link format.
(6) In v23.1/differences-in-metrics-between-third-party-monitoring-integrations-and-db-console.md, replaced dedicated with standard/advanced and fixed link format.
(7) In third-party-monitoring-tools.md, (a) replaced dedicated rows with standard/advanced rows, (b) fixed link format, (c) removed CockroachDB in CockroachDB Deployment column, (d) added rows for Prometheus Platform for standard, advanced, and self-hosted deployments, (e) re-organized with availability matrix and platform sections, (f) added section for GCP Logging Platform.

### CODE REVIEW

**Review by rmloveland — APPROVED** [review]
LGTM!

**Comment by florence-crl** [comment]
@kevin-v-ngo On the [Third-Party Monitoring tools page](https://deploy-preview-18352--cockroachdb-docs.netlify.app/docs/v23.2/third-party-monitoring-tools.html), should I add 2 additional lines (for Standard and Advanced) in the table for Prometheus, similar to Cloudwatch and Datadog?

**Comment by kevin-v-ngo** [comment]
> @kevin-v-ngo On the [Third-Party Monitoring tools page](https://deploy-preview-18352--cockroachdb-docs.netlify.app/docs/v23.2/third-party-monitoring-tools.html), should I add 2 additional lines (for Standard and Advanced) in the table for Prometheus, similar to Cloudwatch and Datadog?

Yeah we should. Since not all integrations will be available across the tiers. Is that also the best way to represent this info? We can also do a matrix similar to here: https://docs.google.com/document/d/1PHXAazIgSzNW-RMEV1eXd0UGAQKEBJiX9ulnEiMMQbM/edit#heading=h.lwue2o24rfv

I'll defer to you though.

**Comment by florence-crl** [comment]
@kevin-v-ngo and @rmloveland: Please review [Third-Party Monitoring Integrations](https://deploy-preview-18352--cockroachdb-docs.netlify.app/docs/v23.2/third-party-monitoring-tools.html). I made the following changes:
> (e) re-organized with availability matrix and platform sections, (f) added section for GCP Logging Platform.

The link for Standard for GCP Logging and AWS CloudWatch logs incorrectly go to the Dedicated/Advanced page. I will update the links when I document Export Logs for Standard Clusters in [DOC-8581](https://cockroachlabs.atlassian.net/browse/DOC-8581)

**Review by rmloveland — APPROVED** [review]
LGTM

**Comment by florence-crl** [comment]
I reviewed [Third-Party Monitoring Integrations](https://deploy-preview-18352--cockroachdb-docs.netlify.app/docs/v23.2/third-party-monitoring-tools.html) with @kevin-v-ngo and he approved.

**Pull request merged**
