### PR TITLE
Spring MyBatis Hello World tutorial

### LINKED ISSUE #6040: [Docs] MyBatis Tutorial
Currently, there is no getting started tutorial for this ORM. #7498 includes a tutorial for Spring + MyBatis.

Team: Andrew Woods, Rafi Shamim, Eric Harmeling

### LINKED ISSUE #7737: Add Spring + MyBatis tutorial

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7737. 
Fixes #6040. 
Related to #6046.

This PR includes:

- A simple tutorial on developing a basic Spring Boot application on CRDB with MyBatis-Spring-Boot-Starter.

The code referenced by this tutorial is located here: https://github.com/jeffgbutler/mybatis-cockroach-demo/tree/master/src. 

I made a couple minor changes to the application that are reflected in the .java files in this PR and in the tutorial:
- Added a transaction retry aspect (based on https://github.com/cockroachlabs/roach-data/tree/master/roach-data-jdbc).
- Added transactional annotations to the public methods of the app's service class.

Those changes are reflected in a fork of the repo: https://github.com/ericharmeling/mybatis-cockroach-demo/tree/transaction-retries.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@jeffgbutler 
Would you mind looking over this PR before we publish the tutorial to our public docs site? If you plan to move the code samples to a different repo, please let us know so I can update the links.

Cheers!

**Comment by jeffgbutler** [comment]
I think this looks really good. Couple of things to think about:

1. Do you want to say anything about the tests that use TestContainers? The tests in this example will run immediately without any further command line setup for an external Cockroach instance - which I think is cool.
1. JDBC batch can get complex, so it might not be worth mentioning this. But the batch methods in this example do intermediate commits - that's why there is weird logic around the batch size of 128. If you don't want to do intermediate commits it can be simplified substantially. But I also think I remember reading somewhere that Cockroach likes batch sizes that are powers of 2?
1. I just can't bring myself to put this example code in the MyBatis official repo (sorry about that). Everything else in our repo uses Maven, not Gradle, and this isn't really setup to use our parent POM, fit into the overall project build system, etc. It's easier for me to maintain if I just leave it where it is. Hope that doesn't cause too much anguish.

**Comment by ericharmeling** [comment]
TFTR, @jeffgbutler!

> 1. Do you want to say anything about the tests that use TestContainers? The tests in this example will run immediately without any further command line setup for an external Cockroach instance - which I think is cool.

Although TestContainers does have a [module for Cockroach](https://www.testcontainers.org/modules/databases/cockroachdb/), we can't officially claim beta support with TestContainers at the moment (we're looking into it in the upcoming quarter). So, we probably want to avoid recommending the tool in our docs. Also, in the interest of simplifying things, it's a good idea to avoid introducing additional tooling where possible. Perhaps we should leave it out of the tutorial, but keep it in the repo?

> 2. JDBC batch can get complex, so it might not be worth mentioning this. But the batch methods in this example do intermediate commits - that's why there is weird logic around the batch size of 128. If you don't want to do intermediate commits it can be simplified substantially. But I also think I remember reading somewhere that Cockroach likes batch sizes that are powers of 2?

Batching reads/writes does add more complexity to the sample... but we do call out [using batch writes as a best practice in our docs](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#use-multi-row-insert-statements-for-bulk-inserts-into-existing-tables). And we implement batch inserts in the other Java examples (e.g., e.g., https://www.cockroachlabs.com/docs/v20.1/build-a-java-app-with-cockroachdb.html). And, as you noted, we have a performance recommendation to use batch sizes of 128 (e.g., https://www.cockroachlabs.com/docs/v20.1/build-a-java-app-with-cockroachdb.html#use-a-batch-size-of-128), with some sample logic that is functionally similar to what you have in [`MyBatisAccountService.java`](https://github.com/jeffgbutler/mybatis-cockroach-demo/blob/master/src/main/java/com/example/cockroachdemo/service/MyBatisAccountService.java#L54). I can definitely clarify your sample's batch logic with some prose in the tutorial. 

> 3. I just can't bring myself to put this example code in the MyBatis official repo (sorry about that). Everything else in our repo uses Maven, not Gradle, and this isn't really setup to use our parent POM, fit into the overall project build system, etc. It's easier for me to maintain if I just leave it where it is. Hope that doesn't cause too much anguish.

No worries! Makes total sense. :)

**Comment by jeffgbutler** [comment]
@ericharmeling makes sense about TestContainers. I'll definitely leave it in the repo.

**Comment by ericharmeling** [comment]
> @ericharmeling makes sense about TestContainers. I'll definitely leave it in the repo.

Sounds good!

**Comment by ericharmeling** [comment]
@jeffgbutler After looking into this more, I believe I was wrong about the batch size recommendation extending beyond our JDBC compatibility to other ORMs.

> If you don't want to do intermediate commits it can be simplified substantially.

I think that's a good idea. Please see https://github.com/jeffgbutler/mybatis-cockroach-demo/pull/2 for my attempt at simplifying things.

@lnhsingh 
These code changes won't affect the docs.

**Pull request merged**
