### PR TITLE
Added clarification around duplicate records

### PR DESCRIPTION
**Pull request by kathancox**
FIxes [DOC-2928](https://cockroachlabs.atlassian.net/browse/DOC-2928)

Added clarification on `schema_change = nobackfills` option policy 

Also corrected typo across docs set

### CODE REVIEW

**Comment by kathancox** [comment]
For review:

https://deploy-preview-13273--cockroachdb-docs.netlify.app/docs/dev/use-changefeeds.html#schema-changes-with-column-backfill

https://deploy-preview-13273--cockroachdb-docs.netlify.app/docs/dev/create-changefeed.html#schema-policy

**Review by amruss — APPROVED** [review]
LGTM - thanks!

**Review by andf-crl — COMMENTED** [review]
Thanks! Just a scope question and some minor phrasing suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13273#-:-Mza6b4WD4OYx7D3ltgD:bsgwirn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @kathancox)

___
*[v20.1/create-changefeed.md, line 111 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mz_zrBc4Z_DPkekkh_G:-Mz_zrBc4Z_DPkekkh_H:bs0psav) ([raw file](https://github.com/cockroachdb/docs/blob/fb37bc57d20669972593b933d8e5aeb56b0854fa/v20.1/create-changefeed.md#L111)):*
> ```Markdown
> `compression` | `gzip` | <span class="version-tag">New in v20.1:</span> Compress changefeed data files written to a [cloud storage sink](#cloud-storage-sink). Currently, only [Gzip](https://www.gnu.org/software/gzip/) is supported for compression.
> `protect_data_from_gc_on_pause` | N/A | <span class="version-tag">New in v20.1:</span> When a [changefeed is paused](pause-job.html), ensure that the data needed to [resume the changefeed](resume-job.html) is not garbage collected.<br><br>Note: If you use this option, changefeeds left paused can prevent garbage collection for long periods of time.
> `schema_change_events` | `default` / `column_changes` | <span class="version-tag">New in v20.1:</span> The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> ```

Thanks, nice catch!
___
*[v20.1/create-changefeed.md, line 112 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza6-1xEyEAX2MwsQYG:-Mza6-1xEyEAX2MwsQYH:b-909fjb) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v20.1/create-changefeed.md#L112)):*
> ```Markdown
> `protect_data_from_gc_on_pause` | N/A | <span class="version-tag">New in v20.1:</span> When a [changefeed is paused](pause-job.html), ensure that the data needed to [resume the changefeed](resume-job.html) is not garbage collected.<br><br>Note: If you use this option, changefeeds left paused can prevent garbage collection for long periods of time.
> `schema_change_events` | `default` / `column_changes` | <span class="version-tag">New in v20.1:</span> The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> `schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](change-data-capture.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](change-data-capture.html#schema-changes-with-column-backfill), perform no logical backfills.</li><li>`stop`: [schema changes with column backfill](change-data-capture.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> ```

[ Q ] Is v20.1 also in scope for this ticket?
___
*[v20.2/create-changefeed.md, line 109 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza5lYs5SFSNVaXOj1V:-Mza5lYs5SFSNVaXOj1W:bss34e0) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v20.2/create-changefeed.md#L109)):*
> ```Markdown
> `protect_data_from_gc_on_pause` | N/A |  When a [changefeed is paused](pause-job.html), ensure that the data needed to [resume the changefeed](resume-job.html) is not garbage collected.<br><br>Note: If you use this option, changefeeds left paused can prevent garbage collection for long periods of time.
> `schema_change_events` | `default` / `column_changes` |  The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> `schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills.</li><li>`stop`: [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> ```

[ Q ] Is v20.2 also in scope for this ticket?
___
*[v21.1/create-changefeed.md, line 110 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza1tZT-TEIsimwYbXx:-Mza1tZT-TEIsimwYbXy:boxr1t6) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v21.1/create-changefeed.md#L110)):*
> ```Markdown
> <a name="protect-pause"></a>`protect_data_from_gc_on_pause` | N/A |  When a [changefeed is paused](pause-job.html), ensure that the data needed to [resume the changefeed](resume-job.html) is not garbage collected.<br><br>Note: If you use this option, changefeeds left paused can prevent garbage collection for long periods of time.
> <a name="schema-events"></a>`schema_change_events` | `default` / `column_changes` |  The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> <a name="schema-policy"></a>`schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills. **Note:** Even with this setting, when there are schema changes, a duplicate of the table will still be sent.</li><li>`stop`: [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> ```

I think it'd be safe to include this admonition inline as part of the description, rather than a separate **Note:**. Using "even with" suggests an unexpected result or abnormal behavior, while this is instead desired and purposeful. I found your description of this behavior on `stream-data-out-of-cockroachdb-using-changefeeds.md` to be clear and very helpful (I am new to this feature myself!), what about using that same language here, maybe something like (apologies if I use "emit" wrong here, new usage for me):



_Suggestion:_
```Markdown
For [schema changes with column backfill](stream-data-out-of-cockroachdb-using-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills. The changefeed will still emit any duplicate records for the table being altered, but will not emit the new schema records.
```
___
*[v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza52x5C9hM8tLsQUg_:-Mza52x5C9hM8tLsQUga:bk14d4o) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md#L161)):*
> ```Markdown
> ~~~
> 
> When using the [`schema_change_policy = nobackfill` option](create-changefeed.html#schema-policy), the changefeed will still emit duplicate records for the table that is being altered. In the preceding output, the `# Duplicate` records will still emit with this option, but not the new schema records.
> ```

[ nit ] I could see possible confusion surrounding use of monospace here for a comment. What about something like:



_Suggestion:_
```Markdown
In the preceding output, the records marked as `# Duplicate` will still ...
```
___
*[v21.2/create-changefeed.md, line 120 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza5ICl4zwuTsIq8Xs7:-Mza5ICl4zwuTsIq8Xs8:b-v9xe5n) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v21.2/create-changefeed.md#L120)):*
> ```Markdown
> <a name="protect-pause"></a>`protect_data_from_gc_on_pause` | N/A |  When a [changefeed is paused](pause-job.html), ensure that the data needed to [resume the changefeed](resume-job.html) is not garbage collected.<br><br>Note: If you use this option, changefeeds left paused can prevent garbage collection for long periods of time.
> <a name="schema-events"></a>`schema_change_events` | `default` / `column_changes` |  The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> <a name="schema-policy"></a>`schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills. **Note:** Even with this setting, when there are schema changes, a duplicate of the table will still be sent.</li><li>`stop`: [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> ```

Same [ Note: ] suggestion.
___
*[v21.2/use-changefeeds.md, line 156 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza5OCt1LhL-FaanXK5:-Mza5OCt1LhL-FaanXK6:b-s2b4th) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v21.2/use-changefeeds.md#L156)):*
> ```Markdown
> ~~~
> 
> When using the [`schema_change_policy = nobackfill` option](create-changefeed.html#schema-policy), the changefeed will still emit duplicate records for the table that is being altered. In the preceding output, the `# Duplicate` records will still emit with this option, but not the new schema records.
> ```

Same [ # Duplicate ] suggestion.
___
*[v22.1/create-changefeed.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza5a4G6iuNtTZu7Jxy:-Mza5a4G6iuNtTZu7Jxz:b-lmphaf) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v22.1/create-changefeed.md#L117)):*
> ```Markdown
> <a name="protect-pause"></a>`protect_data_from_gc_on_pause` | N/A |  When a [changefeed is paused](pause-job.html), ensure that the data needed to [resume the changefeed](resume-job.html) is not garbage collected.<br><br>Note: If you use this option, changefeeds left paused can prevent garbage collection for long periods of time.
> <a name="schema-events"></a>`schema_change_events` | `default` / `column_changes` |  The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> <a name="schema-policy"></a>`schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills. **Note:** Even with this setting, when there are schema changes, a duplicate of the table will still be sent.</li><li>`stop`: [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> ```

Same [ Note: ] suggestion
___
*[v22.1/use-changefeeds.md, line 156 at r1](https://reviewable.io/reviews/cockroachdb/docs/13273#-Mza5gLm-eLVzctgTn0T:-Mza5gLm-eLVzctgTn0U:b-wzeyq5) ([raw file](https://github.com/cockroachdb/docs/blob/fa835867d99e0cd5524b3b328ba8fcfbc4ae29b0/v22.1/use-changefeeds.md#L156)):*
> ```Markdown
> ~~~
> 
> When using the [`schema_change_policy = nobackfill` option](create-changefeed.html#schema-policy), the changefeed will still emit duplicate records for the table that is being altered. In the preceding output, the `# Duplicate` records will still emit with this option, but not the new schema records.
> ```

Same [ # Duplicate ] suggestion

**Comment by kathancox** [comment]
Hey @andf-crl, TFTR. I will add the duplicate record into those earlier files since I touched the files anyway (with a find/replace for that typo). Typically, we only update stable version (-1)... unless I would say there is anything egregious or a product change to that specific version. Take a look at "Update Docs Across Versions" on the wiki. I'll make these changes!

**Review by andf-crl — APPROVED** [review]
Thank you! You're absolutely right, thank you for the link. Sorry about that!

Everything else LGTM, just one small optional nit. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13273#-:-MzaUwD60JRfo4AuBsRm:b-q49xj1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @kathancox)

___
*[v20.1/change-data-capture.md, line 137 at r3](https://reviewable.io/reviews/cockroachdb/docs/13273#-MzaVAJf7XxyEJvPhWyf:-MzaVAJf7XxyEJvPhWyg:b4btia6) ([raw file](https://github.com/cockroachdb/docs/blob/58776fb71fc93277e74a53656ced6a788761537f/v20.1/change-data-capture.md#L137)):*
> ```Markdown
> ~~~
> 
> When using the [`schema_change_policy = nobackfill` option](create-changefeed.html#schema-policy), the changefeed will still emit duplicate records for the table that is being altered. In the preceding output, the records marked as `# Duplicate` records will still emit with this option, but not the new schema records.
> ```

[ nit ] safe to remove the second 'records' here. 5x instances in this commit.



_Code snippet:_
```Markdown
the records marked as `# Duplicate` will still ...
```

**Comment by kathancox** [comment]
> Thank you! You're absolutely right, thank you for the link. Sorry about that!
> 
> Everything else LGTM, just one small optional nit. Thank you!
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13273#-:-MzaUwD60JRfo4AuBsRm:b-q49xj1)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @kathancox)
> 
> _[v20.1/change-data-capture.md, line 137 at r3](https://reviewable.io/reviews/cockroachdb/docs/13273#-MzaVAJf7XxyEJvPhWyf:-MzaVAJf7XxyEJvPhWyg:b4btia6) ([raw file](https://github.com/cockroachdb/docs/blob/58776fb71fc93277e74a53656ced6a788761537f/v20.1/change-data-capture.md#L137)):_
> 
> > ```gfm
> > ~~~
> > 
> > When using the [`schema_change_policy = nobackfill` option](create-changefeed.html#schema-policy), the changefeed will still emit duplicate records for the table that is being altered. In the preceding output, the records marked as `# Duplicate` records will still emit with this option, but not the new schema records.
> > ```
> 
> [ nit ] safe to remove the second 'records' here. 5x instances in this commit.
> 
> _Code snippet:_
> 
> ```gfm
> the records marked as `# Duplicate` will still ...
> ```
oooops, thanks!

**Pull request merged**
