### PR TITLE
VPC peering/privatelink clarifications

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes: 
https://cockroachlabs.atlassian.net/browse/CC-3821
https://cockroachlabs.atlassian.net/browse/CC-4282
https://cockroachlabs.atlassian.net/browse/CC-3939

### CODE REVIEW

**Comment by gemma-shay** [comment]
cc: @emily-horing @daniel-crlabs @kannanlakshmi 
Combined these issues as they are pretty small and have crossover. Let me know if anyone wants to review.

**Comment by kannanlakshmi** [comment]
Please add @thtruo as a reviewer as he worked on the feature. Thanks!

**Review by thtruo — CHANGES_REQUESTED** [review]
Thanks! @gemma-shay these look great! I have just one straightforward suggestion - once that's addressed the whole thing will look good to me 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10683#-:-MbDe6lq0noDdAoFX4Xt:bxhf7of)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/network-authorization.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/10683#-MbDdXj09F13EjCd2NVb:-MbDdXj17eQUuKkd5unL:b-3igk8a) ([raw file](https://github.com/cockroachdb/docs/blob/49ddddbcaec73c59a1c68ad565063396e89321f9/cockroachcloud/network-authorization.md#L32)):*
> ```
> To set up VPC peering for existing clusters created after March 5, 2020, [contact us](https://support.cockroachlabs.com/hc/en-us/requests/new).
> ```

I think we can cut this sentence out directly. 

For context: In the old version of the docs, the "contact us" option was meant to smooth over cases where users wanted to set up VPC peering for clusters made _before_ March 5 2020. Now that you've explicitly called out this date (and given that it's been over a year and we rarely get support requests), I'd vote for cutting out this sentence

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10683)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @thtruo)

___
*[cockroachcloud/network-authorization.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/10683#-MbDdXj09F13EjCd2NVb:-MbIYM8w5dO3SoT6KEyK:be7up05) ([raw file](https://github.com/cockroachdb/docs/blob/49ddddbcaec73c59a1c68ad565063396e89321f9/cockroachcloud/network-authorization.md#L32)):*
<details><summary><i>Previously, thtruo (Tommy) wrote…</i></summary><blockquote>

> ```
> To set up VPC peering for existing clusters created after March 5, 2020, [contact us](https://support.cockroachlabs.com/hc/en-us/requests/new).
> ```

I think we can cut this sentence out directly. 

For context: In the old version of the docs, the "contact us" option was meant to smooth over cases where users wanted to set up VPC peering for clusters made _before_ March 5 2020. Now that you've explicitly called out this date (and given that it's been over a year and we rarely get support requests), I'd vote for cutting out this sentence
</blockquote></details>

Updated it to say this:
`If your cluster was deployed without VPC peering enabled, you will have to [create a new cluster](create-your-cluster.html) with VPC peering enabled, then [export your data](backups-page.html) from the old cluster to the new cluster.`
Does that make more sense, since whether you created your cluster before or after March 5, 2020, I assume you would have to follow the same steps and create a new cluster?

**Review by thtruo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10683)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @thtruo)

___
*[cockroachcloud/network-authorization.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/10683#-MbDdXj09F13EjCd2NVb:-MbImYIBApN4FHSJDTiG:b-ck6l1q) ([raw file](https://github.com/cockroachdb/docs/blob/49ddddbcaec73c59a1c68ad565063396e89321f9/cockroachcloud/network-authorization.md#L32)):*
@gemma-shay I'd actually clarify it as something along the lines of this (I think the date is important to call out):

> Self-service VPC peering setup is not supported for CockroachCloud clusters deployed before March 5, 2020. If your cluster was deployed before March 5, 2020 you will have to create a new cluster with VPC peering enabled, then export your data from the old cluster to the new cluster. If your cluster was deployed on or after March 5, 2020 it will be locked into the default CIDR range chosen by CockroachCloud unless you explicitly configured a different IP range during the cluster creation step. 

The reason for this is that, for CC clusters created on/after March 5, we will assign the default CIDR range for all GCP clusters for VPC peering even if the user does not explicitly toggle the VPC peering option to "yes" during the cluster creation process. Whether the user toggles the VPC peering setting to "yes" or "no" in the cluster creation process, that cluster will use the default CIDR range for VPC peering. However, only when the user explicit enters their own IP range does this override the default.

Lemme know if you need more clarity around this - this is a tricky one so I prefer explicit language in this alert.

**Review by thtruo — APPROVED** [review]
Nice @gemma-shay I took a peak at f0c98a3 - this LGTM! 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10683#-:-MbbivOH1ttyytMwjSDb:bf5sho6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

**Review by thtruo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10683#-:-Mbbj7L6B5pKQPnLv5O_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay)

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
