### PR TITLE
DOC-3279 add VIEWCLUSTERSETTING role

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-3279
CRDB Commit: [#76012](https://github.com/cockroachdb/cockroach/pull/76012)

- Added new `VIEWCLUSTERSETTING` role/user to `CREATE | ALTER ... USER | ROLE` documentation
- Updated *Required privileges* section on `SHOW CLUSTER SETTINGS` reference page to include new `VIEWCLUSTERSETTING` role option.
- Alphabetized `v22.1/alter-user.md`. Other three pages were already alphabetized, this just brings `alter-user.md` in line.
- Standardized `v22.1/alter-user.md` to use `role option` over `parameter`.  Other three pages already use `role option`, this just brings `alter-user.md` in line.
- Standardized all references to `admin` role to use monospace.

Staging: [alter-user](https://deploy-preview-13653--cockroachdb-docs.netlify.app/docs/dev/alter-user.html#parameters) | [create-user](https://deploy-preview-13653--cockroachdb-docs.netlify.app/docs/dev/create-user.html#role-options) | [alter-role](https://deploy-preview-13653--cockroachdb-docs.netlify.app/docs/dev/alter-role.html#role-options) | [create-role](https://deploy-preview-13653--cockroachdb-docs.netlify.app/docs/dev/create-role.html#role-options) | [show-cluster-setting](https://deploy-preview-13653--cockroachdb-docs.netlify.app/docs/dev/show-cluster-setting.html#required-privileges)

### CODE REVIEW

**Review by koorosh — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13653)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andf-crl)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0AKexi8-syV8pBx4fR:-N0AKexj7dv7WEzRgyoP:bnfp4nl) (no related file):*
:lgtm:

---

**Review by taroface — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13653)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andf-crl)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0AKexi8-syV8pBx4fR:-N0XoA9b-sZU2euXcVy9:bnoz84m) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

:lgtm:
</blockquote></details>

Some formatting comments.

---
___
*[`v22.1/alter-role.md` line 62 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0XGDnv95pdDYBfn5vO:-N0XGDnv95pdDYBfn5vP:bewokuj) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-role.md#L62)):*
> ```Markdown
> `VALID UNTIL` |  The date and time (in the [`timestamp`](timestamp.html) format) after which the [password](#parameters) is not valid.
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [Statements](ui-statements-page.html) and [Transactions](ui-transactions-page.html) pages in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data and the DB Console pages are unavailable. If a user has the `VIEWACTIVITYREDACTED` role, they will be able to see DB Console pages. <br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTINGS` or to access the **Cluster Settings** page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> ```

We should link to reference docs where possible. This page is accessed via Advanced Debug: https://www.cockroachlabs.com/docs/v22.1/ui-debug-pages.html 



_Suggestion:_
```Markdown
**Cluster Settings** page
```
___
*[`v22.1/alter-user.md` line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xmmua1kCRGN8v3u1d:-N0Xmmub--xLAan8oSz6:b-tkrquz) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L37)):*
> ```Markdown
> ----------|-------------
> `name` | The name of the user whose role options you want to alter.
> `CANCELQUERY`/`NOCANCELQUERY` | Allow or disallow the user to cancel [queries](cancel-query.html) and [sessions](cancel-session.html) of other users. Without this privilege, users can only cancel their own queries and sessions. Even with this privilege, non-admins cannot cancel admin queries or sessions. This option should usually be combined with `VIEWACTIVITY` so that the user can view other users' query and session information. <br><br>By default, the role option is set to `NOCANCELQUERY` for all non-`admin` users.
> ```

Nit: have all instances of "admin" in code ticks.
___
*[`v22.1/alter-user.md` line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xn0XT92lAXfpeTKAM:-N0Xn0XU4FV6kqESt3LM:bqbwks1) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L37)):*
> ```Markdown
> ----------|-------------
> `name` | The name of the user whose role options you want to alter.
> `CANCELQUERY`/`NOCANCELQUERY` | Allow or disallow the user to cancel [queries](cancel-query.html) and [sessions](cancel-session.html) of other users. Without this privilege, users can only cancel their own queries and sessions. Even with this privilege, non-admins cannot cancel admin queries or sessions. This option should usually be combined with `VIEWACTIVITY` so that the user can view other users' query and session information. <br><br>By default, the role option is set to `NOCANCELQUERY` for all non-`admin` users.
> ```

Maybe this should be (I'm assuming) "Even with the `CANCELQUERY` privilege" for clarity.



_Code quote:_
```Markdown
Even with this privilege
```
___
*[`v22.1/alter-user.md` line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xn8cI2mtTBAKSZlZx:-N0Xn8cI2mtTBAKSZlZy:bt36aue) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L39)):*
> ```Markdown
> `CANCELQUERY`/`NOCANCELQUERY` | Allow or disallow the user to cancel [queries](cancel-query.html) and [sessions](cancel-session.html) of other users. Without this privilege, users can only cancel their own queries and sessions. Even with this privilege, non-admins cannot cancel admin queries or sessions. This option should usually be combined with `VIEWACTIVITY` so that the user can view other users' query and session information. <br><br>By default, the role option is set to `NOCANCELQUERY` for all non-`admin` users.
> `CONTROLCHANGEFEED`/`NOCONTROLCHANGEFEED` | Allow or disallow the user to run [`CREATE CHANGEFEED`](create-changefeed.html) on tables they have `SELECT` privileges on. <br><br>By default, the role option is set to `NOCONTROLCHANGEFEED` for all non-`admin` users.
> `CONTROLJOB`/`NOCONTROLJOB` | Allow or disallow the user to [pause](pause-job.html), [resume](resume-job.html), and [cancel](cancel-job.html) jobs. non-`admin` users cannot control jobs created by admins. <br><br>By default, the role option is set to `NOCONTROLJOB` for all non-`admin` users.
> ```

Nit: capitalize



_Code quote:_
```Markdown
non
```
___
*[`v22.1/alter-user.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0XnLqgDg90qGOzhyCF:-N0XnLqgDg90qGOzhyCG:bdfl7xv) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L42)):*
> ```Markdown
> `CREATEDB`/`NOCREATEDB` | Allow or disallow the user to [create](create-database.html) or [rename](rename-database.html) a database. The user is assigned as the owner of the database. <br><br>By default, the role option is set to `NOCREATEDB` for all non-`admin` users.
> `CREATELOGIN`/`NOCREATELOGIN` | Allow or disallow the user to manage authentication using the `WITH PASSWORD`, `VALID UNTIL`, and `LOGIN/NOLOGIN` parameters. <br><br>By default, the role option is set to `NOCREATELOGIN` for all non-`admin` users.
> `CREATEROLE`/`NOCREATEROLE` |  Allow or disallow the user to [create](create-user.html), alter, and [drop](drop-user.html) other non-`admin` users. <br><br>By default, the role option is set to `NOCREATEROLE` for all non-`admin` users.
> ```

Link to alter-user.html



_Code quote:_
```Markdown
alter
```
___
*[`v22.1/alter-user.md` line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0XnRJu7d84IggzGzbL:-N0XnRJu7d84IggzGzbM:bmcgm72) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L48)):*
> ```Markdown
> `VALID UNTIL` |  The date and time (in the [`timestamp`](timestamp.html) format) after which the password is not valid.
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other users' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and **Transactions** pages in the DB Console. Without this privilege, the `SHOW` commands only show the user's own data and the DB Console pages are unavailable. <br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` users.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow the user to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTINGS`, and to access the **Cluster Settings** page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` users.
> ```

Same comment as earlier re: linking to Advanced Debug page
___
*[`v22.1/create-role.md` line 78 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xo2fj6PsWLAXJrLyh:-N0Xo2fj6PsWLAXJrLyi:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/create-role.md#L78)):*
> ```Markdown
> `VALID UNTIL` |  The date and time (in the [`timestamp`](timestamp.html) format) after which the [password](#parameters) is not valid.
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [Statements](ui-statements-page.html) and [Transactions](ui-transactions-page.html) pages in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data and the DB Console pages are unavailable. If a user has the `VIEWACTIVITYREDACTED` role, they will be able to see DB Console pages. <br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTINGS` or to access the **Cluster Settings** page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> ```

Ditto
___
*[`v22.1/create-user.md` line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xo4u5-WD6tM6eT4hC:-N0Xo4u5-WD6tM6eT4hD:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/create-user.md#L68)):*
> ```Markdown
> `VALID UNTIL` |  The date and time (in the [`timestamp`](timestamp.html) format) after which the [password](#parameters) is not valid.
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [Statements](ui-statements-page.html) and [Transactions](ui-transactions-page.html) pages in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data and the DB Console pages are unavailable. If a user has the `VIEWACTIVITYREDACTED` role, they will be able to see DB Console pages. <br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTINGS` or to access the **Cluster Settings** page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> ```

Ditto

**Review by andf-crl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andf-crl, @koorosh, and @taroface)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0AKexi8-syV8pBx4fR:-N0adnXF2Xt7RlX0xOml:b-583c0e) (no related file):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Some formatting comments.
</blockquote></details>

Thanks Ryan, I've folded in your feedback with some comments. In addition, I've:
- Further standardized on `the role` --> `a user` to match language throughout; most changes to `create-user.html`

---
___
*[`v22.1/alter-role.md` line 61 at r2](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0acsuz2lXzWYmrn6Lv:-N0acsuz2lXzWYmrn6Lw:b-8kgc26) ([raw file](https://github.com/cockroachdb/docs/blob/0472d8ff7cc513ce4d72b4d9dba581a79e71e537/v22.1/alter-role.md#L61)):*
> ```Markdown
> `SQLLOGIN`/`NOSQLLOGIN` | Allow or disallow a role to log in using the SQL CLI with one of the [client authentication methods](authentication.html#client-authentication). The role option to `NOSQLLOGIN` prevents the role from logging in using the SQL CLI with any authentication method while retaining the ability to log in to DB Console. It is possible to have both `NOSQLLOGIN` and `LOGIN` set for a role and `NOSQLLOGIN` takes precedence on restrictions. <br><br>Without any role options all login behavior is permitted.
> `VALID UNTIL` |  The date and time (in the [`timestamp`](timestamp.html) format) after which the [password](#parameters) is not valid.
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> ```

This was a test to see the effect of `rebase` on ongoing reviews on Reviewable. I suspected as much. Please excuse the presence of out-of-commit changes here, I now understand the proper order of operations: rebase to be run only post-review && pre-merge.

The commit diff itself is unaffected by this: this change is only present in Reviewable.
___
*[`v22.1/alter-user.md` line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xn0XT92lAXfpeTKAM:-N0a_mFdCFj42CfykKWu:balmawx) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L37)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Maybe this should be (I'm assuming) "Even with the `CANCELQUERY` privilege" for clarity.
</blockquote></details>

Good clarification. Further clarified to `role`, as privileges are discrete concepts, defined elsewhere.
___
*[`v22.1/alter-user.md` line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0Xmmua1kCRGN8v3u1d:-N0aatDJ8X1DLuNwHXWj:b3zuhe7) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L37)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: have all instances of "admin" in code ticks.
</blockquote></details>

Done. Some instances required minor rephrasing e.g., "non-`admin`s" --> "non-`admin` users / roles".
___
*[`v22.1/alter-user.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0XnLqgDg90qGOzhyCF:-N0aa4T22eCWSnhZokbr:b-gk4ivs) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L42)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Link to alter-user.html
</blockquote></details>

I have done this on all 4 ... but we are linking to the page we are already on in these cases. How does this help the user?

Further:
- Did the same for unlinked `create`
- Standardized each to link to `role` | `user` depending on which `*-role.html ` | `*-user.html` page we are on.

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andf-crl, @koorosh, and @taroface)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0AKexi8-syV8pBx4fR:-N0l1V_s855Zs67YMu2Q:b-54200k) (no related file):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

Thanks Ryan, I've folded in your feedback with some comments. In addition, I've:
- Further standardized on `the role` --> `a user` to match language throughout; most changes to `create-user.html`
</blockquote></details>

LGTM with one comment about `alter-user.html` - my mistake!

---
___
*[`v22.1/alter-user.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/13653#-N0XnLqgDg90qGOzhyCF:-N0l1N6P7S9R5Y5mJQaS:b-4u43zl) ([raw file](https://github.com/cockroachdb/docs/blob/c9750739a60c534e3b9172216305f4ab81990fb3/v22.1/alter-user.md#L42)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

I have done this on all 4 ... but we are linking to the page we are already on in these cases. How does this help the user?

Further:
- Did the same for unlinked `create`
- Standardized each to link to `role` | `user` depending on which `*-role.html ` | `*-user.html` page we are on.
</blockquote></details>

Ah, I missed that this is already `alter-user.html`. I agree it's unnecessary. Please disregard that suggestion!

**Pull request merged**
