### PR TITLE
Updated privileges on SHOW SCHEMAS, SHOW TABLES, and SHOW TYPES

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/docs/issues/5118.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@roncrdb

**Comment by roncrdb** [comment]
@ericharmeling might also want to get clarification if SHOW TYPES and SHOW TABLES also need privileges on a DB in order to return.

**Comment by ericharmeling** [comment]
@roncrdb 

> might also want to get clarification if SHOW TYPES and SHOW TABLES also need privileges on a DB in order to return.

Done.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8768#-:-MKu8PJuETQFXytJ1vwM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Pull request merged**
