### PR TITLE
DOC-2868: Add first-level references to modified includes in Changed Files bot

### PR DESCRIPTION
**Pull request by nickvigilante**
Fixes DOC-2868:

- First-level references to includes will display a link to the pages on which that modified include is referenced

### CODE REVIEW

**Comment by stbof** [comment]
> Fixes [DOC-2868](https://cockroachlabs.atlassian.net/browse/DOC-2868):
> 
> * First-level references to includes will display a link to the pages on which that modified include is referenced

I'm still not following this. Where is the link displayed?

**Comment by ianjevans** [comment]
> I'm still not following this. Where is the link displayed?

Look in the Files Changed comment above.

**Comment by ianjevans** [comment]
Looks really good, Nick. This should help with reviews, and for sanity-checking changes to `_include` files as well.

**Review by ianjevans — APPROVED** [review]
Just remove the test strings, and this is ready to merge.

**Pull request merged**
