### PR TITLE
Fix scrollbar on Chrome

### PR DESCRIPTION
**Pull request by yingzhuchin**
Makes scrollbar visible on Chrome

Fixes issue #5029

### CODE REVIEW

**Comment by yingzhuchin** [comment]
Hi @jseldess, I looked at http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e23402969be2c33d336bc8ab2f663769b9114ec8/stable/architecture/transaction-layer.html, taken from your previous example on https://github.com/cockroachdb/docs/pull/6420. I'm on Chrome Version 83.0.4103.97 and I see one scrollbar even when the TOC is long. Does that match what you're seeing?

**Comment by jseldess** [comment]
@yingzhuchin, scrollbars are still not showing up correctly for me. In this screenshot, for example, you can see there are two scrollbars next to the toc and when you scroll the main content, you see a third one all the way to the right (whereas I'd expect it directly to the right of the main body...

Screen Shot 2020-06-09 at 5 48 11 PM

**Comment by yingzhuchin** [comment]
Could you let me know which browser and what version? I'm unable to reproduce unfortunately.

**Comment by jseldess** [comment]
Sure: Screen Shot 2020-06-09 at 6 11 17 PM

**Comment by yingzhuchin** [comment]
Hi @jseldess, the latest preview shows scrollbars working correctly for TOCs. What do you think? 

Unfortunately the main scrollbar cannot be between the page content and the TOC at this point, because not all pages have TOCs, and any TOCs that are present are generated dynamically by Javascript. See #1696.

**Pull request merged**
