### PR TITLE
Update getting started docs

### LINKED ISSUE #1403: Restarting a local cluster
Our Start a Local Cluster tutorial shows how to stop a three-node local cluster but not how to restart it. Users tend to like to do that, but when they following the initial start steps, they can get tripped up by the fact that the cluster doesn't respond until 2 of the 3 nodes are back online (a quorum). 

See https://github.com/cockroachdb/cockroach/issues/15889.

### PR DESCRIPTION
**Pull request by jseldess**
- Update all getting started tutorials to:
  - start nodes in distinct terminals (no use of `--background`) 
  - stop nodes via `CTRL + D` 
  - show command for removing data stores
- In `start-a-local-cluster.md` and `secure-a-cluster.md`:
  - add a step for restarting the cluster
  - update admin ui screenshots
  - include an insecure/secure toggle to encourage users to start with secure, if they're so inclined, or at least to see the differences

Fixes #1403

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1472)

### CODE REVIEW

**Comment by jseldess** [comment]
@a-robinson, @bdarnell, before updating all of the get started scenarios to more intuitively accommodate cluster restarts, I'm starting with the `Start a Cluster` from binary page. PTAL.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[start-a-local-cluster.md, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlA6dLSneiD2vVwfQnF:-KlA6dLSneiD2vVwfQnG:bb1z8y2) ([raw file](https://github.com/cockroachdb/docs/blob/9b116956f1fff3478392fe78427b85ce8ff3f3d8/start-a-local-cluster.md#L171)):*
> ```Markdown
> ## Step 5.  Stop the cluster
> 
> Once you're done with your test cluster, open a new terminal and stop the first node:
> ```

Since everything's running in the foreground of separate terminals, the simplest way to stop them is to switch back to the terminal running the node and type ctrl-c. (you can do this twice on the last one to avoid waiting for the 1-minute timeout)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-:-KlA73O-JGczaQ3ed8e0:bnfp4nl)*

**Comment by jseldess** [comment]
*[start-a-local-cluster.md, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlA6dLSneiD2vVwfQnF:-KlL7blRgMJBuHDFgRsm:b-wlci8v) ([raw file](https://github.com/cockroachdb/docs/blob/9b116956f1fff3478392fe78427b85ce8ff3f3d8/start-a-local-cluster.md#L171)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Since everything's running in the foreground of separate terminals, the simplest way to stop them is to switch back to the terminal running the node and type ctrl-c. (you can do this twice on the last one to avoid waiting for the 1-minute timeout)
</blockquote></details>

I went with `cockroach quit` more for educational purposes, since it seems a good opportunity to call out that command. But the approach you recommend is much simpler, it's true. I'm happy to go that way, if that's what you'd prefer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[start-a-local-cluster.md, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlA6dLSneiD2vVwfQnF:-KlPOhpQ0DKvYqQGSKYn:blsms7h) ([raw file](https://github.com/cockroachdb/docs/blob/9b116956f1fff3478392fe78427b85ce8ff3f3d8/start-a-local-cluster.md#L171)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I went with `cockroach quit` more for educational purposes, since it seems a good opportunity to call out that command. But the approach you recommend is much simpler, it's true. I'm happy to go that way, if that's what you'd prefer.
</blockquote></details>

My feeling is I'd rather teach people about `kill` and `ctrl-c` (if they don't already know - this is fairly common knowledge) since it's a transferable skill, unlike the specialized `cockroach quit` (which introduces a lot of new failure modes since it requires the network and certificates). Real-world deployments are going to use some sort of orchestration or process manager which will work more naturally with a signal-based shutdown protocol.

I'd almost say that `cockroach quit` and `cockroach start --background` were mistakes - they're legitimately useful in a few narrow situations (scripting single-node test setups without a polling loop), but they shouldn't be a part of the normal flow of managing a cluster. Better to use the standard unix tools of `kill` and shell-level backgrounding. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472)*

**Comment by jseldess** [comment]
*[start-a-local-cluster.md, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlA6dLSneiD2vVwfQnF:-KlPX-GFIh2yrMP0KXpZ:b-wjuecb) ([raw file](https://github.com/cockroachdb/docs/blob/9b116956f1fff3478392fe78427b85ce8ff3f3d8/start-a-local-cluster.md#L171)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

My feeling is I'd rather teach people about `kill` and `ctrl-c` (if they don't already know - this is fairly common knowledge) since it's a transferable skill, unlike the specialized `cockroach quit` (which introduces a lot of new failure modes since it requires the network and certificates). Real-world deployments are going to use some sort of orchestration or process manager which will work more naturally with a signal-based shutdown protocol.

I'd almost say that `cockroach quit` and `cockroach start --background` were mistakes - they're legitimately useful in a few narrow situations (scripting single-node test setups without a polling loop), but they shouldn't be a part of the normal flow of managing a cluster. Better to use the standard unix tools of `kill` and shell-level backgrounding. 
</blockquote></details>

Got it. I'll just go with `ctrl-c`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472)*

**Comment by sploiselle** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[secure-a-cluster.md, line 2 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlVDYTuNdsYfd8Eca2N:-KlVDYTuNdsYfd8Eca2O:b-kyp16x) ([raw file](https://github.com/cockroachdb/docs/blob/4a4615017acf60048c02568792469b1e8b3fdb77/secure-a-cluster.md#L2)):*
> ```Markdown
> ---
> title: Secure a Cluster
> ```

"Secure a Cluster" sounds like it will show you "how to secure a cluster." I recommend changing the title to something more aligned with the procedure like "Start a Local Secure Cluster." Renaming the file and links to it would probably be a good idea, as well.

---

*[start-a-local-cluster.md, line 2 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlVEl83i1qtYNl9NflU:-KlVEl84QSuwEvRy43Bs:bjv28t) ([raw file](https://github.com/cockroachdb/docs/blob/4a4615017acf60048c02568792469b1e8b3fdb77/start-a-local-cluster.md#L2)):*
> ```Markdown
> ---
> title: Start a Cluster
> ```

I'd change the title of this page to reflect the file, as well as what the user actually accomplishes here, Start a Local Cluster

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472)*

**Comment by jseldess** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[secure-a-cluster.md, line 2 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlVDYTuNdsYfd8Eca2N:-KlZ16noRHO130bPJIQz:b3co8fn) ([raw file](https://github.com/cockroachdb/docs/blob/4a4615017acf60048c02568792469b1e8b3fdb77/secure-a-cluster.md#L2)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

"Secure a Cluster" sounds like it will show you "how to secure a cluster." I recommend changing the title to something more aligned with the procedure like "Start a Local Secure Cluster." Renaming the file and links to it would probably be a good idea, as well.
</blockquote></details>

Good point. I've updated the page titles:
- `Start a Local Cluster (Insecure)`
- `Start a Local Cluster (Secure)`

I've updated the sidenav as well.

But since there's a [link to `secure-a-cluster.html`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L587) from cockroach, I don't want to change the filename yet. We should probably put a redirect in place first, then change the filename, and then update cockroach (which would probably go into 1.1). I'll open a follow-up issue.

---

*[start-a-local-cluster.md, line 2 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-KlVEl83i1qtYNl9NflU:-KlZ2IZU0w7KUDZ9ERh4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4a4615017acf60048c02568792469b1e8b3fdb77/start-a-local-cluster.md#L2)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

I'd change the title of this page to reflect the file, as well as what the user actually accomplishes here, Start a Local Cluster
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472)*

**Comment by sploiselle** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1472#-:-KlZBC_WVP7j0nS5FfR0:bnfp4nl)*

**Pull request merged**
