### PR TITLE
DOC-1607: Correct RN for #64004

### PR DESCRIPTION
**Pull request by nickvigilante**
Fixes DOC-1607

### CODE REVIEW

**Comment by nickvigilante** [comment]
@jordanlewis Just touching base again. Are you able to review this for me?

**Comment by jordanlewis** [comment]
Hi, sorry I've been on PTO returning next week. It looks good to me, thanks!

**Comment by nickvigilante** [comment]
I'm so sorry for bothering you. Should have checked Slack first. Thank you!

**Comment by nickvigilante** [comment]
@gemma-shay TFTR!

**Pull request merged**
