### PR TITLE
Use consistent time ranges. Make description agree with Explain output. Include stats.

### PR DESCRIPTION
**Pull request by stbof**
https://cockroachlabs.atlassian.net/browse/DOC-888
https://cockroachlabs.atlassian.net/browse/DOC-908
https://cockroachlabs.atlassian.net/browse/DOC-909

### CODE REVIEW

**Comment by rmloveland** [comment]
Hi @stbof can you please remove me and re-add me once the technical review is done?  Otherwise I may forget to revisit after that step - also would rather not get all the emails etc until it's ready for docs review. Thanks!

**Comment by stbof** [comment]
> Hi @stbof can you please remove me and re-add me once the technical review is done? Otherwise I may forget to revisit after that step - also would rather not get all the emails etc until it's ready for docs review. Thanks!

Sorry for all the spam.

**Review by Lukens4242 — APPROVED** [review]
Looks good.  Thanks.

**Review by lin-crl — APPROVED** [review]
LGTM

**Review by rmloveland — COMMENTED** [review]
LGTM @stbof , thanks for updating this!

**Pull request merged**
