### PR TITLE
Change cdc azure cloud storage scheme from azure-blob:// to azure://

### PR DESCRIPTION
**Pull request by kathancox**
Fixes DOC-10269

### CODE REVIEW

**Comment by kathancox** [comment]
cc @awoods187

**Review by awoods187 — APPROVED** [review]
LGTM

**Review by rmloveland — APPROVED** [review]
LGTM from a docs POV

**Review by rharding6373 — APPROVED** [review]
LGTM, thank you!

**Comment by kathancox** [comment]
TFTRs!

**Pull request merged**
