### PR TITLE
Updating required Go version for build from source

### PR DESCRIPTION
**Pull request by jseldess**
Fixes https://github.com/cockroachdb/cockroach/issues/7206

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/381)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM
@tamird: you tend to be the one to upgrade Go. Could you tag those PRs as "docs update required"?

**Comment by tamird** [comment]
Sure.

**Comment by tamird** [comment]
LGTM but also would be good to not mention this version verbatim. Perhaps we could link to https://github.com/cockroachdb/cockroach/blob/master/.go-version

**Comment by jseldess** [comment]
As mentioned in https://github.com/cockroachdb/cockroach/pull/7214, I'll work on redirecting people from CONTRIBUTING.md to this page so we only have one file to keep up.

**Pull request merged**
