### PR TITLE
v20.2.0-rc.2 Release Notes

### LINKED ISSUE #8636: v20.2.0-rc.2 Release Notes
Prep date: 10/13/20
Release date: 10/20/20
SHA: `9fe9b6d95e858d9f7d65d9fd661311a88d9daaf2 `
Release Manager: Lucy
Issue: https://github.com/cockroachdb/cockroach/issues/55525

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [x] Run script to generate release notes
- [x] Update docs site
- [x] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8636

### CODE REVIEW

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @taroface)

___
*[releases/v20.2.0-rc.2.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0doLc077gzds6k5Fi:-MK0doLc077gzds6k5Fj:b6a1r7y) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L42)):*
> ```Markdown
> ### Backward-incompatible changes
> 
> - The Docker image is now based on RedHat's ubi8/ubi-minimal image (instead of ubi8/ubi). This image is smaller. [#55519][#55519]
> ```

`UBI` should be capitalized, it seems: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image
___
*[releases/v20.2.0-rc.2.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0dv0lB017yb6ghkAu:-MK0dv0lB017yb6ghkAv:b-wjz1mg) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L47)):*
> ```
> ../v20.2//enum.html
> ```

Extra slash in the URL

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @taroface)

___
*[releases/v20.2.0-rc.2.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0doLc077gzds6k5Fi:-MK0kvGk5H8mcyOUZlJc:b-qp07dk) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L42)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

`UBI` should be capitalized, it seems: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image
</blockquote></details>

I think it can be UBI8 or ubi8/ubi-minimal. @jlinder is this current capitalization or should it be changed?
___
*[releases/v20.2.0-rc.2.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0dv0lB017yb6ghkAu:-MK0lB4B6cLldjNfUOds:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L47)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> ../v20.2//enum.html
> ```

Extra slash in the URL
</blockquote></details>

Done.

**Review by jlinder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[releases/v20.2.0-rc.2.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0doLc077gzds6k5Fi:-MK0mtxEDA7rgzrgt3oQ:btaxgz) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L42)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think it can be UBI8 or ubi8/ubi-minimal. @jlinder is this current capitalization or should it be changed?
</blockquote></details>

I think this is good as is. When saying the specific image, it's `ubi8/ubi-minimal` or `ubi8/ubi` (which are two different base images). RedHat UBI 8 is an umbrella term that refers to a family of images that include those two specific images. You can see the image names further down the page @taroface pointed at.

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[releases/v20.2.0-rc.2.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0doLc077gzds6k5Fi:-MK0pcnK2f0uckMtwxt5:b-69gm0l) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L42)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

I think this is good as is. When saying the specific image, it's `ubi8/ubi-minimal` or `ubi8/ubi` (which are two different base images). RedHat UBI 8 is an umbrella term that refers to a family of images that include those two specific images. You can see the image names further down the page @taroface pointed at.
</blockquote></details>

I should have taken a closer look. Thanks for clarifying!

**Review by jlinder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8704)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[releases/v20.2.0-rc.2.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/8704#-MK0doLc077gzds6k5Fi:-MK0q1Np4wAlPdYgyodO:bpvfsj4) ([raw file](https://github.com/cockroachdb/docs/blob/539cb537dddaaf629a08f5d29116694b9c601519/releases/v20.2.0-rc.2.md#L42)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I should have taken a closer look. Thanks for clarifying!
</blockquote></details>

No worries. Thanks for checking!

**Pull request merged**
