### PR TITLE
generate: vendor generator deps

### PR DESCRIPTION
**Pull request by dt**
the generator script is pretty simple and only depends on a couple external libs.
given our experience in the main repo, no fancy submodules or glide here -- just
a folder with a few deps in it.

Note that we're not vendoring everything depended on, since obviously we depend on
cockroachdb/cockroach but want to use the current version checked out in GOPATH.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/916)

### CODE REVIEW

**Comment by dt** [comment]
@mjibson should we consider moving the generator code to cockroach/cockroach (and just having it write to ../docs/.. by default)?

**Comment by jseldess** [comment]
@dt, can you help me understand this change generally and how it will affect auto-generating sql diagrams and functions.

**Comment by dt** [comment]
@jseldess basically the generator go code makes use of a couple external libraries (mostly for parsing the command line parameters). Currently, when `go` tries to run the generator, needs the user to have those libraries installed in their GOPATH, at the version that the generator is compatible with -- if they don't have it installed there, or another project they work on has installed a different version, they can't run the generator. This change puts copies of the libraries we use in the generator where `go` will find them, before it looks in `GOPATH`, so if someone just checks out this repo, they don't need to also have the other libraries installed at particular versions elsewhere on their system.

**Comment by mjibson** [comment]
I think it's fine to stay here, unless there is some workflow or other problem that moving it to the main repo would solve. Being here makes it a bit easier to change, even though it does get out of sync with the main repo once in a while.

**Comment by jseldess** [comment]
Thanks for the explanation, @dt. LGTM, too.

**Pull request merged**
