### PR TITLE
[DOC-4750] Document kv.allocator.recovery_store_selector cluster setting

### PR DESCRIPTION
**Pull request by mdlinville**
[DOC-4750]

Relates to https://github.com/cockroachdb/cockroach/commit/3ce0fd5483a6bf3d4a5102da9cf9775904f5c572#diff-0ef17f0a19fa72bb8e62ee9059086c15959d49920b702da3f8d1aa2659cc225eR90

## Previews
[v22.2/node-shutdown.md](https://deploy-preview-15615--cockroachdb-docs.netlify.app/docs/v22.2/node-shutdown.html)

## Tests
- [x] Local build
- [x] Linkcheck

### CODE REVIEW

**Review by rmloveland — APPROVED** [review]
LGTM modulo technical review

**Review by AlexTalks — CHANGES_REQUESTED** [review]
Left a couple comments in line.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15615#-:-NHRUDEkAEjEp4sWDiS5:bif0zz2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mdlinville)

___
*[`v22.2/node-shutdown.md` line 206 at r1](https://reviewable.io/reviews/cockroachdb/docs/15615#-NHRU9YB5NyVyCQxm2Zx:-NHRU9YB5NyVyCQxm2Zy:b26zqjl) ([raw file](https://github.com/cockroachdb/docs/blob/b7b4d5740124b5f3b7d7744263a5208b059ffe88/v22.2/node-shutdown.md#L206)):*
Small correction:
> When a node is <strike>rebalancing</strike> **dead or decommissioning and** all of its range replicas **are being upreplicated** onto other nodes...

It may also be worth clarifying that "all eligible nodes" really means "the nodes that satisfy all constraints" - I.e., for both "good" and "best" settings, the node chosen will satisfy all available constraints for replica placement and survivability; however if "good" is selected instead of "best", it will not consider range count balance in its selection, as you described.

**Review by mdlinville — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[`v22.2/node-shutdown.md` line 206 at r1](https://reviewable.io/reviews/cockroachdb/docs/15615#-NHRU9YB5NyVyCQxm2Zx:-NHRW00I7fmDUlEQswRX:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b7b4d5740124b5f3b7d7744263a5208b059ffe88/v22.2/node-shutdown.md#L206)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Small correction:
> When a node is <strike>rebalancing</strike> **dead or decommissioning and** all of its range replicas **are being upreplicated** onto other nodes...

It may also be worth clarifying that "all eligible nodes" really means "the nodes that satisfy all constraints" - I.e., for both "good" and "best" settings, the node chosen will satisfy all available constraints for replica placement and survivability; however if "good" is selected instead of "best", it will not consider range count balance in its selection, as you described.
</blockquote></details>

Done.

**Review by AlexTalks — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15615#-:-NHRWIByBpktJuV3Lb9m:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
