### PR TITLE
Limitation for stats refresher

### LINKED ISSUE #12176: stats: stats should be automatically refreshed after an upgrade
Known limitation per https://github.com/cockroachdb/cockroach/issues/54816

See also:

- #11958

### PR DESCRIPTION
**Pull request by kathancox**
Closes #12176 

Added docs for stats refresh limitation on upgrade to 20.2 – 21.2 as noted in PR.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12268#-:-MoJz4868b5uqW8Iovs7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox)

___
*[_includes/v20.2/known-limitations/stats-refresh-upgrade.md, line 1 at r1](https://reviewable.io/reviews/cockroachdb/docs/12268#-MoJylMt-A8AtU-d3xcZ:-MoJylMt-A8AtU-d3xc_:bxpbj79) ([raw file](https://github.com/cockroachdb/docs/blob/9d3eb9741794db571362515bfdff84b6cb43bf65/_includes/v20.2/known-limitations/stats-refresh-upgrade.md#L1)):*
> ```Markdown
> The [automatic statistics refresher](cost-based-optimizer.html#control-statistics-refresh-rate) automatically checks whether it needs to refresh statistics for every table in the database upon startup of each node in the cluster. If statistics for a table have not been refreshed in a while, this will trigger collection of statistics for that table. If statistics have been refreshed recently, it will not force a refresh. As a result, the automatic statistics refresher does not necessarily perform a refresh of statistics after an [upgrade](upgrade-cockroach-version.html). This could cause a problem, for example, if the upgrade moves from a version without [histograms](cost-based-optimizer.html#control-histogram-collection) to a version with histograms.
> ```

Is it worth mentioning a workaround? For example, users can always refresh statistics manually using `CREATE STATISTICS` (or `ANALYZE` on recent versions) if they find that statistics have not been refreshed automatically.

**Comment by kathancox** [comment]
TFTR @rytaft! Yes, definitely should include that! I've added that here.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12268#-:-MoK7iNk3Z6byBHjNUzT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rmloveland)

**Review by rmloveland — APPROVED** [review]
LGTM

**Pull request merged**
