### PR TITLE
Add v21.2.4 release notes

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-1747
Fixes DOC-2188

### CODE REVIEW

**Comment by rmloveland** [comment]
Eric, adding you for general review - this is scheduled for Monday 2022-01-10 so I guess anytime tomorrow if you're around or on Monday AM is fine

Nick, adding you as the ride-along person for this release

Kathryn, please take a look at the removal of the known limitation on BACKUP/RESTORE?  If you could look by Monday at like lunchtime EST that would be awesome!

Thanks all!

**Comment by kathancox** [comment]
This LGTM @rmloveland. I had covered this in a PR submitted today, but I can take it out of mine? Lmk what you think is best. https://github.com/cockroachdb/docs/pull/12675.

**Comment by rmloveland** [comment]
> This LGTM @rmloveland. I had covered this in a PR submitted today, but I can take it out of mine? Lmk what you think is best. #12675. 

Thanks Kathryn! I'll change this PR to remove the updates to everything except the actual release notes file - having your PR do all that other stuff at once makes more sense, I think

**Comment by rmloveland** [comment]
>> This LGTM @rmloveland. I had covered this in a PR submitted today, but I can take it out of mine? Lmk what you think is best. #12675.
> Thanks Kathryn! I'll change this PR to remove the updates to everything except the actual release notes file - having your PR do all that other stuff at once makes more sense, I think

Actually Kathryn do you mind changing your PR?  Sorry for the flip-flop.  That would be a lot easier for me since I think this will merge in front of #12675 b/c it's merging Monday

**Review by ericharmeling — COMMENTED** [review]
Looks good! Per your comment above, I only reviewed the release notes. I had some grammar/linkage nits.

Also, as a general note, there is some inconsistency about the issue refs (`cockroachdb/cockroach#1234` vs `#1234`). IDK if it really matters, just something to note.

> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12683#-:-MspKMqs4UGKbt0rgg1l:b-25wcv0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox, @nickvigilante, and @rmloveland)

___
*[releases/v21.2.4.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspGHCC8PlW8JYJiW-u:-MspGHCC8PlW8JYJiW-v:b6bgkbi) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L35)):*
> ```Markdown
> ### Security updates
> 
> - It is now possible to pre-compute the hash of the password credentials of a SQL user client-side, and set the SQL user's password using the hash, so that the CockroachDB never sees the password string in clear in the SQL session. This auto-detection is subject to the new [cluster setting](../v21.2/cluster-settings.html) `server.user_login.store_client_pre_hashed_passwords.enabled`. This setting defaults to `true` (i.e. feature enabled). This feature is meant for use in automation/orchestration, when the control plane constructs passwords for users outside of CockroachDB, and there is an architectural desire to ensure that cleartext passwords are not transmitted/stored in-clear. Note: **when the client provides the password hash, CockroachDB cannot carry any checks on the internal structure of the password,** such as minimum length, special characters, etc. Should a deployment require such checks to be performed database-side, the operator would need to disable the mechanism via the [cluster setting](../v21.2/cluster-settings.html) named above. When upgrading a cluster from a previous version, to ensure that the feature remains disabled throughout the upgrade, use the following statement prior to the upgrade: `INSERT INTO system.settings(name, value, "valueType") VALUES('server.user_login.store_client_pre_hashed_passwords.enabled', 'false', 'b');`.  (We do not recommend relying on the database to perform password checks. Our recommended deployment best practice is to implement credential definitions in a control plane / identity provider that is separate from the database.) [#73855][#73855]
> ```

nit: grammar

TBH, I don't really understand this sentence.



_Code quote:_
```Markdown
so that the CockroachDB never sees the password string in clear in the SQL session
```
___
*[releases/v21.2.4.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspGNHk0As8X_nsTW_Y:-MspGNHk0As8X_nsTW_Z:bn2t27r) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L35)):*
> ```Markdown
> ### Security updates
> 
> - It is now possible to pre-compute the hash of the password credentials of a SQL user client-side, and set the SQL user's password using the hash, so that the CockroachDB never sees the password string in clear in the SQL session. This auto-detection is subject to the new [cluster setting](../v21.2/cluster-settings.html) `server.user_login.store_client_pre_hashed_passwords.enabled`. This setting defaults to `true` (i.e. feature enabled). This feature is meant for use in automation/orchestration, when the control plane constructs passwords for users outside of CockroachDB, and there is an architectural desire to ensure that cleartext passwords are not transmitted/stored in-clear. Note: **when the client provides the password hash, CockroachDB cannot carry any checks on the internal structure of the password,** such as minimum length, special characters, etc. Should a deployment require such checks to be performed database-side, the operator would need to disable the mechanism via the [cluster setting](../v21.2/cluster-settings.html) named above. When upgrading a cluster from a previous version, to ensure that the feature remains disabled throughout the upgrade, use the following statement prior to the upgrade: `INSERT INTO system.settings(name, value, "valueType") VALUES('server.user_login.store_client_pre_hashed_passwords.enabled', 'false', 'b');`.  (We do not recommend relying on the database to perform password checks. Our recommended deployment best practice is to implement credential definitions in a control plane / identity provider that is separate from the database.) [#73855][#73855]
> ```

nit: grammar

`(i.e., feature enabled)`



_Code quote:_
```Markdown
(i.e. feature enabled)
```
___
*[releases/v21.2.4.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspHFsy8dK1J4avUrQI:-MspHFsy8dK1J4avUrQJ:b1sceb1) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L43)):*
> ```Markdown
> ### Enterprise edition changes
> 
> - [Changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) can be created with a new option called `metrics_label` which lets operators configure changefeeds to use dedicated set of metrics for those changefeed(s) so that they can be monitored independently of other changefeed(s) in the system. [#73014][#73014]
> ```

nit: grammar

`to use a dedicated set of metrics`



_Code quote:_
```Markdown
to use dedicated set of metrics
```
___
*[releases/v21.2.4.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspIWCJ48hCeI9YH1_k:-MspIWCJ48hCeI9YH1_l:bdpljib) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L55)):*
> ```Markdown
>     - CockroachDB only recognizes password hashes computed using bcrypt, as follows (we detail this algorithm so that orchestration software can implement their own password hash computation, separate from the database):
>         1. Take the cleartext password string.
>         2. Append the following byte array to the password: `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (These are 32 hex-encoded bytes. What are these bytes? The SHA-256 hash of an empty string. Why is it appended? This is a historical oddity in CockroachDB with no particular reason. It adds no security.)
> ```

TBH, I don't think we should include these last 3 sentences. IDK if they add any valuable information.



_Code quote:_
```Markdown
Why is it appended? This is a historical oddity in CockroachDB with no particular reason. It adds no security.
```
___
*[releases/v21.2.4.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspI7HjA7j9ivGCXXec:-MspI7HjA7j9ivGCXXed:b-kolf9z) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L57)):*
> ```Markdown
>         2. Append the following byte array to the password: `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (These are 32 hex-encoded bytes. What are these bytes? The SHA-256 hash of an empty string. Why is it appended? This is a historical oddity in CockroachDB with no particular reason. It adds no security.)
>         3. Choose a bcrypt cost. (CockroachDB servers use cost 10 by default.)
>         4. Generate a bcrypt hash of the string generated at step 2 with the cost chosen at step 3, as per https://en.wikipedia.org/wiki/Bcrypt or https://bcrypt.online/ Note that CockroachDB only supports hashes computed using bcrypt version 2a.
> ```

nit:

`[https://en.wikipedia.org/wiki/Bcrypt](https://en.wikipedia.org/wiki/Bcrypt)`



_Code quote:_
```Markdown
https://en.wikipedia.org/wiki/Bcrypt
```
___
*[releases/v21.2.4.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspIE8P9CrNqTVDdah3:-MspIE8P9CrNqTVDdah4:b-i597h7) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L57)):*
> ```Markdown
>         2. Append the following byte array to the password: `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (These are 32 hex-encoded bytes. What are these bytes? The SHA-256 hash of an empty string. Why is it appended? This is a historical oddity in CockroachDB with no particular reason. It adds no security.)
>         3. Choose a bcrypt cost. (CockroachDB servers use cost 10 by default.)
>         4. Generate a bcrypt hash of the string generated at step 2 with the cost chosen at step 3, as per https://en.wikipedia.org/wiki/Bcrypt or https://bcrypt.online/ Note that CockroachDB only supports hashes computed using bcrypt version 2a.
> ```

nit:

`[https://bcrypt.online](https://bcrypt.online).`



_Code quote:_
```Markdown
https://bcrypt.online/
```
___
*[releases/v21.2.4.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspJPtMDrwYxed3bLGY:-MspJPtMDrwYxed3bLGZ:bat7slm) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L65)):*
> ```Markdown
>             |-----------------+----------------------------------------------+-----------------------------------------------------------------------------|
>             | `crdb-bcrypt`   | yes (`CRDB-BCRYPT$2a$...`)                   | recognized if enabled via [cluster setting](../v21.2/cluster-settings.html) |
>             | `scram-sha-256` | yes (`SCRAM-SHA-256$4096:...`)               | not implemented yet (issue #42519)                                          |
> ```

nit:

`[#42519](https://github.com/cockroachdb/cockroach/pull/42519)`

or add a ref to a link defined at the bottom



_Code quote:_
```Markdown
#42519
```
___
*[releases/v21.2.4.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspIn_dB8Q_zCrFq4PF:-MspIn_dB8Q_zCrFq4PG:b-6fx9gr) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L68)):*
> ```Markdown
>             | `md5`           | yes (`md5...`)                               | obsolete, will likely not be implemented                                    |
> 
> - Backport the `server.user_login.store_client_pre_hashed_passwords.enabled` [cluster setting](../v21.2/cluster-settings.html) to v21.2. The backported default value in v21.2 is `false`. In v22.1 the default will be `true`. [cockroachdb/cockroach#73855][#73855]
> ```

nit: grammar

`Backported the`



_Code quote:_
```Markdown
Backport the
```
___
*[releases/v21.2.4.md, line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspJ-KU1xQJg2VlxfY4:-MspJ-KU1xQJg2VlxfY5:b-lxy69b) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L77)):*
> ```Markdown
> ### Command-line changes
> 
> - Fixed a bug affecting the [redactability of logging tags in output log entries](../v21.2/configure-logs.html#redact-logs). This bug was introduced in [the v21.2.0 release](v21.2.0.html). [#74155][#74155]
> ```

Might want to move this to `### Bug fixes` and remove the `### Command-line changes` section altogether.



_Code quote:_
```Markdown
- Fixed a bug affecting the [redactability of logging tags in output log entries](../v21.2/configure-logs.html#redact-logs). This bug was introduced in [the v21.2.0 release](v21.2.0.html). [#74155][#74155]
```
___
*[releases/v21.2.4.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspJx100xVvAzyA64Vz:-MspJx100xVvAzyA64W-:b5vwnc6) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L81)):*
> ```Markdown
> ### DB Console changes
> 
> - Added new formatting functions to create summarized queries for [`SELECT`](../v21.2/selection-queries.html), [`INSERT`](../v21.2/insert.html), and [`UPDATE`](../v21.2/update.html) statements. Also add new metadata fields, which will later be used to pass this information to the front-end [Statements page](../v21.2/ui-statements-page.html). [cockroachdb/cockroach#73661][#73661]
> ```

nit: grammar

`Also added`



_Code quote:_
```Markdown
Also add 
```
___
*[releases/v21.2.4.md, line 84 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspKz3PATJ_UKyRbNkh:-MspKz3Q-3Jo6unPs9dn:b8wc7vu) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L84)):*
> ```Markdown
> - The [jobs overview table in DB Console](../v21.2/ui-jobs-page.html) now shows when jobs have the status "reverting", and shows the badge "retrying" when running or reverting jobs are also retrying. Hovering over the status for a "retrying" job will show the "Next execution time" in UTC. Two new columns, "Last Execution Time (UTC)" and "Execution Count", were also added to the jobs overview table in DB Console, and the "Status" column was moved left to the second column in the table. The `status` query parameter in the `/jobs` endpoint now supports the values `reverting` and `retrying`. [#73624][#73624]
> - Added new statement summaries to the [Statements page](../v21.2/ui-statements-page.html). This applies for [`SELECT`](../v21.2/selection-queries.html), [`INSERT`](../v21.2/insert.html)/[`UPSERT`](../v21.2/upsert.html), and [`UPDATE`](../v21.2/update.html) statements, and will enable them to be more detailed and less ambiguous than our previous formats. [#73661][#73661]
> - Use new summarized formats for [`SELECT`](../v21.2/selection-queries.html), [`INSERT`](../v21.2/insert.html)/[`UPSERT`](../v21.2/upsert.html), and [`UPDATE`](../v21.2/update.html) statements on the [Sessions page](../v21.2/ui-sessions-page.html) and the [Transactions page](../v21.2/ui-transactions-page.html), to be consistent with the [Statements page](../v21.2/ui-statements-page.html). Show "Mean rows written" as a metric for all statement types on the [Statements page](../v21.2/ui-statements-page.html), instead of hiding this metric for [`SELECT`](../v21.2/selection-queries.html) statements. [#73661][#73661]
> ```

nit: grammar

`Added new summarized`



_Code quote:_
```Markdown
Use new summarized
```
___
*[releases/v21.2.4.md, line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspM3Nr66pXOLvsIb6V:-MspM3Nr66pXOLvsIb6W:ba6xl5f) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L114)):*
> ```Markdown
> 
> - Added admit and commit latency metrics to [changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html). [cockroachdb/cockroach#73014][#73014]
> - Update and improve the set of sink specific [changefeed](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) metrics. [#73014][#73014]
> ```

nit: grammar

`Updated and improved`



_Code quote:_
```Markdown
Update and improve
```

**Review by rmloveland — COMMENTED** [review]
thanks Eric!

Fixed the various nits

Also removed the issue ref inconsistency - I added those manually and forgot to remove them until now (I have some editor tooling that uses that format to open issues in my browser).  they should all be gone now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12683#-:-MspQXz96APpoXEei_aM:b-veyoow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @kathancox, and @nickvigilante)

___
*[releases/v21.2.4.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspGHCC8PlW8JYJiW-u:-MspOpi603s_-kloCijp:b-9yj1n3) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L35)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

TBH, I don't really understand this sentence.
</blockquote></details>

edited lightly to say "so that CockroachDB never sees the password string in the clear in the SQL session"

I don't fully understand it but I think it means basically the app computes a hash of a user password and sends the hash to CRDB so CRDB never sees a plaintext password string.  Because security etc.
___
*[releases/v21.2.4.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspGNHk0As8X_nsTW_Y:-MspPMDx0gHFIUV65Z_R:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L35)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

`(i.e., feature enabled)`
</blockquote></details>

Fixed!
___
*[releases/v21.2.4.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspHFsy8dK1J4avUrQI:-MspPR2z6CvcgPMRLN0E:be0yepa) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L43)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

`to use a dedicated set of metrics`
</blockquote></details>

Fixed, nice catch thanks
___
*[releases/v21.2.4.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspIWCJ48hCeI9YH1_k:-MspPY_iBJKavDFILAai:bfz04zr) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L55)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

TBH, I don't think we should include these last 3 sentences. IDK if they add any valuable information.
</blockquote></details>

ya that makes sense - removed!
___
*[releases/v21.2.4.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspI7HjA7j9ivGCXXec:-MspP_ab3xAQSBKORvH-:b-84419s) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L57)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:

`[https://en.wikipedia.org/wiki/Bcrypt](https://en.wikipedia.org/wiki/Bcrypt)`
</blockquote></details>

did it!
___
*[releases/v21.2.4.md, line 57 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspIE8P9CrNqTVDdah3:-MspPpedBdzlrCwKlqLB:b-84419s) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L57)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:

`[https://bcrypt.online](https://bcrypt.online).`
</blockquote></details>

did it!
___
*[releases/v21.2.4.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspJPtMDrwYxed3bLGY:-MspQ8dU8mzoudMpw7Wo:b8980yp) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L65)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:

`[#42519](https://github.com/cockroachdb/cockroach/pull/42519)`

or add a ref to a link defined at the bottom
</blockquote></details>

oh nice catch - totally missed this one
___
*[releases/v21.2.4.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspIn_dB8Q_zCrFq4PF:-MspQEli025DnXuRNZof:b-886gsx) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L68)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

`Backported the`
</blockquote></details>

Fixed
___
*[releases/v21.2.4.md, line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspJ-KU1xQJg2VlxfY4:-MspSqs312QP3GLX75lT:b-t20k8o) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L77)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Might want to move this to `### Bug fixes` and remove the `### Command-line changes` section altogether.
</blockquote></details>

good call - done!
___
*[releases/v21.2.4.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspJx100xVvAzyA64Vz:-MspQNQB2sEMHhNnBq9m:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L81)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

`Also added`
</blockquote></details>

Done!
___
*[releases/v21.2.4.md, line 84 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspKz3PATJ_UKyRbNkh:-MspQShVDGbrtGnfofue:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L84)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

`Added new summarized`
</blockquote></details>

Done!
___
*[releases/v21.2.4.md, line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/12683#-MspM3Nr66pXOLvsIb6V:-MspQWQi4ZrjDJYaFKFH:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/579da8add0a2c165b2fe18bf50fad6f1da087c02/releases/v21.2.4.md#L114)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: grammar

`Updated and improved`
</blockquote></details>

Fixed!

**Review by ericharmeling — APPROVED** [review]
LGTM!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12683#-:-Msp_wAxD3qh8A9uKhxx:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @nickvigilante)

**Pull request merged**
