### PR TITLE
Doc updates for cockroach init

### LINKED ISSUE #1288: core: Explicit init command
Background: 
  - https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recdaFNmgzO5oBwe7
  - RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/init_command.md

Owner: @bdarnell 

PRs: https://github.com/cockroachdb/cockroach/pull/16371

### LINKED ISSUE #1718: Use includes in cloud deployment guides
There's a lot of redundancy across our cloud deployment tutorials. We should look into using includes to reduce the need to update multiple files.

### PR DESCRIPTION
**Pull request by jseldess**
- Document the `cockroach init` command
- Update 1.1 prod deployment docs 
  - Revise workflow to use `init` command
  - Use includes wherever possible 
- Update 1.1 `cockroach start` docs
- Use init command in 1.1 core feature demos
- Update formatting on 1.1 local deployment docs
- Make 1.1 build an app tutorials single-node only

Fixes #1288 
Fixes #1718

### CODE REVIEW

**Comment by jseldess** [comment]
@bdarnell, for now, I didn't change the "Start a Local Cluster" tutorials because revising them to focus more on single-node local deployment is a broader project. The risk of leaving the pages as-is, though, is that users might be surprised or confused that the workflow is different once they get to prod deployment. Thoughts?

**Comment by bdarnell** [comment]
:lgtm:

Yeah, the updates to the "local cluster" docs can come in a separate change.

---

Reviewed 28 of 28 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[_includes/prod_deployment/insecure-requirements.md, line 1 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSgOcfOCH6xm8GWLWt:-KvSgOcfOCH6xm8GWLWu:b-taj6w3) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/insecure-requirements.md#L1)):*
> ```Markdown
> - You must have SSH access to each machine with `root` or `sudo` privileges. This is necessary for distributing and starting CockroachDB binaries.
> ```

It's necessary for the instructions we use here, but it's not true in general. It's entirely possible to run cockroach without root/sudo permissions (that's what we do on our own test clusters). The only thing in our instructions that needs root is putting the binary in `/usr/local/bin`, which we only do because it's easier than giving detailed instructions about modifying your `$PATH` (alternatively, we could use `./cockroach` in all the instructions so it doesn't need to go on your path. This is what I normally do)

The insecure requirements should have the same `page.ssh_link` trick as the secure ones.

---

*[_includes/prod_deployment/insecure-requirements.md, line 4 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSjDhvh-59cSjKwsFR:-KvSjDhvh-59cSjKwsFS:b-tr1plo) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/insecure-requirements.md#L4)):*
> ```Markdown
> 
> - Your network configuration must allow TCP communication on the following ports:
> 	- **26257** (`tcp:26257`) for intra-cluster and client-cluster communication
> ```

Repeating the port here is weird. What's the `tcp:26257` syntax for?

---

*[_includes/prod_deployment/secure-generate-certificates.md, line 125 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiNkmT9TqBfQ7hKlI:-KvSiNkmT9TqBfQ7hKlJ:blq42ds) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-generate-certificates.md#L125)):*
> ```Markdown
> 	~~~
> 
>     {{site.data.alerts.callout_success}}In later steps, you'll use the <code>root</code> user's certificate to run <a href="cockroach-commands.html"><code>cockroach</code></a> client commands from your local machine. If you might also want to run <code>cockroach</code> client commands directly on a node (e.g., for local debugging), you'll need to copy the <code>root</code> user's certificate and key to that node as well.{{site.data.alerts.end}}
> ```

Since the remaining steps all assume the node has a copy of the root cert, we should include the scp command for that here (but describe it as optional)

---

*[_includes/prod_deployment/secure-recommendations.md, line 4 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSj6ITbFkIogvn1Cab:-KvSj6ITbFkIogvn1Cac:bgiukjf) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-recommendations.md#L4)):*
> ```Markdown
> 
> - Decide how you want to access your Admin UI:
>   - Only from specific IP addresses, which requires you to set firewall rules to allow communication on port `8080` *(documented on this page)*.
> ```

Is that supposed to be a link?

---

*[_includes/prod_deployment/secure-recommendations.md, line 5 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiyVGuhjOX76gMXCF:-KvSiyVGuhjOX76gMXCG:bhpzygl) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-recommendations.md#L5)):*
> ```Markdown
> - Decide how you want to access your Admin UI:
>   - Only from specific IP addresses, which requires you to set firewall rules to allow communication on port `8080` *(documented on this page)*.
>   - Using an SSH tunnel, which requires you to use `--http-host=localhost` when starting your nodes.
> ```

Is that required? That's unfortunate. We should file an issue about that if there's not one.

---

*[v1.1/deploy-cockroachdb-on-aws-insecure.md, line 21 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSkRW3JwED0WYzCqIG:-KvSkRW3JwED0WYzCqIH:br3ma9j) ([raw file](https://github.com/cockroachdb/docs/blob/79cd7a4e0b6e60f39c9733107f83dd4eb5f7c1c4/v1.1/deploy-cockroachdb-on-aws-insecure.md#L21)):*
> ```Markdown
> ## Requirements
> 
> You must have SSH access ([key pairs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html)/[SSH login](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html)) to each machine with root or sudo privileges. This is necessary for distributing binaries and starting CockroachDB.
> ```

We should add the platform-specific links here to the See Also section (or as additional links in this section after the include)

---

*[v1.1/start-a-node.md, line 20 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSlimiaF8l0niDaliE:-KvSlimiaF8l0niDaliF:biwyj15) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/v1.1/start-a-node.md#L20)):*
> ```Markdown
> 
> # Start a multi-node cluster:
> $ cockroach start <flags, including --join>
> ```

This command should end with `&` so it goes into the background (otherwise you won't get another prompt to be able to run `cockroach init`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-:-KvSm93WR-_loInhnNOo:b-ix48bo)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[_includes/prod_deployment/insecure-requirements.md, line 4 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSjDhvh-59cSjKwsFR:-KvTTR2i0Dr6BvbKhvYE:b-nong8h) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/insecure-requirements.md#L4)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Repeating the port here is weird. What's the `tcp:26257` syntax for?
</blockquote></details>

Don't remember why that was there. Removing. 

---

*[_includes/prod_deployment/secure-generate-certificates.md, line 125 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiNkmT9TqBfQ7hKlI:-KvTU8kgHqq7UN9vhahv:b2n44g8) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-generate-certificates.md#L125)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Since the remaining steps all assume the node has a copy of the root cert, we should include the scp command for that here (but describe it as optional)
</blockquote></details>

Which remaining steps require the root cert on the node? I think they all run client commands from the local machine?

---

*[_includes/prod_deployment/secure-recommendations.md, line 4 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSj6ITbFkIogvn1Cab:-KvTT_-l5S5fEPYaW2Np:b-hwdfoh) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-recommendations.md#L4)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is that supposed to be a link?
</blockquote></details>

No, I think it's meant to just call out that our tutorials go the route of opening the port via the firewall. I'll just remove that.

---

*[_includes/prod_deployment/secure-recommendations.md, line 5 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiyVGuhjOX76gMXCF:-KvTVKIDO5_MBYlHKQCK:b7pzzeb) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-recommendations.md#L5)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is that required? That's unfortunate. We should file an issue about that if there's not one.
</blockquote></details>

Checking with @mberhault.

---

*[v1.1/deploy-cockroachdb-on-aws-insecure.md, line 21 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSkRW3JwED0WYzCqIG:-KvTVd8GaD53csLhPyof:b5ufdqf) ([raw file](https://github.com/cockroachdb/docs/blob/79cd7a4e0b6e60f39c9733107f83dd4eb5f7c1c4/v1.1/deploy-cockroachdb-on-aws-insecure.md#L21)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should add the platform-specific links here to the See Also section (or as additional links in this section after the include)
</blockquote></details>

Can you clarify which platform-specific links you mean?

---

*[v1.1/start-a-node.md, line 20 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSlimiaF8l0niDaliE:-KvTVrUTKX41qWTry5Lv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/v1.1/start-a-node.md#L20)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This command should end with `&` so it goes into the background (otherwise you won't get another prompt to be able to run `cockroach init`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Comment by bdarnell** [comment]
Review status: 35 of 38 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[_includes/prod_deployment/secure-generate-certificates.md, line 125 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiNkmT9TqBfQ7hKlI:-KvTZW6iKyLZYx0Fzsn5:bq201q8) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-generate-certificates.md#L125)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Which remaining steps require the root cert on the node? I think they all run client commands from the local machine?
</blockquote></details>

Oh, the insecure instructions say "ssh to any node" and run it there, but the secure versions say to run it locally. I missed that because I paid more attention to the insecure versions (since they come first alphabetically). This discrepancy between secure and insecure mode is strange and we should run client commands locally in both cases. 

---

*[_includes/prod_deployment/secure-test-cluster.md, line 55 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvT_INU4VCVrn8KknT3:-KvT_INU4VCVrn8KknT4:b-vnxugl) ([raw file](https://github.com/cockroachdb/docs/blob/cd4bdfea64820e81b038f2b2c624d35cc87ee96c/_includes/prod_deployment/secure-test-cluster.md#L55)):*
> ```Markdown
> 	~~~
> 
> 6. Use **CTRL + D**, **CTRL + C**, or `\q` to exit the SQL shell.
> ```

On windows (if you're running this locally instead of sshing to any node), it's ctrl-z instead of ctrl-d (i know `\q` works anywhere, and i think `ctrl-c` does). But `ctrl-d`/`ctrl-z` is probably the most "normal" way to do this. 

---

*[v1.1/deploy-cockroachdb-on-aws-insecure.md, line 21 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSkRW3JwED0WYzCqIG:-KvTY_0AT8q7V4vOzK_1:bu6abvu) ([raw file](https://github.com/cockroachdb/docs/blob/79cd7a4e0b6e60f39c9733107f83dd4eb5f7c1c4/v1.1/deploy-cockroachdb-on-aws-insecure.md#L21)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Can you clarify which platform-specific links you mean?
</blockquote></details>

Sorry, I meant to delete/rewrite this comment. I meant that we should the `page.ssh_link` for the insecure docs too. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Comment by jseldess** [comment]
*[_includes/prod_deployment/insecure-requirements.md, line 1 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSgOcfOCH6xm8GWLWt:-KvToKys4h1L0Q_51gZ1:b-3ufs2s) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/insecure-requirements.md#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's necessary for the instructions we use here, but it's not true in general. It's entirely possible to run cockroach without root/sudo permissions (that's what we do on our own test clusters). The only thing in our instructions that needs root is putting the binary in `/usr/local/bin`, which we only do because it's easier than giving detailed instructions about modifying your `$PATH` (alternatively, we could use `./cockroach` in all the instructions so it doesn't need to go on your path. This is what I normally do)

The insecure requirements should have the same `page.ssh_link` trick as the secure ones.
</blockquote></details>

Removed that bit about root/sudo, and added the ssh_link to the insecure docs. Thanks for catching that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Comment by jseldess** [comment]
*[v1.1/deploy-cockroachdb-on-aws-insecure.md, line 21 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSkRW3JwED0WYzCqIG:-KvTofuWZ3wKZ7cHr8KR:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/79cd7a4e0b6e60f39c9733107f83dd4eb5f7c1c4/v1.1/deploy-cockroachdb-on-aws-insecure.md#L21)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Sorry, I meant to delete/rewrite this comment. I meant that we should the `page.ssh_link` for the insecure docs too. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Comment by jseldess** [comment]
*[_includes/prod_deployment/secure-recommendations.md, line 5 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiyVGuhjOX76gMXCF:-KvTooRm99UNMb8H09u4:b-yfiwr1) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-recommendations.md#L5)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Checking with @mberhault.
</blockquote></details>

Revised, with help from Marc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Comment by jseldess** [comment]
Review status: 18 of 38 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[_includes/prod_deployment/secure-test-cluster.md, line 55 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvT_INU4VCVrn8KknT3:-KvTr1KSxd9CRarobfwE:b2a3bjq) ([raw file](https://github.com/cockroachdb/docs/blob/cd4bdfea64820e81b038f2b2c624d35cc87ee96c/_includes/prod_deployment/secure-test-cluster.md#L55)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

On windows (if you're running this locally instead of sshing to any node), it's ctrl-z instead of ctrl-d (i know `\q` works anywhere, and i think `ctrl-c` does). But `ctrl-d`/`ctrl-z` is probably the most "normal" way to do this. 
</blockquote></details>

I'll go with just `\q` or `ctrl-c`, since they'll work everywhere. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Comment by jseldess** [comment]
*[_includes/prod_deployment/secure-generate-certificates.md, line 125 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1942#-KvSiNkmT9TqBfQ7hKlI:-KvTtLbKfP2lZK35ziMk:btq1k1l) ([raw file](https://github.com/cockroachdb/docs/blob/80dbfb6e38702ab61bd35d5e8bbd9bcee8608b40/_includes/prod_deployment/secure-generate-certificates.md#L125)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Oh, the insecure instructions say "ssh to any node" and run it there, but the secure versions say to run it locally. I missed that because I paid more attention to the insecure versions (since they come first alphabetically). This discrepancy between secure and insecure mode is strange and we should run client commands locally in both cases. 
</blockquote></details>

Updated the insecure docs to run client commands locally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1942)*

**Pull request merged**
