### PR TITLE
DOC-3675-deprecate-events-endpoint

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-3675

- For v22.1 and v21.2: added deprecation notice to `/events` cluster API endpoint, and recommended external log sinks or configuring alerting for specific events instead. The two versions required slightly different link targets due to the new `rules` API endpoint in v22.1.

Note: we don't appear to mention the `/events` endpoint or the `system.logevents` table elsewhere in the corpus besides release notes (and should not edit there), so this is a small PR.

Open question for Docs reviewer (or anyone) whether more inline or current `<br><br>` approach is preferred.

[v22.1: cluster-api.md](https://deploy-preview-13959--cockroachdb-docs.netlify.app/docs/stable/cluster-api.html#resources) | [v21.2: cluster-api.md](https://deploy-preview-13959--cockroachdb-docs.netlify.app/docs/v21.2/cluster-api#resources)

### CODE REVIEW

**Review by thtruo — APPROVED** [review]
> <
Thanks @andf-crl, this LGTM! Regarding inline vs <br> tags: the`<br><br>` as you have it reads more legibly to me, though I'd lean on the general docs style guide to influence the decision. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13959#-:-N30tSNS1xN5j7ElSysj:b-wpntqc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by thtruo** [comment]
Alternatively, it might be helpful to utilize a similar treatment (red banner) similar to https://www.cockroachlabs.com/docs/v22.1/create-index.html or https://www.cockroachlabs.com/docs/v22.1/create-table.html (see row for `opt_interleave`)

**Comment by andf-crl** [comment]
Thanks! I'd probably save the big red warning for when the endpoint is removed i.e. 404s. Presently this is still accessible and serving data, so a bolded notice seems more appropriate.

**Review by taroface — APPROVED** [review]
LGTM

**Pull request merged**
