### PR TITLE
Expand Begin Transaction diagram

### PR DESCRIPTION
**Pull request by uptimeDBA**
My first PR following the new [CONTRIBUTING](https://github.com/cockroachdb/docs/blob/gh-pages/CONTRIBUTING.md) guidelines. (`html-proofer` took a while on my system but completed successfully.)
This one may require some discussion as I've included the **iso_level** production which, I my mind, doesn't match the documentation/blogs around transaction isolation levels in CockroachDB. 
image 1

Parts of it might need some `unimplemented()` or `SKIP_DOC` or something in the grammar file.

I haven't done the Basic/Expanded thing with the iso_level diagram because it was only the one diagram. Let me know if you want it and I'll add the JavaScript.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/417)

### CODE REVIEW

**Comment by uptimeDBA** [comment]
I'm not sure I did this correctly. Is there any more setup required for circleci for documentation? I couldn't find the AWS URL in the circleci output, but maybe that's because it failed?

**Comment by jseldess** [comment]
Don't think you did anything wrong, @uptimeDBA, but circle ci didn't find our circle.yml configuration for some reason, so it never ran the files through Jekyll, checked the output with htmlproofer, and synced the output to aws.

@mberhault, any idea why circle ci ignored our tests here?

**Comment by jseldess** [comment]
Paul, the grammar shows the ANSI SQL isolation levels, but the only two we need to show in our docs are `SERIALIZABLE` and `SNAPSHOT ISOLATION`. `transactions.md` has a mapping to the ANSI levels.

Since we only need to show two, what do you think about inlining them rather than breaking out a separate image.  

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/417#-:-KKv-I1sWoxoEbQMK7R2:757681149)*

**Comment by jseldess** [comment]
Thanks for running `htmlproofer` locally. It takes quite a while for me, too; I should add that note to `contributing.md`.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/417#-:-KKv0GNC2A3RX7mU0TpV:1015953267)*

**Comment by uptimeDBA** [comment]
The grammar file (`sql.y`) maps:
`READ UNCOMMITTED`, `READ COMMITTED`, and `SNAPSHOT` to our `SNAPSHOT ISOLATION` level

and

`REPEATABLE READ` and `SERIALIZABLE` to our `SERIALIZABLE` level.

I could use the `Replace` functionality in the `generate` utility to remove all but `SNAPSHOT` and `SERIALIZABLE` but it's probably better to use the `{ /* SKIP DOC */ }` syntax added to the `sql.y` file:

```
iso_level:
  READ UNCOMMITTED
  {
    $$.val = SnapshotIsolation
  }
| READ COMMITTED
  {
    $$.val = SnapshotIsolation
  }
| SNAPSHOT
  {
    $$.val = SnapshotIsolation
  }
| REPEATABLE READ
  {
    $$.val = SerializableIsolation
  }
| SERIALIZABLE
  {
    $$.val = SerializableIsolation
  }
```

Is that a good idea @mjibson? and if so, is the syntax like:

```
iso_level:
  READ UNCOMMITTED
  {
    /* SKIP DOC */    
    $$.val = SnapshotIsolation
  }
| READ COMMITTED
  {
    /* SKIP DOC */    
    $$.val = SnapshotIsolation
  }
| SNAPSHOT
  {
    $$.val = SnapshotIsolation
  }
| REPEATABLE READ
  {
    /* SKIP DOC */    
    $$.val = SerializableIsolation
  }
| SERIALIZABLE
  {
    $$.val = SerializableIsolation
  }
```

@jseldess. Yes, when this grammar is down to two options I will inline.

**Comment by mberhault** [comment]
@uptimeDBA: your branch isn't synced to master, so there's no circle.yml file in there. You'll need to fetch/rebase/push to refresh it.

**Comment by mjibson** [comment]
I don't think we should remove that syntax from the docs. I would just document which syntax goes to which level.

**Comment by uptimeDBA** [comment]
@mjibson. That makes sense, given that's it still valid syntax. Maybe the [COMPARISON TO ANSI SQL ISOLATION LEVELS](https://www.cockroachlabs.com/docs/transactions.html#comparison-to-ansi-sql-isolation-levelshttpsenwikipediaorgwikiisolationdatabasesystemsisolationlevels) section should document this mapping so we can refer to it from this page.

**Comment by uptimeDBA** [comment]
Thanks @mberhault. I take a copy of the latest before I make a change. I must remember to refresh it after the change just before I submit the PR.

So I've updated and it's now got a `circle.yml` file to work with but it failed on:
```
aws s3 sync --quiet --delete ./_site s3://cockroach-docs-review/${CIRCLE_SHA1}/ returned exit code 1
```
Something else I need to do?

**Comment by jseldess** [comment]
@uptimeDBA, good idea about updating that ansi sql > cockroach comparison. I'll do that.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/417#-:-KKzAbBbhmezexK630JA:-547445911)*

**Comment by mberhault** [comment]
@uptimeDBA: ah. right. circleci doesn't push aws credentials for fork PRs do avoid leaking our credentials (which makes sense). I'm not sure there's a good way around that, other than a completely public AWS bucket which isn't a great solution.

**Comment by jseldess** [comment]
@uptimeDBA, I wasn't aware of the aws credential limitation. I'll update the docs `contributing.md`.

But I think everything looks good to go here, in terms of the graphic? If so, I'll merge.

**Comment by uptimeDBA** [comment]
Yeap, all good from me. Whoever ends up documenting the the Begin Transaction command will have the full syntax available on the page.

**Pull request merged**
