### PR TITLE
v20.2.0-rc.4 release notes

### LINKED ISSUE #8795: v20.2.0-rc.4 Release Notes
Prep date: 10/30/20
Release date: 11/3/20
SHA: `150c5918fb6e28e0ea5bfa4e8e94088986fbbf98 `
Release Manager: Juan Leon
Issue: https://github.com/cockroachdb/cockroach/issues/56145

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [ ] Run script to generate release notes
- [ ] Update docs site
- [ ] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8795.

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8802)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess)

___
*[releases/v20.2.0-rc.4.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/8802#-ML8M5zl9q_PEliPVOfG:-ML8M5zvElJHuy5RChbb:bx4g21p) ([raw file](https://github.com/cockroachdb/docs/blob/defbadc6d4f858e109338e364e1f8a13128ceb5e/releases/v20.2.0-rc.4.md#L40)):*
> ```Markdown
> ~~~
> 
> There are no additional release notes since [v20.2.0-rc.3](v20.2.0-rc.3.html).
> ```

@jseldess - There aren't any release notes since rc.3 but the download links, etc. changed for rc.4. Is this enough of a note to explain the lack of release notes?

**Review by jseldess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8802)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess and @lnhsingh)

___
*[releases/v20.2.0-rc.4.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/8802#-ML8M5zl9q_PEliPVOfG:-ML8Mss61FP_37_W3mVb:b6ulcrd) ([raw file](https://github.com/cockroachdb/docs/blob/defbadc6d4f858e109338e364e1f8a13128ceb5e/releases/v20.2.0-rc.4.md#L40)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@jseldess - There aren't any release notes since rc.3 but the download links, etc. changed for rc.4. Is this enough of a note to explain the lack of release notes?
</blockquote></details>

Yes, I think that's fine, if there are, in fact, no notes to share with users. Though something must've changed to warrant an rc4... Can you ask the release eng if there's anything else to say?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8802)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess, @JuanLeon1, and @solongordon)

___
*[releases/v20.2.0-rc.4.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/8802#-ML8M5zl9q_PEliPVOfG:-ML8PaCa-0jjcVyX4zlI:b-g1lghe) ([raw file](https://github.com/cockroachdb/docs/blob/defbadc6d4f858e109338e364e1f8a13128ceb5e/releases/v20.2.0-rc.4.md#L40)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Yes, I think that's fine, if there are, in fact, no notes to share with users. Though something must've changed to warrant an rc4... Can you ask the release eng if there's anything else to say?
</blockquote></details>

@juanleon1 / @solongordon - There were no release notes included for the schema permissions backport. Can you confirm that this is correct? Also, is there anything else we want to say on these release notes or is the above note (`There are no additional release notes since v20.2.0-rc.3.`) enough?

**Comment by solongordon** [comment]
There were no release notes compared to 20.1 but there was a fix for a bug in earlier 20.2 versions. I'll write up a note and post it here shortly.

**Comment by solongordon** [comment]
Release note (bug fix): A bug in earlier v20.2 versions caused some GRANT and REVOKE commands on user-defined schemas to incorrectly fail with an invalid privileges error. This affected schemas which were created after granting privileges at the database level. This bug is now resolved.

**Comment by lnhsingh** [comment]
Thanks @solongordon! @jseldess do you mind reviewing? rc.4 is ready to be published today.

**Review by taroface — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8802#-:-ML9ClR-4JPPUt2V72V8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @JuanLeon1 and @solongordon)

**Pull request merged**
