### PR TITLE
Adapt C++ Sample App doc for Free Tier

### PR DESCRIPTION
**Pull request by lnhsingh**
Related to #9793.

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9901)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUVbwvSBdlZ1s_hK_F7:-MUVbwvSBdlZ1s_hK_F8:b-hsny40) ([raw file](https://github.com/cockroachdb/docs/blob/b8169ec4e98058cdb83d7fdef2be982cd15891e3/v20.2/build-a-c++-app-with-cockroachdb.md#L122)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ shell
> $ g++ -std=c++17 txn-sample.cpp -lpq -lpqxx -o txn-sample
> ```

I wasn't able to get this to work because I kept getting an error about `pqxx_exception does not name a type` and am not sure how to fix.

**Review by ianjevans — APPROVED** [review]

**Review by ericharmeling — COMMENTED** [review]
Thanks for tackling this, Lauren.

See my comments below. I ran into a lot of errors when trying to follow this tutorial without having postgres actually installed on my machine.

One of those errors was the one you ran into. I think the lipqxx exception classes have changed since this was first written. See the suggestion below to use the correct class.

All of the other errors that I ran into had to do with the installation of libpq and libpqxx. I honestly don't think we should document those in detail, but I think it's worth being a little more explicit. See my suggestions below. I also have a lengthier explanation of my own installation journey, but that's just for the record.

> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9901#-:-MUoU9d289MObSNp9cP_:b-rq0jf3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[_includes/v20.2/app/basic-sample.cpp, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUixnKA7w4EVulotgyC:-MUixnKBEqgBH_lFYwfg:b-1n4pe) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/_includes/v20.2/app/basic-sample.cpp#L13)):*
> ```
> postgresql://{username}:{password}@{host}:{port}
> ```

`postgresql://{username}:{password}@{host}:{port}/bank`
___
*[_includes/v20.2/app/txn-sample.cpp, line 50 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUnXKLG05HoHvi6IF-_:-MUnXKLH-dJYpLl_fXdm:b-ff6fxo) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/_includes/v20.2/app/txn-sample.cpp#L50)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     } catch (const pqxx::pqxx_exception& e) {
>       // Swallow "transaction restart" errors; the transaction will be retried.
>       // Unfortunately libpqxx doesn't give us access to the error code, so we
>       // do string matching to identify retryable errors.
>       if (string(e.base().what()).find("restart transaction:") == string::npos) {
>         throw;
>       }
>     }
> ```
</details>


I think this should be

```
catch (const pqxx::sql_error& e) {
      // Swallow "transaction restart" errors; the transaction will be retried.
      // Unfortunately libpqxx doesn't give us access to the error code, so we
      // do string matching to identify retryable errors.
      if (string(e.what()).find("restart") == string::npos) {
        throw;
      }
    }
```

But I could be wrong.
___
*[_includes/v21.1/app/basic-sample.cpp, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUiyqCB0QKKrGEvpBn4:-MUiyqCB0QKKrGEvpBn5:b-evx8f8) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/_includes/v21.1/app/basic-sample.cpp#L13)):*
> ```
> postgresql://{username}:{password}@{host}:{port}
> ```

` postgresql://{username}:{password}@{host}:{port}/bank`
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 122 at r1](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUVbwvSBdlZ1s_hK_F7:-MUnXuAPBVADE_4zaQZL:b-mb2evj) ([raw file](https://github.com/cockroachdb/docs/blob/b8169ec4e98058cdb83d7fdef2be982cd15891e3/v20.2/build-a-c++-app-with-cockroachdb.md#L122)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I wasn't able to get this to work because I kept getting an error about `pqxx_exception does not name a type` and am not sure how to fix.
</blockquote></details>

See the suggested code fix above.
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUoWWL54rmxREKOD46R:-MUoWWL54rmxREKOD46S:b-2530q2) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/v20.2/build-a-c++-app-with-cockroachdb.md#L20)):*
> ```
> Install the libpqxx driver
> ```

Install libpq and the libpqxx driver
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUoWZqSBlPQkOs54ld6:-MUoWZqSBlPQkOs54ld7:b-r5yiwj) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/v20.2/build-a-c++-app-with-cockroachdb.md#L21)):*
> ```Markdown
> 
> ## Step 3. Install the libpqxx driver
> ```

Install `libpq` on your machine. 

For example, on macOS:

~~~ shell
$ brew install libpq
~~~
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUoVojD4OIh701NkrHQ:-MUoVojD4OIh701NkrHR:bpzfp5f) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/v20.2/build-a-c++-app-with-cockroachdb.md#L22)):*
> ```
> Install the C++ libpqxx driver as described in the [official documentation](https://github.com/jtv/libpqxx).
> ```

Install the C++ libpqxx driver, using [CMake](https://github.com/jtv/libpqxx/blob/master/BUILDING-cmake.md) or the [`configure` script](https://github.com/jtv/libpqxx/blob/master/configure) provided in the [`libpqxx` repo](https://github.com/jtv/libpqxx).
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUoWwP4CDYuGdF-9arD:-MUoWwP4CDYuGdF-9arE:blacgv9) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/v20.2/build-a-c++-app-with-cockroachdb.md#L27)):*
> ```Markdown
> If you are running macOS, you need to install version 4.0.1 or higher of the libpqxx driver.
> {{site.data.alerts.end}}
> ```

This is beyond the scope of updating this page... but the current instructions (and even the instructions I suggest in the comments above) are insufficient.

You need to first install PostgreSQL, or libpq.

Here's how to install libpq on a mac:

```
$ brew install libpq
```

You then might need to create a symlink for libpq and add the libpq binaries to do the PATH:

```
$ brew link --force libpq
$ echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.zshrc
```

When building libpqxx, you might also need to specify where the libpq headers are located with a flag that you pass to the build commands... 

For example, if you use CMake to build the library:

(from the top of the libpqxx repo directory)

Make a `build` folder:

```
$ mkdir build
```

Configure CMake:

```
$ cmake -S . -B ./build -DPostgreSQL_INCLUDE_DIR=/usr/local/opt/libpq/include -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/local/opt/libpq/include -DPostgreSQL_LIBRARY_DIR=/usr/local/opt/libpq/bin
```

Then, from the same directory, build the package:

```
$ cmake --build ./build
```

Then you can install the binary to your system's default install directory:

```
$ cmake --install ./build
```

**Review by lnhsingh — COMMENTED** [review]
TFTR! I was able to run through this with your updates and a few other tweaks - PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9901#-:-MVOOoHt0_5vwCqYNUQi:bmjqxhd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @lnhsingh)

___
*[_includes/v20.2/app/basic-sample.cpp, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUixnKA7w4EVulotgyC:-MVNFi_BEfUqceND-7dw:bqe4izj) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/_includes/v20.2/app/basic-sample.cpp#L13)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> postgresql://{username}:{password}@{host}:{port}
> ```

`postgresql://{username}:{password}@{host}:{port}/bank`
</blockquote></details>

Updated to be `"postgresql://{username}:{password}@{host}:{port}/{cluster_name}.bank?sslmode=verify-full&sslrootcert={path/to/ca.crt}"`
___
*[_includes/v20.2/app/txn-sample.cpp, line 50 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUnXKLG05HoHvi6IF-_:-MVNFx8u4kbOShSn-jUo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/_includes/v20.2/app/txn-sample.cpp#L50)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
>     } catch (const pqxx::pqxx_exception& e) {
>       // Swallow "transaction restart" errors; the transaction will be retried.
>       // Unfortunately libpqxx doesn't give us access to the error code, so we
>       // do string matching to identify retryable errors.
>       if (string(e.base().what()).find("restart transaction:") == string::npos) {
>         throw;
>       }
>     }
> ```

I think this should be

```
catch (const pqxx::sql_error& e) {
      // Swallow "transaction restart" errors; the transaction will be retried.
      // Unfortunately libpqxx doesn't give us access to the error code, so we
      // do string matching to identify retryable errors.
      if (string(e.what()).find("restart") == string::npos) {
        throw;
      }
    }
```

But I could be wrong.
</blockquote></details>

Done.
___
*[_includes/v21.1/app/basic-sample.cpp, line 13 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUiyqCB0QKKrGEvpBn4:-MVNG1eH-1EAoXGEQoru:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/_includes/v21.1/app/basic-sample.cpp#L13)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> postgresql://{username}:{password}@{host}:{port}
> ```

` postgresql://{username}:{password}@{host}:{port}/bank`
</blockquote></details>

Done.
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUoWWL54rmxREKOD46R:-MVNGdDvAFh3YDCsCVuD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/v20.2/build-a-c++-app-with-cockroachdb.md#L20)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> Install the libpqxx driver
> ```

Install libpq and the libpqxx driver
</blockquote></details>

Done.
___
*[v20.2/build-a-c++-app-with-cockroachdb.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/9901#-MUoWZqSBlPQkOs54ld6:-MVNGd-67atls9lsnU_g:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d00664aed6b6e591814a32b954af5277fdd5a67d/v20.2/build-a-c++-app-with-cockroachdb.md#L21)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Install `libpq` on your machine. 

For example, on macOS:

~~~ shell
$ brew install libpq
~~~
</blockquote></details>

Done.

**Review by ericharmeling — APPROVED** [review]
Sorry for the delay on the re-review. LGTM with the exception of the updates to the Gemfile build files - are those meant for this PR?

> Reviewed 6 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9901#-:-MWydt3I3wa_ErRl-izA:b-287s3s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by lnhsingh** [comment]
Thanks! I think my local build got messed up so the Gemfile.lock is now
different. I'll work to resolve them before I merge

**Pull request merged**
