### PR TITLE
Implicit SELECT FOR UPDATE on UPSERT statements

### LINKED ISSUE #8317: sql/opt: add implicit SELECT FOR UPDATE support for UPSERT statements
PR: https://github.com/cockroachdb/cockroach/pull/53132

From release notes:
> [`UPSERT`](../v20.2/upsert.html) statements now acquire locks using the `FOR UPDATE` locking mode during their initial row scan, which improves performance for contended workloads. This behavior is configurable using the `enable_implicit_select_for_update` session variable and the `sql.defaults.implicit_select_for_update.enabled` [cluster setting](../v20.2/cluster-settings.html). [#53132][#53132] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #8317.

### CODE REVIEW

**Review by nvanbenschoten — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8650)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @nvanbenschoten)

___
*[_includes/v20.2/sql/select-for-update-overview.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/8650#-MJ_37F99hM-xzF_3edA:-MJ_37F99hM-xzF_3edB:b-5gvwsg) ([raw file](https://github.com/cockroachdb/docs/blob/eedacbc5953e96aea070e7a0bc5cfed723e68467/_includes/v20.2/sql/select-for-update-overview.md#L10)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> By default, CockroachDB adds an implicit `SELECT FOR UPDATE` statement to all [`UPDATE`](update.html) and [`UPSERT`](upsert.html) queries. To turn off implicit `SELECT FOR UPDATE` statements, set `enable_implicit_select_for_update` to `false`.
> ```

I think we'll want to be a little more precise if we want to mention this at all. CockroachDB doesn't actually execute a `SELECT FOR UPDATE` statement under the hood when running an UPDATE or UPSERT statement. Instead, it uses the same locking mechanism that a `SELECT FOR UPDATE` statement does during the initial row scan of these mutation statements. The sentence you touched in `explain.md` is a little clearer about this.

**Review by ericharmeling — COMMENTED** [review]
TFTR @nvanbenschoten !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8650#-:-MJbBUrR8gof2pAgWP_4:b-csfsvu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[_includes/v20.2/sql/select-for-update-overview.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/8650#-MJ_37F99hM-xzF_3edA:-MJb9zAC8YZhf6BlmFYG:b-tmh2qn) ([raw file](https://github.com/cockroachdb/docs/blob/eedacbc5953e96aea070e7a0bc5cfed723e68467/_includes/v20.2/sql/select-for-update-overview.md#L10)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we'll want to be a little more precise if we want to mention this at all. CockroachDB doesn't actually execute a `SELECT FOR UPDATE` statement under the hood when running an UPDATE or UPSERT statement. Instead, it uses the same locking mechanism that a `SELECT FOR UPDATE` statement does during the initial row scan of these mutation statements. The sentence you touched in `explain.md` is a little clearer about this.
</blockquote></details>

Got it. I've updated this note. Please re-review. :)

**Review by nvanbenschoten — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8650#-:-MJdOYQv8-9rFYuCyi8Y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[_includes/v20.2/sql/select-for-update-overview.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/8650#-MJ_37F99hM-xzF_3edA:-MJdOWcu6P9x0bMmB9hi:b9bkkp1) ([raw file](https://github.com/cockroachdb/docs/blob/eedacbc5953e96aea070e7a0bc5cfed723e68467/_includes/v20.2/sql/select-for-update-overview.md#L10)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Got it. I've updated this note. Please re-review. :)
</blockquote></details>

Looks great!

**Review by lnhsingh — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8650#-:-MJi59dmElf5saIY70Ic:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @lnhsingh)

**Pull request merged**
