### PR TITLE
Fix SQL Basics training

### LINKED ISSUE #3711: sql basics: confusion in transactions example
In https://www.cockroachlabs.com/docs/dev/training/sql-basics.html, in the Transactions section, we have:

`
SELECT balance >= 250 FROM bank.accounts WHERE type = 'checking' AND customer_id = 2;
UPDATE bank.accounts SET balance = balance - 250 WHERE type = 'savings' AND customer_id = 2;
`

This seems to not work as expected since we are checking that the "checking" account has over 250, but we're withdrawing from the "savings" account, instead of withdrawing from the account that is being checked.

### PR DESCRIPTION
**Pull request by lhirata**
Closes #3711.

### CODE REVIEW

**Comment by changangela** [comment]
LGTM, thanks! random question: why is there an `OPEN>` prompt?

**Comment by lhirata** [comment]
Thanks for the catch @changangela! `OPEN>` is included to denote the open transaction. If you press enter twice after you start a transaction, you'll see the prompt. For example:

~~~
root@:26257/> begin;
Now adding input for a multi-line SQL transaction client-side.
Press Enter two times to send the SQL text collected so far to the server, or Ctrl+C to cancel.
You can also use \show to display the statements entered so far.
           ->
BEGIN

Time: 741.873µs

root@:26257/  OPEN>
~~~

**Comment by lhirata** [comment]
@changangela ah! I see that the `OPEN>` prompt in the training gets copied when you click the copy button. I'll fix that in another PR!

**Comment by changangela** [comment]
@lhirata haha thanks for the clarification

**Pull request merged**
