### PR TITLE
DOC-8310: Update MOLT Verify with new build instructions

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Addresses [DOC-8310](https://cockroachlabs.atlassian.net/jira/software/c/projects/DOC/issues/DOC-8310)

### CODE REVIEW

**Review by cotedm — APPROVED** [review]
LGTM

**Review by otan — APPROVED** [review]

**Review by gemma-shay — COMMENTED** [review]
Just had some formatting suggestions. Also, we might need more input here because I don't think this works right out of the box. Testing on my own terminal, it seemed like I had to add the downloaded file to my path and run the full name of the file (`./downloads/molt.darwin.amd64 ...`), not just `./molt`.

**Comment by Amruta-Ranade** [comment]
> Just had some formatting suggestions. Also, we might need more input here because I don't think this works right out of the box. Testing on my own terminal, it seemed like I had to add the downloaded file to my path and run the full name of the file (`./downloads/molt.darwin.amd64 ...`), not just `./molt`.

Hmm we do say "Optionally, add the binary to your `PATH` so you can execute the `molt verify` command from any shell." @otan should the user have to use the full file name? or am I missing a step?

**Comment by cotedm** [comment]
I think it's a good point that I hadn't caught because I had just run with the full file name `./molt.darwin.arm64`. I think the move is to add a step to rename the downloaded binary to `molt` and then run it.

**Review by gemma-shay — APPROVED** [review]
thx!

**Pull request merged**
