### PR TITLE
docs for the dump command

### LINKED ISSUE #470: dump command
https://github.com/cockroachdb/cockroach/pull/7511

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #470

HTML version: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e56d57b24ab1ebb55f22c655dec41c5de7d7fd41/back-up-and-restore-data.html

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/472)

### CODE REVIEW

**Comment by mjibson** [comment]
Everything here LGTM. However I think we should include a paragraph that some operational notes and consistency guarantees of dump. Here's the bullet points:

- Data will be dumped as it appeared at the time the dump command started. Data changed or added after the dump command started but before it completed will not appear in the output. If a dump takes longer to complete than the configured GC threshold, the dump may fail.
- Data changes can safely be made while running a dump.
- Schema changes can safely be made while running a dump.
- Reads can be done normally during a dump.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[back-up-and-restore-data.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/472#-KNDisLSzoWzLgW6kN3_:-KNDisLSzoWzLgW6kN3a:1804366904) ([raw file](https://github.com/cockroachdb/docs/blob/e56d57b24ab1ebb55f22c655dec41c5de7d7fd41/back-up-and-restore-data.md#L11)):*
> ```Markdown
> {{site.data.alerts.callout_info}}Currently, only the <code>root</code> user can run the <code>cockroach dump</code> command.{{site.data.alerts.end}}
> 
> <div id="toc"></div>
> ```

Why do we need this div if toc is false?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/472#-:-KNDjKzmB4-2-oMRzzV0:-902734593)*

**Comment by jseldess** [comment]
Done. PTAL, Matt.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[back-up-and-restore-data.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/472#-KNDisLSzoWzLgW6kN3_:-KNDkzF3T6GKU0kzmlH1:-1113062133) ([raw file](https://github.com/cockroachdb/docs/blob/e56d57b24ab1ebb55f22c655dec41c5de7d7fd41/back-up-and-restore-data.md#L11)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why do we need this div if toc is false?
</details>
See second bullet here: https://github.com/cockroachdb/docs/blob/gh-pages/CONTRIBUTING.md#toc-placement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/472#-:-KNDnVutkwUWr5g9Gyj3:313448126)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[back-up-and-restore-data.md, line 13 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/472#-KNDqf-ikIpiULyoOzPx:-KNDqf-ikIpiULyoOzPy:915439148) ([raw file](https://github.com/cockroachdb/docs/blob/5fd593f61262c9c746fc90c44652170b5fcd7a85/back-up-and-restore-data.md#L13)):*
> ```Markdown
> - The table data is dumped as it appears at the time that the command is started. Any changes after the command starts will not be included in the dump.
> - If the dump takes longer than the `ttlseconds` [replication zone](configure-replication-zones.html) setting for the table (24 hours by default), the dump may fail. 
> - Reads and schema changes can happen while a dump is in progress.
> ```

I would add "writes" here just to be explicit: "Reads, writes, and schema changes ..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/472)*

**Comment by jseldess** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[back-up-and-restore-data.md, line 13 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/472#-KNDqf-ikIpiULyoOzPx:-KNEumVDstIQFAtmO0-j:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/5fd593f61262c9c746fc90c44652170b5fcd7a85/back-up-and-restore-data.md#L13)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I would add "writes" here just to be explicit: "Reads, writes, and schema changes ..."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/472)*

**Pull request merged**
