### PR TITLE
Add/remove regions cloud

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/DOC-2045

Release note date to be edited

### CODE REVIEW

**Review by jramos-crl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14267)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @jramos-crl)

___
*[`cockroachcloud/cluster-management.md` line 121 at r2](https://reviewable.io/reviews/cockroachdb/docs/14267#-N4TPzZ_CIbrj-MRHKcR:-N4TPzZa3cb2aihz7wR9:b60b3ny) ([raw file](https://github.com/cockroachdb/docs/blob/7ac88ea4e33b7418a8ec9f7ff4c3ce6b87652faa/cockroachcloud/cluster-management.md#L121)):*
> ```Markdown
> ## Add or remove regions from a cluster
> 
> You can add or remove up to three regions at a time through the Console. See the [Planning your cluster](plan-your-cluster.html) section of this page for cluster requirements and recommendations before proceeding.
> ```

They can actually add more than 3 regions at a time. Seems like the max is up to 9 different regions.
___
*[`cockroachcloud/cluster-management.md` line 141 at r2](https://reviewable.io/reviews/cockroachdb/docs/14267#-N4TQCcL4Inkhcayfufu:-N4TQCcL4Inkhcayfufv:b-sk2cth) ([raw file](https://github.com/cockroachdb/docs/blob/7ac88ea4e33b7418a8ec9f7ff4c3ce6b87652faa/cockroachcloud/cluster-management.md#L141)):*
> ```Markdown
> 1. Click **OK**.
> 
> ### Remove a region from your cluster
> ```

Could be worth leaving a note here that 2 regions aren't allowed. So if they are going to remove regions from a 3 region multi-region cluster, it will go back down to 1 region. The minimum is 3 regions for a multi-region cluster.

**Review by jramos-crl — APPROVED** [review]
LGTM! note - that we are still finalizing testing so we can't release the docs just yet, but will keep you in the loop on timing @gemma-shay

**Comment by jramos-crl** [comment]
@gemma-shay looks good to me! The one thing to add to the release notes is the availability of Historical Invoices for everyone. Otherwise it is all good to go.

**Comment by gemma-shay** [comment]
> @gemma-shay looks good to me! The one thing to add to the release notes is the availability of Historical Invoices for everyone. Otherwise it is all good to go.

sorry i missed this! will edit in the august release notes PR

**Pull request merged**
