### PR TITLE
Add docs on disk stalls (impact/mitigation)

### LINKED ISSUE #8901: Add docs on impacts of and mitigations for disk stalls
We currently mention the phrase "disk stall" in one place, on our [Cluster Troubleshooting](https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html) page, where we note that it is one of the things that will cause node liveness issues.  Based on a quick search we do not seem to mention the term `fsync` at all except in some obscure no-longer-visible-in-20.2+ cluster settings.

However, we should probably add more information about this area, including but not limited to:

- What is a disk stall?
- Why does it happen?
- What can you do about it, if anything?

At a high level it seems like a thing that is more likely to happen if you are underprovisioned on IOPS, but there are apparently other reasons, including hardware failures and possible SELinux interactions, that we should also write up.

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #8901

### CODE REVIEW

**Comment by rmloveland** [comment]
Hi Bilal!

This is based on an internal disk stall doc you wrote a while back.  Maybe a lot has changed, so let me know if I should read something else and make a new PR instead of this one!  Thank you :-)

**Comment by rmloveland** [comment]
Hi Bilal!  Sorry for the long gap, I was on vacation - probably should have waited to post this one, sorry!

Do you think the latest changes are ok?

**Comment by rmloveland** [comment]
Hey @itsbilal sorry to bug you again.  Do you think these latest changes are OK?

**Review by itsbilal — APPROVED** [review]
Oops, sorry I missed this earlier! Thanks for the repeat ping. This all looks great now.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11119#-:-Mkd4Ahu0EHiC81LWkN5:b-cgw3r4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.2/cluster-setup-troubleshooting.md, line 325 at r1](https://reviewable.io/reviews/cockroachdb/docs/11119#-Mi1tcjjDXEstluU-dFl:-Mkd4JVbBSP67lIAqtqS:br7t48z) ([raw file](https://github.com/cockroachdb/docs/blob/9bed65a41455a1cd667dd13785352ccb04b38626/v21.2/cluster-setup-troubleshooting.md#L325)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

OK, updated to try to include that info.  I changed "usually crash" to "attempt to shut down the node" and mentioned that orchestration should restart it, hope I didn't lose too much of the meaning 
</blockquote></details>

Looks great now! Thanks for updating
___
*[v21.2/cluster-setup-troubleshooting.md, line 343 at r2](https://reviewable.io/reviews/cockroachdb/docs/11119#-Mkd4YSs6pcyoiVjm7nY:-Mkd4YSs6pcyoiVjm7nZ:bunipwt) ([raw file](https://github.com/cockroachdb/docs/blob/d1875f36b6abadc1041196696fcfc98fec421bab/v21.2/cluster-setup-troubleshooting.md#L343)):*
> ```Markdown
> - Every 10 seconds, the CockroachDB storage engine checks the [_write-ahead log_](https://en.wikipedia.org/wiki/Write-ahead_logging), or _WAL_.  If data has not been synced to disk (via `fsync`) within that interval, the log message `disk stall detected: unable to write to %s within %s %s warning log entry` is written to the [storage logs](logging.html#storage).  If this state continues for 60 seconds or more (configurable with the `COCKROACH_ENGINE_MAX_SYNC_DURATION` environment variable), the `cockroach` process is killed.
> 
> - Every time the storage engine writes to the main [`cockroach.log` file](logging.html#dev), the engine waits 30 seconds for the write to succeed.  If the write to the log fails, the `cockroach` process is killed and the following message is written to STDERR / `cockroach.log`:
> ```

Since you're mentioning `COCKROACH_ENGINE_MAX_SYNC_DURATION`, you could probably top it off by mentioning `COCKROACH_LOG_MAX_SYNC_DURATION` as the env variable that configures this 30s variable. But up to you.

**Review by rmloveland — COMMENTED** [review]
Thanks Bilal!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11119#-:-MkmB5G1DmLvmOogt_kL:b67k8eb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[v21.2/cluster-setup-troubleshooting.md, line 325 at r1](https://reviewable.io/reviews/cockroachdb/docs/11119#-Mi1tcjjDXEstluU-dFl:-MkmCvZu-U92_81UjUu9:b-ucfknh) ([raw file](https://github.com/cockroachdb/docs/blob/9bed65a41455a1cd667dd13785352ccb04b38626/v21.2/cluster-setup-troubleshooting.md#L325)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Looks great now! Thanks for updating
</blockquote></details>

Thanks!
___
*[v21.2/cluster-setup-troubleshooting.md, line 343 at r2](https://reviewable.io/reviews/cockroachdb/docs/11119#-Mkd4YSs6pcyoiVjm7nY:-MkmB3iTDrpI3LdEbYth:b3ir7vk) ([raw file](https://github.com/cockroachdb/docs/blob/d1875f36b6abadc1041196696fcfc98fec421bab/v21.2/cluster-setup-troubleshooting.md#L343)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Since you're mentioning `COCKROACH_ENGINE_MAX_SYNC_DURATION`, you could probably top it off by mentioning `COCKROACH_LOG_MAX_SYNC_DURATION` as the env variable that configures this 30s variable. But up to you.
</blockquote></details>

Added - thanks!

**Comment by itsbilal** [comment]
Yes, it also applies to 21.1. I'll let you make the call on whether it's worthwhile to update those docs, but if you could that'd be great. Thanks!

**Review by taroface — APPROVED** [review]
Small comments!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11119#-:-Mkmo3MHD9XiuLQ2q-2t:bl0s9vz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @rmloveland)

___
*[v21.2/cluster-setup-troubleshooting.md, line 325 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmhPUe3dXSJ7RTZ75z:-MkmhPUe3dXSJ7RTZ76-:b-lhm871) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L325)):*
> ```
> e.  This
> ```

Extra space here! Also, in various places below.
___
*[v21.2/cluster-setup-troubleshooting.md, line 325 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmhWJMArOSeSsS_b_m:-MkmhWJN6gSyhVq30jjr:b-7faf4m) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L325)):*
> ```
> a.k.a.
> ```

Nit: I think the periods aren't needed in this
___
*[v21.2/cluster-setup-troubleshooting.md, line 331 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmhyVb02FN9GGnYg-F:-MkmhyVb02FN9GGnYg-G:b-vnsg75) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L331)):*
> ```
> even though it can't make progress on the ranges for which it's the leaseholder.
> ```

Suggestion: can't -> cannot and it's -> its

Only because the contractions distracted from visualizing the process you were describing here
___
*[v21.2/cluster-setup-troubleshooting.md, line 331 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmmX_U5PY9Y1aZsRQp:-MkmmX_U5PY9Y1aZsRQq:bt4z24f) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L331)):*
> ```Markdown
> - Bad cluster write performance, usually in the form of a substantial drop in QPS for a given workload.
> - [Node liveness issues](#node-liveness-issues).
> - Writes on one node come to a halt.  In rare cases, a node may be able to perform liveness checks (which involve writing to disk) even though it cannot write other data to disk due to one or more slow/stalled calls to `fsync`. Because the node is passing its liveness checks, it is able to hang onto its leases even though it can't make progress on the ranges for which it's the leaseholder.  This wedged node has a ripple effect on the rest of the cluster such that all processing of the ranges whose leaseholders are on that node basically grinds to a halt.  As mentioned above, CockroachDB's disk stall detection will attempt to shut down the node when it detects this state.
> ```

It sounds like this item is describing one symptom ("Writes on one node come to a halt") and a second symptom caused by this ("In rare cases, [...] all processing of the ranges whose leaseholders are on that node basically grinds to a halt."). For clarity, do you think it's worth bringing the latter symptom to the top, i.e.:

"In rare cases, the processing of ranges whose leaseholders are on this node also comes to halt. This occurs when a node is able to perform liveness checks..."
___
*[v21.2/cluster-setup-troubleshooting.md, line 341 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmnczxDkhrKtUIco6k:-MkmnczyBFkR7qdxD6oM:bhlu1vv) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L341)):*
> ```
> storage logs
> ```

I'd say either "`STORAGE` logs" or "`STORAGE` logging channel". 
___
*[v21.2/cluster-setup-troubleshooting.md, line 343 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-Mkmnsvx3njAM-UU54b8:-Mkmnsvy9w5zRoskAcFd:b8o1td3) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L343)):*
> ```
> STDERR
> ```

`stderr`

**Review by rmloveland — COMMENTED** [review]
Thanks Ryan!

Updated all the things, and porting to v21.1 before merge

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11119#-:-MkrIkxU-QyhmomD1ZQd:b-6egup7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @taroface)

___
*[v21.2/cluster-setup-troubleshooting.md, line 325 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmhPUe3dXSJ7RTZ75z:-MkrFgQUC64j5oFCSVmy:b5n0mgw) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L325)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> e.  This
> ```

Extra space here! Also, in various places below.
</blockquote></details>

I'll never give up on my first love, Ryan (which to be clear is two spaces after a period)

PS sorry for forgetting to strip these out already, doing it now :-) 
___
*[v21.2/cluster-setup-troubleshooting.md, line 325 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmhWJMArOSeSsS_b_m:-MkrGhmFDODhHIT6uor7:b6onkw0) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L325)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> a.k.a.
> ```

Nit: I think the periods aren't needed in this
</blockquote></details>

interesting!  I wonder if this has evolved now, cool - kinda like e-mail to email
___
*[v21.2/cluster-setup-troubleshooting.md, line 331 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmhyVb02FN9GGnYg-F:-MkrGxxF4bIxu5N2gBm1:bjez9f4) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L331)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> even though it can't make progress on the ranges for which it's the leaseholder.
> ```

Suggestion: can't -> cannot and it's -> its

Only because the contractions distracted from visualizing the process you were describing here
</blockquote></details>

Did it!
___
*[v21.2/cluster-setup-troubleshooting.md, line 331 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmmX_U5PY9Y1aZsRQp:-MkrHS4O6PkXTVJEumk0:b-h01udc) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L331)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

It sounds like this item is describing one symptom ("Writes on one node come to a halt") and a second symptom caused by this ("In rare cases, [...] all processing of the ranges whose leaseholders are on that node basically grinds to a halt."). For clarity, do you think it's worth bringing the latter symptom to the top, i.e.:

"In rare cases, the processing of ranges whose leaseholders are on this node also comes to halt. This occurs when a node is able to perform liveness checks..."
</blockquote></details>

I meant for it to be "symptom -> reason" such that the user can see "writes come to a halt" as the simple description of the symptom, and then what follows as the cause of the symptom

But your comment makes it clear we did not get there.

To try to achieve this I just edited this to say "Writes on one node come to a halt. This can happen because in rare cases, ..."

That way the user can stop reading after a first simple sentence that says what they are seeing , but read more if they care.

I hope this is a good compromise!
___
*[v21.2/cluster-setup-troubleshooting.md, line 341 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-MkmnczxDkhrKtUIco6k:-MkrIVtU3x0rs4cMAObY:bloelsp) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L341)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> storage logs
> ```

I'd say either "`STORAGE` logs" or "`STORAGE` logging channel". 
</blockquote></details>

Nice to get a review from The Logging Person (tm) on the team - updated, thanks!  :-) 

(At least ISTR - feel free to disavow that label also lol)
___
*[v21.2/cluster-setup-troubleshooting.md, line 343 at r3](https://reviewable.io/reviews/cockroachdb/docs/11119#-Mkmnsvx3njAM-UU54b8:-MkrIiv580rrns72bXaD:b-cypxrp) ([raw file](https://github.com/cockroachdb/docs/blob/77ebed2dfe05ab3164f7b54ed9f2c1cf891049ef/v21.2/cluster-setup-troubleshooting.md#L343)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> STDERR
> ```

`stderr`
</blockquote></details>

updated!

**Pull request merged**
