### PR TITLE
Tell a bit more about SQL name resolution.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1050)

### CODE REVIEW

**Comment by sploiselle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql-name-resolution.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbpHbTrZndxA82ce0fP:-KbpHbTrZndxA82ce0fQ:b-9cz5t6) ([raw file](https://github.com/cockroachdb/docs/blob/99afbe8d508247a3dee8d94fb8e1ace124eec495/sql-name-resolution.md#L7)):*
> ```Markdown
> ---
> 
> Table and function names can exist in multiple places. Resolution decides which one to use.
> ```

Such a welcome surprise to get these PRs from you, @knz!

So I can get a better understanding of what this page does for users, can I get you to reframe this introductory paragraph? I like to think of the first line of a technical document as "making sure the reader knows what they get by reading this doc." I think this is most of the way there, but I'm wondering if we can make this a little more explicit? When/why would someone use this page? What are the actions someone has recently taken that would lead them to need the info you've outlined here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1050)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql-name-resolution.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbpHbTrZndxA82ce0fP:-Kbpo_ir8b9NyjJD1KYQ:b-p59hfd) ([raw file](https://github.com/cockroachdb/docs/blob/99afbe8d508247a3dee8d94fb8e1ace124eec495/sql-name-resolution.md#L7)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Such a welcome surprise to get these PRs from you, @knz!

So I can get a better understanding of what this page does for users, can I get you to reframe this introductory paragraph? I like to think of the first line of a technical document as "making sure the reader knows what they get by reading this doc." I think this is most of the way there, but I'm wondering if we can make this a little more explicit? When/why would someone use this page? What are the actions someone has recently taken that would lead them to need the info you've outlined here?
</blockquote></details>

I just moved some text at the beginning for this purpose. PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1050)*

**Comment by jseldess** [comment]
LGTM, with some comments. Thanks for this addition, @knz!

In a separate PR, I've arrange general SQL syntax topics under a new subsection of **Develop**. I'll put this there once it's been merged.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[sql-expressions.md, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuRG3eahV9xQH5UVPa:-KbuRG3eahV9xQH5UVPb:b54nuld) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-expressions.md#L36)):*
> ```Markdown
>   configuration`.
> 
>   In case the column name is ambiguous (e.g. when joining across
> ```

I'd reformat this section a bit:

- Using the name of the column, e.g., `price` in `SELECT price FROM items`.
  - If the name of the column is a SQL keyword, the name just be quoted, e.g., `SELECT "Default" FROM configuration`.
  - If the name is ambiguous (e.g., when joining across multiple tables), it can be disambiguated by prefixing the column name with the table name, e.g., `SELECT items.price FROM items`.
- Using the ordinal position of the column, e.g., `SELECT items.price FROM items`.

---

*[sql-expressions.md, line 283 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuSZegXCSRyK7m6ywE:-KbuSZegXCSRyK7m6ywF:b-hqq83n) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-expressions.md#L283)):*
This sentence is a bit confusing. Let's combine with the previous sentence and clarify, something like:

> This applies the named function to the arguments between parentheses. When the function's name space is not included, name resolution rules determine which function is called. 

---

*[sql-name-resolution.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbpHbTrZndxA82ce0fP:-KbuLGlq1138x5PMF_Je:b8df6f7) ([raw file](https://github.com/cockroachdb/docs/blob/99afbe8d508247a3dee8d94fb8e1ace124eec495/sql-name-resolution.md#L7)):*
This is a great addition, @knz. Thank you.

General American English style nit: use a comma after `e.g.` and `i.e.`. Feel free to adjust here and in other files (didn't catch this earlier), or I can take care of it later.

In second sentence, for readability, let's move the example into parentheses:

> The same table name (e.g., `orders`) can exist in multiple databases.

In third sentence, let's stick with `e.g.` instead of `for example`. This is something we should look at more globally, but not important now. And let's move it into parentheses:

> When a query specifies a table name without a database name (e.g., `SELECT * FROM orders;`), how does CockroachDB know which `orders` table is being considered?

---

*[sql-name-resolution.md, line 24 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuM9b6UCO8xCeu1eFl:-KbuM9b6UCO8xCeu1eFm:b4dn0oe) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L24)):*
> ```Markdown
> function names in [value expressions](sql-expressions.html):
> 
> - If the given name already tells where to look explicitly, i.e. it is *qualified*, then just use this information.
> ```

Let's make the two top-level bullets a bit more direct:

- If the name is qualified (i.e., the name already tells where to look), use this information.
- If the name is unqualified: 

---

*[sql-name-resolution.md, line 28 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuOwbP3UWOj171LgY6:-KbuOwbP3UWOj171LgY7:bbadwll) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L28)):*
> ```Markdown
>   - Try to find the name in the "default database" as set by [`SET DATABASE`](set-database.html).
>   - Try to find the name using the [search path](#search-path).
>    - If the name was not found so far, produce an error.
> ```

nit: If the name is not found, produce an error.

---

*[sql-name-resolution.md, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuPVSZs8gnD9DQwjIp:-KbuPVS_oL7A8Xy3o9MC:bxx4z51) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L39)):*
> ```Markdown
> 
> The current search path can be inspected using the statement `SHOW
> SEARCH_PATH`, or `SHOW ALL`.
> ```

Make `SHOW ALL` a link: 

```
[`SHOW ALL`](show-all.html)
```

---

*[sql-name-resolution.md, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuPgJu8uKkEox2IIni:-KbuPgJu8uKkEox2IInj:b-fxzn9y) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L44)):*
Maybe clarify the opening of this paragraph a bit: 

> By default, the search path for new sessions is `pg_catalog`, ...

Also a nit: Remove quotes around `pg_catalog`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-:-KbuTXxnaq0ug6GYGy55:b-8ph62h)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[sql-expressions.md, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuRG3eahV9xQH5UVPa:-KbvLOTNsnxca-83PaLY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-expressions.md#L36)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I'd reformat this section a bit:

- Using the name of the column, e.g., `price` in `SELECT price FROM items`.
  - If the name of the column is a SQL keyword, the name just be quoted, e.g., `SELECT "Default" FROM configuration`.
  - If the name is ambiguous (e.g., when joining across multiple tables), it can be disambiguated by prefixing the column name with the table name, e.g., `SELECT items.price FROM items`.
- Using the ordinal position of the column, e.g., `SELECT items.price FROM items`.
</blockquote></details>

Done.

---

*[sql-expressions.md, line 283 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuSZegXCSRyK7m6ywE:-KbvLPOXmG0zti_UcJB2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-expressions.md#L283)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

This sentence is a bit confusing. Let's combine with the previous sentence and clarify, something like:

> This applies the named function to the arguments between parentheses. When the function's name space is not included, name resolution rules determine which function is called. 
</blockquote></details>

Done.

---

*[sql-name-resolution.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbpHbTrZndxA82ce0fP:-KbvKRicgN1ozaI8BgVi:b3jyjdn) ([raw file](https://github.com/cockroachdb/docs/blob/99afbe8d508247a3dee8d94fb8e1ace124eec495/sql-name-resolution.md#L7)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

This is a great addition, @knz. Thank you.

General American English style nit: use a comma after `e.g.` and `i.e.`. Feel free to adjust here and in other files (didn't catch this earlier), or I can take care of it later.

In second sentence, for readability, let's move the example into parentheses:

> The same table name (e.g., `orders`) can exist in multiple databases.

In third sentence, let's stick with `e.g.` instead of `for example`. This is something we should look at more globally, but not important now. And let's move it into parentheses:

> When a query specifies a table name without a database name (e.g., `SELECT * FROM orders;`), how does CockroachDB know which `orders` table is being considered?
</blockquote></details>

I have adjusted these occurrences but also some others I found in sql-expressions.md. Thanks for pointing this out.

---

*[sql-name-resolution.md, line 24 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuM9b6UCO8xCeu1eFl:-KbvKiRyj6kpzR-Yx2TP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L24)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Let's make the two top-level bullets a bit more direct:

- If the name is qualified (i.e., the name already tells where to look), use this information.
- If the name is unqualified: 
</blockquote></details>

Done.

---

*[sql-name-resolution.md, line 28 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuOwbP3UWOj171LgY6:-KbvKl7ylSmngCQAKjLn:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L28)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

nit: If the name is not found, produce an error.
</blockquote></details>

Done.

---

*[sql-name-resolution.md, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuPVSZs8gnD9DQwjIp:-KbvKq8wwOoKPSluWYYp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L39)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Make `SHOW ALL` a link: 

```
[`SHOW ALL`](show-all.html)
```
</blockquote></details>

Done.

---

*[sql-name-resolution.md, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-KbuPgJu8uKkEox2IIni:-KbvKyhVIwZ8RvmEYdsQ:b-t8txkz) ([raw file](https://github.com/cockroachdb/docs/blob/45ce9f3b7c97dddbee8d4828139de2380f63bb0e/sql-name-resolution.md#L44)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Maybe clarify the opening of this paragraph a bit: 

> By default, the search path for new sessions is `pg_catalog`, ...

Also a nit: Remove quotes around `pg_catalog`.
</blockquote></details>

The quotes around the second occurrence is because we're talking about the text of the prefix, not the thing named pg_catalog.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1050)*

**Comment by jseldess** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1050#-:-KbvSG08vAPdCfOBkhVb:bnfp4nl)*

**Comment by jseldess** [comment]
There's a broken internal link preventing the tests from succeeding, but I'll fix that in a follow-up PR.

**Pull request merged**
