### PR TITLE
Update configure-replication-zones.md

### PR DESCRIPTION
**Pull request by shannonbradshaw**
Topography -> Topology

### CODE REVIEW

**Review by rmloveland — APPROVED** [review]
Hi @shannonbradshaw !

This change LGTM - it also needs to be updated in same files in the v23.2 and v24.2 folders

Let me know if you want me to do it!

Thanks!

**Comment by shannonbradshaw** [comment]
Thanks, @rmloveland. Yes, please make the changes in the other folders.

**Comment by rmloveland** [comment]
@taroface I ported the small change in this PR across the [supported versions](https://www.cockroachlabs.com/docs/releases/release-support-policy)

the updated commit message has details:

> Update 'cluster topography' to 'cluster topology' In the replication zone and connection pooling docs across the following versions: v24.2, v24.1, v23.2, v23.1

> Prompted by internal Slack message in #docs

**Review by taroface — APPROVED** [review]
LGTM!

**Pull request merged**
