### PR TITLE
Add SHOW TRANSACTIONS

### LINKED ISSUE #8342: sql: add SHOW TRANSACTIONS
PR: https://github.com/cockroachdb/cockroach/pull/51902

From release notes:
> Added the `SHOW TRANSACTIONS` statement, similar to [`SHOW SESSIONS`](../v20.2/show-sessions.html) and variants. It shows the currently active transactions in the node or cluster, and some information about them. [#51902][#51902] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8342.

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8606)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[v20.2/show-transactions.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJ827Uv9zZSD3rU6vd2:-MJ827Uv9zZSD3rU6vd3:bft4upy) ([raw file](https://github.com/cockroachdb/docs/blob/f70757bb9be1e69020889ba2d3d57c7acba49be7/v20.2/show-transactions.md#L18)):*
> ```Markdown
> ## Required privileges
> 
> No [privileges](authorization.html#assign-privileges) are required to execute this statement. However, note that non-`admin` users see only their own currently active transactions, whereas the `admin` users see all users' currently active transactions.
> ```

This note about non-admin can only see their currently active transactions is copied over from `SHOW SESSIONS`. Does this apply to `SHOW TRANSACTIONS` too?
___
*[v20.2/show-transactions.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJ82HeGAyg7TtiMh9lN:-MJ82HeGAyg7TtiMh9lO:b-p4btem) ([raw file](https://github.com/cockroachdb/docs/blob/f70757bb9be1e69020889ba2d3d57c7acba49be7/v20.2/show-transactions.md#L23)):*
> ```Markdown
> 
> ~~~
> SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
> ```

What does the `ALL` do? Is `SHOW ALL CLUSTER TRANSACTIONS` = `SHOW CLUSTER TRANSACTIONS` = `SHOW TRANSACTIONS`?

**Comment by lnhsingh** [comment]
@jordanlewis friendly ping to PTAL :)

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8606#-:-MJV5T1P01KXEAbvS8Fp:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @lnhsingh)

___
*[v20.2/show-transactions.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJV4wrh0iAqSU7t_ZiS:-MJV4wrh0iAqSU7t_ZiT:b8p26bx) ([raw file](https://github.com/cockroachdb/docs/blob/f70757bb9be1e69020889ba2d3d57c7acba49be7/v20.2/show-transactions.md#L3)):*
> ```Markdown
> ---
> title: SHOW TRANSACTIONS
> summary: The SHOW TRANSACTIONS statement lists all currently active transactions across the cluster or on the local node.
> ```

Do we usually say "local" or "gateway"?
___
*[v20.2/show-transactions.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJ827Uv9zZSD3rU6vd2:-MJV4swDDouy6CoUUSMw:bb77ufg) ([raw file](https://github.com/cockroachdb/docs/blob/f70757bb9be1e69020889ba2d3d57c7acba49be7/v20.2/show-transactions.md#L18)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This note about non-admin can only see their currently active transactions is copied over from `SHOW SESSIONS`. Does this apply to `SHOW TRANSACTIONS` too?
</blockquote></details>

Yes.
___
*[v20.2/show-transactions.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJ82HeGAyg7TtiMh9lN:-MJV4gYA49yR6yj3EkL6:b-5gh9pv) ([raw file](https://github.com/cockroachdb/docs/blob/f70757bb9be1e69020889ba2d3d57c7acba49be7/v20.2/show-transactions.md#L23)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

What does the `ALL` do? Is `SHOW ALL CLUSTER TRANSACTIONS` = `SHOW CLUSTER TRANSACTIONS` = `SHOW TRANSACTIONS`?
</blockquote></details>

`ALL` means show internal queries/txns as well. Internal txns are issued by the database itself and don't initiate from users.
___
*[v20.2/show-transactions.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJV54X44bcRszK0cny8:-MJV54X44bcRszK0cny9:b-dwrhp0) ([raw file](https://github.com/cockroachdb/docs/blob/f70757bb9be1e69020889ba2d3d57c7acba49be7/v20.2/show-transactions.md#L27)):*
> ```Markdown
> 
> - To list the active transactions across all nodes of the cluster, use `SHOW TRANSACTIONS` or `SHOW CLUSTER TRANSACTIONS`.
> - To list the active transactions just on the local node, use `SHOW LOCAL TRANSACTIONS`.
> ```

ditto re: local/gateway

**Review by ericharmeling — APPROVED** [review]
Great work @lnhsingh !!

LGTM

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8606#-:-MJY80MDDab3d44R4C9B:b-lpzqnc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @jordanlewis, and @lnhsingh)

___
*[v20.2/show-transactions.md, line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJY8B2b8GdNvPZgvjIn:-MJY8B2b8GdNvPZgvjIo:b4khkq5) ([raw file](https://github.com/cockroachdb/docs/blob/bd2cc10d62e782cdb2f1104f29dc77d2a4cfc50b/v20.2/show-transactions.md#L20)):*
> ```
> ## Synopsis
> ```

Not that this needs to change in this PR, but I've been using "Syntax" in lieu of "Synopsis" because it makes way more sense (and is in general more approachable language), IMO. Pretty sure the only reason why we use the term "Synopsis" on SQL **syntax** pages is because that's the term that Postgres syntax docs use... and I don't think we should necessarily copy their docs in *every* respect.
___
*[v20.2/show-transactions.md, line 23 at r2](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJY85saDGznFCrdIp6o:-MJY85saDGznFCrdIp6p:bkkywd2) ([raw file](https://github.com/cockroachdb/docs/blob/bd2cc10d62e782cdb2f1104f29dc77d2a4cfc50b/v20.2/show-transactions.md#L23)):*
> ```
> ~~~
> SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
> ~~~
> ```

Help text FTW!! Woohoo!

**Review by lnhsingh — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8606#-:-MJYCoaf6w8-bDlctbSW:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @jordanlewis)

___
*[v20.2/show-transactions.md, line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJY8B2b8GdNvPZgvjIn:-MJYCeR11EaDwpUPlhku:b-cxontw) ([raw file](https://github.com/cockroachdb/docs/blob/bd2cc10d62e782cdb2f1104f29dc77d2a4cfc50b/v20.2/show-transactions.md#L20)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> ## Synopsis
> ```

Not that this needs to change in this PR, but I've been using "Syntax" in lieu of "Synopsis" because it makes way more sense (and is in general more approachable language), IMO. Pretty sure the only reason why we use the term "Synopsis" on SQL **syntax** pages is because that's the term that Postgres syntax docs use... and I don't think we should necessarily copy their docs in *every* respect.
</blockquote></details>

Makes sense to me! Changed to Syntax.
___
*[v20.2/show-transactions.md, line 23 at r2](https://reviewable.io/reviews/cockroachdb/docs/8606#-MJY85saDGznFCrdIp6o:-MJYChal0zu_FfNDrgXR:bjwa7hh) ([raw file](https://github.com/cockroachdb/docs/blob/bd2cc10d62e782cdb2f1104f29dc77d2a4cfc50b/v20.2/show-transactions.md#L23)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> ~~~
> SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
> ~~~
> ```

Help text FTW!! Woohoo!
</blockquote></details>

:tada:

**Pull request merged**
