### PR TITLE
add missing job types for SHOW JOBS

### PR DESCRIPTION
**Pull request by taroface**
DOC-8354

### CODE REVIEW

**Comment by dt** [comment]
I'm a little uneasy calling this "possible values" when the there are other possible values that we just don't think users should care about, and the set changes over time. Do we actually need to claim to enumerate all "possible values" for a string result?

**Comment by dt** [comment]
Alternatively, is there a way to soften the claim? e.g. "Some common values" or "Possible values include:" or some wording that makes it clearer that there could be other values here.

**Comment by taroface** [comment]
@dt that makes sense -- I adjusted by simply removing those words; let me know if you think it works.

**Review by dt — APPROVED** [review]
Works for me. We could also say "e.g." or "Examples:" to introduce this (partial) list of types.

**Comment by taroface** [comment]
> Works for me. We could also say "e.g." or "Examples:" to introduce this (partial) list of types.

TFTR. I like e.g.! Using that.

**Review by dt — APPROVED** [review]

**Review by Amruta-Ranade — APPROVED** [review]

**Pull request merged**
