### PR TITLE
feat: Add docker-compose local cluster

### PR DESCRIPTION
**Pull request by devalexandre**
Local cluster proposal using docker-compose.

[Repository for test](https://github.com/devalexandre/cockroachdb)

### CODE REVIEW

**Comment by dbist** [comment]
adding 

```bash

listen cockroach-ui
    bind :8080
    mode tcp
    balance roundrobin
    option httpchk GET /health
    server roach-0 roach-0:8080 check port 8080
    server roach-1 roach-1:8080 check port 8080
    server roach-2 roach-2:8080 check port 8080
```
to the haproxy.conf eliminates the need for an nginx configuration and container as haproxy will load balance sql and DB Console UI

**Comment by rainleander** [comment]
@dbist - is there any other information we need to move forward on this feature request? Documentation or otherwise? Let us know either way, please?

**Comment by dbist** [comment]
you can add an init container to remove the step with initializing the cluster see [topic 1](https://blog.ervits.com/2022/03/cockroachdb-til-volume-6.html), you can also add the haproxy container and load the config into it see [this](https://github.com/dbist/cockroach-docker/blob/main/cockroach-pgbouncer/docker-compose.yml#L23-L41). You will need a separate docker directory for [haproxy](https://github.com/dbist/cockroach-docker/tree/main/cockroach-pgbouncer/haproxy). Otherwise looks good. Sorry for delay. Ping me next time.

**Comment by devalexandre** [comment]
> you can add an init container to remove the step with initializing the cluster see [topic 1](https://blog.ervits.com/2022/03/cockroachdb-til-volume-6.html), you can also add the haproxy container and load the config into it see [this](https://github.com/dbist/cockroach-docker/blob/main/cockroach-pgbouncer/docker-compose.yml#L23-L41). You will need a separate docker directory for [haproxy](https://github.com/dbist/cockroach-docker/tree/main/cockroach-pgbouncer/haproxy). Otherwise looks good. Sorry for delay. Ping me next time.

when use init and image hproxy not work.

image

source using for test:
https://github.com/devalexandre/cockroachdb/tree/chore/hproxy

@dbist

**Comment by devalexandre** [comment]
> you can add an init container to remove the step with initializing the cluster see [topic 1](https://blog.ervits.com/2022/03/cockroachdb-til-volume-6.html), you can also add the haproxy container and load the config into it see [this](https://github.com/dbist/cockroach-docker/blob/main/cockroach-pgbouncer/docker-compose.yml#L23-L41). You will need a separate docker directory for [haproxy](https://github.com/dbist/cockroach-docker/tree/main/cockroach-pgbouncer/haproxy). Otherwise looks good. Sorry for delay. Ping me next time.

the way I did the initial one is much simpler, and the function of hproxy and nginx is very clear, for a better didactic, don't you think?

**Comment by dbist** [comment]
you have an error here https://github.com/devalexandre/cockroachdb/blob/chore/hproxy/haproxy/haproxy.cfg#L20-L22
those servers need to be named after node names, i.e.

    server roach1 roach1:26257 check port 8080
    server roach2 roach2:26257 check port 8080
    server roach3 roach3:26257 check port 8080

**Comment by devalexandre** [comment]
> you have an error here https://github.com/devalexandre/cockroachdb/blob/chore/hproxy/haproxy/haproxy.cfg#L20-L22 those servers need to be named after node names, i.e.
> 
> ```
> server roach1 roach1:26257 check port 8080
> server roach2 roach2:26257 check port 8080
> server roach3 roach3:26257 check port 8080
> ```
> 
> you also did not add network to the init container, which means it cannot see roach1 container. After you correct those errors, it should work, otherwise it is up to you, I don't have authoritative view on this.

okay I go try update.

**Comment by devalexandre** [comment]
@dbist it's work !!!!

**Comment by dbist** [comment]
@jseldess need a review

**Comment by jseldess** [comment]
Sorry for the delay, all. This would be another start a local multi-node cluster option, correct? @taroface, would you mind reviewing this?

**Comment by devalexandre** [comment]
> 

yes,  start a local multi-node cluster with docker-compose

**Comment by devalexandre** [comment]
@taroface  some news?

**Comment by devalexandre** [comment]
up

**Comment by taroface** [comment]
Hi @devalexandre, I am having a look at the drafted steps. Thanks for your patience!

**Comment by taroface** [comment]
Hi, I cannot get the documented steps to work yet. I am deploying with the configuration

```
version: '3.8'

services:

  roach1:
    image: cockroachdb/cockroach:v22.1.0
    container_name: roach1
    command: start --insecure --join=roach1,roach2,roach3 --accept-sql-without-tls 
    volumes:
    - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
        - roach1

  roach2:
    image: cockroachdb/cockroach:v22.1.0
    container_name: roach2
    command: start --insecure --join=roach1,roach2,roach3  --accept-sql-without-tls 
    volumes:
    - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
        - roach2

  roach3:
    image: cockroachdb/cockroach:v22.1.0
    container_name: roach3
    command: start --insecure --join=roach1,roach2,roach3 --accept-sql-without-tls 
    volumes:
    - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
    networks:
      cockroachdb_net:
        aliases:
        - roach3

  init:
    image: cockroachdb/cockroach:v22.1.0
    command: init --insecure --host=roach1
    depends_on:
    - roach1
    networks:
      cockroachdb_net:
        aliases:
        - init

networks:
    cockroachdb_net:
        driver: bridge
```

which results in one cockroach pod and the init pod failing to run:

```
NAME                COMMAND                  SERVICE             STATUS              PORTS
roach1              "/cockroach/cockroac…"   roach1              running             26257/tcp
roach2              "/cockroach/cockroac…"   roach2              exited (1)
roach3              "/cockroach/cockroac…"   roach3              running             26257/tcp
ryankuo_init_1      "/cockroach/cockroac…"   init                exited (1)
```

@dbist am I missing something obvious here?

**Comment by devalexandre** [comment]
> Hi, I cannot get the documented steps to work yet. I am deploying with the configuration
> 
> ```
> version: '3.8'
> 
> services:
> 
>   roach1:
>     image: cockroachdb/cockroach:v22.1.0
>     container_name: roach1
>     command: start --insecure --join=roach1,roach2,roach3 --accept-sql-without-tls 
>     volumes:
>     - "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"
>     networks:
>       cockroachdb_net:
>         aliases:
>         - roach1
> 
>   roach2:
>     image: cockroachdb/cockroach:v22.1.0
>     container_name: roach2
>     command: start --insecure --join=roach1,roach2,roach3  --accept-sql-without-tls 
>     volumes:
>     - "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data"
>     networks:
>       cockroachdb_net:
>         aliases:
>         - roach2
> 
>   roach3:
>     image: cockroachdb/cockroach:v22.1.0
>     container_name: roach3
>     command: start --insecure --join=roach1,roach2,roach3 --accept-sql-without-tls 
>     volumes:
>     - "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
>     networks:
>       cockroachdb_net:
>         aliases:
>         - roach3
> 
>   init:
>     image: cockroachdb/cockroach:v22.1.0
>     command: init --insecure --host=roach1
>     depends_on:
>     - roach1
>     networks:
>       cockroachdb_net:
>         aliases:
>         - init
> 
> networks:
>     cockroachdb_net:
>         driver: bridge
> ```
> 
> which results in one cockroach pod and the init pod failing to run:
> 
> ```
> NAME                COMMAND                  SERVICE             STATUS              PORTS
> roach1              "/cockroach/cockroac…"   roach1              running             26257/tcp
> roach2              "/cockroach/cockroac…"   roach2              exited (1)
> roach3              "/cockroach/cockroac…"   roach3              running             26257/tcp
> ryankuo_init_1      "/cockroach/cockroac…"   init                exited (1)
> ```
> 
> @dbist am I missing something obvious here?

because you need use the haproxy, I'll update this

**Pull request closed without merging**
