### PR TITLE
Fixed Error Message

### PR DESCRIPTION
**Pull request by chaneth8**

### CODE REVIEW

**Comment by chaneth8** [comment]
Related issue: https://github.com/cockroachdb/docs/issues/13888

**Comment by andf-crl** [comment]
Thank you @chaneth8! We maintain only the most recent two versions of the docs: currently this is `v22.1` and `v21.2`. Could you please adjust your PR to only affect these files:
- `v21.2/monitoring-and-alerting.md`
- `v22.1/monitoring-and-alerting.md`

I would be happy to approve following this change. Thank you again for contributing!

**Review by andf-crl — CHANGES_REQUESTED** [review]
Please limit changes to supported docs versions per my previous comment -- thank you!

**Review by andf-crl — CHANGES_REQUESTED** [review]
Almost there, just one last change to make.

**Review by andf-crl — APPROVED** [review]
Thanks so much for your quick fix! I'll merge this in shortly. We appreciate your contribution!

**Pull request merged**
