### PR TITLE
v20.2 session variables update

### LINKED ISSUE #7614: sql: implement the client_min_messages session var
PR: https://github.com/cockroachdb/cockroach/pull/46650

From release notes:
> Users now have the ability to control the level of `NOTICE` outputs with the [session variable](../v20.2/show-vars.html) `client_min_messages`. [#46650][#46650] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8148: sql: support synchronous_commit and enable_seqscan as dummy no-op
PR: https://github.com/cockroachdb/cockroach/pull/52168

From release notes:
> Added support for the setting and getting of the `synchronous_commit` and `enable_seqscan` variables, which do not affect any performance characteristics. These are no-ops enabled to allow certain tools to work. [#52168][#52168] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8319: sql: implement idle_in_transaction_session_timeout
PR: https://github.com/cockroachdb/cockroach/pull/52938

From release notes:
> Implemented the `IdleInTransactionSessionTimeout` variable to allow terminating sessions that are idle in a transaction past the provided threshold. Set the variable by using `SET idle_in_transaction_session_timeout = 'time'`. Sessions that are idle in `OPEN`, `ABORTED`, and `DONE(COMMITWAIT)` transaction states will be terminated if the user idles longer than the threshold time. [#52938][#52938] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #8148.
Fixes #8319. 
Fixes #7614.

This PR adds the new v20.2 session variables to the list of exposed session variables in the v20.2 docs. 

The PR also includes the following fixes:

- Updates to the session variables in v20.1 and v20.2 that were added in previous CRDB versions, but were not previously documented (https://github.com/cockroachdb/cockroach/pull/37333, https://github.com/cockroachdb/cockroach/pull/35116, https://github.com/cockroachdb/cockroach/pull/42914, https://github.com/cockroachdb/cockroach/pull/48333)
- Changed `prefer_lookup_joins_for_fk` to `prefer_lookup_joins_for_fks`, to reflect the true name of the variable.

Adding @otan as primary engineering reviewer, but feel free to add anyone else.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@otan 

This might also resolve #7614.

I can't tell from https://github.com/cockroachdb/cockroach/pull/46650 if `client_min_messages` is meant for users. If it is, I'm not sure where to find the accepted arguments (i.e. the levels of severity).

**Comment by otan** [comment]
https://postgresqlco.nf/en/doc/param/client_min_messages/

[debug5, debug4, debug3, debug2, debug1, log, notice, warning, error]

are the accepted args!

**Comment by ericharmeling** [comment]
>[debug5, debug4, debug3, debug2, debug1, log, notice, warning, error]
>
> are the accepted args!

Awesome. Thanks!

**Review by otan — APPROVED** [review]

**Review by lnhsingh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8548#-:-MJ3jEam5JnCYhH7lOeM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Pull request merged**
