### PR TITLE
2.1 release notes

### PR DESCRIPTION
**Pull request by lhirata**

### CODE REVIEW

**Comment by nstewart** [comment]
___
*[releases/v2.1.0.md, line 9 at r3](https://reviewable.io/reviews/cockroachdb/docs/3937#-LQ419vC-ywipw9_otaG:-LQ419vC-ywipw9_otaH:b-n7r98k) ([raw file](https://github.com/cockroachdb/docs/blob/e31b66abac208b59984d9ef1bbec3b493c346e5e/releases/v2.1.0.md#L9)):*
> ```Markdown
> ## October 30, 2018
> 
> With the release of CockroachDB v2.1, we’ve made significant performance improvements, added more cluster details to our Admin UI, expanded our PostgreSQL compatibility, and provided guidance for migrating to CockroachDB.  
> ```

We didn't just provide guidance, we overall "made it easier" to migrate to CockroachDB

**Comment by nstewart** [comment]
___
*[releases/v2.1.0.md, line 9 at r3](https://reviewable.io/reviews/cockroachdb/docs/3937#-LQ419vC-ywipw9_otaG:-LQ41JrD2jc-urzPWG7o:b4kybji) ([raw file](https://github.com/cockroachdb/docs/blob/e31b66abac208b59984d9ef1bbec3b493c346e5e/releases/v2.1.0.md#L9)):*
<details><summary><i>Previously, nstewart (Nate) wrote…</i></summary><blockquote>

We didn't just provide guidance, we overall "made it easier" to migrate to CockroachDB
</blockquote></details>

With the release of CockroachDB v2.1, we've made significant performance improvements, improved our troubleshooting workflows in our Web UI, and made it easier to migrate to CockroachDB from MySQL and Postgres

**Comment by nstewart** [comment]
___
*[releases/v2.1.0.md, line 11 at r3](https://reviewable.io/reviews/cockroachdb/docs/3937#-LQ41_pX0Dfm5nKga-MG:-LQ41_pX0Dfm5nKga-MH:b-cbejnf) ([raw file](https://github.com/cockroachdb/docs/blob/e31b66abac208b59984d9ef1bbec3b493c346e5e/releases/v2.1.0.md#L11)):*
> ```Markdown
> With the release of CockroachDB v2.1, we’ve made significant performance improvements, added more cluster details to our Admin UI, expanded our PostgreSQL compatibility, and provided guidance for migrating to CockroachDB.  
> 
> - Read more about these changes in the [v2.1 blog post](https://www.cockroachlabs.com/blog/cockroachdb-2-1-release/).
> ```

This will be a broken link for a couple days. Marketing isn't releasing that blog until 11/1

**Comment by nstewart** [comment]
___
*[releases/v2.1.0.md, line 11 at r3](https://reviewable.io/reviews/cockroachdb/docs/3937#-LQ41_pX0Dfm5nKga-MG:-LQ41qz3DwHDh_0292kg:bqfxsvn) ([raw file](https://github.com/cockroachdb/docs/blob/e31b66abac208b59984d9ef1bbec3b493c346e5e/releases/v2.1.0.md#L11)):*
<details><summary><i>Previously, nstewart (Nate) wrote…</i></summary><blockquote>

This will be a broken link for a couple days. Marketing isn't releasing that blog until 11/1 
</blockquote></details>

We can add that line after the release blog goes live

**Comment by knz** [comment]
- the release note for "ALTER COLUMN ... SET TYPE" must include the disclaimer "Only type changes that do not require data checks nor data conversion are supported at this time."

- `SET distsql` is not new in 2.1. It was already available in 2.0.

- `extra_float_digits` needs not be called out in the release notes (`SET` / `SHOW`) - it's an esoteric feature only supported for compatibility with certain pg clients

**Comment by jseldess** [comment]
___
*[releases/v2.1.0.md, line 9 at r3](https://reviewable.io/reviews/cockroachdb/docs/3937#-LQ419vC-ywipw9_otaG:-LQ4IvMfC0ASD4vi8Bpf:bu0b2ti) ([raw file](https://github.com/cockroachdb/docs/blob/e31b66abac208b59984d9ef1bbec3b493c346e5e/releases/v2.1.0.md#L9)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Update again to better language from the upcoming blog post.

**Comment by jseldess** [comment]
Done. TFTR, @knz.

**Pull request merged**
