### PR TITLE
Cloud release changelog

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/CC-5408

### CODE REVIEW

**Review by ianjevans — APPROVED** [review]

**Comment by gemma-shay** [comment]
If you click on any h3, i.e. **General changes**, every instances of that heading gets highlighted. You also can't use them to navigate to specific date. Is this fixable? Could they be removed from the sidebar if not?

**Comment by ianjevans** [comment]
The anchor links are generated automatically, and I don't know that there's an easy workaround for them not linking properly. I'll try to look into this.

**Comment by gemma-shay** [comment]
@ianjevans Just discovered that they work with html. Is it okay to use html on all the h3s? (`<h3>General changes</h3>` gets turned into `#general-changes-1`, `#general-changes-2`, etc.)

**Comment by ianjevans** [comment]
I think our options are either:

1. Use HTML tags.
2. [Extend Redcarpet](https://github.com/uswds/uswds-site/pull/363/files) to handle duplicate anchor links.

First is the easiest but least sustainable. Second is the best solution, but would take a little bit of time to implement (half a day?), and would require everyone to re-bootstrap their dev env.

**Comment by gemma-shay** [comment]
@ianjevans I'm leaning 1 for now because it's an easy find&replace for me to revert, and I'm not familiar with redcarpet or ruby.

**Comment by ianjevans** [comment]
Weirdly enough, we [already extend Redcarpet](https://github.com/cockroachdb/docs/commit/75e5b5b0a0e0f21edd83ae659f12703b7569a3b5). So I tested adding some better anchor handling and it compiles and seems to work. Adding a commit.

**Comment by ianjevans** [comment]
@gemma-shay can you revert your HTML headings commit?

**Comment by ianjevans** [comment]
The good news was the concatenation of duplicate heading anchors worked. The bad news is that extending Redcarpet's renderer changed most other anchor names, causing massive broken links.

And even though you can extend Redcarpet, [you can't call superclass methods from Ruby](https://github.com/vmg/redcarpet/issues/51) as it's actually implemented in C.

So the option to customize Redcarpet seems like a no-op, as it would require re-implementing the heading parser in Ruby so it generates exact matches for anchor names as the C parser logic.

**Comment by gemma-shay** [comment]
@ianjevans My local builds are failing after pulling these updates, do you know how I can fix it? Tried `bundle install` and `make clean`.
```
An error occurred while installing redcarpet (3.5.1), and Bundler
cannot continue.
```

**Comment by ianjevans** [comment]
@gemma-shay Try running:

```
make clean
make cockroachdb
```

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[releases/index-cockroachcloud.md, line 7 at r8](https://reviewable.io/reviews/cockroachdb/docs/12334#-Mtj47WgDk81DdVhh9fC:-MtsO53i5zrvsKeOO_wk:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8b8e960192f9ea8fb5fa7084fe4055ef3e2e8637/releases/index-cockroachcloud.md#L7)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Also, does it make sense to add the "As of MM/DD/YYYY, new Cloud clusters will run CockroachDB vX.X" callout?
</blockquote></details>

Done.
___
*[releases/index-cockroachcloud.md, line 7 at r8](https://reviewable.io/reviews/cockroachdb/docs/12334#-Mtj3kDj6fYsLb96aTro:-MtsO8pH57Y1NMpOGdXO:btk8k42) ([raw file](https://github.com/cockroachdb/docs/blob/8b8e960192f9ea8fb5fa7084fe4055ef3e2e8637/releases/index-cockroachcloud.md#L7)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Does it make sense to rename this file to `releases/index-cloud.md` (or just even just `releases/cloud.md`) and add in the appropriate redirects?
</blockquote></details>

Changed to cloud.md. Is the second part of this comment a typo?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[releases/index-cockroachcloud.md, line 7 at r8](https://reviewable.io/reviews/cockroachdb/docs/12334#-Mtj3kDj6fYsLb96aTro:-MtsQ2Bz55yMLb6WCzFm:bhc9ny8) ([raw file](https://github.com/cockroachdb/docs/blob/8b8e960192f9ea8fb5fa7084fe4055ef3e2e8637/releases/index-cockroachcloud.md#L7)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Changed to cloud.md. Is the second part of this comment a typo?
</blockquote></details>

Yeah, LGTM
___
*[releases/index-cockroachcloud.md, line 7 at r8](https://reviewable.io/reviews/cockroachdb/docs/12334#-Mtj47WgDk81DdVhh9fC:-MtsQef30w0VJKt_cxRO:bflgyqf) ([raw file](https://github.com/cockroachdb/docs/blob/8b8e960192f9ea8fb5fa7084fe4055ef3e2e8637/releases/index-cockroachcloud.md#L7)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>



I think this information needs to be visually set apart from the rest of the intro information - it gets lost in the text and if we are no longer going to include the version in each week's update, this needs to be easy for users to find. Similarly, I still think we need to include an "as of date" so it's clear to users when/who this information is applicable to

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[releases/index-cockroachcloud.md, line 7 at r8](https://reviewable.io/reviews/cockroachdb/docs/12334#-Mtj47WgDk81DdVhh9fC:-MtsR9A26W6_-1edl_La:b-120l32) ([raw file](https://github.com/cockroachdb/docs/blob/8b8e960192f9ea8fb5fa7084fe4055ef3e2e8637/releases/index-cockroachcloud.md#L7)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>



I think this information needs to be visually set apart from the rest of the intro information - it gets lost in the text and if we are no longer going to include the version in each week's update, this needs to be easy for users to find. Similarly, I still think we need to include an "as of date" so it's clear to users when/who this information is applicable to
</blockquote></details>

Question too: How are we going to email release notes to Cloud users when we switch to this changelog? Will Product Marketing compile notes for the month and email? (this is definitely a nice-to-have or next step but) maybe we can set up an RSS feed?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[releases/index-cockroachcloud.md, line 7 at r8](https://reviewable.io/reviews/cockroachdb/docs/12334#-Mtj47WgDk81DdVhh9fC:-MtsnxHi1vOWFEyXA9bn:b-u6ud9i) ([raw file](https://github.com/cockroachdb/docs/blob/8b8e960192f9ea8fb5fa7084fe4055ef3e2e8637/releases/index-cockroachcloud.md#L7)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Added an H2 for **Current version**, or could do an info callout if you think that would stand out more.
</blockquote></details>

The H2 is better for scanability, but I think it could be confusing that the other H2s are dates? I would suggest putting it in a callout at the end of the intro. If you go the H2 route, I think you'd need to nest the current H2s (the dates) under something like "Changelog" and clarify that the current version is the "Current cluster version"

**Review by lnhsingh — COMMENTED** [review]
LGTM once you decide on how to display the version info

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12334#-:-MtsoxP44t7kaK-jdyfs:b-jak1xm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

**Pull request merged**
