### PR TITLE
Fix ycsb download/untar in Fault Tolerance and Replication tutorial

### PR DESCRIPTION
**Pull request by a-robinson**
I somehow forgot to remove the filenames in
a196f8ce0a6280f614d79ceddea58bcfc3cf8ef1.

### CODE REVIEW

**Comment by petermattis** [comment]
Jesse, should that be `tar xz`?

**Comment by a-robinson** [comment]
@jseldess that's because the file doesn't appear to be hosted on the review site. If you omit the `| tar xJ` the command just hangs forever.

Does the real hosted file work for you? i.e. `curl https://www.cockroachlabs.com/docs/training/resources/crdb-ycsb-mac.tar.gz | tar xJ`

**Comment by a-robinson** [comment]
> Jesse, should that be `tar xz`?

I'd think so as well, but our ["Install CockroachDB" page](https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html) has recommended using `tar -xJ` for as long as I can remember, so I didn't want to mess with that at the last minute here.

I did just switch this from `tar xJ` to `tar -xJ` for consistency with that page, but I doubt that matters.

**Comment by jseldess** [comment]
Oh, yes, the real hosted file works for me, @a-robinson. Thanks for the clarification.

**Comment by jseldess** [comment]
Also, @a-robinson, feel free to change to `xz` if that's better.

**Comment by a-robinson** [comment]
> Also, @a-robinson, feel free to change to xz if that's better.

Sticking with what's been working for binary downloads for a long time is better than changing it at the last minute.

**Pull request merged**
