### PR TITLE
Add encoding clause to Create Database diagram

### PR DESCRIPTION
**Pull request by uptimeDBA**
As discussed in #360

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/367)

### CODE REVIEW

**Comment by jseldess** [comment]
:lgtm:, thanks for this enhancement, Paul!

<details><summary><i>Previously, uptimeDBA (Paul Steffensen) wrote…</i></summary>
> #### Add encoding clause to Create Database diagram
> 
> As discussed in #360
> 
> 
> 
</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[create-database.md, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/367#-KJs06rjWtpE7X6gaonx:-KJs06rjWtpE7X6gaony:1840838315) ([raw file](https://github.com/cockroachdb/docs/blob/e5bdec4cc3be57f7072cfe59a52ceb13fcf58526/create-database.md#L24)):*
> ```Markdown
> `IF NOT EXISTS` | Create a new database only if a database of the same name does not already exist; if one does exist, do not return an error. 
> `name` | The name of the database to create, following these [naming rules](identifiers.html).
> `encoding` | The `CREATE DATABASE` statement accepts an optional `ENCODING` clause for compatibility with PostgreSQL, but `UTF-8` is the only supported encoding. The aliases `UTF8` and `UNICODE` are also accepted. Values should be enclosed in single quotes and are case insensitive. Eg; `CREATE DATABASE bank ENCODING = 'UTF8'`.
> ```

Let's replace "Eg;" with "Example:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/367#-:-KJs0QovMN1lB2qW5MBN:1532634514)*

**Comment by jseldess** [comment]
*[create-database.md, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/367#-KJs06rjWtpE7X6gaonx:-KJs0evuCErBInYBU3WQ:1622332310) ([raw file](https://github.com/cockroachdb/docs/blob/e5bdec4cc3be57f7072cfe59a52ceb13fcf58526/create-database.md#L24)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Let's replace "Eg;" with "Example:"
</details>
Oh, and we might as well use `UTF-8` in the example, since we're giving it preference in the definition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/367)*

**Comment by uptimeDBA** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[create-database.md, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/367#-KJs06rjWtpE7X6gaonx:-KJsMu7PIvER8eN3pK_3:-1457478403) ([raw file](https://github.com/cockroachdb/docs/blob/e5bdec4cc3be57f7072cfe59a52ceb13fcf58526/create-database.md#L24)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Oh, and we might as well use `UTF-8` in the example, since we're giving it preference in the definition.
</details>
Done. `UTF-8` is the official name of the encoding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/367)*

**Comment by jseldess** [comment]
The one downside here, which I didn't see before we merged, is that the `encoding` link in the diagram no longer sends you to the right place in the complete grammar page. On that page, the link is still `opt_encoding_clause`. @mjibson, @uptimeDBA, what should we do about cases like this, where we change the terminology in the statement-specific diagrams but not in the overall grammar?

**Comment by uptimeDBA** [comment]
@jseldess @mjibson 
I'm almost tempted to suggest we don't link to the grammar page. If we expand the diagrams so everything except identifiers (names, etc) and expressions are present on the statement page, with links to any additional page like we have done in the `CREATE TABLE` page for constraints in the parameter descriptions, then it's self contained. I find the links to the grammar page for things like Identifiers  and expressions to be confusing and of little value in understanding the syntax of a statement. Better not to link in the diagram and refer to the [Identifiers](http://cockroachdb.github.io/docs/identifiers.html) page in the description (and maybe have an [Expressions] page that describes them in a user friendly way.)

**Comment by mjibson** [comment]
I agree that in cases like this it shouldn't link to the grammar page.

**Comment by jseldess** [comment]
Sounds good to me, too. I've opened an issue for Matt to deactivate those links in a way that they won't be recreated each time we regenerate grammar diagrams. See https://github.com/cockroachdb/docs/issues/375.

@uptimeDBA, for an "Expressions" page, you can perhaps open an issue with more details about what that would contain?

**Pull request merged**
