### PR TITLE
Add release notes for v21.1.4, v21.1.5

### LINKED ISSUE #10706: v21.1.4 Release Notes
Prep date: tbd
Release date: Jul 19, 2021
SHA candidate: tbd
Release Manager: tbd
Issue: tbd
[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [ ] Run script to generate release notes
- [ ] Update docs site
- [ ] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @jseldess)

### LINKED ISSUE #10707: v21.1.5 Release Notes
Prep date: tbd
Release date: Aug 9, 2021
SHA candidate: tbd
Release Manager: tbd
Issue: tbd
[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [ ] Run script to generate release notes
- [ ] Update docs site
- [ ] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @jseldess)

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #10706.
Fixes #10707.

### CODE REVIEW

**Comment by rmloveland** [comment]
Hi @JuanLeon1 

Batching the v21.1.4 and v21.1.5 release notes for speed

Had some questions (which are also in the files in this PR and marked with `XXX`) which I hope you can answer:

-  Do we need a note in the v21.1.4 notes that says something like "don't use v21.1.4, use v21.1.5 instead ?"
 - Is v21.1.4 a "withdrawn" release?  Asking because that entails doing some other things like removing download links etc.
 - For v21.1.5, is July 2nd the correct release date?
 - In the v21.1.5 notes, should we say something like "users who were on v21.1.4 should upgrade to this bugfix release ASAP" ?

**Comment by JuanLeon1** [comment]
Rich,  
Whether or not to withdraw 21.1.4 depends on how disruptive it is.   If it were not disruptive, I'd vote to withdraw it, but writing notes like you have suggested is good enough.  21.1.4 works for many workloads.

July 2 is the correct date, yes.

Thanks for jumping on this Rich!

**Comment by rmloveland** [comment]
JuanLeon1 ***@***.***> writes:

> Rich,
> Whether or not to withdraw 21.1.4 depends on how disruptive it is. If
> it were not disruptive, I'd vote to withdraw it, but writing notes
> like you have suggested is good enough. 21.1.4 works for many
> workloads.

Sounds good, thanks Juan!

I just pushed an update that basically says "users of v21.1.4 should
upgrade to the v21.1.5 bugfix release as soon as possible" on both
versions' pages.

Do you mind looking at the updated language in the PR and verifying it's
OK?

> July 2 is the correct date, yes.

Noted, thanks!

> Thanks for jumping on this Rich!

Anytime!

**Comment by rmloveland** [comment]
Hey @taroface FYI this PR might change slightly if Juan has any feedback on the "please upgrade" language in both the v21.1.4 and v21.1.5 notes, but otherwise I think the content is ready for docs review

**Review by taroface — APPROVED** [review]
Some nits and questions, but LGTM. Thanks again for taking on these release notes, @rmloveland !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10880#-:-Me0g6hBAuV3PHEgDZYA:bhklien)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JuanLeon1 and @rmloveland)

___
*[releases/v21.1.4.md, line 39 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0dsG58JGlAtYmZnXo:-Me0dsG58JGlAtYmZnXp:b-7avwwb) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L39)):*
> ```Markdown
> ### Security updates
> 
> - Previously, all the logging output to files or network sinks was disabled temporarily while an operator was using the `/debug/logspy` HTTP API, resulting in lost entries and a breach of auditability guarantees. This behavior has been corrected. [#66328][#66328]
> ```

Maybe link "logging" to `../v21.1/logging-overview.html`
___
*[releases/v21.1.4.md, line 39 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0ekgG2-inrSXUbxTD:-Me0ekgG2-inrSXUbxTE:bcdjaxx) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L39)):*
> ```Markdown
> ### Security updates
> 
> - Previously, all the logging output to files or network sinks was disabled temporarily while an operator was using the `/debug/logspy` HTTP API, resulting in lost entries and a breach of auditability guarantees. This behavior has been corrected. [#66328][#66328]
> ```

Does "HTTP API" refer to https://www.cockroachlabs.com/docs/api/cluster/v2.html or is this something else? Just checking on whether this is the terminology we want to use here. cc @mikecrl 
___
*[releases/v21.1.4.md, line 44 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0e4rBAtkGfxQjbbWC:-Me0e4rBAtkGfxQjbbWD:b-q2fuus) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L44)):*
> ```Markdown
> ### SQL language changes
> 
> - Implement the `ST_HasArc` [function](../v21.1/functions-and-operators.html#spatial-functions). This adds better out-of-the-box support for [GeoServer](../v21.1/geoserver.html). [#66531][#66531]
> ```

Implement -> Implemented

function -> builtin function (I think?)
___
*[releases/v21.1.4.md, line 49 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0eJCYEsvaVuofXDjw:-Me0eJCYEsvaVuofXDjx:bhun7sb) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L49)):*
> ```
> infinite floating point values are formatted as `Infinity` rather than `Inf` now.
> ```

```
infinite floating point values are now formatted as `Infinity` rather than `Inf`.
```
___
*[releases/v21.1.4.md, line 50 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0ePi92LjYmxFbaC-l:-Me0ePi92LjYmxFbaC-m:b-nlh4kj) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L50)):*
> ```Markdown
> 
> - The [SQL shell](../v21.1/cockroach-sql.html) now formats times with time zones so that the minutes and seconds offsets are only shown if they are non-zero. Also, infinite floating point values are formatted as `Infinity` rather than `Inf` now. [#66130][#66130]
> - When [log entries](../v21.1/logging-overview.html) are written to disk, the first few header lines written at the start of every new file now report the configured logging format. [#66328][#66328]
> ```

Link "logging format" to `..v21.1/log-formats.html`.
___
*[releases/v21.1.4.md, line 54 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0eydL8j9XK4ke0O7m:-Me0eydMBb9Qe7pp5vCp:bqtbow3) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L54)):*
> ```Markdown
> ### API endpoint changes
> 
> - The `/debug/logspy` HTTP API has changed. The endpoint now returns JSON data by default. If the previous format is desired, the user can pass the query argument `&flatten=1` to the `logspy` URL to obtain the previous flat text format (`crdb-v1`) instead. [#66328][#66328] This change is motivated as follows:
> ```

Same question as above re: "HTTP API"
___
*[releases/v21.1.4.md, line 63 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0f8Z7BRgAS9ezc10S:-Me0f8Z7BRgAS9ezc10T:b-ziehwv) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L63)):*
> ```Markdown
>     - As for the regular `vmodule` command-line flag, the maximum verbosity across all the source code can be selected with the pattern `*=4`.
>     - Note: at most one in-flight HTTP API request is allowed to modify the `vmodule` parameter. This maintains the invariant that the configuration restored at the end of each request is the same as when the request started.
> - The new `/debug/vmodule` API makes it possible for an operator to configure the logging verbosity in a similar way as the SQL [built-in function](../v21.1/functions-and-operators.html) `crdb_internal.set_vmodule()`, or to query the current configuration as in `crdb_internal.get_vmodule()`. Additionally, any configuration change performed via this API can be automatically reverted after a configurable delay. [#66328][#66328] The API forms are:
> ```

built-in -> builtin (I think)
___
*[releases/v21.1.4.md, line 69 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fD7f661QKbRXP-6G:-Me0fD7f661QKbRXP-6H:b1qjm0m) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L69)):*
> ```Markdown
> ### DB Console changes
> 
> - Fixed an issue with displaying more than 100 hours of remaining time on the [jobs page](../v21.1/ui-jobs-page.html). [#66596][#66596]
> ```

jobs page -> Jobs page
___
*[releases/v21.1.4.md, line 73 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fJkKA8o4njIpYz8g:-Me0fJkKA8o4njIpYz8h:bfmkux0) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L73)):*
> ```
> `TimeTZ`  values
> ```

Extra space

Also, I think these are usually formatted either `timestamptz` and `timetz`, or in all caps. Not sure how important that is...
___
*[releases/v21.1.4.md, line 74 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fWDl4_35z1Qtnv6L:-Me0fWDl4_35z1Qtnv6M:b-qni1y7) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L74)):*
> ```Markdown
> 
> - Minute timezone offsets are only displayed in the wire protocol if they are non-zero for `TimestampTZ` and `TimeTZ`  values. Previously, they would always display. [#66130][#66130]
> - Fixed a bug where binary `TimeTZ` values were not being decoded correctly when being sent as a parameter in the wire protocol. [#66130][#66130]
> ```

ditto re: `TimeTZ`
___
*[releases/v21.1.4.md, line 77 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fapVAbZulkBVhOjw:-Me0fapVAbZulkBVhOjx:bbxx912) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L77)):*
> ```Markdown
> - CockroachDB's [SQL shell](../v21.1/cockroach-sql.html) now properly displays results of common array types, for example: arrays of floats, or arrays of strings. [#66130][#66130]
> - Fixed a bug where the `--log='file-defaults: {format: crdb-v1}'` flag was not being handled properly. This bug existed since v21.1.0. [#66328][#66328]
> - Fixed a bug where log entries could be lost while the `/debug/logspy` HTTP API was being used. This bug had existed since CockroachDB v1.1. [#66328][#66328]
> ```

Ditto re: HTTP API
___
*[releases/v21.1.4.md, line 79 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fh8d00v3YZ3eDmQY:-Me0fh8d00v3YZ3eDmQZ:b69ew37) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L79)):*
> ```
> version 20.2.0
> ```

`v20.2.0`
___
*[releases/v21.1.4.md, line 81 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fjCXEpshoTrULMS2:-Me0fjCXEpshoTrULMS3:b-wa4yij) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L81)):*
> ```
> 21.1.1-21.1.3
> ```

`v21.1.1-v21.1.3`
___
*[releases/v21.1.4.md, line 84 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0frDnCZLENbqewzlU:-Me0frDnCZLENbqewzlV:blot2p2) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L84)):*
> ```Markdown
> - Fixed a bug where CockroachDB could encounter an internal error when computing [window functions](../v21.1/window-functions.html) with `ROWS` mode of window framing if the offsets were very large for the `OFFSET FOLLOWING` boundary type. [#66446][#66446]
> - Fixed a bug where using [`ADD COLUMN UNIQUE`](../v21.1/add-column.html) on [`REGIONAL BY ROW` tables](../v21.1/set-locality.html#regional-by-row) did not correctly add the [zone configs](../v21.1/configure-replication-zones.html) for the newly created column index. [#66696][#66696]
> - Fixed a bug where reading from Google Cloud Storage was not using the resuming reader, as a result of which some retryable errors were not being treated as such, and the read would fail. [#66190][#66190]
> ```

retryable -> retriable
___
*[releases/v21.1.4.md, line 87 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fvTQ4tAItPDFPlu0:-Me0fvTQ4tAItPDFPlu1:bpckdo1) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L87)):*
> ```Markdown
> - Fixed a deadlock during [backups](../v21.1/backup.html) and [imports](../v21.1/import.html). [#66773][#66773]
> - Fixed incorrect accounting for statement/transaction sampled [execution statistics](../v21.1/explain-analyze.html). [#66790][#66790]
> - Fixed a bug causing [transactions](../v21.1/transactions.html) to be spuriously aborted in rare circumstances. [#66567][#66567]
> ```

Spuriously!

**Review by rmloveland — COMMENTED** [review]
Thanks for the review Ryan!  I have fixed (almost) everything!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10880#-:-Me1UCxqC7xA2eSRTNEM:b-hav7in)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JuanLeon1, @mikeCRL, and @taroface)

___
*[releases/v21.1.4.md, line 39 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0ekgG2-inrSXUbxTD:-Me1Rpb53UpTpmBRg3f6:b-oebny5) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L39)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Does "HTTP API" refer to https://www.cockroachlabs.com/docs/api/cluster/v2.html or is this something else? Just checking on whether this is the terminology we want to use here. cc @mikecrl 
</blockquote></details>

I'm not sure!  But I'm not seeing a `/debug/*` endpoint documented on that page, so I think we should punt for now
___
*[releases/v21.1.4.md, line 39 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0dsG58JGlAtYmZnXo:-Me1UAz23jQpYdgGzYGX:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L39)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Maybe link "logging" to `../v21.1/logging-overview.html`
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 44 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0e4rBAtkGfxQjbbWC:-Me1SE6yAVlBZg9OQ2eK:b-lbwdxf) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L44)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Implement -> Implemented

function -> builtin function (I think?)
</blockquote></details>

done and done!
___
*[releases/v21.1.4.md, line 49 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0eJCYEsvaVuofXDjw:-Me1SS63D9LDXBtDx1pA:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L49)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> infinite floating point values are formatted as `Infinity` rather than `Inf` now.
> ```

```
infinite floating point values are now formatted as `Infinity` rather than `Inf`.
```
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 50 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0ePi92LjYmxFbaC-l:-Me1SSo17OIZcEvYto5F:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L50)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Link "logging format" to `..v21.1/log-formats.html`.
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 54 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0eydL8j9XK4ke0O7m:-Me1STn87WepHmnIlmxH:b-9po524) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L54)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same question as above re: "HTTP API"
</blockquote></details>

same as above I don't think the `/debug` endpoint is documented there so punting for now! 
___
*[releases/v21.1.4.md, line 63 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0f8Z7BRgAS9ezc10S:-Me1SdZ9-KZ3-LsaZEh-:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L63)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

built-in -> builtin (I think)
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 69 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fD7f661QKbRXP-6G:-Me1SgAw7IVpNnBlT4nJ:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L69)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

jobs page -> Jobs page
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 73 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fJkKA8o4njIpYz8g:-Me1ShNJ9iDzr2TWegf-:buv8n5v) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L73)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> `TimeTZ`  values
> ```

Extra space

Also, I think these are usually formatted either `timestamptz` and `timetz`, or in all caps. Not sure how important that is...
</blockquote></details>

I did a bit of Googling and these appear to be the names of the data types from the point of view of the code that deals with the wire protocol so I went with the casing as-is 
___
*[releases/v21.1.4.md, line 74 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fWDl4_35z1Qtnv6L:-Me1TsNB7w78KmhH3pS_:bnj7hl0) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L74)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

ditto re: `TimeTZ`
</blockquote></details>

same as above
___
*[releases/v21.1.4.md, line 77 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fapVAbZulkBVhOjw:-Me1TuRZ-JzerK-Btpso:bnj7hl0) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L77)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto re: HTTP API
</blockquote></details>

same as above
___
*[releases/v21.1.4.md, line 79 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fh8d00v3YZ3eDmQY:-Me1Ty0s52xuOaA_bd_n:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L79)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> version 20.2.0
> ```

`v20.2.0`
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 81 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fjCXEpshoTrULMS2:-Me1U0wp2UBbpqD40aRv:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L81)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> 21.1.1-21.1.3
> ```

`v21.1.1-v21.1.3`
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 84 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0frDnCZLENbqewzlU:-Me1U46b85ZOf9KFSPsY:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L84)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

retryable -> retriable
</blockquote></details>

Done!
___
*[releases/v21.1.4.md, line 87 at r3](https://reviewable.io/reviews/cockroachdb/docs/10880#-Me0fvTQ4tAItPDFPlu0:-Me1U5-cBJN4DJWcEPac:bz624iu) ([raw file](https://github.com/cockroachdb/docs/blob/7f5706e81ac77ea2ca26ceb751c55418a5e600af/releases/v21.1.4.md#L87)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Spuriously!
</blockquote></details>

SPURIOUSLY YO

**Comment by rmloveland** [comment]
Gonna merge these now - can always edit later if needed

**Pull request merged**
