### PR TITLE
Mesos tutorial

### LINKED ISSUE #507: Mesosphere: DC/OS Integration
We need this. More details TBD.

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #507

### CODE REVIEW

**Comment by a-robinson** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0Awj_vObVN9c9SfTWx:-L0Awj_vObVN9c9SfTWy:b-99vnlx) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L19)):*
> ```Markdown
> ### Requirements
> 
> - At this time, only CockroachDB v1.0.x is supported. Support for subsequent versions of CockroachDB is comming soon.
> ```

s/comming/coming

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AwlYA_kStcDXLHtmu:-L0AwlYA_kStcDXLHtmv:b-kft162) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L32)):*
> ```Markdown
> 
> - The `cockroachdb` DC/OS service has been tested only on DC/OS versions 1.9 and 1.10.
> - Accessing the CockroachDB Admin UI from inside or outside the DC/OS cluster is not possible at this time.
> ```

It is technically possible, it's just not easy. You don't have the change that part of the phrasing if you don't want, but I would ask that you remove the words "inside or" from this sentence, since it actually is easy to access the admin UI from inside the cluster (it's just usually not easy to run a web browser hooked up to your monitor from inside the cluster).

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0Ax9N5cC9e4evWFQp8:-L0Ax9N5cC9e4evWFQp9:ba0aaxo) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L36)):*
> ```Markdown
> - Neither volume type nor volume size requirements may be changed after initial deployment.
> - Rack placement and awareness are not supported at this time.
> - Storage of backups, and restoring from backups, in datastores other than S3 is not yet supported.
> ```

Should we be more specific here? Enterprise backups can be stored/restored to/from anywhere they normally can be. It's just the DCOS-specific `cockroach dump` wrapper that only knows how to speak to AWS.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AxpKyPRlPB-iCNSu2:-L0AxpKyPRlPB-iCNSu3:bb41d3c) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L106)):*
> ```Markdown
>     - A `vip` address, which is an HA-enabled hostname for accessing any of the instances. You'll use the `vip` address in the next step.
> 
>     In general, the `.mesos` endpoints will only work from within the same DC/OS cluster. From outside the cluster, you can either use the direct IPs or set up a proxy service that acts as a frontend to your CockroachDB instance. For development and testing purposes, you can use [DC/OS Tunnel](https://dcos.io/docs/latest/developing-services/tunnel/) to access services from outside the cluster, but this option is not suitable for production use.
> ```

Did you get the DC/OS Tunnel working? I'd expect that we could use it to access the admin UI, but never personally got it working so I didn't feel comfortable recommending it.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 224 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AyQp8-HhmQZETxHgU:-L0AyQp8-HhmQZETxHgV:b2vic7q) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L224)):*
> ```Markdown
> ### Restart a Node
> 
> You can restart a node while keeping it as its current location with its current persistent volume data. This may be thought of as similar to restarting a system process, but it also deletes any data that is not on a persistent volume.
> ```

s/keeping it as/keeping it at/

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 253 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0Ayey3fMoEPx41YTNG:-L0Ayey3fMoEPx41YTNH:bil1ifz) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L253)):*
> ```Markdown
> ### Replace a Node
> 
> You can move a node to a new system and discard the persistent volumes at the prior system to be rebuilt at the new system. Nodes are not moved automatically, so this step must be performed performed, for example, before a system is offlined or when a system has already been offlined.
> ```

s/performed performed/performed/

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 344 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AzEdAC-eWhhBYRyQ2:-L0AzEdAC-eWhhBYRyQ3:b-cfz0vv) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L344)):*
> ```Markdown
> By default, the AWS access and secret keys will be pulled from your environment via the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables, respectively. You must either have these environment variables defined or specify the flags for the backup to work.
> 
> ## Step 9. Stop the cluster
> ```

As loosely mentioned in our Slack DMs, we might want to also mention cleaning up the DC/OS cluster itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0Awj_vObVN9c9SfTWx:-L0BQ9mzXyvrlanrz0Xc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L19)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/comming/coming
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AwlYA_kStcDXLHtmu:-L0BQAe2XYx_BPWy7kQv:b6xrz8f) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L32)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

SSH tunneling is easier than running a browser inside the cluster. I did `ssh -L 8123:cockroachdb-0-node-init.cockroachdb.mesos:8123 -t core@${PUBLIC_MESOS_NODE}` and then accessed the UI at localhost:8123. 
</blockquote></details>

I didn't test this. I'll spin up another cluster, test it, and if it works well, add it as another"Monitor the cluster" step or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0Ax9N5cC9e4evWFQp8:-L0BT15_koMtl0q19ybW:b-tui5j3) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L36)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Should we be more specific here? Enterprise backups can be stored/restored to/from anywhere they normally can be. It's just the DCOS-specific `cockroach dump` wrapper that only knows how to speak to AWS.
</blockquote></details>

Removed this bullet and added more detail to the backup/restore section. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 106 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AxpKyPRlPB-iCNSu2:-L0BT7prgaYrXpKlnPPt:bf8c6xl) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L106)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Did you get the DC/OS Tunnel working? I'd expect that we could use it to access the admin UI, but never personally got it working so I didn't feel comfortable recommending it.
</blockquote></details>

I'll test and document.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 224 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AyQp8-HhmQZETxHgU:-L0BTD6m7He6PYKZKc-H:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L224)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/keeping it as/keeping it at/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 253 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0Ayey3fMoEPx41YTNG:-L0BTG0HCjAqrEeOKaYq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L253)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/performed performed/performed/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 344 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AzEdAC-eWhhBYRyQ2:-L0BMl-hwbarK80wqndK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L344)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

As loosely mentioned in our Slack DMs, we might want to also mention cleaning up the DC/OS cluster itself.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by a-robinson** [comment]
:lgtm: pending the couple UI-related comments

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AwlYA_kStcDXLHtmu:-L0BUVkCg0uTsoiy8Lcy:b44tpx) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L32)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I didn't test this. I'll spin up another cluster, test it, and if it works well, add it as another"Monitor the cluster" step or something.
</blockquote></details>

👍

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-:-L0BUr5BrcJAFNaHjVBF:b-gjx2qf)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0AwlYA_kStcDXLHtmu:-L0BktPHXblGtZYRKa0B:bhbq0bc) ([raw file](https://github.com/cockroachdb/docs/blob/48c5ddd2e2d18b7285856ba3034618ea5b8e6ecd/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L32)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

👍
</blockquote></details>

Wohoo. Got it work. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by a-robinson** [comment]
Nice! Just a couple small comments on the UI bits, otherwise this is good to go

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 181 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0CCDvLidDbtDNL3t9I:-L0CCDvLidDbtDNL3t9J:ban70g4) ([raw file](https://github.com/cockroachdb/docs/blob/8bb1c76a52b45cd1c8ac7a76084b1b8598fab485/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L181)):*
> ```Markdown
>     ~~~
> 
> 3. Discover the http endpoints for your CockroachDB cluster:
> ```

This step isn't technically needed since it's always going to be the same address -- we could just tell people to directly go to `http.cockroachdb.l4lb.thisdcos.directory.mydcos.directory`. Your call on whatever you think is nicer.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0CC6apkUYE0Cvo4cbz:-L0CC6apkUYE0Cvo4cc-:b-u1074z) ([raw file](https://github.com/cockroachdb/docs/blob/8bb1c76a52b45cd1c8ac7a76084b1b8598fab485/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L204)):*
> ```Markdown
>     ~~~
> 
> 3. In a browser, go to the `vip` address with `.mydcos.directory` appended before the `:80` port, e.g., `http.cockroachdb.l4lb.thisdcos.directory.mydcos.directory:80`.
> ```

s/3/4/, unless you remove the step above

Also, the `:80` isn't needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-:-L0CCQC1RtUf6KWPINtG:bhlgag5)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 181 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0CCDvLidDbtDNL3t9I:-L0Cqt31mR1uyL2IEe6a:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8bb1c76a52b45cd1c8ac7a76084b1b8598fab485/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L181)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This step isn't technically needed since it's always going to be the same address -- we could just tell people to directly go to `http.cockroachdb.l4lb.thisdcos.directory.mydcos.directory`. Your call on whatever you think is nicer.
</blockquote></details>

Done.

---

*[v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-L0CC6apkUYE0Cvo4cbz:-L0Cqtf_qLp3UlZYI8Fk:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8bb1c76a52b45cd1c8ac7a76084b1b8598fab485/v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md#L204)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/3/4/, unless you remove the step above

Also, the `:80` isn't needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277)*

**Comment by jseldess** [comment]
TFTR, @a-robinson!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2277#-:-L0CrKqieLSuBdZ_wVPz:blms7sm)*

**Pull request merged**
