### PR TITLE
Alternate docs homepage for a/b testing

### PR DESCRIPTION
**Pull request by jseldess**
This PR proposes an alternate approach for the docs homepage for a/b testing against the current docs homepage. The intention is to highlight ease of use and compatibility in response to Marketing's dev interviews and to bubble up more prod-relevant topics around deployment and integration. 

- Created new, alternate homepage (`home.md`).
- Adjusted styling to affect `home.md` but not `index.md`.
- Added optimizely script to new homepage and to all pages linked from "cards" on the `home.md`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1034)

### CODE REVIEW

**Comment by dianasaur323** [comment]
@jseldess This looks excellent! The one comment I have is that "Connect" and "Examine" seem a little vague. 

Perhaps "Build an app" - Connect with any compatible PostgreSQL driver
Maybe something like "Explore" - See how we provide replication, easy scaling, and fault-resistance built in

**Comment by swatikumar16** [comment]
I really like the idea of using cards! I'd say adding some kind of comparison module will likely be valuable. We may also need to be slightly more explicit with the big text on each card (start, connect, examine, etc.). Someone skimming seems unlikely to read the detail text, so we could possibly need to make it clear what this means. So maybe "Test" or "Build Test App" rather than "Connect" for clarity? Thoughts?

**Comment by jseldess** [comment]
@dianasaur323, @swatikumar16, thanks for the feedback! I actually started with more explicit big text and was trying these one-word version on a hunch. I'll revert and ask for another review.

**Comment by dianasaur323** [comment]
@jseldess Awesome! Thanks. The only nitpick I have is that "Reduce operator overhead even more" is a little vague, but I'm not sold that we need to worry about wordsmithing that too much.

On the paragraph, it is definitely long, but I do think it adds value to have it there, if only to have those keywords on that page. Perhaps we could delete "disk, machine, rack, and even datacenter failures" and just go with "failures". We also talk about strongly consistent twice. I think just saying "ACID transactions" is good enough. We can also delete "for structuring, manipulating, and querying data."

**Comment by dianasaur323** [comment]
Woohoo! The paragraph reads a little smoother now. Did you want to remove strongly consistent in front of ACID transactions? I don't feel strongly about it, since it reads fine now.

**Comment by jseldess** [comment]
@dianasaur323, yep, shorted that to just "supports ACID transactions". New link will be posted in a moment. Also not that I reworked the Orchestration subtext a bit. Thanks!

**Comment by dianasaur323** [comment]
LGTM!

**Comment by jess-edwards** [comment]
@jseldess LGTM!

This looks awesome. LATM. 
=)

**Comment by sploiselle** [comment]
:lgtm:, as well. This is a really phenomenal redesign.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1034#-:-KbXAd0LX_znd6TK_uYW:bk7pkbt)*

**Comment by kuanluo** [comment]
@jseldess 

Looks great! Two feedback:

1. Agree with @swatikumar16 that it would be a huge value add to add a comparison module somewhere. 
2. On my 13in screen, the titles of the second row of cards are "below the fold." Since the illustrations aren't necessarily value-add, I would love to see if Deploy, Orchestrate and Monitor could be more visible. An easy solution would be to make the illustrations a little smaller. Or we can consider tweak the top paragraph somehow to make more room for the bottom modules. Screenshot of my screen below:
image

Thank you!

**Comment by jseldess** [comment]
Thanks, @jess-edwards and @sploiselle.

@kuanluo, I reduced the image size as well as the padding above the headings within the "cards". They're now a bit less rectangular. Is the second row more visible for you now? 

I sort of like it, but interested in everyone else's general opinion about this change, too. New link will be posted shortly.

**Comment by kuanluo** [comment]
@jseldess I like this very much! A lot more options are more visible right on the homepage.

**Comment by jseldess** [comment]
All, after chatting with @swatikumar16, we're taking a different approach. This PR adds a second, alternate homepage (`home.md`) that Optimizely will automatically 50% of users to when they land on cockroachlabs.com/docs. Once tests are green, I'll merge this, and then Swati will start the test, probably tomorrow.

**Comment by kuanluo** [comment]
Just to clarify, @swatikumar16 @jseldess, we're A/B testing the existing docs homepage with the new design you proposed?

**Comment by jseldess** [comment]
That's right, @kuanluo.

**Comment by kuanluo** [comment]
That's awesome. Look forward to the result, @jseldess !

**Pull request merged**
