### PR TITLE
DOC-3463 add rebalancing ts metrics

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-3463

- Adds two new `rebalancing` metrics.

Note:
- Other `rebalancing` metrics appear to be present in source code, but are not currently presented on `metric-names.md`. DOCS will be updating this full list with missing metrics post v22.2 GA. This just FYI: Please limit scope of _this_ review to these two specific metrics: any others missing will be handled out of band. Thanks!

Suggest:
- Consider adding "over the last 30 minutes" to your `metrics.go` description. DOCS (will soon) populates `metric-names.md` exclusively from `chartcatalog`, which means we can only present the descriptions included therein for these metrics (and not hand-tune). Rate per second average is only useful if cliff is known: recommend including it directly in your description.

Staging:
- [_includes/v22.2/metric-names.md](https://deploy-preview-15441--cockroachdb-docs.netlify.app/docs/v22.2/ui-custom-chart-debug-page#available-metrics)

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
Lgtm.

Ack on defining the period of time that is rated. I will file an issue and update.

**Comment by andf-crl** [comment]
@kvoli TYFR!

**Review by MichaelTrestman — APPROVED** [review]
LGTM

**Comment by andf-crl** [comment]
TYFR!

**Pull request merged**
