### PR TITLE
Added new ALTER CHANGEFEED  to v22.1 docs

### PR DESCRIPTION
**Pull request by kathancox**
Fixes [DOC-2753](https://cockroachlabs.atlassian.net/browse/DOC-2753) [DOC-2918](https://cockroachlabs.atlassian.net/browse/DOC-2918) [DOC-2601](https://cockroachlabs.atlassian.net/browse/DOC-2601) [DOC-2737](https://cockroachlabs.atlassian.net/browse/DOC-2737)

- Added `ALTER CHANGEFEED` sql page
- Updated CDC overview page to mention
- Create and Configure changefeed page updated
- Changefeed sink page

### CODE REVIEW

**Comment by kathancox** [comment]
Hey @amruss, @sherman-grewal Here are the docs for `ALTER CHANGEFEED`. Few things to note, the SQL diagram will be updated in either a fast-follow PR, or, I will be able to add it into this PR next week. Also, the known limitations definitely need your eyes! I gathered those from issues and such, thanks

**Review by sherman-grewal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @amruss and @kathancox)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/13344#-MzH9hFk3Gz4B00Voe6Q:-MzH9hFk3Gz4B00Voe6R:b3tvbw7) (no related file):*
This looks awesome! Thanks for working on this :raised_hands: Let me know when the SQL diagram is ready

---
___
*[v22.1/alter-changefeed.md, line 34 at r3](https://reviewable.io/reviews/cockroachdb/docs/13344#-MzHFrlh91CSORR3SQGT:-MzHFrlh91CSORR3SQGU:bqi580) ([raw file](https://github.com/cockroachdb/docs/blob/6b26d6f033da6724236f1b5c87c48c2cfae3c48f/v22.1/alter-changefeed.md#L34)):*
> ```Markdown
> ----------------------------------------+-------------------------------------------------------------------------------------------------------------------------
> `job ID`                               | Include the `job ID` to specify the changefeed job to modify.
> `WITH`                                 | Use `ADD <table> WITH initial_scan` to perform a scan when adding a target. By default, there is not an initial scan after an `ALTER CHANGEFEED` statement regardless of whether [`initial_scan`](create-changefeed.html#initial-scan) was set with the **original** `CREATE CHANGEFEED` statement. It is also possible to explicitly state `ADD <table> WITH no_initial_scan` (although the default makes this unnecessary). See further details in the [Options](#scan-details) section.
> ```

We can actually apply `initial_scan`/`no_initial_scan` to multiple tables with one `WITH` clause. For example: The following is valid syntax:

`ALTER CHANGEFEED <job_id> ADD foo, bar WITH initial_scan`

Hence it might be worth saying `ADD <tables> WITH initial_scan` 
___
*[v22.1/alter-changefeed.md, line 48 at r3](https://reviewable.io/reviews/cockroachdb/docs/13344#-MzHAyRB48hjH7EHy1un:-MzHADg-6jLW6-XZMcI3:bfq017f) ([raw file](https://github.com/cockroachdb/docs/blob/6b26d6f033da6724236f1b5c87c48c2cfae3c48f/v22.1/alter-changefeed.md#L48)):*
> ```Markdown
> - You can set a different [sink URI](changefeed-sinks.html#sink-uri) for an existing changefeed with the `sink` option. It is **not** possible to change the sink type. For example, you can use `SET sink = 'gs://{BUCKET NAME}?AUTH=IMPLICIT'` to use a different Google Cloud Storage bucket. However, you cannot use the `sink` option to move to Amazon S3 (`s3://`) or Kafka (`kafka://`). See the [Set options on a changefeed](#set-options-on-a-changefeed) example.
> 
> - The [`CREATE CHANGEFEED`](create-changefeed.html#options) options are compatible with `SET`/`UNSET`. This excludes the [`cursor`](create-changefeed.html#cursor-option) option, which you **cannot** use in an `ALTER CHANGEFEED` statement.  
> ```

We recently added changefeed options `end_time` and `initial_scan_only`, and both of these options cannot be altered.
___
*[v22.1/alter-changefeed.md, line 189 at r3](https://reviewable.io/reviews/cockroachdb/docs/13344#-MzHGWFQ0GjMuXThVpq3:-MzHGWFQ0GjMuXThVpq4:b-a3bqyo) ([raw file](https://github.com/cockroachdb/docs/blob/6b26d6f033da6724236f1b5c87c48c2cfae3c48f/v22.1/alter-changefeed.md#L189)):*
> ```Markdown
> ~~~
> 
> ## Known Limitations
> ```

Another limitation is that we do not keep track of which tables you individually applied `initial_scan` or `no_initial_scan`. For example, if the user performs

`ALTER CHANGEFEED <job_id> ADD foo WITH initial_scan`

Although we keep track of the fact that `foo` was added to the changefeed, we do not keep track of the fact that an `initial_scan` was applied to `foo`.

**Review by amruss — APPROVED** [review]
LGTM

**Comment by kathancox** [comment]
Hey @sherman-grewal, I'm going to push this through to docs team review, but feel free to add further feedback, if you have any.

**Review by sherman-grewal — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @kathancox)

**Review by andf-crl — APPROVED** [review]
Nice work! Examples are especially helpful!

Only small language recommendations from me! Feel free to merge after you've considered, or run it past me again if you prefer. Up to you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13344#-:-N-TggehDGal87CvdKZJ:b-xnv7sg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

___
*[v22.1/alter-changefeed.md, line 10 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TM8WF-bfaPeOty1Sc:-N-TM8WF-bfaPeOty1Sd:b-7ww7a1) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L10)):*
> ```Markdown
> {% include enterprise-feature.md %}
> 
> <span class="version-tag">New in v22.1:</span> The `ALTER CHANGEFEED` statement modifies an existing changefeed. You can use `ALTER CHANGEFEED` to do the following:
> ```

Let's link the first instance of "changefeed" to its overview / intro page: use-changefeeds.html



_Code quote:_
```Markdown
changefeed
```
___
*[v22.1/alter-changefeed.md, line 19 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TMQ1nB0GT4hMJVir_:-N-TMQ1nB0GT4hMJVira:b-371a8x) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L19)):*
> ```Markdown
> The statement will return a job ID and the new job description.
> 
> It is necessary to [**pause**](pause-job.html) a changefeed before running the `ALTER CHANGEFEED` statement against it. For an example of creating a changefeed and then modifying it with `ALTER CHANGEFEED`, see [Modify a changefeed](#modify-a-changefeed).
> ```

[ nit ]: "for an example of <gerund>" is awkward (but would be fine for "for an example of a <noun>"). How about something like:

"For an example of a changefeed modification using `ALTER CHANGEFEED`, see ... "
___
*[v22.1/alter-changefeed.md, line 31 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TSmVzDZPztfziEwp6:-N-TSmVzDZPztfziEwp7:b-qa8l7y) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L31)):*
> ```Markdown
> Parameter                               | Description
> ----------------------------------------+-------------------------------------------------------------------------------------------------------------------------
> `job ID`                               | Include the `job ID` to specify the changefeed job to modify.
> ```

This can be simplified (in similar format to ADD below):

"Specify the changefeed `job_id` to modify."

Using `job_id` to match output of `SHOW CHANGEFEED JOB` column header.

Q: should this parameter (column 1 above) be `job_id` to match?
___
*[v22.1/alter-changefeed.md, line 32 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TSSnI1ZJ_GExmc9pr:-N-TSSnJ6EcRP9y1R6BR:b-3nkdef) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L32)):*
> ```Markdown
> ----------------------------------------+-------------------------------------------------------------------------------------------------------------------------
> `job ID`                               | Include the `job ID` to specify the changefeed job to modify.
> `WITH`                                 | Use `ADD {tables} WITH initial_scan` to perform a scan when adding a target table or multiple target tables. By default, there is not an initial scan after an `ALTER CHANGEFEED` statement regardless of whether [`initial_scan`](create-changefeed.html#initial-scan) was set with the **original** `CREATE CHANGEFEED` statement. It is also possible to explicitly state `ADD {tables} WITH no_initial_scan` (although the default makes this unnecessary). See further details in the [Options](#scan-details) section.
> ```

Suggest switching things around here to make this more of an active statement:

"""
The `ALTER CHANGEFEED` statement does not perform an initial scan by default, regardless of whether [`initial_scan`](create-changefeed.html#initial-scan) was set with the **original** `CREATE CHANGEFEED` statement.
"""

The parenthetical "(although the default makes this unnecessary)" can also likely be safely integrated into the statement itself:

"""
It is also possible to explicitly issue `ADD {tables} WITH no_initial_scan`, though this is the default behavior.
"""



_Code quote:_
```Markdown
By default
```
___
*[v22.1/alter-changefeed.md, line 35 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TXWCZ11sc4zoS8KsG:-N-TXWCZ11sc4zoS8KsH:bs30ziw) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L35)):*
> ```Markdown
> `ADD`                                  | Add a new target table to a changefeed. See the [example](#add-targets-to-a-changefeed).
> `DROP`                                 | Drop a target table from a changefeed. It is **not** possible to drop all target tables from a changefeed. See the [example](#drop-targets-from-a-changefeed).
> `SET`                                  | Set new options on a changefeed. `SET` uses the [`CREATE CHANGEFEED`](create-changefeed.html#options) options. The following [Options](#options) section provides more detail on these. **Note:** There are some [exceptions](#option-exceptions) to the compatible options with `ALTER CHANGEFEED`. To set options, see the [example](#set-options-on-a-changefeed).
> ```

Here we use "options" a lot:
- SET options for ALTER CHANGEFEED
- SET uses the same options as CREATE CHANGEFEED
- the Options section below provides more detail on these options
- there are some exceptions to the options, listed below under Options

Here's a slight simplification:

"""
Set new options on a changefeed. `ALTER CHANGEFEED ... SET ...` uses the [`CREATE CHANGEFEED`](create-changefeed.html#options) options, with some [exceptions](#option-exceptions). See the [example](#set-options-on-a-changefeed).
"""

What do you think?
___
*[v22.1/alter-changefeed.md, line 36 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TZxFO6A4S-rIs2bMH:-N-TZxFO6A4S-rIs2bMI:b-nzkvcg) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L36)):*
> ```Markdown
> `DROP`                                 | Drop a target table from a changefeed. It is **not** possible to drop all target tables from a changefeed. See the [example](#drop-targets-from-a-changefeed).
> `SET`                                  | Set new options on a changefeed. `SET` uses the [`CREATE CHANGEFEED`](create-changefeed.html#options) options. The following [Options](#options) section provides more detail on these. **Note:** There are some [exceptions](#option-exceptions) to the compatible options with `ALTER CHANGEFEED`. To set options, see the [example](#set-options-on-a-changefeed).
> `UNSET`                                | Remove options that were set with the original `CREATE CHANGEFEED` statement. See the [example](#unset-options-on-a-changefeed).
> ```

It looks like UNSET is also subject to the same options / exceptions as described for SET. Tiny mention of this here should suffice, maybe something like:

"""
Remove options that were set with the original `CREATE CHANGEFEED` statement. `ALTER CHANGEFEED UNSET ...` uses the [`CREATE CHANGEFEED`](create-changefeed.html#options) options, with some [exceptions](#option-exceptions). See the [example](#unset-options-on-a-changefeed).
"""
___
*[v22.1/alter-changefeed.md, line 38 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TRYTR-4vHqzMHJO5D:-N-TRYTS8qy8nA8Qu_b2:be0a7hv) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L38)):*
> ```Markdown
> `UNSET`                                | Remove options that were set with the original `CREATE CHANGEFEED` statement. See the [example](#unset-options-on-a-changefeed).
> 
> When the listed parameters are used together in the same statement, all changes will apply at the same time—there is not a particular order of operations.
> ```

"-there is not ..." can probably be removed.
___
*[v22.1/alter-changefeed.md, line 44 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TZoFw9N0xCnhbgQvn:-N-TZoFw9N0xCnhbgQvo:b-dnvzbv) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L44)):*
> ```Markdown
> Consider the following when specifying options with `ALTER CHANGEFEED`:
> 
> - You can set a different [sink URI](changefeed-sinks.html#sink-uri) for an existing changefeed with the `sink` option. It is **not** possible to change the sink type. For example, you can use `SET sink = 'gs://{BUCKET NAME}?AUTH=IMPLICIT'` to use a different Google Cloud Storage bucket. However, you cannot use the `sink` option to move to Amazon S3 (`s3://`) or Kafka (`kafka://`). See the [Set options on a changefeed](#set-options-on-a-changefeed) example.
> ```

This practical example is really helpful, thanks!
___
*[v22.1/alter-changefeed.md, line 54 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-T_ewq6efHIUmHUomL:-N-T_ewq6efHIUmHUomM:b3uv23z) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L54)):*
> ```Markdown
> 
>     ~~~ sql
>     ALTER CHANGEFEED {job ID} ADD movr.rides, movr.vehicles WITH initial_scan SET updated UNSET resolved;
> ```

Curiously, UNSET isn't picked up by the `sql` code highligher! Something for another day, I'd say.
___
*[v22.1/alter-changefeed.md, line 57 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-Ta2ue3lUW_c2Sa2Bc:-N-Ta2ue3lUW_c2Sa2Bd:b-ouoivj) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L57)):*
> ```Markdown
>     ~~~
> 
>     Adding the `initial_scan` option will trigger an initial scan on the newly added table. Even though the default behavior during an `ALTER CHANGEFEED` statement is that there will be no initial scan, you can still explicitly define that there should be no initial scan by adding the `no_initial_scan` option in the same way. The changefeed does not track the application of this option post scan. This means that you will not see the option listed in output or after a `SHOW CHANGEFEED JOB` statement.
> ```

We discuss the concept of the initial scan a bunch, but don't link out to a resource describing what it is. I couldn't find any resource that talks about it, but if you know of a good resource that answers the question: why would I want to run an initial scan when I ALTER CHANGEFEED, it'd be great to include it! If, like me, you don't know of one, we can skip.

Also a phrasing recommendation, similar to above regarding the default behavior:

"""
Adding the `initial_scan` option will trigger an initial scan on the newly added table. You may also explicitly define `no_initial_scan`, though this is already the default behavior.
"""
___
*[v22.1/alter-changefeed.md, line 147 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-Tc4h29drLYf71Qad1:-N-Tc4h33spsbj-6Z2aG:b-7ukzab) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L147)):*
> ```Markdown
> {% include_cached copy-clipboard.html %}
> ~~~ sql
>  ALTER CHANGEFEED {job ID} ADD movr.rides, movr.vehicles;
> ```

[ nit ] Should "job ID" in code examples be "job_id" ? Fine to leave it "job ID" in descriptions imo.
___
*[v22.1/alter-changefeed.md, line 168 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TcN3f7kic4zeuHSDc:-N-TcN3f7kic4zeuHSDd:b-4cmh9b) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L168)):*
> ```Markdown
> ~~~
> 
> `ALTER CHANGEFEED ... SET` can implement the options listed on the [`CREATE CHANGEFEED`](create-changefeed.html#options) page. For details on the few exceptions to this, see the [Options](#options) section on this page.
> ```

Similar to above, I would recommend:

"""
`ALTER CHANGEFEED ... SET ...` uses the [`CREATE CHANGEFEED`](create-changefeed.html#options) options, with some [exceptions](#option-exceptions).
"""
___
*[v22.1/alter-changefeed.md, line 179 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TdCHK3ied9Ey-ZPIu:-N-TdCHK3ied9Ey-ZPIv:b33cleq) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L179)):*
> ```Markdown
> ~~~
> 
> The type (or scheme) of the sink **cannot** change. That is, if the changefeed was originally sending messages to `kafka://`, then you can change to a different Kafka URI. For cloud storage sinks, the cloud storage scheme must remain the same (e.g., `s3://`).
> ```

I know what you mean here ( e.g `s3://` must remain `s3://`, no sudden GCP sinks!) but I think the following small edits help to clarify:

"""
The type (or scheme) of the sink **cannot** change. That is, if the changefeed was originally sending messages to `kafka://`, for example, then you can only change to a different Kafka URI. Similarly, for cloud storage sinks, the cloud storage scheme must remain the same (e.g., `s3://`), but you can change to a different storage sink on the same cloud provider.
"""



_Code quote:_
```Markdown
(e.g., `s3://`)
```

**Review by andf-crl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

___
*[v22.1/alter-changefeed.md, line 19 at r5](https://reviewable.io/reviews/cockroachdb/docs/13344#-N-TMQ1nB0GT4hMJVir_:-N-Th8hN4YVIV4Ha1hR6:b-atphvm) ([raw file](https://github.com/cockroachdb/docs/blob/728a95666d5956409528ac774c89219feec3ed4b/v22.1/alter-changefeed.md#L19)):*
<details><summary><i>Previously, andf-crl wrote…</i></summary><blockquote>

[ nit ]: "for an example of <gerund>" is awkward (but would be fine for "for an example of a <noun>"). How about something like:

"For an example of a changefeed modification using `ALTER CHANGEFEED`, see ... "
</blockquote></details>

Reviewable ate my $gt, $lt. Here's is this line with less text dissappeared!

[ nit ]: "for an example of [gerund]" is awkward (but would be fine for "for an example of a [noun]"). How about something like:

"For an example of a changefeed modification using ALTER CHANGEFEED, see ... "

**Comment by kathancox** [comment]
TFTR Andrew, I pretty much incorporated all of your feedback. Yes, it's unfortunate re the `UNSET` sql highlighting — I wonder if there are examples of that elsewhere in code examples. That is, a keyword not highlighting. Re `initial_scan` I have linked out to the options table on `CREATE CHANGEFEED`, which will provide some more color, but I do think backfills and scanning in changefeeds is something that we might build out in the coming releases for docs.

But yes, thanks for tightening up that language. It's funny when you want to create a changefeed, modify a changfeed, pause a changefeed, use options, many options, changefeed, changefeed in one sentence... it gets quite hypnotic! So thanks for that :-)

**Pull request merged**
