### PR TITLE
SERIAL type

### LINKED ISSUE #356: document SERIAL column type
Added in https://github.com/cockroachdb/cockroach/pull/7032.

Some notes to start with:

A SERIAL column is an INT column with a DEFAULT that is unique per row. Notably, ours is a bit different than Postgres's SERIAL and MySQL's AUTO_INCREMENT, both of which approximate a sequence starting at 1 (or maybe 0?).

Our implementation covers the essential uniqueness property, but the differences may be jarring to users so they should be called out in the docs. One important point to include is that there are two common misconceptions with Postgres's SERIAL and MySQL's AUTO_INCREMENTING. They do have holes and they are not strictly increasing.

#### Example of hole:

    CREATE TABLE ab (a SERIAL PRIMARY KEY, b INT);
    BEGIN; INSERT INTO ab (b) VALUES (1); ROLLBACK;
    BEGIN; INSERT INTO ab (b) VALUES (2); COMMIT;
    SELECT * from ab;
     a | b
    ---+---
     2 | 2

#### Example of out-of-order:

In client 1:

    CREATE TABLE ab (a SERIAL PRIMARY KEY, b INT);
    BEGIN; INSERT INTO ab (b) VALUES (1); SELECT * FROM ab;

In client 2:

    BEGIN; INSERT INTO ab (b) VALUES (2); COMMIT;

In client 3:

    SELECT * FROM ab;
     a | b
    ---+---
     2 | 2

In client 1:

    COMMIT;

In client 3:

    SELECT * FROM ab;
     a | b
    ---+---
     1 | 1
     2 | 2

Note the `(2, 2)` was committed before `(1, 1)`.

### PR DESCRIPTION
**Pull request by jseldess**
Adding docs for the new `SERIAL` type. Fixes #356.

HTML version: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/serial.html

@paperstreet, @petermattis, not sure if the last example is clear enough.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/362)

### CODE REVIEW

**Comment by uptimeDBA** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[serial.md, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJnLtR9tO6-UhiOpniR:-KJnLtR9tO6-UhiOpniS:1110213181) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L10)):*
> ```Markdown
> The default value for a `SERIAL` column is the combination of the insert timestamp and the ID of the node executing the insert. This combination is guaranteed to be globally unique, and because value generation does not require talking to other nodes, it is much faster than sequentially auto-incrementing a value, which requires distributed coordination.
> 
> {{site.data.alerts.callout_info}}This data type is <strong>experimental</strong>. We believe it is a better solution than PostgeSQL's <code>SERIAL</code> and MySQL's <code>AUTO_INCREMENT</code> types, both of which auto-increment integers but not necessarily in a strictly sequential fashion (see the <a href="#auto-incrementing-is-not-always-sequential">Auto-Incrementing Is Not Always Sequential</a> example below). However, if you find that this feature is incompatible with your application, please <a href="https://github.com/cockroachdb/cockroach/issues">open an issue</a> or <a href="https://gitter.im/cockroachdb/cockroach">chat with us on Gitter</a>.{{site.data.alerts.end}}
> ```

The name(s) for this feature across all databases I'm aware of have caused no end of grief between DBA's and developers. The **only** thing this type of column can guarantee is uniqueness.  (and even that can be called into question if you're allowed to insert your own values.) There can be gaps as values are consumed even if the transaction is rolled back (as the example shows). Are the values strictly increasing based on transaction time? In the case of Oracle, sequence values can appear out of transaction order due to multi instances and caching.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/362)*

**Comment by paperstreet** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[serial.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpTCFTCin8Mvrdx4NY:-KJpTCFTCin8Mvrdx4NZ:-236841309) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L46)):*
> ```Markdown
> ~~~
> 
> When we insert 3 rows without column `a` values and return the new rows, we see that each row has defaulted to a unique value in column `a`. 
> ```

"without column `a` values" reads a bit awkward to me

---

*[serial.md, line 59 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpT_vGONkVGHT-o7rp:-KJpT_vGONkVGHT-o7rq:-1354761348) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L59)):*
> ```Markdown
> ~~~
> 
> Of course, we can explicitly insert an integer value into the `SERIAL` column as long as it meets the unique and non-null constraints.
> ```

Not sure we want to call this out in the docs. If you're using a SERIAL column, it's generally because you're not manually specifying the ids. Same for "## Format" above

---

*[serial.md, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpUbttuUEyM7TM3q-Y:-KJpUbttuUEyM7TM3q-Z:-444808379) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L73)):*
> ```Markdown
> ~~~
> 
> ### Auto-Incrementing Is Not Always Sequential
> ```

Did we cut the out of order example?

---

*[serial.md, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpTstmqCILIiMP3BhF:-KJpTstnj5E2_rHW3-64:195797575) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L75)):*
> ```Markdown
> ### Auto-Incrementing Is Not Always Sequential
> 
> Some people assume that the auto-incrementing types in PostgreSQL and MySQL generate strictly sequential values that provide an accurate count of rows in a table. In fact, each insert increases the sequence by one, even when the insert is not commited. This means that these auto-incrementing types may leave gaps in a sequence. 
> ```

"Some people" feels accusatory. How about "A common misconception"

---

*[serial.md, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpU204Ioos9bYtOFDW:-KJpU204Ioos9bYtOFDX:551039302) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L75)):*
> ```Markdown
> ### Auto-Incrementing Is Not Always Sequential
> 
> Some people assume that the auto-incrementing types in PostgreSQL and MySQL generate strictly sequential values that provide an accurate count of rows in a table. In fact, each insert increases the sequence by one, even when the insert is not commited. This means that these auto-incrementing types may leave gaps in a sequence. 
> ```

There are other reasons this is a bad idea besides the "accurate count of rows" example. Maybe delete the example or make it clear it's one of many ways this assumption can bite you

---

*[serial.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpUf-TK6zG6tY0vnX7:-KJpUf-TK6zG6tY0vnX8:-545571535) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L77)):*
> ```Markdown
> Some people assume that the auto-incrementing types in PostgreSQL and MySQL generate strictly sequential values that provide an accurate count of rows in a table. In fact, each insert increases the sequence by one, even when the insert is not commited. This means that these auto-incrementing types may leave gaps in a sequence. 
> 
> To demonstrate this possibility, we create a table and treat the `INT` column like an auto-incrementing column in PostgreSQL or MySQL. 
> ```

This reads a lot clearer if you're actually using Postgres. Are we intentionally avoiding that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/362)*

**Comment by jseldess** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[serial.md, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJnLtR9tO6-UhiOpniR:-KJq0b28WC-vqRDg2V9K:-644845140) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L10)):*
<details><summary><i>Previously, uptimeDBA (Paul Steffensen) wrote…</i></summary>
> The name(s) for this feature across all databases I'm aware of have caused no end of grief between DBA's and developers. The **only** thing this type of column can guarantee is uniqueness.  (and even that can be called into question if you're allowed to insert your own values.) There can be gaps as values are consumed even if the transaction is rolled back (as the example shows). Are the values strictly increasing based on transaction time? In the case of Oracle, sequence values can appear out of transaction order due to multi instances and caching.
</details>
I think the values are strictly increasing based on transaction time, yes. But Dan, can you confirm?

---

*[serial.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpTCFTCin8Mvrdx4NY:-KJpmBrvhS3Ds8gAAJ30:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L46)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> "without column `a` values" reads a bit awkward to me
</details>
Done.

---

*[serial.md, line 59 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpT_vGONkVGHT-o7rp:-KJpm5YZ8gTxG7XQPbVD:1901975853) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L59)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Not sure we want to call this out in the docs. If you're using a SERIAL column, it's generally because you're not manually specifying the ids. Same for "## Format" above
</details>
Done. Let me know if the revisions need more work.

---

*[serial.md, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpTstmqCILIiMP3BhF:-KJpmmxn6c_WSyuyfZDu:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L75)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> "Some people" feels accusatory. How about "A common misconception"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/362)*

**Comment by paperstreet** [comment]
:lgtm:

<details><summary><i>Previously, jseldess wrote…</i></summary>
> #### SERIAL type
> 
> Adding docs for the new `SERIAL` type. Fixes #356.
> 
> 
> 
> HTML version: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/serial.html
> 
> 
> 
> @paperstreet, @petermattis, not sure if the last example is clear enough.
> 
> 
> 
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[serial.md, line 94 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJq7G57bhMK5lg-SAQi:-KJq7G58WfmI_KuDU7ml:-892786993) ([raw file](https://github.com/cockroachdb/docs/blob/e495a44489d0a096009dda18e4fa343ae30fb03a/serial.md#L94)):*
> ```Markdown
>    ~~~
> 
> Since each insert increased the sequence in column `a` by one, the first commited insert got the value `2`, and the second commited insert got the value `4`. As you can see, the values aren't strictly sequential, and the last value doesn't give an accurate count of rows in the table.
> ```

When we discussed this offline, I think the plan for the end of this example was to specifically call out that Postgres and Cockroach are thus doing the same thing, we're just doing it more often in exchange for speed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/362#-:-KJq7moLQZaL2ZakhTb2:1417088721)*

**Comment by jseldess** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[serial.md, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpUbttuUEyM7TM3q-Y:-KJqBgT-JafbXOeqyYsC:500566901) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L73)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Did we cut the out of order example?
</details>
Discussed with Dan. Decided to leave the out of order example out.

---

*[serial.md, line 75 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpU204Ioos9bYtOFDW:-KJqBlrgGSE2CGEtk-z2:2145910505) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L75)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> There are other reasons this is a bad idea besides the "accurate count of rows" example. Maybe delete the example or make it clear it's one of many ways this assumption can bite you
</details>
Removed example.

---

*[serial.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJpUf-TK6zG6tY0vnX7:-KJqBpi8NCPM35B6wZAk:-241468258) ([raw file](https://github.com/cockroachdb/docs/blob/1067a26aade70271c597cef14eab0cf8a38bf8a0/serial.md#L77)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> This reads a lot clearer if you're actually using Postgres. Are we intentionally avoiding that?
</details>
Changed example to use postgres.

---

*[serial.md, line 94 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/362#-KJq7G57bhMK5lg-SAQi:-KJqBtjL0vTZV6LjsnUp:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/e495a44489d0a096009dda18e4fa343ae30fb03a/serial.md#L94)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> When we discussed this offline, I think the plan for the end of this example was to specifically call out that Postgres and Cockroach are thus doing the same thing, we're just doing it more often in exchange for speed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/362)*

**Comment by bdarnell** [comment]
"Guaranteed to be globally unique" is a stronger claim than I'm comfortable making for a 64-bit integer generated in a decentralized way. IMHO we're providing this type for compatibility with existing systems and the fact that people are *really* attracted to integers as IDs, but if you want a guarantee of global uniqueness you should be using a UUID in a BYTES field instead.

**Comment by jseldess** [comment]
Chatted with @bdarnell. He was thinking that `SERIAL` is the combination of timestamp and random. Since it's timestamp and node ID, it is in fact guaranteed to be globally unique. That is, as Ben mentioned, "until you reach some very large number of nodes." For future reference:

> In a large enough cluster (32K nodes), it breaks down. Why? Because that’s how many bits we allocated to the node id portion of the value. It’s 15 bits of node id and 49 bits of timestamp.

**Pull request merged**
