### PR TITLE
Re-style GitHub contribute button

### LINKED ISSUE #8064: Update ‘Contribute’ to Github button

### PR DESCRIPTION
**Pull request by yingzhuchin**
Fixes #8064.

I will try to merge into `docs-redesign` branch after I get reviews.

### CODE REVIEW

**Comment by luciaaaaaaa** [comment]
Hi -- noticing that the down-carrot icon looks a bit pixelated, anyone else noticing this? cc @lnhsingh

**Comment by yingzhuchin** [comment]
> Hi -- noticing that the down-carrot icon looks a bit pixelated, anyone else noticing this? cc @lnhsingh

I grabbed the icon from the Figma page -- happy to use a higher-resolution image if there's one! Just point me to it.

**Comment by lnhsingh** [comment]
I'm not noticing any pixelation when I view: 
image

**Comment by luciaaaaaaa** [comment]
This is what it looks like for me:
image

@yingzhuchin the icon in figma is correct but it should look sharp (Eg: like the "open with" button in gitbuh that has a down carrot. When I zoom in the icon looks as sharp as the text). In the past I've worked with  from an icon font set...maybe this can help prevent the pixelation. Just asked in the #design-system channel to see if they have something we can try out

**Comment by yingzhuchin** [comment]
Thanks, @luciaaaaaaa. How about now? (Props to @anagio for helping me get the SVG version.)

**Comment by luciaaaaaaa** [comment]
Yay thanks Anne! It looks good now, thanks for looking into this

**Comment by yingzhuchin** [comment]
Great! I will mark this as done then.

**Pull request closed without merging**
