### PR TITLE
Document SQL shell help options

### LINKED ISSUE #1810: sql: Integrate inline/contextual help
Roadmap: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recJfXkkUorGJPEKN

PRs:
- https://github.com/cockroachdb/cockroach/pull/16295
- https://github.com/cockroachdb/cockroach/pull/13540

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1810

### CODE REVIEW

**Comment by jseldess** [comment]
@knz, PTAL. Suspect I might have missed a few aspects of the inline help functionality...

**Comment by knz** [comment]
:lgtm: with nit about ctrl+c

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.1/use-the-built-in-sql-client.md, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1952#-Kva5owZ3QKJ5nG2v4Gj:-Kva5ow_6a9J-5jxhP0Q:b86rhhu) ([raw file](https://github.com/cockroachdb/docs/blob/c702fa622a7b589fcbd5d4dd29b3e81b90eb3450/v1.1/use-the-built-in-sql-client.md#L86)):*
> ```Markdown
> Command | Usage
> --------|------------
> `\q`<br>`ctrl-d`<br>`ctrl-c` | Exit the shell.
> ```

ctrl-c does not only exit the shell. If you have entered some text on a line already, it will clear the line first without exiting. Only on a line on its own does it exit the shell. (This is not new)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1952#-:-Kva6GBf17T8yl9fonrQ:b-uu6788)*

**Comment by jseldess** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[v1.1/use-the-built-in-sql-client.md, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1952#-Kva5owZ3QKJ5nG2v4Gj:-KvblUQJ_9tMJNSNjJCQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c702fa622a7b589fcbd5d4dd29b3e81b90eb3450/v1.1/use-the-built-in-sql-client.md#L86)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ctrl-c does not only exit the shell. If you have entered some text on a line already, it will clear the line first without exiting. Only on a line on its own does it exit the shell. (This is not new)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1952)*

**Comment by jseldess** [comment]
TFTR, @knz

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1952#-:-KvblWdNf46sbEjSU371:b-lhrcps)*

**Pull request merged**
