### PR TITLE
Add redirect to naked URL across our docs

### PR DESCRIPTION
**Pull request by nickvigilante**
Fixes DOC-8338

This PR serves as a redo for https://github.com/cockroachdb/docs/pull/17064.

Testing plan:

- [x] Open the following URLs to ensure they display correctly:
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/v23.1/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/v22.2/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/dev/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/stable/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/advisories/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/releases/
- [x] Within https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs, find a few pages (Foreign Key, What's New in v23.1, etc.) and add a forward slash and a `.html` suffix to the URL and load the page. You should 301 back to the naked version of that page.
- [x] Navigate to the following pages and watch them redirect:
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/advisories/advisories.html
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/advisories/advisories
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/advisories/index.html
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/advisories/index
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/advisories/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/releases/index.html
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/releases/index
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/releases/
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/stable/install-cockroachdb
	- [ ] https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/stable/install-cockroachdb.html

### CODE REVIEW

**Review by mikeCRL — COMMENTED** [review]
All of the URLs in the testing plan result in a trailing slash (except the `install` URLs which end up on https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/stable/install-cockroachdb-mac for me with no trailing slash). I don't think this matches the intended behavior.

**Comment by nickvigilante** [comment]
@mikeCRL Can I get your review on this once the Netlify build finishes?

**Review by mikeCRL — COMMENTED** [review]
Adding a forward slash for pages does not seem to be redirecting to the URL without the forward slash.

For example:  
https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/stable/architecture/reads-and-writes-overview/ 
https://deploy-preview-17464--cockroachdb-docs.netlify.app/docs/stable/schema-design-database/

**Review by mikeCRL — APPROVED** [review]
Tested these and other URLs - all LGTM!

**Pull request merged**
