### PR TITLE
Add python to json tutorial

### PR DESCRIPTION
**Pull request by jseldess**
- Add python code.
- Update tutorial to let user choose go or python.

### CODE REVIEW

**Comment by justinj** [comment]
LGTM besides the `resp` thing

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[_includes/json/json-sample.py, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2772#-L8XWjNJCeNU3ekJdaWi:-L8XWjNJCeNU3ekJdaWj:b-9npx16) ([raw file](https://github.com/cockroachdb/docs/blob/9b92ec8c9a5dddb11d4e212f3a97e3e987701c75/_includes/json/json-sample.py#L36)):*
> ```Python
>     cur.execute("""INSERT INTO jsonb_test.programming (posts)
>             SELECT json_array_elements(%s->'data'->'children')
>             RETURNING %s->'data'->'after'""", (resp,resp))
> ```

doing the two `resp`s here is unfortunate, I'm starting to think we just shouldn't be fancy and just parse it on the client side as well :/ it also hadn't occurred to me that the `RETURNING` would happen for each row being inserted, which is sort of ugly and inefficient, I can PR a fix for that for the Go example (we can either parse it on the client side or use a CTE, I think).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2772#-:-L8XYj5k62vrSaR-Q4u9:b-dyxn5x)*

**Comment by lhirata** [comment]
:lgtm: from a docs perspective. Thanks for adding!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2772#-:-L8XbXcwHqXz0BP2swBK:bdcuhgh)*

**Comment by jseldess** [comment]
*[_includes/json/json-sample.py, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2772#-L8XWjNJCeNU3ekJdaWi:-L8XezxoDh4ioidDdfXk:bi1lfxe) ([raw file](https://github.com/cockroachdb/docs/blob/9b92ec8c9a5dddb11d4e212f3a97e3e987701c75/_includes/json/json-sample.py#L36)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

doing the two `resp`s here is unfortunate, I'm starting to think we just shouldn't be fancy and just parse it on the client side as well :/ it also hadn't occurred to me that the `RETURNING` would happen for each row being inserted, which is sort of ugly and inefficient, I can PR a fix for that for the Go example (we can either parse it on the client side or use a CTE, I think).
</blockquote></details>

But doing the two `resp`s is just a python requirement. For each placeholder, you need a corresponding item. Is that in itself really a problem? 

I also agree that parsing client-side would probably be easier, but then we'd lose the demonstration of our support for functions like `json_array_elements()`. 

That said, totally your call on what we do here. If you like, I can put this on hold if you want to open a separate PR with changes to the Go sample.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2772)*

**Comment by justinj** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[_includes/json/json-sample.py, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2772#-L8XWjNJCeNU3ekJdaWi:-L8c-ahC1KyytNIzZ1RV:bj4klcc) ([raw file](https://github.com/cockroachdb/docs/blob/9b92ec8c9a5dddb11d4e212f3a97e3e987701c75/_includes/json/json-sample.py#L36)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

But doing the two `resp`s is just a python requirement. For each placeholder, you need a corresponding item. Is that in itself really a problem? 

I also agree that parsing client-side would probably be easier, but then we'd lose the demonstration of our support for functions like `json_array_elements()`. 

That said, totally your call on what we do here. If you like, I can put this on hold if you want to open a separate PR with changes to the Go sample.
</blockquote></details>

We don't necessarily have to lose the demonstration of `json_array_elements()`, it's just that if we can't send the data in a single time, we're definitely going to have to parse it again, whereas the benefit of getting back `after` from the query was that we only have to parse it once. If we'd rather leave it in just to demonstrate it's possible that's cool.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2772#-:-L8c1118ChTdN3ZNl3vO:bnfp4nl)*

**Comment by jseldess** [comment]
I updated the code to get `after` on the client side. Thanks for the help, @justinj.

**Pull request merged**
