### PR TITLE
Add params and examples to `VALIDATE CONSTRAINT`

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes https://github.com/cockroachdb/docs/issues/990

### CODE REVIEW

**Comment by rmloveland** [comment]
@a-robinson or @dt, since y'all were commenting on #990 would one of you mind reviewing this?  Thanks!

**Comment by a-robinson** [comment]
@dt is more of a subject matter expert here, I just like to complain about things. I'll let him review.

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[v1.1/validate-constraint.md, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fn6w014sUOuEiyNt8:-L7fn6w014sUOuEiyNt9:btfpxkt) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v1.1/validate-constraint.md#L36)):*
> ```Markdown
> ~~~
> 
> In order to ensure that all new updates to the `orders` table honor that constraint, run the following:
> ```

_new updates_ are already checking the constraint as soon as it is added -- `validate` means check if the _existing_ data conforms to it as well.

---

*[v1.1/validate-constraint.md, line 42 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fmxWP0g77ZNV0MY9a:-L7fmxWP0g77ZNV0MY9b:b-hpa012) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v1.1/validate-constraint.md#L42)):*
> ```Markdown
> ~~~
> 
> This will also validate all of the existing data and bring the table into a fully validated state.
> ```

there could be other constraints not validated yet, so i don't know if i'd go as far as saying "the table into a fully validated state."

---

*[v2.0/validate-constraint.md, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fnNzRCbtPuWcMBq_o:-L7fnNzRCbtPuWcMBq_p:b-7ropln) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v2.0/validate-constraint.md#L36)):*
> ```Markdown
> ~~~
> 
> In order to ensure that all new updates to the `orders` table honor that constraint, run the following:
> ```

ditto

---

*[v2.0/validate-constraint.md, line 42 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fnOolE4sM_tTIFp6o:-L7fnOolE4sM_tTIFp6p:b-7ropln) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v2.0/validate-constraint.md#L42)):*
> ```Markdown
> ~~~
> 
> This will also validate all of the existing data and bring the table into a fully validated state.
> ```

ditto

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2730)*

**Comment by rmloveland** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v1.1/validate-constraint.md, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fn6w014sUOuEiyNt8:-L7yxlCZD6xqJ5McW5Ja:b2yh32n) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v1.1/validate-constraint.md#L36)):*
Thanks @dt - updated in ff817cf1 to say 

> In order to ensure that the data added to the `orders` table prior to the creation of the `customer_fk` constraint conforms to that constraint, run the following:

---

*[v1.1/validate-constraint.md, line 42 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fmxWP0g77ZNV0MY9a:-L7yy2-uEhKaFY4FC5m5:bp0v1gl) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v1.1/validate-constraint.md#L42)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

there could be other constraints not validated yet, so i don't know if i'd go as far as saying "the table into a fully validated state."
</blockquote></details>

Removed in ff817cf1 since the new language covers this info

---

*[v2.0/validate-constraint.md, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fnNzRCbtPuWcMBq_o:-L7yyHz-CPvUgB2HCpFq:b-zi772q) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v2.0/validate-constraint.md#L36)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed in ff817cf1 as described above

---

*[v2.0/validate-constraint.md, line 42 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2730#-L7fnOolE4sM_tTIFp6o:-L7yyNnT6H-n16Ncp35P:b-zi772q) ([raw file](https://github.com/cockroachdb/docs/blob/181bc88355624e7b616bf219591c6c74ec698b81/v2.0/validate-constraint.md#L42)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed in ff817cf1 as described above

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2730)*

**Pull request merged**
