### PR TITLE
Bulk-update data

### LINKED ISSUE #9863: Developer Guide v2: Bulk-update Data
Part of https://github.com/cockroachdb/docs/issues/9065.

*from planning doc*

>Misc notes:
Requires code snippet.
https://www.cockroachlabs.com/docs/v20.2/delete#batch-deletes

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #9863. 

Related to #9065.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@bdarnell 

Adding you for review of the Python code. I followed the non-indexed column pattern from our [batch delete docs](https://www.cockroachlabs.com/docs/stable/bulk-delete-data.html#batch-delete-on-a-non-indexed-column). It runs, but I'm not very confident in its efficiency.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9926)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/bulk-update-data.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy3TAP8ve6Wrg_J_wM:-MUy3TAP8ve6Wrg_J_wN:bqd81q4) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L31)):*
> ```Markdown
>     For the example on this page, we load a cluster with the `movr` database and data from [`cockroach workload`](cockroach-workload.html).
> 
> ## Write a batch-update loop
> ```

There's a danger with this pattern: if the script crashes and you restart it, you'll update the first rows more than once. (and the second run will process newer rows that wouldn't have been included the first time) You need some way in the database to tell which rows have already been processed. This tends to be application-dependent (for the "discount" example here, you'd want a `discount_applied` boolean column on the table, with corresponding application changes to apply the discount to new records and set this flag accordingly).  
___
*[v21.1/bulk-update-data.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy55KvE5LJYHbkJ7B4:-MUy55KvE5LJYHbkJ7B5:b-ci14kz) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L43)):*
> ```Markdown
> ## Example
> 
> Suppose that you have recorded hundreds of thousands of [MovR](movr.html) rides in a cluster loaded with the [`movr`](cockroach-workload.html#movr) database. And suppose that you want to apply a discount to all of the rides that cost more than 70¤. To do this, you need to update all of the rows in the `rides` table where the `revenue` column is greater than `70`. You can create a script that loops over the data and updates the relevant rows in batches, following the query guidance provided above.
> ```

This use case doesn't make a lot of sense - changing the price of trips that have already happened (and presumably already been charged)? 
___
*[v21.1/bulk-update-data.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy9dNrBV2QxTpyGPlg:-MUy9dNrBV2QxTpyGPlh:b-1ayoy9) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L64)):*
> ```Markdown
>                 cur.execute("SET TRANSACTION AS OF SYSTEM TIME '-5s'")
>                 if len(usedpks) > 0:
>                     cur.execute("SELECT id FROM rides WHERE id != ANY %s AND revenue > 70 ORDER BY id LIMIT 10000", (usedpks,))
> ```

Passing `usedpks` back into the DB gets expensive as that set grows. You're ordering by ID so you just want `where ID > %s` with the last ID you processed (the bulk delete page probably needs a similar change if it's doing the same thing).

**Review by ericharmeling — COMMENTED** [review]
TFTR @bdarnell !

I believe that I've addressed your comments below in the latest commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9926#-:-MV2t51n6kOS8sbZyio2:b-3ywm40)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[v21.1/bulk-update-data.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy3TAP8ve6Wrg_J_wM:-MV2Su76DBPAFKfxOiER:b-x44dl1) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There's a danger with this pattern: if the script crashes and you restart it, you'll update the first rows more than once. (and the second run will process newer rows that wouldn't have been included the first time) You need some way in the database to tell which rows have already been processed. This tends to be application-dependent (for the "discount" example here, you'd want a `discount_applied` boolean column on the table, with corresponding application changes to apply the discount to new records and set this flag accordingly).  
</blockquote></details>

I've added instructions to add a new `discounted` boolean column. The top-level select query now filters on this column, and the nested update queries update the `discounted` and `revenue` columns in the same statement . 

This removes the need to filter on the primary key (or a set of "used" primary key values) in the top-level select query, which simplifies tracking the columns that still need to be updated.
___
*[v21.1/bulk-update-data.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy55KvE5LJYHbkJ7B4:-MV2G-fUBF6uNnjR0oxb:b-hep856) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L43)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This use case doesn't make a lot of sense - changing the price of trips that have already happened (and presumably already been charged)? 
</blockquote></details>

You're right. I updated the language and the use case a little bit to make the example a little more reasonable. TLDR: applied the discount when you charged the user, but you haven't yet updated the `rides` table.

Hopefully this example now works for pedagogical purposes, but I'm open to reconsidering it.
___
*[v21.1/bulk-update-data.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy9dNrBV2QxTpyGPlg:-MV2DS8yABfAUQObk89c:b-b30brs) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L64)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Passing `usedpks` back into the DB gets expensive as that set grows. You're ordering by ID so you just want `where ID > %s` with the last ID you processed (the bulk delete page probably needs a similar change if it's doing the same thing). 
</blockquote></details>

You're right. I removed the `usedpks` set. 

I would use the `where id > s%`, but filtering on the new `discounted` boolean column makes it so we don't need to track the rows that have already been updated by primary key.

The non-indexed pattern on the bulk delete page doesn't actually use a `usedpks` set. It just returns all of the filtered rows that haven't yet been deleted.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9926)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @ericharmeling)

___
*[v21.1/bulk-update-data.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy9dNrBV2QxTpyGPlg:-MVIc0P98pMmZzERfDAk:bb906wl) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L64)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

You're right. I removed the `usedpks` set. 

I would use the `where id > s%`, but filtering on the new `discounted` boolean column makes it so we don't need to track the rows that have already been updated by primary key.

The non-indexed pattern on the bulk delete page doesn't actually use a `usedpks` set. It just returns all of the filtered rows that haven't yet been deleted.
</blockquote></details>

You still want the `where id > %s` clause - without it, the query will get slower over time since it has to skip over all the already-processed rows every time.

**Review by ericharmeling — COMMENTED** [review]
TFTR @bdarnell !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9926#-:-MVJDhCL7cLhmW2QHCa8:b-7b0vls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[v21.1/bulk-update-data.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/9926#-MUy9dNrBV2QxTpyGPlg:-MVIoG9y78Bk0ClMGUtU:bz3vudb) ([raw file](https://github.com/cockroachdb/docs/blob/19cfb9b1f206efc29c353f65622e3b50afa962bd/v21.1/bulk-update-data.md#L64)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

You still want the `where id > %s` clause - without it, the query will get slower over time since it has to skip over all the already-processed rows every time. 
</blockquote></details>

Makes sense! Done.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
