### PR TITLE
Fixing how far anchor links jump

### LINKED ISSUE #133: Anchor links jump a little too far
When you click an anchor link on a page, the page jumps to the referenced anchor but a bit too far, with the topnav covering the heading a little. 

screen shot 2016-03-22 at 3 24 03 pm

cc: @nvanbenschoten

### PR DESCRIPTION
**Pull request by jseldess**
@mrtracy helped add the jquery to fix #133. 

@nvanbenschoten, can you test real quick at http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/207)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
It seems a lot better, but I wonder if we want to scroll a little further down to provide the header with some padding (and line up with the search bar). Do you mind replacing the `scroll_target - 10` with `scroll_target - 76` and seeing how that looks?

**Comment by jseldess** [comment]
Good suggestion. Adding more padding, also when you click a link in a page TOC. 

Can you take another look?

**Comment by jseldess** [comment]
But I just noticed that after clicking an achor, the header id doesn't get appended to URL in the browser anymore. Seems like the jquery we added changed that somehow...

**Comment by nvanbenschoten** [comment]
It seems like the anchor links and the text headers have different click behavior.

**Comment by jseldess** [comment]
@mrtracy, when you have a little free time, can you take a look and let me know if you see any obvious correction?

**Comment by jseldess** [comment]
@nvanbenschoten, I can get this to work when using the `.animate` method. The anchor link now jumps to the right place AND the header id gets appended to the URL. 

But there is a slightly annoying jump, where the header goes all the way up and then pops back down to the right place. I'm ok with this for the time being, given that the two features above are working. Thoughts? 

You can test again at link above.

**Comment by jseldess** [comment]
OK, I put in a request to have Divison/Of come up with a better solution here. Thanks for spending time on this, Nathan and Matt!

**Comment by jseldess** [comment]
Fixed by PR #212

**Pull request closed without merging**
