### PR TITLE
SELECT FOR UPDATE NOWAIT and locking mode docs

### LINKED ISSUE #8301: sql: support FOR {UPDATE,SHARE} NOWAIT
PR: https://github.com/cockroachdb/cockroach/pull/52522

From release notes:
> Added support for `SELECT ... FOR {UPDATE,SHARE} NOWAIT`. The option can be used to throw an error instead of blocking on contended row-level lock acquisition. [#52522][#52522] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #8301.

### CODE REVIEW

**Review by nvanbenschoten — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @nvanbenschoten)

___
*[v20.2/select-for-update.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBpXOL1qMfVIKgn0fs:-MKBpXOL1qMfVIKgn0ft:b-bm5gdu) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L24)):*
> ```Markdown
> Parameter | Description
> ----------|------------
> `FOR SHARE` | CockroachDB currently does not support the `FOR SHARE` locking mode. This syntax is a no-op, allowed for PostgreSQL compatibility.
> ```

I think we should be a little more explicit here. The syntax is a no-op in that it does not cause CRDB to acquire pessimistic shared locks over the rows retrieved, but CRDB does still ensure serializability.
___
*[v20.2/select-for-update.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBpRLJ32YEXe_NyyAy:-MKBpRLK6Y20mkLKoaLB:blrnw9x) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L27)):*
> ```Markdown
> `FOR KEY SHARE` | CockroachDB currently does not support the `FOR KEY SHARE` locking mode. This syntax is a no-op, allowed for PostgreSQL compatibility.
> `FOR UPDATE` | Lock the rows returned by the [`SELECT`](selection-queries.html) statement, such that other transactions trying to access those rows must wait for the transaction to finish.
> `FOR NO KEY UPDATE` | CockroachDB currently does not support the `FOR NO KEY UPDATE` locking mode. This syntax is a no-op, allowed for PostgreSQL compatibility.
> ```

This syntax isn't a no-op. Instead, it is the same as `FOR UPDATE`.
___
*[v20.2/select-for-update.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBptYx4VuFHLwuzBgn:-MKBptYx4VuFHLwuzBgo:bk447pj) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L28)):*
> ```Markdown
> `FOR UPDATE` | Lock the rows returned by the [`SELECT`](selection-queries.html) statement, such that other transactions trying to access those rows must wait for the transaction to finish.
> `FOR NO KEY UPDATE` | CockroachDB currently does not support the `FOR NO KEY UPDATE` locking mode. This syntax is a no-op, allowed for PostgreSQL compatibility.
> `SKIP LOCKED` | Skipping locked rows is not yet supported by CockroachDB. `SELECT` statements with `SKIP LOCKED` will return an `"unimplemented"` error.
> ```

I don't think these two options should be in the same table as the other four. The first four are "locking strengths". The last two are "wait policies".

It also seems strange to phrase this as "will return an unimplemented error". Is that what we usually do? Should we just say "this is unsupported"?

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[v20.2/select-for-update.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBpXOL1qMfVIKgn0fs:-MKFa1S-1eRzt63cBc1c:b-2znknu) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L24)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we should be a little more explicit here. The syntax is a no-op in that it does not cause CRDB to acquire pessimistic shared locks over the rows retrieved, but CRDB does still ensure serializability.
</blockquote></details>

Updated this.
___
*[v20.2/select-for-update.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBpRLJ32YEXe_NyyAy:-MKFdLSU7eJnTl7dc19p:b5ilov0) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L27)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This syntax isn't a no-op. Instead, it is the same as `FOR UPDATE`.
</blockquote></details>

Clarified this.
___
*[v20.2/select-for-update.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBptYx4VuFHLwuzBgn:-MKC-UWM3UoeOsaQUFdL:biw7v81) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L28)):*
> I don't think these two options should be in the same table as the other four. The first four are "locking strengths". The last two are "wait policies".

Separated these out into two subsections.

> It also seems strange to phrase this as "will return an unimplemented error". Is that what we usually do? Should we just say "this is unsupported"?

It's meant to highlight the fact that CRDB recognizes certain syntax and returns an unimplemented error if it is not supported. This contrasts with invalid syntax, which throws a more general exception. But I don't think this distinction is super important, and we aren't very consistent about documenting "unimplemented" syntax. Updated the description to be a little more general.

**Review by ericharmeling — COMMENTED** [review]
TFTR @nvanbenschoten !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720#-:-MKFf9OW3owRmmZP2M2q:b-csfsvu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvanbenschoten — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v20.2/select-for-update.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBptYx4VuFHLwuzBgn:-MKG3fL--fCQtUMJzFM5:b-9tkho6) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L28)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> I don't think these two options should be in the same table as the other four. The first four are "locking strengths". The last two are "wait policies".

Separated these out into two subsections.

> It also seems strange to phrase this as "will return an unimplemented error". Is that what we usually do? Should we just say "this is unsupported"?

It's meant to highlight the fact that CRDB recognizes certain syntax and returns an unimplemented error if it is not supported. This contrasts with invalid syntax, which throws a more general exception. But I don't think this distinction is super important, and we aren't very consistent about documenting "unimplemented" syntax. Updated the description to be a little more general.
</blockquote></details>

Looks great! The only change I would make is to add a sentence before each of these tables describing what Locking Strengh and Wait Policies are. For instance:
```
# Locking strengths

Locking strength dictates the row-level locking mode used by SELECT statements.

...

# Wait policies

Wait policies control the policy used for handling conflicting locks held by other active transactions when attempting to lock rows due to FOR UPDATE/SHARE clauses.

...
```

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[v20.2/select-for-update.md, line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/8720#-MKBptYx4VuFHLwuzBgn:-MKGofyVDJMTTF7bHOMt:bwx44jg) ([raw file](https://github.com/cockroachdb/docs/blob/2836b8ac3e2ffa7f89494bcc6f88b1fe15fbcb8c/v20.2/select-for-update.md#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks great! The only change I would make is to add a sentence before each of these tables describing what Locking Strengh and Wait Policies are. For instance:
```
# Locking strengths

Locking strength dictates the row-level locking mode used by SELECT statements.

...

# Wait policies

Wait policies control the policy used for handling conflicting locks held by other active transactions when attempting to lock rows due to FOR UPDATE/SHARE clauses.

...
```
</blockquote></details>

Done! Thanks for the suggestion. :)

**Review by nvanbenschoten — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720#-:-MKGzX2A17YCJK8CaV2O:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by lnhsingh — COMMENTED** [review]
:lgtm: nice job!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8720#-:-MKMLexbDCd1L_Ydj1pN:bxpgx20)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh)

**Pull request merged**
