### PR TITLE
Add missing COPY buttons to Kubernetes docs

### PR DESCRIPTION
**Pull request by a-robinson**
Also add a couple of missing `kubectl get pods` commands and clean up
the formatting of the commands to be entered into the SQL shell.

### CODE REVIEW

**Comment by a-robinson** [comment]
Any idea why the `gcloud container clusters create` command isn't rendering properly?

screen shot 2018-03-01 at 5 56 32 pm

**Comment by jseldess** [comment]
Ugh, unfortunately, it looks like, when we're wrapping markdown in `<div class="filter-content" markdown="1" data-scope="BLAH">` tags for filtering purposes, using the `{% include copy-clipboard.html %}` within the `<div>` breaks the page. I don't see an immediate solution right now because even if you remove `{% include copy-clipboard.html %}` from the first code block in the div, the second one with the include snippet breaks. 

For now, I'd suggest reverting all of the includes you added within divs and opening an issue for @j-low to help us fix the include snippet. We already have an issue for incorrect styling of the copy button in cases like this, so perhaps we should just expand that issue: https://github.com/cockroachdb/docs/issues/2146.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2585#-:-L6aHdUHsRs5k0absyjd:b-oq181x)*

**Comment by jseldess** [comment]
We could also get around this by splitting the hosted gke, manual gce, and manual aws into separate pages. But for now, I think accepting a slightly annoying UX of not having copy to clipboard on code snippets inside those divs is ok.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2585#-:-L6aKLZ_8VKijVjORUDG:b-xgbsqq)*

**Comment by jseldess** [comment]
OK, I found a workaround. Whenever you're using an `{% include copy-clipboard.html %}` within a `<div> </div>`, change those div tags to `<section> </section>`. I tested this on your branch, and it works fine. However, it seems important to **not** make this change when there's no include within the div. I don't understand what's going on, but I suspect the html div generated by the include snippet is somehow invalid and therefore causing choas when nested in another div. 

Would you prefer I make this change and push to your branch?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2585#-:-L6b14yA26jQQd63MIG2:bxj8rpt)*

**Comment by a-robinson** [comment]
That is certainly unfortunate. Feel free to take over, or I can just remove the buggy COPY buttons if you'd prefer.

**Comment by a-robinson** [comment]
Your changes LGTM. Thanks, @jseldess.

**Pull request merged**
