### PR TITLE
Surface core value props in start a cluster

### PR DESCRIPTION
**Pull request by jseldess**
These changes attempt to keep the Start a Cluster tutorial
quick and easy while introducing new users to what makes
CockroachDB unique, not just ease of deployment, but also
automated replication and survival.

I've also stripped out some details that I think are not
important to the majority of users getting up and running
for the first time, e.g., how to customize `start` flags
and the fact that you can use third-party monitoring.

Finally, I've update the Stop the Cluster step to account
for the fact that `cockroach quit` can't be used to stop
nodes once quorum is lost.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1257)

### CODE REVIEW

**Comment by jseldess** [comment]
@bdarnell, @spencerkimball, would appreciate your feedback, too.

**Comment by dianasaur323** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-:-Kh2sJT_VXv65AV9-_sA:bnfp4nl)*

**Comment by jseldess** [comment]
@asubiotto, can you please check the [Stop the cluster](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/302c837d84c33e9dc5574982b8b8a994eb3b7b78/start-a-local-cluster.html#step-5--stop-the-cluster) step?

**Comment by sploiselle** [comment]
:lgtm: Really, really wonderful.

---

Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[start-a-local-cluster.md, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh30NNiuSQkTroO96_s:-Kh30NNiuSQkTroO96_t:b-hxbrcv) ([raw file](https://github.com/cockroachdb/docs/blob/302c837d84c33e9dc5574982b8b8a994eb3b7b78/start-a-local-cluster.md#L48)):*
> ```Markdown
> - The [standard output](start-a-node.html#standard-output) gives you helpful details such as the CockroachDB version, the URL for the admin UI, and the SQL URL for clients.
> 
> {{site.data.alerts.callout_success}}By default, each node's cache is limited to 25% of available memory. This default is reasonable when running one node per host. When you run multiple nodes on a single host, however, this default may lead to out of memory errors, especially if you test in a serious way. To avoid such errors, you can limit each node's cache size by setting the <code>--cache</code> flag in the <code>start</code> command.{{site.data.alerts.end}}
> ```

nit: maybe "out of memory" or out-of-memory

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-:-Kh2zf0Qra8vNXj1ZS95:b-8d2yod)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[start-a-local-cluster.md, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh38U5hnKLn6pt_OVCU:-Kh38U5hnKLn6pt_OVCV:blekhr6) ([raw file](https://github.com/cockroachdb/docs/blob/129a842951cb4272302c76e04fcfae232cbcb32f/start-a-local-cluster.md#L76)):*
> ```Markdown
> ## Step 3. Test the cluster
> 
> Now that you've scaled to 3 nodes, you can use any node as a SQL gateway to the cluster. To demonstrate this, start the [built-in SQL cleint](use-the-built-in-sql-client.html) on node 1 and run some basic [CockroachDB SQL statements](learn-cockroachdb-sql.html):
> ```

Typo: cleint

---

*[start-a-local-cluster.md, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh38Xxtr9KrKhL5Ut47:-Kh38Xxtr9KrKhL5Ut48:b9ir77b) ([raw file](https://github.com/cockroachdb/docs/blob/129a842951cb4272302c76e04fcfae232cbcb32f/start-a-local-cluster.md#L81)):*
> ```Markdown
> 
> ~~~ shell
> $ cockroach sql --port=26257
> ```

Should we mention that the `--port` flag is normally optional (and we're just using it here to demonstrate a point?)

---

*[start-a-local-cluster.md, line 192 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh39NqYYYt3uBr0PaeD:-Kh39NqYYYt3uBr0PaeE:b-62rkpr) ([raw file](https://github.com/cockroachdb/docs/blob/129a842951cb4272302c76e04fcfae232cbcb32f/start-a-local-cluster.md#L192)):*
> ```Markdown
> ~~~
> 
> With only 1 node online, a majority of replicas are no longer available, and so the cluster is not operational. As a result, you can't use `cockroach quit` to stop the last node, but instead must get the node's process ID and then force kill it:
> ```

As an alternative to this slightly complicated process, we could recommend that they run all three nodes without `--background` in three different terminals. Then you can kill the first two nodes with ctrl-c, and the third node by typing ctrl-c twice. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-:-Kh39bZ4ylV4iPpjJk6K:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[start-a-local-cluster.md, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh30NNiuSQkTroO96_s:-Kh3dKxYOmd6hZ2LO93R:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/302c837d84c33e9dc5574982b8b8a994eb3b7b78/start-a-local-cluster.md#L48)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

nit: maybe "out of memory" or out-of-memory
</blockquote></details>

Done.

---

*[start-a-local-cluster.md, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh38U5hnKLn6pt_OVCU:-Kh3dPSzaXBLJgK4Trj-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/129a842951cb4272302c76e04fcfae232cbcb32f/start-a-local-cluster.md#L76)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Typo: cleint
</blockquote></details>

Done.

---

*[start-a-local-cluster.md, line 81 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh38Xxtr9KrKhL5Ut47:-Kh3hZs1ZgO7PIagPpNj:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/129a842951cb4272302c76e04fcfae232cbcb32f/start-a-local-cluster.md#L81)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Should we mention that the `--port` flag is normally optional (and we're just using it here to demonstrate a point?)
</blockquote></details>

Done.

---

*[start-a-local-cluster.md, line 192 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1257#-Kh39NqYYYt3uBr0PaeD:-Kh3C_1yks5smmAwTQQY:bjbd4hm) ([raw file](https://github.com/cockroachdb/docs/blob/129a842951cb4272302c76e04fcfae232cbcb32f/start-a-local-cluster.md#L192)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

As an alternative to this slightly complicated process, we could recommend that they run all three nodes without `--background` in three different terminals. Then you can kill the first two nodes with ctrl-c, and the third node by typing ctrl-c twice. 
</blockquote></details>

Running each node in a separate terminal does make this particular step a lot easier, I agree, but I think it complicates the process overall. All other steps feel a lot quicker in the same terminal. Also, I don't know whether I can get an asciicast to work across terminal windows...   

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1257)*

**Comment by kuanluo** [comment]
Love the called-out admin ui replication graph. 👍

**Pull request merged**
