### PR TITLE
DOC-2793: Add SSO note for Cloud Console login

### PR DESCRIPTION
**Pull request by MichaelTrestman**
Add a note that we support GitHub SSO and will support other options soon, and that SSO is to be preferred for security.

### CODE REVIEW

**Review by taroface — CHANGES_REQUESTED** [review]
Some style and formatting notes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13163#-:-MxGJuRz7-HArzgd8e9B:biy60dh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @MichaelTrestman and @taroface)

___
*[_includes/cockroachcloud/prefer-sso.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGHFdm6uH8wXuaCw6C:-MxGHFdn5Zg8VgCv_Wzc:b-d3nxml) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L2)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> It is best practice for {{ site.data.products.db }} Console users to login with Single Sign-On (SSO), with two-factor authentication (2FA) enabled for the SSO provider. This prevents potential attackers from using stolen credentials to accesss or tamper with your critical data.
> ```

The phrase "It is best practice" feels strange to me. Maybe:

"We recommend accessing the {{ site.data.products.db }} Console with Single Sign-On (SSO)"

Or "It is best to access" instead of "We recommend"



_Suggestion:_
```Markdown
It is best practice for {{ site.data.products.db }} Console users to login with Single Sign-On (SSO)
```
___
*[_includes/cockroachcloud/prefer-sso.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGHvli911uB_YXa91L:-MxGHvli911uB_YXa91M:b-2i7e1t) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L3)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> It is best practice for {{ site.data.products.db }} Console users to login with Single Sign-On (SSO), with two-factor authentication (2FA) enabled for the SSO provider. This prevents potential attackers from using stolen credentials to accesss or tamper with your critical data.
> {{ site.data.products.db }} currently supports SSO with GitHub, and will be adding more SSO providers in the near future.
> ```

If this is meant to start a new paragraph, add another line break. If not, remove the line break above it.

Re: "near future" - I saw there was a thread about this, but didn't follow. Are we OK with suggesting that things are coming soon?
___
*[_includes/cockroachcloud/prefer-sso.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGH2kxAN05MizBpwUn:-MxGH2kxAN05MizBpwUo:b-jnmyhy) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L4)):*
> ```Markdown
> It is best practice for {{ site.data.products.db }} Console users to login with Single Sign-On (SSO), with two-factor authentication (2FA) enabled for the SSO provider. This prevents potential attackers from using stolen credentials to accesss or tamper with your critical data.
> {{ site.data.products.db }} currently supports SSO with GitHub, and will be adding more SSO providers in the near future.
> Visit your CockroachDB Cloud Console's [account settings page](https://cockroachlabs.cloud/account/profile) and switch to SSO to improve the security of your cluster.
> ```

Use liquid



_Code quote:_
```Markdown
CockroachDB Cloud 
```
___
*[_includes/cockroachcloud/prefer-sso.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIH-d4IaenqsYPgTB:-MxGIH-d4IaenqsYPgTC:b87bmr7) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L4)):*
> ```Markdown
> It is best practice for {{ site.data.products.db }} Console users to login with Single Sign-On (SSO), with two-factor authentication (2FA) enabled for the SSO provider. This prevents potential attackers from using stolen credentials to accesss or tamper with your critical data.
> {{ site.data.products.db }} currently supports SSO with GitHub, and will be adding more SSO providers in the near future.
> Visit your CockroachDB Cloud Console's [account settings page](https://cockroachlabs.cloud/account/profile) and switch to SSO to improve the security of your cluster.
> ```

Ditto, is this a new paragraph or no? Markdown doesn't normally recognize single line breaks so we shouldn't use them.
___
*[cockroachcloud/authentication.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIPayApqv9ARGzVgx:-MxGIPayApqv9ARGzVgy:b6wcy9g) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L10)):*
> ```Markdown
> Users may connect with {{ site.data.products.db }} in two ways:
> 
> - the [Cloud Console](https://cockroachlabs.cloud/) offers an overview of your {{ site.data.products.db }} account, and offers functionality for administrating or connecting to clusters.
> ```

Capitalize "the"

I think the Console name should be `{{ site.data.products.db }} Console`, but maybe double-check with another writer or PM?
___
*[cockroachcloud/authentication.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIe3N9y1_Mq3nLbEQ:-MxGIe3N9y1_Mq3nLbER:boc8csf) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L10)):*
> ```Markdown
> Users may connect with {{ site.data.products.db }} in two ways:
> 
> - the [Cloud Console](https://cockroachlabs.cloud/) offers an overview of your {{ site.data.products.db }} account, and offers functionality for administrating or connecting to clusters.
> ```

This word is used twice in the sentence.



_Code quote:_
```Markdown
offers
```
___
*[cockroachcloud/authentication.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIiCEBYY-ImNutg6F:-MxGIiCEBYY-ImNutg6G:b-4pojpi) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L12)):*
> ```Markdown
> - the [Cloud Console](https://cockroachlabs.cloud/) offers an overview of your {{ site.data.products.db }} account, and offers functionality for administrating or connecting to clusters.
> - SQL clients, including the CockroachDB CLI client and the [various supported drivers and ORMs](../{{site.versions["stable"]}}/install-client-drivers.html), connect directly to CockroachDB clusters using the [CockroachDB SQL interface](../{{site.versions["stable"]}}/sql-feature-support.html).
> ```

Remove extra line break
___
*[cockroachcloud/authentication.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIlPKDhfNFARoQ80B:-MxGIlPKDhfNFARoQ80C:b-bswunt) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L14)):*
> ```Markdown
> 
> 
> ## Cloud Console authentication
> ```

{{ site.data.products.db }} Console



_Code quote:_
```Markdown
Cloud Console
```
___
*[cockroachcloud/authentication.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJPCf4J-VezWwzwqO:-MxGJPCf4J-VezWwzwqP:bgi8qur) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L16)):*
> ```Markdown
> ## Cloud Console authentication
> 
> Users may log into the [Cloud Console](https://cockroachlabs.cloud/) with a username and password, or using SSO.
> ```

We don't normally use third-person to refer to the user. See style guide: https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#style-and-tone



_Code quote:_
```Markdown
Users
```
___
*[cockroachcloud/authentication.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJeuB1ckyrcQVGLZ3:-MxGJeuB1ckyrcQVGLZ4:b-6je5t7) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L16)):*
> ```Markdown
> ## Cloud Console authentication
> 
> Users may log into the [Cloud Console](https://cockroachlabs.cloud/) with a username and password, or using SSO.
> ```

log in to



_Code quote:_
```Markdown
log into
```
___
*[cockroachcloud/authentication.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJh4w0bB2cVdUyMsI:-MxGJh4w0bB2cVdUyMsJ:b-n0lgac) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L20)):*
> ```Markdown
> {% include cockroachcloud/prefer-sso.md %}
> 
> ## SQL Authentication
> ```

lowercase



_Code quote:_
```Markdown
Authentication
```

**Review by MichaelTrestman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13163)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[_includes/cockroachcloud/prefer-sso.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGHFdm6uH8wXuaCw6C:-MxGO2ym-lTDp30pYc54:bfosphq) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L2)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

The phrase "It is best practice" feels strange to me. Maybe:

"We recommend accessing the {{ site.data.products.db }} Console with Single Sign-On (SSO)"

Or "It is best to access" instead of "We recommend"
</blockquote></details>

"It is best practice to..." is pretty common diction, google it! :) But ok, if that's not how we say it in the docs.
___
*[_includes/cockroachcloud/prefer-sso.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGHvli911uB_YXa91L:-MxGOTA19txltOGJQfKh:b-ud6w4g) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L3)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

If this is meant to start a new paragraph, add another line break. If not, remove the line break above it.

Re: "near future" - I saw there was a thread about this, but didn't follow. Are we OK with suggesting that things are coming soon?
</blockquote></details>

Yup, Lauren okayed the included phrasing 
___
*[_includes/cockroachcloud/prefer-sso.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIH-d4IaenqsYPgTB:-MxGP9Jx7KRRldi0Uav7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L4)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto, is this a new paragraph or no? Markdown doesn't normally recognize single line breaks so we shouldn't use them.
</blockquote></details>

Done.
___
*[_includes/cockroachcloud/prefer-sso.md, line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGH2kxAN05MizBpwUn:-MxGP9eG9vuFLLbqBU-0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L4)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Use liquid
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIPayApqv9ARGzVgx:-MxGPMbN6SCZAIoaht1J:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L10)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Capitalize "the"

I think the Console name should be `{{ site.data.products.db }} Console`, but maybe double-check with another writer or PM?
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 10 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIe3N9y1_Mq3nLbEQ:-MxGPXW42wDUNm0sCNBv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L10)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

This word is used twice in the sentence.
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIiCEBYY-ImNutg6F:-MxGPakHDhcu9DPBauTS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L12)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Remove extra line break
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIlPKDhfNFARoQ80B:-MxGPb1O7zmmxprgrvaN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L14)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

{{ site.data.products.db }} Console
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJPCf4J-VezWwzwqO:-MxGQ0WeAjq7RXP4vmFn:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

We don't normally use third-person to refer to the user. See style guide: https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#style-and-tone
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJeuB1ckyrcQVGLZ3:-MxGQ4uqB-JT0i7dFRyT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

log in to
</blockquote></details>

Done.
___
*[cockroachcloud/authentication.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJh4w0bB2cVdUyMsI:-MxGQ6ZP-a5N_nu5F82B:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L20)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

lowercase
</blockquote></details>

Done.

**Review by MichaelTrestman — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13163#-:-MxGRCwrEIfVpCAM3TsO:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @taroface)

**Review by taroface — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13163)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @MichaelTrestman and @taroface)

___
*[_includes/cockroachcloud/prefer-sso.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGHFdm6uH8wXuaCw6C:-MxGRWhSAdTiM8lou3is:bf41pdf) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/_includes/cockroachcloud/prefer-sso.md#L2)):*
> It is best practice

I see now, fair enough.

> {{ site.data.products.db }} Console users login

Two other things I was addressing in my rephrasing were:

- I don't think the phrase "Console users" makes sense because they aren't users of the Console. They are users of the product (CockroachDB Cloud), which includes the Console.
- Should be "log in"; "login" is a noun
___
*[cockroachcloud/authentication.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGIlPKDhfNFARoQ80B:-MxGSajz7QOcmjoDNEzb:b-l6jwdc) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L14)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This doesn't look fixed.
___
*[cockroachcloud/authentication.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGJeuB1ckyrcQVGLZ3:-MxGT6WsA0YfhUxwmArE:b1wdf0m) ([raw file](https://github.com/cockroachdb/docs/blob/01f56d07d514dc082d3b18c9797fa277675f1cba/cockroachcloud/authentication.md#L16)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This isn't fixed.
___
*[cockroachcloud/authentication.md, line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13163#-MxGSJDW3n3thySFSMfh:-MxGSJDW3n3thySFSMfi:baylbiz) ([raw file](https://github.com/cockroachdb/docs/blob/103c6ed27c57230191a378397b7641bbd59afb20/cockroachcloud/authentication.md#L8)):*
> ```Markdown
> ---
> 
> Users may connect with {{ site.data.products.db }} in two ways:
> ```

Sorry if I missed this last time. This should use second-person like the other instance I pointed out.



_Code quote:_
```Markdown
Users may connect with 
```

**Pull request merged**
