### PR TITLE
Remove download links for beta-20161110

### PR DESCRIPTION
**Pull request by bdarnell**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/853)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM

are you changing the S3 binaries? the `cockroach-latest-*` tarballs need to be rebuilt from the previous beta.

**Comment by bdarnell** [comment]
I was going to ask about that; I don't know how those builds work. Can we not just use the 1103 binaries instead of building new ones?

**Comment by mberhault** [comment]
We can definitely use those binaries, but the `cockroach-latest.darwin-10.9-amd64.tgz` and `cockroach-latest.linux-amd64.tgz` (used in a bunch of places in the docs) need to be repackaged with the previous beta. This doesn't involve building new binaries, just a tar using the proper directory name. The idea is to have a tarball that is always the same name across beta.

Anyway, I can do it, I expect it wouldn't be fun to do behind a sluggish VPN.

**Comment by bdarnell** [comment]
OK, thanks.

**Comment by mberhault** [comment]
updated the `latest` tarballs with the binary from `beta-20161103` and renamed the `beta-20161110` tarballs.

We now have:
```
$ aws s3 ls s3://binaries.cockroachdb.com
...
2016-11-03 16:12:15   13760469 cockroach-beta-20161103.darwin-10.9-amd64.tgz
2016-11-03 16:12:09   14203402 cockroach-beta-20161103.linux-amd64.tgz
2016-11-13 11:56:29   13833054 cockroach-beta-20161110.darwin-10.9-amd64.tgz.DO_NOT_USE
2016-11-13 11:56:59   14280142 cockroach-beta-20161110.linux-amd64.tgz.DO_NOT_USE
2016-11-13 11:51:41   13729797 cockroach-latest.darwin-10.9-amd64.tgz
2016-11-13 11:54:10   14164594 cockroach-latest.linux-amd64.tgz
```

**Comment by jseldess** [comment]
@bdarnell, I just ran docs teamcity project, so the live docs should be up-to-date soon.

**Pull request merged**
