### PR TITLE
Update secure-a-cluster.md

### PR DESCRIPTION
**Pull request by dbist**

### CODE REVIEW

**Comment by dbist** [comment]
@jseldess according to this [thread](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1581935937148700?thread_ts=1581577209.135700&cid=CP4D9LD5F), the steps to add user to admin role requires a server restart. I confirmed in my 19.2.4 environment that to be the case.

**Comment by jseldess** [comment]
@Amruta-Ranade, @taroface, which one of you can test this out and review Artem's changes? We need to be very careful to get the guidance right in our getting started docs. 

On a related node, this morning, I found that you can't even get to the Admin UI logic page for a secure local cluster on Chrome: https://github.com/cockroachdb/cockroach/issues/46319

**Comment by Amruta-Ranade** [comment]
@taroface Is it okay if I take this up?

**Comment by taroface** [comment]
@Amruta-Ranade Yes, sounds good!

**Comment by taroface** [comment]
@dbist Thanks for this! I think the same steps have to be repeated in other docs. Do you mind if I take over this PR and #6859 ?

**Comment by dbist** [comment]
yes go ahead

**Comment by dbist** [comment]
> @Amruta-Ranade, @taroface, which one of you can test this out and review Artem's changes? We need to be very careful to get the guidance right in our getting started docs.
> 
> On a related node, this morning, I found that you can't even get to the Admin UI logic page for a secure local cluster on Chrome: [cockroachdb/cockroach#46319](https://github.com/cockroachdb/cockroach/issues/46319)

@jseldess you can do the following on Chrome:

```
If you are using Google Chrome as your browser, you may want to navigate here chrome://flags/#allow-insecure-localhost and set this flag to Enabled.
```
courtesy of @timveil

**Comment by taroface** [comment]
@dbist I did not need to restart a node in order to access the secure Admin UI pages. Perhaps it's sufficient to add a note to this [callout](https://www.cockroachlabs.com/docs/stable/admin-ui-overview.html#admin-ui-access) that you "may need to restart a node for the changes to take effect". What do you think?

**Comment by dbist** [comment]
your mileage will vary, by all means, do what you think makes sense. Didn't work in my testing and as I pointed out before, users in community slack reported the same behavior. No issues on my side.

**Comment by taroface** [comment]
I opened #6958 based on this change. Closing this one!

**Pull request closed without merging**
