### PR TITLE
CC All Releases

### LINKED ISSUE #9455: Add an All Releases page for CockroachCloud
Currently, we add each month's release as an item in the sidebar. Now that we've been documenting CC releases for almost a year, I think it makes sense to only show the most recent month's release notes and move the rest to an "All Releases" page, [similar to what we do for CRDB](https://www.cockroachlabs.com/docs/releases/#production-releases).

I would like this page to be as automated as possible, which I think would require creating a version of [releases.yaml](https://github.com/cockroachdb/docs/blob/master/_data/releases.yml) to generate the table, show the latest release, the release dates, and a link to the relevant release notes.

@jseldess is the above assumption correct? Once the yaml file is created, how do we specify what page we want it to generate so we can link to it in the sidebar?

### PR DESCRIPTION
**Pull request by gemma-shay**
-Add Latest Release page
-Add All CC Releases page with script & yaml similar to CockroachDB Releases
-Remove versions from sidebar

Closes #9455

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/index-cc.md, line 2 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZXnn61DnPthjbba-g:-MSZXnn61DnPthjbba-h:bi1ak3q) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L2)):*
> ```Markdown
> ---
> title: CockroachCloud Releases
> ```

nit: can we rename this doc to be `releases/index-cockroachcloud.md`? That will keep it more consistent with the rest of our CockroachCloud doc names
___
*[releases/index-cc.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZY5EM8H-eN7cO_hOy:-MSZY5EM8H-eN7cO_hOz:bx2eyvj) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L7)):*
> ```Markdown
> ---
> 
> CockroachCloud [supports](/docs/cockroachcloud/upgrade-policy.html) the latest major version of CockroachDB and the version immediately preceding it. All clusters are subject to automatic upgrades to the latest supported minor version. When a new major version is available, [CockroachCloud Admins](/docs/cockroachcloud/console-access-management.html#console-admin) will be able to [start an upgrade directly from the CockroachCloud Console](/docs/cockroachcloud/upgrade-to-v20.2.html). [CockroachCloud Free (beta)](https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html) clusters are subject to automatic upgrades for both minor and major releases.
> ```

Suggested update:

```
CockroachCloud supports the latest major version of CockroachDB and the version immediately preceding it. All clusters are subject to automatic upgrades to the latest supported minor version. [CockroachCloud Free (beta)](../cockroachcloud/quickstart.html) clusters are subject to automatic upgrades for both minor and major releases.

For more information, see the [CockroachCloud Upgrade Policy](../cockroachcloud/upgrade-policy.html).
```

(Note: Links should be relative (../cockroachcloud/xyz.html) instead of absolute links where possible.)
___
*[releases/index-cc.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZZ4M-3gP-3H5IJQcJ:-MSZZ4M-3gP-3H5IJQcK:bsxj5q7) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L12)):*
> ```Markdown
>   <thead>
>     <tr>
>       <td>Version</td>
> ```

nit: I think this should be called "Release Notes" since "Version" is not quite correct (since the version would be v20.2.x, etc.)

Related question: Do you think the sidebar should say "Release Notes" / "Latest Release Notes" / "All Release Notes" instead of "Releases" , etc.? Again, "Releases" doesn't seem exactly correct since we're actually "releasing" every week or so, and these pages are just the notes about the features that were released during the month. Thoughts or other suggested names?
___
*[releases/index-cc.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZWonu4SFsK9X0cHxX:-MSZWonu4SFsK9X0cHxY:b-vfl9bs) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L32)):*
> ```Markdown
> </table>
> 
> Get future release notes emailed to you:
> ```

I think we can remove this sign up section since it's on each individual release notes page

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[releases/index-cc.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZY5EM8H-eN7cO_hOy:-MSZg1loCmAVUqyL0JUr:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L7)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggested update:

```
CockroachCloud supports the latest major version of CockroachDB and the version immediately preceding it. All clusters are subject to automatic upgrades to the latest supported minor version. [CockroachCloud Free (beta)](../cockroachcloud/quickstart.html) clusters are subject to automatic upgrades for both minor and major releases.

For more information, see the [CockroachCloud Upgrade Policy](../cockroachcloud/upgrade-policy.html).
```

(Note: Links should be relative (../cockroachcloud/xyz.html) instead of absolute links where possible.)
</blockquote></details>

Done.
___
*[releases/index-cc.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZWonu4SFsK9X0cHxX:-MSZgj3_EGiiRJUwsfe6:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L32)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think we can remove this sign up section since it's on each individual release notes page
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[releases/index-cc.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSZY5EM8H-eN7cO_hOy:-MScfda503godEP5lzMd:b-aznt45) ([raw file](https://github.com/cockroachdb/docs/blob/99717c93e97aa2de6ef7a971219b30e69def066b/releases/index-cc.md#L7)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing the updated content (re: suggested paragraph update). Did you commit?

**Comment by gemma-shay** [comment]
@lnhsingh it should be there, just double checked the commit. the file name was changed so it might not show up on index-cc. https://github.com/cockroachdb/docs/pull/9695/files#diff-c0581892e2addea9d6ac5d31c145c0cc34d83783fa965a6cdc46e5b50fa54089

**Comment by lnhsingh** [comment]
@gemma-shay I'm still seeing the old content:

```
CockroachCloud [supports](../cockroachcloud/upgrade-policy.html) the latest major version of CockroachDB and the version immediately preceding it. All clusters are subject to automatic upgrades to the latest supported minor version. When a new major version is available, [CockroachCloud Admins](../cockroachcloud/console-access-management.html#console-admin) will be able to [start an upgrade directly from the CockroachCloud Console](../cockroachcloud/upgrade-to-v20.2.html). [CockroachCloud Free (beta)](../cockroachcloud/quickstart.html) clusters are subject to automatic upgrades for both minor and major releases.
```

instead of 

```
CockroachCloud supports the latest major version of CockroachDB and the version immediately preceding it. All clusters are subject to automatic upgrades to the latest supported minor version. [CockroachCloud Free (beta)](../cockroachcloud/quickstart.html) clusters are subject to automatic upgrades for both minor and major releases.

For more information, see the [CockroachCloud Upgrade Policy](../cockroachcloud/upgrade-policy.html).
```

**Comment by gemma-shay** [comment]
@lnhsingh My bad, I misread that comment yesterday and thought it was just about the links! Sorry about that. Should be good now.

**Comment by lnhsingh** [comment]
No problem! This LGTM now, I think you can merge, unless you would feel
more comfortable with a second review (maybe from Jesse)

**Review by jseldess — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[_data/releases-cc.yml, line 4 at r4](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSd-p7y2PBVHC5av7J5:-MSd-p7y2PBVHC5av7J6:b-az2md5) ([raw file](https://github.com/cockroachdb/docs/blob/84bc48a50fbddc27bd1c48ebb618cd7b2a2ee0ef/_data/releases-cc.yml#L4)):*
> ```YAML
>   releases:
>     - name: January 2021
>       date: Jan 22, 2021
> ```

It doesn't look like the `date` field is getting used at all. If not, we should just remove it and go with `name` and `link`.
___
*[releases/index-cockroachcloud.md, line 18 at r4](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSd-PZ22R9wKZn6t71X:-MSd-PZ22R9wKZn6t71Y:b-8ndt1v) ([raw file](https://github.com/cockroachdb/docs/blob/84bc48a50fbddc27bd1c48ebb618cd7b2a2ee0ef/releases/index-cockroachcloud.md#L18)):*
> ```Markdown
>   </thead>
>   
>   {% for section in site.data.releases-cc %}
> ```

Glad you got this to work! My only concern is that it's weird to have a single column table. Would you be willing to adjust the html to create a bulleted list instead? I'm not certain the latest badge will work outside of a table, but it's worth a try and we could update the css.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9695)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess and @lnhsingh)

___
*[_data/releases-cc.yml, line 4 at r4](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSd-p7y2PBVHC5av7J5:-MSd2_QF9UTOPmePf4id:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/84bc48a50fbddc27bd1c48ebb618cd7b2a2ee0ef/_data/releases-cc.yml#L4)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

It doesn't look like the `date` field is getting used at all. If not, we should just remove it and go with `name` and `link`.
</blockquote></details>

Done!
___
*[releases/index-cockroachcloud.md, line 18 at r4](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSd-PZ22R9wKZn6t71X:-MSd2gJR3YFInWiBw1td:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/84bc48a50fbddc27bd1c48ebb618cd7b2a2ee0ef/releases/index-cockroachcloud.md#L18)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Glad you got this to work! My only concern is that it's weird to have a single column table. Would you be willing to adjust the html to create a bulleted list instead? I'm not certain the latest badge will work outside of a table, but it's worth a try and we could update the css. 
</blockquote></details>

Done.

**Review by jseldess — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9695#-:-MSdkw7rBjWheBZFH9HS:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[releases/index-cockroachcloud.md, line 18 at r4](https://reviewable.io/reviews/cockroachdb/docs/9695#-MSd-PZ22R9wKZn6t71X:-MSdkpiT8lyaoiRTwTlN:b-cbyh0a) ([raw file](https://github.com/cockroachdb/docs/blob/84bc48a50fbddc27bd1c48ebb618cd7b2a2ee0ef/releases/index-cockroachcloud.md#L18)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very nice! Thank you.

**Pull request merged**
