### PR TITLE
help widget

### PR DESCRIPTION
**Pull request by eballeste**
new static help widget with links to gitter & forum

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/988)

### CODE REVIEW

**Comment by jseldess** [comment]
Looks great overall, @eballeste. However, just noticed that, if you get the newsletter signup overlay to pop up by scrolling to bottom of a page, you now can't close that overlay because it's behind the help buttons. 

screen shot 2017-01-12 at 10 25 38 am

**Comment by jseldess** [comment]
We'll also need to revise the **Need Help?** section of `contribute-to-cockroachdb.md`. I'm happy to do that in a follow-up PR, though, if you prefer.

**Comment by eballeste** [comment]
Need to talk it over with Nick and Kuan, seems like we need to reposition
the buttons location so that it doesn't rest on the close button. Will be
able to include updating the link in this same PR.

**Comment by jseldess** [comment]
Thank you, @eballeste. @jess-edwards and I just looked and we're worried that there are too many inconsistently positioned elements now. Can we try the following:

- Right-align the Help button(s) with the back to top button. 
- Position the back to top button a few hundred pixels above where the Forum button appears (when hovering on Help). This involves changing the js associated to the back to top button, so it is a bit of an expansion of scope, but consistent positioning would be best. 

cc @kuanluo

**Comment by kuanluo** [comment]
What @jseldess proposed sounds good to me.

**Comment by eballeste** [comment]
positioned back to top button relative to the content-col and also cached its visibility state in order to avoid chaining fadeOut/fadeIn animations it was doing previously

**Comment by kuanluo** [comment]
@eballeste 

I think what what @jseldess meant is to move the Help button out of the content-col to right align with the Back to Top button, so it doesn't cover content in Docs.

**Comment by eballeste** [comment]
@kuanluo this is not possible if you want to keep the help buttons to stay
static but stop just above the footer, the way the site is structured will
not allow it.

**Comment by kuanluo** [comment]
@eballeste 

Gotcha. Then my vote is to go with what's on staging, and test it out to see usage. 

@jess-edwards @jseldess Thoughts?

**Comment by jess-edwards** [comment]
@kuanluo & @eballeste & @jseldess 

The constraint makes sense. I care more that the buttons were in alignment with each other, so this solution works. If we see good usage, we can consider investing more hours into figuring out how to break the page constraints. 

LGTM.

**Comment by jseldess** [comment]
@eballeste, I don't understand why the help and back to top buttons need the `right: 90px` styling, which causes them to overlap the body content? how does the site structure not allow them to be in the whitespace of the right margin instead?

**Comment by eballeste** [comment]
The only way I could think of keeping the button from scrolling below the
footer is to place them in the html right before it and switch between
having absolute and fixed positions for them. I can't place them in a
separate div between the main content block and the footer because it would
push the footer down while the border that divides the sidenav and the
content on the left break due to that gap. Since the next option is putting
it inside the .content-col box, the 90px to the right of the window is
where the button would be when i remove its fixed positon when the user
reaches the footer. This right position also depends on browser width which
further complicates things.

**Comment by jseldess** [comment]
I see. Thanks for the explanation, @eballeste.

For me, it's more important, in terms of user experience, for the help button to be right aligned (and thus not overlapping content on desktop-sized screens) than it is for it not to scroll onto the footer. 

If we do right align, can we avoid the initial problem I reported (not being able to close the email signup) without stopping the help button before the footer? 

I don't want to add a big delay here, but I really don't like current experience.

cc: @kuanluo

**Comment by kuanluo** [comment]
I'm also not a fan of blocking text on Docs with the help button.

> can we avoid the initial problem I reported (not being able to close the email signup) without stopping the help button before the footer?

@eballeste  Possible to do what @jseldess proposed by end of day?

**Comment by eballeste** [comment]
@kuanluo @jseldess, I could revert to its original iteration and make sure that it's stacked behind the popup banner but then we would confront @kuanluo's original problem of the buttons landing on top of the hubspot form on the footer. 

I was thinking about it this morning on my way to work and I think I might be able to keep it from landing on the footer but also break it from the margin restraints of the `.container` div.

**Comment by kuanluo** [comment]
@eballeste That will be magical. What's the time cost? 

cc @jseldess

**Comment by jseldess** [comment]
Yes, that'd be great, @eballeste. Thank you. Interested to hear your solution.

**Comment by eballeste** [comment]
@jseldess @kuanluo was able to figure out a workaround, now placed in footer div but outside of the main container, also needed to dynamically figure out it's top position in order to push it out of the footer vertically.

**Comment by jseldess** [comment]
Looks and behaves excellent now, @eballeste! Thanks for making this work. I'll merge.

**Comment by kuanluo** [comment]
Thanks to you both! Very excited to have this live!

**Pull request merged**
