### PR TITLE
Update locality optimized search limitation.

### PR DESCRIPTION
**Pull request by stbof**
https://cockroachlabs.atlassian.net/browse/DOC-3311
https://cockroachlabs.atlassian.net/browse/DOC-2664

### CODE REVIEW

**Review by msirek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13790)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stbof)

___
*[`_includes/v22.1/sql/locality-optimized-search-limited-records.md` line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/13790#-N1ErLKcET0ngB5nUkS9:-N1ErLKcET0ngB5nUkSA:by7lfw4) ([raw file](https://github.com/cockroachdb/docs/blob/d7f7ada21b1115668722be76bd179950cee55ddc/_includes/v22.1/sql/locality-optimized-search-limited-records.md#L4)):*
> ```Markdown
> 
>     - The table is defined with `LOCALITY REGIONAL BY ROW`.
>     - The number of qualified rows (the sum of the `LIMIT` clause and optional `OFFSET` clause values) residing in the local region is less than or equal to `100000`.
> ```

The limitation in the old version of the docs applies to non-LIMIT queries too, so the new wording makes it sound a little bit like only LIMIT queries have the 100,000 rows (unique keys) limitation.  So, for the documentation we can probably keep the original text and just remove the part which mentions the restriction on LIMIT clauses:
```
Locality optimized search only works for queries selecting a limited number of records (up to 100,000 unique keys).
```

Is there a section of the docs highlighting new features which should mention removal of the restriction on LIMIT clauses?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13790)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stbof)

___
*[`_includes/v22.1/sql/locality-optimized-search-limited-records.md` line 4 at r1](https://reviewable.io/reviews/cockroachdb/docs/13790#-N1ErLKcET0ngB5nUkS9:-N1F3TvH789Lnt7Ikzwb:b-ucfknh) ([raw file](https://github.com/cockroachdb/docs/blob/d7f7ada21b1115668722be76bd179950cee55ddc/_includes/v22.1/sql/locality-optimized-search-limited-records.md#L4)):*
<details><summary><i>Previously, stbof (Stephanie Bodoff) wrote…</i></summary><blockquote>

There's a release note towards the end of this section: https://www.cockroachlabs.com/docs/releases/v22.1.html#v22-1-0-alpha-2-performance-improvements
</blockquote></details>

Thanks!

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13790#-:-N1FLwQ8ByVU4ehAGq2v:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @stbof)

**Review by rmloveland — APPROVED** [review]
LGTM

**Pull request merged**
