### PR TITLE
Offset anchor IDs from page header

### LINKED ISSUE #217: Use CSS to jump to anchors
We're currently using JavaScript to jump to anchors on click (anchors in js-generated page tocs and in js-generate anchor icons next to headings). See [`_layouts/page.html`](https://github.com/cockroachdb/docs/blob/gh-pages/_layouts/page.html).

In these cases, the JavaScript adds the proper padding so that the header isn't under the topnav, but if you copy the URL and paste it into a new browser, the proper padding is gone.

@mjibson has a better solution for all of this using css.

### PR DESCRIPTION
**Pull request by mjibson**
Remove JS click scrolls.

Fixes #217

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/227)

### CODE REVIEW

**Comment by jseldess** [comment]
Anchors working great now, but it looks like you removed some necessary padding above headings. 

Compare this branch:

screen shot 2016-04-19 at 11 18 40 am

With the live version:

screen shot 2016-04-19 at 11 18 49 am

LGTM once you can put that padding back in.

**Comment by mjibson** [comment]
I fixed those headers. Things look pretty good now.

**Comment by jseldess** [comment]
Thanks, Matt. I hate to nitpick here, but I think we still need a little more padding above headings. Can you get it a little closer to how it is on the live site? 

This branch:
screen shot 2016-04-19 at 10 45 13 pm

Live site:
screen shot 2016-04-19 at 10 45 25 pm

**Comment by mjibson** [comment]
Spacing between headers is now identical to the old version (afaict). There is 20px more between the TOC and the first header, which appears to be the same as between header sections. Ok?

**Comment by jseldess** [comment]
Looks excellent now. Thanks, @mjibson!

**Pull request merged**
