### PR TITLE
Style guide for lists

### LINKED ISSUE #1492: style guide: paragraphs/code blocks in a list item
After https://github.com/cockroachdb/docs/pull/1477 is merged, paragraphs or code blocks following a list item (bullet or number) need to be indented 4 times. We should add this guidance to our basic [style guide](https://github.com/cockroachdb/docs/blob/gh-pages/CONTRIBUTING.md#code-samples).

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1492

### CODE REVIEW

**Comment by sploiselle** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1493#-:-KlyXm-mPokibOBbBU1M:bnfp4nl)*

**Comment by sploiselle** [comment]
Also, per our discussion, indenting code blocks under nested list items requires 8 spaces. I don't think we'll have any of these, but because it's an edge case, might be worth documenting.

**Comment by jseldess** [comment]
Just added more details, @sploiselle. PTAL.

**Comment by sploiselle** [comment]
Looks even good-er to me. Thanks, @jseldess

**Pull request merged**
