### PR TITLE
Style guide QA updates

### PR DESCRIPTION
**Pull request by deronjohnson**
Addresses further QA items on the recent style guide push.

### CODE REVIEW

**Comment by jseldess** [comment]
Thank you, @deronjohnson. To make it easier to review, would you please summarize the updates for us?

**Comment by deronjohnson** [comment]
Sure!
- Change remaining instances of 18px font to 17px.
- Update styling on "was this page helpful buttons."
- Reduce font size and vertical spacing on table of contents.
- Add underline to hover on code links.
- Decrease horizontal space between text and arrows in sidebar.
- Add top border and padding to footer.
- Update $ sign color in terminal code snippets (further update incoming on this).

**Comment by jseldess** [comment]
LGTM! @sploiselle, @kuanluo should probably review as well.

**Comment by kuanluo** [comment]
LGTM as well! Thank you!

**Comment by sploiselle** [comment]
LGTM

**Comment by jseldess** [comment]
Great! Merging now.

**Pull request merged**
