### PR TITLE
add --self flag to node drain

### PR DESCRIPTION
**Pull request by taroface**
Fixes DOC-2211.

Added `--self` flag to `node drain` reference (v22.1 and v21.2).

### CODE REVIEW

**Review by knz — APPROVED** [review]
thanks

**Review by kathancox — APPROVED** [review]
Looks good Ryan!

**Review by MichaelTrestman — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13398)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Review by MichaelTrestman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13398#-:-MzqAR4e86NCLj26i0s2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

**Pull request merged**
