### PR TITLE
Minor improvements to Install CockroachDB page

### LINKED ISSUE #1999: Install CockroachDB Doc Update
Re: [Install CockroachDB](https://cockroachlabs.com/docs//v1.1/install-cockroachdb.html)

## Issue Description
The "quick start" link just redirects back to the install page.

### PR DESCRIPTION
**Pull request by jseldess**
- Fix a link
- Remove extra language to shorten page
- Remove h2 headers
- Make homebrew the default for mac

Fixes #1999

### CODE REVIEW

**Comment by jseldess** [comment]
@nstewart, @kuanluo, can you take a look? I'd like to merge these changes. In a follow-up PR, @j-low will reduce the size of the OS tabs.

**Comment by kuanluo** [comment]
👍 Great short-term improvement. Thoughts on changing the copy "Get future release notes emailed to you" to something stronger? Once the OS tabs are reduced in size, the page would be better! @jess-edwards should take a look, too. Thanks, @jseldess!

**Comment by jseldess** [comment]
@kuanluo, oh right, I forgot to change that copy to "Keep up-to-date with CockroachDB software releases and usage best practices", which we use in the footer overlay. I'll do that now.

**Comment by kuanluo** [comment]
@jseldess LGTM! Thanks!

**Comment by jess-edwards** [comment]
@jseldess  LGTM

Love the copy update to "Keep up to date..." =)

**Pull request merged**
