### PR TITLE
Docs for 1.0.1 release

### PR DESCRIPTION
**Pull request by jseldess**
- Add known limitation about dropping db containing views
- Add known limitation about quoting uppercase collation locales
- Add known limitation on qualifying columns from views
- Make risks of insecure deployment more explicit
- Mark known limitation about creating views with arrays as resolved
- Mark known limitation about running Win as non-admin as resolved
- Remove mention of needing to enter password twice when using it

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1456)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-:-KkvUEMyPX0N6AqdsZo7:bnfp4nl)*

**Comment by sploiselle** [comment]
:lgtm: w/ a few minor nits

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[deploy-cockroachdb-on-aws-insecure.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-KkvUG7p0OeKj8rH-M3a:-KkvUG7p0OeKj8rH-M3b:b-l2ndw9) ([raw file](https://github.com/cockroachdb/docs/blob/74f750b2644de65da7056d926409b52d2a13c73b/deploy-cockroachdb-on-aws-insecure.md#L26)):*
> ```Markdown
> 
> - If you plan to use CockroachDB in production, we recommend using a [secure cluster](deploy-cockroachdb-on-aws.html) instead. Using an insecure cluster comes with risks:
>   - Your cluster is open for any client that can access any nodes' IP addresses.
> ```

nit: s/for any client/to any client/

If you agree, also needs to be changed in other insecure deployment docs.

---

*[known-limitations.md, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-KkvVBcUvJXBr_yepHGz:-KkvVBcUvJXBr_yepHH-:b-7wbex8) ([raw file](https://github.com/cockroachdb/docs/blob/74f750b2644de65da7056d926409b52d2a13c73b/known-limitations.md#L133)):*
> ```Markdown
> ~~~
> 
> As a workaround, make the locale lowercase or remove the quotes.
> ```

nit: Would love a quick example of what this is supposed to look like here.

---

*[start-a-node.md, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-KkvVsjo-OENQ2GhKGqj:-KkvVsjo-OENQ2GhKGqk:b67tcac) ([raw file](https://github.com/cockroachdb/docs/blob/74f750b2644de65da7056d926409b52d2a13c73b/start-a-node.md#L40)):*
> ```Markdown
> `--http-host` | The hostname or IP address to listen on for Admin UI HTTP requests. <br><br>**Default:** same as `--host`
> `--http-port` | The port to bind to for Admin UI HTTP requests. <br><br>**Default:** `8080`
> `--insecure` | Run in insecure mode. If this flag is not set, the `--certs-dir` flag must point to valid certificates.<br><br><strong>Note the following risks:</strong> An insecure cluster is open for any client that can access the node's IP addresses; any user, even `root`, can log in without providing a password; any user, connecting as `root`, can read or write any data in your cluster; and there is no network encryption or authentication, and thus no confidentiality.<br><br>**Default:** `false`
> ```

same nit: s/open for/open to/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-:-KkvVzL0wUFlcrB7CRhD:b-1ndq8r)*

**Comment by mberhault** [comment]
LGTM

**Comment by jseldess** [comment]
TFTRs! 

---

Review status: 6 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy-cockroachdb-on-aws-insecure.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-KkvUG7p0OeKj8rH-M3a:-KkvaAgsXQ55J6k49YFN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74f750b2644de65da7056d926409b52d2a13c73b/deploy-cockroachdb-on-aws-insecure.md#L26)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

nit: s/for any client/to any client/

If you agree, also needs to be changed in other insecure deployment docs.
</blockquote></details>

Done.

---

*[known-limitations.md, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-KkvVBcUvJXBr_yepHGz:-KkvbEDkVHbWcvzLoPlu:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74f750b2644de65da7056d926409b52d2a13c73b/known-limitations.md#L133)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

nit: Would love a quick example of what this is supposed to look like here.
</blockquote></details>

Done.

---

*[start-a-node.md, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-KkvVsjo-OENQ2GhKGqj:-KkvbGs46-Z_XIGoaFXQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74f750b2644de65da7056d926409b52d2a13c73b/start-a-node.md#L40)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

same nit: s/open for/open to/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1456#-:-KkvbM56h-alzv-H9mZa:bodi8jh)*

**Pull request merged**
