### PR TITLE
Replication Zone Constraints error

### PR DESCRIPTION
**Pull request by dgabriel123**
Updated the language for the 'constraints' variable. Updated in versions 19.2 20.1 and 20.2 (#7781 ).

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
Can we reword the new text as:
"To prevent this error, make sure at least one active node is configured to match the constraint. For example, apply  `constraints = '[-region=west]'` only if you had set `--locality=region=west` for at least one node while starting the cluster."

cc @florence-crl

**Comment by dgabriel123** [comment]
> Can we reword the new text as:
> "To prevent this error, make sure at least one active node is configured to match the constraint. For example, apply `constraints = '[-region=west]'` only if you had set `--locality=region=west` for at least one node while starting the cluster."
> 
> cc @florence-crl

all set with the copy update @Amruta-Ranade . Let me know if I missed anything.

**Comment by Amruta-Ranade** [comment]
I made a mistake in the suggested text..it should be `constraints = '[+region=west]'` instead of `constraints = '[-region=west]'`. Sorry!

**Comment by dgabriel123** [comment]
> I made a mistake in the suggested text..it should be `constraints = '[+region=west]'` instead of `constraints = '[-region=west]'`. Sorry!

No problem at all! Corrected.

**Pull request merged**
