### PR TITLE
DOC-7159 cpu usage merics new and improved

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-7159

- Updated metrics description to match upstream changes. As a reminder, docs will shortly be unable to present metrics descriptions that differ from upstream in any way. If you want metrics descriptions to be different in docs copy, please amend your `X.go` HELP text values. Updated descriptions:
	- `sys.cpu.sys.ns`
	- `sys.cpu.sys.percent`
	- `sys.cpu.user.ns`
	- `sys.cpu.user.percent`
- Added new metrics, one new in upstream PR, 2 new to the docs team, as lest per our ticketing system:
	- `sys.cpu.combined.percent-normalized`
	- `sys.cpu.host.combined.percent-normalized`
	- `sys.cpu.now.ns`
- Added new graph to Metrics > Hardware dashboard in DB Console.
- Minor clarification to existing CPU graph (process only) to help differentiate between new CPU graph (hostwide).

Staging

[v23.1/metrics.md](https://deploy-preview-16519--cockroachdb-docs.netlify.app/docs/dev/metrics.html) | [v23.1/ui-hardware-dashboard.md](https://deploy-preview-16519--cockroachdb-docs.netlify.app/docs/dev/ui-hardware-dashboard.html#host-cpu-percent)

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/16519#-:-NRoL4xm36FU6n5eH1Ih:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andf-crl)

___
*[`v23.1/ui-hardware-dashboard.md` line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/16519#-NRoICIh82yo01h6dxAB:-NRoICIh82yo01h6dxAC:b-2maj34) ([raw file](https://github.com/cockroachdb/docs/blob/8f1e67c2ddf2de6f8cb8f277dc6eeeef679ab9cd/v23.1/ui-hardware-dashboard.md#L20)):*
> ```Markdown
> {% include {{ page.version.version }}/ui/cpu-percent-graph.md %}
> 
> ## Host CPU Percent
> ```

consider adding a note explaining that measurement artifacts can make these metrics appear to be slightly less than the CRDB CPU consumption when everything else on the host is really silent. See https://github.com/cockroachdb/cockroach/issues/99740 and https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1679949478356079
___
*[`v23.1/ui-hardware-dashboard.md` line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/16519#-NRoIW5MDWOKvy0iEd6Q:-NRoIW5MDWOKvy0iEd6R:b-ufq92i) ([raw file](https://github.com/cockroachdb/docs/blob/8f1e67c2ddf2de6f8cb8f277dc6eeeef679ab9cd/v23.1/ui-hardware-dashboard.md#L20)):*
> ```Markdown
> {% include {{ page.version.version }}/ui/cpu-percent-graph.md %}
> 
> ## Host CPU Percent
> ```

Consider making a note about containers, saying that the value is normalized to the number of cores the machine has, not the number of cores that crdb might be limited to.
This is in contrast to the crdb cpu usage, which is normalized to the container (maybe this can be spelled out in the docs for the respective metrics, if they're not already).
___
*[`v23.1/ui-hardware-dashboard.md` line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/16519#-NRoHr1-1ohjhsbb5voN:-NRoHr1-1ohjhsbb5voO:brxf7yx) ([raw file](https://github.com/cockroachdb/docs/blob/8f1e67c2ddf2de6f8cb8f277dc6eeeef679ab9cd/v23.1/ui-hardware-dashboard.md#L25)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> This graph shows the CPU consumption by the host the CockroachDB process is running on, including other processes on the host. To measure the CPU consumption of just the CockroachDB process, use the **PU Percent** graph instead.
> ```

is the **PU Percent** right?
___
*[`v23.1/ui-hardware-dashboard.md` line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/16519#-NRoHvwoARIC5yRD-iAX:-NRoHvwoARIC5yRD-iAY:b-wm9scw) ([raw file](https://github.com/cockroachdb/docs/blob/8f1e67c2ddf2de6f8cb8f277dc6eeeef679ab9cd/v23.1/ui-hardware-dashboard.md#L25)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> This graph shows the CPU consumption by the host the CockroachDB process is running on, including other processes on the host. To measure the CPU consumption of just the CockroachDB process, use the **PU Percent** graph instead.
> ```

maybe s/by the host/on the host

**Comment by andf-crl** [comment]
@andreimatei Thanks Andrei! Pleasure working with you!

**Review by MichaelTrestman — APPROVED** [review]
LGTM

**Comment by mikeCRL** [comment]
Will raise a new PR to prevent conflicts, address 23.2 docs, and merge to the newer `main` branch.

**Pull request closed without merging**
