### PR TITLE
CC Dedicated Credits Billing Info

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/DOC-2257

~~Remove warnings about contract cluster self-service restrictions
Document how to see amount of credits spent~~
Update doc for new billing page layout

### CODE REVIEW

**Comment by jramos-crl** [comment]
@gemma-shay everything looks good to me pending timing. Are you planning to keep this on hold until everything is released? We could release it in phases alongside the features too if you want.
Phase 1 - overview/billing page changes + invoice history
Phase 2 - remove the "self-serve" contract customer limitations + add credits information

Up to you how you prefer to handle it. The information itself looks good to me.

**Comment by gemma-shay** [comment]
@jramos-crl Sorry I missed your comment before the holidays; what's the best guess eta for Phase 2? I can cut this down to Phase 1 changes if it's more than a week or two away.

**Comment by jramos-crl** [comment]
@gemma-shay no worries! Phase 2 will probably take at least a month after Phase 1. We will release the overview page and invoice history first and then a month or so later I would expect the credits to be released.

**Comment by gemma-shay** [comment]
@jramos-crl I cut this down to the new billing layout, going to create separate tickets for 1) invoices and 2) credits + contract scaling. Just a matter of un-commenting some text and deleting a callout, so can have PRs ready for whenever the changes go out.

**Comment by jramos-crl** [comment]
@gemma-shay perfect that works with me. Are you good to create the ticket in Jira? Thank you!

**Comment by gemma-shay** [comment]
Credits + contract scaling: https://cockroachlabs.atlassian.net/browse/DOC-1936
Invoices: https://cockroachlabs.atlassian.net/browse/DOC-2258

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
