### PR TITLE
style updates for docs sidebar

### PR DESCRIPTION
**Pull request by elkmaster**
Screenshot 2020-10-19 at 18 40 29

Resolves: #8059, #7295

### CODE REVIEW

**Comment by anagio** [comment]
This looks good to me

**Comment by lnhsingh** [comment]
The nav/links itself looks good! Will the nav align left once you add in mobile adaptation? Also, will the narrow grey bar to the right of the nav go away once independent scroll is implemented?

Screen Shot 2020-10-21 at 1 13 51 PM

**Comment by luciaaaaaaa** [comment]
Feedback:
- Hover states should be darker shade of grey rather than underline (UI/text 3) 
- Do we have a loading state? seeing everything just kind of jump to next section and realizing this was not included in the design system

**Comment by luciaaaaaaa** [comment]
- Side-nav. 'Quickstart' was not considered in the design. In the homepage, we have space to incorporate this to give users the ability to jump into that option. do we still want it in the side-nav? @lnhsingh cc @jseldess

**Comment by jseldess** [comment]
I think it's good to have in the sidenav for now. It's ok to be in both places.

@lnhsingh, @luciaaaaaaa, have we taking a close look at the content on the landing page? My sense is that the overall design is clear but that we still need to nail down the topics/links?

**Comment by luciaaaaaaa** [comment]
Yes @jseldess that's on our to-do list for today actually! We can share updates for next week's catch up

**Comment by lnhsingh** [comment]
@elkmaster following up here - were you able to address my and @luciaaaaaaa's feedback? Do you need anything from us?

**Comment by elkmaster** [comment]
Sorry forgot to post comment here, latest commit should contain feedback items resloved

- _Hover states should be darker shade of grey rather than underline (UI/text 3)_. - done
- _Do we have a loading state? seeing everything just kind of jump to next section and realizing this was not included in the design system_ - no we don't have. ticket\design needed
- _Will the nav align left once you add in mobile adaptation_ - yes
- _will the narrow grey bar to the right of the nav go away once independent scroll is implemented_ - I do not have such thing, but I have a mac. Could you check latest commit if it still there?

Menu items itself left untouched. Should we change anything here?

**Comment by lnhsingh** [comment]
Looking good! I'm still seeing the narrow grey bar (I'm also on Mac and I tried it in Chrome and Firefox and saw it in both) - are others seeing it?

Screen Shot 2020-11-10 at 12 44 05 PM

I don't think anything needs to be done for the menu items themselves - @luciaaaaaaa can you confirm? The links and everything are edited/updated by the docs writers.

**Comment by luciaaaaaaa** [comment]
Hi, we still need to remove the underline and replace for a darker shade of grey as hover state (UI/text 3) 
Otherwise it looks good to me. 
Note that this is likely to be impacted by the changes we need to do on the primary nav bar

**Comment by elkmaster** [comment]
@luciaaaaaaa, 

it was done for second-tier+ menu items. 
Screenshot 2020-11-17 at 15 54 25

top level menu is already pretty dark (#242A35), almost black. so darker tone on hover is invisible. thats why I left it with underline.
Screenshot 2020-11-17 at 15 54 31

**Comment by anagio** [comment]
@lnhsingh i'll fix these conflicts locally and get the sidebar into our dev branch

**Comment by lnhsingh** [comment]
@anagio thank you!

**Pull request merged**
