### PR TITLE
Clarified content about email alerts

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Addresses [DOC-9152](https://cockroachlabs.atlassian.net/browse/DOC-9152)
- If you have maintenance windows set up, you will get emails about basically all maintenance and version upgrades
- If you don’t, you will only get emails about version upgrades (which we’ve always sent out anyway)
Update: Removed content re: email notifications from the maintenance window section since the notifications are not tied to maintenance windows

### CODE REVIEW

**Comment by kannanlakshmi** [comment]
actually based on a few more conversations [here](https://cockroachlabs.slack.com/archives/C01CD39JX8E/p1699301650696879?thread_ts=1699299934.871019&cid=C01CD39JX8E) 
turns out we only send emails about minor version upgrades, not about K8s - this is true regardless of whether windows are set or not. So we should just update docs to remove mention of "all other upgrades" as thats not true today.

**Comment by kannanlakshmi** [comment]
This is a nit - "scheduled upgrades"--> "minor or patch release versions of CockroachDB upgrades" ? Or something that clarifies that its CRDB _minor upgrades__ 

Also "Scheduled" is a bit confusing - because even customers who dont use MW will get upgrade emails, do we consider those scheduled?

**Comment by Amruta-Ranade** [comment]
Based on a Slack convo with @kannanlakshmi: Remove the content re: email notifications from the maintenance windows section since the notifications are not tied to maintenance windows.

**Review by kannanlakshmi — COMMENTED** [review]
Thank you - will we add this detail back in some other part of our docs? I think this could fit wherever we talk about alerts, potentially?

**Comment by Amruta-Ranade** [comment]
@kannanlakshmi The [Alerts page](https://www.cockroachlabs.com/docs/cockroachcloud/alerts-page#configure-alerts) talks about it:

> Cluster Maintenance:
> 
> When a cluster is scheduled for [maintenance or a patch upgrade](https://www.cockroachlabs.com/docs/cockroachcloud/cluster-management#set-a-maintenance-window) that could temporarily impact the cluster's performance.

Let me know if we need to edit the content.

**Comment by Amruta-Ranade** [comment]
Based on a Slack convo with @kannanlakshmi : The Alerts page has the information we want, but the page structure makes it difficult to find. Opened a [follow-up issue](https://cockroachlabs.atlassian.net/browse/DOC-9214) to restructure the page.

**Review by mdlinville — APPROVED** [review]

**Pull request merged**
