### PR TITLE
Fix typo: Jepson -> Jepsen

### PR DESCRIPTION
**Pull request by loverdos**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/418)

### CODE REVIEW

**Comment by jseldess** [comment]
:lgtm: Thanks for catching these, @loverdos.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/418#-:-KL0y1aes5B1VDPQovp3:-1297913725)*

**Comment by jseldess** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/418)*

**Comment by jseldess** [comment]
@mberhault, the aws sync step of circle ci failed on this pr as well. Any ideas?

**Comment by loverdos** [comment]
My pleasure :)

**Pull request merged**
