### PR TITLE
Update BACKUP, RESTORE, SHOW BACKUP

### LINKED ISSUE #7831: bulkio: Support running BACKUP under transaction.
PR: https://github.com/cockroachdb/cockroach/pull/50775

From release notes:
> `BACKUP` can now run in a new `detached` mode, which means the Job ID is now returned immediately without waiting for the `BACKUP` job to finish. [#50775][#50775] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8040: SHOW BACKUP: start_time and end_time descriptions are wrong
https://www.cockroachlabs.com/docs/v20.1/show-backup.html

They say:
`start_time: The time at which the backup was started. For a full backup, this will be empty.`
`end_time: The time at which the backup was completed.`

When in fact
`start_time` is the earliest data encapsulated in that backup. So if you have a full backup, it's null. If it's incremental, then it captures changes that occurred between the `start_time` and `end_time`
`end_time` is equivalent to the AOST of the backup itself -- the time to which a user can restore. Without revision_history, it's the only time a user can restore to. WITH revision_history it's the latest time they can restore to.

### LINKED ISSUE #8119: parser, backupccl: support running RESTORE in explicit txn
PR: https://github.com/cockroachdb/cockroach/pull/52779

From release notes:
> The [`RESTORE`](../v20.2/restore.html) statement can now run in "detached" mode. That is, instead of waiting for the `RESTORE` job to finish, the job ID is returned immediately, and the job itself runs in the background. [#52779][#52779] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8293: backupccl: add SHOW BACKUPS IN Y and SHOW BACKUP x IN Y
PR: https://github.com/cockroachdb/cockroach/pull/52758

From release notes:
> [`SHOW BACKUP`](../v20.2/show-backup.html) can be used to list backups in a backup collection created by `BACKUP ... INTO`. [#52758][#52758] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8340: backupccl: update SHOW BACKUP to show all descriptors
PR: https://github.com/cockroachdb/cockroach/pull/53321

From release notes:
> [`SHOW BACKUP`](../v20.2/show-backup.html) now shows all schemas in a backup. Previously, databases, types, and schemas were not shown. **Note:** This introduces a **breaking change** in that it changes the schema of `SHOW BACKUP` and will no longer return the column `table_name`. This column is replaced by the more general `object_name`. [#53321][#53321] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by lnhsingh**
`BACKUP`
- Added the `detached` option. Closes #7831.

`RESTORE`
- Added the `detached` option. Closes #8119.

`SHOW BACKUP`
- Corrected the `start_time` and `end_time` descriptions. Closes #8040.
- Updated the `SHOW BACKUP` response. Closes #8340.
- Added new syntax `SHOW BACKUPS IN y` and `SHOW BACKUP x IN y`. Closes #8293.

This update partially addresses #8431. Note that I will not be making updates to the `BACKUP` statement page to include the new `BACKUP INTO` syntax until after the release. See #8431 for more details.

### CODE REVIEW

**Review by mwang1026 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, and @mwang1026)

___
*[_includes/v20.2/backups/backup-options.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI15QlS8bg15as7hEjG:-MI15QlS8bg15as7hEjH:b-fn4bli) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/_includes/v20.2/backups/backup-options.md#L5)):*
> ```Markdown
> `revision_history`<a name="with-revision-history"></a>           | N/A                     | Create a backup with full [revision history](take-backups-with-revision-history-and-restore-from-a-point-in-time.html), which records every change made to the cluster within the garbage collection period leading up to and including the given timestamp.
> `encryption_passphrase`<a name="with-encryption-passphrase"></a> | [`STRING`](string.html) | The passphrase used to [encrypt the files](take-and-restore-encrypted-backups.html) (`BACKUP` manifest and data files) that the `BACKUP` statement generates. This same passphrase is needed to decrypt the file when it is used to [restore](take-and-restore-encrypted-backups.html) and to list the contents of the backup when using [`SHOW BACKUP`](show-backup.html).
> `detached`                                                       | N/A                     | <span class="version-tag">New in v20.2:</span> When a backup runs in `detached` mode, the backup job will execute asynchronously and the job ID will be returned immediately without waiting for the job to finish.
> ```

May also not be clear that it won't return on failed or succeeded? They have to check the job status itself to know if it finished or not if they use detached. Same with RESTORE as well.
___
*[v20.2/show-backup.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI163up4vcjQPBVx7AQ:-MI163uqBAJPGBI3ViAZ:bxyzirj) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/v20.2/show-backup.md#L24)):*
> ```Markdown
> ----------|------------
> `SHOW BACKUP location` | Show the details of the backup in the given [`location`](backup.html#backup-file-urls). [See the example below](#show-a-backup).
> `SHOW BACKUP SCHEMAS` | Show the schema details of the backup. [See the example below](#show-a-backup-with-schemas).
> ```

Maybe `SHOW BACKUP SCHEMAS location` for consistency?
___
*[v20.2/show-backup.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI18Swm1FBKJlHu0Jkt:-MI18Swm1FBKJlHu0Jku:bjy0i8x) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/v20.2/show-backup.md#L189)):*
> ```Markdown
>           path
> ------------------------
>   2020/09/24-204152.88
> ```

nit: Maybe an example with more than one subdirectory?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @mwang1026)

___
*[_includes/v20.2/backups/backup-options.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI15QlS8bg15as7hEjG:-MIKikv4DqD8-1nC1BwO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/_includes/v20.2/backups/backup-options.md#L5)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

May also not be clear that it won't return on failed or succeeded? They have to check the job status itself to know if it finished or not if they use detached. Same with RESTORE as well.
</blockquote></details>

Done.
___
*[v20.2/show-backup.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI163up4vcjQPBVx7AQ:-MIKixxrCuBVduPfcpTP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/v20.2/show-backup.md#L24)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

Maybe `SHOW BACKUP SCHEMAS location` for consistency?
</blockquote></details>

Done.
___
*[v20.2/show-backup.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI18Swm1FBKJlHu0Jkt:-MIKkM-JDrior-reF2et:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/v20.2/show-backup.md#L189)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

nit: Maybe an example with more than one subdirectory?
</blockquote></details>

Done.

**Review by mwang1026 — COMMENTED** [review]
Thoughts on adding a `SHOW BACKUPS IN` example to the `Manage a backup schedule` doc? Just got a question about that from a customer that was testing it out today and it might not be clear how to inspect the context of a backup "collection".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467#-:-MIL296a6D0_uIlvtWL8:btjxvtu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lnhsingh)

___
*[_includes/v20.2/backups/backup-options.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI15QlS8bg15as7hEjG:-MIL1dWw2d6ewImKqiWs:b-q7f9wk) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/_includes/v20.2/backups/backup-options.md#L5)):*
> ```
> Note that the job ID will not be returned when the job finishes.
> ```
I think it's that the Job completion will not be returned...? Like, success or failure? The paragraph as a whole reads weird :)

**Review by mwang1026 — APPROVED** [review]
One more TEENY TINY thing. Otherwise LGTM!

> Reviewed 4 of 7 files at r1, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467#-:-MILc4m16432YSoG4Fkf:bx3bhec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lnhsingh)

___
*[v20.2/manage-a-backup-schedule.md, line 236 at r3](https://reviewable.io/reviews/cockroachdb/docs/8467#-MILb_QLAEbgHi9fRpZ3:-MILb_QLAEbgHi9fRpZ4:b-fxjh59) ([raw file](https://github.com/cockroachdb/docs/blob/2a55085272cd2b9b91d5ade280052258a9049bf1/v20.2/manage-a-backup-schedule.md#L236)):*
> ```Markdown
> ~~~ sql
> > RESTORE
>     FROM 's3://test/backups/test_schedule_1/20200819/035600.00?AWS_ACCESS_KEY_ID=x&AWS_SECRET_ACCESS_KEY=x'
> ```

I think the example should be representative of what a Scheduled Backup's URL would look like, so 's3://test/backups/test_schedule_1/yyyy/mm/dd-time' instead

**Comment by mwang1026** [comment]
Also, thoughts on "backporting" improvements on the `start_time` and `end_time` definitions in the `SHOW BACKUP` docs? Just got some confusion on that in Slack

**Comment by mwang1026** [comment]
Screen Shot 2020-09-28 at 4 16 14 PM

in http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2a55085272cd2b9b91d5ade280052258a9049bf1/dev/manage-a-backup-schedule.html#restore-from-a-scheduled-backup

**Review by lnhsingh — COMMENTED** [review]
TFTR Michael!

@dt do you mind taking a quick pass? Related: Can you review this cockroach PR: https://github.com/cockroachdb/cockroach/pull/54760 (it hides the BACKUP INTO syntax from the SQL diagram for now)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467#-:-MILqffG1GCvDJ8qNvN5:b-atrse)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @mwang1026)

___
*[_includes/v20.2/backups/backup-options.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8467#-MI15QlS8bg15as7hEjG:-MIL4FVs2a9E7bV4CJY4:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/942f4f62449848f8567870ad3b038e517e243179/_includes/v20.2/backups/backup-options.md#L5)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> Note that the job ID will not be returned when the job finishes.
> ```
I think it's that the Job completion will not be returned...? Like, success or failure? The paragraph as a whole reads weird :)
</blockquote></details>

Fixed!
___
*[v20.2/manage-a-backup-schedule.md, line 236 at r3](https://reviewable.io/reviews/cockroachdb/docs/8467#-MILb_QLAEbgHi9fRpZ3:-MILqezg3I0QHX7APdkw:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2a55085272cd2b9b91d5ade280052258a9049bf1/v20.2/manage-a-backup-schedule.md#L236)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

I think the example should be representative of what a Scheduled Backup's URL would look like, so 's3://test/backups/test_schedule_1/yyyy/mm/dd-time' instead
</blockquote></details>

Done.

**Comment by mwang1026** [comment]
What are your thoughts on also including the `SHOW BACKUPS IN` stuff in `SHOW BACKUP` docs or their own separate doc?

**Comment by lnhsingh** [comment]
Not sure I follow. Do you mean include a `SHOW BACKUPS IN` example on the
`SHOW BACKUP` doc? There is a section already:
http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/685371fb37af7d95a0bfc576d06f207241733947/dev/show-backup.html#show-details-for-scheduled-backups

**Comment by mwang1026** [comment]
Huh weird. I must have been looking at 20.1 or something. Ignore me sorry :D

**Review by taroface — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, @mwang1026, and @taroface)

___
*[v19.2/show-backup.md, line 33 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSnjOa-yjm6zwyXijn:-MJSnjOa-yjm6zwyXijo:bwa3j6b) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v19.2/show-backup.md#L33)):*
> ```Markdown
> `database_name` | The database name.
> `table_name` | The table name.
> `start_time` | The earliest data encapsulated in the backup. For a full backup, this is `NULL`. For an incremental backup, changes that occurred between the `start_time` and `end_time` are captured.
> ```

I think this could use some clarification. It is confusing to me (not being familiar with backups) because I would expect this value to be a timestamp. This description makes it sound like backup data is being displayed?
___
*[v20.1/show-backup.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpDRt0fN9WTPsz8sK:-MJSpDRuAQoBTgNatMy3:benpsw9) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.1/show-backup.md#L41)):*
> ```Markdown
> `database_name` | The database name.
> `table_name` | The table name.
> `start_time` | The earliest data encapsulated in the backup. For a full backup, this is `NULL`. For an incremental backup, changes that occurred between the `start_time` and `end_time` are captured.
> ```

Same comment as above.
___
*[v20.2/create-schedule-for-backup.md, line 78 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpT212s1dclgDKURO:-MJSpT22084Ae32ie1Da:b-klrqjx) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/create-schedule-for-backup.md#L78)):*
> ```Markdown
> - Ensure you are monitoring your backup schedule (e.g., [Prometheus](monitor-cockroachdb-with-prometheus.html)) and alerting metrics that will confirm that your backups are completing, but also that they're not running more concurrently than you expect.
> - Ensure that your [GC window](configure-replication-zones.html#gc-ttlseconds) is long enough to accommodate your backup schedule, otherwise your incremental backups will fail. For example, if you set up your schedule to be `RECURRING '@daily'` but your GC window is less than 1 day, all your incremental backups will fail.
> - Schedules are created to maintain a particular [recovery point objective (RPO)](https://en.wikipedia.org/wiki/Disaster_recovery#Recovery_Point_Objective) (e.g., an hour); therefore, you cannot set the `AS OF SYSTEM TIME` when creating a scheduled backup. CockroachDB will set the appropriate `AS OF SYSTEM TIME` when the schedules executes to meet the specified RPO.
> ```

"when the schedule executes"
___
*[v20.2/create-schedule-for-backup.md, line 216 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpWjYE2nFQMLwtYbT:-MJSpWjYE2nFQMLwtYbU:b-uh242p) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/create-schedule-for-backup.md#L216)):*
> ```Markdown
> Because the [`FULL BACKUP` clause](#full-backup-clause) was not included, CockroachDB also scheduled a full backup to run `@daily`. This is the default cadence for incremental backups `RECURRING` <= 1 hour.
> 
> ### View scheduled backups details
> ```

Nit: "View scheduled backup details" maybe?
___
*[v20.2/create-schedule-for-backup.md, line 221 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpjDw5AlEIjQsdqQl:-MJSpjDw5AlEIjQsdqQm:b-dbog40) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/create-schedule-for-backup.md#L221)):*
> ```
> #view-a-list-of-the-full-and-incremental-backups-in-a-specifc-full-backup-subdirectory
> ```

Typo in this URL (`specifc`)
___
*[v20.2/manage-a-backup-schedule.md, line 36 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpoXOBmZXqCjppvB3:-MJSpoXOBmZXqCjppvB4:benpsw9) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/manage-a-backup-schedule.md#L36)):*
> ```Markdown
> We recommend that you monitor your backup schedule and alert on metrics that will confirm that your backups are completing, but also that they're not running more concurrently than you expect. For more information, see [Monitor CockroachDB with Prometheus](monitor-cockroachdb-with-prometheus.html).
> 
> ## View scheduled backups details
> ```

Same comment as above.
___
*[v20.2/manage-a-backup-schedule.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpqAk804Pw1MZ25RG:-MJSpqAk804Pw1MZ25RH:bomls3c) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/manage-a-backup-schedule.md#L41)):*
> ```Markdown
> 
> - `SHOW BACKUPS IN y` statement to [view a list of the full backup's subdirectories](#view-a-list-of-the-full-backups-subdirectories).
> - `SHOW BACKUP x IN y` statement to [view a list of the full and incremental backups that are stored in a specific full backup's subdirectory](#view-a-list-of-the-full-and-incremental-backups-in-a-specifc-full-backup-subdirectory).
> ```

Same comment as above (typo)
___
*[v20.2/show-backup.md, line 44 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSqNTo64E4_KKt7Mkj:-MJSqNTp9fGnRKP7ciLn:b-h1t2rz) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/show-backup.md#L44)):*
> ```Markdown
> `database_name` | The database name.
> `parent_schema_name` | <span class="version-tag">New in v20.2:</span> The name of the [parent schema]((sql-name-resolution.html#logical-schemas-and-namespaces)).
> `object_name` | The name of the [database](create-database.html), [table](create-table.html), [type](create-type.html), or schema. Note: This column used to be called `table_name` in previous versions of CockroachDB (this is a breaking change).
> ```

Suggestion: "used to be" -> "was"

Do we have a standard way of calling out breaking changes? I feel like this one could be more visible, since it's buried inside the table. Maybe bold around "Note:" or "breaking change"? Also, would this also merit a `v20.2` span?

**Review by lnhsingh — COMMENTED** [review]
TFTR! Edits made - please take a look at the wording for the `start_time` description.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467#-:-MJSzCfm86qKBATljX6V:bi753su)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, @mwang1026, and @taroface)

___
*[v19.2/show-backup.md, line 33 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSnjOa-yjm6zwyXijn:-MJSwypWA081uxCd3YHM:bemodkc) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v19.2/show-backup.md#L33)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

I think this could use some clarification. It is confusing to me (not being familiar with backups) because I would expect this value to be a timestamp. This description makes it sound like backup data is being displayed?
</blockquote></details>

Updated - PTAL
___
*[v20.2/create-schedule-for-backup.md, line 78 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpT212s1dclgDKURO:-MJSy8pu0FemQ-cl8zOf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/create-schedule-for-backup.md#L78)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

"when the schedule executes"
</blockquote></details>

Done.
___
*[v20.2/create-schedule-for-backup.md, line 216 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpWjYE2nFQMLwtYbT:-MJSyJKkDlOrZIDoLIr9:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/create-schedule-for-backup.md#L216)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: "View scheduled backup details" maybe?
</blockquote></details>

Done
___
*[v20.2/create-schedule-for-backup.md, line 221 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpjDw5AlEIjQsdqQl:-MJSyWx69USKZJiS-WIS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/create-schedule-for-backup.md#L221)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> #view-a-list-of-the-full-and-incremental-backups-in-a-specifc-full-backup-subdirectory
> ```

Typo in this URL (`specifc`)
</blockquote></details>

Done.
___
*[v20.2/manage-a-backup-schedule.md, line 36 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpoXOBmZXqCjppvB3:-MJSybKG-rzyUDk9-IWA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/manage-a-backup-schedule.md#L36)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Done.
___
*[v20.2/manage-a-backup-schedule.md, line 41 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSpqAk804Pw1MZ25RG:-MJSycE14el55SbCeadD:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/manage-a-backup-schedule.md#L41)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above (typo)
</blockquote></details>

Done.
___
*[v20.2/show-backup.md, line 44 at r5](https://reviewable.io/reviews/cockroachdb/docs/8467#-MJSqNTo64E4_KKt7Mkj:-MJSyvzw6Cljh0lWHemq:b62kbck) ([raw file](https://github.com/cockroachdb/docs/blob/a3fd7fe3db0c869f6d95fc758e282e3e8942f2f9/v20.2/show-backup.md#L44)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggestion: "used to be" -> "was"

Do we have a standard way of calling out breaking changes? I feel like this one could be more visible, since it's buried inside the table. Maybe bold around "Note:" or "breaking change"? Also, would this also merit a `v20.2` span?
</blockquote></details>

Fixed. Added the span and add the breaking change note as all bold

**Comment by lnhsingh** [comment]
@taroface (sorry for the noise with all the rebasing, etc.) - can you PTAL at updates and lmk if I should edit anything else? Thanks!

**Review by taroface — APPROVED** [review]
LGTM 👍

**Review by lnhsingh — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8467#-:-MJcpSWlBCFM6vi9zQhu:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, @mwang1026, and @taroface)

**Pull request merged**
