### PR TITLE
[DOC-9256] Update Terraform page

### PR DESCRIPTION
**Pull request by mdlinville**
[DOC-9256] Update Terraform page

- Remove machine_type field
- Change wget examples to use curl to remove a dependency

Preview: [src/current/cockroachcloud/provision-a-cluster-with-terraform.md](https://deploy-preview-18474--cockroachdb-docs.netlify.app/docs/cockroachcloud/provision-a-cluster-with-terraform.html)

### CODE REVIEW

**Comment by fantapop** [comment]
IIRC, we require a feature flag to be set to include the machine_type.  Is that right?

**Comment by fantapop** [comment]
> Change wget examples to use curl to remove a dependency

**Review by codingconcepts — APPROVED** [review]
LGTM!

**Review by rmloveland — APPROVED** [review]
LGTM

FYI this change is not in this PR:

> Change wget examples to use curl to remove a dependency

**Pull request merged**
