### PR TITLE
Draft release notes for beta-20161215

### PR DESCRIPTION
**Pull request by bdarnell**
As of cockroachdb/cockroach@5596982

@knz, were any of your join changes user-facing or is it all in preparation for distsql?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/923)

### CODE REVIEW

**Comment by knz** [comment]
The changes are preparing some optimization.

Also we discovered today that these changes introduce a (temporary) regression, for now outer joins with an ON condition may not return all expected result rows. This will be fixed in the next beta.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nvanbenschoten** [comment]
While the three bullet points on ARRAY support are all true, their inclusion as-is seems a little misleading because users cannot actually create ARRAY columns. I'd suggest we make one of the following changes:
- qualify them with text discussing the limitation and how these changes are currently only applicable to system schemas
- remove the bullets completely, since they are not very pertinent to users

That said, we've mentioned ARRAYs before in release notes (#905) and haven't heard any confusion from users, so maybe it's fine to leave them.

**Comment by jseldess** [comment]
I'm in favor of adding a qualification. I didn't understand this before; otherwise, I would've suggested qualifying earlier mentions of array functionality. 

Should we maybe group the first three bullets under a bullet like the following?

- Additional support for standard database introspection required by popular ORMs. These features apply to built-in databases only; eventually, they will be made available for user-generated databases as well.

**Comment by knz** [comment]
" These features apply to built-in ~databases~ tables only; eventually, they will be made available for user-generated ~databases~ tables as well."

**Comment by jseldess** [comment]
Thanks, @knz. @nvanbenschoten, @bdarnell, you ok with this change?

**Comment by bdarnell** [comment]
Yeah, the change is fine with me. I've been on the fence about mentioning ARRAY stuff (I think some weeks I leave it out and some weeks I include it). It's probably best not to go into too much detail until we have full support for ARRAY columns in user tables but I erred on the side of inclusion this week since it's otherwise been a little slow (a lot of work on things like distsql which aren't enabled yet)

**Comment by jseldess** [comment]
OK, I'll merge this and open a new PR to make these changes, add docs links and updates, and add other relevant updates based on additional commits included, if any.

**Pull request merged**
