### PR TITLE
Update userfile: Example with triple slash

### LINKED ISSUE #8875: userfile: Example with triple slash
We don't have any userfile examples for IMPORT with triple slash. That's how you would reference without the full db.schema.table path. This may not be obvious to users who uploaded to the default but don't actually know the default path.

suggestion is to either update this example to use triple slash, or add another example with triple slash
https://www.cockroachlabs.com/docs/v20.2/use-userfile-for-bulk-operations.html#import-from-userfile

So instead of `'userfile://defaultdb.public.userfiles_root/test-data.csv'` it's `'userfile:///test-data.csv'`

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8875

### CODE REVIEW

**Review by mwang1026 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8918)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @mwang1026)

___
*[v20.2/use-userfile-for-bulk-operations.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/8918#-MMGXj5c1CcnwRv2q4O1:-MMGXj5d5WYUq4zmsby5:bafi6f9) ([raw file](https://github.com/cockroachdb/docs/blob/bc28cf35d4ce175b1daa40eefe55ea3943b877f8/v20.2/use-userfile-for-bulk-operations.md#L72)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> `userfile:///` references the default path (`userfile://defaultdb.public.userfiles_root/`).
> ```

nit: it's only userfiles_root if the user who uploaded it was root. Maybe a placeholder like <username> where it's the username of the user who is running the command.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8918)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[v20.2/use-userfile-for-bulk-operations.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/8918#-MMGXj5c1CcnwRv2q4O1:-MMGo-8d3hqAX8e9WoB7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/bc28cf35d4ce175b1daa40eefe55ea3943b877f8/v20.2/use-userfile-for-bulk-operations.md#L72)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

nit: it's only userfiles_root if the user who uploaded it was root. Maybe a placeholder like <username> where it's the username of the user who is running the command.
</blockquote></details>

Done.

**Review by mwang1026 — APPROVED** [review]
LGTM! Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8918#-:-MMGokoJ7IxwW3XcArzw:bn0yqgx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Review by taroface — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8918#-:-MMHJBWIAG1IVDwgqwA8:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Comment by lnhsingh** [comment]
TFTRs!

**Pull request merged**
