### PR TITLE
Added crdb_branch_name to _config_base.yml

### PR DESCRIPTION
**Pull request by nickvigilante**
This will help us control the branch to use for diagrams and other
cockroach-related remote_include blocks. Instead of manually having
to update 100+ files every time a new cockroach branch is cut, this
limits the scope to changing a single file.

### CODE REVIEW

**Comment by nickvigilante** [comment]
@stbof @andf-crl Looks like the master version of show_backup references `location_opt_list` and doesn't unlink it. I'll log a new ticket for that and temporarily work around it in this PR.

**Comment by stbof** [comment]
Can you do the workaround so the build works so I can review the output?

**Review by stbof — APPROVED** [review]

**Comment by stbof** [comment]
Please update `https://cockroachlabs.atlassian.net/wiki/spaces/ED/pages/1134166645/SQL+Grammar+Documentation#Add-a-SQL-diagram-to-a-SQL-reference-page` after this is merged.

**Review by andf-crl — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
