### PR TITLE
Add release notes for v19.1.0-rc.3

### LINKED ISSUE #4661: Release notes for v19.1.0-rc.3
For https://github.com/cockroachdb/cockroach/issues/36750.

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #4661.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

**Comment by RaduBerinde** [comment]
___
*[_config_base.yml, line 46 at r1](https://reviewable.io/reviews/cockroachdb/docs/4662#-LcWTPen0BLNSc-2KFyd:-LcWTPen0BLNSc-2KFye:b-qjt57x) ([raw file](https://github.com/cockroachdb/docs/blob/61f20a5dcceaf751d090cd76e018ae2444c369e2/_config_base.yml#L46)):*
> ```YAML
>     version: v19.1.0-rc.3
>     docker_image: cockroachdb/cockroach-unstable
>     build_time: 2019/04/15 14:48:26 (go1.11.6)
> ```

Do these times show up anywhere? They are bogus, we should at least make them some round value like `12:00:00` so it's clear they're bogus.

**Comment by jseldess** [comment]
@RaduBerinde, yeah, they show up in some example outputs for `cockroach start`, for example: https://www.cockroachlabs.com/docs/dev/start-a-local-cluster.html#step-1-start-the-first-node. Happy to change to a round value if you think it's better.

**Comment by RaduBerinde** [comment]
Ideally the build time should be the value that would actually show up with that build. Unfortunately I don't know of an easy way to get it, other than downloading the binary and running start. This is what I get with `rc3`:

```
CockroachDB node starting at 2019-04-15 15:28:04.42550294 +0000 UTC (took 0.2s)
build:               CCL v19.1.0-rc.3 @ 2019/04/11 23:27:22 (go1.11.6)
webui:               http://radu-linux:8080
sql:                 postgresql://root@radu-linux:26257?sslmode=disable
client flags:        ./cockroach <client cmd> --host=radu-linux:26257 --insecure
logs:                /tmp/cockroach-v19.1.0-rc.3.linux-amd64/cockroach-data/logs
temp dir:            /tmp/cockroach-v19.1.0-rc.3.linux-amd64/cockroach-data/cockroach-temp155301491
external I/O path:   /tmp/cockroach-v19.1.0-rc.3.linux-amd64/cockroach-data/extern
store[0]:            path=/tmp/cockroach-v19.1.0-rc.3.linux-amd64/cockroach-data
status:              initialized new cluster
clusterID:           46394c87-d925-470f-83f2-d441ca769f39
```

**Pull request merged**
