### PR TITLE
Feat/kapa segment integration

### PR DESCRIPTION
**Pull request by ebembi-crdb**
Have integrated kapa and segment to send events to segment.
Currently staging segment is used in the PR, please **don't merge** before changing that
This solves - https://cockroachlabs.atlassian.net/browse/DOC-10649

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
Two things I'm noting in review.

We need to match the legal language (and links on the current production widget). So you'll need to update that parameter.
This AI bot is experimental and might provide inaccurate or incomplete answers. Always consult the official CockroachDB documentation to verify any responses provided here. Interactions with this AI bot may be monitored or recorded, and your use of the AI bot is subject to the Cockroach Labs' [Terms of Use](https://www.cockroachlabs.com/website-terms-of-use/) and [Privacy policy](https://www.cockroachlabs.com/privacy/).
We need to ensure that we're using the same design (e.g., colors) as the current widget on the docs site.

**Comment by shannonbradshaw** [comment]
Screenshot 2024-07-24 at 10 26 47 AM

Are we getting this repactcha message because we're using the kapa staging instance?

**Comment by ebembi-crdb** [comment]
> Two things I'm noting in review.
> 
> We need to match the legal language (and links on the current production widget). So you'll need to update that parameter. This AI bot is experimental and might provide inaccurate or incomplete answers. Always consult the official CockroachDB documentation to verify any responses provided here. Interactions with this AI bot may be monitored or recorded, and your use of the AI bot is subject to the Cockroach Labs' [Terms of Use](https://www.cockroachlabs.com/website-terms-of-use/) and [Privacy policy](https://www.cockroachlabs.com/privacy/). We need to ensure that we're using the same design (e.g., colors) as the current widget on the docs site.

Sure, i'll look into that and fix that.

**Comment by ebembi-crdb** [comment]
> Screenshot 2024-07-24 at 10 26 47 AM
> Are we getting this repactcha message because we're using the kapa staging instance?

Yes

**Review by shannonbradshaw — CHANGES_REQUESTED** [review]
@ebembi-crdb There are two issues we need to address. I believe they are small. Let me know when you've made the fixes.

**Comment by ebembi-crdb** [comment]
> Screenshot 2024-07-24 at 10 26 47 AM
> Are we getting this repactcha message because we're using the kapa staging instance?

As you can see here - https://docs.kapa.ai/integrations/website-widget#step-3-whitelist-recaptcha
This is already done on production site i assume earlier

**Comment by ebembi-crdb** [comment]
> > Two things I'm noting in review.
> > We need to match the legal language (and links on the current production widget). So you'll need to update that parameter. This AI bot is experimental and might provide inaccurate or incomplete answers. Always consult the official CockroachDB documentation to verify any responses provided here. Interactions with this AI bot may be monitored or recorded, and your use of the AI bot is subject to the Cockroach Labs' [Terms of Use](https://www.cockroachlabs.com/website-terms-of-use/) and [Privacy policy](https://www.cockroachlabs.com/privacy/). We need to ensure that we're using the same design (e.g., colors) as the current widget on the docs site.
> 
> Sure, i'll look into that and fix that.

Fixed this

**Review by shannonbradshaw — APPROVED** [review]
LGTM.

**Pull request merged**
