### PR TITLE
Replaced screenshot for 20.1 and 20.2

### PR DESCRIPTION
**Pull request by dgabriel123**
#7878 Replaced Network Latency page screenshot image for versions 20.1 and 20.2 (admin_ui_network_latency_collapsed_nodes.png)

### CODE REVIEW

**Comment by dgabriel123** [comment]
@cockroach-teamcity why is this check failing? I do not have login access.

**Comment by taroface** [comment]
@yingzhuchin would you be able to help diagnose this build failure? I don't understand what's in the build log, myself...

**Comment by yingzhuchin** [comment]
> @yingzhuchin would you be able to help diagnose this build failure? I don't understand what's in the build log, myself...

Hi @taroface, if you examine the full build log, you'll see at the bottom some link check errors:

```  e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/alter-table.html
11:26:12
    hash does not exist --- e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/alter-table.html --> sql-name-resolution.html#logical-schemas-and-namespaces
11:26:12
  e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/set-schema.html
11:26:12
    hash does not exist --- e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/set-schema.html --> sql-name-resolution.html#logical-schemas-and-namespaces
11:26:12
  e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/convert-to-schema.html
11:26:12
    hash does not exist --- e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/convert-to-schema.html --> sql-name-resolution.html#logical-schemas-and-namespaces
11:26:12
    hash does not exist --- e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/convert-to-schema.html --> sql-name-resolution.html#logical-schemas-and-namespaces
11:26:12
  e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/alter-database.html
11:26:12
    hash does not exist --- e40f6ab0bb00db852d818d57b48b0ea939db9eb7/v20.2/alter-database.html --> sql-name-resolution.html#logical-schemas-and-namespaces```

Hope this helps!

**Comment by taroface** [comment]
@yingzhuchin I saw these errors but didn't understand them, because this PR only adds 2 images. Maybe rebasing will help.

**Comment by yingzhuchin** [comment]
Yes, this PR needs to pull in the fix here: https://github.com/cockroachdb/docs/commit/055b0a484bbe2081d572122357e1421534a00147

**Comment by dgabriel123** [comment]
@yingzhuchin @taroface thank you!

**Comment by taroface** [comment]
@dgabriel123 So the best way to fix this is to do a [git rebase](https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master/18442755#18442755). The reason we had a conflict is because your branch was missing changes that were merged to master after you created your branch. If you don't mind, could you please revert your changes to the unrelated docs and try doing the rebase instead?

**Comment by dgabriel123** [comment]
> @dgabriel123 So the best way to fix this is to do a [git rebase](https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master/18442755#18442755). The reason we had a conflict is because your branch was missing changes that were merged to master after you created your branch. If you don't mind, could you please revert your changes to the unrelated docs and try doing the rebase instead?

I can try, but haven't my doc changes made my branch consistent with the master?

**Comment by taroface** [comment]
Yes, but manually duplicating updates is not a good practice as it creates noise in the git history.

**Comment by dgabriel123** [comment]
> Yes, but manually duplicating updates is not a good practice as it creates noise in the git history.

Roger that.

**Comment by dgabriel123** [comment]
Bothersome merge conflict

**Pull request closed without merging**
