### PR TITLE
Expand the Python example with automatic txn retries.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/152)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.py, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjWYywovgoyZtWm0mk:-KDjWYywovgoyZtWm0ml:880782566) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L33)):*
spaces here and below

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152#-:-KDjWkIwMoJzqf_IcL-2:1417088721)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/txn-sample.py, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDja1QJBfHAfdEFyw1P:-KDja1QJBfHAfdEFyw1Q:-1191526963) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L21)):*
nit: asks *for* the transaction to be retried

---

*[_includes/app/txn-sample.py, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjaFDx5ha59hiBS_Hn:-KDjaFDx5ha59hiBS_Ho:1068723661) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L35)):*
I think there's `e.pgcode`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
*[_includes/app/basic-sample.py, line 5 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjbrl10d_87xIaNxSw:-KDjbrl10d_87xIaNxSx:-1431987524) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/basic-sample.py#L5)):*
Before these samples, I'm going to have root grant privileges to a `maxroach` user, so can you change `user='root'` to `user='maxroach'`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
*[_includes/app/basic-sample.py, line 19 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjcDA9fr2HSNMIzrlt:-KDjcDA9fr2HSNMIzrlu:831546300) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/basic-sample.py#L19)):*
Super small, but can you change `Account balances` to `Initial balances`? I'm going to show printout after transaction as `Balances after transfer`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
*[_includes/app/txn-sample.py, line 5 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjcRg2MthG0JaxmfGo:-KDjcRg2MthG0JaxmfGp:-346276214) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L5)):*
Same as above: Change `root` to `maxroach`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
*[_includes/app/txn-sample.py, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjcvQPGtGP9jwp_qfa:-KDjcvQPGtGP9jwp_qfb:-868741088) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L14)):*
Do we need to show this insert? We inserted initial balances in the previous example, so we could probably just focus on the transfer here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
*[_includes/app/txn-sample.py, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjdTroEAuKoz7x95vK:-KDjdTroEAuKoz7x95vL:1510239228) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L57)):*
Can we read and print balances again here after the transfer? Like:

```
# Check balances after the transfer.
cur.execute("SELECT id, balance FROM accounts")
rows = cur.fetchall()
print('Balances after transfer:')
for row in rows:
    print([str(cell) for cell in row])
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152#-:-KDje4j7wkzd6jZbffzr:1417088721)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[_includes/app/basic-sample.py, line 5 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjbrl10d_87xIaNxSw:-KDlBJzNuDkTd9UvQoQr:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/basic-sample.py#L5)):*
Done.

---

*[_includes/app/basic-sample.py, line 19 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjcDA9fr2HSNMIzrlt:-KDlBW_707-pkV4_6ziI:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/basic-sample.py#L19)):*
Done.

---

*[_includes/app/txn-sample.py, line 5 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjcRg2MthG0JaxmfGo:-KDlBZzMp37Dhk19qpbe:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L5)):*
Done.

---

*[_includes/app/txn-sample.py, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjcvQPGtGP9jwp_qfa:-KDlBaLLkKKFOpwEo9rS:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L14)):*
Done.

---

*[_includes/app/txn-sample.py, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDja1QJBfHAfdEFyw1P:-KDlBe4fMWgxExnD4WBK:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L21)):*
Done.

---

*[_includes/app/txn-sample.py, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjWYywovgoyZtWm0mk:-KDlBhFgeIKtffSu3dlE:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L33)):*
Done.

---

*[_includes/app/txn-sample.py, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjaFDx5ha59hiBS_Hn:-KDlBpSEW_JWfIfoWVcU:1083234524) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L35)):*
I can't find it, do you have a reference?

---

*[_includes/app/txn-sample.py, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjdTroEAuKoz7x95vK:-KDlBscvve6Dpi5gpewj:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L57)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[_includes/app/txn-sample.py, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjaFDx5ha59hiBS_Hn:-KDlCyqnq9ZH6LK84Rjv:310330133) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L35)):*
http://initd.org/psycopg/docs/module.html#psycopg2.Error

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[_includes/app/txn-sample.py, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/152#-KDjaFDx5ha59hiBS_Hn:-KDlJAmNxqCjzXiupaBA:344074523) ([raw file](https://github.com/cockroachdb/docs/blob/89b9b00cbebd3a62a03d6d31222ae4f559d4ecd4/_includes/app/txn-sample.py#L35)):*
Ow indeed! See my new change: is the code always CR000?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/152)*

**Comment by jseldess** [comment]
Thanks for the updates, @knz. Merging.

**Pull request merged**
