### PR TITLE
Document BIT/VARBIT. 

### LINKED ISSUE #4070: sql: fix (really: add) the handling of bit arrays
PR: https://github.com/cockroachdb/cockroach/pull/28807

From release notes:
> CockroachDB now supports the `BIT` and `VARBIT (BIT VARYING)` bit array data types like PostgreSQL. Currently, only the bit array literal notation with a capital B (e.g., `B'10001'`) is supported; the notation with a small `b` (e.g., `b'abcd'`) continues to denote **byte** arrays as in previous versions of CockroachDB. [#28807][#28807] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by knz**
Fixes #4070.
First commit from #4452.

@rmloveland feel free to take this over.

### CODE REVIEW

**Comment by rmloveland** [comment]
Taking over - thanks Raphael!

**Comment by jseldess** [comment]
@rmloveland, please re-assign me when you're ready for review.

**Comment by rmloveland** [comment]
Thanks for the review Jesse!  I don't see any comments about the nits you found though. (Maybe I'm missing them somehow?)

**Comment by knz** [comment]
you'll need to rebase since the other pr was merged underneath

**Comment by rmloveland** [comment]
Thanks Raphael - rebased and fixed conflicts but still not seeing comments.  Oh well, gotta move on to some other higher-prio tasks.  Gonna merge since LGTM'd.

**Pull request merged**
