### PR TITLE
BACKUP / RESTORE / EXPORT are now core features + deprecate cockroach dump

### LINKED ISSUE #8088: Update Enterprise Features page - CDC / Backup / Restore
https://www.cockroachlabs.com/docs/v20.2/enterprise-licensing.html

- Backup / restore added to core
- Add clarification re: core vs. enterprise changefeeds

### LINKED ISSUE #8259: Update docs: BACKUP / RESTORE / EXPORT are core features in 20.2+
- Remove enterprise license notes
- Update Enterprise Features doc
- Remove information about `cockroach dump` as the core equivalent to backup
- Add deprecation note to `cockroach dump`

Related to #8088. cc @mwang1026

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8259:
- Removed enterprise license notes from BACKUP / RESTORE / EXPORT docs
- Removed info about cockroach dump as the core equivalent to backup
- Added a deprecation note to cockroach dump

Closes #8088:

- Updated the Enterprise Features doc for BACKUP / RESTORE / EXPORT
- Edited the CDC (now "Changefeeds to a Configurable Sink") description

### CODE REVIEW

**Comment by lnhsingh** [comment]
@dt / @mwang1026: I'm not sure how the deprecation affects the following two mentions of `cockroach dump`. Thoughts?

1. [Known Limitations](https://www.cockroachlabs.com/docs/v20.2/known-limitations#enterprise-backup-does-not-capture-database-table-column-comments):

    ```
    The COMMENT ON statement associates comments to databases, tables, or columns. However, the internal table (system.comments) in which these comments are stored is not captured by enterprise BACKUP.

    As a workaround, alongside a BACKUP, run the cockroach dump command with --dump-mode=schema for each table in the backup. This will emit COMMENT ON statements alongside CREATE statements.
    ```

    If dump is now deprecated, what is the alternative way for emitting COMMENT ON statements?

2. [Orchestrate with Mesosphere](https://www.cockroachlabs.com/docs/v20.1/orchestrate-cockroachdb-with-mesosphere-insecure.html#backup-and-restore):

    ```
    The cockroachdb DC/OS service provides an easy way use CockroachDB's cockroach dump command to back up data on a per-database basis to an S3 bucket and to restore data from such a backup. Note that using datastores other than S3 is not yet supported.

    Tip: If you need to back up to/restore from datasources other than S3, or you have a very large database and need faster backups, incremental backups, or a faster, distributed restore process, consider contacting Cockroach Labs about an enterprise license.
    ```
  
    Should this just be replaced with a full backup?

**Comment by mwang1026** [comment]
> 1. [Known Limitations](https://www.cockroachlabs.com/docs/v20.2/known-limitations#enterprise-backup-does-not-capture-database-table-column-comments):
>    ```
>    The COMMENT ON statement associates comments to databases, tables, or columns. However, the internal table (system.comments) in which these comments are stored is not captured by enterprise BACKUP.
>    
>    As a workaround, alongside a BACKUP, run the cockroach dump command with --dump-mode=schema for each table in the backup. This will emit COMMENT ON statements alongside CREATE statements.
>    ```
>    
>    
>    If dump is now deprecated, what is the alternative way for emitting COMMENT ON statements?

Cluster Backups also backup the comments table now so probably that's the best workaround in the meantime.

**Comment by mwang1026** [comment]
> 2\. [Orchestrate with Mesosphere](https://www.cockroachlabs.com/docs/v20.1/orchestrate-cockroachdb-with-mesosphere-insecure.html#backup-and-restore):
>     ```
>     The cockroachdb DC/OS service provides an easy way use CockroachDB's cockroach dump command to back up data on a per-database basis to an S3 bucket and to restore data from such a backup. Note that using datastores other than S3 is not yet supported.
>     
>     Tip: If you need to back up to/restore from datasources other than S3, or you have a very large database and need faster backups, incremental backups, or a faster, distributed restore process, consider contacting Cockroach Labs about an enterprise license.
>     ```
>     
>     
>     Should this just be replaced with a full backup?

Oof. This is above my head. Not really sure what to say here?

**Review by mwang1026 — CHANGES_REQUESTED** [review]
A few minor change requests. Otherwise looks good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8818#-:-MLJAPQrCFg7cL3uckf0:bkgt799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, and @mwang1026)

___
*[v20.2/cockroach-commands.md, line 24 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJ8ukiAZwLvqVh31Yz:-MLJ8ukiAZwLvqVh31Z-:bhc7re7) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/cockroach-commands.md#L24)):*
> ```Markdown
> [`cockroach sqlfmt`](cockroach-sqlfmt.html) | Reformat SQL queries for enhanced clarity.
> [`cockroach node`](cockroach-node.html) | List node IDs, show their status, decommission nodes for removal, or recommission nodes.
> [`cockroach dump`](cockroach-dump.html) | **Deprecated.** Take a [full backup](take-full-and-incremental-backups.html) instead.
> ```

I think maybe we make it clear that you should take a full backup instead to back up your data. To export your data in plain text format, you can use EXPORT. To view table schema in plain text, you can use `SHOW CREATE TABLE`.
___
*[v20.2/cockroach-dump.md, line 10 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJ9OlA6UKmI2DSu02t:-MLJ9OlA6UKmI2DSu02u:b69q5d4) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/cockroach-dump.md#L10)):*
> ```
> `cockroach dump` is no longer recommended and has been deprecated in v20.2. We recommend taking a [full backup](take-full-and-incremental-backups.html) instead, which no longer requires an enterprise license.
> ```

Same callout as above re: EXPORT and SHOW CREATE TABLE. Also, we plan to make a better SHOW CREATE TABLE where it dumps create statements for the whole database. Worth linking github issue here to say "we are working to make the schema export path better"?
___
*[v20.2/restore.md, line 88 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJ9sUZ9Joidyq99h3v:-MLJ9sUZ9Joidyq99h3w:bfd419c) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/restore.md#L88)):*
> ```
> on
> ```

nit: of? rather than on?
___
*[v20.2/take-full-and-incremental-backups.md, line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJABmOETIh40urtMaW:-MLJABmOETIh40urtMaX:bzrrmp) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/take-full-and-incremental-backups.md#L21)):*
> ```
> ## Watch the demo
> <iframe width="560" height="315" src="https://www.youtube.com/embed/RGuya_SYfY8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
> ```

This isn't a demo, and is 20.1 content. Can we remove? :)

**Review by lnhsingh — COMMENTED** [review]
TFTR. Updated the known limitation to add info about taking a cluster backup if you want to backup comments. I'm not sure what to do about the mention of `dump` in the Orchestration docs, but maybe @taroface will have an idea when he reviews this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8818#-:-MLKmM-v1AfvT2UPDXrc:b-us13wh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @mwang1026)

___
*[v20.2/cockroach-commands.md, line 24 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJ8ukiAZwLvqVh31Yz:-MLKj83C3ldkJhRm_aCn:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/cockroach-commands.md#L24)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

I think maybe we make it clear that you should take a full backup instead to back up your data. To export your data in plain text format, you can use EXPORT. To view table schema in plain text, you can use `SHOW CREATE TABLE`.
</blockquote></details>

Done.
___
*[v20.2/cockroach-dump.md, line 10 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJ9OlA6UKmI2DSu02t:-MLKl9WhDbvvo5Tdjjgq:b32uhov) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/cockroach-dump.md#L10)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> `cockroach dump` is no longer recommended and has been deprecated in v20.2. We recommend taking a [full backup](take-full-and-incremental-backups.html) instead, which no longer requires an enterprise license.
> ```

Same callout as above re: EXPORT and SHOW CREATE TABLE. Also, we plan to make a better SHOW CREATE TABLE where it dumps create statements for the whole database. Worth linking github issue here to say "we are working to make the schema export path better"?
</blockquote></details>

Added the info about EXPORT and SHOW CREATE. I'm going to leave the note about making SHOW CREATE TABLE better since I'm not sure we document things ahead of time (in case things change)? We can add a note later if we get a lot of questions about it
___
*[v20.2/restore.md, line 88 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJ9sUZ9Joidyq99h3v:-MLKlbgmDmAGA-CBfsvp:bxn0rbo) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/restore.md#L88)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> on
> ```

nit: of? rather than on?
</blockquote></details>

Tightened up. I think this was left over from something else.
___
*[v20.2/take-full-and-incremental-backups.md, line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLJABmOETIh40urtMaW:-MLKlkJ-C9r2Cmi6W4q6:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/8f4f92f3696d499fdc55abed500ca1eec6e1fb80/v20.2/take-full-and-incremental-backups.md#L21)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> ## Watch the demo
> <iframe width="560" height="315" src="https://www.youtube.com/embed/RGuya_SYfY8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
> ```

This isn't a demo, and is 20.1 content. Can we remove? :)
</blockquote></details>

Done.

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, @mwang1026, and @taroface)

___
*[v20.2/cockroach-commands.md, line 24 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOB9hAAKbwsv9DkotD:-MLOB9hB5Yy8k2tiBB1v:b-r2fiv2) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/cockroach-commands.md#L24)):*
> ```Markdown
> [`cockroach sqlfmt`](cockroach-sqlfmt.html) | Reformat SQL queries for enhanced clarity.
> [`cockroach node`](cockroach-node.html) | List node IDs, show their status, decommission nodes for removal, or recommission nodes.
> [`cockroach dump`](cockroach-dump.html) | **Deprecated.** Use one of the following instead:<ul><li>To back up your data, take a [full backup](take-full-and-incremental-backups.html).</li><li>To export your data in plain text format, use [`EXPORT`](export.html).</li><li>To view table schema in plain text, use [`SHOW CREATE TABLE`](show-create.html).</li></ul>
> ```

Nit: "plain text" -> "plaintext" in two places
___
*[v20.2/cockroach-dump.md, line 10 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBH8O77Js4E73NXOY:-MLOBH8O77Js4E73NXOZ:bvv0wk8) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/cockroach-dump.md#L10)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> `cockroach dump` is no longer recommended and has been deprecated in v20.2. Instead, back up your data in a [full backup](take-full-and-incremental-backups.html), [export](export.html) your data in plain text format, or view table schema in plain text with [`SHOW CREATE TABLE`](show-create.html).</li></ul>
> ```

Same nit re: "plaintext"
___
*[v20.2/take-full-and-incremental-backups.md, line 74 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBVlgEhYyioaTT973:-MLOBVlgEhYyioaTT974:b-itjra3) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/take-full-and-incremental-backups.md#L74)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> To take incremental backups, you need an [Enterprise license](enterprise-licensing.html).
> ```

nit: "Enterprise" is more often than not lowercase in our docs
___
*[v20.2/take-full-and-incremental-backups.md, line 115 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBa8W4jM0Z200jQ-z:-MLOBa8W4jM0Z200jQ0-:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/take-full-and-incremental-backups.md#L115)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> To take incremental backups, you need an [Enterprise license](enterprise-licensing.html).
> ```

Ditto
___
*[v20.2/take-full-and-incremental-backups.md, line 212 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBcI--T8zKeSmqJ5h:-MLOBcI--T8zKeSmqJ5i:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/take-full-and-incremental-backups.md#L212)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> To take incremental backups, backups with revision history, locality-aware backups, and encrypted backups, you need an [Enterprise license](enterprise-licensing.html).
> ```

Ditto

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @mwang1026, and @taroface)

___
*[v20.2/cockroach-commands.md, line 24 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOB9hAAKbwsv9DkotD:-MLOJGKRCIFasAFRkiuY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/cockroach-commands.md#L24)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: "plain text" -> "plaintext" in two places
</blockquote></details>

Done.
___
*[v20.2/cockroach-dump.md, line 10 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBH8O77Js4E73NXOY:-MLOJM3h8yaGpNS7trgY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/cockroach-dump.md#L10)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same nit re: "plaintext"
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 74 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBVlgEhYyioaTT973:-MLOJVcC0sY2vj-FOZMp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/take-full-and-incremental-backups.md#L74)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

nit: "Enterprise" is more often than not lowercase in our docs
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 115 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBa8W4jM0Z200jQ-z:-MLOJWNu-PxdzAB0_ee4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/take-full-and-incremental-backups.md#L115)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[v20.2/take-full-and-incremental-backups.md, line 212 at r4](https://reviewable.io/reviews/cockroachdb/docs/8818#-MLOBcI--T8zKeSmqJ5h:-MLOJYzTEDj0bcYu6dvC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3421806b9df98fa731dd23dfe438862e43310add/v20.2/take-full-and-incremental-backups.md#L212)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Pull request merged**
