### PR TITLE
DOC-2749 VIEWACTIVITYREDACTED with listSessions

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-2749

- Added notice that `VIEWACTIVITYREDACTED` now also redacts queries which contain constants for other users when using the `listSessions` endpoint.

Note: `alter-user.md` is missing `VIEWACTIVITYREDACTED` entry, so untouched. Investigating in separate ticket.

[alter-role.md](https://deploy-preview-13992--cockroachdb-docs.netlify.app/docs/v22.1/alter-role.html#role-options) | [create-role.md](https://deploy-preview-13992--cockroachdb-docs.netlify.app/docs/v22.1/create-role#role-options) | [create-user.md](https://deploy-preview-13992--cockroachdb-docs.netlify.app/docs/v22.1/create-user.html#role-options)

### CODE REVIEW

**Review by xinhaoz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13992)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by taroface — CHANGES_REQUESTED** [review]
A few nits, but one blocking request about the contraction: See https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#style-and-tone

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13992#-:-N3aYoUx-v_4cIUFdrLS:bnyslkk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl, @taroface, and @xinhaoz)

___
*[`v22.1/alter-role.md` line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/13992#-N3aY5qO-2TPdhhgud-U:-N3aY5qO-2TPdhhgud-V:bbbk2yx) ([raw file](https://github.com/cockroachdb/docs/blob/b944edecebbf9f61878a358ce3794decaedaffc1/v22.1/alter-role.md#L63)):*
> ```Markdown
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTING` or to access the [**Cluster Settings**](ui-debug-pages.html) page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> `VIEWACTIVITYREDACTED`/`NOVIEWACTIVITYREDACTED` | Allow or disallow a role to see other roles' queries and sessions using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the Statements and Transactions pages in the DB Console. With `VIEWACTIVITYREDACTED`, a user won't have access to the usage of statements diagnostics bundle (which can contain PII information) in the DB Console, and won't be able to list queries containing [constants](sql-constants.html) for other users when using the `listSessions` endpoint through the [Cluster API](cluster-api.html). It is possible to have both `VIEWACTIVITY` and `VIEWACTIVITYREDACTED`, and `VIEWACTIVITYREDACTED` takes precedence on restrictions. If the user has `VIEWACTIVITY` but doesn't have `VIEWACTIVITYREDACTED`, they will be able to see DB Console pages and have access to the statements diagnostics bundle. <br><br>By default, the role option is set to `NOVIEWACTIVITYREDACTED` for all non-`admin` roles.
> ```

Per our style, we should not use contractions when describing technical aspects. I know this wasn't part of your update, but since you use the same contraction to match this one, I thought I should raise this.



_Suggestion:_
```Markdown
will not
```
___
*[`v22.1/alter-role.md` line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/13992#-N3aYK9pDC6DBev0ZLbe:-N3aYK9pDC6DBev0ZLbf:undefined) ([raw file](https://github.com/cockroachdb/docs/blob/b944edecebbf9f61878a358ce3794decaedaffc1/v22.1/alter-role.md#L63)):*
> ```Markdown
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTING` or to access the [**Cluster Settings**](ui-debug-pages.html) page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> `VIEWACTIVITYREDACTED`/`NOVIEWACTIVITYREDACTED` | Allow or disallow a role to see other roles' queries and sessions using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the Statements and Transactions pages in the DB Console. With `VIEWACTIVITYREDACTED`, a user won't have access to the usage of statements diagnostics bundle (which can contain PII information) in the DB Console, and won't be able to list queries containing [constants](sql-constants.html) for other users when using the `listSessions` endpoint through the [Cluster API](cluster-api.html). It is possible to have both `VIEWACTIVITY` and `VIEWACTIVITYREDACTED`, and `VIEWACTIVITYREDACTED` takes precedence on restrictions. If the user has `VIEWACTIVITY` but doesn't have `VIEWACTIVITYREDACTED`, they will be able to see DB Console pages and have access to the statements diagnostics bundle. <br><br>By default, the role option is set to `NOVIEWACTIVITYREDACTED` for all non-`admin` roles.
> ```





_Suggestion:_
```Markdown
will not
```
___
*[`v22.1/alter-role.md` line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/13992#-N3aYNez6mwk70HFc-Vc:-N3aYNez6mwk70HFc-Vd:b-1b4jdp) ([raw file](https://github.com/cockroachdb/docs/blob/b944edecebbf9f61878a358ce3794decaedaffc1/v22.1/alter-role.md#L63)):*
> ```Markdown
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTING` or to access the [**Cluster Settings**](ui-debug-pages.html) page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> `VIEWACTIVITYREDACTED`/`NOVIEWACTIVITYREDACTED` | Allow or disallow a role to see other roles' queries and sessions using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the Statements and Transactions pages in the DB Console. With `VIEWACTIVITYREDACTED`, a user won't have access to the usage of statements diagnostics bundle (which can contain PII information) in the DB Console, and won't be able to list queries containing [constants](sql-constants.html) for other users when using the `listSessions` endpoint through the [Cluster API](cluster-api.html). It is possible to have both `VIEWACTIVITY` and `VIEWACTIVITYREDACTED`, and `VIEWACTIVITYREDACTED` takes precedence on restrictions. If the user has `VIEWACTIVITY` but doesn't have `VIEWACTIVITYREDACTED`, they will be able to see DB Console pages and have access to the statements diagnostics bundle. <br><br>By default, the role option is set to `NOVIEWACTIVITYREDACTED` for all non-`admin` roles.
> ```

Maybe cut "information" as this seems redundant with "PII".



_Code quote:_
```Markdown
PII information
```
___
*[`v22.1/alter-role.md` line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/13992#-N3aYWZG5okHsStKQxRo:-N3aYWZG5okHsStKQxRp:bg37oek) ([raw file](https://github.com/cockroachdb/docs/blob/b944edecebbf9f61878a358ce3794decaedaffc1/v22.1/alter-role.md#L63)):*
> ```Markdown
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTING` or to access the [**Cluster Settings**](ui-debug-pages.html) page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> `VIEWACTIVITYREDACTED`/`NOVIEWACTIVITYREDACTED` | Allow or disallow a role to see other roles' queries and sessions using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the Statements and Transactions pages in the DB Console. With `VIEWACTIVITYREDACTED`, a user won't have access to the usage of statements diagnostics bundle (which can contain PII information) in the DB Console, and won't be able to list queries containing [constants](sql-constants.html) for other users when using the `listSessions` endpoint through the [Cluster API](cluster-api.html). It is possible to have both `VIEWACTIVITY` and `VIEWACTIVITYREDACTED`, and `VIEWACTIVITYREDACTED` takes precedence on restrictions. If the user has `VIEWACTIVITY` but doesn't have `VIEWACTIVITYREDACTED`, they will be able to see DB Console pages and have access to the statements diagnostics bundle. <br><br>By default, the role option is set to `NOVIEWACTIVITYREDACTED` for all non-`admin` roles.
> ```

Also outside the scope of your update, but this wording seems slightly confusing to me. Do you agree? Would cutting "usage of" be clear enough and still accurate?



_Code quote:_
```Markdown
the usage of statements diagnostics bundle
```
___
*[`v22.1/create-role.md` line 79 at r1](https://reviewable.io/reviews/cockroachdb/docs/13992#-N3aYi0M4e70XKk00xlb:-N3aYi0M4e70XKk00xlc:bwmesx4) ([raw file](https://github.com/cockroachdb/docs/blob/b944edecebbf9f61878a358ce3794decaedaffc1/v22.1/create-role.md#L79)):*
> ```Markdown
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a role to see other roles' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the role's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` roles.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a role to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTING` or to access the [**Cluster Settings**](ui-debug-pages.html) page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` roles.
> `VIEWACTIVITYREDACTED`/`NOVIEWACTIVITYREDACTED` | Allow or disallow a role to see other roles' queries and sessions using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the Statements and Transactions pages in the DB Console. With `VIEWACTIVITYREDACTED`, a user won't have access to the usage of statements diagnostics bundle (which can contain PII information) in the DB Console, and won't be able to list queries containing [constants](sql-constants.html) for other users when using the `listSessions` endpoint through the [Cluster API](cluster-api.html). It is possible to have both `VIEWACTIVITY` and `VIEWACTIVITYREDACTED`, and `VIEWACTIVITYREDACTED` takes precedence on restrictions. If the user has `VIEWACTIVITY` but doesn't have `VIEWACTIVITYREDACTED`, they will be able to see DB Console pages and have access to the statements diagnostics bundle. <br><br>By default, the role option is set to `NOVIEWACTIVITYREDACTED` for all non-`admin` roles.
> ```

Same comments as above.
___
*[`v22.1/create-user.md` line 69 at r1](https://reviewable.io/reviews/cockroachdb/docs/13992#-N3aYkMX-BW1gsJmHrZT:-N3aYkMX-BW1gsJmHrZU:bwmesx4) ([raw file](https://github.com/cockroachdb/docs/blob/b944edecebbf9f61878a358ce3794decaedaffc1/v22.1/create-user.md#L69)):*
> ```Markdown
> `VIEWACTIVITY`/`NOVIEWACTIVITY` | Allow or disallow a user to see other users' [queries](show-statements.html) and [sessions](show-sessions.html) using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the [**Statements**](ui-statements-page.html) and [**Transactions**](ui-transactions-page.html) pages in the DB Console. `VIEWACTIVITY` also permits visibility of node hostnames and IP addresses in the DB Console. With `NOVIEWACTIVITY`, the `SHOW` commands show only the user's own data, and DB Console pages redact node hostnames and IP addresses.<br><br>By default, the role option is set to `NOVIEWACTIVITY` for all non-`admin` users.
> `VIEWCLUSTERSETTING` / `NOVIEWCLUSTERSETTING` | Allow or disallow a user to view the [cluster settings](cluster-settings.html) with `SHOW CLUSTER SETTING` or to access the [**Cluster Settings**](ui-debug-pages.html) page in the DB Console. <br><br>By default, the role option is set to `NOVIEWCLUSTERSETTING` for all non-`admin` users.
> `VIEWACTIVITYREDACTED`/`NOVIEWACTIVITYREDACTED` | Allow or disallow a user to see other users' queries and sessions using `SHOW STATEMENTS`, `SHOW SESSIONS`, and the Statements and Transactions pages in the DB Console. With `VIEWACTIVITYREDACTED`, a user won't have access to the usage of statements diagnostics bundle (which can contain PII information) in the DB Console, and won't be able to list queries containing [constants](sql-constants.html) for other users when using the `listSessions` endpoint through the [Cluster API](cluster-api.html). It is possible to have both `VIEWACTIVITY` and `VIEWACTIVITYREDACTED`, and `VIEWACTIVITYREDACTED` takes precedence on restrictions. If the user has `VIEWACTIVITY` but doesn't have `VIEWACTIVITYREDACTED`, they will be able to see DB Console pages and have access to the statements diagnostics bundle. <br><br>By default, the role option is set to `NOVIEWACTIVITYREDACTED` for all non-`admin` users.
> ```

Same comments as above.

**Review by andf-crl — COMMENTED** [review]
Thanks Ryan. I've made the contraction fix, but propose that I handle opportunistic edits separately: DOC-3694. Many of the comments you raise here can be found there already; great minds ;)

Since you requested changes, please kindly review once more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13992#-:-N3dptu-2GBix5Pr2uZB:b-v5w5fb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl, @taroface, and @xinhaoz)

**Review by taroface — APPROVED** [review]
LGTM!

**Pull request merged**
