### PR TITLE
[WIP] Docs informational architecture updates

### PR DESCRIPTION
**Pull request by j-low**
__[description]__
* changes to look & feel of sidebar nav
* refinements made to existing layout and styles

### CODE REVIEW

**Comment by j-low** [comment]
cc: @jseldess @lhirata @Amruta-Ranade @kuanluo @josueeee

**Comment by kuanluo** [comment]
Looks great visually! Thank you, @j-low. A few nits: 

1. Is the white scroll bar on the right side intentionally? 
image

2. The font-size for the all caps on the left side nav looks a bit too big. Let's make it 13px. 
image

3. Now that we have all caps font treatment on the left nav, let's use the same treatment for "version" in the version control label. 13px "Avenir-Heavy" instead of "Avenir Black": 
image

4. On mobile, the ">" icon looks a bit odd. I added a [new one](https://drive.google.com/open?id=1CrXT5bsbK9zZNkcyZrlTAmfSba5aKNJE) to the _Icons folder on drive.
image

**Comment by j-low** [comment]
Referencing issue filed on Hugo repo to be addressed in PR: https://github.com/cockroachlabs/hugo-website/issues/331

**Comment by jseldess** [comment]
Supplanted by https://github.com/cockroachdb/docs/pull/3133.

**Pull request closed without merging**
