### PR TITLE
Secure cloud deployments

### LINKED ISSUE #775: GCE secure deployment
How to deploy to GCE using certs.

Blocked by cockroachdb/cockroach#10120

### PR DESCRIPTION
**Pull request by sploiselle**
Includes 
- GCE secure deployment
- AWS secure deployment
- Digital Ocean secure deployment
- Updated overview 
- Change to site's information architecture to favor secure deployments

Closes #775, #776, #777

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/821)

### CODE REVIEW

**Comment by sploiselle** [comment]
From @bdarnell on #818:

>Nodes don't need (and shouldn't have) a client cert/key, just the node cert/key and CA cert.

> Call out that the ca.key should not be uploaded to every node, only ca.cert.

> After uploading the node keys, you should delete them from the machine where you generated them, so that each node key/cert pair exists only on that node.

**Comment by sploiselle** [comment]
From @jseldess: Also review [Manual Deployment: Start a Secure Cluster](manual-deployment.html#deploy-a-secure-cluster) to ensure consistency with other docs

**Comment by sploiselle** [comment]
Integrated @bdarnell's feedback except for leaving the client cert on the nodes for the sake of how the documentation is structured (running commands on nodes after SSHing into them). Filed [a follow-on issue](https://github.com/cockroachdb/docs/issues/827) to rework docs to have all commands issued from local machine to nodes without SSHing into them directly.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[deploy-cockroachdb-on-aws-insecure.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KVedHbioXE9UwHX_UGx-r1-36:-KVzTtsVHrP0DFY9qfQZ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9208f451772000bf320c83455029cf4f54ae3169/deploy-cockroachdb-on-aws-insecure.md#L36)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> oddly phrased. how about:
> 
> `All the instances on which you want to run CockroachDB etc...`
</details>
Done.

---

*[deploy-cockroachdb-on-aws-insecure.md, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KVedHbioXE9UwHX_UGx-r1-38:-KVzTuF-THU6D9GwUaB8:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9208f451772000bf320c83455029cf4f54ae3169/deploy-cockroachdb-on-aws-insecure.md#L38)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> is `(documented here)` a placeholder for future stuff? or is it supposed to be a link?
> 
> 
> 
> Also applies to the similar section in the Digital Ocean and GCE docs.
</details>
Done.

---

*[deploy-cockroachdb-on-aws.md, line 164 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KVedHbioXE9UwHX_UGy-r1-164:-KVzTvECt2ZDjjTGEZEC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9208f451772000bf320c83455029cf4f54ae3169/deploy-cockroachdb-on-aws.md#L164)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> for best practices, we should add another step:
> 
> ```
> 
> 5. Delete the node-specific certificate and key
> 
> $ rm certs/<node name>.cert certs/<node name>.key
> 
> ```
> 
> 
> 
> Same for the Digital Ocean and GCE docs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/821#-:-KVzVXJb7WtWoUt4meZL:b-daxzx0)*

**Comment by sploiselle** [comment]
@jseldess Ready for your review!

**Comment by jseldess** [comment]
Looks great, @sploiselle! Just have some minor comments and corrections. 

---

Review status: 0 of 8 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[deploy-cockroachdb-on-aws.md, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3Nqgis6l5kZl5YieX:-KW3Nqgis6l5kZl5YieY:b-34pwsf) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L38)):*
> ```Markdown
> ## Recommendations
> 
> - All of the instances which you want to run CockroachDB should be members of the same Security Group.
> ```

Like Marc mentioned above for the insecure version, this formulation would be clearer as:

All the instances on which you want to run CockroachDB...

---

*[deploy-cockroachdb-on-aws.md, line 131 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3PwAeVrbMYe0Y5J17:-KW3PwAeVrbMYe0Y5J18:b-atj3lh) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L131)):*
> ```Markdown
>    - `<node internal IP address>` which is the instance's **Internal IP**.
>    - `<node external IP address>` which is the instance's **External IP address**.
>    - `<node hostname>` which is the instance's hostname. <br/><br/>You can find this by SSHing into a server and running `hostname`. For many AWS EC2 servers, this is `ip-` followed by the internal IP address delimited by dashes; e.g., `ip-172-31-18-168`.
> ```

nit: With two breaks, the spacing is a bit much. Can you try:

- `<node hostname` which is the instance's hostname.
  You can find this by...

Basically, indent that second line so it start at the same position as the backtick on the previous line.

---

*[deploy-cockroachdb-on-aws.md, line 251 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3Rxxuuq40dXXiKIAL:-KW3Rxxuuq40dXXiKIAM:bph0vwo) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L251)):*
> ```Markdown
> 	{{site.data.alerts.callout_info}}When issuing <a href="cockroach-commands.html"><code>cockroach</code></a> commands on secure clusters, you must include flags for the <code>ca-cert</code>, as well as the client's <code>cert</code> and <code>key</code>.{{site.data.alerts.end}}
> 	~~~ sql
> 	> CREATE DATABASE insecurenodetest;
> ```

Let's change the db name to `securenodetest`.

---

*[deploy-cockroachdb-on-aws.md, line 266 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3S28ASYowc_YhZz5S:-KW3S28ASYowc_YhZz5T:bkrq1z7) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L266)):*
> ```Markdown
> 	~~~
> 
> 5.	View the cluster's databases, which will include `insecurenodetest`:
> ```

Change to `securenodetest` here, too. 

Please change in all other secure cloud deployment tutorials as well.

---

*[deploy-cockroachdb-on-aws.md, line 275 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3S8--7XP3h49v2gVP:-KW3S8--7XP3h49v2gVQ:bvprb3v) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L275)):*
> ```Markdown
> 	|     DATABASE     |
> 	+------------------+
> 	| insecurenodetest |
> ```

Change to `securenodetest` here as well.


Please change in all other secure cloud deployment tutorials as well.

---

*[deploy-cockroachdb-on-aws.md, line 286 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3SEaKdjwKaz0LGklf:-KW3SEaKdjwKaz0LGklg:b6s3al5) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L286)):*
> ```Markdown
> 
> - **Nodes** to ensure all of your nodes successfully joined the cluster
> - **Databases** to ensure `insecurenodetest` is listed
> ```

Change to `securenodetest` here, too.


Please change in all other secure cloud deployment tutorials as well.

---

*[deploy-cockroachdb-on-google-cloud-platform-insecure.md, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3SgLGn_-Cvy6cQA8R:-KW3SgLGn_-Cvy6cQA8S:bh6564u) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform-insecure.md#L52)):*
> ```Markdown
> - **8080** (`tcp:8080`) for exposing your Admin UI
> 
> Inter-node communication works by default using your GCE instances' internal IP addresses, which allow communication with other instances on CockroachDB's default port `26257`. However, to accept data from applications external to GCE and expose your admin UI you need to [create firewall rules for your project](https://cloud.google.com/compute/docs/networking).
> ```

Comma needed: "and expose your admin UI, you need to..."

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3SsvfudIK5hjrKspH:-KW3SsvfudIK5hjrKspI:bh6564u) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L54)):*
> ```Markdown
> - **8080** (`tcp:8080`) for exposing your Admin UI
> 
> Inter-node communication works by default using your GCE instances' internal IP addresses, which allow communication with other instances on CockroachDB's default port `26257`. However, to accept data from applications external to GCE and expose your admin UI you need to [create firewall rules for your project](https://cloud.google.com/compute/docs/networking).
> ```

Comma needed: "and expose your admin UI, you need to..."

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3TJqGHQh2imHJ6i1x:-KW3TJqGHQh2imHJ6i1y:bulx0uw) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L56)):*
> ```Markdown
> Inter-node communication works by default using your GCE instances' internal IP addresses, which allow communication with other instances on CockroachDB's default port `26257`. However, to accept data from applications external to GCE and expose your admin UI you need to [create firewall rules for your project](https://cloud.google.com/compute/docs/networking).
> 
> ### Guidance
> ```

This isn't new, but it just occurred to me that this heading could be more descriptive. What do you think about changing it to "Creating Firewall Rules"? 

Same would apply for the insecure tutorial.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 129 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3VnTIX6VnqHVIvwg-:-KW3VnTIX6VnqHVIvwg0:b-b70p6a) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L129)):*
> ```Markdown
>    ~~~
> 
> 3. Create a node key pair for each node issued for all common names you might use to refer to the node, including:
> ```

nit: Would read better as: "For each node, create a node key pair issue for..."

Same for all other tutorials.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 133 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3Un3KWZi7Vk9MQyA2:-KW3Un3LfK0vQ72BJmjC:by3q5z1) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L133)):*
> ```Markdown
>    - `<node internal IP address>` which is the instance's **Internal IP**.
>    - `<node external IP address>` which is the instance's **External IP address**.
>    - `<node hostname>` which is the instance's **Name**.
> ```

What about adding the tip you have in the aws tutorial for sshing into the node to get the node's hostname?

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3ZCRjDShQc1DxVAG5:-KW3ZCRjDShQc1DxVAG6:b-hiktpq) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L188)):*
> ```Markdown
> 	~~~
> 
> 3. 	Start a new CockroachDB cluster with a single node:
> ```

Since `--advertise-host` is appear here for the first time, I wonder whether it might be helpful to expand the intro text to something like:

Start a new CockroachDB cluster with a single node, specifying the location of certificates and the address at which other nodes can reach it.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 228 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3_68UUEGJoh7KOlFh:-KW3_68VZTFFhe-NWZbD:brhqf1b) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L228)):*
> ```Markdown
> 	--cert=certs/<node name>.cert \
> 	--key=certs/<node name>.key \
> 	--ca-cert=certs/ca.cert \
> ```

Maybe list `--ca-cert` first, for consistency with step 4.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3aSyJ4oXuk8_d24Am:-KW3aSyJ4oXuk8_d24An:b-shu2mc) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L237)):*
> ```Markdown
> ## Step 6. Test Your Cluster
> 
> To test your distributed, multi-node cluster, access SQL and create a new database. That database will then be accessible from all of the nodes in your cluster.
> ```

"access SQL" sounds a bit strange to me. Maybe something like "access the built-in SQL client"?

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 242 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3ahgdjO-9mtpLXbYZ:-KW3ahgdjO-9mtpLXbY_:boebd55) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L242)):*
> ```Markdown
> 
> 	~~~ shell
> 	$ ssh <username>@<node2 external IP address>
> ```

Since we're saying to SSH to the first node, we should change `node2` to `node`.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 282 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3br0VURiYLcHnQ7Jt:-KW3br0WL-LeEuc6i-R9:b-4cg6ai) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L282)):*
> ```Markdown
> ## Step 7. View the Admin UI
> 
> View your cluster's Admin UI by going to `http://<any node's external IP address>:8080`. 
> ```

Address should be `https`.

Also, we might want to add a note similar to what we have in the secure a local cluster doc:

Note that your browser will consider the CockroachDB-created certificate invalid; you’ll need to click through a warning message to get to the UI.

---

*[manual-deployment.md, line 251 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3fMIWE9QcSqrr8teH:-KW3fMIWE9QcSqrr8teI:ba0zxn9) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/manual-deployment.md#L251)):*
> ```Markdown
> CockroachDB Admin UI
> 
> {{site.data.alerts.callout_info}}If your network setting preclude allowing traffic in on port <code>8080</code>, you can instead you can use SSH to tunnel from a local machine to a node.{{site.data.alerts.end}}
> ```

Delete second "you can".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/821#-:-KW3h18nODebBouEKJrP:b67mff0)*

**Comment by sploiselle** [comment]
Review status: 0 of 8 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[deploy-cockroachdb-on-aws.md, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3Nqgis6l5kZl5YieX:-KW3zVLBAPGvenReXSjW:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L38)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Like Marc mentioned above for the insecure version, this formulation would be clearer as:
> 
> All the instances on which you want to run CockroachDB...
</details>
Done.

---

*[deploy-cockroachdb-on-aws.md, line 131 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3PwAeVrbMYe0Y5J17:-KW3zW4VpEzdrUJG6Chg:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L131)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> nit: With two breaks, the spacing is a bit much. Can you try:
> 
> - `<node hostname` which is the instance's hostname.
>   You can find this by...
> 
> Basically, indent that second line so it start at the same position as the backtick on the previous line.
</details>
Done.

---

*[deploy-cockroachdb-on-aws.md, line 251 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3Rxxuuq40dXXiKIAL:-KW3tnZ2m1zt04sYFV7z:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L251)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Let's change the db name to `securenodetest`.
</details>
Done.

---

*[deploy-cockroachdb-on-aws.md, line 266 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3S28ASYowc_YhZz5S:-KW3to8ywcougN8IzhK4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L266)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Change to `securenodetest` here, too. 
> 
> Please change in all other secure cloud deployment tutorials as well.
</details>
Done.

---

*[deploy-cockroachdb-on-aws.md, line 275 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3S8--7XP3h49v2gVP:-KW3tol21Vm95JovTDWC:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L275)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Change to `securenodetest` here as well.
> 
> 
> Please change in all other secure cloud deployment tutorials as well.
</details>
Done.

---

*[deploy-cockroachdb-on-aws.md, line 286 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3SEaKdjwKaz0LGklf:-KW3tpHlSUwRyUdTQYLM:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-aws.md#L286)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Change to `securenodetest` here, too.
> 
> 
> Please change in all other secure cloud deployment tutorials as well.
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform-insecure.md, line 52 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3SgLGn_-Cvy6cQA8R:-KW3txlaNkvKl18nVCX4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform-insecure.md#L52)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Comma needed: "and expose your admin UI, you need to..."
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3SsvfudIK5hjrKspH:-KW3u4Ads6vLPPgSGFsO:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L54)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Comma needed: "and expose your admin UI, you need to..."
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3TJqGHQh2imHJ6i1x:-KW3uHua7q5sPVfqhU1q:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L56)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> This isn't new, but it just occurred to me that this heading could be more descriptive. What do you think about changing it to "Creating Firewall Rules"? 
> 
> Same would apply for the insecure tutorial.
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 129 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3VnTIX6VnqHVIvwg-:-KW3uZai95Y8Ge1iPY7Z:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L129)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> nit: Would read better as: "For each node, create a node key pair issue for..."
> 
> Same for all other tutorials.
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 133 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3Un3KWZi7Vk9MQyA2:-KW3u_iNN6HyRrvMRGUh:bh3tdxp) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L133)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> What about adding the tip you have in the aws tutorial for sshing into the node to get the node's hostname?
</details>
For AWS, the only way to get the hostname is to run the command, or do the inference I listed. On the other platforms, the hostname is always just the name that displays in the UI.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 188 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3ZCRjDShQc1DxVAG5:-KW3xgoIsYKOqmQgiQW0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L188)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Since `--advertise-host` is appear here for the first time, I wonder whether it might be helpful to expand the intro text to something like:
> 
> Start a new CockroachDB cluster with a single node, specifying the location of certificates and the address at which other nodes can reach it.
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 228 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3_68UUEGJoh7KOlFh:-KW3xhJI4dl40pixM0d2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L228)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Maybe list `--ca-cert` first, for consistency with step 4.
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3aSyJ4oXuk8_d24Am:-KW3yYMK692RD2vINBtp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L237)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> "access SQL" sounds a bit strange to me. Maybe something like "access the built-in SQL client"?
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 242 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3ahgdjO-9mtpLXbYZ:-KW3ymmpRPcPEdXfRSTx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L242)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Since we're saying to SSH to the first node, we should change `node2` to `node`.
</details>
Done.

---

*[deploy-cockroachdb-on-google-cloud-platform.md, line 282 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3br0VURiYLcHnQ7Jt:-KW3zDQBJP6wpROBhT6V:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/deploy-cockroachdb-on-google-cloud-platform.md#L282)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Address should be `https`.
> 
> Also, we might want to add a note similar to what we have in the secure a local cluster doc:
> 
> Note that your browser will consider the CockroachDB-created certificate invalid; you’ll need to click through a warning message to get to the UI.
</details>
Done.

---

*[manual-deployment.md, line 251 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/821#-KW3fMIWE9QcSqrr8teH:-KW3zTSVJd75HCYKOyFg:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/43d971b579d09ccdf9977f912a77c1f720f7e2ed/manual-deployment.md#L251)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Delete second "you can".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/821)*

**Comment by jseldess** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/821#-:-KW46LPQeEgBAHIlPcS0:bnfp4nl)*

**Pull request merged**
