### PR TITLE
Move sidebar JS later in the page to avoid blocking rendering

### PR DESCRIPTION
**Pull request by shermanCRL**
Make scripts defer and async where appropriate. Tweak version menu to avoid layout shift.

Motivated by Lighthouse recommendation.

Addresses https://github.com/cockroachdb/docs/issues/10697

### CODE REVIEW

**Comment by jseldess** [comment]
Thank you very much for these improvements, @shermanCRL! 

I know @anagio is working on docs site improvements, so I'd like to have him review this.

**Review by anagio — APPROVED** [review]
lgtm

**Comment by shermanCRL** [comment]
Would y’all click around on [the preview](https://deploy-preview-10733--cockroachdb-docs.netlify.app/docs/) to make sure I didn’t break some existing behavior?

**Comment by jseldess** [comment]
@shermanCRL. Just clicked around, and I don't see anything funny. LGTM. Want me to merge?

**Review by jseldess — APPROVED** [review]

**Comment by shermanCRL** [comment]
@jseldess Thanks, will merge now.

**Pull request merged**
