### PR TITLE
CC IP Allowlist limitation

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/CC-4588
You can add up to 24 ip addresses via the allowlist. Use VPC peering or PrivateLink if you need to add more.

### CODE REVIEW

**Comment by gemma-shay** [comment]
cc: @kannanlakshmi @logston Let me know if you'd rather the limit be documented as 20.

**Comment by kannanlakshmi** [comment]
I am fine with 24 as that's the real limit, is there a reason you suggest 20?

**Comment by gemma-shay** [comment]
@kannanlakshmi 20 was suggested in the comments here: https://cockroachlabs.atlassian.net/browse/SREOPS-2350

**Comment by kannanlakshmi** [comment]
Got it, then 20 is fine. LGTM

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
