### PR TITLE
Misc CSS improvements

### LINKED ISSUE #525: Change double-click select highlighting behavior to only highlight commands
Throughout the docs page, there are convenient code snippets that appear in gray boxes such as:

image

Unfortunately, when you attempt to highlight by double clicking the command, the bash symbol $ gets highlighted as well. This forces the user to manually highlight the command if they want to copy and paste it directly into terminal, costing them a bit of time. It would be nice if when you double clicked anywhere in the command, it only copied the command as you'd want to paste it into your terminal. Also, ideally a series of commands could be copied with newlines separating them so that you can paste it into your terminal and have them be run in sequence. There may be better solutions, but a google search came up with:

https://css-tricks.com/almanac/properties/u/user-select/

IMO this is low priority, and not something where time should be wasted trying to get it working for out of date, unpopular browsers.

### LINKED ISSUE #575: Clickable hyperlink area on major headings is too large
On a bunch of our docs pages, the clickable link on a major heading within the page expands pretty far above the actual text of the heading. Normally this isn't a big deal, but on some pages that clickable area goes over top of the scroll bar of a code sample, making it very hard to scroll sideways within the code sample with a mouse.

For example, on https://www.cockroachlabs.com/docs/view-node-details.html#see-also, see this quick video of how my cursor stays focused on the link even while hovering over the scroll bar: https://goo.gl/photos/r8echbKwJPVkHjNC6

@jseldess

### PR DESCRIPTION
**Pull request by sploiselle**
- When using syntax highlighting, made terminal identifier (e.g. "$" for shell) unselectable (#525)
- Fixed bug with over-large area for anchors (#575)
- Included background color for all bs-callout styles (same for all callouts); color choice driven by need to accommodate green link text and medium-gray code formatting

### Related issues
Fixes #525
Fixes #575

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/585)

### CODE REVIEW

**Comment by sploiselle** [comment]
@jseldess Can I get some guidance on how to generate new CSS files from `scss` files? Seems like there's a single command that aggregates all changes into `customstyles.css` but can't deduce what it is.

**Comment by sploiselle** [comment]
Figured out how CSS works on the site, which I [documented in the Wiki](https://github.com/cockroachdb/docs/wiki/CSS-Changes).

## Details

### Unselectable Shell Marker

- [**Demo**](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e2bea12df0921a12d0a201e9276ec2d488577d35/secure-a-cluster.html)
- **Details**: This inordinately complex because of the `user-select:none`'s imperfect implementation. You can see one of the problems [here](https://css-tricks.com/almanac/properties/u/user-select) that shows you can "accidentally" select text that has been marked as `user-select:none` if you select the elements around it. This happens often in the doc site because we include series of commands in the same code box.<br/><br/>To resolve the issue, I have JavaScript actually remove all of the `$`s from the page (they're marked with `class="gp"` and then apply another class to them that puts the `$` back on the page using CSS's `::before` pseudo-class, which causes the text to display but doesn't actually render in the on-page HTML. In conjunction with the `user-select:none` style originally set on `class=gp`, this makes the `$` totally unselectable.<br/><br/>This implementation is the least obtrusive and most performant of everything I tried. It's kludgy on the back-end, but seamless for the user and the writer.

### Over-Large Area for Anchors
- [**Demo**](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e2bea12df0921a12d0a201e9276ec2d488577d35/indexes.html)
- **Details**: This was caused by using `h1[id]::before`. I found another site that used `anchor.js` that didn't have the issue and copied their CSS declaration (`h1:target:before`) and it fixed the issue.
- **Gotcha**: The way `anchor.js` handles anchor mapping has an odd behavior where the vertical size of the target defaults to 621 pixels if the same anchor is present in many documents. You can see this with the [See Also](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e2bea12df0921a12d0a201e9276ec2d488577d35/indexes.html#see-also) header.<br/><br/>I first noticed it with **What's Next?** which was repeated a number of times in `install-cockroachdb.md`. After removing the duplicate instances, the issue righted itself somewhat, so I included it in the PR.

### Background color for bs-callout
- [**Demo**](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e2bea12df0921a12d0a201e9276ec2d488577d35/create-index.html)
- **Details**: Toyed around with a few different designs and my favorite was to just add the same color background to all bs-callouts. The only other viable alternative was to add a border around the boxes, but it looked off to me. I think the color might be improved, which I'll follow up with Kuan on.

**Comment by jseldess** [comment]
:lgtm:, Sean, once you've worked out the design for callouts with Kuan and updated the SQL samples as discussed offline. Thanks!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/585#-:-KQLzkhZQoPxcLFOcHPM:bgiwd8q)*

**Comment by sploiselle** [comment]
@jseldess Can I get you to take a gander at `CONTRIBUTING.md` before I merge? Not my finest writing but tried to make it succinct.

---

Review status: 1 of 47 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/585#-:-KQNFWRx9LtOjZ_HOcit:bfi065g)*

**Comment by eballeste** [comment]
Hi @sploiselle, @jseldess ! Just chiming in a little here concerning the sass files in case you want to include more details in the wiki:

Originally all styles were included in customstyles.css. For sake of sanity and maintenance ease, I created a sass version of this file and started to break apart all of the docs components into modular, easy to recognize files. 

Ideally, it would be great to limit the use of customstyles.scss exclusively as a loader for all of the different components, with absolutely no css in the file. The css should be included in the different components and are named with a leading underscore. This naming convention lets the sass compiler know that the component is included somewhere else and it shouldn't generate it's own file.

An example of it's current structure with some of the components: 
- **css**
  - customstyles.css
  - customstyles.scss
  - **components**
    - _toc.scss 
    - _search.scss
    - _filtertabs.scss
  - **layouts**
    - _footer.scss
    - _header.scss
    - _sidebar.scss

**Comment by jseldess** [comment]
`CONTRIBUTING.md` looks great. @sploiselle. Thanks. 

And thanks for the scss tips, @eballeste. Given the guidance that we should put css in components, @sploiselle, I wonder if it would make sense to create a new component for the code selection styling you've introduced? Or would that fit well in an existing component? 

@eballeste, based on what I've read [here](https://jekyllrb.com/docs/assets/) and [here](http://markdotto.com/2014/09/25/sass-and-jekyll/), it should be possible to have the css files regenerated from the scss on `jekyll serve` rather than having to run the sass command extra, as Sean documented on the [wiki](https://github.com/cockroachdb/docs/wiki/CSS-Changes). Is there a reason not to change things around so that Jekyll can take care of that for us?

---

Review status: 1 of 47 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/585#-:-KQO7MVjO_YukMXhTp0k:b-mrsmej)*

**Comment by eballeste** [comment]
@jseldess I don't see any reason no to skip the extra step and let jekyll take care of compiling all the sass files. I glanced over the links you provided and my only concern is whether it recognizes the partial files can be organized within subfolders like in it's current implementation. I'm guessing it should work but wouldn't know without testing it.

**Comment by sploiselle** [comment]
@eballeste Thanks for taking the time to look this over.

@jseldess Moved the code sample CSS into its `css/components/_codesamples` and imported that into `css/customstyles.scss`. 
Best tests are:
- [SQL statements](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02fcb5f9e99fe0f6e45c27fc8dc771eef402eba9/learn-cockroachdb-sql.html)
- [Shell statements](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02fcb5f9e99fe0f6e45c27fc8dc771eef402eba9/start-a-local-cluster.html#step-6--stop-the-cluster)
- [`bs-callout` style](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/02fcb5f9e99fe0f6e45c27fc8dc771eef402eba9/create-index.html)
- All pages still show improvement for over-large anchor area

**Comment by jseldess** [comment]
LGTM. Go ahead and merge, @sploiselle.  

I'll create a separate issue to get jekyll to compile the sass files.

**Pull request merged**
