### PR TITLE
Update java "build an app" tutorial

### PR DESCRIPTION
**Pull request by jseldess**
This PR updates the java "build an app" tutorial to cover both the jdbc driver and the Hibernate ORM.

@jordanlewis, @cuongdo, not sure if the "Run the Java code" step is as clear as it should be. Please don't hold back.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1100)

### CODE REVIEW

**Comment by cuongdo** [comment]
Also, in the language/driver/ORM matrix, it still says "Hibernate support coming soon"

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[build-a-java-app-with-cockroachdb.md, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-KcyZ4b9XE7L8uD7Y0WM:-KcyZ4b9XE7L8uD7Y0WN:b-h698rk) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L43)):*
> ```Markdown
> 
> ~~~ shell
> $ brew install gradle
> ```

This is macOS-specific. On Ubuntu Linux, it'd be `apt-get install gradle` 

---

*[build-a-java-app-with-cockroachdb.md, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_zxQpR2BX_9b8wfi:-Kcy_HiDNuVguqiM8RUz:b-rxliyt) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L105)):*
> ```Markdown
> `build.gradle` | This is the file you will run to execute your app. 
> 
> For more insight into this sample application, review the `Sample.java` file, which uses the [Hibernate ORM](http://hibernate.org/orm/) to map Java-specific objects to SQL operations. Specifically, `public Account() {}` creates an `accounts` table based on the Account class, `session.save(new Account())` inserts rows into the table, and `session.getCriteriaBuilder().createQuery(Account.class)` selects from the table so that balances can be printed. 
> ```

The part about `public Account(){}` isn't right. @jordanlewis can help with wording this

---

*[build-a-java-app-with-cockroachdb.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_0kXbBGcYL6jf5wR:-Kcy_0kXbBGcYL6jf5wS:b-d098a6) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L108)):*
> ```Markdown
> 
> ~~~ java
> {% include app/hibernate-basic-sample/Sample.java %}
> ```

This code block should have some heading to identify it, like the filename (`Sample.java`)

---

*[build-a-java-app-with-cockroachdb.md, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_STzII_JC9g-1iPq:-Kcy_STzII_JC9g-1iPr:bancp5h) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L117)):*
> ```Markdown
> ~~~
> 
> Toward the end of the output, you shoud see:
> ```

s/shoud/should/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-:-KcyYagaxYfTqCspjy25:b-mgclaf)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[build-a-java-app-with-cockroachdb.md, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_zxQpR2BX_9b8wfi:-KcybiS5u85qVTfmUbzO:bsnwl8d) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L105)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

The part about `public Account(){}` isn't right. @jordanlewis can help with wording this
</blockquote></details>

Cuong is correct, this isn't quite right. You can say something like "The Account class defines a model representing an account.". The part that instructs Hibernate to turn the model into a table is actually in the top of the file, where it says `.addAnnotatedClass(Account.class)`, but I wouldn't really write a sentence explaining where the `accounts` table is created - that's all done behind the scenes. We can talk offline if you need more clarity here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1100)*

**Comment by jseldess** [comment]
Updated that matrix, @cuongdo. Thanks.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[build-a-java-app-with-cockroachdb.md, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-KcyZ4b9XE7L8uD7Y0WM:-Kd1MQ_SZWuZHq643U8r:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L43)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

This is macOS-specific. On Ubuntu Linux, it'd be `apt-get install gradle` 
</blockquote></details>

Done.

---

*[build-a-java-app-with-cockroachdb.md, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_zxQpR2BX_9b8wfi:-Kd1UnTDostB7MvQYtcS:b-z9i59d) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L105)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Cuong is correct, this isn't quite right. You can say something like "The Account class defines a model representing an account.". The part that instructs Hibernate to turn the model into a table is actually in the top of the file, where it says `.addAnnotatedClass(Account.class)`, but I wouldn't really write a sentence explaining where the `accounts` table is created - that's all done behind the scenes. We can talk offline if you need more clarity here.
</blockquote></details>

Reworked with Jordan's help.

---

*[build-a-java-app-with-cockroachdb.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_0kXbBGcYL6jf5wR:-Kd1Ur2eUjevt1k26B-J:b1oi1an) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L108)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

This code block should have some heading to identify it, like the filename (`Sample.java`)
</blockquote></details>

I need to research how to do this. Might have to do it after merging. 

---

*[build-a-java-app-with-cockroachdb.md, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-Kcy_STzII_JC9g-1iPq:-Kd1OQPj6qHEXlYWzqA_:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5cbdd0d9f99c336e8c622c5d38bbe9b2e8319ce7/build-a-java-app-with-cockroachdb.md#L117)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

s/shoud/should/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-:-Kd1MKrS4GLBb8A9dpuK:b-kb5a8i)*

**Comment by jordanlewis** [comment]
:lgtm:!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1100#-:-Kd1g-lGNuR7WJxkJRK6:bg7igkw)*

**Pull request merged**
