### PR TITLE
Update training for exposure on site

### PR DESCRIPTION
**Pull request by jseldess**
- Show only relevant modules in sidenav
- Update training homepage
- Add v2.0 pages

### CODE REVIEW

**Comment by kuanluo** [comment]
Thanks, @jseldess ! Dropdown LGTM, we will drop the "events" from "Resources" very soon, so that will make the dropdown feels less crowded. 

- We talked about how the training nav on mobile isn't exposed properly. Are we going to try to fix that? 
- On the new training home, given the proximity of the Tips box to the feedback box, and the length of text on the page. I suggest to remove the styling for "tips" and make the copy standard body style instead. The appearance and the position of the Tips feel a bit jarring. 

image

**Comment by j-low** [comment]
@jseldess per @kuanluo we're removing `Events` from the header under `Resources` too in [the hugo-website PR](https://github.com/cockroachlabs/hugo-website/pull/398)  Would you be able to remove that on this PR?

**Comment by jseldess** [comment]
Please take another look, @kuanluo.

@j-low, I don't know how to fix the mobile nav problem @kuanluo has identified. When you're on the training home page on mobile, the docs menu doesn't show any of the other training sections. Would be great to get your help with that.

**Comment by kuanluo** [comment]
LGTM. Thank you, @jseldess !

**Comment by jess-edwards** [comment]
@jseldess LGTM. This is awesome.

If you can get swap the survey from google forms --> survey monkey, it'll be a better phase 0 experience. Survey Monkey integrates with HubSpot. An extra 30 minutes effort here to save us hours in April. Then we can deal with HubSpot forms in Phase 1.

**Comment by jseldess** [comment]
Done. Thanks, @jess-edwards.

**Pull request merged**
