### PR TITLE
CLI import command

### PR DESCRIPTION
**Pull request by gemma-shay**
-Add new `cockroach import` statement to cockroach commands page
-Create new `cockroach import` page
-Add callout to `cockroach userfile upload` page suggesting when to use `cockroach import` instead

Closes: #9139

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
Good first pass! Left a couple of comments 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9788#-:-MTcT-2w2Z5Q2yiHitJC:be433vt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @gemma-shay)

___
*[v21.1/cockroach-import.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcP9sBEe56PEWZ2T89:-MTcP9sBEe56PEWZ2T8A:b-d2vwe6) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L9)):*
> ```Markdown
> <span class="version-tag">New in v21.1:</span> The `cockroach import` [command](cockroach-commands.html) imports a database or table from a local dump file into a running cluster. `PGDUMP` and `MYSQLDUMP` file formats are currently supported.
> 
> Behind the scenes, this command [uploads a userfile](cockroach-userfile-upload.html), imports its data, then [deletes the userfile](cockroach-userfile-delete.html).
> ```

Cut "behind the scenes", as this is an idiom. I would also move this to be after the first sentence of the doc.
___
*[v21.1/cockroach-import.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcQ6x05C8OYn3MCZox:-MTcQ6x05C8OYn3MCZoy:b-3y6b98) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L12)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> We recommend using `cockroach import` for quick imports from your client (about 15MB or smaller). For larger imports, you can use a SQL [IMPORT](import.html) statement.
> ```

Suggested wording: "For larger imports, use the IMPORT statement."
___
*[v21.1/cockroach-import.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcQVm3-Sm1UvSlNTKC:-MTcQVm3-Sm1UvSlNTKD:bkmpbty) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L24)):*
> ```Markdown
> 
> ~~~ shell
> $ cockroach import db <format> <location/of/file> [flags]
> ```

Maybe the synopsis should be one for pgdump and one for mysql since the format can only be one or the other? Like:

````
Import a database from a PGDUMP file:
~~~shell
cockroach import db pgdump ....
~~~
```

 Otherwise, I'd suggest adding a description under each that describes what the placeholders should be replaced with
___
*[v21.1/cockroach-import.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcSjnk9_5lI_rojTnA:-MTcSjnl5UhGrZV671Q7:b-b658g1) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L30)):*
> ```Markdown
> 
> ~~~ shell
> $ cockroach import table <table_name> <format> <location/of/file> [flags]
> ```

Same comment as above applies here
___
*[v21.1/cockroach-userfile-upload.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcFIIL37ddVirG9biV:-MTcFIIL37ddVirG9biW:b-o900p3) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-userfile-upload.md#L15)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> {{site.data.alerts.callout_info}}
> ```

I think we have a callout that shows `Tip:` that would be good to use here. I think it's `callout_success`


<!-- Sent from Reviewable.io -->

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9788)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @lnhsingh)

___
*[v21.1/cockroach-import.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcP9sBEe56PEWZ2T89:-MTgh0ij4dKllV-xhNBS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L9)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Cut "behind the scenes", as this is an idiom. I would also move this to be after the first sentence of the doc.
</blockquote></details>

Done.
___
*[v21.1/cockroach-import.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcQ6x05C8OYn3MCZox:-MTgh0K_6-5KlqvcaAmB:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L12)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggested wording: "For larger imports, use the IMPORT statement."
</blockquote></details>

Done.
___
*[v21.1/cockroach-import.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcQVm3-Sm1UvSlNTKC:-MTgh-Ji--4--RUFVSGo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L24)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Maybe the synopsis should be one for pgdump and one for mysql since the format can only be one or the other? Like:

````
Import a database from a PGDUMP file:
~~~shell
cockroach import db pgdump ....
~~~
```

 Otherwise, I'd suggest adding a description under each that describes what the placeholders should be replaced with
</blockquote></details>

Done.
___
*[v21.1/cockroach-import.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcSjnk9_5lI_rojTnA:-MTgh-kT3H8_e4nCjSnl:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-import.md#L30)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Same comment as above applies here
</blockquote></details>

Done.
___
*[v21.1/cockroach-userfile-upload.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTcFIIL37ddVirG9biV:-MTgh2YP4qu1E8Ki8wD1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2c26d8e311335a643a692f3018c3f9d02d489b34/v21.1/cockroach-userfile-upload.md#L15)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think we have a callout that shows `Tip:` that would be good to use here. I think it's `callout_success`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Comment by lnhsingh** [comment]
@adityamaru, friendly reminder to review- thanks!

**Review by adityamaru — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9788)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[v21.1/cockroach-import.md, line 15 at r2](https://reviewable.io/reviews/cockroachdb/docs/9788#-MTwApiVEyjB-xe8WhZs:-MTwApiVEyjB-xe8WhZt:bmwgzxh) ([raw file](https://github.com/cockroachdb/docs/blob/45f702ea1f5919c699174994f4c7b4ce744459be/v21.1/cockroach-import.md#L15)):*
> ```Markdown
> ## Required privileges
> 
> Only members of the `admin` role can run `cockroach import`. By default, the `root` user belongs to the `admin` role.
> ```

The privileges required to run this command are the same as in IMPORT. i.e. CREATE on the database being imported into. A non-admin user can run this command using the --user= flag.

**Comment by adityamaru** [comment]
Apologies! Dropped the ball on this. FYI we just realized that we might need to add a couple of extra CLI flags to tie this feature in with work we have done on the underlying `IMPORT PGDUMP`. This might be added early next week so I can create a docs issue once that is merged in.

**Pull request merged**
