### PR TITLE
Add vetted docs re: how to do data domiciling

### LINKED ISSUE #10553: Add specific, vetted documentation about handling compliance, etc. in multi-region databases
Follow-on to cockroachdb/docs#10554

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #10553

### CODE REVIEW

**Comment by rmloveland** [comment]
hey @taroface!  FYI this has had some pretty heavy internal review re: the technical and legal claims w.r.t domiciling so if I am worried about changing any specific thing based on your suggestions that is why.  also happy to chat offline if that is easier

**Comment by rmloveland** [comment]
PS the above is not me saying "please just rubber stamp this with no feedback", sorry if it came off that way.  happy to update to make it clearer etc, just saying it will need more care than usual for reasons mentioned above

**Comment by rmloveland** [comment]
Hey @taroface just wanted to check in on this one!  I realize it's kinda big.  Do you think maybe next week?  It's not really a rush,  but I wondered if it fell through the cracks since that happens to me as a reviewer sometimes!

**Comment by taroface** [comment]
Sorry @rmloveland, this totally passed me by somehow. I will take a loop ASAP.

**Review by taroface — APPROVED** [review]
LGTM, such a crystal-clear document! I just have a few suggestions and nits. Sorry again that I missed this review earlier.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11019#-:-Mgw8P15DhiHS5rVbWli:b-5j296l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/data-domiciling.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-MgvxhwS4i6sQzpRfPpT:-MgvxhwS4i6sQzpRfPpU:becxgvc) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L19)):*
> ```
> Data which
> ```

I think this should be "Data that"
___
*[v21.1/data-domiciling.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw4pgkCs01cT6KJr8R:-Mgw4pgkCs01cT6KJr8S:bjq93or) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L21)):*
> ```
> you can associate that database with only those regions
> ```

Is it worth adding a pointer here to how exactly this is done, if there is one obvious way? Or is this done in various ways? (Sorry that I'm still catching up on this side of the product.)

Also, perhaps it would be good to be explicit at this point that we're talking about "allowed localities" and that "regions" are one level of locality (if I understand correctly).
___
*[v21.1/data-domiciling.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw5qZX6NNWyMs3B7LO:-Mgw5qZX6NNWyMs3B7LP:bzpyyv) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L24)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> As of CockroachDB v21.1 and earlier, some metadata about the user data may be stored in system ranges, system tables, etc. This might result in potential "leakage" outside of the desired domicile if your schema includes table names, etc., that may reveal information about their contents (e.g., `SELECT * FROM germany_users_with_iphones_over_35` to provide a silly example).
> ```

Nit: add a comma after the SQL statement
___
*[v21.1/data-domiciling.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw8Gr--dIJDjlaKhkz:-Mgw8Gr--dIJDjlaKhl-:b2aqrtr) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L25)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> As of CockroachDB v21.1 and earlier, some metadata about the user data may be stored in system ranges, system tables, etc. This might result in potential "leakage" outside of the desired domicile if your schema includes table names, etc., that may reveal information about their contents (e.g., `SELECT * FROM germany_users_with_iphones_over_35` to provide a silly example).
> {{site.data.alerts.end}}
> ```

Do you suppose this would be better placed under a `## Limitations` heading rather than in a callout?
___
*[v21.1/data-domiciling.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw5wmP5jbK8GsRqmaG:-Mgw5wmP5jbK8GsRqmaH:b-ht34kd) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L27)):*
> ```
> we recommend making sure
> ```

Maybe just "make sure"?
___
*[v21.1/data-domiciling.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw657X0hfuIlU6akcJ:-Mgw657X0hfuIlU6akcK:b-5mbtj2) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L27)):*
> ```
> information which
> ```

information that

I realize that is potentially repetitive with "such that" but it seems more readable/vaguely correct to me. Also, perhaps say "data" rather than "information" to be consistent with your intro?
___
*[v21.1/data-domiciling.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw6Rbp2_ONnPDWQ_ds:-Mgw6RbqBSON1F3pjVRR:bfv2nxh) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L33)):*
> ```
> keep it in a separate database
> ```

This is referring to "data sets", so perhaps "keep them in separate databases" or "keep data in separate databases" or "keep each data set in a separate databases".
___
*[v21.1/data-domiciling.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw6hFJC9o3zQAYiLGb:-Mgw6hFJC9o3zQAYiLGc:b8qirfv) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L43)):*
> ```
> Next, 
> ```

This isn't needed imo.
___
*[v21.1/data-domiciling.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw6lvWBKDG9HJPDa95:-Mgw6lvWBKDG9HJPDa96:b-23gi3p) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L43)):*
> ```
> eu_users
> ```

Code backticks on this
___
*[v21.1/data-domiciling.md, line 53 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw73Qy4u3tbgn9kRso:-Mgw73Qy4u3tbgn9kRsp:bc050w1) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L53)):*
> ```
> [cockroach start --locality](cockroach-start.html#locality) flag
> ```

Suggestion: `cockroach start` [`--locality` flag](cockroach-start.html#locality)
___
*[v21.1/data-domiciling.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw7YZL1E6vL_02MPUo:-Mgw7YZL1E6vL_02MPUp:bbn26ru) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L60)):*
> ```
> , e.g.
> ```

Suggest using `. For example:`
___
*[v21.1/data-domiciling.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw7wac94xARojaCBPK:-Mgw7wac94xARojaCBPL:b-7i0f60) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L81)):*
> ```
> limitations of
> ```

Nit: "limitations to"

**Review by rmloveland — COMMENTED** [review]
Thanks for the review Ryan!  And don't worry, I miss things all the time.  We're all doing our best!  Thanks for looking it over!

(I am 3/4 in the above for adding unnecessary exclamation points! I guess I'm finally cracking up!!!1! :-) )

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11019#-:-Mh-U85X96uHgjKfm297:b-bq5wi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[v21.1/data-domiciling.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-MgvxhwS4i6sQzpRfPpT:-Mh-UuQ743ANS1yHYDFq:b-bw8e1h) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Data which
> ```

I think this should be "Data that"
</blockquote></details>

Updated!
___
*[v21.1/data-domiciling.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw4pgkCs01cT6KJr8R:-Mh-UvwOA5Nx-O5AHb8T:bdm9e9) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L21)):*
I think this is kinda already covered by the bit above in the overview re: using `ADD REGION`:

>  At a high level, this process involves:

> Creating separate databases per domicile.
> Adding regions to those databases using the ADD REGION statement.
> Making sure your application is adding data meant for a specific domicile to the correct database.

Hesitant to add more linkage here since I was trying to keep out as much technical detail / linkage as possible since this needed legal review (and will continue to if more substantive changes are made going forward)

I agree re: localities is more specific generally but the regions are the localities we are using in the context of this example about EU, etc.  My assumption (perhaps wrong) is that a user needs to have already read and understood a bunch of our other docs before trying to implement some kind of data domiciling, so trying to stay high level with just this example
___
*[v21.1/data-domiciling.md, line 24 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw5qZX6NNWyMs3B7LO:-Mh-WcQw0ILl1G1CWQX9:bqmjwcm) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L24)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Nit: add a comma after the SQL statement
</blockquote></details>

Added!
___
*[v21.1/data-domiciling.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw8Gr--dIJDjlaKhkz:-Mh-WdPr9P6wDdIkB02E:b-ot0eop) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L25)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Do you suppose this would be better placed under a `## Limitations` heading rather than in a callout?
</blockquote></details>

It's also in Limitations, just to be sure!
___
*[v21.1/data-domiciling.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw5wmP5jbK8GsRqmaG:-Mh-Wm4x6YYnDPqVqioU:b5us1um) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L27)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> we recommend making sure
> ```

Maybe just "make sure"?
</blockquote></details>

Great point, if it is in our docs we are recommending it lol
___
*[v21.1/data-domiciling.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw657X0hfuIlU6akcJ:-Mh-WrFv7Ht0We3mGCSe:b2eu64n) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L27)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> information which
> ```

information that

I realize that is potentially repetitive with "such that" but it seems more readable/vaguely correct to me. Also, perhaps say "data" rather than "information" to be consistent with your intro?
</blockquote></details>

Updated to "that" - once again you are correct!  According to https://www.writersdigest.com/write-better-fiction/which-vs-that "If the sentence doesn't need the clause that the word in question is connecting, use which. If it does, use that."

Re: saying "Data" instead, I'd rather keep it "information" because it's (a) sort of a synonym? to add variety and (b) the data is what is in the database but one can deduce "information" about what is in the data due to the possible "leakage" due to unintentional schema design issues
___
*[v21.1/data-domiciling.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw6Rbp2_ONnPDWQ_ds:-Mh-XaU8CGSNNYPAq_2Z:bvoocyr) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L33)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> keep it in a separate database
> ```

This is referring to "data sets", so perhaps "keep them in separate databases" or "keep data in separate databases" or "keep each data set in a separate databases".
</blockquote></details>

Ah!  Yes, went with "keep them in separate databases"
___
*[v21.1/data-domiciling.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw6hFJC9o3zQAYiLGb:-Mh-Xm3D1B1r2jDEqdqv:b-slm8i3) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L43)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Next, 
> ```

This isn't needed imo.
</blockquote></details>

How dare you notice my UNNECESSARY TRANSITIONS RYANNNNNNNNNNNNNN

(deleted, thanks)
___
*[v21.1/data-domiciling.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw6lvWBKDG9HJPDa95:-Mh-XuQH77Rl1sZeh9iv:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L43)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> eu_users
> ```

Code backticks on this
</blockquote></details>

Done!
___
*[v21.1/data-domiciling.md, line 53 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw73Qy4u3tbgn9kRso:-Mh-Y3Zt2R0I1NcR3x9Y:b1025jn) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L53)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> [cockroach start --locality](cockroach-start.html#locality) flag
> ```

Suggestion: `cockroach start` [`--locality` flag](cockroach-start.html#locality)
</blockquote></details>

Updated to use code font!
___
*[v21.1/data-domiciling.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw7YZL1E6vL_02MPUo:-Mh-Y8bs8Za-D9LOQWKW:b-4pj5nb) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L60)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> , e.g.
> ```

Suggest using `. For example:`
</blockquote></details>

Nice, done!
___
*[v21.1/data-domiciling.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/docs/11019#-Mgw7wac94xARojaCBPK:-Mh-YD434pN_L4VidCbk:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/b3da2756dba2761fc19458c79017b4d8b874a504/v21.1/data-domiciling.md#L81)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> limitations of
> ```

Nit: "limitations to"
</blockquote></details>

Fixed!

**Pull request merged**
