### PR TITLE
Document SerializationFailureError for retryable errors

### PR DESCRIPTION
**Pull request by nvanbenschoten**
See cockroachdb/cockroach#6797.

We changed the error code that clients should expect for retryable
serialization errors. This change reflects how clients should react to
this new error.

Any seemingly unrelated changes here are because I ran `make`.

For now I've simply replaced the expected error code in samples, but if sample authors 
know about more idiomatic ways to catch standard PG errors from their respective drivers
(i.e. specific exceptions to catch), please let me know. 
@bdarnell @andreimatei @tschottdorf @tamird @dt

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/315)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@jseldess Let me know if I missed any references. I skimmed over the docs briefly and these were the only ones I found.

**Comment by dt** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/sql/diagrams/grammar.html, line 1217 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/315#-KIYPULPoRgFpdFfSxML:-KIYPULPoRgFpdFfSxMM:1239317811) ([raw file](https://github.com/cockroachdb/docs/blob/c643fc7936a87c42f78dc75dd1f6b018e0509057/_includes/sql/diagrams/grammar.html#L1217)):*
> ```HTML
>             <li><a href="#name_list" title="name_list">name_list</a></li>
>             <li><a href="#opt_name" title="opt_name">opt_name</a></li>
>             <li><a href="#opt_name_parens" title="opt_name_parens">opt_name_parens</a></li>
> ```

whoops, sorry, this was me -- i should have done this in a standalone PR, but IIRC the position is we aren't picky about git history cleanliness in docs so fine leaving this here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/315)*

**Comment by jseldess** [comment]
LGTM, @nvanbenschoten. I wonder why the other transaction examples don't use the error code, though? The C++ example seems to look for the "restart transaction:" string instead of the error code, for example. Do we want to update all examples to use the code?

Also, we need to update the error code in the go library: https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go#L82.

**Comment by nvanbenschoten** [comment]
@andreimatei Can expand on the C++ example, but I seem to remember the reason was that the driver did not expose error codes through exceptions.

And yep, already taken care of! https://github.com/cockroachdb/cockroach-go/pull/14.

**Comment by jseldess** [comment]
Merging this. If we want to update the C++ example and others to use the error code, we can do that in a separate PR.

**Comment by jseldess** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/315)*

**Comment by nvanbenschoten** [comment]
Ah sorry, I should made it more clear that we were waiting on the week's release to merge this (see https://github.com/cockroachdb/cockroach/pull/6797#issuecomment-221404111). It's probably not worth reverting to fix the inconsistency for a day though.

**Comment by andreimatei** [comment]
Yeah, the C++ lib doesn't want to give you the error codes. But now that
we're using a standard one, it might have an appropriate Exception class.
I'll check.

**Comment by jseldess** [comment]
Whoops, sorry about that, @nvanbenschoten. Need to get better about keeping the release schedule in mind. But I agree that it's probably fine to leave it be this time.

**Pull request merged**
