### PR TITLE
Secure orchestration with Docker Swarm

### LINKED ISSUE #876: Secure deployment on Docker Swarm
We need to expand [orchestrate cockroachdb with docker swarm](https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-docker-swarm.html) to cover security.

@a-robinson

### PR DESCRIPTION
**Pull request by jseldess**
This PR breaks the swarm tutorial into two pages, one for secure orchestration and the other for insecure orchestration. For secure orchestration, the main difference is the creation and use of certs and Docker secrets.

Fixes #876

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1184)

### CODE REVIEW

**Comment by jseldess** [comment]
@a-robinson, if any explanations are lacking, or details are missing, please let me know. Likewise if you feel there's too much detail (it's a pretty long page at this point).

**Comment by a-robinson** [comment]
Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCpmWP17dDMYFRXisr:-KfCpmWP17dDMYFRXiss:bjcomh4) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L1)):*
> ```Markdown
> ---
> ```

Are these instructions just copied over verbatim from the old file or have they changed? i.e. should I read through them carefully?

---

*[orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCpfoi1KO8lZWRfEXl:-KfCpfoi1KO8lZWRfEXm:b-w4soeh) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L206)):*
> ```Markdown
>    ~~~
> 
> ## Step 7. Use the built-in SQL client
> ```

You skipped step 6 :)

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCqwKWlXUaYH7Zue2-:-KfCqwKWlXUaYH7Zue20:b95sc19) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L14)):*
> ```Markdown
> This page shows you how to orchestrate the deployment and management of a secure three-node CockroachDB cluster as a [swarm of Docker Engines](https://docs.docker.com/engine/swarm/).
> 
> If you are not concerned with protecting your data with TLS encryption, you can use an insecure cluster instead. Select **Insecure** above for instructions.
> ```

It *might* be worth clarifying that this is about encryption on the wire (not on disk), but I'm kind of on the fence about whether that's needed.

Or that an insecure cluster is simpler to setup? Although that's probably assumed by most people

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCuXjRrYBL7mafe8qO:-KfCuXjS7i6vmRdaexAX:bqdxmpw) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L166)):*
> ```Markdown
>    ~~~
> 
>    These commands issue the cert/key pairs to the service names you will use for the nodes later (`cockroachdb-1`, `cockroachdb-2`, `cockroachdb-3`), as well as to local addresses that will make it possible to run the built-in SQL shell and other CockroachDB client commands in the same containers as the nodes. If you plan to connect a client to the cluster from a separate container, you'll need to <a href="create-security-certificates.html#create-the-certificate-and-key-for-a-client">create a client cert and key</a> as well.
> ```

"easier" would be more accurate than "possible" in this case, since it's still possible without it, just more verbose.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCvbrDa68zzcXlgEF0:-KfCvbrEYUJXXVUSKbss:bgmrbr3) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L204)):*
> ```Markdown
>    --secret cockroachdb-cacert \
>    --secret cockroachdb-1-cert \
>    --secret source=cockroachdb-1-key,target=cockroachdb-1-key,mode=0600 \
> ```

As I mentioned last week, there's also the option of setting the target to something generic so that fewer lines differ between each node's configuration -- e.g. if you set `target=node.key` then the command-line argument below could be `--key=/run/secrets/node.key` on all nodes.

It's not necessarily better, so it's your call. The main benefit of it would be not having to figure out which service's container you're in when exec'ing into one of them in step 7.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 222 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCwTIVnjGAicepCBjt:-KfCwTIVnjGAicepCBju:b-gg85dg) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L222)):*
> ```Markdown
>      {{site.data.alerts.callout_info}}If you plan on replacing or adding instances, it's recommended to use remote storage instead of local disk. To do so, <a href="https://docs.docker.com/engine/reference/commandline/volume_create/">create a remote volume</a> for each CockroachDB instance using the volume driver of your choice, and then specify that volume driver instead of the <code>volume-driver=local</code> part of the command above, e.g., <code>volume-driver=gce</code> if using the <a href="https://github.com/mcuadros/gce-docker">GCE volume driver</a>.
>    - `--stop-grace-period`: This flag sets a grace period to give CockroachDB enough time to shut down gracefully, when possible.
>    - `--secret`: These flags identify the secrets to use in securing the node. They must reference the secret names for the CA certificate and node certificate and key, as defined in step 5.5. Also, the file permissions for the node key secret must be set to `0600` as shown; if this isn't set, Docker will assign a default file permission of `0400`, which will not work with CockroachDB.
> ```

You don't have to change this, but the default permissions work fine for the server, it's just CockroachDB's built-in SQL client that rejects them.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 268 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCwsIOAdp8Rc_RXa6c:-KfCwsIOAdp8Rc_RXa6d:bjq38gk) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L268)):*
> ```Markdown
> 
>    - The `--name` and `--secret` flags are unique for each service.
>    - The CockroachDB command to [`start`](start-a-node.html) each node uses the the `--join` flag to connect it to the cluster via the name of the first service and its default port, `cockroachdbb-1:26257`.
> ```

s/cockroachdbb/cockroachdb

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 310 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCxOte-FjUCMVVDNjR:-KfCxOte-FjUCMVVDNjS:bxi6fyi) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L310)):*
> ```Markdown
> ## Step 7. Use the built-in SQL client
> 
> 1. On the first instance, use the `sudo docker ps` command to get the ID of the container running the CockroachDB node:
> ```

This step might cause problems for people, since I don't believe there's any guarantee about which service will end up on instance, meaning that they might have cockroachdb-1 or cockroachdb-3 on that instance rather than cockroachdb-2, as in your example. We either have to tell people to get the service name out of the hostname (as below) or use more generic filenames for the node cert and key inside the containers.

```
   $ sudo docker exec -it 9539871cc769 \
   ./cockroach sql \
   --ca-cert=/run/secrets/cockroachdb-cacert \
   --cert="/run/secrets/$(hostname)-cert" \
   --key="/run/secrets/$(hostname)-key"
```

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 361 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCy4DIQtFzN45mi08M:-KfCy4DIQtFzN45mi08N:b2lzphw) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L361)):*
> ```Markdown
> To see this in action:
> 
> 1. On the second instance and use the `sudo docker ps` command to get the ID of the container running the CockroachDB node:
> ```

The same comment applies here about the cert/key name issue.

Or we have to switch to using `docker kill`, as I think we discussed last week

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 414 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCyNVX3RVNa-wA1fmc:-KfCyNVYydRHJkYTHXFQ:byzra3b) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L414)):*
> ```Markdown
> ~~~
> 
> You may want to remove the persistent volumes used by the services as well. To do this, on each instance:
> ```

You might also want to remove the secrets

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1184)*

**Comment by bdarnell** [comment]
Review status: 7 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCqwKWlXUaYH7Zue2-:-KfCyow9CyEiC_OekgvA:b-obd69e) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L14)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It *might* be worth clarifying that this is about encryption on the wire (not on disk), but I'm kind of on the fence about whether that's needed.

Or that an insecure cluster is simpler to setup? Although that's probably assumed by most people
</blockquote></details>

Note that our insecure mode is even less secure than most databases', so people who might run mysql or postgres without tls might still not want to use our insecure mode. We should emphasize that insecure mode is only for testing with data your don't care about (and to the extent that we can simplify the certificate management stuff, we should phase out documentation of insecure clusters completely. Maybe we should limit discussion of insecure clusters to the single-node case)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1184)*

**Comment by jseldess** [comment]
Review status: 7 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCpmWP17dDMYFRXisr:-KfHCyas__UeF5LVBHHb:b-6p6skk) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L1)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Are these instructions just copied over verbatim from the old file or have they changed? i.e. should I read through them carefully?
</blockquote></details>

Yes, these haven't changed. No need to check this file.

---

*[orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCpfoi1KO8lZWRfEXl:-KfHDTIapByLHJgvbL_9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L206)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You skipped step 6 :)
</blockquote></details>

Done.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCqwKWlXUaYH7Zue2-:-KfHgWJMD_BVS9TGh00A:b-aa53l2) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L14)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Note that our insecure mode is even less secure than most databases', so people who might run mysql or postgres without tls might still not want to use our insecure mode. We should emphasize that insecure mode is only for testing with data your don't care about (and to the extent that we can simplify the certificate management stuff, we should phase out documentation of insecure clusters completely. Maybe we should limit discussion of insecure clusters to the single-node case)
</blockquote></details>

Emphasized the testing scenario for insecure deployment, and revised the language a bit so it can't be misunderstood to be about on-disk data.

@bdarnell, I'll open a separate docs issue to talk discuss how much to de-emphasize insecure deployment throughout the docs.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCuXjRrYBL7mafe8qO:-KfHEUB2JFFUqg9MdZid:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L166)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

"easier" would be more accurate than "possible" in this case, since it's still possible without it, just more verbose.
</blockquote></details>

Done.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCvbrDa68zzcXlgEF0:-KfHLZ6XYMP5pbd0vb2S:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L204)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

As I mentioned last week, there's also the option of setting the target to something generic so that fewer lines differ between each node's configuration -- e.g. if you set `target=node.key` then the command-line argument below could be `--key=/run/secrets/node.key` on all nodes.

It's not necessarily better, so it's your call. The main benefit of it would be not having to figure out which service's container you're in when exec'ing into one of them in step 7.
</blockquote></details>

Done.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 222 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCwTIVnjGAicepCBjt:-KfHLXZlKhdlXh2LeQh3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L222)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You don't have to change this, but the default permissions work fine for the server, it's just CockroachDB's built-in SQL client that rejects them.
</blockquote></details>

Done.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 268 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCwsIOAdp8Rc_RXa6c:-KfHLdrtrKGMNYdT9iJ9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L268)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/cockroachdbb/cockroachdb
</blockquote></details>

Done.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 310 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCxOte-FjUCMVVDNjR:-KfHLn92t5aT5bb-lLah:b-i5vntp) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L310)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This step might cause problems for people, since I don't believe there's any guarantee about which service will end up on instance, meaning that they might have cockroachdb-1 or cockroachdb-3 on that instance rather than cockroachdb-2, as in your example. We either have to tell people to get the service name out of the hostname (as below) or use more generic filenames for the node cert and key inside the containers.

```
   $ sudo docker exec -it 9539871cc769 \
   ./cockroach sql \
   --ca-cert=/run/secrets/cockroachdb-cacert \
   --cert="/run/secrets/$(hostname)-cert" \
   --key="/run/secrets/$(hostname)-key"
```
</blockquote></details>

Went with more generic filenames.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 361 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCy4DIQtFzN45mi08M:-KfHeHkuxkK_HOft4Dhm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L361)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The same comment applies here about the cert/key name issue.

Or we have to switch to using `docker kill`, as I think we discussed last week
</blockquote></details>

Done.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 414 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfCyNVX3RVNa-wA1fmc:-KfHMcgTQ3ZJ5B_2SJR0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ec0cdfb4cdfa2a98a0e7fc9b032d1185958e04a6/orchestrate-cockroachdb-with-docker-swarm.md#L414)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You might also want to remove the secrets
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1184)*

**Comment by a-robinson** [comment]
:lgtm: Looks great, Jesse!

---

Reviewed 6 of 7 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 425 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfIILYQ0hg2gxpuE5JH:-KfIILYQ0hg2gxpuE5JI:b-bshqeh) ([raw file](https://github.com/cockroachdb/docs/blob/fa56b2d7af47595b7b79365c72fd0ac28caa7f80/orchestrate-cockroachdb-with-docker-swarm.md#L425)):*
> ```Markdown
> 
> # Remove the secrets:
> $ sudo docker secret rm ca.cert cockroachdb-2.cert cockroachdb-1.key
> ```

I think you mean cockroachdb-1.cert, judging by the output of your `ls` command above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-:-KfIIQKzKKW0cSwgs-Xt:b42g1fh)*

**Comment by jseldess** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[orchestrate-cockroachdb-with-docker-swarm.md, line 425 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1184#-KfIILYQ0hg2gxpuE5JH:-KfILZ73zfBvG-utxG6u:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fa56b2d7af47595b7b79365c72fd0ac28caa7f80/orchestrate-cockroachdb-with-docker-swarm.md#L425)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I think you mean cockroachdb-1.cert, judging by the output of your `ls` command above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1184)*

**Pull request merged**
