### PR TITLE
Document RESET and SET TO DEFAULT

### LINKED ISSUE #1245: sql: Support RESET and SET TO DEFAULT
PR: https://github.com/cockroachdb/cockroach/pull/14105

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1245

### CODE REVIEW

**Comment by jseldess** [comment]
@knz or @jordanlewis, can one of you PTAL?

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v1.1/reset-vars.md, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw08q2lM74ZKCzZ5Weq:-Kw08q2mR0E7YS5BX8S0:b-o742is) ([raw file](https://github.com/cockroachdb/docs/blob/660e51fc510fd0c851dd715a0286067179234b00/v1.1/reset-vars.md#L2)):*
> ```Markdown
> ---
> title: RESET (session setting)
> ```

s/setting/variable

---

*[v1.1/set-vars.md, line 2 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw094iBefZVDEqFgi3u:-Kw094iCDBCj8jAgnL1W:b-o742is) ([raw file](https://github.com/cockroachdb/docs/blob/a9edd5c0bd0554ab92a9e545e1531092c1f051ce/v1.1/set-vars.md#L2)):*
> ```Markdown
> ---
> title: SET (session setting)
> ```

s/setting/variable

---

*[v1.1/set-vars.md, line 3 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw095rDKwBeSDkgzvB5:-Kw095rERYvqSqGILeAy:b-i5wptt) ([raw file](https://github.com/cockroachdb/docs/blob/a9edd5c0bd0554ab92a9e545e1531092c1f051ce/v1.1/set-vars.md#L3)):*
> ```Markdown
> ---
> title: SET (session setting)
> summary: The SET statement modifies the current settings for the client session.
> ```

"the current configuration variables for"

---

*[v1.1/set-vars.md, line 116 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw09ACCIY_noSdjODrC:-Kw09ACCIY_noSdjODrD:b-o742is) ([raw file](https://github.com/cockroachdb/docs/blob/a9edd5c0bd0554ab92a9e545e1531092c1f051ce/v1.1/set-vars.md#L116)):*
> ```Markdown
> ~~~
> 
> ### Reset a Setting to Its Default Value
> ```

s/setting/variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1979)*

**Comment by jseldess** [comment]
TFTR, @knz.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v1.1/reset-vars.md, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw08q2lM74ZKCzZ5Weq:-Kw0ahEgqUp9MxfpPei-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/660e51fc510fd0c851dd715a0286067179234b00/v1.1/reset-vars.md#L2)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/setting/variable
</blockquote></details>

Done.

---

*[v1.1/set-vars.md, line 2 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw094iBefZVDEqFgi3u:-Kw0airNYQ9DGcP3-uCn:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a9edd5c0bd0554ab92a9e545e1531092c1f051ce/v1.1/set-vars.md#L2)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/setting/variable
</blockquote></details>

Done.

---

*[v1.1/set-vars.md, line 3 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw095rDKwBeSDkgzvB5:-Kw0aqDwKEr8OWQ--p0y:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a9edd5c0bd0554ab92a9e545e1531092c1f051ce/v1.1/set-vars.md#L3)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"the current configuration variables for"
</blockquote></details>

Done.

---

*[v1.1/set-vars.md, line 116 at r7](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-Kw09ACCIY_noSdjODrC:-Kw0at4PE9QiSDS0nDY0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/a9edd5c0bd0554ab92a9e545e1531092c1f051ce/v1.1/set-vars.md#L116)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/setting/variable
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-:-Kw0c702LYbKswpiu8qH:b-r0jgdu)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r9, 1 of 1 files at r10, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 3 of 3 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1979#-:-Kw0eWC4mN9tIOX1nGwx:bnfp4nl)*

**Pull request merged**
