### PR TITLE
add --cert-principal-map

### LINKED ISSUE #6967: cli,security: add --cert-principal-map
PR: https://github.com/cockroachdb/cockroach/pull/45819

From release notes:
> Client and node certificates are now allowed to specify the principal in either the SubjectCommonName field or the SubjectAlternateNames field. Previously, the principal could only be specified in the SubjectCommonName field. [#45819][#45819] {% comment %}doc{% endcomment %}
>
> Added the `--cert-principal-map` flag to [`cockroach start`](../v20.1/cockroach-start.html), which specifies a comma-separated list of `cert-principal`:`db-principal` mappings that map the principals found in certificates to DB principals. This allows the usage of "node" and "root" certificates where the common name contains dots or a host name, which allows such certificates to be generated by certificate authorities that place restrictions on the contents of the common name field. [#45819][#45819] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Closes #6967 

cc @piyush-singh for visibility: The docs and the review comments might help guide your acceptance testing efforts :)

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
@dbist via Slack:
Maybe adding example of first client with root and second client with maxroach user is useful? Just the fact you need create user maxroach; not to be forgotten

**Comment by Amruta-Ranade** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/7104)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dbist and @petermattis)
> 
> _[v20.1/create-security-certificates-openssl.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/docs/7104#-M4RDy0_5pTuKdRY9lCe:-M4Uit7HBymPGmfBaXBO:b-u0oi98) ([raw file](https://github.com/cockroachdb/docs/blob/33ca546f67f13ba4ae4f74011a9e38c4bd6e081f/v20.1/create-security-certificates-openssl.md#L189)):_
> 
> Previously, Amruta-Ranade (Amruta Ranade) wrote…
> After poking at this, I think this is borne out of how certificate use changed per RFC 5280.
> 
> `commonName` used to be is expected to represent the dns hostname or IP of a server but ultimately it's just a printable string.
> 
> The `subjectAltName` extension is meant to eventually replace `commonName` because it adds typing to the subject value.
> 
> Today, it is incumbent on the consumer to check both fields as the RFC states "_The subject name MAY be carried in the subject field and/or the subjectAltName extension._"
> 
> We know that CRDB now can do this courtesy of [cockroachdb/cockroach#45819](https://github.com/cockroachdb/cockroach/pull/45819) meaning that the value of the commonName field doesn't actually matter as long as the correct value(s) appear in the subjectAltName(s).
> 
> The configuration immediately above would result in the commonName being set to "DNS:node.crdb.io" which isn't a valid URL, but because it is correctly represented as a DNS entry in subjectAltName as `node.crdb.io` it doesn't matter.
> 
> It doesn't hurt anything to have it in both places today but it doesn't help either.
> 
> On an aside according to RFC 5280 "_If subject naming information is present only in the subjectAltName extension (e.g., a key bound only to an email address or URI), then the subject name MUST be an empty sequence and the subjectAltName extension MUST be critical._"
> 
> I was able to get OpenSSL to generate a certificate that matches this pattern with the below modifications but haven't yet had time to test it against the database.
> 
> In `ca.cnf` replace "commonName = supplied" with "commonName = optional"
> 
> For 'node.cnf' I removed the commonName from the distinguished_name section and set subjectAltName as critical.
> 
> ```
> # OpenSSL node configuration file
> [ req ]
> prompt=no
> distinguished_name = distinguished_name
> req_extensions = extensions
> 
> [ distinguished_name ]
> organizationName = Cockroach
> 
> [ extensions ]
> subjectAltName = critical,DNS:localhost,DNS:node,IP:0.0.0.0
> ```

This is confusing :) 
For now, I feel it's safer to recommend setting all values in both commonName and subjectAltName, especially since things seem to be in flux. Is that okay?

**Comment by Amruta-Ranade** [comment]
> I went through the steps without a hitch. I think the following nits will improve the overall document.
> 
> 1. In the root client creation section, rephrase repeat steps 1-5 for each additional client to refer to step 5. creating cert for clients other than `root`.

Oh, I had a question about this as I was writing it and forgot to ask it in the channel: Should I just delete steps 5 and 6 from the "create certs for root" section? We expect the users to connect to the cluster using their local machine using the root cert, right? Not upload the cert anywhere?

> 2. rename Step 5 to say: create cert for client other than `root`.

Done. Renamed to "Create the certificate and key pair for a non-`root` client"
 
> 3. In step 5.1, creating additional clients, rephrase create `client.cnf` to create or reuse the one used for `root` user. It is the same content, just note to change `commonName` for each additional user.

Good catch. I meant to say "edit" instead of "create". Is that the right way though? Should they reuse the file or create a new one for each client?

> 4. in the step to start cluster, I'd include `<fqdn,nodename>`. Check with others on the thoughts?

cc @aaron-crl for thoughts

> 5. In Peter's document, he provided a step to introspect certificates, I think it's valuable to add here for both client and node certs at the end of each respective certificate creation sections.
>    `openssl x509 -in node-certs/node.crt -text | grep "X509v3 Subject Alternative Name" -A 1`
> 
> ```
>             X509v3 Subject Alternative Name: critical
>                 DNS:localhost, DNS:node.example.com, IP Address:127.0.0.1
> ```
> 
> `openssl x509 -in client-certs/client.root.crt -text | grep CN=`
> 
> ```
>         Issuer: O=Cockroach, CN=Cockroach CA
>         Subject: O=Cockroach, CN=root
> ```
> 
> `openssl x509 -in client-certs/client.roach.crt -text | grep CN=`
> 
> ```
>         Issuer: O=Cockroach, CN=Cockroach CA
>         Subject: O=Cockroach, CN=roach
> ```

Oooh...That's a great idea! Added!

> 1. finally, add a step to use the client cert in the very last step
>    `cockroach sql --certs-dir=client-certs --user=roach`

Done.

**Comment by Amruta-Ranade** [comment]
> since we're using placeholders, perhaps `--user=roach` should say `--user=<username>`

Yes..sorry. Fixed.

**Comment by dbist** [comment]
@petermattis in my tests with `openssl`, single directory did not work either. The error was similar to ```
ERROR: failed to generate client certificate and key: client/server node certificate has principals ["node.crdb.io" "localhost" "Artems-MBP" "*.local" "127.0.0.1::1"], expected "node"
Failed running "cert create-client"
```

**Comment by aaron-crl** [comment]
We may want to change the default certificate lifespans to bring usage in line with what OSX and Chrome expect per: https://github.com/cockroachdb/docs/issues/6946#issuecomment-601339317

Namely:
- In ca.cnf change default_days to 365
- Change lifespan for the CA from 3660 to 365 days
- Remove `-days 1830` override from the cert generation code leaving the default 365 to propigate from the CA config.

**Comment by Amruta-Ranade** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/7104)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Amruta-Ranade, @dbist, and @petermattis)
> 
> _[v20.1/create-security-certificates-openssl.md, line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/7104#-M4REODo130LBQHxjTV_:-M4noc-b91x2ILy5d7Uw:b-3exku9) ([raw file](https://github.com/cockroachdb/docs/blob/33ca546f67f13ba4ae4f74011a9e38c4bd6e081f/v20.1/create-security-certificates-openssl.md#L77)):_
> 
> Previously, Amruta-Ranade (Amruta Ranade) wrote…
> I'd like to see that error if you can generate it? It doesn't make sense to me that it should fail.

Same error as Artem's:

~~~
ERROR: failed to generate client certificate and key: client/server node certificate has principals ["node.crdb.io" "localhost" "Artems-MBP" "*.local" "127.0.0.1::1"], expected "node"
Failed running "cert create-client"
~~~

> _[v20.1/create-security-certificates-openssl.md, line 250 at r1](https://reviewable.io/reviews/cockroachdb/docs/7104#-M4noPVl0_QFI9tKnnv2:-M4noPVl0_QFI9tKnnv3:by5ekqu) ([raw file](https://github.com/cockroachdb/docs/blob/33ca546f67f13ba4ae4f74011a9e38c4bd6e081f/v20.1/create-security-certificates-openssl.md#L250)):_
> 
> > ```gfm
> >     $ scp node-certs/ca.crt \
> >     node-certs/node.crt \
> >     Node-certs/node.key \
> > ```
> 
> Does this break something? `Node` vs `node`?

Oh, good point. Haven't checked that yet. Will report back.

**Comment by aaron-crl** [comment]
> > _[v20.1/create-security-certificates-openssl.md, line 77 at r1](https://reviewable.io/reviews/cockroachdb/docs/7104#-M4REODo130LBQHxjTV_:-M4noc-b91x2ILy5d7Uw:b-3exku9) ([raw file](https://github.com/cockroachdb/docs/blob/33ca546f67f13ba4ae4f74011a9e38c4bd6e081f/v20.1/create-security-certificates-openssl.md#L77)):_
> > Previously, Amruta-Ranade (Amruta Ranade) wrote…
> > I'd like to see that error if you can generate it? It doesn't make sense to me that it should fail.
> 
> Same error as Artem's:
> 
> ```
> ERROR: failed to generate client certificate and key: client/server node certificate has principals ["node.crdb.io" "localhost" "Artems-MBP" "*.local" "127.0.0.1::1"], expected "node"
> Failed running "cert create-client"
> ```
> 

I'm having trouble reproducing this. Here's my test script that works with a single directory and separate ones:

**BE CAREFUL IT AUTOMATICALLY KILLS THE PROCESS AND DELETES CERT FILES**

```
export CCERTS=client-certs
#export NCERTS=node-certs
export NCERTS=$CCERTS
export CADIR=my-safe-directory

kill -9 $( ps | grep start-single-node | grep -v "grep" | sed 's/$ +//g' | cut -f1 -d \ )

rm index.txt* *.csr serial.*

rm -rf $CCERTS
rm -rf $NCERTS
rm -rf $CADIR

mkdir $CCERTS
mkdir $NCERTS
mkdir $CADIR

mkdir $CADIR
openssl genrsa -out $CADIR/ca.key 2048
chmod 400 $CADIR/ca.key 
  
mkdir $NCERTS/
openssl req -new -x509 -config ca.cnf -key $CADIR/ca.key -out $NCERTS/ca.crt -days 3660 -batch
rm -f index.txt serial.txt
touch index.txt
echo '01' > serial.txt
openssl genrsa -out $NCERTS/node.key 2048
chmod 400 $NCERTS/node.key
openssl req -new -config node.cnf -key $NCERTS/node.key -out node.csr -batch
openssl ca -config ca.cnf -keyfile $CADIR/ca.key -cert $NCERTS/ca.crt -policy signing_policy -extensions signing_node_req -out $NCERTS/node.crt -outdir $NCERTS/ -in node.csr -days 1830 -batch
openssl x509 -in $NCERTS/node.crt -text | grep "X509v3 Subject Alternative Name" -A 1

mkdir $CCERTS
cp $NCERTS/ca.crt $CCERTS
openssl genrsa -out $CCERTS/client.root.key 2048
chmod 400 $CCERTS/client.root.key
openssl req -new -config client.cnf -key $CCERTS/client.root.key -out client.root.csr -batch
openssl ca -config ca.cnf -keyfile $CADIR/ca.key -cert $CCERTS/ca.crt -policy signing_policy -extensions signing_client_req -out $CCERTS/client.root.crt -outdir $CCERTS/ -in client.root.csr -days 1830 -batch
openssl x509 -in $CCERTS/client.root.crt -text | grep CN=

cockroach start-single-node --certs-dir=$NCERTS --cert-principal-map=node.localhost:node --background
```

However, the CLI seems to validate the principle name appears in the `node` cert before using the client cert to connect.

For example:
My SAN entry for my `node` cert is: 
```
[ extensions ]
subjectAltName = critical,DNS:node,DNS:node.localhost,IP:127.0.0.1
```
And I get the below error:

```
$ cockroach sql --certs-dir=client-certs
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: x509: certificate is valid for node, node.localhost, not localhost
Failed running "sql"
```

But if I add `localhost` to the **node** cert, I'm able to connect just fine as root.
```
[ extensions ]
subjectAltName = critical,DNS:node,DNS:node.localhost,DNS:localhost,IP:127.0.0.1
```

```
$ cockroach sql --certs-dir=client-certs
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v20.1.0-beta.4 (x86_64-apple-darwin14, built 2020/03/24 01:31:53, go1.13.5) (same version as client)
# Cluster ID: 765314c3-f249-48d1-8747-7bb59c315ed3
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> 
```

I'm going to update https://github.com/cockroachdb/cockroach/issues/47300 to narrow it to CLI client only since it sounds like these issues are related.

**Comment by Amruta-Ranade** [comment]
My SAN field has localhost in it and it still doesn't work with a single directory :(
I also need help troubleshooting the root:client mapping.

**Comment by Amruta-Ranade** [comment]
Note to self: Check if it makes sense to have instructions to upload certs to nodes/clients and also ask users to create a local cluster to test stuff. The older instructions (the ones abt uploading certs) may no longer be relevant.

**Comment by Amruta-Ranade** [comment]
Update: Aaron and I confirmed that the single directory approach doesn't work. Documenting the two-directory approach for 20.1 unless we get a patch in before the release.
cc @petermattis @dbist for visibility.

**Comment by aaron-crl** [comment]
> Update: Aaron and I confirmed that the single directory approach doesn't work. Documenting the two-directory approach for 20.1 unless we get a patch in before the release.
> cc @petermattis @dbist for visibility.

For context (I'll write this up in its own issue tomorrow with repro steps) the `cockroach sql` command seems to load node certificates first if it finds them in the `--certs-dir`, then any others. If the node certs are not in the --certs-dir (or if they are not named node.crt and node.key) then the client ignores them and loads the client.root.* files.

**Comment by dbist** [comment]
@Amruta-Ranade here's my write-up with single directory and `--url` instead.

```
mkdir certs my-safe-directory
openssl genrsa -out my-safe-directory/ca.key 2048
chmod 400 my-safe-directory/ca.key
openssl req -new -x509 -config ca.cnf -key my-safe-directory/ca.key -out certs/ca.crt -days 365 -batch
rm -f index.txt serial.txt
touch index.txt
echo '01' > serial.txt
openssl genrsa -out certs/node.key 2048
chmod 400 certs/node.key
openssl req -new -config node.cnf -key certs/node.key -out node.csr -batch
openssl ca -config ca.cnf -keyfile my-safe-directory/ca.key -cert certs/ca.crt -policy signing_policy -extensions signing_node_req -out certs/node.crt -outdir certs/ -in node.csr -batch
openssl x509 -in certs/node.crt -text | grep "X509v3 Subject Alternative Name" -A 1
openssl genrsa -out certs/client.root.key 2048
chmod 400 certs/client.root.key
openssl req -new -config client.cnf -key certs/client.root.key -out client.root.csr -batch
openssl ca -config ca.cnf -keyfile my-safe-directory/ca.key -cert certs/ca.crt -policy signing_policy -extensions signing_client_req -out certs/client.root.crt -outdir certs/ -in client.root.csr -batch
openssl x509 -in certs/client.root.crt -text | grep CN=
# removing .pem files is only required once with a single directory
rm -rf certs/*.pem
cockroach start-single-node --certs-dir=certs --cert-principal-map=node.example.com:node,user.example.com:root --background
cockroach sql --url 'postgresql://root@node.example.com:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt'

# create another user called `user2.example.com` as that's what's it's called in client.cnf `DNS:user2.example.com`, you can use another name like user2 but you have to strip `.example.com` from every step including file names.

# in sql shell
create user 'user2.example.com';
\q
openssl genrsa -out certs/client.user2.example.com.key 2048
chmod 400 certs/client.user2.example.com.key
openssl req -new -config client.cnf -key certs/client.user2.example.com.key -out client.user2.example.com.csr -batch
openssl ca -config ca.cnf -keyfile my-safe-directory/ca.key -cert certs/ca.crt -policy signing_policy -extensions signing_client_req -out certs/client.user2.example.com.crt -outdir certs/ -in client.user2.example.com.csr -batch
openssl x509 -in certs/client.user2.example.com.crt -text | grep CN=
cockroach sql --url 'postgresql://user2.example.com@node.example.com:26257?sslcert=certs%2Fclient.user2.example.com.crt&sslkey=certs%2Fclient.user2.example.com.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt'
```

**Comment by Amruta-Ranade** [comment]
Updated the instructions to use the connection URL instead of `cockroach sql`. This takes care of the single/separate directory issue as well as the cert mapping issue 🎉 

cc @aaron-crl @dbist @petermattis for final checks/approvals.

**Comment by Amruta-Ranade** [comment]
> aside from mentioning to remove `.pem` file once because all of them will reside in the single `certs` dir, this looks good to me. 

Updated as discussed on Slack.

> The `client.cnf` file for additional users is missing SAN but it's not a deal breaker. Mine looks like so
> 
> ```
> [ extensions ]
> subjectAltName = email:user2@example.com,DNS:user2.example.com,DNS:user2
> ```

The reason I didn't include SAN in the second user's conf is that we aren't mapping the second user to a DB principal, whereas in the first user's conf, we are mapping the user to root. It makes things clearer to me to see what's mapped and what isn't. But I might be mistaken. cc @aaron-crl for input.

> which demonstrates this user is not root and also referenced by short name `user2`. Again not major. This is long and painful, great job, thank you for sticking with it! LGTM after removing `.pem`.

**Comment by dbist** [comment]
I noticed a difference in the first and second url, for the root user, you didn't include place holder <username_1> in `cockroach sql --url='postgres://root@node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.user.crt&sslkey=certs/client.user.key&sslmode=verify-full'` and `cockroach sql --url='postgres://node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.user.crt&sslkey=certs/client.user.key&sslmode=verify-full'` both work but it's probably best to be explicit. I noticed it because my url did not include username for root so I just copied that for user2 and got tripped up, only after I explicitly added user@node then it worked `cockroach sql --url='postgres://user2@node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.user2.crt&sslkey=certs/client.user2.key&sslmode=verify-full'`. It is not a big deal but maybe for consistency sake I suggest to add `<username_1>@<hostname> to the first mention of url.

**Comment by Amruta-Ranade** [comment]
> I noticed a difference in the first and second url, for the root user, you didn't include place holder <username_1> in `cockroach sql --url='postgres://root@node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.user.crt&sslkey=certs/client.user.key&sslmode=verify-full'` and `cockroach sql --url='postgres://node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.user.crt&sslkey=certs/client.user.key&sslmode=verify-full'` both work but it's probably best to be explicit. I noticed it because my url did not include username for root so I just copied that for user2 and got tripped up, only after I explicitly added user@node then it worked `cockroach sql --url='postgres://user2@node.example.com:26257/?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.user2.crt&sslkey=certs/client.user2.key&sslmode=verify-full'`. It is not a big deal but maybe for consistency sake I suggest to add `<username_1>@ to the first mention of url.
> Otherwise LGTM!

I didn't add <username_1> for the first URL because it doesn't work 😕It gives the following error: `ERROR: password authentication failed for user maxroach
Failed running "sql"`

It works without the username because it assumes `root`, which I believe is a safer way than specifying root@<hostname>. Pls correct me if I am wrong.

**Comment by dbist** [comment]
it works with the following configuration file
```
[ req ]
prompt=no
distinguished_name = distinguished_name
req_extensions = extensions

[ distinguished_name ]
organizationName = ExampleCorp
commonName = user@example.com

[ extensions ]
subjectAltName = email:user@example.com,DNS:user.example.com,DNS:user,DNS:root
```

my user2 client.cnf file is like so:
```
[ req ]
prompt=no
distinguished_name = distinguished_name
req_extensions = extensions

[ distinguished_name ]
organizationName = ExampleCorp
commonName = user2@example.com

[ extensions ]
subjectAltName = email:user2@example.com,DNS:user2.example.com,DNS:user2
```

my command to start the cluster
`start-single-node --certs-dir=certs --cert-principal-map=node.example.com:node,user@example.com:root --background`

Again, it's a matter of preference but at least we know the reasoning was intentional.

**Pull request merged**
