### PR TITLE
Go and c++ txn sample improvements - no more inserts

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/163)

### CODE REVIEW

**Comment by jseldess** [comment]
*[_includes/app/txn-sample.cpp, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/163#-KE-_djqf9cSqIKXL_Ej:-KE-_djqf9cSqIKXL_Ek:-1697608629) ([raw file](https://github.com/cockroachdb/docs/blob/c2df3a98d003deefca29ab6fbf64b8af12efa460/_includes/app/txn-sample.cpp#L31)):*
Do we want to use the comment and function name that Spencer uses in his Go sample?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/163)*

**Comment by jseldess** [comment]
*[_includes/app/txn-sample.go, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/163#-KE-_ysWju84GLXvJQTB:-KE-_ysWju84GLXvJQTC:585958192) ([raw file](https://github.com/cockroachdb/docs/blob/c2df3a98d003deefca29ab6fbf64b8af12efa460/_includes/app/txn-sample.go#L23)):*
Can you remove the $?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/163)*

**Comment by jseldess** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/163#-:-KE-a4a4utMeFCIpWa_k:1417088721)*

**Comment by jseldess** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/163)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/app/txn-sample.cpp, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/163#-KE-_djqf9cSqIKXL_Ej:-KE1rkEWKXock_wNeTwM:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/c2df3a98d003deefca29ab6fbf64b8af12efa460/_includes/app/txn-sample.cpp#L31)):*
Done.

---

*[_includes/app/txn-sample.go, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/163#-KE-_ysWju84GLXvJQTB:-KE1s4l9uhFudPgML4q4:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/c2df3a98d003deefca29ab6fbf64b8af12efa460/_includes/app/txn-sample.go#L23)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/163)*

**Pull request merged**
