### PR TITLE
update EXPLAIN example output

### PR DESCRIPTION
**Pull request by taroface**
DOC-5262

- Updated several examples that became outdated due to this change. 
- Made a few opportunistic updates to example output that also seemed incorrect/out of date.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15810#-:-NJCWvd05cy2d80LXRi1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[`v22.2/trigram-indexes.md` line 237 at r1](https://reviewable.io/reviews/cockroachdb/docs/15810#-NJCWixbCVVn4iX0vNIn:-NJCWixbCVVn4iX0vNIo:b-x3pxg8) ([raw file](https://github.com/cockroachdb/docs/blob/13465aa1d1b6c2a90c5bab9e1fddfb60eca9e367/v22.2/trigram-indexes.md#L237)):*
> ```Markdown
>       │
>       └── • filter
>           │ estimated row count: 3,337
> ```

I think this line should be kept. I just tried this manually and do see it (after running `ANALYZE t`):
```
root@127.0.0.1:26257/movr> analyze t;
ANALYZE


Time: 46ms total (execution 46ms / network 0ms)

root@127.0.0.1:26257/movr> EXPLAIN SELECT w, similarity(w, 'word')                                                                                         FROM t                                                                                                                                                   WHERE w % 'word'                                                                                                                                         ORDER BY similarity DESC, w;
                                             info
-----------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • sort
  │ estimated row count: 3,337
  │ order: -similarity,+w
  │
  └── • render
      │
      └── • filter
          │ estimated row count: 3,337
          │ filter: w % 'word'
          │
          └── • scan
                estimated row count: 10,012 (100% of the table; stats collected 1 second ago)
                table: t@t_pkey
                spans: FULL SCAN
(17 rows)


Time: 1ms total (execution 1ms / network 0ms)
```

**Comment by taroface** [comment]
> I think this line should be kept. I just tried this manually and do see it (after running `ANALYZE t`):

TFTR! Fixed. It did not appear for me until a few minutes after I created and populated the table. The output also had `missing stats` instead of `estimated row count` until then. Is this a kind of behavior we should mention?

**Review by yuzefovich — COMMENTED** [review]
This is due to table statistics being collected asynchronously after some delay after the INSERTs. We might want to include a recommendation to run `ANALYZE t` in this example, but generally speaking it's a known behavior (not sure if it's documented somewhere).

Namely, we run the table statistics collection in the background and the table stats collection job is kicked off probabilistically  - looks like we do mention something along these lines [here](https://www.cockroachlabs.com/docs/v22.2/cost-based-optimizer#control-statistics-refresh-rate), so I'll leave it up to you to decide whether it's worth including `ANALYZE t` suggestion to get the consistent behavior with the examples.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15810#-:-NJCkver9LwAt3SYG7sB:b-pjo3lq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kathancox)

**Review by kathancox — APPROVED** [review]
LGTM!

**Pull request merged**
