### PR TITLE
Added detached option to IMPORT

### LINKED ISSUE #10085: importccl: support DETACHED option when running IMPORT
PR: https://github.com/cockroachdb/cockroach/pull/60442

From release notes:
> CockroachDB now supports the `DETACHED` option when running [`IMPORT`](../v21.1/import.html). The detached import will return `jobID` and the user can later use [`SHOW JOB`](../v21.1/show-jobs.html) to check the result of the detached import. This allows users to run `IMPORT` under explicit transactions with `DETACHED` option specified. [#60442][#60442] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by kathancox**
Updated import option table, warning, and added examples.

Closes #10085

### CODE REVIEW

**Review by Elliebababa — APPROVED** [review]

**Review by lnhsingh — COMMENTED** [review]
Nice job! Two small nits, but once those are fixed, :lgtm: !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392#-:-MYqA-VF1fHzY6wvSCIl:bi96q33)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox)

___
*[v21.1/import.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq97wxBO-u8zUX4Rvn:-MYq97wxBO-u8zUX4Rvo:b2bhr55) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L21)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> `IMPORT` cannot be used within a [rolling upgrade](upgrade-cockroach-version.html). `IMPORT` can be used in a [transaction](transactions.html) only when the `detached` option is specified, see the [Examples](#examples) section below.
> ```

I think you can remove the second sentence from this warning-- I'm not sure need to talk about transactions in this warning now, since you CAN do it.
___
*[v21.1/import.md, line 112 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq9duq65L4sbD2S8Ej:-MYq9duq65L4sbD2S8Ek:b-5yvvs3) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L112)):*
> ```Markdown
> 
> 
> ```

I know this was existing already, but let's remove this commented out row.

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox and @lnhsingh)

___
*[v21.1/import.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq97wxBO-u8zUX4Rvn:-MYqBnC9-5eTEvxIPAB6:b-1ttnpb) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think you can remove the second sentence from this warning-- I'm not sure need to talk about transactions in this warning now, since you CAN do it.
</blockquote></details>

I take a look at the doc of `BACKUP`, 
 since they are alike in terms of `detached` within a transaction. https://www.cockroachlabs.com/docs/v20.2/backup.html . It still writes cannot `The BACKUP statement cannot be used within a transaction.` in a NOTE box instead of a WARNING BOX. I think we can keep `BACKUP` and `IMPORT` detached alike. Maybe moving "`IMPORT` can be used in a [transaction](transactions.html) only when the `detached` option is specified, see the [Examples](#examples) section below." to a NOTE box?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Elliebababa and @kathancox)

___
*[v21.1/import.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq97wxBO-u8zUX4Rvn:-MYqHhSk0jyT4TGmdjLY:bfgvyj7) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L21)):*
<details><summary><i>Previously, Elliebababa wrote…</i></summary><blockquote>

I take a look at the doc of `BACKUP`, 
 since they are alike in terms of `detached` within a transaction. https://www.cockroachlabs.com/docs/v20.2/backup.html . It still writes cannot `The BACKUP statement cannot be used within a transaction.` in a NOTE box instead of a WARNING BOX. I think we can keep `BACKUP` and `IMPORT` detached alike. Maybe moving "`IMPORT` can be used in a [transaction](transactions.html) only when the `detached` option is specified, see the [Examples](#examples) section below." to a NOTE box?
</blockquote></details>

You're right, and actually this is an update that wasn't made in v20.2, even though it should be. 

The note that Ellie is pointing out in v20.2 should be removed since we introduced the `DETACHED` option in v20.2. Additionally, we probably want to add "To run a backup within a transaction, use the `DETACHED` option." to the description in the table.

Once this note is removed, the `BACKUP` docs will be similar to the `IMPORT` docs.

One small nit that I'm realizing too: we say `DETACHED` (all caps) in the `BACKUP` docs, but `detached` (lowercase) in the `IMPORT` docs. Which do we want to use (since it should be consistent across both docs)? @elliebababa, do you have an opinion on if the option name should be all caps or not?

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox and @lnhsingh)

___
*[v21.1/import.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq97wxBO-u8zUX4Rvn:-MYqeAvW1RvKgqMeMvWO:b-vqhutj) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

You're right, and actually this is an update that wasn't made in v20.2, even though it should be. 

The note that Ellie is pointing out in v20.2 should be removed since we introduced the `DETACHED` option in v20.2. Additionally, we probably want to add "To run a backup within a transaction, use the `DETACHED` option." to the description in the table.

Once this note is removed, the `BACKUP` docs will be similar to the `IMPORT` docs.

One small nit that I'm realizing too: we say `DETACHED` (all caps) in the `BACKUP` docs, but `detached` (lowercase) in the `IMPORT` docs. Which do we want to use (since it should be consistent across both docs)? @elliebababa, do you have an opinion on if the option name should be all caps or not?
</blockquote></details>

Emm I might have missed some context for why we changed detached (v20.2 doc) to DETACHED(v21.1 doc) ? 
But also in v21.1 Backup doc, not all the `detached` are caps.  I could not see why this changing happening... To my knowledge, both `DETACHED` and `detached` are valid syntax.

**Review by lnhsingh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Elliebababa and @kathancox)

___
*[v21.1/import.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq97wxBO-u8zUX4Rvn:-MYqitjg45z7ghthsu8Y:b-mwgkx2) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L21)):*
<details><summary><i>Previously, Elliebababa wrote…</i></summary><blockquote>

Emm I might have missed some context for why we changed detached (v20.2 doc) to DETACHED(v21.1 doc) ? 
But also in v21.1 Backup doc, not all the `detached` are caps.  I could not see why this changing happening... To my knowledge, both `DETACHED` and `detached` are valid syntax.

</blockquote></details>

Yep, they are both valid syntax, but whichever syntax we choose, we should have it be consistent across our docs

**Review by Elliebababa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox and @lnhsingh)

___
*[v21.1/import.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/10392#-MYq97wxBO-u8zUX4Rvn:-MYqjzzi-TY4nAA-51P4:bwxi2rb) ([raw file](https://github.com/cockroachdb/docs/blob/0e4a6b8dedccf589d75d64b9d79d4dc32e884442/v21.1/import.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Yep, they are both valid syntax, but whichever syntax we choose, we should have it be consistent across our docs
</blockquote></details>

Yep. Then let's have them all caps.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10392#-:-MYty2SR0nrLbrMBbP9g:b593w5u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kathancox and @lnhsingh)

**Pull request merged**
