### PR TITLE
Add redirects from /docs/training to docs/training/v1.1

### PR DESCRIPTION
**Pull request by jseldess**

### CODE REVIEW

**Comment by jseldess** [comment]
TFTR, @couchand. I'm going to wait until after today's training wraps up before merging.

**Comment by couchand** [comment]
@jseldess should this be live now?  it's still seems to not be working...

**Comment by jseldess** [comment]
Yes, it's live and working for me. Heading to office now. Maybe you can show me in person?

**Comment by jseldess** [comment]
Btw, we weren't properly hiding these pages from search crawlers. I fixed that just this morning with https://github.com/cockroachdb/docs/pull/2531.

**Pull request merged**
