### PR TITLE
adding expand collapse for step details

### PR DESCRIPTION
**Pull request by jseldess**
Keeping the **Start a Local Cluster** page as tight as possible by adding css/html to expand/collapse details after each step.

### CODE REVIEW

**Comment by jseldess** [comment]
Chatting with Spencer about refashioning this doc a bit, breaking it into two pages:
- First page called something like "Start Your First Cluster", walking through steps to setup an insecure, multi-node local cluster.
- Second page called something like "Secure Your First Cluster", walking through stoping cluster, creating certs, and restarting cluster securely.  

Will work on that.

**Comment by spencerkimball** [comment]
"Start a Cluster" sounds better than "Start Your First Cluster". Also, "Secure a Cluster".

**Comment by jseldess** [comment]
@spencerkimball, I broke **Start a Local Cluster** into two pages:
- [Start a Cluster](http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/start-a-local-cluster.html)
- [Secure a Cluster](http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/secure-a-cluster.html)

Please let me know what you think. 

Essentially, the commands on the first page can be copy/pasted into the terminal to start a 3-node insecure cluster, do some sql in the shell, and call up the admin ui. The commands on the second page can be copy/pasted to shut down the nodes, generate certs, restart the nodes, do more sql in the shell, and look at the admin ui again.

**Comment by spencerkimball** [comment]
LGTM

**Pull request merged**
