### PR TITLE
Change download links for SQL shells to archives/tarballs

### PR DESCRIPTION
**Pull request by nickvigilante**
Informs #14814

### CODE REVIEW

**Comment by rail** [comment]
The tarballs are up and we can proceed with this PR

**Comment by stbof** [comment]
The table is really wide and there are some inconsistencies in the labels. Also, do we really need Precompiled if it's already labeled as a binary? How about:

64-bit Binary (Full)     Full Binary SHA256     64-bit Binary (SQL shell)    SQL Shell Binary SHA256

**Comment by nickvigilante** [comment]
@stbof There may be subsequent CSS changes that need to be made on tables that we can address in a separate JIRA. For now, let me know how this looks.

**Review by stbof — APPROVED** [review]
So much better!

**Pull request merged**
