### PR TITLE
Remove info about restoring CC clusters/db/tables

### LINKED ISSUE #8911: Remove info about requesting a backup path from CC docs
Related to: https://github.com/cockroachlabs/support/issues/675

This is an interim fix until the restore modal is available.

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #8911.

### CODE REVIEW

**Review by mwang1026 — APPROVED** [review]
LGTM!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8917#-:-MMGfSTUBVPwP5eLVGO9:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/backups-page.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/8917#-MMHj44oDBBlY1QR4vP-:-MMHj44p2y6bEMdTwb95:b-9fkkso) ([raw file](https://github.com/cockroachdb/docs/blob/694ff913d08e92710aa173bd6708f27063451218/cockroachcloud/backups-page.md#L16)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> Currently, you cannot access the backups that Cockroach Labs runs to restore your data. In the future, you will be able to restore databases and tables from the CockroachCloud Console.
> ```

Does not being able to "access the backups" mean that your backup data can't be used to restore your data? Or that you have to contact Support in order to do this? Would be good to clarify that here.

Also, is it possible to be more specific than "In the future", e.g.,  In an upcoming release, or in the near future? Or even link a public GitHub issue?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[cockroachcloud/backups-page.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/8917#-MMHj44oDBBlY1QR4vP-:-MMHqFQ7E07cOgclStI-:bpohm4c) ([raw file](https://github.com/cockroachdb/docs/blob/694ff913d08e92710aa173bd6708f27063451218/cockroachcloud/backups-page.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Does not being able to "access the backups" mean that your backup data can't be used to restore your data? Or that you have to contact Support in order to do this? Would be good to clarify that here.

Also, is it possible to be more specific than "In the future", e.g.,  In an upcoming release, or in the near future? Or even link a public GitHub issue?
</blockquote></details>

Michael mentioned that we can help users in a "true emergency" - I moved the "contact support" sentence from the second paragraph up to here.

re: "In the future" - it's happening really soon but I don't want to promise a timeframe and I unfortunately don't think I can link to a tracking issue since CC work is in Jira (and isn't open source). I'm banking on this being a placeholder for only another couple of weeks.

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @mwang1026)

___
*[cockroachcloud/backups-page.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/8917#-MMHj44oDBBlY1QR4vP-:-MMHsSwz2Mj77A4-TZBg:b-a7ljwq) ([raw file](https://github.com/cockroachdb/docs/blob/694ff913d08e92710aa173bd6708f27063451218/cockroachcloud/backups-page.md#L16)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Michael mentioned that we can help users in a "true emergency" - I moved the "contact support" sentence from the second paragraph up to here.

re: "In the future" - it's happening really soon but I don't want to promise a timeframe and I unfortunately don't think I can link to a tracking issue since CC work is in Jira (and isn't open source). I'm banking on this being a placeholder for only another couple of weeks. 
</blockquote></details>

Makes sense to me!

**Comment by lnhsingh** [comment]
TFTRs!

**Pull request merged**
