### PR TITLE
Add the encode JSON null value option to cdc docs

### PR DESCRIPTION
**Pull request by kathancox**
Fixes DOC-10529

This PR adds the `encode_json_value_null_as_object` option to the cdc docs:

- `CREATE CHANGEFEED` option table
- Example to the Changefeed Messages page
- Update link to release note

For rendered previews:

[Options table](https://deploy-preview-18718--cockroachdb-docs.netlify.app/docs/v24.2/create-changefeed.html#encode-json-value-null-as-object)
[Changefeed Messages example](https://deploy-preview-18718--cockroachdb-docs.netlify.app/docs/v24.2/changefeed-messages.html#json)

### CODE REVIEW

**Review by asg0451 — APPROVED** [review]
i only reviewed the rendered previews but those look great!

**Comment by kathancox** [comment]
> i only reviewed the rendered previews but those look great!

Great! Thank you for the review.

**Review by rmloveland — APPROVED** [review]
LGTM!

**Comment by kathancox** [comment]
TFTRs!

**Pull request merged**
