### PR TITLE
Added missing parameter to table for create schedule for backup

### PR DESCRIPTION
**Pull request by katmayb**
Fixes [DOC-4990](https://cockroachlabs.atlassian.net/browse/DOC-4990)

Quick fix to add the missing `targets` parameter to the parameters table for `CREATE SCHEDULE FOR BACKUP`

### CODE REVIEW

**Comment by livlobo** [comment]
@kathancox  - can you add the deploy preview URL? (or teach me how to generate it?)

**Comment by kathancox** [comment]
Sure, here is the page for this: https://deploy-preview-14523--cockroachdb-docs.netlify.app/docs/stable/create-schedule-for-backup.html

You'll find the deploy preview link above our comments in the Netlify Preview table on this PR. That will take you to the docs home site, which you can then navigate to the page you want to see. 

I do try and add the link as a courtesy, but sometimes there are several pages, sorry I forgot for this one!

**Review by livlobo — APPROVED** [review]
Thanks Kathryn! Looks good. 

PS: Thanks for the note on the deploy preview. I was using that generic link, but wsan't sure if there was a magical way to get to the page directly. No worries at all, I can navigate to it going forward! :)

**Review by andf-crl — APPROVED** [review]
LGTM! Left an optional layout suggestion.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14523#-:-N71U88V35dNu8lUAvCb:b-3xh3zy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @kathancox)

___
*[`v21.2/create-schedule-for-backup.md` line 44 at r1](https://reviewable.io/reviews/cockroachdb/docs/14523#-N71TqGd0314ZD6NxrbF:-N71T3qe21Dl9sXojv_B:badk2v4) ([raw file](https://github.com/cockroachdb/docs/blob/9676cdb1fdf2a47f2461bc59f2598536e3594f81/v21.2/create-schedule-for-backup.md#L44)):*
> ```Markdown
> `IF NOT EXISTS`                         | **New in v21.2:** Use to specify that a scheduled backup should not be created if the [`label`](#label) already exists. Produces an error if the schedule label already exists, or if the `label` is not specified.
> <a name="label"></a>`label`             | The name used to identify the backup schedule. This is optional and does not need to be unique. If not provided, the schedule will be assigned the name `BACKUP`.
> `targets`                               | The targets you want to back up: [cluster](#create-a-scheduled-backup-for-a-cluster), [database](#create-a-scheduled-backup-for-a-database) `DATABASE <database_name> [, ...]`, or [table](#create-a-scheduled-backup-for-a-table) `TABLE <table_pattern> [, ...]`.
> ```

nit: consider listing these three options as list elements, with cluster also getting example code:

The targets you want to back up:
- [Cluster](): `[ ] `
- [Database](): `DATABASE <database_name> [, ...]`
- [Table](): `TABLE <table_pattern> [, ...]`

**Pull request merged**
