### PR TITLE
Hibernate Spatial, RGeo/RGeo-ActiveRecord, and GeoDjango support

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/docs/issues/10026.
Fixes https://github.com/cockroachdb/docs/issues/9393.

### CODE REVIEW

**Review by vy-ton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[_includes/v21.1/misc/tooling.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeL9O_8k0UgcCA3fjT:-MWeL9O_8k0UgcCA3fjU:b-cokbn0) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/_includes/v21.1/misc/tooling.md#L31)):*
> ```Markdown
> |----------+-----+---------------------+---------------|
> | Go | [GORM](build-a-go-app-with-cockroachdb-gorm.html)<hr>[upper/db](build-a-go-app-with-cockroachdb-upperdb.html) | [1.9.11](https://github.com/jinzhu/gorm/releases)<hr>[v4](https://github.com/upper/db/releases) | Full<hr>Full |
> | Java | [Hibernate](build-a-java-app-with-cockroachdb-hibernate.html)<br>(including [Hibernate Spatial](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#spatial))<hr>[jOOQ](build-a-java-app-with-cockroachdb-jooq.html)<hr>[MyBatis](build-a-spring-app-with-cockroachdb-mybatis.html) | [5.4.19 and higher](https://hibernate.org/orm/releases/)<br><br><hr>[3.13.2](https://www.jooq.org/download/versions) (must be 3.13.0 or higher)<hr>[3.5.5 and higher](https://mybatis.org/mybatis-3/) | Full<br><br><hr>Full<hr>Full |
> ```

`5.4.19` is the first version that introduced CRDB support

We now test/recommend `5.4.30`. How should this be conveyed? 
___
*[_includes/v21.1/misc/tooling.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeLnQG65txVmq2Bj7n:-MWeLnQG65txVmq2Bj7o:b9waftk) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/_includes/v21.1/misc/tooling.md#L33)):*
> ```Markdown
> | Java | [Hibernate](build-a-java-app-with-cockroachdb-hibernate.html)<br>(including [Hibernate Spatial](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#spatial))<hr>[jOOQ](build-a-java-app-with-cockroachdb-jooq.html)<hr>[MyBatis](build-a-spring-app-with-cockroachdb-mybatis.html) | [5.4.19 and higher](https://hibernate.org/orm/releases/)<br><br><hr>[3.13.2](https://www.jooq.org/download/versions) (must be 3.13.0 or higher)<hr>[3.5.5 and higher](https://mybatis.org/mybatis-3/) | Full<br><br><hr>Full<hr>Full |
> | JavaScript/TypeScript | [Sequelize](build-a-nodejs-app-with-cockroachdb-sequelize.html)<br><br><hr>[TypeORM](https://typeorm.io/#/) | [sequelize 5.21.9](https://www.npmjs.com/package/sequelize)<br>[sequelize-cockroachdb 1.1.0](https://www.npmjs.com/package/sequelize-cockroachdb)<hr>[0.2.24](https://www.npmjs.com/package/typeorm) | Beta<br><br><hr>Full |
> | Ruby | [ActiveRecord](build-a-ruby-app-with-cockroachdb-activerecord.html)<br>[RGeo](https://github.com/rgeo/rgeo)/[RGeo-ActiveRecord](https://github.com/rgeo/rgeo-activerecord) | [activerecord 5.2](https://rubygems.org/gems/activerecord/versions)<br>[activerecord-cockroachdb-adpater 5.2.2](https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions)<hr>[activerecord 6.0](https://rubygems.org/gems/activerecord/versions)<br>[activerecord-cockroachdb-adpater 6.0.0beta3](https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions) | Full<br><br><hr>Beta |
> ```

Let's do just an `RGeo` link to our [adapter README](https://github.com/cockroachdb/activerecord-cockroachdb-adapter#working-with-spatial-data), which already talks about RGeo and RGeo-ActiveRecord
___
*[v21.1/spatial-data.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeJ2XO7CACKKh-7Cku:-MWeJ2XO7CACKKh-7Ckv:brxlic3) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L30)):*
> ```Markdown
> For a list of other known limitations, see [Known Limitations](known-limitations.html#spatial-support-limitations).
> 
> ### ORM compatibility
> ```

[django-cockroachdb 3.1.3](https://pypi.org/project/django-cockroachdb/3.1.3/) now supports spatial as well. The linked release notes have installation notes.
___
*[v21.1/spatial-data.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeKpEC8kt97v1LqIIR:-MWeKpED3NyYRe6bdq1k:b-osa89g) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L30)):*
> ```Markdown
> For a list of other known limitations, see [Known Limitations](known-limitations.html#spatial-support-limitations).
> 
> ### ORM compatibility
> ```

Can we link to this in the `Spatial Features Overview` page?
___
*[v21.1/spatial-data.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeKEuP6oF7sFuVFICc:-MWeKEuP6oF7sFuVFICd:b-gzw437) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L32)):*
> ```Markdown
> ### ORM compatibility
> 
> CockroachDB's spatial support is limited. As a result, not all PostGIS-compatible client libraries are compatible with CockroachDB's spatial features.
> ```

`ORM spatial support with CockroachDB is limited to the following frameworks`? or swap with the sentence below `The following ORM...`

Right now, the first sentence reads as spatial support itself if limited
___
*[v21.1/spatial-data.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeJLNN8iGCAc4DEqOl:-MWeJLNN8iGCAc4DEqOm:b-b5ab9t) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L36)):*
> ```Markdown
> The following ORM spatial libraries are fully compatible with CockroachDB's spatial features:
> 
> - [Hibernate Spatial](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#spatial)
> ```

Use URL with current version, https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#spatial?
___
*[v21.1/spatial-data.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeK7CL4p7eK8ZV-1YY:-MWeK7CL4p7eK8ZV-1YZ:b-dkhvru) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L42)):*
> ```Markdown
> - [RGeo/RGeo-ActiveRecord](https://github.com/rgeo/rgeo-activerecord)
> 
>     CockroachDB's ActiveRecord adapter ([`activerecord-cockroachdb-adapter`](https://github.com/cockroachdb/activerecord-cockroachdb-adapter)) uses [RGeo](https://github.com/rgeo/rgeo) and [RGeo-ActiveRecord](https://github.com/rgeo/rgeo-activerecord) for spatial support with ActiveRecord v5.2.2+ and v6.0.0+. For information about using CockroachDB spatial features with ActiveRecord, see the [`activerecord-cockroachdb-adapter` README](https://github.com/cockroachdb/activerecord-cockroachdb-adapter#working-with-spatial-data).
> ```

For 6.0.0, they need to use v6.0.0beta3+

**Review by vy-ton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/spatial-data.md, line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeK7CL4p7eK8ZV-1YY:-MWeMH_821q0axbMW0xd:bg7okcp) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L42)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

For 6.0.0, they need to use v6.0.0beta3+
</blockquote></details>

We plan to have a GA 6.0.0 version soon so leaving this should be fine

**Review by ericharmeling — COMMENTED** [review]
TFTR, @vy-ton !

I think I got to all your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10034#-:-MWyV9nZ6qyK9wXLXufs:b-rez6w0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland and @vy-ton)

___
*[_includes/v21.1/misc/tooling.md, line 31 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeL9O_8k0UgcCA3fjT:-MWyCbkv4tO95mHdFGcJ:b-5kbf7c) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/_includes/v21.1/misc/tooling.md#L31)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

`5.4.19` is the first version that introduced CRDB support

We now test/recommend `5.4.30`. How should this be conveyed? 
</blockquote></details>

Updated.

Sometime in the future, we'll want to remote-include the version numbers from the testing configurations. (https://github.com/cockroachdb/docs/issues/10195)
___
*[_includes/v21.1/misc/tooling.md, line 33 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeLnQG65txVmq2Bj7n:-MWyDc9qB97w8kjUyJ_9:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/_includes/v21.1/misc/tooling.md#L33)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

Let's do just an `RGeo` link to our [adapter README](https://github.com/cockroachdb/activerecord-cockroachdb-adapter#working-with-spatial-data), which already talks about RGeo and RGeo-ActiveRecord
</blockquote></details>

Done
___
*[v21.1/spatial-data.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeJ2XO7CACKKh-7Cku:-MWyIDTmEnkcstCD9f_y:bbkycz7) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L30)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

[django-cockroachdb 3.1.3](https://pypi.org/project/django-cockroachdb/3.1.3/) now supports spatial as well. The linked release notes have installation notes.
</blockquote></details>

Added here and to the tooling tables.
___
*[v21.1/spatial-data.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeKpEC8kt97v1LqIIR:-MWyMPEd-NV6D6ehiQ8u:bzht3nu) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L30)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

Can we link to this in the `Spatial Features Overview` page?
</blockquote></details>

I added a link... but FWIW, it doesn't much sense to link to "Working with Spatial Data", and then link to a level-3 header of that same page (i.e., "ORM compatibility"), and not link to other level-2 headers (i.e., "Supported Data Types" and "Performance", or even "Compatibility").

@rmloveland Maybe in the future, as more ORM libraries get added, it might make sense for us to add another reference page ("PostGIS Compatibility" or something). That page might facilitate some other docs work (e.g., https://github.com/cockroachdb/docs/issues/8995 and https://github.com/cockroachdb/docs/issues/8780).
___
*[v21.1/spatial-data.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeKEuP6oF7sFuVFICc:-MWyERXU7mxoPuXm2U26:b-alpkf) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L32)):*
> Right now, the first sentence reads as spatial support itself if limited

That's intentional. CRDB's spatial support is pretty limited, as spelled out in the first few sentences of the "Compatibility" section (also see https://www.cockroachlabs.com/docs/stable/known-limitations.html#spatial-support-limitations). IIUC, it's as direct a result of the limitations to our spatial support that CRDB is not directly compatible with most PostGIS libraries, unless there is some kind of adapter.

I updated the language to make this a little more explicit.
___
*[v21.1/spatial-data.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeJLNN8iGCAc4DEqOl:-MWyNBCYDcL0_ETPB3fa:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L36)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

Use URL with current version, https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#spatial?
</blockquote></details>

Done.

**Review by rmloveland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans and @vy-ton)

___
*[v21.1/spatial-data.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/docs/10034#-MWeKpEC8kt97v1LqIIR:-MWzN7zj8rbi_A9nACsT:bnca0un) ([raw file](https://github.com/cockroachdb/docs/blob/0ef550b2e0473208a31ab022dc29eec31c19e99e/v21.1/spatial-data.md#L30)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I added a link... but FWIW, it doesn't much sense to link to "Working with Spatial Data", and then link to a level-3 header of that same page (i.e., "ORM compatibility"), and not link to other level-2 headers (i.e., "Supported Data Types" and "Performance", or even "Compatibility").

@rmloveland Maybe in the future, as more ORM libraries get added, it might make sense for us to add another reference page ("PostGIS Compatibility" or something). That page might facilitate some other docs work (e.g., https://github.com/cockroachdb/docs/issues/8995 and https://github.com/cockroachdb/docs/issues/8780).
</blockquote></details>

Yes, that sounds like a plan to me Eric!

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
