### PR TITLE
CC Release Notes June 2021

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes: https://cockroachlabs.atlassian.net/browse/CC-3666

### CODE REVIEW

**Comment by gemma-shay** [comment]
@j-low Is it okay to have multi-region in this release notes (to be published on 6/7)?
Also, do you mind checking over the bullet about the AWS endpoint update? Wasn't sure what exactly changed in the UI.

**Review by j-low — APPROVED** [review]
LGTM!  I think the change re: AWS is hard to sum up in a sentence but your version works well.  I think as long as we have some guidance in the docs towards the "Accept connection" option in the row's action menu in the connections list then we're good.

**Review by ianjevans — APPROVED** [review]

**Comment by gemma-shay** [comment]
cc: @kannanlakshmi for optional review

**Review by kannanlakshmi — COMMENTED** [review]
Are the Statements and sessions pages rolled out broadly to all orgs without feature flags? Tommy would know. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10687#-:-MbIOJqSC0FYqZZNnUu2:bniduwm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/cockroachcloud-06072021.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/10687#-MbINxTf4YiMwCeBtY0Y:-MbINxTf4YiMwCeBtY0Z:bb80mjz) ([raw file](https://github.com/cockroachdb/docs/blob/ea51786a920312a63b383157080c477b8cd79340/releases/cockroachcloud-06072021.md#L21)):*
> ```Markdown
> - Previously, users were getting stuck during the verification step of creating an [AWS PrivateLink](../cockroachcloud/network-authorization.html#aws-privatelink) endpoint. Now, users can enter the verification step of the **Add Endpoint Connection** dialog with an incomplete connection endpoint ID preset.
> - Added a **Cloud** column to the **Clusters** page so users can see which cloud provider any cluster is using without having to click through to the **Cluster Overview** page.
> - The maximum number of nodes was raised to 50 nodes per region and 150 nodes per cluster.
> ```

Nit: max number of nodes in a cluster created via the Console (we can support more than that just not via UI)

**Comment by gemma-shay** [comment]
@kannanlakshmi Just checked with Tommy, they are rolled out to all orgs. Good to merge?

**Comment by kannanlakshmi** [comment]
If Statements and sessions pages are rolled out to all orgs, do we want to call them out in the release notes? I don't believe we have called this out in the past, right @thtruo ?

**Comment by thtruo** [comment]
That's correct @kannanlakshmi we haven't called out Statements/Sessions in past release notes. It would be great to call these out in the June release note. cc @gemma-shay

**Comment by kannanlakshmi** [comment]
Thanks @thtruo 
@gemma-shay it seems like we need a better system for generating these release notes since the observability stuff is not making it to this list. I just happened to know about statements pages, otherwise it would have been a big miss. 

For now, let's make sure to add Tommy as a reviewer for all release notes since he is aware of all the releases as it pertains to Observability. You can also add Emily and myself. Thanks! 

@thtruo I know PMM team has similar concerns of not knowing when things are released to CC, might be a process change on our end where we ensure docs and PMM are up to date of all monthly releases for CC related items across areas. It could just be part of go to market.

**Comment by gemma-shay** [comment]
@kannanlakshmi @thtruo Sorry, I thought we were talking about whether to include the last bullet under **Console changes** saying the Statements and Sessions pages were updated. Should that be changed to say they were released to all dedicated users? https://deploy-preview-10687--cockroachdb-docs.netlify.app/docs/releases/cockroachcloud-06072021.html#console-changes

The release notes generator is definitely missing stuff, last month it didn't pick up on github auth.

**Comment by thtruo** [comment]
@kannanlakshmi ack - noted the go to market process for raising awareness to Observability features shipped.

> Should that be changed to say they were released to all dedicated users?
@gemma-shay Yeah I'd say so :)

**Review by thtruo — APPROVED** [review]
LGTM!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10687#-:-MbbjclP9bonW1pDnXiw:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

**Pull request merged**
