### PR TITLE
add Vectorized info to statements page

### LINKED ISSUE #7872: ui,sql: add Vectorized info to statements page
PR: https://github.com/cockroachdb/cockroach/pull/50255

From release notes:
> The `Statements` page now shows if the vectorized execution engine is used or not. [#50255][#50255] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by gemma-shay**
Add Vectorized execution info to Statements page and update the Statement Details Page screenshot.

Closes #7872.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9458)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @taroface)

___
*[v20.2/ui-statements-page.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/9458#-MRfUTw7DrBzARZPXfkI:-MRfUTw7DrBzARZPXfkJ:b-lz1rhx) ([raw file](https://github.com/cockroachdb/docs/blob/08327dc14d5556f3a30912807cedb40f4e92b5ea/v20.2/ui-statements-page.md#L102)):*
> ```Markdown
> - **Transaction Type** displays the type of transaction (implicit or explicit).
> - **Distributed execution?** indicates whether the execution was distributed.
> - **Vectorized execution?** indicates whether the transaction used the vectorized execution engine.
> ```

nit: I'd use wording similar to others around it, something like "indicates whether the execution used the vectorized engine".

Saying that "the transaction used the vectorized" engine is somewhat technically incorrect because a transaction can contain multiple statements, and each of those statements might or might not use the vectorized engine.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9458#-:-MRfvJid5EvV4Jwz9HLf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @taroface)

**Review by taroface — CHANGES_REQUESTED** [review]
Big apologies for seeing this so late! I have 1 request.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9458#-:-MSV0EdN4hB1kLRNS5Ls:b-62jy1s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @yuzefovich)

___
*[v20.2/ui-statements-page.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/docs/9458#-MRfUTw7DrBzARZPXfkI:-MSV07fh0tWl26UzCh-W:b-ot3mbm) ([raw file](https://github.com/cockroachdb/docs/blob/08327dc14d5556f3a30912807cedb40f4e92b5ea/v20.2/ui-statements-page.md#L102)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd use wording similar to others around it, something like "indicates whether the execution used the vectorized engine".

Saying that "the transaction used the vectorized" engine is somewhat technically incorrect because a transaction can contain multiple statements, and each of those statements might or might not use the vectorized engine.
</blockquote></details>

I'd link `vectorized execution engine` to https://www.cockroachlabs.com/docs/v20.2/vectorized-execution.html
___
*[v21.1/ui-statements-page.md, line 102 at r2](https://reviewable.io/reviews/cockroachdb/docs/9458#-MSV0Bi09RnXHF2mblA8:-MSV0Bi1-WJ_QrBijiY2:b2nreh6) ([raw file](https://github.com/cockroachdb/docs/blob/ef84356cfe1591b73a225fc602a571629cb71af9/v21.1/ui-statements-page.md#L102)):*
> ```Markdown
> - **Transaction Type** displays the type of transaction (implicit or explicit).
> - **Distributed execution?** indicates whether the execution was distributed.
> - **Vectorized execution?** indicates whether the execution used the vectorized execution engine.
> ```

Same as above.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9458)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[v21.1/ui-statements-page.md, line 102 at r2](https://reviewable.io/reviews/cockroachdb/docs/9458#-MSV0Bi09RnXHF2mblA8:-MSZUx2P75xR7CLkIqM6:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ef84356cfe1591b73a225fc602a571629cb71af9/v21.1/ui-statements-page.md#L102)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by taroface — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9458#-:-MSZW5eX2LV0JaA6uPJT:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @taroface and @yuzefovich)

**Pull request merged**
