### PR TITLE
Add CASCADE to TRUNCATE docs

### LINKED ISSUE #655: sql: Implement CASCADE for TRUNCATE
PR: https://github.com/cockroachdb/cockroach/pull/9240

### LINKED ISSUE #9240: Start a Local Cluster (Insecure) Doc Update
Re: [Start a Local Cluster (Insecure)](https://cockroachlabs.com/docs//v20.2/start-a-local-cluster.html)

## Issue Description

The instructions reference the ```cockroach quit``` command, which is [deprecated](https://www.cockroachlabs.com/docs/dev/cockroach-quit.html).
Running this command produces the following message:

```
Command "quit" is deprecated, see 'cockroach node drain' instead to drain a 
server without terminating the server process (which can in turn be done using 
an orchestration layer or a process manager, or by sending a termination signal
directly).
```

## Suggested Resolution 

First, for these instructions, decide whether draining the server process before terminating the server process is necessary.  The [docs](https://www.cockroachlabs.com/docs/dev/cockroach-quit.html) seem to indicate that, when shutting down a node, draining happens automatically without it being necessary to manually drain the server process first.

Second, for these instructions, decide the best way to stop the server process.  Since, in these instructions, the server process was started from the command line, it seems appropriate to use the ```kill``` command to stop the server process.   That is the approach suggested below, but the doc discusses other approaches, such as using a process manager.

If the manual drain is necessary, then replace references to ```cockroach quit``` with the sequence: 
1. ```cockroach drain```
1. determine the process ID, presumably using the ```ps``` command
1. issue the ```kill``` command for the process ID determined above

If the manual drain is not necessary, then replace references to ```cockroach quit``` with just steps #&#x2060;2 and #&#x2060;3 above.

Screen shots:

cockroach quit command is deprecated 2020-12-23

cockroach quit command is deprecated 2020-12-23b

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #655 

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1297)

### CODE REVIEW

**Comment by sploiselle** [comment]
David's feedback from my PR:
<hr/>
:lgtm:

Huh, I didn't know we supported that. Does it... 

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[truncate.md, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1260#-KhYAqx5CVUFZYaF4HpZ:-KhYAqx5CVUFZYaF4Hp_:begnpz9) ([raw file](https://github.com/cockroachdb/docs/blob/2fa8e2ad99d1df3138a2a1e0c3d102abcb8db5e4/truncate.md#L25)):*
> ```Markdown
>  `table_name` | The [`qualified_name`](sql-grammar.html#qualified_name) of the table you want to truncate. 
> `CASCADE` | Drop all objects (such as [constraints](constraints.html) and [views](views.html)) that depend on the table.<br><br>`CASCADE` does not list objects it drops, so should be used cautiously.
> `RESTRICT`    | _(Default)_ Do not truncate the table if any objects (such as [constraints](constraints.html) and [views](views.html)) depend on it.
> ```

 unless they are also being truncated in the same statement.

e.g. you *can* `TRUNCATE orders, products`, which is arguably safer than CASCADE since you're explicitly listing what you want truncated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1260#-:-KhYAVgTaY6Ls7Ezh02l:b-wfl8gj)*

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[truncate.md, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1297#-KhdOe5FROqTlxvnrDv-:-KhdOe5FROqTlxvnrDv0:bfsryfg) ([raw file](https://github.com/cockroachdb/docs/blob/b6a8d909302a160bd8e92a783899dee4445397b8/truncate.md#L25)):*
Also includes Views' dependencies. Here's what I wrote:

> Do not truncate the table if any objects (such as [constraints](constraints.html) and [views](views.html)) depend on it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1297)*

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[truncate.md, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1297#-KhdOe5FROqTlxvnrDv-:-KhdPD9bgAR2tvZmg5vV:bcwxi6d) ([raw file](https://github.com/cockroachdb/docs/blob/b6a8d909302a160bd8e92a783899dee4445397b8/truncate.md#L25)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Also includes Views' dependencies. Here's what I wrote:

> Do not truncate the table if any objects (such as [constraints](constraints.html) and [views](views.html)) depend on it
</blockquote></details>

Derp. I was wrong. Truncate doesn't care about Views.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1297)*

**Comment by jseldess** [comment]
Updated the examples to show truncating dependent tables both `CASCADE` as well as explicitly.

**Comment by dt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1297#-:-Khhf8Bu6JcWnKKajHVJ:bnfp4nl)*

**Pull request merged**
