### PR TITLE
Add transaction Rust sample

### PR DESCRIPTION
**Pull request by nvanbenschoten**
This sample uses the newly supported Rust driver, that now also
supports savepoints.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/326)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KIkpno_lo868SNwd2hB:598240995) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
> ```Rust
> 
> /// Runs op inside a transaction and retries it as needed.
> /// On non-retryable failures, the transaction is aborted and
> ```

aborted _and_ rolled back?

---

*[_includes/app/txn-sample.rs, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkq9lxw-1rBvshbGPb:-KIkq9lxw-1rBvshbGPc:-1772189581) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L9)):*
> ```Rust
> /// On non-retryable failures, the transaction is aborted and
> /// rolled back; on success, the transaction is committed.
> fn execute_txn<T, F>(conn: &Connection, mut op: F) -> Result<T>
> ```

why is `op` `mut`?

---

*[_includes/app/txn-sample.rs, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkquglx96HcqW66GOQ:-KIkquglx96HcqW66GOR:757914234) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L13)):*
> ```Rust
> {
>     let txn = try!(conn.transaction());
>     let res: Result<T>;
> ```

i think you can remove this, and make the loop below:
```rust
    loop {
        let sp = try!(txn.savepoint("cockroach_restart"));
        match op(&sp).and_then(|t| sp.commit().map(|_| t)) {
            Err(Error::Db(ref e)) if e.code == SqlState::SerializationFailure => continue,
            r => return r.and_then(|t| txn.commit().map(|_| t));,
        }
    }
    unreachable!() // not sure if you need this
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KIkweYI5xGeuo5MZl0K:-1358991559) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> aborted _and_ rolled back?
</details>
As opposed to what? The copy was taken from the C++ example for consistency by the way.

---

*[_includes/app/txn-sample.rs, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkq9lxw-1rBvshbGPb:-KIksyrFLZiW0TIXHExL:372268578) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L9)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why is `op` `mut`?
</details>
I get the compiler error 

```
src/main.rs:49:15: 49:17 error: cannot borrow immutable argument `op` as mutable
src/main.rs:49         match op(&sp).and_then(|t| sp.commit().map(|_| t)) {
                             ^~
```

when it's not. It might have to do with `FnMut`, I'm not 100% sure.

---

*[_includes/app/txn-sample.rs, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkquglx96HcqW66GOQ:-KIkvZ9bjvpJm1MDvJtL:2124349534) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think you can remove this, and make the loop below:
> ```rust
>     loop {
>         let sp = try!(txn.savepoint("cockroach_restart"));
>         match op(&sp).and_then(|t| sp.commit().map(|_| t)) {
>             Err(Error::Db(ref e)) if e.code == SqlState::SerializationFailure => continue,
>             r => return r.and_then(|t| txn.commit().map(|_| t));,
>         }
>     }
>     unreachable!() // not sure if you need this
> ```
</details>
Yeah I spent a while trying to find the best option for this. `txn.savepoint(...)` borrows `txn`, so we cant access it again in that scope. We'd get an error like `cannot move `txn` into closure because it is borrowed`. It's too bad `loops` can't [return values](https://github.com/rust-lang/rfcs/issues/961).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> #### Add transaction Rust sample
> 
> This sample uses the newly supported Rust driver, that now also
> 
> supports savepoints.
> 
> 
> 
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KIkzysA9ESKw3YehvaT:1664922472) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> As opposed to what? The copy was taken from the C++ example for consistency by the way.
</details>
it's redundant - one or the other would suffice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326#-:-KIl-50WIPoSOELsMC1S:1417088721)*

**Comment by jseldess** [comment]
*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KImdWF1oa0xXcG0vbaW:41274101) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> it's redundant - one or the other would suffice.
</details>
Tamir has a point. I'd say we go with just "...the transaction is aborted." Once this PR is merged, I'll update other comments accordingly while adding Rust to `build-a-test-app.d`. Will probably also want to update https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7J4ylrmY92hrIyENT:1207737171) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Tamir has a point. I'd say we go with just "...the transaction is aborted." Once this PR is merged, I'll update other comments accordingly while adding Rust to `build-a-test-app.d`. Will probably also want to update https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go.
</details>
I don't think there's any reason to remove "and rolled back". Maybe the terms are a little redundant, but they have different implications (see http://stackoverflow.com/questions/25339413/what-is-the-meaning-of-commit-and-abort-in-a-transaction). Extra explicitly, especially in a sample application, isn't bad. Also, in our code base, the aborted txn state != the rolled back txn state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7KZBubVUJInby6AHa:-911139805) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I don't think there's any reason to remove "and rolled back". Maybe the terms are a little redundant, but they have different implications (see http://stackoverflow.com/questions/25339413/what-is-the-meaning-of-commit-and-abort-in-a-transaction). Extra explicitly, especially in a sample application, isn't bad. Also, in our code base, the aborted txn state != the rolled back txn state.
</details>
None of this makes any sense. If you'd like to use that SO article's semantics, aborting _AND_ rolling back a transaction is not possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7KyS8T4Y_oASdqu9v:773204741) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> None of this makes any sense. If you'd like to use that SO article's semantics, aborting _AND_ rolling back a transaction is not possible.
</details>
The point is that the article discusses "aborting" in relation to "killing the current ongoing transaction" and "rolling back" in relation to "reverting to a previous stable state". On non-retryable failures, we do both. Why force the reader to imply one or the other?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7Lzu4rToJZAcvVxFX:425490123) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> The point is that the article discusses "aborting" in relation to "killing the current ongoing transaction" and "rolling back" in relation to "reverting to a previous stable state". On non-retryable failures, we do both. Why force the reader to imply one or the other?
</details>
What database implements "reverting to a previous stable state" without "killing the current ongoing transaction"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7MeBkZIJJ5-kEe5DD:1360472523) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> What database implements "reverting to a previous stable state" without "killing the current ongoing transaction"?
</details>
That's exactly what `ROLLBACK TO savepoint` does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7NHsWMxHz7jDbc1UF:343579760) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> That's exactly what `ROLLBACK TO savepoint` does.
</details>
No it doesn't - it does not roll back the **transaction** as this comment claims.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7Q6Yg0qHm4p4M3Uyl:1559983682) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> No it doesn't - it does not roll back the **transaction** as this comment claims.
</details>
Given our current [transaction retry scheme](https://www.cockroachlabs.com/docs/transactions.html#transaction-retries), that is what it does because the savepoint wraps the entire transaction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/app/txn-sample.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/326#-KIkpno_lo868SNwd2hA:-KJ7SK-loWFu4EyxMSVo:-1901135891) ([raw file](https://github.com/cockroachdb/docs/blob/2a6dc28a8ca3f76be9797443ad9f6d10622659b4/_includes/app/txn-sample.rs#L7)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Given our current [transaction retry scheme](https://www.cockroachlabs.com/docs/transactions.html#transaction-retries), that is what it does because the savepoint wraps the entire transaction.
</details>
If we really want to change this though, let's keep the comment consistent in this PR and make the global refactor separately. There's no reason to get the comments out of sync before the change is made everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/326)*

**Comment by tamird** [comment]
Yes, I think that's what Jesse suggested.

**Comment by jseldess** [comment]
Yeah, I'll rework the comments in a follow-up PR.

**Pull request merged**
