### PR TITLE
2.0 release notes and known limitations

### LINKED ISSUE #2446: Document Known Limitations in 2.0

### LINKED ISSUE #2566: sql: PARTITION BY does not support placeholders
Document #19464

### PR DESCRIPTION
**Pull request by jseldess**
@bdarnell, @nstewart, PTAL at these draft release notes for 2.0. As you'll see, I tried to summarize the most significant user-facing features (pretty much all from the roadmap). Please let me know if anything significant is missing, or if any language should be changed. 

Of course, this leaves out a LOT of significant internal work and granular changes to the product, but I don't think we can list out everything here. Or if we want to, I'd need help. 

This PR also documents 2.0 known limitations. 

Fixes #2446.
Fixes #2566.

### CODE REVIEW

**Comment by jseldess** [comment]
Oh, and @nstewart, I need help with the intro sentence:

> With the release of CockroachDB v2.0, we’ve...

For reference, here's what we had for v1.1:

> With the release of CockroachDB v1.1.0, we’ve included support for faster migrations from other databases for developers, simplified cluster management for operators, and improved performance in real-world environments.

**Comment by bdarnell** [comment]
We need to be sure to copy forward any of the backwards-incompatible changes from previous release notes. We have some in 0305 (sequences (only applies relative to previous alphas/betas) and zone constraints), 1026 (bytes/string casts), 1113 (NaN and drop user with grants), 0122 (removed settings and env vars).

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[releases/v2.0.0.md, line 11 at r4](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-L926CclCre8C5Bct_sk:-L926CclCre8C5Bct_sl:b-xw87uq) ([raw file](https://github.com/cockroachdb/docs/blob/709faec6a0813f5706a35c91209d6cc8708799c7/releases/v2.0.0.md#L11)):*
> ```Markdown
> With the release of CockroachDB v2.0, we’ve...
> 
> - Read more about these changes in the [v2.0 blog post](https://www.cockroachlabs.com/blog/cockroachdb-1dot1/).
> ```

Don't forget to update this link. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-:-L926grEDeRMWYt-hy4l:bkygu3u)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[v2.0/known-limitations.md, line 17 at r4](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-L92nc_R4fe8EcROem8h:-L92nc_SDAvXCJw8liCj:b-7ofxw0) ([raw file](https://github.com/cockroachdb/docs/blob/709faec6a0813f5706a35c91209d6cc8708799c7/v2.0/known-limitations.md#L17)):*
> ```Markdown
> The `--cache` and `--max-sql-memory` flags of the [`cockroach start`](start-a-node.html) command do not support non-integer values with a unit suffix, for example, `--cache=1.5GiB`.
> 
> As a workaround, use integer values or a percentage, for example, `--cache=1610612736B`.
> ```

A more compact and easier to understand suggested workaround would be `--cache=1536MiB`. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823)*

**Comment by jseldess** [comment]
Added backward-incompatible changes, @bdarnell. PTAL. 

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[v2.0/known-limitations.md, line 17 at r4](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-L92nc_R4fe8EcROem8h:-L935VcF45lM1CqMul02:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/709faec6a0813f5706a35c91209d6cc8708799c7/v2.0/known-limitations.md#L17)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

A more compact and easier to understand suggested workaround would be `--cache=1536MiB`. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-:-L93Be2MDg1UQgrQ653C:b-e0aqbc)*

**Comment by nstewart** [comment]
@jseldess point in time backup/restore is a beta feature. I think @Amruta-Ranade is updating this cc @dianasaur323

**Comment by dianasaur323** [comment]
yes, it is beta! just pinged @Amruta-Ranade about it. Also, @jseldess am I on deck to write the user contract for experimental vs beta? It would be great to have a docs person to work with so that I know where it lives and what best practices are? Do you mind letting me know who would be good to sync up with? Just need 15 minutes of their time and then I can go come up with a draft.

**Comment by jseldess** [comment]
*[releases/v2.0.0.md, line 11 at r4](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-L926CclCre8C5Bct_sk:-L95zNsA7s567LfpC-Gh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/709faec6a0813f5706a35c91209d6cc8708799c7/releases/v2.0.0.md#L11)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Don't forget to update this link. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823)*

**Comment by jseldess** [comment]
@nstewart and @dianasaur323, added `beta` and `experimental` language where necessary.

**Comment by dianasaur323** [comment]
Thanks jesse!

**Comment by knz** [comment]
The following callout must be inserted below the "Parameters" section in `create-view.md`:

```
{{site.data.alerts.callout_info}}It is not yet possible to use a <a
href="common-table-expressions.html">common table expression</a>
defined 1with <code>WITH</code> inside the selection query used to defined a
view. This is a known limitation that may be lifted in a future
version of CockroachDB.{{site.data.alerts.end}}
```

(you may want to insert a similar paragraph in the known limitation page)

The following callout must be inserted at the end of the "Syntax" sub-section of the "VALUES Clause" sub-section of `selection-queries.md`:

```
{{site.data.alerts.callout_info}}It is not yet possible to use a <a
href="common-table-expressions.html">common table expression</a>
defined with <code>WITH</code> outside of a <code>VALUES</code>
clause, inside a <a href="subqueries.html>subquery</a> inside the
<code>VALUES</code> clause. This limitation may be lifted in a
future version of CockroachDB.{{site.data.alerts.end}}
```

The following sub-section must be added at the end of the "Set Operations" sections in `selection-queries.md`:

```
### Using Set Operations With Common Table Expressions

Due to a current limitation in CockroachDB, a common table
expression (CTE) defined using `WITH` outside of a set expression
cannot be used in the right operand of a set operator. For example,
the following query is not yet recognized:

{% include copy-clipboard.html %}
~~~ sql
> WITH a AS (SELECT 1)
  SELECT * FROM users UNION SELECT * FROM a; -- "a" used on the
right, not yet supported.
~~~

For `UNION`, you can work around this limitation by swapping the
operands. For the other set operators, you can inline the definition
of the CTE inside the right operand.

This limitation may be lifted in a future version of CockroachDB.
```

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-:-L96C8Zb74NM1BLSqnrN:bw79rkz)*

**Comment by knz** [comment]
I would also recommend adding a sub-section "LInks to known limitations" in the separate doc page `common-table-expressions.md` which cross references these things.

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-:-L96E7oW81gW3WKrFbVr:b-v9sjrq)*

**Comment by jseldess** [comment]
Thanks, @knz! Done.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2823#-:-L96Xmzf1YUOv6DdusC7:bdtuhlg)*

**Comment by andreimatei** [comment]
Please pull to get #2851

**Comment by jseldess** [comment]
Done. Thanks, @andreimatei.

**Pull request merged**
