### PR TITLE
clarify query plan cache behavior

### PR DESCRIPTION
**Pull request by taroface**
Fixes [DOC-5265](https://cockroachlabs.atlassian.net/browse/DOC-5265).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'll defer to @rytaft and @mgartner for approval since they are more familiar with the optimizer.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14846#-:-N9cD9hP2I32618h9pUZ:bms8qtg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Comment by yuzefovich** [comment]
Also, this is not a new behavior, so we might want to make the same change to 21.2 branch.

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14846)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @taroface)

___
*[`v22.1/cost-based-optimizer.md` line 231 at r1](https://reviewable.io/reviews/cockroachdb/docs/14846#-N9mo04B9--G1mj_JjxU:-N9mo04B9--G1mj_JjxV:b-7d2sp8) ([raw file](https://github.com/cockroachdb/docs/blob/ff9fb864ae0ca39c9a02d46a03931f404ac1073d/v22.1/cost-based-optimizer.md#L231)):*
> ```Markdown
> - [`DELETE`](delete.html)
> 
> The optimizer can cache statements if they are: 
> ```

nit: this is slightly incorrect. I'd say "The optimizer can use cached plans if they are:"

**Comment by taroface** [comment]
> nit: this is slightly incorrect. I'd say "The optimizer can use cached plans if they are:"

TFTR! Used this and added to v21.2 (and now v22.2).

**Review by kathancox — APPROVED** [review]
LGTM!

**Pull request merged**
