### PR TITLE
Cloud september notes

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/DOC-5574

### CODE REVIEW

**Review by emily-horing — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @jramos-crl, and @kevin-v-ngo)

___
*[`releases/cloud.md` line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/14954#-NBJWBCW7DBLenMZBvIN:-NBJWBCXEMSGnuoKmzXw:b-sb54vn) ([raw file](https://github.com/cockroachdb/docs/blob/51ff1bfc6bd94a523b708a03b63d84740f39e8c6/releases/cloud.md#L18)):*
> ```Markdown
> 
> {{site.data.alerts.callout_version}}
> As of August 23, 2022, {{ site.data.products.serverless }} clusters are running CockroachDB [v22.1.5](v22.1.html#v22-1-5) and new {{ site.data.products.dedicated }} clusters are running CockroachDB [v22.1.5](v22.1.html#v22-1-5).
> ```

As of 8/29 serverless is running 22.1.6, dedicated was even before that. see https://cockroachlabs.slack.com/archives/CJX8V9SJ2/p1661971577790269?thread_ts=1661803781.292069&cid=CJX8V9SJ2

**Comment by gemma-shay** [comment]
Links are breaking due to being dependent on [this pr](https://github.com/cockroachdb/docs/pull/14973) btw. I will remove if the feature & docs are not live before the notes.

**Review by jramos-crl — APPROVED** [review]
LGTM!

**Comment by gemma-shay** [comment]
removing databases note in favor of including it in the relevant docs pr. @kevin-v-ngo @rmloveland do you both have time to review today?

**Review by rmloveland — APPROVED** [review]
LGTM

**Comment by gemma-shay** [comment]
tftr! going to go ahead and merge as i was already late on this and i don't think anything in kevin's area was affected

**Pull request merged**
