### PR TITLE
Add example for filtering key-value pairs

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Add example for filtering JSONB values through key-value pairs 

Solves #7294 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

### CODE REVIEW

**Comment by SpicyThrow** [comment]
I think this looks good, but someone with more JSON expertise than me should verify that this is correct.

**Comment by Amruta-Ranade** [comment]
Got an internal LGTM 🎉
@vipulgupta2048 Can you update the 20.1 and 20.2 docs too?

**Comment by vipulgupta2048** [comment]
Awesome @SpicyThrow @Amruta-Ranade Just a side thought, I like looking into the documentation pipelines and am always curious about them (part of the job) and I wanted to suggest if you folks have thought of going more into `docs as code` style for your documentation. I haven't looked at Jekyll for quite some time, but I feel the documentation's versioning and generation could be automated. Removing a lot of overhead on writers and contributors because it wasn't clear to me which version to edit and but issue had a link mentionining 19.2. Nonetheless, love to have a discussion on issue or something. 

Will update the PR for 20.1 and 20.2

**Comment by Amruta-Ranade** [comment]
We have had discussions about it but never enough bandwidth to dive into the issue. We now have a product operations engineer onboard, so we might revisit this issue some time in the near future :)

**Comment by vipulgupta2048** [comment]
That's great to hear, thank you for the prompt response @Amruta-Ranade More power to you folks! I will be especially interested to see that happen. I have updated the PR.

**Pull request merged**
