### PR TITLE
update serverless -> dedicated migration steps

### PR DESCRIPTION
**Pull request by taroface**
DOC-2622

- Update serverless -> dedicated migration steps to use `EXPORT` rather than local storage
- Fix some misformatted links elsewhere

### CODE REVIEW

**Review by otan — COMMENTED** [review]
hmm, does BACKUP and RESTORE not work for serverless -> dedicated?

**Review by awoods187 — APPROVED** [review]
LGTM 

I'd check with @andy-kimball and  @amruss  to make sure serverless and export are positioned correctly

**Comment by andy-kimball** [comment]
Seems pretty tough to do a database migration this way - table by table? Is that really our best answer to this problem? Like @otan, I'd expect BACKUP/RESTORE to work and be much faster/easier.

**Comment by taroface** [comment]
I conferred with @awoods187 and have created a [ticket](https://cockroachlabs.atlassian.net/browse/DOC-6461) to track refactoring this doc with BACKUP/RESTORE (as well as bring in the latest migration recommendations).

This PR is only meant to correct the outdated info that `EXPORT` couldn't be used with serverless clusters.

**Comment by otan** [comment]
> This PR is only meant to correct the outdated info that EXPORT couldn't be used with serverless clusters.

but you're using export here? do you mean export into local files doesn't work with serverless clusters?

**Comment by taroface** [comment]
> > This PR is only meant to correct the outdated info that EXPORT couldn't be used with serverless clusters.
> 
> 
> 
> but you're using export here? do you mean export into local files doesn't work with serverless clusters?

Sorry, yeah. Previously this doc recommended export to local files only because it was presumably written when EXPORT from serverless directly to cloud storage was still not possible. The update simplifies the existing steps so that they are using EXPORT direct to S3 instead of exporting to local files and then uploading to S3.

**Review by otan — APPROVED** [review]
this is fine for now i guess, but yeah BACKUP/RESTORE seems much better

**Review by kathancox — APPROVED** [review]
LGTM!

**Pull request merged**
