### PR TITLE
add missing documentation to SHOW GRANTS page

### LINKED ISSUE #8237: Field `schema_name` not described by documentation in `SHOW GRANTS`
In `show-grants.md`, the `SHOW GRANTS` command returns a table with several fields, but it doesn't define them. The most confusing are `schema_name` and `privilege_type`, as it's not obvious what they refer to. This is a problem for all examples on this page.

This is a problem because users may be confused about what they're seeing even after using the docs.

Steps to reproduce:
* Go to https://www.cockroachlabs.com/docs/v20.1/show-grants#show-all-grants
* Look at the first example, `SHOW GRANTS;`

Expected result: columns in the table returned get defined

Actual result: columns are not defined anywhere.

### PR DESCRIPTION
**Pull request by HugoLiconV**
fix #8237

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
Oh, didn't get a notification for this PR. Sorry for the delay! The Parameter table lists the parameters with user-defined values.  If I am not mistaken, the `grantee` , `schema_name`, and `privilege_type` are not user-defined parameters. Could you add the description text to the example instead of the parameters table, as we discussed in the issue (sorry if it wasn't clear earlier).

**Comment by HugoLiconV** [comment]
> table lists the parameters

Sorry, I misunderstood what you were asking for. So, just to clarify, I need to remove `grantee`, `schema_name`, and `privilege_type` from the parameters table and add them to the _Example section_. 

I was thinking to add another table defining each one of the fields that the `SHOW GRANTS;` commands returns. Something like this:


## Parameters

Parameter | Description
----------|------------
`role_name` | A comma-separated list of role names.
`table_name` | A comma-separated list of table names. Alternately, to list privileges for all tables, use `*`.
`database_name` | A comma-separated list of database names.
`user_name` | An optional, comma-separated list of grantees.

## Examples
HERE WOULD BE THE TABLE DEFINING EACH ON OF THE FIELDS
Field | Description
----------|------------
`database_name` | ...
`schema_name` | ...
`table_name` | ...
`grantee` | ...
`privilege_type` | ...


### Show all grants
To list all grants for all users and roles on all databases and tables:

``` sql
> SHOW GRANTS;
```
...

Does this make sense to you?

**Comment by Amruta-Ranade** [comment]
Hmm..I like the idea but it breaks consistency across other SQL statement docs. For now, I think it's best to add the descriptions as text-only in the example section. I'll bring your idea up with the team if we find a quiet moment (the team's swamped with release work rn 😓)

**Comment by SWDevAngel** [comment]
@HugoLiconV LAST DAY TO ORDER!!!
Hi Hugo. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. We tried to reach you via GitHub or on email, but if you didn’t see the message please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link to order your gift. (If you don’t want a gift, we also have a charitable contribution choice.) All orders must be in by December 13 (that’s tomorrow!), so please send this asap. :)

**Comment by SWDevAngel** [comment]
@HugoLiconV It looks like your email listed above is bouncing, but the fulfillment center did confirm they received your order. :) If you have a new email address you want to give me you can dm me on our [community Slack](https://cockroa.ch/slack) `@lisa` or twitter `@swdevangel`. :)

**Pull request merged**
