### PR TITLE
footer redesign

### PR DESCRIPTION
**Pull request by elkmaster**
Resolves: #8641 

Screenshot 2020-11-02 at 17 43 38
Screenshot 2020-11-02 at 17 43 50

### CODE REVIEW

**Comment by luciaaaaaaa** [comment]
Looking good! Should I test the links aswell?

UI Feedback:

- the footer should go all the way to the edge, right now there are gaps on both sides 
- titles should not be all caps 
- would like @jseldess and @lnhsingh to look at the links and assess whether everything that is on there makes sense

**Comment by elkmaster** [comment]
@luciaaaaaaa gaps will be removed by sidenav pr

**Comment by lnhsingh** [comment]
I think the footer links should be the same as what's currently on the website but then that also needs to be updated to what [Marketing recently requested](https://github.com/cockroachdb/docs/issues/8712)

**Comment by jseldess** [comment]
Yes, I agree with @lnhsingh. No reason to diverge on the footer. 

@yingzhuchin, can you make that quick fix to the footer that @jess-edwards requested?

**Comment by yingzhuchin** [comment]
> Yes, I agree with @lnhsingh. No reason to diverge on the footer.
> 
> @yingzhuchin, can you make that quick fix to the footer that @jess-edwards requested?

This is done.

@elkmaster, can you please pull commit 1740d890559767f8984e5ce69ad6622ed2182c7d into your PR here? Thank you!

**Comment by elkmaster** [comment]
Updated menu items to match 1740d89

Screenshot 2020-11-10 at 19 16 12

**Comment by yingzhuchin** [comment]
> Updated menu items to match [1740d89](https://github.com/cockroachdb/docs/commit/1740d890559767f8984e5ce69ad6622ed2182c7d)

Thanks, @elkmaster! I am seeing in Figma that the footer text should be underlined in blue when user hovers: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=3020%3A4

Could you make that change?

**Comment by elkmaster** [comment]
@yingzhuchin, can't find hover state for that element in figma except:
Screenshot 2020-11-10 at 19 39 31
But this is not intended to display hover state. This is internal figma app highlights of clickable elements.

**Comment by yingzhuchin** [comment]
> But this is not intended to display hover state. This is internal figma app highlights of clickable elements.

**Review by lnhsingh — APPROVED** [review]
Looks good from a content standpoint.

**Pull request closed without merging**
