### PR TITLE
CC machine type, storage, and IOPS info

### PR DESCRIPTION
**Pull request by gemma-shay**
Specified machine types, storage types, and AWS IOPS per node in Step 5 of **Create Your Cluster** page.

Closes: https://cockroachlabs.atlassian.net/browse/CC-3698?atlOrigin=eyJpIjoiNjAwMWVlYWI3Y2U4NDlkMzg2ODUxOTkyY2FjN2U4Y2YiLCJwIjoiaiJ9

Question: Do we want to include IOPS for GCP cluster?

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
Small language nit and would suggest that we add the IOPS for GCP as well, to be consistent with the info we provide for AWS 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10483#-:-MZshO0w4_0joIqdB-yr:b-lgrcdy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @kannanlakshmi)

___
*[cockroachcloud/create-your-cluster.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/docs/10483#-MZshICW2GXanRUzTG7G:-MZshICX9-XDIZI1SOIi:bl44n8d) ([raw file](https://github.com/cockroachdb/docs/blob/2a925b5c7f0ad96c20f613c2371a1ae0d27cf9db/cockroachcloud/create-your-cluster.md#L81)):*
> ```Markdown
> 16 vCPU    | 2000
>  
> To change the hardware configuration after the cluster is created, you will have to [contact us](https://support.cockroachlabs.com/hc/en-us/requests/new).
> ```

nit: `you will have to contact us` > `contact Support`

**Comment by gemma-shay** [comment]
@lnhsingh Do you think it would be better to combine this info with this table: http://localhost:4000/docs/cockroachcloud/create-your-cluster.html#step-2-select-the-cloud-provider ?

**Comment by lnhsingh** [comment]
Oh yeah, that's a good idea since Step 2 talks about vCPU

**Comment by gemma-shay** [comment]
@kannanlakshmi friendly reminder to review when you can :)

**Review by kannanlakshmi — APPROVED** [review]
This LGTM for now. Note that this will change in the next 1-2 months based on the work that @jramos-crl and @iibuaka are doing.

**Comment by kannanlakshmi** [comment]
And apologies for the 1 week delay here, this slipped my inbox last week!

**Pull request merged**
