### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by awreece**
> thought of as AN always close to

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @awreece.

@sploiselle, for the correct meaning, shouldn't we just remove `an/and`?

**Comment by sploiselle** [comment]
@jseldess I meant it like [(thought-of-as) and (always-close-to) local wall time]. Could be rephrased to something like `...which are composed of a physical component (always close to local wall time)...`

@awreece Thanks for letting us know you stumbled on this. Just an FYI, if you wanted to implement your edit, you'd need to hyphenated it, i.e. `thought of as an-always-close-to-local wall time`, though that's pretty strange wording.

**Comment by awreece** [comment]
Yeah, I think there is actually a bit of work we can do to simplify the grammar here :)

I just didn't want to rock the boat on my first PR! Would you be interested in me doing a bit more work on this section, or is perhaps not a great time for that?

**Comment by jseldess** [comment]
Thanks for the clarification, @sploiselle. And for your offer to edit the section, @awreece. Please do propose simplifications, if you have them. If we stay close to the current formulation, I'd suggest something like: `...physical component (always close to local wall time)...`

**Comment by jseldess** [comment]
I went ahead and opened a separate PR with this change and applied it to other versions of the page as well. Thanks for triggering this improvement, @awreece.

**Pull request closed without merging**
