### PR TITLE
MVP content for Managed CockroachDB docs

### PR DESCRIPTION
**Pull request by benesch**
Basic content for initial Managed CockroachDB docs, includeing:
- Get Started
    - Sign Up for the Service
    - Connect to Your Cluster (sql client and drivers)
    - Learn CockroachDB SQL
    - Use the Admin UI
- Use Your Cluster
    - Migrate Data
    - Tune Performance (just SQL best practices for now) 
- Manage Your Account
    - User Management (users and privileges)
    - Cluster Management (task that require CRLB involvement)

Also add some Jekyll magic on top of https://github.com/cockroachdb/docs/pull/3891 so that links are automatically fixed up to point at the standard docs when a page does not exist in the managed docs.

Note: These initial docs are "minimum viable", quite thin. We will plan and build out more content post-release.

### CODE REVIEW

**Comment by benesch** [comment]
> Will the TeamCity jobs need adjusting at all, with the removal of those python scripts?

Nope! That's the benefit of keeping everything in the Makefile. Just one thing to change.

> Would you mind committing these changes to the branch with my content work? I'm planning to continue work there, and I'm unsure of how to handle this PR and that one without strange conflicts.

I can, but perhaps it would be easier if you just took over this PR? It already incorporates the content changes you've made in #3891 so far.

**Comment by jseldess** [comment]
OK, yes, I'll take over this PR next week. Thank you.

**Comment by kannanlakshmi** [comment]
Overall, looks great Jesse! Happy to review the stuff under "Use your cluster" and "Manage your cluster" whenever you are ready -- it can be super simple and just point them to existing docs. 

On the landing page, we changed the talking points since we last chatted. Latest from marketing (and pm) is here: 
1. 

1. **Always-on Service**
Cloud vendor agnostic
Automatic data replication across 3+ data centers
Zero downtime migration between cloud providers

**Operational Excellence** 
Automatic hardware provisioning, setup, and configuration 
Automatic rolling upgrades
Automated daily backups and hourly incremental backups 

**Enterprise-Grade Security**
TLS 1.2 for all connections
Single tenant clusters 
SOC-2 Compliance (in process)

2. Minor nit: 
In the Getting Started page, instead of "SQL connection URL with fake details" can we say "SQL connection URL with example details" and specify the details that we are using for the example? 
Like, name: hostname: password: etc. 

3. I know we discussed deleting the private Slack channel details already but adding it here for completeness sake. 

4. In the "Use the CockroachDB SQL Client" section, step 2 binary path is slightly different from the step 1 binary path and gave me an error. Update step 2 to say: (its missing that initial cockroach-)
`cp -i cockroach-v2.1.0-beta.20181015.darwin-10.9-amd64/cockroach /usr/local/bin`

5. In the "Use the Admin UI" minor nit. Missing an `a` 
"This URL is **a** combination of the global hostname and port 8080."

6. In the Admin UI section, "Log in with your username and password. If you're using the default user, the credentials were provided in the confirmation email."
Suggest adding a link on how to create another user (from the next section), if they are not using the default user. 

7. I really like the idea of telling them how to run benchmarks under "Use your cluster." Understood that this won't be done for next week's release. 

8. Not sure what you were thinking for migrate, but we should point them to the import docs. For performance, we could point them to production perf tuning? 

9. Finally for manage your account, to recap what we discussed this am (for posterity here), we should include the actions they need to contact us for. And also add that the best way to reach us for immediate assistance is support.cockroachlabs.com and a member of our team will respond shortly.

**Comment by jseldess** [comment]
Thanks, @kannanlakshmi. I believe I address all of your concerns. Please take another look. Also, please do review everything under "Use Your Cluster" and "Manage Your Account". It's ready for review.

**Comment by mberhault** [comment]
LGTM. Do we want to mention the managed@cockroachlabs.com support email? Or just point to the generic support url?

**Comment by jseldess** [comment]
Direct link to latest test site: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/4283b0882fdc9e7390d510b25fd49b483b137e2a/managed/stable/

**Comment by tim-o** [comment]
Direct people to support.cockroachlabs.com. It'll go to managed@ anyway, and we'll get the benefits of reporting and paging. Less change management later.

**Comment by mberhault** [comment]
Oh, right. managed@ is just one of the users for support, not a separate category. Nevermind then, the URL works just fine.

**Comment by jseldess** [comment]
___
*[v2.1/managed-sign-up-for-a-cluster.md, line 70 at r9](https://reviewable.io/reviews/cockroachdb/docs/3892#-LPbi0vq4m9OU1ZtEld0:-LPcJ7Fm5lUo2LEdFMxs:bd3j75h) ([raw file](https://github.com/cockroachdb/docs/blob/4283b0882fdc9e7390d510b25fd49b483b137e2a/v2.1/managed-sign-up-for-a-cluster.md#L70)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

I think we should add "See also" links 
</blockquote></details>

There are so few pages right now. I'm going to hold off till we build out the content more.

**Comment by jseldess** [comment]
TFTRs, @kannanlakshmi, @lhirata, @mberhault.

**Pull request merged**
