### PR TITLE
Add download link for cockroach-sql

### PR DESCRIPTION
**Pull request by knz**
Informs #13562.
Epic: CC-5993

cc @jseldess

### CODE REVIEW

**Comment by nickvigilante** [comment]
@knz This looks good, but can you also apply the change you made in https://github.com/cockroachdb/cockroach/pull/79788 to [this file](https://github.com/cockroachdb/docs/blob/master/_includes/releases/release-downloads-docker-image.md)?

**Comment by knz** [comment]
> can you also apply the change you made in https://github.com/cockroachdb/cockroach/pull/79788 to [this file](https://github.com/cockroachdb/docs/blob/master/_includes/releases/release-downloads-docker-image.md?rgh-link-date=2022-04-11T18%3A43%3A01Z)?

Done.

Can you also point me to who/how the file `releases.csv` is generated? We need to change the generation to add a new column.

**Review by nickvigilante — APPROVED** [review]

**Comment by nickvigilante** [comment]
@knz As a stop gap until I figured out a good way to maintain the existing functionality of the Python script while satisfying the docs team's purposes, I put a copy of it here:

https://github.com/cockroachdb/ed-tools/blob/main/docs/release-notes/release-notes.py

**Comment by knz** [comment]
ok, are you expecting me to update that copy to add the new column?

**Comment by nickvigilante** [comment]
@knz I can update it if you want me to; I just need to know the logic used to calculate it (under what situations is it true or false?).

**Comment by knz** [comment]
It's true for v22.1-beta.1 and all later versions after that
it's false for all versions before v22.1 (so also false for later patch releases of v21.2 etc)

**Pull request merged**
