### PR TITLE
doc updates for beta-20160407 release

### PR DESCRIPTION
**Pull request by jseldess**
Docs should be good for beta-20160407 now. 

@bdarnell, please take a quick look before I merge and publish.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/205)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by JackKrupansky** [comment]
Docker question: Does the indicated command always pull the image tagged "latest", or does the user need to select a tag, like beta-20160407?

Also, if various test images are created, are they by definition never tagged as "latest"?

(There are quite a few hex-named images out there that I suspect should be removed unless they are still running for inhouse test clusters.)

Finally, are "latest" and "beta-20160407" by definition identical (at this moment)?

I'm also thinking of the case where someone has a running cluster and simply wants to add or replace a node - they need or may want the same image as they have for the current nodes rather than "latest", which may have breaking changes (as is the case at this moment.) In which case, they should have doc instructions for that case that use an explicit tag (I haven't checked if such doc exists.)

**Comment by bdarnell** [comment]
@JackKrupansky Good catch. The `latest` docker image corresponds to the github `master` branch, i.e. the in-development version and not the beta. The `docker pull` command does need to include the `beta-20160407` tag. (and we should figure out how to set up a `beta` tag that will get the latest beta without hard-coding a specific version).

**Comment by jseldess** [comment]
@bdarnell, does this mean I should call out in the docs that using the docker image or building from source will get you the in-development version and not the latest official "beta" version?

**Comment by bdarnell** [comment]
The instructions should be updated to give you the beta. For docker, the pull command should be `docker pull cockroachdb/cockroach:{{site.data.strings.version}}`. When building from source, add `git checkout {{site.data.strings.version}}` before `make build`.

**Comment by jseldess** [comment]
Open another PR with these changes: https://github.com/cockroachdb/docs/pull/208

**Pull request merged**
