### PR TITLE
tech talks update

### PR DESCRIPTION
**Pull request by eballeste**
sidenav update, now links to new page in main site’s community section
removal of docs tech-talks page

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/994)

### CODE REVIEW

**Comment by eballeste** [comment]
@jseldess some type of 301 redirect needs to be setup for removed page

**Comment by jseldess** [comment]
@eballeste, there's just one more link in `beta-20160512.md`pointing to the old page. If you update that link to point to the new page, your PR should pass the test.

**Comment by eballeste** [comment]
No problem. Would you be able to help out with the 301 redirects? We need
to set that up before making the change because we found that there are a
lot of sites that are linking to the current tech talks page within the
docs.

On Jan 13, 2017 12:13 AM, "jseldess" <notifications@github.com> wrote:

@eballeste <https://github.com/eballeste>, there's just one more link in
beta-20160512.mdpointing to the old page. If you update that link to point
to the new page, your PR should pass the test.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/docs/pull/994#issuecomment-272362914>, or mute
the thread

**Comment by jseldess** [comment]
@mberhault is going to look into the redirect for us. You can track that here: https://github.com/cockroachdb/docs/issues/999

**Comment by eballeste** [comment]
@jseldess just pushed

did the team city checks fail because it detected that broken link?

**Comment by jseldess** [comment]
Thanks, @eballeste. Yep. Now it passes. 

Do we need to wait on the 301 redirect before merging this?

**Comment by eballeste** [comment]
@jseldess TeamCity auto deploys after the merge right? If so, then we should wait on the redirect to kick in first.

**Comment by jseldess** [comment]
It doesn't autodeploy for docs. We need to press run. But it's possible that we'll merge something else in the meantime that does need to get deployed. So safest to just leave this until the redirect is in place. 

@mberhault, just so you know: the redirect needs to happen before we can merge this change.

**Comment by mberhault** [comment]
Redirect is in place.

**Comment by eballeste** [comment]
@mberhault @jseldess seems like the url was incorrect, accessing the page without the trailing forward slash will still load the soon to be removed docs page.

**Comment by mberhault** [comment]
odd, I definitely entered the URL without the slash and it was working
shortly after.
Could be a mix of wordpress/htaccess refreshes, and cloudflare caching.
I'll double check.

**Comment by mberhault** [comment]
I cleared the cloudflare cache (just that one file) and tried again in an
incognito window, the redirect looks fine.

**Comment by eballeste** [comment]
@mberhault working for me too, thanks!

**Comment by jseldess** [comment]
Thanks, @mberhault and @eballeste. Closing and merging.

**Pull request merged**
