### PR TITLE
Removed tutorials for community-supported drivers

### PR DESCRIPTION
**Pull request by ericharmeling**
Follow-up on https://github.com/cockroachdb/docs/pull/12913.

Fixes https://cockroachlabs.atlassian.net/browse/DOC-371.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-928.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2382.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-289.

This PR includes several updates to our community-supported tooling docs, including the removal of tutorials for community-supported drivers. See commit message for more details.

Merging this PR will remove some clutter from our docs site and docs repo and will establish a more sustainable precedent for how we document tools that we don't officially support (i.e., that we don't document them).

All sample code for community-supported drivers will now be available in separate directories of the new [`community-tooling-samples` repo](https://github.com/cockroachlabs/community-tooling-samples). The `README` files in each driver's directory contain an adapted version of each sample's original tutorial. Before this PR can be merged, we will need to make that repo public (it is currently private). 

As a follow-up to this PR, we can move any extant issues in the `docs` repo that relate to any community-supported drivers to that repo.

### CODE REVIEW

**Review by jseldess — APPROVED** [review]
This LGTM. Part of me is sad that we're removing all of those old tutorials from the side, as I remember building them in the first few years of Cockroach's existence. But I completely agree with the logic here at the same time. 

Question: `community-tooling-samples` repo is currently in the `cockroachlabs` org. Why is that? Why not the `cockroachdb` org? If it stays in `cockroachlabs`, in any case, it needs to be made public.

**Comment by jseldess** [comment]
Oh, also, what do we plan to do with previous doc version?

**Comment by jseldess** [comment]
Just realized that we link to some of these community supported tutorials from the Marketing team's developers page: https://www.cockroachlabs.com/developers/. See "Other languages". 

We're fine for now because you've put in place redirects, but we should consider chatting with them and thinking through another approach. cc @kernfeld-cockroach

**Comment by kernfeld-cockroach** [comment]
1. Can you list the affected languages in the commit message? That just makes it a little easier to see the effect of this change.
2. Out of these languages, I think we actually do care about Rust because it's popular with experienced innovators so I'd like to leave it.

**Comment by ericharmeling** [comment]
@jseldess 

> Question: `community-tooling-samples` repo is currently in the `cockroachlabs` org. Why is that? Why not the `cockroachdb` org? If it stays in `cockroachlabs`, in any case, it needs to be made public.

Moved that repo into `cockroachdb`. I also opened a Jira issue to move all other samples into `cockroachdb`: https://cockroachlabs.atlassian.net/browse/DOC-2777

> Oh, also, what do we plan to do with previous doc version?

Since these changes have been approved, I've propagated the changes to 21.1. I'm not sure we need to go back any further than that. Do you disagree?

> Just realized that we link to some of these community supported tutorials from the Marketing team's developers page: https://www.cockroachlabs.com/developers/. See "Other languages".

We should get that page updated. We ought to remove explicit mentions of C++, Clojure, and PHP. Also, Node.js shouldn't be listed in "Other languages". It really should have its own tile. Probably even the first tile. Not sure who controls that page.

@kernfeld-cockroach 

> Can you list the affected languages in the commit message? That just makes it a little easier to see the effect of this change.

Done.

> Out of these languages, I think we actually do care about Rust because it's popular with experienced innovators so I'd like to leave it.

Done.

**Review by nickvigilante — CHANGES_REQUESTED** [review]
Aside from the nits, this LGTM!

> Reviewed 181 of 181 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13053#-:-MxZwZjx10iK8oO7wXiA:b-8tp58v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v21.1/build-a-go-app-with-cockroachdb-pq.md, line 39 at r1](https://reviewable.io/reviews/cockroachdb/docs/13053#-MxZul199Eb2JC0afzPk:-MxZul199Eb2JC0afzPl:b-o1u9um) ([raw file](https://github.com/cockroachdb/docs/blob/2a23cc59f609c2da4dcf31291c6d22b645668951/v21.1/build-a-go-app-with-cockroachdb-pq.md#L39)):*
> ```Markdown
> ### Get the code
> 
> You can copy the code below, <a href="https://raw.githubusercontent.com/cockroachlabs/hello-world-go-pq/master/main.go">download the code directly</a>, or clone [the code's GitHub repository](https://github.com/cockroachlabs/hello-world-go-pq).
> ```

For usability, I suggest converting the `a href` link to a markdown link, since it should 1) open that link in a new tab and 2) add `target=noopener` automatically.
___
*[v21.2/build-a-go-app-with-cockroachdb-pq.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/13053#-MxZw3Nf3k7Bmqi0E5SV:-MxZw3Nf3k7Bmqi0E5SW:buodkiy) ([raw file](https://github.com/cockroachdb/docs/blob/2a23cc59f609c2da4dcf31291c6d22b645668951/v21.2/build-a-go-app-with-cockroachdb-pq.md#L38)):*
> ```Markdown
> ### Get the code
> 
> You can copy the code below, <a href="https://raw.githubusercontent.com/cockroachlabs/hello-world-go-pq/master/main.go">download the code directly</a>, or clone [the code's GitHub repository](https://github.com/cockroachlabs/hello-world-go-pq).
> ```

Same nit.
___
*[v22.1/build-a-go-app-with-cockroachdb-pq.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/13053#-MxZwPsVE58ks3B4_DDA:-MxZwPsVE58ks3B4_DDB:buodkiy) ([raw file](https://github.com/cockroachdb/docs/blob/2a23cc59f609c2da4dcf31291c6d22b645668951/v22.1/build-a-go-app-with-cockroachdb-pq.md#L38)):*
> ```Markdown
> ### Get the code
> 
> You can copy the code below, <a href="https://raw.githubusercontent.com/cockroachlabs/hello-world-go-pq/master/main.go">download the code directly</a>, or clone [the code's GitHub repository](https://github.com/cockroachlabs/hello-world-go-pq).
> ```

Same nit.

**Comment by ericharmeling** [comment]
@nickvigilante TFTR!

> For usability, I suggest converting the a href link to a markdown link, since it should 1) open that link in a new tab and 2) add target=noopener automatically.

Done.

**Pull request merged**
