### PR TITLE
Added null-handling page

### PR DESCRIPTION
**Pull request by uptimeDBA**
@jseldess As requested I've "de-blogged" the narrative of my NULL handling post and created a null-handling page. 
I haven't added this page to the menu as I wasn't sure if you wanted a separate page or the content added to somewhere like the data-definition page.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/333)

### CODE REVIEW

**Comment by jseldess** [comment]
LGTM, Paul. Thanks for this contribution. Let me get a dev to review as well.

<details><summary><i>Previously, uptimeDBA (Paul Steffensen) wrote…</i></summary>
> #### Added null\-handling page
> 
> @jseldess As requested I've "de-blogged" the narrative of my NULL handling post and created a null-handling page. 
> 
> I haven't added this page to the menu as I wasn't sure if you wanted a separate page or the content added to somewhere like the data-definition page.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[null-handling.md, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ68_xWf7qu40vEkyBR:-KJ68_xWf7qu40vEkyBS:342816328) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L6)):*
> ```Markdown
> ---
> 
> This page summarizes how *NULL* values are handled in CockroachDB SQL.
> ```

Let's code-format `NULL` here and anywhere else it shows up in the text. 

---

*[null-handling.md, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ698iSF3uevz3QTv_5:-KJ698iSF3uevz3QTv_6:-1032191126) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L142)):*
> ```Markdown
> Aggregate functions are those that operate on a set of rows and return a single value. The example data has been repeated here to make it easier to understand the results.
> 
> Note that *NULL* values are not included in the `COUNT()` of a column that contains *NULL* values. `COUNT(*)` returns 7 while `COUNT(b)` returns 4.
> ```

How about we format these notes as a bulleted list? Perhaps something like:

Note the following:

- `NULL` values are not included in the `COUNT()` of a column that contains `NULL` values. `COUNT(*)` returns 7 while `COUNT(b)` returns 4.
- `NULL` values are not considered as high or low values in `MIN()` or `MAX()`.
- The `AVG(b)` function returns `SUM(b)/COUNT(b)`,  which is different than `AVG(*)` as `NULL` values are not considered in the `COUNT(b)` of rows.  Refer to the [`NULL`s as Other Values](#nulls-as-other-values) section below.

---

*[null-handling.md, line 292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ6Bk13y6LTOvtl_dPh:-KJ6Bk14q9e-0grYqxqP:-1821557150) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L292)):*
> ```Markdown
> ## See Also
> 
> IFNULL()
> ```

Unfortunately, it's not yet possible to link directly to a specific function, but perhaps you could link to the page. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/333#-:-KJ6C26X7UO3r6HZatth:-1846568017)*

**Comment by uptimeDBA** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[null-handling.md, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ68_xWf7qu40vEkyBR:-KJCXRNqe8erT1UJl0Ed:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L6)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Let's code-format `NULL` here and anywhere else it shows up in the text. 
</details>
Done.

---

*[null-handling.md, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ698iSF3uevz3QTv_5:-KJCXgMCVAX0lnQNh25n:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L142)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> How about we format these notes as a bulleted list? Perhaps something like:
> 
> Note the following:
> 
> - `NULL` values are not included in the `COUNT()` of a column that contains `NULL` values. `COUNT(*)` returns 7 while `COUNT(b)` returns 4.
> - `NULL` values are not considered as high or low values in `MIN()` or `MAX()`.
> - The `AVG(b)` function returns `SUM(b)/COUNT(b)`,  which is different than `AVG(*)` as `NULL` values are not considered in the `COUNT(b)` of rows.  Refer to the [`NULL`s as Other Values](#nulls-as-other-values) section below.
</details>
Done.

---

*[null-handling.md, line 292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ6Bk13y6LTOvtl_dPh:-KJCY07Pr0WJdGh4l5qp:1583107231) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L292)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Unfortunately, it's not yet possible to link directly to a specific function, but perhaps you could link to the page. 
</details>
I didn't link to the functions-and-operations page because `IFNULL()` is not listed there. I think  we are getting close to needing at least stub pages for all functions/operators like we have for SQL commands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/333)*

**Comment by jseldess** [comment]
*[null-handling.md, line 292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/333#-KJ6Bk13y6LTOvtl_dPh:-KJCvUcu94G19PNX_UnZ:-1798870400) ([raw file](https://github.com/cockroachdb/docs/blob/a0a33c171400bf4f9a1c2743255139f478a9e76b/null-handling.md#L292)):*
<details><summary><i>Previously, uptimeDBA (Paul Steffensen) wrote…</i></summary>
> I didn't link to the functions-and-operations page because `IFNULL()` is not listed there. I think  we are getting close to needing at least stub pages for all functions/operators like we have for SQL commands.
</details>
I see. Just spoke with Matt Jibson about this. Opened an issue to get special SQL functions like this added to the docs: https://github.com/cockroachdb/docs/issues/346. 

I agree that we need to make progress soon on functions docs. We're going to try to auto-generate a lot of it from the code. I'm syncing with Matt on this soon, so I can get back to you with details, if you like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/333)*

**Comment by jseldess** [comment]
Updates look great. I'll merge and publish soon. Thanks again!

<details><summary><i>Previously, jseldess wrote…</i></summary>
> LGTM, Paul. Thanks for this contribution. Let me get a dev to review as well.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/333#-:-KJCvwbivSV5M2doQ1WO:1063459168)*

**Comment by jseldess** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/333)*

**Pull request merged**
