### PR TITLE
Refresh 2.0 functions and operators doc

### LINKED ISSUE #2345: Functions and Operators Doc Update
Re: [Functions and Operators](https://cockroachlabs.com/docs//v2.0/functions-and-operators.html)

List of functions is missing sequence functions:

```
nextval('sequence_name')
currval('sequence_name')
lastval()
setval('sequence_name', value, is_called)
```

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #2345

### CODE REVIEW

**Comment by jseldess** [comment]
Note: TC is failing on some links pointing to a not-yet-existing page for the `TIME` type. That page is coming soon: https://github.com/cockroachdb/docs/pull/2336

**Comment by andreimatei** [comment]
:lgtm:

I don't see any sequence functions in here...

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2348#-:-L2WPM5UWTazq65ePf9i:b-czei6q)*

**Comment by lhirata** [comment]
Sequence functions show up in V2.0

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2348#-:-L2WSRxU3EjgdOXb_pUJ:b7xwy48)*

**Comment by andreimatei** [comment]
Ah sorry, I think reviewable screwed me; I see them now.
It all LGTM but keep in mind that I think we should document the interaction of these functions with parallel execution somewhere.
And possibly the interactions with transactions too, as is being discussed now on eng@.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2348#-:-L2WV0ZiZmezTDjXZsXh:b-5iwf95)*

**Comment by jseldess** [comment]
TFTR, @andreimatei. Once that @eng discussion comes to consensus, we'll work on a follow-up. 

Overriding TC despite the broken `TIME` links, since those docs are imminent.

**Pull request merged**
