### PR TITLE
Style guide fixit day updates [WIP]

### LINKED ISSUE #3248: Style Guide (Part 2/4)
Docs to cover:
- `build-an-app-with-cockroachdb.md` to `experimental-audit.md`

To do:
- Change H2+ to sentence case
- Add `{% include copy-clipboard.html %}` where necessary
- Edit tone for examples (Outlined in [Language and Tone](https://github.com/cockroachdb/docs/blob/master/STYLE.md#language-and-tone): "For tutorials, training, and examples, use the first-person plural tense (e.g., we, let's). These docs should be conversational, as if they are teaching the user." )
- If you are feeling ambitious, use the [prose linter](https://github.com/cockroachdb/docs/pull/3194) in the CLI to find hyperbolic language in your files or from your PR's TC build log, and evaluate whether each instance should be updated accordingly.

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Closes #3248 

Style guide FixitDay updates:
- Change H2+ to sentence case
- Add {% include copy-clipboard.html %} where necessary
- Fix formatting broken by the copy-to-clipboard widget
- Other minor style updates.

### CODE REVIEW

**Comment by lhirata** [comment]
Review status: 0 of 49 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[v2.1/column-families.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQd8pT8sFAmZPNByyP:-LEQd8pT8sFAmZPNByyQ:bsbh2st) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/column-families.md#L27)):*
> ```Markdown
> For example, let's say we want to create a table to store an immutable blob of data (`data BYTES`) with a last accessed timestamp (`last_accessed TIMESTAMP`). Because we know that the blob of data will never get updated, we use the `FAMILY` keyword to break it into a separate column family:
> 
> {% include copy-clipboard.html %}
> ```

I think you need to add backslashes at the end of each code block line in order for somebody to copy/paste correctly 

---

*[v2.1/commit-transaction.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdQtt9nWXg1MGq24k:-LEQdQtt9nWXg1MGq24l:b-on7feu) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/commit-transaction.md#L38)):*
> ```Markdown
> 
> {% include copy-clipboard.html %}
> ~~~ sql
> ```

I think this need to be split into a code block for each command

---

*[v2.1/create-security-certificates.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdizl2rsunVC9QwJr:-LEQdizl2rsunVC9QwJs:b-ivijmg) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-security-certificates.md#L46)):*
> ```Markdown
> `node.crt`   | Server certificate
> `node.key`   | Key for server certificate
> `client.<user>.crt` | Client certificate for `<user>` (for example: `client.root.crt` for user `root`)
> ```

Suggestion: use "i.e.," instead of "for example"

---

*[v2.1/create-view.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQe-LH-_oXR6O2YEnK:-LEQe-LH-_oXR6O2YEnL:b-fku5s0) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-view.md#L56)):*
> ```Markdown
> 
> {% include copy-clipboard.html %}
> ~~~ sql
> ```

Needs backslashes at the end of each line (I'll add this to the Style Guide)

---

*[v2.1/debug-zip.md, line 32 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQf7g13g6bdqv2UZCz:-LEQf7g13g6bdqv2UZD-:b73snij) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/debug-zip.md#L32)):*
> ```Markdown
> - If you experience severe or difficult-to-reproduce issues with your cluster, Cockroach Labs might ask you to send us your cluster's debugging information using `cockroach debug zip`.
> 
> {{site.data.alerts.callout_danger}}The file produced by <code>cockroach debug zip</code> can contain highly sensitive, unanonymized information, such as usernames, passwords, and your table's data. You should share this data only with Cockroach Labs developers and only after determining the most secure method of delivery.{{site.data.alerts.end}}
> ```

Callouts can be written in Markdown if you move the liquid tags to their own lines

---

*[v2.1/delete.md, line 100 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfJP70ldmXxx3a4-p:-LEQfJP70ldmXxx3a4-q:b-mrljey) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/delete.md#L100)):*
> ```Markdown
> As you can see, one difference is that `TRUNCATE` does not return the number of rows it deleted.
> 
> {{site.data.alerts.callout_info}}The <code>TRUNCATE</code> statement removes all rows from a table by dropping the table and recreating a new table with the same name. This is much more performant than deleting each of the rows. {{site.data.alerts.end}}
> ```

Same as above (Although, I don't think this isn't urgent since it renders the same for the user)

---

*[v2.1/float.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfsY1ACugRbLFnfBG:-LEQfsY1ACugRbLFnfBH:bkiayvh) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/float.md#L94)):*
> ```Markdown
> ~~~
> 
> ## Supported casting & conversion
> ```

Change & to "and"

---

*[v2.1/inet.md, line 81 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfvNwDCLCbsZJdeg5:-LEQfvNwDCLCbsZJdeg6:bkiayvh) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/inet.md#L81)):*
> ```Markdown
> ~~~
> 
> ## Supported casting & conversion
> ```

Change & to "and"

---

*[v2.1/int.md, line 91 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfyCxENNbo7LGLgFR:-LEQfyCxENNbo7LGLgFS:bkiayvh) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/int.md#L91)):*
> ```Markdown
> ~~~
> 
> ## Supported casting & conversion
> ```

Change & to "and"

---

*[v2.1/interval.md, line 89 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg02E1junoCA40W20:-LEQg02E1junoCA40W21:bkiayvh) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/interval.md#L89)):*
> ```Markdown
> ~~~
> 
> ## Supported casting & conversion
> ```

Change & to "and"

---

*[v2.1/jsonb.md, line 189 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg2WxDQQKHK_29ZWF:-LEQg2WxDQQKHK_29ZWG:bkiayvh) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/jsonb.md#L189)):*
> ```Markdown
> {% include computed-columns/jsonb.md %}
> 
> ## Supported casting & conversion
> ```

Change & to "and"

---

*[v2.1/string.md, line 88 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg4cT1yfTvRvNoKKK:-LEQg4cT1yfTvRvNoKKL:bqj2c5v) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/string.md#L88)):*
> ```Markdown
> ~~~
> 
> ## Supported casting & conversion
> ```

Change to "and"

---

*[v2.1/timestamp.md, line 98 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg7QHB2MgbaUVETjQ:-LEQg7QHB2MgbaUVETjR:bqj2c5v) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/timestamp.md#L98)):*
> ```Markdown
> ~~~
> 
> ## Supported casting & conversion
> ```

Change to "and"

---

*[v2.1/uuid.md, line 110 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg8lyCyPP6NcDLMnb:-LEQg8lyCyPP6NcDLMnc:bqj2c5v) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/uuid.md#L110)):*
> ```Markdown
> {% include faq/auto-generate-unique-ids_v1.1.html %}
> 
> ## Supported casting & conversion
> ```

Change to "and"

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by lhirata** [comment]
:lgtm: , with some minor edits!

---

Review status: 0 of 49 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263#-:-LEQgEefEngw_lx1_-Pn:byqku8o)*

**Comment by Amruta-Ranade** [comment]
*[v2.1/column-families.md, line 27 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQd8pT8sFAmZPNByyP:-LEQjY7m6Mwgj1DC0Lf9:b-j6ue52) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/column-families.md#L27)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

I think you need to add backslashes at the end of each code block line in order for somebody to copy/paste correctly 
</blockquote></details>

I don't think it's a requirement. I checked in the SQL shell..the copy-to-clipboard function works fine without the backlashes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by Amruta-Ranade** [comment]
*[v2.1/float.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfsY1ACugRbLFnfBG:-LEQnqcLCaAZkNraVTkW:bu2orx6) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/float.md#L94)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change & to "and"
</blockquote></details>

Gah! I had one whole commit just for "&" to "and" changes, and it didn't show up  here :cry: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by Amruta-Ranade** [comment]
*[v2.1/create-security-certificates.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdizl2rsunVC9QwJr:-LEQk17S-Vv3isOuuu9T:bm1rjsw) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-security-certificates.md#L46)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Suggestion: use "i.e.," instead of "for example"
</blockquote></details>

But it _is_ an example :thinking: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by Amruta-Ranade** [comment]
*[v2.1/commit-transaction.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdQtt9nWXg1MGq24k:-LEQjmWK0UrlF1X1gR3q:b-eeqlth) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/commit-transaction.md#L38)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

I think this need to be split into a code block for each command
</blockquote></details>

Because it's a transaction, I think it should be one code block

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by Amruta-Ranade** [comment]
Review status: 0 of 49 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[v2.1/float.md, line 94 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfsY1ACugRbLFnfBG:-LEQpizHCXAQ7VHiMtYT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/float.md#L94)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

Gah! I had one whole commit just for "&" to "and" changes, and it didn't show up  here :cry: 
</blockquote></details>

Done.

---

*[v2.1/inet.md, line 81 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfvNwDCLCbsZJdeg5:-LEQpjsz-50U1We1kgCj:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/inet.md#L81)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change & to "and"
</blockquote></details>

Done.

---

*[v2.1/int.md, line 91 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQfyCxENNbo7LGLgFR:-LEQpkgJEl41-5DHfVGS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/int.md#L91)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change & to "and"
</blockquote></details>

Done.

---

*[v2.1/interval.md, line 89 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg02E1junoCA40W20:-LEQplRU8EG149__EATc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/interval.md#L89)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change & to "and"
</blockquote></details>

Done.

---

*[v2.1/jsonb.md, line 189 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg2WxDQQKHK_29ZWF:-LEQplxe1Q5VwmurkFn1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/jsonb.md#L189)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change & to "and"
</blockquote></details>

Done.

---

*[v2.1/string.md, line 88 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg4cT1yfTvRvNoKKK:-LEQpmZDA7WykAdehAYH:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/string.md#L88)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change to "and"
</blockquote></details>

Done.

---

*[v2.1/timestamp.md, line 98 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg7QHB2MgbaUVETjQ:-LEQpn-20HxATDgCzzdQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/timestamp.md#L98)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change to "and"
</blockquote></details>

Done.

---

*[v2.1/uuid.md, line 110 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQg8lyCyPP6NcDLMnb:-LEQpnXP-gO9ZqIsioK0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/uuid.md#L110)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Change to "and"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by lhirata** [comment]
Review status: 0 of 49 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[v2.1/create-security-certificates.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdizl2rsunVC9QwJr:-LEQrkcR4il7XHTt2xnB:br9165l) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-security-certificates.md#L46)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

But it _is_ an example :thinking: 
</blockquote></details>

Oops, I meant "e.g.," but I suppose that's just a style preference so up to you!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by lhirata** [comment]
Review status: 0 of 49 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[v2.1/commit-transaction.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdQtt9nWXg1MGq24k:-LEQt-4w-m8snK8KWdhA:b-u6zmsa) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/commit-transaction.md#L38)):*
<details><summary><i>Previously, Amruta-Ranade (Amruta Ranade) wrote…</i></summary><blockquote>

Because it's a transaction, I think it should be one code block
</blockquote></details>

Good point. I think I did that in my PR so I'll update mine back.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by jseldess** [comment]
:lgtm:

---

Review status: 0 of 50 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[v2.1/commit-transaction.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdQtt9nWXg1MGq24k:-LEUpWR_BEi0VBwyeprf:b-hwv7hh) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/commit-transaction.md#L38)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Good point. I think I did that in my PR so I'll update mine back.
</blockquote></details>

I think it'd actually be nice to split this into multiple blocks because the user would enter each of these one at a time anyway. As is, it can't be pasted into the sql shell.

---

*[v2.1/create-security-certificates.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdizl2rsunVC9QwJr:-LEUpkQgBizx9weGRNqs:b1ox95a) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-security-certificates.md#L46)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Oops, I meant "e.g.," but I suppose that's just a style preference so up to you!
</blockquote></details>

Yeah, we should probably have a documented convention. For this type of "example", where it's not in a sentence, I personally prefer `e.g.,`. In any case, if you stick with `for example`, please replace the colon with a comma.

---

*[v2.1/create-view.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQe-LH-_oXR6O2YEnK:-LEUq9yg5rMfzXhpxLRj:b-giepvr) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-view.md#L56)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Needs backslashes at the end of each line (I'll add this to the Style Guide)
</blockquote></details>

We all clarified that we don't use backslashes in multi-line SQL examples, so this is good as-is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263#-:-LEUrNDV-fX-dba4Anl3:bnfp4nl)*

**Comment by Amruta-Ranade** [comment]
*[v2.1/commit-transaction.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdQtt9nWXg1MGq24k:-LEjZ6h_6nnGUVxb9tsT:b-mf0jlc) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/commit-transaction.md#L38)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I think it'd actually be nice to split this into multiple blocks because the user would enter each of these one at a time anyway. As is, it can't be pasted into the sql shell.
</blockquote></details>

I tried copy-pasting a transaction as a single code block, and it works fine. IMO, it makes sense to have it as a single code block.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Comment by Amruta-Ranade** [comment]
*[v2.1/create-security-certificates.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3263#-LEQdizl2rsunVC9QwJr:-LEjZv9z7iBtKQxSPF53:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/20dcd5433defb7b0be2514e709d8a42e26ca4287/v2.1/create-security-certificates.md#L46)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Yeah, we should probably have a documented convention. For this type of "example", where it's not in a sentence, I personally prefer `e.g.,`. In any case, if you stick with `for example`, please replace the colon with a comma.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3263)*

**Pull request merged**
