### PR TITLE
Managed docs UI

### PR DESCRIPTION
**Pull request by j-low**
__[description]__
* User interface for rollout of managed service

cc: @jseldess

### CODE REVIEW

**Comment by jseldess** [comment]
@j-low, @benesch, I can't get the `CockroachDB` and `Managed CockroachDB` links in the secondary topnav to work. Also, @benesch, even after rebasing against master, I'm seeing the link checker problems again. Can you help?

One other problem to solve after the above: Getting "CockroachDB" to be highlighted in the secondary top nav when on a page in the standard docs, and getting "Managed CockroachDB" to be highlighted in the secondary top nav when on a page in the managed docs.

**Comment by jseldess** [comment]
@benesch, I figured out the htmltest errors. Just needed to add alt attributes to the new CockroachDB /Managed CockroachDB nav images. 

Remaining things I'd love your help on:
1. I hard-coded the CockroachDB / Managed CockroachDB links. That's not ideal at all, of course. Can you see a way around that?
2. We need to find a way to highlight CockroachDB when the user is on those pages, and Managed CockroachDB when the user is on those pages.

**Comment by benesch** [comment]
Ok, I think I've taken care of both issues. PTAL.

**Comment by jseldess** [comment]
Nice! Thanks very much @benesch! There's a redirect happening whenever you click `CockroachDB` or `Managed CockroachDB`, but that's probably ok.

**Comment by benesch** [comment]
Yeah, not seeing a great way around that redirect. Now that we use Netlify it should be possible to avoid the client side "redirecting you now" flicker. Perhaps something @mjibson could look into.

**Comment by benesch** [comment]
Actually, maybe there is. One sec.

**Comment by jseldess** [comment]
@j-low, one more minor problem:

When you click an anchor link, the heading ends up hidden behind the new nav:

screen shot 2018-10-26 at 3 14 46 pm

**Pull request merged**
