### PR TITLE
Fix meta descriptions for SEO

### PR DESCRIPTION
**Pull request by jseldess**
Addresses https://github.com/cockroachdb/docs/issues/10183#issuecomment-813406293, e.g.,

- Shortens meta descriptions to under 160 characters
- Removes unnecessary pages without meta descriptions
- Increases length of meta descriptions less than 50 characters

Also adds sidebar highlighting for 20.2.6 release notes.

### CODE REVIEW

**Review by yingzhuchin — APPROVED** [review]
Ran your branch through the tests and it passes all checks. LGTM! Note though per #10183 that the checks are currently run on v21.1 only. Do you want the checks to be run on all version folders, or just latest stable and/or dev?

**Comment by jseldess** [comment]
TFTR, @yingzhuchin! I think we may as well run on all versions and see what we get?

**Comment by yingzhuchin** [comment]
Sorry, missed one with >160 characters: `life-of-a-distributed-transaction.md`. Meanwhile, working on beefing up the tests to check all versions.

**Comment by yingzhuchin** [comment]
Okay! Ran all versions through checks, and here's what we have:

Missing summaries:

     'v1.0/explore-the-admin-ui.md',
      'v1.0/keywords-and-identifiers.md',
      'v1.0/orchestration.md',
      'v1.0/table.md',
      'v1.0/views.md',
      'v1.1/admin-ui-databases-page.md',
      'v1.1/admin-ui-jobs-page.md',
      'v1.1/admin-ui-runtime-dashboard.md',
      'v1.1/architecture/distribution-layer.md',
      'v1.1/architecture/overview.md',
      'v1.1/architecture/replication-layer.md',
      'v1.1/architecture/sql-layer.md',
      'v1.1/architecture/storage-layer.md',
      'v1.1/architecture/transaction-layer.md',
      'v1.1/keywords-and-identifiers.md',
      'v1.1/table.md',
      'v1.1/views.md',
      'v19.1/admin-ui-cluster-overview-page.md',
      'v19.1/admin-ui-custom-chart-debug-page.md',
      'v19.1/admin-ui-databases-page.md',
      'v19.1/admin-ui-debug-pages.md',
      'v19.1/admin-ui-jobs-page.md',
      'v19.1/admin-ui-runtime-dashboard.md',
      'v19.1/admin-ui-statements-page.md',
      'v19.1/create-sequence.md',
      'v19.1/demo-serializable.md',
      'v19.1/drop-sequence.md',
      'v19.1/keywords-and-identifiers.md',
      'v19.1/views.md',
      'v19.2/admin-ui-cluster-overview-page.md',
      'v19.2/admin-ui-custom-chart-debug-page.md',
      'v19.2/admin-ui-databases-page.md',
      'v19.2/admin-ui-debug-pages.md',
      'v19.2/admin-ui-jobs-page.md',
      'v19.2/admin-ui-runtime-dashboard.md',
      'v19.2/admin-ui-statements-page.md',
      'v19.2/create-sequence.md',
      'v19.2/demo-serializable.md',
      'v19.2/drop-sequence.md',
      'v19.2/keywords-and-identifiers.md',
      'v19.2/views.md',
      'v2.0/admin-ui-custom-chart-debug-page.md',
      'v2.0/admin-ui-databases-page.md',
      'v2.0/admin-ui-jobs-page.md',
      'v2.0/admin-ui-runtime-dashboard.md',
      'v2.0/create-sequence.md',
      'v2.0/drop-sequence.md',
      'v2.0/keywords-and-identifiers.md',
      'v2.0/table.md',
      'v2.0/views.md',
      'v2.1/admin-ui-cluster-overview-page.md',
      'v2.1/admin-ui-custom-chart-debug-page.md',
      'v2.1/admin-ui-databases-page.md',
      'v2.1/admin-ui-debug-pages.md',
      'v2.1/admin-ui-jobs-page.md',
      'v2.1/admin-ui-runtime-dashboard.md',
      'v2.1/admin-ui-statements-page.md',
      'v2.1/create-sequence.md',
      'v2.1/demo-serializable.md',
      'v2.1/drop-sequence.md',
      'v2.1/keywords-and-identifiers.md',
      'v2.1/views.md',
      'v20.1/admin-ui-cluster-overview-page.md',
      'v20.1/admin-ui-custom-chart-debug-page.md',
      'v20.1/admin-ui-databases-page.md',
      'v20.1/admin-ui-debug-pages.md',
      'v20.1/admin-ui-jobs-page.md',
      'v20.1/admin-ui-network-latency-page.md',
      'v20.1/admin-ui-runtime-dashboard.md',
      'v20.1/admin-ui-statements-page.md',
      'v20.1/create-sequence.md',
      'v20.1/demo-serializable.md',
      'v20.1/drop-sequence.md',
      'v20.1/keywords-and-identifiers.md',
      'v20.1/views.md'

Summaries with <50 characters:

     'v1.0/cockroachdb-architecture.md',
      'v1.0/create-view.md',
      'v1.0/go-implementation.md',
      'v1.0/known-limitations.md',
      'v1.0/open-source.md',
      'v1.0/porting-postgres.md',
      'v1.0/select.md',
      'v1.0/stop-a-node.md',
      'v1.0/troubleshoot.md',
      'v1.1/admin-ui-access-and-navigate.md',
      'v1.1/create-view.md',
      'v1.1/enable-node-map.md',
      'v1.1/go-implementation.md',
      'v1.1/import.md',
      'v1.1/open-source.md',
      'v1.1/porting-postgres.md',
      'v1.1/select.md',
      'v1.1/selection-clauses.md',
      'v1.1/show-trace.md',
      'v19.1/admin-ui-access-and-navigate.md',
      'v19.1/architecture/overview.md',
      'v19.1/create-view.md',
      'v19.1/enable-node-map.md',
      'v19.1/performance-benchmarking-with-tpc-c.md',
      'v19.1/porting-postgres.md',
      'v19.2/admin-ui-access-and-navigate.md',
      'v19.2/architecture/overview.md',
      'v19.2/create-view.md',
      'v19.2/enable-node-map.md',
      'v19.2/performance-benchmarking-with-tpc-c-10k-warehouses.md',
      'v19.2/performance-benchmarking-with-tpc-c-1k-warehouses.md',
      'v19.2/performance.md',
      'v2.0/admin-ui-access-and-navigate.md',
      'v2.0/architecture/overview.md',
      'v2.0/create-view.md',
      'v2.0/enable-node-map.md',
      'v2.0/go-implementation.md',
      'v2.0/import.md',
      'v2.0/open-source.md',
      'v2.0/performance-benchmarking-with-tpc-c.md',
      'v2.0/porting-postgres.md',
      'v2.1/admin-ui-access-and-navigate.md',
      'v2.1/architecture/overview.md',
      'v2.1/create-view.md',
      'v2.1/enable-node-map.md',
      'v2.1/go-implementation.md',
      'v2.1/open-source.md',
      'v2.1/performance-benchmarking-with-tpc-c.md',
      'v2.1/porting-postgres.md',
      'v20.1/architecture/overview.md',
      'v20.1/create-view.md',
      'v20.1/enable-node-map.md',
      'v20.1/performance-benchmarking-with-tpc-c-10k-warehouses.md',
      'v20.1/performance-benchmarking-with-tpc-c-1k-warehouses.md',
      'v20.1/performance.md',
      'v20.2/architecture/overview.md',
      'v21.1/architecture/overview.md'

Summaries with >160 characters:

      'v19.1/architecture/life-of-a-distributed-transaction.md',
      'v19.1/changefeed-for.md',
      'v19.2/architecture/life-of-a-distributed-transaction.md',
      'v2.1/architecture/life-of-a-distributed-transaction.md',
      'v20.1/architecture/life-of-a-distributed-transaction.md',
      'v20.2/architecture/life-of-a-distributed-transaction.md',
      'v21.1/architecture/life-of-a-distributed-transaction.md'

**Comment by jseldess** [comment]
Yikes! OK, I don't have the time to fix all of those, so let's go with your initial suggestion and just run this against stable and dev versions for now, @yingzhuchin. Thank you!

**Comment by jseldess** [comment]
Done, @yingzhuchin. PTAL.

**Comment by yingzhuchin** [comment]
Looks good to me! I think you just have to pull in the broken link fixes from main branch, then all set to merge!

**Comment by jseldess** [comment]
OK, trying that.

**Pull request merged**
