### PR TITLE
v22.1 Known Limitations

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes DOC-3357 and DOC-3358

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`v22.1/known-limitations.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2IiX7f1iAWA5fCvZzq:-N2IiX7f1iAWA5fCvZzr:bfeb1i7) ([raw file](https://github.com/cockroachdb/docs/blob/013e6b3daa3bcc2c6d6f2e237490a71b3dc9d5a6/v22.1/known-limitations.md#L13)):*
> ```Markdown
> ## New limitations
> 
> ### Row-level TTL
> ```

@vy-ton can you review this section? 
___
*[`v22.1/known-limitations.md` line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2Ii_-687n7cJoz1s9s:-N2Ii_-687n7cJoz1s9t:b-syf31h) ([raw file](https://github.com/cockroachdb/docs/blob/013e6b3daa3bcc2c6d6f2e237490a71b3dc9d5a6/v22.1/known-limitations.md#L20)):*
> ```Markdown
> - The `ttl_expiration_expression` column is not yet supported. This would allow for an override expression for row-level TTL. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/76916)
> 
> ### The `split_column_families` and `resolved` options cannot be used on the same changefeed
> ```

@amruss can you review this section?

**Review by vy-ton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @vy-ton)

___
*[`v22.1/known-limitations.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2IiX7f1iAWA5fCvZzq:-N2MfoBWC_Ckr4ULz6ug:b-aw1vqz) ([raw file](https://github.com/cockroachdb/docs/blob/013e6b3daa3bcc2c6d6f2e237490a71b3dc9d5a6/v22.1/known-limitations.md#L13)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@vy-ton can you review this section? 
</blockquote></details>

Rich added a section below already - https://deploy-preview-13862--cockroachdb-docs.netlify.app/docs/v22.1/known-limitations.html#row-level-ttl-limitations 

Can we just bump it up?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vy-ton)

___
*[`v22.1/known-limitations.md` line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2IiX7f1iAWA5fCvZzq:-N2Nb9y19roaYUJni-JK:b46axnz) ([raw file](https://github.com/cockroachdb/docs/blob/013e6b3daa3bcc2c6d6f2e237490a71b3dc9d5a6/v22.1/known-limitations.md#L13)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

Rich added a section below already - https://deploy-preview-13862--cockroachdb-docs.netlify.app/docs/v22.1/known-limitations.html#row-level-ttl-limitations 

Can we just bump it up?
</blockquote></details>

Done! Thanks
___
*[`v22.1/known-limitations.md` line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2Ii_-687n7cJoz1s9s:-N2NcNRJCdxLPwQSo6Pu:b-ki5d9z) ([raw file](https://github.com/cockroachdb/docs/blob/013e6b3daa3bcc2c6d6f2e237490a71b3dc9d5a6/v22.1/known-limitations.md#L20)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@amruss can you review this section?
</blockquote></details>

Edited - no longer need review as it was previously reviewed in a different PR. Thanks!

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vy-ton)

___
*[`v22.1/known-limitations.md` line 19 at r3](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2Sfe8y9y-tUm4aDDde:-N2Sfe8y9y-tUm4aDDdf:b-svuoss) ([raw file](https://github.com/cockroachdb/docs/blob/e61d06505262f8d954e3f1a20e057a605f44a5d7/v22.1/known-limitations.md#L19)):*
> ```Markdown
> [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/71502)
> 
> ### Multiple CTEs with mutations on the same row can cause inconsistency
> ```

@rytaft - can you review the 3 SQL known limitations here? Thanks!

**Review by lnhsingh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vy-ton)

**Comment by rytaft** [comment]
*[`v22.1/known-limitations.md` line 19 at r3](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2Sfe8y9y-tUm4aDDde:-N2dZAoe8tr2RZieoKGm:b-gev12z) ([raw file](https://github.com/cockroachdb/docs/blob/e61d06505262f8d954e3f1a20e057a605f44a5d7/v22.1/known-limitations.md#L19)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@rytaft - can you review the 3 SQL known limitations here? Thanks!
</blockquote></details>

@michae2 can you please review these? Thanks!

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh and @michae2)

___
*[`v22.1/known-limitations.md` line 21 at r3](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2lhGR99GijOmciLLwR:-N2m-nVl-KMfkg33-t-5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/e61d06505262f8d954e3f1a20e057a605f44a5d7/v22.1/known-limitations.md#L21)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Nit: should the second upsert be capitalized and monospaced? E.g., `UPSERT`
</blockquote></details>

Done.

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh)

___
*[`v22.1/known-limitations.md` line 19 at r3](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2Sfe8y9y-tUm4aDDde:-N2m670M1Jz8uEwpo0rQ:bv0j09f) ([raw file](https://github.com/cockroachdb/docs/blob/e61d06505262f8d954e3f1a20e057a605f44a5d7/v22.1/known-limitations.md#L19)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

@michae2 can you please review these? Thanks!
</blockquote></details>

Yes, absolutely. Thank you for including these!
___
*[`v22.1/known-limitations.md` line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2m7GxQ8nJTdnykD4F2:-N2m7GxQ8nJTdnykD4F3:bxeriq4) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L21)):*
> ```Markdown
> ### Multiple CTEs with mutations on the same row can cause inconsistency
> 
> You can [`UPSERT`](upsert.html) the same row multiple times in a single statement using [common table expressions](common-table-expressions.html) (CTEs), which could lead to inconsistencies due to the `UPSERT` operator not reading its own writes.
> ```

This was the original issue, but the known limitation is not that the issue exists. The known limitation is that **statements containing multiple modification subqueries of the same table have been disallowed**, to _prevent_ this issue.

(Sorry I didn't make this clear when I tagged 70731. Maybe I should have tagged the PR disallowing these statements instead.)

Here's the full story:
* In [70731](https://github.com/cockroachdb/cockroach/issues/70731) we discovered that statements containing multiple modification subqueries mutating the same row (modifications of *any* kind, not just `UPSERT`) could cause corruption.
* In [70976](https://github.com/cockroachdb/cockroach/pull/70976) we disallowed these statements, unless cluster setting `sql.multiple_modifications_of_table.enabled` is true. The release note goes into some detail about which statements are disallowed, with examples.
* In [79677](https://github.com/cockroachdb/cockroach/pull/79677) we added a session setting, `enable_multiple_modifications_of_table`, that can be used instead of the cluster setting.

I don't think we need to tell the full story in known limitations. I think it would suffice to say that these particular statements are disallowed to prevent inconsistencies, with a link to 70731.
___
*[`v22.1/known-limitations.md` line 22 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2mFZoA3wRUg4P3mdh5:-N2mFZoA3wRUg4P3mdh6:b-dg4k50) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L22)):*
In a [comment on 70731](https://github.com/cockroachdb/cockroach/issues/70731#issuecomment-1130726891) @knz mentioned that we should _also_ document this related fact as a known limitation:

> **if multiple mutations inside the same statement affect different tables with FK relations and ON CASCADE clauses between them, the results will be different between pg and crdb**
___
*[`v22.1/known-limitations.md` line 27 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2mET4mEEpFDEg8LuP2:-N2mET4mEEpFDEg8LuP3:b-4pqrvc) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L27)):*
> ```Markdown
> ### Limit on the number of rows read or written by a single transaction
> 
> A [transaction](transactions.html#limit-the-number-of-rows-written-or-read-in-a-transaction) reading more than `transaction_rows_read_err` rows (or writing more than `transaction_rows_written_err` rows) fails with an error.
> ```

(Again, sorry for another confusing one. :slightly_smiling_face:) This is indeed how `transaction_rows_read_err` and `transaction_rows_written_err` work, but it is not the known limitation. The known limitation is that **transaction_rows_read_err and transaction_rows_written_err do not halt query execution**, they only return an error after query execution has finished, and results have been returned to the client.

There's more information in [70473](https://github.com/cockroachdb/cockroach/issues/70473).

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @lnhsingh, and @michae2)

___
*[`v22.1/known-limitations.md` line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2m7GxQ8nJTdnykD4F2:-N2mVELNBqwYOvNnueAI:b-oo1r70) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L21)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This was the original issue, but the known limitation is not that the issue exists. The known limitation is that **statements containing multiple modification subqueries of the same table have been disallowed**, to _prevent_ this issue.

(Sorry I didn't make this clear when I tagged 70731. Maybe I should have tagged the PR disallowing these statements instead.)

Here's the full story:
* In [70731](https://github.com/cockroachdb/cockroach/issues/70731) we discovered that statements containing multiple modification subqueries mutating the same row (modifications of *any* kind, not just `UPSERT`) could cause corruption.
* In [70976](https://github.com/cockroachdb/cockroach/pull/70976) we disallowed these statements, unless cluster setting `sql.multiple_modifications_of_table.enabled` is true. The release note goes into some detail about which statements are disallowed, with examples.
* In [79677](https://github.com/cockroachdb/cockroach/pull/79677) we added a session setting, `enable_multiple_modifications_of_table`, that can be used instead of the cluster setting.

I don't think we need to tell the full story in known limitations. I think it would suffice to say that these particular statements are disallowed to prevent inconsistencies, with a link to 70731.
</blockquote></details>

Edited - PTAL
___
*[`v22.1/known-limitations.md` line 22 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2mFZoA3wRUg4P3mdh5:-N2mVFJN-Z-Bls1hB3fy:bnaib0w) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L22)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

In a [comment on 70731](https://github.com/cockroachdb/cockroach/issues/70731#issuecomment-1130726891) @knz mentioned that we should _also_ document this related fact as a known limitation:

> **if multiple mutations inside the same statement affect different tables with FK relations and ON CASCADE clauses between them, the results will be different between pg and crdb**
</blockquote></details>

Added a note - can you take a look, I wasn't sure if my wording is correct.
___
*[`v22.1/known-limitations.md` line 27 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2mET4mEEpFDEg8LuP2:-N2mVyF7EnZs5l5ujALP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L27)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

(Again, sorry for another confusing one. :slightly_smiling_face:) This is indeed how `transaction_rows_read_err` and `transaction_rows_written_err` work, but it is not the known limitation. The known limitation is that **transaction_rows_read_err and transaction_rows_written_err do not halt query execution**, they only return an error after query execution has finished, and results have been returned to the client.

There's more information in [70473](https://github.com/cockroachdb/cockroach/issues/70473).
</blockquote></details>

Done.

**Comment by lnhsingh** [comment]
Merging for now so we have something up for the release. If anything needs to be updated, will open a fast follow PR. Thank you to everybody who reviewed!

**Review by michae2 — COMMENTED** [review]
Just a small nit from me, which can be addressed in following PR. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13862#-:-N2msRtJ8cxMlreE5q9g:b-gc3pi1)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[`v22.1/known-limitations.md` line 21 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2m7GxQ8nJTdnykD4F2:-N2mouJK9FAMkP3Bh7Nm:b-58y1yg) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Edited - PTAL
</blockquote></details>

Looks good. Thanks!
___
*[`v22.1/known-limitations.md` line 22 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2mFZoA3wRUg4P3mdh5:-N2mocOX3-CFs8pQ5j1F:b-ie4mj1) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L22)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Added a note - can you take a look, I wasn't sure if my wording is correct.
</blockquote></details>

I think this looks good. @knz, would you please also review this item? Thank you!
___
*[`v22.1/known-limitations.md` line 27 at r4](https://reviewable.io/reviews/cockroachdb/docs/13862#-N2mET4mEEpFDEg8LuP2:-N2mpNDU9SQF_tAvZUgG:b5wfaq8) ([raw file](https://github.com/cockroachdb/docs/blob/716f5def7d283e9c6f432efb1f717080ec55f5bb/v22.1/known-limitations.md#L27)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"do not halt query execution" is awkward, because "a transaction" is the subject of the sentence.

One idea is to change "but do not halt query execution" to something like "but not until the current query finishes executing and results have been returned to the client".

It might be more clear to make `transaction_rows_read_err` and `transaction_rows_written_err` the subject of the sentence. Then the limitation can be framed as a limitation of these settings, rather than a limitation of transactions.

**Pull request merged**
