### PR TITLE
Add Create a Free Cluster / Connect to a Free Cluster

### LINKED ISSUE #8967: Document Create a Cluster and Connect to a Cluster for Free Tier
We need to have documentation around CockroachCloud Free once we release it in January 2021. This document should include, but not be limited, to the following topics: 
- What is free tier?
-- Uniqueness of free tier (e.g. connection string confusion)
- What are the best use cases for free tier? 
- What are the limitations of free tier?
- Any other details that might come up from free tier feedback

The main epic to keep track of remaining work for free tier can be found here: [CC-2871](https://cockroachlabs.atlassian.net/browse/CC-2871)

Work with Jose for any questions.

### PR DESCRIPTION
**Pull request by lnhsingh**
This PR adds:
- Steps on how to create a free cluster
- How to connect to your free cluster
- Update the sidenav to default to the Free version of the above docs

Closes #8967

### CODE REVIEW

**Comment by lnhsingh** [comment]
Note: Once the [CC Free FAQ PR](https://github.com/cockroachdb/docs/pull/9413) is merged, I will link to that where relevant.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[cockroachcloud/connect-to-a-free-cluster.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqZaJiCnWOnlNTFqCt:-MRqZaJiCnWOnlNTFqCu:b-ia8rec) ([raw file](https://github.com/cockroachdb/docs/blob/4134a86382a200b8bb78c7e8ccaaddeaf34ec734/cockroachcloud/connect-to-a-free-cluster.md#L25)):*
> ```Markdown
> 1. In the top right corner of the CockroachCloud Console, click the **Connect** button.
> 
>     The **Connection info** modal displays on the **Step 2. Connect > CockroachDB client** subtab.
> ```

Note: this is kinda weird UX - it seems like clicking the button should open the modal in Step 1. Will chat with Rachel and file an issue / revise this part in the docs later (if needed)

**Review by kannanlakshmi — APPROVED** [review]
LGTM!

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[cockroachcloud/connect-to-a-free-cluster.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqZaJiCnWOnlNTFqCt:-MRu3p7c07ijTd0UWqHB:bi7ai2g) ([raw file](https://github.com/cockroachdb/docs/blob/4134a86382a200b8bb78c7e8ccaaddeaf34ec734/cockroachcloud/connect-to-a-free-cluster.md#L25)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Note: this is kinda weird UX - it seems like clicking the button should open the modal in Step 1. Will chat with Rachel and file an issue / revise this part in the docs later (if needed)
</blockquote></details>

Followed up with Rachel/Jeremy. This is expected behavior and needs to be documented this way. This UX might be updated in the future.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[cockroachcloud/connect-to-your-cluster.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3NRK7BznB3QIHA0oF:-MS3NRK8DWH1CTFmFebj:b69bv9f) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L51)):*
> ```Markdown
>      {{site.data.alerts.end}}
> 
>      To add a range of IP addresses, use the CIDR (Classless Inter-Domain Routing) notation. The CIDR notation is constructed from an IP address (e.g., `192.168.15.161`), a slash (`/`), and a number (e.g., `32`). The number is the count of leading 1-bits in the network identifier. In the example above, the IP address is 32-bits and the number is `32`, so the full IP address is also the network identifier. For more information, see Digital Ocean's [Understanding IP Addresses, Subnets, and CIDR Notation for Networking](https://www.digitalocean.com/community/tutorials/understanding-ip-addresses-subnets-and-cidr-notation-for-networking#cidr-notation).
> ```

question from @emily-horing on #9469: 

```I thought all the allowlisted IPs needed to use CIDR notation. Is that not the case for your local/app network?```
___
*[cockroachcloud/connect-to-your-cluster.md, line 53 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3Nqdr2bLAGkDIPArP:-MS3Nqds0y1r5lPpe6Af:bqaxd4z) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L53)):*
> ```Markdown
>      To add a range of IP addresses, use the CIDR (Classless Inter-Domain Routing) notation. The CIDR notation is constructed from an IP address (e.g., `192.168.15.161`), a slash (`/`), and a number (e.g., `32`). The number is the count of leading 1-bits in the network identifier. In the example above, the IP address is 32-bits and the number is `32`, so the full IP address is also the network identifier. For more information, see Digital Ocean's [Understanding IP Addresses, Subnets, and CIDR Notation for Networking](https://www.digitalocean.com/community/tutorials/understanding-ip-addresses-subnets-and-cidr-notation-for-networking#cidr-notation).
> 
> 6. Select whether the network can connect to the cluster's **UI**, **SQL** client, or both.
> ```

From Emily in #9469: ```We should update to use the same language in the UI. I think we say "DB Console" and "SQL access" or something like that now```
___
*[cockroachcloud/connect-to-your-cluster.md, line 121 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3OZF97bNqjlHCThID:-MS3OZF97bNqjlHCThIE:b-zovid) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L121)):*
> ```Markdown
>     To connect to your cluster using the [in-built SQL client](#use-the-cockroachdb-sql-client), use the command displayed on the **CockroachDB Client** tab.
> 
>     To connect to your cluster [using a Postgres ORM or driver](#use-a-postgres-driver-or-orm), use either the **Connection String** or the **Parameters** as required by your ORM or driver.
> ```

From Emily in #9469: I think technically we labeled them "Your app" and "your tool" but I think we're actually going to change it back to "connection string" and "parameters" after some initial feedback. But FYI that's not what it says in the UI as of today
___
*[cockroachcloud/connect-to-your-cluster.md, line 141 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3PIKjCIpC5Scmnqxs:-MS3PIKjCIpC5Scmnqxt:bg4prqz) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L141)):*
> ```Markdown
> On the machine where you want to run the CockroachDB SQL client:
> 
> 1. [Download the CockroachDB binary](../stable/install-cockroachdb.html):
> ```

From Emily in #9469: ```We let you download this directly from the connect modal. Maybe worth noting here?```

**Review by rmloveland — APPROVED** [review]
LGTM, had some comments that could be taken as "improvements for later" depending on timing

**Review by lnhsingh — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481#-:-MS44W2y5zkcOswmBHJV:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh and @rmloveland)

___
*[_includes/sidebar-data-cockroachcloud.json, line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNT-r2-14:-MS3sBtKEKiULKRE-VVx:bws23nx) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/_includes/sidebar-data-cockroachcloud.json#L14)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Does this need redirecting anywhere?
</blockquote></details>

Nope, should be ok because the old file still exists, we are just defaulting to this new one in the sidebar
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 18 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-18:-MS3sPLgBReVbUlLjIec:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L18)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Non-blocking:

Might rephrase as actions, e.g.

1. Create free cluster
2. leave as-is
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 66 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-66:-MS3sXoG2T9LDRyMtJz-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L66)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

(that is, needs a starting slash)
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 69 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-69:-MS3sq0hEJliAtq8UiEk:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L69)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Slightly more accurate as "Install the CockroachDB binary"
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 70 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-70:-MS3ss4I0_AliuMHC-ZW:b-2q33ul) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L70)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

provided where?  by the UI dialog? 
</blockquote></details>

Yah, provided by the UI. Updated.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 78 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-78:-MS3tJcSD8as-Sh9EVO7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L78)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

docs for SQL users page to link to?
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 84 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-84:-MS3tlEd-oYWdUrPNv5n:b-c6vh8p) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L84)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

The `data-scope` for "your-app" and "your-tool" appear to be swapped.  This section has the tool instructions, I think (?), and the other one has code samples for apps (?)
</blockquote></details>

Ah, you're right. This is actually a bug in the UI too - the descriptions for each type of connection are wrong. Fixed in the docs and filed a bug.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 99 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-99:-MS3uNCj6AoJhVsmDXmq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L99)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

This and all other uses of directories need to use a slash at the beginning, e.g.

`mv /path/to/cc-ca.crt /path/to/certs`
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 106 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-106:-MS3uQSf07Sf83ngb3-O:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L106)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Missing slash at start of path
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 119 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-119:-MS3uVBw6SDDO69pGsh_:b2a6wrn) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L119)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

In general it feels like (in a perfect world with more time?) the right thing to do in this section is to use includes to share the examples with https://www.cockroachlabs.com/docs/v20.2/connect-to-the-database, the SQLAlchemy doc, etc. to make sure errors don't creep into the code snippets

(I suspect there is not time for this now, so maybe something for later)
</blockquote></details>

Yeah, good thinking. I just ripped all this out and replaced with links to the updated Sample Apps docs
___
*[cockroachcloud/connect-to-your-cluster.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3NRK7BznB3QIHA0oF:-MS3lTp93oZ3fb5mfWQi:b-y7can) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L51)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

question from @emily-horing on #9469: 

```I thought all the allowlisted IPs needed to use CIDR notation. Is that not the case for your local/app network?```
</blockquote></details>

Not sure about this - @thtruo is this something you can answer?
___
*[cockroachcloud/connect-to-your-cluster.md, line 53 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3Nqdr2bLAGkDIPArP:-MS3s37r0u18go5nNn4m:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L53)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

From Emily in #9469: ```We should update to use the same language in the UI. I think we say "DB Console" and "SQL access" or something like that now```
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-your-cluster.md, line 121 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3OZF97bNqjlHCThID:-MS3s24-AWR34pkfjJBe:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L121)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

From Emily in #9469: I think technically we labeled them "Your app" and "your tool" but I think we're actually going to change it back to "connection string" and "parameters" after some initial feedback. But FYI that's not what it says in the UI as of today
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-your-cluster.md, line 141 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3PIKjCIpC5Scmnqxs:-MS3ou_Z8NH5t6wEG8QA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L141)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

From Emily in #9469: ```We let you download this directly from the connect modal. Maybe worth noting here?```
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[cockroachcloud/connect-to-a-free-cluster.md, line 120 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-120:-MS4GLfdCLV1uAHOyMu5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L120)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

This says "your tool" but this section appears to be about app development code samples
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 122 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-122:-MS4GVmr-RiV4qHujuvn:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L122)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

should probably link to the 'connection parameters' doc page in case users mess up the conn string, or if it doesn't work for them for some other reason we can't know in advance
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 133 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-133:-MS4GYGLBikjH55d2PSe:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L133)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

IDK what our philosophy is for Cloud/CRDB split in docs (feels like we don't know yet?), but I think linking to our CRDB docs for these drivers will be more useful to folks trying to use these with CRDB.  These snippets are good but will not be enough to run and test your connection with

Probably same comment for any language/library combo mentioned here
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 161 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-161:-MS4GZe80bKo_goYwPzV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L161)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

This can def be an include with what's on the SQLAlchemy page (future work?)
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 175 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-175:-MS4GZyW12phE4OaAzNv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L175)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Same as above re: probably more useful to link to our docs than generic lib docs
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 210 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-210:-MS4G_tGDoRaTvRxLA2P:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L210)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Same as above re: linking to our examples being probably more useful than the lib homepages
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-a-free-cluster.md, line 265 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MRqYxlF6kMGIE0kcuNU-r2-265:-MS4GcS32vcIBeZYhw2D:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-a-free-cluster.md#L265)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Same as above re: linking to our docs being most useful.  Esp. since there is a lot of retry stuff handled in those docs that is not here
</blockquote></details>

Done.
___
*[cockroachcloud/connect-to-your-cluster.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3NRK7BznB3QIHA0oF:-MS4GeFC703j9IbFnYs2:b-lr4mh6) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L51)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Not sure about this - @thtruo is this something you can answer?
</blockquote></details>

or maybe @piyush-singh? (sorry for the spam)

**Review by piyush-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @rmloveland, and @thtruo)

___
*[cockroachcloud/connect-to-your-cluster.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3NRK7BznB3QIHA0oF:-MS8dFaG0KM4ANLUjcaL:b-reh5z4) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L51)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

or maybe @piyush-singh? (sorry for the spam)
</blockquote></details>

This paragraph looks correct to me, @emily-horing can you clarify your question? CIDR notation is indeed always used. Not sure I'm following the question about the local/app network.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @rmloveland, and @thtruo)

___
*[cockroachcloud/connect-to-your-cluster.md, line 51 at r2](https://reviewable.io/reviews/cockroachdb/docs/9481#-MS3NRK7BznB3QIHA0oF:-MS9WwVB8BXv-hudDEzD:b-8ouh29) ([raw file](https://github.com/cockroachdb/docs/blob/1e3e7fd40f3f1491efaa9c418418e5d27392d5b2/cockroachcloud/connect-to-your-cluster.md#L51)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

This paragraph looks correct to me, @emily-horing can you clarify your question? CIDR notation is indeed always used. Not sure I'm following the question about the local/app network.
</blockquote></details>

Following up: It doesn't seem like the subnet is needed for single IP addresses. I tried adding a single IP address (it's actually what the UI defaults to if you select to add current/new network) and it seems to be fine. If we have issues with this part of the doc in the future, we can open a bug and fix it.

**Pull request merged**
