### PR TITLE
CC Free Cert Expiration

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-4790

### CODE REVIEW

**Review by emily-horing — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[_includes/cockroachcloud/cc-cert-expire.md, line 2 at r3](https://reviewable.io/reviews/cockroachdb/docs/11058#-MhK0lZdASLPNNv9SbLf:-MhK0lZe20ntqhDPMNYZ:b-3efv9g) ([raw file](https://github.com/cockroachdb/docs/blob/053251368ca259b53d8a3f3a53c55ba5ec7ab868/_includes/cockroachcloud/cc-cert-expire.md#L2)):*
> ```Markdown
> {{site.data.alerts.callout_danger}}
> We have updated the CA certificate used by CockroachCloud Free (beta) clusters. If you downloaded this certificate prior to [date], **you must download the updated certificate by September 30, 2021** to avoid disruptions to your service. 
> ```

I think the date is June 15th 2021. Checking when exactly this pr was pushed to prod: https://github.com/cockroachlabs/managed-service/pull/5720
___
*[cockroachcloud/troubleshooting-page.md, line 10 at r3](https://reviewable.io/reviews/cockroachdb/docs/11058#-MhK4Ft_82gImHrpmk1o:-MhK4Fta4c9rbn2wzuN-:b3j0vnj) ([raw file](https://github.com/cockroachdb/docs/blob/053251368ca259b53d8a3f3a53c55ba5ec7ab868/cockroachcloud/troubleshooting-page.md#L10)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> We have updated the CA certificate used by CockroachCloud Free (beta) clusters. If you downloaded this certificate prior to [date], **you must [download the updated certificate](connect-to-a-free-cluster.html#step-2-connect-to-your-cluster) by September 30, 2021** to avoid disruptions to your service. 
> ```

Oddly not seeing this on the Netlify preview. Not sure why?
i think it might be worth adding a section for this in addition to the call out. WDTY?

**Comment by gemma-shay** [comment]
@emily-horing updated! 

should work here: https://deploy-preview-11058--cockroachdb-docs.netlify.app/docs/cockroachcloud/troubleshooting-page.html

If you click on anything from the preview's search results it just takes you to the live docs, so maybe that was what happened.

**Comment by emily-horing** [comment]
@gemma-shay thanks! I think this looks good. Only update is from Darin in the ticket -- he said that the correct date is actually June 17th. 

This LGTM with that change.

**Comment by gemma-shay** [comment]
done!

**Review by kathancox — APPROVED** [review]
LGTM! The only thing I had thought was customers finding this, but since you mentioned the email in Slack for Monday — so makes sense!

**Pull request merged**
