### PR TITLE
DOC-2426: Add front-matter for Google Analytics reporting

### PR DESCRIPTION
**Pull request by jseldess**
This PR adds two front-matter fields to 21.2 pages and
other non-release-specific pages:
   - doc_area: This should indicates the sidenav section
               where the page is found, e.g., get_started,
               develop, deploy, etc.
   - product_area: This should indicate the primary product
               area responsible for the page.

Separately, we will create 2 custom dimensions in GA and then
update the docs site logic to transate these front-matter fields
into JS that passes the values to GA properly.

The end goal is to more easily report on pageviews and csat
responses by doc and product area.

### CODE REVIEW

**Comment by ianjevans** [comment]
@jseldess There are only 4 changed files with this PR. That doesn't seem right, as it should be basically all the v21.2 topics.

**Comment by jseldess** [comment]
Sorry, @ianjevans. You're right. Please check again.

**Review by mikeCRL — APPROVED** [review]

**Review by lnhsingh — APPROVED** [review]

**Review by ianjevans — APPROVED** [review]

**Comment by stbof** [comment]
@jseldess While I was working on [content types](https://github.com/cockroachdb/docs/pull/12806), I was thinking we could add a page variable that describes the page type: concept, task, reference, tutorial, best-practice, faq, troubleshooting.

**Comment by jseldess** [comment]
Given the large number of merge of merge conflicts, I've porting these changes into a new PR: https://github.com/cockroachdb/docs/pull/12878.

**Comment by jseldess** [comment]
Great idea, @stbof. It will be easy to add that logic once those types are finalized.

**Pull request closed without merging**
