### PR TITLE
troubleshooting content

### PR DESCRIPTION
**Pull request by jseldess**
Adding troubleshooting recommendations for "replicas failing" errors.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/204)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by bdarnell** [comment]
We may want to add some instructions to the "Start a cluster" page to recommend the `zone set` command for all single-node clusters. This is such a common issue that I think it may need to be more prominent.

**Comment by jseldess** [comment]
Yep, I can do that. But I also opened an issue a bit ago to see if there's another way we could handle the single-node scenario: https://github.com/cockroachdb/cockroach/issues/5919

Maybe it'd be easier for users intending to run a single node to just pass a flag that automatically sets the default zone config to one replica?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/204#-:-KElHvdk7dL3NZKAoQG-:-1620756274)*

**Comment by bdarnell** [comment]
We used to have that with `--dev`, but that flag did a bunch of different things and we removed it. It would be easy to add a `--singlenode` flag that could set the default zone config when bootstrapping a new cluster, but it would have some weird quirks. (what happens when you add or remove the flag on a restart? does it immediately change the zone config again?). For the time being, the `zone set` command is the way to go (I'd just like to fix it so you can say "replicas: 1" instead of the one-line `attrs` list).

**Comment by jseldess** [comment]
Added a note to `start-a-local-cluster.md` about editing the default zone config when you don't plan to use more than one node.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/204#-:-KEln3GDkXC-NKYXfIEP:-1687187780)*

**Pull request merged**
