### PR TITLE
Update docker swarm tutorials

### LINKED ISSUE #1617: Orchestrate CockroachDB with Docker Swarm Doc Update
Re: [Orchestrate CockroachDB with Docker Swarm](https://cockroachlabs.com/docs//orchestrate-cockroachdb-with-docker-swarm.html)

## Issue Description

The instructions to create a client certificate are very subtle, just a short phrase with link under section 5, bullet 5.

## Suggested Resolution 

Since we have a sample `cockroach sql` invocation, we should have a specific step to create a client certificate as well.

### LINKED ISSUE #1640: Orchestrate CockroachDB with Docker Swarm can't run SQL client
Re: [Orchestrate CockroachDB with Docker Swarm](https://cockroachlabs.com/docs//orchestrate-cockroachdb-with-docker-swarm.html)

## Issue Description
I have followed the steps and appear to have a functioning cluster. I did have some trouble until I time synced my three nodes, you might want to add that to your steps.

I try to start the SQL client:

root@csx20064:~/cockroachdb# docker exec -it f0b341479625 ./cockroach sql --certs-dir=/run/secrets
Error: pq: user root must use certificate authentication instead of password authentication
Failed running "sql"

Suggestions on what I am doing wrong?

### LINKED ISSUE #1736: Docker Swarm: Accessing the UI
As a follow-up to https://github.com/cockroachdb/docs/pull/1680, we should add a section to the doc about accessing the UI of a swarm cluster.

### PR DESCRIPTION
**Pull request by jseldess**
- Secure: Add steps for generating client (root) cert/key and secrets
- Secure & Insecure: Add copy-to-clipboard feature
- Secure & Insecure: Add guidance on accessing the Admin UI from outside the swarm

Fixes #1617
Fixes #1640
Fixes #1736

### CODE REVIEW

**Comment by jseldess** [comment]
@mberhault, @a-robinson, the main update here is adding explicit instructions for generating client (`root) certs and secrets. Please let me know where we might need to update or expand relevant explanations (I'm not really sure).

Otherwise, I'm wondering if we should add a step for calling up the admin UI? Do we have guidance anywhere on how to do that for a swarm?

**Comment by jseldess** [comment]
Ah, now I remember https://github.com/cockroachdb/docs/issues/1664. I'll look at that and work in a  section on accessing the admin UI.

**Comment by a-robinson** [comment]
I assume you'll copy your changes into the 1.1 files as well before merging?

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpQA9MgNwWFzGJOMd2_:bae0chr) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
> ```Markdown
>     --secret source=cockroachdb-1-crt,target=node.crt \
>     --secret source=cockroachdb-1-key,target=node.key,mode=0600 \
>     --secret source=cockroachdb-root-crt,target=client.root.crt \
> ```

I'm not the biggest fan in the world of loading the client certs into all the node containers rather than just running a new container with the client certs to open up a shell remotely, but I'm curious what @mberhault's opinion is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-:-KpQ8_K5GvK_TigbxIH6:b-w4dz8e)*

**Comment by a-robinson** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by jseldess** [comment]
Yeah, I'll copy everything to the 1.1 docs once changes are final. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-:-KpQQLKPz3dNkxZWBAac:b-cpu44j)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpQR7YbAOJsh9IT1sqF:baca3nc) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm not the biggest fan in the world of loading the client certs into all the node containers rather than just running a new container with the client certs to open up a shell remotely, but I'm curious what @mberhault's opinion is.
</blockquote></details>

Yeah, we avoid this in our other deployment docs now. Happy to do this differently with some guidance. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by mberhault** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpQxerdwrU_P4taLNxb:bvtn2z2) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Yeah, we avoid this in our other deployment docs now. Happy to do this differently with some guidance. 
</blockquote></details>

I think we should skip those in orchestrated deployments. While it's somewhat reasonable to talk to the cluster locally on bare metal, it's usually a bit more difficult inside containers and better to support connecting from outside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by mberhault** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-:-KpQxzAuzVY8brhiRh91:bnfp4nl)*

**Comment by a-robinson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpRi-K1qBnQtO5Lxf_w:-KpRi-K1qBnQtO5Lxf_x:b8k7353) ([raw file](https://github.com/cockroachdb/docs/blob/5391be6ccf33f42e941191e46a25ddfac6c3300a/v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L143)):*
> at the IP of any instance running a node

It exposes it on all swarm nodes, not just those running a cockroach node.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpRiDJNWFRE8e3f2tvu:-KpRiDJNWFRE8e3f2tvv:b7uix4) ([raw file](https://github.com/cockroachdb/docs/blob/5391be6ccf33f42e941191e46a25ddfac6c3300a/v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L143)):*
> https://docs.docker.com/engine/swarm/services/#publish-a services-ports-using-the-routing-mesh

For whatever reason, this URL isn't routable. https://docs.docker.com/engine/swarm/services/#publish-ports is the best alternative.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpRifcjlbpU0kdyfChm:b-kx0227) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

I think we should skip those in orchestrated deployments. While it's somewhat reasonable to talk to the cluster locally on bare metal, it's usually a bit more difficult inside containers and better to support connecting from outside.
</blockquote></details>

That sounds good to me. We can instead run a separate container where we mount in the client secrets and connect to the cluster from there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpRi-K1qBnQtO5Lxf_w:-KpW0BWTdXc4VCV5zvtQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5391be6ccf33f42e941191e46a25ddfac6c3300a/v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L143)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> at the IP of any instance running a node

It exposes it on all swarm nodes, not just those running a cockroach node.
</blockquote></details>

Done.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md, line 143 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpRiDJNWFRE8e3f2tvu:-KpW0NRCmJUqBxs5Sdfa:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/5391be6ccf33f42e941191e46a25ddfac6c3300a/v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md#L143)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> https://docs.docker.com/engine/swarm/services/#publish-a services-ports-using-the-routing-mesh

For whatever reason, this URL isn't routable. https://docs.docker.com/engine/swarm/services/#publish-ports is the best alternative.
</blockquote></details>

Done.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpW0QPxzozJisiAyTDT:b236ue9) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

That sounds good to me. We can instead run a separate container where we mount in the client secrets and connect to the cluster from there.
</blockquote></details>

OK, I'll need some guidance to get this right. In the cert generation step, we create the root user's cert and key on one of the instances running a node. So:

1. Where should the client cert and secrets be generated?
2. How do we get a separate container with those secrets and then start the sql shell from there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by a-robinson** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpWT4RQj33mzweiRDvd:b-o6vql1) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

OK, I'll need some guidance to get this right. In the cert generation step, we create the root user's cert and key on one of the instances running a node. So:

1. Where should the client cert and secrets be generated?
2. How do we get a separate container with those secrets and then start the sql shell from there?
</blockquote></details>

I did a little looking, and it turns out that secrets are only usable by swarm services, not by individual containers. So our options are:

1. Generate the client cert/key and secret the same as they are in this guide. Then run a service pinned to the current host that mounts them, using a scheduling constraint. This gets pretty awkward because we have to run a command that will keep the container from exiting, like `sleep 10000` or something, so that we can then attach to it once it's up.
2. Generate the client cert/key locally without creating secrets for them and run a local docker container that mounts them in. This isn't a great example of how to talk to the service, because a real client would probably run as a swarm service and use secrets, but it's a little less awkward.

Does either of those sound less bd to you? I suppose there's also a third option, which is to run something like our loadgen image as a service rather showing how to get an interactive shell.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by a-robinson** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpWdceEGYEHhYkWPxCf:bl17piq) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I did a little looking, and it turns out that secrets are only usable by swarm services, not by individual containers. So our options are:

1. Generate the client cert/key and secret the same as they are in this guide. Then run a service pinned to the current host that mounts them, using a scheduling constraint. This gets pretty awkward because we have to run a command that will keep the container from exiting, like `sleep 10000` or something, so that we can then attach to it once it's up.
2. Generate the client cert/key locally without creating secrets for them and run a local docker container that mounts them in. This isn't a great example of how to talk to the service, because a real client would probably run as a swarm service and use secrets, but it's a little less awkward.

Does either of those sound less bd to you? I suppose there's also a third option, which is to run something like our loadgen image as a service rather showing how to get an interactive shell.
</blockquote></details>

The third option actually sounds most realistic, and thus most helpful. Though I think it might be a mistake not to show uses how to connect our sql shell to the cluster as well, since we focus on the shell in so many other tutorials. 

I guess, ideally, we would do both, with "Use the built-in SQL shell" step as well as a "Run the loadgen client". 

That said, would it be ok  to go with the the tutorial as-is for now (with client certs on the nodes) and handle this work in a follow-up PR? I'm about to go on vacation and don't want to leave this sitting for 2 weeks...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpWgFzhPJGrMp2eCR3e:b-l4888e) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

The third option actually sounds most realistic, and thus most helpful. Though I think it might be a mistake not to show uses how to connect our sql shell to the cluster as well, since we focus on the shell in so many other tutorials. 

I guess, ideally, we would do both, with "Use the built-in SQL shell" step as well as a "Run the loadgen client". 

That said, would it be ok  to go with the the tutorial as-is for now (with client certs on the nodes) and handle this work in a follow-up PR? I'm about to go on vacation and don't want to leave this sitting for 2 weeks...
</blockquote></details>

Yeah, it can go in as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Comment by jseldess** [comment]
*[v1.0/orchestrate-cockroachdb-with-docker-swarm.md, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1735#-KpQA9MfgeX962OFkveB:-KpWjVr39kPOm8Ee4suN:b-7cmir2) ([raw file](https://github.com/cockroachdb/docs/blob/526eccceb8ef0fd9d782a873d92bd3e97e10761b/v1.0/orchestrate-cockroachdb-with-docker-swarm.md#L326)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Yeah, it can go in as is.
</blockquote></details>

OK, great. I just created https://github.com/cockroachdb/docs/issues/1745. I'll pick it back up once I'm back from vacation. If you happen to have time, please add any additional details you think I'll need. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1735)*

**Pull request merged**
