### PR TITLE
known limitation on upgrades and non-terminal jobs

### LINKED ISSUE #8968: document limitation on upgrading to 20.2 with >100 non-terminal jobs
We introduced a bug in a startup migration in 20.2 (https://github.com/cockroachdb/cockroach/issues/56859) which will prevent clusters with more than 100 jobs in a non-terminal state (i.e., anything other than `succeeded`, `canceled`, or `failed`) from being upgraded to 20.2.

The upgrade docs (https://www.cockroachlabs.com/docs/v20.2/upgrade-cockroach-version#let-ongoing-bulk-operations-finish, https://www.cockroachlabs.com/docs/cockroachcloud/upgrade-to-v20.2.html#let-ongoing-bulk-operations-finish) need to be updated, and possibly the known limitations docs as well.

Here's what we need users to do:

1. Before starting the upgrade to 20.2, ensure there are at most 100 jobs that are in any state other than `succeeded`, `canceled`, or `failed`. (This includes `running` and `reverting` jobs). They can do this via the admin UI or with a query like `SELECT count(*) FROM crdb_internal.jobs WHERE status NOT IN ('succeeded', 'canceled', 'failed')`.
2. Once that condition is met, begin the rolling upgrade by upgrading one node to 20.2. Then wait until the log message `done ensuring all necessary migrations have run` appears.
3. At this point, there are no more restrictions on how many jobs are allowed, and the rest of the rolling upgrade can proceed as usual.

If users have more than 100 jobs when they upgrade, the 20.2 node will hang and never successfully start, and they'll see `checked 100 jobs for existence of deprecated schema change jobs` in a tight loop in the logs.

These instructions are much more pedantic than necessary. We already advise users to avoid running jobs during the upgrade, so this shouldn't be much of an extra burden. One thing we should specifically note is that `SCHEMA CHANGE GC` jobs count as jobs, even though they're passive and mostly do nothing except wait.

This is going to affect all releases at least through v20.2.2. We expect to fix this in a later point release.

### PR DESCRIPTION
**Pull request by taroface**
Fixes #8968.

### CODE REVIEW

**Review by lucy-zhang — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[v20.2/known-limitations.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnR8IBJD6HeBeVBae:-MMYnR8IBJD6HeBeVBaf:b1f4xkc) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L11)):*
> ```Markdown
> ## New limitations
> 
> ### Upgrading to v20.2 with more than 100 non-terminal jobs
> ```

I just realized this should actually be `with 100 or more non-terminal jobs` (i.e., my original issue was incorrect; having exactly 100 jobs won't work).
___
*[v20.2/known-limitations.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYndQM3XSM1iQdy5gx:-MMYndQM3XSM1iQdy5gy:b-upgckb) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L13)):*
> ```Markdown
> ### Upgrading to v20.2 with more than 100 non-terminal jobs
> 
> Clusters with more than 100 jobs in a non-terminal state (i.e., any state other than `succeeded`, `failed`, or `canceled`) are unable to upgrade to v20.2. The v20.2 node will hang and never successfully start, and the [logs](debug-and-error-logs.html) will show `checked 100 jobs for existence of deprecated schema change jobs` in a tight loop.
> ```

Same here: `Clusters with 100 or more jobs`
___
*[v20.2/known-limitations.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnlyZ9_sC2DICL-ig:-MMYnlyZ9_sC2DICL-ih:bvi65dy) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L17)):*
> ```Markdown
> To avoid this limitation: 
> 
> 1. Before starting the upgrade to v20.2, check the [Jobs page](ui-jobs-page.html#jobs-list) in the DB Console or run `SELECT count(*) FROM crdb_internal.jobs WHERE status NOT IN ('succeeded', 'canceled', 'failed')` to ensure that no more than 100 jobs are in a non-terminal state. 
> ```

Same here: `fewer than 100 jobs` or `no more than 99 jobs`
___
*[v20.2/known-limitations.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnxob2DUUyaVUk6ob:-MMYnxob2DUUyaVUk6oc:b-m33w9y) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L19)):*
> ```Markdown
> 1. Before starting the upgrade to v20.2, check the [Jobs page](ui-jobs-page.html#jobs-list) in the DB Console or run `SELECT count(*) FROM crdb_internal.jobs WHERE status NOT IN ('succeeded', 'canceled', 'failed')` to ensure that no more than 100 jobs are in a non-terminal state. 
> 
> 1. You can then [start the rolling upgrade](upgrade-cockroach-version.html#step-4-perform-the-rolling-upgrade) and wait for the log message `done ensuring all necessary migrations have run` to appear, at which point there are no further restrictions on jobs.
> ```

I'd say `to appear on the first upgraded node`.

**Review by lucy-zhang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[v20.2/known-limitations.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnxob2DUUyaVUk6ob:-MMYpatzELR0GY4Cuc6O:bh5qegj) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L19)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'd say `to appear on the first upgraded node`.
</blockquote></details>

nit: both list elements start with `1.`
___
*[v20.2/upgrade-cockroach-version.md, line 103 at r2](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYpYeG0APriOAIooJe:-MMYpYeG0APriOAIooJf:b-1uboe8) ([raw file](https://github.com/cockroachdb/docs/blob/9e1be6ba16a4d26bcd62063c67abc102fa36d491/v20.2/upgrade-cockroach-version.md#L103)):*
> ```Markdown
> Before upgrading to v20.2, you must have fewer than 100 jobs in a non-terminal state (i.e., any state other than `succeeded`, `failed`, or `canceled`). Otherwise, the v20.2 node will hang and never successfully start. Note that `SCHEMA CHANGE GC` jobs are counted even though they are passive.
> 
> This will be fixed in a later v20.2 testing release. For more context, see [Known Limitations in CockroachDB v20.2](known-limitations.html#upgrading-to-v20-2-with-more-than-100-non-terminal-jobs).
> ```

Also, should this say `testing release`?

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @taroface)

___
*[v20.2/known-limitations.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnR8IBJD6HeBeVBae:-MMYpQJp-yPdBLG5mJVI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L11)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I just realized this should actually be `with 100 or more non-terminal jobs` (i.e., my original issue was incorrect; having exactly 100 jobs won't work).
</blockquote></details>

Done.
___
*[v20.2/known-limitations.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYndQM3XSM1iQdy5gx:-MMYpUcDAGCLiLWT7I1q:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L13)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Same here: `Clusters with 100 or more jobs`
</blockquote></details>

Done.
___
*[v20.2/known-limitations.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnlyZ9_sC2DICL-ig:-MMYpYJSAqvm0bgSgI1D:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L17)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Same here: `fewer than 100 jobs` or `no more than 99 jobs`
</blockquote></details>

Done.
___
*[v20.2/known-limitations.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnxob2DUUyaVUk6ob:-MMYpatm88-fPgp_CUYq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L19)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'd say `to appear on the first upgraded node`.
</blockquote></details>

Done.

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[v20.2/known-limitations.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnxob2DUUyaVUk6ob:-MMYqC-H238_nTXpiQDF:by5vx7u) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! Numbering all list elements with `1.` is standard and Markdown handles the enumeration on the page.
___
*[v20.2/upgrade-cockroach-version.md, line 103 at r2](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYpYeG0APriOAIooJe:-MMYpv7a4y4M3tMuxfHG:b-64ro8g) ([raw file](https://github.com/cockroachdb/docs/blob/9e1be6ba16a4d26bcd62063c67abc102fa36d491/v20.2/upgrade-cockroach-version.md#L103)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Also, should this say `testing release`?
</blockquote></details>

Do you mean with the code formatting? It doesn't appear that we use that elsewhere in the docs.

**Review by lucy-zhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @taroface)

___
*[v20.2/known-limitations.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYnxob2DUUyaVUk6ob:-MMYqwK09FfvqG2_1NMS:b10xk9o) ([raw file](https://github.com/cockroachdb/docs/blob/b3a8a9c751e83cb938fe4ec9582ad21bb7d629e0/v20.2/known-limitations.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Thanks! Numbering all list elements with `1.` is standard and Markdown handles the enumeration on the page.
</blockquote></details>

That's good to know, thanks.
___
*[v20.2/upgrade-cockroach-version.md, line 103 at r2](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYpYeG0APriOAIooJe:-MMYr-IX3a4wZbPwf2fv:b-z8qnte) ([raw file](https://github.com/cockroachdb/docs/blob/9e1be6ba16a4d26bcd62063c67abc102fa36d491/v20.2/upgrade-cockroach-version.md#L103)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Do you mean with the code formatting? It doesn't appear that we use that elsewhere in the docs.
</blockquote></details>

Sorry, I meant that I think this should be `patch release` or `point release` (I'm not sure which we usually use).
___
*[v20.2/upgrade-cockroach-version.md, line 101 at r3](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYrOZLDE1VU2nXnJjq:-MMYrOZLDE1VU2nXnJjr:b-ov164d) ([raw file](https://github.com/cockroachdb/docs/blob/55ce12f481b84198d02e6b38df8597f73a9b266c/v20.2/upgrade-cockroach-version.md#L101)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> Before upgrading to v20.2, you must have fewer than 100 jobs in a non-terminal state (i.e., any state other than `succeeded`, `failed`, or `canceled`). Otherwise, the v20.2 node will hang and never successfully start. Note that `SCHEMA CHANGE GC` jobs are counted even though they are passive.
> ```

Thinking about this again, I think we can just leave out the last sentence. It should be clear to users that a running job is a running job regardless of type.

**Comment by lucy-zhang** [comment]
Also, does this page also need updating? https://www.cockroachlabs.com/docs/cockroachcloud/upgrade-to-v20.2.html

I guess upgrading on CC is tricky because there's nothing preventing users from starting more jobs after they initiate the upgrade, and they have less control over exactly when the rolling restart happens (as well as the CC backup jobs). I'm not sure what to do. Maybe we need to loop in someone from the CC team.

**Comment by taroface** [comment]
> Also, does this page also need updating? https://www.cockroachlabs.com/docs/cockroachcloud/upgrade-to-v20.2.html
> 
> I guess upgrading on CC is tricky because there's nothing preventing users from starting more jobs after they initiate the upgrade, and they have less control over exactly when the rolling restart happens (as well as the CC backup jobs). I'm not sure what to do. Maybe we need to loop in someone from the CC team.

Hi @DuskEagle, do you think we should provide a similar warning on the CC upgrade docs? If so, could you recommend the appropriate guidance?

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @taroface)

___
*[v20.2/upgrade-cockroach-version.md, line 103 at r2](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYpYeG0APriOAIooJe:-MMaWLEG7HzDLgHK7dNq:b4mo6ee) ([raw file](https://github.com/cockroachdb/docs/blob/9e1be6ba16a4d26bcd62063c67abc102fa36d491/v20.2/upgrade-cockroach-version.md#L103)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Sorry, I meant that I think this should be `patch release` or `point release` (I'm not sure which we usually use).
</blockquote></details>

Ah, I wasn't familiar with the nomenclature. Looks like it's "patch release"!
___
*[v20.2/upgrade-cockroach-version.md, line 101 at r3](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMYrOZLDE1VU2nXnJjq:-MMaWBlY7Ku69wJmNlri:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/55ce12f481b84198d02e6b38df8597f73a9b266c/v20.2/upgrade-cockroach-version.md#L101)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Thinking about this again, I think we can just leave out the last sentence. It should be clear to users that a running job is a running job regardless of type.
</blockquote></details>

Done.

**Comment by taroface** [comment]
@lucy-zhang @DuskEagle After discussing this with @jseldess, I added the same guidance to the CC upgrade doc (and also relocated the callout to a more appropriate section). Can you have a look and let @jseldess know if this is OK to merge?

**Comment by jseldess** [comment]
@lucy-zhang, I'll be taking over this PR, so please let me know what you think of the current state.

**Review by lucy-zhang — APPROVED** [review]
Looks good from my end.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978#-:-MMag3yD5sFjRSfa7T2s:b-oxivlp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[cockroachcloud/upgrade-to-v20.2.md, line 59 at r7](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMbXoV0ENwvP6v5XaXN:-MMbXoV0ENwvP6v5XaXO:b-7bcc7g) ([raw file](https://github.com/cockroachdb/docs/blob/794140376fa2bab46b9d04313d912b9aaaffb79b/cockroachcloud/upgrade-to-v20.2.md#L59)):*
> ```Markdown
> - If everything looks good, you can wait for the upgrade to automatically finalize or you can [trigger finalization more quickly](#finalize-the-upgrade).
> 
> - If you see unexpected behavior, you can [rollback to v20.1](#roll-back-the-upgrade). This option is available only during the 72-hour window. If you see unexpected behavior after the upgrade has been finalized, you will have to [reach out to support](https://support.cockroachlabs.com/hc/en-us/requests/new).
> ```

`of all types`
___
*[v20.2/upgrade-cockroach-version.md, line 49 at r7](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMbXwU2EPwZunC9sQIe:-MMbXwU2EPwZunC9sQIf:b-2guby3) ([raw file](https://github.com/cockroachdb/docs/blob/794140376fa2bab46b9d04313d912b9aaaffb79b/v20.2/upgrade-cockroach-version.md#L49)):*
> ```Markdown
> Make sure there are no [bulk imports](import.html) or [schema changes](online-schema-changes.html) in progress. These are complex operations that involve coordination across nodes and can increase the potential for unexpected behavior during an upgrade.
> 
> In addition, make sure there are fewer than 100 jobs of all kinds, including backups, in a non-terminal state (i.e., any state other than `succeeded`, `failed`, or `canceled`). Otherwise, v20.2 nodes will hang and never successfully start. Note that this will be fixed in a later v20.2 patch release. For more context, see [Known Limitations in CockroachDB v20.2](known-limitations.html#upgrading-to-v20-2-with-100-or-more-non-terminal-jobs).
> ```

same here

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8978)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[cockroachcloud/upgrade-to-v20.2.md, line 59 at r7](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMbXoV0ENwvP6v5XaXN:-MNOqbk-1hFc1VBpPwX7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/794140376fa2bab46b9d04313d912b9aaaffb79b/cockroachcloud/upgrade-to-v20.2.md#L59)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`of all types`
</blockquote></details>

Done.
___
*[v20.2/upgrade-cockroach-version.md, line 49 at r7](https://reviewable.io/reviews/cockroachdb/docs/8978#-MMbXwU2EPwZunC9sQIe:-MNOqfpN0YMkPEV1_yzG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/794140376fa2bab46b9d04313d912b9aaaffb79b/v20.2/upgrade-cockroach-version.md#L49)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Pull request merged**
