### PR TITLE
Add v20.1.0-alpha20200113 release notes

### LINKED ISSUE #6286: v20.1.0-alpha.20200113 release notes
For https://github.com/cockroachdb/cockroach/issues/43754

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #6286.

### CODE REVIEW

**Comment by lnhsingh** [comment]
@jseldess - can you review and add the docs section?

**Comment by miretskiy** [comment]
The release note for #43789 :
Release note (bug fix): CockroachDB will not any more try to issue HTTP requests as part of an import after the import job has been cancelled.

**Comment by jseldess** [comment]
@lnhsingh, here are the doc updates:

```
### Documentation Updates

- Documented how to [use keyset pagination to iterate through query results](../v20.1/selection-queries.html#paginate-through-limited-results). [#6114](https://github.com/cockroachdb/docs/pull/6114) 
- Updated the [Build a Java App with Hibernate tutorial](../v20.1/build-a-java-app-with-cockroachdb-hibernate.html) with app-level retry logic. [#5760](https://github.com/cockroachdb/docs/pull/5760)
- Improved the [GSSAPI authentication](../v20.1/gssapi_authentication.html) instructions for configuring Active Directory and MIT and for configuring the client. [#6115](https://github.com/cockroachdb/docs/pull/6115) 
- Expanded the [Kubernetes tutorial](../v20.1/orchestrate-cockroachdb-with-kubernetes.html#manual) to show how to use a custom CA instead of Kuberentes built-in CA when using configs. [#6232](https://github.com/cockroachdb/docs/pull/6232)
- Updated the [Kubernetes tutorial](../v20.1/orchestrate-cockroachdb-with-kubernetes.html) for Helm 3.0. [#6121](https://github.com/cockroachdb/docs/pull/6121)
- Added language-specific connections strings to the instructions on [connecting to a CockroachCloud cluster](https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html#use-a-postgres-driver-or-orm). [#6077](https://github.com/cockroachdb/docs/pull/6077)
- Added Docker as a download option on the full [release notes list](../releases/#docker). [#5792](https://github.com/cockroachdb/docs/issues/5792) 
- Updated the [`IMPORT` documentation](../v20.1/import.html) with an example usage of the `DELIMITED` with escaping, a note about `DEFAULT` values, and an explanation of the `strict_quotes` option. [#6244](https://github.com/cockroachdb/docs/pull/6244)
- Added an FAQ on [why Cockroach Labs changed the license for CockroachDB](../v20.1/frequently-asked-questions.html#why-did-cockroach-labs-change-the-license-for-cockroachdb). [#6154](https://github.com/cockroachdb/docs/pull/6154)
```

**Comment by knz** [comment]
There's a weird looking link:

image

**Pull request merged**
