### PR TITLE
Add Confluent Cloud scheme to changefeed sinks

### PR DESCRIPTION
**Pull request by kathancox**
Fixes DOC-8145, DOC-8951

This PR adds the `confluent-cloud` scheme to the v23.2 docs. This includes the usual treatment of sinks on the following pages:

- Changefeed Sinks. Rendered preview: https://deploy-preview-18031--cockroachdb-docs.netlify.app/docs/v23.2/changefeed-sinks.html#confluent-cloud
- Changefeed Examples. Rendered preview: https://deploy-preview-18031--cockroachdb-docs.netlify.app/docs/v23.2/changefeed-examples.html#create-a-changefeed-connected-to-a-confluent-cloud-sink
- `CREATE CHANGEFEED`. Rendered preview: https://deploy-preview-18031--cockroachdb-docs.netlify.app/docs/v23.2/create-changefeed.html

Some opportunistic edits to copy repetitive content on the Examples page.

### CODE REVIEW

**Comment by kathancox** [comment]
cc @amruss

**Review by jayshrivastava — APPROVED** [review]
LGTM

**Review by florence-crl — COMMENTED** [review]
2 questions on CREATE CHANGEFEED
- one ambiguous reference
- should Confluent Cloud be added to `sasl_user` and `sasl_password` since they are required by `sasl_mechanism`?

**Comment by amruss** [comment]
LGTM

**Comment by kathancox** [comment]
> 2 questions on CREATE CHANGEFEED
> 
> * one ambiguous reference
> * should Confluent Cloud be added to `sasl_user` and `sasl_password` since they are required by `sasl_mechanism`?

@florence-crl The api key and api secret are passed in as the sasl user and password for Confluent Cloud sinks. So, I think having the api_key and `api_secret` as the new params listed for Confluent Cloud is correct here.

**Review by florence-crl — APPROVED** [review]
LGTM

**Comment by kathancox** [comment]
TFTRs!

**Pull request merged**
