### PR TITLE
Improve app examples

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/162)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm: modulo tabs and the js one

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz7liIwEyHnLz9LrTb:-KDz7liIwEyHnLz9LrTc:678051331) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/basic-sample.js#L34)):*
tabs

---

*[_includes/app/txn-sample.js, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz6lQb6olsRQKoFXfz:-KDz6lQb6olsRQKoFXg-:-244032342) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L16)):*
tabs (which will screw up formatting probably on the web)

---

*[_includes/app/txn-sample.js, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz7gsGVGbkQ3N2KpB3:-KDz7gsGVGbkQ3N2KpB4:-1954342724) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L23)):*
no retry magic yet?

---

*[_includes/app/txn-sample.js, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz7Tq4ZRM6ZgsDAhmr:-KDz7Tq5u73WB_BTYck3:-1552964122) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L39)):*
capitalize `UPDATE`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/162#-:-KDz7nye0dNEQ_UhmnbH:2027021934)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 8 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz8B74abcB4ZXxBe0w:-KDz8B74abcB4ZXxBe0x:199499596) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/basic-sample.js#L8)):*
Proper Node.js formatting specifies 2 space indentations. If you have 15 nested callbacks you'd hope it would fit on a desktop monitor.

---

*[_includes/app/txn-sample.js, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDzCjoyNFhdVKp3A6aE:-KDzCjoyNFhdVKp3A6aF:-1262359018) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L32)):*
The indenting is off here. See https://github.com/caolan/async#waterfall

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/162)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[_includes/app/txn-sample.js, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDzEmwQuP_JzMAi6HQR:-KDzEmwRS2JfBiOQc7c8:242035005) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L25)):*
I think we want the `INSERT` in the txn samples too. The python one is missing it too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/162)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[_includes/app/txn-sample.js, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDzEmwQuP_JzMAi6HQR:-KDzFeVHzKmYiK20-lgY:821828212) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L25)):*
never mind, I'll delete from from go and cpp

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/162)*

**Comment by knz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 8 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz8B74abcB4ZXxBe0w:-KDzFs04ZEnrAHn7wInA:-1614001103) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/basic-sample.js#L8)):*
I honestly don't really care about indent for examples in docs. Since I don't write JS regularly I do not know how to set up my editor accordingly. If you feel like it should be different, suit yourself in a follow-up commit :)

---

*[_includes/app/txn-sample.js, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/162#-KDz7gsGVGbkQ3N2KpB3:-KDzGBsmQknN4k1KWfrN:-510817129) ([raw file](https://github.com/cockroachdb/docs/blob/0c584ce23aedcf57dc840b0de61c8f62cb17158c/_includes/app/txn-sample.js#L23)):*
Not sure how to do that. Ask @nvanbenschoten

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/162)*

**Comment by jseldess** [comment]
Hey @nvanbenschoten, do you think you can make final updates on these files today?

**Comment by nvanbenschoten** [comment]
@jseldess Yeah, I'll polish off the JS files this afternoon.

**Comment by jseldess** [comment]
Merging. Nathan will open a new PR to address open issues here (spacing in js samples).

**Pull request merged**
