### PR TITLE
Clarify examples for enterprise/core changefeeds on new Changefeed Example page

### PR DESCRIPTION
**Pull request by kathancox**
Fixes [DOC-2503](https://cockroachlabs.atlassian.net/browse/DOC-2503)

Customer found the new layout of the changefeed examples page confusing. There was a feeling that the Cloud storage examples were hard to find. 

Adjusted the layout to make Enterprise changefeeds more prominent in the filter placements. Added a sink breakdown to start with links to the respective sections and added link out to the Changefeed Sinks page to make clear that information on forming sink URIs can be found there.

### CODE REVIEW

**Review by amruss — APPROVED** [review]
this LGTM, thanks for getting this out so quickly!

**Comment by kathancox** [comment]
@taroface Just bumping this up your inbox for when you return! Thanks

**Comment by kathancox** [comment]
Hey @taroface, could you take a review of this when you have time? Thanks!

**Review by taroface — APPROVED** [review]
So sorry I missed this before. Just a nit on capitalization, otherwise LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12935#-:-Mx0EqEaD1tufjeIiTri:bufpu0z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @taroface)

___
*[v21.2/changefeed-examples.md, line 424 at r2](https://reviewable.io/reviews/cockroachdb/docs/12935#-Mx0F6If1azhy8p6FAxT:-Mx0F6If1azhy8p6FAxU:b-9xgdsz) ([raw file](https://github.com/cockroachdb/docs/blob/0149ada56d84a241d1eff940bd0b61c0089a0261/v21.2/changefeed-examples.md#L424)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> ### Create a core changefeed
> ```

Should `core` be capitalized per the style in this doc?
___
*[v21.2/changefeed-examples.md, line 428 at r2](https://reviewable.io/reviews/cockroachdb/docs/12935#-Mx0F8V7Cb_PgQz9yE6a:-Mx0F8V7Cb_PgQz9yE6b:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/0149ada56d84a241d1eff940bd0b61c0089a0261/v21.2/changefeed-examples.md#L428)):*
> ```Markdown
> {% include {{ page.version.version }}/cdc/create-core-changefeed.md %}
> 
> ### Create a core changefeed using Avro
> ```

Ditto

**Pull request merged**
