### PR TITLE
Various small Architecture Overview improvements

### PR DESCRIPTION
**Pull request by rmloveland**
As part of addressing #10794, started with edits to the architecture
overview page.

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey Ryan, this PR should be strictly copy edits, adding links, etc. That's why I didn't go for an engineering review first (in case you were wondering!)

**Review by taroface — APPROVED** [review]
LGTM! Added a bunch of suggestions, most highly subjective, so use and discard at will.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10847#-:-MdJWe0O6EdTG6A4KCoY:bgrr7rm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[_includes/v20.2/misc/basic-terms.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ41QIETvSQmEH4Mgd:-MdJ41QIETvSQmEH4Mge:b-4ah5yi) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v20.2/misc/basic-terms.md#L5)):*
> ```
>  it splits into two ranges
> ```

Is it worth reiterating here that the table/indexes will then be mapped across both ranges?

Also: Per the thread in #docs-style, let's use American style for punctuation, and move the comma inside the quote: `"ranges," such that`!

Same for other quotes on this page!
___
*[_includes/v20.2/misc/basic-terms.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ4BDn0QiC6gccO5F_:-MdJ4BDn0QiC6gccO5Fa:b-rvkuzx) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v20.2/misc/basic-terms.md#L5)):*
> ```
> every key can always be found in a single range.
> ```

Nit: This point seems (?) significant, so I wonder if stating that e.g. "every key is found in one range" would bring it home. IMO the "can always be" part slightly sounds like it's conveying "it's always possible to find a key in a range" if someone is glossing over this sentence.
___
*[_includes/v20.2/misc/basic-terms.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ5L229jo7OdBNpV8z:-MdJ5L229jo7OdBNpV9-:b-r3oxc6) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v20.2/misc/basic-terms.md#L8)):*
> ```
> https://www.cockroachlabs.com/docs/{{ page.version.version }}/architecture/replication-layer.html#raft
> ```

Is the full URL necessary here?
___
*[_includes/v21.1/misc/basic-terms.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ5be-79KeoQvAlFkZ:-MdJ5be-79KeoQvAlFk_:b-b4k71) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v21.1/misc/basic-terms.md#L5)):*
> ```Markdown
> **Cluster** | Your CockroachDB deployment, which acts as a single logical application.
> **Node** | An individual machine running CockroachDB. One or more nodes join together to create your cluster.
> **Range** | <a name="architecture-range"></a> CockroachDB stores all user data (tables, indexes, etc.) and almost all system data in a giant sorted map of key-value pairs. This keyspace is divided into contiguous chunks called "ranges", such that every key can always be found in a single range.<br /><br />From a SQL perspective, a table and its secondary indexes initially map to a single range, where each key-value pair in the range represents a single row in the table (also called the primary index because the table is sorted by the primary key) or a single row in a secondary index. As soon as that range reaches 512 MiB in size ([the default](../configure-replication-zones.html#range-max-bytes)), it splits into two ranges. This process continues for these new ranges as the table and its indexes continue growing.
> ```

Same 2 comments as v20.2 doc.
___
*[_includes/v21.1/misc/basic-terms.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ6ZMG-OgFueyYw_KS:-MdJ6ZMG-OgFueyYw_KT:b-wsac7u) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v21.1/misc/basic-terms.md#L8)):*
> ```Markdown
> **Replica** <a name="architecture-replica"></a>| CockroachDB replicates each range (3 times [by default](../configure-replication-zones.html#num_replicas)) and stores each replica on a different node.
> **Leaseholder** <a name="architecture-leaseholder"></a> | For each range, one of the replicas holds the "range lease". This replica, referred to as the "leaseholder", is the one that receives and coordinates all read and write requests for the range.<br /><br />Unlike writes, read requests access the leaseholder and send the results to the client without needing to coordinate with any of the other range replicas. This reduces the network round trips involved and is possible because the leaseholder is guaranteed to be up-to-date due to the fact that all write requests also go to the leaseholder.
> **Raft Leader** | For each range, one of the replicas is the "leader" for write requests. Via the [Raft consensus protocol](https://www.cockroachlabs.com/docs/{{ page.version.version }}/architecture/replication-layer.html#raft), this replica ensures that a majority of replicas (the leader and enough followers) agree, based on their Raft logs, before committing the write. The Raft leader is almost always the same replica as the leaseholder.
> ```

Same question about the URL.
___
*[v20.2/architecture/overview.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ6ee07DbIS6iwTY89:-MdJ6ee07DbIS6iwTY8A:b88mabi) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L16)):*
> ```Markdown
> This guide is broken out into pages detailing each layer of CockroachDB. We recommended reading through the layers sequentially, starting with this overview and then proceeding to the [SQL layer](sql-layer.html).
> 
> If you're looking for a high-level understanding of CockroachDB, you can read the **Overview** section of each layer. For more technical detail - for example, if you're interested in [contributing to the project](https://cockroachlabs.atlassian.net/wiki/x/QQFdB) - you should read the **Components** sections as well.
> ```

Suggest making these hyphens em dashes: `—`
___
*[v20.2/architecture/overview.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ741O19Amv34xwogd:-MdJ741O19Amv34xwoge:b-8kblrw) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L19)):*
> ```
> how to architect an application
> ```

Maybe "build" or "create" would be a clearer word here, to avoid overlap with "Architecture" docs?
___
*[v20.2/architecture/overview.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ7Niu-ppNO0ga3hKW:-MdJ7Niu-ppNO0ga3hKX:b-ydvung) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L26)):*
> ```
> for operators
> ```

Hmm, it would be good to have a corresponding link for "operators". I think the Deploy section fits, although there's no overview page. https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html may make sense, though?

In case we end up with a new operator-focused landing page after @ianjevans' personas project, this could also point there.

EDIT: Disregard above! Just saw that you pointed a different version of this doc to `operate-cockroachdb-kubernetes.html`, which is probably a better choice after all. Since I'm doing the K8s docs refactor, I think this URL can become a landing page for pages documenting operator tasks. In that case, that URL just needs to be added to this version of the doc :)
___
*[v20.2/architecture/overview.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ7vGG2P4bY_cFzO1v:-MdJ7vGG2P4bY_cFzO1w:bf7ied0) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L32)):*
> ```
> resilient applications.
> ```

Maybe "deployments and applications"? Otherwise this sounds exclusive to developers.
___
*[v20.2/architecture/overview.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ8KXQ02EtE547Ldam:-MdJ8KXQ02EtE547Ldan:b-993475) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L51)):*
> ```
> Synchronous replication
> ```

It might be clearest to start this paragraph: "Synchronous replication is used by CockroachDB. Synchronous replication requires all writes [...]. This ensures the consistency of your data.

> ```
> Asynchronous replication
> ```

Likewise, perhaps start off with "Asynchronous replication is _not_ used by CockroachDB." ?
___
*[v20.2/architecture/overview.md, line 62 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJAtzs68l-PZpF9qCm:-MdJAtzs68l-PZpF9qCn:bnduwi3) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L62)):*
> ```
> any of them
> ```

Maybe "Any node"?
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBAFb-WXmHv3Mmg4H:-MdJBAFb-WXmHv3Mmg4I:bps4217) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
> ```
> if any nodes go down,
> ```

Is it worth adding "(due to tk, tk, tk)" in case this sounds like nodes going down is a routine event?
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBQ015nh55HNr2ROq:-MdJBQ015nh55HNr2ROr:btrhnbt) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
> ```
> you still have copies of the data which can be used for reads and writes, as well as consistently replicating the data to other nodes.
> ```

For the first part of this sentence, maybe "copies of the data can still be used for reads and writes"?

For the second part ("as well as consistently...") I can't quite parse this. Does it mean to continue the first part of the sentence: "you still have copies of the data which can be used for ... consistently replicating the data..."?

No particular suggestion here, just calling it out as it's a bit confusing to me.
___
*[v21.1/architecture/overview.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJIXpC8o9xt3HNPwpq:-MdJIXpC8o9xt3HNPwpr:b-5cnahe) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L16)):*
> ```Markdown
> This guide is broken out into pages detailing each layer of CockroachDB. We recommended reading through the layers sequentially, starting with this overview and then proceeding to the [SQL layer](sql-layer.html).
> 
> If you're looking for a high-level understanding of CockroachDB, you can read the **Overview** section of each layer. For more technical detail - for example, if you're interested in [contributing to the project](https://cockroachlabs.atlassian.net/wiki/x/QQFdB) - you should read the **Components** sections as well.
> ```

Em dashes `—` here?
___
*[v21.1/architecture/overview.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJI_gM46dGwl834Kst:-MdJI_gM46dGwl834Ksu:b6tbwpn) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L19)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> This guide details how CockroachDB is built, but does not explain how to architect an application using CockroachDB. For more information about how to develop applications that use CockroachDB, check out our [Developer Guide](../developer-guide-overview.html).
> ```

Same comment as above re: "architect"
___
*[v21.1/architecture/overview.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJWRqg30W6NVtFKSr-:-MdJWRqg30W6NVtFKSr0:b7mx5ci) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L32)):*
> ```Markdown
> - Support familiar tools for working with relational data (i.e., SQL).
> 
> With the confluence of these features, we hope that CockroachDB helps you build global, scalable, resilient applications.
> ```

Same comment as above: "deployments and applications"?
___
*[v21.1/architecture/overview.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJWXKrAOx8B7be-5I8:-MdJWXKrAOx8B7be-5I9:b-1894kn) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L51)):*
> ```Markdown
> **Isolation** | CockroachDB provides the [`SERIALIZABLE`](https://en.wikipedia.org/wiki/Serializability) isolation level, which provides the highest level of data consistency and protects against concurrency-based attacks and bugs.
> **Consensus** | <a name="architecture-overview-consensus"></a> When a range receives a write, a quorum of nodes containing replicas of the range acknowledge the write. This means your data is safely stored and a majority of nodes agree on the database's current state, even if some of the nodes are offline.<br/><br/>When a write does not achieve consensus, forward progress halts to maintain consistency within the cluster.
> **Replication** | Replication involves creating and distributing copies of data, as well as ensuring that those copies remain consistent. There are two types of replication: _synchronous_ and _asynchronous_.<br/><br/>Synchronous replication requires all writes to propagate to a [quorum](https://en.wikipedia.org/wiki/Quorum_%28distributed_computing%29) of copies of the data before being considered committed. To ensure the consistency of your data, CockroachDB uses synchronous replication.<br/><br/>Asynchronous replication only requires a single node to receive the write to be considered committed; state is then propagated to each copy of the data after the fact. This is more or less equivalent to ["eventual consistency"](https://en.wikipedia.org/wiki/Eventual_consistency), which was popularized by NoSQL databases. This method of replication is likely to cause anomalies and loss of data. It is not used by CockroachDB.
> ```

Same suggestions as above.

**Review by rmloveland — COMMENTED** [review]
Thanks Ryan!  They are all great suggestions, so I tried to do everything!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10847#-:-MdOICEiAx-4UCHZkms-:bdq849h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans, @rmloveland, and @taroface)

___
*[_includes/v20.2/misc/basic-terms.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ4BDn0QiC6gccO5F_:-MdO0HXqAN7zZYad8Qkl:b-wej9p6) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v20.2/misc/basic-terms.md#L5)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> every key can always be found in a single range.
> ```

Nit: This point seems (?) significant, so I wonder if stating that e.g. "every key is found in one range" would bring it home. IMO the "can always be" part slightly sounds like it's conveying "it's always possible to find a key in a range" if someone is glossing over this sentence.
</blockquote></details>

Updated!  Agree that is much clearer / more direct
___
*[_includes/v20.2/misc/basic-terms.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ41QIETvSQmEH4Mgd:-MdO0Nbp3StWGIKHiJVB:b-m74uey) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v20.2/misc/basic-terms.md#L5)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
>  it splits into two ranges
> ```

Is it worth reiterating here that the table/indexes will then be mapped across both ranges?

Also: Per the thread in #docs-style, let's use American style for punctuation, and move the comma inside the quote: `"ranges," such that`!

Same for other quotes on this page!
</blockquote></details>

I might not want to reiterate but only because it's in the previous sentence and I think the following one

Changed the punctuation of "ranges"!  (see what I did there lol)

Also fixed the other couple quote usages I found in this file
___
*[_includes/v20.2/misc/basic-terms.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ5L229jo7OdBNpV8z:-MdO1Zpd6MdrFYXNCx5H:biqeu33) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v20.2/misc/basic-terms.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> https://www.cockroachlabs.com/docs/{{ page.version.version }}/architecture/replication-layer.html#raft
> ```

Is the full URL necessary here?
</blockquote></details>

Nope, just tested and it works fine as a normal link, so I changed it!
___
*[_includes/v21.1/misc/basic-terms.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ5be-79KeoQvAlFkZ:-MdO2svK0BSkNAuZruNg:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v21.1/misc/basic-terms.md#L5)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same 2 comments as v20.2 doc.
</blockquote></details>

Fixed!
___
*[_includes/v21.1/misc/basic-terms.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ6ZMG-OgFueyYw_KS:-MdO2uJk2P_viBf1LOL1:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/_includes/v21.1/misc/basic-terms.md#L8)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same question about the URL.
</blockquote></details>

Fixed!
___
*[v20.2/architecture/overview.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ6ee07DbIS6iwTY89:-MdOCoFwC7SI-Cb7iKGO:bkuahw4) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Suggest making these hyphens em dashes: `—`
</blockquote></details>

upgraded!!!
___
*[v20.2/architecture/overview.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ741O19Amv34xwogd:-MdOCs8w2quz-0mowIBu:bnc60v7) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> how to architect an application
> ```

Maybe "build" or "create" would be a clearer word here, to avoid overlap with "Architecture" docs?
</blockquote></details>

went with "build"
___
*[v20.2/architecture/overview.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ7Niu-ppNO0ga3hKW:-MdOCwe4-OAga7M2rV5T:bm3z50v) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L26)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> for operators
> ```

Hmm, it would be good to have a corresponding link for "operators". I think the Deploy section fits, although there's no overview page. https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html may make sense, though?

In case we end up with a new operator-focused landing page after @ianjevans' personas project, this could also point there.

EDIT: Disregard above! Just saw that you pointed a different version of this doc to `operate-cockroachdb-kubernetes.html`, which is probably a better choice after all. Since I'm doing the K8s docs refactor, I think this URL can become a landing page for pages documenting operator tasks. In that case, that URL just needs to be added to this version of the doc :)
</blockquote></details>

In v20.2 it looks like we don't seem to have the k8s page (operate-cockroachdb-kubernetes.html), so I linked the recommended prod settings as you suggested above
___
*[v20.2/architecture/overview.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ7vGG2P4bY_cFzO1v:-MdODjLf57vNrGx6E0ce:b-bw8e1h) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L32)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> resilient applications.
> ```

Maybe "deployments and applications"? Otherwise this sounds exclusive to developers.
</blockquote></details>

Updated!
___
*[v20.2/architecture/overview.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ8KXQ02EtE547Ldam:-MdOE0otEdhzj4ffOO-m:bx4nh5p) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L51)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Synchronous replication
> ```

It might be clearest to start this paragraph: "Synchronous replication is used by CockroachDB. Synchronous replication requires all writes [...]. This ensures the consistency of your data.

> ```
> Asynchronous replication
> ```

Likewise, perhaps start off with "Asynchronous replication is _not_ used by CockroachDB." ?
</blockquote></details>

Done and done!
___
*[v20.2/architecture/overview.md, line 62 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJAtzs68l-PZpF9qCm:-MdOE3yk8QarP-9KUHLu:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L62)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> any of them
> ```

Maybe "Any node"?
</blockquote></details>

Done!
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBAFb-WXmHv3Mmg4H:-MdOEAQuDUBuHAaxGI6j:b-n8znl5) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> if any nodes go down,
> ```

Is it worth adding "(due to tk, tk, tk)" in case this sounds like nodes going down is a routine event?
</blockquote></details>

what is tk? 
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBQ015nh55HNr2ROq:-MdOE_ya9r7ccY188O2R:bl2irgy) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
yeah this phrasing is awkward.  I revised to a list as below, let me know what you think!

> still have copies of the data which can be used for:
> - Continuing to serve reads and writes
> - Consistently replicating the data to other nodes.
___
*[v21.1/architecture/overview.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJI_gM46dGwl834Kst:-MdOHbHT9nTRoN1IuP8Z:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L19)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above re: "architect"
</blockquote></details>

Fixed!
___
*[v21.1/architecture/overview.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJWRqg30W6NVtFKSr-:-MdOHdWTBNdCdIM_xwxG:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L32)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same comment as above: "deployments and applications"?
</blockquote></details>

Fixed!
___
*[v21.1/architecture/overview.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJWXKrAOx8B7be-5I8:-MdOHeiC5Tgn9po6mr4P:bt2vr0y) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L51)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Same suggestions as above.
</blockquote></details>

Fixed!

**Review by taroface — APPROVED** [review]
Nice! Added a few responses.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10847#-:-MdOmjR4BKtNEwBoZm9O:bji476s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans, @rmloveland, and @taroface)

___
*[v20.2/architecture/overview.md, line 26 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJ7Niu-ppNO0ga3hKW:-MdOlYOZ6-fBiK9FsoAN:b8g8s2s) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L26)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

In v20.2 it looks like we don't seem to have the k8s page (operate-cockroachdb-kubernetes.html), so I linked the recommended prod settings as you suggested above
</blockquote></details>

Oh, right. Sounds good!
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBAFb-WXmHv3Mmg4H:-MdOlx6h5mqKxreBTe8F:b-kudhyk) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

what is tk? 
</blockquote></details>

Hmm good point. How about using something like "if any nodes experience liveness issues" and linking to: https://www.cockroachlabs.com/docs/v21.1/cluster-setup-troubleshooting#node-liveness-issues instead?

Caveat: I don't know if all "liveness" issues on a node would immediately cause CRDB to attempt to access another node.

Another idea is to say/link "if any nodes go down (for example, due to liveness issues)".
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBQ015nh55HNr2ROq:-MdOmgu291IwYaD9pYiu:b-6klrdc) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

yeah this phrasing is awkward.  I revised to a list as below, let me know what you think!

> still have copies of the data which can be used for:
> - Continuing to serve reads and writes
> - Consistently replicating the data to other nodes.
</blockquote></details>

Yeah this is great!

**Review by rmloveland — COMMENTED** [review]
thanks for the review Ryan!  I punted on the one thing but only b/c it's so easy to add a slightly technically wrong or misleading statement and I didn't want to stray into that territory since this is an "edit" PR with no eng review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10847#-:-MdSL5ql6u-XxWZp1Rgd:buagaba)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans and @taroface)

___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBQ015nh55HNr2ROq:-MdSL1us3ifg4A2VRksp:bd5l6mr) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Yeah this is great!
</blockquote></details>

thanks!
___
*[v20.2/architecture/overview.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJBAFb-WXmHv3Mmg4H:-MdSLAAbBfSWR_357qlF:b6mvcf7) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v20.2/architecture/overview.md#L66)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Hmm good point. How about using something like "if any nodes experience liveness issues" and linking to: https://www.cockroachlabs.com/docs/v21.1/cluster-setup-troubleshooting#node-liveness-issues instead?

Caveat: I don't know if all "liveness" issues on a node would immediately cause CRDB to attempt to access another node.

Another idea is to say/link "if any nodes go down (for example, due to liveness issues)".
</blockquote></details>

Hmmm I think I will leave this alone for now.  kinda don't want to get into any possible technical correctness issues with this specific PR since I wanted to mostly do edits and skip the eng review. but maybe in the future!
___
*[v21.1/architecture/overview.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/10847#-MdJIXpC8o9xt3HNPwpq:-MdSLrGe9gQkZ7Vzsf9a:b-hbd5m8) ([raw file](https://github.com/cockroachdb/docs/blob/a0455385cb3baecc30cc6da1c5495960b2e49114/v21.1/architecture/overview.md#L16)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Em dashes `—` here?
</blockquote></details>

(did this yesterday and forgot to respond!)

**Pull request merged**
