### PR TITLE
Replace  [] syntax with CTE syntax

### PR DESCRIPTION
**Pull request by stbof**
https://cockroachlabs.atlassian.net/browse/DOC-3410

https://deploy-preview-13843--cockroachdb-docs.netlify.app/docs/dev/table-expressions.html#table-expressions-language

https://deploy-preview-13843--cockroachdb-docs.netlify.app/docs/dev/table-expressions.html#use-the-output-of-another-statement

https://deploy-preview-13843--cockroachdb-docs.netlify.app/docs/dev/subqueries.html#data-writes-in-subqueries

I cannot convert this query: 

https://www.cockroachlabs.com/docs/dev/crdb-internal.html#join-to-show-blocking-statements-text

```
SELECT DISTINCT
  hce.blocking_statement,
  substring(ss2.metadata ->> 'query', 1, 60) AS waiting_statement,
  hce.contention_count
FROM [SELECT
        hce.blocking_txn_fingerprint_id,
        hce.waiting_txn_fingerprint_id,
        hce.contention_count,
        substring(ss.metadata ->> 'query', 1, 60) AS blocking_statement
      FROM [SELECT
              encode(hce.blocking_txn_fingerprint_id, 'hex') as blocking_txn_fingerprint_id,
              encode(hce.waiting_txn_fingerprint_id, 'hex') as waiting_txn_fingerprint_id,
              count(*) AS contention_count
            FROM
              crdb_internal.transaction_contention_events hce
            GROUP BY
              hce.blocking_txn_fingerprint_id, hce.waiting_txn_fingerprint_id
            ] hce,
          crdb_internal.statement_statistics ss
      WHERE
        hce.blocking_txn_fingerprint_id = encode(ss.transaction_fingerprint_id, 'hex')] hce,
      crdb_internal.statement_statistics ss2
WHERE
  hce.blocking_txn_fingerprint_id != '0000000000000000' AND
  hce.waiting_txn_fingerprint_id != '0000000000000000' AND
  hce.waiting_txn_fingerprint_id = encode(ss2.transaction_fingerprint_id, 'hex')
ORDER BY
  contention_count
DESC;
```

### CODE REVIEW

**Comment by stbof** [comment]
@msirek Thank you!

**Review by jordanlewis — APPROVED** [review]
All of the replacements of `[]` with `WITH` look good to me. There are a bunch of other changes that also look good, but I can't say I can properly review them for stylistic uniformity across the rest of the docs or anything like that. Thanks Stephanie!

**Review by nickvigilante — CHANGES_REQUESTED** [review]
A few nits, but otherwise :lgtm_strong: 

> Reviewed 25 of 36 files at r1, 6 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13843#-:-N4D446Z0dvdKX3OZbRG:b-k2wctp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stbof)

___
*[`v22.1/common-table-expressions.md` line 165 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4CzCJIBqa2TsEP-PkY:-N4CzCJIBqa2TsEP-PkZ:bzg9yx7) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/common-table-expressions.md#L165)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> ## Reference multiple common table expressions
> ```

Nit: add a redirect in `_redirects` from the old header to the new header.
___
*[`v22.1/selection-queries.md` line 345 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D1Ur57ZdRtFufz2rp:-N4D1Ur57ZdRtFufz2rq:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/b1dcee4c9a272a0c26d03697f8417c072ff1f8d9/v22.1/selection-queries.md#L345)):*
> ```Markdown
> [Selection clauses](#selection-clauses) are defined in the context of selection queries. [Table expressions](table-expressions.html) are defined in the context of the `FROM` sub-clause of [`SELECT`](select-clause.html). Nevertheless, you can integrate them with one another to form more complex queries or statements.
> 
> ### Use any selection clause as a selection query
> ```

Nit: should add a redirect to this header.
___
*[`v22.1/selection-queries.md` line 385 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D1cvv5sVZ1gAs1fT8:-N4D1cvv5sVZ1gAs1fT9:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/b1dcee4c9a272a0c26d03697f8417c072ff1f8d9/v22.1/selection-queries.md#L385)):*
> ```Markdown
> ~~~
> 
> ### Use any table expression as selection clause
> ```

Nit: should add a redirect to this header.
___
*[`v22.1/selection-queries.md` line 403 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D1eCaE2e3mk9ivE50:-N4D1eCaE2e3mk9ivE51:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/b1dcee4c9a272a0c26d03697f8417c072ff1f8d9/v22.1/selection-queries.md#L403)):*
> ```Markdown
> ~~~
> 
> ### Use any selection query as table expression
> ```

Nit: should add a redirect to this header.
___
*[`v22.1/table-expressions.md` line 54 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D2TQGAKJPCrHrmMzg:-N4D2TQGAKJPCrHrmMzh:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/table-expressions.md#L54)):*
> ```Markdown
> data.
> 
> ### Table and view names
> ```

Nit: should add a redirect to this header.
___
*[`v22.1/table-expressions.md` line 104 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D2Y42Ee0U7Op43hQG:-N4D2Y42Ee0U7Op43hQH:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/table-expressions.md#L104)):*
> ```Markdown
> ~~~
> 
> ### Result from a function
> ```

Nit: should add a redirect to this header.
___
*[`v22.1/table-expressions.md` line 226 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D3Rsd4zUZMp_tHXt4:-N4D3Rsd4zUZMp_tHXt5:b-y89fqg) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/table-expressions.md#L226)):*
> ```Markdown
> ### Ordinality annotation
> 
> Designates a data source equivalent to the table expression operand with
> ```

Incomplete sentence. _What_ designates a data source equivalent?
___
*[`v22.1/table-expressions.md` line 276 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D2aOyAfgB4VNDyifg:-N4D2aOyAfgB4VNDyifh:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/table-expressions.md#L276)):*
> ```Markdown
> See [`JOIN` expressions](joins.html) for more details.
> 
> ## Use another query as a table expression
> ```

Nit: should add a redirect to this header.
___
*[`v22.1/table-expressions.md` line 281 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D2bF08XDoYCHwDq7N:-N4D2bF08XDoYCHwDq7O:b-2f6igf) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/table-expressions.md#L281)):*
> ```Markdown
> another SQL query or statement as a table expression.
> 
> ### Use a subquery
> ```

Nit: should add a redirect to this header.

**Comment by stbof** [comment]
@nickvigilante I don't believe we do redirects for headings, only filename changes.

**Review by nickvigilante — CHANGES_REQUESTED** [review]
One nit not related to redirects left.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13843#-:-N4D60WcCc2G0pwbDFqg:bdxai8x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stbof)

___
*[`v22.1/table-expressions.md` line 226 at r5](https://reviewable.io/reviews/cockroachdb/docs/13843#-N4D3Rsd4zUZMp_tHXt4:-N4D5tsq72F5a4SOE0iT:b-u7hst4) ([raw file](https://github.com/cockroachdb/docs/blob/eaa34424af017ac47794dd513f5a4b163a606fda/v22.1/table-expressions.md#L226)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Incomplete sentence. _What_ designates a data source equivalent?
</blockquote></details>

Not a redirect nit.

**Review by nickvigilante — APPROVED** [review]
We said it was a bit weird to have incomplete sentences directly after a heading. I suggested we create a style ticket to follow-up. Otherwise, great work! LGTM!

**Pull request merged**
