### PR TITLE
Updates to Django Hello World tutorial

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/docs/issues/7998.
Fixes https://github.com/cockroachdb/docs/issues/8898.

### CODE REVIEW

**Review by ianjevans — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @ianjevans)

___
*[v20.2/build-a-python-app-with-cockroachdb-django.md, line 119 at r1](https://reviewable.io/reviews/cockroachdb/docs/8959#-MMNjTFO7F_PoxFc3dYG:-MMNjTFO7F_PoxFc3dYH:b-a488k4) ([raw file](https://github.com/cockroachdb/docs/blob/9b73b177ee9f54708e8c7286273eb3b9b8d09a71/v20.2/build-a-python-app-with-cockroachdb-django.md#L119)):*
> ```Markdown
> ### Models
> 
> Start by building some [models](https://docs.djangoproject.com/en/3.0/topics/db/models/), defined in a file called `models.py`. You can copy the sample code below and paste it into a new file, or you can <a href="https://raw.githubusercontent.com/cockroachdb/examples-orms/master/python/django/cockroach_example/models.py" download>download the file directly</a>.
> ```

Should this point to the Django 3.1 doc?

**Review by ianjevans — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8959)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v20.2/build-a-python-app-with-cockroachdb-django.md, line 119 at r1](https://reviewable.io/reviews/cockroachdb/docs/8959#-MMNjTFO7F_PoxFc3dYG:-MMQxnSV--3NJ3VB4EPX:b6xyjpu) ([raw file](https://github.com/cockroachdb/docs/blob/9b73b177ee9f54708e8c7286273eb3b9b8d09a71/v20.2/build-a-python-app-with-cockroachdb-django.md#L119)):*
> ```
> https://docs.djangoproject.com/en/3.0/topics/db/models/
> ```

Yeah!
Updated all links on this page to point to 3.1 docs.

**Review by ianjevans — APPROVED** [review]

**Comment by ericharmeling** [comment]
TFTR @ianjevans !

**Pull request merged**
