### PR TITLE
Simplify docs feedback

### PR DESCRIPTION
**Pull request by jseldess**
This PR simplifies the feedback widget at the bottom of every docs page. Previously, clicking Yes or No would trigger a popup with a hubspot form. Now, clicking Yes returns a "Thanks for the feedback!" message, and clicking No returns "Thank you! Have specific feedback? Please open an issue." "open an issue" is a link to the docs github repo.

I'd like to roll this out and see if the volume of feedback increases.

@mjibson, do you see ways to clarify or clean this up further?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/841)

### CODE REVIEW

**Comment by jseldess** [comment]
@sploiselle will help pre-populate title of issue with url of page from which feedback is submitted.

**Comment by mjibson** [comment]
This no longer submits the feedback.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/feedback-widget.html, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWER6eTOut--jU37LeQ:-KWER6eTOut--jU37LeR:b-btmdgo) ([raw file](https://github.com/cockroachdb/docs/blob/dee517488855d86e9a04c54836ace0b789437df9/_includes/feedback-widget.html#L17)):*
> ```HTML
> <script>
>   $(document).ready(function(){
>       $("#yes-response, #no-response").hide();
> ```

The spacing here is inconsistent. It apparently should be 2 spaces per indent, but there are 4 here.

---

*[_includes/feedback-widget.html, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWER08ifKNIOj7bjfRK:-KWER08ifKNIOj7bjfRL:bwgh5up) ([raw file](https://github.com/cockroachdb/docs/blob/dee517488855d86e9a04c54836ace0b789437df9/_includes/feedback-widget.html#L19)):*
> ```HTML
>       $("#yes-response, #no-response").hide();
>       $("#yes-button, #no-button").bind("click", function () {
>         $("#yes-response, #no-response").hide();        
> ```

remove whitespace at EOL

---

*[css/components/_feedback-widget.scss, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWEQUL3M_kP4K93T6iL:-KWEQUL3M_kP4K93T6iM:bnul7p7) ([raw file](https://github.com/cockroachdb/docs/blob/dee517488855d86e9a04c54836ace0b789437df9/css/components/_feedback-widget.scss#L51)):*
> ```SCSS
> }
> 
> #yes-response, #no-response {
> ```

I think you can just use `.feedback-question` for this and below instead of the IDs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/841#-:-KWEX_Gk2xIFux3xR6jr:b-ez7ark)*

**Comment by jseldess** [comment]
Yes, we're no longer using hubspot but rather just tracking the click events in Google Analytics. 

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_includes/feedback-widget.html, line 17 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWER6eTOut--jU37LeQ:-KWFFkY1fWZtO9LMWp5k:b4v67u6) ([raw file](https://github.com/cockroachdb/docs/blob/dee517488855d86e9a04c54836ace0b789437df9/_includes/feedback-widget.html#L17)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> The spacing here is inconsistent. It apparently should be 2 spaces per indent, but there are 4 here.
</details>
I've simplified the jquery based on your input. Thanks!

---

*[_includes/feedback-widget.html, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWER08ifKNIOj7bjfRK:-KWFFo6Uy1B8SQTExlmg:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/dee517488855d86e9a04c54836ace0b789437df9/_includes/feedback-widget.html#L19)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> remove whitespace at EOL
</details>
Done.

---

*[css/components/_feedback-widget.scss, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWEQUL3M_kP4K93T6iL:-KWFFpF9o8HbsIO97rvn:b-8prufk) ([raw file](https://github.com/cockroachdb/docs/blob/dee517488855d86e9a04c54836ace0b789437df9/css/components/_feedback-widget.scss#L51)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I think you can just use `.feedback-question` for this and below instead of the IDs.
</details>
Through simplified jquery, I've removed some of the css.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/841#-:-KWEqIx2avvdOVOq_Eyj:bpfb5bf)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_includes/feedback-widget.html, line 10 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWGjaIjYNRTD_qedJ_A:-KWGjaIjYNRTD_qedJ_B:b-mcxgbd) ([raw file](https://github.com/cockroachdb/docs/blob/df9456a3845ac4d5f6a39183e14b5699b07d5496/_includes/feedback-widget.html#L10)):*
> ```HTML
>   $(document).ready(function(){
>       $("#yes-button, #no-button").bind("click", function () {
>         $("#yes-response, #no-response").hide();        
> ```

This line can go away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/841)*

**Comment by mjibson** [comment]
:lgtm: after my comment

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/841#-:-KWGk4LKEtKNTpNLrOGU:b-8knjdu)*

**Comment by jseldess** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[_includes/feedback-widget.html, line 10 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/841#-KWGjaIjYNRTD_qedJ_A:-KWI2Kq480N_7KdWwrJx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/df9456a3845ac4d5f6a39183e14b5699b07d5496/_includes/feedback-widget.html#L10)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> This line can go away.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/841)*

**Comment by jseldess** [comment]
@sploiselle, let's do pre-populate the issue title in a follow-up PR. I create an issue for you: #844

**Pull request merged**
