### PR TITLE
New ignore_unsupported_statements and log_ignored_statements options for PGDUMP

### LINKED ISSUE #10147: cli: add new pgdump/mysqldump flags to import cli command
PR: https://github.com/cockroachdb/cockroach/pull/60923

From release notes:
> Added the `ignore-unsupported-statements`, `log-ignored-statements` and `row-limit` flags to the [`cockroach import`](../v21.1/cockroach-import.html) command. [#60923][#60923] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ianjevans**
Fixes #10147.

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Looks good! I just had a few comments (mainly nits).

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10186#-:-MWyhzNx8RC5Fg-TMjKb:bxwzl75)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans and @lnhsingh)

___
*[v21.1/cockroach-import.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWyeT_xArvkBlTP2q4a:-MWyeT_xArvkBlTP2q4b:b-xx76ci) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/cockroach-import.md#L49)):*
> ```Markdown
> `--insecure`     | Use an insecure connection.<br><br>**Env Variable:** `COCKROACH_INSECURE`<br>**Default:** `false`
> `--user`<br>`-u` | The [SQL user](create-user.html) that will own the client session.<br><br>**Env Variable:** `COCKROACH_USER`<br>**Default:** `root`
> `--ignore-unsupported-statements=` | Ignore statements that are unsupported during an import from a PGDUMP file. <br/>**Default:** `false`
> ```

For all features added in 21.1, you'll need to add the following:

```
<span class="version-tag">New in v21.1:</span> 
```

We usually place these at the beginning of the "Description" column row when they are flags in tables.

This applies to the rest of the new flags on this page as well.

I just now saw that you do this for the new `IMPORT` parameters, but you probably should also do so here, as this is a separate flag for a CLI command.
___
*[v21.1/cockroach-import.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWyfI3z7SatwAu7H8_L:-MWyfI3z7SatwAu7H8_M:b-5mdrhd) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/cockroach-import.md#L83)):*
> ```Markdown
> 
> ### Import a database with unsupported SQL syntax and log all unsupported statements
> ```

I think we also add the `<span class="version-tag">New in v21.1:</span>` to examples (at the beginning of the first sentence, and not to the header), but it's not as essential as it is to the syntax tables.
___
*[v21.1/cockroach-import.md, line 96 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWyfACm6sKuuDxlSG8K:-MWyfACm6sKuuDxlSG8L:b-6vs64h) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/cockroach-import.md#L96)):*
> ```Markdown
> 
> ### Import a limited number of rows from a dump file
> ```

Add an intro here, to be consistent with the examples above (e.g. "To limit the number of rows imported ...").
___
*[v21.1/import.md, line 97 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWyfejb848AiPaIYWuD:-MWyfejb848AiPaIYWuE:b-rcfyku) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/import.md#L97)):*
> ```
> <span class="version-tag">New in v21.1:</span> 
> ```

Nice.
___
*[v21.1/import.md, line 719 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWyfmfz15c9ZGZCwIp-:-MWyfmfz15c9ZGZCwIp0:b23uz7q) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/import.md#L719)):*
> ```Markdown
> > IMPORT PGDUMP 's3://your-external-storage/employees.sql?AWS_ACCESS_KEY_ID=[placeholder]&AWS_SECRET_ACCESS_KEY=[placeholder]' WITH ignore_unsupported_statements;
> ~~~
> ```

You might want to add a note here about why you are using `WITH ignore_unsupported_statements` (i.e., that the example statement fails without it as of 21.1).
___
*[v21.1/migrate-from-postgres.md, line 87 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWygxro2jR7ZYTljUbH:-MWygxro2jR7ZYTljUbI:b-vi9axw) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/migrate-from-postgres.md#L87)):*
> ```
> WITH ignore_unsupported_statements;
> ```

You might want to add a note here about why you are using `WITH ignore_unsupported_statements` (i.e., that the example statement fails without it as of 21.1).
___
*[v21.1/migrate-from-postgres.md, line 194 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWygClD3LElXsYU1s8j:-MWygClE1bn4w-NY7xxP:b-9qnb9w) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/migrate-from-postgres.md#L194)):*
> ```
> **Default: false**. 
> ```

Suggestion: put a line break after `**Default: false**.`
___
*[v21.1/migrate-from-postgres.md, line 194 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MWygJxTCJ0-7La3R8I_:-MWygJxTCJ0-7La3R8Ia:b-nxs6kf) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/migrate-from-postgres.md#L194)):*
> ```
> If unset
> ```

Note sure what "unset" means here. Does it mean "If set to `true`?" Does it just mean "if not specified"? Or is there an "unset" keyword for parameters?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10186)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v21.1/cockroach-import.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MX3u_4C7c5sn78Gzm9q:-MX3u_4C7c5sn78Gzm9r:b3u6biw) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/cockroach-import.md#L49)):*
> ```Markdown
> `--insecure`     | Use an insecure connection.<br><br>**Env Variable:** `COCKROACH_INSECURE`<br>**Default:** `false`
> `--user`<br>`-u` | The [SQL user](create-user.html) that will own the client session.<br><br>**Env Variable:** `COCKROACH_USER`<br>**Default:** `root`
> `--ignore-unsupported-statements=` | Ignore statements that are unsupported during an import from a PGDUMP file. <br/>**Default:** `false`
> ```

nit: On CLI flags, we usually don't include the `=` in the flag name
___
*[v21.1/cockroach-import.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MX3x7cTEw08SjwmfISY:-MX3x7cTEw08SjwmfISZ:b-lyso2z) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/cockroach-import.md#L50)):*
> ```Markdown
> `--user`<br>`-u` | The [SQL user](create-user.html) that will own the client session.<br><br>**Env Variable:** `COCKROACH_USER`<br>**Default:** `root`
> `--ignore-unsupported-statements=` | Ignore statements that are unsupported during an import from a PGDUMP file. <br/>**Default:** `false`
> `--log-ignored-statements=` | Log statements that are ignored during an import from a PGDUMP file to the specified destination.
> ```

I think `specified destination` > `specified destination (i.e., [cloud storage](use-cloud-storage-for-bulk-operations.html) or [userfile storage](use-userfile-for-bulk-operations.html).`

Also, Michael had noted in https://github.com/cockroachdb/docs/issues/9494 the following:

```
--log-ignored-statements="'filelocation'"
^Note the weird quoting on that last one. It's being looked at cockroachdb/cockroach#62464
```

Do we want to document this weirdness now? Or hope that the bug will be fixed?
___
*[v21.1/cockroach-import.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MX3uw4u4eWp9tNDDB9r:-MX3uw4u4eWp9tNDDB9s:bhgzvb5) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/cockroach-import.md#L51)):*
> ```Markdown
> `--ignore-unsupported-statements=` | Ignore statements that are unsupported during an import from a PGDUMP file. <br/>**Default:** `false`
> `--log-ignored-statements=` | Log statements that are ignored during an import from a PGDUMP file to the specified destination.
> `--row-limit=` | Specify the number of rows that will be imported for each table during a PGDUMP or MYSQLDUMP import. <br/> This can be used to check schema and data correctness without running
> ```

Could this description be tightened up a bit? Maybe `The number of rows to import for each table during a PGDUMP or MYSQLDUMP import.`?

Also there's a formatting issue going on here, i think because there's a misplaced return after `running`.
___
*[v21.1/import.md, line 98 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MX3xwXC4hq6ehnZeuv-:-MX3vwh00wB2kS3qdB0C:b3tij8p) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/import.md#L98)):*
> ```Markdown
> `max_row_size`         | `PGDUMP`        | Override limit on line size. **Default: 0.5MB**.  This setting may need to be tweaked if your Postgres dump file has extremely long lines, for example as part of a `COPY` statement.
> `ignore_unsupported_statements` | `PGDUMP`  | <span class="version-tag">New in v21.1:</span> Ignore SQL statements in the dump file that are unsupported by CockroachDB.
> `log_ignored_statements` | `PGDUMP` | <span class="version-tag">New in v21.1:</span> Log unsupported statements when using `ignore_unsupported_statements` to a specified destination.
> ```

Same as above - I think `specified destination` > `specified destination (i.e., [cloud storage](use-cloud-storage-for-bulk-operations.html) or [userfile storage](use-userfile-for-bulk-operations.html).`
___
*[v21.1/migrate-from-postgres.md, line 194 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MX3wOBoEtKJUftXOYmX:-MX3wOBoEtKJUftXOYmY:b-fmd348) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/migrate-from-postgres.md#L194)):*
> ```
> ignore_unsupported_statements` option
> ```

Might be useful to link to `import.html#import-options` here
___
*[v21.1/migrate-from-postgres.md, line 205 at r1](https://reviewable.io/reviews/cockroachdb/docs/10186#-MX3wYs6DZRfXYTgH7Fx:-MX3wYs6DZRfXYTgH7Fy:b-xvukpf) ([raw file](https://github.com/cockroachdb/docs/blob/e3b81df5a476b5a6461a64eff76101db4c03fe4c/v21.1/migrate-from-postgres.md#L205)):*
> ```Markdown
> ### Log unsupported statements
> 
> <span class="version-tag">New in v21.1:</span> The `log_ignored_statements` is used with `ignore_unsupported_statements` to log unsupported statements in the `PGDUMP` file to specified a destination file.
> ```

nit: `The log_ignored_statements is used with ignore_unsupported_statements ...` > `The log_ignored_statements option is used with ignore_unsupported_statements option ...`

Also maybe link to `import.html#import-options` here too

**Comment by lnhsingh** [comment]
Also fixes #9494

**Comment by ianjevans** [comment]
Fixed all those except...

> Also, Michael had noted in #9494 the following:
> 
> ```
> --log-ignored-statements="'filelocation'"
> ^Note the weird quoting on that last one. It's being looked at cockroachdb/cockroach#62464
> ```
> 
> Do we want to document this weirdness now? Or hope that the bug will be fixed?

I have a deep aversion to documenting bug workarounds in a main doc, but after reading cockroachdb/cockroach#62464 I'm not sure if this will be fixed soon. Might have to leave this now, and if it is fixed it will get caught by the generated RN issue.

**Review by ericharmeling — APPROVED** [review]
Looks great!

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10186#-:-MX7WlY33KBUWwB4IBjE:b9bkkp1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

**Review by lnhsingh — COMMENTED** [review]
Re: documenting bug workarounds - that's fine with me. We could always come back to it if it doesn't get fixed / is causing issues.

:lgtm: - thanks for documenting this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10186#-:-MX7bwWU38jpyYtTJk8l:b-vlg9vz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans)

**Pull request merged**
