### PR TITLE
create TIME docs

### LINKED ISSUE #2250: Add TIME column type and datum
PR: https://github.com/cockroachdb/cockroach/pull/19923

### PR DESCRIPTION
**Pull request by lhirata**
Fixes #2250

### CODE REVIEW

**Comment by solongordon** [comment]
Nice! I left some thoughts, mostly picky stuff.

---

Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[v2.0/interval.md, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MjlMBR35n0Sd6pmfZ:-L2MjlMBR35n0Sd6pmf_:b-qg0vyr) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/interval.md#L99)):*
> ```Markdown
> `FLOAT` | Converts to number of picoseconds
> `STRING` | Converts to `h-m-s` format (nanosecond precision)
> `TIME` | <span class="version-tag">New in v2.0:</span> Converts to `HH:MM:SS` (microsecond precision)
> ```

Could be more clear that this is the time equivalent to that interval after midnight.

---

*[v2.0/time.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Mduoo7yDdutJIpN8l:-L2Mduop_7GhQcOnQHnM:b52tg6s) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L3)):*
> ```Markdown
> ---
> title: TIME
> summary: The TIME data type stores a time in UTC.
> ```

It would be more accurate to say it stores a time of day without timezone.

---

*[v2.0/time.md, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Me2Y1aZun10X2b-jh:-L2Me2Y2xCmPVZqtQtV9:b9ssfxw) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L6)):*
> ```Markdown
> toc: false
> ---
> <span class="version-tag">New in v2.0:</span> The `TIME` [data type](data-types.html) stores the time of day as an `int64` representing microseconds since midnight (00:00:00) UTC.
> ```

Scratch "UTC". Also I wonder if we really need to describe how it's stored since that's an implementation detail most users won't care about. I would say it's enough to say it stores a time of day without time zone.

---

*[v2.0/time.md, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MgwQ6BvepHiQXCm-X:-L2MgwQ6BvepHiQXCm-Y:bec689o) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L12)):*
> ```Markdown
> ## Considerations
> 
> - `TIME` does not support any time formats beyond what we already support in the time portion of [`TIMESTAMP`](timestamp.html).
> ```

"already" sounds a little off to me since the reader won't necessarily know we supported TIMESTAMP before TIME. Actually we could probably ditch this line entirely since the Syntax section should cover supported formats.

---

*[v2.0/time.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MhGvOpQplJAf1oTCi:-L2MhGvOpQplJAf1oTCj:b-j005y3) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L13)):*
> ```Markdown
> 
> - `TIME` does not support any time formats beyond what we already support in the time portion of [`TIMESTAMP`](timestamp.html).
> - The fractional portion of `TIME` is optional and is rounded to microseconds (i.e., six digits after the decimal) for compatibility with the PostgreSQL wire protocol.
> ```

Move to the bottom of Syntax perhaps?

---

*[v2.0/time.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MiBpZIJa_0xTYje0H:-L2MiBpZIJa_0xTYje0I:b2nwjsp) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L14)):*
> ```Markdown
> - `TIME` does not support any time formats beyond what we already support in the time portion of [`TIMESTAMP`](timestamp.html).
> - The fractional portion of `TIME` is optional and is rounded to microseconds (i.e., six digits after the decimal) for compatibility with the PostgreSQL wire protocol.
> ```

Btw, `TIME WITHOUT TIME ZONE` is also a supported alias. Maybe you'll want to have an Aliases section like the TIMESTAMP doc.

---

*[v2.0/time.md, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Mhbjbqk-3rrY9__cM:-L2Mhbjbqk-3rrY9__cN:bq08yvm) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L25)):*
> ```Markdown
> `TIME`.
> 
> The string format for time is `HH:MM:SS`. For example: `TIME '05:40:00'`.
> ```

Minor: Maybe `HH:MM:SS.ssssss` (or however you're supposed to write that) to make it clear microseconds are supported?

---

*[v2.0/time.md, line 79 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MifwoORTY0qJc5k6X:-L2MifwoORTY0qJc5k6Y:b-bc7z9s) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L79)):*
> ```Markdown
> Type | Details
> -----|--------
> `INT` | Converts to the span of time since midnight (00:00)
> ```

`INTERVAL`, not `INT`

---

*[v2.0/time.md, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Miy9w3WjN3VEepVYM:-L2Miy9w3WjN3VEepVYN:b-kbwdjw) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L82)):*
> ```Markdown
> `STRING` | Converts to format `'HH:MM:SS'` (microsecond precision)
> 
> {{site.data.alerts.callout_info}}Because the <a href="serial.html"><code>SERIAL</code> data type</a> represents values automatically generated by CockroachDB to uniquely identify rows, you cannot meaningfully cast other data types as <code>SERIAL</code> values.{{site.data.alerts.end}}
> ```

Is this relevant since we can't cast from INTs to TIME anyway?

---

*[v2.0/time.md, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Mj00J9bu--plpVDfS:-L2Mj00J9bu--plpVDfT:bw506le) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L86)):*
> ```Markdown
> ## See Also
> 
> [Data Types](data-types.html)
> ```

I think TIME still needs to be added here.

---

*[v2.0/timestamp.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MjLqozskchSoxVbKH:-L2MjLqozskchSoxVbKI:b-q8issz) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/timestamp.md#L108)):*
> ```Markdown
> `DECIMAL` | Converts to number of seconds since the Unix epoch (Jan. 1, 1970)
> `FLOAT` | Converts to number of seconds since the Unix epoch (Jan. 1, 1970)
> `TIME` | <span class="version-tag">New in v2.0:</span> Displays the time portion (HH:MM:SS) of the timestamp
> ```

"Displays" doesn't sound quite right to me since maybe we're storing it not displaying. Maybe "Converts to the..." instead? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-:-L2Mkj6turcX1alNrf7P:b-gcdmtj)*

**Comment by lhirata** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[v2.0/interval.md, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MjlMBR35n0Sd6pmfZ:-L2MuKgaQdKR3AoTTxlh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/interval.md#L99)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Could be more clear that this is the time equivalent to that interval after midnight.
</blockquote></details>

Done.

---

*[v2.0/time.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Mduoo7yDdutJIpN8l:-L2MuJiNkQnpvRqQhXvT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L3)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

It would be more accurate to say it stores a time of day without timezone.
</blockquote></details>

Done.

---

*[v2.0/time.md, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Me2Y1aZun10X2b-jh:-L2MuWuegT_Rg8hMwUio:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L6)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Scratch "UTC". Also I wonder if we really need to describe how it's stored since that's an implementation detail most users won't care about. I would say it's enough to say it stores a time of day without time zone.
</blockquote></details>

Done.

---

*[v2.0/time.md, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MgwQ6BvepHiQXCm-X:-L2Mv6yJXMZqTyziEsq3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L12)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

"already" sounds a little off to me since the reader won't necessarily know we supported TIMESTAMP before TIME. Actually we could probably ditch this line entirely since the Syntax section should cover supported formats.
</blockquote></details>

Done.

---

*[v2.0/time.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MhGvOpQplJAf1oTCi:-L2Mv8ERWv6HNbUOD-tJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L13)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Move to the bottom of Syntax perhaps?
</blockquote></details>

Done.

---

*[v2.0/time.md, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MiBpZIJa_0xTYje0H:-L2MvOhKTZDjEGPapyjK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L14)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Btw, `TIME WITHOUT TIME ZONE` is also a supported alias. Maybe you'll want to have an Aliases section like the TIMESTAMP doc.
</blockquote></details>

Done.

---

*[v2.0/time.md, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Mhbjbqk-3rrY9__cM:-L2MvXEkrsgcz8VN8AQb:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L25)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Minor: Maybe `HH:MM:SS.ssssss` (or however you're supposed to write that) to make it clear microseconds are supported?
</blockquote></details>

Done.

---

*[v2.0/time.md, line 79 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MifwoORTY0qJc5k6X:-L2Mvex4g-7xA3r1CYYA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L79)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

`INTERVAL`, not `INT`
</blockquote></details>

Done.

---

*[v2.0/time.md, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Miy9w3WjN3VEepVYM:-L2MwCz4HkMhnVogxAN-:ba3dfob) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L82)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Is this relevant since we can't cast from INTs to TIME anyway?
</blockquote></details>

Removed

---

*[v2.0/time.md, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Mj00J9bu--plpVDfS:-L2MwJc6dc-A0hZ5E_n7:bsygeju) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L86)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I think TIME still needs to be added here.
</blockquote></details>

Good catch! Added.

---

*[v2.0/timestamp.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2MjLqozskchSoxVbKH:-L2Mwr0ecPSWGZTh_oxL:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/timestamp.md#L108)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

"Displays" doesn't sound quite right to me since maybe we're storing it not displaying. Maybe "Converts to the..." instead? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336)*

**Comment by solongordon** [comment]
:lgtm: pending a few more small fixes.

---

Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v2.0/data-types.md, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Qa4kQc6zRKB65B8Lq:-L2Qa4kQc6zRKB65B8Lr:bafilh1) ([raw file](https://github.com/cockroachdb/docs/blob/70337a0ec5f48a368543deaf6c6a62779c1617ce/v2.0/data-types.md#L20)):*
> ```Markdown
> [`BOOL`](bool.html) | A Boolean value. | `true`
> [`DATE`](date.html) | A date. | `DATE '2016-01-25'`
> [`TIME`](time.html) | A time. | `TIME '01:23:45.123456'`
> ```

`time of day` would be clearer, or even `time of day (no time zone)`

---

*[v2.0/time.md, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Miy9w3WjN3VEepVYM:-L2Q_tcBlnhvc3Giswmf:bhk73fr) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L82)):*
<details><summary><i>Previously, lhirata wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Seems to still be there?

---

*[v2.0/time.md, line 3 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Q_Mqw0DX_RAyq3teD:-L2Q_MqxmJidQ37h0fQu:byb2raz) ([raw file](https://github.com/cockroachdb/docs/blob/70337a0ec5f48a368543deaf6c6a62779c1617ce/v2.0/time.md#L3)):*
> ```Markdown
> ---
> title: TIME
> summary: The TIME data type stores a time time of day without a time zone.
> ```

It says `time` twice in a row now.

---

*[v2.0/time.md, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2QbC2nrv-Zu1SBkV9c:-L2QbC2nrv-Zu1SBkV9d:b-84ugd7) ([raw file](https://github.com/cockroachdb/docs/blob/70337a0ec5f48a368543deaf6c6a62779c1617ce/v2.0/time.md#L74)):*
> ```Markdown
> +---+---------------------------+
> ~~~
> {{site.data.alerts.callout_info}}Cockroach SQL displays the date and timezone, but they aren’t relevant or stored in the database.{{site.data.alerts.end}}
> ```

Just realized "Cockroach SQL" is a little confusing. Maybe clearer to say `cockroach sql` or "the built-in SQL client."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-:-L2Qbow5lPhY13FlnJP-:bemkx8w)*

**Comment by lhirata** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v2.0/time.md, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Miy9w3WjN3VEepVYM:-L2Qk1YjLeam_eBWEgvJ:b-18lbjl) ([raw file](https://github.com/cockroachdb/docs/blob/ce404fc87c3a3317c6394c9cad7cdcdb7ee93e8d/v2.0/time.md#L82)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Seems to still be there?
</blockquote></details>

Oops. Now it should be removed.

---

*[v2.0/time.md, line 3 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2Q_Mqw0DX_RAyq3teD:-L2QjuY_hjoq5vvqYQl4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/70337a0ec5f48a368543deaf6c6a62779c1617ce/v2.0/time.md#L3)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

It says `time` twice in a row now.
</blockquote></details>

Done.

---

*[v2.0/time.md, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2QbC2nrv-Zu1SBkV9c:-L2QjvJOUyb9SXelkZxs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/70337a0ec5f48a368543deaf6c6a62779c1617ce/v2.0/time.md#L74)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Just realized "Cockroach SQL" is a little confusing. Maybe clearer to say `cockroach sql` or "the built-in SQL client."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336)*

**Comment by solongordon** [comment]
Reviewed 1 of 5 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[v2.0/string.md, line 99 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2X1VR4jXgrMefjWmhk:-L2X1VR5Wg1Xq6vIzrpa:b-9v6z36) ([raw file](https://github.com/cockroachdb/docs/blob/47c5429a4d46afe1d4bcb8f41f13519ad14ccae7/v2.0/string.md#L99)):*
> ```Markdown
> `BOOL` | Requires supported [`BOOL`](bool.html) string format, e.g., `'true'`.
> `DATE` | Requires supported [`DATE`](date.html) string format, e.g., `'2016-01-25'`.
> `TIME` | <span class="version-tag">New in v2.0:</span> Requires supported [`TIME`](time.html) string format, e.g., `01:22:12` (microsecond precision).
> ```

I think the example should be `'01:22:12'`?

---

*[v2.0/string.md, line 100 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2X1c8Tx50X55XzBdp7:-L2X1c8UBdFJ8DF2fdFd:bgqpndr) ([raw file](https://github.com/cockroachdb/docs/blob/47c5429a4d46afe1d4bcb8f41f13519ad14ccae7/v2.0/string.md#L100)):*
> ```Markdown
> `DATE` | Requires supported [`DATE`](date.html) string format, e.g., `'2016-01-25'`.
> `TIME` | <span class="version-tag">New in v2.0:</span> Requires supported [`TIME`](time.html) string format, e.g., `01:22:12` (microsecond precision).
> `TIMESTAMP` | Requires supported [`TIMESTAMP`](timestamp.html) string format, e.g., `''2016-01-25 10:10:10.555555''`.
> ```

While you're here, I think we can remove one apostrophe from each end.

---

*[v2.0/time.md, line 38 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2WzkSCN7v4OiILPXK5:-L2WzkSDwp4fyZOXytbv:b-tjqkrh) ([raw file](https://github.com/cockroachdb/docs/blob/47c5429a4d46afe1d4bcb8f41f13519ad14ccae7/v2.0/time.md#L38)):*
> ```Markdown
> A `TIME` column supports values up to 8 bytes in width, but the total storage size is likely to be larger due to CockroachDB metadata.
> 
> ## Examples
> ```

Let's make this singular: `Example`.

---

*[v2.0/time.md, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2WzzJN9HZDaesCaMl3:-L2WzzJN9HZDaesCaMl4:bc24ofp) ([raw file](https://github.com/cockroachdb/docs/blob/47c5429a4d46afe1d4bcb8f41f13519ad14ccae7/v2.0/time.md#L74)):*
After chatting with @solongordon, I think we should clarify and expand this note a little. This relates to the go sql driver our shell is using, and some other sql drivers may behave similarly. Here's a recommended revision:

> The `cockroach sql` shell displays the date and timezone due to the Go sql driver it uses. Some other client drivers may behave similarly. In such cases, however, the date and timezone are not relevant and are not stored in the database. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336)*

**Comment by jseldess** [comment]
:lgtm:, with some final, minor edits

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-:-L2X1txTHA0MuYpbMcOG:b-a5768l)*

**Comment by solongordon** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[v2.0/time.md, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/2336#-L2WzzJN9HZDaesCaMl3:-L2X4Q9Wj-362IC-30Fw:b4c9lyr) ([raw file](https://github.com/cockroachdb/docs/blob/47c5429a4d46afe1d4bcb8f41f13519ad14ccae7/v2.0/time.md#L74)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

After chatting with @solongordon, I think we should clarify and expand this note a little. This relates to the go sql driver our shell is using, and some other sql drivers may behave similarly. Here's a recommended revision:

> The `cockroach sql` shell displays the date and timezone due to the Go sql driver it uses. Some other client drivers may behave similarly. In such cases, however, the date and timezone are not relevant and are not stored in the database. 
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/2336)*

**Pull request merged**
