### PR TITLE
DOC-5188 DOC-5296 RBAC new sys privs

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-5188, DOC-5296

- Added new system privilege versions of existing roles:
	- VIEWACTIVITY
	- VIEWACTIVITYREDACTED
	- VIEWCLUSTERSETTING
	- CANCELQUERY
	- NOSQLLOGIN
- Adds new observability system privileges:
	- VIEWDEBUG
	- VIEWCLUSTERMETADATA
- Updated mention of deprecated roles with new system privileges, framing roles as "legacy" (to match live CDC and BulkIO language for this effort)
- Added "or user in the `admin` role" to several statements, as your code confirms you check for both.

NOTES:

- Ignore double "Role Options" on create-user, etc pages. Have D O C - 6 2 2 8 to fix sitewide after this effort (present in live dev docs, not related to this PR).

QUESTIONS:

- Updated `hot ranges` page to indicate that `VIEWCLUSTERMETADATA` priv is now required. Explicitly indicated that legacy `VIEWACTIVITY` and `VIEWACTIVITYREDACTED` roles still work, but that new `VIEWACTIVITY` and `VIEWACTIVITYREDACTED` privs do not. Just confirming that this correct. (i.e. you permit legacy roles to work in v22.2 for this one release only, and users should be using the new `VIEWCLUSTERMETADATA` priv for this)?
- Any uses for `VIEWDEBUG` outside of (undocumented) debug endpoints and (seemingly-undocumented) trace-taking? Otherwise, it now appears only on the privs list table, and nowhere else. Or:
- Is [this](https://www.cockroachlabs.com/docs/stable/show-trace.html#required-privileges) still accurate, or maybe does [this](https://www.cockroachlabs.com/docs/stable/cockroach-debug-job-trace.html) now require `VIEWDEBUG`?
- Another clarification: `NOSQLLOGIN` is deprecated ... but `SQLLOGIN` is not? Same with all inverse-refutation-named privs basically: am I missing something in my notation that the one listed (in your code) is deprecated, while the one not (present in your code) is still alive? Both versions still work for me in v22.2.0-rc.3, but then even the deprecated ones are guaranteed to last one more GA release, per design. Just checking, thank you.

SELECTED STAGING:

- [authorization.md](https://deploy-preview-15652--cockroachdb-docs.netlify.app/docs/dev/security-reference/authorization.html#supported-privileges) | [#role-options](https://deploy-preview-15652--cockroachdb-docs.netlify.app/docs/v22.2/create-user#role-options) | [ui-hot-ranges-page.md](https://deploy-preview-15652--cockroachdb-docs.netlify.app/docs/v22.2/ui-hot-ranges-page.html) | [cancel-query.md](https://deploy-preview-15652--cockroachdb-docs.netlify.app/docs/v22.2/cancel-query.html#required-privileges) | [ui-debug-pages.md](https://deploy-preview-15652--cockroachdb-docs.netlify.app/docs/dev/ui-debug-pages.html#required-privileges) | [ui-overview.md](https://deploy-preview-15652--cockroachdb-docs.netlify.app/docs/dev/ui-overview.html#advanced-debug)

### CODE REVIEW

**Review by thtruo — COMMENTED** [review]
Nice, thanks @andf-crl! Left a few nits and responses to your questions below:

> Updated hot ranges page to indicate that VIEWCLUSTERMETADATA priv is now required. Explicitly indicated that legacy VIEWACTIVITY and VIEWACTIVITYREDACTED roles still work, but that new VIEWACTIVITY and VIEWACTIVITYREDACTED privs do not. Just confirming that this correct. (i.e. you permit legacy roles to work in v22.2 for this one release only, and users should be using the new VIEWCLUSTERMETADATA priv for this)?

Yes that is correct, users should be using the `VIEWCLUSTERMETADATA` privilege to view the hot ranges page. `VIEWACTIVITY` and `VIEWACTIVITYREDACTED` privileges should not allow it. 

I know this is slightly confusing, so I'll share some context. In prior releases, we lacked a granular privilege/role to give a SQL user permissions to look at range related activity (it was gated by ADMIN). So we gated this behind `VIEWACTIVITY` as a stop gap. Ideally, all access to range related reports should be separated out into a different gate. Because we're introducing `VIEWCLUSTERMETADATA` in 22.2, we want to gate the hot ranges page and similar views behind this privilege.

Let me know if you have other thoughts related to this.

> Any uses for VIEWDEBUG outside of (undocumented) debug endpoints and (seemingly-undocumented) trace-taking? Otherwise, it now appears only on the privs list table, and nowhere else. Or:

That sounds correct. One idea is to make a mention of `VIEWDEBUG` in this doc https://www.cockroachlabs.com/docs/dev/ui-debug-pages.html and to call out the fact that this privilege gates the usage of debug/profiling endpoints and tracing. 

> Is this still accurate, or maybe does this now require VIEWDEBUG?

For the first one https://www.cockroachlabs.com/docs/stable/show-trace.html#required-privileges, I'm surprised that no privileges were required for running `SHOW TRACE FOR SESSION`. I don't believe we've made explicit changes here cc @santamaura to confirm.

For the second one https://www.cockroachlabs.com/docs/stable/cockroach-debug-job-trace.html, this refers to a cockroach CLI command which isn't gated by system privileges (the CLI command is not a SQL statement) so no need to make a mention of this requiring `VIEWDEBUG`


> Another clarification: NOSQLLOGIN is deprecated ... but SQLLOGIN is not? Same with all inverse-refutation-named privs basically: am I missing something in my notation that the one listed (in your code) is deprecated, while the one not (present in your code) is still alive? Both versions still work for me in v22.2.0-rc.3, but then even the deprecated ones are guaranteed to last one more GA release, per design. Just checking, thank you.

@santamaura can you clarify this point?

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15652#-:-NI33u3S9YjR9hNgHcEM:b14ffbj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andf-crl and @Santamaura)

___
*[`v22.2/cockroach-sql.md` line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/15652#-NI33F3w8v9y64zGxp9M:-NI33F3w8v9y64zGxp9N:b-31dk4j) ([raw file](https://github.com/cockroachdb/docs/blob/89e8ab4130ce77ede36148c1ad76fbf99b0fc7ce/v22.2/cockroach-sql.md#L21)):*
> ```Markdown
> ## Prerequisites
> 
> The [role option of the user](create-role.html#role-options) logging in must be `LOGIN` or `SQLLOGIN`, which are granted by default. If the user has been set to use the `NOLOGIN` role or the `NOSQLLOGIN` [system privilege](security-reference/authorization.html#supported-privileges) (or the legacy `NOSQLLOGIN` role), the user cannot log in using the SQL CLI with any authentication method.
> ```

Nit: say "role option" instead of just "role"



_Code quote:_
```Markdown
role
```
___
*[`v22.2/cockroach-sql-binary.md` line 67 at r1](https://reviewable.io/reviews/cockroachdb/docs/15652#-NI33ONh6_X6a7MGOgBd:-NI33ONh6_X6a7MGOgBe:b-iukoux) ([raw file](https://github.com/cockroachdb/docs/blob/89e8ab4130ce77ede36148c1ad76fbf99b0fc7ce/v22.2/cockroach-sql-binary.md#L67)):*
> ```Markdown
> ## Prerequisites
> 
> The [role option of the user](security-reference/authorization.html#role-options) logging in must be `LOGIN` or `SQLLOGIN`, which are granted by default. If the user has been set to use the `NOLOGIN` role or the `NOSQLLOGIN` [system privilege](security-reference/authorization.html#supported-privileges) (or the legacy `NOSQLLOGIN` role option), the user cannot log in using the SQL CLI with any authentication method.
> ```

Nit: use "role option" instead of "role"



_Code quote:_
```Markdown
role
```

**Comment by Santamaura** [comment]
> I'm surprised that no privileges were required for running SHOW TRACE FOR SESSION. I don't believe we've made explicit changes here

We made no explicit changes to this sql command

> @Santamaura can you clarify this point?

We added a `NOSQLLOGIN` system privilege since we only needed one of them (if user has it they can't login and if not they can). The role options are deprecated but we still defer to them to regulate access for now.

**Comment by andf-crl** [comment]
@thtruo @Santamaura TYFR both! Tommy I've added notice of `VIEWDEBUG` requirement to **Advanced Debug** and **Overview** pages, thanks for this! Otherwise, things look good on the engineering side before I send off to copy review? Thanks!!

**Review by thtruo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15652#-:-NI3lsu34mQ1Cb01e07D:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andf-crl and @Santamaura)

**Comment by shannonbradshaw** [comment]
@andf-crl go ahead and assign to me as copy reviewer. I reviewed and LGTM.

**Comment by shannonbradshaw** [comment]
@andf-crl it looks like @Santamaura is implicitly LGTM? My take is that we can unblock and merge. Let me know if you feel differently.

**Comment by andf-crl** [comment]
Thanks so much @shannonbradshaw !! I've added you as reviewer: just `Approve` from the green `Review Changes` button [upper right](https://github.com/cockroachdb/docs/pull/15652/files) when you get a chance. I'll get this merged -- thanks again!!

**Pull request merged**
