### PR TITLE
DOC-1055: Add info about UUID uniqueness cluster setting

### PR DESCRIPTION
**Pull request by nickvigilante**
Fixes DOC-1055

Added info about the cluster setting that controls uniqueness checks on gen_random_uuid()

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickvigilante)

___
*[_includes/v21.1/sql/regional-by-row-table-description.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuC65fy89UJ5gQjmxfQ:-MuC65fy89UJ5gQjmxfR:bwqi332) ([raw file](https://github.com/cockroachdb/docs/blob/f290c40ee0060f4caf38403c4e0db2326871b7f6/_includes/v21.1/sql/regional-by-row-table-description.md#L11)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> When using `DEFAULT gen_random_uuid()` on columns in `REGIONAL BY ROW` tables, uniqueness checks on those columns are disabled by default for performance purposes. CockroachDB assumes uniqueness based on the way this column generates [`UUIDs`](uuid.html#create-a-table-with-auto-generated-unique-row-ids). To enable this check, you can modify the `sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled` [cluster setting](cluster-settings.html). Note that while there is virtually no chance of a [collision](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions) from occurring when enabling this setting, it is not truly zero.
> {{site.data.alerts.end}}
> ```

Seems a bit weird to include this info here, since there's no info about the uniqueness checks anywhere else on the page. Should this be moved to where the uniqueness checks are described, or at least include a link there?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12799#-:-MuCRwsS6qJrz7MDe7M_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nickvigilante)

**Comment by nickvigilante** [comment]
@rytaft TFTR!

**Review by lnhsingh — COMMENTED** [review]
A nit but otherwise LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12799#-:-MuDW0MvAvN_HN3E8xqx:b-q195bq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @nickvigilante)

___
*[v21.2/add-constraint.md, line 320 at r2](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuDUen_2BNyKqPM1jIa:-MuDUen_2BNyKqPM1jIb:b-5fs5q5) ([raw file](https://github.com/cockroachdb/docs/blob/f331f40135d0e9b324644686641a52a789d15e38/v21.2/add-constraint.md#L320)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ sql
> > INSERT INTO users (name, city) VALUES ('Petee', 'new york'), ('Eric', 'seattle'), ('Dan', 'seattle');
> ```

It's nice to see that me addition of my dog's name into examples still exists in our current docs :)
___
*[v21.2/add-constraint.md, line 338 at r2](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuDV_O69jXzebT7bI9X:-MuDV_O69jXzebT7bI9Y:b-ue3vvh) ([raw file](https://github.com/cockroachdb/docs/blob/f331f40135d0e9b324644686641a52a789d15e38/v21.2/add-constraint.md#L338)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> When using `DEFAULT gen_random_uuid()` on columns in `REGIONAL BY ROW` tables, uniqueness checks on those columns are disabled by default for performance purposes. CockroachDB assumes uniqueness based on the way this column generates [`UUIDs`](uuid.html#create-a-table-with-auto-generated-unique-row-ids). To enable this check, you can modify the `sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled` [cluster setting](cluster-settings.html). Note that while there is virtually no chance of a [collision](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions) from occurring when enabling this setting, it is not truly zero.
> ```

"[...] from occurring [...]"  should be just "occurring"



_Code quote:_
```Markdown
from occurring
```

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12799)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @nickvigilante)

___
*[v21.1/add-constraint.md, line 338 at r2](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuDWfAz0TXNouPUwLgg:-MuDWfAz0TXNouPUwLgh:buo7pq7) ([raw file](https://github.com/cockroachdb/docs/blob/f331f40135d0e9b324644686641a52a789d15e38/v21.1/add-constraint.md#L338)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> When using `DEFAULT gen_random_uuid()` on columns in `REGIONAL BY ROW` tables, uniqueness checks on those columns are disabled by default for performance purposes. CockroachDB assumes uniqueness based on the way this column generates [`UUIDs`](uuid.html#create-a-table-with-auto-generated-unique-row-ids). To enable this check, you can modify the `sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled` [cluster setting](cluster-settings.html). Note that while there is virtually no chance of a [collision](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions) from occurring when enabling this setting, it is not truly zero.
> ```

Same edit

**Review by nickvigilante — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12799#-:-MuIXN-gBqlEIG_2H7rT:bb6un1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh and @rytaft)

___
*[v21.1/add-constraint.md, line 338 at r2](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuDWfAz0TXNouPUwLgg:-MuIXPodCLU2vxxkBxCj:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/f331f40135d0e9b324644686641a52a789d15e38/v21.1/add-constraint.md#L338)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Same edit
</blockquote></details>

Done
___
*[v21.2/add-constraint.md, line 320 at r2](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuDUen_2BNyKqPM1jIa:-MuIXQTtE7-uQMLIn1XO:byrli1e) ([raw file](https://github.com/cockroachdb/docs/blob/f331f40135d0e9b324644686641a52a789d15e38/v21.2/add-constraint.md#L320)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

It's nice to see that me addition of my dog's name into examples still exists in our current docs :)
</blockquote></details>

Agreed :)
___
*[v21.2/add-constraint.md, line 338 at r2](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuDV_O69jXzebT7bI9X:-MuIXS9iBdWWoViQgPba:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/f331f40135d0e9b324644686641a52a789d15e38/v21.2/add-constraint.md#L338)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

"[...] from occurring [...]"  should be just "occurring"
</blockquote></details>

Done
___
*[_includes/v21.1/sql/regional-by-row-table-description.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/docs/12799#-MuC65fy89UJ5gQjmxfQ:-MuIXTZW-vGg9ICDpe4K:bb6un1j) ([raw file](https://github.com/cockroachdb/docs/blob/f290c40ee0060f4caf38403c4e0db2326871b7f6/_includes/v21.1/sql/regional-by-row-table-description.md#L11)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems a bit weird to include this info here, since there's no info about the uniqueness checks anywhere else on the page. Should this be moved to where the uniqueness checks are described, or at least include a link there?
</blockquote></details>

Done

**Pull request merged**
