### PR TITLE
Update header and footer to match hugo site

### PR DESCRIPTION
**Pull request by deronjohnson**
@jseldess We've made quite a few changes that the Docs site never received. Let me know if anything looks strange or buggy.

### CODE REVIEW

**Comment by jseldess** [comment]
@deronjohnson, I'll look more in-depth later today. The topnav looks good, but at first glance, there's a slight discrepancy in the padding/styling of the footer.

Live non-docs footer:
screen shot 2017-10-13 at 6 09 36 am

Docs footer from this PR:
screen shot 2017-10-13 at 6 12 10 am

**Comment by deronjohnson** [comment]
@jseldess The footer should match now. There are some global style rules here that differ from the hugo site, which makes it hard to catch everything.

**Comment by jseldess** [comment]
Thanks, @deronjohnson. A few other minor tweaks needed:

- The footer section on docs starts a little further up the page than on the new site.
- In the topnav, the cockroachdb logo differs a little in color and proportion.

**Comment by jseldess** [comment]
Also, in the mobile topnav menu, the vertical spacing differs a bit.

Same for the mobile footer.

**Comment by deronjohnson** [comment]
@jseldess, sorry for the delay. I'll push updates this morning.

**Comment by deronjohnson** [comment]
@jseldess, I've pushed some changes, but it looks like GitHub is having a backlog issue (https://status.github.com/messages), so they might take a little bit to appear. 

There's a PR on the hugo site that's about to go live, so I made the latest round of updates with that in mind. You can compare here: http://cockroach-website-review.s3-website-us-east-1.amazonaws.com/eb7c09722f86b283c1e85db069d79e2d51364995/

**Comment by jseldess** [comment]
Thanks, @deronjohnson. LGTM.

**Pull request merged**
