### PR TITLE
Add docs for optimizer join hints

### LINKED ISSUE #2012: [MH] Query optimizer hints/ extensible optimizer hinting syntax
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rechsShAEmvPVOzD4
PM: @awoods187 
Eng Partner: @knz

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #2012.

Summary of changes:

- Added a section to the CBO page, 'Join hints', which describes:

  - Join hint syntax

  - Supported join algorithms, and how they work

### CODE REVIEW

**Comment by rmloveland** [comment]
Direct link to new section is [here](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/622ef2b3ba83281722f49e3abc18f04c10eba6ae/v19.1/cost-based-optimizer.html#join-hints).

**Comment by rmloveland** [comment]
Direct link to latest doc is [here](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e8e5136291bd813957a26aa75acf85e9d5738a49/dev/cost-based-optimizer.html#join-hints)

**Comment by rmloveland** [comment]
Update: added some links to the Join hint docs from the [Join expressions page](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/9316036bd14ab68e4c90ff3381417ca25bc76b57/dev/joins.html) as well.

**Comment by RaduBerinde** [comment]
Could you put the link at the end of the "Performance best practices" section rather than at the top?

**Comment by RaduBerinde** [comment]
A heads up that we decided to add hints for CROSS JOIN as well, e.g. `CROSS MERGE JOIN` (https://github.com/cockroachdb/cockroach/issues/35695).

**Comment by rmloveland** [comment]
> A heads up that we decided to add hints for CROSS JOIN as well

Thanks @RaduBerinde I opened #4502  to add that ASAP once that work goes in.

**Comment by jseldess** [comment]
@rmloveland, I'm going to merge this so we can point to it from release notes. You can handle the remaining nits in a follow-up PR.

**Pull request merged**
