### PR TITLE
Updated sqlalchemy-basic-sample.py to fix code smell and a few other syntax issues

### PR DESCRIPTION
**Pull request by zuliatowoade**
updated _includes/v20.1/app/sqlalchemy-basic-sample.py and _includes/v20.2/app/sqlalchemy-basic-sample.py

updates include:
1. Include code smell fix that was fixed in Commit 17fc080
2. Added docstrings
3. updated variable names and other syntax as suggested by pylon

### CODE REVIEW

**Comment by zuliatowoade** [comment]
@jseldess Mentioning you here because the contribution doc specified that all pull requests be assigned to you.

**Comment by jseldess** [comment]
Thanks, @zuliatowoade. I've assigned @ericharmeling as the reviewer.

**Review by ericharmeling — APPROVED** [review]
LGTM

@zuliatowoade 
Thanks for the contribution! Does this resolve a particular docs issue that we have open in our repo, or is this just a general improvement?

**Comment by ericharmeling** [comment]
Propagated these changes to https://github.com/cockroachlabs/hello-world-python-sqlalchemy in https://github.com/cockroachlabs/hello-world-python-sqlalchemy/commit/d89b8dc7bf63ada29371c8707453f9c8c0208133.

**Pull request merged**
