### PR TITLE
DOC-3223 add marked-for-compaction-files metric

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-3223

- Added new `storage.marked-for-compaction-files` metric to `metric-names.md`.

Note:

- Assuming this is not avail for Serverless given nature of metric. Pls correct if not the case (as I would need to also add to `metric-names-serverless.md`)

Staging:

[metric-names.md](url)

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:  although while reviewing, I noticed these metrics:

> compactor.compactingnanos	Number of nanoseconds spent compacting ranges
> compactor.compactions.failure	Number of failed compaction requests sent to the storage engine
> compactor.compactions.success	Number of successful compaction requests sent to the storage engine
> compactor.suggestionbytes.compacted	Number of logical bytes compacted from suggested compactions
> compactor.suggestionbytes.queued	Number of logical bytes in suggested compactions in the queue
> compactor.suggestionbytes.skipped	Number of logical bytes in suggested compactions which were not compacted

all of these are obsolete metrics no longer published by Cockroach (for quite some time; I think as far back as 21.1)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15430#-:-NEr2gtzCiGraD0R_bij:b-orrzc)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andf-crl** [comment]
> :lgtm: although while reviewing, I noticed these metrics:
> 
> > compactor.compactingnanos	Number of nanoseconds spent compacting ranges
> > compactor.compactions.failure	Number of failed compaction requests sent to the storage engine
> > compactor.compactions.success	Number of successful compaction requests sent to the storage engine
> > compactor.suggestionbytes.compacted	Number of logical bytes compacted from suggested compactions
> > compactor.suggestionbytes.queued	Number of logical bytes in suggested compactions in the queue
> > compactor.suggestionbytes.skipped	Number of logical bytes in suggested compactions which were not compacted
> 
> all of these are obsolete metrics no longer published by Cockroach (for quite some time; I think as far back as 21.1)
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15430#-:-NEr2gtzCiGraD0R_bij:b-orrzc)_ status: :shipit: complete! 1 of 0 LGTMs obtained

Thanks! Docs will be re-architecting this monolithic table shortly after v22.2 GA to build from the live `cockroach chartcatalog` report, which will cover this then. Thanks for this head's up though!

**Review by MichaelTrestman — APPROVED** [review]
LGTM

**Comment by andf-crl** [comment]
TYFR!

**Pull request merged**
