### PR TITLE
Syntax highlighting colors

### PR DESCRIPTION
**Pull request by j-low**
__[description]:__
* Re: Issue #2114
* Update syntax highlighting font to use `SourceCodePro-Regular`
* Update syntax highlighting colors

### CODE REVIEW

**Comment by j-low** [comment]
@kuanluo @jseldess PTAL

**Comment by kuanluo** [comment]
Hi @j-low, I'm ready to review this, but the link above no longer works. :/ Sorry for taking so long - would you mind resending? Thank you!

**Comment by jseldess** [comment]
@kuanluo, I just reran TeamCity, which will create a new test build for us. Link should be posted shortly. I'll review then as well.

**Comment by jseldess** [comment]
LGTM overall. Thanks, @j-low! 

The font is a clear improvement. The colors look softer now, which I think is fine if that's what you and @kuanluo prefer. The only other change I can detect is that comments are now grey instead of blueish. Again, looks fine to me, if that's what we want. If there's otherwise anything specific to check, please let me know.

**Comment by kuanluo** [comment]
Looks awesome, @j-low! Thank you. 

One question for @jseldess and you - We use the navy blue as one of the main colors for the syntax and it's frequently paired with black. Example: 
image

I wonder if using a more distinguishable color, such as the light blue, would be better? Example:
image

**Comment by jseldess** [comment]
Yes, I agree with @kuanluo that a bit more contrast in such cases would be great.

**Comment by kuanluo** [comment]
Awesome, thanks @jseldess to validate my assumption. @j-low, can we use the light blue instead in the case?

**Comment by jseldess** [comment]
@j-low, that color change looks good, but I just realized that `code` formatted text that's also a link no longer gets the green link coloring. See `INSERT` here for an example: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/30746693c48db86bc872e37f589e7be3bcc29ff3/stable/learn-cockroachdb-sql.html#insert-rows-into-a-table

**Comment by jseldess** [comment]
@j-low, the link color for code-formatted text is different than the link color for regular text. That feels confusing to me. Was that intentional?

**Comment by kuanluo** [comment]
LGTM, @j-low!

**Pull request merged**
