### PR TITLE
Columns referenced by FK do not need to be indexed

### PR DESCRIPTION
**Pull request by ericharmeling**
Background: https://github.com/cockroachdb/cockroach/pull/50771#issuecomment-849701585

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM from me, but I'm not the expert. Please involve someone from the schema team.

**Review by ajwerner — COMMENTED** [review]
I think updating the docs here for correctness is great but I also think this is a place where we could help some people avoid some pain. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10681#-:-Mb8N-QbBrLdbZCoVMvh:b-8to8if)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @ianjevans)

___
*[v20.2/foreign-key.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/10681#-Mb8Mk3O33vkkiwT6zvB:-Mb8Mk3O33vkkiwT6zvC:b-1qclx3) ([raw file](https://github.com/cockroachdb/docs/blob/54f73a85807ac69167d065f831a73651ba8bd45c/v20.2/foreign-key.md#L40)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - Referenced columns must be [indexed](indexes.html). There are a number of ways to meet this requirement:
>     - You can create indexes explicitly using the [`INDEX`](create-table.html#create-a-table-with-secondary-and-inverted-indexes) clause of `CREATE TABLE`.
>     - You can rely on indexes created by the [`PRIMARY KEY`](primary-key.html) or [`UNIQUE`](unique.html) constraints.
>     - If an index on the referenced column does not already exist, CockroachDB automatically creates one. It's important to note that if you later remove the `FOREIGN KEY` constraint, this automatically created index _is not_ removed.
> ```
</details>

Do we want to change this to state that it's a good idea (and, of course, remove the last line)?
___
*[v20.2/foreign-key.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/10681#-Mb8MwSw1WOJ83KwN9bb:-Mb8MwSw1WOJ83KwN9bc:bw5lezu) ([raw file](https://github.com/cockroachdb/docs/blob/54f73a85807ac69167d065f831a73651ba8bd45c/v20.2/foreign-key.md#L161)):*
> ```Markdown
>     customer INT NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
>     orderTotal DECIMAL(9,2),
>     INDEX (customer)
> ```

This index may not be required but it is a good idea...

**Review by ericharmeling — COMMENTED** [review]
TFTR @ajwerner !

Made some updates following your feedback. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10681#-:-Mb8XdIM9euu12bARQ7i:by53f4n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @ianjevans)

___
*[v20.2/foreign-key.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/10681#-Mb8Mk3O33vkkiwT6zvB:-Mb8Xk0U1pBG86TTK7tY:b-62ke96) ([raw file](https://github.com/cockroachdb/docs/blob/54f73a85807ac69167d065f831a73651ba8bd45c/v20.2/foreign-key.md#L40)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> - Referenced columns must be [indexed](indexes.html). There are a number of ways to meet this requirement:
>     - You can create indexes explicitly using the [`INDEX`](create-table.html#create-a-table-with-secondary-and-inverted-indexes) clause of `CREATE TABLE`.
>     - You can rely on indexes created by the [`PRIMARY KEY`](primary-key.html) or [`UNIQUE`](unique.html) constraints.
>     - If an index on the referenced column does not already exist, CockroachDB automatically creates one. It's important to note that if you later remove the `FOREIGN KEY` constraint, this automatically created index _is not_ removed.
> ```
Do we want to change this to state that it's a good idea (and, of course, remove the last line)?
</blockquote></details>

IIUC, all referenc**ed** columns will always be indexed, because of the `UNIQUE`/`PRIMARY` requirement stated above. So isn't information about indexing referenced columns kind of meaningless (unless it's a good idea to have referenced column(s) in two indexes?). I could be missing something though.

It's not guaranteed that referenc**ing** columns (i.e., "foreign key columns") are indexed. In my original doc changes (https://github.com/cockroachdb/docs/pull/8480), I removed [an equivalent index requirement](https://github.com/cockroachdb/docs/pull/8480/files#diff-b6122925623267ed9642c8fd4c06bb9bd9da6fdcd7b91024feb7117b3fb6d571L26) from the **Foreign Key Columns** rules list.

So maybe we should leave this be and just add a recommendation to index referencing foreign key columns to the ["Performance" section](https://www.cockroachlabs.com/docs/stable/foreign-key.html#performance) instead? I've made this change in the latest commit.
___
*[v20.2/foreign-key.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/10681#-Mb8MwSw1WOJ83KwN9bb:-Mb8XxyT2E0gDJzaoj_h:bge0ewx) ([raw file](https://github.com/cockroachdb/docs/blob/54f73a85807ac69167d065f831a73651ba8bd45c/v20.2/foreign-key.md#L161)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This index may not be required but it is a good idea...
</blockquote></details>

Added it back (and below)!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10681#-:-MbCJnPj1m0bclOAUrtb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans)

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
