### PR TITLE
Add TA 122372

### PR DESCRIPTION
**Pull request by kathancox**
Technical Advisory 122372

### CODE REVIEW

**Comment by kathancox** [comment]
@rytaft I also added notes to the v23.2 and v24.1 docs by the Kafka sink section to recommend users enable the cluster setting. I haven't yet added a note to the v24.2 docs, it looks as though users would have to enable the setting manually for test releases and v24.2.0?

**Review by rytaft — APPROVED** [review]
LGTM thank you!

**Comment by rytaft** [comment]
> I haven't yet added a note to the v24.2 docs, it looks as though users would have to enable the setting manually for test releases and v24.2.0?

That's correct

**Review by rharding6373 — APPROVED** [review]
Thank you!

**Review by rmloveland — APPROVED** [review]
LGTM as well

**Pull request merged**
