### PR TITLE
CC September release notes

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-3669

### CODE REVIEW

**Review by jramos-crl — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @kannanlakshmi, and @thtruo)

**Review by emily-horing — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kannanlakshmi and @thtruo)

**Review by kannanlakshmi — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11173#-:-MiNMMsRD5karos0YB9Z:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @thtruo)

**Review by thtruo — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by thtruo — APPROVED** [review]
lgtm!

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11173)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/cockroachcloud-09062021.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/11173#-Mj-h13C26zEwNUFKJI2:-Mj-h13C26zEwNUFKJI3:b-xow9a6) ([raw file](https://github.com/cockroachdb/docs/blob/0e2ff8eb0319d0d84bb7cc9b5040e1e64a1c4d27/releases/cockroachcloud-09062021.md#L7)):*
> ```
> September 6, 2021
> ```

Let's change this to today's date
___
*[releases/cockroachcloud-09062021.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/docs/11173#-Mj-hRwMAgh1FWh1mtpP:-Mj-hRwMAgh1FWh1mtpQ:baobbh4) ([raw file](https://github.com/cockroachdb/docs/blob/0e2ff8eb0319d0d84bb7cc9b5040e1e64a1c4d27/releases/cockroachcloud-09062021.md#L19)):*
> ```Markdown
> ### Console changes
> 
> - Pages shown to logged out users are now optimized for mobile devices.
> ```

All pages or specific ones? Should we clarify?

Also, not sure if this is pertinent, but why only logged out users?
___
*[releases/cockroachcloud-09062021.md, line 21 at r1](https://reviewable.io/reviews/cockroachdb/docs/11173#-Mj-hJHp5d5zOefTUoG5:-Mj-hJHp5d5zOefTUoG6:bht47rb) ([raw file](https://github.com/cockroachdb/docs/blob/0e2ff8eb0319d0d84bb7cc9b5040e1e64a1c4d27/releases/cockroachcloud-09062021.md#L21)):*
> ```Markdown
> - Pages shown to logged out users are now optimized for mobile devices.
>   
> - Improved error message when an [AWS PrivateLink](../cockroachcloud/network-authorization.html#aws-privatelink) endpoint request fails.
> ```

Change to "Improved the error message for when an AWS ..."
___
*[releases/cockroachcloud-09062021.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/11173#-Mj-hu32EXhYTFzukNNm:-Mj-hu32EXhYTFzukNNn:b-6b4xfj) ([raw file](https://github.com/cockroachdb/docs/blob/0e2ff8eb0319d0d84bb7cc9b5040e1e64a1c4d27/releases/cockroachcloud-09062021.md#L27)):*
> ```Markdown
> - Fixed tooltip behavior on **Sessions**, **Statements**, and **Transactions** pages.
> 
> - Fixed bug where clicking on the label of the [Terms of Service](https://www.cockroachlabs.com/cloud-terms-and-conditions/) checkbox would select the Terms of Service checkbox when signing up with GitHub.
> ```

Change to "Fixed a bug"

**Review by lnhsingh — COMMENTED** [review]
Edits LGTM, but we should change the CRDB version # to v21.1.7, per the discussion currently happening in slack

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11173#-:-Mj0PMUr3A5s4QzY4PP0:b-tpduc2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, @jramos-crl, and @thtruo)

**Pull request merged**
