### PR TITLE
enhance WITH FORECAST docs

### PR DESCRIPTION
**Pull request by taroface**
Relates to DOC-4740.

### CODE REVIEW

**Comment by taroface** [comment]
@michae2 It looks like Stephanie mostly handled (and you reviewed) this work in https://github.com/cockroachdb/docs/pull/15177. I added a few things to the reference doc.

**Review by michae2 — CHANGES_REQUESTED** [review]
Thanks for doing this!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15339#-:-NE803tV0O4kH7WDufY3:bxgavm9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[`v22.2/show-statistics.md` line 85 at r1](https://reviewable.io/reviews/cockroachdb/docs/15339#-NE7zed47LTaDr2aeEOV:-NE7zed5BYsh3aK9HG0x:b-9d3spr) ([raw file](https://github.com/cockroachdb/docs/blob/03cf0be2bdd70c6735ea91a2c7edba9cf0ba4721/v22.2/show-statistics.md#L85)):*
> ```Markdown
> - There have been at least 3 historical statistics collections.
> - The historical statistics closely fit a linear pattern.
> - The column's [data type](data-types.html) allows a rate of change to be determined between two values (for example, `DATE`, `TIME`/`TIMETZ`, `TIMESTAMP`/`TIMESTAMPTZ`, `INT`, `FLOAT`, and `DECIMAL`).
> ```

The column type only comes into consideration for the histogram part of the stats. We can still generate forecasts for columns of other types. So I would leave this part out for now.

**Comment by taroface** [comment]
@michae2 Got it; I removed the bullet!

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15339#-:-NECbfAsESds4k0h6TUn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

**Review by kathancox — APPROVED** [review]
LGTM sorry for the delay on this one!

**Pull request merged**
