### PR TITLE
Link to beta binaries

### PR DESCRIPTION
**Pull request by mberhault**
Set the links for the beta binaries.

I'll merge once they've been built and pushed, then we'll need to rebuild and push the docs.

A few other things that we should look into later:
* can we have a parameter somewhere and reuse it? that would be easier and less error-prone
* lots of trailing whitespaces in those files. we tend to avoid those.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/172)

### CODE REVIEW

**Comment by mberhault** [comment]
binaries are now available.

**Comment by jseldess** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[install-cockroachdb.md, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/172#-KE4YKavqAB9S2aVRvbZ:-KE4YKavqAB9S2aVRvb_:-1127016896) ([raw file](https://github.com/cockroachdb/docs/blob/ec7e0bcb356a8dabf37ac7d553909b4a45b76408/install-cockroachdb.md#L100)):*
Mark, can you change the filename here, too?

---

*[install-cockroachdb.md, line 264 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/172#-KE4YQgNPRcOAjP1PfUM:-KE4YQgNPRcOAjP1PfUN:1473363512) ([raw file](https://github.com/cockroachdb/docs/blob/ec7e0bcb356a8dabf37ac7d553909b4a45b76408/install-cockroachdb.md#L264)):*
Marc, can you change the filename here, too?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/172)*

**Comment by jseldess** [comment]
:lgtm: after few updates I mention.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/172#-:-KE4YWp0sgQYe6r4beJm:2072212940)*

**Comment by jseldess** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/172)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[install-cockroachdb.md, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/172#-KE4YKavqAB9S2aVRvbZ:-KE6g0hgQplqgmhrYeNx:-672841684) ([raw file](https://github.com/cockroachdb/docs/blob/ec7e0bcb356a8dabf37ac7d553909b4a45b76408/install-cockroachdb.md#L100)):*
oops. right.

---

*[install-cockroachdb.md, line 264 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/172#-KE4YQgNPRcOAjP1PfUM:-KE6g2Ax5RtW2grjDh8X:1432762559) ([raw file](https://github.com/cockroachdb/docs/blob/ec7e0bcb356a8dabf37ac7d553909b4a45b76408/install-cockroachdb.md#L264)):*
ditto. nice catch.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/172)*

**Comment by mberhault** [comment]
oh, another thing. When do we want to start mentioning the version number in the actual text? eg: instead of "download the latest ...", maybe "download version beta-..."

**Comment by jseldess** [comment]
As discussed in person: For now, we'll just reference the "latest version", but once we're able to point to a list of previous versions, we'll work that into the docs.

**Pull request merged**
