### PR TITLE
DOC-30: Update AWS instance type recommendations

### PR DESCRIPTION
**Pull request by jseldess**
Changing our instance type recs from c5 to m5 based
on what Cloud uses and internal consensus.

### CODE REVIEW

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @jseldess)

___
*[v21.2/deploy-cockroachdb-on-aws.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDvy1yE632MN0T1K6l:-MpDvy1yE632MN0T1K6m:bz0asp9) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/deploy-cockroachdb-on-aws.md#L72)):*
> ```
> Use `m` (general purpose), `c` (compute-optimized), or `i` (storage-optimized) instance types
> ```

Should we amend this to use the same line from the Prod Checklist ("Use `m5` instances with EBS as a primary AWS configuration. To simulate bare-metal deployments, use `m5d` with [SSD Instance Store volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html).")? I'm not sure the example of our internal testing conveys a clear recommendation for `m` machines.
___
*[v21.2/deploy-cockroachdb-on-aws-insecure.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDw9C3DiD12w0i9D6t:-MpDw9C46K1KFkQJ7ErG:b-cnl81w) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/deploy-cockroachdb-on-aws-insecure.md#L40)):*
> ```
> - Use `m` (general purpose), `c` (compute-optimized), or `i` (storage-optimized) instance types
> ```

Ditto
___
*[v21.2/recommended-production-settings.md, line 131 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDwJwa1wnd6nE-Z0zr:-MpDwJwa1wnd6nE-Z0zs:bxfhn7a) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/recommended-production-settings.md#L131)):*
> ```
> Use `m` (general purpose) or `c` (compute-optimized) [instances](https://aws.amazon.com/ec2/instance-types/).
> ```

Ditto

**Review by jseldess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @taroface)

___
*[v21.2/deploy-cockroachdb-on-aws.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDvy1yE632MN0T1K6l:-MpEUI4--x_la2St3-0a:b-r0wp39) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/deploy-cockroachdb-on-aws.md#L72)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Use `m` (general purpose), `c` (compute-optimized), or `i` (storage-optimized) instance types
> ```

Should we amend this to use the same line from the Prod Checklist ("Use `m5` instances with EBS as a primary AWS configuration. To simulate bare-metal deployments, use `m5d` with [SSD Instance Store volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html).")? I'm not sure the example of our internal testing conveys a clear recommendation for `m` machines.
</blockquote></details>

Good idea. Done. 
___
*[v21.2/deploy-cockroachdb-on-aws-insecure.md, line 40 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDw9C3DiD12w0i9D6t:-MpEUJQvDVsjvgf4u4di:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/deploy-cockroachdb-on-aws-insecure.md#L40)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> - Use `m` (general purpose), `c` (compute-optimized), or `i` (storage-optimized) instance types
> ```

Ditto
</blockquote></details>

Done.
___
*[v21.2/recommended-production-settings.md, line 131 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDwJwa1wnd6nE-Z0zr:-MpEUliQC_35fA9yFSVy:bsooazk) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/recommended-production-settings.md#L131)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

> ```
> Use `m` (general purpose) or `c` (compute-optimized) [instances](https://aws.amazon.com/ec2/instance-types/).
> ```

Ditto
</blockquote></details>

Done. Please check this one in particular to make sure things make sense. I had to move the note about "burstable" instances.

**Review by taroface — CHANGES_REQUESTED** [review]
Just a request to move the burstable instances note that you mentioned.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12445#-:-MpJ1Q_K21cfl9zY27gf:bjc9vld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @jseldess, and @taroface)

___
*[v21.2/recommended-production-settings.md, line 136 at r2](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpJ1Fi46SZE9hWFdNpc:-MpJ1Fi46SZE9hWFdNpd:b-m9spg7) ([raw file](https://github.com/cockroachdb/docs/blob/50c3e222ef42bba54bcf4256e564bc1bad2831ca/v21.2/recommended-production-settings.md#L136)):*
> ```
> Do not use ["burstable" `t` instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances.html), which limit the load on CPU resources.
> ```

I think this note should go directly under the `m5` instances note, as both are about instance types. Currently it's under the recommendation for volume type.

**Review by bdarnell — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess and @taroface)

___
*[v21.2/deploy-cockroachdb-on-aws.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDvy1yE632MN0T1K6l:-Mpgz5gyAIDZEcpslDBj:bqs45f6) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/deploy-cockroachdb-on-aws.md#L72)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Good idea. Done. 
</blockquote></details>

The old language also gave a specific size (4xlarge) as an example, which is now gone. Do we want to give an example or size range here? Consistency with our other recommendations would I think be a range of `m5.xlarge` to `m5.8xlarge`.

Not all `m`-series instances are OK - we don't support the arm-based `m6g` instances. I think we should be explicit about this: we recommend m5, we do not support m6g, and other `m`-series instances (m5a, m6i, m6a) are acceptable (after this year's cloud report I expect one of m6a or m6i to become our new recommendation). 
___
*[v21.2/deploy-cockroachdb-on-aws.md, line 74 at r2](https://reviewable.io/reviews/cockroachdb/docs/12445#-Mph1PsJBioaVf2OOupG:-Mph1PsJBioaVf2OOupH:bxr82yu) ([raw file](https://github.com/cockroachdb/docs/blob/50c3e222ef42bba54bcf4256e564bc1bad2831ca/v21.2/deploy-cockroachdb-on-aws.md#L74)):*
> ```Markdown
> - Use `m5` instances with EBS as a primary AWS configuration. To simulate bare-metal deployments, use `m5d` with [SSD Instance Store volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html).
> 
>   - **Do not** use ["burstable" `t2` instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html), which limit the load on a single core.
> ```

This is a bit outdated - there have been several more generations of "burstable" instances (t4g, t3, t3a). None of the `t`-series instances are supported. 
___
*[v21.2/recommended-production-settings.md, line 133 at r2](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpgzUab3N-52IcWmI-G:-MpgzUab3N-52IcWmI-H:bd90ihd) ([raw file](https://github.com/cockroachdb/docs/blob/50c3e222ef42bba54bcf4256e564bc1bad2831ca/v21.2/recommended-production-settings.md#L133)):*
> ```Markdown
> - Use `m5` instances with EBS as a primary AWS configuration. To simulate bare-metal deployments, use `m5d` with [SSD Instance Store volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ssd-instance-store.html).
> 
>     [Provisioned IOPS SSD-backed (`io1`) EBS volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html#EBSVolumeTypes_piops) need to have IOPS provisioned, which can be very expensive. Cheaper `gp2` volumes can be used instead, if your performance needs are less demanding. Allocating more disk space than you will use can improve performance of `gp2` volumes.
> ```

I think it's tracked in a separate issue, but the EBS recommendations are also due for an update.

**Comment by jseldess** [comment]
___
*[v21.2/deploy-cockroachdb-on-aws.md, line 74 at r2](https://reviewable.io/reviews/cockroachdb/docs/12445#-Mph1PsJBioaVf2OOupG:-MwgYxvs9Y3__lBIll77:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/50c3e222ef42bba54bcf4256e564bc1bad2831ca/v21.2/deploy-cockroachdb-on-aws.md#L74)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is a bit outdated - there have been several more generations of "burstable" instances (t4g, t3, t3a). None of the `t`-series instances are supported. 
</blockquote></details>

Done.

**Comment by jseldess** [comment]
___
*[v21.2/deploy-cockroachdb-on-aws.md, line 72 at r1](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpDvy1yE632MN0T1K6l:-Mwg_l6Q03vSU605L0qc:bfk8ctq) ([raw file](https://github.com/cockroachdb/docs/blob/295aaea7150c5162d50bd009016ebd18d47633a9/v21.2/deploy-cockroachdb-on-aws.md#L72)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The old language also gave a specific size (4xlarge) as an example, which is now gone. Do we want to give an example or size range here? Consistency with our other recommendations would I think be a range of `m5.xlarge` to `m5.8xlarge`.

Not all `m`-series instances are OK - we don't support the arm-based `m6g` instances. I think we should be explicit about this: we recommend m5, we do not support m6g, and other `m`-series instances (m5a, m6i, m6a) are acceptable (after this year's cloud report I expect one of m6a or m6i to become our new recommendation). 
</blockquote></details>

Ryan, can you help here?



_Code quote:_
```Markdown
For example, Cockroach Labs has used `c5d.4xlarge` (16 vCPUs and 32 GiB of RAM per instance, EBS) for internal testing.
```

**Comment by jseldess** [comment]
___
*[v21.2/recommended-production-settings.md, line 133 at r2](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpgzUab3N-52IcWmI-G:-Mwg_oYg6ZCjcxJJs1U4:bu7i9fa) ([raw file](https://github.com/cockroachdb/docs/blob/50c3e222ef42bba54bcf4256e564bc1bad2831ca/v21.2/recommended-production-settings.md#L133)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think it's tracked in a separate issue, but the EBS recommendations are also due for an update. 
</blockquote></details>

Ryan, can you check on this?

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @taroface)

___
*[v21.2/recommended-production-settings.md, line 133 at r2](https://reviewable.io/reviews/cockroachdb/docs/12445#-MpgzUab3N-52IcWmI-G:-Mx1V9tp23qoMEnaHxIB:bc8x4u1) ([raw file](https://github.com/cockroachdb/docs/blob/50c3e222ef42bba54bcf4256e564bc1bad2831ca/v21.2/recommended-production-settings.md#L133)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Ryan, can you check on this?
</blockquote></details>

Updated `gp2` to `gp3` and `io1` to `io2`. Also shifting emphasis to recommend `gp3` first, as this is used for CC.

**Comment by jseldess** [comment]
Thank you, @taroface!

**Pull request merged**
