### PR TITLE
SSL security risks section

### LINKED ISSUE #9336: Add security risk section to CockroachCloud connection docs
image
In the CockroachCloud connection modal, we specifically call out the security risks of setting `ssl-mode=require` and link to our docs to learn more. The link, however, is only to the [generic connection modal docs](https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster.html). Instead we should add a section that explains the risks of different `ssl-mode` settings and link directly to that. For an example of existing docs, [postgres has a great table](https://www.postgresql.org/docs/current/libpq-ssl.html) that we may be able to reuse:

image

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes #9336

Added a security risks section with descriptions for `require` and `verify-full`.

### CODE REVIEW

**Review by lnhsingh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/connect-to-your-cluster.md, line 189 at r2](https://reviewable.io/reviews/cockroachdb/docs/9795#-MTI18Kq33MBgFgMfIqZ:-MTI18Kq33MBgFgMfIq_:b-6wxdyd) ([raw file](https://github.com/cockroachdb/docs/blob/05bc18c0d1b5a12d7f4a613ff3cc38ee66d3dae3/cockroachcloud/connect-to-your-cluster.md#L189)):*
> ```Markdown
> </section>
> 
> ## Security risks for SSL Mode settings
> ```

I'd suggest moving this section to `authentication.md`, as that doc already discusses SSL mode (and then update the cross-reference link above). You may need to edit the Auth doc to point to this new section instead of to Postgres docs (where it makes sense)

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 189 at r2](https://reviewable.io/reviews/cockroachdb/docs/9795#-MTI18Kq33MBgFgMfIqZ:-MTIGoAD4IzNOcjXIGGj:b1edql9) ([raw file](https://github.com/cockroachdb/docs/blob/05bc18c0d1b5a12d7f4a613ff3cc38ee66d3dae3/cockroachcloud/connect-to-your-cluster.md#L189)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I'd suggest moving this section to `authentication.md`, as that doc already discusses SSL mode (and then update the cross-reference link above). You may need to edit the Auth doc to point to this new section instead of to Postgres docs (where it makes sense)
</blockquote></details>

perfect! didn't really like it on the connect page.

**Review by lnhsingh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/authentication.md, line 28 at r3](https://reviewable.io/reviews/cockroachdb/docs/9795#-MTbwMdw6S9MyexH5VxJ:-MTbwMdw6S9MyexH5VxK:b5ykdg1) ([raw file](https://github.com/cockroachdb/docs/blob/089264c417335369c69c210f97227c7a45fa5299/cockroachcloud/authentication.md#L28)):*
> ```Markdown
> For more information about creating SQL users and passwords, see [User Authorization](user-authorization.html).
> 
> ## SSL Mode settings
> ```

nit: I think "Mode" should be "mode"
___
*[cockroachcloud/connect-to-your-cluster.md, line 106 at r3](https://reviewable.io/reviews/cockroachdb/docs/9795#-MTbwlYf8uEOfuyv69E8:-MTbwlYf8uEOfuyv69E9:b-g1a20j) ([raw file](https://github.com/cockroachdb/docs/blob/089264c417335369c69c210f97227c7a45fa5299/cockroachcloud/connect-to-your-cluster.md#L106)):*
> ```Markdown
> To connect to your cluster with the [built-in SQL client](../v20.2/cockroach-sql.html):
> 
> 1. Click the name of the `<cluster_name>-ca.crt` to download the CA certificate to your local machine. Alternatively, you can set [`sslmode=require`](authentication.html#ssl-mode-settings).
> ```

I think this additional sentence should be on it's own line, nested under the step. It should also probably have a warning that  `sslmode=require` is less secure than using a CA cert

Also- is it `sslmode=` or `ssl-mode=`? Whatever it is, it should be consistent here and on the new content you added to the Auth page.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/authentication.md, line 28 at r3](https://reviewable.io/reviews/cockroachdb/docs/9795#-MTbwMdw6S9MyexH5VxJ:-MTfVvBz7uqF4mo9SD0K:b-c1tlet) ([raw file](https://github.com/cockroachdb/docs/blob/089264c417335369c69c210f97227c7a45fa5299/cockroachcloud/authentication.md#L28)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: I think "Mode" should be "mode"
</blockquote></details>

Done. Also changed the descriptions to be more consistent with this page: https://www.cockroachlabs.com/docs/stable/connection-parameters.html#secure-connections-with-urls.
___
*[cockroachcloud/connect-to-your-cluster.md, line 106 at r3](https://reviewable.io/reviews/cockroachdb/docs/9795#-MTbwlYf8uEOfuyv69E8:-MTfTvAc6fDX8Ncux3pZ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/089264c417335369c69c210f97227c7a45fa5299/cockroachcloud/connect-to-your-cluster.md#L106)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

I think this additional sentence should be on it's own line, nested under the step. It should also probably have a warning that  `sslmode=require` is less secure than using a CA cert

Also- is it `sslmode=` or `ssl-mode=`? Whatever it is, it should be consistent here and on the new content you added to the Auth page.
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795#-:-MTfcdPrD1LngT9O7Gug:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by piyush-singh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 108 at r4](https://reviewable.io/reviews/cockroachdb/docs/9795#-MThKgfM71z2O95jtF0q:-MThKgfM71z2O95jtF0r:b-j8sgf5) ([raw file](https://github.com/cockroachdb/docs/blob/58ee09222a4637a2f474d07feb3fe29298a2504b/cockroachcloud/connect-to-your-cluster.md#L108)):*
> ```Markdown
> 1. Click the name of the `<cluster_name>-ca.crt` to download the CA certificate to your local machine.
> 
>     Alternatively, you can set [`sslmode=require`](authentication.html#ssl-mode-settings).
> ```

I would definitely add a note that this is less secure than the option using the CA certificate (subject to MITM attacks) and that it should not be used with any sensitive data.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh and @piyush-singh)

___
*[cockroachcloud/connect-to-your-cluster.md, line 108 at r4](https://reviewable.io/reviews/cockroachdb/docs/9795#-MThKgfM71z2O95jtF0q:-MTkzKK7Ex_tinRvQ899:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/58ee09222a4637a2f474d07feb3fe29298a2504b/cockroachcloud/connect-to-your-cluster.md#L108)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

I would definitely add a note that this is less secure than the option using the CA certificate (subject to MITM attacks) and that it should not be used with any sensitive data.
</blockquote></details>

Done.

**Review by piyush-singh — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9795)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh and @piyush-singh)

**Pull request merged**
