### PR TITLE
February 2021 CC Release notes

### LINKED ISSUE #9518: CockroachCloud Release Notes: February 2021
For information about the CockroachCloud release note process, see the [Docs Internal Wiki](https://cockroachlabs.atlassian.net/wiki/x/fIAFUg).

### PR DESCRIPTION
**Pull request by lnhsingh**
Closes #9518.

### CODE REVIEW

**Comment by lnhsingh** [comment]
@kannanlakshmi am I missing anything? (cc @emily-horing @jramos-crl)

**Review by kannanlakshmi — APPROVED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9734)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by kannanlakshmi — COMMENTED** [review]
LGTM! thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9734#-:-MT2oDgQBZl9KhVyG6zW:b-t29ceo)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by lnhsingh** [comment]
TFTR!

@gemma-shay - do you mind doing the docs review for me since Rich is without a laptop?

**Review by emily-horing — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9734)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay, @kannanlakshmi, and @lnhsingh)

___
*[releases/cockroachcloud-02092021.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/9734#-MT30w_h7-u7WPLSFCeB:-MT30w_h7-u7WPLSFCeC:b-9gbnqi) ([raw file](https://github.com/cockroachdb/docs/blob/4b2b546a91aee5862024b7a6945739389db69c67/releases/cockroachcloud-02092021.md#L19)):*
> ```Markdown
> - [CockroachCloud Free](../cockroachcloud/free-faqs.html) is now in beta. CockroachCloud Free (beta) delivers free CockroachDB clusters for you and your organization. It is a managed instance of CockroachDB that removes the friction of initial cluster sizing and auto-scales based on your application traffic. There is an upper limit of usage of up to 1 vCPU and 5GB storage per free cluster.
> 
>     You can submit feedback or log any bugs you find through [this survey](https://cockroachlabs.typeform.com/to/gvCcF14q).
> ```

@lnhsingh we actually changed the survey link, we shouldn't use the typeform survey. Use this link instead: https://forms.gle/jWNgmCFtF4y15ePw5
___
*[releases/cockroachcloud-02092021.md, line 23 at r2](https://reviewable.io/reviews/cockroachdb/docs/9734#-MT31WDs1--a5SksshGi:-MT31WDs1--a5SksshGj:b-up3m89) ([raw file](https://github.com/cockroachdb/docs/blob/4b2b546a91aee5862024b7a6945739389db69c67/releases/cockroachcloud-02092021.md#L23)):*
> ```Markdown
> - You can now [restore databases and tables](../cockroachcloud/backups-page.html) from backups of CockroachCloud clusters. This feature is only available to clusters running the paid version of CockroachCloud.
> - [reCAPTCHA](https://www.google.com/recaptcha/about/) has been added to the sign up process for new users signing up with an email and password. Some users may need to complete an image challenge.
> - An email will now be sent to [Console Admins](../cockroachcloud/console-access-management.html#console-admin) when a [30-day free trial of CockroachCloud](../cockroachcloud/quickstart-trial-cluster.html) is nearing its end.
> ```

"nearing its end and once it has expired"
You get 2 emails :)

**Review by gemma-shay — APPROVED** [review]
LGTM! 
I think the **Latest** badge might be broken but I'll look into it.
Screen Shot 2021-02-09 at 10 33 54 AM

**Review by lnhsingh — COMMENTED** [review]
TFTRs! And thanks for the fix, Gemma

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9734#-:-MT6YPDk0rxfUdHCgLs2:b-ukx4dr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @kannanlakshmi)

___
*[releases/cockroachcloud-02092021.md, line 19 at r2](https://reviewable.io/reviews/cockroachdb/docs/9734#-MT30w_h7-u7WPLSFCeB:-MT6YGnK3xxODJllZM-h:brnship) ([raw file](https://github.com/cockroachdb/docs/blob/4b2b546a91aee5862024b7a6945739389db69c67/releases/cockroachcloud-02092021.md#L19)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

@lnhsingh we actually changed the survey link, we shouldn't use the typeform survey. Use this link instead: https://forms.gle/jWNgmCFtF4y15ePw5
</blockquote></details>

Updated link here and on the FAQs!
___
*[releases/cockroachcloud-02092021.md, line 23 at r2](https://reviewable.io/reviews/cockroachdb/docs/9734#-MT31WDs1--a5SksshGi:-MT6YOEY9oInR2Kuyycf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b2b546a91aee5862024b7a6945739389db69c67/releases/cockroachcloud-02092021.md#L23)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

"nearing its end and once it has expired"
You get 2 emails :)
</blockquote></details>

Done.

**Pull request merged**
