### PR TITLE
Clarify serverless workload costs

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/DOC-6141

### CODE REVIEW

**Review by rmloveland — CHANGES_REQUESTED** [review]
I would prefer an engineer or PM review on this before me.  It LGTM from a Docs POV but I'm not qualified to OK these technical content changes re: RUs.  Don't want to be the sole reviewer on this

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[`cockroachcloud/optimize-serverless-workload.md` line 28 at r1](https://reviewable.io/reviews/cockroachdb/docs/15588#-NGXhP1pBJHjSfMUw_sv:-NGXhP1pBJHjSfMUw_sw:b-2nx69d) ([raw file](https://github.com/cockroachdb/docs/blob/c9942e5754e99c8e4c3d7ae93ea81ab7ffa3c1a2/cockroachcloud/optimize-serverless-workload.md#L28)):*
> ```Markdown
>   - 1 RU = 8 storage read requests
>   - 1 RU = 64 KiB request payload (prorated)
>   - 1 RU = 2 storage read batches
> ```

I'd move this to the top of the list, so that reads are in the same order as writes.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15588#-:-NGXhcQK7R3Wf1v6joJU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay)

**Review by rmloveland — APPROVED** [review]
LGTM!

**Pull request merged**
