### PR TITLE
add builtin func's long-form info if present

### PR DESCRIPTION
**Pull request by dt**
currently only `replace(...)` has a its Info set, so that's the one to look at.

This also switches to wrapping the function signatures in `<code>` blocks, to distinguish them from the prose describing them, which required switching 'linkType' to return HTML.

HTMl `<code>` blocks, rather than backticks, are required to preserve the links.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/917)

### CODE REVIEW

**Comment by dt** [comment]
The lack of left-alignment from the extra 2px padding on the `<code>` elements looks kinda strange too -- we could make a `.funcdesc` class that gets a similar 2px of padding, restoring the left alignment and adding a little more separation?

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[generate/funcs.go, line 155 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/917#-KYbQOWhTESKoGdlJRBA:-KYbQOWhTESKoGdlJRBB:b-4gbzus) ([raw file](https://github.com/cockroachdb/docs/blob/556f90cf83fdaf960a4df4f815047eca7a4f0f12/generate/funcs.go#L155)):*
> ```Go
> 			extra := ""
> 			if fn.Info != "" {
> 				extra = fmt.Sprintf(" <br />%s", fn.Info)
> ```

I'm ok with using a br here, but it may be easier to style and deal with if it's in a <div class="fn-info"> or something instead. Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/917#-:-KYbQfSr-uTRe_qBxV3s:bnfp4nl)*

**Comment by jseldess** [comment]
Good idea, @dt. Go ahead and add that class and I can update the css in the follow-up PR.

**Comment by dt** [comment]
@jseldess Wrapped the descriptive text in a span and added a `desc` class, and added a hack to push `Compatibility` to bottom of the list.

After discussion with @sploiselle, I think I want to break up `_includes/sql/functions.md` to be one include per category, so we could added manually written copy between/above sections.

**Comment by jseldess** [comment]
@dt, sounds good. Are you doing that as a part of this PR or a follow-on?

**Comment by dt** [comment]
@jseldess let's punt the bigger restructuring (separate includes for each category) for now.

**Comment by dt** [comment]
@jseldess I added a TODO about breaking it up to the note about the hack to sort `Compatibility` last.

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[generate/funcs.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/917#-KYoMbxoC6abvYAJCpsW:-KYoMbxoC6abvYAJCpsX:b-4slxj1) ([raw file](https://github.com/cockroachdb/docs/blob/4d57769a464319f2b7ce8c708c1b31da9599ba37/generate/funcs.go#L155)):*
> ```Go
> 			extra := ""
> 			if fn.Info != "" {
> 				extra = fmt.Sprintf(" <br /> <span class=\"desc\">%s</span>", fn.Info)
> ```

Can we remove the <br> completely and use a CSS rule like `display: block` or something to force it onto a newline. Or maybe a <div> instead of a span? But same as last time: whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/917)*

**Comment by dt** [comment]
TFTR. I added the display:block and padding css and regenerated it. RFAL.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/917#-:-KYoXmXLxe5vHAQ0mQ5q:b-9viw14)*

**Pull request merged**
