### PR TITLE
Update when cockroach is not suitable

### PR DESCRIPTION
**Pull request by jseldess**
Also mark "cloud dbaas" as coming soon.

### CODE REVIEW

**Comment by jess-edwards** [comment]
Also refresh: `Can a PostgreSQL or MySQL application be migrated to CockroachDB?`
Recommend softening it to highlight new migration capabilities.

**Comment by rkruze** [comment]
:lgtm:

**Comment by jseldess** [comment]
___
*[v2.0/frequently-asked-questions.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/3882#-LP8BXKPBf6-x7SXm1bB:-LP8VJtS3Bd3D6dwTxdp:buzghup) ([raw file](https://github.com/cockroachdb/docs/blob/ffc71c762acde37d87186805384973975640c392/v2.0/frequently-asked-questions.md#L17)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

We expect CockroachDB to provide 2ms reads and 4ms writes for OLTP workloads.  
</blockquote></details>

@awoods187, happy to add this, but shouldn't we be specific that we're talking about single-key reads and writes? It could be very misleading otherwise.

**Comment by jseldess** [comment]
___
*[v2.0/frequently-asked-questions.md, line 17 at r1](https://reviewable.io/reviews/cockroachdb/docs/3882#-LP8BXKPBf6-x7SXm1bB:-LPbqGm_-uWLUrKyYCJg:bkwrl3k) ([raw file](https://github.com/cockroachdb/docs/blob/ffc71c762acde37d87186805384973975640c392/v2.0/frequently-asked-questions.md#L17)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Updated the language here. Please take another look.
</blockquote></details>

Robert signed off on the latest phrasing offline.

**Pull request merged**
