### PR TITLE
Asciicast of secure a cluster

### LINKED ISSUE #887: asciicast for secure a cluster

### PR DESCRIPTION
**Pull request by jseldess**
This PR adds an asciicast to `secure-a-cluster.md`.

Fixes #887

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/888)

### CODE REVIEW

**Comment by jseldess** [comment]
@sploiselle, I don't think any of this changes with your password auth PR, but let me know if I'm wrong.

**Comment by sploiselle** [comment]
The frame in which the text "plays" is too narrow and some of the commands are strangely truncated, e.g. the line:
```
$ cockroach cert create-client root --ca-cert=certs/ca.cert --ca-key=certs/ca.key --cert=certs/root.cert --key=certs/root.key    
```

If you blow the asciicast out to "full screen," you can see the text wrap happens at 950px, regardless of the dimension of the player on the page. Is there an option to enforce wrapping earlier? e.g. at our default width, which is 780x?

**Comment by jseldess** [comment]
Good catch, Sean. Rerecorded the asciicast with the terminal at the right width. Please check again.

**Comment by jseldess** [comment]
@sploiselle, please check once more. Think narrowing the terminal just a bit more did the trick.

**Comment by sploiselle** [comment]
Absolutely perfect.

**Comment by jseldess** [comment]
Great! I'll tweak the others similarly tomorrow.

**Pull request merged**
