### PR TITLE
Update `EXPLAIN` and `EXPLAIN ANALYZE` topics and output for 21.1

### LINKED ISSUE #9102: sql: single-column EXPLAIN output
PR: https://github.com/cockroachdb/cockroach/pull/55866

From release notes:
> Added a new single-column output format for `EXPLAIN` and `EXPLAIN (VERBOSE)`. [#55866][#55866] {% comment %}doc{% endcomment %}

### LINKED ISSUE #9112: sql: introduce EXPLAIN ANALYZE (PLAN)
PR: https://github.com/cockroachdb/cockroach/pull/56524

From release notes:
> Added a new variant of explain: `EXPLAIN ANALYZE (PLAN)`. [#56524][#56524] {% comment %}doc{% endcomment %}

### LINKED ISSUE #9154: release-20.1: sql: switch table and index in EXPLAIN (DISTSQL) diagrams
PR: https://github.com/cockroachdb/cockroach/pull/56396

From release notes:
> Table names are now listed before index names in [`EXPLAIN (DISTSQL)`](../v20.1/explain.html) diagram output. Previously, the diagrams used `index@table`, and now they use `table@index`. [#56396][#56396] {% comment %}doc{% endcomment %}

### LINKED ISSUE #9553: sql: decrease vectorize_row_count_threshold to 0
PR: https://github.com/cockroachdb/cockroach/pull/55713

From release notes:
> The default value for `vectorize_row_count_threshold` setting has been decreased from 1000 to 0, meaning that from now on CockroachDB will always use the [vectorized engine](../v21.1/vectorized-execution.html) for all supported queries regardless of the row estimate (unless `vectorize=off` is set). [#55713][#55713] {% comment %}doc{% endcomment %}

### LINKED ISSUE #9555: sql: humanize counts and durations in EXPLAIN ANALYZE
PR: https://github.com/cockroachdb/cockroach/pull/57420

From release notes:
> [`EXPLAIN`](../v21.1/explain.html) and [`EXPLAIN ANALYZE`](../v21.1/explain-analyze.html) now show counts and durations in a more user-friendly way. [#57420][#57420] {% comment %}doc{% endcomment %}

### LINKED ISSUE #9582: sql: reimplement EXPLAIN ANALYZE (DISTSQL)
PR: https://github.com/cockroachdb/cockroach/pull/57804

From release notes:
> New [`EXPLAIN ANALYZE (DISTSQL)`](../v21.1/explain-analyze.html) output format. [`EXPLAIN ANALYZE (DISTSQL)`](../v21.1/explain-analyze.html) now only works as a top-level statement (it can no longer be part of a bigger query). [#57804][#57804] {% comment %}doc{% endcomment %}

### LINKED ISSUE #10020: explain: Clarify meaning of distribution full vs local
It would be helpful to clarify the meaning `distribution` in explain plans. The possible values appear to be `full` and `local`.

On the page: https://www.cockroachlabs.com/docs/v20.2/explain#default-query-plans

It states:
> `distribution`:`full`
The query plan will be distributed across all nodes on a distributed cluster.

However, it does not explain what `local` means. And it is not clear what `distribution` is referring to.

Reference internal Slack: 
https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1616110866018700
and follow-on
https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1616110946019100

Summarizing the slack conversation.

**distribution: full**
Means that the planner chose a distributed execution plan, where execution of the query is performed by multiple nodes in parallel. Such as a distributed join or aggregation, where each node performs a portion of the work in parallel, and then final or downstream results are returned by the gateway node.

**distribution: local**
Means the planner chose a local execution plan, where execution of the query is performed only on the local node (aka gateway node). It is important to note that rows may be fetched by one or more remote nodes, but the processing of those rows is performed only by the local node.

Therefore "distribution" refers more to the style of processing of the records during query execution (e.g. distributed processing, or local processing), vs the fetching of the rows that will be processed by the query.

### distribution: local
```
root@127.0.0.1:59856/movr> explain 
select u.name, u.id
from users u
where u.city = 'Amsterdam' and u.id = 'b3333333-3333-4000-8000-000000000023';
  tree |        field        |                                                 description
-------+---------------------+--------------------------------------------------------------------------------------------------------------
       | distribution        | local
       | vectorized          | false
  scan |                     |
       | estimated row count | 1
       | table               | users@primary
       | spans               | [/'Amsterdam'/'b3333333-3333-4000-8000-000000000023' - /'Amsterdam'/'b3333333-3333-4000-8000-000000000023']
(6 rows)
```
image

Notice that all query processing occurs on node 1.

### distribution: full
```
root@127.0.0.1:59856/movr> explain 
select u.city, count(*) as num
from users u
where u.city = 'Amsterdam' group by u.city;
    tree    |        field        |          description
------------+---------------------+--------------------------------
            | distribution        | full
            | vectorized          | false
  group     |                     |
   └── scan |                     |
            | estimated row count | 0
            | table               | users@primary
            | spans               | [/'Amsterdam' - /'Amsterdam']
(7 rows)
```
image

Notice that query processing involves node 1 and node5.

Therefore it is important to note the `full` does not mean that processing happens on ALL nodes, but that it happens on multiple nodes simultaneously.

### LINKED ISSUE #10083: sql: add percentage to the estimated row count for scans
PR: https://github.com/cockroachdb/cockroach/pull/60467

From release notes:
> [`EXPLAIN`](../v21.1/explain.html) now shows the estimated percentage of the table that is scanned. [#60467][#60467] {% comment %}doc{% endcomment %}

### LINKED ISSUE #10096: sql: add query level stats to EXPLAIN ANALYZE
PR: https://github.com/cockroachdb/cockroach/pull/60641

From release notes:
> [`EXPLAIN ANALYZE`](../v21.1/explain-analyze.html) now shows more top-level query statistics. [#60641][#60641] {% comment %}doc{% endcomment %}

### LINKED ISSUE #10102: sql: add nodes for each EXPLAIN ANALYZE operator
PR: https://github.com/cockroachdb/cockroach/pull/60550

From release notes:
> [`EXPLAIN ANALYZE`](../v21.1/explain-analyze.html) now includes the nodes which were involved in the execution of each operator in the tree. [#60550][#60550] {% comment %}doc{% endcomment %}

### LINKED ISSUE #10127: sql: add estimated row count to all operators in EXPLAIN
PR: https://github.com/cockroachdb/cockroach/pull/61344

From release notes:
> [`EXPLAIN`](../v21.1/explain.html) now shows estimated row counts for all operators even without `VERBOSE` (except when we don't have statistics for the tables). [#61344][#61344] {% comment %}doc{% endcomment %}

### LINKED ISSUE #10262: release-21.1: sql: add EXPLAIN (VEC) output to the stmt bundle
PR: https://github.com/cockroachdb/cockroach/pull/62049

From release notes:
> Statement [diagnostics bundles](../v21.1/explain-analyze.html#debug-option) now contain output of `EXPLAIN (VEC)` and `EXPLAIN (VEC, VERBOSE)` commands for the statements. [#62049][#62049] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ianjevans**
Changes related to `EXPLAIN` and `EXPLAIN ANALYZE` refactoring in 21.1. Because these changes affected more than just the reference topics for `EXPLAIN` and `EXPLAIN ANALYZE` I addressed multiple issues in this PR.

Fixes #9102
Fixes #9112
Fixes #9154
Fixes #9553
Fixes #9555
Fixes #9582
Fixes #10020
Fixes #10083 
Fixes #10096
Fixes #10102
Fixes #10127
Fixes #10262

### CODE REVIEW

**Comment by ianjevans** [comment]
cc @Azhng if you want to check out the updated EXPLAIN/EXPLAIN ANALYZE content.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Looks great, thanks for doing all this work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10240#-:-MXclc5kBuNpJZD3WEif:bpzdebk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187, @ericharmeling, and @ianjevans)

___
*[v21.1/explain-analyze.md, line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXclR5iAxuNkNYifxQ1:-MXclR5iAxuNkNYifxQ2:bta14hx) ([raw file](https://github.com/cockroachdb/docs/blob/e8436758f2c144e24493b62e68d025fb4fc05801/v21.1/explain-analyze.md#L7)):*
> ```Markdown
> ---
> 
> The `EXPLAIN ANALYZE` [statement](sql-statements.html) **executes a SQL query** and generates a physical query plan with execution statistics, a URL for a physical query plan, or a URL to download a bundle with more details about the query plan. Query plans provide information around SQL execution, which can be used to troubleshoot slow queries by figuring out where time is being spent, how long a processor (i.e., a component that takes streams of input rows and processes them according to a specification) is not doing work, etc. For more information about distributed SQL queries, see the [DistSQL section of our SQL Layer Architecture docs](architecture/sql-layer.html#distsql).
> ```

I'd remove the first "physical" (generates a query plan with execution statistics). It's the same plan as in the regular EXPLAIN.
___
*[v21.1/explain-analyze.md, line 104 at r3](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXcl-WE9Ud2hPvss2ql:-MXcl-WE9Ud2hPvss2qm:bqiii37) ([raw file](https://github.com/cockroachdb/docs/blob/e8436758f2c144e24493b62e68d025fb4fc05801/v21.1/explain-analyze.md#L104)):*
> ```Markdown
> `distsql.html`      | The query's [physical query plan](#distsql-plan-viewer). This diagram is identical to the one generated by [`EXPLAIN(DISTSQL)`](explain.html#distsql-option)
> `plan.txt`          | The query execution plan. This is identical to the output of [`EXPLAIN (VERBOSE)`](explain.html#verbose-option).
> `opt-vv.txt`        | The query plan tree generated by the [cost-based optimizer](cost-based-optimizer.html), with cost details and input column data types. This is identical to the output of [`EXPLAIN (OPT, TYPES)`](explain.html#opt-option).
> ```

[nit] it's odd that they're not in the "opt.txt", "opt-v.txt", "opt-vv.txt" order

**Comment by ianjevans** [comment]
> I'd remove the first "physical" (generates a query plan with execution statistics). It's the same plan as in the regular EXPLAIN.

Done.

> [nit] it's odd that they're not in the "opt.txt", "opt-v.txt", "opt-vv.txt" order

Done.

**Review by awoods187 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10240)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @ianjevans)

___
*[v21.1/cost-based-optimizer.md, line 316 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgsbl59wWzgVbTCB91:-MXgsbl630WEjMQBm2c7:b-sjipy) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/cost-based-optimizer.md#L316)):*
> ```Markdown
> For example, if you have 11 nodes, you may see 11 queries with high latency due to schema cache misses.  Once all nodes have cached the schema locally, the latencies will drop.
> 
> This behavior may also cause the [Statements page of the Web UI](ui-statements-page.html) to show misleadingly high latencies until schemas are cached locally.
> ```

DB console
___
*[v21.1/cost-based-optimizer.md, line 333 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgskKc2PeVGlj7uz5n:-MXgskKc2PeVGlj7uz5o:b-j2wj1i) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/cost-based-optimizer.md#L333)):*
> ```Markdown
> 
>   • scan
>     missing stats
> ```

Is it intentional to not have collected stats here? Ideally we'd want people to see missing stats recognize that this is a problem and take action by running analyze 
___
*[v21.1/explain-analyze.md, line 7 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgsz9GAZ_p4s7dE8o4:-MXgsz9GAZ_p4s7dE8o5:b77vu33) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L7)):*
> ```Markdown
> ---
> 
> The `EXPLAIN ANALYZE` [statement](sql-statements.html) **executes a SQL query** and generates a query plan with execution statistics, a URL for a physical query plan, or a URL to download a bundle with more details about the query plan. Query plans provide information around SQL execution, which can be used to troubleshoot slow queries by figuring out where time is being spent, how long a processor (i.e., a component that takes streams of input rows and processes them according to a specification) is not doing work, etc. For more information about distributed SQL queries, see the [DistSQL section of our SQL Layer Architecture docs](architecture/sql-layer.html#distsql).
> ```

it also doesnt generate a URL anymore. I get that you can get that with distsql but i think we want to be minimizing this for users. I'd suggest something like "Explain Analyze generates a query plan with execution statistics." Explain Analyze (debug) generates a bundle with more details about the query plan for advanced debugging." And not mention distsql here. @raduberinde do you think there is value in even exposing distsql here at all? We constantly get feedback that all of the variations are confusing and it doesn't seem helpful to include it.
___
*[v21.1/explain-analyze.md, line 55 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXguE9g0AmyIEEWXirm:-MXguE9g0AmyIEEWXirn:b9k4tdd) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L55)):*
> ```Markdown
> Global property | Description
> ----------------|------------
> planning time | The total time the planner took to create a query plan.
> ```

should this be statement plan instead of query plan? You can use explain analyze with inserts
___
*[v21.1/explain-analyze.md, line 64 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXguVoZ8JmzOzWbScUh:-MXguVoZ8JmzOzWbScUi:b3fa2je) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L64)):*
> ```Markdown
> maximum memory usage | The maximum amount of memory used by this query anytime during its execution.
> network usage | The amount of data transferred over the network while the query was executed. If this value is 0 B, the statement was executed on a single node and didn't use the network.
> ```

Do stats collected need to go here?

**Review by ericharmeling — COMMENTED** [review]
Nice work! Loving the new EXPLAIN updates.

I had some nits/comments/suggestions. Please see my comments and take/leave as you wish.

> Reviewed 11 of 15 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10240#-:-MXgxi-V33pzXDKpoFvO:b2fs3dr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ianjevans)

___
*[v20.2/explain.md, line 119 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXglZ6dDCy-QN03d5oB:-MXglZ6dDCy-QN03d5oC:b-gi0tjg) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v20.2/explain.md#L119)):*
A couple nits here:

> ```
> A `full` execution plan doesn't mean that processing occurs on all nodes in the cluster
> ```

It might be better to say something like:

"An execution plan with `full` distribution doesn't process on all nodes..."

> ```
> The `local` execution plan
> ```

It might be better to say something like:

"An execution plan with `local` distribution, on the other hand, is performed only on the gateway node."
___
*[v20.2/make-queries-fast.md, line 398 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgnsNw8OhnY1rcVROf:-MXgnsNw8OhnY1rcVROg:b-83sjo4) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v20.2/make-queries-fast.md#L398)):*
> ```Markdown
> 
> The query is a little faster when we force CockroachDB to use a merge join:
> ```

Nice.
___
*[v21.1/explain.md, line 25 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgw0LY7VIwxoj-LueT:-MXgw0LY7VIwxoj-LueU:b-zfzke1) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain.md#L25)):*
> ```
> index join
> ```

We really need a formal definition for "index join". For now, I'd just link this to indexes.html.
___
*[v21.1/explain.md, line 68 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgwgK20VKmMHRXtyul:-MXgwgK20VKmMHRXtyum:by7fpy1) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain.md#L68)):*
nit:

> ```
> The `distribution` and `vectorized` properties apply to the entire query plan.
> ```

It might be clearer to say something more like:

"Properties that apply to the entire query plan. Global properties include `distribution` and `vectorization`."
___
*[v21.1/explain.md, line 117 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgxFcv0FPMFP61sAS1:-MXgxFcv0FPMFP61sAS2:b4a813s) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain.md#L117)):*
A couple nits here:

> ```
> A `full` execution plan doesn't mean that processing occurs on all nodes in the cluster
> ```

It might be clearer to say something like:

"An execution plan with `full` distribution doesn't process on all nodes..."

> ```
> The `local` execution plan
> ```

It might be clearer to say something like:

"An execution plan with `local` distribution, on the other hand, is performed only on the gateway node."
___
*[v21.1/explain-analyze.md, line 21 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgqD1K6i8FGc5Nifoz:-MXgqD1K6i8FGc5Nifp-:b-a9e2jx) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L21)):*
> ```
> {% include {{ page.version.version }}/sql/generated/diagrams/explain_analyze.html %}
> ```

This diagram also needs updating (the new `PLAN` parameter isn't in the diagram).
___
*[v21.1/explain-analyze.md, line 38 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgqoC3CbSlG8J_y5MX:-MXgqoC3CbSlG8J_y5MY:bati7st) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L38)):*
typo:

> ```
> return return tables
> ```

return tables
___
*[v21.1/explain-analyze.md, line 47 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgrIfp1uAMWGmyxstI:-MXgrIfp1uAMWGmyxstJ:bhheocn) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L47)):*
> ```
> {% include {{ page.version.version }}/sql/physical-plan-url.md %}
> ```

I'd put this in a note (if we had footnotes in our style guide, I'd actually put it in a footnote :) ).
___
*[v21.1/explain-analyze.md, line 57 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgrZdZC2FKCK9h6m9a:-MXgrZdZC2FKCK9h6m9b:b-x41dlp) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L57)):*
small nit:

> ```
> is `full` execution
> ```

is `full`, execution
___
*[v21.1/explain-analyze.md, line 88 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgs1Uo9koUUttTxdEN:-MXgs1Up03UV4ZsinV1s:b-tkrtcc) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L88)):*
> ```
> <span class="version-tag">New in v21.1:</span> `EXPLAIN ANALYZE (DISTSQL)` can only be used as the top-level statement in a query.
> ```

I'd put this in a note.
___
*[v21.1/explain-analyze.md, line 242 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgsje3Ehges4T9HZp_:-MXgsje3Ehges4T9HZpa:b-whzs9o) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/explain-analyze.md#L242)):*
> ```Markdown
> To view the [DistSQL Plan Viewer](#distsql-plan-viewer), point your browser to the URL provided:
> 
> EXPLAIN ANALYZE (DISTSQL)
> ```

This image needs to be updated. It corresponds to a different query against the TPCH database.
___
*[v21.1/partial-indexes.md, line 98 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXghmFMBzVudnoRlmw_:-MXghmFMBzVudnoRlmwa:b1bfpno) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/partial-indexes.md#L98)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> {% include copy-clipboard.html %}
> ~~~ shell
> $ cockroach demo movr --num-histories 250000 --num-promo-codes 250000 --num-rides 125000 --num-users 12500 --num-vehicles 3750
> ~~~
> ```
</details>


Can you use that `demo_movr` include file here?
___
*[v21.1/partial-indexes.md, line 113 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgtYwgE_BUW14RrMtw:-MXgtYwh541oG-HZe4U6:b-c6cr41) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/partial-indexes.md#L113)):*
nit:
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> schema_name | table_name | type  | owner | estimated_row_count | locality
> --------------+------------+-------+-------+---------------------+-----------
> public      | rides      | table | demo  |                   0 | NULL
> (1 row)
> Time: 17ms total (execution 16ms / network 1ms)
> ```
</details>


This output is off-center (gotta ctrl+cmd+V).
___
*[v21.1/sql-tuning-with-explain.md, line 22 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXguohR-saCYhQMY_VQ:-MXguohR-saCYhQMY_VR:byer6tx) ([raw file](https://github.com/cockroachdb/docs/blob/b1fdfc733325a05a524e631d1f7100e4126c5ae1/v21.1/sql-tuning-with-explain.md#L22)):*
> ```
> ~~~
> ```

I think you accidentally deleted this.
___
*[v21.1/sql-tuning-with-explain.md, line 73 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgv-TZAOr9hVccSJRl:-MXgv-TZAOr9hVccSJRm:b-lzimbz) ([raw file](https://github.com/cockroachdb/docs/blob/b1fdfc733325a05a524e631d1f7100e4126c5ae1/v21.1/sql-tuning-with-explain.md#L73)):*
nit:
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> ~~~
>                    id                  | city  |      name      |      address      | credit_card
> id                  |   city   |      name      |      address      | credit_card
> ---------------------------------------+-------+----------------+-------------------+--------------
>   e147ae14-7ae1-4800-8000-00000000002c | paris | Cheyenne Smith | 8550 Kelsey Flats | 4374468739
> ---------------------------------------+----------+----------------+-------------------+--------------
> 00e6afcc-e1c5-4258-8000-00000000002c | new york | Cheyenne Smith | 8550 Kelsey Flats | 4374468739
> (1 row)
> ```
</details>


This output is off-center (gotta ctrl+cmd+V).
___
*[v21.1/sql-tuning-with-explain.md, line 126 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgvOZH28qBuXMpP81z:-MXgvOZH28qBuXMpP82-:bssmeb8) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/sql-tuning-with-explain.md#L126)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> ~~~
> name      | credit_card
> -----------------+--------------
> Cheyenne Smith | 4374468739
> (1 row)
> ```
</details>


This output is off-center (gotta ctrl+cmd+V).
___
*[v21.1/vectorized-execution.md, line 32 at r5](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXgvYwTBm-OuTf7fWJA:-MXgvYwTBm-OuTf7fWJB:b-pkx969) ([raw file](https://github.com/cockroachdb/docs/blob/305cbccad707faa1dd422e51a2b1be5187bc105f/v21.1/vectorized-execution.md#L32)):*
> ```
> By default, vectorized execution is enabled for all queries.
> ```

Sweet.

**Comment by ianjevans** [comment]
> Is it intentional to not have collected stats here? Ideally we'd want people to see missing stats recognize that this is a problem and take action by running analyze

It was unintentional. Just ran the commands too early for stats.

Refactored the setup instructions and redid the output.

> it also doesnt generate a URL anymore. I get that you can get that with distsql but i think we want to be minimizing this for users. I'd suggest something like "Explain Analyze generates a query plan with execution statistics." Explain Analyze (debug) generates a bundle with more details about the query plan for advanced debugging." And not mention distsql here. @RaduBerinde do you think there is value in even exposing distsql here at all? We constantly get feedback that all of the variations are confusing and it doesn't seem helpful to include it.

Rewrote the section to de-emphasize the URL, but leaving in `DISTSQL` doc for now until we get consensus that we should have it undocumented.

> Do stats collected need to go here?

I broke down the output into global properties, which apply to the entire statement plan and execution, and the statement plan tree properties which have stats for each processor. They're in the next section.

**Review by awoods187 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10240)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling and @ianjevans)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXrJh6rE26zFKgUaCXC:-MXrJh6rE26zFKgUaCXD:b-60ewgh) (no related file):*
LGTM! Nice job!

---
___
*[v21.1/cost-based-optimizer.md, line 347 at r6](https://reviewable.io/reviews/cockroachdb/docs/10240#-MXrJPJj9nYe1NakA5dt:-MXrJPJkDemwXHhqywk-:bvchhpu) ([raw file](https://github.com/cockroachdb/docs/blob/8640adb4c24829309f8325b57110f70f3291c296/v21.1/cost-based-optimizer.md#L347)):*
> ```Markdown
> 
>   • scan
>     estimated row count: 1 (100% of the table; stats collected 5 minutes ago)
> ```

It'd be cool if we had a tool tip on the first one of these, or maybe even a section header that says, what if the plan says no stats collected/stats collected a long time ago? And then you could show how to use analyze to collect statistics

**Comment by jseldess** [comment]
Nice work, @ianjevans! Is there anywhere we should put the "New in v21.1" callout, though?

**Pull request merged**
