### PR TITLE
v20.2 SHOW GRANT updates

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/docs/issues/8510.

### CODE REVIEW

**Review by otan — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by ericharmeling** [comment]
@lnhsingh Ping on review. :)

**Review by lnhsingh — COMMENTED** [review]
Sorry for the delay and thanks for the reminder!

:lgtm: with one nit that you can take or leave

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8807#-:-MLhb8Zq5pScsP5w158Q:b-sgav6y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @lnhsingh)

___
*[v20.2/show-grants.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/8807#-MLhbTdB3XHRJC0ox8wp:-MLhbTdB3XHRJC0ox8wq:bnr07j0) ([raw file](https://github.com/cockroachdb/docs/blob/6d5c5d0d3116a31fbf766e1f20ca6f4a3299e7e6/v20.2/show-grants.md#L37)):*
> ```Markdown
> `targets`    | A comma-separated list of database, schema, table, or user-defined type names.<br><br>{{site.data.alerts.callout_info}}To list the privilege grants for all tables in the current database, you can use `SHOW GRANTS ON TABLE *`.{{site.data.alerts.end}}
> `roles`      | A comma-separated list of the roles whose grants you want to show.
> `users`      | A comma-separated list of the [users](authorization.html#sql-users) whose privileges or roles you want to show.
> ```

This is a small nit / feel free to ignore: maybe move the `users` row above the `roles` row since it appears second in the syntax?

**Review by ericharmeling — COMMENTED** [review]
TFTR @lnhsingh !

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8807#-:-MLi0H5o0GIY7cCNUt1K:bhjhpnt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[v20.2/show-grants.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/8807#-MLhbTdB3XHRJC0ox8wp:-MLi05LK1PcA4XjfjTBq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/6d5c5d0d3116a31fbf766e1f20ca6f4a3299e7e6/v20.2/show-grants.md#L37)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

This is a small nit / feel free to ignore: maybe move the `users` row above the `roles` row since it appears second in the syntax?
</blockquote></details>

Done.

**Pull request merged**
