### PR TITLE
Mention that the --background flag is unavailable in Windows

### LINKED ISSUE #8472: Modify --background flag in cockroach start(-single-node) documentation
Re: [cockroach start-single-node](https://cockroachlabs.com/docs//v20.1/cockroach-start-single-node.html)

## Issue Description
On Windows, `cockroach start-single-node` does not accept the --background flag
## Suggested Resolution 
Add info that `--background` is not available on the Windows binary.

### PR DESCRIPTION
**Pull request by mikeCRL**
Resolves #8472. Updates the `--background` flag description to include this limitation and other minor edits.

### CODE REVIEW

**Comment by mikeCRL** [comment]
@lnhsingh I believe these changes should be in 21.1 and 20.2, and we should bump up the version numbers in the headers [here](https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/1134002829/Update+Docs+Across+Versions), but please let me know and I'll update this branch with any additional changes. Thanks!

**Comment by mikeCRL** [comment]
> @lnhsingh I believe these changes should be in 21.1 and 20.2, and we should bump up the version numbers in the headers [here](https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/1134002829/Update+Docs+Across+Versions), but could you please let me know and I'll update this branch with any additional changes?
> 
> Also, does this require any technical/eng review? I did do some verification (see [#8472 (comment)](https://github.com/cockroachdb/docs/issues/8472#issuecomment-752255921)) and I saved screenshots of that, but I'm not sure if that's enough. Thanks!

FYI, Jesse confirmed all of the above and updated the wiki with the latest version numbers. I'll add these changes to 21.1. He also suggested I check in with Piyush on getting a technical review and considering this as a bug vs. limitation, so I'll be doing that, too.

**Review by lnhsingh — COMMENTED** [review]
Sorry for the delayed review! Once edited on v21.1, this looks good to me. Agreed - add Piyush as a reviewer but I don't think you need another eng review after that!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9247#-:-MQIdFQL2oB9hZhfgrTS:b279ih0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by mikeCRL** [comment]
@lnhsingh Thanks! And by the way, I've since been reminded that I can default to my review partner vs. the person who triaged the issue. Thanks for taking a look at this one regardless!

**Review by piyush-singh — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9247)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by taroface — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL and @taroface)

___
*[v20.2/cockroach-start.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/9247#-MRuWcAH4Asew8aE_xpF:-MRuWcAH4Asew8aE_xpG:bjhx97) ([raw file](https://github.com/cockroachdb/docs/blob/4c1b88c2d61900cbc53ab75d2f07271322f2853e/v20.2/cockroach-start.md#L56)):*
> ```Markdown
> -----|-----------
> `--attrs` | Arbitrary strings, separated by colons, specifying node capability, which might include specialized hardware or number of cores, for example:<br><br>`--attrs=ram:64gb`<br><br>These can be used to influence the location of data replicas. See [Configure Replication Zones](configure-replication-zones.html#replication-constraints) for full details.
> `--background` | Runs the node in the background. Control is returned to the shell only once the node is ready to accept requests, so this is recommended over appending `&` to the command. This flag is not available in Windows environments.<br><br>**Note:** `--background` is suitable for writing automated test suites or maintenance procedures that need a temporary server process running in the background. It is not intended to be used to start a long-running server, because it does not fully detach from the controlling terminal.  Consider using a service manager or a tool like [daemon(8)](https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8) instead.
> ```

I'd suggest bolding "not", i.e. `This flag is **not** available` for extra visibility in the table.

Nice copyedits also!
___
*[v20.2/cockroach-start-single-node.md, line 42 at r2](https://reviewable.io/reviews/cockroachdb/docs/9247#-MRuWphr9UFNl4HWvTax:-MRuWphr9UFNl4HWvTay:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/4c1b88c2d61900cbc53ab75d2f07271322f2853e/v20.2/cockroach-start-single-node.md#L42)):*
> ```Markdown
> -----|-----------
> `--attrs` | **Not relevant for single-node clusters.** Arbitrary strings, separated by colons, specifying node capability, which might include specialized hardware or number of cores, for example:<br><br>`--attrs=ram:64gb`<br><br>These can be used to influence the location of data replicas. See [Configure Replication Zones](configure-replication-zones.html#replication-constraints) for full details.
> `--background` | Runs the node in the background. Control is returned to the shell only once the node is ready to accept requests, so this is recommended over appending `&` to the command. This flag is not available in Windows environments.<br><br>**Note:** `--background` is suitable for writing automated test suites or maintenance procedures that need a temporary server process running in the background. It is not intended to be used to start a long-running server, because it does not fully detach from the controlling terminal. Consider using a service manager or a tool like [daemon(8)](https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8) instead.
> ```

Ditto
___
*[v21.1/cockroach-start.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/9247#-MRuWrBR6xSMnYgZ_rxr:-MRuWrBR6xSMnYgZ_rxs:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/4c1b88c2d61900cbc53ab75d2f07271322f2853e/v21.1/cockroach-start.md#L56)):*
> ```Markdown
> -----|-----------
> `--attrs` | Arbitrary strings, separated by colons, specifying node capability, which might include specialized hardware or number of cores, for example:<br><br>`--attrs=ram:64gb`<br><br>These can be used to influence the location of data replicas. See [Configure Replication Zones](configure-replication-zones.html#replication-constraints) for full details.
> `--background` | Runs the node in the background. Control is returned to the shell only once the node is ready to accept requests, so this is recommended over appending `&` to the command. This flag is not available in Windows environments.<br><br>**Note:** `--background` is suitable for writing automated test suites or maintenance procedures that need a temporary server process running in the background. It is not intended to be used to start a long-running server, because it does not fully detach from the controlling terminal.  Consider using a service manager or a tool like [daemon(8)](https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8) instead.
> ```

Ditto

**Comment by taroface** [comment]
Just 1 small suggestion. Otherwise LGTM.

**Pull request merged**
