### PR TITLE
fix Helm SQL container steps

### PR DESCRIPTION
**Pull request by taroface**
Fixes [DOC-3745](https://cockroachlabs.atlassian.net/browse/DOC-3745).

### CODE REVIEW

**Review by chrisseto — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14240#-:-N48RFpHByQABjnm6Gxw:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chrisseto and @taroface)

___
*[`_includes/v21.2/orchestration/test-cluster-secure.md` line 96 at r1](https://reviewable.io/reviews/cockroachdb/docs/14240#-N48QvFCC9oZTzj0yU3z:-N48QvFCC9oZTzj0yU4-:be30rsj) ([raw file](https://github.com/cockroachdb/docs/blob/62a31f6f09b0feecd32ef6776cd44021104d62ff/_includes/v21.2/orchestration/test-cluster-secure.md#L96)):*
> ```Markdown
>         ~~~
>         serviceAccountName: my-release-cockroachdb
>         name: my-release-cockroachdb-client-secret
> ```

There's a couple `name` fields that are in this yaml file:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: cockroachdb-client-secure
    image: cockroachdb/cockroach:v21.1.11
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach/cockroach-certs/
    command:
    - sleep
    - "2147483648" # 2^31
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    projected:
        sources:
          - secret:
              name: cockroachdb-client-secret.  # THIS ONE
              items:
                - key: ca.crt
                  path: ca.crt
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
        defaultMode: 256
```

Maybe it'll be a bit more clear if we add in the `-secret` here? WDYT?

```yaml
- secret:
  name: my-release-cockroachdb-client-secret
```

**Comment by taroface** [comment]
@chrisseto Makes total sense; sorry I glossed over this a bit. How does the latest update look to you?

**Review by chrisseto — COMMENTED** [review]
:sweat_smile: that's the wrong `name` field. We need to update the one at `spec.volumes[0].project.sources[0].secret.name`

Would it be more clear if we included the entire YAML file with comments next to the appropriate lines? That does add a dependency but this likely won't change for like... a year minimum?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14240#-:-N48Tlv20T5NlnKDboVt:b-89crg7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chrisseto and @taroface)

**Comment by taroface** [comment]
Argh, my mistake again. I do think the similarity of the `name` fields is conducive to human error. What about replacing the whole step with this:

```
    1. In the file, set the following values:

        - `spec.serviceAccountName: my-release-cockroachdb`
        - `spec.image: cockroachdb/cockroach: {your CockroachDB version}`
        - `spec.volumes[0].project.sources[0].secret.name: my-release-cockroachdb-client-secret`
```

And _also_ commenting those 3 lines in the YAML to the effect of `# Update this value for your deployment` (someone else on the team should do this IMO)?

**Comment by chrisseto** [comment]
That is much more clear! I can update the linked YAML.

**Comment by MichaelTrestman** [comment]
*[`_includes/v21.1/orchestration/test-cluster-secure.md` line 94 at r3](https://reviewable.io/reviews/cockroachdb/docs/14240#-N4XEXfd8G7HWi8tgvW4:-N4XEXfe2bdjHBs5mX0l:b93xcf5) ([raw file](https://github.com/cockroachdb/docs/blob/e8c367ec315c30d969dd7195d54104ed607bb688/_includes/v21.1/orchestration/test-cluster-secure.md#L94)):*
> ```Markdown
>     1. In the file, set the following values:
> 
>         - `spec.serviceAccountName: my-release-cockroachdb`
> ```

This list appears not be rendering correctly. Weird, I'm actually not sure why...

**Review by MichaelTrestman — CHANGES_REQUESTED** [review]
There's just the list rendering issue, otherwise LGTM!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/14240#-:-N4XFMHP8dz7-JzD-JJL:b196nlo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[`_includes/v21.2/orchestration/test-cluster-secure.md` line 93 at r3](https://reviewable.io/reviews/cockroachdb/docs/14240#-N4XF62R1xW122Y1WPug:-N4XF62R1xW122Y1WPuh:b-f4p8wc) ([raw file](https://github.com/cockroachdb/docs/blob/e8c367ec315c30d969dd7195d54104ed607bb688/_includes/v21.2/orchestration/test-cluster-secure.md#L93)):*
> ```Markdown
> 
>     1. In the file, set the following values:
> ```

Same rendering problem with the list.

___
*[`_includes/v22.1/orchestration/test-cluster-secure.md` line 93 at r3](https://reviewable.io/reviews/cockroachdb/docs/14240#-N4XFJt28EjwqjYJd2p0:-N4XFJt28EjwqjYJd2p1:b-7ropln) ([raw file](https://github.com/cockroachdb/docs/blob/e8c367ec315c30d969dd7195d54104ed607bb688/_includes/v22.1/orchestration/test-cluster-secure.md#L93)):*
> ```Markdown
> 
>     1. In the file, set the following values:
> ```

ditto

**Comment by taroface** [comment]
@MichaelTrestman Thank you for catching this! It led to some investigation of how exactly the nested lists work. I lightly restructured the lists to make them render correctly.

**Pull request merged**
