### PR TITLE
add --cluster-name and --disable-cluster-name-verification

### LINKED ISSUE #7649: cli: Support cluster name flags in all non-sql client commands
PR: https://github.com/cockroachdb/cockroach/pull/48000

From release notes:
> Client commands such as [`cockroach init`](../v20.2/cockroach-init.html) and [`cockroach quit`](../v20.2/cockroach-quit.html) now support the `--cluster-name` and `--disable-cluster-name-verification` flags in order to support running them on clusters that have been configured to use a cluster name. Previously, it was impossible to run such commands against nodes configured with the `--cluster-name` flag. [#48000][#48000] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by taroface**
Fixes #7649.

Also adds `--cluster-name` and `--disable-cluster-name-verification` to `cockroach start`. They didn't appear to be documented previously.

@knz Not sure if I covered all of the relevant CLI commands. This change should cover:

Through the include:

- `cockroach init`
- `cockroach quit`
- `cockroach node`

Separately:

- `cockroach start`
- `cockroach debug ballast`
- `cockroach debug zip`
- `cockroach debug merge logs`
- `cockroach debug encryption active key`

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[_includes/v20.2/sql/connection-parameters.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_5Oc8RfOJ7gjnHBW:-MJk_5Od4f9M3LOQQNw2:b-34tlby) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L5)):*
> ```Markdown
> `--host` | The server host and port number to connect to. This can be the address of any node in the cluster. <br><br>**Env Variable:** `COCKROACH_HOST`<br>**Default:** `localhost:26257`
> `--port`<br>`-p` | The server port to connect to. Note: The port number can also be specified via `--host`. <br><br>**Env Variable:** `COCKROACH_PORT`<br>**Default:** `26257`
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

"The cluster name to connect to" -> "The cluster name to use to verify the cluster's identity."

Also both flags only pertain to commands that use a RPC connection (`init`, `node decommission` etc). SQL-only commands (e.g. `cockroach sql`, `dump`, `node ls` etc) do not support the flag.

(For context: the difference between RPC commands and SQL commands was prominent in v2.0 and can still be recognized on this doc page. We "erased" this difference in UX some time after that, but it still exists in the code and --cluster-name is a reminder of that. In v21.1 we want to get rid of RPC-only commands altogether).

Maybe it's worth only including this for the specific sub-commands that need it, and not include it in this table which seems common? Unsure.
___
*[_includes/v20.2/sql/connection-parameters.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_E7ZCfGTkGJL9CnV:-MJk_E7ZCfGTkGJL9CnW:b-hr1bv) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L6)):*
> ```Markdown
> `--port`<br>`-p` | The server port to connect to. Note: The port number can also be specified via `--host`. <br><br>**Env Variable:** `COCKROACH_PORT`<br>**Default:** `26257`
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> `--disable-cluster-name-verification` | Disables the cluster name check for this command. If the cluster has a cluster name, either this flag or `--cluster-name` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

I didn't realize this flag existed for client commands too. This surprises me.
(It's necessary server side, but I believe it has no purpose client side. If my understanding is right, then we should remove the flag for client commands. If my understanding is wrong, we may have a bug. I'll investigate.)


If the flag is necessary, in any case it's not valid without --cluster-name
and also this sentence should include a notice that this flag exists for configuration transition only and the operator is responsible to eventually remove it from the command line. (It negates the benefit of --cluster-name)
___
*[v20.2/cockroach-debug-ballast.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_dV72G4I6StBmC1X:-MJk_dV72G4I6StBmC1Y:bbakmhj) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-ballast.md#L38)):*
> ```Markdown
> `--size`<br>`-z` | The amount of space to fill, or to leave available, in a node's storage directory via a ballast file. Positive values equal the size of the ballast file. Negative values equal the amount of space to leave after creating the ballast file. This can be a percentage (notated as a decimal or with %) or any bytes-based unit, for example:<br><br>`--size=1000000000 ----> 1000000000 bytes`<br>`--size=1GiB ----> 1073741824 bytes`<br>`--size=5% ----> 5% of available space`<br>`--size=0.05 ----> 5% of available space`<br>`--size=.05 ----> 5% of available space`<br><br>**Default:** `1GB`
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> `--disable-cluster-name-verification` | Disables the cluster name check for this command. If the cluster has a cluster name, either this flag or `--cluster-name` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

This command does not connect to a cluster. so it does not have connection parameters.
___
*[v20.2/cockroach-debug-encryption-active-key.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_ekq0ZmaRuAQHOF1:-MJk_ekq0ZmaRuAQHOF2:bbakmhj) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-encryption-active-key.md#L23)):*
> ```Markdown
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> `--disable-cluster-name-verification` | Disables the cluster name check for this command. If the cluster has a cluster name, either this flag or `--cluster-name` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

This command does not connect to a cluster. so it does not have connection parameters.
___
*[v20.2/cockroach-debug-merge-logs.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJka8AzEbjKAulfXIIT:-MJka8AzEbjKAulfXIIU:br25xgh) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-merge-logs.md#L34)):*
> ```Markdown
> `--from` | Start time for the time range filter.
> `--to` | End time for the time range filter.
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

`merge-logs` does not connect to a cluster. So it does not have connection flags.
___
*[v20.2/cockroach-debug-zip.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJkaULREJQIXHsFqoEX:-MJkaULREJQIXHsFqoEY:b4z457d) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-zip.md#L78)):*
> ```Markdown
> `--certs-dir` | The path to the [certificate directory](cockroach-cert.html). The directory must contain valid certificates if running in secure mode.<br><br>**Env Variable:** `COCKROACH_CERTS_DIR`<br>**Default:** `${HOME}/.cockroach-certs/`
> `--host` | The server host to connect to. This can be the address of any node in the cluster. <br><br>**Env Variable:** `COCKROACH_HOST`<br>**Default:** `localhost`
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

see my initial comment about "verify"
___
*[v20.2/cockroach-debug-zip.md, line 79 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJkaWCV9RoNWnZtqrWG:-MJkaWCV9RoNWnZtqrWH:b-2qbg1g) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-zip.md#L79)):*
> ```Markdown
> `--host` | The server host to connect to. This can be the address of any node in the cluster. <br><br>**Env Variable:** `COCKROACH_HOST`<br>**Default:** `localhost`
> `--cluster-name` | The cluster name to connect to. If the cluster has a cluster name, either this flag or `--disable-cluster-name-verification` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> `--disable-cluster-name-verification` | Disables the cluster name check for this command. If the cluster has a cluster name, either this flag or `--cluster-name` must be included. For more information, see [`cockroach start`](cockroach-start.html#general).
> ```

see my initial comment about whether this flag exists for client commands and the disclaimer.
___
*[v20.2/cockroach-start.md, line 59 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJkaeEhDeT4frzZ8GLI:-MJkaeEhDeT4frzZ8GLJ:bg60ipx) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-start.md#L59)):*
> ```Markdown
> `--cache` | The total size for caches, shared evenly if there are multiple storage devices. This can be a percentage (notated as a decimal or with `%`) or any bytes-based unit, for example: <br><br>`--cache=.25`<br>`--cache=25%`<br>`--cache=1000000000 ----> 1000000000 bytes`<br>`--cache=1GB ----> 1000000000 bytes`<br>`--cache=1GiB ----> 1073741824 bytes` <br><br><strong>Note:</strong> If you use the `%` notation, you might need to escape the `%` sign, for instance, while configuring CockroachDB through `systemd` service files. For this reason, it's recommended to use the decimal notation instead.<br><br>**Default:** `128MiB`<br><br>The default cache size is reasonable for local development clusters. For production deployments, this should be increased to 25% or higher. Increasing the cache size will generally improve the node's read performance. See [Recommended Production Settings](recommended-production-settings.html#cache-and-sql-memory-size) for more details.
> `--cluster-name` | A string that specifies a cluster name. This is used together with `--join` to ensure that all newly created nodes join the intended cluster when you are running multiple clusters.<br><br>**Note:** If this is set, [`cockroach init`](cockroach-init.html), [`cockroach node decommission`](cockroach-node.html), [`cockroach node recommission`](cockroach-node.html), and the `cockroach debug` commands must specify either `--cluster-name` or `--disable-cluster-name-verification` in order to work.
> `--disable-cluster-name-verification` | On clusters for which `--cluster-name` has been set, this flag disables the cluster name check for the command. This is necessary on existing clusters, when setting a cluster name or changing the cluster name: Perform a rolling restart of all nodes and include both the new `--cluster-name` value and `--disable-cluster-name-verification`, then a second rolling restart with `--cluster-name` and without `--disable-cluster-name-verification`.
> ```

nice :100:

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[_includes/v20.2/sql/connection-parameters.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_5Oc8RfOJ7gjnHBW:-MK1tpoMENc4TL1qAJbq:b-h9dl8p) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L5)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"The cluster name to connect to" -> "The cluster name to use to verify the cluster's identity."

Also both flags only pertain to commands that use a RPC connection (`init`, `node decommission` etc). SQL-only commands (e.g. `cockroach sql`, `dump`, `node ls` etc) do not support the flag.

(For context: the difference between RPC commands and SQL commands was prominent in v2.0 and can still be recognized on this doc page. We "erased" this difference in UX some time after that, but it still exists in the code and --cluster-name is a reminder of that. In v21.1 we want to get rid of RPC-only commands altogether).

Maybe it's worth only including this for the specific sub-commands that need it, and not include it in this table which seems common? Unsure.


</blockquote></details>

Thanks for this context. I removed the flags from this include and added them separately for `cockroach init`, `cockroach quit`, and `cockroach node decommission` and `cockroach node recommission`. They are also still listed for `cockroach start` and `cockroach debug zip`. Are there any other commands that need to include these flags?
___
*[_includes/v20.2/sql/connection-parameters.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_E7ZCfGTkGJL9CnV:-MK1s8wJB69XNWeRvzs9:b7h848s) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L6)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I didn't realize this flag existed for client commands too. This surprises me.
(It's necessary server side, but I believe it has no purpose client side. If my understanding is right, then we should remove the flag for client commands. If my understanding is wrong, we may have a bug. I'll investigate.)


If the flag is necessary, in any case it's not valid without --cluster-name
and also this sentence should include a notice that this flag exists for configuration transition only and the operator is responsible to eventually remove it from the command line. (It negates the benefit of --cluster-name)
</blockquote></details>

It was my understanding from https://github.com/cockroachdb/cockroach/pull/48000 that this flag can be used in client commands. Let me know if I misunderstood something here.
___
*[v20.2/cockroach-debug-ballast.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_dV72G4I6StBmC1X:-MK1r7PwA7jpXh0IQkbv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-ballast.md#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This command does not connect to a cluster. so it does not have connection parameters.
</blockquote></details>

Done.
___
*[v20.2/cockroach-debug-encryption-active-key.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_ekq0ZmaRuAQHOF1:-MK1rE8F0tuTqT3IctDK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-encryption-active-key.md#L23)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This command does not connect to a cluster. so it does not have connection parameters.
</blockquote></details>

Done.
___
*[v20.2/cockroach-debug-merge-logs.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJka8AzEbjKAulfXIIT:-MK1rGql18NBUD0AByR0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-merge-logs.md#L34)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`merge-logs` does not connect to a cluster. So it does not have connection flags.
</blockquote></details>

Done.

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[v20.2/cockroach-debug-zip.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJkaULREJQIXHsFqoEX:-MK1uQck0dEGGeNQR6n-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-zip.md#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see my initial comment about "verify"
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[_includes/v20.2/sql/connection-parameters.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_5Oc8RfOJ7gjnHBW:-MK43oL8-Rxz5vPDr-No:b-wan2oz) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L5)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Thanks for this context. I removed the flags from this include and added them separately for `cockroach init`, `cockroach quit`, and `cockroach node decommission` and `cockroach node recommission`. They are also still listed for `cockroach start` and `cockroach debug zip`. Are there any other commands that need to include these flags?
</blockquote></details>

I did some spelunking and here's the current list of RPC client commands:

`quit`
`debug gossip-values`
`gen haproxy`
`init`
`node decommission` / `recommission`
`node drain`
`debug tsdump`
`debug zip` (this one is mixed RPC/SQL)
___
*[_includes/v20.2/sql/connection-parameters.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_E7ZCfGTkGJL9CnV:-MK44Udh1_I5iZQ-Sd2R:b3c7s39) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L6)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

It was my understanding from https://github.com/cockroachdb/cockroach/pull/48000 that this flag can be used in client commands. Let me know if I misunderstood something here.
</blockquote></details>

Yes I can see it's currently implemented this way. It's unclear to me still whether it is necessary or useful. In any case it only works paired with `--cluster-name`.

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[_includes/v20.2/sql/connection-parameters.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_5Oc8RfOJ7gjnHBW:-MK5Y3yt6fsy3JVcBmj7:bx8aspx) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L5)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I did some spelunking and here's the current list of RPC client commands:

`quit`
`debug gossip-values`
`gen haproxy`
`init`
`node decommission` / `recommission`
`node drain`
`debug tsdump`
`debug zip` (this one is mixed RPC/SQL)

</blockquote></details>

Thanks! Also added to `gen haproxy` and `node drain` (the other remaining commands aren't mentioned in docs).
___
*[_includes/v20.2/sql/connection-parameters.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJk_E7ZCfGTkGJL9CnV:-MK5YFF03PhfMvBdhTIq:b-m0jgmq) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/_includes/v20.2/sql/connection-parameters.md#L6)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes I can see it's currently implemented this way. It's unclear to me still whether it is necessary or useful. In any case it only works paired with `--cluster-name`.
</blockquote></details>

Clarified in field descriptions that this must be paired with `--cluster-name`.
___
*[v20.2/cockroach-debug-zip.md, line 79 at r1](https://reviewable.io/reviews/cockroachdb/docs/8676#-MJkaWCV9RoNWnZtqrWG:-MK5YMpT-uS_9K6NRNv5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4b2854887b0244d98bb70acaf187559fbf49214e/v20.2/cockroach-debug-zip.md#L79)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see my initial comment about whether this flag exists for client commands and the disclaimer.
</blockquote></details>

Done.

**Review by Amruta-Ranade — APPROVED** [review]

**Pull request merged**
