### PR TITLE
Include generated functions and operators docs

### LINKED ISSUE #9883: use remote includes on generated docs
Docs that use auto-generated `cockroach` content, such as:

- https://www.cockroachlabs.com/docs/stable/functions-and-operators.html
- https://www.cockroachlabs.com/docs/stable/cluster-settings.html
- https://www.cockroachlabs.com/docs/stable/sql-grammar.html

should use remote includes so that we won't have to manually update them for each release.

Remote includes should point to the appropriate branch for each docs version.

### PR DESCRIPTION
**Pull request by jseldess**
Instead of copying the generated files from the cockroach
repo to the docs repo, we can now use the remote_include plugin
to pull directly from the cockroach repo.

Continuation of https://github.com/cockroachdb/docs/pull/9904

Fixes #9883

### CODE REVIEW

**Comment by jseldess** [comment]
Have to resolve some broken links:

```
========================================================================
13:49:20
  running in concurrent mode, this is experimental
13:49:20
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/uuid.html
13:49:20
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/uuid.html --> functions-and-operators.html#id-generation-functions
13:49:20
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/uuid.html --> functions-and-operators.html#id-generation-functions
13:49:21
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/performance-best-practices-overview.html
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/performance-best-practices-overview.html --> functions-and-operators.html#id-generation-functions
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/performance-best-practices-overview.html --> functions-and-operators.html#id-generation-functions
13:49:21
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/sql-faqs.html
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/sql-faqs.html --> functions-and-operators.html#id-generation-functions
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/sql-faqs.html --> functions-and-operators.html#id-generation-functions
13:49:21
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/create-table.html
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/create-table.html --> functions-and-operators.html#id-generation-functions
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.1/create-table.html --> functions-and-operators.html#id-generation-functions
13:49:21
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-is-contained-by
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-contains
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-equals
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-get-object-field
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-less-than
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-less-than-or-equal
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-is-contained-by
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/inverted-indexes.html --> functions-and-operators.html#operator-contains
13:49:21
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/array.html
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/array.html --> functions-and-operators.html#operator-contains
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.1/array.html --> functions-and-operators.html#operator-is-contained-by
13:49:21
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/releases/beta-20161013.html
13:49:21
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/releases/beta-20161013.html --> ../v1.0/functions-and-operators.html#date-and-time-functions
13:49:22
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.0/sql-faqs.html
13:49:22
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.0/sql-faqs.html --> functions-and-operators.html#id-generation-functions
13:49:22
  1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.0/create-table.html
13:49:22
    hash does not exist --- 1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v1.0/create-table.html --> functions-and-operators.html#id-generation-functions
13:49:24
  ========================================================================
```

**Review by ericharmeling — APPROVED** [review]
Wow. Amazing. Thank you @jseldess and @ianjevans.

And I honestly did not know about the `release-X.x` branch convention that we had. Makes keeping these up-to-date even easier. I was anticipating having to update at minor releases.

Only glaring thing I noticed in this PR was that there is some funky black text background on a note in some of the date time function descriptions (e.g., http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1a9281d5629bb36c45cd6ef7bc7b2b18e3b0d09f/v20.2/functions-and-operators.html#date-and-time-functions).

These notes aren't in [the current docs](https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions) because the current docs are out-of-date. The notes were introduced in this commit: https://github.com/cockroachdb/cockroach/commit/d2c08369a93d03dbb7fe602b2110b55f65b298a8#diff-03b025681dddd011154c7efd11796ef2e412eb8d2269df3e207b4e37ba0bd04aR334

So we might need to do some accompanying (or follow-up) work to update the stylesheet so that all `<pre>` elements (there are only two in `functions.md`) just make the text italic or something.

Other than that, the changes LGTM. I guess next on the list is `settings.md`?

> Reviewed 3 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9907#-:-MUnS0Qc2tOhNOsHnW2h:b-1a1wh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

**Comment by ericharmeling** [comment]
>  I guess next on the list is settings.md?

Never mind - I see you already did that!

https://github.com/cockroachdb/docs/pull/9904

**Comment by jseldess** [comment]
TFTR, @ericharmeling! And good catch on that formatting. I'll open an issue about that after merging this.

**Pull request merged**
