### PR TITLE
steps to increase the open files limit

### LINKED ISSUE #436: Recommended Production Settings
Page to list recommendations for production environments. 

Possible topics:
- [File descriptor limits](https://github.com/cockroachdb/docs/issues/53)
- Clock synchronization

For reference:
- Cassandra's [production recommendations](https://docs.datastax.com/en/cassandra/2.0/cassandra/install/installRecommendSettings.html)

### PR DESCRIPTION
**Pull request by jseldess**
Adding steps to increase the open files limit on various versions of Mac and Linux. 

HTML version: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.html

Fixes #436

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/459)

### CODE REVIEW

**Comment by jseldess** [comment]
@bdarnell, @petermattis, PTAL as well. If there are any other production settings to recommend, let me know and I'll try to work them into this PR.

**Comment by petermattis** [comment]
I'm sure there are other production setting recommendations, but none are coming to mind right now.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[recommended-production-settings.md, line 28 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KMzfoHL0o3Y2wdtmJpf:-KMzfoHL0o3Y2wdtmJpg:1851995087) ([raw file](https://github.com/cockroachdb/docs/blob/935260c3d95a377b9086840e6753a78c966fc7ea/recommended-production-settings.md#L28)):*
> ```Markdown
> For each CockroachDB node:
> 
> - At a **minimum**, the open files limit must be 256 per store plus 256 for networking. If the limit is below this threshold, the node will not start. 
> ```

I wonder if you should do the math here: `At a minimum, the open files limit must be 512 -- 256 per store plus 256 for networking.` Ditto for the next bullet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459#-:-KMzg8K_q-PmseoZjYdZ:-32292333)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459#-:-KMzgH_Zu3DV8eQxuPYi:1417088721)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[recommended-production-settings.md, line 28 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KMzfoHL0o3Y2wdtmJpf:-KMzqcZI0dkcH3VWLvQ_:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/935260c3d95a377b9086840e6753a78c966fc7ea/recommended-production-settings.md#L28)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I wonder if you should do the math here: `At a minimum, the open files limit must be 512 -- 256 per store plus 256 for networking.` Ditto for the next bullet.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[recommended-production-settings.md, line 125 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-97omcKeb9CPv6T1l:-KN-97omcKeb9CPv6T1m:-1525128680) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L125)):*
> ```Markdown
>     ~~~
> 
>     `kern.maxfilesperproc` is the relevant setting, as it controls the open file limit for a single process.
> ```

Don't you need to set `maxfiles` at least as high as `maxfilesperproc`? (I don't know how this works, just guessing from the names)

---

*[recommended-production-settings.md, line 167 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9NjHHf1T9vwfaCcc:-KN-9NjHHf1T9vwfaCcd:1297846146) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L167)):*
> ```Markdown
>               <string>launchctl</string>
>               <string>limit</string>
>               <string>maxproc</string>
> ```

Should this be `maxfilesperproc`?

---

*[recommended-production-settings.md, line 200 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9nMvtalZP4fVx4_A:-KN-9nMvtalZP4fVx4_B:1785662312) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L200)):*
> ```Markdown
>     ~~~ shell
>     $ launchtctl limit maxfiles
>     maxfiles    10240          10240      
> ```

Do you need `maxfilesperproc` here or is that only for yosemite?

---

*[recommended-production-settings.md, line 245 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9ykO7vVyyoVG0OVM:-KN-9ykO7vVyyoVG0OVN:1955131120) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L245)):*
> ```Markdown
>     ~~~ shell
>     *              soft     nofile          20000
>     *              hard     nofile          20000
> ```

Mention that the `*` could be replaced with the username that will be running the cockroachdb server.

---

*[recommended-production-settings.md, line 253 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-AK9nklPOpz2-1jyC:-KN-AK9nklPOpz2-1jyD:1558031304) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L253)):*
> ```Markdown
> 
>     ~~~ shell
>     UseLogin yes
> ```

This seems like an odd requirement to me. You need `UsePam`, which is the default, but I'm not sure why you'd need `UseLogin`.

---

*[recommended-production-settings.md, line 297 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-BhAVBKOPqVqgwk9p:-KN-BhAVBKOPqVqgwk9q:-179690621) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L297)):*
> ```Markdown
> #### Attributions
> 
> This section, "File Descriptors Limit", is a derivative of Open File Limits by Riak, used under Creative Commons Attribution 3.0 Unported License.
> ```

Please link to the original source.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[recommended-production-settings.md, line 125 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-97omcKeb9CPv6T1l:-KN-syoYJgs8XN8mAYWU:893935905) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L125)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Don't you need to set `maxfiles` at least as high as `maxfilesperproc`? (I don't know how this works, just guessing from the names)
</details>
Good point. I've mentioned that.

---

*[recommended-production-settings.md, line 167 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9NjHHf1T9vwfaCcc:-KN-t3YOPhQk6U4Jz7JM:199019575) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L167)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Should this be `maxfilesperproc`?
</details>
Nope, I'm only seeing it referenced as `maxproc`. This is all quite confusing. I went through this process, though, and it worked for me.

---

*[recommended-production-settings.md, line 200 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9nMvtalZP4fVx4_A:-KN-tLsZkErRu6Gt2s0a:-1485448062) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L200)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Do you need `maxfilesperproc` here or is that only for yosemite?
</details>
That's only for yosemite and later, I think.

---

*[recommended-production-settings.md, line 245 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9ykO7vVyyoVG0OVM:-KN-u1gnAJMC6-5ppOl_:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L245)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Mention that the `*` could be replaced with the username that will be running the cockroachdb server.
</details>
Done.

---

*[recommended-production-settings.md, line 253 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-AK9nklPOpz2-1jyC:-KN-uEpggh--INxqMgSM:-812456695) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L253)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This seems like an odd requirement to me. You need `UsePam`, which is the default, but I'm not sure why you'd need `UseLogin`.
</details>
This is marked as optional in the basho docs. Should I just remove it? 

---

*[recommended-production-settings.md, line 297 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-BhAVBKOPqVqgwk9p:-KN-uRRuJA-DR7016mGS:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L297)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Please link to the original source.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[recommended-production-settings.md, line 167 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9NjHHf1T9vwfaCcc:-KN0F6LYMeoggu5CIyND:885256084) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L167)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Nope, I'm only seeing it referenced as `maxproc`. This is all quite confusing. I went through this process, though, and it worked for me.
</details>
I don't understand then. You say that `maxfilesperproc` is the important one, but then you never actually change it. `maxproc` looks like it's something unrelated that we don't need to change.

---

*[recommended-production-settings.md, line 253 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-AK9nklPOpz2-1jyC:-KN0FNdw-Dyu_6jjbuj_:2033735428) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L253)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> This is marked as optional in the basho docs. Should I just remove it? 
</details>
They say that it's optional in the sense that you don't have to use ssh, but ssh is important enough that if this matters then we should document it here. It doesn't feel right to me but I don't know enough about this stuff to say that the basho docs are wrong. 

I think in this case I'd lean toward leaving it out until it's proven necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459)*

**Comment by BramGruneir** [comment]
In code, I got rid of the soft/hard terminology to use cur/max instead.  But I noticed that we use a combination here.  Should we settle on a single style, or perhaps mention that they are equivalent but named different in different OSs?

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459#-:-KN2giqYWQYtNpCcI4Na:-870770182)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[recommended-production-settings.md, line 167 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-9NjHHf1T9vwfaCcc:-KN3RT15SjVtJoTL1u_g:-2010592169) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L167)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I don't understand then. You say that `maxfilesperproc` is the important one, but then you never actually change it. `maxproc` looks like it's something unrelated that we don't need to change.
</details>
I've reworked the steps based on our offline talk. We know use the `launchctl` command to read the limits, and we only set `limit.maxfiles.plist`.

---

*[recommended-production-settings.md, line 253 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/docs/459#-KN-AK9nklPOpz2-1jyC:-KN3RpP_Gr_rkJdLZRv2:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.md#L253)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> They say that it's optional in the sense that you don't have to use ssh, but ssh is important enough that if this matters then we should document it here. It doesn't feel right to me but I don't know enough about this stuff to say that the basho docs are wrong. 
> 
> I think in this case I'd lean toward leaving it out until it's proven necessary.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459)*

**Comment by jseldess** [comment]
@BramGruneir, sorry for the delay. If you don't mind editing those messages again, I now think it's best to go with soft/hard. That's what I've seen used most often. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459#-:-KN3leOwGvL4AAIxz5yb:476915014)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/459#-:-KN42THAdan0NTUqepBT:1417088721)*

**Pull request merged**
