### PR TITLE
Add Windows binary to install instructions

### LINKED ISSUE #1307: Windows binary
Need to update Windows installation instructions and perhaps other getting started tutorials.

PRs: 
- https://github.com/cockroachdb/cockroach/pull/15061
- https://github.com/cockroachdb/cockroach/pull/15238

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1307

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1311)

### CODE REVIEW

**Comment by tamird** [comment]
Heh, the big green "install" button at the top right of the page is broken in the TC preview. Paging @mjibson.

I would disclaim:

"Please note that support for running CockroachDB on Windows is experimental and has not been extensively tested by the Cockroach Labs team. The Windows binary is provided as a convenience for local development and experimentation; production deployments of CockroachDB on Windows are strongly discouraged."

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[install-cockroachdb.md, line 471 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1311#-KiBmcpIgnirWvv3KhDR:-KiBmcpJj2e_NIOOokGK:b-qyi3gg) ([raw file](https://github.com/cockroachdb/docs/blob/87ce89be2c14e8fe668cc73582d98034d45b9483/install-cockroachdb.md#L471)):*
> ```Markdown
>   </li>
>   <li>
>     <p>Open PowerShell and make sure CockroachDB installed successfully:</p>
> ```

"installed" is a weird term. "make sure the CockroachDB executable works:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1311#-:-KiBmOCfnb4uVuH-D95B:b-k2n00z)*

**Comment by jseldess** [comment]
Thanks, @tamird. We know about the install button being broken on TC. It's due to the way Jekyll is prepending the site baseurl to that link, which works fine on the production server.

**Comment by jseldess** [comment]
Added the disclaimer and fixed some styling.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[install-cockroachdb.md, line 471 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1311#-KiBmcpIgnirWvv3KhDR:-KiC1QqOT20YJPhIGZsK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/87ce89be2c14e8fe668cc73582d98034d45b9483/install-cockroachdb.md#L471)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"installed" is a weird term. "make sure the CockroachDB executable works:"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1311#-:-KiC1TMoDpWo3slkLGeZ:blabo7a)*

**Comment by bdarnell** [comment]
There are some rough edges with the windows distribution (cockroachdb/cockroach#15221 and cockroachdb/cockroach#15223) so let's wait until next week to announce and document this. Please remove the windows link and mention from the release notes too.

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1311)*

**Comment by jseldess** [comment]
OK, I'll leave this for next week.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1311#-:-KiC5z4AzTAj6KCjL0mB:b-fsq6r4)*

**Comment by tamird** [comment]
:lgtm: but needs to go out after release as discussed.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1311#-:-Kijl4ynzDJK6gbygIxO:b-xpqo9i)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1311)*

**Pull request merged**
