### PR TITLE
adding SQL feature support matrix

### PR DESCRIPTION
**Pull request by sploiselle**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/550)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql-feature-support.md, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/550#-KPKFNxhIaZUa93M7Lu-:-KPKFNxhIaZUa93M7Lu0:b-of6677) ([raw file](https://github.com/cockroachdb/docs/blob/96c7abdeddac6be92f03e4f1cf805b62603a4a84/sql-feature-support.md#L60)):*
> ```Markdown
> | Component | Supported | Type | Details |
> |-----------|-----------|------|---------|
> | `INNER JOIN` | ✓ | Standard | [`JOIN` blog post](https://www.cockroachlabs.com/blog/cockroachdbs-first-join/) |
> ```

Given our current implementation, we should mark these with a footnote instead of a full "check". The footnote can say that these operations are supported only for small data sets. @knz what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/550)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql-feature-support.md, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/550#-KPKFNxhIaZUa93M7Lu-:-KPKG6VzyghUsfih0X7m:b-ju1jhr) ([raw file](https://github.com/cockroachdb/docs/blob/96c7abdeddac6be92f03e4f1cf805b62603a4a84/sql-feature-support.md#L60)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Given our current implementation, we should mark these with a footnote instead of a full "check". The footnote can say that these operations are supported only for small data sets. @knz what do you think?
</details>
Yes I agree with you. Let's make it a yellow checkmark or a round blue info icon. At least avoid green.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/550)*

**Comment by sploiselle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql-feature-support.md, line 60 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/550#-KPKFNxhIaZUa93M7Lu-:-KPNfW-JdBy5qInafoo0:b423eb9) ([raw file](https://github.com/cockroachdb/docs/blob/96c7abdeddac6be92f03e4f1cf805b62603a4a84/sql-feature-support.md#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Yes I agree with you. Let's make it a yellow checkmark or a round blue info icon. At least avoid green.
</details>
Done. Moved this to the __Statements__ section since all of the `JOIN` types are supported and had the same info and lengthy note. Avoided obfuscating the info by changing the "Supported" column from ✓ to Functional, with the specification about small data sets in the "Details" column.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/550)*

**Comment by RaduBerinde** [comment]
Very nice, thank you! :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/550#-:-KPOYv5bJ_EuRojsLq7W:b1jdflu)*

**Comment by jseldess** [comment]
Excellent work, @sploiselle! LGTM.

@nvanbenschoten, should introspection be added? If so, can you suggest an approach?

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql-feature-support.md, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/550#-KPSvS3UCINF01iMoAjO:-KPSvS3UCINF01iMoAjP:bpi0txe) ([raw file](https://github.com/cockroachdb/docs/blob/96c7abdeddac6be92f03e4f1cf805b62603a4a84/sql-feature-support.md#L7)):*
> ```Markdown
> 
> ## Overview
> Making CockroachDB easy to use was a top priority for us, so we chose to implement SQL. However, even though SQL has a standard, no database implements all of it, nor do any of them have standard implementations of all features.
> ```

Let's continue this priority until the end of time: "...easy to use **is** a top priority for us..."

---

*[sql-feature-support.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/550#-KPTDiEbibUoBAS7MlMj:-KPTDiEcfrwR9RZK2hC6:btq00x) ([raw file](https://github.com/cockroachdb/docs/blob/96c7abdeddac6be92f03e4f1cf805b62603a4a84/sql-feature-support.md#L11)):*
> ```Markdown
> To understand which standard SQL features we support (as well as common extensions to the standard), use the table below.
> 
> - __Component__ lists the components that are commonly considered part of SQL.
> ```

nit: Would you mind using `**Component**` as the markdown for bold, for consistency with other pages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/550#-:-KPTElYgenUVMLxI55cK:bt2s1pp)*

**Comment by nvanbenschoten** [comment]
@jseldess We could add a section for supported methods of introspection, but I foresee a page/section like https://www.postgresql.org/docs/9.5/static/information-schema.html being more immediately useful. Each subsection would provide a brief overview of a supported introspection table, along with it's schema.

**Comment by jseldess** [comment]
Thanks, @nvanbenschoten. Noted.

**Pull request merged**
