### PR TITLE
CREATE TABLE LIKE

### LINKED ISSUE #7605: sql: add CREATE TABLE LIKE
PR: https://github.com/cockroachdb/cockroach/pull/47017

From release notes:
> Added `CREATE TABLE LIKE` specifiers. [#47017][#47017] {% comment %}doc{% endcomment %}
>
> Made small UX improvements to [hash sharded index](../v20.2/indexes.html#hash-sharded-indexes) creation. [#47017][#47017] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7605.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@jordanlewis Friendly review reminder. :)

**Comment by jordanlewis** [comment]
LGTM, sorry for the delay!

**Comment by ericharmeling** [comment]
No worries! TFTR

**Review by lnhsingh — COMMENTED** [review]
I think the `like_table_option_list` should be included in the parameters, but otherwise LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8222#-:-MGj7Xnr4g5O5KNQDCy4:b-cm7bfb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @jordanlewis, and @lnhsingh)

___
*[v20.2/create-table.md, line 96 at r1](https://reviewable.io/reviews/cockroachdb/docs/8222#-MGj34jM-3KMD2WRX6zW:-MGj34jN-4bWf6ODpref:b-x1b56a) ([raw file](https://github.com/cockroachdb/docs/blob/75c35e7ee3ff45442f13be997d06179a0d51a423/v20.2/create-table.md#L96)):*
> ```Markdown
> `family_def` | An optional, comma-separated list of [column family definitions](column-families.html). Column family names must be unique within the table but can have the same name as columns, constraints, or indexes.<br><br>A column family is a group of columns that are stored as a single key-value pair in the underlying key-value store. CockroachDB automatically groups columns into families to ensure efficient storage and performance. However, there are cases when you may want to manually assign columns to families. For more details, see [Column Families](column-families.html).
> `table_constraint` | An optional, comma-separated list of [table-level constraints](constraints.html). Constraint names must be unique within the table but can have the same name as columns, column families, or indexes.
> `LIKE` | <span class="version-tag">New in v20.2:</span> Create a new table based on the schema of an existing table. For details, see [Create a table like an existing table](#create-a-table-like-an-existing-table). For examples, see [Create a new table from an existing one](#create-a-new-table-from-an-existing-one).
> ```

I think `like_table_option_list` should be included in the parameters, even if the description just links to the #create-a-table-like-an-existing-one section

**Comment by ericharmeling** [comment]
> I think the `like_table_option_list` should be included in the parameters, but otherwise LGTM
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8222#-:-MGj7Xnr4g5O5KNQDCy4:b-cm7bfb)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @jordanlewis, and @lnhsingh)
> 
> _[v20.2/create-table.md, line 96 at r1](https://reviewable.io/reviews/cockroachdb/docs/8222#-MGj34jM-3KMD2WRX6zW:-MGj34jN-4bWf6ODpref:b-x1b56a) ([raw file](https://github.com/cockroachdb/docs/blob/75c35e7ee3ff45442f13be997d06179a0d51a423/v20.2/create-table.md#L96)):_
> 
> > ```gfm
> > `family_def` | An optional, comma-separated list of [column family definitions](column-families.html). Column family names must be unique within the table but can have the same name as columns, constraints, or indexes.<br><br>A column family is a group of columns that are stored as a single key-value pair in the underlying key-value store. CockroachDB automatically groups columns into families to ensure efficient storage and performance. However, there are cases when you may want to manually assign columns to families. For more details, see [Column Families](column-families.html).
> > `table_constraint` | An optional, comma-separated list of [table-level constraints](constraints.html). Constraint names must be unique within the table but can have the same name as columns, column families, or indexes.
> > `LIKE` | <span class="version-tag">New in v20.2:</span> Create a new table based on the schema of an existing table. For details, see [Create a table like an existing table](#create-a-table-like-an-existing-table). For examples, see [Create a new table from an existing one](#create-a-new-table-from-an-existing-one).
> > ```
> 
> I think `like_table_option_list` should be included in the parameters, even if the description just links to the #create-a-table-like-an-existing-one section

Done.

TFTR!

**Pull request merged**
