### PR TITLE
+ results_buffer_size conn param, - session var

### PR DESCRIPTION
**Pull request by rmloveland**
Summary of changes:

- Remove `results_buffer_size` as a session variable (it cannot be `SET`) from the session variables page, from a mention in the Read Committed docs, and another in an include about server-side retries

- Add `results_buffer_size` as a connection string parameter (at top-level or in `options` param) and point most previous mentions of the session variable at the conn param

- NB. These changes were made to v23.1, v23.2, v24.1, v24.2

Fixes:

- DOC-10309
- DOC-6494

See also:

- cockroachdb/cockroach#124360
- cockroachdb/cockroach#124437

### CODE REVIEW

**Comment by rmloveland** [comment]
@dikshant FYI this is getting done (removed you from review)

**Review by rafiss — APPROVED** [review]
lgtm!

**Review by taroface — APPROVED** [review]
This is also mentioned in the `performance/increase-server-side-retries.md` include, and I guess it should be removed from there as well. Also, should this be ported to additional versions?

**Comment by rmloveland** [comment]
> This is also mentioned in the `performance/increase-server-side-retries.md` include, and I guess it should be removed from there as well

Ah thanks, must have missed that one, I'll take a look and remove / edit

> Also, should this be ported to additional versions?

looks like DOC-6494 was filed in Jan 2023 so that would be v22.2+

since our [currently supported releases](https://www.cockroachlabs.com/docs/releases/release-support-policy#current-supported-releases)  are only v23.1+, I'll port these changes to v23.1+

**Pull request merged**
