### PR TITLE
Updated --city-pair flag to --city flag for affected docker commands

### PR DESCRIPTION
**Pull request by mokaixu**
Pertains to documentation about Low Latency Reads and Writes in a Multi-Region Cluster

Fixes: #8647

### CODE REVIEW

**Comment by lnhsingh** [comment]
@taroface - mind reviewing?

**Review by taroface — CHANGES_REQUESTED** [review]
@mokaixu I think this update should be limited to `v20.1` and above. Could you please revert the changes on `v19.2` and `v19.1`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9196#-:-MOmZO3E2jTttDcGZPCL:bmxkpzn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Review by mokaixu — COMMENTED** [review]
Done! Changes for 19.1 and 19.2 have been reverted. Changes now only apply to v20.1, 20.2, and 21.1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9196#-:-MOma1Zk-7-AkjkIPP3_:b-ai0onv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Review by taroface — APPROVED** [review]
LGTM! Thank you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9196#-:-MOmavY5-6Bm1E1dDnG_:b3wlixp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

**Pull request merged**
