### PR TITLE
Improve load balancing docs

### LINKED ISSUE #1253: cli: haproxy config now includes `check`
[Manual Deployment](https://www.cockroachlabs.com/docs/manual-deployment.html) guide needs to be updated to reflect cockroachdb/cockroach#14624

According to @mberhault the new `check` value at the end end of the `server` line simply enabled TCP checks, which are good so you know which instances are up or down.

### LINKED ISSUE #2594: Doc updates for /health?ready=1
Need to mention in rolling upgrade docs and in load balancer instructions in deployment tutorials.

### LINKED ISSUE #2794: cockroach gen haproxy has been extended with readiness checks
PR: https://github.com/cockroachdb/cockroach/pull/23590

### PR DESCRIPTION
**Pull request by jseldess**
- Add load balancing to production checklist.
- Reference new health endpoint in cloud deployment tutorials.
- Update haproxy docs to cover health checks
- Link to load balancing from rolling upgrade doc.
- Revise the sidenav.

Fixes #2594.
Fixes #2794.
Fixes #1253.

### CODE REVIEW

**Comment by a-robinson** [comment]
Reviewed 8 of 8 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[v2.0/deploy-cockroachdb-on-aws.md, line 94 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mWAdP5zrJbpBIsCLL:-L8mWAdP5zrJbpBIsCLM:bqlpurx) ([raw file](https://github.com/cockroachdb/docs/blob/944dad5309de6a1d924ec1fbad944f4a7ecaeb8e/v2.0/deploy-cockroachdb-on-aws.md#L94)):*
> ```Markdown
> 1. [Add AWS load balancing](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-increase-availability.html). Be sure to:
>     - Set forwarding rules to route TCP traffic from the load balancer's port **26257** to port **26257** on the nodes.
>     - Configure health checks to use HTTP port **8080** and `/health?ready=1`. This [health endpoint](monitoring-and-alerting.html#health-ready-1) ensures that load balancers don't direct traffic to nodes that are live but not ready to receive requests.
> ```

Any reason why you removed the word "path" from all but one of these files? It reads more clearly to me with it left in.

---

*[v2.0/deploy-cockroachdb-on-premises.md, line 89 at r2](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mZAP48lRQ3kreiKge:-L8mZAP48lRQ3kreiKgf:bz6j3s0) ([raw file](https://github.com/cockroachdb/docs/blob/b68f6c95d8b51322b9765a4d9458e6748d625d56/v2.0/deploy-cockroachdb-on-premises.md#L89)):*
> ```Markdown
>         balance roundrobin
>         option httpchk GET /health?ready=1
>         server cockroach1 <node1 address>:26257
> ```

For all the v2.0 files, this should be

```
        server cockroach1 <node1 address>:26257 check port 8080
```

And ditto for the two lines below. You may then want to add info to the table below about the "check port" keywords as well

---

*[v2.0/generate-cockroachdb-resources.md, line 248 at r2](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8m__TQ8cWDrC29eCB9:-L8m__TQ8cWDrC29eCBA:bu33tta) ([raw file](https://github.com/cockroachdb/docs/blob/f8fbaaeff39ac36d67ce751c13d413c70dac0fc8/v2.0/generate-cockroachdb-resources.md#L248)):*
> ```Markdown
> </div>
> 
> By default, the generated configuration file is called `haproxy.cfg` and looks as follows, with the `server` addresses pre-populated correctly:
> ```

Without this intro text, given the way it's presented a user might expect the `cockroach gen haproxy` command to print this output, when in reality the command outputs nothing. This is what you'd see in the `haproxy.cfg` file after running the command.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2816)*

**Comment by jseldess** [comment]
*[v2.0/deploy-cockroachdb-on-aws.md, line 94 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mWAdP5zrJbpBIsCLL:-L8mh0lO1_m1-EH3_9Gy:bwarhut) ([raw file](https://github.com/cockroachdb/docs/blob/944dad5309de6a1d924ec1fbad944f4a7ecaeb8e/v2.0/deploy-cockroachdb-on-aws.md#L94)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Any reason why you removed the word "path" from all but one of these files? It reads more clearly to me with it left in.
</blockquote></details>

Mistake. Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2816)*

**Comment by a-robinson** [comment]
Reviewed 3 of 3 files at r3, 9 of 16 files at r4, 6 of 6 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[v1.1/recommended-production-settings.md, line 77 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mhw0b-vfKZTMNZFJI:-L8mhw0b-vfKZTMNZFJJ:b-ta1jk1) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v1.1/recommended-production-settings.md#L77)):*
> ```Markdown
> ## Load Balancing
> 
> Each CockroachDB node is an equally suitable SQL gateway to a cluster, but to ensure client performance and reliability, it's important to use TCP load balancing:
> ```

nit: it isn't really important that the load balancing is TCP load balancing. Application-aware (L7) load balancing would be fine too, so I'd just say "it's important to use load balancing".

---

*[v1.1/recommended-production-settings.md, line 81 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mhJVk9uLYgPlNiUpb:-L8mhJVk9uLYgPlNiUpc:b7i3efl) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v1.1/recommended-production-settings.md#L81)):*
> ```Markdown
> - **Performance:** Load balancers spread client traffic across nodes. This prevents any one node from being overwhelmed by requests and improves overall cluster performance (queries per second).
> 
> - **Reliability:** Load balancers decouple client health from the health of a single CockroachDB node. To ensure that traffic is not directed to failed nodes or nodes that are not ready to receive requests, load balancers should use [CockroachDB's health check](monitoring-and-alerting.html#health).
> ```

In v1.1 our health check isn't all that useful to a load balancer. Our `gen haproxy` config just uses whether it's able to connect to a node's serving port as the signal of whether it's healthy.

If it doesn't make the wording here too weird, I'd just leave out the recommendation to use the health endpoint in the v1.1 docs.

---

*[v2.0/recommended-production-settings.md, line 76 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mi4YfA6oUtxyyPUfd:-L8mi4YfA6oUtxyyPUfe:b-ta1jk1) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v2.0/recommended-production-settings.md#L76)):*
> ```Markdown
> ## Load Balancing
> 
> Each CockroachDB node is an equally suitable SQL gateway to a cluster, but to ensure client performance and reliability, it's important to use TCP load balancing:
> ```

nit: it isn't really important that the load balancing is TCP load balancing. Application-aware (L7) load balancing would be fine too, so I'd just say "it's important to use load balancing".

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2816)*

**Comment by jseldess** [comment]
Review status: 2 of 35 files reviewed at latest revision, 5 unresolved discussions.

---

*[v1.1/recommended-production-settings.md, line 81 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mhJVk9uLYgPlNiUpb:-L8o0kRs3A00B59ewc40:b-5xb04y) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v1.1/recommended-production-settings.md#L81)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

In v1.1 our health check isn't all that useful to a load balancer. Our `gen haproxy` config just uses whether it's able to connect to a node's serving port as the signal of whether it's healthy.

If it doesn't make the wording here too weird, I'd just leave out the recommendation to use the health endpoint in the v1.1 docs.
</blockquote></details>

Np, I'll just revert to what we had before.

---

*[v2.0/generate-cockroachdb-resources.md, line 248 at r2](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8m__TQ8cWDrC29eCB9:-L8o2V9J5u9o5Ni2LmAh:b-lvuzji) ([raw file](https://github.com/cockroachdb/docs/blob/f8fbaaeff39ac36d67ce751c13d413c70dac0fc8/v2.0/generate-cockroachdb-resources.md#L248)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Without this intro text, given the way it's presented a user might expect the `cockroach gen haproxy` command to print this output, when in reality the command outputs nothing. This is what you'd see in the `haproxy.cfg` file after running the command.
</blockquote></details>

That was a mistake. Thanks for catching it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2816)*

**Comment by jseldess** [comment]
Review status: 2 of 35 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[v1.1/recommended-production-settings.md, line 77 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mhw0b-vfKZTMNZFJI:-L8o7vO3BjLuj_TSwHB5:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v1.1/recommended-production-settings.md#L77)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

nit: it isn't really important that the load balancing is TCP load balancing. Application-aware (L7) load balancing would be fine too, so I'd just say "it's important to use load balancing".
</blockquote></details>

Done.

---

*[v2.0/deploy-cockroachdb-on-premises.md, line 89 at r2](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mZAP48lRQ3kreiKge:-L8o7yIB6bAoIGbGVNPE:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b68f6c95d8b51322b9765a4d9458e6748d625d56/v2.0/deploy-cockroachdb-on-premises.md#L89)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

For all the v2.0 files, this should be

```
        server cockroach1 <node1 address>:26257 check port 8080
```

And ditto for the two lines below. You may then want to add info to the table below about the "check port" keywords as well
</blockquote></details>

Done.

---

*[v2.0/recommended-production-settings.md, line 76 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mi4YfA6oUtxyyPUfd:-L8o7zLuDeLKc11kBEyB:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v2.0/recommended-production-settings.md#L76)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

nit: it isn't really important that the load balancing is TCP load balancing. Application-aware (L7) load balancing would be fine too, so I'd just say "it's important to use load balancing".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2816)*

**Comment by a-robinson** [comment]
Great changes! :lgtm: 

---

Reviewed 33 of 33 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v1.1/recommended-production-settings.md, line 77 at r3](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-L8mhw0b-vfKZTMNZFJI:-L8pEI4J2IxNbxfPDFta:b-tez41e) ([raw file](https://github.com/cockroachdb/docs/blob/878fd4bea3b3e729e01175b8695086b405f6af57/v1.1/recommended-production-settings.md#L77)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't realize this would involve changing so many files. Thanks for tracking them all down!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2816#-:-L8pEarP-yX5YQS-W0Ri:b7vf7t6)*

**Comment by jseldess** [comment]
TFTR, @a-robinson. I also added a link from rolling upgrade to load balancing, and I reorganized the sidenav a bit to put monitoring content together under deployment.

**Pull request merged**
