### PR TITLE
First pass at adding circle-ci on the docs repo.

### PR DESCRIPTION
**Pull request by mberhault**
* runs jekyll to generates pages
* runs htmlproofer on generates pages
* copies generated pages to a S3-as-website bucket

It's a bit annoying that it will run everything regardless of test
failures, but we can't use the deployment section for all PRs, and I
prefer to have the individual steps listed in circleci as opposed to one
big step.

Also added `https` to a bunch of URLs.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/407)

### CODE REVIEW

**Comment by mberhault** [comment]
The generated docs were pushed to http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8e64fe181372d4aa9e6a225381809063188f2c23/

**Comment by uptimeDBA** [comment]
I can't find my reference to it but I had issues a while ago (on another site) when I put `https` in the URLs as some users/browsers got an error. I ended up leaving the URLs starting with `//` so the user's browser determined the protocol. If we want to force them to use `https` for the documentation, then I guess including `https` is the way to go.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/407#-:-KKojMDGcnP6ZqpPNgt_:2042281544)*

**Comment by mberhault** [comment]
I'm not sure where it would cause problems, especially for the URLs I adjusted here. Most of them are for `cockroachlabs.com` (which doesn't even have an http version, it's just a redirect to https) and a couple of other external properties. The links within `docs/` are still relative, so viewing it them in plain http for testing should be just fine.

That said, I'm happy to reconsider if it causes issues. We would just have to make `htmlproof` happy with the scheme-less URLs.

**Comment by uptimeDBA** [comment]
Probably all good. Might pay to keep in mind just in case there are any access issues reported.

**Comment by jseldess** [comment]
Looks great to me! I notice that a few of the links in the topnav (install and docs) are broken on aws because they're using  `prepend:site.baseurl`, which adds `/docs`. But this isn't an issue for me. 

Thanks for setting this up so quickly, Marc. We can look into a way to add a comment to the PR with the aws url in a future PR.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/407#-:-KKpKX8mZuFoxIXDdgKd:1775173413)*

**Comment by mberhault** [comment]
Ah. interesting. We would need to replace the `site.baseurl` with the sha. If this does not interfere with either jekyll or htmlproof, that should be fine. Is this something we can specify on the commandline to jekyll or do we need to modify a file?

**Comment by jseldess** [comment]
It looks like you can use `jekyll build --baseurl URL`. But I'm confused. `_config.yml` has `baseurl: "/docs"`. How is that not getting added to page urls on aws? I see that `circle.yml` uses the sha. Is that replacing `baseurl` for all pages?

**Comment by mberhault** [comment]
the full URL for the docs' main page is:
http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/8e64fe181372d4aa9e6a225381809063188f2c23/, which means that relative links of the form `/docs/foo.html` need to point to `/8e64fe181372d4aa9e6a225381809063188f2c23/foo.html`

The `/docs/` dir isn't there at all, it's only correct because that's what we use as the directory on the real server. Changing the baseurl just for circleci should be sufficient, I'll give it a shot tomorrow.

**Comment by mberhault** [comment]
Turns out `--baseurl` is an option only when using `serve`, it doesn't work on `build`. Instead, I'm creating a one-line config file and using it to override the default one.
I've also replaced `/docs/` with `baseurl` in a bunch of places (mainly the nav and footer) and set some of them to be ignored by the proofer. It means that the nav pieces work on the S3 preview, but aren't checked.

**Comment by mberhault** [comment]
After a fair amount of tweaking, finally got things in a (hopefully) reasonable state. S3 preview is at: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3c0b5159e241cc3127e07ac9c05389dacb31049e/

**Comment by jseldess** [comment]
:lgtm: Thanks, Marc. 

For future reference, here's a script Pantheon runs to have the preview URL posted as a comment in the PR: https://github.com/pantheon-systems/documentation/blob/master/scripts/deploy-multidev.sh#L80

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/407#-:-KKsYLvH-4av1UHQ728b:-1448942763)*

**Comment by jseldess** [comment]
Fixes #39

**Pull request merged**
