### PR TITLE
Document Change

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Adding copy clipboad command to copy the codes from the documentation

### CODE REVIEW

**Comment by NiteshKoushik** [comment]
Gone through the preview window, the edited page is working as expected, kindly review.

**Comment by NiteshKoushik** [comment]
Closing the PR as no action taken from long time

**Comment by SWDevAngel** [comment]
Hi Nitesh. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) @lisa so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Comment by SWDevAngel** [comment]
@NiteshKoushik LAST DAY TO ORDER!
Hi Nitesh. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. We tried to reach you via GitHub or on email, but if you didn’t see the message please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link to order your gift. (If you don’t want a gift, we also have a charitable contribution choice.) All orders must be in by December 13 (that’s tomorrow!), so please send this asap. :)

**Pull request closed without merging**
