### PR TITLE
Added Self-Hosted to connection reference

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/docs/issues/12723.

This PR adds a "Self-Hosted" tab to the [Connect to a CockroachDB Cluster](https://www.cockroachlabs.com/docs/stable/connect-to-the-database.html) page.

### CODE REVIEW

**Comment by ericharmeling** [comment]
Related to https://github.com/cockroachlabs/support/issues/1384...

I was unable to get password-less client cert/key auth working with [the JDBC connection string format presented in this PR](https://deploy-preview-12745--cockroachdb-docs.netlify.app/docs/v21.2/connect-to-the-database.html?filters=core&filters=java).

I ran the [`example-app-java-jdbc` sample app](https://github.com/cockroachlabs/example-app-java-jdbc/blob/master/app/src/main/java/com/cockroachlabs/BasicExample.java) with a modified connection configuration:

```
PGSimpleDataSource ds = new PGSimpleDataSource();
ds.setUrl(System.getenv("DATABASE_URL"));
```

Where `DATABASE_URL="jdbc:postgresql://localhost:26257/defaultdb?user=eric&sslmode=verify-full&sslcert=$CLIENT_CERT_PATH&sslrootcert=$CA_CERT_PATH&sslkey=$CLIENT_KEY_PATH_PK8"`. 

The sample app returns the following error:

```
The server requested password-based authentication, but no password was provided.
```

**Comment by rafiss** [comment]
using a connection string works for me. i used
```
ds.setURL("jdbc:postgresql://localhost:26257/defaultdb?user=testuser&sslmode=verify-full&sslcert=%2FUsers%2Frafiss%2Fgo%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcerts%2Fclient.testuser.crt&sslrootcert=%2FUsers%2Frafiss%2Fgo%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcerts%2Fca.crt&sslkey=%2FUsers%2Frafiss%2Fgo%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fcerts%2Fclient.testuser.key.pk8");
```

**Review by nickvigilante — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12745)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by nickvigilante** [comment]
Formatting wise, this looks good. The only thing I might suggest is if we can somehow consolidate Connection Parameters across all combinations into a single block, but I don't know if that would make it more confusing to edit in the future. Just seems like a lot of copying/pasting for small text changes.

**Comment by ericharmeling** [comment]
> we can somehow consolidate Connection Parameters across all combinations into a single block, but I don't know if that would make it more confusing to edit in the future. Just seems like a lot of copying/pasting for small text changes.

I tried to consolidate as many parameter tables as made sense (i.e., one per language), without creating some arbitrary div group or some (as you noted) confusing conditional logic. I'm comfortable making things less confusing but a little more tedious for future updates. 😁

**Comment by nickvigilante** [comment]
Gotcha. LGTM otherwise!

**Comment by ericharmeling** [comment]
TFTR @nickvigilante !

I think I'm going to just merge.

I've tested all of the self-hosted connection strings at the driver level on local, secure clusters. So they should all work. I don't expect anyone to run through all of these again in review of these docs. We can always iterate if users run into any bugs.

**Pull request merged**
