### PR TITLE
Add learn cockroachdb sql interactive tutorial

### PR DESCRIPTION
**Pull request by jseldess**
- Add new full-page layout for katacoda scenarios.
- Add new page for learn cockroachdb sql tutorial.
- Simplify intro to learn cockroachdb sql tutorial.
- Add CTA for interactive tutorial to learn cockroahdb
  sql tutorial.

### CODE REVIEW

**Comment by jseldess** [comment]
@ericharmeling, ahead of being able to implement @luciaaaaaaa's vision for interactive tutorials, this PR puts one in place for Learn CockroachDB SQL. You'll see a CTA on that page now that opens the interactive version in a new tab. PTAL.

@yingzhuchin, to accomplish this, I had to add a new layout. PTAL and let me know if we should do this differently.

**Review by ericharmeling — APPROVED** [review]
This is awesome. Love it!

Question: Where is the content coming from in the interactive tutorial (i.e., where is `cockroachlabs/courses/get-started/learn-cockroachdb-sql` pointing to?) 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8711#-:-MK5PuRw5qaAtbtpoB0K:b-ov61xt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yingzhuchin)

**Review by yingzhuchin — APPROVED** [review]
Looks good to me except for a small nit: The Cockroach chat button on the lower right obscures part of the interactive window. Do we want to keep the chat option for the tutorial?

**Review by jseldess — COMMENTED** [review]
TFTRs!

@yingzhuchin, good catch. I've removed the drift widget from this layout.

@ericharmeling, you ask a good question. I'll have to document how this is all working as it's not easy to discern. The source for this and all other interactive tutorials will be in a subdirectory of our docs repo: `/docs/interactive-tutorials`. We've hooked the repo into our Katacoda account, so anytime we push to that content, Katacoda knows to rebuild the tutorials wherever they are displayed. They are current displayed on our Katacaoda profile (https://www.katacoda.com/cockroachlabs) and then wherever we embed them in our docs. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8711#-:-MKEwrVS7DEm_KXNSsPq:b-v9r9z1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

**Comment by jseldess** [comment]
@yingzhuchin or @anagio, can either of you help me with the challenge described in commit 2? 

```
Still need to figure out how to remove

top-padding: 100px

from the .content class. That padding is there to
accommodate the version switch bar. This will be
going away with the redesign, but ahead of that,
I need to remove it from this tutorial page
because it's pushing the prompt in the terminal
below the fold.
```

**Pull request merged**
