### PR TITLE
Add TA 123371

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-10236

Rendered preview: [TA a123371](https://deploy-preview-18599--cockroachdb-docs.netlify.app/docs/advisories/a123371.html)

### CODE REVIEW

**Comment by rmloveland** [comment]
@rytaft I marked this as WIP since AIUI this is to go out on June 10th (per [this convo](https://cockroachlabs.slack.com/archives/CSPK16V51/p1716386840541819?thread_ts=1715114397.674989&cid=CSPK16V51)) - is that still the plan?

**Comment by rytaft** [comment]
> @rytaft AIUI this is to go out on June 10th (per [this convo](https://cockroachlabs.slack.com/archives/CSPK16V51/p1716386840541819?thread_ts=1715114397.674989&cid=CSPK16V51)) - is that still the plan?

That's correct, thank you!

**Review by rytaft — APPROVED** [review]
LGTM, thanks! Sorry for the delay.

**Comment by rytaft** [comment]
Can we merge this now?

**Pull request merged**
