### PR TITLE
Document USE and SET NAMES, simplifies SET TIME ZONE

### LINKED ISSUE #1502: sql: add an alias USE for SET DATABASE = ...
PR: https://github.com/cockroachdb/cockroach/pull/16293

### LINKED ISSUE #1503: sql: alias SET client_encoding to SET NAMES
PR: https://github.com/cockroachdb/cockroach/pull/16305

### PR DESCRIPTION
**Pull request by knz**
Fixes #1502.
Fixes #1503.

Also covers the change implemented in https://github.com/cockroachdb/cockroach/pull/16459

Based off #1107 to separate concerns, and also because this change applies to 1.1 not 1.0.

### CODE REVIEW

**Comment by knz** [comment]
Agreed. I'll rebase off release-1.1 when the other PR is merged.
Any suggested ETA on that btw?

**Comment by jseldess** [comment]
I'm reviewing it now. Hopefully we can have feedback to you very soon.

**Comment by jseldess** [comment]
@knz, now that https://github.com/cockroachdb/docs/pull/1107 has landed, you should be free to wrap this one up, right? No rush, just don't want it to get lost.

**Comment by knz** [comment]
No problem. Do you want me to also take my changes from #1107 and pick them to apply on top of `release-1.1`?

**Comment by jseldess** [comment]
Yeah, that'd be great, @knz. Thank you!

**Comment by knz** [comment]
Superseded by #1609.

**Pull request closed without merging**
