### PR TITLE
add Satori integration doc

### PR DESCRIPTION
**Pull request by MichaelTrestman**
https://cockroachlabs.atlassian.net/browse/DOC-3294

### CODE REVIEW

**Review by abhinavg6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @harshn08, @kathancox, and @MichaelTrestman)

___
*[`_includes/v22.1/misc/tooling.md` line 58 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0hzTXN3W0_o9OUhYgJ:-N0hzTXN3W0_o9OUhYgK:b-ay23lt) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/misc/tooling.md#L58)):*
> ```Markdown
> | [IntelliJ IDEA](https://www.jetbrains.com/idea/) | 2021.1 | Full | [Use IntelliJ IDEA with CockroachDB](intellij-idea.html)
> 
> ## Enhanced data access control tools
> ```

Maybe call it "Enhanced data security tools". Just trying to not paint it into a corner of access control only.
___
*[`_includes/v22.1/misc/tooling.md` line 60 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0hydFh4uUNkC2jDH40:-N0hydFh4uUNkC2jDH41:b-uzrmzr) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/misc/tooling.md#L60)):*
> ```Markdown
> ## Enhanced data access control tools
> 
> [Satori](satori-integration.html) offers fine-grained access control and dymamic data masking.
> ```

typo: "dynamic" with an "n"

You could also add "Partner supported" in the field "Support level". Also, I think the main link should be external to https://satoricyber.com/ (like for other tools), and then the "satori-integration.html" should probably be a link in the "Tutorial" field.
___
*[`_includes/v22.1/sidebar-data/reference.json` line 1795 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i-0yhE7TgOxoEz-eo:-N0i-0yi89gOGQDvzOPU:b-jz0d9p) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/sidebar-data/reference.json#L1795)):*
> ```JSON
>                   "/${VERSION}/satori-integration.html"
>                 ]
>               }
> ```

Why is this the only one as an item here, when I see many other tools listed at https://www.cockroachlabs.com/docs/v21.2/third-party-database-tools.html?
___
*[`v22.1/satori-integration.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i-cQo5ele0EWh6892:-N0i-cQo5ele0EWh6893:b-got3hs) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L8)):*
> ```Markdown
> ---
> 
> [Satori](https://satoricyber.com/) offers powerful tooling to extend CockroachDB's grain of access control. Satori can be used in concert with {{ site.data.products.db }} or {{ site.data.products.core }}.
> ```

Maybe a slight change, something like the following:

[Satori](https://satoricyber.com/) offers powerful tooling to extend CockroachDB's data security capabilities. Satori's Data Access Controller (DAC) can be used in concert with {{ site.data.products.db }} or {{ site.data.products.core }}.
___
*[`v22.1/satori-integration.md` line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i05WrAc-TR6dDvJWS:-N0i05WrAc-TR6dDvJWT:bqj0fp2) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L14)):*
> ```Markdown
> ## [Fine-grained access control](https://satoricyber.com/fine-grained-access-control/)
> 
> - "No-code" advanced policy control.
> ```

- "No-code" advanced policy-based access control.
___
*[`v22.1/satori-integration.md` line 15 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i0Gi840dDuT9ANwiI:-N0i0Gi840dDuT9ANwiJ:b-l9axim) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L15)):*
> ```Markdown
> 
> - "No-code" advanced policy control.
> - Admins can configure fine-grained access control to restrict a SQL user's access to specific rows or columns.
> ```

- Admins can configure fine-grained access control in a scalable manner across their users, to restrict SQL access to specific rows and / or columns.
___
*[`v22.1/satori-integration.md` line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i0uSFDZyXNlyEmNfc:-N0i0uSFDZyXNlyEmNfd:bt38hfx) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L20)):*
> ```Markdown
> ## [Dynamic data masking](https://satoricyber.com/dynamic-data-masking/)
> 
> Admins can configure dynamic data masking for PII or other organizational confidential data, to prevent access to sensitive data and add a level of defense-in-depth against any possible data theft.
> ```

Admins can configure dynamic data masking for PII, PHI or other organizationally confidential data, to prevent access to sensitive data and add a level of defense-in-depth to significantly reduce the risk of data theft. A common use case is to combine it with fine-grained access control. 


Also, I think we should add the following below this section:



_Code snippet:_
```Markdown
## [Scalable data access auditing](https://satoricyber.com/data-access-auditing-monitoring/)

Admins can also configure scalable data access auditing which could augment the CockroachDB audit logs, by providing enriched metadata and contextual information. This is particularly useful if one is looking to enable auditing across all their OLTP and OLAP data stores from one single location.

To use Satori with your CockroachDB deployment, reach out to your CockroachDB team.
```

**Review by MichaelTrestman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @harshn08, @kathancox, and @MichaelTrestman)

___
*[`_includes/v22.1/misc/tooling.md` line 58 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0hzTXN3W0_o9OUhYgJ:-N14T-MZ6QDRkQBDHyAG:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/misc/tooling.md#L58)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Maybe call it "Enhanced data security tools". Just trying to not paint it into a corner of access control only.
</blockquote></details>

Done.
___
*[`_includes/v22.1/misc/tooling.md` line 60 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0hydFh4uUNkC2jDH40:-N14TLJo6JwNzCzwdZur:b-x75mk5) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/misc/tooling.md#L60)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

typo: "dynamic" with an "n"

You could also add "Partner supported" in the field "Support level". Also, I think the main link should be external to https://satoricyber.com/ (like for other tools), and then the "satori-integration.html" should probably be a link in the "Tutorial" field.
</blockquote></details>

To complete the table, do we have a "Latest tested version"?
___
*[`v22.1/satori-integration.md` line 20 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i0uSFDZyXNlyEmNfc:-N14_E8vCTNPpMtGhRbx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L20)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Admins can configure dynamic data masking for PII, PHI or other organizationally confidential data, to prevent access to sensitive data and add a level of defense-in-depth to significantly reduce the risk of data theft. A common use case is to combine it with fine-grained access control. 


Also, I think we should add the following below this section:
</blockquote></details>

Done.
___
*[`_includes/v22.1/sidebar-data/reference.json` line 1795 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i-0yhE7TgOxoEz-eo:-N14WN-o2B5lIdN-mpXq:b-lnd7bg) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/sidebar-data/reference.json#L1795)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Why is this the only one as an item here, when I see many other tools listed at https://www.cockroachlabs.com/docs/v21.2/third-party-database-tools.html?
</blockquote></details>

Moved it under Develop / Tutorials where some of the others live.

**Review by abhinavg6 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @harshn08, @kathancox, and @MichaelTrestman)

___
*[`_includes/v22.1/misc/tooling.md` line 60 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0hydFh4uUNkC2jDH40:-N15-0D-7aOcE89SeNI_:b-mnezfw) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/_includes/v22.1/misc/tooling.md#L60)):*
<details><summary><i>Previously, MichaelTrestman (Michael Trestman) wrote…</i></summary><blockquote>

To complete the table, do we have a "Latest tested version"?
</blockquote></details>

They don't have a public-facing versioning, so we can skip it.
___
*[`v22.1/satori-integration.md` line 24 at r3](https://reviewable.io/reviews/cockroachdb/docs/13642#-N15-qUYDLOSXO_zcjds:-N15-qUYDLOSXO_zcjdt:b77umsr) ([raw file](https://github.com/cockroachdb/docs/blob/16f1611b89959e72bc12441ec50c4c770c09bc88/v22.1/satori-integration.md#L24)):*
> ```Markdown
> Satori Documentation: [Dynamic data masking](https://satoricyber.com/dynamic-data-masking/)
> 
> Admins can configure dynamic data masking. This feature adds a layer of defense-in-depth against data theft, and can be combined with fine-grained access control for powerful and precise protection of personally identifiable information (PII), protect health information (PHI) or other confidential data.
> ```

"protected health information (PHI)"
___
*[`v22.1/satori-integration.md` line 31 at r3](https://reviewable.io/reviews/cockroachdb/docs/13642#-N1504jD6jKyIHD-HcPA:-N1504jD6jKyIHD-HcPB:bxjivmc) ([raw file](https://github.com/cockroachdb/docs/blob/16f1611b89959e72bc12441ec50c4c770c09bc88/v22.1/satori-integration.md#L31)):*
> ```Markdown
> 
> - Admins can configure scalable data access auditing, augmenting CockroachDB's audit logs with enriched metadata and contextual information.
> - Allows consolidation of audit logs from OLTP and OLAP data stores to a single location.
> ```

Actually thinking about it, we should change this to:

"Allows consolidation of SQL audit logs from multiple CockroachDB clusters to a single location."

**Review by MichaelTrestman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @harshn08, and @kathancox)

___
*[`v22.1/satori-integration.md` line 8 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i-cQo5ele0EWh6892:-N157jStEzfC-Go6n7ZM:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L8)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Maybe a slight change, something like the following:

[Satori](https://satoricyber.com/) offers powerful tooling to extend CockroachDB's data security capabilities. Satori's Data Access Controller (DAC) can be used in concert with {{ site.data.products.db }} or {{ site.data.products.core }}.
</blockquote></details>

Done.
___
*[`v22.1/satori-integration.md` line 14 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i05WrAc-TR6dDvJWS:-N157jmB42hp1hBK0oQq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L14)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

- "No-code" advanced policy-based access control.
</blockquote></details>

Done.
___
*[`v22.1/satori-integration.md` line 15 at r2](https://reviewable.io/reviews/cockroachdb/docs/13642#-N0i0Gi840dDuT9ANwiI:-N157oVU7O71AyPOO3il:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f0f3d106dde76df6892cea252e8092eb78c88586/v22.1/satori-integration.md#L15)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

- Admins can configure fine-grained access control in a scalable manner across their users, to restrict SQL access to specific rows and / or columns.
</blockquote></details>

Done.
___
*[`v22.1/satori-integration.md` line 24 at r3](https://reviewable.io/reviews/cockroachdb/docs/13642#-N15-qUYDLOSXO_zcjds:-N157rRa7-VrpEAJnFq-:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/16f1611b89959e72bc12441ec50c4c770c09bc88/v22.1/satori-integration.md#L24)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

"protected health information (PHI)"
</blockquote></details>

Done.
___
*[`v22.1/satori-integration.md` line 31 at r3](https://reviewable.io/reviews/cockroachdb/docs/13642#-N1504jD6jKyIHD-HcPA:-N158-pp2sog3mmrIBf2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/16f1611b89959e72bc12441ec50c4c770c09bc88/v22.1/satori-integration.md#L31)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Actually thinking about it, we should change this to:

"Allows consolidation of SQL audit logs from multiple CockroachDB clusters to a single location."
</blockquote></details>

Done.

**Review by abhinavg6 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @harshn08 and @kathancox)

**Review by kathancox — APPROVED** [review]
LGTM, with the few typos corrected. 

Couple other things to consider.

**Review by MichaelTrestman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13642)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @harshn08 and @kathancox)

___
*[`v22.1/satori-integration.md` line 8 at r4](https://reviewable.io/reviews/cockroachdb/docs/13642#-N021G-lFJnV_sVaVasK-r4-8:-N1FcFFP2NgaaDCcIP1U:b-ckmn11) ([raw file](https://github.com/cockroachdb/docs/blob/f40156342b74184f16677f9592100d955c4d1579/v22.1/satori-integration.md#L8)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Completely my opinion, so take or leave it: 

I try and avoid language pushing into hyperbole or opinion, so would not include "powerful". I think without the message carries fine. 

But "powerful" is in other places in the docs 🤷‍♀️ 
</blockquote></details>

Removed. The irony is that saying "powerful" just sounds so weak, doesn't it?
___
*[`v22.1/satori-integration.md` line 12 at r4](https://reviewable.io/reviews/cockroachdb/docs/13642#-N021G-lFJnV_sVaVasK-r4-12:-N1FbH2AD9HjXHnWP-UR:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f40156342b74184f16677f9592100d955c4d1579/v22.1/satori-integration.md#L12)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Just a thought: 

Before seeing the link to each of the Satori Documentation pieces, I kind of wanted to read your description first. As a reader, it feels like the link out is if I need more information. Perhaps it could follow your description in each case? 

Maybe within a sentence: "See Satori's documentation for more on X." 
</blockquote></details>

Done.
___
*[`v22.1/satori-integration.md` line 24 at r4](https://reviewable.io/reviews/cockroachdb/docs/13642#-N021G-lFJnV_sVaVasK-r4-24:-N1FbRAEBBvW4J6XkuD7:brxx30e) ([raw file](https://github.com/cockroachdb/docs/blob/f40156342b74184f16677f9592100d955c4d1579/v22.1/satori-integration.md#L24)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: Add in a serial comma after "or" here.
</blockquote></details>

Done. You meant before "or" I believe.
___
*[`v22.1/satori-integration.md` line 30 at r4](https://reviewable.io/reviews/cockroachdb/docs/13642#-N021G-lFJnV_sVaVasK-r4-30:-N1Fbz9F4FFEDagTLBEE:bywgzfp) ([raw file](https://github.com/cockroachdb/docs/blob/f40156342b74184f16677f9592100d955c4d1579/v22.1/satori-integration.md#L30)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

"scalable data access auditing" 

Not sure on the meaning, exactly, but would a hyphen clear this up: "scalable data-access auditing". I guess it depends on what is being audited.
</blockquote></details>

removed the 'scalables' from throughout the doc and hoisted them to a covering 'at scale' in the top scope at the beginning of the doc.
___
*[`v22.1/satori-integration.md` line 33 at r4](https://reviewable.io/reviews/cockroachdb/docs/13642#-N021G-lFJnV_sVaVasK-r4-33:-N1FcBO8-W4hf9MY-DmY:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/f40156342b74184f16677f9592100d955c4d1579/v22.1/satori-integration.md#L33)):*
<details><summary><i>Previously, kathancox (Kathryn Hancox) wrote…</i></summary><blockquote>

Typo: there's an extra parenthesis at the end here. 

This is more of a question, is it likely that users will have to reach out to the support team? I'm not sure what's involved with integrating Satori — wondering if this will lead users to think they need to reach out. But, as I say, I don't know the plan here.
</blockquote></details>

Done.

**Pull request merged**
