### PR TITLE
Providing copy feature for commands

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Providing copy feature for commands

### CODE REVIEW

**Comment by jseldess** [comment]
@NiteshKoushik, first, thank you for all the energy and good will you've invested to make many minor improvements to our documentation. We very much appreciate such contributions from the community. 

However, our Docs team is very busy with documentation efforts for our upcoming release and for other important projects, and so we don't have the time and bandwidth the volume of PRs you've opened. 

If you'd like us to review, respond, and implement your changes, I'd suggest the following to make it more efficient for us:

- Instead of opening a separate PR for each minor change, please group types of changes into less PRs. For example, use a single PR to add all "copy to clipboard" functionality to code blocks that you want to suggest instead of one PR per file, use a single PR to add links, use a single PR to correct spelling mistakes. Grouping your changes like this will make it much easier for us to review and respond to your changes. 
- Also, it'd be great if you could make each change to both the v19.1 and v19.2 versions of the files. v19.1 is our stable version, while v19.2 is our dev version which starts as a clone of v19.1. This too would save us a lot of time. 

Would you be willing to do this? If so, I'll close your PRs and wait for your new PRs with batched changes. 

If you're not willing or able to do this, that's fine, too. In that case, please refrain from opening more PRs and let us review and resolve the ones you've already opened, when we can.

**Comment by NiteshKoushik** [comment]
Sure. I will be working on it.

**Comment by NiteshKoushik** [comment]
@jseldess - Thanks for providing suggestion, going forward I will be taking care and will be working it. For the current PR request you to review and close it.

**Comment by jseldess** [comment]
LGTM

**Pull request merged**
