### PR TITLE
Automate expired version check in SEO

### PR DESCRIPTION
**Pull request by nickvigilante**

### CODE REVIEW

**Comment by jseldess** [comment]
@nickvigilante, thanks for the quick work here, but I can't follow what you've done. Can you please include a more detailed description of the logic and how it works?

**Comment by nickvigilante** [comment]
@jseldess The logic I use here is equivalent to what I already use in `_layouts/page.html`, but I'll expand more on it below:

`{% assign x = site.data.versions | where_exp: "m", "m.major_version == page.version.version" | first %}`
This line queries the information in `versions.csv` and returns the current page's version.

`{% unless x.maint_supp_exp_date == "N/A" or x.asst_supp_exp_date == "N/A" %}`
If the current page version has a maintenance or assistance support expiration date of N/A (meaning it's not yet released), we skip all code inside of the `unless` block.

`{% assign today = "today" | date: "%s" %}`
Fetch today's date and format it in seconds.
`{% assign a = x.asst_supp_exp_date | date: "%s" %}`
Format the assistance support expiration date for the given page version in seconds.

`{% if page.version and a < today %}`
If the page version exists and the assistance support expiration date has passed, include the additional `meta` tags:

  ```
  <meta name="robots" content="noindex">
  <meta name="robots" content="nofollow">
  <meta name="robots" content="noarchive">
  <meta name="robots" content="nocache">
{% endif %}
{% endunless %}
```

**Comment by jseldess** [comment]
That's very helpful. Can you add comments to the code to that effect? I'll check the preview now.

**Review by jseldess — APPROVED** [review]
LGTM!

**Pull request merged**
