### PR TITLE
Corrected localities on partitioning doc

### PR DESCRIPTION
**Pull request by tim-o**
earlier version had inconsistent localities between steps 2 and 5.

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @tim-o! @Amruta-Ranade, can you please review? We'll also want to update the 2.1 version of the page.

**Comment by Amruta-Ranade** [comment]
LGTM! Thanks @tim-o !

**Comment by jseldess** [comment]
Amruta, can you please apply this change to the 2.1 docs in a follow-up or?

**Comment by Amruta-Ranade** [comment]
@jseldess Yes, on it.

**Pull request merged**
