### PR TITLE
Docs for column families

### LINKED ISSUE #423: Column families
Update docs to cover column families. 

RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_column_families.md
Test: https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/family

### PR DESCRIPTION
**Pull request by jseldess**
- Regenerated and adjusted grammar diagrams.
- Added column families to `create-table.md`. 
- Added stand-alone page on column families: `column-families.md`.
- Updated kv faq to mention using column families.

HTML version available here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6545def8fd90b97db710c935cc7322955af9fa4c/

Fixes #423 

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/422)

### CODE REVIEW

**Comment by jseldess** [comment]
@paperstreet, I don't think the story is right yet. Once we define column families by default, I'm inclined to reveal more about that in `column-families.md` and `create-table.md`. But please let me know your thoughts. I know I'm light on details here, and there must be areas I'm missing.

@petermattis

**Comment by paperstreet** [comment]
I think the story is pretty good as you have it. Here's my initial thoughts. I'll do a followup pass and think of what you're missing

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[column-families.md, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIVNqEWtQ6LjeO_M8G:-KLIVNqEWtQ6LjeO_M8H:-609961167) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L9)):*
> ```Markdown
> As of the `beta-20160629` release, CockroachDB supports **column families**. A column family is a group of columns in a table that are stored as a single key-value pair in the underlying key-value layer. Storing column values in this way significantly reduces storage overhead. 
> 
> {{site.data.alerts.callout_info}}Tables created as of <code>beta-20160629</code> are not be compatible with earlier versions of CockroachDB.{{site.data.alerts.end}}
> ```

This is only true if you use the feature, which I feel is an important distinction. If you've upgraded and haven't manually assigned families (even if you've created new tables), you can downgrade

---

*[column-families.md, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIVqdYPDrRrwMSMOax:-KLIVqdZPWvfwJbiigwU:-1927936419) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L15)):*
> ```Markdown
> ## Overview
> 
> When a row is inserted into a table with column families, CockroachDB stores the values for each column family as a single key-value pair. For example, consider a table with 2 columns, where the columns are grouped into a column family:
> ```

single key-value pair per family

---

*[column-families.md, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIW1Mp7SCawmtSVtFL:-KLIW1Mq4dBDdTDyuSvE:-1887274474) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L25)):*
> ```Markdown
> ~~~
> 
> Inserting 10 rows into this table would create 10 underlying key-value pairs, 1 per row. In contrast, if the table's columns were not grouped into a family, each column and value would be a distinct key-value pair; thus, inserting 10 rows would create 20 underlying key-value pairs, 2 per row. 
> ```

I'm not really sure what we're contrasting to. If some competitor, which one? If previous versions of cockroach, this is not technically true, because we'd have an extra +1 per row for a total of 30

---

*[column-families.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIWPA87gUaz9OsAhiY:-KLIWPA9q8kOSdDHN2d5:-1499814179) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L77)):*
> ```Markdown
> ## Upcoming Improvements
> 
> In an upcoming release, you won't need to define column families manually. Instead, CockroachDB will group columns into families for you when a table is created. CockroachDB's default groupings will ensure optimal storage and performance, but you will still have the option to define your own groups using the `FAMILY` keyword, as show above. 
> ```

optimal is far too strong a promise for what is coming : - )

maybe reasonable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422#-:-KLIWg228dsN-UVpujNJ:916787041)*

**Comment by paperstreet** [comment]
Okay this what I could think of that's missing

dt mentions that the "Storage Parameters" section of https://www.postgresql.org/docs/current/static/sql-createtable.html is a good example of the level of emphasis we should be placing on the manual configuration of these. Note that it's fairly buried.

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[column-families.md, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIWyWXNNTTn1HUpYRz:-KLIWyWXNNTTn1HUpYS-:1667580899) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L7)):*
> ```Markdown
> ---
> 
> As of the `beta-20160629` release, CockroachDB supports **column families**. A column family is a group of columns in a table that are stored as a single key-value pair in the underlying key-value layer. Storing column values in this way significantly reduces storage overhead. 
> ```

The even bigger advantage is that it reduces the number of keys you're changing during inserts/updates/deletes, which has all kinds of performance benefits. Less data over the wire, smaller raft and rocksdb logs, fewer write intents to conflict. Basically, this is even a bigger deal for a 3 node setup than a single node.

Maybe " 

---

*[column-families.md, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIXfApj-2IoOrcz1Xp:-KLIXfApj-2IoOrcz1Xq:1421190882) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L52)):*
> ```Markdown
> ~~~
> 
> To group columns into multi-column families, you must use the `FAMILY` keyword, for example:
> ```

I don't think it's clear anywhere that you can specify more than one family. You might want to do this if you have one small column that gets updated a lot and one big column that doesn't. Because of the way families work, if you put both in one family, the big one will have to be rewritten every time the little one is updated. This general issue is why we won't simply always use one family

Important to emphasize: You should always use as few column families as reasonable. Our upcoming heuristic tries to group "bounded-size" columns (INT, TIMESTAMP, STRING(100), etc). Unfortunately, if the user specifies STRING, DECIMAL, BYTES without a max size, we have to be pessimistic and give it its own group. This is the major reason that users should expect to tell cockroach about family assignments. If you know that your STRING (or DECIMAL or BYTES) field will usually be small, but don't want the hard bound on it, then you can use this feature to force them together. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422#-:-KLI_5AYcfWCfvA7smZ-:1643048666)*

**Comment by jseldess** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[column-families.md, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIVNqEWtQ6LjeO_M8G:-KLIXuImY-xxnsRiE4gI:-1570315453) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L9)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> This is only true if you use the feature, which I feel is an important distinction. If you've upgraded and haven't manually assigned families (even if you've created new tables), you can downgrade
</details>
Oh, right. I guess this statement will be true once we define families by default. I've revised the note for now. Look ok now?

---

*[column-families.md, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIVqdYPDrRrwMSMOax:-KLI_6ZlA-znSK-gS8Gq:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L15)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> single key-value pair per family
</details>
Done.

---

*[column-families.md, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIW1Mp7SCawmtSVtFL:-KLIaYKckO7opsJE4-WH:734617807) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L25)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I'm not really sure what we're contrasting to. If some competitor, which one? If previous versions of cockroach, this is not technically true, because we'd have an extra +1 per row for a total of 30
</details>
OK, refined this to contrast to earlier versions of cockroach. Let me know if you don't think this is useful.

---

*[column-families.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIWPA87gUaz9OsAhiY:-KLIalS4iGgwc7rcVAh6:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L77)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> optimal is far too strong a promise for what is coming : - )
> 
> maybe reasonable
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422)*

**Comment by jseldess** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[column-families.md, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIWyWXNNTTn1HUpYRz:-KLIlLG20PZXiygWhjLZ:1939409817) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L7)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> The even bigger advantage is that it reduces the number of keys you're changing during inserts/updates/deletes, which has all kinds of performance benefits. Less data over the wire, smaller raft and rocksdb logs, fewer write intents to conflict. Basically, this is even a bigger deal for a 3 node setup than a single node.
> 
> Maybe " 
</details>
Revised a bit. Let me know if you want more detail still. 

---

*[column-families.md, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIXfApj-2IoOrcz1Xp:-KLIrDXVzQRROL76ofmh:-1354941326) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L52)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I don't think it's clear anywhere that you can specify more than one family. You might want to do this if you have one small column that gets updated a lot and one big column that doesn't. Because of the way families work, if you put both in one family, the big one will have to be rewritten every time the little one is updated. This general issue is why we won't simply always use one family
> 
> Important to emphasize: You should always use as few column families as reasonable. Our upcoming heuristic tries to group "bounded-size" columns (INT, TIMESTAMP, STRING(100), etc). Unfortunately, if the user specifies STRING, DECIMAL, BYTES without a max size, we have to be pessimistic and give it its own group. This is the major reason that users should expect to tell cockroach about family assignments. If you know that your STRING (or DECIMAL or BYTES) field will usually be small, but don't want the hard bound on it, then you can use this feature to force them together. 
</details>
I added a "Column Family Recommendations" section to cover some of this. For now, though, I'm leaving out the details connected to our heuristics. I can put those in later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422)*

**Comment by paperstreet** [comment]
just a last couple notes

---

Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[column-families.md, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIXfApj-2IoOrcz1Xp:-KLMRqOcycUw4X14bQ0S:51341534) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L52)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> I added a "Column Family Recommendations" section to cover some of this. For now, though, I'm leaving out the details connected to our heuristics. I can put those in later.
</details>
Agreed that we don't need the heuristics yet. I do think it's important to specify in which circumstances you'd need to hint to cockroach about family assignments. The most common one will be a STRING (or DECIMAL or BYTES) field that has no declared limit, but you know it will be small. Cockroach has to be pessimistic (maybe it will be huge, how do we know) but if you know otherwise, the override will be beneficial.

For example
    CREATE TABLE users (id SERIAL PRIMARY KEY, name STRING, address STRING)

name and address with both be small enough that this should all be one family

---

*[column-families.md, line 74 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLMRAm1xeKOgY35HCpg:-KLMRAm1xeKOgY35HCph:678005523) ([raw file](https://github.com/cockroachdb/docs/blob/7897c692b835e103604554a06eb534d407568179/column-families.md#L74)):*
> ```Markdown
> | Table |                CreateTable                 |
> +-------+--------------------------------------------+
> | t30   | CREATE TABLE t30 (␤                        |
> ```

t30?

---

*[column-families.md, line 87 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLMRTqtIBIeLTObzyc9:-KLMRTqu-NT3Gsat4DSo:2099359663) ([raw file](https://github.com/cockroachdb/docs/blob/7897c692b835e103604554a06eb534d407568179/column-families.md#L87)):*
> ```Markdown
> ~~~
> 
> ## Column Family Recommendations
> ```

I only just remembered one more restriction on family assignments. Primary index columns must be placed in the first listed family (family #0).

    > create table foo (a int primary key, b int, family (b), family (a));
    pq: primary key column 1 is not in column family 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422#-:-KLMSg1OTD6IoCgqXo7w:1701446269)*

**Comment by jseldess** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[column-families.md, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLIXfApj-2IoOrcz1Xp:-KLMlw083ZaP4YtwjMHf:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/bdba3cb29eaccd555d61434d57d50eaf1e001bb1/column-families.md#L52)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Agreed that we don't need the heuristics yet. I do think it's important to specify in which circumstances you'd need to hint to cockroach about family assignments. The most common one will be a STRING (or DECIMAL or BYTES) field that has no declared limit, but you know it will be small. Cockroach has to be pessimistic (maybe it will be huge, how do we know) but if you know otherwise, the override will be beneficial.
> 
> For example
>     CREATE TABLE users (id SERIAL PRIMARY KEY, name STRING, address STRING)
> 
> name and address with both be small enough that this should all be one family
</details>
Done.

---

*[column-families.md, line 74 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLMRAm1xeKOgY35HCpg:-KLMXHMQfxn9yL83ytF3:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/7897c692b835e103604554a06eb534d407568179/column-families.md#L74)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> t30?
</details>
Done.

---

*[column-families.md, line 87 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/docs/422#-KLMRTqtIBIeLTObzyc9:-KLMg-MBn9p_csI1UWs0:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/7897c692b835e103604554a06eb534d407568179/column-families.md#L87)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I only just remembered one more restriction on family assignments. Primary index columns must be placed in the first listed family (family #0).
> 
>     > create table foo (a int primary key, b int, family (b), family (a));
>     pq: primary key column 1 is not in column family 0
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/422#-:-KLMvr0zcQJqEVfyWpHI:1417088721)*

**Pull request merged**
