### PR TITLE
Use jekyll-include-cache

### LINKED ISSUE #9928: Jekyll serve --incremental is very slow, making a live edit workflow very difficult
It takes over 30 seconds to see one edit to a page go live.  This is slow enough that it makes the incremental "write-and-check, write-and-check" style of working very difficult and frustrating.

Running as:

```
bundle exec jekyll serve --port 4000 --incremental --trace --config _config_base.yml,_config_cockroachdb.yml
```

The performance on a brand new MBP with 1TB SSD and 16 GB RAM is ... very bad.  As shown below I am making small edits to one file and it takes 30+ seconds to show me the changes.

```
      Regenerating: 1 file(s) changed at 2021-03-04 10:36:24
                    v21.1/set-locality.md
                    ...done in 32.932964 seconds.
                    
      Regenerating: 1 file(s) changed at 2021-03-04 10:36:57
                    v21.1/set-locality.md
                    ...done in 32.305148 seconds.
                    
      Regenerating: 2 file(s) changed at 2021-03-04 10:39:43
                    v21.1/set-locality.md
                    v21.1/.#set-locality.md
                    ...done in 33.882001 seconds.
                    
      Regenerating: 1 file(s) changed at 2021-03-04 10:40:17
                    v21.1/set-locality.md
                    ...done in 33.165183 seconds.
                    
      Regenerating: 2 file(s) changed at 2021-03-04 10:41:10
                    v21.1/set-locality.md
                    v21.1/.#set-locality.md
                    ...done in 31.34292 seconds.
```

Possibly related old issues:

- #1716
- #2941 

Seems like it would be fixed by:

- #4959

### PR DESCRIPTION
**Pull request by yingzhuchin**
This should slightly improve build speed, but there's also slowdown due to `remote_include` that isn't as easily addressed.

Partially fixes #9928 

This change pulls in https://github.com/benbalter/jekyll-include-cache. From the description:

"If you have a computationally expensive include (such as a sidebar or navigation), Jekyll Include Cache renders the include once, and then reuses the output any time that includes is called with the same arguments, potentially speeding up your site's build significantly."

### CODE REVIEW

**Comment by yingzhuchin** [comment]
With this change, TeamCity build generation now takes 80+ seconds, whereas before it took 100+ seconds.

**Comment by yingzhuchin** [comment]
On further thought, it's overzealous/unnecessary to replace *all* instances of `include`, especially for things like `include_cached copy-clipboard.html`. I'll attempt a second pass that's smarter instead of just blanket replacement.

**Review by rmloveland — APPROVED** [review]
LGTM, thanks YZ!

This appears to speed things up by about 30% (33s -> 24s) in my very unscientific testing just now :-) 

```
make standard
bundle exec jekyll serve --port 4000 --incremental --trace --config _config_base.yml,_config_cockroachdb.yml,_config_cockroachdb_local.yml 
Configuration file: /Users/rloveland/work/code/docs/_config_base.yml
Configuration file: /Users/rloveland/work/code/docs/_config_cockroachdb.yml
Configuration file: /Users/rloveland/work/code/docs/_config_cockroachdb_local.yml
            Source: /Users/rloveland/work/code/docs
       Destination: /Users/rloveland/work/code/docs/_site/docs
 Incremental build: enabled
      Generating... 
                    done in 35.663 seconds.
 Auto-regeneration: enabled for '/Users/rloveland/work/code/docs'
    Server address: http://127.0.0.1:4000/docs/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2021-03-17 10:11:54
                    v21.1/spatial-tutorial.md
                    ...done in 26.824129 seconds.
                    
      Regenerating: 2 file(s) changed at 2021-03-17 10:12:21
                    v21.1/spatial-tutorial.md
                    v21.1/.#spatial-tutorial.md
                    ...done in 26.905892 seconds.
                    
      Regenerating: 2 file(s) changed at 2021-03-17 10:12:57
                    v21.1/spatial-tutorial.md
                    v21.1/.#spatial-tutorial.md
                    ...done in 22.116522 seconds.
                    
      Regenerating: 2 file(s) changed at 2021-03-17 10:13:24
                    v21.1/spatial-tutorial.md
                    v21.1/.#spatial-tutorial.md
                    ...done in 24.225246 seconds.
 ```

**Comment by jseldess** [comment]
This seems to speed up the incremental build for me even more than for @rmloveland:

```
JesseS’s-MacBook-Pro:docs jesseseldess$ make standard
bundle exec jekyll serve --port 4000 --incremental --trace --config _config_base.yml,_config_cockroachdb.yml,_config_cockroachdb_local.yml
Configuration file: /Users/jesseseldess/go/src/github.com/cockroachdb/docs/_config_base.yml
Configuration file: /Users/jesseseldess/go/src/github.com/cockroachdb/docs/_config_cockroachdb.yml
Configuration file: /Users/jesseseldess/go/src/github.com/cockroachdb/docs/_config_cockroachdb_local.yml
            Source: /Users/jesseseldess/go/src/github.com/cockroachdb/docs
       Destination: /Users/jesseseldess/go/src/github.com/cockroachdb/docs/_site/docs
 Incremental build: enabled
      Generating...
                    done in 27.895 seconds.
 Auto-regeneration: enabled for '/Users/jesseseldess/go/src/github.com/cockroachdb/docs'
    Server address: http://127.0.0.1:4000/docs/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2021-03-17 11:47:02
                    v21.1/add-column.md
                    ...done in 9.059219 seconds.

      Regenerating: 1 file(s) changed at 2021-03-17 11:47:19
                    v21.1/add-column.md
                    ...done in 8.368137 seconds.
```

**Review by jseldess — APPROVED** [review]

**Comment by jseldess** [comment]
LGTM once the conflict is resolved.

**Comment by yingzhuchin** [comment]
> LGTM, thanks YZ!
> 
> This appears to speed things up by about 30% (33s -> 24s) in my very unscientific testing just now :-)
> 
> ```
> make standard
> bundle exec jekyll serve --port 4000 --incremental --trace --config _config_base.yml,_config_cockroachdb.yml,_config_cockroachdb_local.yml 
> Configuration file: /Users/rloveland/work/code/docs/_config_base.yml
> Configuration file: /Users/rloveland/work/code/docs/_config_cockroachdb.yml
> Configuration file: /Users/rloveland/work/code/docs/_config_cockroachdb_local.yml
>             Source: /Users/rloveland/work/code/docs
>        Destination: /Users/rloveland/work/code/docs/_site/docs
>  Incremental build: enabled
>       Generating... 
>                     done in 35.663 seconds.
>  Auto-regeneration: enabled for '/Users/rloveland/work/code/docs'
>     Server address: http://127.0.0.1:4000/docs/
>   Server running... press ctrl-c to stop.
>       Regenerating: 1 file(s) changed at 2021-03-17 10:11:54
>                     v21.1/spatial-tutorial.md
>                     ...done in 26.824129 seconds.
>                     
>       Regenerating: 2 file(s) changed at 2021-03-17 10:12:21
>                     v21.1/spatial-tutorial.md
>                     v21.1/.#spatial-tutorial.md
>                     ...done in 26.905892 seconds.
>                     
>       Regenerating: 2 file(s) changed at 2021-03-17 10:12:57
>                     v21.1/spatial-tutorial.md
>                     v21.1/.#spatial-tutorial.md
>                     ...done in 22.116522 seconds.
>                     
>       Regenerating: 2 file(s) changed at 2021-03-17 10:13:24
>                     v21.1/spatial-tutorial.md
>                     v21.1/.#spatial-tutorial.md
>                     ...done in 24.225246 seconds.
> ```

Hi Rich, thanks for testing it out! Glad to see there's some improvement. One quick thing: Can you delete the `.XXX.md` temp files and see if that helps? Seems like your build might be doing double work?

**Comment by ianjevans** [comment]
FWIW, here's my output when adding `--profile`.

```
Build Process Summary:

| PHASE      |    TIME |
+------------+---------+
| RESET      |  0.0002 |
| READ       |  2.4739 |
| GENERATE   |  0.9628 |
| RENDER     | 39.2196 |
| CLEANUP    |  0.0483 |
| WRITE      |  3.4468 |
+------------+---------+
| TOTAL TIME | 46.1516 |


Site Render Stats:

| Filename                                                | Count |      Bytes |   Time |
+---------------------------------------------------------+-------+------------+--------+
| v21.1/build-a-spring-app-with-cockroachdb-jpa.md        |     1 |     69.28K |  1.605 |
| sitemap.xml                                             |     1 |    274.76K |  1.536 |
| _layouts/default.html                                   |  3143 | 433341.65K |  1.088 |
| v1.0/functions-and-operators.md                         |     1 |      2.62K |  1.052 |
| v20.2/build-a-spring-app-with-cockroachdb-mybatis.md    |     1 |     56.75K |  1.005 |
| v21.1/build-a-spring-app-with-cockroachdb-mybatis.md    |     1 |     56.75K |  0.994 |
| v1.1/functions-and-operators.md                         |     1 |      2.95K |  0.960 |
| _layouts/page.html                                      |  3142 | 110011.71K |  0.919 |
| v21.1/build-a-spring-app-with-cockroachdb-jdbc.md       |     1 |     96.22K |  0.880 |
| v20.2/build-a-spring-app-with-cockroachdb-jdbc.md       |     1 |     96.23K |  0.814 |
| v20.2/build-a-spring-app-with-cockroachdb-jpa.md        |     1 |     69.28K |  0.716 |
| v20.1/functions-and-operators.md                        |     1 |    303.01K |  0.360 |
| v2.1/functions-and-operators.md                         |     1 |    241.52K |  0.353 |
| v19.2/functions-and-operators.md                        |     1 |    257.32K |  0.347 |
| v21.1/functions-and-operators.md                        |     1 |    542.60K |  0.345 |
| v20.2/functions-and-operators.md                        |     1 |    480.04K |  0.345 |
| v19.1/functions-and-operators.md                        |     1 |    251.28K |  0.331 |
| v21.1/build-a-python-app-with-cockroachdb-django.md     |     1 |     37.90K |  0.271 |
| v20.2/build-a-python-app-with-cockroachdb-django.md     |     1 |     37.89K |  0.255 |
| v2.0/functions-and-operators.md                         |     1 |    179.48K |  0.244 |
| v21.1/build-a-ruby-app-with-cockroachdb.md              |     1 |     19.47K |  0.180 |
| _includes/copy-clipboard.html                           | 30132 |  18567.67K |  0.180 |
| v21.1/build-a-ruby-app-with-cockroachdb-activerecord.md |     1 |     21.69K |  0.176 |
| v20.2/build-a-ruby-app-with-cockroachdb.md              |     1 |     19.47K |  0.167 |
| v20.2/build-a-ruby-app-with-cockroachdb-activerecord.md |     1 |     21.69K |  0.162 |
| v21.1/build-a-java-app-with-cockroachdb.md              |     1 |     44.73K |  0.116 |
| v20.2/build-a-go-app-with-cockroachdb.md                |     1 |     20.52K |  0.101 |
| v20.1/build-a-python-app-with-cockroachdb.md            |     1 |     16.12K |  0.097 |
| v20.2/build-a-java-app-with-cockroachdb-hibernate.md    |     1 |     34.24K |  0.097 |
| v2.1/cluster-settings.md                                |     1 |     17.11K |  0.096 |
| v20.2/build-a-nodejs-app-with-cockroachdb.md            |     1 |     19.86K |  0.096 |
| v20.2/build-a-python-app-with-cockroachdb.md            |     1 |     24.35K |  0.093 |
| v21.1/build-a-go-app-with-cockroachdb.md                |     1 |     20.52K |  0.092 |
| v21.1/cluster-settings.md                               |     1 |     23.86K |  0.092 |
| v20.2/cluster-settings.md                               |     1 |     21.56K |  0.087 |
| v21.1/build-a-python-app-with-cockroachdb.md            |     1 |     24.35K |  0.086 |
| v19.1/cluster-settings.md                               |     1 |     27.19K |  0.085 |
| v20.1/build-a-nodejs-app-with-cockroachdb-sequelize.md  |     1 |     11.22K |  0.084 |
| v20.1/cluster-settings.md                               |     1 |     16.86K |  0.084 |
| v21.1/build-a-nodejs-app-with-cockroachdb.md            |     1 |     19.86K |  0.082 |
| v21.1/build-a-java-app-with-cockroachdb-hibernate.md    |     1 |     34.25K |  0.079 |
| v20.2/build-a-go-app-with-cockroachdb-pq.md             |     1 |     20.31K |  0.079 |
| v21.1/build-a-nodejs-app-with-cockroachdb-sequelize.md  |     1 |     17.78K |  0.078 |
| v21.1/build-a-go-app-with-cockroachdb-gorm.md           |     1 |     20.38K |  0.078 |
| v21.1/build-a-go-app-with-cockroachdb-pq.md             |     1 |     20.31K |  0.077 |
| v20.2/build-a-java-app-with-cockroachdb.md              |     1 |     44.74K |  0.076 |
| v20.2/build-a-nodejs-app-with-cockroachdb-sequelize.md  |     1 |     17.78K |  0.076 |
| v20.2/build-a-go-app-with-cockroachdb-gorm.md           |     1 |     20.38K |  0.076 |
| v19.2/cluster-settings.md                               |     1 |     29.44K |  0.071 |
| v20.1/build-a-nodejs-app-with-cockroachdb.md            |     1 |     13.30K |  0.063 |
+---------------------------------------------------------+-------+------------+--------+
| TOTAL (for 50 files)                                    | 36464 | 565640.26K | 17.427 |

                    done in 46.196 seconds.
```

**Comment by yingzhuchin** [comment]
Thanks @rmloveland and @jseldess for validating the changes! Would you be able to test again with the latest on branch? Fingers crossed for a bit more improvement.

**Comment by yingzhuchin** [comment]
Thanks for the output, @ianjevans! It does look like a lot of pages that use `remote_include` to me.

**Comment by rmloveland** [comment]
yingzhuchin ***@***.***> writes:

> Hi Rich, thanks for testing it out! Glad to see there's some
> improvement. One quick thing: Can you delete the .XXX.md temp files
> and see if that helps? Seems like your build might be doing double
> work?

I think you are right - Emacs is auto-creating these .XXX.md temp save
files and then really quickly deleting them when I actually save my
edited file.  So I never see them because they disappear but Jekyll's
file watcher must be seeing them!

So in other words my build is slow and it's kinda my own fault. But I
thank you for speeding things up for me anyway! :-}

**Comment by yingzhuchin** [comment]
Thanks Rich! Merging.

**Pull request merged**
