### PR TITLE
Create node.js code sample

### PR DESCRIPTION
**Pull request by nvanbenschoten**
Also @mrtracy

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/141)

### CODE REVIEW

**Comment by tamird** [comment]
looks OK to me but thank christ I don't use this stuff every day

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_aPDR9B4KuG9rlDv-:-KD_aPDR9B4KuG9rlDv0:-1871367787) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L6)):*
generally gone a little overboard with the comments

---

*[_includes/app/basic-sample.js, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_aWphTbzvLpmo_3wD:-KD_aWphTbzvLpmo_3wE:-461705272) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L24)):*
magic

---

*[_includes/app/basic-sample.js, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_akg9TjomYvhcG9j0:-KD_akg9TjomYvhcG9j1:122912573) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L31)):*
wtf bro no placeholders?

---

*[_includes/app/basic-sample.js, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_aa5-xKLyN2muoajs:-KD_aa5-xKLyN2muoajt:-621944486) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L40)):*
throughout: either log the naked error or add the statement you tried to execute. probably worth looking at the the kinds of errors this yields

---

*[_includes/app/basic-sample.js, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_bDOrSoBCWi-q7BIy:-KD_bDOrSoBCWi-q7BIz:-2078459510) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L48)):*
this style of callback passing and piping is insane to read. surely there is a better style

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/141#-:-KD_bLpvYzk27hh4gIod:1771926945)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_akg9TjomYvhcG9j0:-KD_f20rDyXWTK9bDZ84:-1056166727) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L31)):*
Assuming node allows them, I would also suggest using placeholders.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/141)*

**Comment by nvanbenschoten** [comment]
Thanks for the reviews, and welcome to the wonderful world of asynchronicity and callback hell!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_aPDR9B4KuG9rlDv-:-KDaYsySIOVHsdC3eEPe:93887135) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L6)):*
You think so? For an example app?

---

*[_includes/app/basic-sample.js, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_aWphTbzvLpmo_3wD:-KDaYvbaDctetx7_Hymy:1939496621) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L24)):*
Waterfalls are always magical

---

*[_includes/app/basic-sample.js, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_akg9TjomYvhcG9j0:-KDaZ2LC4S-oA9Ozf3ZZ:-1555819779) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L31)):*
Completely agree, although I was trying to stick to https://www.cockroachlabs.com/docs/build-a-test-app.html as closely as possible. Should we go back and make sure all examples are using placeholders for values?

---

*[_includes/app/basic-sample.js, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_aa5-xKLyN2muoajs:-KDaZSuifDFaaqbv6Ruz:1562307518) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L40)):*
This stye is actually pretty common for Node. See https://www.npmjs.com/package/pg. The errors are full objects so they provide a good amount of context.

---

*[_includes/app/basic-sample.js, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/141#-KD_bDOrSoBCWi-q7BIy:-KDaZfAwC4So94XNYyAD:434855288) ([raw file](https://github.com/cockroachdb/docs/blob/f6c39bf3d9f1a42143b62231e742ce655c21ed7d/_includes/app/basic-sample.js#L48)):*
[17,000 stars](https://github.com/caolan/async) and the [third most used](https://www.npmjs.com/browse/star) library would seem to argue otherwise. Go doesn't seem so bad now, does it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/141#-:-KDaYryS6PWaeH3NVJ5I:1307160284)*

**Comment by jseldess** [comment]
Can't authenticate in reviewable right now. So my 2 cents here.

Maybe just put `// Connect to the cluster.` before the variable declaration and get rid of `// Construct a connection configuration`?

If you all think we should be using placeholders in all example, we should do that. @spencerkimball, your opinion?

**Comment by nvanbenschoten** [comment]
@jseldess Done.

**Comment by jseldess** [comment]
Thanks, @nvanbenschoten. As discussed, once @andreimatei's samples are merged in, you can open another PR to adjust this basic sample and create a transaction-focused sample.

**Pull request merged**
