### PR TITLE
CONVERT TO SCHEMA docs

### LINKED ISSUE #8318: sql: introduce a command to convert a database into a schema
PR: https://github.com/cockroachdb/cockroach/pull/52997

From release notes:
> Users can now convert existing databases into schemas under other databases through the `ALTER DATABASE ... CONVERT TO SCHEMA UNDER PARENT ...` command. This command can only be run by `admin` and is only valid for databases that don't already have any child schemas other than `public`. [#52997][#52997] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8348: sql: miscellaneous fixes to the `CONVERT TO SCHEMA` command
PR: https://github.com/cockroachdb/cockroach/pull/53564

From release notes:
> Disallowed the `CONVERT TO SCHEMA` command on the current database. [#53564][#53564] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #8348. 
Fixes #8318. 

- Added `CONVERT TO SCHEMA` docs page, with example.
- Added misc links to `CONVERT TO SCHEMA` page.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I feel like this page could use with some prose explaining why this operation exists. Namely that it exists to help transition from the 20.1 and earlier world when there were no user-defined schemas to the 20.2+ world which is more postgres compatible. I'm a little bit worried that we don't generally have any docs about the namespace hierarchy. I'm going to loop in @vy-ton on this to see what she thinks would be the right amount of initial documentation. 

The content itself seems good! Happy to move the follow-up to another place. Let me know what you think. 

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8486#-:-MIP-boqD9hPzw6tCQzu:b-sjhvbu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ericharmeling — COMMENTED** [review]
Thanks for reviewing, @ajwerner!

We do have a page about namespace resolution that goes into more detail about the namespace hierarchy: https://www.cockroachlabs.com/docs/dev/sql-name-resolution.html
Perhaps we should add a paragraph at the top of the `CONVERT TO SCHEMA` page that links to the the [Logical schemas and namespaces](https://www.cockroachlabs.com/docs/dev/sql-name-resolution.html#logical-schemas-and-namespaces) section of that page? 

Also, @awoods187 opened a related docs issue about improving this page: https://github.com/cockroachdb/docs/issues/7272
I'm in favor of folding any additional improvements/clarifications on the CRDB namespace hierarchy into a separate PR that addresses the point you bring up in your comment here, and resolves Andy's issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8486#-:-MIPEmBy1JKRHK3UHPXD:bi760jq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ericharmeling** [comment]
@ajwerner 
Just added a note (see latest commit). Let me know what you think.

**Review by ajwerner — APPROVED** [review]
That all sgtm. Thanks!

:lgtm: 

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8486#-:-MIQWaiQ0qsNcrHmNN9F:b-4qbbte)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ericharmeling** [comment]
TFTR @ajwerner !

FYI: #8493

**Comment by vy-ton** [comment]
> I'm in favor of folding any additional improvements/clarifications on the CRDB namespace hierarchy into a separate PR that addresses the point you bring up in your comment here, and resolves Andy's issue.

This sgtm. I'll be working on a blog post for SQL updates in 20.2 and can link out to these docs in our narrative.

**Review by lnhsingh — COMMENTED** [review]
One suggestion (take it or leave it) but otherwise :lgtm: !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8486#-:-MIUmT114AzQRAdR4Kjn:b5ycf6h)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v20.2/convert-to-schema.md, line 29 at r2](https://reviewable.io/reviews/cockroachdb/docs/8486#-MIUiIzx5qRvWEUY9yt_:-MIUiIzx5qRvWEUY9yta:bafcleq) ([raw file](https://github.com/cockroachdb/docs/blob/d33449c3e06295b9984ff8f1a97862a11c858fc4/v20.2/convert-to-schema.md#L29)):*
> ```Markdown
> Parameter | Description
> ----------|------------
> `name` | The first instance of `name` specifies the name of the database to convert. The second instance of `name` specifies the name of the parent database to which the new schema will belong.
> ```

Suggestion: Break this into two lines (and make the `name` placeholders in the statement unique. So first would be `name` and second might be `parent_name`. I'll leave this up to you though-- I think it currently works as is, but might be a little easier to read if you split it.

**Review by ericharmeling — COMMENTED** [review]
TFTR @lnhsingh !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8486#-:-MIVle4M1UWz4PG7TmLn:bhjhpnt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @lnhsingh)

___
*[v20.2/convert-to-schema.md, line 29 at r2](https://reviewable.io/reviews/cockroachdb/docs/8486#-MIUiIzx5qRvWEUY9yt_:-MIVk1JdARIV33HAStI8:b-2bhsz7) ([raw file](https://github.com/cockroachdb/docs/blob/d33449c3e06295b9984ff8f1a97862a11c858fc4/v20.2/convert-to-schema.md#L29)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggestion: Break this into two lines (and make the `name` placeholders in the statement unique. So first would be `name` and second might be `parent_name`. I'll leave this up to you though-- I think it currently works as is, but might be a little easier to read if you split it.
</blockquote></details>

Good idea. Done.

FYI, this syntax format is copied from the help text for this statement. If we end up automating how we populate syntax (i.e., pull from the help text in `sql.y`), this sort of improvement will be difficult to make without manual intervention (or work on the part of docs on the source help text).

**Pull request merged**
