### PR TITLE
Update commands to work as designed.

### PR DESCRIPTION
**Pull request by DBarney**
Missing backslash causes command to not background correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1465)

### CODE REVIEW

**Comment by benesch** [comment]
Nice catch, @DBarney, and thanks for the fix! Much appreciated.

**Comment by DBarney** [comment]
No problem, I was busy going through the docs trying things out when those two commands hung. Figured I should fix it if no one else already had.

**Comment by jseldess** [comment]
Yes, thanks very much, @DBarney! Merging now. But I'm curious. Did you use the on-page **Contribute > Edit This Page** option to make this change?

**Comment by DBarney** [comment]
I did actually, I was prepared to fork the repo and do it on my machine, but saw the option and decided to try it out. It was actually pretty slick!

**Comment by jseldess** [comment]
Very nice to hear! Thanks, @DBarney.

**Pull request merged**
