### PR TITLE
Restructured LIMIT/OFFSET page

### LINKED ISSUE #6735: sql: fix SQL:2008 FETCH FIRST syntax to allow parameters
PR: https://github.com/cockroachdb/cockroach/pull/45112

From release notes:
> The SQL:2008 syntax `OFFSET <x> ROWS` and `FETCH FIRST <y> ROWS ONLY` now accept parameter values. [#45112][#45112] {% comment %}doc{% endcomment %}

### LINKED ISSUE #6961: release-19.2: sql: fix SQL:2008 FETCH FIRST syntax to allow parameters
PR: https://github.com/cockroachdb/cockroach/pull/45166

From release notes:
> The SQL:2008 syntax `OFFSET <x> ROWS` and `FETCH FIRST <y> ROWS ONLY` now accepts parameter values. [#45166][#45166] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #6735. 
Fixes #6961. 

- Removed limit_clause and offset_clause diagrams.
- Restructured the LIMIT/OFFSET page for clarity.

I'm not sure we need to explicitly document that `OFFSET <x> ROWS` and `FETCH FIRST <y> ROWS ONLY` now accept signed values, but if you disagree, please say so.

### CODE REVIEW

**Review by nvanbenschoten — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8727#-:-MKBkW73ATLpBwspcUdC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v19.2/limit-offset.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8727#-MKBkBrl0oNuRBvhl7O_:-MKBkBrl0oNuRBvhl7Oa:b-1zqn01) ([raw file](https://github.com/cockroachdb/docs/blob/0f19ef94f74af67ff4b979ae5a79d4cd819af61b/v19.2/limit-offset.md#L13)):*
> ```Markdown
> 
> 
> `OFFSET` restricts the operation to skip a specified number of rows. It is often used in conjunction with `LIMIT` to "paginate" through retrieved rows.
> ```

Is "restricts" the right word? Or "instructs"?

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8727)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[v19.2/limit-offset.md, line 13 at r1](https://reviewable.io/reviews/cockroachdb/docs/8727#-MKBkBrl0oNuRBvhl7O_:-MKBxE4p7cP6v_d3Krsb:bv65prg) ([raw file](https://github.com/cockroachdb/docs/blob/0f19ef94f74af67ff4b979ae5a79d4cd819af61b/v19.2/limit-offset.md#L13)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is "restricts" the right word? Or "instructs"?
</blockquote></details>

Yeah that's way better. Done. Thanks!

**Review by nvanbenschoten — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8727#-:-MKCEs-3BgC1BSh_jt0f:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh and @nvanbenschoten)

**Review by lnhsingh — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8727#-:-MKGDPkJ0wCRtaTnHxUz:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @lnhsingh and @nvanbenschoten)

**Pull request merged**
