### PR TITLE
Release notes for beta-20160616

### PR DESCRIPTION
**Pull request by bdarnell**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/391)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM

**Comment by jseldess** [comment]
:lgtm:. I can update the h2 date when I add links and doc updates, if you like.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[beta-20160616.md, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/391#-KKOWIpls5VaTVTF_PXF:-KKOWIpls5VaTVTF_PXG:1280669653) ([raw file](https://github.com/cockroachdb/docs/blob/79045b6f42e1963b6e21fc23e8f609f5bae0cbac/beta-20160616.md#L6)):*
> ```Markdown
> ---
> 
> ## Jun 9, 2016
> ```

June 16, 2016

---

*[beta-20160616.md, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/391#-KKOWbwa3uGeJKrzigab:-KKOWbwa3uGeJKrzigac:514956122) ([raw file](https://github.com/cockroachdb/docs/blob/79045b6f42e1963b6e21fc23e8f609f5bae0cbac/beta-20160616.md#L14)):*
In the zone config docs, we currently say: 

> Each zone can also contain `range_min_bytes` and `ttlseconds` fields, but the former is not yet implemented and the latter is not yet useful.

Is it time to properly document these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/391#-:-KKOX4PKRfZ2rBtPAhuu:-743280267)*

**Comment by jseldess** [comment]
*[beta-20160616.md, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/391#-KKOXCmjGXrMMyztjpbl:-KKOXCmjGXrMMyztjpbm:-638955371) ([raw file](https://github.com/cockroachdb/docs/blob/79045b6f42e1963b6e21fc23e8f609f5bae0cbac/beta-20160616.md#L2)):*
> ```Markdown
> ---
> title: What's New in beta-20160609
> ```

in beta-20160616

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/391)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[beta-20160616.md, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/391#-KKOXCmjGXrMMyztjpbl:-KKOjXOy_HrWNpIXp0aH:-1239943180) ([raw file](https://github.com/cockroachdb/docs/blob/79045b6f42e1963b6e21fc23e8f609f5bae0cbac/beta-20160616.md#L2)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> in beta-20160616
</details>
Oops. I'll let you get this in your followup PR.

---

*[beta-20160616.md, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/391#-KKOWbwa3uGeJKrzigab:-KKOjYRzLfw3W11BCI6-:-980299912) ([raw file](https://github.com/cockroachdb/docs/blob/79045b6f42e1963b6e21fc23e8f609f5bae0cbac/beta-20160616.md#L14)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> In the zone config docs, we currently say: 
> 
> > Each zone can also contain `range_min_bytes` and `ttlseconds` fields, but the former is not yet implemented and the latter is not yet useful.
> 
> Is it time to properly document these?
</details>
`range_min_bytes` is still unimplemented, but I guess it's time to document `ttlseconds`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/391)*

**Pull request merged**
