### PR TITLE
Recommended production settings

### LINKED ISSUE #53: Document recommended ulimit/sysctl settings
Many deployments will need to increase the file descriptor limit, and possibly other ulimit settings. This is true of large deployments on linux and even small ones on OSX. We should have a document explaining this along with other recommended system-level settings. 

For comparison, https://docs.datastax.com/en/cassandra/2.0/cassandra/install/installRecommendSettings.html

### PR DESCRIPTION
**Pull request by jseldess**
This PR adds a page with cluster topology, clock synchronization, and file descriptor limit recommendations for production deployments. 

This aims to fix #53 and is a start for #436.

HTTP version available here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7ccfa14b230bce596d6aaa73ccc78761ea1e015c/recommended-production-settings.html

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/449)

### CODE REVIEW

**Comment by jseldess** [comment]
@BramGruneir, as you'll see, the **File Descriptor Limit** section is very light right now. I need your help conveying the appropriate limits and context. 

@bdarnell, are there other limits or recommendations we should add to this page?

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[recommended-production-settings.md, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/449#-KM_HOjkrZ_YzLyO-Ywa:-KM_HOjkrZ_YzLyO-Ywb:-985185158) ([raw file](https://github.com/cockroachdb/docs/blob/7ccfa14b230bce596d6aaa73ccc78761ea1e015c/recommended-production-settings.md#L13)):*
> ```Markdown
> ## Cluster Topology
> 
> Put each node on a different machine. Since CockroachDB [replicates](configure-replication-zones.html) across nodes, placing more than one node on a single machine increases the risk of data unavailability when a machine fails.
> ```

This is true, but simplistic. "Put each node on a different machine" will sound very obvious to most of our target audience. Try this instead: "Run one node per machine. If a machine has multiple disks or SSDs, it's better to run one node with multiple store flags instead of one node per disk, because this informs CockroachDB about the relationship between the stores and ensures that data will be replicated across different machines instead of being assigned to different disks of the same machine."

---

*[recommended-production-settings.md, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/449#-KM_HDTJG6dyKGyDOXTO:-KM_HDTJG6dyKGyDOXTP:291538933) ([raw file](https://github.com/cockroachdb/docs/blob/7ccfa14b230bce596d6aaa73ccc78761ea1e015c/recommended-production-settings.md#L21)):*
> ```Markdown
> ## File Descriptor Limit (Max Open Files)
> 
> For each CockroachDB node, the max file descriptor limit must be at least XXX. If the limit is below this threshold, the node will fail. 
> ```

The minimum is 512 (the node will fail to start if this minimum is not available), but the recommendation is at least 10000. (it's actually 5000 + 5000 * number of stores per node).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/449)*

**Comment by jseldess** [comment]
Would like to merge this now to have the page in place for this week's release notes. I'll open a separate PR with explicit instructions for increasing the file descriptor limit per OS.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/449#-:-KMel74OZ218fodKeXeK:2113144745)*

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
