### PR TITLE
Adjust the pscyopg2 and sqlalchemy tutorials for cockroach demo and CC

### PR DESCRIPTION
**Pull request by jseldess**
- Refactor the tutorials to default to cockroach demo with free
  CC cluster as an alternative instead instead of using
  insecure vs. secure local persistent clusters.
- Create start cockroach and create db steps as includes
  that can be used across other hello world tutorials.
- For psycopg2, update the app code includes to match the corresponding
  code at https://github.com/cockroachlabs/hello-world-python-psycopg2.
  For sqlalchemy, the app code is already matches the code at
  https://github.com/cockroachlabs/hello-world-python-sqlalchemy.
- Update the connection string in the app code to work more
  seamlessly with cockroach demo and CC. 

Addresses #7816.
Fixes https://github.com/cockroachdb/docs/issues/8277.

Opened separate PRs to  make the same updates to the code in the 
hello-world-python-psycopg2 and hello-world-python-sqlalchemy repos:
- https://github.com/cockroachlabs/hello-world-python-psycopg2/pull/1
- https://github.com/cockroachlabs/hello-world-python-sqlalchemy/pull/1

### CODE REVIEW

**Comment by ericharmeling** [comment]
@jseldess 

I like this a lot! I think we should consolidate all examples (no insecure v secure), and make CC the alternative, and not the default, as most developers will prefer to just run a local cluster. Creating that cluster will take 20-30 minutes, which could be double the time that it would take to do the entire tutorial with a local cluster. Just a thought.

**Comment by Amruta-Ranade** [comment]
This looks great! I agree with Eric -- we might want to make the local cluster the default for now.

**Comment by jseldess** [comment]
Thanks, @ericharmeling and @Amruta-Ranade. I'm glad you both like this approach. I agree that we should default to demo clusters for now. Once we have free tier, we should consider defaulting to CC.

If we're in agreement here (and I'd like to get @vy-ton's buy-in), I'll try to refactor all of the hello worlds to follows suit here. However, I think we may want to adjust the code so there are fewer changes needed to the connection parameters: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/6b714b4343eedb013eb5545026c129a81c609532/v20.1/build-a-python-app-with-cockroachdb.html#update-the-connection-parameters. Thoughts?

**Comment by vy-ton** [comment]
+1 to having the 2 options be `local demo cluster` and `CC cluster` with the default being the local cluster for now

A few thoughts,
* With plans to remove `--insecure`, what authentication method should local examples highlight going forward?

> However, I think we may want to adjust the code so there are fewer changes needed to the connection parameters

Have we considered building a simple connection URL builder for docs? I know we have [these examples](https://www.cockroachlabs.com/docs/v20.1/connection-parameters.html?__hstc=106031708.81844b1160fcd9684adf33dd096dc53d.1589819563263.1598288177700.1600736986252.27&__hssc=106031708.3.1600736986252&__hsfp=1874026354#connect-using-a-url) Then instead of documenting the right substitution, it could be copy/paste. The only tricky thing is most libraries let you specify a URL and/or key/value properties.

**Comment by jseldess** [comment]
TFTR, @vy-ton!

> With plans to remove --insecure, what authentication method should local examples highlight going forward?

I don't think we know the answer to this yet. I was discussing this with @bdarnell, @knz, and a few other people, and we agreed we need to wait and see the what security UX ends up being for 21.1 before we thoroughly remove insecure. For now, I've adjusted one local cluster tutorial to secure, as an example: https://github.com/cockroachdb/docs/pull/8469. 

In any case, for these hello worlds, we can just use secure demo and CC, which is also secure. 

> Have we considered building a simple connection URL builder for docs? I know we have these examples Then instead of documenting the right substitution, it could be copy/paste. The only tricky thing is most libraries let you specify a URL and/or key/value properties.

This sounds interesting, but I don't quite know what this would look like. Can you say more?

**Comment by jseldess** [comment]
@ericharmeling, I went ahead and updated the 20.1 and 20.2 psycopg2 and sqlalchemy tutorials to work more seamlessly with `cockroach demo` and CC. I opened separate PRs to update the external hello world repos accordingly as well. Please review this and those other PRs and let me know what you think. If you're ok with these changes, I'd like to merge them and then move on to other app tutorials.

**Review by ericharmeling — APPROVED** [review]
Looks great!! Thanks for making these updates. 

I had just a few suggestions, but they aren't critical.

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8429#-:-MJSEysIAkDCF_4dyAdU:b711eh3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess)

___
*[_includes/v20.1/app/create-a-database.md, line 14 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJS9eeCAtFQo_ENrTov:-MJS9eeCAtFQo_ENrTow:bfatm3s) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/_includes/v20.1/app/create-a-database.md#L14)):*
> ```
> CREATE USER <username> WITH PASSWORD <password>;
> ```

I'm in favor of making this a standard, example user and password, as we've done for other examples (i.e. `max` WITH PASSWORD `roach`). This would make the example more turnkey.
___
*[_includes/v20.1/app/start-cockroachdb.md, line 36 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJSAcMQC0sQnJt_NjJz:-MJSAcMQC0sQnJt_NjK-:bp7iogu) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/_includes/v20.1/app/start-cockroachdb.md#L36)):*
> ```
> ### Create a free cluster
> ```

This whole setup process is very involved. Really looking forward to free tier! 
___
*[_includes/v20.1/app/start-cockroachdb.md, line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJSAm759zOrsKUIeGnS:-MJSAm759zOrsKUIeGnT:b-syupeu) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/_includes/v20.1/app/start-cockroachdb.md#L63)):*
> ```
>  Enter a **Username** and **Password**.
> ```

Again, I think we should suggest using a standard username and password (`max` and `roach`) to make the example more turnkey.
___
*[v20.1/build-a-python-app-with-cockroachdb.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJSC4GBBeYSVVFC1Clq:-MJSC4GBBeYSVVFC1Clr:bimmqmi) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/v20.1/build-a-python-app-with-cockroachdb.md#L16)):*
> ```
> a temporary local cluster
> ```

[a temporary local cluster](cockroach-demo.html)
___
*[v20.1/build-a-python-app-with-cockroachdb.md, line 67 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJSCfXGBbKZJHt74yTl:-MJSCfXGBbKZJHt74yTm:b-uyczpu) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/v20.1/build-a-python-app-with-cockroachdb.md#L67)):*
> ```
> - Replace `<username>` and `<password>` with the SQL username and password that you created earlier.
> ```

If we use a standard name and password, this extra bullet wouldn't be needed.
___
*[v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJSC_slAKmo8vmvRTWa:-MJSC_slAKmo8vmvRTWb:b-k986nr) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md#L16)):*
> ```
> temporary local cluster
> ```

[a temporary local cluster](cockroach-demo.html)
___
*[v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/docs/8429#-MJSER6B3ciTyIb9q-8H:-MJSER6B3ciTyIb9q-8I:bakv22d) ([raw file](https://github.com/cockroachdb/docs/blob/914cf84df09a98897d506cc757f1999f7e6e5329/v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md#L32)):*
> ```
> psycopg2
> ```

psycopg2-binary

**Comment by rafiss** [comment]
Looks like this will close https://github.com/cockroachdb/docs/issues/8471 as well

Thanks for the updates!

**Review by ericharmeling — APPROVED** [review]
LGTM!

Thanks @jseldess !

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8429#-:-MK1P2iT-nmrd8FxR_yi:bo49roj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jseldess)

**Pull request merged**
