### PR TITLE
Added cross-database references to the list of deprecations

### LINKED ISSUE #8874: Document intention to deprecate cross-database referencing
We need to call out the intention to deprecate cross-database referencing in 21.2 (see https://github.com/cockroachdb/cockroach/issues/55791). 

As a first step towards deprecation, 20.2 introduces gating via the following cluster settings that disallow cross-database referencing for foreign keys, views, and sequences (all are `false` by default): 

- `sql.cross_db_fks.enabled`
- `sql.cross_db_sequence_owners.enabled`
- `sql.cross_db_views.enabled`

I can add an additional bullet here in the docs so users know that the deprecation is coming:

- https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations

We should also call out the gating and deprecation intention to users who are upgrading from 20.1:

- https://www.cockroachlabs.com/docs/v20.2/upgrade-cockroach-version#features-that-require-upgrade-finalization

FYI
@vy-ton @ajwerner @lucy-zhang

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #8874. 

@vy-ton 
From https://github.com/cockroachdb/docs/issues/8874#issuecomment-724851144:

> We should also document the alternatives/migration steps that a user can take.

@ajwerner @lucy-zhang 

Do we have a recommended process for upgrading to v20.2 from a v20.1 cluster with cross-database references? 

This is all I have so far:

"Before [upgrading to v20.2](../v20.2/upgrade-cockroach-version.html), we recommend removing all cross-database references."

### CODE REVIEW

**Review by lucy-zhang — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @vy-ton)

___
*[releases/v20.2.0.md, line 141 at r1](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMIaPX30YYX3Puqc8IO:-MMIaPX30YYX3Puqc8IP:b8v4ccn) ([raw file](https://github.com/cockroachdb/docs/blob/6549628ff9508b990249f31550fd52c405349455/releases/v20.2.0.md#L141)):*
> ```Markdown
> - The `--log-dir-max-size` command-line flag is now deprecated and has been replaced with a new flag named `--log-group-max-size`. The flags limit the combined size of all files generated by one *logging group* inside CockroachDB.
> - CockroachDB built-in SQL shell ([`cockroach sql`](../v20.2/cockroach-sql.html) and/or [`cockroach demo`](../v20.2/cockroach-demo.html)) no longer prompts for more lines of input after the user enters `BEGIN` before sending the input to the server. Instead, full lines of input are always sent to the server immediately. The corresponding client-side option `smart_prompt` is thus ineffective and deprecated. It will be removed in a later version.
> - Cross-database references will be deprecated in a future release (see [tracking issue](https://github.com/cockroachdb/cockroach/issues/55791)). In v20.2, cross-database references are disabled for [foreign keys](../v20.2/foreign-key.html), [views](../v20.2/views.html), and [sequence ownership](../v20.2/create-sequence.html) with the `sql.cross_db_fks.enabled`, `sql.cross_db_views.enabled`, and `sql.cross_db_sequence_owners.enabled` [cluster settings](../v20.2/cluster-settings.html) set to `false` by default. Before [upgrading to v20.2](../v20.2/upgrade-cockroach-version.html), we recommend removing all cross-database references.
> ```

I'd say `the creation of new cross-database references is disabled`. If a user is upgrading, we keep the existing cross-database references as they are in 20.2.

We can't advise users to remove their cross-database references _before_ upgrading to 20.2, because support for user-defined schemas is what make cross-database references obsolete. In terms of giving users guidance on how to migrate away from cross-db references, I think this should be part of the wider push to get users to start using user-defined schemas instead. We can advise them to use some combination of `ALTER DATABASE ... CONVERT TO SCHEMA` to turn databases into schemas, and `ALTER TABLE ... RENAME` to move tables between databases, so that cross-referencing tables end up in the same database (possibly in different schemas).

**Comment by vy-ton** [comment]
+1 to Lucy's suggestions. We can also link to the [name resolution page](https://www.cockroachlabs.com/docs/v20.2/sql-name-resolution.html#naming-hierarchy)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @vy-ton)

___
*[releases/v20.2.0.md, line 141 at r1](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMIaPX30YYX3Puqc8IO:-MMLZSJSD5GQzwUmNG_l:bzd9x22) ([raw file](https://github.com/cockroachdb/docs/blob/6549628ff9508b990249f31550fd52c405349455/releases/v20.2.0.md#L141)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I'd say `the creation of new cross-database references is disabled`. If a user is upgrading, we keep the existing cross-database references as they are in 20.2.

We can't advise users to remove their cross-database references _before_ upgrading to 20.2, because support for user-defined schemas is what make cross-database references obsolete. In terms of giving users guidance on how to migrate away from cross-db references, I think this should be part of the wider push to get users to start using user-defined schemas instead. We can advise them to use some combination of `ALTER DATABASE ... CONVERT TO SCHEMA` to turn databases into schemas, and `ALTER TABLE ... RENAME` to move tables between databases, so that cross-referencing tables end up in the same database (possibly in different schemas).
</blockquote></details>

+1 on the suggestions to link out to these strategies. Perhaps we should also indicate on ` ALTER TABLE ... RENAME` that it is an important part of the migration story for now to remove cross-database references but in a subsequent release will lose the ability to move relations between databases.

**Review by ericharmeling — COMMENTED** [review]
@ajwerner @lucy-zhang 

Thanks for the review and suggestions!

Please review the latest commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8876#-:-MMMORer0RjIu0xi3H1P:bo17m18)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @vy-ton)

**Review by lucy-zhang — COMMENTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @vy-ton)

___
*[releases/v20.2.0.md, line 141 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcFfDTAACyoSuW2IbV:-MMcFfDTAACyoSuW2IbW:b99grzj) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/releases/v20.2.0.md#L141)):*
> ```
> Cross-database references are only allowed in a cluster if they existed in the cluster before the upgrade.
> ```
Not strictly true: The user could toggle those cluster settings. Maybe `Pre-existing cross-database references are unaffected`?
___
*[v20.2/sql-name-resolution.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcHJdvDs2Yv5yEIUEz:-MMcHJdvDs2Yv5yEIUF-:b8v4nu9) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L21)):*
> ```Markdown
> - object name
> 
> A CockroachDB cluster can store multiple databases. Each database can store multiple schemas, and each schema can store multiple tables, views, and sequences.
> ```

and user-defined types?
___
*[v20.2/sql-name-resolution.md, line 37 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcJ1Du27m9qBxZw9uH:-MMcJ1Du27m9qBxZw9uI:b-wpolh6) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L37)):*
> ```Markdown
> If you are upgrading to v20.2, take any combination of the following actions after the upgrade is complete:
> 
> - Use the [`ALTER DATABASE ... CONVERT TO SCHEMA`](convert-to-schema.html) statement to convert databases into schemas. This statement is particularly useful if you created databases for the sole purpose of creating a multi-level naming structure. When you convert a database to a schema, all tables and sequences in the database are copied over to a new schema, and the database is deleted. Note that you cannot convert databases that contain user-defined schemas or [views](views.html).
> ```

`copied over to a new schema` is slightly misleading since there's no bulk copying going on; we just update some metadata. Maybe `all tables, views, sequences, and types in the database become child objects of a new schema`.
___
*[v20.2/sql-name-resolution.md, line 39 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcHTuH2f6m8tZ2xrE8:-MMcHTuH2f6m8tZ2xrE9:bu6j5d2) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L39)):*
> ```Markdown
> - Use the [`ALTER DATABASE ... CONVERT TO SCHEMA`](convert-to-schema.html) statement to convert databases into schemas. This statement is particularly useful if you created databases for the sole purpose of creating a multi-level naming structure. When you convert a database to a schema, all tables and sequences in the database are copied over to a new schema, and the database is deleted. Note that you cannot convert databases that contain user-defined schemas or [views](views.html).
> 
> - [Create new schemas](create-schema.html) in databases on your cluster such that the schemas satisfy a coherent naming structure. After the schemas are created, use [`ALTER TABLE ... RENAME`](rename-table.html), [`ALTER SEQUENCE ... RENAME`](rename-sequence.html), or [`ALTER VIEW ... RENAME`](alter-view.html) statements to move objects between databases as needed. To move objects between schemas, use [`ALTER TABLE ... SET SCHEMA`](set-schema.html), [`ALTER SEQUENCE ... SET SCHEMA`](set-schema.html), or [`ALTER VIEW ... SET SCHEMA`](set-schema.html).
> ```

Same goes for `ALTER TYPE`.
___
*[v20.2/sql-name-resolution.md, line 39 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcIlfF9zvbCn-jRV6I:-MMcIlfF9zvbCn-jRV6J:b805nnv) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L39)):*
> ```Markdown
> - Use the [`ALTER DATABASE ... CONVERT TO SCHEMA`](convert-to-schema.html) statement to convert databases into schemas. This statement is particularly useful if you created databases for the sole purpose of creating a multi-level naming structure. When you convert a database to a schema, all tables and sequences in the database are copied over to a new schema, and the database is deleted. Note that you cannot convert databases that contain user-defined schemas or [views](views.html).
> 
> - [Create new schemas](create-schema.html) in databases on your cluster such that the schemas satisfy a coherent naming structure. After the schemas are created, use [`ALTER TABLE ... RENAME`](rename-table.html), [`ALTER SEQUENCE ... RENAME`](rename-sequence.html), or [`ALTER VIEW ... RENAME`](alter-view.html) statements to move objects between databases as needed. To move objects between schemas, use [`ALTER TABLE ... SET SCHEMA`](set-schema.html), [`ALTER SEQUENCE ... SET SCHEMA`](set-schema.html), or [`ALTER VIEW ... SET SCHEMA`](set-schema.html).
> ```

I think `such that the schemas satisfy a coherent naming structure` is kind of vague.
___
*[v20.2/sql-name-resolution.md, line 41 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcHcgAA6pCeuWP-gji:-MMcHcgAA6pCeuWP-gjj:b47l5vo) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L41)):*
> ```Markdown
> - [Create new schemas](create-schema.html) in databases on your cluster such that the schemas satisfy a coherent naming structure. After the schemas are created, use [`ALTER TABLE ... RENAME`](rename-table.html), [`ALTER SEQUENCE ... RENAME`](rename-sequence.html), or [`ALTER VIEW ... RENAME`](alter-view.html) statements to move objects between databases as needed. To move objects between schemas, use [`ALTER TABLE ... SET SCHEMA`](set-schema.html), [`ALTER SEQUENCE ... SET SCHEMA`](set-schema.html), or [`ALTER VIEW ... SET SCHEMA`](set-schema.html).
> 
> - If your cluster contains cross-database references (e.g., a cross-database foreign key reference, or a cross-database view reference), use the relevant [`ALTER TABLE`](alter-table.html), [`ALTER SEQUENCE`](alter-sequence.html), or [`ALTER VIEW `](alter-view.html) statements to move any cross-referencing objects to the same database, but different schemas. Cross-database object references were allowed in earlier versions of CockroachDB to make database-object naming hierarchies more flexible for users. In v20.2, creating cross-database references are disabled for [foreign keys](foreign-key.html), [views](views.html), and [sequence ownership](create-sequence.html), as cross-database references will be deprecated in a future release. For details, see [tracking issue](https://github.com/cockroachdb/cockroach/issues/55791).
> ```

Also sequence ownership

**Review by ericharmeling — COMMENTED** [review]
Thanks for the follow-up review, @lucy-zhang ! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8876#-:-MMqxeOKCfGUyPv3QARf:bx8q2i6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @vy-ton)

___
*[releases/v20.2.0.md, line 141 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcFfDTAACyoSuW2IbV:-MMqRtS50tia7Z6LfDOC:b-bu91xm) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/releases/v20.2.0.md#L141)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> ```
> Cross-database references are only allowed in a cluster if they existed in the cluster before the upgrade.
> ```
Not strictly true: The user could toggle those cluster settings. Maybe `Pre-existing cross-database references are unaffected`?
</blockquote></details>

Updated
___
*[v20.2/sql-name-resolution.md, line 21 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcHJdvDs2Yv5yEIUEz:-MMqTKq1Dz9incOcvOic:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L21)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

and user-defined types?
</blockquote></details>

Done.
___
*[v20.2/sql-name-resolution.md, line 37 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcJ1Du27m9qBxZw9uH:-MMqpQr48MaPs3ZnxUSO:b-c2q8k7) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L37)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

`copied over to a new schema` is slightly misleading since there's no bulk copying going on; we just update some metadata. Maybe `all tables, views, sequences, and types in the database become child objects of a new schema`.
</blockquote></details>

Done, with the exception of the `views`.

You can't convert a database to a schema if the database has views in it, right?

Here's what I get when I try:

```
root@127.0.0.1:63459/movr> CREATE VIEW ny_users AS SELECT id FROM users WHERE city = 'new york';
CREATE VIEW

Time: 31ms total (execution 7ms / network 24ms)

root@127.0.0.1:63459/movr> CREATE DATABASE cockroach_labs;
CREATE DATABASE

Time: 3ms total (execution 3ms / network 0ms)

root@127.0.0.1:63459/movr>  USE cockroach_labs;
SET

Time: 2ms total (execution 2ms / network 0ms)

root@127.0.0.1:63459/cockroach_labs> ALTER DATABASE movr CONVERT TO SCHEMA WITH PARENT cockroach_labs;
ERROR: could not convert database "movr" into schema because "movr.public.users" has dependent objects [cockroach_labs.movr.ny_users]
SQLSTATE: 2BP01
```

This PR notes this limitation in `convert-to-schema.md`.
___
*[v20.2/sql-name-resolution.md, line 39 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcHTuH2f6m8tZ2xrE8:-MMqpZwp9eb5-v4CYLRQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L39)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Same goes for `ALTER TYPE`.
</blockquote></details>

Done.
___
*[v20.2/sql-name-resolution.md, line 39 at r2](https://reviewable.io/reviews/cockroachdb/docs/8876#-MMcIlfF9zvbCn-jRV6I:-MMqptDm2kcwqaFFrWLe:bss4a2b) ([raw file](https://github.com/cockroachdb/docs/blob/62cb6f74d06085f8573a32c622d8b41d26afc6fd/v20.2/sql-name-resolution.md#L39)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I think `such that the schemas satisfy a coherent naming structure` is kind of vague.
</blockquote></details>

Removed.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
