### PR TITLE
Move release notes into a directory

### LINKED ISSUE #1695: Put release notes in a separate directory
https://www.cockroachlabs.com/docs/v1.0 is the release notes for version 1.0, while https://www.cockroachlabs.com/docs/v1.0/ with a trailing slash is version 1.0 of the docs home page. It's unconventional for urls that differ only in a trailing slash to lead to different pages. We should probably tweak the naming conventions for either release notes or version directories so they don't collide (at least for future releases)

### PR DESCRIPTION
**Pull request by jseldess**
Also edit sidebar-release.json, releases.md, and install pages
to account for the new location.

Fixes #1695

### CODE REVIEW

**Comment by jseldess** [comment]
@benesch, a few things I couldn't figure out:

- When you're on a release notes page and click somewhere in the sidenav, we no longer pick up the selected version. Instead, "page not found". Tips for what needs changing?
- When you click on `/release-notes/releases.html`, though the link is correct, the page redirects to `/stable`, which breaks the link. I'm sure there's something in one of the ruby plugins that I just can't understand. Help?

Also, I just realized that, on release notes pages, the urls for all links to docs pages need to be directed up one level now.

**Comment by benesch** [comment]
Ok, I think I've fixed up everything you mentioned!

> When you're on a release notes page and click somewhere in the sidenav, we no longer pick up the selected version. Instead, "page not found". Tips for what needs changing?

The sidebar JS wasn't equipped to handle directories that didn't represent versions, like the `release-notes` you've introduced. I've taught it to only consider directories that look like `v#.#` as versions.

> Also, I just realized that, on release notes pages, the urls for all links to docs pages need to be directed up one level now.

I ran a script to fix this up, though I'm relying on htmlproofer to catch any potential mistakes.

**Comment by benesch** [comment]
> When you click on /release-notes/releases.html, though the link is correct, the page redirects to /stable, which breaks the link. I'm sure there's something in one of the ruby plugins that I just can't understand. Help?

Oddly, I can't reproduce this!

**Comment by jseldess** [comment]
Thank you, @benesch! I fixed the remaining broken links caught by htmlproofer. I'll check it all again once the test site is posted.

**Comment by jseldess** [comment]
@benesch, so the only remaining problem I can see is that now, when you click a version link on http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1497e41630d5788cb765954786daf68f8f78de0/release-notes/releases.html, you get "page not found". 

Example:
- Under `Releases` in the sidenav, click `1.0.3` and you land on http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1497e41630d5788cb765954786daf68f8f78de0/release-notes/v1.0.3.html
- On http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/f1497e41630d5788cb765954786daf68f8f78de0/release-notes/releases.html, click `v1.0.3` and you get "page not found". Looks like it's losing the s3-specific test directory: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/release-notes/v1.0.3.html 

Any ideas?

**Comment by benesch** [comment]
Ah, whoops. The releases page was linking to e.g. `/v1.0.html` instead of `v1.0.html`. Fixed! I also took the liberty of making a few more changes:

    * I renamed the directory from `release-notes` to `releases` in the interest of keeping the URLs short. There's precedent for this: Django and CoreOS both keep their release notes in a directory called `releases`. But @jseldess I am 100% happy to change this back!

   * I renamed `release-notes/releases.html` to `releases/index.html`. This just *feels* right: `/docs/releases/` now gives you a nice listing of all available releases.

   * I added redirects for '/VERSION.html -> releases/VERSION.html` to avoid breaking any outside links to old release notes. We won't have to do this for new releases.

   * I retitled the versions in the sidebar to match the releases page. So "v1.0", "v1.0.1" instead of "1.0.0" and "1.0.0", etc.

Let me know what you think!

**Comment by jseldess** [comment]
Love all of your changes, @benesch! Thanks again. 

I just fixed some strangler broken links. Once TC goes green, I'll merge.

**Comment by jseldess** [comment]
It's great, but before merging, just want to get @bdarnell's final review, since he caught this issue in the first place. Ben, any feedback, or good to merge?

**Comment by benesch** [comment]
Woohoo, thanks @jseldess!

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 112 files at r1.
Review status: 3 of 61 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[_includes/sidebar.html, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1710#-KpG45Ok5KHNruKkAKVc:-KpG45Ok5KHNruKkAKVd:b-rbr99p) ([raw file](https://github.com/cockroachdb/docs/blob/12d4dcf88b85793404e9e5aded92e398d4bba6a3/_includes/sidebar.html#L98)):*
> ```HTML
>                     // The version is the first directory component in the URL,
>                     // if it exists.
>                     if (pathComponents.length > 1 && /^v\d.\d$/.test(pathComponents[0])) {
> ```

Do we need to handle `/stable/` and `/dev/` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1710#-:-KpG4cw7EoBOCZ16xD8V:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 2 of 61 files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/sidebar.html, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1710#-KpG45Ok5KHNruKkAKVc:-KpGZsrXVklWIlukExsM:b-2pdpl6) ([raw file](https://github.com/cockroachdb/docs/blob/12d4dcf88b85793404e9e5aded92e398d4bba6a3/_includes/sidebar.html#L98)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do we need to handle `/stable/` and `/dev/` here?
</blockquote></details>

Whoops, we absolutely do. Thanks! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1710)*

**Pull request merged**
