### PR TITLE
Updated TypeORM to use DataSource API

### PR DESCRIPTION
**Pull request by ericharmeling**
Related to https://cockroachlabs.atlassian.net/browse/DOC-3063, https://cockroachlabs.atlassian.net/browse/CC-6539, https://github.com/cockroachlabs/hello-world-typescript-typeorm/pull/4.

Ahead of merging this PR, I'm going to rename [`hello-world-typescript-typeorm`](https://github.com/cockroachlabs/hello-world-typescript-typeorm) to `example-app-typescript-typeorm`.

### CODE REVIEW

**Comment by ericharmeling** [comment]
Pages of interest for first review:
- https://deploy-preview-13489--cockroachdb-docs.netlify.app/docs/v22.1/connect-to-the-database.html?filters=typeorm
- https://deploy-preview-13489--cockroachdb-docs.netlify.app/docs/v22.1/build-a-typescript-app-with-cockroachdb.html#step-4-configure-your-cockroachdb-connection

Note that after https://github.com/cockroachdb/docs/pull/13472 is merged, the cluster set up steps will be more accurate.

**Comment by laurenbarker** [comment]
@ericharmeling do you need a review on this or were Sean and I added for awareness?

**Review by laurenbarker — APPROVED** [review]
This all :lgtm: I just had some general nits that can be ignored and a question.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13489#-:-MzuW6Ol8BG3xr-d35K0:b-u7cs7y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @sjbarag)

___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuPLa8BeEKXcMWfbcR:-MzuPLa8BeEKXcMWfbcS:btsq2bk) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L27)):*
> ```Markdown
> ## Step 3. Get the code
> 
> Clone [the code's GitHub repository](https://github.com/cockroachlabs/example-app-typescript-typeorm).
> ```

nit: We should probably have a lock file (or two) checked into this repo so everyone is installing the exact same versions.
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuPn2W3vWVqb_c88MB:-MzuPn2W3vWVqb_c88MC:btmw5ap) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L35)):*
> ```Markdown
> 1. Open the `datasource.ts` file, and comment out the `extra` and `options` configuration properties.
> 
> 1. In the `datasource.ts` file, replace `ssl: true` with `ssl: { rejectUnauthorized: false }`.
> ```

nit: It could be more clear in the instructions that the other option is commented out in the file. I almost copied this line in.
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuR_MrAkjuXYlrPb90:-MzuR_MrAkjuXYlrPb91:b-3d4h2o) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L49)):*
> ```Markdown
> 1. Open the `datasource.ts` file, and edit the `--cluster=<routing-id>` configuration property to specify the routing ID to your serverless cluster.
> 
> 1. Set the `DATABASE_URL` environment variable to a CockroachDB connection string compatible with TypeORM.
> ```

I confirmed that this works! We don't make it easy in CC to copy just the connection string, though. We recently talked about having the connection string in a separate copy block in CC in the future, but for these types of instructions we would also need to have the options value (e.g., `--cluster=<routing-id>`) as a separate block as well. cc @emily-horing 
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuUtmaDhRK16Pzn6QF:-MzuUtmbCpQE2sdWHDN-:bp5x7we) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L66)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ shell
> $ npm install
> ```

super nit: I would expect the dep install instructions to be after the git clone instructions because otherwise editors may complain that imports aren't available which is a little distracting. I also have the terminal open after cloning the repo.
___
*[v22.1/connect-to-the-database.md, line 280 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuVWUi2rRb5L6XszSU:-MzuVWUi2rRb5L6XszSV:b-fzriyc) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/connect-to-the-database.md#L280)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ ts
> export const AppDataSource = new DataSource({
> ```

Should we include `import { DataSource } from "typeorm"` in these copy blocks?

**Review by ericharmeling — COMMENTED** [review]
TFTR @laurenbarker ! I think I got to all your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13489#-:-MzvHu3X38IvJOskQDTl:b-iwa0fd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @emily-horing, @laurenbarker, and @sjbarag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuZmUd--kTGlW8lVca:-MzvImau9olOHm5Nmoj6:b-opo8g5) (no related file):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Looking good!  +1 to @laurenbarker's comments (as always), but I agree that they're not blocking.

:lgtm: thanks for taking this on, @ericharmeling !
</blockquote></details>

TFTR @sjbarag ! Happy to help :)

---
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 27 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuPLa8BeEKXcMWfbcR:-Mzuy87yB173vcyB7sOJ:b-tjd68m) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L27)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

> This all  I just had some general nits that can be ignored and a question.
</blockquote></details>

Done. 

(see https://github.com/cockroachlabs/example-app-typescript-typeorm/commit/d2d1b8a9d0523ecd74112735eb6e0634bab25af2).
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 35 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuPn2W3vWVqb_c88MB:-MzuyE7-1qFO4VPFJqWS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L35)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

nit: It could be more clear in the instructions that the other option is commented out in the file. I almost copied this line in.
</blockquote></details>

Done.
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 49 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuR_MrAkjuXYlrPb90:-MzuyK5h14C1mmtJA9qs:b-eyozca) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L49)):*
> We recently talked about having the connection string in a separate copy block in CC in the future

The connection string sounds like the most helpful artifact to give users, TBH. The code snippets I use in https://www.cockroachlabs.com/docs/stable/connect-to-the-database.html are super generic and probably won't be helpful for most users who already have environments set up to connect to postgres or some other rdbms. 
___
*[v22.1/build-a-typescript-app-with-cockroachdb.md, line 66 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuUtmaDhRK16Pzn6QF:-Mzuyj1gAc9u_MpXSpXV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/build-a-typescript-app-with-cockroachdb.md#L66)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

super nit: I would expect the dep install instructions to be after the git clone instructions because otherwise editors may complain that imports aren't available which is a little distracting. I also have the terminal open after cloning the repo.
</blockquote></details>

Done.
___
*[v22.1/connect-to-the-database.md, line 280 at r1](https://reviewable.io/reviews/cockroachdb/docs/13489#-MzuVWUi2rRb5L6XszSU:-MzuykjCABhrVCEkPiiy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/55f8a7b665b323257b8e3595ba511e9343400f7f/v22.1/connect-to-the-database.md#L280)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

I'd guess yes :smiley: 
</blockquote></details>

Done.

**Review by nickvigilante — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13489#-:-Mzv_ACc6C7U_hoNo5vv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @emily-horing and @laurenbarker)

**Pull request merged**
