### PR TITLE
Update cluster scaling callouts

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/CC-4888
https://cockroachlabs.atlassian.net/browse/CC-4831

Update that users can scale clusters up and down but cannot go from multi-node to single-node.
Add a callout that contract customers need to contact support to scale.

### CODE REVIEW

**Review by emily-horing — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/11234#-:-Mj5Lc-g2UsCgtPr4hEO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @daniel-crlabs)

**Review by daniel-crlabs — COMMENTED** [review]
Looks good, one question, can they scale from a single node to multi-node? Maybe we should add an explanation for that as well?

**Comment by gemma-shay** [comment]
@daniel-crlabs yes, non-invoice customers can scale up/down in the console as long as they're not going from multi-node to single-node. we have instructions for adding/removing nodes and some recommendations at the top the [cluster management page](cockroachcloud/cluster-management.md). did you have something else in mind?

**Comment by daniel-crlabs** [comment]
Ok, sounds good, as long as our docs and the UI reflect this in a way to grab the customer's attention, that's all good.
Thanks again for this.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
