### PR TITLE
Querying partitioned data

### LINKED ISSUE #4796: Make it easy to focus queries onto partitioned data
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recKgsWJj2YKGBh50?blocks=hide

PM: @awoods187

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #4796. 

- Added "Querying partitions" include file.
- Included this file as a section in [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html) and [PARTITION BY](https://www.cockroachlabs.com/docs/dev/partition-by.html) pages.

Still a WIP - please provide feedback.

### CODE REVIEW

**Comment by awoods187** [comment]
Overall this PR looks really good. I don't think we should be using `Explain (opt, verbose)` because its output can be extremely long and overwhelming. We pretty much only want to recommend this for troubleshooting when you are working with a CRL. We should instead show the regular `EXPLAIN` which also shows the plans being scanned in parallel. cc @RaduBerinde

**Comment by ericharmeling** [comment]
@awoods187 I updated this PR to just use the standard `EXPLAIN` statement.

Also, added @RaduBerinde for an engineering review. :)

**Comment by awoods187** [comment]
lgtm

**Comment by ericharmeling** [comment]
@RaduBerinde reminder to review :)

**Comment by RaduBerinde** [comment]
___
*[_includes/v19.2/sql/querying-partitions.md, line 79 at r1](https://reviewable.io/reviews/cockroachdb/docs/5710#-Lt0Ki7NCilTzcxYCtu8:-Lt0rOdu-8i0wqemvQ0v:b215iqy) ([raw file](https://github.com/cockroachdb/docs/blob/ca8670f3e84eae1fd1952eb03b2b4f4bfb18f7ed/_includes/v19.2/sql/querying-partitions.md#L79)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Added an additional example EXPLAIN statement:

```
EXPLAIN SELECT * FROM users WHERE id='00000000-0000-4000-8000-000000000000' 
AND city IN ('amsterdam','boston','los angeles','new york','paris','rome','san francisco','seattle','washington dc');
```
</blockquote></details>

I meant we can add `city IN ('amsterdam','boston','los angeles','new york','paris','rome','san francisco','seattle','washington dc')` as a CHECK constraint in the schema, which would do the same without having to specify it on each query.

**Pull request merged**
