### PR TITLE
updates to insecure and secure startup

### LINKED ISSUE #47: Update docs for starting cockroach - insecure and secure
Need to update [Start a Local Cluster](http://www.cockroachlabs.com/docs/start-a-local-cluster.html). See:

[#4269](https://github.com/cockroachdb/cockroach/issues/4269) - see below 
[#4335](https://github.com/cockroachdb/cockroach/issues/4335) - default `--stores` value for `cockroach start`
[#4352](https://github.com/cockroachdb/cockroach/issues/4352) - remove `--dev` mode for `cockroach start` 

* If `cockroach start` is specified then the server only listens on localhost and the server starts in insecure mode. This allows a developer running a local instance to start cockroach with no additional arguments.
* If `cockroach start --insecure` is specified the server listens on all addresses and starts in insecure mode. This forces a production cockroach cluster composed of multiple nodes to explicitly specify `--insecure`.
* If `cockroach start --cert-file` is specified the server listens on all addresses and starts in secure mode.

### PR DESCRIPTION
**Pull request by jseldess**
Updated start-a-local-cluster.md to account for:

- removal of `--dev` flag
- default storage location
- attribute optional when passing `--stores` flag

@petermattis, @mberhault, please let me know if I missed anything, or if you want me to cut back or expand any explanations. I'll also be sure all of this gets into the `cockroach` CLI docs. 

I'll work on this file again once @mberhault's done with his changes to certs, @BramGruneir's done with his changes to `--store`, and @tamird's done with his changes to ports.

Fixes #47

### CODE REVIEW

**Comment by tamird** [comment]
Heads up that I just merged https://github.com/cockroachdb/cockroach/pull/4536, so you might want to include that documentation update here.

**Comment by jseldess** [comment]
Thanks, @tamird. I upgraded to go 1.6 and got the latest cockroach code, but when I try to start up a cluster now, I get `E0224 11:12:32.580766 15556 gossip/client.go:73  failed to dial: grpc: timed out trying to connect`. Any ideas?

**Comment by tamird** [comment]
Discussed one-on-one; the error @jseldess reported above was a red herring caused by an old gossip cache.

**Comment by jseldess** [comment]
@petermattis, one specific question for you: Should I show and discuss the node startup response in this quickstart, or should that be elsewhere? 

```
build:     alpha.v1-362-g723805f @ 2016/02/24 16:03:23 (go1.6)
admin:     http://JESSEs-MacBook-Pro.local:26257
sql:       postgresql://root@JESSEs-MacBook-Pro.local:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  cockroach-data
```

**Comment by petermattis** [comment]
We should definitely discuss the node startup output. Not sure I have enough context at the moment to say whether the quickstart guide or elsewhere is more appropriate. The info is meant to be somewhat self-explanatory, so leaving the discussion of the output out of the quickstart guide could be reasonable.

**Comment by jseldess** [comment]
@petermattis, included the startup output with a brief explanation (third bullet in step 1 of insecure procedure and step 2 of secure procedure).

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
