### PR TITLE
version the sql diagrams

### PR DESCRIPTION
**Pull request by benesch**
#1609 is blocked on this, and it's an important step towards #1546.

### CODE REVIEW

**Comment by benesch** [comment]
This should be the last massive PR like this!

**Comment by jseldess** [comment]
@benesch, finally getting to this. So sorry for the delay. The change make sense in principle, but it doesn't seem to work with the diagram generator. For example, when I try to regenerate a single diagram:

```
$ ~/src/github.com/cockroachdb/docs$ cd generate/
~/src/github.com/cockroachdb/docs/generate$ go run main.go --filter add_column
2017/07/10 11:02:23 generate BNF: https://raw.githubusercontent.com/cockroachdb/cockroach/master/pkg/sql/parser/sql.y
2017/07/10 11:02:24 parse: alter_table_stmt, inline: [alter_table_cmds alter_table_cmd column_def], descend: false
2017/07/10 11:02:28 add_column: generated railroad diagram
2017/07/10 11:02:28 add_columnopen ../_includes/sql/diagrams/add_column.html: no such file or directory
exit status 1
```

The program fails due to this directory structure change. 

Runnig `make` in the root directory to regenerate everything, including function docs, also doesn't work:

```
~/src/github.com/cockroachdb/docs/generate$ cd ..
~/src/github.com/cockroachdb/docs$ make
make: Nothing to be done for `all'.
```

That, however, happens even without this PR's changes. Something we didn't catch with the versioning PR. 

Any ideas?

**Comment by benesch** [comment]
Sorry for not being more clear! This is a necessary step towards making the diagram generator work with versioning. It's expected that it won't work until we move it to the cockroachdb/cockroach repo (#1546).

**Comment by jseldess** [comment]
Sorry for misunderstanding this, @benesch. LGTM then. With this change in place, we won't be able to use the diagram generator until the rest of the work is done, though. Are you planning to move it over?

**Comment by benesch** [comment]
Yup! Or talking @dt and @mjibson into it.

**Comment by dt** [comment]
Moving the markdown generation is on my radar -- I hadn't looked at the diagram generator at all (though I imagine it probably is straightforward?)

**Pull request merged**
