### PR TITLE
Reflect some v2.0 changes to the SQL CLI

### LINKED ISSUE #2176: Various fixes to the interactive SQL shell
From release notes:
> Many bugs in the interactive SQL shell have been fixed by switching to libedit for command-line input. The normalize_history option has been removed.

PRs: 
- https://github.com/cockroachdb/cockroach/pull/18531
- https://github.com/cockroachdb/cockroach/pull/19125

### PR DESCRIPTION
**Pull request by knz**
Fixes  #2176.

### CODE REVIEW

**Comment by jseldess** [comment]
Actually, same update needed on the 1.0 version of the page: https://github.com/cockroachdb/docs/blob/master/v1.0/known-limitations.md#repeated-or-combined-commands-in-the-sql-shell-history

**Comment by jseldess** [comment]
@knz, would you like me to handle these final updates?

**Comment by knz** [comment]
Yes that would be lovely. Thanks!

**Comment by jseldess** [comment]
I'm actually going to hand it in a follow-up PR since I'm having trouble pushing to your fork again.

**Pull request merged**
