### PR TITLE
Updated rust simple CRUD topic for new code and full support.

### PR DESCRIPTION
**Pull request by ianjevans**
Fixes DOC-4976.

### CODE REVIEW

**Comment by gemma-shay** [comment]
Had to cd in to the directory and `brew install rust` to get it to run, then got this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigParse, cause: Some(InvalidValue("sslmode")) }', src/main.rs:76:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ianjevans** [comment]
> Had to cd in to the directory and `brew install rust` to get it to run, then got this error:
> 
> ```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigParse, cause: Some(InvalidValue("sslmode")) }', src/main.rs:76:53
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Can you rerun it with `RUST_BACKTRACE=1` to get the backtrace?

**Comment by gemma-shay** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigParse, cause: Some(InvalidValue("sslmode")) }', src/main.rs:76:53
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/core/src/result.rs:1107:23
   4: bank::main
             at ./src/main.rs:76:9
   5: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
```

**Comment by gemma-shay** [comment]
full backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigParse, cause: Some(InvalidValue("sslmode")) }', src/main.rs:76:53
stack backtrace:
   0:        0x10e560852 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h408486b2bd61a14d
   1:        0x10e574a5a - core::fmt::write::h398bbe0d0a065ca9
   2:        0x10e54c968 - std::io::Write::write_fmt::h9eb0f934b0343a80
   3:        0x10e551b28 - std::panicking::default_hook::{{closure}}::h9f1a676cea86d276
   4:        0x10e5517dc - std::panicking::default_hook::he6707bf4997bbc04
   5:        0x10e552192 - std::panicking::rust_panic_with_hook::hd8e6eef88261a338
   6:        0x10e560b73 - std::panicking::begin_panic_handler::{{closure}}::hfba8e523b00f4966
   7:        0x10e560967 - std::sys_common::backtrace::__rust_end_short_backtrace::h90514e9212607e52
   8:        0x10e551c63 - _rust_begin_unwind
   9:        0x10e57ec43 - core::panicking::panic_fmt::he4403f4ab5a63c4d
  10:        0x10e57ed25 - core::result::unwrap_failed::h59d91b4f214ced4c
  11:        0x10e36d422 - core::result::Result<T,E>::unwrap::h18d999d413244bce
                               at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/core/src/result.rs:1107:23
  12:        0x10e3540cb - bank::main::h8389d93482d4d7ae
                               at /Users/gemmashay/example-app-rust-postgres/src/main.rs:76:9
  13:        0x10e35bbce - core::ops::function::FnOnce::call_once::h21d4c211aeff4615
                               at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
  14:        0x10e370fa1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3df3eb9f0c3e9841
                               at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/std/src/sys_common/backtrace.rs:122:18
  15:        0x10e36a9a4 - std::rt::lang_start::{{closure}}::h1d8a49469e37b7b4
                               at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/std/src/rt.rs:145:18
  16:        0x10e544815 - std::rt::lang_start_internal::h29747419ad3cbd79
  17:        0x10e36a97e - std::rt::lang_start::h22e5a799c458be95
                               at /private/tmp/rust-20220923-6877-yszh4a/rustc-1.64.0-src/library/std/src/rt.rs:144:17
  18:        0x10e354b56 - _main
```

**Comment by ianjevans** [comment]
Do you have the full output from `cargo run`? Specifically, I'm looking for the dependencies.

```
❯ cargo run
   Compiling autocfg v1.1.0
   Compiling libc v0.2.132
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling typenum v1.15.0
   Compiling version_check v0.9.4
   Compiling unicode-ident v1.0.3
   Compiling memchr v2.5.0
   Compiling syn v1.0.99
   Compiling futures-core v0.3.23
   Compiling pin-project-lite v0.2.9
   Compiling once_cell v1.13.1
   Compiling subtle v2.4.1
   Compiling futures-sink v0.3.23
   Compiling futures-channel v0.3.23
   Compiling log v0.4.17
   Compiling futures-task v0.3.23
   Compiling tinyvec_macros v0.1.0
   Compiling futures-util v0.3.23
   Compiling cc v1.0.73
   Compiling bytes v1.2.1
   Compiling pkg-config v0.3.25
   Compiling pin-utils v0.1.0
   Compiling ppv-lite86 v0.2.16
   Compiling futures-io v0.3.23
   Compiling unicode-bidi v0.3.8
   Compiling cpufeatures v0.2.2
   Compiling parking_lot_core v0.9.3
   Compiling siphasher v0.3.10
   Compiling scopeguard v1.1.0
   Compiling byteorder v1.4.3
   Compiling base64 v0.13.0
   Compiling fallible-iterator v0.2.0
   Compiling smallvec v1.9.0
   Compiling async-trait v0.1.57
   Compiling openssl v0.10.41
   Compiling core-foundation-sys v0.8.3
   Compiling foreign-types-shared v0.1.1
   Compiling uuid v1.1.2
   Compiling tokio-openssl v0.6.3
   Compiling percent-encoding v2.1.0
   Compiling bitflags v1.3.2
   Compiling tracing-core v0.1.29
   Compiling tinyvec v1.6.0
   Compiling generic-array v0.14.6
   Compiling slab v0.4.7
   Compiling tokio v1.20.1
   Compiling lock_api v0.4.7
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling phf_shared v0.10.0
   Compiling foreign-types v0.3.2
   Compiling openssl-sys v0.9.75
   Compiling phf v0.10.1
   Compiling tracing v0.1.36
   Compiling unicode-normalization v0.1.21
   Compiling iana-time-zone v0.1.45
   Compiling getrandom v0.2.7
   Compiling mio v0.8.4
   Compiling socket2 v0.4.4
   Compiling time v0.1.44
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.12.1
   Compiling stringprep v0.1.2
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling block-buffer v0.10.2
   Compiling crypto-common v0.1.6
   Compiling chrono v0.4.22
   Compiling digest v0.10.3
   Compiling md-5 v0.10.1
   Compiling sha2 v0.10.2
   Compiling hmac v0.12.1
   Compiling postgres-protocol v0.6.4
   Compiling postgres-types v0.2.3
   Compiling tokio-util v0.7.3
   Compiling futures-macro v0.3.23
   Compiling openssl-macros v0.1.0
   Compiling futures-executor v0.3.23
   Compiling futures v0.3.23
   Compiling tokio-postgres v0.7.6
   Compiling postgres-openssl v0.5.0
   Compiling postgres v0.19.3
   Compiling bank v0.1.0 (/Users/ian/go/src/github.com/cockroachdb/example-app-rust-postgres)
    Finished dev [unoptimized + debuginfo] target(s) in 21.36s
     Running `target/debug/bank`
```

**Comment by gemma-shay** [comment]
that's not showing up anymore but the first time i ran `cargo run`, i got this (sorry it's long):
```
    Updating crates.io index
warning: spurious network error (2 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
  Downloaded autocfg v1.1.0
  Downloaded rand v0.8.5
  Downloaded tinyvec_macros v0.1.0
  Downloaded log v0.4.17
  Downloaded openssl-macros v0.1.0
  Downloaded pin-utils v0.1.0
  Downloaded proc-macro2 v1.0.43
  Downloaded tinyvec v1.6.0
  Downloaded tracing v0.1.36
  Downloaded uuid v1.1.2
  Downloaded version_check v0.9.4
  Downloaded stringprep v0.1.2
  Downloaded postgres-protocol v0.6.4
  Downloaded tokio-openssl v0.6.3
  Downloaded time v0.1.44
  Downloaded unicode-ident v1.0.3
  Downloaded phf v0.10.1
  Downloaded parking_lot_core v0.9.3
  Downloaded pkg-config v0.3.25
  Downloaded smallvec v1.9.0
  Downloaded sha2 v0.10.2
  Downloaded cpufeatures v0.2.2
  Downloaded chrono v0.4.22
  Downloaded rand_core v0.6.3
  Downloaded iana-time-zone v0.1.45
  Downloaded postgres-openssl v0.5.0
  Downloaded once_cell v1.13.1
  Downloaded futures-channel v0.3.23
  Downloaded libc v0.2.132
  Downloaded futures-task v0.3.23
  Downloaded tokio v1.20.1
  Downloaded futures-sink v0.3.23
  Downloaded futures-macro v0.3.23
  Downloaded futures-io v0.3.23
  Downloaded futures-executor v0.3.23
  Downloaded futures-core v0.3.23
  Downloaded num-integer v0.1.45
  Downloaded postgres-types v0.2.3
  Downloaded postgres v0.19.3
  Downloaded futures v0.3.23
  Downloaded siphasher v0.3.10
  Downloaded quote v1.0.21
  Downloaded ppv-lite86 v0.2.16
  Downloaded pin-project-lite v0.2.9
  Downloaded openssl-sys v0.9.75
  Downloaded openssl v0.10.41
  Downloaded num-traits v0.2.15
  Downloaded memchr v2.5.0
  Downloaded lock_api v0.4.7
  Downloaded getrandom v0.2.7
  Downloaded generic-array v0.14.6
  Downloaded foreign-types-shared v0.1.1
  Downloaded foreign-types v0.3.2
  Downloaded fallible-iterator v0.2.0
  Downloaded digest v0.10.3
  Downloaded crypto-common v0.1.6
  Downloaded core-foundation-sys v0.8.3
  Downloaded cfg-if v1.0.0
  Downloaded cc v1.0.73
  Downloaded bytes v1.2.1
  Downloaded byteorder v1.4.3
  Downloaded bitflags v1.3.2
  Downloaded base64 v0.13.0
  Downloaded syn v1.0.99
  Downloaded futures-util v0.3.23
  Downloaded tokio-postgres v0.7.6
  Downloaded unicode-normalization v0.1.21
  Downloaded unicode-bidi v0.3.8
  Downloaded typenum v1.15.0
  Downloaded tracing-core v0.1.29
  Downloaded tokio-util v0.7.3
  Downloaded subtle v2.4.1
  Downloaded socket2 v0.4.4
  Downloaded slab v0.4.7
  Downloaded md-5 v0.10.1
  Downloaded hmac v0.12.1
  Downloaded block-buffer v0.10.2
  Downloaded phf_shared v0.10.0
  Downloaded percent-encoding v2.1.0
  Downloaded parking_lot v0.12.1
  Downloaded mio v0.8.4
  Downloaded async-trait v0.1.57
  Downloaded scopeguard v1.1.0
  Downloaded rand_chacha v0.3.1
  Downloaded 84 crates (4.3 MB) in 1.64s
   Compiling autocfg v1.1.0
   Compiling libc v0.2.132
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.3
   Compiling version_check v0.9.4
   Compiling typenum v1.15.0
   Compiling memchr v2.5.0
   Compiling syn v1.0.99
   Compiling futures-core v0.3.23
   Compiling pin-project-lite v0.2.9
   Compiling futures-sink v0.3.23
   Compiling log v0.4.17
   Compiling subtle v2.4.1
   Compiling once_cell v1.13.1
   Compiling futures-channel v0.3.23
   Compiling futures-task v0.3.23
   Compiling cc v1.0.73
   Compiling bytes v1.2.1
   Compiling futures-util v0.3.23
   Compiling tinyvec_macros v0.1.0
   Compiling pkg-config v0.3.25
   Compiling futures-io v0.3.23
   Compiling ppv-lite86 v0.2.16
   Compiling pin-utils v0.1.0
   Compiling cpufeatures v0.2.2
   Compiling parking_lot_core v0.9.3
   Compiling unicode-bidi v0.3.8
   Compiling byteorder v1.4.3
   Compiling base64 v0.13.0
   Compiling smallvec v1.9.0
   Compiling async-trait v0.1.57
   Compiling fallible-iterator v0.2.0
   Compiling scopeguard v1.1.0
   Compiling siphasher v0.3.10
   Compiling uuid v1.1.2
   Compiling core-foundation-sys v0.8.3
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.41
   Compiling percent-encoding v2.1.0
   Compiling tokio-openssl v0.6.3
   Compiling bitflags v1.3.2
   Compiling generic-array v0.14.6
   Compiling slab v0.4.7
   Compiling tokio v1.20.1
   Compiling lock_api v0.4.7
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling tinyvec v1.6.0
   Compiling tracing-core v0.1.29
   Compiling phf_shared v0.10.0
   Compiling foreign-types v0.3.2
   Compiling tracing v0.1.36
   Compiling phf v0.10.1
   Compiling openssl-sys v0.9.75
   Compiling unicode-normalization v0.1.21
   Compiling iana-time-zone v0.1.45
   Compiling getrandom v0.2.7
   Compiling mio v0.8.4
   Compiling socket2 v0.4.4
   Compiling time v0.1.44
   Compiling rand_core v0.6.3
   Compiling stringprep v0.1.2
   Compiling parking_lot v0.12.1
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.2
   Compiling digest v0.10.3
   Compiling chrono v0.4.22
   Compiling sha2 v0.10.2
   Compiling md-5 v0.10.1
   Compiling hmac v0.12.1
   Compiling postgres-protocol v0.6.4
   Compiling postgres-types v0.2.3
   Compiling tokio-util v0.7.3
   Compiling futures-macro v0.3.23
   Compiling openssl-macros v0.1.0
   Compiling futures-executor v0.3.23
   Compiling futures v0.3.23
   Compiling tokio-postgres v0.7.6
   Compiling postgres-openssl v0.5.0
   Compiling postgres v0.19.3
   Compiling bank v0.1.0 (/Users/gemmashay/example-app-rust-postgres)
    Finished dev [unoptimized + debuginfo] target(s) in 3m 41s
     Running `target/debug/bank`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ConfigParse, cause: Some(InvalidValue("sslmode")) }', src/main.rs:76:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ianjevans** [comment]
Ah, I remember what this is now.

In your connection string, change `sslmode=verify-full` to `sslmode=require`. Rust's `postgres` driver doesn't recognize `verify-full`. I added a note to the [README](https://github.com/cockroachdb/example-app-rust-postgres), but forgot to add it to the doc.

**Comment by gemma-shay** [comment]
cool, LGTM otherwise!

**Comment by ianjevans** [comment]
New edits forthcoming. Sorry I forgot about this. #covidbrain

**Pull request merged**
