### PR TITLE
Add docs on running multi-region TPC-C

### PR DESCRIPTION
**Pull request by rmloveland**
Addresses the on-prem part of DOC-1487

### CODE REVIEW

**Comment by rmloveland** [comment]
@ajstorm here's a direct link to preview of the new page for convenience: [Performance benchmarking with TPC-C (local multi-region)](https://deploy-preview-12530--cockroachdb-docs.netlify.app/docs/v21.2/performance-benchmarking-with-tpcc-local-multiregion)

This seems like the natural place to add this to the docs.  Please let me know if you have other thoughts.

If this looks ~good to you, I will do the following additional tasks:

- add these instructions to the v21.1 docs as well
- add links to these instructions from the various "multi-region foo" pages elsewhere in the docs

Adding a Cloud version will be a separate PR

**Comment by rmloveland** [comment]
Also let me know if I should ask someone else to review instead

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 3 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoP7jV6cT4hUPglg3H:-MqoP7jV6cT4hUPglg3I:b-4sai1y) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L3)):*
> ```Markdown
> ---
> title: Performance Benchmarking with TPC-C
> summary: Learn how to benchmark CockroachDB against TPC-C 13k on 3 nodes on your laptop
> ```

This title seems to be out of place.  I think we need to drop the 13k (as all scale factors are described below) and the "laptop" part too.
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 8 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoPcLW1_hHSWK7Q7TM:-MqoPcLW1_hHSWK7Q7TN:b-nfvry) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L8)):*
> ```Markdown
> ---
> 
> This page shows you how to reproduce [CockroachDB's TPC-C performance benchmarking results](performance.html#scale) on commodity AWS hardware. Across all scales, CockroachDB can process tpmC (new order transactions per minute) at near maximum efficiency. Start by choosing the scale you're interested in:
> ```

Nit: "on commodity AWS hardware" seems stale, since there are laptops mentioned below as well.

Also, do we want more of an intro here as to what we're doing?  This is simulating a MR setup with 9 nodes in 3 separate regions, blah, blah, blah?
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 15 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoQPgnAD9K7zBdN7B9:-MqoQPgnAD9K7zBdN7BA:bjq5wnr) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L15)):*
> ```Markdown
>   <a href="performance-benchmarking-with-tpcc-small.html"><button class="filter-button">Small</button></a>
>   <a href="performance-benchmarking-with-tpcc-medium.html"><button class="filter-button">Medium</button></a>
>   <a href="performance-benchmarking-with-tpcc-large.html"><button class="filter-button">Large</button></a>
> ```

Nit: When you click on these different buttons, the table below stays the same.  I'm not sure if that's what we want (I could see an argument for it being the correct behaviour), so I just wanted to make sure that this was intentional.
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoRu0V-H3LNoXVb4qw:-MqoRu0W4UWYFa9ES7ZV:b-hnnjta) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L65)):*
> ```Markdown
> ## Step 3. Run the benchmark
> 
> Run the workload for ten "warehouses" of data for ten minutes. In order to spread the simulated workload across the 3 regions specified in the previous step, you will need to start each of the following commands from 3 different terminals:
> ```

Can we do it from the same terminal by backgrounding the processes (using `&`)?  Also, we probably want customers to route the output to a file, so that it doesn't overwhelm the terminal.
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 144 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoSEbW6ny9-UNs7noL:-MqoSEbW6ny9-UNs7noM:b-473cn0) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L144)):*
> ```Markdown
> ~~~
> _elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
>   600.0s       49.1  38.2%    170.6     44.0    536.9    872.4   1543.5   3087.0
> ```

Something's wrong here.  With three partitions, we shouldn't see efficiency above 33.3%.  Is it possible you ran this and set the waiting flag to false?
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoScfcD5CufrQydI21:-MqoScfd3rCiNxnAvF0c:b-4kpmkj) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L161)):*
> ```Markdown
> ~~~
> 
> You will also see some audit checks and latency statistics for each individual query in each terminal. Some of those checks might indicate that they were `SKIPPED` due to insufficient data since this is a small run on a small machine. For a more comprehensive test, run `workload` for a longer duration (e.g., two hours). The `tpmC` (new order transactions/minute) number is the headline number and `efc` ("efficiency") tells you how close CockroachDB gets to theoretical maximum `tpmC`.
> ```

We might want to add here "in a perfect execution, the sum of the efficiency across all partitions would be 100%".

**Review by ajstorm — COMMENTED** [review]
:lgtm: 

If you're looking for a second set of eyes, I'd recommend @otan, as he did much of this work in 21.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12530#-:-Mr-dYQz0zNSxfyMGVJu:bxsp1rs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoRu0V-H3LNoXVb4qw:-Mr-Z9Ps-tTyHvH-Q-Sx:b-b1b9e0) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L65)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

I'd kinda rather not because even though this is clunky (and you're right, it is :-} ) I think it's better than the alternative: if the user is Good At UNIX (tm) they can just do this for themselves if they want to; and if they are not good at it I don't think we should try to teach them both how to run these commands and also do UNIX things etc.  Maybe another way of saying it is that I'd rather not mix concerns in this doc of how the user runs these commands vs how they choose to admin their desktop/terminal emulators for tidiness or lack thereof.  A nice property of multiple terminals (though clunky) is the spatial awareness of "I am running 5 different things" without us having to get into job control etc
</blockquote></details>

That's all fair.  What I'm mildly worried about is that users that are comfortable with UNIX will think "this is clunky".  Just a mild concern though, and I could buy an argument that we shouldn't over-index to super-users.
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 144 at r1](https://reviewable.io/reviews/cockroachdb/docs/12530#-MqoSEbW6ny9-UNs7noL:-Mr-cOHe01qMMSNb1Kl2:b-qh3fp) ([raw file](https://github.com/cockroachdb/docs/blob/f909e968701ec0c187190a4c41ea17ed942d1136/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L144)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

No idea. Pretty sure I just ran what is on the page above, but  I can re-run and see what happens. Possibly an artifact of running against demo?  Also I started these in 1-2-3 order so maybe that did something?  Anyway I'll try again, thanks for that info, I did not know that

Update:

This happened again, I got: 36.8, 27.8, 27.9.  For the purposes of this docs PR I edited the first value on the page to be 33.2%.  Let me know if I should file something, or if we think this is just an artifact of `demo` or running on MBP or similar
</blockquote></details>

I can confirm that this is happening on my setup too.  It seems like a bug though.  I've opened an issue for it, and am fine with your manual edit for now.

**Review by rmloveland — COMMENTED** [review]
Thanks Adam!  sounds like a good idea, sent up the otan bat signal 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12530#-:-Mr2noOS73xlVQAAuvwV:big77hp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

**Review by ajstorm — COMMENTED** [review]
Just a heads-up that @otan is out for PTO until the end of the year.  You might want to merge now, ask questions later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12530#-:-Mr33wtCCM-kKxM-qO7u:b-tps5ru)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

**Review by ericharmeling — APPROVED** [review]
Pretty much LGTM! Just a couple nits.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12530#-:-Mr3GJDXC8bjmSLP3Ivv:b-wgeeqi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @rmloveland)

___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 65 at r2](https://reviewable.io/reviews/cockroachdb/docs/12530#-Mr3E54r88QA7XrKoTYH:-Mr3E54r88QA7XrKoTYI:b-y8umf4) ([raw file](https://github.com/cockroachdb/docs/blob/00970a2c73aec4732f0e87a7ca1c5e8478e3f53f/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L65)):*
> ```Markdown
> ## Step 3. Run the benchmark
> 
> Run the workload for ten "warehouses" of data for ten minutes. In order to spread the simulated workload across the 3 regions specified in the previous step, you will need to start each of the following commands from 3 different terminals:
> ```

nit:

Above you use `10 "warehouses"`. Probably best to use `10 "warehouses"` here too, instead of `ten "warehouses"`.



_Code quote:_
```Markdown
ten "warehouses"
```
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 96 at r2](https://reviewable.io/reviews/cockroachdb/docs/12530#-Mr3Ew9WCHaee2iAA-HQ:-Mr3Ew9WCHaee2iAA-HR:b-40p3ku) ([raw file](https://github.com/cockroachdb/docs/blob/00970a2c73aec4732f0e87a7ca1c5e8478e3f53f/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L96)):*
> ```Markdown
> --survival-goal zone \
> --regions=europe-west1,us-east1,us-west1 \
> 'postgresql://root@127.0.0.1:26257/tpcc?sslmode=disable'
> ```

No idea if it makes any difference with the simulated multi-region cluster, but wouldn't you want to use different gateway nodes for the different workloads? 

Like shouldn't the urls for the terminal 3 and terminal 4 workloads be `'postgresql://root@127.0.0.1:26260/tpcc?sslmode=disable'` and `'postgresql://root@127.0.0.1:26263/tpcc?sslmode=disable'`?

(Kinda like [here](https://www.cockroachlabs.com/docs/v21.2/demo-low-latency-multi-region-deployment.html#step-2-determine-node-locations))



_Code quote:_
```Markdown
'postgresql://root@127.0.0.1:26257/tpcc?sslmode=disable'
```

**Review by rmloveland — COMMENTED** [review]
Thanks Eric!  I updated things based on your suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12530#-:-Mr3noDO5eXepHFUKfaM:bsy1mwv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @ericharmeling)

___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 65 at r2](https://reviewable.io/reviews/cockroachdb/docs/12530#-Mr3E54r88QA7XrKoTYH:-Mr3m_FlBRM8VUTIYBQH:b-llo5ax) ([raw file](https://github.com/cockroachdb/docs/blob/00970a2c73aec4732f0e87a7ca1c5e8478e3f53f/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L65)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit:

Above you use `10 "warehouses"`. Probably best to use `10 "warehouses"` here too, instead of `ten "warehouses"`.
</blockquote></details>

Updated to 10!
___
*[v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, line 96 at r2](https://reviewable.io/reviews/cockroachdb/docs/12530#-Mr3Ew9WCHaee2iAA-HQ:-Mr3nRQq-DiR3fKpAjH9:b6o1376) ([raw file](https://github.com/cockroachdb/docs/blob/00970a2c73aec4732f0e87a7ca1c5e8478e3f53f/v21.2/performance-benchmarking-with-tpcc-local-multiregion.md#L96)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

No idea if it makes any difference with the simulated multi-region cluster, but wouldn't you want to use different gateway nodes for the different workloads? 

Like shouldn't the urls for the terminal 3 and terminal 4 workloads be `'postgresql://root@127.0.0.1:26260/tpcc?sslmode=disable'` and `'postgresql://root@127.0.0.1:26263/tpcc?sslmode=disable'`?

(Kinda like [here](https://www.cockroachlabs.com/docs/v21.2/demo-low-latency-multi-region-deployment.html#step-2-determine-node-locations))
</blockquote></details>

It probably doesn't matter practically (?) but I agree we should do this 

Updated (and re-ran) with ports `26257`, `26260`, and `26263`

**Pull request merged**
