### PR TITLE
Changed minimum Kubernetes version in K8s tutorial from 1.8 to 1.15

### PR DESCRIPTION
**Pull request by mokaixu**
Fixes: #9072

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
Thanks Monica! Can you actually remove the edits from the v1.1 / v2.0 / v2.1 pages and instead edit v20.1 / v20.2 / v21.1? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9195#-:-MOg9KyiAk2_aeuMpGYy:b-k0s0dz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by mokaixu — COMMENTED** [review]
@lnhsingh

I tried doing the change and without the v1.1/v2.0/v2.1 edits and it looked like the changes weren't reflected for (v20+) docs? Looks like the v2.0 and v2.1 pages `includes` the MD file for v20.1 / v20.2 / v21.1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9195#-:-MOgyV-p8k94GEwSd7Re:bvq49dg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mokaixu)

**Review by lnhsingh — COMMENTED** [review]
@mokaixu :thinking: hmm that seems weird! Did you try updating the `_includes/v21.1/orchestration/kubernetes-limitations.md` file and seeing if that would update the v21.1 file? That would be expected to work but lmk if you see something else happening

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9195#-:-MOh0rsg6KOkqBf_TF8a:bt477qc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mokaixu)

**Review by mokaixu — COMMENTED** [review]
I have removed changes for v1.1/2.0/2.1 files and it looks like the changes are reflected! Please let me know if I need to address anything else :)

The problem I was running into earlier was:
0) Builds docs repo and goes to localhost URL in browser
1) Searches Kubernetes in search bar of website deployed locally
2) clicks the Kubernetes orchestration ... multiple cluster result
3) it redirects me to the cockroach website in PROD (https://www.cockroachlabs.com/docs/) instead of localhost:4000

but I'm assuming that should be fixed once everything is deployed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9195#-:-MOhafaE4rKKGbh6Xc-Q:bouqbx7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mokaixu)

**Comment by lnhsingh** [comment]
These changes LGTM, I'll merge them. Thanks for this fix, Monica! 🎉 

And ahh, that makes sense-- yeah the search bar in the preview site still points to our live search index, which then returns the PROD links. If you need to navigate to a page in the local site, you unfortunately have to manually enter the URL

**Pull request merged**
