### PR TITLE
Clarify description for SHOW GRANTS

### PR DESCRIPTION
**Pull request by thtruo**
Address feedback noted in #8452 to clarify that `SHOW GRANTS` will list grants for all users and roles on the _current_ database and its tables, _not_ all databases and tables as was previously documented.

Updated for v21.1, v20.2, and v20.1

### CODE REVIEW

**Comment by thtruo** [comment]
One more fixit item for ya @lnhsingh!

**Review by lnhsingh — COMMENTED** [review]
Thanks Tommy! I think the edit should also be applied to `v20.1/show-databases.md`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9199#-:-MOgAOFD9igiS1xdNyWy:befaqwj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by thtruo** [comment]
Thanks for the heads up @lnhsingh. I'm not sure if I'm following the proper github workflow, but I put up another small PR to address your note here: https://github.com/cockroachdb/docs/pull/9203

**Comment by lnhsingh** [comment]
Thanks @thtruo! Normally, you would update and push to the same branch so all of the edits show up in the same PR, but I think it's ok how you did it for this small edit!

**Pull request merged**
