### PR TITLE
docs on show constraints statement

### LINKED ISSUE #521: SHOW CONSTRAINTS statement
https://github.com/cockroachdb/cockroach/pull/7584

### PR DESCRIPTION
**Pull request by jseldess**
This PR adds docs on the `SHOW CONSTRAINT` statement. Fixes #521.

HTML version here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ac93df39a27eed858da4f66cb1379724cd98ff2d/show-constraints.html

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/520)

### CODE REVIEW

**Comment by jseldess** [comment]
@dt, while documenting this, I found that `NOT NULL` and `DEFAULT` constraints are missing from the response. See https://github.com/cockroachdb/cockroach/pull/7584.

**Comment by dt** [comment]
It should include any *named* `NOT NULL`/`DEFAULT` constraints. I started it since I wanted a way to list the named constraints (those that I could refer to in an ALTER or DROP, etc). I'm starting to think we should just generate names for every constrain all the time so that all constraints have names, but until then, I think that's what you're seeing.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[show-constraints.md, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/520#-KO78j_Oc1a3-cy5A4bv:-KO78j_Ptc_bJtyBLni-:354615251) ([raw file](https://github.com/cockroachdb/docs/blob/fa8cbf861d9bfa3e30488bec2abd202edac1290a/show-constraints.md#L31)):*
> ```Markdown
> ## Response
> 
> The following fields are returned for each constraint. 
> ```

let's throw a little banner in here saying that this is under development and the exact output will continue change? I don't want anyone relying on anything in here having a particular value or form just yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/520#-:-KO79Kxr81QuRDB7u5_I:-11657876)*

**Comment by dt** [comment]
:lgtm: mod putting a warning about the specific output of `SHOW CONSTRAINTS` not being something to rely on.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/520#-:-KO79kHtK22rXVjC5pLs:990823920)*

**Comment by jseldess** [comment]
Thanks, @dt. I updated the intro to clarify that the statement returns all named constraints and any unnamed check constraints. Let me know if something's still missing.   

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[show-constraints.md, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/520#-KO78j_Oc1a3-cy5A4bv:-KP3Wd7Kk4AA6vdqPr3l:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fa8cbf861d9bfa3e30488bec2abd202edac1290a/show-constraints.md#L31)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> let's throw a little banner in here saying that this is under development and the exact output will continue change? I don't want anyone relying on anything in here having a particular value or form just yet.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/520#-:-KP3WeP6FBSNVDWoa5i6:bv0o83q)*

**Pull request merged**
