### PR TITLE
Configuring replication zones

### PR DESCRIPTION
**Pull request by jseldess**
First draft of docs on configuring replication zones. Want to know what I've missed or got wrong, obviously, but also ideas for how to make this content clearer or easier to digest. Also welcome ideas for more helpful or realistic examples.

@petermattis, @bdarnell, @spencerkimball 

Pushed content to aws in case html version is easier to read: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/configure-replication-zones.html

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/189)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[configure-replication-zones.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpymBIGu8892yrRNH:-KEHpymBIGu8892yrRNI:167121669) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L30)):*
`s/it uses a replication/it uses the replication/g`? I'm not sure about this, but I think when we're talking about the replication zone for a table or database the grammar should be `the replication zone`. Feel free to correct me about this if I'm wrong.

---

*[configure-replication-zones.md, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHoAws8C2VyzS0_Wy2:-KEHoAws8C2VyzS0_Wy3:-777970264) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L34)):*
`s/is in/is specified in/g`

---

*[configure-replication-zones.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHoKD2Jpf9kpM7S01p:-KEHoKD2Jpf9kpM7S01q:-740747135) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L46)):*
Rather than say "randomly choose", I think this should read: `the replica can be placed on any node in the cluster`.

We should probably also mention that the number of replicas should be odd as otherwise we can encounter situations where both sides of a network partition can form a quorum. In fact, we should just disallow even number of replicas. Do you mind filing a bug about that?

`s/no specific attributes/no attributes/g`

---

*[configure-replication-zones.md, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHohgzcOg6O2PeeiUN:-KEHohgzcOg6O2PeeiUO:612223101) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L49)):*
`s/a zone/the zone/g`

`ttlseconds` is implemented, but I don't think we should document it yet as we have no means of accessing older versions. 

---

*[configure-replication-zones.md, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpH2k_w7Ha7t38ulv:-KEHpH2k_w7Ha7t38ulw:-1355246231) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L161)):*
I think you should use single quote shell strings (i.e. `'`) instead of double quote to avoid any possibility of weird expansion.

No need to specify `--insecure` any more.

---

*[configure-replication-zones.md, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpYg5cnSIBpVWu7Ie:-KEHpYg5cnSIBpVWu7If:1525143803) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L239)):*
Perhaps `zone set` should echo the full zone config that was set so that the user doesn't need to `zone get` to see it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Comment by jseldess** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[configure-replication-zones.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpymBIGu8892yrRNH:-KEHzg_YjmOuqm6iBDua:-1581303452) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L30)):*
Yep, fixing with next commit.

---

*[configure-replication-zones.md, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHoAws8C2VyzS0_Wy2:-KEHziVEv9TpXgSOxNdu:893581110) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L34)):*
Fixing with next commit.

---

*[configure-replication-zones.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHoKD2Jpf9kpM7S01p:-KEI0yPhC2Ic941N_Hb3:1671081357) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L46)):*
Ok, changing this with next commit. I think "the replica can be placed on any node" is a little ambiguous in terms of who is taking that action (cockroach or user), but not a big deal. 

Filed bug to disallow even number of replicas in a zone: https://github.com/cockroachdb/cockroach/issues/5809

---

*[configure-replication-zones.md, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHohgzcOg6O2PeeiUN:-KEI-IsZixs_NbaOTDsS:-1268417763) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L49)):*
OK, can you explain what `ttlseconds` is again? Would like to provide something basic.

---

*[configure-replication-zones.md, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpH2k_w7Ha7t38ulv:-KEI-ea7EO50Rzl_He6X:426247005) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L161)):*
Fixing throughout with next commit.

In terms of `--insecure`, though, these examples are implicitly multi-machine, so you would need `--insecure`, right?

---

*[configure-replication-zones.md, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpYg5cnSIBpVWu7Ie:-KEI08BXy7BHtV-V9N7i:886889739) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L239)):*
Done with next commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[configure-replication-zones.md, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHohgzcOg6O2PeeiUN:-KEI53l_x524Arr5rVHV:-60667917) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L49)):*
We store multiple versions of a value for each key in our low-level KV storage. `ttlseconds` controls how long a version will be kept around after it has been replaced by a newer version. The default setting keeps old versions around for 1 day before deleting them.

---

*[configure-replication-zones.md, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpH2k_w7Ha7t38ulv:-KEI5P8_yLXBsLufYRlI:-1601066795) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L161)):*
Ah, excellent point. I retract my comment.

---

*[configure-replication-zones.md, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpYg5cnSIBpVWu7Ie:-KEI5WAPuOUZqit5jBR5:1651007552) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L239)):*
Well, this will need to be done in the code. Can you file an issue?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/189#-:-KEI5apmnvl9omPLYNsg:1417088721)*

**Comment by jseldess** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[configure-replication-zones.md, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpymBIGu8892yrRNH:-KEI2E8ql0VL8s0enx9F:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L30)):*
Done.

---

*[configure-replication-zones.md, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHohgzcOg6O2PeeiUN:-KEI9zXhCfBPaVPtO1Mm:-1055531392) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L49)):*
Thanks. I'll say something vague for now.

---

*[configure-replication-zones.md, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpYg5cnSIBpVWu7Ie:-KEI8nB-dxfLziJLLqqE:-992631148) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L239)):*
Don't understand. What needs to be done in the code?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[configure-replication-zones.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHoKD2Jpf9kpM7S01p:-KEIC63gRwG3yaHejObm:686212167) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L46)):*
Replicas are always assigned to nodes by cockroach. While a user can provide guidance, the actual assignment is up to the system.

---

*[configure-replication-zones.md, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpYg5cnSIBpVWu7Ie:-KEICPhNxf4tc4MRyyG7:206910353) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L239)):*
The zone set` command should echo the full zone config that it set. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Comment by jseldess** [comment]
@bdarnell, @petermattis, please check the new **Node/Replica Recommendations** section.

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[configure-replication-zones.md, line 46 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENxN9ahFkhKkAckbg6:-KENxN9ahFkhKkAckbg7:-1830419205) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L46)):*
We should emphasize that even though repeating `attrs: []` looks weird, it's perfectly normal to not have any attributes and it's common that the only thing you'll do with a zone config is change the number of `attrs` lines. People shouldn't feel pressured to "fill in the blanks" with attrs if they don't need them.

Also be aware that we're planning on reworking this interface so you can specify a number of replicas independent of attributes: https://github.com/cockroachdb/cockroach/issues/4868

---

*[configure-replication-zones.md, line 47 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENyF491x2lrJCjueCc:-KENyF491x2lrJCjueCd:-1926951568) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L47)):*
Express the default as 64MB.

---

*[configure-replication-zones.md, line 57 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENyS84m7yn0dT3EpXz:-KENyS84m7yn0dT3EpY-:1290943420) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L57)):*
The previous sentence is good, but I don't like this one as much. I think it would be better to explain why even numbers are bad: "Configurations with odd numbers of replicas are more robust than those with even numbers. Clusters of three and four nodes can each tolerate one node failure and still reach a quorum (2/3 and 3/4 respectively), so the fourth replica doesn't add any extra fault-tolerance. To survive two simultaneous failures, you must have five replicas."

---

*[configure-replication-zones.md, line 197 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEO-Jd1MRQssjx4gMJd:-KEO-Jd1MRQssjx4gMJe:-1676967276) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L197)):*
Attributes should be something that are shared across many machines. With this configuration if one of the nodes went down, the data would be underreplicated until a new node was given the attribute of the downed one. Instead, the attribute should be `ssd` in all cases; the system knows that it needs to find three *different* nodes with the attribute so it won't put all the replicas in one place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/189#-:-KEO08zRFlL8nPPVW0eq:676834233)*

**Comment by jseldess** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[configure-replication-zones.md, line 239 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEHpYg5cnSIBpVWu7Ie:-KEJUmAWPtJSES2NMGOm:1640665016) ([raw file](https://github.com/cockroachdb/docs/blob/4df35c4a56459d1e9694358c1c16a6c88a49df3e/configure-replication-zones.md#L239)):*
Created an issue for this: https://github.com/cockroachdb/cockroach/issues/5819

---

*[configure-replication-zones.md, line 46 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENxN9ahFkhKkAckbg6:-KEOgVWPTPG6oIB5EHIp:536416947) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L46)):*
I'll work on improving that. Thanks, Ben.

---

*[configure-replication-zones.md, line 47 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENyF491x2lrJCjueCc:-KEOe2VsvtKDRCBmAo3U:1167458077) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L47)):*
Will do, Ben. But does this mean that the field accepts any bytes-based unit, with the suffix required for anything but straight bytes?

---

*[configure-replication-zones.md, line 57 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENyS84m7yn0dT3EpXz:-KEOeqoDsiDljyTmxcQl:1953206668) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L57)):*
This is excellent, Ben. Thanks!

---

*[configure-replication-zones.md, line 197 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KEO-Jd1MRQssjx4gMJd:-KEOmdXZVZuAq77CrvOn:66437425) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L197)):*
Makes sense. Fixing with next commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Comment by bdarnell** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[configure-replication-zones.md, line 47 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENyF491x2lrJCjueCc:-KERIA3y2rl-3Ka5J6uu:-1459730868) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L47)):*
I don't think it does, but it probably should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Comment by jseldess** [comment]
*[configure-replication-zones.md, line 47 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/docs/189#-KENyF491x2lrJCjueCc:-KES5Ut2ZKPvtuVekTgt:592432257) ([raw file](https://github.com/cockroachdb/docs/blob/979f533d34175541a4e99f6ee76db09d40b5d5a7/configure-replication-zones.md#L47)):*
Opened an issue for this: https://github.com/cockroachdb/cockroach/issues/5828

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/189)*

**Pull request merged**
