### PR TITLE
Add row_limit import option and examples

### PR DESCRIPTION
**Pull request by gemma-shay**
- Add row_limit option to IMPORT options table
- Add row_limit with CSV example to IMPORT examples
- Added row_limit option info & example to all relevant migration pages (CSV, Avro, Postgres, Mysql, Oracle)

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
A couple of nits from a language / consistency perspective but otherwise LGTM. You can send to eng review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9665#-:-MSYyPQL9i7RQjjdhz0m:b-7dtrdd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[v21.1/import.md, line 105 at r1](https://reviewable.io/reviews/cockroachdb/docs/9665#-MSYx0c3DC7LNL5RYk5U:-MSYx0c3DC7LNL5RYk5V:b-2ol4tx) ([raw file](https://github.com/cockroachdb/docs/blob/ed1dba0079874ced0a1dce19911975845337f457/v21.1/import.md#L105)):*
> ```Markdown
> `skip`                 | `CSV DATA `, [`DELIMITED DATA`](#delimited-data-files) | The number of rows to be skipped while importing a file. **Default: `'0'`**.
> `decompress`           | General         | The decompression codec to be used: `gzip`, `bzip`, `auto`, or `none`.  **Default: `'auto'`**, which guesses based on file extension (`.gz`, `.bz`, `.bz2`). `none` disables decompression.
> `row_limit`           | General         |<span class="version-tag">New in v21.1:</span> The number of rows to import. Useful for doing a test run of an import and finding errors quickly. For non-bundled formats, setting `row_limit = "n"` will import the first *n* rows of a table. For bundled formats, this option will import the first *n* rows from each table in the dump file.
> ```

nit: I think you can use double quotes or single quotes in `row_limit = "n"` interchangeably, but I would keep this consistent across all definitions and your example section below
___
*[v21.1/import.md, line 528 at r1](https://reviewable.io/reviews/cockroachdb/docs/9665#-MSYxriP1QUZ2I6RdwIx:-MSYxh_S3kj6CI-Q0C76:bgz642p) ([raw file](https://github.com/cockroachdb/docs/blob/ed1dba0079874ced0a1dce19911975845337f457/v21.1/import.md#L528)):*
> ```Markdown
> ### Import a limited number of rows
> 
> <span class="version-tag">New in v21.1:</span> The `row_limit` option determines the number of rows to import. For non-bundled formats, setting `row_limit = "n"` will import the first *n* rows of a table. For bundled formats, this option will import the first *n* rows from each table in the dump file. It is useful for finding errors quickly before executing a more time-consuming import. The examples below use CSV data, but `row_limit` is also an option for [Avro files](migrate-from-avro.html#step-3-import-the-avro), [delimited data files](#import-a-delimited-data-file), [Postgres dump files](migrate-from-postgres.html#row-limit), and [MySQL dump files](migrate-from-mysql.html#row-limit).
> ```

nit: `time- and resource-consuming full import` maybe?
nit: add a line break before the last sentence

**Review by adityamaru — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[v21.1/import.md, line 528 at r2](https://reviewable.io/reviews/cockroachdb/docs/9665#-MTfCq8v4UKK205SDefG:-MTfCq8v4UKK205SDefH:b-tj3ab6) ([raw file](https://github.com/cockroachdb/docs/blob/4effc40a1a5afca6dc0a190466ae89841d172c46/v21.1/import.md#L528)):*
> ```Markdown
> ### Import a limited number of rows
> 
> <span class="version-tag">New in v21.1:</span> The `row_limit` option determines the number of rows to import. For non-bundled formats, setting `row_limit = 'n'` will import the first *n* rows of a table. For bundled formats, this option will import the first *n* rows from each table in the dump file. It is useful for finding errors quickly before executing a more time- and resource-consuming import. 
> ```

It might be worth adding that the imported table(s) can then be inspected for their schema and data, and need to be dropped before running the actual import.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[v21.1/import.md, line 528 at r2](https://reviewable.io/reviews/cockroachdb/docs/9665#-MTfCq8v4UKK205SDefG:-MTgv7gHDBp_TIBltRP7:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/4effc40a1a5afca6dc0a190466ae89841d172c46/v21.1/import.md#L528)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

It might be worth adding that the imported table(s) can then be inspected for their schema and data, and need to be dropped before running the actual import.
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9665#-:-MTk_U9P34rdjplkEfLZ:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Pull request merged**
