### PR TITLE
v20.2 REVOKE updates

### PR DESCRIPTION
**Pull request by ericharmeling**
Related to #8808.

### CODE REVIEW

**Comment by ericharmeling** [comment]
@ajwerner Friendly ping on review. 

Would like to get these docs merged by the marketing release Tuesday. LMK if I should request review from another engineer. Thanks! :)

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Hmm, maybe somebody who worked on this should look. @solongordon can you nominate somebody. I can give it a pass but I don't have all of the changes here paged in. Same for https://github.com/cockroachdb/docs/pull/8808. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8817#-:-MLTTPtZAsq4JQf-EH3e:b-iv56ce)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ericharmeling** [comment]
@ajwerner Just going to pass this to writer review, as the official release day is tomorrow.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8817#-:-MLiKxz0DM7p-Gu-Y7an:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v20.2/revoke.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/8817#-MLiKp1gCWmAGtjY4tLP:-MLiKp1gCWmAGtjY4tLQ:b-gwxdv4) ([raw file](https://github.com/cockroachdb/docs/blob/614238e5d8ce53975d614d5c0ba543dd94353222/v20.2/revoke.md#L48)):*
> ```Markdown
> The user revoking privileges must have the `GRANT` privilege on the target [database](create-database.html), [schema](create-schema.html), [table](create-table.html), or [user-defined type](enum.html).
> 
>  In addition to the `GRANT` privilege, the user revoking privileges must have the privilege being revoked on the target object. For example, a user revoking the `SELECT` privilege on a table to another user must have the `GRANT` and `SELECT` privileges on that table.
> ```

minor nit: there's an extra space at the front of this line. Feel free to ignore if you don't want to fix - it doesn't change the rendered page.

**Comment by ericharmeling** [comment]
@lnhsingh TFTR!

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8817)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner)

___
*[v20.2/revoke.md, line 48 at r1](https://reviewable.io/reviews/cockroachdb/docs/8817#-MLiKp1gCWmAGtjY4tLP:-MLj1CXC7EtIaoCKJQf_:bt2vr1b) ([raw file](https://github.com/cockroachdb/docs/blob/614238e5d8ce53975d614d5c0ba543dd94353222/v20.2/revoke.md#L48)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

minor nit: there's an extra space at the front of this line. Feel free to ignore if you don't want to fix - it doesn't change the rendered page.
</blockquote></details>

Fixed.

**Pull request merged**
