### PR TITLE
Updated changefeed `initial_scan` option with values

### PR DESCRIPTION
**Pull request by kathancox**
Fixes [DOC-3121](https://cockroachlabs.atlassian.net/browse/DOC-3121) and [DOC-3253](https://cockroachlabs.atlassian.net/browse/DOC-3253)

Updated the `initial_scan` option with the unified values in 22.1. Changes apply to `CREATE CHANGEFEED` and `ALTER CHANGEFEED` page. The values are now `yes` `no` `only` instead of the separate keys `initial_scan` `no_initial_scan` `initial_scan_only`.

### CODE REVIEW

**Review by HonoreDB — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

___
*[`v22.1/create-changefeed.md` line 136 at r1](https://reviewable.io/reviews/cockroachdb/docs/13831#-N2NPjPoDgQyBrWM2z21:-N2NPjPoDgQyBrWM2z22:b-mzwwae) ([raw file](https://github.com/cockroachdb/docs/blob/6def21bf7c8d0513d6e63788da719d2482a0d8d2/v22.1/create-changefeed.md#L136)):*
> ```Markdown
> <a name="schema-events"></a>`schema_change_events` | `default` / `column_changes` |  The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> <a name="schema-policy"></a>`schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills. The changefeed will still emit any duplicate records for the table being altered, but will not emit the new schema records. </li><li>`stop`: [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> <a name="initial-scan"></a>`initial_scan` | `yes`/`no`/`only` |  Control whether or not an initial scan will occur at the start time of a changefeed. `initial_scan ='yes'` and `initial_scan = 'no'` cannot be used simultaneously. If neither `initial_scan = 'yes'` nor `initial_scan = 'no'` is specified, an initial scan will occur if there is no [`cursor`](#cursor-option), and will not occur if there is one. This preserves the behavior from previous releases.<br><br>Default: `initial_scan = 'yes'` <br>If used in conjunction with `cursor`, an initial scan will be performed at the cursor timestamp. If no `cursor` is specified, the initial scan is performed at `now()`.
> ```

I think this section needs to be restructured a bit more to take into account `only`. Something like `Only one initial_scan option ('yes', 'no', or 'only') can be used. If none of these are set, an initial scan will occur if...` Also may be necessary to mention that we still support the initial_scan, no_initial_scan, and initial_scan_only for backwards compatibility, and those forms also can't be combined with the new ones.

**Comment by kathancox** [comment]
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13831)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)
> 
> _[`v22.1/create-changefeed.md` line 136 at r1](https://reviewable.io/reviews/cockroachdb/docs/13831#-N2NPjPoDgQyBrWM2z21:-N2NPjPoDgQyBrWM2z22:b-mzwwae) ([raw file](https://github.com/cockroachdb/docs/blob/6def21bf7c8d0513d6e63788da719d2482a0d8d2/v22.1/create-changefeed.md#L136)):_
> 
> > ```gfm
> > <a name="schema-events"></a>`schema_change_events` | `default` / `column_changes` |  The type of schema change event that triggers the behavior specified by the `schema_change_policy` option:<ul><li>`default`: Include all [`ADD COLUMN`](add-column.html) events for columns that have a non-`NULL` [`DEFAULT` value](default-value.html) or are [computed](computed-columns.html), and all [`DROP COLUMN`](drop-column.html) events.</li><li>`column_changes`: Include all schema change events that add or remove any column.</li></ul><br>Default: `schema_change_events=default`
> > <a name="schema-policy"></a>`schema_change_policy` | `backfill` / `nobackfill` / `stop` |  The behavior to take when an event specified by the `schema_change_events` option occurs:<ul><li>`backfill`: When [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill) are finished, output all watched rows using the new schema.</li><li>`nobackfill`: For [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), perform no logical backfills. The changefeed will still emit any duplicate records for the table being altered, but will not emit the new schema records. </li><li>`stop`: [schema changes with column backfill](use-changefeeds.html#schema-changes-with-column-backfill), wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred. An `error: schema change occurred at <timestamp>` will display in the `cockroach.log` file.</li></ul><br>Default: `schema_change_policy=backfill`
> > <a name="initial-scan"></a>`initial_scan` | `yes`/`no`/`only` |  Control whether or not an initial scan will occur at the start time of a changefeed. `initial_scan ='yes'` and `initial_scan = 'no'` cannot be used simultaneously. If neither `initial_scan = 'yes'` nor `initial_scan = 'no'` is specified, an initial scan will occur if there is no [`cursor`](#cursor-option), and will not occur if there is one. This preserves the behavior from previous releases.<br><br>Default: `initial_scan = 'yes'` <br>If used in conjunction with `cursor`, an initial scan will be performed at the cursor timestamp. If no `cursor` is specified, the initial scan is performed at `now()`.
> > ```
> 
> I think this section needs to be restructured a bit more to take into account `only`. Something like `Only one initial_scan option ('yes', 'no', or 'only') can be used. If none of these are set, an initial scan will occur if...` Also may be necessary to mention that we still support the initial_scan, no_initial_scan, and initial_scan_only for backwards compatibility, and those forms also can't be combined with the new ones.

Good point @HonoreDB! I totally missed giving any description on `only`. I have added to this and included the other comments you made.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

**Review by andf-crl — APPROVED** [review]
LGTM with one question and one nit. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13831#-:-N2SJfJJ8MPHl5e-ChhR:bihk4sd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @kathancox)

___
*[`v22.1/alter-changefeed.md` line 236 at r2](https://reviewable.io/reviews/cockroachdb/docs/13831#-N2SJ5Ew7UgrsVbSGb_3:-N2SJ5Ew7UgrsVbSGb_4:b-a323v7) ([raw file](https://github.com/cockroachdb/docs/blob/b06b9e0832770b79227274d42b21d34b1d6ba06d/v22.1/alter-changefeed.md#L236)):*
Question: Options section above mentions that `only` is unsupported for `ALTER`; should this just be: 

> when it is set to 'yes'
___
*[`v22.1/create-changefeed.md` line 136 at r2](https://reviewable.io/reviews/cockroachdb/docs/13831#-N2SGjbyDeCQR46JB89o:-N2SGjbyDeCQR46JB89p:bxtbefd) ([raw file](https://github.com/cockroachdb/docs/blob/b06b9e0832770b79227274d42b21d34b1d6ba06d/v22.1/create-changefeed.md#L136)):*
nit: `only` phrasing could suggest that the difference is "scan + status report" rather than "scan - (minus) changefeed job". Tiny addition like the following could help to clarify:

>  ... the changefeed job will end with a successful status (`succeeded`) after the initial scan completes, without creating the changefeed.

**Review by amruss — APPROVED** [review]
LGTM

**Pull request merged**
