### PR TITLE
v20.1.6 release notes

### LINKED ISSUE #7985: v20.1.6 Release Notes
Prep date: 9/17/20
Release date: 9/24/20
SHA: `be8c0a720e98a147263424cc13fc9bfc75f46013`
Release Manager: @arulajmani
Issue: https://github.com/cockroachdb/cockroach/issues/54507 

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [ ] Run script to generate release notes
- [ ] Update docs site
- [ ] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7985. 
Fixes #8430.

### CODE REVIEW

**Comment by arulajmani** [comment]
The 20.1.6 release is supposed to come out on Thursday (not yesterday, the calendar reflected the wrong dates). Should we stash this PR until the qualification process completes and the release is ready to go? Seems like the release date on this will require updating.

**Comment by ericharmeling** [comment]
@arulajmani 

I'll update the dates after the qualification is complete. If the SHA changes, I can update the notes as well.

**Comment by ericharmeling** [comment]
@arulajmani 
Updated the dates.

@dbist 
Added TA-54418 to second commit (https://github.com/cockroachdb/docs/pull/8435/commits/64d3a76d9757c7f8feb312847ee8b85933b58be5). Feel free to add any others who want to review.

**Review by arulajmani — APPROVED** [review]

**Review by lnhsingh — COMMENTED** [review]
LGTM, once the nits are fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8435#-:-MI0vbFN3-QpN2ZIJDyf:bas6pab)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dbist, @ericharmeling, and @lnhsingh)

___
*[releases/v20.1.6.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/8435#-MI0uY7a74UXLyLnKhqk:-MI0uY7a74UXLyLnKhql:bgbm76e) ([raw file](https://github.com/cockroachdb/docs/blob/64d3a76d9757c7f8feb312847ee8b85933b58be5/releases/v20.1.6.md#L43)):*
> ```Markdown
> ### SQL language changes
> 
> - The concurrency of the evaluation of [UNION ALL](../v20.1/selection-queries.html#union-combine-two-queries) queries has been reduced. Previously, such queries could crash a server (in extreme cases, due to memory shortage). That bug is now fixed, at the expense of possible minor reduction in performance. [#53444][#53444]
> ```

nit: `UNION ALL`
___
*[releases/v20.1.6.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/8435#-MI0v64ZDZ3sB94JDfSJ:-MI0v64ZDZ3sB94JDfSK:b-u4347d) ([raw file](https://github.com/cockroachdb/docs/blob/64d3a76d9757c7f8feb312847ee8b85933b58be5/releases/v20.1.6.md#L60)):*
> ```Markdown
> - Fixed a bug that allowed new types to be used in an [array type](../v20.1/array.html) during a [version upgrade](../v20.1/upgrade-cockroach-version.html). [#53962][#53962]
> - Database [creation](../v20.1/create-database.html) and [deletion](../v20.1/drop-database.html) was previously not correctly tracked by `revision_history` cluster backups. This is now fixed. [#53806][#53806]
> - Fixed two bugs that caused CockroachDB to return errors when attempting to add [constraints](../v20.1/constraints.html) in the same transaction in which the table was created: 1. Adding a [`NOT NULL` constraint](../v20.1/not-null.html) no longer fails with the error `check ... does not exist`. 2. Adding a `NOT VALID` [foreign key constraint](../v20.1/foreign-key.html) no longer fails with the internal error `table descriptor is not valid: duplicate constraint name`. [#54288][#54288]
> ```

The `1.` and `2.` should start new sub-bullets (I think it's fine to change these to bullets if you can't get the numbered list to nest)
___
*[releases/v20.1.6.md, line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/8435#-MI0vNO77KH5iPs2TzZb:-MI0vNO77KH5iPs2TzZc:b-qmn78q) ([raw file](https://github.com/cockroachdb/docs/blob/64d3a76d9757c7f8feb312847ee8b85933b58be5/releases/v20.1.6.md#L63)):*
> ```Markdown
> - Fixed a bug that could lead to out-of-memory errors when [dropping](../v20.1/drop-table.html) large numbers of tables at a high frequency. [#54285][#54285]
> - CockroachDB could previously crash in rare circumstances when many queries running in the cluster were consuming a lot of memory and at least one query was running through the [vectorized execution engine](../v20.1/vectorized-execution.html). This is now fixed. [#54406][#54406]
> - In releases v20.1.4 and v20.1.5, CockroachDB might finish [`UPSERT`](../v20.1/upsert.html) operations too early. A simple `UPSERT` would correctly insert up to 10,000 rows and then ignore the rest. An `UPSERT` with a `RETURNING` clause would process up to 10,000 rows but return no rows. [#54418][#54418]
> ```

Maybe also include a `For more information, see the [Technical Advisory](link-to-advisory).` at the end?

**Review by ericharmeling — COMMENTED** [review]
@lnhsingh 
Thanks for getting to this so quickly!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8435#-:-MI0xGO76BbwE5FTULtV:b4x0tcs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dbist and @lnhsingh)

___
*[releases/v20.1.6.md, line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/8435#-MI0uY7a74UXLyLnKhqk:-MI0wnXm8A_MK70Dyf8A:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/64d3a76d9757c7f8feb312847ee8b85933b58be5/releases/v20.1.6.md#L43)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: `UNION ALL`
</blockquote></details>

Done.
___
*[releases/v20.1.6.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/8435#-MI0v64ZDZ3sB94JDfSJ:-MI0xhdTBHqBM7cMQ5qa:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/64d3a76d9757c7f8feb312847ee8b85933b58be5/releases/v20.1.6.md#L60)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

The `1.` and `2.` should start new sub-bullets (I think it's fine to change these to bullets if you can't get the numbered list to nest)
</blockquote></details>

Done.
___
*[releases/v20.1.6.md, line 63 at r1](https://reviewable.io/reviews/cockroachdb/docs/8435#-MI0vNO77KH5iPs2TzZb:-MI0wyljBbdVGXH56ub2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/64d3a76d9757c7f8feb312847ee8b85933b58be5/releases/v20.1.6.md#L63)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Maybe also include a `For more information, see the [Technical Advisory](link-to-advisory).` at the end?
</blockquote></details>

Done.

**Comment by jseldess** [comment]
@lnhsingh, just FYI, took a look, and I don't think we need to generate any docs issues from these notes.

**Pull request merged**
