### PR TITLE
consolidate external URL docs

### LINKED ISSUE #2170: storageccl: add setting for GCS key
PR: https://github.com/cockroachdb/cockroach/pull/19018

From release notes:
> A new cluster setting `cloudstorage.gs.default.key` can be used to store authentication credentials to be used by `BACKUP` and `RESTORE`.

### LINKED ISSUE #2400: sqlccl: include http's configured custom CA setting when using custom s3 endpoints
From release notes:

> When using HTTPS storage for IMPORT/BACKUP/RESTORE, a custom CA for HTTPS storage providers can now be specified via the cloudstorage.http.custom_ca cluster setting. This is also used when accessing custom s3 export storage endpoints.

PR: https://github.com/cockroachdb/cockroach/pull/21404

### PR DESCRIPTION
**Pull request by mjibson**
Also update with GCS and custom CA settings/params.

Fixes #2170
Fixes #2400

### CODE REVIEW

**Comment by jseldess** [comment]
:lgtm:, with one nit. Thanks, @mjibson.

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[_includes/external-urls.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/docs/3017#-LAruxGGDNf8bFAj-MO7:-LAruxGGDNf8bFAj-MO8:b-fb4093) ([raw file](https://github.com/cockroachdb/docs/blob/e90c6001496c24a25b47a8d087010e6b771d8b3a/_includes/external-urls.md#L16)):*
> ```Markdown
> #### Considerations
> 
> - <sup>1</sup> If the `AUTH` parameter is empty or `default`, all GCS connections use Google's [default authentication strategy](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application). The `cloudstorage.gs.default.key` cluster setting can be set to the contents of a service account file which will be used during authentication. The `AUTH` parameter can be set to `implicit` to ignore `cloudstorage.gs.default.key` and always use the default strategy.
> ```

Let's make "cluster setting" a link: `[cluster setting](cluster-settings.html)`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3017#-:-LArvdmv6t8l5nwkg_ko:bsun7f5)*

**Comment by dt** [comment]
LGTM, though I think we should go further:

I think we're going to want even more detailed info sections for each provider, and I think this is going to expand beyond what we should include in every page that uses external storage. Maybe the short, concise table makes sense, but I still think we want a first-class page on external storage providers that can discuss each on their own.

**Comment by Amruta-Ranade** [comment]
@dt Yes, that's on my to-do list. Planning to take it up as a Docs project.

**Comment by mjibson** [comment]
@jseldess The build is failing with a log that contain the error `/ is not writable`. Have you seen this before? I've hit re-run twice and it's still failing.

**Comment by mjibson** [comment]
Ah yes! Thanks so much. I can fix this.

**Pull request merged**
