### PR TITLE
Recommend `disallow_full_table_scans` session var

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-7875

### CODE REVIEW

**Comment by rafiss** [comment]
@dikshant do you have thoughts on whether we should recommend passing it in the connection string, versus recommending to configure the default value with `ALTER ROLE ALL SET disallow_full_table_scans = true`?

**Comment by rmloveland** [comment]
> @dikshant do you have thoughts on whether we should recommend passing it in the connection string, versus recommending to configure the default value with `ALTER ROLE ALL SET disallow_full_table_scans = true`?

Thanks for looking @rafiss - I have pushed an update that makes this into a list of options instead:

1. per-cluster setting for all roles using `ALTER ROLE` as you mentioned
2. per-application setting on the connection string (less preferred since it's the number 2 option)

PTAL!

**Comment by rmloveland** [comment]
@rafiss and/or @dikshant - any objection to these latest changes?  sorry to ping, I know I was away from it a bit myself

has a couple linked support issues from DOC-7875 so wanted to get it in

**Comment by dikshant** [comment]
LGTM! Thanks for adding this!

**Review by rafiss — APPROVED** [review]
i like describing both options. lgtm!

**Comment by dikshant** [comment]
Ah I missed this:
> @dikshant do you have thoughts on whether we should recommend passing it in the connection string, versus recommending to configure the default value with ALTER ROLE ALL SET disallow_full_table_scans = true?

Yes let's have both and let customers pick whichever they prefer.

**Review by taroface — APPROVED** [review]

**Pull request merged**
