### PR TITLE
Remove serverless benchmarking page

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Addresses [DOC-9079](https://cockroachlabs.atlassian.net/jira/software/c/projects/DOC/issues/DOC-9079)

### CODE REVIEW

**Review by mdlinville — CHANGES_REQUESTED** [review]
I think you need to add a redirect from the old page to somewhere reasonable, in case users have it bookmarked or come in through a search engine. WDYT?

**Comment by Amruta-Ranade** [comment]
> I think you need to add a redirect from the old page to somewhere reasonable, in case users have it bookmarked or come in through a search engine. WDYT?

I thought about it, but IIUC, we want them to know the content isn't supported anymore. So 404'ing on the page if they have it bookmarked seems like the right UX? The other pages we could send them to are https://www.cockroachlabs.com/docs/v23.1/performance or https://www.cockroachlabs.com/docs/v23.1/performance-best-practices-overview, but that seems misleading if the content they're looking for is Serverless benchmarking  / baseline performance. I don't mind linking to those or other pages if that seems better tho!

**Review by mdlinville — APPROVED** [review]

**Comment by mdlinville** [comment]
> > I think you need to add a redirect from the old page to somewhere reasonable, in case users have it bookmarked or come in through a search engine. WDYT?
> 
> I thought about it, but IIUC, we want them to know the content isn't supported anymore. So 404'ing on the page if they have it bookmarked seems like the right UX? The other pages we could send them to are https://www.cockroachlabs.com/docs/v23.1/performance or https://www.cockroachlabs.com/docs/v23.1/performance-best-practices-overview, but that seems misleading if the content they're looking for is Serverless benchmarking / baseline performance. I don't mind linking to those or other pages if that seems better tho!

Makes sense, thank you for the context. This seems like a reasonable solution.

**Comment by mdlinville** [comment]
> > > I think you need to add a redirect from the old page to somewhere reasonable, in case users have it bookmarked or come in through a search engine. WDYT?
> > 
> > 
> > I thought about it, but IIUC, we want them to know the content isn't supported anymore. So 404'ing on the page if they have it bookmarked seems like the right UX? The other pages we could send them to are https://www.cockroachlabs.com/docs/v23.1/performance or https://www.cockroachlabs.com/docs/v23.1/performance-best-practices-overview, but that seems misleading if the content they're looking for is Serverless benchmarking / baseline performance. I don't mind linking to those or other pages if that seems better tho!
> 
> Makes sense, thank you for the context. This seems like a reasonable solution.

I guess the other option is to leave this old page as a stub that just says this isn't supported anymore, and has a "See Also" section with a few links. WDYT?

**Comment by Amruta-Ranade** [comment]
> > > > I think you need to add a redirect from the old page to somewhere reasonable, in case users have it bookmarked or come in through a search engine. WDYT?
> > > 
> > > 
> > > I thought about it, but IIUC, we want them to know the content isn't supported anymore. So 404'ing on the page if they have it bookmarked seems like the right UX? The other pages we could send them to are https://www.cockroachlabs.com/docs/v23.1/performance or https://www.cockroachlabs.com/docs/v23.1/performance-best-practices-overview, but that seems misleading if the content they're looking for is Serverless benchmarking / baseline performance. I don't mind linking to those or other pages if that seems better tho!
> > 
> > 
> > Makes sense, thank you for the context. This seems like a reasonable solution.
> 
> I guess the other option is to leave this old page as a stub that just says this isn't supported anymore, and has a "See Also" section with a few links. WDYT?

@mdlinville Mark pointed me to this [page](https://www.cockroachlabs.com/docs/cockroachcloud/serverless-resource-usage) which seems a better fit for what the users might look for. I'm now inclined to redirect to this page and delete the original page.

**Comment by marksoper** [comment]
@Amruta-Ranade and I chatted about this and agreed that a simple redirect will be the best way to resolve this.

**Review by mdlinville — APPROVED** [review]

**Pull request merged**
