### PR TITLE
Add changefeed metrics labels option & usage

### PR DESCRIPTION
**Pull request by kathancox**
Fixes [DOC-2130](https://cockroachlabs.atlassian.net/browse/DOC-2130)

Added a reference and usage section to the Monitor and Debug Changefeeds page on changefeed metrics labels. 

- Included warning on experimental feature
- Usage considerations, availability, etc. 
- Option to the `CREATE CHANGEFEED` option table.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
Other than 1 comment, this looks very nice.

**Review by amruss — APPROVED** [review]
LGTM

**Review by taroface — CHANGES_REQUESTED** [review]
A couple questions on how we indicate "experimental" and "Enterprise", plus some nits. Also, I left comments on v21.2 only, but they should all apply to v22.1 as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13233#-:-MyDi7BeEw6vUa6rMABt:b-1tbskr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox, @miretskiy, and @taroface)

___
*[v21.2/create-changefeed.md, line 129 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDcGvd2733gOmJjenM:-MyDcGvf9uJt-_YRsWES:bay17l5) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/create-changefeed.md#L129)):*
> ```Markdown
> `topic_in_value`         | [`BOOL`](bool.html)              | <span class="version-tag">New in v21.2:</span> Set to include the topic in each emitted row update. Note this is automatically set for [webhook sinks](changefeed-sinks.html#webhook-sink).
> `webhook_sink_config`    | [`STRING`](string.html)          | <span class="version-tag">New in v21.2:</span> Set fields to configure sink batching and retries. The schema is as follows:<br><br> `{ "Flush": { "Messages": ..., "Bytes": ..., "Frequency": ..., }, "Retry": {"Max": ..., "Backoff": ..., } }`. <br><br>**Note** that if either `Messages` or `Bytes` are nonzero, then a non-zero value for `Frequency` must be provided. <br><br>See [Webhook sink configuration](changefeed-sinks.html#webhook-sink-configuration) for more details on using this option.
> `metrics_label` | [`STRING`](string.html) | This is an **experimental** feature. Define a metrics label to which the metrics for one or multiple changefeeds increment. All changefeeds also have their metrics aggregated.<br><br>The maximum length of a label is 128 bytes. There is a limit of 1024 unique labels.<br><br>`WITH metrics_label=label_name` <br><br>For more detail on usage and considerations, see [Using changefeed metrics labels](monitor-and-debug-changefeeds.html#using-changefeed-metrics-labels). 
> ```

Btw, does this need to be added to `experimental-features.md`? (I have no experience with that page.)
___
*[v21.2/create-changefeed.md, line 129 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDcY1K9nXuucnEOh8E:-MyDcY1K9nXuucnEOh8F:b-ssromj) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/create-changefeed.md#L129)):*
> ```Markdown
> `topic_in_value`         | [`BOOL`](bool.html)              | <span class="version-tag">New in v21.2:</span> Set to include the topic in each emitted row update. Note this is automatically set for [webhook sinks](changefeed-sinks.html#webhook-sink).
> `webhook_sink_config`    | [`STRING`](string.html)          | <span class="version-tag">New in v21.2:</span> Set fields to configure sink batching and retries. The schema is as follows:<br><br> `{ "Flush": { "Messages": ..., "Bytes": ..., "Frequency": ..., }, "Retry": {"Max": ..., "Backoff": ..., } }`. <br><br>**Note** that if either `Messages` or `Bytes` are nonzero, then a non-zero value for `Frequency` must be provided. <br><br>See [Webhook sink configuration](changefeed-sinks.html#webhook-sink-configuration) for more details on using this option.
> `metrics_label` | [`STRING`](string.html) | This is an **experimental** feature. Define a metrics label to which the metrics for one or multiple changefeeds increment. All changefeeds also have their metrics aggregated.<br><br>The maximum length of a label is 128 bytes. There is a limit of 1024 unique labels.<br><br>`WITH metrics_label=label_name` <br><br>For more detail on usage and considerations, see [Using changefeed metrics labels](monitor-and-debug-changefeeds.html#using-changefeed-metrics-labels). 
> ```

Looks like some extra spaces/tab here.



_Code quote:_
```Markdown
labels).··
```
___
*[v21.2/monitor-and-debug-changefeeds.md, line 39 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDef210MIXr4orhCGn:-MyDef238pIAJ--vDiLK:b-xvuyty) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L39)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> ### Using changefeed metrics labels
> ```

Per the [style guide](https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#task) and consistency with `Monitor a changefeed`, should this be "Use changefeed metrics labels"?

In addition, I see that we add `(Enterprise)` to headings for Enterprise features. Might be good to foreground that requirement?
___
*[v21.2/monitor-and-debug-changefeeds.md, line 43 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDf0dS2pIoCqUhf2sY:-MyDf0dS2pIoCqUhf2sZ:b98rxzr) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L43)):*
> ```Markdown
> {% include common/experimental-warning.md %}
> 
> To measure metrics per changefeed, define a "metrics label" to which one or multiple changefeed(s) will increment each [changefeed metric](#metrics). Metrics label information is sent with time-series metrics to `http://<host>:<http-port>/_status/vars`, viewable via the [Prometheus endpoint](monitoring-and-alerting.html#prometheus-endpoint). An aggregated metric of all changefeeds is also measured.
> ```

We've been using `{ }` for bracketed content, though I'm not sure if that would look funny within a URL.



_Code quote:_
```Markdown
<
```
___
*[v21.2/monitor-and-debug-changefeeds.md, line 49 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDfqdk6p_m-xiUbyJL:-MyDfqdk6p_m-xiUbyJM:b-doz5oc) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L49)):*
> ```Markdown
> - An {{ site.data.products.enterprise }} license is required to use this feature.
> - Metrics labels are **not** available in {{ site.data.products.db }}.
> - The `COCKROACH_EXPERIMENTAL_ENABLE_PER_CHANGEFEED_METRICS` environment variable must be specified to use this feature.
> ```

Link `cockroach-commands.html#environment-variables` here



_Code quote:_
```Markdown
environment variable
```
___
*[v21.2/monitor-and-debug-changefeeds.md, line 55 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDfvfe68HgqUiBY_FG:-MyDfvfe68HgqUiBY_FH:borrfv6) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L55)):*
> ```Markdown
> - The maximum length of a metrics label is 128 bytes.
> 
> Before using the `metrics_label` option, it is necessary to set the `COCKROACH_EXPERIMENTAL_ENABLE_PER_CHANGEFEED_METRICS` [environment variable](cockroach-commands.html#environment-variables) on the cluster.
> ```

This is already in the bullet points, so maybe one of them should be cut?
___
*[v21.2/monitor-and-debug-changefeeds.md, line 64 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDh4hE2GQrsNAK0-qh:-MyDh4hFBpTnl0h7RPkj:b-9pe5i6) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L64)):*
> ```Markdown
> ~~~
> 
> Create the changefeed passing the `metrics_label` option with the label name as its value:
> ```

Add comma after "changefeed", I think
___
*[v21.2/monitor-and-debug-changefeeds.md, line 83 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDhQrXCyMb0mJsHsp6:-MyDhQrXCyMb0mJsHsp7:b-gmdyzw) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L83)):*
> ```Markdown
> ~~~
> 
> `http://<host>:<http-port>/_status/vars` shows the defined changefeed(s) by label and the aggregated metric for all changefeeds. This output also shows the `default` scope, which will include changefeeds started without a metrics label:
> ```

Ditto re: `{ }`
___
*[v21.2/monitor-and-debug-changefeeds.md, line 117 at r2](https://reviewable.io/reviews/cockroachdb/docs/13233#-MyDhgS_83XevTP7jKhq:-MyDhgSa7e9tan1joPSc:b-x0z2la) ([raw file](https://github.com/cockroachdb/docs/blob/f196bdc74e0cafc7de0eda641e9bcec790ed4550/v21.2/monitor-and-debug-changefeeds.md#L117)):*
> ```Markdown
> `emit_latency`     | Difference between the event's [MVCC](architecture/storage-layer.html#mvcc) timestamp and the time the event was emitted by CockroachDB. | Nanoseconds
> `admit_latency`    | Difference between the event's MVCC timestamp and the time the event is put into the memory buffer. | Nanoseconds
> `commit_latency`   | Different between the event's MVCC timestamp and the time it is acknowledged by the [downstream sink](changefeed-sinks.html). If the sink is batching events, then the difference is between the oldest event and when the acknowledgment is recorded. | Nanoseconds
> ```

Difference



_Code quote:_
```Markdown
Different
```

**Comment by kathancox** [comment]
@taroface On this one:

> Per the [style guide](https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#task) and consistency with Monitor a changefeed, should this be "Use changefeed metrics labels"?

The reason I went for the gerund, is that I followed the construction of the other H3 headings on this page. But, let me know if you think this is weird and I'll update those too/links.

**Comment by taroface** [comment]
> @taroface On this one:
> 
> > Per the [style guide](https://github.com/cockroachdb/docs/blob/master/StyleGuide.md#task) and consistency with Monitor a changefeed, should this be "Use changefeed metrics labels"?
> 
> The reason I went for the gerund, is that I followed the construction of the other H3 headings on this page. But, let me know if you think this is weird and I'll update those too/links.

Oh, okay. In that case, this seems fine to me!

**Review by taroface — COMMENTED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13233#-:-MyEIobb0u2vqbN8Ptzg:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox, @miretskiy, and @taroface)

**Review by taroface — APPROVED** [review]

**Comment by kathancox** [comment]
> LGTM!
> 
TFTR!

**Pull request merged**
