### PR TITLE
Add beekeeper studio to your docs

### PR DESCRIPTION
**Pull request by rathboma**
You guys added CockroachDB support to Beekeeper a few months ago, so figured I'd call it out!

### CODE REVIEW

**Comment by rathboma** [comment]
👋  Hey folks, just checking in to see what you think here?

**Comment by rathboma** [comment]
@ericharmeling how's that?

**Comment by ericharmeling** [comment]
@rathboma 

Great! Thanks!

**Comment by Amruta-Ranade** [comment]
@rathboma Thank you for contributing to CockroachDB this year. As a token of our appreciation, we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) @Amruta so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please contact me as soon as possible :)

**Pull request merged**
