### PR TITLE
Docs for decommissioning and removing nodes

### LINKED ISSUE #97: cli: complete docs for node command
Need to provide descriptions for `node ls` and `node status` response: https://www.cockroachlabs.com/docs/view-node-details.html#response

### LINKED ISSUE #1496: core: Decommissioning a node
Roadmap: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recGdsZPsKLSD26fY
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/decommission.md
Issues:
- https://github.com/cockroachdb/cockroach/issues/17419
- https://github.com/cockroachdb/cockroach/issues/6198
 
PRs: 
- https://github.com/cockroachdb/cockroach/pull/16528
- https://github.com/cockroachdb/cockroach/pull/17272

Test:
- https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/decommission_test.go

### PR DESCRIPTION
**Pull request by jseldess**
- Update docs on temporary stopping a node.
- Add docs on decommissioning and permanent removal of nodes, as well as recommissioning.
- Update `cockroach node` docs.
- Update command overview and sidenav.

Fixes #1496 
Fixes #97

### CODE REVIEW

**Comment by jseldess** [comment]
@tschottdorf, @bdarnell, I still have a bit of work to do, but I'd like your early feedback on how I've documented decommissioning and removing nodes. Please take a look at the changes to `stop-a-node.md` and the new `decommission-a-node.md` file.

**Comment by tschottdorf** [comment]
Looks good! I don't fully understand where the docs sit in the greater scheme of things, but it seems that there's a bit of duplication that's likely to rot? Other than that, only two points:

1. `./cockroach quit --decommission` is essentially `./cockroach node decommission <self> && ./cockroach quit`. That means you'll use it to decommission and then stop a node, it's not necessary to decommission it first.
1. Discussing the case in which multiple nodes are decommissioned would be good. It's more efficient to do them all at once than one after another to minimize data movement.
1. The diagrams are good!

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[_includes/cli/decommission-a-node.html, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7KQb5IBrPvkomDK-c:-Kt7KQb5IBrPvkomDK-d:bx2uozj) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/_includes/cli/decommission-a-node.html#L8)):*
> ```HTML
> 1. Confirm that there are enough nodes to take over the replicas from the node you want to remove. See [Considerations](decommission-a-node.html#consideration) for some example scenarios.
> 
> 2. [Install the `cockroach` binary](install-cockroachdb.html) on a machine separate from the node.
> ```

This isn't necessary, can do this from one of the machines itself.

---

*[v1.1/stop-a-node.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7JTHRg2N81e6Erniw:-Kt7JTHSx7ZTb7DRqsUt:btbzwel) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/stop-a-node.md#L9)):*
> ```Markdown
> <span class="version-tag">Changed in v1.1:</span> This page shows you how to use the `cockroach quit` [command](cockroach-commands.html) to either temporarily stop a node that you plan to restart or permanently remove a node that has already been [decommissioned](decommission-a-node.html).
> 
> Generally, you temporarily stop nodes during the process of [upgrading your cluster's version of CockroachDB](upgrade-cockroach-version.html), whereas you permanently remove nodes when downsizing a cluster.
> ```

or reacting to hardware failures.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-:-Kt7JI4mqsmunkeFPI9f:baekzth)*

**Comment by tschottdorf** [comment]
Oh, and perhaps a `Considerations` section that removes a node that had a hardware failure would be interesting (i.e. use `--wait=live` since the node is already dead).

**Comment by bdarnell** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[_includes/cli/decommission-a-node.html, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt8064PDm9wcDXGf_6a:-Kt8064PDm9wcDXGf_6b:btn97b) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/_includes/cli/decommission-a-node.html#L10)):*
> ```HTML
> 2. [Install the `cockroach` binary](install-cockroachdb.html) on a machine separate from the node.
> 
> 3. Run the [`cockroach node status`](view-node-details.html) command and identify the ID of the node you want to remove:
> ```

If the node is up, it's often easier to ask it for its ID than to scan the `node status` output in a large cluster:  `cockroach sql --security-flags --host=<node-to-be-removed> -e 'show node_id'`. The node ID is also printed when the node starts up. 

---

*[v1.1/decommission-a-node.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7zHYZ8XWa8T2pD5Fu:-Kt7zHYZ8XWa8T2pD5Fv:bo7pony) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/decommission-a-node.md#L13)):*
> ```Markdown
> <div id="toc"></div>
> 
> ## Considerations
> ```

This should also discuss what it means to decommission a node that's already down (i.e. that this is what you'd do to remove permanently dead nodes from the UI). 

---

*[v1.1/recommission-a-node.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7xc42XMyYuC7o_sfp:-Kt7xc42XMyYuC7o_sfq:b-odoty1) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/recommission-a-node.md#L3)):*
> ```Markdown
> ---
> title: Recommission Nodes
> summary: Learn why and how to temporarily stop a CockroachDB node.
> ```

Recommissioning is not about temporarily stopping a node, it's only for undoing a (mistaken) decommission. I'd include it on the decommission page instead of giving it its own page. 

---

*[v1.1/remove-a-node.md, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7y-p68qCsAawuUOxV:-Kt7y-p68qCsAawuUOxW:b-ovfl4h) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/remove-a-node.md#L2)):*
> ```Markdown
> ---
> title: Remove a Node
> ```

"Removing" a node implies permanent (decomissioning) removal to me, whereas "stop" is very strongly associated with a temporary stop. I'd swap this doc with the stop-a-node one, so "stop" describes the temporary `quit` process and "remove a node" is the high-level guide about the two options. 

---

*[v1.1/remove-a-node.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7yqy2Y138AEdBhWfl:-Kt7yqy2Y138AEdBhWfm:boum1yg) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/remove-a-node.md#L7)):*
> ```Markdown
> ---
> 
> To stop a CockroachDB node running in the background, run the `cockroach quit` [command](cockroach-commands.html) with appropriate flags. To stop a node running in the foreground, use **CTRL + C** or run `cockroach quit` from another shell.
> ```

Sending a signal to the process is also a valid option (for both foreground and background  processes). This is the mechanisms that most process managers would use. 

---

*[v1.1/remove-a-node.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7z5Iu6ykuTW8sts2J:-Kt7z5Iu6ykuTW8sts2K:b-ll2cfh) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/remove-a-node.md#L9)):*
> ```Markdown
> To stop a CockroachDB node running in the background, run the `cockroach quit` [command](cockroach-commands.html) with appropriate flags. To stop a node running in the foreground, use **CTRL + C** or run `cockroach quit` from another shell.
> 
> The `quit` command allows in-flight requests to complete and then shuts down the node. Once a node has been offline for approximately 5 minutes, CockroachDB automatically rebalances replicas from the missing node, using unaffected replicas on other nodes as sources.
> ```

Not just the `quit` command - `ctrl-c` and signals also allow in-flight requests to complete. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[_includes/cli/decommission-a-node.html, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt8064PDm9wcDXGf_6a:-KtI4U8vLWhaS7pE55sw:bclc5ot) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/_includes/cli/decommission-a-node.html#L10)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If the node is up, it's often easier to ask it for its ID than to scan the `node status` output in a large cluster:  `cockroach sql --security-flags --host=<node-to-be-removed> -e 'show node_id'`. The node ID is also printed when the node starts up. 
</blockquote></details>

... or it's printed in the admin ui, if what you know is the host it's running on.

Note that the node may be dead, in which case they shouldn't try to talk to the node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by jseldess** [comment]
TFTR, @tschottdorf and @bdarnell. Will rework soon.

**Comment by jseldess** [comment]
*[_includes/cli/decommission-a-node.html, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7KQb5IBrPvkomDK-c:-KtIJhK9BTOjL6-s0jhY:b-l5s2vk) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/_includes/cli/decommission-a-node.html#L8)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This isn't necessary, can do this from one of the machines itself.
</blockquote></details>

Hmm, you can ssh onto the node, it's true, but I think I've been told by @mberhault or @bdarnell that it's best to recommend running client commands from elsewhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by jseldess** [comment]
*[v1.1/decommission-a-node.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7zHYZ8XWa8T2pD5Fu:-KtIKCt7iDQAtF59XBnL:bj2sjy4) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/decommission-a-node.md#L13)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This should also discuss what it means to decommission a node that's already down (i.e. that this is what you'd do to remove permanently dead nodes from the UI). 
</blockquote></details>

In that case, do you just run the `cockroach node decommission` command and the UI will catch on? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by jseldess** [comment]
*[v1.1/recommission-a-node.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7xc42XMyYuC7o_sfp:-KtIKZA2clQADNcbUyB6:bfsw0eg) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/recommission-a-node.md#L3)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Recommissioning is not about temporarily stopping a node, it's only for undoing a (mistaken) decommission. I'd include it on the decommission page instead of giving it its own page. 
</blockquote></details>

Sorry. This is just a stub page with incorrect copy. I'll remove it and add this content to the decommission page, as you suggest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by jseldess** [comment]
*[v1.1/remove-a-node.md, line 2 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7y-p68qCsAawuUOxV:-KtIKhyG7X1oEkl3Uc4t:b-ugpce5) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/remove-a-node.md#L2)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"Removing" a node implies permanent (decomissioning) removal to me, whereas "stop" is very strongly associated with a temporary stop. I'd swap this doc with the stop-a-node one, so "stop" describes the temporary `quit` process and "remove a node" is the high-level guide about the two options. 
</blockquote></details>

Again, sorry. This is just a stub I left in place accidentally. I think I'll try to have one page, Stop or Remove a Node, cover both cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[v1.1/decommission-a-node.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7zHYZ8XWa8T2pD5Fu:-KtILbBc2OMGAssEPsQ_:b-yuas0z) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/v1.1/decommission-a-node.md#L13)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

In that case, do you just run the `cockroach node decommission` command and the UI will catch on? 
</blockquote></details>

Yes. (Just don't use `--wait=all`, or it won't finish)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[_includes/cli/decommission-a-node.html, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7KQb5IBrPvkomDK-c:-KtIVqNbscXAykErVh-D:b-t8p4xl) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/_includes/cli/decommission-a-node.html#L8)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Hmm, you can ssh onto the node, it's true, but I think I've been told by @mberhault or @bdarnell that it's best to recommend running client commands from elsewhere?
</blockquote></details>

Serious deployments would likely have a controller host, but generally I don't think it's necessary. @mberhault and @bdarnell are definitely the authority on what we want to recommend though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[_includes/cli/decommission-a-node.html, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7KQb5IBrPvkomDK-c:-KtKPCiUPMJ6PNO9rlUI:b-g5alxd) ([raw file](https://github.com/cockroachdb/docs/blob/b2a273faad958b18f796bc981133a0cac4432b93/_includes/cli/decommission-a-node.html#L8)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Serious deployments would likely have a controller host, but generally I don't think it's necessary. @mberhault and @bdarnell are definitely the authority on what we want to recommend though.
</blockquote></details>

In general, I think it's fine for our instructions to demonstrate running the command on a node; we don't need to be didactic about this every time. However, because `decommission` is a command that is intended to be used some of the times on a downed node, it's probably a good idea to demonstrate this command on a node other than the one to be decommissioned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by jseldess** [comment]
@tschottdorf and @bdarnell, please take another look. 

- `stop-a-node.md` now focuses on temporary stopping.
- `remove-a-node.md` now focuses on decommissioning and node removal.
- I expanded `view-node-details.md` to cover the `decommission` and `recommission` subcommands and flags. In a follow-up PR, I'll add more details about the response fields for those commands.

**Comment by jseldess** [comment]
Review status: 12 of 28 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[v1.1/stop-a-node.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7JTHRg2N81e6Erniw:-KtSqAoQrqdTBp1SCVKK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fedb1462cb415dd34f31c576b64e6f60bdadf5df/v1.1/stop-a-node.md#L9)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

or reacting to hardware failures.
</blockquote></details>

Done.

---

*[_includes/cli/decommission-a-node.html, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7KQb5IBrPvkomDK-c:-KtSqFtAwqvJbmRjSzhP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fedb1462cb415dd34f31c576b64e6f60bdadf5df/_includes/cli/decommission-a-node.html#L8)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In general, I think it's fine for our instructions to demonstrate running the command on a node; we don't need to be didactic about this every time. However, because `decommission` is a command that is intended to be used some of the times on a downed node, it's probably a good idea to demonstrate this command on a node other than the one to be decommissioned.
</blockquote></details>

Done.

---

*[_includes/cli/decommission-a-node.html, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt8064PDm9wcDXGf_6a:-KtSqH_H0k7m75vILRVd:bsr513o) ([raw file](https://github.com/cockroachdb/docs/blob/fedb1462cb415dd34f31c576b64e6f60bdadf5df/_includes/cli/decommission-a-node.html#L10)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

... or it's printed in the admin ui, if what you know is the host it's running on.

Note that the node may be dead, in which case they shouldn't try to talk to the node.
</blockquote></details>

Using both of these methods now, in different places.

---

*[v1.1/decommission-a-node.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-Kt7zHYZ8XWa8T2pD5Fu:-KtSqKf7xk0P-j-aRIWL:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/fedb1462cb415dd34f31c576b64e6f60bdadf5df/v1.1/decommission-a-node.md#L13)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yes. (Just don't use `--wait=all`, or it won't finish)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 14 of 21 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1876#-:-KtTSUVlw_XeHMT8sKD2:bnfp4nl)*

**Comment by jseldess** [comment]
Decided to add descriptions for fields in `cockroach node` subcommand responses.

**Pull request merged**
