### PR TITLE
cockroach statement-diag docs

### LINKED ISSUE #7922: release-20.1: cli: add commands for managing statement diagnostics
PR: https://github.com/cockroachdb/cockroach/pull/51229

From release notes:
> The new `statement-diag` [`cockroach` command](../v20.1/cockroach-commands.html) can now be used to manage statement diagnostics. [#51229][#51229] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8189: cli: add commands for managing statement diagnostics
PR: https://github.com/cockroachdb/cockroach/pull/50924

From release notes:
> Added a set of `statement-diag` CLI commands that can be used to manage statement diagnostics. [#50924][#50924] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by taroface**
Fixes #7922.
Fixes #8189.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @taroface)

___
*[v20.1/cockroach-statement-diag.md, line 58 at r2](https://reviewable.io/reviews/cockroachdb/docs/8814#-MLAlwRDD363g08p9ZxN:-MLAlwRDD363g08p9ZxO:b-p0kesg) ([raw file](https://github.com/cockroachdb/docs/blob/5395e8b89d46b2c05b4ca2f85ad41dabcc5b2a04/v20.1/cockroach-statement-diag.md#L58)):*
> ```Markdown
> ## Flags
> 
> - The `delete` and `cancel` subcommands support the following [general-use](#general) flag.
> ```

"following" is confusing, maybe remove it?
___
*[v20.1/cockroach-statement-diag.md, line 97 at r2](https://reviewable.io/reviews/cockroachdb/docs/8814#-MLAmLxH33Uo1VOx0wKI:-MLAmLxH33Uo1VOx0wKJ:bjanbcn) ([raw file](https://github.com/cockroachdb/docs/blob/5395e8b89d46b2c05b4ca2f85ad41dabcc5b2a04/v20.1/cockroach-statement-diag.md#L97)):*
> ```Markdown
> Statement diagnostics bundles:
>   ID                  Collection time          Statement
>   603820372518502401  2020-11-02 18:29:13 UTC  SELECT id, statement_fingerprint, collected_at FROM system.statement_diagnostics WHERE error IS NULL ORDER BY collected_at DESC
> ```

It's strange that the sample query here is actually an internal query related to statement diagnostics. I would replace it with something simpler. Also, I think this is a fingerprint which has `_` instead of names.
___
*[v20.1/cockroach-statement-diag.md, line 101 at r2](https://reviewable.io/reviews/cockroachdb/docs/8814#-MLAmpvkEmQZ1I3XzRPm:-MLAmpvkEmQZ1I3XzRPn:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/5395e8b89d46b2c05b4ca2f85ad41dabcc5b2a04/v20.1/cockroach-statement-diag.md#L101)):*
> ```Markdown
> Outstanding activation requests:
>   ID                  Activation time          Statement
>   603811900498804737  2020-11-02 17:46:08 UTC  SELECT node_id FROM crdb_internal.gossip_liveness WHERE (membership = _) OR (split_part(expiration, _, _)::DECIMAL > now()::DECIMAL)
> ```

Ditto
___
*[v20.1/cockroach-statement-diag.md, line 130 at r2](https://reviewable.io/reviews/cockroachdb/docs/8814#-MLAmrUa0Y_HQvF5c1sA:-MLAmrUa0Y_HQvF5c1sB:b-89a4l7) ([raw file](https://github.com/cockroachdb/docs/blob/5395e8b89d46b2c05b4ca2f85ad41dabcc5b2a04/v20.1/cockroach-statement-diag.md#L130)):*
> ```Markdown
> Outstanding activation requests:
>   ID                  Activation time          Statement
>   603811900498804737  2020-11-02 17:46:08 UTC  SELECT node_id FROM crdb_internal.gossip_liveness WHERE (membership = _) OR (split_part(expiration, _, _)::DECIMAL > now()::DECIMAL)
> ```

Ditto

**Review by taroface — COMMENTED** [review]
TFTR Radu!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8814#-:-MLFGYOd6Zx_Rq51-Y5v:b-qe86ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]

**Comment by taroface** [comment]
@RaduBerinde i forgot to ask if any user roles/privileges are required here. `admin` and/or `VIEWACTIVITY`?

**Comment by RaduBerinde** [comment]
I believe admin is required

**Review by Amruta-Ranade — APPROVED** [review]

**Pull request merged**
