### PR TITLE
fix HTML proofer for internal link to os toggle

### PR DESCRIPTION
**Pull request by benesch**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1178)

### CODE REVIEW

**Comment by mjibson** [comment]
HTML proofer has some ignore content options: https://github.com/gjtorikian/html-proofer#ignoring-content

Would that or one of the other options there be a better choice? I think I'd prefer to use a regex to ignore these as just a thing in the teamcity build config instead of changing the docs output. But I don't have too strong feelings if you still think this way is better.

**Comment by benesch** [comment]
I saw `data-proofer-ignore` but it unfortunately turns off all checks for the link. I figured it's nice to have HTML proofer verify you didn't fat-finger the rest of the href, at least. The other similar options, like `url_ignore`, have the same caveat.

I agree it's unfortunate that this adds cruft to the generated HTML. I also don't feel strongly ¯\_(ツ)_/¯.

**Comment by mjibson** [comment]
LGTM for now. At some future point we will make these actual pages anyway and remove this work around, so for now I think we should just ship this and move on.

**Comment by benesch** [comment]
Works for me!

**Pull request merged**
