### PR TITLE
Added CC free-tier connection steps to the Java tutorials.

### PR DESCRIPTION
**Pull request by ianjevans**
Related to #5738.

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
`v20.2/build-a-java-app-with-cockroachdb-hibernate.md` and `v20.2/build-a-java-app-with-cockroachdb.md` LGTM.

But, IIUC, the CC Free Tier does not support 21.1 (and probably won't for a few months at least).

Is that correct, @lnhsingh ?

If so, you should remove these from the PR:
- `v21.1/build-a-java-app-with-cockroachdb-hibernate.md`
- `v21.1/build-a-java-app-with-cockroachdb.md`
- `_includes/v21.1/app/cc-free-tier-params.md`

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9532#-:-MSDlSSy4m_ug36_iPg9:b-d00nvf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by lnhsingh — COMMENTED** [review]
@ericharmeling that's correct -- CC only runs on 20.2. However, I chatted with Jesse about it and he says that the dev docs can but updated to save us work having to coordinate updates in the future. I actually just opened an [issue](https://github.com/cockroachdb/docs/issues/9515) yesterday to port over the changes you and I made.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9532#-:-MSDmmkZASSm0bhexS5O:b-x3id2u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

**Review by lnhsingh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9532#-:-MSDrGaU-aHycctXnuu6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans)

**Review by ericharmeling — APPROVED** [review]
> he says that the dev docs can but updated to save us work having to coordinate updates in the future.

Gotcha! Makes sense. 

LGTM then, after the build errors are resolved (all broken links). 

Some of the broken links appear to be unrelated to this PR? This one in particular: 

```
hash does not exist --- 81a3e157c6c2b589fc97b364183ee33d8300bd7b/cockroachcloud/backups-page.html --> connect-to-your-cluster.html#use-the-cockroachdb-sql-client
```

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9532#-:-MSDyI1_9P60YMV46_Ji:b70i4ii)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v21.1/build-a-java-app-with-cockroachdb-hibernate.md, line 90 at r1](https://reviewable.io/reviews/cockroachdb/docs/9532#-MSDylUq1H-suz7djQb3:-MSDylUq1H-suz7djQb4:bo77cyn) ([raw file](https://github.com/cockroachdb/docs/blob/81a3e157c6c2b589fc97b364183ee33d8300bd7b/v21.1/build-a-java-app-with-cockroachdb-hibernate.md#L90)):*
> ```
> [earlier](#set-up-your-cluster-connection)
> ```

This is breaking the build.

**Comment by lnhsingh** [comment]
ah yeah, we were getting that broken link with the redesign project's branch too. if you wait until 2PMish ET today, you can rebase with the new master and that should be updated (and this PR will have the new site styling, etc. too)

**Comment by ianjevans** [comment]
> > ```
> > [earlier](#set-up-your-cluster-connection)
> > ```
> 
> This is breaking the build.

This is bizarre, since that's an included section if you select CockroachCloud.
Screen Shot 2021-01-29 at 10 02 43 AM

**Comment by ianjevans** [comment]
@ericharmeling Any idea why the `#set-up-your-cluster-connection` links would cause a build failure in the Hibernate topic, but not e.g. in the Go GORM tutorial? I'm doing essentially the same thing. And all the links work correctly in my local build.

**Comment by ianjevans** [comment]
Ok, finally tracked it down. What's weird is that local builds were including the correct content. So strange.

**Pull request merged**
