### PR TITLE
Doc for importing data

### LINKED ISSUE #1062: Import data into CockroachDB
We should add a page more explicitly documenting the current conventions for getting data into CockroachDB, as well as limitations and future improvements.

- Batches of statements
- From CSV

cc: @dianasaur323

### PR DESCRIPTION
**Pull request by sploiselle**
Closes #1062

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1076)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[import-data.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcPZrA0zAV0yvU9X6GN:-KcPZrA0zAV0yvU9X6GO:bn8hp2o) ([raw file](https://github.com/cockroachdb/docs/blob/1492982d3ca48eff2a63bfb2ccfceaa89037b1ab/import-data.md#L13)):*
> ```Markdown
> ## Import from SQL File
> 
> You can execute batches of `INSERT` statements stored in `.sql` files from the command line, letting you import data into your cluster.
> ```

It would be good to add another paragraph (maybe after the sql command below) that grouping insert rows by ~500 will speed up insert performance. Much more or less than that and we run into various bottlenecks.

---

*[import-data.md, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcPXN1muBqQbclT3HtU:-KcPXN1muBqQbclT3HtV:bl75pmw) ([raw file](https://github.com/cockroachdb/docs/blob/1492982d3ca48eff2a63bfb2ccfceaa89037b1ab/import-data.md#L52)):*
> ```Markdown
> 2. Review any other [constraints](constraints.html) to ensure they're properly listed on the table.
> 3. Remove all statements from the file besides the `CREATE TABLE` and `COPY` statements.
> 4. Surround the `COPY` statement with `BEGIN` and `COMMIT` statements (making it a transaction). For example:
> ```

This is no longer true, and shouldn't be here either. Putting the COPY in a transaction will make it very slow and possibly fail (I think) if there's enough data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1076)*

**Comment by sploiselle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[import-data.md, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcPZrA0zAV0yvU9X6GN:-KcUH1b--btn6qBRxR8d:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/1492982d3ca48eff2a63bfb2ccfceaa89037b1ab/import-data.md#L13)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It would be good to add another paragraph (maybe after the sql command below) that grouping insert rows by ~500 will speed up insert performance. Much more or less than that and we run into various bottlenecks.
</blockquote></details>

Done.

---

*[import-data.md, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcPXN1muBqQbclT3HtU:-KcUH2dM8vVzgjXbmZIu:b-t7cj9m) ([raw file](https://github.com/cockroachdb/docs/blob/1492982d3ca48eff2a63bfb2ccfceaa89037b1ab/import-data.md#L52)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This is no longer true, and shouldn't be here either. Putting the COPY in a transaction will make it very slow and possibly fail (I think) if there's enough data.
</blockquote></details>

After discussion, filing [bug](https://github.com/cockroachdb/cockroach/issues/13490) and commenting out this content until bug is resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1076)*

**Comment by sploiselle** [comment]
@jseldess Ready for your review. LMK if you have questions about content I've commented out.

**Comment by jseldess** [comment]
:lgtm:, with a few comments. 

Another thought: This might warrant callout from somewhere in the getting started pages...

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[import-data.md, line 7 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUTb_sF41F4f2dF_Y_:-KcUTb_sF41F4f2dF_Ya:b-tbpcmg) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/import-data.md#L7)):*
> ```Markdown
> ---
> 
> CockroachDB supports importing data from from `.sql` and some `.csv` files.
> ```

Should we mention that additional, more robust ways to get data into CockroachDB are in development, just so users don't think this is it?

---

*[import-data.md, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUT3lHEiOG8l0CPXDL:-KcUT3lHEiOG8l0CPXDM:bwbps3n) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/import-data.md#L75)):*
> ```Markdown
> You can import numeric data stored in `.csv` files by executing a bash script that reads values from the files and uses them in `INSERT` statements.
> 
> {{site.data.alerts.callout_danger}}To import non-numerical data, convert the <code>.csv</code> file to a <code>.sql</code> file (you can find free conversion software online), and then import the <code>.sql</code> file.{{site.data.alerts.end}}
> ```

Does this need to be a warning (red), or can it be an info callout (blue)?

---

*[_data/sidebar_doc.yml, line 389 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUTs3Fc-813obg5uB2:-KcUTs3Fc-813obg5uB3:b-89bhd8) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/_data/sidebar_doc.yml#L389)):*
> ```YAML
>           url: /configure-replication-zones.html
> 
>         - title: Import Data
> ```

What do you think about putting this under `Manage`, perhaps adjacent to `Back Up and Restore Data`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-:-KcUToCIsF1vkxJc9-ll:brflpnu)*

**Comment by sploiselle** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[import-data.md, line 7 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUTb_sF41F4f2dF_Y_:-KcUXn70TcfU46lTJDJQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/import-data.md#L7)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Should we mention that additional, more robust ways to get data into CockroachDB are in development, just so users don't think this is it?
</blockquote></details>

Done.

---

*[import-data.md, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUT3lHEiOG8l0CPXDL:-KcUXpxEKN0WiKFSZPbe:b-5hihbj) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/import-data.md#L75)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Does this need to be a warning (red), or can it be an info callout (blue)?
</blockquote></details>

To me the "only-numerical-data" limitation is unexpected behavior, hence why I chose the warning  class.

---

*[_data/sidebar_doc.yml, line 389 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUTs3Fc-813obg5uB2:-KcUYFE7xg5jRBkNbBFU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/_data/sidebar_doc.yml#L389)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

What do you think about putting this under `Manage`, perhaps adjacent to `Back Up and Restore Data`? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1076)*

**Comment by jseldess** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[import-data.md, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/1076#-KcUT3lHEiOG8l0CPXDL:-KcUuhWg_W1S4dmfWVUI:b-ugvacs) ([raw file](https://github.com/cockroachdb/docs/blob/bb02c03792673d763b3140de4f862f8c8f2f9185/import-data.md#L75)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

To me the "only-numerical-data" limitation is unexpected behavior, hence why I chose the warning  class.
</blockquote></details>

Ah, that makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1076)*

**Pull request merged**
