### PR TITLE
Data recovery tutorial

### LINKED ISSUE #8221: Disaster Recovery follow-up: Add tutorial on how to recover data from a either a fat finger or malicious data attack
from Chris: 
> [Client] really liked the new Disaster Recovery doc.  One thing they were looking for is some examples on how to recover from some of these scenarios.  I created a quick tutorial on how to do this for the “Run Differentials” section if we want to add it to our docs: https://github.com/chriscasano/cockroach-dr

Jesse: 
> This might also be nice to do as an interactive tutorial in katacoda. I can help with that if it's something you'd be interested in.

### PR DESCRIPTION
**Pull request by kathancox**
First tutorial on data recovery after a malicious attack as per @chriscasano [draft](https://github.com/chriscasano/cockroach-dr). 

Added to v21.1 & 20.2, wasn't sure if this would sit in any other versions. Suggestions on title would be especially appreciated! Look forward to your feedback!

Closes #8221

### CODE REVIEW

**Review by mwang1026 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox)

___
*[_includes/sidebar-data-v21.1.json, line 1011 at r3](https://reviewable.io/reviews/cockroachdb/docs/10522#-M_fTKQC1qoBTH0UvS9d:-M_fTKQC1qoBTH0UvS9e:bii6x1v) ([raw file](https://github.com/cockroachdb/docs/blob/d9814b797dd0a470157192c023549f898b965646/_includes/sidebar-data-v21.1.json#L1011)):*
> ```
> "Data Recovery Tutorial"
> ```
Given that this is just one example of a disaster and one example of how to recover from this type of disaster, what's your thinking on using a very specific title vs a more generic one? Or a specific one nested in a generic one?
___
*[v20.2/data-recovery.md, line 2 at r3](https://reviewable.io/reviews/cockroachdb/docs/10522#-M_fT92v3t3tPFQfFZyn:-M_fT92w4QaPQ24LxnKk:ba1xp4n) ([raw file](https://github.com/cockroachdb/docs/blob/d9814b797dd0a470157192c023549f898b965646/v20.2/data-recovery.md#L2)):*
> ```
> Differentials
> ```
Maybe `Differential Queries`?
___
*[v20.2/data-recovery.md, line 11 at r3](https://reviewable.io/reviews/cockroachdb/docs/10522#-M_fSoaT66aE4TkMYgjk:-M_fSoaT66aE4TkMYgjl:b9v3sr3) ([raw file](https://github.com/cockroachdb/docs/blob/d9814b797dd0a470157192c023549f898b965646/v20.2/data-recovery.md#L11)):*
> ```
> data failure recovery
> ```

Is there a reason you used this term vs `disaster recovery`?
___
*[v20.2/data-recovery.md, line 35 at r3](https://reviewable.io/reviews/cockroachdb/docs/10522#-M_fU5-LCLhIWMU1jowY:-M_fU5-LCLhIWMU1jowZ:b-mehucm) ([raw file](https://github.com/cockroachdb/docs/blob/d9814b797dd0a470157192c023549f898b965646/v20.2/data-recovery.md#L35)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 1. In the [built-in SQL shell](cockroach-sql.html), turn on SQL audit logging for the `rides` table:
>     {% include copy-clipboard.html %}
>     ~~~ sql
>     > ALTER TABLE movr.rides EXPERIMENTAL_AUDIT SET READ WRITE;
>     ~~~
> 
>     You use the [`EXPERIMENTAL_AUDIT`](experimental-audit.html) subcommand of `ALTER TABLE` to turn audit logging on and off. This will log all reads and writes, so both `READ` and `WRITE` are required here.
> ```
</details>


@chriscasano do we recommend audit log turned on by default? AFAIK (and I may be wrong) it's resource intensive. There is another way to think about this where instead of looking at the audit log that you can find, for example, the max(timestamp) where ride value wasn't $1000 for poor Tyler

**Comment by kathancox** [comment]
Great points. 

1. We have "Disaster Recovery" nested under Cluster Maintenance, what about nesting this tutorial under "Disaster Recovery" and using the specific title so "Run Differential Queries for Data Recovery"... then this will make way for further tutorials/scenarios/use cases under that heading. Thoughts?

2. On title, "Differential Queries" yes, much better.

3. "data failure recovery", I think I was trying to be specific about the disaster, but given the placement of this, and already noting the "garbage collection window" I think keeping it to "disaster recovery" makes sense here. 

4. Interested in what @chriscasano  thinks here from a user's pov. Since we specify in docs that audit logging does affect performance but promotes durability... could we maybe also include an alternative in `max(TIMESTAMP)` in the tutorial? 

Although I've linked to the audit logging page, I could have probably done a better job calling out performance implications in a note in the tutorial.

**Comment by chriscasano** [comment]
Good point - We can should probably use the new logging channels in 21.1 instead of using the SQL audit log here. https://www.cockroachlabs.com/docs/v21.1/logging-overview.html

**Comment by kathancox** [comment]
@chriscasano Agree on shifting to referencing the 21.1 [`SENSITIVE_ACCESS` logging channel](https://www.cockroachlabs.com/docs/v21.1/logging-use-cases#sensitive_access). Also, do you have a sense of "real-life" usage of the audit logs? Although we mention the performance impacts [in the docs](https://www.cockroachlabs.com/docs/v21.1/experimental-audit#performance-considerations), do we recommend having audit logs on by default for security?

**Comment by chriscasano** [comment]
I don't have a good idea on how much SQL audit logging is used although it comes up alot at customers that have regulations.  I tried checking if this feature is tracked in our telemetry data but I didn't see anything stand our in the internal crdb_intenal.feature_usage table.  Probably a SQL Product Manager would know better if this information is being tracked.

**Comment by jseldess** [comment]
___
*[v20.2/data-recovery.md, line 2 at r3](https://reviewable.io/reviews/cockroachdb/docs/10522#-M_fT92v3t3tPFQfFZyn:-Mae1Gqw6M79OnO3y_V1:b-5fpm58) ([raw file](https://github.com/cockroachdb/docs/blob/d9814b797dd0a470157192c023549f898b965646/v20.2/data-recovery.md#L2)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> Differentials
> ```
Maybe `Differential Queries`?
</blockquote></details>

On the topic of title, isn't it important that users know up fron that we're talking about recovering data within the garbage collection window, since there would be a different approach if we're talking recovery after garbage collection?  What about `Data Recovery within the Garbage Collection Window`? Or perhaps, if we plan two versions, we could do: `Recover Data After a Malicious Data Attack` and, on the page, have two toggles, e.g., "Within Garbage Collection Window", "After Garbage Collection Window"...

**Comment by jseldess** [comment]
___
*[v20.2/data-recovery.md, line 35 at r3](https://reviewable.io/reviews/cockroachdb/docs/10522#-M_fU5-LCLhIWMU1jowY:-Mae2Yw_AmhSSXAA7fB9:ba3cppy) ([raw file](https://github.com/cockroachdb/docs/blob/d9814b797dd0a470157192c023549f898b965646/v20.2/data-recovery.md#L35)):*
<details><summary><i>Previously, mwang1026 (Michael Wang) wrote…</i></summary><blockquote>

> ```
> 1. In the [built-in SQL shell](cockroach-sql.html), turn on SQL audit logging for the `rides` table:
>     {% include copy-clipboard.html %}
>     ~~~ sql
>     > ALTER TABLE movr.rides EXPERIMENTAL_AUDIT SET READ WRITE;
>     ~~~
> 
>     You use the [`EXPERIMENTAL_AUDIT`](experimental-audit.html) subcommand of `ALTER TABLE` to turn audit logging on and off. This will log all reads and writes, so both `READ` and `WRITE` are required here.
> ```

@chriscasano do we recommend audit log turned on by default? AFAIK (and I may be wrong) it's resource intensive. There is another way to think about this where instead of looking at the audit log that you can find, for example, the max(timestamp) where ride value wasn't $1000 for poor Tyler
</blockquote></details>

@mwang1026, @chriscasano, I think this is the biggest open question for this tutorial: Is the audit log the only way to detect a malicious data attack? If so, does that mean that customers need to turn it on for certain sensitive tables proactively and accept the performance implications? We really need to answer this so Kathryn can make progress on this tutorial.

**Review by jseldess — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chriscasano, @kathancox, and @mwang1026)

___
*[v20.2/run-differential-queries-data-recovery.md, line 49 at r4](https://reviewable.io/reviews/cockroachdb/docs/10522#-Mae2vgPCLkgc831Lquj:-Mae2vgPCLkgc831Lquk:b1b6vy4) ([raw file](https://github.com/cockroachdb/docs/blob/f0fc6ec308741bc8a7af6e30d311546689260e6e/v20.2/run-differential-queries-data-recovery.md#L49)):*
> ```Markdown
>     {% include copy-clipboard.html %}
>     ~~~ shell
>     cockroach workload run movr --max-rate 10 --duration 10s '<connection string>'
> ```

Replace `<connection string>` with `postgresql://root@localhost:26257?sslmode=disable`.
___
*[v20.2/run-differential-queries-data-recovery.md, line 77 at r4](https://reviewable.io/reviews/cockroachdb/docs/10522#-Mae35qOEUqT51T0cCVa:-Mae35qP85Ktr6KlaHYF:b1b6vy4) ([raw file](https://github.com/cockroachdb/docs/blob/f0fc6ec308741bc8a7af6e30d311546689260e6e/v20.2/run-differential-queries-data-recovery.md#L77)):*
> ```Markdown
>     {% include copy-clipboard.html %}
>     ~~~ shell
>     cockroach workload run movr --max-rate 10 --duration 10s '<connection string>'
> ```

Replace `<connection string>` with `postgresql://root@localhost:26257?sslmode=disable`.
___
*[v20.2/run-differential-queries-data-recovery.md, line 161 at r4](https://reviewable.io/reviews/cockroachdb/docs/10522#-Mae3OTPAsT6qUbiXB0S:-Mae3OTPAsT6qUbiXB0T:b-rnh2l9) ([raw file](https://github.com/cockroachdb/docs/blob/f0fc6ec308741bc8a7af6e30d311546689260e6e/v20.2/run-differential-queries-data-recovery.md#L161)):*
> ```Markdown
>     ~~~
> 
> 1. Since `bad_actor` has `SELECT` and `UPDATE` privileges on the database remove these:
> ```

Add comma before `remove these`.

**Comment by jseldess** [comment]
@kathancox, any updates on the plan here? If we've decided not to move forward, we should probably close the PR.

**Comment by kathancox** [comment]
Closing this PR since we're not moving head with this tutorial right now

**Pull request closed without merging**
