### PR TITLE
[Do not merge] Update the IMPORT syntax

### PR DESCRIPTION
**Pull request by knz**
Goes with https://github.com/cockroachdb/cockroach/pull/31263

### CODE REVIEW

**Comment by knz** [comment]
Note that both forms (with and without parentheses) are already accepted by CockroachDB. The parentheses are now promoted for consistency with the syntax form using DATA.

**Comment by knz** [comment]
let's not merge this just yet. David found a compelling argument why this PR may not be needed/useful after all.

**Comment by jseldess** [comment]
OK. Just post an update here when you have one, @knz.

**Comment by jseldess** [comment]
@knz, any updates here?

**Comment by knz** [comment]
The change in CockroachDB was cancelled. There is nothng left to do here.

**Pull request closed without merging**
