### PR TITLE
Draft of S3-compatible services non testing

### LINKED ISSUE #11674: Update docs to indicate that we do not support s3-like paths
Liv Lobo (livlobo) commented:

We want to remove the "s3-compatible-services" row from the docs here and explicitly mention that we do not support s3-compatible-services
https://www.cockroachlabs.com/docs/stable/use-cloud-storage-for-bulk-operations.html

### PR DESCRIPTION
**Pull request by kathancox**
Closes #11674 

Added a warning to S3-compatible services section.

### CODE REVIEW

**Review by livlobo — APPROVED** [review]
Looks good, Kathryn. I think we can leave it in, the warning should help us cover our bases.

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @taroface)

___
*[v21.1/use-cloud-storage-for-bulk-operations.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/docs/12284#-Mr-4dKc2GINInxW0KY8:-Mr-4dKc2GINInxW0KY9:b-f8r9i3) ([raw file](https://github.com/cockroachdb/docs/blob/004715e09ffdafdc9c02e27134397a1fd4d9cc1e/v21.1/use-cloud-storage-for-bulk-operations.md#L163)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> The usage of S3-compatible services is not actively tested by Cockroach Labs.
> ```

This warning reads a bit vague to me - does it mean to convey that we don't test and therefore explicitly advocate the use of S3-compatible services for bulk operations, and therefore aren't responsible for things that go wrong? Or something of a different nature?

Also, I notice that Amazon S3 doesn't have the warning. I assume we support Amazon S3 directly but not the S3-compatible services? Is there a simple way to clarify this as well?

**Comment by kathancox** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12284)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @taroface)
> 
> _[v21.1/use-cloud-storage-for-bulk-operations.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/docs/12284#-Mr-4dKc2GINInxW0KY8:-Mr-4dKc2GINInxW0KY9:b-f8r9i3) ([raw file](https://github.com/cockroachdb/docs/blob/004715e09ffdafdc9c02e27134397a1fd4d9cc1e/v21.1/use-cloud-storage-for-bulk-operations.md#L163)):_
> 
> > ```gfm
> > {{site.data.alerts.callout_danger}}
> > The usage of S3-compatible services is not actively tested by Cockroach Labs.
> > ```
> 
> This warning reads a bit vague to me - does it mean to convey that we don't test and therefore explicitly advocate the use of S3-compatible services for bulk operations, and therefore aren't responsible for things that go wrong? Or something of a different nature?
> 
> Also, I notice that Amazon S3 doesn't have the warning. I assume we support Amazon S3 directly but not the S3-compatible services? Is there a simple way to clarify this as well?

Hey @taroface, gotcha, good points. We don't want to explicitly advocate against S3-compatible services — it's just the bulk team don't test the many options here. Though it's still a valid use option. I could see there being some confusion around S3-compatible vs. Amazon S3. 

What about something that compares and contrasts within the warning? 
"Unlike [Amazon S3](#amazon-s3), [Google Cloud Storage](#google-cloud-storage, and [Azure](#azure-storage) storage options, the usage of S3-compatible services is not actively tested by Cockroach Labs."

I'd love your feedback on this!

**Comment by taroface** [comment]
> > > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12284)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @taroface)
> > 
> > 
> > _[v21.1/use-cloud-storage-for-bulk-operations.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/docs/12284#-Mr-4dKc2GINInxW0KY8:-Mr-4dKc2GINInxW0KY9:b-f8r9i3) ([raw file](https://github.com/cockroachdb/docs/blob/004715e09ffdafdc9c02e27134397a1fd4d9cc1e/v21.1/use-cloud-storage-for-bulk-operations.md#L163)):_
> > > ```
> > > {{site.data.alerts.callout_danger}}
> > > The usage of S3-compatible services is not actively tested by Cockroach Labs.
> > > ```
> > 
> > 
> > This warning reads a bit vague to me - does it mean to convey that we don't test and therefore explicitly advocate the use of S3-compatible services for bulk operations, and therefore aren't responsible for things that go wrong? Or something of a different nature?
> > Also, I notice that Amazon S3 doesn't have the warning. I assume we support Amazon S3 directly but not the S3-compatible services? Is there a simple way to clarify this as well?
> 
> Hey @taroface, gotcha, good points. We don't want to explicitly advocate against S3-compatible services — it's just the bulk team don't test the many options here. Though it's still a valid use option. I could see there being some confusion around S3-compatible vs. Amazon S3.
> 
> What about something that compares and contrasts within the warning? "Unlike [Amazon S3](#amazon-s3), [Google Cloud Storage](#google-cloud-storage, and [Azure](#azure-storage) storage options, the usage of S3-compatible services is not actively tested by Cockroach Labs."
> 
> I'd love your feedback on this!

Sorry for the late reply on this. That suggestion sounds good and clear to me!

**Review by taroface — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12284#-:-Mr4giOsC8NT4gPSCrpV:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kathancox and @taroface)

**Pull request merged**
