### PR TITLE
Re-work Node.js transaction model to support retries

### PR DESCRIPTION
**Pull request by nvanbenschoten**
Also, @andreimatei would you mind double checking the txn retry logic?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/179)

### CODE REVIEW

**Comment by jseldess** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/179#-KE9auJMqtSlpf-KWglz:-KE9auJMqtSlpf-KWgm-:-1635683057) ([raw file](https://github.com/cockroachdb/docs/blob/d4c35ba1390d6822b7316104cc9b5c7aeabca2c2/_includes/app/basic-sample.js#L15)):*
exits?

---

*[_includes/app/basic-sample.js, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/179#-KE9axo8Au4mSveXD6NI:-KE9axo8Au4mSveXD6NJ:1131632356) ([raw file](https://github.com/cockroachdb/docs/blob/d4c35ba1390d6822b7316104cc9b5c7aeabca2c2/_includes/app/basic-sample.js#L27)):*
Insert two rows into the "accounts" table. 

Just to be totally consistent with other samples.

---

*[_includes/app/basic-sample.js, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/179#-KE9bHFOnVMHxpuwQPa5:-KE9bHFOnVMHxpuwQPa6:-1327549244) ([raw file](https://github.com/cockroachdb/docs/blob/d4c35ba1390d6822b7316104cc9b5c7aeabca2c2/_includes/app/basic-sample.js#L31)):*
"Print out the balances."

Again, just to be totally consistent with other samples.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/179#-:-KE9blbKA3QC0zdhUg1Y:1417088721)*

**Comment by jseldess** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/179)*

**Comment by nvanbenschoten** [comment]
Made a few changes to address @andreimatei's comment.

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/basic-sample.js, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/179#-KE9auJMqtSlpf-KWglz:-KEC1oCdRGfUTs7YQciP:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/d4c35ba1390d6822b7316104cc9b5c7aeabca2c2/_includes/app/basic-sample.js#L15)):*
Done.

---

*[_includes/app/basic-sample.js, line 27 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/179#-KE9axo8Au4mSveXD6NI:-KEC1y9qJm-RE-GTocLH:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/d4c35ba1390d6822b7316104cc9b5c7aeabca2c2/_includes/app/basic-sample.js#L27)):*
Done.

---

*[_includes/app/basic-sample.js, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/179#-KE9bHFOnVMHxpuwQPa5:-KEC26cwUKSs5hE_M5gW:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/d4c35ba1390d6822b7316104cc9b5c7aeabca2c2/_includes/app/basic-sample.js#L31)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/179#-:-KEC501m-VHNTLPUPXVe:-1249591625)*

**Comment by andreimatei** [comment]
:LGTM:

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/179#-:-KEC5pYo9SoqDE35f19k:1386550993)*

**Pull request merged**
