### PR TITLE
Add ActiveRecord basic sample.

### PR DESCRIPTION
**Pull request by jordanlewis**
This can be run via `ruby activerecord-basic-sample.rb` once
the ActiveRecord, pg and activerecord-cockroachdb-adapter gems are
installed. That can be done via
`gem install activerecord pg activerecord-cockroachdb-adapter`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1232)

### CODE REVIEW

**Comment by tamird** [comment]
Haven't reviewed in detail, but I think we should have a proper Rails example. I've never heard of anyone using ActiveRecord in this way.

**Comment by jordanlewis** [comment]
We already have a proper Rails example in examples-orms. I was thinking that the docs could link to that for users who are interested in a more complete and canonical example. The sample code in this repo seems to be non-canonical for pretty much every ORM - it's just around to show compatibility in a super simple way.

**Comment by cuongdo** [comment]
LGTM

This sample fits the current structure of the docs. We should still try to do better in the future though. I think it'd make sense to have a series of "Build a Web App with [Node.js|ActiveRecord] In-Depth Tutorial" docs that are more in-depth and canonical.

For now, since `examples-orms` has a more canonical ActiveRecord example, I think we should link to it from our "Build an App With ActiveRecord" page so that the community knows where to find it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1232#-:-KgZuO0OnRi9WsrUwoFF:b-4tcc9k)*

**Comment by jseldess** [comment]
:lgtm:

Agree with Cuong and Jordan. These examples are overly simplistic demonstrations of compatibility. I'm all for building out more realistic, in-depth tutorials, with dev help. For now, I agree that we should at least be linking to `examples-orms`. I'll do that in a follow-up PR, also in other ORM tutorials.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1232#-:-KgZwOyoEIKm5pJKMXdt:bhhoova)*

**Comment by jseldess** [comment]
Note: Test failures are fixed in another PR.

**Pull request merged**
