### PR TITLE
cockroachdb and kubernetes in the cloud

### LINKED ISSUE #677: Kubernetes - Cloud deployment
Our Kuberenetes page focuses on a local cluster. Once this [PR](https://github.com/cockroachdb/cockroach/pull/9515), we should update the docs to cover cloud deployment as well.

### PR DESCRIPTION
**Pull request by jseldess**
This PR updates our Kubernetes-specific docs to focus on cloud deployments. 

Fixes #677

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/727)

### CODE REVIEW

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQPmoQ2Pb68ymbNaIR:-KTQPmoQ2Pb68ymbNaIS:b21ui4g) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L81)):*
> ```Markdown
> ## Step 3. Use the Built-in SQL Client 
> 
> 1. Start the [built-in SQL client](use-the-built-in-sql-client.html) in one-off interactive pod, using the `cockroachdb-public` hostname to access the CockroachDB cluster::
> ```

s/in one-off/in a one-off/

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQPtlMB806WHQGE2cS:-KTQPtlMB806WHQGE2cT:bbet0uj) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L91)):*
> ```Markdown
> 
>    ~~~ sql
>    > CREATE DATABASE bank;
> ```

Was it intentional that you removed the output from most of these commands and removed the shell info from the start of each line?

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQ95Z9PIqhJ6hQMHj:-KTQQ95_IYFUastby-Z3:b-mtb7ec) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L109)):*
> ```Markdown
>    ~~~
> 
> 4. When you're done with the SQL shell, press **CTRL + D** to exit and delete the temporary pod.
> ```

I believe **CTRL + C** and `\q` still work as well if you want to leave those in

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQKHljDRkCROapUQm:-KTQQKHljDRkCROapUQn:bd25s6u) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L152)):*
> ```Markdown
> To increase or decrease the number of pods/nodes in your cluster, use the [`kubectl patch`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_patch/) command to alter the `replicas: 3` configuration for your PetSet. 
> 
> For example, since the Kubernetes script create 4 VMs, and only 3 of them are in use by pods, you can add a replica and safely assume that it will run on the final VM:
> ```

Did you actually find this to be the case? I wouldn't expect any containers to ever be created on the master VM.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 162 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQTC2028Qohqo-zAg:-KTQQTC2028Qohqo-zAh:b-dboz5k) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L162)):*
> ```Markdown
> ~~~ 
> 
> Verify that a fourth pod/node was added successfully: 
> ```

The use of the word node is somewhat confusing here due to Kubernetes' use of it as a term as well, so it may be best to just use the word pod

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQlG556askv6tQ1qJ:-KTQQlG556askv6tQ1qK:b-picy80) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L184)):*
> ```Markdown
> Alternately, to stop the entire Kubernetes cluster, run the `kube-down.sh` script in the `kubernetes` directory. 
> 
> {{site.data.alerts.callout_success}}Stopping the Kubernetes cluster will delete the persistent storage, which was bound to temp directories, so if you want to retain logs, copy them from each pod's <code>stderr</code> before shutting down the cluster. To access a pod's standard error stream, run <code>kubectl logs &lt;podname&gt;</code>.{{site.data.alerts.end}}
> ```

This is only true for Minikube deployments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQPmoQ2Pb68ymbNaIR:-KTVK49-pYRhJ6tMnFOK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L81)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> s/in one-off/in a one-off/
</details>
Done.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQPtlMB806WHQGE2cS:-KTVK5tsLvBo6BNmxVhj:b-nnk4eq) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L91)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Was it intentional that you removed the output from most of these commands and removed the shell info from the start of each line?
</details>
Yeah. I removed everything but the `>` prompt so that users can copy and paste without grabbing the prompt info (based on some JS Sean put in place a few week's back. If the prompt has more than `>`, that effect is lost. 

That said, if you feel it's overly confusing to remove that shell info, happy to put it back in. 

I removed all responses but the response for `SELECT` because the others are so basic. Again, though, if you feel this could lead to confusion, happy to put them back in.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 109 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQ95Z9PIqhJ6hQMHj:-KTVL1G76904kfEkSRlf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L109)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> I believe **CTRL + C** and `\q` still work as well if you want to leave those in
</details>
Done.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQKHljDRkCROapUQm:-KTVL4tgikimhGiZA9_k:b-g62b0o) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L152)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Did you actually find this to be the case? I wouldn't expect any containers to ever be created on the master VM.
</details>
I did add a pod, but I'm not sure how to check which VM it got put on. Just ssh into each instance and check the containers running there?

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 162 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQTC2028Qohqo-zAg:-KTVLUovwweIKC6wA9vS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L162)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> The use of the word node is somewhat confusing here due to Kubernetes' use of it as a term as well, so it may be best to just use the word pod
</details>
Done.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQlG556askv6tQ1qJ:-KTVLYZ6qKL0nF0bgcz9:bbz0km5) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L184)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> This is only true for Minikube deployments
</details>
Good to know. So how do you know where the remote volumes are and how to access them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQPtlMB806WHQGE2cS:-KTVMS5tT2L3dYHlVxOx:bdxu19d) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L91)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Yeah. I removed everything but the `>` prompt so that users can copy and paste without grabbing the prompt info (based on some JS Sean put in place a few week's back. If the prompt has more than `>`, that effect is lost. 
> 
> That said, if you feel it's overly confusing to remove that shell info, happy to put it back in. 
> 
> I removed all responses but the response for `SELECT` because the others are so basic. Again, though, if you feel this could lead to confusion, happy to put them back in.
</details>
Nope, this is fine with me, I was just curious

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQKHljDRkCROapUQm:-KTVMcuZB0UxQ0slId64:b-p6a2tf) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L152)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> I did add a pod, but I'm not sure how to check which VM it got put on. Just ssh into each instance and check the containers running there?
</details>
`kubectl describe pod $PODNAME` should include the node that the pod is running on. But I'm 99% sure that it won't be put on the master VM and you'll end up with 2 cockroachdb pods on the same VM if you don't create a 4th minion VM.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQlG556askv6tQ1qJ:-KTVNmdzJHYLsF1TvCXn:b2qqwwo) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L184)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Good to know. So how do you know where the remote volumes are and how to access them?
</details>
I don't know that we'll want to take it upon ourselves to document where the remote volumes are, since it'll defer by environment. These are the important facts, document them however you think appropriate:

* Running the `kubectl delete` command above will delete all relevant resources, including the persistent volumes and logs
* Deleting the Kubernetes cluster without first deleting the resources will have different behavior in different environments. On Minikube, everything will be deleted. On GCE/AWS, the logs will be deleted when the nodes are brought down, but the GCE persistent disks / AWS EBS volumes containing the database data won't be deleted and will still exist in your cloud project.
* Because of the above, we should probably recommend deleting the resources before deleting the cluster to avoid leaking resources that cost money

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by jseldess** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQKHljDRkCROapUQm:-KTzkkIZP3lEcCoVO-Oe:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L152)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> `kubectl describe pod $PODNAME` should include the node that the pod is running on. But I'm 99% sure that it won't be put on the master VM and you'll end up with 2 cockroachdb pods on the same VM if you don't create a 4th minion VM.
</details>
Done.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 184 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTQQlG556askv6tQ1qJ:-KTzklCskPPK9nVMsrBo:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c2ffcce8b2e2327948b20e05bd63aafd2af5a694/orchestrate-cockroachdb-with-kubernetes.md#L184)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> I don't know that we'll want to take it upon ourselves to document where the remote volumes are, since it'll defer by environment. These are the important facts, document them however you think appropriate:
> 
> * Running the `kubectl delete` command above will delete all relevant resources, including the persistent volumes and logs
> * Deleting the Kubernetes cluster without first deleting the resources will have different behavior in different environments. On Minikube, everything will be deleted. On GCE/AWS, the logs will be deleted when the nodes are brought down, but the GCE persistent disks / AWS EBS volumes containing the database data won't be deleted and will still exist in your cloud project.
> * Because of the above, we should probably recommend deleting the resources before deleting the cluster to avoid leaking resources that cost money
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by a-robinson** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTztquAoFyTxfpo2x_X:-KTztquBOZ4lpqAoqooJ:b-99p4vi) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L44)):*
> ```Markdown
> [pod](http://kubernetes.io/docs/user-guide/pods/) | A pod is a group of one of more Docker containers. In this tutorial, each pod will run on a separate instance and contain one Docker container running a single CockroachDB node. You'll start with 3 pods and grow to 4.
> [PetSet](http://kubernetes.io/docs/user-guide/petset/) | A PetSet is a group of pods treated as stateful units, where each pod has distinguishable network identity and always binds back to the same persistent storage on restart. PetSets are an alpha feature as of Kubernetes version 1.4. As such, they may not be available in some production-ready hosting environments.
> [persistent volume](http://kubernetes.io/docs/user-guide/persistent-volumes/) | Because each CockroachDB node must bind back to the same persistent storage on restart, external temporary directories will be dynamically mounted as persistent volumes that will endure for as long as the Kubernetes cluster is running.<br><br>This tutorial assumes that dynamic volume provisioning is available. When that is not the case, [persistent volume claims](http://kubernetes.io/docs/user-guide/persistent-volumes/#persistentvolumeclaims) need to be created manually. See our [`minikube.sh`](https://github.com/cockroachdb/cockroach/tree/master/cloud/kubernetes/minikube.sh) script for the necessary steps.
> ```

Replace the bit about external temporary directories to reflect the fact that the cloud example uses the cloud-specific remote persistent block devices (either persistent disks on GCE or elastic block store on AWS).

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 173 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzujTuhrIbkM4vESD2:-KTzujTuhrIbkM4vESD3:bgk2ogh) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L173)):*
> ```Markdown
>    ~~~
> 
> {{site.data.alerts.callout_success}}The Pet Set configuration sets all CockroachDB nodes to write to <code>stderr</code>, so if you ever need access to a pod/node's logs to troubleshoot, use <code>kubectl logs PODNAME</code> rather than checking the log on the pod itself.{{site.data.alerts.end}}
> ```

You have `kubectl logs PODNAME` here and `kubectl logs <podname>` in the cloud section. I don't care which we use, but we should probably keep them consistent.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 213 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzvFtCud-8DUz4ojeL:-KTzvFtDArgpZscbhYfM:bofdpq8) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L213)):*
> ```Markdown
> </div>
> 
> <div class="filter-content" markdown="1" data-scope="local">
> ```

Sorry if this is a dumb quesiton, but do we actually need separate divs for this section?

If so, is there a reason for the SQL statements content to differ between them, as it currently does?

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 296 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzvSySGGG81TGS7dda:-KTzvSySGGG81TGS7ddb:b-nlvf0p) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L296)):*
> ```Markdown
> <div class="filter-content current" markdown="1" data-scope="cloud">
> 
> The Kubernetes script created 4 nodes, one master and 3 workers. Pods only get placed on worker nodes, so to ensure that you don't have two pods on the same node, you need to add a new worker node and then edit your PetSet configuration to add an additional pod.
> ```

It may be worth throwing in a link to our best practices doc here, something like:

"[...] to ensure that you don't have two pods on the same node ([as recommended by our production best practices](https://www.cockroachlabs.com/docs/recommended-production-settings.html#cluster-topology)), you need [...]"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTztquAoFyTxfpo2x_X:-KU04fQqtUjRG84qhrnX:b2ohdcv) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L44)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Replace the bit about external temporary directories to reflect the fact that the cloud example uses the cloud-specific remote persistent block devices (either persistent disks on GCE or elastic block store on AWS).
</details>
I tried to improve this. Let me know if it's still unclear or incorrect.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 173 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzujTuhrIbkM4vESD2:-KU05AD-sBM6dw7RfTyB:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L173)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> You have `kubectl logs PODNAME` here and `kubectl logs <podname>` in the cloud section. I don't care which we use, but we should probably keep them consistent.
</details>
Done.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 213 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzvFtCud-8DUz4ojeL:-KU0DN3IzGpojfOWEIBV:b-3wx4za) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L213)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> Sorry if this is a dumb quesiton, but do we actually need separate divs for this section?
> 
> If so, is there a reason for the SQL statements content to differ between them, as it currently does?
</details>
Good point. I've removed the extra div. 

However, when trying to start a local minikube cluster to test this, after running the petset yaml config, I saw that the first node is continuously failing and restarting:

```
~/kubernetes$ kubectl get pods
NAME            READY     STATUS             RESTARTS   AGE
cockroachdb-0   0/1       CrashLoopBackOff   4          2m
~/kubernetes$ kubectl get pods
NAME            READY     STATUS             RESTARTS   AGE
cockroachdb-0   0/1       CrashLoopBackOff   4          2m
~/kubernetes$ kubectl get pods
NAME            READY     STATUS             RESTARTS   AGE
cockroachdb-0   0/1       CrashLoopBackOff   4          2m
```

I looked in the pod's logs and saw an error about the `http-host` flag:

```
~/kubernetes$ kubectl logs cockroachdb-0
+ CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)" "--http-host" "0.0.0.0")
++ hostname -f
++ hostname
+ '[' '!' cockroachdb-0 == cockroachdb-0 ']'
+ '[' -e /cockroach/cockroach-data/COCKROACHDB_VERSION ']'
+ exec /cockroach/cockroach start --logtostderr --insecure --host cockroachdb-0.cockroachdb.default.svc.cluster.local --http-host 0.0.0.0
Error: unknown flag: --http-host
Failed running "start"
```

That flag seems valid to me, so I'm not sure why that error is happening. In any case, I removed `"--http-host" "0.0.0.0"` from the petset config and tried again, and pods started up fine...

```
~/kubernetes$ kubectl get pod
NAME            READY     STATUS    RESTARTS   AGE
cockroachdb-0   1/1       Running   0          17s
cockroachdb-1   0/1       Running   0          6s...
```

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 296 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzvSySGGG81TGS7dda:-KU0Eo_rRFq_l1zG4rUg:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L296)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> It may be worth throwing in a link to our best practices doc here, something like:
> 
> "[...] to ensure that you don't have two pods on the same node ([as recommended by our production best practices](https://www.cockroachlabs.com/docs/recommended-production-settings.html#cluster-topology)), you need [...]"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KU2LeC9SSlpfCLogUUW:-KU2LeC9SSlpfCLogUUX:b-2rol74) ([raw file](https://github.com/cockroachdb/docs/blob/58aff834b0d5168ad8fde56cbd9485529a076a0f/orchestrate-cockroachdb-with-kubernetes.md#L44)):*
> ```Markdown
> [pod](http://kubernetes.io/docs/user-guide/pods/) | A pod is a group of one of more Docker containers. In this tutorial, each pod will run on a separate instance and contain one Docker container running a single CockroachDB node. You'll start with 3 pods and grow to 4.
> [PetSet](http://kubernetes.io/docs/user-guide/petset/) | A PetSet is a group of pods treated as stateful units, where each pod has distinguishable network identity and always binds back to the same persistent storage on restart. PetSets are an alpha feature as of Kubernetes version 1.4. As such, they may not be available in some production-ready hosting environments.
> [persistent volume](http://kubernetes.io/docs/user-guide/persistent-volumes/) | A persistent volume is a piece of networked storage (Persistent Disk on GCE, Elastic Block Store on AWS) mounted into a pod. Persistent volumes endure for as long as the Kubernetes cluster is running, and so ensure that each CockroachDB node binds back to the same storage on restart.<br><br>This tutorial assumes that dynamic volume provisioning is available. When that is not the case, [persistent volume claims](http://kubernetes.io/docs/user-guide/persistent-volumes/#persistentvolumeclaims) need to be created manually. See our [`minikube.sh`](https://github.com/cockroachdb/cockroach/tree/master/cloud/kubernetes/minikube.sh) script for the necessary steps.
> ```

s/Persistent volumes endure for as long as the Kubernetes cluster is running, and so ensure that/The lifetime of a persistent volume is decoupled from the lifetime of the pod that's using it, ensuring that/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727#-:-KU2ME9jNHvz5kZrFyrY:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 213 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KTzvFtCud-8DUz4ojeL:-KU2UCBl-M6N1JPX7q9V:b-uw35dj) ([raw file](https://github.com/cockroachdb/docs/blob/2ef3b5075422389aeddf399ccbde144be8e935ae/orchestrate-cockroachdb-with-kubernetes.md#L213)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Good point. I've removed the extra div. 
> 
> However, when trying to start a local minikube cluster to test this, after running the petset yaml config, I saw that the first node is continuously failing and restarting:
> 
> ```
> ~/kubernetes$ kubectl get pods
> NAME            READY     STATUS             RESTARTS   AGE
> cockroachdb-0   0/1       CrashLoopBackOff   4          2m
> ~/kubernetes$ kubectl get pods
> NAME            READY     STATUS             RESTARTS   AGE
> cockroachdb-0   0/1       CrashLoopBackOff   4          2m
> ~/kubernetes$ kubectl get pods
> NAME            READY     STATUS             RESTARTS   AGE
> cockroachdb-0   0/1       CrashLoopBackOff   4          2m
> ```
> 
> I looked in the pod's logs and saw an error about the `http-host` flag:
> 
> ```
> ~/kubernetes$ kubectl logs cockroachdb-0
> + CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)" "--http-host" "0.0.0.0")
> ++ hostname -f
> ++ hostname
> + '[' '!' cockroachdb-0 == cockroachdb-0 ']'
> + '[' -e /cockroach/cockroach-data/COCKROACHDB_VERSION ']'
> + exec /cockroach/cockroach start --logtostderr --insecure --host cockroachdb-0.cockroachdb.default.svc.cluster.local --http-host 0.0.0.0
> Error: unknown flag: --http-host
> Failed running "start"
> ```
> 
> That flag seems valid to me, so I'm not sure why that error is happening. In any case, I removed `"--http-host" "0.0.0.0"` from the petset config and tried again, and pods started up fine...
> 
> ```
> ~/kubernetes$ kubectl get pod
> NAME            READY     STATUS    RESTARTS   AGE
> cockroachdb-0   1/1       Running   0          17s
> cockroachdb-1   0/1       Running   0          6s...
> ```
</details>
Disregard. Alex pointed out that my minikube cluster was using an older version of cockroach. With a newer version, all's well. 

---

*[orchestrate-cockroachdb-with-kubernetes.md, line 44 at r4](https://reviewable.io:443/reviews/cockroachdb/docs/727#-KU2LeC9SSlpfCLogUUW:-KU2UAP_jlKZ2UDTw4Zy:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/58aff834b0d5168ad8fde56cbd9485529a076a0f/orchestrate-cockroachdb-with-kubernetes.md#L44)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> s/Persistent volumes endure for as long as the Kubernetes cluster is running, and so ensure that/The lifetime of a persistent volume is decoupled from the lifetime of the pod that's using it, ensuring that/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/727#-:-KU2YXYJXBiU-MKFRJGK:bnfp4nl)*

**Pull request merged**
