### PR TITLE
Add --file flag to zone config docs

### LINKED ISSUE #601: cockroach zone set -f -
Accepts yaml config as file or from stdin.

PR: https://github.com/cockroachdb/cockroach/issues/7643

### PR DESCRIPTION
**Pull request by jseldess**
Add `--file` flag to `configure-replication-zones.md` and update examples.

I'll open a separate PR to handle the new zone config format and other related changes on `develop`.

Fixes #601

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/602)

### CODE REVIEW

**Comment by d4l3k** [comment]
Might want to mention the `-f -` syntax somewhere for completeness.

:LGTM:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[configure-replication-zones.md, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQXeKNhmZeFVFDtMvtM:-KQXeKNiUKpLtdgFMUg8:b6jjm9m) ([raw file](https://github.com/cockroachdb/docs/blob/3a962ad41871e447f6ee8244d9f3e841b06acc8b/configure-replication-zones.md#L95)):*
> ```Markdown
> 
> # Edit the default replication zone for the cluster:
> $ cockroach zone set .default --file=<zone-content.yaml> <flags>
> ```

Any reason to prefer `--file` over `-f`?

---

*[configure-replication-zones.md, line 180 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQXebrcdJN8KeEYM9uL:-KQXebrcdJN8KeEYM9uM:b-98f3ke) ([raw file](https://github.com/cockroachdb/docs/blob/3a962ad41871e447f6ee8244d9f3e841b06acc8b/configure-replication-zones.md#L180)):*
> ```Markdown
> 
>    ~~~ shell
>    $ cat default_update.yaml
> ```

You could also do
```
cockroach zone set .default -f - <<EOF
replicas:
   - attrs: [us-east-1a]
   - attrs: [us-east-1b]
   - attrs: [us-west-1a]
EOF
```
https://stackoverflow.com/questions/6541109/send-string-to-stdin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/602#-:-KQXesth47izZkP98Sgb:b3endgn)*

**Comment by d4l3k** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/602)*

**Comment by jseldess** [comment]
Thanks, @d4l3k. I've mentioned that syntax in the `--file` flag definition.  I've updated the example to use it as well. 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[configure-replication-zones.md, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQXeKNhmZeFVFDtMvtM:-KQYCdkIubVe9-NJMRSF:b-e57b19) ([raw file](https://github.com/cockroachdb/docs/blob/3a962ad41871e447f6ee8244d9f3e841b06acc8b/configure-replication-zones.md#L95)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Any reason to prefer `--file` over `-f`?
</details>
The long form is clearer at-a-glance. I've kept it here and updated the examples to use `-f`. 

---

*[configure-replication-zones.md, line 180 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQXebrcdJN8KeEYM9uL:-KQYCZzllBp_zn9Lz1Ag:b-rjk3x6) ([raw file](https://github.com/cockroachdb/docs/blob/3a962ad41871e447f6ee8244d9f3e841b06acc8b/configure-replication-zones.md#L180)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> You could also do
> ```
> cockroach zone set .default -f - <<EOF
> replicas:
>    - attrs: [us-east-1a]
>    - attrs: [us-east-1b]
>    - attrs: [us-west-1a]
> EOF
> ```
> https://stackoverflow.com/questions/6541109/send-string-to-stdin
</details>
I updated all of the the examples to show this as an alternative. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/602#-:-KQYCtNWcFU-ivC4WVTE:bqtiik9)*

**Comment by jseldess** [comment]
@sploiselle, PTAL as well.

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[configure-replication-zones.md, line 126 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQaHR2f5Iv88c3SaoK9:-KQaHR2f5Iv88c3SaoKA:b-6flcuj) ([raw file](https://github.com/cockroachdb/docs/blob/411a9d14bd7d261c422a1b75908a85c78ef3a2d4/configure-replication-zones.md#L126)):*
> ```Markdown
> `--cert` | The path to the [client certificate](create-security-certificates.html). This flag is required if the cluster is secure.<br><br>**Env Variable:** `COCKROACH_CERT`
> `--database`<br>`-d` | Not currently implemented. 
> `--file`<br>`-f` | The path to the [YAML file](#replicaton-zone-format) defining the zone configuration. To pass the zone configuration via the standard input, set this flag to `-`.<br><br>This flag is relevant only for the `set` subcommand.
> ```

Without using this (or knowing more about how the syntax of flags like this work with feeding in files), my question is what the default path is. Is it the working directory, or off of root?

---

*[configure-replication-zones.md, line 217 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQaHolnJFT9PwvNmLwW:-KQaHolnJFT9PwvNmLwX:b-6xtujj) ([raw file](https://github.com/cockroachdb/docs/blob/411a9d14bd7d261c422a1b75908a85c78ef3a2d4/configure-replication-zones.md#L217)):*
> ```Markdown
>    ~~~ shell
>    # Start nodes with ssd storage:
>    $ cockroach start --insecure --host=node1-hostname --store=path=node1-data,attr=ssd
> ```

for my own edification, why are all of the other flags space delimited, but this is comma (and no space) delimited?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/602)*

**Comment by jseldess** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[configure-replication-zones.md, line 126 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQaHR2f5Iv88c3SaoK9:-KQaLf3REkD0CaQTeUqf:bsjxzc6) ([raw file](https://github.com/cockroachdb/docs/blob/411a9d14bd7d261c422a1b75908a85c78ef3a2d4/configure-replication-zones.md#L126)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary>
> Without using this (or knowing more about how the syntax of flags like this work with feeding in files), my question is what the default path is. Is it the working directory, or off of root?
</details>
This works the same as the filepath to cert and key files.  The file can be anywhere.  Do you think this needs to be clarified? If so, any quick language suggestions?

---

*[configure-replication-zones.md, line 217 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQaHolnJFT9PwvNmLwW:-KQaURiS0WWQypazJ30K:b125oj9) ([raw file](https://github.com/cockroachdb/docs/blob/411a9d14bd7d261c422a1b75908a85c78ef3a2d4/configure-replication-zones.md#L217)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary>
> for my own edification, why are all of the other flags space delimited, but this is comma (and no space) delimited?
</details>
Are you looking at the `--store` flag? It's one of the only ones that takes a number of fields. https://www.cockroachlabs.com/docs/start-a-node.html#store 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/602)*

**Comment by sploiselle** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[configure-replication-zones.md, line 126 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQaHR2f5Iv88c3SaoK9:-KQaig03APg24350wbS8:b264d17) ([raw file](https://github.com/cockroachdb/docs/blob/411a9d14bd7d261c422a1b75908a85c78ef3a2d4/configure-replication-zones.md#L126)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> This works the same as the filepath to cert and key files.  The file can be anywhere.  Do you think this needs to be clarified? If so, any quick language suggestions?
</details>
Ah––it's off of root, then. That makes sense. Don't think folks who know more than me would be confused.

---

*[configure-replication-zones.md, line 217 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/docs/602#-KQaHolnJFT9PwvNmLwW:-KQaj-0SZenRecxRmV-k:b-7pbhu1) ([raw file](https://github.com/cockroachdb/docs/blob/411a9d14bd7d261c422a1b75908a85c78ef3a2d4/configure-replication-zones.md#L217)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Are you looking at the `--store` flag? It's one of the only ones that takes a number of fields. https://www.cockroachlabs.com/docs/start-a-node.html#store 
</details>
I was looking at `--store`, yeah. Didn't realize there were multiple instances of `--attr`. I get it now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/602#-:-KQajKzEnlkUo1ChN2AI:bnfp4nl)*

**Pull request merged**
