### PR TITLE
Add a warning to beta-20170112

### PR DESCRIPTION
**Pull request by bdarnell**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1012)

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM.

Should we drop `beta-20170112` from the list of versions on register?

**Comment by bdarnell** [comment]
We need to decide whether we want to fully withdraw the beta or just add a warning. If we want to fully withdraw it we need to remove it from register, change the `latest` link, update the other version references in the docs, and update the brew config.

**Comment by mberhault** [comment]
True. I'm not sure that we do want to withdraw it entirely, at least not with so much uncertainty about what the true cause of the problem is.

**Comment by jseldess** [comment]
@bdarnell, since the binary links on the install page all use "latest" and, thus, this version, should we also put a warning there? Not sure if new users are going to read the notes before installing...

**Comment by bdarnell** [comment]
I don't think we should add a warning on the install pages; we should either leave them as they are or change the `latest` link so they install the right thing.

**Comment by jseldess** [comment]
OK. I'll merge this then and, if we do redirect latest to a previous release, let me know and I'll have to update a few other links.

**Comment by jseldess** [comment]
Also added warning to the forum post: https://forum.cockroachlabs.com/t/release-notes-for-beta-20170112/410. cc @jess-edwards, @swatikumar16

**Comment by jess-edwards** [comment]
@jseldess Thanks for adding that to the forum post.

**Pull request merged**
