### PR TITLE
shorten Homebrew link by using our new tap

### PR DESCRIPTION
**Pull request by benesch**
If cockroachdb/cockroach#14082 lands, this will update the docs with the new,
shorter URL.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1177)

### CODE REVIEW

**Comment by bdarnell** [comment]
We track installations by detecting when users copy the command line to the clipboard. Simplifying the command line will have the side effect that some users will type it in by hand instead of copying and pasting. That's probably not enough of a reason to keep the longer URL, but we should be aware that we may see a dip in the stats if we make this change.

**Comment by benesch** [comment]
Ah, good to know. We could always adjust the Homebrew formula to hit a URL if `stdin.tty?`.

**Comment by dt** [comment]
if/when we have it pour pre-built bottles, we can also just count downloads of the tarball.

**Comment by benesch** [comment]
Do we do that now for binaries? (I assumed we didn't to avoid false positives from e.g. downstream CIs.)

**Comment by benesch** [comment]
Yep, just rebased! Is there anyone else I should check with before merging this? The tap is ready to go, so these instructions are safe to merge whenever!

**Pull request merged**
