### PR TITLE
CC Callout that you can't add nodes to a single-node cluster

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-3822?atlOrigin=eyJpIjoiMTczYzBmNTQ1ODJiNGM4M2EzOGMxNmQ3NzI1NGMxOTYiLCJwIjoiaiJ9

Add callout to Create Your Cluster page and FAQs

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/create-your-cluster.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/10496#-MZsfduu1x-32o_axW2u:-MZsfduu1x-32o_axW2v:b-tchjov) ([raw file](https://github.com/cockroachdb/docs/blob/5e24529ee4118d3a762292c64e36cf2b416f5565/cockroachcloud/create-your-cluster.md#L55)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> At this time, we do not support adding nodes to existing single-node clusters.
> ```

Few small edits:
- I think this should be an include so there's only one place you have to edit it
- I think this should be a warning (but maybe that's extreme? I'll let you make the final decision)
- Suggestion for tightening up the language: `At this time, you cannot add nodes to a single-node cluster once it is created.` (I'm not sure "existing" is the right word here, since it seems like you _could_ add it to a newly created single-node cluster, but that's not the case)

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10496)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/create-your-cluster.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/docs/10496#-MZsfduu1x-32o_axW2u:-MZsxNm1EOAchbtyFVmr:b-wso5u2) ([raw file](https://github.com/cockroachdb/docs/blob/5e24529ee4118d3a762292c64e36cf2b416f5565/cockroachcloud/create-your-cluster.md#L55)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Few small edits:
- I think this should be an include so there's only one place you have to edit it
- I think this should be a warning (but maybe that's extreme? I'll let you make the final decision)
- Suggestion for tightening up the language: `At this time, you cannot add nodes to a single-node cluster once it is created.` (I'm not sure "existing" is the right word here, since it seems like you _could_ add it to a newly created single-node cluster, but that's not the case)
</blockquote></details>

Kept as a Note but otherwise done!

**Review by lnhsingh — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10496#-:-MZt49p30M83IRYVJKKN:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by daniel-crlabs — COMMENTED** [review]
Looks nice, thanks for working on this.

**Pull request merged**
