### PR TITLE
CC Connection Troubleshooting

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-3687?atlOrigin=eyJpIjoiZDFkMmJiMmY0MGU1NGQ5NjhhMWQ5M2ZhMmE5ZDA0ZGMiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by gemma-shay** [comment]
CC: @thtruo @joshimhoff @kannanlakshmi @ianjevans 

Does anyone have suggestions for additional errors & resolutions? This was all I could find solid information on, but interested in expanding if possible.

**Review by kannanlakshmi — COMMENTED** [review]
cc @emily-horing as part of overall connection experience/ onboarding research, are there other errors you've run across? Could you do a quick scan of the Zendesk issues from the last quarter to look at connection related issues for Gemma to add here? @gemma-shay can you add Emily Horing as a reviewer too? Thanks! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10672#-:-MaoM7p4ESJUSt81DJqS:ba2s481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/troubleshooting-page.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-MaoLnIDDV1RWLkQEvdd:-MaoLnIDDV1RWLkQEvde:bsxazhf) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L73)):*
> ```Markdown
> **Solution:**
> 
> - Increase the timeout value (e.g., from 5 seconds to 30 seconds) and see if connection succeeds.
> ```

Can we link to something that shows how to do this? If that doc doesn't exist, we should outline it here

**Review by emily-horing — CHANGES_REQUESTED** [review]
I added some inline comments. I think eventually we can expand this to have language-specific errors as well, but this seems like a good start to me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10672#-:-Mb86neB-PSBXyZv3JCH:b4s3oli)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @kannanlakshmi)

___
*[cockroachcloud/troubleshooting-page.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb83NCs8kZZusQCG5A8:-Mb83NCt0Ux-LcCqijx_:b4lo5wx) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L20)):*
> ```Markdown
> ~~~
> 
> **Solution:** Check if you are using the right cluster name in the [connection method](connect-to-your-cluster.html#step-4-connect-to-your-cluster).
> ```

Is this the right link? The content on that page doesn't really clarify to me what the right cluster name is if I don't know it. Perhaps we should share a more concrete example?
___
*[cockroachcloud/troubleshooting-page.md, line 59 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb83vR64wfRC_ozWPKX:-Mb83vR64wfRC_ozWPKY:b-5mb7rn) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L59)):*
> ```Markdown
> Check if you are using the correct host name.
> 
> You can find your host name in the CockroachCloud Console by navigating to **Cluster Overview** > **Connect** > **Connection parameters** and locating the **Host** field. If the error persists, [contact Support](https://support.cockroachlabs.com/).
> ```

For dedicated clusters, there will be an intermediate step in the connect modal. We might want to call that out.
___
*[cockroachcloud/troubleshooting-page.md, line 61 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb84Apf6uOCOV9iFSj-:-Mb84Apf6uOCOV9iFSj0:b-a3w5wu) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L61)):*
> ```Markdown
> You can find your host name in the CockroachCloud Console by navigating to **Cluster Overview** > **Connect** > **Connection parameters** and locating the **Host** field. If the error persists, [contact Support](https://support.cockroachlabs.com/).
> 
> ### Application with a short timeout fails to connect
> ```

This seems to be the same error as Network not Authorized. As a user I feel like it might be more intuitive to organize these docs by error type, rather than solution. If I get this error, I would want to be able to quickly see *all* the possible reasons for it, so perhaps this solution could be grouped with the one above?
___
*[cockroachcloud/troubleshooting-page.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-MaoLnIDDV1RWLkQEvdd:-Mb84jj20nXHJI3Njd2h:b2ngthx) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L73)):*
<details><summary><i>Previously, kannanlakshmi (Lakshmi Kannan) wrote…</i></summary><blockquote>

Can we link to something that shows how to do this? If that doc doesn't exist, we should outline it here 
</blockquote></details>

+1 
___
*[cockroachcloud/troubleshooting-page.md, line 74 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb84mWW2ry9U1CeN-WN:-Mb84mWW2ry9U1CeN-WO:b36tk57) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L74)):*
> ```Markdown
> 
> - Increase the timeout value (e.g., from 5 seconds to 30 seconds) and see if connection succeeds.
> - If you can connect and run the same query in the SQL CLI, investigate your application environment.
> ```

Can we expand on the "investigate" part here? Investigate for what? What would I look for in my application?

**Review by gemma-shay — COMMENTED** [review]
Thanks for the feedback and sorry this got so delayed! CC @joshimhoff to help answer some questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10672#-:-McGPBEP-0rXb42ybsgr:bcc5n0c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @joshimhoff, and @kannanlakshmi)

___
*[cockroachcloud/troubleshooting-page.md, line 20 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb83NCs8kZZusQCG5A8:-McGR7IxD7S4-Syzzrgp:b-5b4e5y) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L20)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Is this the right link? The content on that page doesn't really clarify to me what the right cluster name is if I don't know it. Perhaps we should share a more concrete example?
</blockquote></details>

Added info for the console.
___
*[cockroachcloud/troubleshooting-page.md, line 59 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb83vR64wfRC_ozWPKX:-McGS3G_2YVMwtwao9ws:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L59)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

For dedicated clusters, there will be an intermediate step in the connect modal. We might want to call that out.
</blockquote></details>

Done.
___
*[cockroachcloud/troubleshooting-page.md, line 61 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb84Apf6uOCOV9iFSj-:-McGWfLUEyfgkRtd_L0z:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L61)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

This seems to be the same error as Network not Authorized. As a user I feel like it might be more intuitive to organize these docs by error type, rather than solution. If I get this error, I would want to be able to quickly see *all* the possible reasons for it, so perhaps this solution could be grouped with the one above?
</blockquote></details>

Done.
___
*[cockroachcloud/troubleshooting-page.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-MaoLnIDDV1RWLkQEvdd:-McGN7n1-rVTIcJFenJq:b-5nbzgn) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L73)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

+1 
</blockquote></details>

I believe this is specific to the user's application code, so I can clarify that, but Josh can confirm.
___
*[cockroachcloud/troubleshooting-page.md, line 74 at r1](https://reviewable.io/reviews/cockroachdb/docs/10672#-Mb84mWW2ry9U1CeN-WN:-McGWnTKCVY3KMHt77UX:b-jk17yh) ([raw file](https://github.com/cockroachdb/docs/blob/dd1966e66a4f944060c1a8965d9be5677d31c01c/cockroachcloud/troubleshooting-page.md#L74)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Can we expand on the "investigate" part here? Investigate for what? What would I look for in my application?
</blockquote></details>

I'm not sure, calling in @joshimhoff on this one.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
