### PR TITLE
Null handing issues.

### PR DESCRIPTION
**Pull request by stbof**
https://cockroachlabs.atlassian.net/browse/DOC-1207
https://cockroachlabs.atlassian.net/browse/DOC-1716
https://cockroachlabs.atlassian.net/browse/DOC-1507
https://cockroachlabs.atlassian.net/browse/DOC-1121

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @stbof)

___
*[`v21.1/order-by.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/13755#-N0r3xEY6VPgaoXh7W7g:-N0r3xEY6VPgaoXh7W7h:b-popkrb) ([raw file](https://github.com/cockroachdb/docs/blob/522f4081ef2dc871ce9d78b9e2cdc950d46c114e/v21.1/order-by.md#L42)):*
> ```Markdown
> selected by the selection that immediately precedes.
> 
> CockroachDB supports `NULLS FIRST` and `NULLS LAST` in `ORDER BY` clauses for compatibility with [PostgreSQL row-sorting syntax](https://www.postgresql.org/docs/current/queries-order.html). However, support for `NULLS LAST` is syntax-only. If you specify `NULLS LAST` in an `ORDER BY` clause, CockroachDB uses `NULLS FIRST` and returns an error.
> ```

An error is returned if the ask from NULLS FIRST / LAST doesn't "match" the internal structure of the used index. If the index is ascending, then the error is returned for NULLS LAST (because CRDB internally stores nulls first); if the index is descending, then the error is returned for NULLS FIRST (because CRDB stores internally nulls last).
___
*[`v21.2/order-by.md` line 43 at r1](https://reviewable.io/reviews/cockroachdb/docs/13755#-N0r4OzECNl3HWDaWpPk:-N0r4OzECNl3HWDaWpPl:b-7ropln) ([raw file](https://github.com/cockroachdb/docs/blob/522f4081ef2dc871ce9d78b9e2cdc950d46c114e/v21.2/order-by.md#L43)):*
> ```Markdown
> selected by the selection that immediately precedes.
> 
> CockroachDB supports `NULLS FIRST` and `NULLS LAST` in `ORDER BY` clauses for compatibility with [PostgreSQL row-sorting syntax](https://www.postgresql.org/docs/current/queries-order.html). However, support for `NULLS LAST` is syntax-only. If you specify `NULLS LAST` in an `ORDER BY` clause, CockroachDB uses `NULLS FIRST` and returns an error.
> ```

ditto

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @stbof)

___
*[`v21.1/order-by.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/13755#-N0r3xEY6VPgaoXh7W7g:-N0rLJJ22LrCdHwfRQtK:bh3qu37) ([raw file](https://github.com/cockroachdb/docs/blob/522f4081ef2dc871ce9d78b9e2cdc950d46c114e/v21.1/order-by.md#L42)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

An error is returned if the ask from NULLS FIRST / LAST doesn't "match" the internal structure of the used index. If the index is ascending, then the error is returned for NULLS LAST (because CRDB internally stores nulls first); if the index is descending, then the error is returned for NULLS FIRST (because CRDB stores internally nulls last).
</blockquote></details>

The whole paragraph now seems to contradict itself. How about something along these lines:


CockroachDB supports NULLS FIRST and NULLS LAST in ORDER BY clauses. However, in some cases the support is syntax-only - an error is returned if NULLS FIRST or NULLS LAST specification doesn't "match" the internal structure of the used index. If the index is ascending, the error is returned for NULLS LAST; if the index is descending, the error is returned for NULLS FIRST.

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm: modulo updating 21.1 page.

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755#-:-N0rY8CI2wROOlzsvn7_:b-vfgvbc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @stbof)

___
*[`v21.1/order-by.md` line 42 at r1](https://reviewable.io/reviews/cockroachdb/docs/13755#-N0r3xEY6VPgaoXh7W7g:-N0rY2-SDxBuJ3z64cZM:bbrhs7b) ([raw file](https://github.com/cockroachdb/docs/blob/522f4081ef2dc871ce9d78b9e2cdc950d46c114e/v21.1/order-by.md#L42)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The whole paragraph now seems to contradict itself. How about something along these lines:


CockroachDB supports NULLS FIRST and NULLS LAST in ORDER BY clauses. However, in some cases the support is syntax-only - an error is returned if NULLS FIRST or NULLS LAST specification doesn't "match" the internal structure of the used index. If the index is ascending, the error is returned for NULLS LAST; if the index is descending, the error is returned for NULLS FIRST.
</blockquote></details>

The change on this page should be in sync with 21.2 version.

**Comment by stbof** [comment]
@yuzefovich now the order-by discussion 

> CockroachDB supports NULLS FIRST and NULLS LAST in ORDER BY clauses. However, in some cases the support is syntax-only - an error is returned if NULLS FIRST or NULLS LAST specification doesn't "match" the internal structure of the used index. If the index is ascending, the error is returned for NULLS LAST; if the index is descending, the error is returned for NULLS FIRST.

is contradicting what it says in null-handing:

> Note that the NULLS FIRST and NULLS LAST options of the ORDER BY clause are not implemented in CockroachDB, so you cannot change where NULL values appear in the sort order.

I thought that these are implemented only in 22.1.

**Review by yuzefovich — COMMENTED** [review]
I guess it depends on how we define "to implement NULLS FIRST / LAST". There are four possible combinations of support: FIRST vs LAST and ascending vs descending index. In 21.1 and 21.2 we supported only two possible combinations when NULLS FIRST / LAST modifiers already matched the internal state and would error out on two others; in 22.1 we can support all four combinations.

I think the release note in https://cockroachlabs.atlassian.net/browse/DOC-1716 is misleading.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755#-:-N0rZYSZ7j_J9cvJ6Xal:bhtetmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

**Review by yuzefovich — COMMENTED** [review]
> so you cannot change where NULL values appear in the sort order

This is true of 21.1 and 21.2 and doesn't contradict what I said above. One could say CRDB 21.1 and 21.2 "in spirit" doesn't implement changing the order of NULLs, but when those NULLS FIRST / LAST modifiers are no-ops, then we can successfully execute the query without changing the order of NULLs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755#-:-N0r_F4j4QhN8fWtYYf-:b9mxxj9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

**Comment by stbof** [comment]
> > so you cannot change where NULL values appear in the sort order
> 
> This is true of 21.1 and 21.2 and doesn't contradict what I said above. One could say CRDB 21.1 and 21.2 "in spirit" doesn't implement changing the order of NULLs, but when those NULLS FIRST / LAST modifiers are no-ops, then we can successfully execute the query without changing the order of NULLs.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755#-:-N0r_F4j4QhN8fWtYYf-:b9mxxj9)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

So wouldn't it be clearer if I just duplicated this:

> CockroachDB supports NULLS FIRST and NULLS LAST in ORDER BY clauses. However, in some cases the support is syntax-only - an error is returned if NULLS FIRST or NULLS LAST specification doesn't "match" the internal structure of the used index. If the index is ascending, the error is returned for NULLS LAST; if the index is descending, the error is returned for NULLS FIRST.


in the null-handling pages?

**Review by yuzefovich — COMMENTED** [review]
Yeah, duplication there sounds like a good idea.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755#-:-N0r_jx99oNveQrysASy:b-poyyw6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @rmloveland)

**Review by rmloveland — APPROVED** [review]
LGTM

**Pull request merged**
