### PR TITLE
Remove limitation about on conflict and returning

### LINKED ISSUE #1693: sql: UPSERT and INSERT ON CONFLICT with RETURNING
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recfh5aGbH5i9kwn9
PR: https://github.com/cockroachdb/cockroach/pull/17149

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1693

### CODE REVIEW

**Comment by jseldess** [comment]
@couchand, this just involved removing text stating that on conflict with returning is not supported. I don't see the need for anything else. Do you?

@Amruta-Ranade, the language around `returning nothing` in the `upsert` and `insert` docs, and probably in other sql statement docs, needs to be revisited once your [Parallel Statement Execution PR](https://github.com/cockroachdb/docs/pull/1790) is further along.

**Comment by couchand** [comment]
@jseldess LGTM

I'll also draw your attention to https://github.com/cockroachdb/cockroach/pull/17435, which I don't think needs anything in particular, since we hadn't documented the missing functionality anyway.  But it might be nice, for those unfamiliar with the details of PGSQL and uninclined to dig into the SQL syntax page, to point out that the `DO UPDATE` can have a `WHERE` filter after the `SET` clause.

**Comment by jseldess** [comment]
TFTR, @couchand. I also added an example showing `DO UPDATE SET` with a `WHERE` filter and called it out as new in 1.1.

**Comment by jseldess** [comment]
TC only failing on what should be valid links to old cockroach prs. Overriding TC and merging in the hope that the GitHub hiccup will pass.

**Pull request merged**
