### PR TITLE
Document ambigous result errors

### LINKED ISSUE #1727: Document AmbiguousResultErrors
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recmDbcXFLWEMLsj9

We need better documentation on the meaning of `AmbiguousResultErrors` and how to handle them. 

From @bdarnell: 

> Ambiguous errors are inherent in distributed systems, and a client application with a single-node databases is still a distributed system and may experience ambiguous failure (if the database dies while you're committing your transaction, you can't tell what happens). Since these errors are unavoidable, we mistakenly thought we could introduce them without causing new headaches, and without needing to document them in detail. However, we generate these AmbiguousResultErrors far more often than other systems, so we do need to do a better job of documenting this (unless we can reduce their frequency to some minimal level).

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #1727

### CODE REVIEW

**Comment by rmloveland** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2848#-:-L97Hz2P16xE89gaiuzt:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[v2.0/query-behavior-troubleshooting.md, line 49 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2848#-L9AiJ9A9VUsMG8I9-nU:-L9AiJ9A9VUsMG8I9-nV:bsyyfao) ([raw file](https://github.com/cockroachdb/docs/blob/fcacceaa16d41f5b42d778179482e4eb41b66bbf/v2.0/query-behavior-troubleshooting.md#L49)):*
> ```Markdown
> message `result is ambiguous`.
> 
> Ambiguous errors can be cause by nodes crashing, network failures, or
> ```

`s/cause/caused/g`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2848)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2848#-:-L9AieLb6Uxh9GI7K_Zt:bnfp4nl)*

**Comment by jseldess** [comment]
Sorry, I meant to address that last comment to @bdarnell!

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[v2.0/query-behavior-troubleshooting.md, line 46 at r1](https://beta.reviewable.io/reviews/cockroachdb/docs/2848#-L9BH5yQ6QVyKqRCzWpo:-L9BH5yR0oKpr3PK6s89:b-ifak17) ([raw file](https://github.com/cockroachdb/docs/blob/fcacceaa16d41f5b42d778179482e4eb41b66bbf/v2.0/query-behavior-troubleshooting.md#L46)):*
> ```Markdown
> other databases because ambiguous results can be caused by failures
> between the nodes of a cluster. These errors are reported with the
> PostgreSQL error code `40003` (`statement_completion_unknown`) and the
> ```

I think we should give a nod to how only COMMITs or implicit txns can get these errors. In other cases, I believe we turn them into retriable errors.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/docs/2848)*

**Comment by bdarnell** [comment]
Oh, I didn't realize we already had this on the transactions page, and completely overlooked the common-errors page. I've moved the new text to common-errors and replaced some of the text on the transactions page with a link.

**Comment by jseldess** [comment]
Thanks, @bdarnell!

**Pull request merged**
