### PR TITLE
beta-20161208 release note updates

### LINKED ISSUE #913: Document log filename format
PR: https://github.com/cockroachdb/cockroach/pull/11666

### PR DESCRIPTION
**Pull request by jseldess**
Made minor edits. Added links. Updated `version`, `build_time`, and `start_time` strings. Regenerated the sql diagrams and functions. Added description of log filename format.

Fixes #913

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/914)

### CODE REVIEW

**Comment by jseldess** [comment]
@asubiotto, please take a quick look before I merge.

**Comment by asubiotto** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[_includes/sql/diagrams/grammar.html, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/914#-KYV0W8SGAYigCrA559w:-KYV0W8SGAYigCrA559x:b-djdcvi) ([raw file](https://github.com/cockroachdb/docs/blob/0c879a0ce6a7ea227e1a6422556fce0766f1aa6f/_includes/sql/diagrams/grammar.html#L215)):*
> ```HTML
>          <rect x="51" y="3" width="74" height="32" rx="10"></rect>
>          <rect x="49" y="1" width="74" height="32" class="terminal" rx="10"></rect>
>          <text class="terminal" x="59" y="21">BACKUP</text>
> ```

Should BACKUP/RESTORE statements be in the docs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/914)*

**Comment by jseldess** [comment]
*[_includes/sql/diagrams/grammar.html, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/914#-KYV0W8SGAYigCrA559w:-KYV3DHVZtIIBVnGcBE1:b-petzuk) ([raw file](https://github.com/cockroachdb/docs/blob/0c879a0ce6a7ea227e1a6422556fce0766f1aa6f/_includes/sql/diagrams/grammar.html#L215)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should BACKUP/RESTORE statements be in the docs?
</blockquote></details>

I asked Dan. No, this shouldn't be there. I'll revert to the previous version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/914)*

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/914#-:-KYV5QCN_Wvlga28vCFv:bnfp4nl)*

**Pull request merged**
