### PR TITLE
Add v2.0-rc1 release notes

### PR DESCRIPTION
**Pull request by jseldess**

### CODE REVIEW

**Comment by vilterp** [comment]
Hey Jesse, we had to slip another PR into 2.0rc1: #24308. I guess you'll have to run your script again. Sorry about that.

**Comment by jseldess** [comment]
Thanks for the heads up, @vilterp. No need to rerun the script. The commit in that PR has `Release notes: None`.

**Comment by vilterp** [comment]
Oh ok, sounds good. Yeah, all it does is fix a typo on the cluster overview screen, in text that was introduced a couple commits earlier.

**Comment by bdarnell** [comment]
https://github.com/cockroachdb/cockroach/pull/24393 has been added to rc1. This fixes an issue in which permissions may be set incorrectly after upgrading from an older release.

**Comment by jseldess** [comment]
Added. Thanks, @bdarnell.

**Pull request merged**
