### PR TITLE
improve docs for 2.0 import

### LINKED ISSUE #2055: [beta] Stabilized distributed bulk ingest from CSV
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rec8Nuiv3e3nXxRO9

PRs:
- [sql: add some logging for distributed import](https://github.com/cockroachdb/cockroach/pull/19649)

### LINKED ISSUE #2115: sql: need to document setting session DB for IMPORT
See: https://forum.cockroachlabs.com/t/import-data-from-csv-file-failing/1059/3

`into_db` is the same as RESTORE, just isn't documented.

### LINKED ISSUE #2445: Remove experimental flag for IMPORT

### PR DESCRIPTION
**Pull request by mjibson**
Fixes #2115
Fixes #2445 
Fixes #2055

### CODE REVIEW

**Comment by mjibson** [comment]
Not sure who to assign this to so am trying both of you. Also can I request that if there are comments or revisions needed that someone from the docs team take it over the finish line? Is this enough of a start to be useful?

**Comment by Amruta-Ranade** [comment]
@mjibson This is incredible! I can take over the editorial cleanup, no worries. Thank you for this :)

**Comment by jseldess** [comment]
Also, @mjibson, @dianasaur323 just opened an issue asking us to change the classification from "experimental" to "beta": https://github.com/cockroachdb/docs/issues/2599

Let me know if I'm overloading this PR.

**Comment by mjibson** [comment]
Yes, this should close those two issues.

**Comment by jseldess** [comment]
Just noticed @mjibson's request to hand this off. Sorry for missing that before. @Amruta-Ranade, can you take this over?

**Comment by Amruta-Ranade** [comment]
@jseldess @mjibson Yes, I can take this up from here. Thanks Matt!

**Comment by Amruta-Ranade** [comment]
As discussed with @mjibson, all issues listed in the comments have been addressed in the document.

**Comment by jseldess** [comment]
Closing in favor of @Amruta-Ranade copy of this PR: https://github.com/cockroachdb/docs/pull/2676

**Pull request closed without merging**
