### PR TITLE
Added community support page; updated ToC

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes https://github.com/cockroachdb/docs/issues/8248.
Related to https://github.com/cockroachdb/docs/issues/8424, https://github.com/cockroachdb/docs/issues/8423.

@vy-ton 
We should probably add more tools. Also, we need to come up with a list of tools that we currently label as "Beta" support that are, in fact, "Community" support.

### CODE REVIEW

**Comment by vy-ton** [comment]
@ericharmeling Do you know where the Preview links went for this PR?

**Comment by ericharmeling** [comment]
> @ericharmeling Do you know where the Preview links went for this PR?

Yes - sorry. The preview build system changed. We now use the Netlify builds, which are linked in the checks ("deploy/netlify"->"Details").

Here is the link to the preview for this PR: https://deploy-preview-10383--cockroachdb-docs.netlify.app/docs/v21.1/community-tooling.html

**Review by vy-ton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10383)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[_includes/v21.1/misc/tooling.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmic6X423CnHs9UxX_:-MZmic6X423CnHs9UxXa:b-grabpc) ([raw file](https://github.com/cockroachdb/docs/blob/aee7b84535c596a333b783c04bf751fe858f0134/_includes/v21.1/misc/tooling.md#L24)):*
> ```Markdown
> | Python | [psycopg2](build-a-python-app-with-cockroachdb.html) | [2.8.6](https://www.psycopg.org/docs/install.html) | Full |
> | Ruby | [pg](build-a-ruby-app-with-cockroachdb.html) | [1.2.3](https://rubygems.org/gems/pg) | Full |
> | Rust | <a href="https://crates.io/crates/postgres/" data-proofer-ignore>postgres</a> {% comment %} This link is in HTML instead of Markdown because HTML proofer dies bc of https://github.com/rust-lang/crates.io/issues/163 {% endcomment %} | [0.17.3](https://crates.io/crates/postgres/) | Beta |
> ```

These tools should move from here to community tooling:

Drivers
* C++
* Clojure
* PHP

GUIs
* Dbvisualizer

Some other changes:
* IntelliJ IDEA support should be Full
___
*[_includes/v21.1/misc/tooling.md, line 49 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmiOxr8ggEe9ZCLe1k:-MZmiOxr8ggEe9ZCLe1l:b-wl29x1) ([raw file](https://github.com/cockroachdb/docs/blob/aee7b84535c596a333b783c04bf751fe858f0134/_includes/v21.1/misc/tooling.md#L49)):*
> ```Markdown
> | [DBeaver](https://dbeaver.com/) | [5.2.3 or higher](https://dbeaver.com/download/) | Full |
> | [DbVisualizer](https://www.dbvis.com/) | [10.0.22 or higher](https://www.dbvis.com/download/) | Beta |
> | [Navicat for PostgreSQL](https://www.navicat.com/en/products/navicat-for-postgresql)/[Navicat Premium](https://www.navicat.com/en/products/navicat-premium) | [12.1.25 or higher](https://www.navicat.com/en/download/navicat-for-postgresql) | Beta |
> ```

All of these should go under community tooling now?
___
*[v21.1/community-tooling.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmgixx8304-CmhW_HD:-MZmgixx8304-CmhW_HE:b-j75bdb) ([raw file](https://github.com/cockroachdb/docs/blob/22219ee6e7685e1ffdd5c97ef6c1af095e02aba0/v21.1/community-tooling.md#L7)):*
> ```Markdown
> ---
> 
> The following tools have been tested by the CockroachDB community, but are not officially supported by CockroachDB.
> ```

`been tested or developed...supported by Cockroach Labs`
___
*[v21.1/community-tooling.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmgxSy5BSX9xkaAiVR:-MZmgxSy5BSX9xkaAiVS:bxs479p) ([raw file](https://github.com/cockroachdb/docs/blob/22219ee6e7685e1ffdd5c97ef6c1af095e02aba0/v21.1/community-tooling.md#L12)):*
> ```Markdown
> 
> {{site.data.alerts.callout_success}}
> If you have a tested a third-party tool with CockroachDB, and would like it listed on this page, please [open a pull request to our docs GitHub repository](https://github.com/cockroachdb/docs/edit/master/${VERSION}/community-tooling.md).
> ```

`tested or developed`
___
*[v21.1/community-tooling.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmh6scAQQA2stsPk9R:-MZmh6scAQQA2stsPk9S:b-1yn7r3) ([raw file](https://github.com/cockroachdb/docs/blob/22219ee6e7685e1ffdd5c97ef6c1af095e02aba0/v21.1/community-tooling.md#L17)):*
> ```Markdown
> ## Drivers
> 
> ### Powershell
> ```

We could just have a flat list for `Drivers` and avoid headers for specific languages?

**Review by ericharmeling — COMMENTED** [review]
TFTR @vy-ton ! I think I got to all your comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10383#-:-MZn4LAmDbXF4P24b0Gw:b-813uyo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vy-ton)

___
*[_includes/v21.1/misc/tooling.md, line 24 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmic6X423CnHs9UxX_:-MZn4NpfDQEf3fxNGATK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/aee7b84535c596a333b783c04bf751fe858f0134/_includes/v21.1/misc/tooling.md#L24)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

These tools should move from here to community tooling:

Drivers
* C++
* Clojure
* PHP

GUIs
* Dbvisualizer

Some other changes:
* IntelliJ IDEA support should be Full
</blockquote></details>

Done.
___
*[_includes/v21.1/misc/tooling.md, line 49 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmiOxr8ggEe9ZCLe1k:-MZn4QfiCxpPPPmJo4Lm:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/aee7b84535c596a333b783c04bf751fe858f0134/_includes/v21.1/misc/tooling.md#L49)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

All of these should go under community tooling now?
</blockquote></details>

Done.
___
*[v21.1/community-tooling.md, line 7 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmgixx8304-CmhW_HD:-MZn4RYVDH4t37PLSwmq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/22219ee6e7685e1ffdd5c97ef6c1af095e02aba0/v21.1/community-tooling.md#L7)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

`been tested or developed...supported by Cockroach Labs`
</blockquote></details>

Done.
___
*[v21.1/community-tooling.md, line 12 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmgxSy5BSX9xkaAiVR:-MZn4S-p2-oZlOy1s-7R:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/22219ee6e7685e1ffdd5c97ef6c1af095e02aba0/v21.1/community-tooling.md#L12)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

`tested or developed`
</blockquote></details>

Done.
___
*[v21.1/community-tooling.md, line 17 at r2](https://reviewable.io/reviews/cockroachdb/docs/10383#-MZmh6scAQQA2stsPk9R:-MZn4SPkB4jfkzUhSEj1:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/22219ee6e7685e1ffdd5c97ef6c1af095e02aba0/v21.1/community-tooling.md#L17)):*
<details><summary><i>Previously, vy-ton (Vy Ton) wrote…</i></summary><blockquote>

We could just have a flat list for `Drivers` and avoid headers for specific languages?
</blockquote></details>

Done.

**Review by ianjevans — APPROVED** [review]

**Pull request merged**
