### PR TITLE
CC Free Quickstart Update

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes: https://cockroachlabs.atlassian.net/browse/CC-3895?atlOrigin=eyJpIjoiNjc4M2I3MWYxODYwNGYwNGEzZWE5NDgzOWYwM2ZjNzQiLCJwIjoiaiJ9

Simplified and more prescriptive. 
Switched CA cert steps to use `sslmode=require` to avoid confusion.
Add Windows install.

Ticket for new tutorial video to be added when possible: https://cockroachlabs.atlassian.net/browse/EDU-1050?atlOrigin=eyJpIjoiNTdhOTkwYjVjMzZmNDlkMjlkYjk1N2U2MGIxNTM3MmQiLCJwIjoiaiJ9

### CODE REVIEW

**Review by lnhsingh — CHANGES_REQUESTED** [review]
Can you create a tracking issue in Jira for adding the link to the video when it's available?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427#-:-MZNkc0V0P3tGd29kZun:bgrc0h5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/quickstart.md, line 15 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNkvZ80-fWWt0FckP6:-MZNkvZ80-fWWt0FckP7:bv31941) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L15)):*
> ```Markdown
> </div>
> 
> This page guides you through the simplest way to get started with CockroachDB by setting up a CockroachCloud Free (beta) cluster with the default options and minimal security. To create a more advanced CockroachCloud cluster, see [Create a Free Cluster](create-a-free-cluster.html).
> ```

nit: `simplest` > `quickest` ? We have in our Style Guide to avoid `simple` "(along with "just", "easily", "actually", etc.) since it's not really possible to tell what might be easy or hard for the user. Something you think is simple may be challenging for them."

nit: `minimal security` > `minimal connection security`

For the second sentence, I would change it to something like `For information on how to create a CockroachCloud cluster using other options, see Create a Free Cluster.` - i.e.,  users don't have to create more _advanced_ clusters, just clusters using different options.
___
*[cockroachcloud/quickstart.md, line 27 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNmGy59AEbPZKJ1Byr:-MZNmGy59AEbPZKJ1Bys:btrukhp) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L27)):*
> ```Markdown
> 
>     {{site.data.alerts.callout_info}}
>     This cluster will be free forever.
> ```

Should we delete this callout to streamline the instructions?
___
*[cockroachcloud/quickstart.md, line 38 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNtXxV98zIT2t_-Aa8:-MZNtXxWBnp52j1BfwQ4:brxyyis) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L38)):*
> ```Markdown
> Once your cluster is created, the **Connection info** dialog displays. A default SQL user and database have already been set up for you, so you will be taken to the **Command Line** tab of the **Connect** step.
> 
> 1. Skip the first two steps and copy the connection string provided, which will be used in the next steps (and to connect to your cluster in the future).
> ```

Did you test these steps in order to see if it was ok as is? I think I originally wrote these instructions because I was afraid that the user would lose their password, but maybe that's not an issue. We might be able to just say "Skip Step 1 (download the CA cert) since we are going to connect with sslmode=required, which is a less secure option for connecting, etc etc" Then we could move to downloading the binaries (i.e., doing the steps in order, which might be less confusing).
___
*[cockroachcloud/quickstart.md, line 41 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNufPoAgoMSO01p8xY:-MZNufPoAgoMSO01p8xZ:b-xyb1a7) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L41)):*
> ```Markdown
> 
>     {{site.data.alerts.callout_danger}}
>     This connection string contains your password, which will be provided only once. If you forget your password, you can reset it by going to the [**SQL Users** page](https://www.cockroachlabs.com/docs/cockroachcloud/user-authorization.html).
> ```

nit: this link should be a relative link
___
*[cockroachcloud/quickstart.md, line 46 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNzBIdCvBzY2ZYHrqW:-MZNzBIdCvBzY2ZYHrqX:b-gv9z6k) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L46)):*
> ```Markdown
> 1. Edit your connection string by replacing `sslmode=verify-full&sslrootcert=<your_certs_directory>/cc-ca.crt` with `sslmode=require`:
> 
> ~~~
> ```

nit: this should be 

```
{% include_cached copy-clipboard.html %}
~~~ shell
```

(and nested under the step)
___
*[cockroachcloud/quickstart.md, line 61 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNzS7HEtkPMqrnYFUP:-MZNzS7HEtkPMqrnYFUQ:b-skbnmf) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L61)):*
> ```Markdown
> 
> <section class="filter-content" markdown="1" data-scope="mac">
> 1. Open your terminal and run the following command:
> ```

If we want to take a more opinionated approach and go with the fastest/easiest way, I would suggest just using the Homebrew instructions here.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 15 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNkvZ80-fWWt0FckP6:-MZPPaGJDLpY4mLAkJyh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L15)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: `simplest` > `quickest` ? We have in our Style Guide to avoid `simple` "(along with "just", "easily", "actually", etc.) since it's not really possible to tell what might be easy or hard for the user. Something you think is simple may be challenging for them."

nit: `minimal security` > `minimal connection security`

For the second sentence, I would change it to something like `For information on how to create a CockroachCloud cluster using other options, see Create a Free Cluster.` - i.e.,  users don't have to create more _advanced_ clusters, just clusters using different options.
</blockquote></details>

Done.
___
*[cockroachcloud/quickstart.md, line 27 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNmGy59AEbPZKJ1Byr:-MZPPcfQEoe699NgvPmN:bs7wumx) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L27)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Should we delete this callout to streamline the instructions?
</blockquote></details>

Done. 
___
*[cockroachcloud/quickstart.md, line 38 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNtXxV98zIT2t_-Aa8:-MZTHWMd3QZguglRw8Uf:bx1vbfg) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L38)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Did you test these steps in order to see if it was ok as is? I think I originally wrote these instructions because I was afraid that the user would lose their password, but maybe that's not an issue. We might be able to just say "Skip Step 1 (download the CA cert) since we are going to connect with sslmode=required, which is a less secure option for connecting, etc etc" Then we could move to downloading the binaries (i.e., doing the steps in order, which might be less confusing).
</blockquote></details>

The steps work either way, but I don't think it's likely that the user would close the connection tab and lose the password, so probably better to put steps in order. I moved things around and put "Skip step 1" as the last step in **Step 1: Create a free cluster**.
___
*[cockroachcloud/quickstart.md, line 41 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNufPoAgoMSO01p8xY:-MZPPpwp1WgByfRpwCnY:bs7wumx) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L41)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: this link should be a relative link
</blockquote></details>

Done. 
___
*[cockroachcloud/quickstart.md, line 46 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNzBIdCvBzY2ZYHrqW:-MZPQ9Ka1FnwYhY51Uzn:bs7wumx) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L46)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

nit: this should be 

```
{% include_cached copy-clipboard.html %}
~~~ shell
```

(and nested under the step)
</blockquote></details>

Done. 
___
*[cockroachcloud/quickstart.md, line 61 at r3](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZNzS7HEtkPMqrnYFUP:-MZPRfAG3Cn6kbVwndEN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3a075b86ecd901b0a8455f04d326576421d291b3/cockroachcloud/quickstart.md#L61)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

If we want to take a more opinionated approach and go with the fastest/easiest way, I would suggest just using the Homebrew instructions here.
</blockquote></details>

Done.

**Comment by gemma-shay** [comment]
@kannanlakshmi Let me know if you'd like to review/if I should add anyone else 🙂

**Review by kannanlakshmi — COMMENTED** [review]
Can you ask Emily to review it as well? She owns the onboarding experience and this falls under that. Thanks! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427#-:-MZUMjgq294oSkhTxOwv:bvpdv29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by emily-horing — CHANGES_REQUESTED** [review]
Added some nits, but overall this looks great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427#-:-MZnhPDM9IH2pTmxi17P:b-tgkhyd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnf3lT-diPaIARqNzs:-MZnf3lT-diPaIARqNzt:bpjeabh) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L29)):*
> ```Markdown
>     Your cluster will be created in approximately 20-30 seconds and the **Connection info** dialog will display.
>     
> 1. Skip Step 1 (downloading the CA certificate) since we are going to connect with the less secure option `sslmode=required` instead.
> ```

I think we should add some context on why it is less secure. Maybe just a sentence at the end "this option is vulnerable to man-in-the-middle attacks. To connect securely, see <other docs>."
wdyt?
___
*[cockroachcloud/quickstart.md, line 82 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnfZmuAs5g7D9dADZ4:-MZnfZmuAs5g7D9dADZ5:b-9m19oa) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L82)):*
> ```Markdown
> </section>
> 
> ## Step 3. Edit your connection string
> ```

I think we are missing a step for free tier users to copy and save their password for future use. I would love if docs had some pointers (or links to pointers) on where to store this (ie a "secure place" means a password manager or handwritten note -- maybe security team has more suggestions)

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnf3lT-diPaIARqNzs:-MZnnKeX95tEas1Pnfd0:b-qsk8mb) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L29)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I think we should add some context on why it is less secure. Maybe just a sentence at the end "this option is vulnerable to man-in-the-middle attacks. To connect securely, see <other docs>."
wdyt?
</blockquote></details>

Same focus concern as below... what if we link to the Authentication page (https://www.cockroachlabs.com/docs/cockroachcloud/authentication#ssl-mode-settings) in the very beginning where it says we're using "minimal connection security?" cc: @lnhsingh for guidance
___
*[cockroachcloud/quickstart.md, line 82 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnfZmuAs5g7D9dADZ4:-MZnmUOi2rEEw0sMvoNT:baz2ouk) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L82)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

I think we are missing a step for free tier users to copy and save their password for future use. I would love if docs had some pointers (or links to pointers) on where to store this (ie a "secure place" means a password manager or handwritten note -- maybe security team has more suggestions)
</blockquote></details>

Added directions to save your connection string somewhere secure, but I think if we're trying to minimize links/maximize retention it might not be the place for password manager info. Might be something good to add to the regular Connect to Your Cluster docs?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, and @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 29 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnf3lT-diPaIARqNzs:-MZnrEnQC1qTZ8c9RfBh:bqo5klz) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L29)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Same focus concern as below... what if we link to the Authentication page (https://www.cockroachlabs.com/docs/cockroachcloud/authentication#ssl-mode-settings) in the very beginning where it says we're using "minimal connection security?" cc: @lnhsingh for guidance
</blockquote></details>

I agree, re: focus. We want this Quickstart to be opinionated and link out as few times as possible, since we saw users get confused with the cross-links and getting lost / off-track. See my comment above - I think this link (and others) should be added to an appendix or More info section at the end of the doc.
___
*[cockroachcloud/quickstart.md, line 82 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnfZmuAs5g7D9dADZ4:-MZnrhhd5g0TXDcdEp2p:b-vo0mj7) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L82)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Added directions to save your connection string somewhere secure, but I think if we're trying to minimize links/maximize retention it might not be the place for password manager info. Might be something good to add to the regular Connect to Your Cluster docs?
</blockquote></details>

Agreed - we want to keep these directions as simple as possible here. It _might_ be good information to add it to the Connect to Your Cluster doc, but really, I don't know how much value we would get by saying `Save it in a secure place (i.e., a password manager).` - I assume users will understand what a secure place is, but that's just my 2 cents! I'll let you two decide what you think is necessary to add.
___
*[cockroachcloud/quickstart.md, line 15 at r5](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnq6AU6hxNxSiOA9W9:-MZnq6AU6hxNxSiOA9WA:b-hxl0fo) ([raw file](https://github.com/cockroachdb/docs/blob/eaa4fc7161938cf3eb2742d4556bbaa2bd182a75/cockroachcloud/quickstart.md#L15)):*
> ```
> For information on how to create a CockroachCloud cluster with other options, see [Create a Free Cluster](create-a-free-cluster.html).
> ```

Suggestion: Maybe this should be updated to point to an Appendix or More info section at the bottom of this page that provides a description + links to the other ways you can create a cluster. For example something like 

```
## More info

This page outlines the quickest way to get started with CockroachDB. For information on other options that are available when creating a CockroachCloud Free cluster, see the following:

- For information about how to connect securely to your cluster (recommended), see Authentication.
- etc
- etc
```

^ I could also see this list as a table too

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing, @gemma-shay, and @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 156 at r6](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZo6Am73MGPBP1UeBKu:-MZo6Am73MGPBP1UeBKv:bu9s651) ([raw file](https://github.com/cockroachdb/docs/blob/8dec7685e949d0efd6699f88deef6062a4b073c2/cockroachcloud/quickstart.md#L156)):*
> ```Markdown
>     ~~~
> 
> ## Appendix
> ```

nit: An Appendix should be the very last section of a document. That being said, you can either move the Appendix to come after the What's next? section, or you can combine the two (you can probably just remove the "What's next heading and keep the two separate lists). I think I would suggest combining the two since they have relatively similar goals. Also, now that I am reviewing, I'm not sure "Appendix" is descriptive enough of a heading -- suggest that we change it to "More information" or "Learn more" maybe.

**Review by emily-horing — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 82 at r4](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZnfZmuAs5g7D9dADZ4:-MZrkXTUB3TPRXqwtYFe:b-orto9y) ([raw file](https://github.com/cockroachdb/docs/blob/9a99a78d090db0e60a786ae54a838020b54773b3/cockroachcloud/quickstart.md#L82)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Agreed - we want to keep these directions as simple as possible here. It _might_ be good information to add it to the Connect to Your Cluster doc, but really, I don't know how much value we would get by saying `Save it in a secure place (i.e., a password manager).` - I assume users will understand what a secure place is, but that's just my 2 cents! I'll let you two decide what you think is necessary to add.
</blockquote></details>

I think more mature users will but there are users who we meet at hackathons and whatnot who will not really know what that means. I don't mind putting something in the appendix instead of here though. The link could be to another website, we don't have to be the authority on best password management practices, but since this guide is for beginners I think it might be helpful to give some kind guidance there. Not blocking though.

**Review by lnhsingh — COMMENTED** [review]
Just need to fix the old appendix link and then :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10427#-:-MZs-4HfBKJqiMNI_v38:bqa2drw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/quickstart.md, line 15 at r7](https://reviewable.io/reviews/cockroachdb/docs/10427#-MZrzy_Y4INNthdzYiQV:-MZrzy_Y4INNthdzYiQW:b-u9av04) ([raw file](https://github.com/cockroachdb/docs/blob/48d925a6bd198a7fd3192fb9e1cdf021048c4009/cockroachcloud/quickstart.md#L15)):*
> ```
> [appendix](#appendix)
> ```

nit: "see the Learn more section below" (or something along those lines)

**Pull request merged**
