### PR TITLE
netlify block

### PR DESCRIPTION
**Pull request by ebembi-crdb**
### Block Traffic from Bytedance Bots to Prevent Bandwidth Overages

This solves - https://cockroachlabs.atlassian.net/browse/DOC-10684

### CODE REVIEW

**Comment by ebembi-crdb** [comment]
Screenshot 2024-07-23 at 8 31 10 PM
Tested using bytedance user agent

**Review by shannonbradshaw — APPROVED** [review]
LGTM. Thanks!

Let's wait until Monday to deploy.

**Comment by shannonbradshaw** [comment]
@ebembi-crdb we can go live with this at any point, when you have a chance to monitor and revert if we break something.

**Review by shannonbradshaw — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
