### PR TITLE
v21.1.0-beta.4 release notes

### LINKED ISSUE #8938: v21.1.0-beta.4 Release notes
Prep date: 4/12/21
Release date: 4/19/21
SHA: `f5cca5bb`
Release Manager: @absterr08 
Issue: https://github.com/cockroachdb/cockroach/issues/63561

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [x] Run script to generate release notes
- [x] Update docs site
- [x] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by ianjevans**
Fixes #8938

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Nice - just had a few grammar/style nits.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10356#-:-MYf0W-o3zqnUijMwh__:b6h7kce)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[releases/v21.1.0-beta.4.md, line 42 at r2](https://reviewable.io/reviews/cockroachdb/docs/10356#-MYeyVYk-470hYJVpgIv:-MYeyVYk-470hYJVpgIw:br55vxe) ([raw file](https://github.com/cockroachdb/docs/blob/78681023a86fb6be92362c044f72af4aaef8e7b9/releases/v21.1.0-beta.4.md#L42)):*
typo:

> ```
> the the region
> ```

"the region"
___
*[releases/v21.1.0-beta.4.md, line 53 at r2](https://reviewable.io/reviews/cockroachdb/docs/10356#-MYeylEkAtMXcaQgSL19:-MYeylEkAtMXcaQgSL1A:b-f8im3n) ([raw file](https://github.com/cockroachdb/docs/blob/78681023a86fb6be92362c044f72af4aaef8e7b9/releases/v21.1.0-beta.4.md#L53)):*
nit:
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> - `ALTER DATABASE ADD REGION` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> - `ALTER DATABASE SET PRIMARY REGION` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> - `ALTER DATABASE ... SURVIVE ... FAILURE` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> - `ALTER DATABASE DROP REGION` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> - `CREATE TYPE` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> - `ALTER TYPE` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> - `DROP TYPE` renders correctly as an event in the [DB Console](../v21.1/ui-overview.html). [#63141][#63141]
> ```
</details>


A few things:

- All of these sentences are in present tense, but they don't have the "now" adverb. To follow the convention, I'd add "now" before "renders correctly".
- You probably don't need to link to ../v21.1/ui-overview.html after the first row.
- None of the statements link to their reference pages.
- This release note could be simplified, since these are technically all a single PR. I would make this a single change, with multiple bullets beneath it.

For example:

```
The following statements now render correctly as events in the [DB Console](../v21.1/ui-overview.html):

- [`ALTER DATABASE ADD REGION`](../v21.1/alter-database.html)
- `ALTER DATABASE SET PRIMARY REGION`
...
- [`DROP TYPE`](drop-type.html)

[#63141][#63141]
```
___
*[releases/v21.1.0-beta.4.md, line 67 at r2](https://reviewable.io/reviews/cockroachdb/docs/10356#-MYf-if_8F0rDkVZtjOO:-MYf-if_8F0rDkVZtjOP:b-qprg9h) ([raw file](https://github.com/cockroachdb/docs/blob/78681023a86fb6be92362c044f72af4aaef8e7b9/releases/v21.1.0-beta.4.md#L67)):*
grammar nit:

> ```
> This causes a bug when the `REGIONAL BY ROW` transformation fail.
> ```

"This caused a bug when the `REGIONAL BY ROW` transformation failed."

Unless the bug still exists?
___
*[releases/v21.1.0-beta.4.md, line 71 at r2](https://reviewable.io/reviews/cockroachdb/docs/10356#-MYf00SIC5TYktYxhZkJ:-MYf00SIC5TYktYxhZkK:bs2ng4z) ([raw file](https://github.com/cockroachdb/docs/blob/78681023a86fb6be92362c044f72af4aaef8e7b9/releases/v21.1.0-beta.4.md#L71)):*
grammar nit:

> ```
> may prevent
> ```

"would prevent"
___
*[releases/v21.1.0-beta.4.md, line 71 at r2](https://reviewable.io/reviews/cockroachdb/docs/10356#-MYf0Em09cvTgfMvEW-W:-MYf0Em09cvTgfMvEW-X:b-w0a0on) ([raw file](https://github.com/cockroachdb/docs/blob/78681023a86fb6be92362c044f72af4aaef8e7b9/releases/v21.1.0-beta.4.md#L71)):*
grammar nit:

> ```
> may corrupt
> ```

"would corrupt"
___
*[releases/v21.1.0-beta.4.md, line 80 at r2](https://reviewable.io/reviews/cockroachdb/docs/10356#-MYf0RdU4U0GRwXZidic:-MYf0RdU4U0GRwXZidid:bfe2hv3) ([raw file](https://github.com/cockroachdb/docs/blob/78681023a86fb6be92362c044f72af4aaef8e7b9/releases/v21.1.0-beta.4.md#L80)):*
minor minor nit

> ```
> vs
> ```

"versus"

**Comment by ianjevans** [comment]
> Nice - just had a few grammar/style nits.

I think I got all of these.

**Review by ericharmeling — APPROVED** [review]
Looks good!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10356#-:-MYflttY-urr4uRYO4bX:b-vs1prh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

**Comment by absterr08** [comment]
Hey @ianjevans, apologies for the late notice on this but the SHA for this release is being updated to [abc4eb5a](https://github.com/cockroachlabs/release-staging/commit/abc4eb5acda343e64415f0267ccd94805d7f2760). Please include the additional notes whenever you get the chance. Thank you!

**Pull request merged**
