### PR TITLE
Add Spelling.yml to vale/CockroachDB

### PR DESCRIPTION
**Pull request by jdkato**
Continuing #4236, this PR includes `vale/CockroachDB/Spelling.yml` (the rule implementation)
and `vale/vocab.txt` (the custom vocabulary file).

Running this on `v2.2` gives the following output (with sub-error alerts filtered):

```console
 v2.2/admin-ui-cluster-overview-page.md
 16:241  error  Use 'i.e.,' instead of 'i.e.'  CockroachDB.Abbreviations 


 v2.2/admin-ui-access-and-navigate.md
 15:30  error  'the' is repeated!  vale.Repetition 


 v2.2/admin-ui-replication-dashboard.md
 74:524  error  Did you really mean             CockroachDB.Spelling 
                'occasionaly'?                                       


 v2.2/admin-ui-statements-page.md
 55:123  error  'the' is repeated!  vale.Repetition 


 v2.2/architecture/overview.md
 49:448  error  Did you really mean             CockroachDB.Spelling 
                'Aysnchronous'?                                      


 v2.2/array.md
 7:58  error  Did you really mean             CockroachDB.Spelling 
              'homogenous'?                                        


 v2.2/architecture/replication-layer.md
 98:364   error  Use 'i.e.,' instead of 'i.e.'  CockroachDB.Abbreviations 
 102:123  error  Use 'i.e.,' instead of 'i.e.'  CockroachDB.Abbreviations 
 106:120  error  Use 'i.e.,' instead of 'i.e.'  CockroachDB.Abbreviations 


 v2.2/connection-parameters.md
 164:45  error  Did you really mean             CockroachDB.Spelling 
                'sonnection'?                                        


 v2.2/data-types.md
 13:53  error  Did you really mean             CockroachDB.Spelling 
               'homogenous'?                                        


 v2.2/demo-data-replication.md
 26:72  error  'command' is repeated!  vale.Repetition 


 v2.2/demo-serializable.md
 7:400   error  'end result' is redundant       vale.Redundancy      
 271:18  error  Did you really mean 'Posgres'?  CockroachDB.Spelling 
 273:49  error  Did you really mean 'Posgres'?  CockroachDB.Spelling 


 v2.2/file-an-issue.md
 15:124  error  Did you really mean             CockroachDB.Spelling 
                'Specfically'?                                       


 v2.2/learn-cockroachdb-sql.md
 78:103  error  Did you really mean 'whi'?  CockroachDB.Spelling 


 v2.2/kubernetes-performance.md
 385:794  error  Did you really mean             CockroachDB.Spelling 
                 'desparately'?                                       


 v2.2/null-handling.md
 351:182  error  Did you really mean             CockroachDB.Spelling 
                 'calcuations'?                                       


 v2.2/remove-nodes.md
 307:37  error  Did you really mean             CockroachDB.Spelling 
                'decomissioned'?                                     


 v2.2/show-index.md
 46:79  error  Did you really mean             CockroachDB.Spelling 
               'explictly'?                                         


 v2.2/scalar-expressions.md
 265:41  error  Did you really mean             CockroachDB.Spelling 
                'homogenous'?                                        
 285:44  error  Did you really mean             CockroachDB.Spelling 
                'insentively'?                                       


 v2.2/show-sessions.md
 20:177  error  Did you really mean             CockroachDB.Spelling 
                'wherease'?                                          


 v2.2/sql-dump.md
 63:169  error  Did you really mean             CockroachDB.Spelling 
                'demonstraion'?                                      


 v2.2/sql-statements.md
 20:130  error  Did you really mean             CockroachDB.Spelling 
                'availably'?                                         


 v2.2/sql-name-resolution.md
 98:79   error  Use 'e.g.,' instead of 'e.g.'  CockroachDB.Abbreviations 
 99:322  error  Use 'e.g.,' instead of 'e.g.'  CockroachDB.Abbreviations 


 v2.2/table-expressions.md
 53:24  error  Did you really mean 'decribe'?  CockroachDB.Spelling 


 v2.2/start-a-node.md
 64:317  error  'can' is repeated!  vale.Repetition 


 v2.2/training/geo-partitioning.md
 211:27  error  'to' is repeated!  vale.Repetition 


 v2.2/uuid.md
 19:83  error  Did you really mean             CockroachDB.Spelling 
               'seperated'?

✖ 32 errors, 0 warnings and 0 suggestions in 331 files.  
```

I've gone through `vale/vocab.txt` and tried to ensure that it's free of *true* misspellings, but I can remove any terms that shouldn't be there.

### CODE REVIEW

**Comment by jseldess** [comment]
This is great. Thank you, @jdkato. How did you come up with that list of custom vocabulary?

**Comment by jdkato** [comment]
I ran Vale on your documentation without any ignored terms, copied all of the reported misspellings to the `vocab.txt` file, and then attempted to remove the "true positives" by hand. So, every word in that file occurs at least once in this repository.

**Comment by jseldess** [comment]
Excellent. Thanks again, @jdkato! LGTM. I'll merge.

**Comment by jseldess** [comment]
Actually, @jdkato, how are you running vale so that it picks up the vocab file? When I run `vale` locally from the root directory of the repo, it seems to look for the vocab file there and doesn't find it:

```
~/go/src/github.com/cockroachdb/docs$ vale --no-wrap v2.2
open /Users/jesseseldess/go/src/github.com/cockroachdb/docs/vocab.txt: no such file or directory
```

**Comment by jdkato** [comment]
Is your local version (`vale -v`) of Vale older than `v1.1.6`? If so, you'll need to update to a newer version or move the `vocab.txt` file to `docs/vocab.txt`.

I changed this in https://github.com/errata-ai/vale/issues/91 and newer versions will look in both locations, but older ones don't know about the new location (i.e., relative to `StylesPath`).

**Comment by jseldess** [comment]
Yeah, I'm running a much older version locally, and it looks like we're using an old version in our CI process as well: https://github.com/cockroachdb/docs/blob/master/ci/Dockerfile#L26

**Comment by jdkato** [comment]
There's actually a third option too: you can change the path in [Spelling.yml](https://github.com/cockroachdb/docs/blob/master/ci/vale/CockroachDB/Spelling.yml) from `ignore: vocab.txt` to `ignore: ci/vale/vocab.txt`. This will work older and newer versions.

(Sorry - I should've mentioned in this in the original PR.)

**Pull request merged**
