### PR TITLE
Added a note about timestamps in the Overview dashboard

### PR DESCRIPTION
**Pull request by james-sabel**
Added a note to clarify that all timestamps in the Overview dashboard are shown in Coordinated Universal Time (UTC) time zone.

I see the Overview dashboard page has an include file called **admin-ui-metrics-navigation.md** that explains something about the timeframe and date/time range shown in the UI. I just want to mention that I decided not to touch this file, because we decided to keep the time zone information in the Overview dashboard page only, so I put the note directly on that page, right after the include.

This way the note stays on the subject, while at the same time it won't show somewhere else where that include file might be in use.

This fixes issue #7707

### CODE REVIEW

**Review by taroface — CHANGES_REQUESTED** [review]
Thanks! Requesting two changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8556#-:-MJUkohV75iPiAv46Dbt:b-g4gz8h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @james-sabel and @taroface)

___
*[v20.2/admin-ui-overview-dashboard.md, line 12 at r1](https://reviewable.io/reviews/cockroachdb/docs/8556#-MJUkI9fDxT3eRL2PkNf:-MJUkI9fDxT3eRL2PkNg:b-7mboke) ([raw file](https://github.com/cockroachdb/docs/blob/4a9095cfa2c29f33f2f598f0ba852d7146b47975/v20.2/admin-ui-overview-dashboard.md#L12)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> All timestamps in the **Overview** dashboard are shown in Coordinated Universal Time (UTC) time zone.
> ```

Nit: I don't think we need the word "zone".

This applies to all dates in the UI, not just the Overview dashboard. So I'd replace `**Overview** dashboard` with `Admin UI`.

**Comment by james-sabel** [comment]
Thank you @taroface - so I changed "Overview dashboard" to "Admin UI" and removed the term "time zone" altogether, as the word "time" is already in "UTC".

**Review by taroface — APPROVED** [review]
LGTM! Thank you @james-sabel. Feel free to merge, and please don't forget to delete your branch after merging.

**Comment by james-sabel** [comment]
> Feel free to merge, and please don't forget to delete your branch after merging.

Hey @taroface , I'm sorry, but it is possible that I don't have the proper access to merge this pull request? (I'm sorry, I'm new to contributing on GitHub and I might be wrong about this, but I don't see the Merge option and it does say that only those with write access to this repository can merge pull requests).

**Comment by james-sabel** [comment]
Awesome, thank you!

**Comment by james-sabel** [comment]
Closes: #7707

**Comment by SWDevAngel** [comment]
@james-sabel LAST DAY TO ORDER!!!
Hi James. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. We tried to reach you on email, but if you didn’t see the message please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link to order your gift. (If you don’t want a gift, we also have a charitable contribution choice.) All orders must be in by December 13 (that’s tomorrow!), so please send this asap. :)

**Pull request merged**
