### PR TITLE
Document operator operation and precedence

### PR DESCRIPTION
**Pull request by mjibson**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1322)

### CODE REVIEW

**Comment by mjibson** [comment]
See: https://cloud.google.com/spanner/docs/functions-and-operators#operators

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[functions-and-operators.md, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1322#-KiXrUe05jeqscrKOIK0:-KiXrUe05jeqscrKOIK1:b-34hubr) ([raw file](https://github.com/cockroachdb/docs/blob/9ae0bb5e68648949c9ba9f9344917479dca09730/functions-and-operators.md#L58)):*
> ```Markdown
> | 17 | `OR` | Logical OR | binary |
> 
> Operators with the same precedence are left associative. This means that those operators are grouped together starting from the left and moving right.
> ```

Can we move this and the following line before the table?  Scrolling through it I was confused as to what operators with the same precedence meant and didn't know if the information was going to be in this document.

---

*[functions-and-operators.md, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1322#-KiXs7Ow4gr51nIvPab5:-KiXs7Ow4gr51nIvPab6:b-uwiwp5) ([raw file](https://github.com/cockroachdb/docs/blob/9ae0bb5e68648949c9ba9f9344917479dca09730/functions-and-operators.md#L60)):*
> ```Markdown
> Operators with the same precedence are left associative. This means that those operators are grouped together starting from the left and moving right.
> 
> Comparison operators (including `LIKE`, `~`, and `IS`) are non associative.
> ```

Just like you explain what "left associative" means, can I get a quick explanation of what "non associative" means? I don't quite understand its meaning in the Spanner docs, either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1322)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[functions-and-operators.md, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1322#-KiXrUe05jeqscrKOIK0:-KiYL4A_N5YGZBI4UT6l:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9ae0bb5e68648949c9ba9f9344917479dca09730/functions-and-operators.md#L58)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Can we move this and the following line before the table?  Scrolling through it I was confused as to what operators with the same precedence meant and didn't know if the information was going to be in this document.
</blockquote></details>

Done.

---

*[functions-and-operators.md, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1322#-KiXs7Ow4gr51nIvPab5:-KiYL4L2TcWVc6FR3Kqr:b-n322xt) ([raw file](https://github.com/cockroachdb/docs/blob/9ae0bb5e68648949c9ba9f9344917479dca09730/functions-and-operators.md#L60)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Just like you explain what "left associative" means, can I get a quick explanation of what "non associative" means? I don't quite understand its meaning in the Spanner docs, either.
</blockquote></details>

I've taken out the non associative stuff. It means that you can't do:

```
select true < true < true
```

even though you can do

```
select (true < true) < true
```

so it forces users to fully declare how the operators associate. I think we can get by without documenting it since no one writes "true < true < true" or similar things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1322)*

**Comment by mjibson** [comment]
Ping.

**Comment by sploiselle** [comment]
LGTM

**Pull request merged**
