### PR TITLE
Clarify docs for ORDER BY

### LINKED ISSUE #1490: Without ORDER BY, order is unspecified
One of the [examples](https://www.cockroachlabs.com/docs/select.html#order-retrieved-rows-by-one-column) states that by default, results are ordered by primary key. This is untrue: without an ORDER BY, there are no guarantees about the order of results, and in distsql the order is unpredictable (the order is based on which nodes respond the quickest). We should remove this claim, and add an explicit notice that order is unspecified unless an ORDER BY is specified (this sometimes confuses users; see cockroachdb/cockroach#16306)

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1490

### CODE REVIEW

**Comment by sploiselle** [comment]
Awesome, @jseldess. I think this would also make a solid entry in the [SQL FAQ](https://www.cockroachlabs.com/docs/sql-faqs.htm).

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[select.md, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-Km-UTw9YMbIQCLpp8ht:-Km-UTw9YMbIQCLpp8hu:b-r5c1ww) ([raw file](https://github.com/cockroachdb/docs/blob/b2669069193d50a05fcbc3e607861c59b1c4f0ca/select.md#L38)):*
"Otherwise" is a little confusing here because it's a double-negative-like: "When this _isn't_ included..._Otherwise_..."

Maybe something like...

> When `ORDER BY` is not included in a query, rows are not sorted by any consistent criteria. Instead of ordering rows, CockroachDB returns them as the coordinating node receives them.

---

*[select.md, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-Km-WFLE6olUT3W8jm-4:-Km-WFLE6olUT3W8jm-5:b80be68) ([raw file](https://github.com/cockroachdb/docs/blob/b2669069193d50a05fcbc3e607861c59b1c4f0ca/select.md#L458)):*
> ```Markdown
> You can use an `ORDER BY` clause to sort retrieved rows by one or more columns.
> 
> {{site.data.alerts.callout_info}}When <code>ORDER BY</code> is not included in a query, CockroachDB retrieves rows as they become available from relevant nodes. Otherwise, the rows are not sorted by any consistent criteria.{{site.data.alerts.end}}
> ```

Same recommendation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-:-Km-UJo2yhkYCiU3rCS9:bq6jinp)*

**Comment by jseldess** [comment]
TFTR, @sploisell!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[select.md, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-Km-UTw9YMbIQCLpp8ht:-Km-iSom3FxOqKejwk8h:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b2669069193d50a05fcbc3e607861c59b1c4f0ca/select.md#L38)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

"Otherwise" is a little confusing here because it's a double-negative-like: "When this _isn't_ included..._Otherwise_..."

Maybe something like...

> When `ORDER BY` is not included in a query, rows are not sorted by any consistent criteria. Instead of ordering rows, CockroachDB returns them as the coordinating node receives them.
</blockquote></details>

Done.

---

*[select.md, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-Km-WFLE6olUT3W8jm-4:-Km-iTvGR6WzPwFT2O8M:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/b2669069193d50a05fcbc3e607861c59b1c4f0ca/select.md#L458)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Same recommendation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-:-Km-kdC6pK5AvfFXNf_4:b3zvhp9)*

**Comment by sploiselle** [comment]
:lgtm: fwiw

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-:-Km-lIdSOU6JkH8LqXbH:bb71oku)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1526#-:-Km2BL1Tgv0r_ZRLLBhV:bnfp4nl)*

**Pull request merged**
