### PR TITLE
[WIP] Simplify JDBC code sample

### LINKED ISSUE #4621: Simplify jdbc code samples
As discussed with @timveil, @awoods187, and @rmloveland, we should simplify [our JDBC code samples](https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb.html#basic-example) (e.g., use fewer classes) so as to provide an easier, more intuitive point-of-entry for Java developers.

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #4621, #3578, #4399.

Summary of changes:

- Update 'Build a Java App with CockroachDB' to use the Java DAO pattern

- Add a 'Recommended Practices' section that includes information about
  IMPORT, recommended batch size, and the JDBC INSERT rewriting flag

TODO:

- Update "secure" code sample to use certs.  Not worth doing yet until
  this code is reviewed by someone with Java expertise and updated to
  match good style, etc.  Once that is done, the secure code sample in
  this PR will be updated with the necessary cert munging.

### CODE REVIEW

**Comment by rmloveland** [comment]
@jordanlewis can you please help me find someone on our engineering team who has Java expertise and would be willing to review this PR for:

- Idiomatic Java/JDBC usage
- Errors/mistakes in how it interacts with the DB
- Better ways to describe what this doc is trying to describe, if possible
- General smurfiness (💙 )

I am expecting that the code and possibly the doc surrounding it will need updates according to the criteria above, hence the WIPness.

My initial plan was to ask around but I spoke to @awoods187 and he recommended coming directly to you as a team lead / engineering manager type person.

Happy to discuss offline if that's easier/quicker.

**Comment by jordanlewis** [comment]
Hey @rmloveland, will follow up with you offline. Thanks for bringing this up!

**Comment by jordanlewis** [comment]
Hey @rafiss, could you please take a look at this code sample while your Java knowledge is still fresh?

The context is that we're trying to improve our docs for Java users in particular. We'd like to show a canonical way of interacting with the database. Your review would be valuable, as you have recent Java experience.

**Comment by rafiss** [comment]
Sure thing! Some of the suggestions I had might not really be worth doing. Some of the idioms or conventions I suggested probably are not important for this simple example.

**Comment by rmloveland** [comment]
Thanks for the review @rafiss!  Working on making these changes now.

**Comment by rmloveland** [comment]
Whoa, looks like Reviewable really messed up the Github comment output on this one.  Everything looks OK to me on the [actual review page](https://reviewable.io/reviews/cockroachdb/docs/4855#-LgEHnrQ1S-GoSiG8quS) tho

**Comment by rmloveland** [comment]
Thank you @rafiss !!!!!!1!

Apologies in advance for a bit of forthcoming noise, I have to make some uninteresting updates re: secure connections / certs now that we have nailed down the main code samples -- then it goes in for docs team internal review.

**Pull request merged**
