### PR TITLE
Release notes for beta-20160623

### PR DESCRIPTION
**Pull request by bdarnell**
Getting an early start because of my vacation. @mberhault and @jseldess, you'll need to finish this up tomorrow, and next week you're on your own. These notes are accurate as of cockroachdb/cockroach@6d60fb62881a, but feel free to incorporate anything else that gets merged between now and our usual wednesday morning cutoff. The mention of the new UI is a placeholder; I don't know how we want to message this to users.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/409)

### CODE REVIEW

**Comment by mberhault** [comment]
Thank @bdarnell, I'll finish it up once I've picked a sha tomorrow morning, then carry on from there. I'll grab the the UI folks to figure out the wording for the next version.

FYI: I'm on vacation starting next Monday, so I won't be able to work on releases for a while. We should pick a replacement. @petermattis: suggestions? Most of the process (from picking a sha to release) is documented at https://github.com/cockroachdb/cockroach/wiki/Release-Process

**Comment by mberhault** [comment]
@bdarnell: when you have a minute, can you add any tips/commands you use when building the release notes?

**Comment by bdarnell** [comment]
Mostly it's just a lot of poring through `git log` for everything since the last beta. I use the emacs `magit` interface for that. Two specific commands are `git log --oneline --merges beta-2016####..beta-2016#### | wc -l` to count PRs, and `git log -- format=%aN --no-merges beta-2016####..beta-2016#### | sort -u` to get the list of contributors.

**Comment by mberhault** [comment]
Thanks. I'll see if I can put some of that in the release docs as well. Enjoy the vacation!

**Comment by jseldess** [comment]
:lgtm: As usual, I'll add links and doc updates in a separate pr once this is merged. Happy to work with ui guys to tweak the ui messaging as well.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/409#-:-KKsq3JfJzoAJBWgpkLy:179050048)*

**Comment by mberhault** [comment]
No beta for this week. I'll keep this around or a bit though.

**Comment by petermattis** [comment]
To expand on @mberhault's terse message, we encountered a bug during testing of this week's beta which we haven't been able to track down yet. We're going to skip the beta release for this week.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/pull/429

**Pull request closed without merging**
