### PR TITLE
Execute basic statements from a php client

### PR DESCRIPTION
**Pull request by OlivierBarbier**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/184)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Hi @OlivierBarbier, thanks for your contribution. I just opened a PR which does the "same" (but adds some more transactional stuff). Would you mind waiting until that merges and then add any comments you have as a follow-up PR? I'm not familiar with PHP, so I'm sure there are some things you'll have to add. Also, feel free to comment on the PR https://github.com/cockroachdb/docs/pull/183 itself.

**Comment by OlivierBarbier** [comment]
No, it's ok. I don't mind ;)

**Comment by jseldess** [comment]
@tschottdorf, @andreimatei, any updates on this one?

**Comment by tschottdorf** [comment]
@OlivierBarbier if you feel that the code which currently lives on `master` is non-idiomatic, we'd love your input. I'm going to close this for now, thanks!

**Pull request closed without merging**
