### PR TITLE
Improve cockroach quit and rolling upgrade docs

### LINKED ISSUE #1748: version migration for backwards incompatible functionality
RFC: https://github.com/cockroachdb/cockroach/pull/16977

### PR DESCRIPTION
**Pull request by jseldess**
- Improve `cockroach quit` docs.
  - Explain draining and recommend increase time till store dead in certain cases. 
  - Clarify `--certs-dir` flag. 
  - Improve examples.
- Improve rolling upgrade docs. Fixes #1748.
  - Add pre- and post-upgrade instructions. 
  - Better surface rec to script upgrade and warning to upgrade one node a time.
- Update link to rolling upgrades from cluster settings doc.

### CODE REVIEW

**Comment by jseldess** [comment]
@bdarnell, wouldn't mind your eyes on this as well.

**Comment by robert-s-lee** [comment]
The instructions here seem fine.  How about additional pre-requisite sections in addition to the load balance

- take cluster debug to capture cluster state before the upgrade should things not go according the the plan
- make sure there are no un-available ranges or under replicated ranges before the upgrade starts

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[v1.1/stop-a-node.md, line 17 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KtvmJlp-Q5CCCgGsNhL:-KtvmJlp-Q5CCCgGsNhM:b-4eqhhv) ([raw file](https://github.com/cockroachdb/docs/blob/d78c6f5ad1bfb5f04d27746d1ac17a71f7a88dc2/v1.1/stop-a-node.md#L17)):*
> ```Markdown
> ### How It Works
> 
> When you stop a node, CockroachDB lets the node finish in-flight requests and transfers all **range leases** off the node before shutting it down. If the node then stays offline for more than 5 minutes, the cluster considers the node dead and starts to transfer its **range replicas** to other nodes as well.
> ```

Add "(by default)" after "5 minutes". Or maybe just link to a page about system settings instead of repeating "5 minutes" in multiple places (since that value could change). 

---

*[v1.1/stop-a-node.md, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-Ktvn2OdH3MRrpAd6WqR:-Ktvn2OdH3MRrpAd6WqS:bg9hgqi) ([raw file](https://github.com/cockroachdb/docs/blob/d78c6f5ad1bfb5f04d27746d1ac17a71f7a88dc2/v1.1/stop-a-node.md#L29)):*
> ```Markdown
> ### Considerations
> 
> Before temporarily stopping a node to [upgrade its version of CockroachDB](upgrade-cockroach-version.html), if you expect the node to be offline for longer than 5 minutes, you should first set the `server.time_until_store_dead` [cluster setting](cluster-settings.html) to higher than the `5m0s` default. For example, if you think the node might be offline for up to 8 minutes, you might change this setting as follows:
> ```

I'd remove "to upgrade its version of CockroachDB" here. There's no reason for upgrading a cockroachdb version to take more than a few seconds. The more likely reason to increase this value is when you're upgrading other system software (especially the kernel). 

Should we also include a reminder to set it back to 5 minutes once the maintenance is done? (If not, and it's fine to run with a large time_until_store_dead, should we just increase the default?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-:-KtvpLrYUHi3R7ZLHb4L:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[v1.1/stop-a-node.md, line 17 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KtvmJlp-Q5CCCgGsNhL:-KtwTsYg4akNjT2mFOQt:b24drto) ([raw file](https://github.com/cockroachdb/docs/blob/d78c6f5ad1bfb5f04d27746d1ac17a71f7a88dc2/v1.1/stop-a-node.md#L17)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add "(by default)" after "5 minutes". Or maybe just link to a page about system settings instead of repeating "5 minutes" in multiple places (since that value could change). 
</blockquote></details>

Clarified that this is the default. It's a good idea to document such system settings. We have an issue in the backlog (https://github.com/cockroachdb/docs/issues/1351). Hopefully there'll be time for 1.2.

---

*[v1.1/stop-a-node.md, line 29 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-Ktvn2OdH3MRrpAd6WqR:-KtwVbqdLGCZBcsj0z3V:b-m7qo52) ([raw file](https://github.com/cockroachdb/docs/blob/d78c6f5ad1bfb5f04d27746d1ac17a71f7a88dc2/v1.1/stop-a-node.md#L29)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd remove "to upgrade its version of CockroachDB" here. There's no reason for upgrading a cockroachdb version to take more than a few seconds. The more likely reason to increase this value is when you're upgrading other system software (especially the kernel). 

Should we also include a reminder to set it back to 5 minutes once the maintenance is done? (If not, and it's fine to run with a large time_until_store_dead, should we just increase the default?)
</blockquote></details>

Revised. Please take another look. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899)*

**Comment by jseldess** [comment]
Still need to address Roberts suggestions.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-:-KtwXKFJKODWIRzufX49:b-qwghm6)*

**Comment by jseldess** [comment]
@bdarnell and @robert-s-lee, I've added more prerequisites to the rolling upgrade page and tried to improve the structure a bit. It'd be great if one of you could take one more look: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b5e11d6cb5579c83779c1322265e7e0d2c9736e0/dev/upgrade-cockroach-version.html

**Comment by bdarnell** [comment]
Should a user upgrading from 1.0 to 1.1 follow the instructions in the 1.0 version of upgrade-cockroach-version or the 1.1 version? I would suggest that they should use the docs for the version they are upgrading *to*, so the 1.0 page needs a warning that "This page provides instructions for upgrading to new patch releases of CockroachDB 1.0. To upgrade from 1.0.x to 1.1, see {link}". Then the 1.1 page would cover the upgrade from 1.0.x to 1.1 as well as patch releases within the 1.1.x series, and 1.2 will get its own version of the page, etc. 

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[v1.1/upgrade-cockroach-version.md, line 16 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC9w_41Y__xVkDnwEy:-KuC9w_41Y__xVkDnwEz:b-5jh2l6) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L16)):*
> ```Markdown
> - Make sure your cluster is behind a load balancer, or your clients are configured to talk to multiple nodes. If your application communicates with a single node, stopping that node to upgrade its CockroachDB binary will cause your application to fail.
> 
> - By default, if a node stays offline for more than 5 minutes, the cluster will consider it dead and will rebalance its data to other nodes. Therefore, if you expect any nodes to be down for more than 5 minutes during a rolling upgrade, you should first set the `server.time_until_store_dead` [cluster setting](cluster-settings.html) to higher than the `5m0s` default. For example, if you think a node might be offline for up to 8 minutes, you might change this setting as follows:
> ```

I'd remove this from the rolling upgrade docs. If you expect more than 5 minutes downtime per node, you're doing something wrong. 

---

*[v1.1/upgrade-cockroach-version.md, line 30 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC3iYMGq9eg6AN4M-h:-KuC3iYNXyVd5RQBHopa:b-9rzisx) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L30)):*
> ```Markdown
> ## Step 1. Verify cluster health
> 
> 1. SSH to any node in the cluster.
> ```

This is optional if you have the necessary certificates to run the `cockroach` command remotely. 

---

*[v1.1/upgrade-cockroach-version.md, line 39 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC45oJ6qCsnEHaGgLg:-KuC45oJ6qCsnEHaGgLh:b-3cspq8) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L39)):*
> ```Markdown
> 
>     In the response, make sure `ranges_unavailable` and `ranges_underreplicated` show `0` for all nodes. If there are unavailable or underreplicated ranges in your cluster, performing a rolling upgrade increases the risk that ranges will lose a majority of their replicas and cause cluster unavailability. Therefore, it's important to identify and resolve the cause of range unavailability and underreplication before beginning your upgrade.
> ```

Also ensure that all nodes are running the same version, and that you are not skipping minor versions (it's OK to skip patch versions. Minor versions increment the second component of the version number, and patch versions increment the third)

For future minor upgrades (from 1.1 to 1.2), you'll also need to run "show cluster setting version" and make sure that it has the correct value (i.e. that it's 1.1, and it hasn't been left at 1.0).  Following the versioning scheme I suggested above, that would not appear until we write the 1.2 version of this doc. 

---

*[v1.1/upgrade-cockroach-version.md, line 40 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC3yI35GSbcy8hPN5T:-KuC3yI4NypeGyMEN8Yf:b-ijhx2x) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L40)):*
> ```Markdown
>     In the response, make sure `ranges_unavailable` and `ranges_underreplicated` show `0` for all nodes. If there are unavailable or underreplicated ranges in your cluster, performing a rolling upgrade increases the risk that ranges will lose a majority of their replicas and cause cluster unavailability. Therefore, it's important to identify and resolve the cause of range unavailability and underreplication before beginning your upgrade.
> 
> ## Step 2. Collect debug information
> ```

Taking a fresh backup (using the enterprise backup command or `cockroach dump`) is also recommended before starting the process. 

---

*[v1.1/upgrade-cockroach-version.md, line 158 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC5jQZV41KADzciSc5:-KuC5jQZV41KADzciSc6:b5wz5nu) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L158)):*
> ```Markdown
> 
> 8. Wait at least one minute after the node has rejoined the cluster, and then repeat these steps for the next node.
> ```

Talk about downgrades: at any time during or after the rolling upgrade process, it is possible to abort the change by following this procedure in reverse and switching every node back to the previous version. (If you must do this, we recommend making a second `cockroach debug zip` and contacting CRL for support)

For minor upgrades, there is another step: Once you are satisfied with the performance and stability of the new version (we recommend waiting at least a day before proceeding with the next step), it is time to make the upgrade permanent. Connect to the cluster as root and run `set cluster setting version='1.1'`. Once this is done, it will no longer be possible to downgrade to 1.0 (except by restoring from a backup, so another fresh backup is recommended at this point). Certain new features of version 1.1 cannot be used until this step has been completed (and this step is also required before the cluster can be upgraded to version 1.2). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-:-KuC803Y5ZMOvR86OF2y:bozmtuj)*

**Comment by jseldess** [comment]
Thanks for that guidance. I was planning to do broader updates around version upgrades in a subsequent PR, but I might as well just extend this one. I've added notes to these pages to clarity when to use which page. I'll work in more updates soon.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[v1.1/upgrade-cockroach-version.md, line 16 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC9w_41Y__xVkDnwEy:-KuL_mPk4UHKi0sJqi-4:bz061qm) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L16)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd remove this from the rolling upgrade docs. If you expect more than 5 minutes downtime per node, you're doing something wrong. 
</blockquote></details>

OK, done. I thought it might be important to be cautious and explicit.

---

*[v1.1/upgrade-cockroach-version.md, line 30 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC3iYMGq9eg6AN4M-h:-KuLaL-_s75ELnSsZ4ak:b-nt640e) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L30)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is optional if you have the necessary certificates to run the `cockroach` command remotely. 
</blockquote></details>

There are multiple ways to do these things. I need to come up with a good, concise way to summarize the options. For now, I'm removing this step and relying on the link `node` docs to get them there.

---

*[v1.1/upgrade-cockroach-version.md, line 39 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC45oJ6qCsnEHaGgLg:-KuLgfYb1l4NtFfqVtSk:b-z20sjy) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L39)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Also ensure that all nodes are running the same version, and that you are not skipping minor versions (it's OK to skip patch versions. Minor versions increment the second component of the version number, and patch versions increment the third)

For future minor upgrades (from 1.1 to 1.2), you'll also need to run "show cluster setting version" and make sure that it has the correct value (i.e. that it's 1.1, and it hasn't been left at 1.0).  Following the versioning scheme I suggested above, that would not appear until we write the 1.2 version of this doc. 
</blockquote></details>

Thanks, @bdarnell. Worked in checking the version. For now, since nobody will be skipping minor releases, I've left that detail out. 

Question: Is it necessary to work in steps described in the [version migration for backwards incompatible changes](https://github.com/cockroachdb/cockroach/pull/16977) RFC? Or is that not relevant until upgrading from 1.1 to 1.2?

---

*[v1.1/upgrade-cockroach-version.md, line 40 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC3yI35GSbcy8hPN5T:-KuLn5AdJQ5ferDE1Oeg:bmw71hc) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L40)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Taking a fresh backup (using the enterprise backup command or `cockroach dump`) is also recommended before starting the process. 
</blockquote></details>

Done. Added backup as an explicit step.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-:-KuLgBowuqhgOX17MFmy:befnz2p)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[v1.1/upgrade-cockroach-version.md, line 39 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC45oJ6qCsnEHaGgLg:-KuLoa1xAqhB11eedRzW:b-zhvgmn) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L39)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Thanks, @bdarnell. Worked in checking the version. For now, since nobody will be skipping minor releases, I've left that detail out. 

Question: Is it necessary to work in steps described in the [version migration for backwards incompatible changes](https://github.com/cockroachdb/cockroach/pull/16977) RFC? Or is that not relevant until upgrading from 1.1 to 1.2?
</blockquote></details>

Yes, those steps are relevant for upgrading from 1.0 to 1.1. I think that's consistent with what I've been saying here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-:-KuLoqNwRkMHNOnEylV5:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[v1.1/upgrade-cockroach-version.md, line 39 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC45oJ6qCsnEHaGgLg:-KuQPmUGDmhcOKS2O037:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L39)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yes, those steps are relevant for upgrading from 1.0 to 1.1. I think that's consistent with what I've been saying here. 
</blockquote></details>

Done.

---

*[v1.1/upgrade-cockroach-version.md, line 158 at r6](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuC5jQZV41KADzciSc5:-KuQPlpmMjkB2STBuEGh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/9e7920cdc9fcc83ab990971b8e23fdd3e348da10/v1.1/upgrade-cockroach-version.md#L158)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Talk about downgrades: at any time during or after the rolling upgrade process, it is possible to abort the change by following this procedure in reverse and switching every node back to the previous version. (If you must do this, we recommend making a second `cockroach debug zip` and contacting CRL for support)

For minor upgrades, there is another step: Once you are satisfied with the performance and stability of the new version (we recommend waiting at least a day before proceeding with the next step), it is time to make the upgrade permanent. Connect to the cluster as root and run `set cluster setting version='1.1'`. Once this is done, it will no longer be possible to downgrade to 1.0 (except by restoring from a backup, so another fresh backup is recommended at this point). Certain new features of version 1.1 cannot be used until this step has been completed (and this step is also required before the cluster can be upgraded to version 1.2). 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 1 of 1 files at r8, 3 of 4 files at r9, 2 of 2 files at r10.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v1.0/stop-a-node.md, line 73 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuUy1OFTd6xJFpHyOMj:-KuUy1OFTd6xJFpHyOMk:b-ku81rq) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.0/stop-a-node.md#L73)):*
> ```Markdown
> 1. SSH to the machine where the node is running.
> 
> 2. If the node is running in the background, run the `cockroach quit` command:
> ```

Killing the node with a signal is also an option (and IMHO much simpler than `cockroach quit`). Using `cockroach quit` in secure mode requires a client cert to live on the node, which is not a part of our secure deployment docs (and is not generally recommended)

If you're using a process manager for automatic restarts, you must use that process manager to stop the process without restarting it. 

---

*[v1.0/stop-a-node.md, line 91 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuUxy3jPi0oQQSOEZB1:-KuUxy3jPi0oQQSOEZB2:b-93vcgo) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.0/stop-a-node.md#L91)):*
> ```Markdown
> ### Stop a Node from Another Machine
> 
> 1. [Install the `cockroach` binary](install-cockroachdb.html) on a machine separate from the node.
> ```

And in secure mode, you need a client cert. (does `quit` need a root cert or is any cert OK?)

---

*[v1.1/upgrade-cockroach-version.md, line 170 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuVAOMkc0STXrD6lYyo:-KuVAOMkc0STXrD6lYyp:bq5rgh1) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.1/upgrade-cockroach-version.md#L170)):*
> ```Markdown
> 1. [Back up the cluster](back-up-data.html).
> 
> 2. Start the [`cockroach sql`](use-the-built-in-sql-client.html) shell against any node in the cluster and execute the following query:
> ```

This is necessary for the first upgrade from 1.0.x to 1.1.x. For upgrades within the 1.1.x series, no action is necessary to finalize the upgrade. 

---

*[v1.1/upgrade-cockroach-version.md, line 176 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuVAk6OGYxRDpNqBuD6:-KuVAk6OGYxRDpNqBuD7:beu9d0u) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.1/upgrade-cockroach-version.md#L176)):*
> ```Markdown
>     ~~~
> 
>     {{site.data.alerts.callout_info}}Once this is done, it will no longer be possible to perform a rolling downgrade to 1.0. In the event of a catastrophic failure or corruption due to usage of new features requiring 1.1, the only option is to start a new cluster using the old binary and then restore from one of the backups created prior to finalizing the upgrade.{{site.data.alerts.end}}
> ```

If you want to add a little more detail here (a carrot to go along with the stick), say that finalizing the upgrade is necessary to enable certain performance improvements and bug fixes that were introduced in 1.1. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-:-KuVAvfeUETa6Kgoj2af:bb6ywmx)*

**Comment by jseldess** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v1.0/stop-a-node.md, line 73 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuUy1OFTd6xJFpHyOMj:-KuVkRwJOw7ZS-qTGj09:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.0/stop-a-node.md#L73)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Killing the node with a signal is also an option (and IMHO much simpler than `cockroach quit`). Using `cockroach quit` in secure mode requires a client cert to live on the node, which is not a part of our secure deployment docs (and is not generally recommended)

If you're using a process manager for automatic restarts, you must use that process manager to stop the process without restarting it. 
</blockquote></details>

Done.

---

*[v1.0/stop-a-node.md, line 91 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuUxy3jPi0oQQSOEZB1:-KuVxKfVZyUqcjQE2bB5:byr54p2) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.0/stop-a-node.md#L91)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

And in secure mode, you need a client cert. (does `quit` need a root cert or is any cert OK?)
</blockquote></details>

You're right. It needs the the `root` cert and key. Done.

---

*[v1.1/upgrade-cockroach-version.md, line 170 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuVAOMkc0STXrD6lYyo:-KuVdBN3AKjwDUp_uumK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.1/upgrade-cockroach-version.md#L170)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is necessary for the first upgrade from 1.0.x to 1.1.x. For upgrades within the 1.1.x series, no action is necessary to finalize the upgrade. 
</blockquote></details>

Done.

---

*[v1.1/upgrade-cockroach-version.md, line 176 at r10](https://reviewable.io:443/reviews/cockroachdb/docs/1899#-KuVAk6OGYxRDpNqBuD6:-KuVeHclCoE7zuK2IHWI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3523055de17d758eb866d153fee238d402ad9c38/v1.1/upgrade-cockroach-version.md#L176)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If you want to add a little more detail here (a carrot to go along with the stick), say that finalizing the upgrade is necessary to enable certain performance improvements and bug fixes that were introduced in 1.1. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1899)*

**Pull request merged**
