### PR TITLE
Add release notes page

### PR DESCRIPTION
**Pull request by bdarnell**
Not sure how to upload this to staging but here's what it looks like.
screenshot 2016-04-06 18 34 53

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/203)

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[release-notes.md, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEhjBT5Pu4vbbbVwJ6Q:-KEhjBT5Pu4vbbbVwJ6R:-1802974427) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L15)):*
s/where/were/

---

*[release-notes.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEhjONV7_UQQsEnXlOU:-KEhjONV7_UQQsEnXlOV:-1445758331) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L46)):*
need to word this more carefully - it only applies to the UI port

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/203#-:-KEhjhgs6IBwABhRXqft:1417088721)*

**Comment by knz** [comment]
LGTM

**Comment by petermattis** [comment]
Very nice. I'll be interested in how much work it takes next week to create the release notes as I imagine there was a bit of one-time effort to produce them this week.

**Comment by JackKrupansky** [comment]
Looks good.

But if I was at the doc home, how would I know to look under "Learn How It Works"?

I would say that someone is looking at release notes when upgrading, so somewhere around Install, which currently under Getting Started.

**Comment by jseldess** [comment]
Agree with everyone that this looks great. Will add just a few minor suggestions.

Also agree with Jack that we need to make these a little more visible. I think we can leave the page where it is for now but call out a link on the install page. I can add that once this is merged.

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[release-notes.md, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEiXvrjdRw294YRB61T:-KEiXvrjdRw294YRB61U:948635219) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L2)):*
Let's use title case: Release Notes

---

*[release-notes.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEiYM-yeavU19GK0S5N:-KEiYM-yeavU19GK0S5O:1775939185) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L11)):*
Maybe reorder: "Any existing databases using the `DECIMAL` type must be deleted and recreated from scratch. Previously, columns of this type were encoded incorrectly."

---

*[release-notes.md, line 14 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEi_94ckYXsY1fVrjAR:-KEi_94ckYXsY1fVrjAS:-1219904668) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L14)):*
"`SELECT` statements must now specify one or more..."

Also, I'd change the parenthetical into a sentence: "Previously, statements such as..."

---

*[release-notes.md, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEie_RULYm2MOs8pRt5:-KEie_RULYm2MOs8pRt6:1385070991) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L24)):*
"Added support for..."

---

*[release-notes.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEhjONV7_UQQsEnXlOU:-KEicMMsq-MKqcUhKO0R:-417204512) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L46)):*
Would it be more precise to say: "In secure mode, plain HTTP requests to the `http-port` used by the Admin UI are now redirected to HTTPs."

---

*[release-notes.md, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEickPc5JaC-bg_ZwyD:-KEickPc5JaC-bg_ZwyE:456430017) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L51)):*
"The `cockroach zone set` command..."

Also, add period at end of sentence.

---

*[release-notes.md, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEieC5fwfMG1zZmX0s_:-KEieC5fwfMG1zZmX0sa:-1968939592) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L54)):*
Are we saying "highlighted" because we're leaving some out? I think I'd prefer just "Bug Fixes".

---

*[release-notes.md, line 62 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEid0HidNIPfU0-WJM2:-KEid0HidNIPfU0-WJM3:457645152) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L62)):*
"Fixed a panic..."

And add period at end of sentence.

---

*[release-notes.md, line 74 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEidVo3lXgpR5amPbA9:-KEidVo3lXgpR5amPbAA:-924354134) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L74)):*
Maybe start this with heading: ### Contributors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/203)*

**Comment by bdarnell** [comment]
@petermattis I think it'll take about the same amount of time next week; there wasn't a lot of first-time setup work here. I think it's worth the effort; the one thing I might change to make things a little easier would be to get more selective about what changes make it into the notes.

"Learn how it works" isn't ideal, but I don't think it belongs under install/"get started" either - we want to keep that section streamlined and new users won't care about the change history. We should probably have a page with upgrade instructions and the release notes should ultimately live next to that. Or maybe the release notes are a top-level entry in the sidebar; that's what I did on tornadoweb.org.

---

Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[release-notes.md, line 2 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEiXvrjdRw294YRB61T:-KEl9UrLFrCxSSyBHNr1:355393851) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L2)):*
Done, and also changed the sub-headings to title case since that looks like what we do on other pages.

---

*[release-notes.md, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEhjONV7_UQQsEnXlOU:-KEl8WVqJQhYJSHZ7WDI:219056305) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L46)):*
Used Jesse's suggested language.

---

*[release-notes.md, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/203#-KEieC5fwfMG1zZmX0s_:-KEl8JJD1fIc5va4MRKO:-1249531872) ([raw file](https://github.com/cockroachdb/docs/blob/f0ce71eef24ab33d0265b51991a2f949f186e4b5/release-notes.md#L54)):*
Yes; changed back to "Bug fixes". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/203#-:-KEl8_MzqLDtJCFPqRxU:1919673246)*

**Comment by petermattis** [comment]
@bdarnell Ok. How much time did it take to create the notes this week?

**Comment by JackKrupansky** [comment]
How about "What's New" as a top-level item?

**Comment by bdarnell** [comment]
@petermattis Maybe an hour? I wasn't watching the clock.

**Comment by JackKrupansky** [comment]
There is the question of how to organize the RNs after the first one. It would be friendly to just see the latest one, but it should be possible to browse (and search) the rest.

One difference between RNs and CHANGES.txt is that RNs are (traditionally) intended to be a summary/highlights while CHANGES.txt is intended to be exhaustive. If each issue were tagged with its release name, issue search can be used a lot more effectively for what a traditional CHANGES.txt was used. For example, search for relevant keywords in issues and then the release tag tells you which release the fix/feature was in.

**Comment by jseldess** [comment]
I like the idea of adding "Release Notes" as a top-level in the sidebar, Ben. You can change the RN file name to match the title, add a new section in `sidebar_doc.yml`, and list just that one RN for the time being. I'm also happy to do this myself before pushing to the live site, if you prefer.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/203#-:-KElExjVuNZYODQQtmp_:2031217812)*

**Comment by bdarnell** [comment]
@jseldess I'll merge this and leave the reorganization to you.

**Pull request merged**
