### PR TITLE
Update/specify the eval order in a way compatible with pg

### PR DESCRIPTION
**Pull request by knz**
Relevant pg docs:

https://www.postgresql.org/docs/10/static/sql-expressions.html#SYNTAX-EXPRESS-EVAL

https://www.postgresql.org/docs/10/static/functions-conditional.html#FUNCTIONS-CASE

https://www.postgresql.org/docs/10/static/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

+@knz, did you verify that Postgres guarantees short-circuit behavior for the operators other than `CASE`? I don't want to go beyond what Postgres does...

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3307#-:-LG5vPoG6RPWc10TGCL5:b-cc9639)*

**Comment by knz** [comment]
> did you verify that Postgres guarantees short-circuit behavior for the operators other than CASE? I don't want to go beyond what Postgres does...

Have you checked the linked documentation? I put the links in the commit message exactly because I wanted you to satisfy yourself this is indeed the case.

(Regarding the IF syntax. This syntax is not provided by PostgreSQL but as we discussed before it should be desugared to CASE, so the CASE semantics apply.)

**Comment by knz** [comment]
I fixed the broken links too.

**Comment by knz** [comment]
I'll merge this for now, we can fix further in separate PRs if needed.

**Pull request merged**
