### PR TITLE
De-emphasize follow-the-workload

### LINKED ISSUE #8450: Remove follow-the-workload demo
It's the default pattern for multi-region, but it's also an anti-pattern to use it on its own. We have a topology doc on this. We should remove the demo so as not to emphasize it too much.

### PR DESCRIPTION
**Pull request by jseldess**
- Remove follow-the-workload tutorial
- Update links to redirect to the ftw topology pattern doc

Fixes #8450.

### CODE REVIEW

**Review by yingzhuchin — APPROVED** [review]
LGTM

**Comment by jseldess** [comment]
@awoods187, ping

**Comment by awoods187** [comment]
LGTM cc @nvanbenschoten for awareness

**Comment by jseldess** [comment]
TFTR, @awoods187 and @yingzhuchin.

**Pull request merged**
