### PR TITLE
ALTER TABLE statement as multiple pages

### LINKED ISSUE #252: sql: ALTER TABLE statement
Complete reference documentation for the `ALTER TABLE` statement: alter-table.md

Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

More reference:
- https://github.com/cockroachdb/cockroach/blob/master/sql/alter_table.go
- https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/alter_table
- PostgreSQL: http://www.postgresql.org/docs/9.5/static/sql-altertable.html
- MySQL: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

### LINKED ISSUE #705: sql: CHECK constraint via ALTER TABLE VALIDATE and ALTER TABLE ADD CONSTRAINT
Implemented in [crdb pull 9152](https://github.com/cockroachdb/cockroach/pull/9152) and https://github.com/cockroachdb/cockroach/pull/9127; need to take care of term `VALIDATE` in both diagrams and documentation.

Related work in #607

### LINKED ISSUE #735: ADD COLUMN statement
This is a sub-statements of `ALTER TABLE`. Let's break it into its own page, as we've done for other sub-statements.

### LINKED ISSUE #736: ALTER COLUMN statement
This is a sub-statements of `ALTER TABLE`. Let's break it into its own page, as we've done for other sub-statements.

### LINKED ISSUE #737: sql: DROP COLUMN statement
This is a sub-statements of `ALTER TABLE`. Let's break it into its own page, as we've done for other sub-statements.

### LINKED ISSUE #738: sql: DROP CONSTRAINT statement
This is a sub-statements of `ALTER TABLE`. Let's break it into its own page, as we've done for other sub-statements.

### LINKED ISSUE #874: Split ALTER TABLE into subcommands
This may just be me being dumb, but this is a small issue I ran into today.

I wanted to look at the docs for renaming a column. Knowing that `RENAME COLUMN` is part of an `ALTER TABLE` statement, I first went to the `ALTER TABLE` docs and struggled to find a way to get to what I wanted, since there was no reference to `RENAME COLUMN` on the page at all. I instead had to find the separate page for it in the list on the left navigation bar.

There were two things could have improved my experience:

1. A reference from the `ALTER TABLE` page to the `RENAME COLUMN` page
2. Consistency around what's included in the `ALTER TABLE` syntax diagram. If I didn't know better and had just looked at that page, I might conclude that cockroach doesn't support renaming columns, because other `ALTER TABLE` subcommands such as `ADD/ALTER/DROP COLUMN` are all included there.

### PR DESCRIPTION
**Pull request by sploiselle**
Closes #874
Closes #738
Closes #737
Closes #736
Closes #735
Closes #705
Closes #252

#934 still open

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/950)

### CODE REVIEW

**Comment by jseldess** [comment]
Looks great overall. I'll review each new subcommand page in a bit, but just want to send over some initial, higher-level feedback.

---

Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[alter-table.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BS0D3Qc_CdQ3mtUEd:-K_BS0D3Qc_CdQ3mtUEe:b-opijii) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/alter-table.md#L7)):*
> ```Markdown
> ---
> 
> The `ALTER TABLE` [statement](sql-statements.html) applies a schema change to a table.
> ```

Since privileges and diagrams are covered on the pages for subcommands, I don't think we need to include those sections here. Ideally, this page would just give a basic intro and redirect users to the page for the specific subcommand they're interested in. Thoughts?

---

*[alter-table.md, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BRnKntl7DYA13JETw:-K_BRnKoWFJfVCjiU9VM:btxa9d1) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/alter-table.md#L21)):*
> ```Markdown
> The user must have the `CREATE` [privilege](privileges.html) on the table. 
> 
> ## Subcommands
> ```

Can you add `RENAME COLUMN` and `RENAME TABLE` as well? This was one problem Alex was having in https://github.com/cockroachdb/docs/issues/874. He expected to find `rename column` listed here. 

Are there any other subcommands to add?

---

*[sql-statements.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BSwk8e9mZJfRr29oN:-K_BSwk8e9mZJfRr29oO:bthdpah) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/sql-statements.md#L11)):*
> ```Markdown
> Statement | Usage 
> ----------|------------
> [`ADD COLUMN`](add-column.html) | Add columns to a table.
> ```

Please add these to the SQL Statements sidenav as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/950#-:-K_BSlU7V3ockEeh3hTj:b-2ghk3s)*

**Comment by jseldess** [comment]
@sploiselle, added some feedback  on the pages for specific subcommands. Again, looks excellent overall. Thanks!

---

Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[add-constraint.md, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BZi_d0suGTQ8YxDjx:-K_BZi_eaz0-tug1p9JM:bt02zql) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/add-constraint.md#L15)):*
> ```Markdown
> {{site.data.alerts.callout_info}}
> The <a href="default-value.html">Default</a> constraint is managed through <a href="alter-column.html"><code>ALTER COLUMN</code></a>.<br/><br/>
> The <a href="primary-key.html">Primary Key</a> constraint can only be applied through <a href="create-table.html"><code>CREATE TABLE</code></a>.
> ```

big nit: I think these can just be two contiguous sentences.

---

*[add-constraint.md, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_B_6wTxJqjE00N4qt2:-K_B_6wTxJqjE00N4qt3:b-r2vjsa) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/add-constraint.md#L34)):*
> ```Markdown
> | `table_name` | The name of the table containing the column you want to constrain. |
> | `name` | The name of the constraint, which must be unique to its table and follow these [identifier rules](keywords-and-identifiers.html#identifiers). |
> | `constraint_elem` | The [Check](check.html), [Foreign Keys](foreign-key.html), [Unique](unique.html) constraint you want to add. <br/><br/>Adding/changing a Default constraint is done through `ALTER COLUMN`. <br/><br/>Adding/changing the table's Primary Key is not supported through `ALTER TABLE`; it can only be specified during [table creation](create-table.html#create-a-table-primary-key-defined). |
> ```

`, or Unique constraint...`

Also, let's make `ALTER COLUMN` a link to that page.

---

*[add-constraint.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_B_TOKlCOUzyfh0AfX:-K_B_TOKlCOUzyfh0AfY:bvonghu) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/add-constraint.md#L36)):*
> ```Markdown
> | `constraint_elem` | The [Check](check.html), [Foreign Keys](foreign-key.html), [Unique](unique.html) constraint you want to add. <br/><br/>Adding/changing a Default constraint is done through `ALTER COLUMN`. <br/><br/>Adding/changing the table's Primary Key is not supported through `ALTER TABLE`; it can only be specified during [table creation](create-table.html#create-a-table-primary-key-defined). |
> 
> ## Examples
> ```

These example are clear, but it might be more helpful, especially to users not experienced with constraints, to fill in the context a bit more. What do you think?

---

*[alter-column.md, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BdAkSrL1RGJYqXNxO:-K_BdAkSrL1RGJYqXNxP:bant1f5) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/alter-column.md#L29)):*
> ```Markdown
> | `a_expr` | The new Default value you want to use. |
> 
> ## Examples
> ```

Same command as above. These example are clear, but it might be more helpful, especially to novice users, to fill in the context a bit more. What do you think?

---

*[drop-column.md, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BdpDqB9pdpEGXLNgc:-K_BdpDqB9pdpEGXLNgd:b-97neg8) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/drop-column.md#L28)):*
> ```Markdown
> | `RESTRICT` | *(Default)* Do not drop the column if any objects (such as [views](views.html)) depend on it. |
> 
> ## Examples
> ```

Same feedback as for examples on other pages. Perhaps we should provide a bit more context for each of these.

---

*[drop-constraint.md, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_Be6tBnteahB6HaIPM:-K_Be6tBnteahB6HaIPN:b-q0d7po) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/drop-constraint.md#L41)):*
> ```Markdown
> ~~~
> ~~~ sql
> > ALTER TABLE orders DROP CONSTRAINT fk_customer_ref_customers;
> ```

Can you show the response to this statement as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/950#-:-K_BeGhG_-GdibhK_SGm:b-1knalw)*

**Comment by sploiselle** [comment]
Review status: 0 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[add-constraint.md, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BZi_d0suGTQ8YxDjx:-K_GLtZhFMVYjXQiWuyt:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/add-constraint.md#L15)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

big nit: I think these can just be two contiguous sentences.
</blockquote></details>

Done.

---

*[add-constraint.md, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_B_6wTxJqjE00N4qt2:-K_GMPaUSORWSQhyHxsb:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/add-constraint.md#L34)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

`, or Unique constraint...`

Also, let's make `ALTER COLUMN` a link to that page.
</blockquote></details>

Done.

---

*[add-constraint.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_B_TOKlCOUzyfh0AfX:-K_GNF0EPCXRuWw9lAT3:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/add-constraint.md#L36)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

These example are clear, but it might be more helpful, especially to users not experienced with constraints, to fill in the context a bit more. What do you think?
</blockquote></details>

Done.

---

*[alter-column.md, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BdAkSrL1RGJYqXNxO:-K_GOvR3cZc0yyhzd-69:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/alter-column.md#L29)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Same command as above. These example are clear, but it might be more helpful, especially to novice users, to fill in the context a bit more. What do you think?
</blockquote></details>

Done.

---

*[alter-table.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BS0D3Qc_CdQ3mtUEd:-K_GOwpLJwQU8tTvapUa:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/alter-table.md#L7)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Since privileges and diagrams are covered on the pages for subcommands, I don't think we need to include those sections here. Ideally, this page would just give a basic intro and redirect users to the page for the specific subcommand they're interested in. Thoughts?
</blockquote></details>

Done.

---

*[alter-table.md, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BRnKntl7DYA13JETw:-K_GOxnP6N2xULG-EhHw:b-1dndxg) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/alter-table.md#L21)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Can you add `RENAME COLUMN` and `RENAME TABLE` as well? This was one problem Alex was having in https://github.com/cockroachdb/docs/issues/874. He expected to find `rename column` listed here. 

Are there any other subcommands to add?
</blockquote></details>

Had this change stashed. Thanks for catching it. I did do some digging since you asked and found `ALTER TABLE...SPLIT AT` which has some contention around whether or not it should be documented at all. Throwing it in the table with a brief description.

---

*[drop-column.md, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BdpDqB9pdpEGXLNgc:-K_GQ9YS6PQ_BTmwrz5A:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/drop-column.md#L28)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Same feedback as for examples on other pages. Perhaps we should provide a bit more context for each of these.
</blockquote></details>

Done.

---

*[drop-constraint.md, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_Be6tBnteahB6HaIPM:-K_GQI67ValOAUyf9qqx:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/drop-constraint.md#L41)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Can you show the response to this statement as well?
</blockquote></details>

Done.

---

*[sql-statements.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_BSwk8e9mZJfRr29oN:-K_GQJqK598NZQN_DWiR:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/74ce2dd2683458a514e184b0e1cdbd33e9c4dc9e/sql-statements.md#L11)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Please add these to the SQL Statements sidenav as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/950)*

**Comment by jseldess** [comment]
:lgtm:, with one final nit.

---

Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[alter-column.md, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_HNUkdeWSQudX1q30B:-K_HNUkdeWSQudX1q30C:b-dq8njw) ([raw file](https://github.com/cockroachdb/docs/blob/af26e391740d7a1d496fbfa9d179e83067242800/alter-column.md#L33)):*
> ```Markdown
> ### Set or Change a Default Value
> 
> Setting the [Default value constraint](default-value.html) inserts the value when data's written to the table without explicitly defining the value for the column. If the column already has Default value, you can use this statement to change it.
> ```

"If the column already has a Default value..."

---

*[alter-column.md, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_HNaYWvMFVSUORWfc3:-K_HNaYWvMFVSUORWfc4:b-78g3jb) ([raw file](https://github.com/cockroachdb/docs/blob/af26e391740d7a1d496fbfa9d179e83067242800/alter-column.md#L35)):*
> ```Markdown
> Setting the [Default value constraint](default-value.html) inserts the value when data's written to the table without explicitly defining the value for the column. If the column already has Default value, you can use this statement to change it.
> 
> The below example inserts the boolean value `true` whenever you inserted data to the `subscriptions` table without defining a value for the `newsletter` column.
> ```

boolean -> Boolean

Also, "...whenever you insert data..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/950#-:-K_HO4tKgYM_q7bKIqcA:bvoy7f2)*

**Comment by jseldess** [comment]
Reviewed 8 of 14 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/950)*

**Comment by sploiselle** [comment]
Review status: 14 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[alter-column.md, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_HNUkdeWSQudX1q30B:-K_KM-Y_gP0wyccIbnv2:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/af26e391740d7a1d496fbfa9d179e83067242800/alter-column.md#L33)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

"If the column already has a Default value..."
</blockquote></details>

Done.

---

*[alter-column.md, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/950#-K_HNaYWvMFVSUORWfc3:-K_KM54HPp74FtUEESMJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/af26e391740d7a1d496fbfa9d179e83067242800/alter-column.md#L35)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

boolean -> Boolean

Also, "...whenever you insert data..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/950)*

**Comment by sploiselle** [comment]
Thanks for the reviews over the holiday, @jseldess!

**Pull request merged**
