### PR TITLE
[prototype/WIP] widened side grid

### PR DESCRIPTION
**Pull request by j-low**
__[description]:__
* rough draft for what a widened site grid would appear as on docs

### CODE REVIEW

**Comment by j-low** [comment]
cc: @jseldess

**Comment by jseldess** [comment]
This is cool, @j-low. One quick comment: Instead of letting the main body expand to the right indefinitely, I think we want a max width. While we're doing this, we should move the page-level TOC to a right margin. @kuanluo  mocked this up a bit here: https://github.com/cockroachdb/docs/issues/2195#issuecomment-361985920

Some decent examples of using the right margin for page TOC:

- https://developers.google.com/identity/protocols/OAuth2
- https://valelint.github.io/docs/styles/#creating-a-style

**Comment by j-low** [comment]
@jseldess sure thing...there will be progressive updates to this PR.  I'll be working on that third column for the TOC next.

**Comment by jseldess** [comment]
For clarity, I'm closing this in favor of the more recent https://github.com/cockroachdb/docs/pull/3284.

**Pull request closed without merging**
