### PR TITLE
INT and FLOAT aliases

### LINKED ISSUE #1634: sql: Adding support for integral aliases
PR: https://github.com/cockroachdb/cockroach/pull/16548

### LINKED ISSUE #1661: sql: Adding support for int2, int8, float4 and float8 to be in line with postgres support of numerical types
PR: https://github.com/cockroachdb/cockroach/pull/16720

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #1634 
Fixes #1661

### CODE REVIEW

**Comment by jseldess** [comment]
@m-schneider, the issues we discussed are logged here: https://github.com/cockroachdb/cockroach/issues/19197.

**Comment by jseldess** [comment]
@m-schneider, any feedback on this?

**Comment by m-schneider** [comment]
:lgtm: I'll take a look at if we want to change some of this for 1.1.1

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1992#-:-Kw_ZEYrPmVO7fGHcRMb:b-q59ubu)*

**Comment by jseldess** [comment]
Thanks, @m-schneider.

**Pull request merged**
