### PR TITLE
Add note to 21.1.0-beta release notes

### PR DESCRIPTION
**Pull request by lnhsingh**

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @isaactwong)

___
*[_includes/v21.1/misc/beta-release-warning.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/10241#-MXZGy2BBziGRWyTJmyG:-MXZGy2C69w89tFsyG7f:bmlqkyv) ([raw file](https://github.com/cockroachdb/docs/blob/8e5f06a45086b1703cd4ac3ffb0bfccde65d13d4/_includes/v21.1/misc/beta-release-warning.md#L2)):*
> ```Markdown
> {{site.data.alerts.callout_danger}}
> Beta releases are not recommended for production use.
> ```

@isaactwong - Do we want to extrapolate to something like `Beta releases are not recommended for production use and could lead to data corruption, etc.`?

**Review by isaactwong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[_includes/v21.1/misc/beta-release-warning.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/10241#-MXZGy2BBziGRWyTJmyG:-MXZxA6N-wOtJ20Ak7VI:b-95j97o) ([raw file](https://github.com/cockroachdb/docs/blob/094d20b2424f17273b86fb6f8aa37d578b85701e/_includes/v21.1/misc/beta-release-warning.md#L2)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@isaactwong - Do we want to extrapolate to something like `Beta releases are not recommended for production use and could lead to data corruption, etc.`?
</blockquote></details>

I think adding data corruption makes sense. I think we could also identify cluster unavailability and/or performance issues as possibilities. Maybe we add a sentence or two highlighting what betas are intended for? Namely testing, experimentation, etc.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @isaactwong)

___
*[_includes/v21.1/misc/beta-release-warning.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/10241#-MXZGy2BBziGRWyTJmyG:-MXc135GBgjs9TsfPqf_:bemodkc) ([raw file](https://github.com/cockroachdb/docs/blob/094d20b2424f17273b86fb6f8aa37d578b85701e/_includes/v21.1/misc/beta-release-warning.md#L2)):*
<details><summary><i>Previously, isaactwong (Isaac T Wong) wrote…</i></summary><blockquote>

I think adding data corruption makes sense. I think we could also identify cluster unavailability and/or performance issues as possibilities. Maybe we add a sentence or two highlighting what betas are intended for? Namely testing, experimentation, etc.
</blockquote></details>

Updated - PTAL

**Review by isaactwong — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10241#-:-MXeSdXJ8D6q-jHKmy1f:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @isaactwong)

**Review by isaactwong — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10241#-:-MXeShUA5-EIu_B2TVLD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @isaactwong)

**Pull request merged**
