### PR TITLE
Document 2.1 rolling upgrade auto-finalization

### LINKED ISSUE #2996: Finalize upgrades automatically
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recfxL6QVy4FfFnA0
PM: @dianasaur323 
Eng Partner:

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #2996

### CODE REVIEW

**Comment by jseldess** [comment]
@windchan7, PTAL. @bdarnell or @tschottdorf might want to review as well.

**Comment by jseldess** [comment]
Note: Still need to update `v2.1/training/cluster-upgrade.md`.

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[v2.1/orchestrate-cockroachdb-with-kubernetes.md, line 341 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZXu-sEZH-96pb3Jdc:-LDZXu-sEZH-96pb3Jdd:b-noph8j) ([raw file](https://github.com/cockroachdb/docs/blob/7152b7bf3277d8d21ce1e14058a5046aa0ebc235/v2.1/orchestrate-cockroachdb-with-kubernetes.md#L341)):*
> ```Markdown
> {% include orchestration/kubernetes-upgrade-cluster.md %}
> 
> 4. If this was an upgrade between minor or major versions (e.g., between v1.0.x and v1.1.y or between v1.1.y and v2.0.z), then you'll want to [finalize the upgrade](upgrade-cockroach-version.html#finalize-the-upgrade) if you're happy with the new version. Assuming you upgraded to the v2.0 minor version, you'd run:
> ```

This should probably be replaced with a mention of the preserve_downgrade_option setting instead of being removed completely. 

---

*[v2.1/upgrade-cockroach-version.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZYFr-5aJU3_CsMaLw:-LDZYFr0DuRQezZrgfrL:bnq0idf) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L46)):*
> After finalization, however, it will no longer be possible to perform a rolling downgrade to v2.0.

Remove "rolling". After the upgrade is finalized it is not possible to downgrade at all, even if downtime is acceptable. 

> In the event of a catastrophic failure or corruption due to usage of new features requiring v2.1

Remove "new features requiring". Old features can have new bugs. 

---

*[v2.1/upgrade-cockroach-version.md, line 48 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZZaHvAUjk4OtURBOe:-LDZZaHvAUjk4OtURBOf:b9b9pqe) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L48)):*
> ```Markdown
> By default, as soon as all nodes are running the new version, the upgrade process will be **auto-finalized**. This will enable certain performance improvements and bug fixes introduced in v2.1. After finalization, however, it will no longer be possible to perform a rolling downgrade to v2.0. In the event of a catastrophic failure or corruption due to usage of new features requiring v2.1, the only option will be to start a new cluster using the old binary and then restore from one of the backups created prior to performing the upgrade.
> 
> If you want to preserve the ability to perform a rolling downgrade to v2.0 after upgrading all nodes to v2.1, turn off auto-finalization:
> ```

I think we should phrase this as a recommendation rather than a choice: "If you're reading these directions, we recommend disabling auto-finalization (but note that if you do this, you'll need to follow *all* of these directions including the manual finalization in step 5)"

---

*[v2.1/upgrade-cockroach-version.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZZ6wm74GBHdWIomfI:-LDZZ6wm74GBHdWIomfJ:byypghe) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L56)):*
> ```Markdown
>     {% include copy-clipboard.html %}
>     ~~~ sql
>     > SET CLUSTER SETTING cluster.preserve_downgrade_option = crdb_internal.node_executable_version();
> ```

I'd prefer to avoid documenting `crdb_internal.node_executable_version`. Just say `SET CLUSTER SETTING cluster.preserve_downgrade_option = '2.0'` (and then we'll have to update this for the 2.1-to-2.2 docs)

---

*[v2.1/upgrade-cockroach-version.md, line 61 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZY4H9Elq7QF02yFvc:-LDZY4H9Elq7QF02yFvd:b-vjj2zy) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L61)):*
> ```Markdown
>     The `crdb_internal.node_executable_version()` built-in function will set this setting to the current version running on the node, in this case v2.0.
> 
> ## Step 3. Perform the rolling upgrade
> ```

All the later steps need to be re-numbered. 

---

*[v2.1/upgrade-cockroach-version.md, line 186 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZ_K0fCesBy7BOdhGw:-LDZ_K0fCesBy7BOdhGx:bfxullz) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L186)):*
> ```Markdown
> After upgrading all nodes in the cluster, monitor the cluster's stability and performance and consider your next steps.
> 
> ### If you let the upgrade process auto-finalize
> ```

I'm not sure we need this section, since it's basically the same as the support section at the end. I'd go with something like:

Step 5. Finish the upgrade

If you disabled auto-finalization in step 3 above, monitor the stability and performance of your cluster for as long as you require to feel comfortable with the upgrade (generally at least a day). If during this time you decide to roll back the upgrade, simply repeat the rolling restart procedure with the old binary.

Once you are satisfied with the new version, [steps for `RESET CLUSTER SETTING cluster.preserve_downgrade_option`].

Step 6. Troubleshooting

If you are experiencing problems after the upgrade has finalized (whether manually or automatically), it is no longer possible to downgrade to the previous release (except by starting a new cluster and restoring from an old backup). [run debug zip and contact support...]

---

*[v2.1/upgrade-cockroach-version.md, line 194 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZbG5J95OhQ6mXAS-b:-LDZbG5J95OhQ6mXAS-c:by6r2p1) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L194)):*
> ```Markdown
>     2. [Reach out for support](support-resources.html) from Cockroach Labs, sharing your debug zip.
> 
>         In this case, it is not possible to perform a rolling downgrade to v2.0. In the event of a catastrophic failure or corruption due to usage of new features requiring v2.1, Cockroach Labs will help you start a new cluster using the old binary and then restore from one of the backups created prior to finalizing the upgrade.
> ```

Sneaking in a new support obligation here? :)  I wouldn't be so specific. We'll certainly help in cases like this, but that help may take the form of a new patch release to fix bugs rather than help with wiping and restarting a cluster. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3190)*

**Comment by jseldess** [comment]
Thanks for the feedback, @windchan7 and @bdarnell. I'll rework this content today.

**Comment by jseldess** [comment]
Review status: 1 of 4 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[v2.1/upgrade-cockroach-version.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZYFr-5aJU3_CsMaLw:-LE4oF5pCsgbH7y6kUsN:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L46)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> After finalization, however, it will no longer be possible to perform a rolling downgrade to v2.0.

Remove "rolling". After the upgrade is finalized it is not possible to downgrade at all, even if downtime is acceptable. 

> In the event of a catastrophic failure or corruption due to usage of new features requiring v2.1

Remove "new features requiring". Old features can have new bugs. 
</blockquote></details>

Done.

---

*[v2.1/upgrade-cockroach-version.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDJ7hZnHw-mJ1ZI71E2-r2-46:-LE4ydwR45AO8jUKeIA9:b-14yw67) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L46)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

`as soon as` is a strong promise. Generally the upgrade will happen immediately once all nodes are running the latest version. In a couple other cases like the cluster has dead but non-decommissioned nodes, the upgrade will not happen. Just to be clear, we might want to list them out as stated in the [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md). 

However, as long as operators didn't set `cluster.preserve_downgrade_option`, the auto upgrade code will retry until success. 
</blockquote></details>

I weakened the "as soon as" language. In the "Prepare to upgrade" step, we're already mentioning that all nodes should be live before starting the upgrade. I expanded that to say they should be live or decommissioned, and I explicitly called out that finalization won't be possible with dead, non-decommissioned nodes. 

Are there any other important cases not already called out in this doc?

---

*[v2.1/upgrade-cockroach-version.md, line 48 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZZaHvAUjk4OtURBOe:-LE4o_i62fdk9yO1QJ67:b-rcib5w) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L48)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think we should phrase this as a recommendation rather than a choice: "If you're reading these directions, we recommend disabling auto-finalization (but note that if you do this, you'll need to follow *all* of these directions including the manual finalization in step 5)"
</blockquote></details>

By saying "If you're reading these directions", do we mean to say, "If you are performing this upgrade manually instead of with a script"? 

Once Amruta finishes her systemd work for basic deployment, we'll move onto rolling upgrades, in which case we'll revisit how we present upgrade instructions.

---

*[v2.1/upgrade-cockroach-version.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZZ6wm74GBHdWIomfI:-LE4pVkV9yRgPXPhazoI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd prefer to avoid documenting `crdb_internal.node_executable_version`. Just say `SET CLUSTER SETTING cluster.preserve_downgrade_option = '2.0'` (and then we'll have to update this for the 2.1-to-2.2 docs)
</blockquote></details>

Done.

---

*[v2.1/upgrade-cockroach-version.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDJ7hZnHw-mJ1ZI71E2-r2-56:-LE4uyeyArUaSdacJCsz:byhwk7m) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L56)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

We might want to say `cluster.preserve_downgrade_option` can only be set to the current cluster version.
In addition, we also should point out that as long as `cluster.preserve_downgrade_option` is set, it's not possible
to run `set cluster setting version = XXX` manually.
</blockquote></details>

Added that you can only set this to the current version. I left out the bit about `set cluster setting version` because that setting isn't a part of upgrades at all anymore, and I don't want to confuse people. In fact, for 2.1 and beyond, shouldn't we disallow `SET CLUSTER SETTING version`?

---

*[v2.1/upgrade-cockroach-version.md, line 61 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZY4H9Elq7QF02yFvc:-LE4paFmAVe8bdQxhJHA:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L61)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

All the later steps need to be re-numbered. 
</blockquote></details>

Done.

---

*[v2.1/upgrade-cockroach-version.md, line 186 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZ_K0fCesBy7BOdhGw:-LE4uNvA1BVvJrduCrKT:b-qsvnoa) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L186)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not sure we need this section, since it's basically the same as the support section at the end. I'd go with something like:

Step 5. Finish the upgrade

If you disabled auto-finalization in step 3 above, monitor the stability and performance of your cluster for as long as you require to feel comfortable with the upgrade (generally at least a day). If during this time you decide to roll back the upgrade, simply repeat the rolling restart procedure with the old binary.

Once you are satisfied with the new version, [steps for `RESET CLUSTER SETTING cluster.preserve_downgrade_option`].

Step 6. Troubleshooting

If you are experiencing problems after the upgrade has finalized (whether manually or automatically), it is no longer possible to downgrade to the previous release (except by starting a new cluster and restoring from an old backup). [run debug zip and contact support...]
</blockquote></details>

Done. PTAL.

---

*[v2.1/upgrade-cockroach-version.md, line 194 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZbG5J95OhQ6mXAS-b:-LE4uRdoDm_chH_1H66X:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L194)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Sneaking in a new support obligation here? :)  I wouldn't be so specific. We'll certainly help in cases like this, but that help may take the form of a new patch release to fix bugs rather than help with wiping and restarting a cluster. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3190)*

**Comment by windchan7** [comment]
Review status: 1 of 4 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[v2.1/upgrade-cockroach-version.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDJ7hZnHw-mJ1ZI71E2-r2-46:-LE544fq1KlHXjtLQuJc:bxhaoal) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L46)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I weakened the "as soon as" language. In the "Prepare to upgrade" step, we're already mentioning that all nodes should be live before starting the upgrade. I expanded that to say they should be live or decommissioned, and I explicitly called out that finalization won't be possible with dead, non-decommissioned nodes. 

Are there any other important cases not already called out in this doc?
</blockquote></details>

Dead and non-decommissioned nodes will prevent the auto upgrade but I'm not sure if it will prevent manual upgrade. I actually don't think it will prevent manual upgrade and it should behave as it used to be.

---

*[v2.1/upgrade-cockroach-version.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDJ7hZnHw-mJ1ZI71E2-r2-56:-LE55VM_8dPtReudGoKS:bxbxuuf) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L56)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Added that you can only set this to the current version. I left out the bit about `set cluster setting version` because that setting isn't a part of upgrades at all anymore, and I don't want to confuse people. In fact, for 2.1 and beyond, shouldn't we disallow `SET CLUSTER SETTING version`?
</blockquote></details>

We talked about disabling `SET CLUSTER SETTING version` in the RFC discussion but I don't think it's a settled thing. Maybe Ben want to confirm? @bdarnell.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3190)*

**Comment by jseldess** [comment]
*[v2.1/upgrade-cockroach-version.md, line 46 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDJ7hZnHw-mJ1ZI71E2-r2-46:-LEAAKG-BLJWpR5HWJx6:bi5kapj) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L46)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

Dead and non-decommissioned nodes will prevent the auto upgrade but I'm not sure if it will prevent manual upgrade. I actually don't think it will prevent manual upgrade and it should behave as it used to be.
</blockquote></details>

Victor and I discussed in a different channel. Basically, in 2.1, the manual process is just a delayed auto-finalization. Once the user is comfortable and ready to finalize, they run `RESET CLUSTER SETTING cluster.preserve_downgrade_option;`. We don't mention the "old" command anymore. Given that, dead and non-decommissioned nodes will get in the way even in the manual case. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3190)*

**Comment by jseldess** [comment]
*[v2.1/orchestrate-cockroachdb-with-kubernetes.md, line 341 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZXu-sEZH-96pb3Jdc:-LEAJrHw8d9eYOnp3lmC:bli39tm) ([raw file](https://github.com/cockroachdb/docs/blob/7152b7bf3277d8d21ce1e14058a5046aa0ebc235/v2.1/orchestrate-cockroachdb-with-kubernetes.md#L341)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This should probably be replaced with a mention of the preserve_downgrade_option setting instead of being removed completely. 
</blockquote></details>

Done. PTAL. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3190)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v2.1/upgrade-cockroach-version.md, line 48 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDZZaHvAUjk4OtURBOe:-LEALX-G75X2ENM4DwsC:bghgiye) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L48)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

By saying "If you're reading these directions", do we mean to say, "If you are performing this upgrade manually instead of with a script"? 

Once Amruta finishes her systemd work for basic deployment, we'll move onto rolling upgrades, in which case we'll revisit how we present upgrade instructions.
</blockquote></details>

No, I literally meant "if you're reading these directions" as opposed to just doing things on your own (or trying to do a 2.0-to-2.1 upgrade in the same way as a 2.0.x-to-2.0.y upgrade). IMHO auto-finalization is a safety net for people who don't read the directions, while any reasonably careful admin would want to preserve the ability to downgrade for at least a few days. 

---

*[v2.1/upgrade-cockroach-version.md, line 56 at r2](https://reviewable.io/reviews/cockroachdb/docs/3190#-LDJ7hZnHw-mJ1ZI71E2-r2-56:-LEAMM3zAJmimbOwIZs8:b8c8vm6) ([raw file](https://github.com/cockroachdb/docs/blob/36040a84912a3e2298aad6a4530edaa2be42c4d2/v2.1/upgrade-cockroach-version.md#L56)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

We talked about disabling `SET CLUSTER SETTING version` in the RFC discussion but I don't think it's a settled thing. Maybe Ben want to confirm? @bdarnell.
</blockquote></details>

I think we probably want to disable `SET CLUSTER SETTING version` and manage it solely through resetting the `preserve_downgrade_option` setting. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3190#-:-LEAMfflC0gtjeYtOM2j:bnfp4nl)*

**Pull request merged**
