### PR TITLE
Add release notes for v20.1.13

### LINKED ISSUE #8933: v20.1.13 Release notes
Prep date: 3/8/21
Release date: 3/15/21
SHA: `<add>`
Release Manager: <add>
Issue: <add>

[Docs To Do](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs):

- [ ] Run script to generate release notes
- [ ] Update docs site
- [ ] Edit release notes - Additions/changes/omissions to the release notes should be left in this issue's comments
- [ ] Once PR is merged / release notes are live, notify @meagan-g in the #releases Slack channel
- [ ] Email releases@ with link to published release notes
- [ ] Generate release notes issues (cc @lnhsingh)

### PR DESCRIPTION
**Pull request by mikeCRL**
Resolves #8933.

### CODE REVIEW

**Comment by mikeCRL** [comment]
@ajwerner Following up, here's updated draft text on the other items we discussed, excerpted from this PR. Ryan is reviewing on the Docs Team side, but please let me know if you want to change anything. Thanks again.

> - Fixed a bug where high-latency global clusters could sometimes fall behind in [resolving timestamps for changefeeds](../v20.1/create-changefeed.html#messages). [#60926][#60926]

> - In the DB Console's Advanced Debugging section, manually enqueueing a range to the garbage collection (GC) queue now properly respects the SkipShouldQueue option. This ensures that you can force the GC of a specific range. [#60746][#60746]

**Comment by ajwerner** [comment]
LGTM

**Review by taroface — APPROVED** [review]
Suggestions on one item. Otherwise LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9975#-:-MVbLwPaAebLPIVK_Sav:b-5radl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[releases/v20.1.13.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/9975#-MVbLYUWCDTUbUI25i7y:-MVbLYUWCDTUbUI25i7z:bcqxbnc) ([raw file](https://github.com/cockroachdb/docs/blob/954be9c19016f2682216475527f90638c434e3cc/releases/v20.1.13.md#L38)):*
> ```Markdown
> - Fixed a bug where high-latency global clusters could sometimes fall behind in [resolving timestamps for changefeeds](../v20.1/create-changefeed.html#messages). [#60926][#60926]
> - Creating [interleaved](../v20.1/interleave-in-parent.html) partitioned indexes is now disallowed. Previously, the database would crash when trying to create one. Note that [interleaved tables will be deprecated altogether](../v20.2/interleave-in-parent.html#convert-interleaved-tables-to-non-interleaved-tables) in a future release. [#61423][#61423]
> - In the DB Console's Advanced Debugging section, manually enqueueing a range to the garbage collection (GC) queue now properly respects the SkipShouldQueue option. This ensures that you can force the GC of a specific range. [#60746][#60746]
> ```

A few suggestions: 

In -> On

Advanced Debugging -> Advanced Debug page

Link to the corresponding page: https://www.cockroachlabs.com/docs/v20.1/admin-ui-debug-pages.html

SkipShouldQueue should probably have code ticks.

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mikeCRL)

___
*[releases/v20.1.13.md, line 38 at r2](https://reviewable.io/reviews/cockroachdb/docs/9975#-MVbLYUWCDTUbUI25i7y:-MVbM2UU1QCjQ6GVO33n:bk3zjcl) ([raw file](https://github.com/cockroachdb/docs/blob/954be9c19016f2682216475527f90638c434e3cc/releases/v20.1.13.md#L38)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

A few suggestions: 

In -> On

Advanced Debugging -> Advanced Debug page

Link to the corresponding page: https://www.cockroachlabs.com/docs/v20.1/admin-ui-debug-pages.html

SkipShouldQueue should probably have code ticks.
</blockquote></details>

Oh, also, that page calls it the Admin UI, which we renamed to DB Console in v20.2. Not sure if you think it's better to use the current name or stay consistent with the v20.1 naming.

**Comment by mikeCRL** [comment]
@ajwerner & @taroface: Thanks for the super quick review.

**Comment by mikeCRL** [comment]
@taroface
- I went with "Advanced debugging" because that's the title once you get to the page, although the nav has it as "Advanced debug". It's a UI quirk that makes it hard to document, but the true page title seems better to use than the nav, so I'll lean toward keeping it as-is unless you feel strongly that it's worth changing it.
- I also used "SkipShouldQueue" without backticks to match the UI. Again, a UI quirk: the label in the UI should've been changed to prose, but it's code-like. Wasn't sure which way to go on the code formatting. I agree that it at least looks wrong not to have it. I've now added it.
- Good call on the Admin UI term. Thanks for that context. Edited to say: 
  `- In the Advanced Debugging section of the Admin UI (DB Console),`...

**Pull request merged**
