### PR TITLE
SET TIME ZONE and SHOW TIME ZONE

### LINKED ISSUE #496: SET TIMEZONE statement
Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

### LINKED ISSUE #681: SHOW TIME ZONE

### PR DESCRIPTION
**Pull request by jseldess**
This PR completes docs on the `SET TIME ZONE` and `SHOW TIME ZONE` statements. 

@knz, PTAL and let me know if any additional level of details is required re: timezone. Also let me know if you have ideas for additional examples.

HTML versions:
- [`SET TIME ZONE`](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7a68042c8596d24dccab88b57806185e576ddf50/set-time-zone.html)
- [`SHOW TIME ZONE`](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7a68042c8596d24dccab88b57806185e576ddf50/show-time-zone.html)

Fixes #496 
Fixes #681

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/680)

### CODE REVIEW

**Comment by jseldess** [comment]
@paperstreet , @mjibson, I updated `SET TIME ZONE` docs to recommend setting the time zone explicitly in timestamp values.

**Comment by knz** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[set-database.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgCg0B3Ip8WwuckVBF:-KSgCg0CnuAO1dgS3mFx:bx2qy37) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-database.md#L9)):*
> ```Markdown
> The `SET DATABASE` [statement](sql-statements.html) sets the default database for the current session. When connected to the default database, you don't need to reference it explicitly in statements.
> 
> {{site.data.alerts.callout_danger}}In rare cases, CockroachDB may reset session configurations, so it's most reliable to set the database in the client's connection string. For examples in different languages, see <a href="build-a-test-app.html">Build a Test App</a>.{{site.data.alerts.end}}
> ```

I'm not sure where this information comes from but it's partly wrong. 

As long as a connection is alive the session information will be preserved. 
What does happen however sometimes is that a driver (including our own command-line utility `cockroach sql` which has an embedded driver) sometimes will decide the server is taking too long to respond and the driver then spontaneously decides to drop the connection it already has an open a new one; *or* a node is restarted and the driver decides to reconnect. When this happens, any setting made using SET by the application *but not known to the driver* will be lost. Moral of the story: tell the driver what you are doing with SET. Using the database name in the conn string achieves this for "SET DATABASE"; each driver may or may not provide additional ways to inform it which other settings were modified.

Now I get that you are trying to make the life of users using `cockroach sql` easy and try to hide this complexity from them. Then I would recommend you create a new tech issue to request that the CLI sql utility informs the user every time the connection is lost that their custom settings via SET have been lost too and must be re-issued.

---

*[set-time-zone.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgH1s7zg9YESidho8U:-KSgH1s8uRXbNsMn1Y5M:b-q64pkt) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-time-zone.md#L9)):*
> ```Markdown
> The `SET TIME ZONE` [statement](sql-statements.html) sets the default time zone for the current session.  
> 
> {{site.data.alerts.callout_danger}}In rare cases, CockroachDB may reset session configurations, so it's most reliable to set the time zone as an explicit part of a <a href="timestamp.html"><code>TIMESTAMP</code></a> or <a href="timestamp.html"><code>TIMESTAMPTZ</code></a> value.{{site.data.alerts.end}}
> ```

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/680)*

**Comment by jseldess** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[set-database.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgCg0B3Ip8WwuckVBF:-KShJm9irvvxgUSrtrWY:b-peexg0) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-database.md#L9)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I'm not sure where this information comes from but it's partly wrong. 
> 
> As long as a connection is alive the session information will be preserved. 
> What does happen however sometimes is that a driver (including our own command-line utility `cockroach sql` which has an embedded driver) sometimes will decide the server is taking too long to respond and the driver then spontaneously decides to drop the connection it already has an open a new one; *or* a node is restarted and the driver decides to reconnect. When this happens, any setting made using SET by the application *but not known to the driver* will be lost. Moral of the story: tell the driver what you are doing with SET. Using the database name in the conn string achieves this for "SET DATABASE"; each driver may or may not provide additional ways to inform it which other settings were modified.
> 
> Now I get that you are trying to make the life of users using `cockroach sql` easy and try to hide this complexity from them. Then I would recommend you create a new tech issue to request that the CLI sql utility informs the user every time the connection is lost that their custom settings via SET have been lost too and must be re-issued.
</details>
Revised the warning to clarify that the driver reconnecting is the cause of the session settings getting cleared. Look ok, @knz?

---

*[set-time-zone.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgH1s7zg9YESidho8U:-KShK2ed-C429kyJQz8k:bfcoez) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-time-zone.md#L9)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> See above.
</details>
Revised. Look ok?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/680)*

**Comment by knz** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[set-database.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgCg0B3Ip8WwuckVBF:-KShMYI1ykBAV99tTyJ_:b-rp4n9g) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-database.md#L9)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Revised the warning to clarify that the driver reconnecting is the cause of the session settings getting cleared. Look ok, @knz?
</details>
yep that's ok (I also still think the cli sql client should warn/inform the user when a connection is dropped though)

---

*[set-time-zone.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgH1s7zg9YESidho8U:-KShMedUVUY57VznnLNC:bebt8b4) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-time-zone.md#L9)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Revised. Look ok?
</details>
yes! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/680#-:-KShMgOyO0WaHlsPoAoO:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[set-database.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/680#-KSgCg0B3Ip8WwuckVBF:-KShOkSxkGDeWjPat2a2:bh7n2cn) ([raw file](https://github.com/cockroachdb/docs/blob/7a68042c8596d24dccab88b57806185e576ddf50/set-database.md#L9)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> yep that's ok (I also still think the cli sql client should warn/inform the user when a connection is dropped though)
</details>
I agree, @knz. I'll open an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/680)*

**Pull request merged**
