### PR TITLE
CC automatic coupon codes updates

### LINKED ISSUE #8755: Update CC docs to reference automatic coupon codes
We are planning to release automatic coupon codes soon. With this change, users will not have to input any information to get a free trial, it will just be applied so long as their selected configs are eligible. See [mocks](https://www.figma.com/file/wJVvSWjJr1FlWnLCGLWFFK/cc-coupon-codes?node-id=340%3A67) for context.

On the docs side we should:
1. Update the quickstart guide to remove references to CRDB30 and update language to talk about your "free trial" instead of codes
2. Update the "create your cluster" docs to remove references to CRDB30 and to add a note about the automatic free trial
3. Add an FAQ section to the FAQ page for "How do free trials work?"

--- Drafted copy for the FAQ, feel free to edit ---
**How do your free trials work?**
CockroachCloud offers a 30-day free trial so you can test the product without paying. Free trials require a credit card so we can validate that you are not a bot and provide a seamless transition into production. Free-trials apply when you:

- Create the first cluster in your organization
- Select 4 or fewer nodes (we recommend starting with 3 so you can try scaling)
- Don't remove the pre-applied trial code at check out

Once the 30-day period is over, your trial cluster can be scaled beyond 4 nodes. You can create other paid clusters at any time. If Cockroach Labs has provided you with additional codes, you can use those on applicable clusters. For extended trial options, [talk to our team](https://www.cockroachlabs.com/contact-sales/).

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Closes #8755

### CODE REVIEW

**Comment by emily-horing** [comment]
LGTM thanks!

**Comment by emily-horing** [comment]
cc @poojamaniar we can update the link in the UI to go straight to the "How do free trials work" section

**Review by rmloveland — APPROVED** [review]
LGTM

**Comment by poojamaniar** [comment]
@emily-horing will update as soon as this PR gets merged, and I can get a link to the section

**Comment by Amruta-Ranade** [comment]
The PR is ready to be merged but I can't merge it until the feature's available to all customers. Go ahead and add the link to the UI, @poojamaniar

**Comment by poojamaniar** [comment]
Link is updated here: https://github.com/cockroachlabs/managed-service/pull/4243

**Pull request merged**
