### PR TITLE
WIP: draft documentation for roles.

### PR DESCRIPTION
**Pull request by mberhault**
This is far from finished, just the bare-minimum guidance to use roles.

### CODE REVIEW

**Comment by mberhault** [comment]
@BramGruneir: this should give you the user-level explanation of roles, including all existing statements, required permissions and enterprise enforcement.

**Comment by jseldess** [comment]
Thank you, @mberhault! Let me know when you're ready for us to take this over.

**Comment by mberhault** [comment]
Will do. The new commit is a bit premature (the corresponding PR isn't merged), but after that, it's most of the user-visible changes. The rest is optimization and some tables in `information_schema`. I can probably clarify a few more things, but it's getting there.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/pull/2814. Thanks for laying the groundwork, @mberhault!

**Pull request closed without merging**
