### PR TITLE
Added Licensing FAQs

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
To-Do: Update licensing terminology in the rest of the docs

### CODE REVIEW

**Comment by knz** [comment]
note: some of the suggestions i've made in the additional faqs mention the phrase "please contact us". I recommend that the doc page contains a link to a contact form or some more details about _how_ to contact us.

**Comment by piyush-singh** [comment]
We should link to our support channel (link: https://support.cockroachlabs.com/hc/en-us). Alternatively, if we feel that is too specific, we can link to the general contact page (https://www.cockroachlabs.com/contact/), but I would recommend the first option to avoid having requests in many different channels.

**Comment by knz** [comment]
So a friend and I were trying to find this FAQ on the web site and we were stumped: it is not listed in the side bar alongside the other FAQs. Where can we find it?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
I also used the "license" keyword with the search function and couldn't find anything.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Amruta-Ranade** [comment]
@knz 
Here's the link: https://www.cockroachlabs.com/docs/stable/licensing-faqs.html

**Comment by knz** [comment]
So thank you for the link, that helps.

Meanwhile I find the page difficult to find:

- if I open the docs site on my mobile browser, it does not appear listed in the main table of contents (which I assume corresponds to the sidebar)
- the search function does not list it under the keyword "license"

Maybe there are ways to increase its discoverability?

**Comment by Amruta-Ranade** [comment]
You'd have to navigate to FAQs > Licensing FAQs on the sidebar nav. As for search, I remember a convo about indexing taking time after a page is published, but I could be misremembering. cc @jseldess

**Comment by knz** [comment]
So starting later today the mobile version of the site I was getting on my phone was eventually updated. I think I was hitting an outdated version from cloudflare or something. Now the page is easy to discover. Thank you again!

**Pull request merged**
