### PR TITLE
Data deletion details for CockroachCloud

### LINKED ISSUE #9277: Add details on how to request data deletion to docs
Users have requested to remove profile information from CC, including credit card details and email associations. We should add information in docs on how to do this, so it's clear what users' options are.

1. Delete your SQL user (self-service) - deletes your user and any permissions they had on the cluster/databases
2. Delete your cluster (self-service) - deletes all the data in the cluster, backups are deleted after a period (I think ~30 days)
3. Delete your organization (self-service) - deletes all the clusters within your organization, removes the association between email accounts 
4. Remove your credit card (support ticket) - we keep a card on file even when a user deletes their organization so we can process pending charges. Users can request the card be removed once their charges are settled through a ticket
5. Remove your email address (support ticket) - we don't currently allow users to delete their accounts self-service. To remove record of a user's email they can create a support ticket and we can scrub their account record.

cc @aaron-crl for visibility. This is in response to customers requesting data removal in the past month, but I think it puts us in a slightly better position for GDPR to have a clear process here.

### PR DESCRIPTION
**Pull request by gemma-shay**
Admin Tasks on Console Access Management Page
-add delete your organization instructions
-add remove an email address instructions
-add remove a credit card instructions

Cluster Management Page
-add warning that free tier clusters may be deleted after 6 months of no activity

User Authorization Page
-instructions to delete a SQL user were already present. no changes needed.

Closes #9277 and #9767

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/cluster-management.md, line 100 at r2](https://reviewable.io/reviews/cockroachdb/docs/9824#-MU9_afO3h8Us-dnBwg0:-MU9_afO3h8Us-dnBwg1:b-2uuy3s) ([raw file](https://github.com/cockroachdb/docs/blob/421fb6c1067b693fe8a75f1f42f2da20b7eaabc3/cockroachcloud/cluster-management.md#L100)):*
> ```Markdown
> 
> {{site.data.alerts.callout_danger}}
> Deleting a cluster will delete all cluster data. CockroachCloud Free (beta) clusters are subject to deletion after 6 months of no activity.
> ```

Should this be a separate (note) callout? I'm not sure-- thoughts? My thinking is that it's a separate note that isn't really related to the first sentence
___
*[cockroachcloud/console-access-management.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/9824#-MU9_-QiAYiM9iFZagPp:-MU9_-QiAYiM9iFZagPq:b-152xib) ([raw file](https://github.com/cockroachdb/docs/blob/421fb6c1067b693fe8a75f1f42f2da20b7eaabc3/cockroachcloud/console-access-management.md#L92)):*
> ```Markdown
> #### Delete an email address
> 
> This is not currently an option in the Console. To remove the record of an email address, [contact Support](https://support.cockroachlabs.com).
> ```

Suggested wording: `This is not currently available through the Console. To remove an email address from your account, [...]`

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @lnhsingh)

___
*[cockroachcloud/cluster-management.md, line 100 at r2](https://reviewable.io/reviews/cockroachdb/docs/9824#-MU9_afO3h8Us-dnBwg0:-MU9e6Fo3nUDx7DQ02cS:bgog06o) ([raw file](https://github.com/cockroachdb/docs/blob/421fb6c1067b693fe8a75f1f42f2da20b7eaabc3/cockroachcloud/cluster-management.md#L100)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Should this be a separate (note) callout? I'm not sure-- thoughts? My thinking is that it's a separate note that isn't really related to the first sentence
</blockquote></details>

Agree. Is two warnings right next to each other okay?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/cluster-management.md, line 100 at r2](https://reviewable.io/reviews/cockroachdb/docs/9824#-MU9_afO3h8Us-dnBwg0:-MU9efvR7uo4CH0NTN5q:b-60gaey) ([raw file](https://github.com/cockroachdb/docs/blob/421fb6c1067b693fe8a75f1f42f2da20b7eaabc3/cockroachcloud/cluster-management.md#L100)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Agree. Is two warnings right next to each other okay?
</blockquote></details>

Yeah, two next to each other is ok. You could also make the new callout an info one, so it's a different color. I'm not sure it needs to be a warning

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[cockroachcloud/cluster-management.md, line 100 at r2](https://reviewable.io/reviews/cockroachdb/docs/9824#-MU9_afO3h8Us-dnBwg0:-MU9iIxu5B71Rae6D7Ee:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/421fb6c1067b693fe8a75f1f42f2da20b7eaabc3/cockroachcloud/cluster-management.md#L100)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Yeah, two next to each other is ok. You could also make the new callout an info one, so it's a different color. I'm not sure it needs to be a warning
</blockquote></details>

Done.
___
*[cockroachcloud/console-access-management.md, line 92 at r2](https://reviewable.io/reviews/cockroachdb/docs/9824#-MU9_-QiAYiM9iFZagPp:-MU9iJTy8UPzD4ddkFWs:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/421fb6c1067b693fe8a75f1f42f2da20b7eaabc3/cockroachcloud/console-access-management.md#L92)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Suggested wording: `This is not currently available through the Console. To remove an email address from your account, [...]`
</blockquote></details>

Done.

**Review by lnhsingh — COMMENTED** [review]
:lgtm: - I think a review from @emily-horing would be good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9824#-:-MU9ppNB3E8tSirGHSPo:bif9low)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Review by emily-horing — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9824)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh)

**Comment by emily-horing** [comment]
LGTM!

**Comment by emily-horing** [comment]
whoops sorry didn't mean to close on your behalf

**Pull request merged**
