### PR TITLE
Clarify table locality behavior on 'Choosing' page

### PR DESCRIPTION
**Pull request by rmloveland**

### CODE REVIEW

**Review by awoods187 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10542)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

**Comment by awoods187** [comment]
LGTM

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10542)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/choosing-a-multi-region-configuration.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/10542#-M_VhLzcExos40opj487:-M_VhLzdEl4x0peGHC6D:b-nd5jjo) ([raw file](https://github.com/cockroachdb/docs/blob/e7068f809931781f496c33c4d82ca9e66133dd81/v21.1/choosing-a-multi-region-configuration.md#L25)):*
> ```Markdown
>   - Zone survival (the default).
>   - For [global tables](multiregion-overview.html#global-tables), low-latency reads from all regions.
>   - For [regional by row tables](multiregion-overview.html#regional-by-row-tables), low-latency reads and writes from each row's [home region](set-locality.html#crdb_region), and low-latency [follower reads](follower-reads.html) from all other regions.
> ```

Should we be mentioning REGIONAL BY TABLE here too?

**Review by rmloveland — COMMENTED** [review]
Thanks for the review Andy!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10542#-:-M_VsGp32BlSnGzwILvR:b-6rb1xt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[v21.1/choosing-a-multi-region-configuration.md, line 25 at r1](https://reviewable.io/reviews/cockroachdb/docs/10542#-M_VhLzcExos40opj487:-M_VrQGcC8NjnwxiHdTz:bvqgcfn) ([raw file](https://github.com/cockroachdb/docs/blob/e7068f809931781f496c33c4d82ca9e66133dd81/v21.1/choosing-a-multi-region-configuration.md#L25)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should we be mentioning REGIONAL BY TABLE here too?
</blockquote></details>

I didn't mention it b/c this is the "change locality" case but the default is already REGIONAL BY TABLE, and we also link to the lengthy description of table localities above so I didn't want to repeat too much about REGIONAL BY TABLE again

**Comment by rmloveland** [comment]
Hey I forgot about this while on vaca - I'm gonna merge it b/c I think it's an improvement over the existing text

Feel free to shout at me later if needed :-)

**Pull request merged**
