### PR TITLE
Update CC sign up link with referral ID

### PR DESCRIPTION
**Pull request by jseldess**
This will help us attribute new CC strats to docs.

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
LGTM!

**Review by laurenbarker — APPROVED** [review]
URLs LGTM!

> Reviewed 6 of 8 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8913#-:-MM2cGTY6ysh5uaXER9Y:b7dzk7q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @emily-horing and @jseldess)

___
*[_includes/v20.1/app/start-cockroachdb.md, line 41 at r2](https://reviewable.io/reviews/cockroachdb/docs/8913#-MM2bEqh8rSa7NdtPsjE:-MM2bEqh8rSa7NdtPsjF:b-g3qehj) ([raw file](https://github.com/cockroachdb/docs/blob/d5a1fdc2447db6c644870438602b6fc82b15051d/_includes/v20.1/app/start-cockroachdb.md#L41)):*
> ```Markdown
> ### Create a free cluster
> 
> 1. If you haven't already, <a href="https://cockroachlabs.cloud/signup?referralId=docs">sign up for a CockroachCloud account</a>.
> ```

I'm not sure what the difference between markdown link syntax (`[link text](url)`) and an anchor tag is in this context, but the way it is now, the link will redirect the user to the CC site instead of opening it in a new tag. Is that the intended experience?

The alternative with the anchor tag would be:
```html
<a href="https://cockroachlabs.cloud/signup?referralId=docs" rel="noopener" target="_blank">
```

**Comment by laurenbarker** [comment]
___
*[_includes/v20.1/app/start-cockroachdb.md, line 41 at r2](https://reviewable.io/reviews/cockroachdb/docs/8913#-MM2bEqh8rSa7NdtPsjE:-MM2cZy5AAzjD9wlN8Zl:b-d0rzuu) ([raw file](https://github.com/cockroachdb/docs/blob/d5a1fdc2447db6c644870438602b6fc82b15051d/_includes/v20.1/app/start-cockroachdb.md#L41)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

I'm not sure what the difference between markdown link syntax (`[link text](url)`) and an anchor tag is in this context, but the way it is now, the link will redirect the user to the CC site instead of opening it in a new tag. Is that the intended experience?

The alternative with the anchor tag would be:
```html
<a href="https://cockroachlabs.cloud/signup?referralId=docs" rel="noopener" target="_blank">
```
</blockquote></details>

new tab*

**Comment by jseldess** [comment]
___
*[_includes/v20.1/app/start-cockroachdb.md, line 41 at r2](https://reviewable.io/reviews/cockroachdb/docs/8913#-MM2bEqh8rSa7NdtPsjE:-MM2ejxEDAZ7o-pJVpWT:b-9tlmkz) ([raw file](https://github.com/cockroachdb/docs/blob/d5a1fdc2447db6c644870438602b6fc82b15051d/_includes/v20.1/app/start-cockroachdb.md#L41)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

new tab*
</blockquote></details>

TFTR, @laurenbarker! 

With the docs redesign, we will more programmatically open external links in new tabs, but for now, I've used your recommended approach. Thank you!

**Pull request merged**
