### PR TITLE
DOC-4801 DOC-5458 decom metrics and graphs

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: DOC-4801, DOC-5458, DOC-5580

- Added 24 new decommissioning observability metrics
- Updated related decom obs graphs in the DB Console:
	- **Snapshot Data Received**: updated with additional new metrics
	- **Receiver Snapshots Queued**: new
	- **Replicate Queue Actions: Successes**: new
	- **Replicate Queue Actions: Failures**: new
	- **Decommissioning Errors**: new

Questions:

- Should the following metrics indicate that they are rates? Current descriptions suggest instead: running counters since process start. Or maybe, as metrics, they are counters, but when graphed, they become rates as measured against the user-selected timeslice of the graph? I ask because: shortly after v22.2 GA, DOCS will begin populating all metrics exclusively from `_admin/v1/chartcatalog`: descriptions found there will be presented to our users verbatim, so desired updates to metric descriptions will need to take place upstream, not in DOCs:
	- `range.snapshots.rebalancing.rcvd-bytes` | Number of rebalancing snapshot bytes received
	- `range.snapshots.rebalancing.sent-bytes` | Number of rebalancing snapshot bytes sent
	- `range.snapshots.recovery.rcvd-bytes` | Number of recovery snapshot bytes received
	- `range.snapshots.recovery.sent-bytes` | Number of recovery snapshot bytes sent
- Did I guess right that the **Decommissioning Errors** graphs tracks the `queue.replicate.replacedecommissioningreplica.error` metric; same metric as also shown on the **Replicate Queue Actions: Failures** graph? Maybe it sums with `queue.replicate.removedecommissioningreplica.error` as well?
- The linked GDOC in the description to DOC-4801 includes mention of some log filename and log entry type changes (e.g., the new `cockroach-kv-distribution.log` logfile). I couldn't find anything seemingly related in Jira in the DOCS project, nor do any of the child tickets to CRDB - 10792 seem to address this either. Can you point me in the right direction? Maybe the PRs you merged related to this change? Thank you!

Notes:

- 8 metrics have the word `replica` duplicated in the description: `curl -s http://localhost:8080/_admin/v1/chartcatalog | grep 'replica replica'`. I've edited the description here in the docs, but please file a bugfix for CRDB as you can: as mentioned, DOCS will be populating metrics exclusively from engineering's own descriptions as surfaced in `chartcatalog` very soon!

Staging:

- [ui-replication-dashboard.md](https://deploy-preview-15516--cockroachdb-docs.netlify.app/docs/v22.2/ui-replication-dashboard#snapshot-data-received) | [metric-names.md](https://deploy-preview-15516--cockroachdb-docs.netlify.app/docs/v22.2/ui-custom-chart-debug-page.html#available-metrics)

### CODE REVIEW

**Comment by andf-crl** [comment]
@Santamaura Friendly ping on this PR, we'd like to get GA docs live for GA. Feel free to send off to another engineer if preferred. Thanks much!

**Review by Santamaura — COMMENTED** [review]
> Should the following metrics indicate that they are rates?

These are indeed rates.

>Did I guess right that the Decommissioning Errors graphs tracks the queue.replicate.replacedecommissioningreplica.error metric; same metric as also shown on the Replicate Queue Actions: Failures graph? Maybe it sums with queue.replicate.removedecommissioningreplica.error as well?

Yes both graphs use that metric the difference being that `Decommissioning Errors` shows replaced errors / sec per node (e.g. a 3 node cluster will have 3 series on the graph)

> The linked GDOC in the description to DOC-4801 includes mention of some log filename and log entry type changes (e.g., the new cockroach-kv-distribution.log logfile). I couldn't find anything seemingly related in Jira in the DOCS project, nor do any of the child tickets to CRDB - 10792 seem to address this either. Can you point me in the right direction? Maybe the PRs you merged related to this change? Thank you!

@alextalks will know the answer to this I believe.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15516#-:-NI40ozf80IjqmUD5ojW:bp3zqtu)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andf-crl — COMMENTED** [review]
Thanks @Santamaura, I've updates docs copy descriptions to indicate that these metrics are rates.

I've created https://github.com/cockroachdb/cockroach/issues/92925 for engineering to update the metrics descriptions themselves.

Let's leave the log question for another time. Is this PR good to go for GA? Thanks much!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/15516#-:-NIIsL4h6L2hcw2XeMW7:b-wi2bcf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andf-crl** [comment]
@Santamaura friendly ping on this review please.

**Review by Santamaura — APPROVED** [review]
👍

**Review by MichaelTrestman — APPROVED** [review]
LGTM
Great screenshots!

**Comment by andf-crl** [comment]
Thanks folks.

**Pull request merged**
