### PR TITLE
--insecure deprecation announcement; --socket update

### LINKED ISSUE #8396: --socket has been removed
PR: https://github.com/cockroachdb/cockroach/pull/53405

From release notes:
> The command-line flag `--socket` has been removed. It was deprecated since v20.1. Use `--socket-dir` instead. [#53405][#53405] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8397: --insecure marked as deprecated
PR: https://github.com/cockroachdb/cockroach/pull/53405

From release notes:
> The command-line flag `--insecure` has been marked as deprecated. See [issue #53404](https://go.crdb.dev/issue/53404) for details. The flag will be removed in a later version in a staged fashion: first, additional security mechanisms will be added to enable more flexible deployments which were previously done using `--insecure`; then the flag will be removed from server commands; then finally, in a later version, also from client commands. [#53405][#53405] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by taroface**
Fixes #8397.
Fixes #8396.

- For `--insecure`, adds a v21.1 deprecation announcement to the `cockroach start` parameters table and in a callout at the top of many deployment tutorials that use `--insecure`.

cc @jseldess in case you have suggestions on other places where this information should go.

### CODE REVIEW

**Review by jseldess — APPROVED** [review]
:lgtm: with a few nits.

I do think there are some other insecure tutorials we need to address:

- All of the TPC-C benchmarking instructions:http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/performance-benchmarking-with-tpc-c-10-warehouses.html
    - These should just be converted to secure, but I don't know how hard that will be for some of the large-scale cases. @rmloveland, will you be updating these tutorials as part of the performance page update? If so, perhaps you could look into making these secure-only. If not, Ryan can just add the disclaimer.
- The insecure performance tuning tutorial: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/performance-tuning-insecure.html
    - I'd be fine removing the insecure version. But the safe approach is to just add the disclaimer for now. 
- All of the insecure hello world tutorials: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/build-a-go-app-with-cockroachdb.html#insecure
    - I'd like to change all of these to use cockroach demo or CC anyway, so please ignore these for now.
- Local docker deploys are insecure: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/start-a-local-cluster-in-docker-mac.html
    - I'd be fine just converting this page to secure or putting on the disclaimer.
- A bunch of our local cluster tutorials: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/demo-replication-and-rebalancing.html
   - Let me see if I can quickly convert most of these to secure. Otherwise, we can put your disclaimer in place. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417#-:-MHTmyx0EwDS6oND53XZ:bfune2q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @taroface)

___
*[v20.2/cockroach-start.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHTlprd0UUIMwia4Mjc:-MHTlprd0UUIMwia4Mjd:b-rtxpwf) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/cockroach-start.md#L91)):*
I don't find "internal testing" here and "internal use" elsewhere very clear. I'd suggest a formulation more like:

> The `--insecure` flag is intended for non-production testing only.
___
*[v20.2/deploy-cockroachdb-on-aws-insecure.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHTmnac4dVm7bh--YOA:-MHTmnac4dVm7bh--YOB:bvi02xo) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/deploy-cockroachdb-on-aws-insecure.md#L18)):*
> ```Markdown
> If you plan to use CockroachDB in production, we strongly recommend using a secure cluster instead. Select **Secure** above for instructions.
> 
> {{site.data.alerts.callout_danger}}
> ```

In addition to the slight language tweak mentioned above, I think we should make this callout an include file.

**Review by knz — COMMENTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jseldess, @knz, and @taroface)

___
*[v20.1/cockroach-start.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHl8BSlAS86ydgSd-6r:-MHl8BSlAS86ydgSd-6s:bx09h2j) ([raw file](https://github.com/cockroachdb/docs/blob/c7ab8b5f8b801ca8a472032325e8d3be8212ee15/v20.1/cockroach-start.md#L202)):*
> ```Markdown
> `clusterID` | The ID of the cluster.<br><br>When trying to join a node to an existing cluster, if this ID is different than the ID of the existing cluster, the node has started a new cluster. This may be due to conflicting information in the node's data directory. For additional guidance, see the [troubleshooting](common-errors.html#node-belongs-to-cluster-cluster-id-but-is-attempting-to-connect-to-a-gossip-network-for-cluster-another-cluster-id) docs.
> `nodeID` | The ID of the node.
> `socket` | <span class="version-tag">New in v20.1:</span> If the `--socket-dir` flag specifies a directory on which to listen for Unix domain socket connections, this field lists the name of the socket file.
> ```

I'm sorry I did not catch this the first time around. The `--socket` flag was already deprecated in v20.1.

What was new then was `--socket-dir` (a separate flag).
___
*[v20.1/cockroach-start.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHl8Gmh1s3twHMk_Wcx:-MHl8Gmh1s3twHMk_Wcy:bi20mud) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.1/cockroach-start.md#L202)):*
> ```Markdown
> `clusterID` | The ID of the cluster.<br><br>When trying to join a node to an existing cluster, if this ID is different than the ID of the existing cluster, the node has started a new cluster. This may be due to conflicting information in the node's data directory. For additional guidance, see the [troubleshooting](common-errors.html#node-belongs-to-cluster-cluster-id-but-is-attempting-to-connect-to-a-gossip-network-for-cluster-another-cluster-id) docs.
> `nodeID` | The ID of the node.
> `socket` | **Deprecated.** If the `--socket-dir` flag specifies a directory on which to listen for Unix domain socket connections, this field lists the name of the socket file.
> ```

In v20.2, the flag is removed altogether.

The flag `--socket-dir` is absolutely not deprecated and should be documented individually.
___
*[v20.2/cockroach-start.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHTlprd0UUIMwia4Mjc:-MHl8QwDCM0WDvWwWlbZ:b-qgto8n) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/cockroach-start.md#L91)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

I don't find "internal testing" here and "internal use" elsewhere very clear. I'd suggest a formulation more like:

> The `--insecure` flag is intended for non-production testing only.
</blockquote></details>

agree with jesse
___
*[v20.2/cockroach-start.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHl8UhNCH49nPIspYmV:-MHl8UhNCH49nPIspYmW:bu48g3q) ([raw file](https://github.com/cockroachdb/docs/blob/c7ab8b5f8b801ca8a472032325e8d3be8212ee15/v20.2/cockroach-start.md#L202)):*
> ```Markdown
> `clusterID` | The ID of the cluster.<br><br>When trying to join a node to an existing cluster, if this ID is different than the ID of the existing cluster, the node has started a new cluster. This may be due to conflicting information in the node's data directory. For additional guidance, see the [troubleshooting](common-errors.html#node-belongs-to-cluster-cluster-id-but-is-attempting-to-connect-to-a-gossip-network-for-cluster-another-cluster-id) docs.
> `nodeID` | The ID of the node.
> `socket` |  If the `--socket-dir` flag specifies a directory on which to listen for Unix domain socket connections, this field lists the name of the socket file.
> ```

see my comment above

**Review by taroface — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jseldess, @knz, and @taroface)

___
*[v20.1/cockroach-start.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHl8Gmh1s3twHMk_Wcx:-MHlXjY0Dcc-t13njpwW:b-il2gq7) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.1/cockroach-start.md#L202)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

In v20.2, the flag is removed altogether.

The flag `--socket-dir` is absolutely not deprecated and should be documented individually.
</blockquote></details>

Hey @knz, I think this is aligned with what I've done in this PR. `--socket` (above) is marked as deprecated in v20.1, and `--socket-dir` has remained untouched. Let me know if I'm still missing something.

**Review by knz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jseldess and @taroface)

___
*[v20.1/cockroach-start.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHl8Gmh1s3twHMk_Wcx:-MHlZdC5BhwkYnekSt3i:bcthri2) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.1/cockroach-start.md#L202)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Hey @knz, I think this is aligned with what I've done in this PR. `--socket` (above) is marked as deprecated in v20.1, and `--socket-dir` has remained untouched. Let me know if I'm still missing something.
</blockquote></details>

You know what, I simply did not read the diff right. You are absolutely right. My apologies for the noise.

**Review by taroface — COMMENTED** [review]
@jseldess TFTR! I have added the `--insecure` callout to each doc except for:

- TPC-C benchmarking instructions (awaiting @rmloveland feedback)
- Local cluster tutorials e.g. `demo-replication-and-rebalancing.md` (your last item)

I also went ahead and added it to the insecure hello world tutorials, because it only took one addition to the include used by all of these (`before-you-begin.md`). I can revert if you want.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417#-:-MHlsyTUBdHYh1GxgnHI:b-3b68o2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jseldess, @knz, and @taroface)

___
*[v20.2/cockroach-start.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHTlprd0UUIMwia4Mjc:-MHlqTUi3avK-PUSoYPB:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/cockroach-start.md#L91)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

agree with jesse
</blockquote></details>

Done.
___
*[v20.2/deploy-cockroachdb-on-aws-insecure.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/8417#-MHTmnac4dVm7bh--YOA:-MHlrKcIDFPcw8guRbMU:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/d51e4675f82dec61bb1a1d491ab17fd631e04e09/v20.2/deploy-cockroachdb-on-aws-insecure.md#L18)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

In addition to the slight language tweak mentioned above, I think we should make this callout an include file.
</blockquote></details>

Done.

**Review by rmloveland — COMMENTED** [review]
>  @rmloveland, will you be updating these tutorials as part of the performance page update? If so, perhaps you could look into making these secure-only. If not, Ryan can just add the disclaimer.

Yes I am planning to update these with the latest benchmark results.

Suggest adding the disclaimer for now - "update all the perf pages to secure" is kinda unplanned work which I hesitate to commit to since I don't understand  (but will look into and might just do if it's easy).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417#-:-MHpvmJz9ZU56gH3Nvzw:bkvzrh5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jseldess, @knz, and @taroface)

**Review by jseldess — APPROVED** [review]
Thanks, Rich. Fine to leave the tpc-c docs insecure for 20.1. Not high priority.

@taroface, can you please add the disclaimer to those pages?

Thanks for making the other updates. :lgtm: once the performance pages have the disclaimer. I'll continue working on the local cluster tutorials.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8417#-:-MHq9-TJ68Ps8QflKupu:bur17jo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jseldess, @knz, and @taroface)

**Pull request merged**
