### PR TITLE
add subheadings for each group of functions

### PR DESCRIPTION
**Pull request by dt**
this makes the generated TOC at the top include quick links to e.g. all the functions that return strings

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/386)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[generate/funcs.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/386#-KKKIc70pqsBQTa5lhDU:-KKKIc70pqsBQTa5lhDV:-912270106) ([raw file](https://github.com/cockroachdb/docs/blob/7c1d2636eacfb9453f70596bbcd6bd524dfe3cce/generate/funcs.go#L178)):*
> ```Go
> 	b := new(bytes.Buffer)
> 	for _, ret := range rets {
> 		fmt.Fprintf(b, "### %s Functions\n\nFunction | Return\n", ret)
> ```

How about making this two Fprintfs? I think that's clearer than the double newlines in the middle of a string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/386)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[generate/funcs.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/docs/386#-KKKIc70pqsBQTa5lhDU:-KKKJtVg5SohWlxAmT9l:-499146009) ([raw file](https://github.com/cockroachdb/docs/blob/7c1d2636eacfb9453f70596bbcd6bd524dfe3cce/generate/funcs.go#L178)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> How about making this two Fprintfs? I think that's clearer than the double newlines in the middle of a string.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/386)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/386#-:-KKKLP5Od06kbUDqbUbb:1417088721)*

**Comment by jseldess** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/386#-:-KKKPqWBrhUah_aVxAup:1417088721)*

**Pull request merged**
