### PR TITLE
Add docs on SHOW DEFAULT PRIVILEGES FOR GRANTEE

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-8483 and DOC-8017

### CODE REVIEW

**Comment by rmloveland** [comment]
@annrpom asking for your review since you are the author of https://github.com/cockroachdb/cockroach/pull/107953

**Review by annrpom — APPROVED** [review]
I have no complaints - lgtm!

**Review by taroface — APPROVED** [review]
LGTM, and thanks for handling one of my 23.2 features with this!

Btw, maybe worth linking "privileges" to https://www.cockroachlabs.com/docs/v23.1/security-reference/authorization#privileges? Up to you.

**Comment by rmloveland** [comment]
TFTRs!

> LGTM, and thanks for handling one of my 23.2 features with this!

thanks! and np!

> Btw, maybe worth linking "privileges" to https://www.cockroachlabs.com/docs/v23.1/security-reference/authorization#privileges? Up to you.

Done

**Pull request merged**
