### PR TITLE
Clean up getting started and add demo pages for core cockroach features

### PR DESCRIPTION
**Pull request by jseldess**
@spencerkimball, @petermattis, I've changed the approach. This PR now cleans up the existing getting started pages and adds new pages for demonstrating core cockroach features via a local cluster. The demo pages are listed in the new **Explore Core Features** section of **Get Started**. 

At this point, I've completed a draft only for the **[Fault Tolerance and Recovery](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7b89fbfaec928af9b8e37b5fc8a80c4d21afdcdf/demo-fault-tolerance-and-recovery.html)** demo. I'd like feedback on that before I dive into the others. 

@jess-edwards, @sploiselle, @dianasaur323, please chime in as well. 

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/834)

### CODE REVIEW

**Comment by jseldess** [comment]
@spencerkimball, @petermattis: I've also been thinking about keeping the Start a Local Cluster page the same and adding a new page to the **Get Started** section where we demonstrate surviving node failure and perhaps strong consistency (using manual overlapping transactions from different sql shells) and a few other topics. Would this be worth exploring as an alternative approach, and, if so, do you have ideas for other demonstrations we could do with a local cluster?

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo-fault-tolerance-and-recovery.md, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/834#-KWDjS6_zMVygdHZFAW9:-KWDjS6_zMVygdHZFAWA:b-yr6wy7) ([raw file](https://github.com/cockroachdb/docs/blob/cd3802b956a6f4af828ee198408bb50a52d4671d/demo-fault-tolerance-and-recovery.md#L83)):*
> ```Markdown
> ## Step 4. Verify that the cluster remains available
> 
> Open the built-in SQL shell on node 1 (port `26258`) or node 3 (port `26259`):
> ```

Node 1 is port 26257. 

---

*[demo-fault-tolerance-and-recovery.md, line 214 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/834#-KWDjdKxB91CTq0ex3u5:-KWDjdKxB91CTq0ex3u6:b-7vo6tj) ([raw file](https://github.com/cockroachdb/docs/blob/cd3802b956a6f4af828ee198408bb50a52d4671d/demo-fault-tolerance-and-recovery.md#L214)):*
> ```Markdown
> ## Step 7. Verify that the rejoined node has caught up
> 
> Open the SQL shell on the rejoined node 2 (port `26258`) and check for the `startrek` data that was added while the node was offline:
> ```

This doesn't really verify that the rejoined node has caught up - node 2 is acting as a proxy to one of the other nodes at this point. It's catching up in the background, but until it's caught up (and probably even for a time afterwards), it won't be used and so you won't be able to tell whether it's caught up. A better (but longer) demonstration of fault tolerance would be to take each node down in turn and issue an insert each time so that no node was up for all of the inserts. 

---

*[demo-fault-tolerance-and-recovery.md, line 245 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/834#-KWDkA9ENWDIFNJzMSuJ:-KWDkA9FMpThOTFWwVxx:b-prs8jk) ([raw file](https://github.com/cockroachdb/docs/blob/cd3802b956a6f4af828ee198408bb50a52d4671d/demo-fault-tolerance-and-recovery.md#L245)):*
> ```Markdown
> ~~~
> 
> As you see, despite being offline when the update happened, node 2 was updated soon after it rejoined the cluster.
> ```

"updated soon after" sounds like if you were quick enough, you could see the old data before node 2 caught back up. That isn't the case (and this is an important property of cockroachdb!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/834#-:-KWDkuLY41yYaA58zokb:bnfp4nl)*

**Comment by jseldess** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo-fault-tolerance-and-recovery.md, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/834#-KWDjS6_zMVygdHZFAW9:-KWDqVYbLCLr2kMXSMhB:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/cd3802b956a6f4af828ee198408bb50a52d4671d/demo-fault-tolerance-and-recovery.md#L83)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Node 1 is port 26257. 
</details>
Done.

---

*[demo-fault-tolerance-and-recovery.md, line 214 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/834#-KWDjdKxB91CTq0ex3u5:-KWDsPaEgc37IR5AGyO_:b-38ilyo) ([raw file](https://github.com/cockroachdb/docs/blob/cd3802b956a6f4af828ee198408bb50a52d4671d/demo-fault-tolerance-and-recovery.md#L214)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This doesn't really verify that the rejoined node has caught up - node 2 is acting as a proxy to one of the other nodes at this point. It's catching up in the background, but until it's caught up (and probably even for a time afterwards), it won't be used and so you won't be able to tell whether it's caught up. A better (but longer) demonstration of fault tolerance would be to take each node down in turn and issue an insert each time so that no node was up for all of the inserts. 
</details>
Thanks for calling this out, @bdarnell. I've revised the explanation to clarify these points. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/834)*

**Comment by jseldess** [comment]
At @spencerkimball's suggestion, I've removed "Strong Consistency" as a local cluster demo. For the others, here's the plan we talked through. @spencerkimball, let me know if I'm missing anything:

**Data Replication**

1. Start with 1 node.
2. Write data.
3. Add 2 more nodes and watch replication via admin ui.
4. Take a node down.
5. Update zone config to replicate 5 ways.
6. Add 2 more nodes.
7. Watch replication via admin ui.

**Scalability**

1. Create 3 nodes
2. Lower max range size in default zone config, e.g., `echo 'range_max_bytes: 65536' | cockroach zone set .default -f -`
3. Use some type of load generator that creates a schema and loads it. Something like photos app. We need to generate enough data to result in multiple ranges. @knz, does this sound like something you could help with? Might it be possible to make this a part of `cockroach gen`?
4. Watch ranges increas in admin ui.
5. When nodes are filling up, add 2 more nodes.
6. Watch rebalancing in admin ui.
 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/834#-:-KWDtQ287WzVf3W8ZORt:bqkmrq3)*

**Comment by jseldess** [comment]
@spencerkimball, @jess-edwards, since I got the technical LGTM from Ben, and since this PR includes some general cleanup to the other getting started tutorials, I'd like to merge and handle the other two demos (as well as putting a better narrative in place across all three) in follow-up PRs. Is that OK? I've put a few key trackers in place to see how far users make it through the fault tolerance demo.

**Comment by jess-edwards** [comment]
@jseldess LGTM. 

Per our discussion, we can create the narrative from these docs after these docs are merged. No need for the narrative to hold up this PR.

**Comment by jseldess** [comment]
Thanks, @jess-edwards. I created an issue to work out the narrative for all of these, as well as issues for the other tutorials:
- https://github.com/cockroachdb/docs/issues/858
- https://github.com/cockroachdb/docs/issues/857
- https://github.com/cockroachdb/docs/issues/856

Also, I added google tags to track key events in the fault tolerance tutorial: 
1. Adding a bunch of data while one node is down temporarily.
2. Adding a fourth node in preparation for removing another node permanently.

These events should tell us whether users are completing the tutorial.

**Comment by jseldess** [comment]
Fixes #855

**Pull request merged**
