### PR TITLE
Auto generate sitemap

### PR DESCRIPTION
**Pull request by mjibson**

### CODE REVIEW

**Comment by bdarnell** [comment]
What is the URL of the generated sitemap? I can add it to the webmaster console.

**Comment by mjibson** [comment]
It will be cockroachlabs.com/docs/sitemap.xml once @jseldess pushes the new build up.

**Comment by jseldess** [comment]
Pushed new build to dreamhost server. `sitemap.xml` is there now. 

http://www.cockroachlabs.com/docs/sitemap.xml

**Comment by bdarnell** [comment]
Google's parser complains about the use of relative urls in the sitemap; looks like these need to be changed to absolute.

**Comment by mjibson** [comment]
I think we can add some options to our _config.yml to have it do that: https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml#L3.

**Comment by jseldess** [comment]
Yep, I think this is fixed by adding `url: http://cockroachlabs.com` to `_config.yml`. Please take a look at PR #75.

**Comment by jseldess** [comment]
@bdarnell, just pushed back up to dreamhost. `sitemap.xml` now has absolute urls. Can you check again?

**Comment by bdarnell** [comment]
OK, submitted the new sitemap and it looks like it's working. We should start to see some results later today.

**Comment by jseldess** [comment]
Nice. Results are already better. Thanks, Ben.

**Pull request merged**
