### PR TITLE
Link data types to functions and operators

### PR DESCRIPTION
**Pull request by Tawishi**
Addresses #1870 
@jseldess Please review the changes and suggest more, if needed.

### CODE REVIEW

**Comment by Tawishi** [comment]
Can _decimal, float, int_ types be linked to _maths and numeric_ functions and operators?

**Review by jseldess — COMMENTED** [review]
This is great. Thank you, @tawishi. Just two requests:

1. Please apply the same changes to the v20.2 docs as well.
2. Perhaps we should add a "Functions" section to both the `UUID` and `INT` pages, both linking to: `functions-and-operators.html#id-generation-functions`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8701#-:-MK1SmV631mE1CWCRSsi:b-4znxom)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by Tawishi** [comment]
> This is great. Thank you, @Tawishi. Just two requests:
> 
> 1. Please apply the same changes to the v20.2 docs as well.
> 2. Perhaps we should add a "Functions" section to both the `UUID` and `INT` pages, both linking to: `functions-and-operators.html#id-generation-functions`?

I have made the necessary changes in v20.2 also. Please review and suggest changes, if needed.

**Comment by Tawishi** [comment]
@jseldess Why is the ```TeamCity build``` failing ?

**Pull request closed without merging**
