### PR TITLE
Add description of covering indexes

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes DOC-389 / #6127

### CODE REVIEW

**Comment by rmloveland** [comment]
Hey @andreimatei any objections to this change?  Would love to merge this week before my PTO next week if possible

(Once we're ok with the language I will put it in the v21.1 docs also)

**Comment by rmloveland** [comment]
@andreimatei does this change adding "covering indexes" look ok ?  let me know if you have objections / want edits

**Review by rafiss — APPROVED** [review]
lgtm! should it be copied to other releases' docs?

**Comment by rmloveland** [comment]
> should it be copied to other releases' docs?

yes!  copied the changes (with slight modifications) to v21.1 as well.  Didn't bother going back further since <= v20.2 is [out of maintenance support](https://www.cockroachlabs.com/docs/releases/release-support-policy.html) and likely less important for SEO purposes too

**Comment by rmloveland** [comment]
@ericharmeling sorry to bother, any objections to merging this one?

**Review by ericharmeling — APPROVED** [review]
So sorry for the delay on this. Looks great!!

**Pull request merged**
