### PR TITLE
Formatting cleanup on insert.md

### LINKED ISSUE #3128: Page layout oddities on INSERT docs
On https://www.cockroachlabs.com/docs/stable/insert.html I'm seeing two bits of weirdness:

There seems to be a spurious extra internal scroll bar:
screen shot 2018-05-08 at 12 24 47 pm

If I scroll around the version selector doesn't move, so it overlaps other content:
screen shot 2018-05-08 at 12 25 43 pm

Happening to me on both Firefox and Chrome on OS X.

### PR DESCRIPTION
**Pull request by jseldess**
Fixes #3128

### CODE REVIEW

**Comment by jseldess** [comment]
@couchand, @benesch, I'm hoping these minor changes solve the problem you were seeing. Can you please check the test site and let me know?

**Comment by benesch** [comment]
Yeah, fixes it for me!

**Comment by jseldess** [comment]
OK, great, @benesch. Merging. @couchand, please check the live page post-merge and let me know how things look.

**Comment by couchand** [comment]
@jseldess yep, this fixed the first issue (the extra scroll bar).

The other issue is still there.  It looks like one of the SQL railroad diagrams is wider than the page.  If you scroll to the right the version selector doesn't move, even though the rest of the navigation bar does.

**Pull request merged**
