### PR TITLE
Add docs re: controlling leaseholder location

### LINKED ISSUE #2966: Policies for controlling leaseholder location
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/reclZqRmshwJNaq4S
PM: @awoods187 
Eng Partner: @a-robinson

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #2966.

Summary of changes:

- Revised the intro section to use more lists for easier scanning of the
  features of replication zones.

- Added a new *Overview* section below the introduction which describes
  how replication zones work at a high level.  Most of this information
  comes from the old intro.  Since the new intro is now a list of
  features, it made sense to break this "how it works" content into a
  separate section for users who've scanned the list of features and
  decided they wish to read more.

- Updated the *Replication Zone Format* table to include the
  `lease_preferences` field and its description.

- Added a new example, *Constrain leaseholders to specific datacenters*,
  which shows the config file syntax and how to pass the file to
  CockroachDB.

### CODE REVIEW

**Comment by rmloveland** [comment]
Direct link to changes:

http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b12654c1d51f45b55d306a7d426c15b3cd40971c/dev/configure-replication-zones.html

@a-robinson I rewrote the intro to make it easier for me to understand (since I had never looked at zone configs before), but I am also open to moving that change to another PR if you would prefer this change to stick to describing the new `lease_preferences` field and showing an example of its use.

**Comment by rmloveland** [comment]
@Amruta-Ranade FYI I have a lot of conflicts to fix on this one - removing you as reviewer for now, will add you back when I push fixes

@a-robinson sorry for the noise on this one, thanks again for the review

**Comment by rmloveland** [comment]
@a-robinson FYI the only new change is to use the new `ALTER ... CONFIGURE ZONE` syntax instead of the old YAML config files.  I tested it on a local cluster so I'm fairly confident in it but feel free to shout if you would like it updated, of course.

**Comment by jseldess** [comment]
___
*[_includes/v2.1/zone-configs/constrain-leaseholders-to-specific-datacenters.md, line 9 at r4](https://reviewable.io/reviews/cockroachdb/docs/3850#-LPd-2rsDJD4nQrAITIS:-LPdChWm076KXpeOtl9I:bir274w) ([raw file](https://github.com/cockroachdb/docs/blob/288e74e2fe281bb3a3ff88f2cec28900d89f9128/_includes/v2.1/zone-configs/constrain-leaseholders-to-specific-datacenters.md#L9)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Because you can put multiple constraints within each inner bracket, e.g.:

```
lease_preferences: '[[+zone=us-east-1b, +ssd], [+zone=us-east-1a], [+zone=us-east-1c, +ssd]]
```

That would first prefer nodes with an ssd in us-east-1b, then any nodes in us-east-1b, then nodes in us-east-1c with an ssd.
</blockquote></details>

Ah, ok. That makes sense. I don't see that format/flexibility described anywhere. @rmloveland, you might want to work it into the `lease_preferences` description under `Replication zone variables`.

**Pull request merged**
