### PR TITLE
Add basic Hibernate example.

### PR DESCRIPTION
**Pull request by jordanlewis**
Following the example of the other two ORM examples.

`Sample.java` must be placed inside of the
`src/main/java/com/cockroachlabs/` directory. `hibernate.cfg.xml` must
be placed inside of the `src/main/resources` directory. Run `gradle run`
to run the sample application.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1096)

### CODE REVIEW

**Comment by cuongdo** [comment]
LGTM

Are the errors intelligible if the files aren't put in the right places? Also, @jseldess, do we have to have a ZIP version of this (with the right directory structure) for easy download?

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctWKU-5jXKzdUGgW2q:-KctWKU-5jXKzdUGgW2r:blgrxgx) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L38)):*
> ```Java
>         }
> 
>         public Account() {}
> ```

is this needed? (sorry if this is a newb Java question)

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctVyLfubPE5M8H06NE:-KctVyLgZQbgEML_p0cO:b-m4evak) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L49)):*
> ```Java
>             Account accountTwo = new Account(2, 250);
>             session.beginTransaction();
>             session.save(accountOne);
> ```

can you inline `new Account(...)` here to make this more consistent with the other ORM examples?

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctWTSKvUObn7TNJs10:-KctWTSKvUObn7TNJs11:b-exrn06) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L57)):*
> ```Java
>             query.select(query.from(Account.class));
>             for (Account account : session.createQuery(query).getResultList()) {
>                 System.out.println(String.format("%d %d", account.id, account.balance));
> ```

It's more concise to use `System.out.printf` with a `\n` at the end of the string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-:-KctY2TiX7A6g5pnwY2v:b-5laggk)*

**Comment by jordanlewis** [comment]
The errors will be mostly intelligible. You'll get a `could not find or load main class com.cockroachlabs.Sample` or a `could not locate cfg.xml resource [hibernate.cfg.xml]`.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctWKU-5jXKzdUGgW2q:-KctYmiFgk-0vAxRgk0X:b-hfms3i) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L38)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

is this needed? (sorry if this is a newb Java question)
</blockquote></details>

Yeah you need a no-arg constructor for Hibernate to be able to do its thing. I left the other one in for convenience in creating the accounts.

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctVyLfubPE5M8H06NE:-KctYrrI2E0piwn5FHI9:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L49)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

can you inline `new Account(...)` here to make this more consistent with the other ORM examples?
</blockquote></details>

Done.

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctWTSKvUObn7TNJs10:-KctYtKIl_jqqRo8PAJP:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L57)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

It's more concise to use `System.out.printf` with a `\n` at the end of the string
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-:-KctZPj7d6meOz5sHtpZ:bngcv7g)*

**Comment by jordanlewis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[_includes/app/hibernate-basic-sample/Sample.java, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-KctWKU-5jXKzdUGgW2q:-KctZxMf002r6SlqfP1T:b-u3cd6o) ([raw file](https://github.com/cockroachdb/docs/blob/425e8a65ecffb09e1c19a32a498952a981eb8fc9/_includes/app/hibernate-basic-sample/Sample.java#L38)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah you need a no-arg constructor for Hibernate to be able to do its thing. I left the other one in for convenience in creating the accounts.
</blockquote></details>

Added a comment explaining this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1096)*

**Comment by jseldess** [comment]
LGTM as well. I agree that a zip, in addition to the raw files, would be great. Then we could display the files on page but give users the ability to download the zip with the directory structure already in place. @jordanlewis, can you add a zip with the directory structure set like we want it? 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-:-KcxQy5doBs8-pn_xJ-1:b-ecvp85)*

**Comment by jordanlewis** [comment]
Added the zip.

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1096#-:-KcxT_Jm5JceZFHUpHLa:bfly875)*

**Pull request merged**
