### PR TITLE
JDBC compatible URLS and `cockroach convert-url`

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes: #11516, #11515

- Added JDBC compatible urls to the standard output for `cockroach start` and `cockroach start-single-node`. It was already updated for `cockroach demo`.
- Added `cockroach convert url` section to the **Connection parameters** page and a note linking to it on the `cockroach sql` page.

### CODE REVIEW

**Comment by gemma-shay** [comment]
@ericharmeling any idea on that error?

**Comment by ericharmeling** [comment]
> any idea on that error?

https://cockroachlabs.slack.com/archives/G01Q35D80EM/p1636668441019300?thread_ts=1636665670.010600&cid=G01Q35D80EM

It might resolve if we just rerun the checks

**Comment by ericharmeling** [comment]
> It might resolve if we just rerun the checks

Actually, I think you might need to rebase on master and then force push

**Review by ericharmeling — APPROVED** [review]
Thanks for the reminder. Looks good to me!

**Pull request merged**
