### PR TITLE
First pass at Connect to CockroachDB.

### LINKED ISSUE #9033: Developer Guide v2: Connect to a cluster
This chapter includes instructions on how to install a client driver/ORM for an application’s persistence layer, and then use the driver/ORM to connect to a running cluster. 

See [tracking doc for more details](https://docs.google.com/document/d/1yHtJqNgdM04xzA7q5rE-mfXg_FkToSnRHed-3gCwHn8).

### PR DESCRIPTION
**Pull request by ianjevans**
Fixes #9033.

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Looks great so far! I know it's a WIP, but I still have some comments. More than happy to discuss offline as needed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9346#-:-MRPt13F3IY8LHK6TWNG:b-egrog1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v21.1/connect-to-the-database.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPqMb0-tQECi4tYTcd:-MRPqMb18paI3kMiJcP1:b-w2jafs) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L18)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> Make sure you have already:
> - Set up either a local CockroachDB or a CockroachCloud cluster:
> -- [Create](install-cockroachdb.html) and [configure](secure-a-cluster.html) a local cluster.
> -- [Create](cockroachcloud/create-your-cluster.html) and [configure](cockroachcloud/connect-to-your-cluster.html) a CockroachCloud cluster.
> - [Installed a Postgres client](install-client-drivers.html).
> ```
</details>


fairly pretentious grammar nit:

The mix of grammatical moods here is a little difficult to parse. Can we change this to just "Do the following:" and have them all be imperative (and not present perfect indicative).
___
*[v21.1/connect-to-the-database.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPuuqbEFBlr85hn3Kn:-MRPuuqbEFBlr85hn3Ko:b1hgce4) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L37)):*
> ```
> | %} -->
> ```

I think this is breaking the build?

https://teamcity.cockroachdb.com/buildConfiguration/Internal_Docs_GitHubCi/2595098?buildTab=log&focusLine=3&linesState=308

It could also be the includes at the bottom (see my comments there).
___
*[v21.1/connect-to-the-database.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRQ-CkL7DNf9JdW9fh3:-MRQ-CkL7DNf9JdW9fh4:b5hejao) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L64)):*
> ```
> &options=--cluster=<cluster_name>
> ```

Nice. IIUC, this parameter is one of the main differences between connecting to a local cluster and a CC cluster. We should add this to the [Connection Parameters](https://www.cockroachlabs.com/docs/stable/connection-parameters) page ahead of Free Tier launch for sure. 
@lnhsingh 

(Someone might have already started doing this or opened an issue so disregard if that's the case!)
___
*[v21.1/connect-to-the-database.md, line 183 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPzq3d3XDysvcKnmBb:-MRPzq3d3XDysvcKnmBc:b-w09aog) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L183)):*
> ```Markdown
> 
> </section>
> ```

We might want to add a quick paragraph here just explaining the different connection parameters, and then references that connection parameters page. What do you think?
___
*[v21.1/connect-to-the-database.md, line 184 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPxYpL3ahSsmMN8bTX:-MRPxYpL3ahSsmMN8bTY:bpmoulo) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L184)):*
> ```
> {% include {{page.version.version}}/connection_params.md %}
> ```


I think this is meant to be for the above reference to `connection_params` (which is not a file)? If that's the case, the link `[connection_params]: connection-parameters.html` is already at the bottom of the page, so you can remove this.
___
*[v21.1/connect-to-the-database.md, line 186 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPxdUJ5bnZ2XXIkCpf:-MRPxdUK2Zf4qJyAwT9T:btd2b4d) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L186)):*
> ```
> {% include {{page.version.version}}/authentication.md %}
> ```

I think include files need to be in the `_includes` directory, and not have front matter.

Also, we probably just want a short section here on the very basics of authentication that references the lengthier [Authentication security page](https://www.cockroachlabs.com/docs/stable/authentication.html).
___
*[v21.1/install-client-drivers.md, line 2 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPrh1PCpEMObx3-OyY:-MRPrh1PCpEMObx3-OyZ:b-qypcxg) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/install-client-drivers.md#L2)):*
> ```
> ORM Framework
> ```

Unrelated to this PR: If "ORM Framework" this is the more technically accurate phrasing, then we should work to update all other instances in our docs of just "ORM".
___
*[v21.1/install-client-drivers.md, line 182 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRPsjt2D-sVOkBYKzYp:-MRPsjt2D-sVOkBYKzYq:bcb8c0n) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/install-client-drivers.md#L182)):*
> ```
> Not all versions of CockroachDB have a corresponding dialect.
> ```

Not all versions of CockroachDB have a corresponding dialect yet.

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @ianjevans)

___
*[v21.1/connect-to-the-database.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/docs/9346#-MRQ-CkL7DNf9JdW9fh3:-MRRoXG70tRrkjLpzFis:bmvgi9w) ([raw file](https://github.com/cockroachdb/docs/blob/668de73fc17526c80acbe8260ebe3975adcd37dd/v21.1/connect-to-the-database.md#L64)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> &options=--cluster=<cluster_name>
> ```

Nice. IIUC, this parameter is one of the main differences between connecting to a local cluster and a CC cluster. We should add this to the [Connection Parameters](https://www.cockroachlabs.com/docs/stable/connection-parameters) page ahead of Free Tier launch for sure. 
@lnhsingh 

(Someone might have already started doing this or opened an issue so disregard if that's the case!)
</blockquote></details>

Yep, this is needed for apps to connect to CC! When we update Connection Parameters, we need to make sure to update the v20.2 docs too since CC is only in v20.2 at the moment. Let me know if you want me to open an issue for this

**Comment by ianjevans** [comment]
> > @lnhsingh
> Yep, this is needed for apps to connect to CC! When we update Connection Parameters, we need to make sure to update the v20.2 docs too since CC is only in v20.2 at the moment. Let me know if you want me to open an issue for this

We should probably open a separate issue for the 20.2 branch since this branch won't be merged to master for a little while.

**Comment by ianjevans** [comment]
> > ORM Framework
> > ```
> 
> Unrelated to this PR: If "ORM Framework" this is the more technically accurate phrasing, then we should work to update all other instances in our docs of just "ORM".

I definitely don't want this to sound fussy, but just aesthetically I would never say "use the the following settings to configure the Whatever object relational mapping." Just feels like something is missing.

**Review by ericharmeling — COMMENTED** [review]
Looks good to merge into `dev-guide-v2`.

The TC tests are going to keep failing until we fix all the links broken by the changes made to the ToC. We can do that in a future PR.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9346#-:-MRV6pSH26uzQF8b713l:bslbyj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @ianjevans)

**Review by ericharmeling — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

**Pull request merged**
