### PR TITLE
Answer more FAQs in the docs

### PR DESCRIPTION
**Pull request by jseldess**
As we identify more and more FAQs, we need a good way
to make answers to these questions easily accessible/searchable
in the docs. This PR offers one possible approach: Adding
an FAQs section to the sidenav, with categories of FAQs broken
into distinct pages. For example, in addition to the general
FAQ we've had for some time, I've added a page on SQL-specific
FAQs.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1315)

### CODE REVIEW

**Comment by jseldess** [comment]
@sploiselle, @dianasaur323, @spencerkimball, @bdarnell, interesting in your thoughts on this approach. I think it could suffice for a while, in the absence of a more traditional support-type "knowledge base". 

An alternate approach would be to have each question and answer on its own page (much like in a support-style knowledge base), but perhaps we could consider that route when the FAQ pages get too long. 

We were also talking about using StackOverflow and returning SO `cockroachdb` results in our docs search, but from what I can find, it's not going to be possible to do that well. SO can be great both for very niche questions as well as FAQs, and seems to me it doesn't hurt to have some redundancy in our docs.

**Comment by jseldess** [comment]
Also note that, in the near future, the **CockroachDB in Comparison** page will likely move out of docs, and we'll likely put architecture docs, which Sean is working on this quarter, somewhere else, too. So this FAQs section could eventually be exclusively devoted to FAQs.

**Comment by sploiselle** [comment]
Great thinking, @jseldess!

Think we could also solve the "knowledge base" problem you mention by using includes more aggressively. Think that could net us a few things:

- Ensures answers don't get out of sync (e.g. guidance around using interleaved tables)
- Optimizes for search/provides knowledge base-like behavior, while still letting us aggregate them on FAQ pages.

The only thing that gives me slight pause with it is that Google checks for duplicate content, so it might be worth testing this with a few of them and seeing how they behave before committing to the strategy full-on.

Thoughts on that?

**Comment by jseldess** [comment]
Excellent idea, @sploiselle. I've created an `_includes/faq` directory and already created examples of content that appears in an faq and in reference page. 

How should we go about testing how Google responds to the includes?

**Comment by sploiselle** [comment]
Exciting you got this implemented so quickly. 

For the pages that use shared content, I think we can monitor traffic from Google for a decline in the page views.

**Comment by jseldess** [comment]
OK, thanks, @sploiselle.

@dianasaur323, @jess-edwards, thoughts? One thing to point out is that, in this revision, I removed the "CockroachDB Features" pages from the sidenav. The pages are still there, there's just not listed in the sidenav. Figure those pages are going to be replaced by the product page as well as architecture pages that Sean is writing eventually, anyway. But if there are objections, I can put them back in the sidenav.

**Comment by kuanluo** [comment]
Great idea, @jseldess @sploiselle! 

One thought: Would be interesting to A/B test the placement of FAQ link in the nav. My eyes generally land on the first item and glance over the middle and land on the last item. Since FAQ does provide great value, a hypothesis is that by placing it at the bottom of the links, it will get more clicks. I don't have strong feelings about it, but would be cool to test.

**Comment by jseldess** [comment]
Let's go with your assumption, @kuanluo. I've moved FAQs to the bottom of the sidenav. If the content doesn't get enough traffic, we can think about doing A/B testing.

**Comment by dianasaur323** [comment]
:lgtm: The FAQs look good!

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1315#-:-KiHxkxThOt-3DwbELCY:b-sa3l3s)*

**Comment by jseldess** [comment]
OK, for now, I'm putting the CockroachDB Features pages back in and merging the rest of these changes. We can remove the feature pages once it makes sense.

**Pull request merged**
