### PR TITLE
Inverted join support in 21.1

### LINKED ISSUE #9114: sql,util,opt: add support for inverted joins with JSON and Array columns
PR: https://github.com/cockroachdb/cockroach/pull/55679

From release notes:
> It is now possible to hint to the optimizer that it should plan an inverted join by using the syntax `... INNER INVERTED JOIN ...` or `... LEFT INVERTED JOIN ...`. If the hint is provided and it is possible to plan an inverted join, the optimizer will now plan an inverted join, even if it estimates that a different plan would have a lower cost. If the hint is provided but it is not possible to plan an inverted join because there is no inverted index on the right side table or the join condition is not a valid inverted join condition, the database will return an error. [#55679][#55679] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ianjevans**
Fixes #9114

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice! Thanks for working on this.

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10324#-:-MYLyZZA8HHZuzv8z4PS:b-9tovmd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v21.1/cost-based-optimizer.md, line 165 at r2](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYLvepp86nBdqOD14Ul:-MYLvepp86nBdqOD14Um:bvg4o5i) ([raw file](https://github.com/cockroachdb/docs/blob/2bec033ae52090eeda9dbd7c48bbff23d347550f/v21.1/cost-based-optimizer.md#L165)):*
> ```Markdown
> - `LOOKUP`: Forces a lookup join into the right side; the right side must be a table with a suitable index. Note that `LOOKUP` can only be used with `INNER` and `LEFT` joins.
> 
> - `INVERTED`: <span class="version-tag">New in v21.1:</span> Forces an inverted join, even if the optimizer determines that a different plan would have a lower cost. The join must have an [inverted index](inverted-indexes.html).
> ```

nit: instead of this text, I'd do something similar to the `LOOKUP` case above. You can basically copy the `LOOKUP` text exactly, but replace "lookup" with "inverted", and "index" with "inverted index".

The part about "... even if the optimizer determines that a different plan would have a lower cost" is a great point, but it applies for all join hints, not just this one. Might be worth adding that text somewhere higher up.
___
*[v21.1/cost-based-optimizer.md, line 224 at r2](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYLxK5lB04Wwt9pJINV:-MYLxK5lB04Wwt9pJINW:b-ghwsig) ([raw file](https://github.com/cockroachdb/docs/blob/2bec033ae52090eeda9dbd7c48bbff23d347550f/v21.1/cost-based-optimizer.md#L224)):*
> ```Markdown
> #### Inverted join examples
> 
> To run these example, initialize a demo cluster with the MovR workload.
> ```

nit: these example -> these examples
___
*[v21.1/cost-based-optimizer.md, line 266 at r2](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYLxi0w2fIxLZw2lg1R:-MYLxi0w2fIxLZw2lg1S:brjy0wp) ([raw file](https://github.com/cockroachdb/docs/blob/2bec033ae52090eeda9dbd7c48bbff23d347550f/v21.1/cost-based-optimizer.md#L266)):*
> ```Markdown
> ~~~
> 
> You can omit the `INNER INVERTED JOIN` statement by putting the inverted index the left side of the join.
> ```

it doesn't have to be on the left side. You could have also used `FROM vehicles AS v2, vehicles@idx_vehicle_details AS v1`. The important thing is that `v1.ext` is on the left side of the `@>` join condition.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10324#-:-MYlzfym3XEAB2Zu_6cK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v21.1/cost-based-optimizer.md, line 266 at r2](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYLxi0w2fIxLZw2lg1R:-MYlyn1F9rc58T9Tr4SM:b-29m8ox) ([raw file](https://github.com/cockroachdb/docs/blob/2bec033ae52090eeda9dbd7c48bbff23d347550f/v21.1/cost-based-optimizer.md#L266)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

it doesn't have to be on the left side. You could have also used `FROM vehicles AS v2, vehicles@idx_vehicle_details AS v1`. The important thing is that `v1.ext` is on the left side of the `@>` join condition.
</blockquote></details>

looks like you might be missing a backtick after @>

I'd say something like "... by putting `v1.ext` on the left side of a `@>` join condition in a `WHERE` clause and using an index hint for the inverted index."

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10324#-:-MYmEWqb9ksfDj64OTH3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Review by ericharmeling — COMMENTED** [review]
Looks good! Just had a few questions/comments.

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10324#-:-MYohemt0eNsILkpjdPd:buehrxx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans)

___
*[v21.1/cost-based-optimizer.md, line 125 at r4](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYog7C021lEw03KAhES:-MYog7C021lEw03KAhET:bhiwia6) ([raw file](https://github.com/cockroachdb/docs/blob/9573b825af18bf47f658c210c49277b1f00d477f/v21.1/cost-based-optimizer.md#L125)):*

Just realized we don't even link to the Joins page on this page. Should probably add one here.

> ```
> join orderings
> ```

[join orderings](joins.html)


Also at the end of the file, under "See also"

- [JOIN expressions](joins.html)
___
*[v21.1/cost-based-optimizer.md, line 147 at r4](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYofFpq0NXQnQSdjWLb:-MYofFpr6Qwkb1Xw1n30:b-21402n) ([raw file](https://github.com/cockroachdb/docs/blob/9573b825af18bf47f658c210c49277b1f00d477f/v21.1/cost-based-optimizer.md#L147)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - `INNER HASH JOIN`
> - `OUTER MERGE JOIN`
> - `LEFT LOOKUP JOIN`
> - `CROSS MERGE JOIN`
> ```
</details>


Should the `INVERTED` join hints be listed as well?
___
*[v21.1/cost-based-optimizer.md, line 157 at r4](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYoiF8m8b28WHTPUKl2:-MYoiF8n-OkNtzBv8HLB:b-70z0qn) ([raw file](https://github.com/cockroachdb/docs/blob/9573b825af18bf47f658c210c49277b1f00d477f/v21.1/cost-based-optimizer.md#L157)):*
> ```
> ### Supported join algorithms
> ```

> ```
> If it is not possible to use the algorithm specified in the hint, an error is signaled.
> ```


See my comment on joins.md about wording here.
___
*[v21.1/cost-based-optimizer.md, line 222 at r4](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYoetuA15hDUkINNYoz:-MYoetuA15hDUkINNYp-:b-a2kx4c) ([raw file](https://github.com/cockroachdb/docs/blob/9573b825af18bf47f658c210c49277b1f00d477f/v21.1/cost-based-optimizer.md#L222)):*
> ```
> Inverted join examples
> ```

This is a nice example, but it seems a bit out-of-place on this page, since none of the other, more popular types of joins have examples here. 

IDK - I'm sure it'll be fine to keep here. It might just make more sense on the "Inverted Indexes" page (inverted-indexes.md) or the "JOIN expressions" page (joins.md).
___
*[v21.1/joins.md, line 110 at r4](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYogSqPAM_rVy1knn4A:-MYogSqPAM_rVy1knn4B:baup0en) ([raw file](https://github.com/cockroachdb/docs/blob/9573b825af18bf47f658c210c49277b1f00d477f/v21.1/joins.md#L110)):*
> ```
> ## Join algorithms
> ```

On the Cost-based Optimizer page (cost-based-optimizer.md), we list "Inverted joins" under "Supported join algorithms". But it's not listed here. If inverted join is an algorithm type at the level of a merge, hash, or lookup join, then we should def also have it here. If it's not, then maybe we should change the title of the "Supported join algorithms" section on the Cost-based Optimizer page to "Supported join types" or something?

**Comment by ianjevans** [comment]
> Just realized we don't even link to the Joins page on this page. Should probably add one here.

Done.

> Also at the end of the file, under "See also"

Done.

> Should the `INVERTED` join hints be listed as well?

Done.

> See my comment on joins.md about wording here.

Done.

> This is a nice example, but it seems a bit out-of-place on this page, since none of the other, more popular types of joins have examples here.
> 
> IDK - I'm sure it'll be fine to keep here. It might just make more sense on the "Inverted Indexes" page (inverted-indexes.md) or the "JOIN expressions" page (joins.md).

I made it an include, and it's now in both `inverted-indexes.md` and `cost-based-analyzer.md`.

> On the Cost-based Optimizer page (cost-based-optimizer.md), we list "Inverted joins" under "Supported join algorithms". But it's not listed here. If inverted join is an algorithm type at the level of a merge, hash, or lookup join, then we should def also have it here. If it's not, then maybe we should change the title of the "Supported join algorithms" section on the Cost-based Optimizer page to "Supported join types" or something?

Moved it under "Supported join algorithms", as that is what it actually is.

**Review by ericharmeling — APPROVED** [review]
Awesome. Just one final nit. Then, LGTM!

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10324#-:-MYuYTWP3o3DhwNg_JU4:b-bjjmav)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ianjevans)

___
*[v21.1/joins.md, line 39 at r6](https://reviewable.io/reviews/cockroachdb/docs/10324#-MYuYnz69EBKtzzP46PU:-MYuYnz69EBKtzzP46PV:b-gszxvm) ([raw file](https://github.com/cockroachdb/docs/blob/b9cac534833547ec72471cd285e200d34908566a/v21.1/joins.md#L39)):*
> ```
> - [Inverted joins](#inverted-joins)
> ```

Should probably remove this from the list, since its not listed immediately under this list as a "join type" anymore.

**Comment by ianjevans** [comment]
TFTR, Eric and Becca!

**Pull request merged**
