### PR TITLE
Fix spelling of datacenter and round trip on various pages

### PR DESCRIPTION
**Pull request by a-robinson**
Let me know if you'd prefer "round-trip" to "round trip", but the
misspellings should be fixed either way.

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @a-robinson! I'd prefer `round-trip`. LGTM once that's used everywhere.

**Comment by a-robinson** [comment]
I'm getting extra grammatical now - I used "round trip" for all nouns and "round-trip" for adjectives.

**Comment by jseldess** [comment]
`round-trip` is definitely correct as an adjective, but there aren't fixed rules about hyphenating compound nouns, so both `round trip` and `round-trip` are correct as a noun. `round trip` is fine for now. The docs writers want to create a more extensive style guide soonish, and this type of convention should be part of the process (cc @Amruta-Ranade and @lhirata).

**Comment by jseldess** [comment]
Sorry for letting this sit so long, @a-robinson. LGTM. Will merge once it passes TeamCity.

**Comment by a-robinson** [comment]
No worries, I forgot about it too :)

**Pull request merged**
