### PR TITLE
beta-20170105 release notes - links, edits, and doc updates

### PR DESCRIPTION
**Pull request by jseldess**
Links, edits, and additional doc updates. 

@sploiselle, please proof this for me. 

@swatikumar16, @dianasaur323, just fyi, in case you want to take an early look.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/972)

### CODE REVIEW

**Comment by sploiselle** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[beta-20170105.md, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/972#-K_jiwrA3Nc4ic02DvsV:-K_jiwrA3Nc4ic02DvsW:bhsf790) ([raw file](https://github.com/cockroachdb/docs/blob/59878ccb66442f2bb48cc0606f8b28c76f3cfc49/beta-20170105.md#L47)):*
> ```Markdown
> 
> - When a node stops responding to heartbeats, non-heartbeat raft traffic to that node is suspended until it becomes responsive again. [#12631](https://github.com/cockroachdb/cockroach/pull/12631)
> - Improved logic for transfering raft leadership to coincide with the lease holder. [#12323](https://github.com/cockroachdb/cockroach/pull/12323)
> ```

s/transfering/transferring

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/972)*

**Comment by sploiselle** [comment]
:lgtm: mod one comment

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/972#-:-K_jjIBjrRMZ0J9dwPkD:btovv3s)*

**Comment by sploiselle** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/972)*

**Comment by mberhault** [comment]
LGTM

**Comment by sploiselle** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[beta-20170105.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/972#-K_julJLZi7RZdcX2fOS:-K_julJLZi7RZdcX2fOT:b91res4) ([raw file](https://github.com/cockroachdb/docs/blob/59878ccb66442f2bb48cc0606f8b28c76f3cfc49/beta-20170105.md#L22)):*
> ```Markdown
> ### SQL Language Changes
> 
> - `FILTER` clauses for [aggregate functions](functions-and-operators.html#aggregate-functions) are now supported. [#10146](https://github.com/cockroachdb/cockroach/pull/10146)
> ```

Just got [the `FILTER` example](https://www.cockroachlabs.com/docs/select.html#filter-columns-fed-into-aggregate-functions) live if there's a standardized way of including some context there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/972)*

**Comment by dianasaur323** [comment]
Quick edit - fix spelling on "improved logic for transfering raft leadership to coincide with the lease holder"

**Comment by jseldess** [comment]
Thanks, @dianasaur323. Fixed.

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[beta-20170105.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/972#-K_julJLZi7RZdcX2fOS:-K_k7qGHl2pgAlWxE0nQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/59878ccb66442f2bb48cc0606f8b28c76f3cfc49/beta-20170105.md#L22)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Just got [the `FILTER` example](https://www.cockroachlabs.com/docs/select.html#filter-columns-fed-into-aggregate-functions) live if there's a standardized way of including some context there.
</blockquote></details>

Done.

---

*[beta-20170105.md, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/972#-K_jiwrA3Nc4ic02DvsV:-K_k7ro0dcdF6sGm9UDM:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/59878ccb66442f2bb48cc0606f8b28c76f3cfc49/beta-20170105.md#L47)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

s/transfering/transferring
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/972)*

**Pull request merged**
