### PR TITLE
support for collated strings

### LINKED ISSUE #847: sql: collation support
Phase 1 PR: https://github.com/cockroachdb/cockroach/pull/10605
Phase 2 PR: https://github.com/cockroachdb/cockroach/pull/12294

### PR DESCRIPTION
**Pull request by sploiselle**
closes #847

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/974)

### CODE REVIEW

**Comment by eisenstatdavid** [comment]
This doc is in good shape, though I've made several suggestions below. The main thing is documenting that using collated strings in indexes or primary keys will *PANIC* CRDB until #2473 is fixed.

---

Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[collate.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3Omeqxiqo1qNa1mkz:-Ka3Omeqxiqo1qNa1ml-:breu8lh) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L7)):*
> ```Markdown
> ---
> 
> The collated strings [data type](data-types.html) lets you choose the alphabetic sorting of ASCII characters in a string.
> ```

Suggest s/strings/string/. Collations affect the ordering of non-ASCII and even non-alphabetic characters; suggest "lets you sort strings according to language- and country-specific rules".

---

*[collate.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3PmYNDxWduV0xTlY4:-Ka3PmYObHm6zD6PmFm7:blm780q) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L9)):*
> ```Markdown
> The collated strings [data type](data-types.html) lets you choose the alphabetic sorting of ASCII characters in a string.
> 
> {{site.data.alerts.callout_danger}}Whenever using collated strings, all strings in the operation must be cast to use the same collation. Strings without a collation cannot be used alongside those with one, and strings with different collations cannot be used alongside one another. However, it is possible to <a href="#ad-hoc-collation-casting">add or overwrite a collation on the fly</a>.{{site.data.alerts.end}}
> ```

The cast is unnecessary for strings that already have a collation. Suggest replacing the first two sentences with "Operations on collated strings cannot involve strings with a different collation or strings with no collation. It is possible..."

---

*[collate.md, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3RQNYq0FZZjlSRjIA:-Ka3RQNYq0FZZjlSRjIB:bocg42r) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L15)):*
> ```Markdown
> ## SQL Syntax
> 
> Collations appear as normal strings in SQL, but have the `COLLATION` clause appended to them.
> ```

s/Collations/Collated strings/. Suggest s/but have the/but they have a/. Also, s/`COLLATE`/`COLLATION`/g, or am I missing something?

---

*[collate.md, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3SdA_1_kr7CyODwPi:-Ka3SdA_1_kr7CyODwPj:bun7xl) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L31)):*
> ```Markdown
> ### Supported Collations
> 
> CockroachDB offers collations of languages supported in Go's [language package](https://godoc.org/golang.org/x/text/language#Tag). These are identified by the string of characters at the end of each line, immediately preceded by `//`. For example, Afrikaans is supported as the `af` collation.
> ```

Suggest "CockroachDB supports the collations provided by Go's..." and "The `<collation>` argument is the BCP 47 language tag at the end of each line, ..."

---

*[collate.md, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3TbMO1_fQVNrAb5CA:-Ka3TbMO1_fQVNrAb5CB:b-718stn) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L52)):*
> ```Markdown
> ## Length
> 
> To limit the length of a collated string column, use `STRING(n) COLLATE ...`, where `n` is the maximum number of characters allowed. 
> ```

Suggest s/characters/code points/, which is more correct. This is actually the case for `STRING` as well, though I would have higher expectations for the readers of this page w.r.t. how much they know about Unicode.

---

*[collate.md, line 70 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3Up_GRngp_KM8ZBVu:-Ka3Up_GRngp_KM8ZBVv:bne2v6t) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L70)):*
> ```Markdown
> ### Hexadecimal-Encoded String Literal
> 
> When inserting a hexadecimal-encoded string literal into a `STRING` column, format the value as `x` or `X` followed by hexadecimal digits in single quotes followed by the `COLLATION` clause. For example, `x'636174' COLLATE en` or `X'636174' COLLATE en` correspond to the Unicode string literal `'cat'`.
> ```

Maybe a non-ASCII example here to demonstrate the UTF-8 encoding?

---

*[collate.md, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3V0hK0cfRDQjuAcNM:-Ka3V0hK0cfRDQjuAcNN:b18450i) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L74)):*
> ```Markdown
> ### Escape String
> 
> When inserting an escape string into a collated string column, format the value as `e` or `E` followed by one or more of the following backslash escape sequences within single quotes:   
> ```

Just curious -- seeing three horizontal red dots in Reviewable. Is this WAI?

---

*[collate.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3VFxMdzgqRywWYnpB:-Ka3VFxMdzgqRywWYnpC:brshxcf) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L94)):*
> ```Markdown
> ## Size
> 
> The size of a collated string value is variable, but it's recommended to keep values under 64 kilobytes to ensure performance. Above that threshold, [write amplification](https://en.wikipedia.org/wiki/Write_amplification) and other considerations may cause significant performance degradation.
> ```

Worth noting that non-indexed collated strings are the same size as strings on disk. In memory, they need the collation key too, which is the byte sequence used to compare collated strings; this byte sequence should be roughly comparable in size to the string itself. Per top comment, indexes on collated strings do not work yet and will in fact panic CockroachDB -- #2473. When they do work, the extra on-disk cost will be at least another key-value pair whose value is the collation key.

---

*[collate.md, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3WNm_CZ0iImFqSs4B:-Ka3WNm_CZ0iImFqSs4C:b-au1wu1) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L179)):*
> ```Markdown
> SELECT 'X' COLLATE ko < 'ü' COLLATE da;
> ~~~
> ```

To remove a collation, just cast to string.

---

*[sql-feature-support.md, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3WT4Tewh2XmZ2MEnm:-Ka3WT4Ue3eZQQMHsgJk:b-iu4a9e) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/sql-feature-support.md#L34)):*
> ```Markdown
> | `DECIMAL`, `NUMERIC` | ✓ | Standard | [`DECIMAL` documentation](decimal.html) |
> | `STRING`, `CHARACTER` | ✓ | Standard | [`STRING` documentation](string.html) |
> | `COLLATE` | ✓ | Standard | [`COLLATE` documentation](collate.html) |
> ```

Partial for now -- collated string columns cannot be indexed yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974#-:-Ka3WfKJktkJOGimuFRW:b-4tr0w2)*

**Comment by sploiselle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[collate.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3Omeqxiqo1qNa1mkz:-Ka3nEpxxU-HY3iOmC5h:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L7)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Suggest s/strings/string/. Collations affect the ordering of non-ASCII and even non-alphabetic characters; suggest "lets you sort strings according to language- and country-specific rules".
</blockquote></details>

Done.

---

*[collate.md, line 9 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3PmYNDxWduV0xTlY4:-Ka3nQx0LfYBvTA7XRtf:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L9)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

The cast is unnecessary for strings that already have a collation. Suggest replacing the first two sentences with "Operations on collated strings cannot involve strings with a different collation or strings with no collation. It is possible..."
</blockquote></details>

Done.

---

*[collate.md, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3RQNYq0FZZjlSRjIA:-Ka3ngDlCjPEe7FEplAv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L15)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

s/Collations/Collated strings/. Suggest s/but have the/but they have a/. Also, s/`COLLATE`/`COLLATION`/g, or am I missing something?
</blockquote></details>

Done.

---

*[collate.md, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3SdA_1_kr7CyODwPi:-Ka3nsJclkfpkGqs_Ra4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L31)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Suggest "CockroachDB supports the collations provided by Go's..." and "The `<collation>` argument is the BCP 47 language tag at the end of each line, ..."
</blockquote></details>

Done.

---

*[collate.md, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3TbMO1_fQVNrAb5CA:-Ka3po2bW9OVJTlTDZ7V:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L52)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Suggest s/characters/code points/, which is more correct. This is actually the case for `STRING` as well, though I would have higher expectations for the readers of this page w.r.t. how much they know about Unicode.
</blockquote></details>

Done.

---

*[collate.md, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3V0hK0cfRDQjuAcNM:-Ka3qKtwBwQojcwGZ-Fq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L74)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Just curious -- seeing three horizontal red dots in Reviewable. Is this WAI?
</blockquote></details>

Done.

---

*[collate.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3VFxMdzgqRywWYnpB:-Ka3yr0pAk90QILtxdLT:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L94)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Worth noting that non-indexed collated strings are the same size as strings on disk. In memory, they need the collation key too, which is the byte sequence used to compare collated strings; this byte sequence should be roughly comparable in size to the string itself. Per top comment, indexes on collated strings do not work yet and will in fact panic CockroachDB -- #2473. When they do work, the extra on-disk cost will be at least another key-value pair whose value is the collation key.
</blockquote></details>

Done.

---

*[collate.md, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3WNm_CZ0iImFqSs4B:-Ka47He0kiLYtLOmP8vl:b-j8869p) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L179)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

To remove a collation, just cast to string.
</blockquote></details>

@eisenstatdavid Got the following error trying to cast as a string:

```
SELECT CAST(single_char AS STRING) FROM sort_example ORDER BY single_char;
pq: invalid cast: collatedstring{en} -> STRING
```

---

*[sql-feature-support.md, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3WT4Tewh2XmZ2MEnm:-Ka47cdRtXsPJkMnr2qp:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/sql-feature-support.md#L34)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Partial for now -- collated string columns cannot be indexed yet
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974)*

**Comment by bdarnell** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[collate.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka4BrTPcdanfW8G8ylp:-Ka4BrTPcdanfW8G8ylq:b-wzxg0o) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L3)):*
> ```Markdown
> ---
> title: COLLATE
> summary: The COLLATE feature lets you choose the alphabetic sorting of ASCII characters in a STRING.
> ```

Remove "ASCII" everywhere. The collation feature primarily affects non-ascii characters. (You could say "Unicode characters" if you want, but I think just "characters" is sufficient). Or maybe just "the alphabetic sorting of STRINGs" - some locales (e.g. French) are not character-by-character comparisons.

---

*[collate.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka4EqVy4vVfgjpD5Jfi:-Ka4EqVy4vVfgjpD5Jfj:b-czy3vz) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L7)):*
> ```Markdown
> ---
> 
> The collated strings [data type](data-types.html) lets you choose the alphabetic sorting of ASCII characters in a string.
> ```

We should define collation here and give an example. "Different languages have different rules for alphabetic order, especially with respect to accented letters. For example, in German accented letters are sorted with their unaccented counterparts, while in Swedish they are placed at the end of the alphabet. A collation is a set of rules used for ordering and usually corresponds to a language (but some languages have multiple collations; for example German has two: `de` and `de-u-co-phonebk`)" (Do we support the german phonebook collation?) We can link to https://en.wikipedia.org/wiki/Alphabetical_order#Language-specific_conventions

---

*[collate.md, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka4DCdLG4s5_tGv3Lim:-Ka4DCdLG4s5_tGv3Lin:bwsgmbc) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L156)):*
> ```Markdown
> You can cast any string into a collation on the fly.
> 
> For example, you can compare two strings in the Korean (`ko`) collation:
> ```

Demonstrating collation with ü in english, danish, and korean is not very illustrative since english and korean don't even use this letter (does danish? doesn't look like it according to wikipedia). A better example would be to use the letter Ä in swedish and german, since both languages use the character (but german mixes it in with the un-accented A and swedish puts it at the end of the alphabet)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974)*

**Comment by sploiselle** [comment]
After discussing with @bdarnell, decided to revert back to the original structure of treating `COLLATE` as a feature that impacts strings vs. as explicitly their own type. Let me know if there are any other edits, @eisenstatdavid

---

Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[collate.md, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka4BrTPcdanfW8G8ylp:-KaCx8LjKtW9KdefRKmI:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L3)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove "ASCII" everywhere. The collation feature primarily affects non-ascii characters. (You could say "Unicode characters" if you want, but I think just "characters" is sufficient). Or maybe just "the alphabetic sorting of STRINGs" - some locales (e.g. French) are not character-by-character comparisons.
</blockquote></details>

Done.

---

*[collate.md, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka4EqVy4vVfgjpD5Jfi:-KaCx9XAwxBnu0yUUDg4:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L7)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should define collation here and give an example. "Different languages have different rules for alphabetic order, especially with respect to accented letters. For example, in German accented letters are sorted with their unaccented counterparts, while in Swedish they are placed at the end of the alphabet. A collation is a set of rules used for ordering and usually corresponds to a language (but some languages have multiple collations; for example German has two: `de` and `de-u-co-phonebk`)" (Do we support the german phonebook collation?) We can link to https://en.wikipedia.org/wiki/Alphabetical_order#Language-specific_conventions
</blockquote></details>

Done.

---

*[collate.md, line 156 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka4DCdLG4s5_tGv3Lim:-KaCxDedfY1Xd2OpXloJ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L156)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Demonstrating collation with ü in english, danish, and korean is not very illustrative since english and korean don't even use this letter (does danish? doesn't look like it according to wikipedia). A better example would be to use the letter Ä in swedish and german, since both languages use the character (but german mixes it in with the un-accented A and swedish puts it at the end of the alphabet)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974#-:-KaCxFeNyZ00M0U8YXYU:b-ra01eh)*

**Comment by eisenstatdavid** [comment]
:lgtm: Suggestions below.

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[collate.md, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3WNm_CZ0iImFqSs4B:-KaELWXFcWxXOawnB4Bb:b-6s9n5k) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L179)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

@eisenstatdavid Got the following error trying to cast as a string:

```
SELECT CAST(single_char AS STRING) FROM sort_example ORDER BY single_char;
pq: invalid cast: collatedstring{en} -> STRING
```
</blockquote></details>

Fixed the bug -- #12820.

---

*[collate.md, line 7 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/974#-KaEJJWIGGoC1W3v3OuE:-KaEJJWIGGoC1W3v3OuF:b-46uoh4) ([raw file](https://github.com/cockroachdb/docs/blob/638f3c4dc84eac55311ff2cc10e37e82cdc66496/collate.md#L7)):*
> , which are stored in collations (also known as collation keys)
Collation keys are different -- you can think of a collation as a function c : string -> bytes, where the bytes output is the collation key. Two strings s1 and s2 are compared by compare(c(s1), c(s2)).

Suggest "language- and country-specific rules (collations)".

---

*[collate.md, line 43 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/974#-KaEKjQjxE1F8aqEJuer:-KaEKjQjxE1F8aqEJues:b-xz4l68) ([raw file](https://github.com/cockroachdb/docs/blob/638f3c4dc84eac55311ff2cc10e37e82cdc66496/collate.md#L43)):*
> ```Markdown
> Collated strings are stored on disk in the same way as [`STRING`](string.html) values, i.e., the `COLLATE` feature does not require additional disk space.
> 
> However, every time a collated string is accessed, the collation is loaded into memory. This usually doubles the size of the string in memory, which means they perform slightly slower than their non-collated counterparts.
> ```

"is accessed" is unclear. Suggest "Every time a collated string is constructed or loaded into memory, however, CockroachDB computes its collation key, whose size is linear in the length of the collated string. Prefer non-collated strings unless the special ordering is needed."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974#-:-KaEMzDI1qg-5Wd9nYXR:brh8ri5)*

**Comment by eisenstatdavid** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[collate.md, line 7 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/974#-KaEJJWIGGoC1W3v3OuE:-KaEND2UJEKtFPIDdKFP:b-skfq5g) ([raw file](https://github.com/cockroachdb/docs/blob/638f3c4dc84eac55311ff2cc10e37e82cdc66496/collate.md#L7)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

> , which are stored in collations (also known as collation keys)
Collation keys are different -- you can think of a collation as a function c : string -> bytes, where the bytes output is the collation key. Two strings s1 and s2 are compared by compare(c(s1), c(s2)).

Suggest "language- and country-specific rules (collations)".
</blockquote></details>

Quoted this by accident:

Collation keys are different -- you can think of a collation as a function c : string -> bytes, where the bytes output is the collation key. Two strings s1 and s2 are compared by compare(c(s1), c(s2)).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974)*

**Comment by sploiselle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[collate.md, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/docs/974#-Ka3WNm_CZ0iImFqSs4B:-KaJcp8Cs7se4gjg9Giz:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/3671fbc5931e4153df18a4ace75e3e52fbcc5229/collate.md#L179)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Fixed the bug -- #12820.
</blockquote></details>

Done.

---

*[collate.md, line 7 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/974#-KaEJJWIGGoC1W3v3OuE:-KaJcOiUS7q7a3_WuBmk:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/638f3c4dc84eac55311ff2cc10e37e82cdc66496/collate.md#L7)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Quoted this by accident:

Collation keys are different -- you can think of a collation as a function c : string -> bytes, where the bytes output is the collation key. Two strings s1 and s2 are compared by compare(c(s1), c(s2)).
</blockquote></details>

Done.

---

*[collate.md, line 43 at r2](https://reviewable.io:443/reviews/cockroachdb/docs/974#-KaEKjQjxE1F8aqEJuer:-KaJcm2c_1s1jZ2_xg-d:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/638f3c4dc84eac55311ff2cc10e37e82cdc66496/collate.md#L43)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

"is accessed" is unclear. Suggest "Every time a collated string is constructed or loaded into memory, however, CockroachDB computes its collation key, whose size is linear in the length of the collated string. Prefer non-collated strings unless the special ordering is needed."
</blockquote></details>

Done.

---

*[collate.md, line 7 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/974#-K_kZ3DPN5i16RLY3iZ0-r3-7:-KanRlVK5e8fjSJ5pfQ0:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/49cb6f497288910414b2d0b3f25f0d6864ecb219/collate.md#L7)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

Duplicate "lets you".
</blockquote></details>

Done.

---

*[collate.md, line 9 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/974#-K_kZ3DPN5i16RLY3iZ0-r3-9:-KanRx_b7brlM6PHQJeS:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/49cb6f497288910414b2d0b3f25f0d6864ecb219/collate.md#L9)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

I think the warning on the `STRINGS` page is phrased more clearly. Can you use that one here as well?
</blockquote></details>

Done.

---

*[collate.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/974#-K_kZ3DPN5i16RLY3iZ0-r3-13:-KanSG85IxvvjIYrAsuM:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/49cb6f497288910414b2d0b3f25f0d6864ecb219/collate.md#L13)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

The intro feels a bit jumbled. It provides context and explains the significance, but also calls out warnings and special considerations. I think it may help, actually, to pull the warning and info callout into a separate section, perhaps the first section, called something like **Special Considerations**. That may help the flow of the intro a bit. Thoughts?

Alternately, perhaps we could put the warning and info callout together at the end of the intro.
</blockquote></details>

Done.

---

*[collate.md, line 80 at r3](https://reviewable.io:443/reviews/cockroachdb/docs/974#-K_kZ3DPN5i16RLY3iZ0-r3-80:-KanT5zxc78bj9Q0bHsd:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/49cb6f497288910414b2d0b3f25f0d6864ecb219/collate.md#L80)):*
<details><summary><i>Previously, jseldess wrote…</i></summary><blockquote>

The parenthetical doesn't directly map to the example, so I'd either remove it or add a brief follow-up example demonstrating collation-based sorts on non-collated columns. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/974)*

**Comment by jseldess** [comment]
LGTM

**Pull request merged**
