### PR TITLE
DOC-3431: Remove references to CONVERT TO SCHEMA

### PR DESCRIPTION
**Pull request by nickvigilante**
Fixes DOC-3431

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
LGTM

**Review by gemma-shay — APPROVED** [review]
Is there a page that we can add a redirect_from to? LGTM otherwise.

**Comment by nickvigilante** [comment]
@gemma-shay That's a good point, now that you mention it. Maybe the `CREATE SCHEMA` docs?

**Comment by gemma-shay** [comment]
looks good!

**Pull request merged**
