### PR TITLE
New docs on select clauses

### LINKED ISSUE #1488: Docs for INSERT, UPSERT, CREATE TABLE AS and SELECT do not sufficiently explain "select clauses"
This is an unfortunate artifact of the grammar in the source code which obfuscates this fact:
**anywhere you can have a SELECT query, you can also use TABLE and VALUES**.

SELECT, TABLE and VALUES together are the three forms of what is called a "select clause".
Any select clause is a valid data source for INSERT, UPSERT, CREATE TABLE AS, table expressions in SELECT's FROM and within value expressions as a subquery.

| Statement | Example using SELECT | Example using VALUES | Example using TABLE |
|----------------|-----------------------------------|------------------------------------|-------------------------------|
| INSERT | `INSERT INTO foo SELECT * FROM bar` | `INSERT INTO foo VALUES (1), (2), (3)` | `INSERT INTO foo TABLE bar`
| UPSERT | `UPSERT INTO foo SELECT * FROM bar` | `UPSERT INTO foo VALUES (1), (2), (3)` | `UPSERT INTO foo TABLE bar`
| CREATE TABLE AS | `CREATE TABLE foo AS SELECT * FROM bar` | `CREATE TABLE foo AS VALUES (1),(2),(3)` | `CREATE TABLE foo AS TABLE bar`
| SELECT | `SELECT * FROM (SELECT * FROM bar)` | `SELECT * FROM (VALUES (1),(2),(3))` | `SELECT * FROM (TABLE bar)`
| Expression subquery | `SELECT * FROM foo WHERE x IN (SELECT * FROM bar)` | `SELECT * FROM foo WHERE x IN (VALUES (1),(2),(3))` | `SELECT * FROM foo WHERE x IN (TABLE bar)`

I think in general it would be useful to start to convey throughout the docs that SQL is really about manipulating tabular data, and there are fundamentally just 3 ways to obtain tabular data *anywhere where it is manipulated by other statements*: **load it from the database** (TABLE), **list it by the client** (VALUES), and **compute it from other things** (SELECT).

### PR DESCRIPTION
**Pull request by knz**
Fixes #1488.

Also includes using statements between '[...]'

### CODE REVIEW

**Comment by knz** [comment]
The changes in #2199 would greatly benefit from this. Perhaps we could move this discussion forward?

**Comment by jseldess** [comment]
Yes, so sorry for the delay, @knz. I'll look at this today.

**Comment by knz** [comment]
Reviewed 7 of 7 files at r3, 1 of 1 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[v1.1/select-clause.md, line 115 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1934#-Kz_1MJaSKj8ApsdoLx0:-Kz_1MJbWoihIZogjTSy:b-4dvqv0) ([raw file](https://github.com/cockroachdb/docs/blob/08d2f31e0260ee4b482e74a72855cac2a67034c8/v1.1/select-clause.md#L115)):*
> ```Markdown
> ## `SELECT` Clause
> 
> The `SELECT` clause is documented separately as the stand-alone [`SELECT` statement](select.html), which is its most common use in SQL. However, it's important to note the broader application of `SELECT` clauses, which can be used alongside the other two `SELECT` clause forms everywhere such a clause is admissible.
> ```

This paragraph needs extra care to distinguish "selection clause" from "`SELECT` clause".
I think this works:

```
The `SELECT` clause is documented separately as the stand-alone [`SELECT` statement](select.html), which is its most common use in SQL. However, it's important to note the broader application of `SELECT` clauses, which can be used alongside the other two selection clause forms everywhere such a clause is admissible.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1934)*

**Comment by jseldess** [comment]
*[v1.1/selection-clauses.md, line 115 at r5](https://reviewable.io:443/reviews/cockroachdb/docs/1934#-Kz_1MJaSKj8ApsdoLx0:-Kz_5B02iMJ2DHGs6_13:b9me8z5) ([raw file](https://github.com/cockroachdb/docs/blob/08d2f31e0260ee4b482e74a72855cac2a67034c8/v1.1/selection-clauses.md#L115)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This paragraph needs extra care to distinguish "selection clause" from "`SELECT` clause".
I think this works:

```
The `SELECT` clause is documented separately as the stand-alone [`SELECT` statement](select.html), which is its most common use in SQL. However, it's important to note the broader application of `SELECT` clauses, which can be used alongside the other two selection clause forms everywhere such a clause is admissible.
```

</blockquote></details>

Done. Also applied all the other updates we discussed. Let me know what you think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1934)*

**Comment by knz** [comment]
:LGTM:  Thank you! :sparkles: 

---

Reviewed 18 of 18 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/docs/1934#-:-Kz_64OZ1oht6C_aHH8w:b-3ytxy2)*

**Comment by jseldess** [comment]
Thank you, @knz, for the great content!

**Pull request merged**
