### PR TITLE
correct ycsb workload flag and add data-loader flags

### LINKED ISSUE #9215: Correct the YCSB workload flag descriptions
Corrected the `--insert-count` flag on `cockroach workload init ycsb` (was `--initial-count`) and added `--data-loader` to both the tpcc and ycsb workloads.

```
j4-crl:docs$ cockroach workload init ycsb --help
...
...
      --data-loader string                How to load initial table data. Options are INSERT and IMPORT (default "INSERT")
...
      --insert-count int                  Number of rows to sequentially insert before beginning workload. (default 10000)
```

```
j4-crl:docs$ cockroach workload init tpcc --help
...
...
      --data-loader string                     How to load initial table data. Options are INSERT and IMPORT (default "INSERT")
```

### PR DESCRIPTION
**Pull request by sheaffej**
Corrected the `--insert-count` flag on `cockroach workload init ycsb` (was `--initial-count`) and added `--data-loader` to both the tpcc and ycsb workloads.

```
j4-crl:docs$ cockroach workload init ycsb --help
...
...
      --data-loader string                How to load initial table data. Options are INSERT and IMPORT (default "INSERT")
...
      --insert-count int                  Number of rows to sequentially insert before beginning workload. (default 10000)
```

```
j4-crl:docs$ cockroach workload init tpcc --help
...
...
      --data-loader string                     How to load initial table data. Options are INSERT and IMPORT (default "INSERT")
```

Closes #9215

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
Thanks John! Can you add these edits to the `v21.1/cockroach-workload.md` as well? Also, is there an issue for this fix or did you find it on your own?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/9193#-:-MOg8K1g8ggysoIlJJxs:bxrcgcp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

**Comment by sheaffej** [comment]
@lnhsingh added the same changes to the 20.1 docs. This was on my todo list of issues to file, so there wasn't an existing issue that I am aware of.

**Comment by sheaffej** [comment]
Sorry, I misread the request and updated the v20.1 docs. I also just now updated v21.1 docs.

**Comment by lnhsingh** [comment]
Thanks for documenting this, John! These changes look good to me-- I'll merge them!

**Pull request merged**
