### PR TITLE
Indexes no longer needed on fk-constrained columns

### LINKED ISSUE #5967: Improve FK Performance and Compatibility
Background: https://cockroachlabs.atlassian.net/browse/CRDB-779

Team: Andrew Woods, Radu Berinde

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/15157 https://github.com/cockroachdb/cockroach/issues/25809 https://github.com/cockroachdb/cockroach/issues/26786 https://github.com/cockroachdb/cockroach/issues/26795 https://github.com/cockroachdb/cockroach/issues/23580 https://github.com/cockroachlabs/support/issues/224 https://github.com/cockroachdb/cockroach/issues/33467 https://github.com/cockroachdb/cockroach/issues/16491 https://github.com/cockroachdb/docs/issues/4003  https://github.com/cockroachdb/cockroach/issues/36859 https://github.com/cockroachdb/docs/issues/4788 https://github.com/cockroachdb/docs/issues/5967

### LINKED ISSUE #7861: sql: allow for dropping indexes in use in outbound fk
PR: https://github.com/cockroachdb/cockroach/pull/50769

From release notes:
> Enabled dropping indexes used in outbound foreign key relationships. [#50769][#50769] {% comment %}doc{% endcomment %}

### LINKED ISSUE #8122: sql: stop creating indexes on the origin side of an FK
PR: https://github.com/cockroachdb/cockroach/pull/50771

From release notes:
> Indexes are no longer required on the origin side of a [foreign key relationship](../v20.2/foreign-key.html), and are no longer automatically created. [#50771][#50771] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by ericharmeling**
Fixes #7861.
Fixes #8122. 
Related to #5967.

This PR removes language around auto-generated FK indexes on FK columns (i.e., referencing columns). 

----

Note that there still exist a number of examples that use `movr` tables with auto-generated FK indexes:

- comment-on.md
- create-table.md
- delete.md
- demo-low-latency-multi-region-deployment.md
- drop-table.md
- explain.md
- make-queries-fast.md
- multi-region-database.md
- performance-tuning-insecure.md
- performance-tuning.md
- query-replication-reports.md
- show-backup.md
- show-index.md
- show-partitions.md
- show-range-for-row.md
- show-ranges.md
- show-zone-configurations.md
- temporary-tables.md
- import-movr.md
- partition-by-city.md
- create-a-replication-zone-for-a-secondary-index.md
- create-a-replication-zone-for-a-table-partition.md

These examples can be updated in a separate PR, following the removal of these obsolete indexes (see tracking issue: https://github.com/cockroachdb/cockroach/issues/54764). That follow-up work should resolve #5967.

### CODE REVIEW

**Review by lucy-zhang — COMMENTED** [review]
Should we also explicitly indicate that we removed the indexing restriction in v20.2?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8480#-:-MIUreKF9sI4ljZrWL9k:blfpid9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[v20.2/drop-index.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/8480#-MIUpmS1C6zWb1WXKPzZ:-MIUpmS1C6zWb1WXKPz_:b-xphs4a) ([raw file](https://github.com/cockroachdb/docs/blob/f0784a732df1d9533cf706647c139473c1a46c20/v20.2/drop-index.md#L73)):*
> ```Markdown
> ~~~
> 
> ### Remove an index and dependent objects with `CASCADE`
> ```

I don't know if we want to get rid of this warning. It still applies to unique constraints that depend on the underlying unique index. For example:

```
demo@127.0.0.1:58822/defaultdb> CREATE TABLE t(a INT UNIQUE);
CREATE TABLE

Time: 3ms total (execution 2ms / network 1ms)

demo@127.0.0.1:58822/defaultdb> SHOW INDEX FROM t;
  table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
-------------+------------+------------+--------------+-------------+-----------+---------+-----------
  t          | primary    |   false    |            1 | rowid       | ASC       |  false  |  false
  t          | t_a_key    |   false    |            1 | a           | ASC       |  false  |  false
  t          | t_a_key    |   false    |            2 | rowid       | ASC       |  false  |   true
(3 rows)

Time: 6ms total (execution 5ms / network 0ms)

demo@127.0.0.1:58822/defaultdb> DROP INDEX t_a_key;
ERROR: index "t_a_key" is in use as unique constraint
SQLSTATE: 2BP01
HINT: use CASCADE if you really want to drop it.
demo@127.0.0.1:58822/defaultdb> DROP INDEX t_a_key CASCADE;
NOTICE: the data for dropped indexes is reclaimed asynchronously
HINT: The reclamation delay can be customized in the zone configuration for the table.
DROP INDEX

Time: 68ms total (execution 6ms / network 62ms)

```

Maybe we already have a warning about this elsewhere, but we should still mention it here.

**Review by ericharmeling — COMMENTED** [review]
> Should we also explicitly indicate that we removed the indexing restriction in v20.2?

There is a note on the foreign-key.html page. But I added an additional sentence to call attention to the fact that the restriction was in place in versions < v20.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8480#-:-MIVt8uC7gTsrf-TshIS:bexagbb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[v20.2/drop-index.md, line 73 at r1](https://reviewable.io/reviews/cockroachdb/docs/8480#-MIUpmS1C6zWb1WXKPzZ:-MIVlo5h6_bhdWbmzrCo:bdsytva) ([raw file](https://github.com/cockroachdb/docs/blob/f0784a732df1d9533cf706647c139473c1a46c20/v20.2/drop-index.md#L73)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I don't know if we want to get rid of this warning. It still applies to unique constraints that depend on the underlying unique index. For example:

```
demo@127.0.0.1:58822/defaultdb> CREATE TABLE t(a INT UNIQUE);
CREATE TABLE

Time: 3ms total (execution 2ms / network 1ms)

demo@127.0.0.1:58822/defaultdb> SHOW INDEX FROM t;
  table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
-------------+------------+------------+--------------+-------------+-----------+---------+-----------
  t          | primary    |   false    |            1 | rowid       | ASC       |  false  |  false
  t          | t_a_key    |   false    |            1 | a           | ASC       |  false  |  false
  t          | t_a_key    |   false    |            2 | rowid       | ASC       |  false  |   true
(3 rows)

Time: 6ms total (execution 5ms / network 0ms)

demo@127.0.0.1:58822/defaultdb> DROP INDEX t_a_key;
ERROR: index "t_a_key" is in use as unique constraint
SQLSTATE: 2BP01
HINT: use CASCADE if you really want to drop it.
demo@127.0.0.1:58822/defaultdb> DROP INDEX t_a_key CASCADE;
NOTICE: the data for dropped indexes is reclaimed asynchronously
HINT: The reclamation delay can be customized in the zone configuration for the table.
DROP INDEX

Time: 68ms total (execution 6ms / network 62ms)

```

Maybe we already have a warning about this elsewhere, but we should still mention it here.
</blockquote></details>

Good point. I added a `UNIQUE` example. (and refreshed that first example)

**Review by lucy-zhang — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8480)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by lnhsingh — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8480#-:-MIyhf_yBkFWsdJitE7h:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lnhsingh)

**Pull request merged**
