### PR TITLE
Added note on TLS encryption

### LINKED ISSUE #4699: Document that cloud storage SDKs use TLS
A customer noted that we don't explicitly mention whether CockroachDB's connections to external cloud storage systems are encrypted. We should add a note to the table of cloud storage providers indicating that the S3, Google, Azure, and HTTPS cloud storage providers all use TLS under the hood.

### PR DESCRIPTION
**Pull request by kathancox**
Added a note on TLS encryption for in transit and at rest following the cloud storage options table.

Closes #4699

### CODE REVIEW

**Review by mwang1026 — COMMENTED** [review]
What's written lgtm. I think one thing we might consider adding is mention of the client side encryption that we now offer (at the time the docs issue was written we didn't have that feature)

Something like `CRDB also provides client-side encryption of backup data via (link to the backup encryption docs)`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10531#-:-M_RMiZ53suXnoB1ZSu9:bjkbuin)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by kathancox** [comment]
@mwang1026 good point, have added this to the note.

**Review by jseldess — APPROVED** [review]
:lgtm: 

Separate issue, but @kathancox, we should probably look at conventions around how many callouts to include in a section, on a page, etc. Perhaps there are patterns we can use that would lead to less callout overload. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10531#-:-M_SUDh58p47_1LKxy_Q:b-6l8mog)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by kathancox** [comment]
Thanks Jesse. Yes, I would like to figure out some best practices when it comes to that—notes start becoming a bit meaningless at a certain number.

**Pull request merged**
