### PR TITLE
adding async install to nodejs app

### PR DESCRIPTION
**Pull request by sploiselle**
From nwHacks feedback; add steps to install `async` to get app working.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/1212)

### CODE REVIEW

**Comment by sploiselle** [comment]
@maxlang Can I get you to take a peek at this real quickly?

**Comment by maxlang** [comment]
LGTM to me too.

You might also want to walk through the steps and make sure the code runs. The second callback in `async.waterfall` was failing because it was missing an argument.

**Comment by jseldess** [comment]
@sploiselle, does this PR need another iteration, or is it good to merge?

**Comment by sploiselle** [comment]
@jseldess PR needs another iteration/more attention from me, re: Max's comment

>You might also want to walk through the steps and make sure the code runs. The second callback in async.waterfall was failing because it was missing an argument.

I looked at it for a few minutes, didn't grok it, so need to do some more digesting. If we want to clean up, this is fine to merge, though, because we aren't introducing any new problems.

**Comment by benesch** [comment]
I think this is what Max meant!

```diff
--- basic.js	2017-04-04 10:12:21.000000000 -0400
+++ basic-sample.js	2017-04-04 10:11:07.000000000 -0400
@@ -27,7 +27,7 @@
       // Create the "accounts" table.
       client.query("CREATE TABLE IF NOT EXISTS accounts (id INT PRIMARY KEY, balance INT);", next);
     },
-    function (next) {
+    function (results, next) {
       // Insert two rows into the "accounts" table.
       client.query("INSERT INTO accounts (id, balance) VALUES (1, 1000), (2, 250);", next);
     },
```

**Comment by sploiselle** [comment]
Derp. Thank you, @benesch!

**Pull request merged**
