### PR TITLE
CockroachCloud Release Notes April 5 2021

### PR DESCRIPTION
**Pull request by gemma-shay**
Closes https://cockroachlabs.atlassian.net/browse/CC-3655

### CODE REVIEW

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[releases/cockroachcloud-04052021.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDO7mE-gZGFF4cTg0H:-MXDO7mE-gZGFF4cTg0I:b-gtfjd2) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L17)):*
> ```Markdown
> New CockroachCloud clusters will now run CockroachDB [v20.2.7](v20.2.7.html).
> 
> ### Console changes
> ```

As mentioned in the [tracking issue](https://cockroachlabs.atlassian.net/browse/CC-3655), we need to include a release note for the new Status page (and link to it)
___
*[releases/cockroachcloud-04052021.md, line 18 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDMSLj2BjOJZ8xZ06e:-MXDMSLkEAr87o6pDjz9:b-ya2vbe) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L18)):*
> ```Markdown
> 
> ### Console changes
> ```

General nit: It looks like the page is rendering correctly, but I would remove the extra line returns.
___
*[releases/cockroachcloud-04052021.md, line 19 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDMcJt9WhHosakZMZk:-MXDMcJt9WhHosakZMZl:bg4fzs0) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L19)):*
> ```Markdown
> ### Console changes
> 
> - The login form no longer focuses on the email
> ```

Link `login form` to the Login page
___
*[releases/cockroachcloud-04052021.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDN7j37WrGAo5YYghI:-MXDN7j43pnczZ_0ivuq:b-esx34u) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L23)):*
> ```Markdown
>   authentication methods are available.
> - Extraneous information is no longer displayed in the
>   error for failed GCP peering attempts.
> ```

Link `GCP peering` to VPC peering docs
___
*[releases/cockroachcloud-04052021.md, line 27 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDNOy15mMaLGVzwIv7:-MXDNOy15mMaLGVzwIv8:buqdact) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L27)):*
> ```Markdown
> ### Bug fixes
> 
> - The region shown in the GUI for free-tier
> ```

nit: `GUI` > CockroachCloud Console

("GUI" is jargon-y)
___
*[releases/cockroachcloud-04052021.md, line 30 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDNcfI7nnnBYWXNT1n:-MXDNcfI7nnnBYWXNT1o:b9pevr6) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L30)):*
> ```Markdown
>   clusters is now correct. Previously, the GUI showed the wrong
>   region when creating an AWS free-tier cluster.
> - Fixed a bug where an error was thrown when
> ```

nit: `error was thrown` > `error occurred`

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lnhsingh)

___
*[releases/cockroachcloud-04052021.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDO7mE-gZGFF4cTg0H:-MXDpsAP89EYGWUOykSj:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L17)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

As mentioned in the [tracking issue](https://cockroachlabs.atlassian.net/browse/CC-3655), we need to include a release note for the new Status page (and link to it)
</blockquote></details>

Done.
___
*[releases/cockroachcloud-04052021.md, line 18 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDMSLj2BjOJZ8xZ06e:-MXDqQAe1pXhObOH4qKi:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L18)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

General nit: It looks like the page is rendering correctly, but I would remove the extra line returns.
</blockquote></details>

Done.
___
*[releases/cockroachcloud-04052021.md, line 19 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDMcJt9WhHosakZMZk:-MXDqcVV9HDDOip8b5DV:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L19)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Link `login form` to the Login page
</blockquote></details>

Done.
___
*[releases/cockroachcloud-04052021.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDN7j37WrGAo5YYghI:-MXDquui8MOTm1YEnrsK:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L23)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Link `GCP peering` to VPC peering docs
</blockquote></details>

Done.

**Comment by gemma-shay** [comment]
CC: @emily-horing and @jramos-crl for optional review 🙂

**Review by lnhsingh — APPROVED** [review]
:lgtm:

**Comment by lnhsingh** [comment]
Also cc: @iibuaka for review of the Status Page bullet point

**Review by iibuaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kannanlakshmi and @lnhsingh)

___
*[releases/cockroachcloud-04052021.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDO7mE-gZGFF4cTg0H:-MXEJk8H5mdsw5nIwvNq:bechk5u) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L17)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

could we change the language for the status page from "uptime status" to "service status and incident communication"?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kannanlakshmi and @lnhsingh)

___
*[releases/cockroachcloud-04052021.md, line 17 at r3](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXDO7mE-gZGFF4cTg0H:-MXY6WG43loZgzyr5pbq:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/7724bba86539fb843ac5cc6537f89e21acbb2760/releases/cockroachcloud-04052021.md#L17)):*
<details><summary><i>Previously, iibuaka wrote…</i></summary><blockquote>

could we change the language for the status page from "uptime status" to "service status and incident communication"?
</blockquote></details>

Done.

**Review by kannanlakshmi — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lnhsingh)

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gemma-shay, @kannanlakshmi, and @lnhsingh)

___
*[releases/cockroachcloud-04052021.md, line 21 at r6](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXYD_Vi9iYd7lb32VZW:-MXYD_Vj7h5z8b8XyqJX:b-fqx2cq) ([raw file](https://github.com/cockroachdb/docs/blob/b6bf0adeace0200b061fb47b7049d7d4a915ff34/releases/cockroachcloud-04052021.md#L21)):*
> ```Markdown
> - The [login form](https://cockroachlabs.cloud/login) no longer focuses on the email field on page load. This change makes the form more flexible once other authentication methods are available.
> - Extraneous information is no longer displayed in the error for failed [GCP peering](../cockroachcloud/network-authorization.html#vpc-peering) attempts.
> - Added a resource panel to the [CockroachCloud Console](https://cockroachlabs.cloud), which can be accessed by clicking the **?** icon in the top right corner of the Console. Included in the resource panel are links to documentation; links to the CockroachDB Slack community, support portal, and feedback form; and links to additional learning resources, like Cockroach University. 
> ```

@emily-horing - can you review this note and lmk if you want to change / add anything?

**Review by emily-horing — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kannanlakshmi and @lnhsingh)

___
*[releases/cockroachcloud-04052021.md, line 21 at r6](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXYD_Vi9iYd7lb32VZW:-MXYSGwnDqbtaxDvU5F0:b7d4yhp) ([raw file](https://github.com/cockroachdb/docs/blob/b6bf0adeace0200b061fb47b7049d7d4a915ff34/releases/cockroachcloud-04052021.md#L21)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

@emily-horing - can you review this note and lmk if you want to change / add anything?
</blockquote></details>

Nit: I'm not sure the semi colons make a lot of sense. Maybe just: "In the resource panel you can find links to relevant documentation, Cockroach University, the CockroachDB Slack community, support portal, and CockroachCloud feedback form."

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10221)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @emily-horing, @kannanlakshmi, and @lnhsingh)

___
*[releases/cockroachcloud-04052021.md, line 21 at r6](https://reviewable.io/reviews/cockroachdb/docs/10221#-MXYD_Vi9iYd7lb32VZW:-MXZ1gwT2hc6teBQ91yH:b-4iqrmi) ([raw file](https://github.com/cockroachdb/docs/blob/b6bf0adeace0200b061fb47b7049d7d4a915ff34/releases/cockroachcloud-04052021.md#L21)):*
<details><summary><i>Previously, emily-horing wrote…</i></summary><blockquote>

Nit: I'm not sure the semi colons make a lot of sense. Maybe just: "In the resource panel you can find links to relevant documentation, Cockroach University, the CockroachDB Slack community, support portal, and CockroachCloud feedback form."
</blockquote></details>

While grammatically correct, I agree that it's convoluted :) - Updated.

**Pull request merged**
