### PR TITLE
Update recommended TimeoutStopSec to 300 seconds

### PR DESCRIPTION
**Pull request by mikeCRL**
Fixes DOC-6376

### CODE REVIEW

**Review by mdlinville — APPROVED** [review]
LGTM. I pushed a commit into this branch to add a note about the updated recommendation in the 22.2 and 22.1 docs. My thinking is that admins doing new deployments might decide to update the `systemd` configuration on their existing clusters if they read the note. Of course feel free to remove that commit if you don't think it's helpful.

**Comment by shannonbradshaw** [comment]
Any reason we can't just merge this? I know Mike's out, but it doesn't make a lot of sense to wait IMO.

**Comment by shannonbradshaw** [comment]
Unless we're still waiting on field input.

**Comment by mdlinville** [comment]
I'll go ahead and merge. I was just waiting on Mike since I added some content on top of his.

**Pull request merged**
