### PR TITLE
Update spatial install/import/libs info

### LINKED ISSUE #8400: geo: rebrand geospatial to spatial with minor refactors
PR: https://github.com/cockroachdb/cockroach/pull/53721

From release notes:
> The `--geo-libs` flag introduced in v20.2 alpha versions is now renamed to `--spatial-libs`. [#53721][#53721] {% comment %}doc{% endcomment %}

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #8400, #8649.

Addresses #8743, #8780.

Summary of changes:

- Update 'Install CockroachDB Spatial' and 'Working with Spatial Data'
  to point to the latest (pre-GA) release.

- Update 'Working with Spatial Data' to use `IMPORT PGDUMP` to bring in
  the tornadoes data set (auxiliary script & `cockroach sql` no longer
  required).

- Add docs to `cockroach start` for the `--spatial-libs` flag, and link
  to them from 'Install CockroachDB Spatial'.

- Update an old set of release notes to remove the confusing use of the
  term "static" re: the spatial libraries, which are dynamically linked.

- Add some more cross-linkage between 'Working with Spatial Data',
  'Install CockroachDB Spatial', and the other recently added spatial
  pages.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rmloveland)

___
*[v20.2/install-cockroachdb-spatial.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLKs2YQ0Vs2_-IENKU1:-MLKs2YQ0Vs2_-IENKU2:bvtsmk4) ([raw file](https://github.com/cockroachdb/docs/blob/42711d281b5cca259ab0cd069a083ddfe9d3480e/v20.2/install-cockroachdb-spatial.md#L29)):*
> ```Markdown
> {% include copy-clipboard.html %}
> ~~~ shell
> wget https://binaries.cockroachdb.com/cockroach-v20.2.0-rc.4.darwin-10.9-amd64.tgz
> ```

hmm, i wonder if we should chance it and just remove `-rc.4` altogether.
i think we talked about this last time, but how do we prevent this from getting stale?
___
*[v20.2/install-cockroachdb-spatial.md, line 194 at r1](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLKsCjG6ASJ0Pqs7Fdf:-MLKsCjG6ASJ0Pqs7Fdg:b-yzy202) ([raw file](https://github.com/cockroachdb/docs/blob/42711d281b5cca259ab0cd069a083ddfe9d3480e/v20.2/install-cockroachdb-spatial.md#L194)):*
> ```Markdown
> 
> {{site.data.alerts.callout_info}}
> By default, CockroachDB looks for spatial libraries in `/usr/local/lib/cockroach`. You can change the location where CockroachDB looks for spatial libraries by passing the [`--spatial-libs` flag to `cockroach start`](cockroach-start.html#flags-spatial-libs).
> ```

NEW! It also looks in the same directory as the CRDB binary if it is not in there. So another way to deploy is to have

/folder
/folder/cockroach
/folder/cockroach/lib/libgeos.so
/folder/cockroach/lib/libgeos_c.so

I think this is preferred along some camps, but i have no strong opinion.

**Review by rmloveland — COMMENTED** [review]
TFTR OLIVER!!!

Updated to add the other libs location.  Sadly can't fix the hardcoded URLs right now.

PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8831#-:-MLNxs3e0MbL69hv-ME3:b-3ohnqq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[v20.2/install-cockroachdb-spatial.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLKs2YQ0Vs2_-IENKU1:-MLNtdHB87iXqRa6iMZ7:b45rkzs) ([raw file](https://github.com/cockroachdb/docs/blob/42711d281b5cca259ab0cd069a083ddfe9d3480e/v20.2/install-cockroachdb-spatial.md#L29)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, i wonder if we should chance it and just remove `-rc.4` altogether.
i think we talked about this last time, but how do we prevent this from getting stale?
</blockquote></details>

I'd love to, but I don't think we can have a broken link for 5 days or so until Tuesday, for this or the Docker links.

There is probably a technical solution whereby we add some templating logic to Jekyll, but right now it's not really there.

Unfortunately I will have to make another PR on Tuesday to remove `-rc.4` (but you will not need to review it!)
___
*[v20.2/install-cockroachdb-spatial.md, line 194 at r1](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLKsCjG6ASJ0Pqs7Fdf:-MLNx1jn2MpwLbcVhYKb:b-c7amob) ([raw file](https://github.com/cockroachdb/docs/blob/42711d281b5cca259ab0cd069a083ddfe9d3480e/v20.2/install-cockroachdb-spatial.md#L194)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

NEW! It also looks in the same directory as the CRDB binary if it is not in there. So another way to deploy is to have

/folder
/folder/cockroach
/folder/cockroach/lib/libgeos.so
/folder/cockroach/lib/libgeos_c.so

I think this is preferred along some camps, but i have no strong opinion.
</blockquote></details>

Ah yes I forgot about that!

Updated to add that info here and in the docs for the `--spatial-libs` flag on `cockroach start`

**Review by ericharmeling — APPROVED** [review]
Just a couple nits/suggestions to take or leave.

LGTM!

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8831#-:-MLO8qlGC1tmvOzwpvEe:b-6exo8v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rmloveland)

___
*[v20.2/cockroach-start.md, line 68 at r2](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLO6NYlDFrUhr8PDd23:-MLO6NYlDFrUhr8PDd24:butwiil) ([raw file](https://github.com/cockroachdb/docs/blob/8c1df0cc01f1b17186057c4e54efb90324114fee/v20.2/cockroach-start.md#L68)):*
> ```
>   The location...
> ```

<span class="version-tag">New in v20.2:</span>  The location...
___
*[v20.2/cockroach-start.md, line 68 at r2](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLO6Xnz--FDELI0hcpY:-MLO6Xnz--FDELI0hcpZ:b-7tfcxi) ([raw file](https://github.com/cockroachdb/docs/blob/8c1df0cc01f1b17186057c4e54efb90324114fee/v20.2/cockroach-start.md#L68)):*
> ```
> spatial
> ```

Link to spatial features doc?

**Review by rmloveland — COMMENTED** [review]
Thanks Eric!  Made the updates you suggested!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/8831#-:-MLOhXMz0s94ASqpHcyw:b2ucf47)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @otan)

___
*[v20.2/cockroach-start.md, line 68 at r2](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLO6NYlDFrUhr8PDd23:-MLOhPQa32PAjOQvTl69:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/8c1df0cc01f1b17186057c4e54efb90324114fee/v20.2/cockroach-start.md#L68)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
>   The location...
> ```

<span class="version-tag">New in v20.2:</span>  The location...
</blockquote></details>

Done!
___
*[v20.2/cockroach-start.md, line 68 at r2](https://reviewable.io/reviews/cockroachdb/docs/8831#-MLO6Xnz--FDELI0hcpY:-MLOhQhD2PSlRf5YJaQw:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/8c1df0cc01f1b17186057c4e54efb90324114fee/v20.2/cockroach-start.md#L68)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> ```
> spatial
> ```

Link to spatial features doc?
</blockquote></details>

Done!

**Pull request merged**
