### PR TITLE
Ensure that LTS patch releases appear in supported table for release …

### PR DESCRIPTION
**Pull request by shannonbradshaw**
…support policy page

### CODE REVIEW

**Comment by ebembi-crdb** [comment]
@shannonbradshaw there's no 24.2, is that intentional?
Also is there any source of truth for this for me to verify
Screenshot 2024-12-04 at 2 00 21 AM

**Comment by shannonbradshaw** [comment]
@ebembi-crdb thanks for catching that. I pushed a fix. 

Unfortunately, the docs is the source of truth for the most part.

**Comment by ebembi-crdb** [comment]
> @ebembi-crdb thanks for catching that. I pushed a fix.
> 
> Unfortunately, the docs is the source of truth for the most part.

Catch-22   - _ -

**Review by ebembi-crdb — APPROVED** [review]
LGTM!

**Pull request merged**
