### PR TITLE
Modified database restore example

### LINKED ISSUE #2067: sqlccl: support RESTORE DATABASE
PR: https://github.com/cockroachdb/cockroach/pull/19176

From @dt:
> previously you had to recreate the database, then restore the tables
> now you can restore the whole thing

Once we have 1.2 docs, we'll need to update `restore.md`.

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Closes #2067

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @Amruta-Ranada. We still need to update the sql diagram to show the `DATABASE` keyword, and I have one other comment/question.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[v2.0/restore.md, line 184 at r1](https://reviewable.io/reviews/cockroachdb/docs/3020#-LAv5q5-EK9WX-VwsNq3:-LAv5q50Dq_HU3n0iLyf:b-2w7q6t) ([raw file](https://github.com/cockroachdb/docs/blob/6bf4c2905388b6a0dff618e2b3fd27f97a06fcbe/v2.0/restore.md#L184)):*
> ```Markdown
> 
> ~~~ sql
> > RESTORE bank.* FROM 'gs://acme-co-backup/database-bank-2017-03-27-weekly' \
> ```

Should we use `RESTORE DATABASE` here as well, since it's restoring an entire database? Or should we rather change the example to restore a specific table here? @dt?

---

*[v2.1/restore.md, line 184 at r1](https://reviewable.io/reviews/cockroachdb/docs/3020#-LAv64aQ50DGyW-xywNs:-LAv64aQ50DGyW-xywNt:b2nreh6) ([raw file](https://github.com/cockroachdb/docs/blob/6bf4c2905388b6a0dff618e2b3fd27f97a06fcbe/v2.1/restore.md#L184)):*
> ```Markdown
> 
> ~~~ sql
> > RESTORE bank.* FROM 'gs://acme-co-backup/database-bank-2017-03-27-weekly' \
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3020#-:-LAv66z-6JKIdW2hOLWK:beq5zd5)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[v2.0/restore.md, line 184 at r1](https://reviewable.io/reviews/cockroachdb/docs/3020#-LAv5q5-EK9WX-VwsNq3:-LAx6BC1ENKOf1SQtmxX:b-1s5re2) ([raw file](https://github.com/cockroachdb/docs/blob/6bf4c2905388b6a0dff618e2b3fd27f97a06fcbe/v2.0/restore.md#L184)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Should we use `RESTORE DATABASE` here as well, since it's restoring an entire database? Or should we rather change the example to restore a specific table here? @dt?
</blockquote></details>

I'd probably suggest individual table, but either work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3020)*

**Comment by jseldess** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[v2.0/restore.md, line 102 at r4](https://reviewable.io/reviews/cockroachdb/docs/3020#-LB0GYq78q1X-_MPQpts:-LB0GYq78q1X-_MPQptt:bv6xc24) ([raw file](https://github.com/cockroachdb/docs/blob/6ed87197e3a8621626fe388be509fc513914b1b0/v2.0/restore.md#L102)):*
> ```Markdown
> |-----------|-------------|
> | `table_pattern` | The table or [view](views.html) you want to restore. |
> | `name` | The name of the database you want to restore (i.e., restore all tables and views in the database). You can restore an entire database only if you had backed up the entire database. |
> ```

In the diagram, this is `database_name`, so please use that here instead of `name`. Also in the 2.1 version of the page.

---

*[v2.0/restore.md, line 105 at r4](https://reviewable.io/reviews/cockroachdb/docs/3020#-LB0GhxeAqflULPnfO9R:-LB0GhxeAqflULPnfO9S:bkd1r5m) ([raw file](https://github.com/cockroachdb/docs/blob/6ed87197e3a8621626fe388be509fc513914b1b0/v2.0/restore.md#L105)):*
> ```Markdown
> | `full_backup_location` | The URL where the full backup is stored. <br/><br/>For information about this URL structure, see [Backup File URLs](#backup-file-urls). |
> | `incremental_backup_location` | The URL where an incremental backup is stored.  <br/><br/>Lists of incremental backups must be sorted from oldest to newest. The newest incremental backup's timestamp must be within the table's garbage collection period.<br/><br/>For information about this URL structure, see [Backup File URLs](#backup-file-urls). <br/><br/>For more information about garbage collection, see [Configure Replication Zones](configure-replication-zones.html#replication-zone-format). |
> | `AS OF SYSTEM TIME timestamp` | <span class="version-tag">New in v2.0:</span> Restore data as it existed as of [`timestamp`](timestamp.html). You can restore point-in-time data only if you had taken full or incremental backup [with revision history](backup.html#backups-with-revision-history-new-in-v2-0). |
> ```

Your new diagram now shows `as_of_clause`. You have two options:
1. Regenerate the diagram one more time, inlining that element, replacing `a_expr_const` with `timestamp`, and unlinking `timestamp`. This will expose `AS OF SYSTEM TIME timestamp` in the diagram. In this case you won't need to change this row in the table. I prefer this option, so let me know if you want a hand with this.
2. Leave the diagram as-is but change this row to `as_of_clause`. This will mean mentioning the use of `AS OF SYSTEM TIME timestamp` in the description. 

Also, regardless, we should be linking to one of the point-in-time restore examples from here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3020)*

**Comment by Amruta-Ranade** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[v2.0/restore.md, line 105 at r4](https://reviewable.io/reviews/cockroachdb/docs/3020#-LB0GhxeAqflULPnfO9R:-LB0pz5U1kDHU2oQwjGO:bkvv8hz) ([raw file](https://github.com/cockroachdb/docs/blob/6ed87197e3a8621626fe388be509fc513914b1b0/v2.0/restore.md#L105)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Your new diagram now shows `as_of_clause`. You have two options:
1. Regenerate the diagram one more time, inlining that element, replacing `a_expr_const` with `timestamp`, and unlinking `timestamp`. This will expose `AS OF SYSTEM TIME timestamp` in the diagram. In this case you won't need to change this row in the table. I prefer this option, so let me know if you want a hand with this.
2. Leave the diagram as-is but change this row to `as_of_clause`. This will mean mentioning the use of `AS OF SYSTEM TIME timestamp` in the description. 

Also, regardless, we should be linking to one of the point-in-time restore examples from here.

</blockquote></details>

I need help with this :(

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/3020)*

**Pull request merged**
