### PR TITLE
DOC-1045, DOC-1046: Added information about NOT VISIBLE flag for columns

### PR DESCRIPTION
**Pull request by nickvigilante**
Fixes DOC-1045, DOC-1046

Missing SQL grammar diagram.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickvigilante and @postamar)

___
*[v21.1/constraints.md, line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/12729#-MzoyUYv8Z2L54Azx2bN:-MzoyUYv8Z2L54Azx2bO:bksvk5c) ([raw file](https://github.com/cockroachdb/docs/blob/6f3dbb95df1585c1c9285954f2d5f2c1c5bdee39/v21.1/constraints.md#L114)):*
> ```Markdown
> [`FOREIGN KEY`](foreign-key.html) | [Issue a transaction](transactions.html#syntax) that adds a new `FOREIGN KEY` constraint ([`ADD CONSTRAINT`](add-constraint.html)), and then remove the existing one ([`DROP CONSTRAINT`](drop-constraint.html)).
> [`NOT NULL`](not-null.html) | The `NOT NULL` constraint cannot be changed, only added and removed with [`ALTER COLUMN`](alter-column.html).
> [`NOT VISIBLE`](not-visible.html) | The `NOT VISIBLE` constraint cannot be changed, only added and removed with [`ALTER COLUMN`](alter-column.html).
> ```

what do you mean by `cannot be changed`? 
___
*[v21.1/not-visible.md, line 7 at r1](https://reviewable.io/reviews/cockroachdb/docs/12729#-MzoyZlsDYOp0xXwIbq0:-MzoyZlsDYOp0xXwIbq1:b-sfc0qr) ([raw file](https://github.com/cockroachdb/docs/blob/6f3dbb95df1585c1c9285954f2d5f2c1c5bdee39/v21.1/not-visible.md#L7)):*
> ```Markdown
> ---
> 
> The `NOT VISIBLE` [constraint](constraints.html) specifies a column won't be returned when using `*` in a [`SELECT` clause](select-clause.html). Its primary function is to control the display of keys in [geo-partitioned tables](partitioning.html) that could be exposed to client ORMs and other automated tools that inspect the SQL schema.
> ```

I don't know about `primary function` here. I think you can say that that was the motivation, but primary function is a little bit suspect given you can use this feature without using that feature. 
___
*[v21.1/not-visible.md, line 34 at r1](https://reviewable.io/reviews/cockroachdb/docs/12729#-Mzoyoso51nUa2cjXalh:-Mzoyoso51nUa2cjXali:b-3ru1) ([raw file](https://github.com/cockroachdb/docs/blob/6f3dbb95df1585c1c9285954f2d5f2c1c5bdee39/v21.1/not-visible.md#L34)):*
> ```Markdown
>   fae147ae-147a-4000-8000-000000000031   | rome | Richard Bullock   | 21194 Alexander Estate
>   (5 rows)
>   ~~~  
> ```

nit: extra spaces
___
*[v21.1/not-visible.md, line 51 at r1](https://reviewable.io/reviews/cockroachdb/docs/12729#-Mzoyqcz5mtnQDtiw8Kl:-Mzoyqcz5mtnQDtiw8Km:b-3ru1) ([raw file](https://github.com/cockroachdb/docs/blob/6f3dbb95df1585c1c9285954f2d5f2c1c5bdee39/v21.1/not-visible.md#L51)):*
> ```Markdown
>   fae147ae-147a-4000-8000-000000000031   | 2642076323
>   (5 rows)
>   ~~~  
> ```

nit: extra spaces

**Review by ajwerner — COMMENTED** [review]
Generally my problem here is that `NOT VISIBLE` is not a constraint. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12729#-:-N-PCENU4qXXfv9r8xve:b-wdkig2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nickvigilante, and @postamar)

___
*[`v21.1/constraints.md` line 114 at r1](https://reviewable.io/reviews/cockroachdb/docs/12729#-MzoyUYv8Z2L54Azx2bN:-N80AKiJEaYqjelSkNbi:beve8va) ([raw file](https://github.com/cockroachdb/docs/blob/6f3dbb95df1585c1c9285954f2d5f2c1c5bdee39/v21.1/constraints.md#L114)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

I copied that language from NOT NULL, but I've modified it to be more direct about how to set and unset it.
</blockquote></details>

`NOT VISIBLE` is not a constraint, it's a property. 
___
*[`v21.1/not-visible.md` line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80ARP80dIOk725FMqT:-N80ARP80dIOk725FMqU:brz7lot) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.1/not-visible.md#L7)):*
> ```Markdown
> ---
> 
> The `NOT VISIBLE` [constraint](constraints.html) specifies a column won't be returned when using `*` in a [`SELECT` clause](select-clause.html). With this constraint, you can control the display of keys in [geo-partitioned tables](partitioning.html) that could be exposed to client ORMs and other automated tools that inspect the SQL schema.
> ```

It's not a constraint
___
*[`v21.2/constraints.md` line 45 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80AX4dB2IT8d_Ig8cY:-N80AX4dB2IT8d_Ig8cZ:b2pl6pa) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/constraints.md#L45)):*
> ```Markdown
> 
>   {{site.data.alerts.callout_info}}
>   The `DEFAULT`, `NOT NULL`, and `NOT VISIBLE` constraints cannot be applied to multiple columns in a single statement. Separate changes to each column within a single statement per column.
> ```

not a constraint
___
*[`v21.2/constraints.md` line 115 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80AZeuCFCHmFoJJfsD:-N80AZeuCFCHmFoJJfsE:b2pl6pa) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/constraints.md#L115)):*
> ```Markdown
> [`FOREIGN KEY`](foreign-key.html) | [Issue a transaction](transactions.html#syntax) that adds a new `FOREIGN KEY` constraint ([`ADD CONSTRAINT`](add-constraint.html)), and then remove the existing one ([`DROP CONSTRAINT`](drop-constraint.html)).
> [`NOT NULL`](not-null.html) | The `NOT NULL` constraint can be added and removed with [`ALTER COLUMN`](alter-column.html).
> [`NOT VISIBLE`](not-visible.html) | The `NOT VISIBLE` constraint can be added and removed with [`ALTER COLUMN`](alter-column.html).
> ```

not a constraint
___
*[`v21.2/not-null.md` line 81 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80A_UC4ohjHz-M2qwe:-N80A_UC4ohjHz-M2qwf:b2pl6pa) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/not-null.md#L81)):*
> ```Markdown
> - [`PRIMARY KEY` constraint](primary-key.html)
> - [`UNIQUE` constraint](unique.html)
> - [`NOT VISIBLE` constraint](not-visible.html)
> ```

not a constraint
___
*[`v21.2/not-visible.md` line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80Ac-ZB_fZJtX3vhRe:-N80Ac-ZB_fZJtX3vhRf:b2pl6pa) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/not-visible.md#L7)):*
> ```Markdown
> ---
> 
> The `NOT VISIBLE` [constraint](constraints.html) specifies a column won't be returned when using `*` in a [`SELECT` clause](select-clause.html). With this constraint, you can control the display of keys in [geo-partitioned tables](partitioning.html) that could be exposed to client ORMs and other automated tools that inspect the SQL schema.
> ```

not a constraint

**Comment by ajwerner** [comment]
@stbof can you be involved in this one. We'll need to think about how we want to document the term `NOT VISIBLE`. The same term is being used in the context of indexes this release in https://cockroachlabs.atlassian.net/browse/CRDB-11155. That project is a bit of a cross-team project that primarily affects schema from the docs perspective but is on the queries team roadmap.

**Review by nickvigilante — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[`v21.1/not-visible.md` line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80ARP80dIOk725FMqT:-N80DouEBgqMEZMR--Cv:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.1/not-visible.md#L7)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's not a constraint
</blockquote></details>

Done.
___
*[`v21.2/constraints.md` line 45 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80AX4dB2IT8d_Ig8cY:-N80DpnFEQCV-FysVWdQ:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/constraints.md#L45)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

not a constraint
</blockquote></details>

Done.
___
*[`v21.2/constraints.md` line 115 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80AZeuCFCHmFoJJfsD:-N80DqQs1TYC4XmfwWlc:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/constraints.md#L115)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

not a constraint
</blockquote></details>

Done.
___
*[`v21.2/not-null.md` line 81 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80A_UC4ohjHz-M2qwe:-N80EUO3DFDdpy9dk_gu:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/not-null.md#L81)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

not a constraint
</blockquote></details>

Done.
___
*[`v21.2/not-visible.md` line 7 at r3](https://reviewable.io/reviews/cockroachdb/docs/12729#-N80Ac-ZB_fZJtX3vhRe:-N80E9Mg-opR0QO4dyKh:b-896fix) ([raw file](https://github.com/cockroachdb/docs/blob/c4923a7c72fe8aec17c93f668d727f7924c76255/v21.2/not-visible.md#L7)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

not a constraint
</blockquote></details>

Done.

**Comment by stbof** [comment]
@ajwerner Sure, I'll take it from here.

**Review by ajwerner — APPROVED** [review]
:lgtm: my remaining comments are really independent of the changes you're making here, and should be addressed separately. 

> Reviewed 2 of 9 files at r4, 8 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12729#-:-N92KeNSAIC6nxO_oY_k:bsk2ecf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @nickvigilante, and @postamar)

___
*[`v21.2/constraints.md` line 44 at r6](https://reviewable.io/reviews/cockroachdb/docs/12729#-N92K9uK3OXlCJHVSwbg:-N92K9uL-vdGpYdk_adR:bkugqlx) ([raw file](https://github.com/cockroachdb/docs/blob/6efe739865dbd0780fc56222df8d1cfa79f1ca8a/v21.2/constraints.md#L44)):*
> ```Markdown
> 
>   {{site.data.alerts.callout_info}}
>   The `DEFAULT` and `NOT NULL` constraints cannot be applied to multiple columns in a single statement. Separate changes to each column within a single statement per column.
> ```

Where is this coming from? I don't think it's true. I have no clue when it changed, but I think it was a very long time ago. 
```sql
create table foo (i int primary key, j int not null);
alter table foo alter column j drop not null, alter column j default 42;
show create table foo;
  table_name |              create_statement
-------------+----------------------------------------------
  foo        | CREATE TABLE public.foo (
             |     i INT8 NOT NULL,
             |     j INT8 NULL DEFAULT 42:::INT8,
             |     CONSTRAINT foo_pkey PRIMARY KEY (i ASC)
             | )
(1 row)
```
___
*[`v22.1/constraints.md` line 110 at r6](https://reviewable.io/reviews/cockroachdb/docs/12729#-N92KQzHD5-BDmJGKeq4:-N92KQzHD5-BDmJGKeq5:b-c0urfu) ([raw file](https://github.com/cockroachdb/docs/blob/6efe739865dbd0780fc56222df8d1cfa79f1ca8a/v22.1/constraints.md#L110)):*
> ```Markdown
> -----------------|-----------
> [`CHECK`](check.html) | [Issue a transaction](transactions.html#syntax) that adds a new `CHECK` constraint ([`ADD CONSTRAINT`](add-constraint.html)), and then remove the existing one ([`DROP CONSTRAINT`](drop-constraint.html)).
> [`DEFAULT` value](default-value.html) | The `DEFAULT` value can be changed through [`ALTER COLUMN`](alter-column.html).
> ```

While I'm here, I don't think it's right to call `DEFAULT` a constraint. We added in 21.2 `ON UPDATE` which is a lot like `DEFAULT`. I'd think they should be documented together. That can be left for a later time.

**Comment by stbof** [comment]
Replaced with https://github.com/cockroachdb/docs/pull/14871.

**Pull request closed without merging**
