### PR TITLE
Move CC into sidebar nav

### LINKED ISSUE #8058: Move CC tab into side nav
https://github.com/cockroachdb/docs/pull/7783

### PR DESCRIPTION
**Pull request by yingzhuchin**
Fixes #8058 

Move CockroachCloud docs from its own tab into a single sidenav bar shared with CockroachDB.

This branch currently works for local, PR, and Netlify production builds. 

The TeamCity build is failing because of many broken links as a result of moving CC. For example, look at v19.1/frequently-asked-questions.md, v20.1/frequently-asked-questions.md, and v20.2/frequently-asked-questions.md: The CockroachCloud landing page no longer exists and needs to be replaced. I think docs is best equipped to fix these links. @lnhsingh, @jseldess, could you please address or assign someone to address broken links? I'm happy to help answer any questions. Of course please also feel free to rework the sidenav hierarchy however you see fit. The current hierarchy changes are ported from Jesse's initial branch.

@anagio, FYI I'm not pushing this to our shared branch yet because of the broken links causing TeamCity build failures. I'll push when we have a green build.

### CODE REVIEW

**Comment by yingzhuchin** [comment]
There's still some clean-up to do, but I want to address those after we fix the broken links and have a green Teamcity build.

**Comment by lnhsingh** [comment]
@jseldess yes, i'm trying to make those changes now and update the links but i messed up in git.

**Comment by lnhsingh** [comment]
@jseldess @yingzhuchin - Updated most of the links. The remaining "broken links" are listed as `missing reference` and I'm not sure what that refers to because the links listed as such work when I click on them.

Separately, a couple of questions I had when doing this:

- Do we need to update redirects? Do we need to add new redirects for the old structure?
- Reminder to update any links from the UI to CC docs
- Should we rename some of the files (and then redirect?) now? Some of the file names start with `cockroachcloud` so the URL ends up being long (e.g., `docs/cockroachcloud/cockroachcloud-connect-to-your-cluster.html`) 
- Should we move images used in CC into a subdir of the new `cockroachcloud` dir?

**Comment by jseldess** [comment]
Thanks for chipping away at this, @lnhsingh!

> Do we need to update redirects? Do we need to add new redirects for the old structure?
- Yes, good point. For example, this page: `https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-frequently-asked-questions.html`. Now would be at `https://www.cockroachlabs.com/docs/cockroachcloud/cockroachcloud-frequently-asked-questions.html`. The `/stable` path is no longer there. So we will need redirects for all CC pages. 

> Reminder to update any links from the UI to CC docs
- Also a good point. If we put redirects in place, that will suffice technically, but we should certainly update the UI once the urls are clear. 

> Should we rename some of the files (and then redirect?) now? Some of the file names start with cockroachcloud so the 
URL ends up being long (e.g., docs/cockroachcloud/cockroachcloud-connect-to-your-cluster.html)
- I think this is a great idea. The `cockroachcloud-` filename prefix was only there to help us find the files in a broader list of crdb pages. Now that CC-only pages are in a `cockroachcloud` directory, we should rename the files. We should do this before putting redirects in place because we'll need the new names for that, of course.

> Should we move images used in CC into a subdir of the new cockroachcloud dir?
- I believe Jekyll requires images to be in the root-level `images` directory`. But I like the idea of creating a `cockroachcloud` subdirectory there and moving the CC images from v20.1 into that new directory.

**Comment by jseldess** [comment]
I'm not sure what's going on with those remaining broken links in the build log either, btw.

**Comment by lnhsingh** [comment]
@yingzhuchin @jseldess do you want me to rename the files / move the images on this PR?

**Comment by jseldess** [comment]
Yes, @lnhsingh, that'd be great. But we should think about how long this PR will remain open. Writers are continuing to work on docs and complicated conflicts are likely to arise. 

@yingzhuchin, are you hoping to merge this as soon as it's working? Or are we planning to wait until design changes are in place?

**Comment by yingzhuchin** [comment]
We have a green build! 🎊 

Since fixing links has proven to be such an undertaking, I would like to merge as soon as possible and avoid ongoing costs to maintain a branch.

**Comment by lnhsingh** [comment]
That makes sense to me! We can make iterative edits.

**Comment by yingzhuchin** [comment]
Thanks for fixing the links, @lnhsingh! Before I merge, I wanted to check in on the "4-deep" sidenav hierarchy conversation here: https://github.com/cockroachdb/docs/pull/7783#issuecomment-664518563

Do we want to merge as-is with the 4-deep hierarchy, or do we want to restore CockroachDB to its current 3-deep state for now? I defer to you and Jesse of course.

**Comment by lnhsingh** [comment]
I think merging as the 4-deep hierarchy (as is) is fine for now. However, we should make sure that the level 4 has the right styling. Is it displaying like this because it's on staging or because we don't have styling for it?

image

**Comment by jseldess** [comment]
We don't have the styling in place for a level that deep. Can we put that in place in this PR, @yingzhuchin? Would we need Peter to help with that?

**Comment by yingzhuchin** [comment]
I've added the necessary styling. I can merge as soon as I get a thumbs up!

**Comment by lnhsingh** [comment]
👍  from me

**Comment by jseldess** [comment]
This is great, but I think there are a few wrinkles we need to iron out before merging:

- When you switch the version to anything but v20.1.4 (stable), the sidenav reverts to CockroachDB sections and there's no way to access CockroachCloud docs:
    Screen Shot 2020-08-31 at 3 02 42 PM
    We need to add the CockroachCloud sections to all other versioned sidenav files. Ideally, we would create a separate `sidebar-cockroachcloud.json` that gets included in all of the version-specific .json files, like we do for `sidebar-release.json`.
- Have we added redirects for the CC docs, since they no longer include `/stable/` in their url?
- Have we updated the the TC and Netlify build processes to no longer generated CC docs as a distinct step?
- Do we need to do anything for Algolia indexing?

**Comment by yingzhuchin** [comment]
> This is great, but I think there are a few wrinkles we need to iron out before merging:
> 
> * When you switch the version to anything but v20.1.4 (stable), the sidenav reverts to CockroachDB sections and there's no way to access CockroachCloud docs:
>   Screen Shot 2020-08-31 at 3 02 42 PM
>   We need to add the CockroachCloud sections to all other versioned sidenav files. Ideally, we would create a separate `sidebar-cockroachcloud.json` that gets included in all of the version-specific .json files, like we do for `sidebar-release.json`.

I can work on this.

> * Have we added redirects for the CC docs, since they no longer include `/stable/` in their url?

No, I thought from comments above that we're doing this iteratively in separate PRs.

> * Have we updated the the TC and Netlify build processes to no longer generated CC docs as a distinct step?

Yes, done.

> * Do we need to do anything for Algolia indexing?

Yes, done.

**Comment by jseldess** [comment]
Thanks, @yingzhuchin.

> Have we added redirects for the CC docs, since they no longer include /stable/ in their url?
> No, I thought from comments above that we're doing this iteratively in separate PRs.

We can't wait on this because we're breaking links from the live CockroachCloud Console UI. We need to put redirects in place for the CC pages that were moved, which is pretty much all of them, I think? We can either do that server-side in the Netlify `_redirects` file, or client-side in the front-matter of each relevant file. Let me know if you need a hand with this!

**Comment by lnhsingh** [comment]
- Added the redirects in the pages' front matter
- Updated file names to remove the superfluous `cockroachcloud-` and updated links accordingly

**Comment by yingzhuchin** [comment]
Thanks, Lauren, for helping with the redirects! All comments have been addressed. @lnhsingh, @jseldess, this is now ready for final review.

**Comment by lnhsingh** [comment]
LGTM but would like sign off from @jseldess too!

**Comment by yingzhuchin** [comment]
Hi @Amruta-Ranade! @jseldess caught an as-yet unresolved side-effect of with moving CC docs into a separate folder:

```
Just round one more issue:
The markdown files that are shared between CC and CRDB docs (e.g., learn-cockroachdb-sql.md aren’t working properly. In those files, we had conditional logic to hide/show different content based on whether building CC or CRDB docs.
Now that we have all CC docs in the cockroachcloud directory, we probably need to create physical duplicates of these pages in that new directory with the correct content, rather than use show/hide logic.
```
```
I think we need to track down all files in v20.1 that were being built for both crdb and cc docs and think about what to do.
```

Is this something you could help us do?

Thank you!

**Comment by Amruta-Ranade** [comment]
@yingzhuchin Hey! Sorry, totally missed your comment and thought you just wanted me to take a look at the sidebar nav. Yes, I can help think through the duplicates issue.

**Comment by yingzhuchin** [comment]
> @yingzhuchin Hey! Sorry, totally missed your comment and thought you just wanted me to take a look at the sidebar nav. Yes, I can help think through the duplicates issue.

Thank you, @Amruta-Ranade! I took a look, and it's really only two files affected:

- learn-cockroachdb-sql.md
- build-a-python-app-with-cockroachdb-django.md

Do you have any objections to me duplicating those two files into the `cockroachcloud` folder, then removing the hide/show logic?

**Comment by Amruta-Ranade** [comment]
SGTM!

**Comment by yingzhuchin** [comment]
Thanks for all your help, @Amruta-Ranade, @lnhsingh, @jseldess! I will merge this in an hour, then monitor and test the live site for any potential issues.

**Pull request merged**
