### PR TITLE
Clarify VPC peering instructions

### PR DESCRIPTION
**Pull request by gemma-shay**
https://cockroachlabs.atlassian.net/browse/DOC-1947

On **Create a Cluster** page: mentioned that you have to actually establish the connection after enabling it during the cluster creation project, linked to instructions

On **Network Authorization** page: replaced the summarized instructions with links to detailed create & connection doc steps, added note about gke custom routes

On **Security Overview** page: linked to detailed instructions

### CODE REVIEW

**Review by abhinavg6 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12619)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay)

___
*[cockroachcloud/create-your-cluster.md, line 124 at r1](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrTLdIZCYgsoOKejZUx:-MrTLdIZCYgsoOKejZUy:bdf62wg) ([raw file](https://github.com/cockroachdb/docs/blob/4064dfac1237f40dba20004438287f7ec0a24278/cockroachcloud/create-your-cluster.md#L124)):*
> ```Markdown
> 1. Click **Next**.
>         
>         Your cluster will now have VPC Peering enabled. Once your cluster is created, see [Establish VPC Peering or AWS PrivateLink](connect-to-your-cluster.html#establish-vpc-peering-or-aws-privatelink) to finish setting up VPC Peering for your cluster.
> ```

The first statement `Your cluster will now have VPC Peering enabled` may be misconstrued as things being all set, even though we are asking in the next statement to go to the other page after cluster is created. I think we should just remove that first statement to avoid ambiguity.
___
*[cockroachcloud/network-authorization.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrTNOR7-1kZ15zn2fbd:-MrTNOR7-1kZ15zn2fbe:b1ktlfa) ([raw file](https://github.com/cockroachdb/docs/blob/4064dfac1237f40dba20004438287f7ec0a24278/cockroachcloud/network-authorization.md#L29)):*
> ```Markdown
> 
> 1. [Configure the IP range and size while creating the {{ site.data.products.dedicated }} cluster](#configure-the-ip-range-and-size-while-creating-your-cockroachdb-dedicated-cluster)
> 1. [Establish a VPC Peering connection after creating the cluster](#establish-a-vpc-peering-connection-after-creating-your-cockroachdb-dedicated-cluster)
> ```

Just thinking, do we need the detailed sub-sections below, when 1 is already captured at (create-your-cluster.html#step-7-enable-vpc-peering-optional) and 2 at (connect-to-your-cluster#establish-vpc-peering-or-aws-privatelink)? Should we just change the above links to direct to those pages, so it's all centralized? Else, we would always have to keep these in sync in case of any changes. 
Other way would be vice-versa, where we update those create-your-cluster and connect-to-your-cluster pages to direct to detailed sub-sections below. Whatever approach works best from a flow standpoint.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12619)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @gemma-shay, and @ianjevans)

___
*[cockroachcloud/network-authorization.md, line 29 at r1](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrTNOR7-1kZ15zn2fbd:-MrXytGH7a2J3NdhV5sa:b-becndn) ([raw file](https://github.com/cockroachdb/docs/blob/4064dfac1237f40dba20004438287f7ec0a24278/cockroachcloud/network-authorization.md#L29)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Just thinking, do we need the detailed sub-sections below, when 1 is already captured at (create-your-cluster.html#step-7-enable-vpc-peering-optional) and 2 at (connect-to-your-cluster#establish-vpc-peering-or-aws-privatelink)? Should we just change the above links to direct to those pages, so it's all centralized? Else, we would always have to keep these in sync in case of any changes. 
Other way would be vice-versa, where we update those create-your-cluster and connect-to-your-cluster pages to direct to detailed sub-sections below. Whatever approach works best from a flow standpoint.
</blockquote></details>

@ianjevans what do you think? the other option is still repeating the steps but using includes. whatever change is made should probably be made to the PrivateLink section as well.

**Review by abhinavg6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12619)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @ianjevans)

___
*[cockroachcloud/network-authorization.md, line 26 at r3](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrZIfmk1e8OoimpyAaE:-MrZIfmk1e8OoimpyAaF:bn8n9f) ([raw file](https://github.com/cockroachdb/docs/blob/e751e7f77f5b290c619187bcc4bc286df0eb0084/cockroachcloud/network-authorization.md#L26)):*
> ```Markdown
> If you select GCP as your cloud provider while [creating your {{ site.data.products.dedicated }} cluster](create-your-cluster.html), you can use [Google Cloud's VPC Network Peering](https://cloud.google.com/vpc/docs/vpc-peering) feature to connect your GCP application directly to your {{ site.data.products.dedicated }} cluster using internal IP addresses, thus limiting exposure to the public network and reducing network latency.
> 
> GKE users should note that [alias IP addresses](https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips) are enabled by default in order to create a VPC-native cluster. If you are connecting to a [routes-based GKE cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster) and [export custom routes](https://cloud.google.com/vpc/docs/vpc-peering#importing-exporting-routes), {{ site.data.products.db }} will import your custom routes by default.
> ```

Thanks for adding this. Though I feel the first statement about Alias-IPs and VPC-native clusters is not needed and may cause unnecessary confusion. I would change this to something like:

If your application is deployed to a [routes-based GKE cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster) and you [export custom routes](https://cloud.google.com/vpc/docs/vpc-peering#importing-exporting-routes) for the VPC peering connection, {{ site.data.products.db }} will import your custom routes by default.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12619)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @gemma-shay, and @ianjevans)

___
*[cockroachcloud/network-authorization.md, line 26 at r3](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrZIfmk1e8OoimpyAaE:-MrbsGRD7rwjyqx2_HTi:b-sx73ni) ([raw file](https://github.com/cockroachdb/docs/blob/e751e7f77f5b290c619187bcc4bc286df0eb0084/cockroachcloud/network-authorization.md#L26)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Thanks for adding this. Though I feel the first statement about Alias-IPs and VPC-native clusters is not needed and may cause unnecessary confusion. I would change this to something like:

If your application is deployed to a [routes-based GKE cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster) and you [export custom routes](https://cloud.google.com/vpc/docs/vpc-peering#importing-exporting-routes) for the VPC peering connection, {{ site.data.products.db }} will import your custom routes by default.
</blockquote></details>

For context, we had a customer request that first part a while ago (https://cockroachlabs.atlassian.net/browse/DOC-2024). Do you think it should be moved around or just deleted?

**Review by abhinavg6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12619)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gemma-shay and @ianjevans)

___
*[cockroachcloud/network-authorization.md, line 26 at r3](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrZIfmk1e8OoimpyAaE:-MrcOlUD0ZnFHP7BQTgb:b96ce89) ([raw file](https://github.com/cockroachdb/docs/blob/e751e7f77f5b290c619187bcc4bc286df0eb0084/cockroachcloud/network-authorization.md#L26)):*
<details><summary><i>Previously, gemma-shay (Gemma Shay) wrote…</i></summary><blockquote>

For context, we had a customer request that first part a while ago (https://cockroachlabs.atlassian.net/browse/DOC-2024). Do you think it should be moved around or just deleted?
</blockquote></details>

Hmm ok. Actually this particular fix addresses that concern too, but just to be thorough, we could probably amend that first statement and make the whole thing something like the following (please feel free to amend accordingly):

GKE users should note that we recommend deploying your application to a [VPC-native cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips) that uses alias IP addresses. If your application is instead deployed to a [routes-based GKE cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster), you may have to [export custom routes](https://cloud.google.com/vpc/docs/vpc-peering#importing-exporting-routes) for the VPC peering connection. {{ site.data.products.db }} will import your custom routes by default.

**Review by gemma-shay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/12619)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abhinavg6, @gemma-shay, and @ianjevans)

___
*[cockroachcloud/network-authorization.md, line 26 at r3](https://reviewable.io/reviews/cockroachdb/docs/12619#-MrZIfmk1e8OoimpyAaE:-Mrcs6ZU42T5m83iUdhI:b-qebpbf) ([raw file](https://github.com/cockroachdb/docs/blob/e751e7f77f5b290c619187bcc4bc286df0eb0084/cockroachcloud/network-authorization.md#L26)):*
<details><summary><i>Previously, abhinavg6 (Abhinav Garg) wrote…</i></summary><blockquote>

Hmm ok. Actually this particular fix addresses that concern too, but just to be thorough, we could probably amend that first statement and make the whole thing something like the following (please feel free to amend accordingly):

GKE users should note that we recommend deploying your application to a [VPC-native cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips) that uses alias IP addresses. If your application is instead deployed to a [routes-based GKE cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/routes-based-cluster), you may have to [export custom routes](https://cloud.google.com/vpc/docs/vpc-peering#importing-exporting-routes) for the VPC peering connection. {{ site.data.products.db }} will import your custom routes by default.
</blockquote></details>

Sounds good! Done

**Review by abhinavg6 — APPROVED** [review]

**Comment by gemma-shay** [comment]
@mikeCRL no rush, just bumping in case this got lost over the holidays

**Comment by abhinavg6** [comment]
@mikeCRL - It would be great to publish this change soon. There's a related minor change that was deployed as part of today's cloud release, and hence it would be good to share the updated docs with customers. Thanks.

**Review by mikeCRL — APPROVED** [review]

**Pull request merged**
