### PR TITLE
Add architecture docs on non-voting replicas

### LINKED ISSUE #9039: Document "non-voting replicas"
To make CockroachDB v21.1 even more multi-region-er, we are adding a feature called "non-voting replicas", a.k.a. "long-lived learner replicas".  These are used (AIUI) to achieve higher survivability and other Smurfy things.

Estimated scope of work:

- Document approximately what they are / how they work in the architecture docs
- Document any related other changes (such as new zone config fields)
- AIUI there will be new SQL commands/statements which will be associated with survivability etc., which will be used to control these from a higher level (will file other issues for those SQL statements)
- (update 20210223) be sure to document the performance implications of having lots of non-voting replicas

See also:

- https://github.com/cockroachdb/cockroach/issues/51943

### PR DESCRIPTION
**Pull request by rmloveland**
Fixes #9039.

Summary of changes:

- Update 'Replication Layer' docs with a new section, *Non-voting
  replicas*, which explains what these puppies are and what they are
  useful for, with links to various related things such as:

  - zone config var
  - high-level multi-region SQL features they enable
  - other Raft-y things

- Also added a brief note to the 'Raft' section that mentions non-voting
  replicas and links to their section below.

- Finally, added an anchor link to the zone config vars for easier
  reference

### CODE REVIEW

**Review by aayushshah15 — COMMENTED** [review]
:tada: 

BTW, @nvanbenschoten had expressed a desire to talk about the fact that non-voters, for the first time, introduce a dimension of user-configurable async replication to CockroachDB. @rmloveland do you think we should talk about something like that here? Feel free to punt it off to later, I just wanted to throw the idea out there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10036#-:-MWRLCj69SCf4ygXwFKn:bbfzbko)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rmloveland)

___
*[v21.1/architecture/replication-layer.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRK5Pv9uG3EvTfuZ33:-MWRK5Pv9uG3EvTfuZ34:bk0wa2a) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L38)):*
> ```Markdown
> Raft organizes all nodes that contain a replica of a range into a group--unsurprisingly called a Raft group. Each replica in a Raft group is either a "leader" or a "follower". The leader, which is elected by Raft and long-lived, coordinates all writes to the Raft group. It heartbeats followers periodically and keeps their logs replicated. In the absence of heartbeats, followers become candidates after randomized election timeouts and proceed to hold new leader elections.
> 
> <span class="version-tag">New in v21.1:</span> A third replica type is introduced, the "non-voting" or "learner" replica. These replicas do not participate in Raft elections, but are useful for unlocking use cases that require low-latency multi-region reads. For more information, see [Non-voting replicas](#non-voting-replicas).
> ```

I'd prefer to avoid `learner` here unless you have a strong preference.
___
*[v21.1/architecture/replication-layer.md, line 52 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRIsA84aZr_zjzE2-A:-MWRIsA84aZr_zjzE2-B:bfa36n7) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L52)):*
> ```Markdown
> #### Non-voting replicas
> 
> In versions prior to v21.1, CockroachDB only supported _voting_ replicas: that is, [ranges](overview.html#glossary) that participate as voters in the [Raft consensus protocol](#raft). However, the need for all replicas to participate in the consensus algorithm meant that increasing a range's [replication factor](../configure-replication-zones.html#num_replicas) came at a cost of increased write latency, since the additional replicas needed to participate in Raft [quorum](overview.html#architecture-overview-consensus).
> ```

`s/ranges/replicas`
___
*[v21.1/architecture/replication-layer.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRJ-_QE1xeUQSGQmLR:-MWRJ-_QE1xeUQSGQmLS:b-nluh69) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L58)):*
> ```Markdown
> Non-voting replicas follow the [Raft log](#raft-logs) (and are thus able to serve [follower reads](../follower-reads.html)), but do not participate in quorum. They have almost no impact on write latencies.
> 
> They are also sometimes referred to as _learner_ replicas, since they only "learn" what the voting replicas have decided, but do not participate in quorum (and thus do not incur the associated latency costs).
> ```

We could also mention `read-only replicas` here as that's the term Spanner uses: https://cloud.google.com/spanner/docs/replication#:~:text=Read%2Donly%20replicas%20only%20support,used%20in%20multi%2Dregion%20instances.
___
*[v21.1/architecture/replication-layer.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRJEke6a3AyBzmKGDG:-MWRJEke6a3AyBzmKGDH:b2zj5x2) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L60)):*
> ```Markdown
> They are also sometimes referred to as _learner_ replicas, since they only "learn" what the voting replicas have decided, but do not participate in quorum (and thus do not incur the associated latency costs).
> 
> Non-voting replicas are exposed in [zone configurations via the `num_voters` variable](../configure-replication-zones.html#num_voters), but most users should control non-voting replica placement with the high-level [multi-region SQL features](../multiregion-overview.html) instead.
> ```

I wonder if we should phrase this bit slightly differently. Something along the lines of:
```
Non-voting replicas can be configured via zone configurations through `num_voters` and `num_replicas` . 
When `num_voters` is configured to be less than `num_replicas`, the difference dictates the number of non-voting replicas. 
```

What do you think? I feel slightly unhappy about saying "... are exposed via `num_voters`".

**Review by rmloveland — COMMENTED** [review]
Thanks for the review Aayush!  I have made all the requested changes, I think - PTAL

I have punted the description of user-configurable async replication to a new issue #10151 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10036#-:-MWVDls66FpPh3JrtMU_:bxxz5ro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[v21.1/architecture/replication-layer.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRK5Pv9uG3EvTfuZ33:-MWVEGpK9qw35eF5xzD-:btg0iho) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L38)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I'd prefer to avoid `learner` here unless you have a strong preference.
</blockquote></details>

I do not! I have removed all reference to that term
___
*[v21.1/architecture/replication-layer.md, line 52 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRIsA84aZr_zjzE2-A:-MWVEbY12Kd2bML2R2EW:b-896fja) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L52)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

`s/ranges/replicas`
</blockquote></details>

Done!
___
*[v21.1/architecture/replication-layer.md, line 58 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRJ-_QE1xeUQSGQmLR:-MWVF7Zy6dRd59VgiTD9:b-zchsbb) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L58)):*
Nice, revised to

> They are also sometimes referred to as _read-only_ replicas, since they only serve reads, but do not participate in quorum (and thus do not incur the associated latency costs).

and added link to Spanner docs from "read-only replicas"
___
*[v21.1/architecture/replication-layer.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRJEke6a3AyBzmKGDG:-MWVFuJr5kn1E2bGPlnq:b-3kk8xm) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L60)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I wonder if we should phrase this bit slightly differently. Something along the lines of:
```
Non-voting replicas can be configured via zone configurations through `num_voters` and `num_replicas` . 
When `num_voters` is configured to be less than `num_replicas`, the difference dictates the number of non-voting replicas. 
```

What do you think? I feel slightly unhappy about saying "... are exposed via `num_voters`".
</blockquote></details>

Sounds good - replaced with your phrasing, but added the line "however, most users should control non-voting replica placement with the high-level SQL ... " at the end of the paragraph

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10036#-:-MWW0v990pmXckIg1i4d:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @rmloveland)

___
*[v21.1/architecture/replication-layer.md, line 60 at r1](https://reviewable.io/reviews/cockroachdb/docs/10036#-MWRJEke6a3AyBzmKGDG:-MWW0rBC3Jxho03PpTyO:b-zcjvte) ([raw file](https://github.com/cockroachdb/docs/blob/a2c5aafa9f37de1649a9a4b34a2a37a8493e65a9/v21.1/architecture/replication-layer.md#L60)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

Sounds good - replaced with your phrasing, but added the line "however, most users should control non-voting replica placement with the high-level SQL ... " at the end of the paragraph
</blockquote></details>

Thanks

**Review by lnhsingh — COMMENTED** [review]
Nice job! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/10036#-:-MWjz8Np7j4fHHPoWDde:b-nwh7ze)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @rmloveland)

**Comment by rmloveland** [comment]
Thanks Lauren!

**Pull request merged**
