### PR TITLE
Minor edits to build-a-test-app.

### PR DESCRIPTION
**Pull request by knz**
To merge after #146.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/docs/161)

### CODE REVIEW

**Comment by jseldess** [comment]
@knz, thanks for the updates. I just made a few additional changes:

- changed step 1 to focus on db creation and granting privileges, and step 2 to show table creation, as discussed with @mberhault.
- change c++ filename back to .c, since that's what's currently in the apps directory.

**Comment by jseldess** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/161#-:-KE-YkKiPjvqDQEG3M9j:1417088721)*

**Comment by jseldess** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/docs/161)*

**Comment by knz** [comment]
Jesse

You can't put c++ code in a file with extension .c and expect things to work. C is really a different language. Valid file extensions for c++ are .cc, .cpp .cxx .c++ and more rarely .C (with capital c).

**Comment by jseldess** [comment]
@knz, I should've explained better. The source file currently has the .c extension, so the include was failing and not letting Jekyll build the output. I should've just changed the source file extension. I'll open another PR to do that.

**Comment by jseldess** [comment]
Oh, I see that the source file did have the right extension. Sorry about this. Fixing now.

**Pull request merged**
