### PR TITLE
Added docs for changefeeds on tables with column families

### PR DESCRIPTION
**Pull request by kathancox**
Fixes [DOC-2830](https://cockroachlabs.atlassian.net/browse/DOC-2830) [DOC-2920](https://cockroachlabs.atlassian.net/browse/DOC-2920) [DOC-2945](https://cockroachlabs.atlassian.net/browse/DOC-2945) [DOC-3292](https://cockroachlabs.atlassian.net/browse/DOC-3292) 

Adds docs on tables with column families in changefeeds: 

- Description and usage on Use Changefeeds page
- End-to-end examples on Changefeed Examples page
- Example with `ALTER CHANGEFEED`

### CODE REVIEW

**Review by HonoreDB — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @kathancox)

___
*[_includes/v22.1/known-limitations/cdc.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZukgX8inm8Omxzveu:-N-ZukgX8inm8Omxzvev:bm2r811) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/_includes/v22.1/known-limitations/cdc.md#L9)):*
> ```Markdown
> - {{ site.data.products.enterprise }} changefeeds are currently disabled for [{{ site.data.products.serverless }} clusters](https://www.cockroachlabs.com/docs/cockroachcloud/quickstart). Core changefeeds are enabled. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/73429)    
> - Changefeeds will emit [`NULL` values](null-handling.html) for [`VIRTUAL` computed columns](computed-columns.html) and not the column's computed value. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/74688)
> - Using the [`split_column_families`](create-changefeed.html#split-column-families) and [`resolved`](create-changefeed.html#resolved-option) options on the same changefeed will cause an error. The workaround is to use the individual `FAMILY` keyword to specify column families when creating a changefeed. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/79452)
> ```

Will cause an error if using certain sinks: Kafka, pubsub, or experimental-sql.
___
*[v22.1/alter-changefeed.md, line 210 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZvM2uD4c7boDZZjzv:-N-ZvM2uD4c7boDZZjzw:b-ha7cgk) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/alter-changefeed.md#L210)):*
> ```Markdown
> ~~~
> 
> If you then want to remove the table with column families as a target from the changefeed, you must include the `FAMILY` keyword when using `DROP`:
> ```

I would put this a little differently. Not sure of the phrasing, but you have to remove it the same way you added or created it. If you added it as the whole table with `split_column_families`, you need to remove it without using the `FAMILY` keyword. If you added a table as `database.table FAMILY f1, database.table FAMILY f2`, then you need to drop it as `database.table FAMILY f1, database.table FAMILY f2`, or you can just drop one of the families if you still want the other, `database.table FAMILY f1`.
___
*[v22.1/changefeed-examples.md, line 418 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-Zx9OwAUy7K5zl7WwN:-N-Zx9OwAUy7K5zl7WwO:b-j45s0z) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/changefeed-examples.md#L418)):*
> ```Markdown
>     For more detail on emitted changefeed messages, see [responses](use-changefeeds.html#responses).
> 
> ### Create a changefeed on a table with column families
> ```

This looks great!
___
*[v22.1/changefeed-examples.md, line 761 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZxUfe5tr0YLd78MU8:-N-ZxUfe5tr0YLd78MU9:bi39h1b) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/changefeed-examples.md#L761)):*
> ```Markdown
>     ~~~
> 
>     Your changefeed will output the following:
> ```

To be safe, I think we should clarify near these examples that the ordering here is not guaranteed--you might not always see messages about the same row, or even the same change to the same row, next to each other.
___
*[v22.1/use-changefeeds.md, line 214 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZyLUdDfXY78AoZQKt:-N-ZyLUdDfXY78AoZQKu:bm5t0a8) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/use-changefeeds.md#L214)):*
> ```Markdown
> {{site.data.alerts.end}}
> 
> If a table has multiple column families, the `FAMILY` keyword will ensure the changefeed emits messages for **each** column family you define with `FAMILY` in the `CREATE CHANGEFEED` statement. If do not specify `FAMILY`, then the changefeed will emit messages for **all** the table's column families.
> ```

typo: If you do not. Also, up to you but I feel like we should have an example where someone is specifying multiple families on the same table? The right syntax is `TABLE tbl FAMILY f_1, TABLE tbl FAMILY f_2` but I'm worried people will assume it's `TABLE tbl FAMILY f1,f2` which is wrong because it would be parsed as `TABLE tbl FAMILY f1, TABLE f2`. 
___
*[v22.1/use-changefeeds.md, line 249 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-_-4wm5FaZfEeHc9tT:-N-_-4wm5FaZfEeHc9tU:bizvz7u) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/use-changefeeds.md#L249)):*
> ```Markdown
> It is important to consider the following when creating a changefeed on a table with multiple column families:
> 
> - If you create a table **without** column families, and then start a changefeed with the `split_column_families` option, it is not possible to add column families. A subsequent `ALTER TABLE` statement adding a column family to the table, will cause the changefeed to fail.
> ```

typo: extraneous comma

**Comment by kathancox** [comment]
Thanks Aaron that was super helpful, let me know if you think anything else could be adjusted!

**Review by HonoreDB — APPROVED** [review]
:lgtm:, just two minor comments.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13600#-:-N-crISfA0n_uQJmYbID:byb8e18)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @kathancox)

___
*[_includes/v22.1/known-limitations/cdc.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZukgX8inm8Omxzveu:-N-cpZBm-9s12B7J-m5i:brc29ka) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/_includes/v22.1/known-limitations/cdc.md#L9)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Will cause an error if using certain sinks: Kafka, pubsub, or experimental-sql.
</blockquote></details>

I never know the right way to make this distinction, sorry. By experimental-sql I mean the feature almost nobody uses where you do `INTO 'experimental-sql://dbconnectionstring`. Core changefeeds won't error.
___
*[v22.1/alter-changefeed.md, line 210 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZvM2uD4c7boDZZjzv:-N-cqRT-2GxcGmkPH1aO:bsu3ch9) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/alter-changefeed.md#L210)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I would put this a little differently. Not sure of the phrasing, but you have to remove it the same way you added or created it. If you added it as the whole table with `split_column_families`, you need to remove it without using the `FAMILY` keyword. If you added a table as `database.table FAMILY f1, database.table FAMILY f2`, then you need to drop it as `database.table FAMILY f1, database.table FAMILY f2`, or you can just drop one of the families if you still want the other, `database.table FAMILY f1`.
</blockquote></details>

Thanks, the below looks great. I think you meant to remove the above line in favor of the new text.

**Comment by kathancox** [comment]
> :lgtm:, just two minor comments.
> 
> > Reviewed 1 of 4 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13600#-:-N-crISfA0n_uQJmYbID:byb8e18)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB and @kathancox)
> 
> _[_includes/v22.1/known-limitations/cdc.md, line 9 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZukgX8inm8Omxzveu:-N-cpZBm-9s12B7J-m5i:brc29ka) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/_includes/v22.1/known-limitations/cdc.md#L9)):_
> 
> Previously, HonoreDB (Aaron Zinger) wrote…
> I never know the right way to make this distinction, sorry. By experimental-sql I mean the feature almost nobody uses where you do `INTO 'experimental-sql://dbconnectionstring`. Core changefeeds won't error.
> 
> _[v22.1/alter-changefeed.md, line 210 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-ZvM2uD4c7boDZZjzv:-N-cqRT-2GxcGmkPH1aO:bsu3ch9) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/alter-changefeed.md#L210)):_
> 
> Previously, HonoreDB (Aaron Zinger) wrote…
> Thanks, the below looks great. I think you meant to remove the above line in favor of the new text.

Ohhhhh, I honestly hadn't heard of `experimental-sql` before! I'll get these fixed up

**Review by andf-crl — APPROVED** [review]
LGTM with minor nits and optional rephrasings. Feel free to merge if you feel good about the changes, or send back for another review round if you prefer! Love the careful examples: incredibly helpful and well thought out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/docs/13600#-:-N-dqTtK-DDkoG55xgq4:bcdzoh4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andf-crl, @HonoreDB, and @kathancox)

___
*[_includes/v22.1/known-limitations/cdc.md, line 9 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-daYUb50QuufcoZyGT:-N-daYUb50QuufcoZyGU:b-pkmj3e) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/_includes/v22.1/known-limitations/cdc.md#L9)):*
> ```Markdown
> - {{ site.data.products.enterprise }} changefeeds are currently disabled for [{{ site.data.products.serverless }} clusters](https://www.cockroachlabs.com/docs/cockroachcloud/quickstart). Core changefeeds are enabled. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/73429)    
> - Changefeeds will emit [`NULL` values](null-handling.html) for [`VIRTUAL` computed columns](computed-columns.html) and not the column's computed value. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/74688)
> - Using the [`split_column_families`](create-changefeed.html#split-column-families) and [`resolved`](create-changefeed.html#resolved-option) options on the same changefeed will cause an error when using the following [sinks](changefeed-sinks.html): Kafka and Google Cloud Pub/Sub. The workaround is to use the individual `FAMILY` keyword to specify column families when creating a changefeed. [Tracking GitHub Issue](https://github.com/cockroachdb/cockroach/issues/79452) 
> ```

nit: this could be simplified to: "Instead, use the individual `FAMILY` keyword to ..."
___
*[v22.1/alter-changefeed.md, line 208 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dbpBt6quvCwllIABn:-N-db8_w4zWMb9jyQ2ZY:b-5z2a8y) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/alter-changefeed.md#L208)):*
> ```Markdown
> ~~~ sql
> ALTER CHANGEFEED {job_ID} ADD database.table SET split_column_families;
> ~~~
> ```

nit: since we have two alternative options for ADD, and we therefore have two alternative options for DROP which are specifically tied to which options we used initially for ADD, let's try to format these as distinct alternatives. Maybe:

"""
To add a table with [column families](column-families.html) when modifying a changefeed, perform one of the following:

- Use the `FAMILY` keyword to define specific families:

  < code sample >

- Or, set the [`split_column_families`](create-changefeed.html#split-column-families) option:

  < code sample >

To remove a table with column families as a target from the changefeed, you must `DROP` it in the same way that you added it originally as a changefeed target. For example:

- If you used `FAMILY` to add the table to the changefeed, use `FAMILY` when removing it:

  < code sample >

   When using the `FAMILY` keyword, it is possible to remove only one family at a time as needed. You will receive an error if you try to remove a table without specifying the `FAMILY` keyword.

- Or, if you originally added the whole table and its column families with `split_column_families`, you must remove it without using the `FAMILY` keyword:

  < code sample >

"""

Not sure yet how to effectively do unordered lists that have per-entry codeblocks in MD, but that would be my recommendation. Or skip! This is very much a nit.
___
*[v22.1/alter-changefeed.md, line 226 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dd97o2fcarr5x5WBD:-N-dd97p0B-L6n40w_NE:bpan0ib) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/alter-changefeed.md#L226)):*
> ```Markdown
> ~~~
> 
> For more description on using the `FAMILY` keyword and `split_column_families`, see [Tables with column families in changefeeds](use-changefeeds.html#changefeeds-on-tables-with-column-families).
> ```

nit: For more detail on

- or - 

for further discussion of
___
*[v22.1/changefeed-examples.md, line 521 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-df2039eVDnygu3ldP:-N-df2039eVDnygu3ldQ:b-himhkk) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-examples.md#L521)):*
> ```Markdown
>     ~~~
> 
> 1. Create another table:
> ```

nit: let's mention the special thing about this CREATE: it also has two column families defined. Maybe:

Create a second table that also defines column families:
___
*[v22.1/changefeed-examples.md, line 562 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dfygzEP0mstUDXXjg:-N-dfygzEP0mstUDXXjh:b-79ludv) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-examples.md#L562)):*
> ```Markdown
>     {{site.data.alerts.end}}
> 
>     Alternatively, create a changefeed using the `FAMILY` keyword across two tables:
> ```

Having both approaches side by side like this is extremely helpful -- nice work!
___
*[v22.1/changefeed-examples.md, line 568 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dg6qs56JfEwQcSRIt:-N-dg6qs56JfEwQcSRIu:btou65u) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-examples.md#L568)):*
> ```Markdown
>     CREATE CHANGEFEED FOR TABLE office_dogs FAMILY employee, TABLE office_plants FAMILY dog_friendly INTO 'webhook-https://localhost:3000?insecure_tls_skip_verify=true';
>     ~~~
> ```

nit: recommend a tiny sentence introducing the expected results similar to the one above:

You'll receive one message for each insert that affects the specified column families:
___
*[v22.1/changefeed-examples.md, line 588 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dj7uFD6CYTLt04mYf:-N-dj7uFD6CYTLt04mYg:bs1ibbv) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-examples.md#L588)):*
> ```Markdown
>     {{site.data.alerts.end}}
> 
> 1. To create a changefeed that emits messages for all column families in a table, use the `split_column_families` option:
> ```

Let's link split_column_families here:

create-changefeed.html#options

or direct to split_column_families if we have an anchor for it
___
*[v22.1/changefeed-examples.md, line 698 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-diiBS7jY-Uv1kCStQ:-N-diiBT2xdDNDFDOuko:betdcdn) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-examples.md#L698)):*
> ```Markdown
>     ~~~
> 
> 1. Create another table with a column family:
> ```

this table has two column families.
___
*[v22.1/changefeed-examples.md, line 767 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dj0qLCObKDv4Q1n-o:-N-dj0qMAMgNg7TzEJbx:b-3o1ja8) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-examples.md#L767)):*
> ```Markdown
>     {{site.data.alerts.end}}
> 
> 1. To create a changefeed that emits messages for all column families in a table, use the `split_column_families` option:
> ```

Let's link split_column_families here:

changefeed-for.html#options

or direct to split_column_families if we have an anchor for it
___
*[v22.1/changefeed-for.md, line 59 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-djohi36-AJfwkcTQx:-N-djohi36-AJfwkcTQy:bis4h8i) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/changefeed-for.md#L59)):*
> ```Markdown
> `format` | `json` / `avro` | Format of the emitted record. Currently, support for [Avro is limited](use-changefeeds.html#avro-limitations). <br><br>Default: `format=json`.
> `confluent_schema_registry` | Schema Registry address | The [Schema Registry](https://docs.confluent.io/current/schema-registry/docs/index.html#sr) address is required to use `avro`.
> `split_column_families` | N/A | Target a table with multiple columns families. Emit messages for each column family in the target table. Each message will be labeled for `table.family`.
> ```

nit: should this be: "Each message will be labelled in format `table.family`."

Alternatively, this could be:

"""
Each message will include the label `"topic":"<table.family>"`.
"""
___
*[v22.1/use-changefeeds.md, line 249 at r1](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-_-4wm5FaZfEeHc9tT:-N-dptxU9QMkX2UH-SZD:b-k5ot8m) ([raw file](https://github.com/cockroachdb/docs/blob/74d5e6af06b74a210f33c31951fff65c8921cc0f/v22.1/use-changefeeds.md#L249)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

typo: extraneous comma
</blockquote></details>

Yes: table, will --> table will
___
*[v22.1/use-changefeeds.md, line 222 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dlCKLDHUYwE_JRxKg:-N-dlCKLDHUYwE_JRxKh:b4n74fx) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/use-changefeeds.md#L222)):*
> ```Markdown
> ~~~
> 
> <a name="col-family-response"></a>The response will follow a typical [changefeed message format](#messages), but with the family name appended to the table name: `table.family`:
> ```

nit: recommend "in the format" or similar. For example:

"""
... family name appended to the table name with a `.`, in the format `table.family`.
"""
___
*[v22.1/use-changefeeds.md, line 228 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dljVoDYlHKISIW0v_:-N-dljVoDYlHKISIW0va:b3aicze) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/use-changefeeds.md#L228)):*
> ```Markdown
> ~~~
> 
> For [cloud storage sinks](changefeed-sinks.html#cloud-storage-sink), the filename will include the family separated by a `+`. For example, `table+primary`.
> ```

nit: since we just demonstrated expected output format in the previous sentence, let's match the same formatting here too. Something like:

"""
... family name appended to the table name with a `+`, in the format `table+family`.
"""

question: is "filename" correct here? Previously we were talking about messages as the output format to which this pattern was written. Haven't yet practiced with sinks, so apologies if I am mistaken here.
___
*[v22.1/use-changefeeds.md, line 230 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dn3xtDK47vYSoBv2r:-N-dn3xtDK47vYSoBv2s:bond40) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/use-changefeeds.md#L230)):*
> ```Markdown
> For [cloud storage sinks](changefeed-sinks.html#cloud-storage-sink), the filename will include the family separated by a `+`. For example, `table+primary`.
> 
> [Avro](#avro) schema names will include the family name concatenated to the table name.
> ```

nit: since we just talked about `.` and `+` being used as concatenators, let's be explicit here which applies. Maybe:

"""
... family name appended to the table name with a `.`, in the format `table.family`.
"""
___
*[v22.1/use-changefeeds.md, line 232 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dnj_Y4brYqSlQiz4E:-N-dnj_Y4brYqSlQiz4F:baomeza) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/use-changefeeds.md#L232)):*
> ```Markdown
> [Avro](#avro) schema names will include the family name concatenated to the table name.
> 
> The primary key columns will appear in the `key` for all column families. It will also appear in the value **only** for the families that they are in. For example, if the table `office_dogs` has a column family `primary`, containing the primary key and a `STRING` column, and a `secondary` column family containing a different `STRING` column, then you'll receive two messages for an insert.
> ```

nit: does "it" refer to "primary key columns" as "they" does? If so it should be plural. We might even be able to combine like so:

""
The primary key columns will appear in the `key` for **all** column families,  and will also appear in the value for  **only** the families that they are a member of.
""



_Code quote:_
```Markdown
It will also appear in the value **only** for the families that they are in.
```
___
*[v22.1/use-changefeeds.md, line 249 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-doKh27sd79eat-esT:-N-doKh27sd79eat-esU:b-s0gqrp) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/use-changefeeds.md#L249)):*
> ```Markdown
> {"after":{"id":4,"name":"Toby"},"key":[4],"topic":"office_dogs.primary"}],"length":1}
> {"after":{"owner":"Ashley"},"key":[4],"topic":"office_dogs.secondary"}],"length":1}
> ~~~
> ```

nit: "you'll receive two messages for an insert." led me to expect those two lines as the next code block. Instead we first have the table creation step. While I love that this is here, so I can reproduce it on my end and learn it better, let's just briefly introduce what we're doing here:

"""
For example, consider the following table `office_dogs` which has a column family `primary`, containing the primary key and a `STRING` column, and a `secondary` column family containing a different `STRING` column:

<CREATE TABLE example>

The changefeed targeting this table (started with `split_column_families`) will emit two messages for each insert to the table:

<two changelog messages>
___
*[v22.1/use-changefeeds.md, line 258 at r3](https://reviewable.io/reviews/cockroachdb/docs/13600#-N-dqBF07oSrpMAT9yii:-N-dqBF07oSrpMAT9yij:bi31f10) ([raw file](https://github.com/cockroachdb/docs/blob/8cd0e651342cc2eb923677f5c3a51dabcbd97574/v22.1/use-changefeeds.md#L258)):*
> ```Markdown
> - When you do not specify column family names in the `CREATE` or `ALTER TABLE` statement, the family names will default to either of the following:
>     - `primary`: Since `primary` is a key word, you'll receive a syntax error if you run `CREATE CHANGEFEED FOR table FAMILY primary`. To avoid this syntax error, use double quotes: `CREATE CHANGEFEED FOR table FAMILY "primary"`. You'll receive output from the changefeed like: `table.primary`.
>     - `fam_<zero-indexed family id>_<delimited list of columns>`: For a table that does not include a name for the family: `FAMILY (id, name)`. You'll receive output from the changefeed containing: `table.fam_0_id_name`. This references the table, the family ID and the two columns that this column family includes.
> ```

nit: "For a table" is a sentence fragment, but it looks like it can be safely combined with the next sentence (guess!!). Perhaps:

"""
For a table that does not include a name for the family: `FAMILY (id, name)`, you'll receive output from the changefeed containing: `table.fam_0_id_name`.
"""

**Comment by kathancox** [comment]
TFTR Andrew! V helpful.

Yes, so cloud storage sinks... The messages are emitted as JSON files and dropped into the cloud storage sink you specify. The file names are date based in this kind of format `/[date]/[timestamp]-[uniquer]-[topic]-[schema-id]`. If you specify the `resolved` option, `RESOLVED` will be appended to the filename.

**Pull request merged**
