### PR TITLE
Update community-tooling.md

### PR DESCRIPTION
**Pull request by wzrdtales**
just wanted to add, we support cockroachdb as well. Including usually the cockroachdb specific features.

### CODE REVIEW

**Comment by jseldess** [comment]
Thanks, @wzrdtales!

@vy-ton, PTAL.

**Comment by ericharmeling** [comment]
@wzrdtales 

Thanks for adding this! Looks good to me.

Before we merge this, could you also make the same changes to the following files:

- `v20.2/community-tooling.md`
- `v21.2/community-tooling.md`

**Comment by ericharmeling** [comment]
@wzrdtales Additionally, CockroachDB is not listed among the supported databases at https://db-migrate.readthedocs.io/en/latest/. Could you add CockroachDB to that page, or, at the very least, add a note under PostgreSQL support?

**Comment by wzrdtales** [comment]
> @wzrdtales Additionally, CockroachDB is not listed among the supported databases at https://db-migrate.readthedocs.io/en/latest/. Could you add CockroachDB to that page, or, at the very least, add a note under PostgreSQL support?

sure, done

**Review by ericharmeling — APPROVED** [review]
Great. Thank you!

**Comment by wzrdtales** [comment]
replaced previous commit 20.2 didn't had the section yet and it landed in the wrong one

**Comment by ericharmeling** [comment]
> replaced previous commit 20.2 didn't had the section yet and it landed in the wrong one

Thanks for doing that as well. Cheers!

**Pull request merged**
